cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, cfgov/templates/registration/logged_out.html, cfgov/templates/wagtailadmin/login.html, cfgov/templates/welcome.html, cfgov/v1/auth_forms.py, cfgov/v1/util/util.py, cfgov/v1/views.py
This gives us a single page for all logins, removing the need for us (and users!) to keep /admin/login and /django-admin/login straight.
Also:
- provides an intermediary view that sniffs the permissions of the page
you are trying to reach. If you don't have appropriate permissions, then you can
navigate to a page you DO have permissions for (Django admin or wagtail)
- If you log in without requesting a specific page, and you have access to
both Django admin and wagtail, you're presented with a page providing both options
- If you log in without requesting a specific page, and you have access to
ONLY ONE of django admin or wagtail, you're redirected to the one you can
access.
- Create a user with ONLY wagtail access (active, NOT staff, and a member of moderator and/or editor group)
- log …
=> Login Page Reduction Act

CHANGELOG.md, cfgov/jinja2/v1/test-fixture/index.html, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/js/modules/util/breakpoint-state.js, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/organisms/MegaMenu.js, config/webpack-config.js, gulp/tasks/scripts.js
PR #2160 only addressed non-responsive styles, leading to incorrect behavior at smaller screens on the non-responsive test fixture. Added a gulp task to create a nonresponsive script that rewrites `isInDesktop` to always return true.
- Added gulp task for nonresponsive scripts
- Added webpack config for nonresponsive gulp task
- Moved `isInDesktop` to breakpoint state file to resolve TODOs
- `gulp scripts:ondemand && gulp styles:ondemand`
- navigate to `http://localhost:8000/test-fixture/?atomic=header&suffix=nonresponsive` 
- We should wait for #2164 & #2166 to be merged to make sure this PR doesn't break the existing functionality
=> Creates nonresponsive header script for non-v1 sections of the site

CHANGELOG.md, cfgov/jinja2/v1/index.html
The individual posts in "Latest Updates" were missing spacing between each other. The `m-related-posts_list-container` class had been removed at some point in the past, it is now restored fixing the spacing.
- Added `m-related-posts_list-container` where necessary.
- `gulp build` and check the homepage matches the screenshot
- @schaferjh 
- @schaferjh 
- @sarahsimpson09
=> Fixed layout bug in Latest Updates on Home Page

CHANGELOG.md, cfgov/unprocessed/css/molecules/home-hero.less
The home hero lost it's spacing below the content after the global last paragraph margin change. Updated the content wrapper to add the necessary margin back in.
- Added margin to hero content wrapper.
- `gulp build` and navigate to the home page. The margin should match the image below at small device sizes.
- @schaferjh
=> Added correct spacing to Home Hero Content

cfgov/unprocessed/css/misc.less, test/browser_tests/spec_suites/organisms/header.js
Adding some missing tests to the header to test switching between the search and mega menu.
- `gulp test:acceptance --sauce=false --windowSize=400,610 --specs=header.js` 
These tests look at switching between the mega menu and search.
=> Adding mobile tests for the header

test/unit_tests/modules/simple-table-row-links-spec.js
Adding unit tests for simple-table-row
- Adding unit tests for simple-table-row
-  Run ` gulp test:unit:scripts`.
=> Adding unit tests for simple-table-row

cfgov/jinja2/v1/_includes/molecules/contact-address.html, cfgov/jinja2/v1/_includes/molecules/contact-email.html, cfgov/jinja2/v1/_includes/molecules/contact-phone.html, cfgov/jinja2/v1/_includes/molecules/related-posts.html, cfgov/jinja2/v1/_includes/organisms/sidebar-contact-info.html, cfgov/jinja2/v1/_includes/templates/streamfield-sidefoot.html, cfgov/unprocessed/css/molecules/related-posts.less, cfgov/unprocessed/css/organisms/sidebar-contact-info.less
There were multiple spacing issues in the pre-footer that had gone unnoticed until the recent changes to the last paragraph spacing. Updated the contact info to remove extra left/right spacing and added spacing between components where necessary.
- Added generic contact molecule to fix spacing when multiple exist together
- Fixed missing space between `block` and `block__flush-top` modifier
- Updated grid
- Removed grid wrappers where they weren't necessary
- `gulp build` and check http://localhost:8000/accessibility/ and http://localhost:8000/about-us/advisory-groups/ and compare them to Jess's screenshots at https://github.com/cfpb/cfgov-refresh/pull/2186#issuecomment-225941037
- @schaferjh
=> Fixed spacing issues in the pre-footer

CHANGELOG.md, cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/events/_event-detail.html, cfgov/jinja2/v1/events/_macros.html, cfgov/sheerlike/templates.py, cfgov/sheerlike/test_templates.py, cfgov/v1/atomic_elements/organisms.py, cfgov/v1/migrations/0090_auto_20160609_1603.py, cfgov/v1/models/learn_page.py
Timezones were saved in UTC but being treated in code as eastern. Now, they are saved as UTC with their hour difference applied as is best practice. For example, before this change 4:00am was saved as 04:00:00 UTC and now 12:00am is saved as 08:00:00 UTC and Django will apply the eastern timezone when appropriate. [See this for more details on the settings.](https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-TIME_ZONE)
This also changes the block types that are used in EventPage AgendaItemBlock's and ItemIntroduction blocks. Before, they were unnecessarily using DateTimeBlock's and now they use their appropriate block types.
- A new migration that changes the block types and migrates the datetimes on the pages to the appropriate values.
- The timezone is now …
=> Datetimes are now saved in UTC with the eastern timezone

cfgov/templates/wagtailadmin/shared/page_status_tag.html, cfgov/v1/migrations/0091_cfgovpage_has_unshared_changes.py, cfgov/v1/models/base.py, cfgov/v1/templatetags/share.py, cfgov/v1/tests/test_filterable_list.py, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py
This is going to be a pain to review. Sorry in advance. Page statuses haven't been as complex as they've needed to be with our introduction of the `SHARED` status. This fixes that by adding new statuses so that content editors can easily tell what the state of the page is. The page states are as follows:
1. The page is just started, it is neither SHARED nor LIVE. — DRAFT
2. The page moves from draft to share on content but is not LIVE — SHARED
3. The page is SHARED and has unshared updates — SHARED + DRAFT
4. The page is published to www (and shared on content) -- LIVE
5. The page is LIVE and has unpublished updates -- LIVE + DRAFT
6. The page is LIVE and has shared updates -- LIVE + SHARED
7. The page is LIVE and has shared updates and has unpublished updates - LIVE + (SHARED+DRAFT)
- …
=> Make page statuses more descriptive

cfgov/v1/migrations/0090_cfgovpage_has_unshared_changes.py, cfgov/v1/migrations/0091_auto_20160609_1603.py
According to [this issue](https://code.djangoproject.com/ticket/24573) there was a bug in the django migrations module that cause it to look for fields that are not available when retrieving a model through `apps`. Apparently, this was only fixed in the case described in the issue and does not fix our specific situation. I'm opening up an issue soon because this keeps cropping up when we do data migrations. 
This fixes the migrations so that the field is available on model retrieval.
@rosskarchner
=> Switch migration order because of django migration bug

cfgov/v1/tests/test_password_policy.py
TestMinimumPasswordAge.test_too_soon assumed that new users were created with a password that can't be changed until 24 hours later. That assumption is no longer valid, so I've altered the test to make certain that the user is not allowed to change their password.
=> Fixing TestMinimumPasswordAge.test_too_soon

INSTALL.md
The current install instructions recommend using `brew install elasticsearch` to install ES, but this installs a version (2.2) which is later than what seems to be the required version (1.7). Specifically, trying to run `sheer_index` fails on ES 2.x. This PR modifies the install instructions to be more specific about what version to install.
-
-
- Update `INSTALL.md` to specify use of Elasticsearch 1.7 now that `brew install elasticsearch` defaults to ES 2.x.
- Try following install instructions after clean checkout. The command `python cfgov/manage.py sheer_index -r` in `README.md` will fail if you don't have the right ES version.
-
-
=> Update install instructions to specify Elasticsearch 1.7

.eslintrc, CHANGELOG.md, cfgov/unprocessed/js/modules/UStreamPlayer.js, cfgov/unprocessed/js/modules/VideoPlayer.js, cfgov/unprocessed/js/modules/behavior/FlyoutMenu.js, cfgov/unprocessed/js/modules/form-validation.js, cfgov/unprocessed/js/modules/util/atomic-helpers.js, cfgov/unprocessed/js/modules/util/tree-traversal.js, cfgov/unprocessed/js/modules/util/web-storage-proxy.js, cfgov/unprocessed/js/organisms/Expandable.js, gulp/tasks/scripts.js, npm-shrinkwrap.json, test/browser_tests/spec_suites/careers-application-process.js, test/browser_tests/spec_suites/organisms/header.js, test/browser_tests/spec_suites/the-bureau.js, test/unit_tests/modules/ClearableInput-spec.js, test/unit_tests/modules/FlyoutMenu-spec.js
- Updates ESLint to `2.13.1` from `2.7.0`
- Adds `init-declarations`, `max-lines`, `object-curly-newline`, `newline-before-return`, and `newline-per-chained-call` rules, but does not enforce them.
- Enforces `no-prototype-builtins`, `no-unsafe-finally`, `no-duplicate-imports`, `unicode-bom`, `no-useless-computed-key`, `no-useless-rename`, `rest-spread-spacing`, and `no-restricted-globals` rules.
- Warns on `no-useless-escape`, `keyword-spacing`, `max-statements-per-line`, `no-mixed-operators`, `object-property-newline`
- Adds options to `no-confusing-arrow`, `no-magic-numbers`, and `no-unused-vars`. Only `no-confusing-arrow` option has an effect and relaxes the rule.
- Minor code cleanup to fix linter warnings.
- `./setup.sh`
- …
=> Updates ESLint to `2.13.1` from `2.7.0`

test/unit_tests/modules/util/js-loader-spec.js
Adding Unit Test for Js Loader
- Adding Unit Test for Js Loader
- Run `gulp test:unit`.
- @jimmynotjim
- I've not added tests for `script.readyState`. I'm not sure how to test for those branches as it's not implemented by jsDom (https://github.com/tmpvar/jsdom/issues/1436 ). If anyone has ideals then please let me know.
-
=> Adding Unit Test for Js Loader

cfgov/cfgov/urls.py, cfgov/legacy/forms.py, cfgov/legacy/views.py, cfgov/v1/migrations/0057_auto_20160304_1651.py
This is a hotfix that should stop *some* of the bleeding with PDFReactor and our web servers.
We now reject zip+4 codes, because the backend API doesn't support them. PDFReactor doesn't seem to deal well with parsing our error pages.
This also fixes a bug where we were sending error responses with HTTP status 200 that may have been aggravating things.
=> Hotfix: stop trying to process invalid URL's with PDFReactor

CHANGELOG.md, cfgov/jinja2/v1/about-us/careers/index.html, cfgov/jobmanager/tests/test_views.py, cfgov/jobmanager/urls.py, cfgov/jobmanager/views.py, requirements/test.txt
Makes job listing ordering on [/careers/](http://www.consumerfinance.gov/about-us/careers/) consistent with the ordering on [/careers/current-openings/](http://www.consumerfinance.gov/about-us/careers/current-openings/) (ordered first by soonest to close and then alphabetically). Changes text on /careers/ from "Newest Openings" to "Current Openings".
- Converted the careers index view and the current openings view to Django class-based views.
- Modified index view to use an ordering of `('close_date', 'title')` to be consistent with the jobs listing page.
- Changed text on `jinja2/v1/about-us/careers/index.html` from "Newest Openings" to "Current Openings".
- Updated `CHANGELOG.md` to include this update.
- Added new unit tests for the above views. Created new `jobmanager/tests` module to …
=> Consistent ordering of current job openings

requirements/base.txt
- [Bug on BS4](https://bugs.launchpad.net/beautifulsoup/+bug/1603299)
- [Current Wagtail version susceptible](https://github.com/torchbox/wagtail/blob/v1.3/setup.py#L32)
- [Wagtail version upgrade still susceptible](https://github.com/torchbox/wagtail/blob/v1.5.2/setup.py#L31)
- [Wagtail commit to solve issue that's not released yet](https://github.com/torchbox/wagtail/blob/master/setup.py#L31)
- html5lib version _after_ wagtail in `requirements/base.txt`
- `pip install -r requirements/local.txt`
- `tox`
- @willbarton 
- CHANGELOG
=> Pin version of html5lib because of breaking change in latest release

cfgov/cfgov/urls.py, cfgov/core/tests/test_views.py, cfgov/sheerlike/loaders.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/tests/models/test_browse_filterable_page.py, cfgov/v1/tests/models/test_sublanding_filterable_page.py, cfgov/v1/tests/test_password_policy.py, cfgov/v1/util/filterable_list.py, gulp/tasks/test.js, tox.ini
Speedup Python unit tests by removing their dependence on the database. This speeds up the current Python unit tests from roughly two minutes to roughly two seconds:
```sh
$ time tox -e fast
...
Ran 129 tests in 0.506s
...
real    0m1.783s
user    0m1.381s
sys     0m0.313s
```
- This PR introduces an alternate tox environment named `fast` that runs without recreating the virtualenv each time, invoked using `tox -e fast`. It also invokes tests using `python -m unittest discover` instead of `./manage. py test`, removing any dependence on the Django database. The standard tox environment (that recreates the DB and uses it each time) is still run if you just invoke `tox`.
- There were several dozen tests that had some dependence on the database. Many of these were  using the built-in [test …
=> Speedup Python unit tests by removing DB dependence

cfgov/jinja2/v1/_includes/article.html, cfgov/jinja2/v1/_includes/macros/category-slug.html, cfgov/jinja2/v1/_includes/organisms/item-introduction.html, cfgov/unprocessed/css/organisms/item-introduction.less, cfgov/unprocessed/css/post.less, test/browser_tests/page_objects/page_blog-single.js
Update spacing between header elements in item introduction and use item introduction template for blog/newsroom header
- add 'and' between author names in item introduction byline
- add an else condition in category-slug class output
- update spacing between elements in item introduction 
- use item introduction for article header
- Navigate to a [blog post](http://localhost:8000/about-us/blog/older-americans-are-not-alone-in-the-fight-to-stop-financial-abuse/) and a [page with item introduction](http://localhost:8000/data-research/research-reports/2014-consumer-response-annual-report/). Check that:
- Header element spacing matches specs in bug report (issue 10)
- Multiple author names are joined by 'and'
- @contolini 
- @sebworks 
- Lead paragraph is output in item …
=> Update spacing in item introduction

cfgov/jinja2/v1/_includes/macros/filters.html, cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/index.html
Adding validation to the leadership calendar to force users to select at least one option.  The primary goal is to reduce the pdf download size.
- Remove class name the we no longer use and adds selection requirement.
- Visit `http://localhost:8000/about-us/the-bureau/leadership-calendar/` and click the `Download PDF` button. It should display an error notification.
- The `macros/filters` jinja macro should be removed as it's only being used on the Leadership Calendar page. It may require refactoring the `filterable-list-control` macro to be modular.
…ndar
=> Adding validation to require option selection on the Leadership calendar

cfgov/cal/views.py, cfgov/jinja2/v1/_includes/leadership-calendar-table.html, cfgov/jinja2/v1/_includes/macros/active-filters.html, cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/index.html, cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/print/index.html, cfgov/sheerlike/__init__.py
There is a bug in the [Leadership Calendar](http://www.consumerfinance.gov/about-us/the-bureau/leadership-calendar) where a day's events that split across multiple pages output out of order and/or missing. Also, events that have a start date within the hour threshold of being saved in UTC as the next day are showing up in UTC day's table instead of it's actual day's table. Additionally, there was a `pdb` statement left in there from the last PR that needed to be removed because [invalid form submission results in server errors](http://www.consumerfinance.gov/about-us/the-bureau/leadership-calendar/?filter_range_date_gte=01).
The reason for the pagination bug is somewhat simple but took some maneuvering to overcome. We served events to the page in most recent to least then grouped events …
=> Fix pagination bug

CHANGELOG.md, TEST.md, gulp/tasks/lint.js
- Adds ability to auto-fix linter errors with a command-line `--fix` flag on the linter task.
- Run `gulp lint --fix` and look at your changed files in git. See that `Header.js` and `es5-shim.js` have spacing issues that are automatically fixed.
- @sebworks 
- @contolini 
- @chosak 
- @virginiacc
=> Adds ability to auto-fix linter errors

cfgov/jinja2/v1/_includes/organisms/item-introduction.html
The combination of #2234 and #2226 broke the browser tests related to the "Learn Page" test page at `/browse-filterable-page/learn-page/`. This page [uses](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/scripts/initial_test_data.py#L195) an Item Introduction but doesn't fill in the date field. The [`item-introduction`](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/jinja2/v1/_includes/organisms/item-introduction.html#L65) template should check to make sure this field isn't null before trying to render it.
- Modify the `item-introduction.html` template to check for null `published_date` before rendering it.
- Run `gulp test` or `gulp test:acceptance` to see all 48 functional browser tests pass.
- @virginiacc
=> Fix broken Learn Page browser tests 

.eslintrc, npm-shrinkwrap.json, package.json
- Updates ESLint to v3 (latest).
- Minor linter file updates:
- Adds new `line` and `block` sections to `spaced-comment` rule.
- Adds (but doesn't enforce) the `multiline-ternary` rule.
- Matches order of rules to ESLint docs.
- @sebworks 
- @contolini 
- @virginiacc
=> Updates ESLint to v3

CHANGELOG.md, cfgov/v1/models/base.py, cfgov/v1/signals.py, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py, tox.ini
**This should probably go in after the timezone PR is merged #2189**
Scheduled publishing was broken because we changed the `route` function to point to the latest revision when publishing instead of the page itself. When running the management command `publish_scheduled_pages`, it would publish the revisions that were appropriate to publish but it wouldn't hit our logic to update the revision to `live=True` so the changes are never seen. This fixes that by making it hit our logic when calling `publish` on a revision anywhere using signal passing.
- Signal to call our revision logic to update the revision appropriately.
- New function to flush akamai
- [Here](https://github.com/cfpb/cfgov-refresh/pull/2189/files#diff-44507cc860654b805baac659b58d2c53L64) I removed the `publish()` call from …
=> Fix scheduled publishing

cfgov/unprocessed/js/modules/focus-target.js, cfgov/unprocessed/js/modules/util/behavior.js, test/unit_tests/modules/util/behavior-spec.js
Refactoring focus target to remove jQuery
- Added `cfgov/unprocessed/js/modules/util/Behavior.js` to provide easy mechanism for adding behaviors.
- Modified `cfgov/unprocessed/js/modules/focus-target.js` to remove jQuery and uitilize Behavior utility.
- Visit `http://localhost:8000/` and tab once. Click on the `Skip to main content` button in the upper left-hand corner. Observe that the `#main` element should have its `tab-index` attribute set to `-1`.
-
-
=> Refactoring focus target to remove jQuery

cfgov/unprocessed/js/modules/focus-target.js, cfgov/unprocessed/js/modules/util/behavior.js, cfgov/unprocessed/js/organisms/Header.js, cfgov/unprocessed/js/shims/es5-shim.js, test/browser_tests/conf.js, test/unit_tests/modules/util/atomic-helpers-spec.js, test/unit_tests/organisms/FilterableListControls-spec.js
- Minor linter fixes from autofixing errors with `--fix` flag and reformatting to remove some `max-len` warnings.
- `gulp lint` should show no errors (but will show warnings).
- @sebworks 
- @chosak 
- @contolini
=> Minor linter fixes

cfgov/cfgov/settings/test_nomigrations.py, tox.ini
When Python unit tests create a new test database, they start with the initial migration and then apply all subsequent migrations. This can be quite slow, even though we really only care about the final database schema as defined in various `models.py` files.
This PR modifies the `tox -e fast` faster unit test approach introduced in #2227 by restoring the use of a Django test database (using `manage.py test`) but modifying how it applies migrations.
- A new `cfgov.settings.test_nomigrations` inherits all from `cfgov.settings.test` but modifies the [`MIGRATION_MODULES`](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MIGRATION_MODULES) setting so that all migrations are skipped for all apps.
- Modifies the `tox -e fast` implementation introduced in #2227 so that unit tests …
=> Run Python unit tests quickly by skipping test database migrations

CHANGELOG.md, test/browser_tests/environment.js
I couldn't find anywhere that this was used. Seems safe to remove... or?
- Removed `interactiveTestPort` test variable.
- @imuchnik 
- @sebworks 
=> Removed interactiveTestPort variable

TEST.md, package.json, test/browser_tests/conf.js
Protractor accessibility plugin that runs [aXe](https://github.com/dequelabs/axe-core) against every page during browser tests.
- `plugins` array in protractor config file.
- `npm install`
- `gulp test:acceptance:full`
- @sebworks 
- @virginiacc 
- It's reporting lots of accessibility errors. 😓 
- `package.json` is pointing to our fork because our changes haven't reached [upstream](https://github.com/angular/protractor-accessibility-plugin/pull/6) yet.
=> Add accessibility acceptance tests

cfgov/cfgov/settings/base.py, cfgov/sheerlike/external_links.py, cfgov/unprocessed/css/misc.less, cfgov/v1/__init__.py
The logic handling links doesn't insert the correct markup.
- Added download link regex pattern and logic to parse_link function for rich text.
- CSS to add icon classes for files
- Markup is inserted and manipulated differently for affected links matching the patterns.
- Add cfpb link
- Add .gov link
- Add external link
- add file link
- make sure markup is correct for each one
- @willbarton 
- @virginiacc 
- @contolini 
-
- Change where logic is located for efficiency
- Possible refactor for readability
- Write tests
=> Fix link icons

.env_SAMPLE, CHANGELOG.md, cfgov/v1/__init__.py, cfgov/v1/models/base.py, cfgov/v1/templatetags/share.py, cfgov/v1/util/util.py, cfgov/v1/wagtail_hooks.py, config/environment.js, gulp/tasks/browser-sync.js, gulp/tasks/test.js, runserver.sh, test/browser_tests/.eslintrc, test/browser_tests/conf.js, test/browser_tests/environment.js, test/browser_tests/jenkins_conf.js, test/browser_tests/page_objects/page_wagtail_states_pages.js, test/unit_tests/modules/BreakpointHandler-spec.js, tox.ini
- Consolidated all environment variables in `config/environment.js`.
- Ignored `console.log` in tests and enforced `no-process`.
- Updated `STAGING_HOSTNAME` to `DJANGO_STAGING_HOSTNAME` environment var.
- Updated `HTTP_HOST` to `TEST_HTTP_HOST` environment var.
- Updated `HTTP_PORT` to `TEST_HTTP_PORT` environment var.
- Allows passing of port to `runserver.sh`.
- Added misnamed and unreferenced environment variables to .env.
- Removed unused `SELENIUM_URL` environment variable.
- Grab `clear variable state` and `export variable defaults` sections from `.env_SAMPLE` and add to your local `.env`.
- Update values in your local `.env` for:
- `STAGING_HOSTNAME` > `DJANGO_STAGING_HOSTNAME`
- `HTTP_HOST` > `TEST_HTTP_HOST`
- `HTTP_PORT` > `TEST_HTTP_PORT`
- add `SITE_DESC`
- add …
=> Consolidates environment variable references

gulp/tasks/test.js
The `gulp test` task currently spawns various processes to test different things: `tox` for Python unit tests, `wcag` for accessibility tests, `protractor` for browser tests, and `initial-test-data.sh` to load initial test data. If one or any of these processes return with a non-zero error code (for example if the Python unit tests fail), they should cause the gulp task to fail.
- `spawn()` calls in `gulp/tasks/test.js` now check the returned status code and call `process.exit` if it is non-zero.
- Run `gulp test` with a broken Python unit test (or temporarily remove or rename one of the dependent executables) and notice that the failure causes `gulp` to fail:
```sh
$ gulp test:unit
...
----------------------------------------------------------------------
Ran 131 tests in 0.973s
FAILED …
```
=> Fail gulp test when spawned processes fail

gulp/tasks/test.js
As an ASCII art connoisseur it pains me to remove this but I think it's time. Its output makes Travis reports nearly unusable.
- @chosak
=> Remove nyan cat unit test reporter 😿

cfgov/v1/tests/test_links.py
PR #2236 broke three unit tests by changing the expected type of the `parse_links` method. Previously it took a `BeautifulSoup` object but after that change expected a raw string or a `RichText` object. This PR fixes the unit tests in `v1.tests.test_links` to use that new behavior.
- Fixes to `v1.tests.test_links` in how `parse_links` is called.
- Run `tox` to verify that all unit tests pass.
- @kurtw @richaagarwal @Scotchester
=> Fix broken parse_links unit tests

cfgov/scripts/initial_data.py
This PR matches the change in 17239da0459dbf4bc9098cb3909731097d5846c8 to initial_test_data.py. Wagtail's migrations create an initial page with the slug "home". When running `./setup.sh` (or `./backend.sh` or `./initial-data.sh`) this will cause an error because the slug "home" already exists at the time when `./cfgov/scripts/initial_data.py` is run.
- Change the initial home page slug to "home-page" from "home"
- Run `./initial-data.sh` on a clean database.
To ensure that our setup scripts aren’t regularly broken, I will also set up a periodic Jenkins job that runs them and reports any failures.
=> Avoid a collision with Wagtail's initial home page slug

cfgov/jinja2/v1/_includes/organisms/footer.html, cfgov/unprocessed/js/modules/focus-target.js, cfgov/unprocessed/js/modules/footer-button.js, test/unit_tests/organisms/Footer-spec.js
Refactoring footer-button and removing jQuery
- Refactored `footer-button.js` to remove jQuery and use requestAnimationFrame for smooth scrolling to the top of page. 
- Visit `localhost:8000` on mobile an click the `Back to Top` button. It should smoothly scroll you back to the top of the page.
- Run 'gulp test:unit:scripts`
- Need to write further acceptance and unit tests.
=> Refactoring footer-button and removing jQuery

TEST.md, gulp/config.js, gulp/tasks/test.js, test/browser_tests/a11y_conf.js, test/browser_tests/conf.js
Running `gulp test` ran lots of tests including our new accessibility tests. This is annoying because it reports a lot of accessibility problems that we won't have time to address anytime soon.
Running `gulp test` doesn't include the accessibility tests. Run `gulp test --a11y` to include them.
- @chosak 
- It kills me to create a second config file (a11y_conf.js) but it was the only way I could figure out how to modify the `plugins` property via a command line option. Only the [onPrepare](https://github.com/angular/protractor/blob/a74175d4b37fed0b86ca9646b749585a5ff1ba52/docs/referenceConf.js#L195-L209) method seems to have access to the protractor globals and by then it's too late to add a plugin.
=> Only run accessibility tests when requested by the user

cfgov/unprocessed/js/organisms/FilterableListControls.js, test/browser_tests/conf.js, test/browser_tests/spec_suites/content/blog.js
Filter section submit button is cut off when blog page is loaded with more than 3 filter options selected
- Test for disappearing filter button
- Init multiselect before expandable in `FilterableListControls` so initial height set on expandable is calculated after filter choices are added to DOM
- Navigate to [blog page with 3+ filter options selected](http://localhost:8000/about-us/blog/?form-id=1&filter1_title=&filter1_topics=Mortgages&filter1_topics=Students&filter1_topics=Financial+education&filter1_topics=Student+loans&filter1_from_date=&filter1_to_date=) and check that submit button is displayed in filter expandable
Before
After
-
-
=> Fix disappearing submit button in filter expandable on blog page

cfgov/unprocessed/js/molecules/Multiselect.js, test/unit_tests/molecules/Multiselect-spec.js
- Adds `BASE_CLASS` and dom validity check to multiselect to align it with the other atomic components lifecycle.
- Fixes some minor linter warnings.
- `gulp test:unit:scripts && gulp test:acceptance --sauce=false` should pass (expect for the 2 acceptance test errors we're getting from wagtail on all PRs).
- @sebworks 
- Added a todo to scope the multiselect to markup that has the base class. If global behavior is needed, a separate script like this can be added to common.js or similar:
```
var mselects = document.querySelector( 'select[multiple]' );
for ( var i, len = mselects.length; i < len; i++ ) {
mselects.classList.add( 'cf-multi-select' );
}
```
=> Adds BASE_CLASS and dom validity check to multiselect.

cfgov/cal/test_views.py, cfgov/cal/views.py, cfgov/jinja2/v1/_includes/leadership-calendar-table.html, cfgov/jinja2/v1/_includes/macros/filters.html, cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/index.html, cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/print/index.html
Related to [GHE]/CFGOV/platform/issues/131
There are template errors and mishandled PDF logic that is fixed with this.
- Macros in the leadership-calendar-table.html template for modularity and clarity.
- Failed PDFreactor calls return the print template rendered instead of just passing.
- Fixed print template macro call
- Refactored templates and view logic
- Fixed markup for "checked" calendars
- Go to leadership calendar
- Filter on a calendar
- Filter on dates
- Click Download PDF button on the bottom controls form
- If PDFreactor is set up then it should return a pdf. Otherwise, it should direct you to the print page with all the events.
- @willbarton 
- @chosak 
- @virginiacc 
- @contolini 
- Tests
=> Fix bugs on leadership calendar

CONTRIBUTING.md
Modifies the CONTRIBUTING.md file slightly to align with the front-end standards, back-end discussions, our team discussion in-person last week, and our "Building and Deploying" working document.
- Adds some additional text about contributing to this repository.
@cfpb/cfgov-platform
=> Modify CONTRIBUTING guidelines based in-person discussions

cfgov/cfgov/settings/test.py, cfgov/cfgov/test.py, cfgov/scripts/initial_data.py
This PR tries to setup required initial test data before running the Python unit tests, by implementing a custom Django TestRunner class.
- Added new `cfgov/cfgov/test.py` file that contains a `cfgov.test.TestDataTestRunner` class.
- Removed check against `settings.DEBUG` in `cfgov/scripts/initial_data.py` as this seemed like an unnecessary check vs. just not running the script. Is there anywhere this script is ever run in production?
- Python testing using `manage.py test` now uses the custom test runner, which does these steps before running the tests:
1. Checks to see if the Wagtail [initial_data](https://github.com/torchbox/wagtail/blob/v1.5.3/wagtail/wagtailcore/migrations/0002_initial_data.py) migration has been run (it normally is when running `tox` or `manage.py test`, but not …
=> Setup initial test data when running Python unit tests

cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/test-fixture/index.html, cfgov/legacy/templates/front/base_update.html
base_update.html does not include IE8 fallback script to set IE visitors to the no-js state, very likely leading to JS errors on the pages that use that template.
Fixes https://github.com/cfpb/cfgov-refresh/issues/2264
The on-demand header was not including the nonresponsive CSS when it was in IE8. This PR includes the correct CSS where needed.
- Adds conditional code blocks for IE8/9.
- Adds non-responsive CSS for IE8.
- General code style cleanup of inline JS in template.
- Inline JS for adding js/no-js flags that should be set in modernizr.
- No sure how to test this. @rosskarchner do you know how to test changes to the `base_update.html` template?
- For the on-demand bits: 
1. Run `gulp scripts:ondemand && gulp styles:ondemand`
2. Open `/test-fixture/` in sauce labs (won't work in …
=> Add/Correct IE8/9 fallback code for base and on-demand templates

cfgov/jinja2/v1/_includes/molecules/jobs-list.html
We currently don't have a molecule which matches the current Career page requirements, so I've created a jobs list molecule. This molecule will be used on `/about-us/careers/` page, within the `Sidebar-Breakout` organism.  
- Adding Jobs List Molecule
- N/A
- @chosak 
- @virginiacc 
- @ajbush
=> Adding Jobs List Molecule

CHANGELOG.md, package.json
Version has to be three digits long to avoid npm warnings.
- Updates changelog and package.json version to `3.6.0` from `3.6`.
- Adds additional `description`, `homepage`, and `author` fields to `package.json`.
- `npm uninstall sinon-chai` should show no npm warnings in the console.
- @sebworks 
- @virginiacc 
- @contolini 
=> Fixes package.json fields

CHANGELOG.md, npm-shrinkwrap.json, package.json
`sinon-chai` does not appear to be used.
- Removes `sinon-chai` npm package.
- `gulp test:acceptance --sauce=false` should pass.
- @contolini 
- @virginiacc 
- @sebworks
=> Remove unused sinon-chai

cfgov/jinja2/v1/_includes/molecules/contact-email.html, cfgov/jinja2/v1/_includes/molecules/info-unit.html
Adding email address to info-unit molecule
- Modified  `cfgov/jinja2/v1/_includes/molecules/contact-email.html` to use `email.text` before `email.url`.
- Modified  `cfgov/jinja2/v1/_includes/molecules/info-unit.html` to use display email address if `link.text` contains and email address.
- Create a `Sublanding` page via Wagtail. 
- Add a `Half Width Link Blob Group` molecule. 
- Enter `email@example.com` in the link text field. Preview.
- Notice that the link has the email formatting. 
- @chosak 
- @virginiacc 
-
=> Adding email address to info-unit molecule

cfgov/jobmanager/static/jobmanager/js/fellows.js
After getting familiar with the JavaScript files in main repository, I spotted a missing semicolon in fellows signup form jQuery. I decided to fix it as missing semicolon might actually have an adverse effect in submitting the form or printing out the submission message.
File: ```cfgov/jobmanager/static/jobmanager/js/fellows.js```
Added missing semicolon in fellows signup form jQuery.
=> Fixed missing semicolon in fellows.js

CHANGELOG.md, frontend.sh, npm-shrinkwrap.json, package.json, test/browser_tests/spec_suites/integration/global-search.js, test/browser_tests/spec_suites/integration/mega-menu.js
- Updates protractor to version 4.0.2.
- Updates webdriver-update path as that has been spun off to its own module.
- Updates TODOs in search and menu tests for waiting for elements to be hidden.
- If you have global protractor installed, run `npm install -g protractor && webdriver-manager update`
- Run `./setup.sh`
- Run `gulp test:acceptance --sauce=false`
There may be 15 errors from the leadership calendar, but those are existing.
- @chosak 
- @sebworks 
- @virginiacc 
- @contolini
=> Updates protractor to version 4

cfgov/jobmanager/static/jobmanager/js/supervision.js
Hello. While familiarizing myself with the JavaScript source code, I spotted another missing semicolon in the .js files. This time, the bug was in was in file:
cfgov/jobmanager/static/jobmanager/js/supervision.js. 
This has now been amended. The change should mitigate the bug risk.
Thank you. 
- Amended missing semicolon in ```goto-jobs``` jQuery function.
=> Amended missing semicolon

cfgov/jinja2/v1/job-description-page/index.html
Converting Jobs Description template to Wagtail. This is based on the jobs UI from Django Admin and the Event template.
- Modified the existing [template](https://github.com/cfpb/cfgov-refresh/blob/e0e0f874adb344f5afdd47a6404a7acdb5004478/cfgov/jinja2/v1/about-us/careers/_single.html) to allow usage within Wagtail.
- No great way to test until implemented in Wagtail.
- @chosak
=> Converting Jobs Description template to Wagtail

CHANGELOG.md, docs/development-tips.md, gulp/tasks/test.js, npm-shrinkwrap.json, package.json
- `banner-footer-webpack-plugin` was set to `0.0.1`, however that package does not have any releases so this reverts it back to a git URL.
- Updated capital framework to latest release.
- Fixes minor JS linter error.
- Adds instructions for updating a dependency.
- `setup.sh` should have no probs.
- @contolini 
- @sebworks 
- @virginiacc 
- Throwing out and re-generating the shrinkwrap updated a whole bunch of dependencies. I think this means that our shrinkwrap was out of sync with `package.json` prior to this PR, but am I missing something with how to update it? @contolini ?
=> Adds dep update instructions | fixes minor package issues

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/pagination.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/unprocessed/css/molecules/pagination.less, test/browser_tests/shared_objects/pagination.js, test/browser_tests/spec_suites/integration/browse-filterable.js
Pulls the pagination updates out of https://github.com/cfpb/cfgov-refresh/pull/2201 without including the stepper.
- Updated browse-filterable test suite to properly nest pagination tests.
- Updated pagination to support multiple pagination molecules on a single page.
- Moved pagination tests from /organisms/ to /molecules/ where they belong.
- `gulp test:acceptance --specs=integration/browse-filterable.js --sauce=false`
- `gulp test:acceptance --specs=molecules/pagination.js --sauce=false`
- visit /blog/ and check that the pagination with and without a filter work correctly.
- @sebworks 
- @contolini
- @virginiacc  
- @chosak 
- My local dev setup data isn't working to display /blog/ so hopefully that's not broken!
=> Makes pagination a macro

CHANGELOG.md, npm-shrinkwrap.json, package.json
- Update gulp-imagemin to 3.0.2.
- Re-generate shrinkwrap.
- `rm -rf ./node_modules/ && npm install && gulp build` should pass.
- @contolini 
- @sebworks 
- @virginiacc 
- 3.x includes compressor settings that we're not currently using, though I'm unsure if we should be --> https://github.com/sindresorhus/gulp-imagemin/releases/tag/v3.0.0
=> Update gulp-imagemin to 3.0.2

docs/atomic-structure.md
Hi. I spotted few spelling mistakes in the documentation file ```docs/atomic-structure.md```. These have been now amended.
- Documentation spelling amendments. 
Javascript --> JavaScript
url --> URL
No functional changes to software itself.
=> Documentation spelling fixes

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/unprocessed/js/modules/Analytics.js, cfgov/unprocessed/js/organisms/FilterableListControls.js, test/unit_tests/modules/Analytics-spec.js, test/unit_tests/organisms/FilterableListControls-spec.js
Adding Filter Analytics 
-  Added `cfgov/unprocessed/js/modules/Analytics.js` to serve as a singleton for sending events to GTM.  This is based on code contained in [eRegs](https://github.com/cfpb/regulations-site/blob/84891b05e8c24530b78260593bfca29e5b44ecb8/regulations/static/regulations/js/source/events/ga-events.js).
- Added `test/unit_tests/modules/Analytics-spec.js` as a skeleton until I write tests.  The tests are atricky because it's a single and has a self-invoking `init` function.
- Modified `cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html` to fix issues with the filter labels.
- Modified `cfgov/unprocessed/js/organisms/FilterableListControls.js` to send filter events when checkboxes are changed, text is entered, or the form is submitted.
- Modified …
=> Adding Filter Analytics

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Data & Research will be publishing a new page for the Research Conference (whooo!). Adding the link to the nav so that it will be discoverable.
- Added new conference url in the nav
- checkout the branch and make sure the link is in the nav
- @cfarm 
- @schaferjh 
- It doesn't go anywhere yet, but when the page is published next tue/wed this should get merged shortly so it can go out with the following release.
=> READY: Updated the nav for the upcoming conference page

package.json
AFAIK this is cruft (and jenkins doesn't like it).
- `cf-component-demo` dependency
- @virginiacc 
- @sebworks 
=> Remove CF component demo dependency

cfgov/jinja2/v1/_includes/organisms/table.html, cfgov/jinja2/v1/about-us/careers/_macro-table-current-openings.html, cfgov/jinja2/v1/events/_macros.html, cfgov/unprocessed/css/enhancements/tables.less, cfgov/unprocessed/css/pages/event.less, cfgov/unprocessed/js/modules/o-table-row-links.js, cfgov/unprocessed/js/routes/about-us/careers/current-openings/index.js, test/browser_tests/page_objects/page_dbwu-small-businesses.js, test/browser_tests/page_objects/page_dbwu-upcoming-procurement-needs.js, test/unit_tests/modules/o-table-row-links-spec.js
Converting simple table to table organism for Careers Page
- Modified CSS, Javascript, spec files in conjunction with converting simple table to a table organism.
- Visit the `http://localhost:8000/.gov/about-us/careers/current-openings/` and observe that the table highlighting still works via mouseover.
- @virginiacc 
- @contolini 
Wasn't sure if the table highlighting should just be a behavior.
=> Converting simple table to table organism for Careers Page

backend.sh
- Remove `backend.sh` message about activating virtual environment.
- Open a new tab and cd to the project directory.
- Run `deactivate` if a virtual environment was activated.
- Run `./backend.sh` and see that the message output does not include the virtualenv.
- @chosak 
- @kurtrwall
=> Removes potentially misleading instructions from backend.sh

gulp/tasks/test.js
- Script was referencing `HTTP_PORT` and `HTTP_HOST`, which should be prefixed with [`TEST_`](https://github.com/cfpb/cfgov-refresh/blob/master/.env_SAMPLE#L121-L122)
- Set a different port number for `TEST_HTTP_PORT` in `.env`, restart the server, and run `gulp test:perf` and it shouldn't fall over looking for port `8000`.
- @virginiacc 
- @sebworks 
- @contolini 
- I really think the ` || 'localhost'` and ` || '8000'` defaults should be removed and the envvar should be enforced in `.env`, otherwise errors like this get hidden till you need to switch to a non-standard port because you're running two projects at the same time. @chosak sorry to beat a dead horse, but was it decided to enforce `TEST_HTTP_PORT` as a value in `.env`?
=> Update to correct envvars

cfgov/cal/views.py
The 'master' version of this fix should probably use environment variables (but default to localhost if the variable is unset)
=> Be less "clever" when setting BaseURL

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/social-media.html, cfgov/jinja2/v1/_includes/organisms/expandable.html, cfgov/unprocessed/css/molecules/social-media.less, cfgov/unprocessed/css/organisms/expandable.less
We're launching Money as You Grow in Spanish on September 1st. The pages (unlike the existing English pages, which live in the fin-ed-resources repo) will be built in Wagtail. Consequently, they need the microcopy on a few choice modules to be in Spanish.
This needs to be a hotfix because the next regularly-scheduled release is Tuesday, September 6th.
- Added support for Spanish-language cue labels to the Expandables organism.
- Added support for Spanish-language heading to the Social Media molecule.
1. Pull branch
2. `gulp styles`
3. `runserver`
4. Create a new Browse page in your local Wagtail instance.
5. Add an Expandable to the main content area, and a Social Media module (in sharing mode) to the sidefoot.
6. Preview it.
7. Observe the cue labels on the Expandable and the heading on …
=> Hotfix: Spanish molecule translations

cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/print/index.html
While further troubleshooting PDF's, I discovered that PDFReactor was really choking on main.css. Removing it made the difference between **painfully slow** (takes multiple minutes, sometimes times out) to reasonably zippy.
What I've done here, is take the template and remove it from the "base.html" inheritance chain. I've added the necessary CSS directly to the template. This isn't front-end code that we'll be proud of, but with this change, this feature is now usable.
- Review this PDF generated with this code:  [cfpb-leadership (22).pdf](https://github.com/cfpb/cfgov-refresh/files/435530/cfpb-leadership.22.pdf)
- If you have a working PDF reactor, give it a try
(note that this PDF exposes a logic flaw in the application itself-- that event from March 14th should not appear there. This …
=> Hotfix: Decouple leadership calendar PDF template from base.html

requirements/base.txt
I think this upgrade was erroneous (but understandable, the way our requirements have been split among multiple repo's), but I want to make sure @grapesmoker didn't have a specific reason for upgrading it.
- change base.txt to reference djangorestframework==2.4.8
=> Downgrade djangorestframework

.eslintrc, CHANGELOG.md, gulp/.eslintrc, gulp/tasks/test.js
- Updated ESLint dot-notation rule to support `catch` block in a Promise.
- Updated `gulp test:perf` task to use a Promise.
- Added `.eslintrc` override for gulp tasks to allow process.exit and console logging.
- `gulp lint:build` should only warn about TODOs.
- `gulp test:perf` should work as expected (@contolini plz see that I didn't break anything)
- @contolini 
- @sebworks 
- @virginiacc
=> Squash gulp lint:build warnings/errors

cfgov/v1/models/base.py, cfgov/v1/models/learn_page.py, cfgov/v1/tests/models/test_page_settings.py
To make editing Wagtail pages easier for content managers, this PR reorders items in the page configuration tab to match the following specified order:
* Settings, 
* Categories, 
* Tags, 
* Page preview fields (expanded by default)
* Authors, 
* Relevant dates, 
* Scheduled publishing
* Language
- New tests to enforce that all pages that inherit from `CFGOVPage` comply with this order.
- Modified order of fields on `CFGOVPage` and `AbstractFilterPage` to comply with new order.
- Create a new `DocumentDetailPage` or edit an existing one in the Wagtail editor and notice that the field order has changed, and that page preview fields should be expanded by default.
- @cfpb/cfgov-backends @schaferjh
=> Modify default Wagtail page settings panel order

gulp/tasks/docs.js
`glob` was being required while it was not imported in `package.json` so that reference should be updated to the imported `glob-all` module.
- Updates reference to glob-all from glob
=> Updates reference to glob-all from glob

CHANGELOG.md, gulp/tasks/test.js, npm-shrinkwrap.json, package.json
Updates to next major version of mocha, which drops older node support.
- Updated mocha npm module to version `3.0.2` from `2.4.5`.
- Updated gulp-mocha npm module to version `3.0.1` from `2.2.0`.
- Requires gulp-mocha module directly instead of going through plugins since new version had an issue with the plugins syntax (this is probably preferable anyway so that the module name shows up in searches).
- `./frontend.sh` 
- `gulp test:unit:scripts` should pass.
- @contolini 
- @sebworks 
- @virginiacc
=> Updates gulp-mocha/mocha to version `3.x.x`

docs/deployment.md
Hi. I spotted a spelling mistake in the documentation file docs/deployment.md. This has been now amended.
- Documentation spelling amendment.
depoyment -> deployment
No functional changes to software itself.
=> Spelling amendment: deployment.md

npm-shrinkwrap.json, package.json
- Updates gulp-istanbul to `1.1.1` from `0.10.3`.
- `./frontend.sh && gulp test:unit:scripts` should pass.
- @sebworks 
- @virginiacc 
- @contolini
=> Updates gulp-istanbul to `1.1.1`

docs/front-end-build.md
Another documentation spellcheck, this time for docs/front-end-build.md.
- Couple of spelling mistakes amended.
concatinating -> concatenating
clientside -> client-side
No functional changes to software.
=> Docs spellcheck: front-end-build.md

cfgov/v1/forms.py
[This commit](https://github.com/cfpb/cfgov-refresh/commit/12379803d316a6e7321a8f439b8806e499ea3964) accidentally introduced a `pdb` breakpoint into the calendar forms code. This PR removes that breakpoint.
- Removes `import pdb; pdb.set_trace()` statement.
- Assuming this was checked in erroneously @richaagarwal.
=> Remove pdb breakpoint

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/item-introduction.html, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/v1/models/base.py, cfgov/v1/tests/models/test_author_names.py
Filtering breaks if a user clicks a link from an author's name or a tag on the post preview.
- post-preview.html tag/author rendering uses slugs to create links now so filtering doesn't break
- Run `tox`
- Go to any filterable list page and click an author or tag link to make sure you receive results and no errors
- @chosak 
=> Fix post-preview.html to use tag/author slugs in links

CHANGELOG.md, cfgov/cfgov/settings/local.py, cfgov/scripts/archive_events.py
So that we don't have to use print statements.  I updated `archive_events` as an example, although I don't actually think we use it anymore. 
Run `python cfgov/manage.py runscript archive_events` to see the logging in action.
@cfpb/cfgov-backends
=> Set up logging locally

CHANGELOG.md, cfgov/scripts/_atomic_helpers.py, cfgov/v1/models/sublanding_page.py, cfgov/v1/tests/models/test_sublanding_page.py
The get_browsefilterable_posts function had a mistake in it that would cause an uncaught exception if one of the intermediate calls to get_page_set returned None. That was fixed. Also, tests were written for get_browsefilterable_posts and get_appropriate_descendants functions.
* test for get_appropriate_descendants
* test for get_browsefilterable_posts
* in get_browsefilterable_posts, the filtered_controls dict accumulates the results of get_page_set via append so that it doesn't throw an error if that result is None.
* two tests written as above
@richaagarwal @chosak @willbarton
=> fixed a mistake in get_browserfilterable_posts and wrote a test for it

cfgov/legacy/static/nemo/_/c/styles.css, cfgov/legacy/templates/front/base_nonresponsive.html, cfgov/legacy/templates/front/base_update.html
When Javascript is turned off on pages that use the `base_nonresponsive.html` template (like `find-a-housing-counselor`) or `base_update.html`  template (like `askcfpb`), the menu loads open and won't close
- Add `no-js` class to `<html>` in `base_nonresponsive.html` template
- Add `no-js` class to `<html>` in `base_update.html` template
- Override hover state background color for menu links in legacy `styles.less`
- Check out branch
- Turn off js in browser
- Navigate to [http://localhost:8000/find-a-housing-counselor](http://localhost:8000/find-a-housing-counselor) and [http://localhost:8000/askcfpb](http://localhost:8000/askcfpb) and verify that: 
- menu is not open on load & behaves as expected
- menu links don't have background color on hover
Before:
After: …
=> Fix menu on no-js base_nonresponsive/base_update pages

.travis.yml, README.md
In hopes of speeding up test runs, this takes a shot at running parallel
tests, caching pip installs between runs and combining the coverage
reports. If this doesn't help, we could try caching specific directories.
This also fixes branch specifiers for the build and code climate badges, 
which were still pointed at the  flapjack branch.
- New travis configs
- README badges
- @chosak @sebworks
=> Try parallel testing and caching

cfgov/v1/db_router.py, cfgov/v1/tests/test_db_router.py
Models for the `jobmanager` app should go to/from the `default` database on the content server, so that they can be edited and shared/published properly in the Wagtail editor.
- New unit tests for the `CFGOVRouter` database router.
- Adds the `jobmanager` app to the list of apps covered by `CFGOVRouter`.
- Testing this properly locally is difficult because we don't have a way to reproduce the multi-database setup. There are new unit tests (`tox`) that test the router itself. This change mirrors the existing structure which works for other apps.
- @rosskarchner @willbarton
=> Add jobmanager app to CFGOVRouter

cfgov/cfgov/test.py, cfgov/cfgov/urls.py, cfgov/v1/tests/views/test_documents.py, cfgov/v1/views/__init__.py, cfgov/v1/views/documents.py
Current Wagtail behavior for downloads from a remote file storage (e.g. S3) is to load the file contents and serve them as a Django `StreamingHttpResponse`. This can be inefficient and also breaks the file content-type, preventing browsers from e.g. displaying PDFs naturally.
This PR modifies file download behavior so that requests to download a remote file (e.g. `/downloads/pk/filename`) return a (temporary) redirect to the S3 location, e.g. `http://s3.amazonaws.com/bucketname/f/documents/filename`.
Local file serving behavior is not modified when running in debug mode.
- New `v1.views.documents.DocumentServeView` view class that handles non-local file downloads by returning a redirect, and passes local file downloads off to the built-in `wagtail.wagtaildocs.views.serve` method.
- I …
=> Return redirect when retrieving Downloads from S3

CHANGELOG.md, cfgov/unprocessed/css/molecules/info-unit.less
The declaration was unnecessary, as there is an explicit `height` declared on the `__square` variant, and it was unintentionally restricting the size of 16:9 info unit images, which are necessarily taller than 150px when [spanning the full column width](http://cfpb.github.io/design-manual/page-components/50-50.html).
- Removed `max-height` from the styling of info unit images.
1. Run the server.
1. Create a page with a 50/50 Image and Text module, adding an info unit with an image in a 16:9 aspect ratio and selecting the "Use 16:9 image" option.
1. Preview the page and observe the image not spanning the full width of the column.
1. Pull this branch.
1. Reload the test page and observe the image spanning the full width of the column.
- I see that …
=> Remove max-height from info unit images

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/social-media.html
Our stakeholder for Money as You Grow Spanish informed us that the label for the sharing module in Spanish should simply read "Compartir", not "Compartir este"
- Corrected Spanish-language label for sharing module
- @cfpb/cfgov-frontends
=> Fix Spanish label for sharing module

.travis.yml, CHANGELOG.md, gulp/tasks/test.js, requirements/travis.txt, run_travis.sh, tox.ini
Add a run_travis script and travis matrix vars
This produces separate parallel builds for front and back ends and should
fix our blank coverage badge. ~~but the coverage report for js still doesn't pick up data~~
- run_travis.sh to launch separate builds
- the `coverage combine` command, which wasn't doing the job
- @chosak @contolini 
Check out the jobs at https://coveralls.io/builds/8022169
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
- ~~I could use some front-end pairing to work on js reporting~~ -- done
=> Fix coveralls

CHANGELOG.md, cfgov/v1/blocks.py, cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py, cfgov/v1/tests/test_blocks.py, cfgov/v1/tests/test_util.py, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/util/util.py, cfgov/v1/wagtail_hooks.py, docs/forms-in-wagtail.md, tox.ini
This adds a block class to be used for modules that have a form. The class automatically handles getting the form into the context of the page. Developers should only have to follow steps from the docs to get the form in the page context.
- AbstractFormBlock
- `CFGOVPage.serve_ajax()` to handle ajax requests.
- util module
- `load_class` that takes in a path to a class and returns the class
- `get_streamfields` returns a dictionary of a page's streamfield names and values
- `form_module_handlers` function to add form module's context to the page's context
- `CFGOVPage.serve` overridden to call `serve_ajax` for ajax requests.
- `CFGOVPage.get_context` overridden to call registered `cfgovpage-context-handlers` functions
- `tox`
- @hillaryj
=> Add AbstractFormBlock for handling forms in Wagtail pages

docs/release-cadence.md
This PR brings our release cadence documentation (the sample schedule) into line with our current reality, and makes a few minor modifications and clarifications, particularly emphasizing the CHANGELOG being up-to-date.
You can view the changes here: https://github.com/cfpb/cfgov-refresh/blob/69c22928ee950ce5bd0cf88057d71a12ea60bac9/docs/release-cadence.md
=> Update our sample release schedule

cfgov/legacy/templates/front/base_nonresponsive.html, cfgov/legacy/templates/front/base_print.html, cfgov/legacy/templates/front/base_update.html, cfgov/legacy/templates/front/share_links.html, cfgov/templates/find_a_housing_counselor.html
The static tag that you get from `{% load static %}` doesn't respect the value of STATICFILES_STORAGES, which means it can't take advantage of the changes made in #2407.
`{% load static from staticfiles %}` is a drop-in replacement that DOES respect those your configured static storage mechanism.
https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#std:templatetag-staticfiles-static
- described above!
- check a legacy django page (like /find-a-housing-counselor/ ) before and after the change, and you should notice no changes.
- @cfpb/back-end-team-admin
=> Django templates: use staticfiles instead of plain old 'static'

cfgov/v1/__init__.py
As of BeautifulSoup library version 4.4 (release blog post [here](https://www.crummy.com/2015/06/29/0)), a warning is generated if the library is initialized without [specifying a parser](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser). This PR fixes a place in the code where this wasn't being done.
- Specify use of the `html.parser` parser with BeautifulSoup.
- Run `tox -e fast v1.tests.test_links` and note that no warnings are generated.
- The warning being generated was:
```sh
/cfgov-refresh/.tox/fast/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this sys
tem ("lxml"). This usually isn't a problem, but if you run this code on another …
```
=> Specify parser for BeautifulSoup

CHANGELOG.md, cfgov/cfgov/urls.py
The Owning a Home team would like to start using wagtail for their homepage to be able to use wagtail features and change content in wagtail. This PR removes the Owning a Home home page from urls.py and explicitly lists the other OaH pages in its place.
- All of the urls listed in the urls.py should work, but the OaH homepage should 404 locally. On build it will grab the new OaH wagtail page.
- @virginiacc 
- Like all back-end changes, please let me know if something seems even slightly off, since this is my first time doing this. Thanks!
=> Remove the OAH homepage from urls.py

cfgov/jinja2/v1/_includes/article.html, cfgov/jinja2/v1/_includes/setup-feedback-and-render.html, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/jinja2/v1/document-detail/index.html, cfgov/jinja2/v1/landing-page/index.html, cfgov/jinja2/v1/learn-page/index.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/jinja2/v1/wagtail/demo/index.html
Addresses [comments](https://github.com/cfpb/cfgov-refresh/pull/2418/files#r80704024) by @chosak and @richaagarwal about DRYing up the template pieces.
It's probably not a full and complete solution, but I think it's a decent step forward. PRing this to that branch in case folks think there's a better path.
Also fixes that one [missing `endfor`](https://github.com/cfpb/cfgov-refresh/pull/2418/files#r81018476)
- @kurtrwall 
- @chosak 
=> Pull feedback stuff into partial

cfgov/legacy/templates/front/base_nonresponsive.html
These tags should have been removed when the static tag was changed.
-
-
-
-
- @user
-
-
=> remove old get_static_prefix and friends

cfgov/jinja2/v1/_includes/molecules/info-unit.html, cfgov/jinja2/v1/index.html
That was a poorly considered change, and broke info-unit's on wagtail pages that included uploaded pictures. 
- the info-unit's on the home page should still render correctly
- @chosak 
must do that now
=> move the static() calls out of the info-unit module

CHANGELOG.md, cfgov/core/tests/test_missing_migrations.py, cfgov/v1/atomic_elements/organisms.py, run_travis.sh
Subtle changes to Wagtail atomic elements can require unexpected Django migrations, and there have been a few times where PRs have failed to include them. This PR adds a new unit test that fails if there are any unapplied migrations, as determined by using the Django [makemigrations](https://docs.djangoproject.com/en/1.8/ref/django-admin/#makemigrations-app-label) command.
- New `core.tests.test_missing_migrations.py` unit test.
- Run `tox core.tests.test_missing_migrations`. It should pass. Make a minor change to a Wagtail atomic element (say, [this](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/v1/atomic_elements/organisms.py#L83) help text). Run the `tox` command again. It should fail.
- Note that this test will not fail if there are unapplied …
=> Unit test that checks for missing migrations

CHANGELOG.md, gulp/config.js, package.json
Including the version number in built output will lead to files being marked as "changed", even if there aren't actual changes to the code-- busting the cache on every release, instead of just when there are real changes.
This PR stops that from happening. Thank you for the consultation, @sebworks and @contolini!
- no more version number in package.json
- no more version number in the 'banner' gulp template.
- @cfpb/cfgov-frontends
=> Remove version number from css banner and package.json

CHANGELOG.md, cfgov/cfgov/settings/local.py, docs/usage.md, requirements/local.txt, requirements/test.txt, runserver.sh
This PR lets you run a local server using HTTPS, which is useful for debugging mixed-content warnings and other SSL-related issues.
Run the local server using `./runserver.sh ssl`:
```sh
$ ./runserver.sh ssl
SUCCESS! MySQL running (2221)
Starting SSL Django server on port 8000 ...
Validating models...
System check identified no issues (0 silenced).
October 03, 2016 - 15:19:19
Django version 1.8.14, using settings 'cfgov.settings.local'
Starting development server at https://127.0.0.1:8000/
Using SSL certificate: /Users/user/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/sslserver/certs/development.crt
Using SSL key: /Users/user/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/sslserver/certs/development.key
Quit the server with CONTROL-C.
```
The local server is now …
=> Run HTTPS locally

CHANGELOG.md, cfgov/flags/migrations/0008_add_prepaid_release_flag.py, cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
- Added Prepaid Cards to mega menu.
1. Pull branch
2. Migrate
3. Runserver
4. Flip `PREPAID_RELEASE` flag on in Wagtail Admin
5. Visit site and see it in the Consumer Tools menu
- @willbarton 
- @chosak 
- Remove flag in 3.11 release.
=> Hotfix: Adding Prepaid Cards to the mega menu behind a feature flag

cfgov/templates/hud_list.html
This is the template used when generating PDF's from the find-a-housing-counselor tool
- `{% load staticfiles %}` in hud_list.html
- @willbarton
=> Add missing {% load staticfiles %}

CHANGELOG.md, requirements/optional-private.txt, requirements/optional-public.txt
These updates all add [cfgov-django-setup](https://github.com/cfpb/cfgov-django-setup), which centralizes all of our "build front-end assets when building the python app" code, and implements a key improvement: the python build will now fail if the underlying front-end build script fails. 
[These changes are still pending in regulations-site](https://github.com/cfpb/regulations-site/pull/817)
- complaints app updated to 1.2.5
- retiremen app updated to 0.5.3
- knowledgebase app updated to: v2.1.3
- college-costs app updated to: 2.2.6
- @cfpb/back-end-team-admin
=> app version bumps for cfgov-setup

CHANGELOG.md, cfgov/core/static/robots.txt
It's a robots.txt file!
We will almost certainly iterate on this, but I think this is an OK start. I've only chosen to disallow URL's that produce PDF's, and the "print" versions of Spanish AskCFPB pages (the english versions were removed in the recent redesign).
I've also used the 'sitemap' declaration to point to the activity log RSS feed, since [the sitemap protocol allows it](http://www.sitemaps.org/protocol.html#otherformats). We should still look into a "real" sitemap, but this should allow search engines to pick up new content faster (at least, content that's reflected in the activity feed)
Once merged (and deployed), we'll need to create an alias from /robots.txt to  (site location on server/static/robots.txt
- a robots.txt files
- @willbarton 
- @schaferjh 
-
-
=> initial robots.txt

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/global-search.html, test/browser_tests/spec_suites/integration/global-search.js
Links and searches to search.consumerfinance.gov should use HTTPS, not HTTP.
- Changed references from http://search.consumerfinance.gov to https://search.consumerfinance.gov.
- Run a local server, and type a search into the search box. Note that it links to https://search.consumerfinance.gov.
- This will prevent mixed-content warnings when cf.gov moves to HTTPS itself.
=> Use HTTPS for search

cfgov/cfgov/settings/base.py
An "etag" is a token that represents the content at a URL at a particular point in time. The idea is, that if a web browser holds on to these etag values, and if a URL is requested again (using the [If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) request header, the browser can make a *conditional* request-- "send me the content at this URL, unless the etag is still XYZ". If the etag is unchanged, instead of responding with "200 OK" and the content, it'll respond with "304 Not Modified" and *not* transmit the content.
Our Akamai configuration is currently not set to validate etags, but I am working to get that fixed shortly.
You can accomplish similar things with the Last Modified date, but that's a little tricker with dynamic content (and Django …
=> enable USE_ETAGS

requirements/optional-public.txt
This PR bumps the version number of the `complaints` app to 1.2.6.
- Pin the `complaints` requirement to 1.2.6
=> Bump complaints to 1.2.6

requirements/optional-private.txt
Includes @virginiacc's formatting fixes, and fixes a broken `{% static %}` tag
=> bump comparisontool to v1.2.6

CHANGELOG.md, cfgov/jinja2/v1/_layouts/base.html
We currently write the `es-5` script to all browsers. This PR adds code which conditionally adds the script using Modernizr feature detection.
- Modified `base.html` to wrap the es-5 script in a conditional statement.
- Use Saucelabs to browse the site on a Android 4.1 device. Verify that the navigation and site work as expected.
- @contolini 
- @Scotchester
=> Wrapping es-5 script in conditional statement

cfgov/legacy/templates/front/base_nonresponsive.html, cfgov/legacy/templates/front/base_update.html
This PR changes some script includes in legacy templates from HTTP to HTTPS.
This is a followup to #2455.
- Changed references from http://search.usa.gov to https://search.usa.gov.
- Passes all unit tests.
- Run an HTTPS localhost (`./runserver ssl`) and then navigate to [https://localhost:8000/paying-for-college/](https://localhost:8000/paying-for-college/) (requires the `college-costs` app). Note there are no mixed-content warnings.
- @sebworks @cfpb/cfgov-frontends 
- This will prevent mixed-content warnings when cf.gov moves to HTTPS itself.
=> Change search script include from HTTP to HTTPS

cfgov/cfgov/settings/base.py
This PR makes two minor cleanup changes to `settings.OPTIONAL_APPS`.
- Removes reference to `publish-eccu`, which is no longer used as of #2417.
- Moves `jobmanager` from `OPTIONAL_APPS` to `INSTALLED_APPS` as this app is now part of the main `cfgov-refresh` repository.
- All unit tests pass, including `jobmanager` ones.
- I didn't update the CHANGELOG as it seems like a fairly minor thing to mention.
=> Clean list of optional apps

CHANGELOG.md, cfgov/cfgov/test.py, tox.ini
This PR modifies the unit test runner so that it runs unit tests for satellite apps, if they are present.
~~It modifies the default Travis config to install public satellite apps (from `requirements/optional-public.txt`) and run unit tests against them.~~
- Default test runner in `cfgov.test.TestDataTestRunner` now adds optional app unit tests, if those apps are present locally (both public and private).
- ~~Travis default configuration now installs public optional apps as part of its testing.~~
- Install optional apps (`pip install -r requirements/optional-public.txt`) then run `tox -e optional` or `tox -e fast-optional` and verify that extra tests are being run.
- Confirm that default testing still works properly, e.g. `tox -e fast v1`.
- Adding optional app …
=> Run unit tests for optional apps, if they exist

CHANGELOG.md, npm-shrinkwrap.json, package.json
- Upgrade `gulp-sourcemaps` from `1.6.0` to `2.1.1` in `package.json`.
- Rebuild `npm-shrinkwrap.json`.
- throw out `node_modules`.
- `npm install`
- `gulp build` should pass.
- @cfpb/cfgov-frontends
=> Upgrade `gulp-sourcemaps` from `1.6.0` to `2.1.1`

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
This PR restores the Prepaid menu item for the 3.11 release branch.
- Restore Prepaid links in mega-menu
=> Restore Prepaid menu update for 3.11

cfgov/flags/decorators.py, cfgov/jinja2/v1/_includes/organisms/job-listing-list.html, cfgov/jobmanager/models/blocks.py, cfgov/jobmanager/tests/models/test_blocks.py
This PR fixes several issues related to Careers pages in Wagtail:
- Job listing page view was being passed invalid request arguments.
- Links in job listing table were hardcoded to www on content.
- Links in job listing list were hardcoded to www on content.
- Feature flag fallback view doesn't take original request parameters.
- Use relative URLs in job listing list and table.
- Load a production database.
- Set the `WAGTAIL_CAREERS` flag on both content and localhost.
- Publish all careers pages under "About".
- Run `python cfgov/manage.py runscript migrate_job_pages` to migrate job listing pages over.
- Add a `JobListingTable` to the "Current Openings" page.
- Add a `JobListingList` to the "Careers" page.
- Load those two pages; you should see no jobs because none have been published. …
=> 3.11 wagtail jobs fixes

requirements/optional-private.txt
The 1.5 release of Picard doesn't have a v in the tag name.
- Remove the v in the Picard 1.5 tag.
=> There's no v in the Picard 1.5 tag

CHANGELOG.md, requirements/optional-private.txt
Update to picard 1.5.1, which is a bugfix release addressing missing files in the package.
-
-
-
-
- @willbarton
-
-
=> Bump picard to 1.5.1

CHANGELOG.md, gulp/tasks/clean.js, gulp/tasks/copy.js, gulp/tasks/docs.js, gulp/tasks/images.js, gulp/tasks/lint.js, gulp/tasks/styles.js, gulp/tasks/test.js, package.json
`gulp-load-plugins` makes it more difficult to use search to find where a particular npm module is used, since the require statement for the modules is omitted and they come through via the `plugins` variable. 
Some tasks were already not using it, so by removing it completely, there's almost the equivalent amount of code and the modules can now be found in the requires section at the top of the gulp tasks.
- Removes `gulp-load-plugins`
- Alphabetizes require statements in gulp tasks.
- `./frontend.sh` should pass.
- @chosak
=> Removes gulp-load-plugins

CHANGELOG.md, cfgov/jinja2/v1/job-description-page/index.html, cfgov/jobmanager/models/pages.py, cfgov/jobmanager/tests/models/test_pages.py
Implementation of #2500 (Fix job grade ordering) for the 4.0 branch.
- Job grades are displayed using a sorting function.
- See #2500 for testing instructions.
=> Fix job grade ordering (4.0 branch)

CHANGELOG.md, cfgov/cfgov/settings/base.py, docs/development-tips.md
Tax Time Saving has been moved to a Wagtail page, so let's stop handling it as a Sheer site.
- `tax-time-saving` removed from `SHEER_SITES` setting in `base.py`
- Deprecate the [cfpb/tax-time-saving repo](https://github.com/cfpb/tax-time-saving)
=> Remove tax-time-saving from SHEER_SITES

cfgov/v1/__init__.py, cfgov/v1/models/base.py, cfgov/v1/models/sublanding_page.py, cfgov/v1/util/filterable_list.py, cfgov/v1/util/util.py
This PR refactors the function get_form_id into the FilterableMixin class, which it needs to be called on anyway in order to produce the correct result.
- adds form_id to the FilterableMixin class
- change calls to util.get_form_id(page) into calls to page.form_id()
- no new tests required; all current tests should pass
@chosak @richaagarwal @willbarton 
The plan is to eventually replace all the weird get_whatever functions that take pages as arguments with class instance methods. These functions result in a great deal of confusing spaghetti code and logical fragmentation of the codebase.
=> refactored get_form_id into the filterable mixin class

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/table.html, cfgov/jobmanager/models/blocks.py, cfgov/jobmanager/tests/models/test_blocks.py
Hotfix to resolve issue of external-link / download link icons not displaying on tables.
- Modified `cfgov/jinja2/v1/_includes/organisms/table.html` to add `parse_links` context function.
- Add a Table block via Wagtail.
- Add a document link, via the editor, to the the table.
- Preview
- Verify that the table contains the external link.
- @schaferjh 
- @chosak
=> Fix for table block link icons

cfgov/scripts/static_asset_smoke_test.py
bs4 needs a parser, and `html.parser` is fine for this test's purposes.
- switch from `lxml` to `html.parser`
- Try running `python cfgov/scripts/static_asset_smoke_test.py -v` with the changed parser.
Smoketests have been fixed manually in Jenkins for now, so this is mop-up.
@rosskarchner @richaagarwal 
I think this is below the changelog threshold.
=> switch to html.parser to avoid jenkins dependency

CHANGELOG.md, cfgov/unprocessed/js/modules/ContentSlider.js, cfgov/unprocessed/js/modules/util/atomic-helpers.js, cfgov/unprocessed/js/modules/util/standard-type.js, gulp/tasks/docs.js, npm-shrinkwrap.json, package.json
`documentation` npm module has a large footprint. This replaces it with the usejsdoc.org module. 
- Removes `documentation` npm module.
- Adds `jsdoc` npm module.
- Adds missing `@description` tag per jsdoc warnings.
- Updates `npm-shrinkwrap.json`.
- Run `./frontend.sh`
- Run `gulp docs`
- Open `docs/scripts/index.html` in a browser.
- Could the markdown files in `/docs/` be in a subdirectory so the output of different documentation tools can be placed in there and not be lost?
=> Replace documentation with jsdoc

CHANGELOG.md, npm-shrinkwrap.json, package.json
- Removes duplicate browser-sync entry from `package.json`.
- Update `browser-sync` to version `2.17.5` from `2.11.2`.
- Update `mkdirp` to version `0.5.1` from `0.3.0`.
- Update `npm-shrinkwrap.json`.
- `gulp build` should pass.
- `gulp watch` should work.
- @sebworks 
- @virginiacc
=> Update `browser-sync` to version `2.17.5` from `2.11.2`

CHANGELOG.md, cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/test.py, requirements/base.txt
- django-htmlmin removed from middleware and dependencies.
=> Disable htmlmin 4.0

CHANGELOG.md, cfgov/cfgov/settings/test.py
The introduction of the `wagtail.tests.testapp` app for testing in #2481 broke the ability to run the [Django system checks](https://docs.djangoproject.com/en/1.8/ref/checks/) when using test settings (`cfgov.settings.test`).
Previously, running
```
$ DJANGO_SETTINGS_MODULE=cfgov.settings.test python cfgov/manage.py check
```
would produce this error:
```
File "/Users/user/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/wagtail/wagtailadmin/rich_text.py", line 56, in get_rich_text_editor_widget
editor = editor_settings[name]
KeyError: u'custom'
```
This PR copies [settings logic in Wagtail](https://github.com/torchbox/wagtail/blob/v1.6.3/wagtail/tests/settings.py#L188) that sets up an appropriate custom rich text editor for the test app, thus allowing all checks to pass.
- …
=> Fix Django system checks when using test settings

cfgov/core/tests/test_utils.py, cfgov/sheerlike/__init__.py, cfgov/v1/models/base.py
In #2471 I removed SheerLikeContext, but apparently that was premature. It still seems neccessary in order to expose the current request object to "deep" template code (like function calls that render templates that also include macros from other templates). Hopefully we can factor that sort of stuff out soon.
Also updated the breadcrumb logic to use the specific Page subclass, because Page itself doesn't have the `get_appropriate_page_version` method.
=> Fixes some bugs introduced late this week

CHANGELOG.md, npm-shrinkwrap.json, package.json
- Update `snyk` to version `1.19.1` from `1.13.2`.
- Regenerates `npm-shrinkwrap.json`.
- `npm test` should pass (and report vulnerabilities).
- @sebworks 
- @chosak 
- @contolini 
- @virginiacc
=> Update `snyk` to version `1.19.1` from `1.13.2`.

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/link-blob.html
The link blob is including an `h3` even if the `value.heading` doesn't exist causing a spacing error from our `h3+h4` rules. Updated the `heading` value to  conditionally set the `h3` only if the `value.heading` exists.
- Added a conditional statement to the link blob `heading` value
- 
- @sebworks 
- Are there tests for these link blobs I can update?
=> Fix for link blob heading spacing

CHANGELOG.md, cfgov/jinja2/v1/newsroom/press-resources/index.html
Updating newsroom page to remove Laura Van Dyke
-  Removed  Laura Van Dyke from the press resources page.
- Visit `http://localhost:8000/about-us/newsroom/press-resources/` and verify the resources are correct.
- @willbarton 
-
-
=> Updating newsroom page to remove Laura Van Dyke

cfgov/jobmanager/static/jobmanager/js/supervision.js
Hi. Looks like there was a missing semicolon in one of the JavaScript files. This has now been amended. Thank you. 
- Amended missing semicolon in cfgov/jobmanager/static/jobmanager/js/supervision.js, mitigating the possible bug risk.
=> Amended missing semicolon in supervision.js

CHANGELOG.md, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py
This PR simplifies the Akamai cache flushing logic so that a cache flush is always called on every Wagtail page publish. Previously, flushes would only be triggered by pages that were first published over a minute ago. This prevents scheduled publishing events from triggering Akamai cache flushes, which meant that publishing a child page on a schedule (like a job posting) would not force an update of its parent page (for example a list of current open jobs).
- Simplified Akamai cache flushes to always flush on page publish.
- This is difficult to test in practice. See the unit tests in `v1.tests.wagtail_hooks` (I added a few new ones to make sure that my flake8 cleanups to the credentials method didn't break anything).
- In production, schedule a new page to publish, wait for the publish …
=> Simplify publish logic to always flush Akamai cache

CHANGELOG.md, requirements/optional-private.txt
This PR bumps the version of the optional private eregs/ip repository from 1.0.2 to 1.03, the version tagged and created today.
- Eregs/ip updated to version 1.0.3.
=> Bump eregs/ip version from 1.0.2 to 1.0.3

CHANGELOG.md, cfgov/data_research/handlers.py, cfgov/jinja2/v1/_includes/conference-registration-form.html, cfgov/jinja2/v1/_includes/molecules/notification.html
4.1 branch version of #2534 Form Display Fixes by @hillaryj.
- Slight changes to form display in conference registration form.
- Updated (HTML) success message when conference registration form is submitted.
- This requires a properly configured GovDelivery environment, and a valid GovDelivery code in the form configuration. Submitting the form will properly display the success message below.
New success message:
=> Conference registration form display fixes (4.1)

cfgov/v1/forms.py, cfgov/v1/models/base.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/models/sublanding_page.py, cfgov/v1/tests/test_filterable_list.py, cfgov/v1/tests/test_filterable_list_form.py, cfgov/v1/util/filterable_list.py
This is needed because my previous Filterable refactoring (https://github.com/cfpb/cfgov-refresh/pull/2448) unintentionally** removed this functionality.
- **We need to have some way of documenting or capturing more clearly in the code the very custom functionality of the Activity Log and Newsroom pages.  The fact that the Newsroom should not include in its results anything from research reports is not obvious, and I only found this out by @schaferjh pointing it out. I tried to make it clearer in the code I'm adding here, but there are other things specific to these pages (e.g. only include results from AbstractFilterPages) that isn't immediately obvious to someone looking at the page or looking at the code.  @chosak and I have discussed that it might be better to configure this …
=> Exclude reports from showing up on the Newsroom Landing Page

CHANGELOG.md, cfgov/templates/jobmanager/technology-innovation-fellows.html
As reported in #2546 (thanks @KimberlyMunoz), styles on [the Technology & Innovation Fellowship page](http://www.consumerfinance.gov/jobs/technology-innovation-fellows/) are broken.
This is due to some legacy `STATIC_ROOT` references that didn't properly get converted over to the `static` tag.
- Replace use of `STATIC_ROOT` with `static` tag instead.
- Run a local server and navigate to [http://localhost:8000/jobs/technology-innovation-fellows/](http://localhost:8000/jobs/technology-innovation-fellows/) (after running `gulp scripts:ondemand` to generate ondemand assets). Notice that all static assets load properly.
- @cfpb/cfgov-backends @cfpb/cfgov-frontends
=> Fix broken T&I Fellowship page

CHANGELOG.md, cfgov/unprocessed/js/modules/Analytics.js, cfgov/unprocessed/js/organisms/FilterableListControls.js, test/unit_tests/modules/Analytics-spec.js
Updates to Filter Analytics to only send values on form submission. Also, modified the category to be `Page Interaction`.
- Modifed `cfgov/unprocessed/js/modules/Analytics.js` to add function which returned a dataLayer option.
- Modified `cfgov/unprocessed/js/organisms/FilterableListControls.js` to update analytics workflow.
- Visit the Blog page, enter in some criteria via the filter. The page should function as normal.
- @@kelleyholden
- @cfpb/cfgov-frontends
=> Updates to Filter Analytics

CHANGELOG.md, cfgov/jinja2/v1/events/_macros.html, cfgov/unprocessed/css/pages/event.less
Fixing missing event suite field on template.
- Fixing missing event suite field on template
- Create an Event page.
- Fill in all venue fields and preview.
- Verify that the `venue suite` field is being displayed.
- @chosak
=> Fixing missing event suite field on template

CHANGELOG.md
Get the changelog back up to date before the 4.2 tagging
=> Integrate 4.1.x releases into changelog

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/info-unit.html
Icons for file types were missing from links within info-units. Updated the macro to parse the link before priting it to the page.
- Updated the info-unit to set the link to a variable and then run that variable through the `parse_link` function.
- In Wagtail create a 25/75, 50/50, and half-width link blob. Include links with `.pdf` file extensions (they don't have to be real, just add the extension to any url).
- @Scotchester
=> Fixed file type link icons within info-units

CHANGELOG.md, cfgov/v1/models/sublanding_filterable_page.py
See GHE 452
Similar to Andy's work in https://github.com/cfpb/cfgov-refresh/pull/2558.  As of this change, ActivityLog and NewsroomLandingPage are identical except ActivityLog has "Reports" as well.
If possible, this should go in as a hotfix to 4.2.0 and be part of tonight's deploy.
To test: go to http://www.consumerfinance.gov/activity-log/ and [http://localhost:8000/activity-log/](http://localhost:8000/activity-log/) and notice that locally, we are now excluding categories like "Official Guidance" and "Final Rule" which should've never been displayed.
=> Limit Activity Log content to blog, newsroom, and reports pages

CHANGELOG.md, cfgov/v1/signals.py
See GHE 389.  Note that I am not flushing when deleting a page because I have confirmed that it will always be unpublished first.
- Can't test this locally - probably best to just see that it's working once it's in prod, since it shouldn't break anything either way. 
@schaferjh @cfpb/cfgov-backends
=> Flush Akamai when unpublishing or unsharing a page

CHANGELOG.md, cfgov/v1/models/sublanding_filterable_page.py
See https://github.com/cfpb/cfgov-refresh/pull/2563
=> Hotfix - Limit Activity Log content to blog, newsroom, and reports pages

requirements/optional-public.txt
Bumps API version to pick up security update
=> bump oah API version to 0.9.91 for security update

CHANGELOG.md, cfgov/v1/admin.py
Product owner needs better filtering/searching capability for
v1_feedback objects in the admin.
- adjusts the v1_feedback admin for usability.
=> tweak admin for feedback entries

CHANGELOG.md
Okay it turns out @richaagarwal's hotfix *is* already in master. So the changelog is in fact all that needs to be updated.
@Scotchester @higs4281
=> Updating changelog to show 4.2 hotfixes

CHANGELOG.md, cfgov/jinja2/v1/_includes/macros/video-player.html
This PR fixes a bug where videos played from a page accessed with HTTPS would continue playing even when the video module was closed.
- Use the proper (current) request scheme when including the `origin` parameter in YouTube URLs.
- Run your local server as HTTP using `./runserver.sh`.
- Create an `EventPage`. Give it a title, a start and end date (both in the past), and a YouTube embed URL (for example https://www.youtube.com/embed/cx7-2El9NxA).
- Access the page in your browser. Click the play button, let the video start playing, then hit the Close button. Observe that the video disappears and that audio stops playing.
- Restart your local server as HTTPS using `./runserver.sh ssl`.
- Access the same page (via https://localhost:8000/slug instead of http://localhost:8000/slug), and …
=> Fix unstoppable videos when playing in HTTPS

CHANGELOG.md, cfgov/jinja2/v1/_includes/macros/activity-snippets.html, cfgov/jinja2/v1/about-us/index.html, cfgov/v1/__init__.py, cfgov/v1/forms.py, cfgov/v1/models/base.py, cfgov/v1/routing.py, cfgov/v1/templatetags/activity_feed.py, cfgov/v1/templatetags/share.py, cfgov/v1/tests/templatetags/test_activity_feed.py, cfgov/v1/tests/templatetags/test_share.py, cfgov/v1/tests/test_filterable_list_form.py, cfgov/v1/util/categories.py, cfgov/v1/util/util.py
Per GHE 458: 
Currently we show "Latest Activities" on the About Us page, and they're in no particular order -- http://www.consumerfinance.gov/about-us/
We should sort them by latest date.
Because much of this logic existed in a template, I decided to do some heavy refactoring as part of this fix. There's a lot here so please take your time reviewing and ask questions if anything looks questionable.
To test, notice this behavior locally before pulling down the branch, and after, at [http://localhost:8000/about-us/](http://localhost:8000/about-us/
)
=> Refactor Activity Snippets and sort by latest 

CHANGELOG.md, cfgov/v1/migrations/0036_cfgovrendition_uniqueness.py, cfgov/v1/models/images.py, cfgov/v1/tests/models/test_images.py
Our use of a custom image rendition class `v1.models.images.CFGOVRendition` neglected to include the uniqueness constraint present on the reference rendition model [here](https://github.com/wagtail/wagtail/blob/v1.6.3/wagtail/wagtailimages/models.py#L516) and in the documentation [here](http://docs.wagtail.io/en/v1.7/advanced_topics/images/custom_image_model.html?highlight=unique_together#custom-image-models):
```py
class Meta:
unique_together = (
('image', 'filter', 'focal_point_key'),
)
```
This lack of constraint may have enabled the creation of duplicate rendition objects which caused some 500 errors when browsing images today: the rendition creation code [uses](https://github.com/wagtail/wagtail/blob/v1.6.3/wagtail/wagtailimages/models.py#L291) Django `get_or_create`, about which …
=> Add missing uniqueness constraint to CFGOVRendition

CHANGELOG.md, cfgov/v1/__init__.py, cfgov/v1/routing.py, cfgov/v1/templatetags/share.py, cfgov/v1/tests/templatetags/test_share.py, cfgov/v1/util/util.py
#2523 [moved](https://github.com/cfpb/cfgov-refresh/pull/2523/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR20) `get_page_state_url` from `v1.templatetags.share` into `v1.routing`. This avoided a circular dependency but had the unfortunate side effect of breaking use of `{% get_page_state_url %}` in non-Jinja templates (e.g. the Wagtail admin). This causes 500 errors when viewing the root Wagtail admin page with the latest production database dump:
> TemplateSyntaxError at /admin/
Invalid block tag: 'get_page_state_url', expected 'endif'
This PR moves that `get_page_state_url` method back into `v1.templatetags.share`, and resolves the circular dependency by moving a `v1.models` import into a function.
- `get_page_state_url` moved back to `v1.templatetags.share`.
- Browse local admin with a …
=> Move get_page_state_url back to v1.templatetags

CHANGELOG.md, cfgov/unprocessed/js/modules/UStreamPlayer.js, cfgov/unprocessed/js/modules/YoutubePlayer.js
The Youtube API sometimes fails to load which causes problems when accessing its video player API. This is a workaround for that issue which removes and reattaches the iframe when stopping / playing.
I also changed hardcoded `http` references to `https`. 
-  Modified `cfgov/unprocessed/js/modules/UStreamPlayer.js` to switch `http` to `https`.
-  Modifeid c`fgov/unprocessed/js/modules/YoutubePlayer.js` to attach / reattach the iframe when stopping / playing.
- Modify the `origin` property in `video-player.html`
- Visit `http://localhost:8000/about-us/the-bureau/`.
- You should be able to play and stop the video without error.
- Check the console to verify that there are no errors.
=> Fix for failing Youtube API

cfgov/cal/views.py, cfgov/legacy/views.py
This should reduce the noise and weight of PDF reactor logs.
- in the places where we set the log level, use `PDFreactor.LOG_LEVEL_FATAL` instead of  `PDFreactor.LOG_LEVEL_WARN`
=> Set pdfreactor log level to 'fatal'

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/footer.html, test/browser_tests/spec_suites/integration/footer.js
The slug for the privacy policy changed recently. This PR updates the link in the footer to the new URL.
- Update the privacy policy link in the footer
=> Update privacy link

CHANGELOG.md, cfgov/jinja2/v1/blog/blog_page.html, cfgov/jinja2/v1/newsroom/newsroom-page.html
Per GHE 457:
> The "Subscribe to RSS" buttons on the sidebar of individual newsroom or blog post pages are broken - they link to "[this-post-URL]/feed" -- see example at http://www.consumerfinance.gov/about-us/blog/be-your-familys-financial-action-hero-during-emergency and then click "Subscribe to RSS" in the sidebar.
- Add RSS subscription button to newsroom posts
- Fix blog post RSS subscription links
- Making the links absolute URLs feels a little weird but I'm unsure of an alternative. It was a relative URL hardcoded to `feed/` before so I guess this isn't that much different.
=> Fix blog and newsroom RSS feed links

cfgov/v1/forms.py
This PR fixes a problem with filterable list forms where the topics would include all possible topics, not just the topics that apply to the pages being filtered.
We may want to hotfix 4.3 with this once it's merged.
- Change the filterable list `page_ids` to come from the constructed `base_query` rather than all `CFGovPage` objects.
- Visit a BrowseFilterablePage and attempt to search for a topic that doesn't belong to any of the subpages and notice topics that have no results appear. Apply this fix and attempt the same and notice that topics with no results no longer appear.
Before, on http://www.consumerfinance.gov/policy-compliance/enforcement/actions/:
After:
=> Use the base_query to for FilterableListForm page_ids

cfgov/v1/tests/test_wagtail_hooks.py
The unit test `v1.tests.wagtail_hooks.TestFlushAkamai. test_should_flush_gets_called_when_trying_to_flush` actually tries to make an HTTP request to the server defined in environment variable `AKAMAI_PURGE_URL`, which is set by default to [the actual Akamai URL](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/cfgov/settings/base.py#L513). This doesn't actually purge Akamai (because the other settings aren't defined), but does try to make a request. This fails the test when that URL isn't accessible, and is causing some other PR Travis tests to fail.
This PR modifies that test to skip the actual call to Akamai and only test that `should_flush` gets called appropriately.
- Fix to unit test to avoid making HTTP request to Akamai server.
- All unit tests should pass.
=> Fix unit test so it doesn't try to make request to Akamai

CHANGELOG.md
Straightening out the 4.3.2 changelog section
=> move changes introduced in 4.3.2 to the 4.3.2 release section

CHANGELOG.md, cfgov/templates/jobmanager/supervision.html, cfgov/v1/tests/test_legacy_pages.py
[The legacy supervision jobs page](http://www.consumerfinance.gov/jobs/supervision/) is throwing 500 errors because of some careers cleanup in #2612.
This PR fixes use of a now-deprecated URL pattern (by hardcoding links to `/about-us/careers/`, unfortunately the best way right now to link from non-Wagtail to Wagtail pages) and also fixes static asset references.
- Replaced some outdated usage of `STATIC_ROOT` with the `{% static %}` tag.
- Replaced outdated usage of `{% url 'careers:jobs' %}` with `/about-us/careers/`.
- Run a local server and visit [http://localhost:8000/jobs/supervision/](http://localhost:8000/jobs/supervision/). Note the two links to `/about-us/careers/` and that static assets appear properly.
=> Fix broken supervision jobs page

CHANGELOG.md, cfgov/unprocessed/js/modules/ExternalSite.js
The external redirect button isn't working and there is a jQuery reference.
- Added fix for missing button event listener and removed jQuery.
- Visit the homepage ( http://localhost:8000/ ).
- Click on the `Proceed to external site` button.
=> Fixes for External Redirect

CHANGELOG.md, cfgov/v1/tests/test_s3utils.py
The use of `@moto.mock_s3` as a test case decorator was causing some problems when writing other unit tests that access the network. This PR moves the mock s3 setup from the test case decorator to the unit test `setUp` method.
See also https://github.com/spulec/moto/issues/363 for related explanation.
- Modify use of `moto.mock_s3` in unit tests.
- Run unit tests.
=> Better use of moto.mock_s3 in unit tests

CHANGELOG.md, cfgov/v1/forms.py, cfgov/v1/tests/test_forms.py, cfgov/v1/util/util.py
This PR brings in changes from #2629 (Better filterable list form date validation) as a hotfix to 4.4.
`CHANGELOG.md` has been updated.
=> 4.4.2 hotfix

requirements/optional-private.txt
Updates knowledgebase to 2.2.1
You can observe the issue on www, on a page like:
http://www.consumerfinance.gov/askcfpb/search/?selected_facets=category_exact:debt-collection
Clicking the checkboxes does not change the filter results. This is resolved in knowledgebase 2.2.1
=> Bug fix: filter links not working on English ask

requirements/optional-private.txt
I'm not sure if this is a recently introduced error, but in New Relic I noticed that hits on:
/es/obtener-respuestas/buscar
.. without any query arguments, always generates a 500. There does seem to be some traffic on that URL, so I'd like to get the fix out as another hotfix (hopefully, the last AskCFPB hotifx for a few weeks)
=> yet another knowledgebase bump

CHANGELOG.md, cfgov/jinja2/v1/about-us/the-bureau/index.html
- Added missed `block` class to a block on the about the director's page.
- `Our core functions` well on http://www.consumerfinance.gov/about-us/the-bureau/ should look unchanged.
=> Added missed block class to a block

CHANGELOG.md, cfgov/unprocessed/css/main.less
Fix for erroneously removed bureau.less file. Closes issue #2644 
- Changed `cfgov/unprocessed/css/main.less` to add in `bureau.less`.
-  Run `gulp styles`.
- Visit `http://localhost:8000/about-us/the-bureau/` and observe that the `Our work includes:` list should be stacked.
=> Fix for erroneously removed bureau.less file

requirements/optional-private.txt
- A CSS bug on AskCFPB (demonstrated below)
- For questions that exist in the database, attempts to retrieve a non-existent english or spanish answer will result in 404's, not 500's.
Here's an example URL that includes a valid Question ID, but there is no longer an associated english answer: http://www.consumerfinance.gov/askcfpb/145/what-happens-after-i-apply-for-a-loan.html
The CSS fix turns this:
Into this:
=> Update knowledgebase to 2.2.4

CHANGELOG.md
This PR updates the CHANGELOG in master for 4.5.0. Rather than untangling the 4.4/4.5 mess right now, I made the entry inclusive of 4.4.
- A new unreleased section
- Unreleased to 4.5.0
=> Update CHANGELOG for 4.5 (inclusive of 4.4)

CHANGELOG.md, requirements/optional-public.txt
This PR increases the version of the [regulations-site](https://github.com/cfpb/regulations-site) requirement to [the 2.1.5 release](https://github.com/cfpb/regulations-site/releases/tag/2.1.5), to address some [errors that can occur on invalid date redirects](https://github.com/cfpb/regulations-site/pull/821).
- `regulations-site` version bumped to 2.1.5.
=> Bump regulations-site version to 2.1.5

cfgov/v1/apps.py
This PR fixes a bug introduced in the HashedFilesMixin patterns.
- Added trailing comma
- Slight reformatting to better imply the expected structure
```
>>> from django.core.files.storage import get_storage_class
>>> get_storage_class('django.contrib.staticfiles.storage.ManifestStaticFilesStorage')()
<django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x10798fe50>
```
=> Fix hashed files pattern

CHANGELOG.md, cfgov/v1/management/commands/delete_page.py, cfgov/v1/signals.py, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py
- GHE 506
- Unpublishes & deletes a page given its slug name
- `python cfgov/manage.py delete_page --slug page-slug` 
- Grab a page's slug locally and type in the above, replacing `page-slug` as appropriate
=> Add a management command for deleting Wagtail pages

CHANGELOG.md, cfgov/v1/migrations/0044_changing_case_on_enforcement_action_category.py, cfgov/v1/util/ref.py
Fix for filter categories on the Enforcement Actions page. 
- Modified `cfgov/v1/util/ref.py` to fix case issue.
- Visit `http://localhost:8000/policy-compliance/enforcement/actions/` and expand the filter.
- Verify that the categories exist.
=> Fix for filter categories on the Enforcement actions page. 

CHANGELOG.md, cfgov/jinja2/v1/newsroom/_vars-newsroom.html
Fix for breadcrumb on Newsroom page. Closes issue #2635.
- Adds back Breadcrumb which was removed during cleanup way back in the day.
- Visit http://web.archive.org/web/20160430162311/http://www.consumerfinance.gov/about-us/newsroom/press-resources/ and verify that there is a breadcrumb.
- Visit http://www.consumerfinance.gov/about-us/newsroom/press-resources/ and verify that there is no breadcrumb. 
-  Visit http://localhost:8000/about-us/newsroom/press-resources/ and verify that its back.
=> Fix for breadcrumb on Newsroom page

CHANGELOG.md, cfgov/jinja2/v1/_includes/breadcrumbs.html, cfgov/jinja2/v1/_includes/molecules/breadcrumbs.html, cfgov/jinja2/v1/_layouts/content-base-main-first.html, cfgov/jinja2/v1/_layouts/content-base-sidebar-first.html
Removing unused breadcrumb classes. Closes issue #2639.
- Removed unused classes from the breadcrumb macros and provided sensible defaults.
1. Visit http://localhost:8000/about-us/the-bureau/about-deputy-director/.
2. Inspect the breadcrumb and note  `breadcrumb__sidebar-first` shouldn't be present.
=> Removing unused breadcrumb classes

CHANGELOG.md, cfgov/v1/wagtail_hooks.py
- GHE 505
- Disables page deletion via `/delete` POST endpoint in Wagtail admin 
- Can still delete via command line as introduced in this PR -- https://github.com/cfpb/cfgov-refresh/pull/2663
- What you see when you try to delete a page 
- Go to a page in the Wagtail admin, and add `/delete` to the path
- Confirm you see the exception
- Go back to the page and confirm it's still there
=> Disable page deletion via POST request

CHANGELOG.md, cfgov/templates/wagtailadmin/css/richtext.css, cfgov/v1/wagtail_hooks.py
When entering large blocks of information into Full Width Text Blocks, the fields become massively wide. Neither IE nor Chrome provides a horizontal scroll bar to help in navigating the field. This becomes problematic if you need to insert a new field under one that you just created and populated, as the (+) button to add a new field is far off-screen. In order to see that add button, you would have to use the keyboard to move character by character until the button was visible.
This PR places a maximum width of 1000 pixels on richtext fields.
- CSS file for richtext fields that sets a maximum width
- Before loading this branch, log into the Wagtail admin as it exists now on `master` and open the page with the ID of 4529 for editing. In the "Lending levels" area, observe how the buttons …
=> Modify richtext fields to have a max-width of 1000px

requirements/base.txt
- remove publish_eccu from requirements
=> we don't use eccu anymore

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/table.html, cfgov/v1/atomic_elements/organisms.py, cfgov/v1/tests/atomic_elements/organisms/test_organisms.py
Hotfix for key access on datatable when table is empty. Introduced in PR #2662.
- Modified `cfgov/jinja2/v1/_includes/organisms/table.html` to fix issue rendering tables when previewing. The  `to_python` method is not called when previewing, so the `has_data` property doesn't exist.
- Modified `cfgov/v1/atomic_elements/organisms.py` to add safer method for accessing dictionary keys. 
- Visit `http://beta.consumerfinance.gov/policy-compliance/rulemaking/small-business-review-panels/` and observe the error.
- Visit `http://localhost:8000/policy-compliance/rulemaking/small-business-review-panels/` and observe the table renders as expected.
=> Hotfix for key access on datatable when table is empty

CHANGELOG.md, requirements/optional-public.txt
Bump version of optional [owning-a-home-api](https://github.com/cfpb/owning-a-home-api) requirement to [v0.9.93](https://github.com/cfpb/owning-a-home-api/releases/tag/v0.9.93).
- Increase owning-a-home-api requirement to v0.9.93.
=> Update owning-a-home-api dependency to v0.9.93

CHANGELOG.md, requirements/optional-public.txt
4.6.2 hotfix: update owning-a-home-api to v0.9.93. See #2701.
=> 4.6.2: Update owning-a-home-api to v0.9.93

.travis.yml, CHANGELOG.md
This updates the version of Node used in Travis builds to v6. Odd numbered versions of Node are "progress" versions and do not have a long-term support plan, while even numbered versions are considered stable.
- https://github.com/nodejs/LTS
- https://nodejs.org/en/blog/community/v5-to-v7/
=> Use the latest version of Node v6 in Travis builds

CHANGELOG.md, frontend.sh
This PR addresses #2654 and implements @rosskarchner's suggestion in GHE#563 to checksum `package.json`, store the checksum in `$NODE_DIR/CHECKSUM`, and then only delete $NODE_DIR if the checksums don't match. This should improve the efficiency of our `frontend.sh` script.
Some quick and dirty metrics on my local machine:
Full install of all dependencies (checksum doesn't exist or doesn't match):
```
./frontend.sh  110.17s user 30.05s system 66% cpu 3:29.80 total
```
When no dependencies have changed (checksum exists and matches):
```
./frontend.sh  55.34s user 2.62s system 155% cpu 37.200 total
```
So, this cuts down the time spent installing frontend dependencies by half unless `package.json` has changed.
- Checksum package.json to avoid reinstalling dependencies that haven't changed
- …
=> Don't always delete $NODE_DIR

CHANGELOG.md, cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py
If a page has been published but not shared, its status in the Wagtail browser should say "live + draft".
- Change to status string logic to properly support live + draft (but not shared) state.
- Create a new page in the Wagtail editor and publish it. Then manually go back into the editor view and unshare it. You should see it in the browser with 'live + draft' status.
=> Correctly show 'live + draft' status for unshared pages

CHANGELOG.md, cfgov/scripts/http_smoke_test.py
Out smoke test script always exits with 0, even with failures. This fixes that.
- Failing/timing out smoke tests return 1 not 0
=> Make sure smoke tests that fail exit with an appropriate status

CHANGELOG.md, requirements/optional-private.txt
This PR bumps the version of the internal knowledgebase repository to version ~2.2.5~ 2.2.6 (note: purposefully no 'v').
- Bump knowledgebase from v2.2.4 to ~2.2.5~ 2.2.6.
- Unit tests: `tox -e optional-private knowledgebase`.
=> Update knowledgebase requirement to 2.2.6

CHANGELOG.md, requirements/optional-private.txt
This PR hotfixes #2711 into 4.6 as a new 4.6.5 release.
- Updates the version of the knowledgebase requirement to 2.2.6.
=> 4.6.5: Update knowledgebase requirement to 2.2.6

CHANGELOG.md, requirements/optional-private.txt
This PR updates the optional (private) knowledgebase version from 2.2.6 to 2.2.7.
It also updates the CHANGELOG with missing release notes from version 4.6.5.
- Release notes for 4.6.5.
- Knowledgebase dependency bumped to 2.2.7
=> Update knowledgebase requirement to 2.2.7

CHANGELOG.md
This changelog update is based on a script that pulls the PR differences between tags. 4.6.6 was tagged from master because of the complexity of cherry-picking all the relevant commits into 4.6 and the uncertainty about interrelationships between recent build-related PRs.
=> Update CHANGELOG for 4.6.6

CHANGELOG.md
This is an update to CHANGELOG.md with release notes from 4.6.7 and 4.6.8.
=> Update CHANGELOG.md for 4.6.7 and 4.6.8

cfgov/cfgov/urls.py
We're moving "The Bureau" section to Wagtail. This PR adds a check in `urls.py` for the feature flag `WAGTAIL_THE_BUREAU`, and if it **is not enabled** the hard-coded templates will be used for all urls under "The Bureau" except for the leadership calendar. 
The leadership calendar will need to be copied into about-us/the-bureau in Wagtail before the page will work once the `WAGTAIL_THE_BUREAU` flag is set. After this, about-us/leadership-calendar can be deleted in Wagtail.
- Checks for `WAGTAIL_THE_BUREAU` in `cfgov/urls.py` for all "The Bureau" urls.
- Use a recent database dump that has the Wagtail work on "The Bureau" pages.
- Visit the following URLs to confirm they work *without the feature flag set*:
- http://localhost:8000/about-us/the-bureau/
- …
=> Add feature flag check for WAGTAIL_THE_BUREAU

requirements/optional-public.txt
Update to pick up automated data collection.  
Also drops the 'v' from the oah-api release tag
=> bump oah-api release to 0.9.94

CHANGELOG.md, cfgov/legacy/static/nemo/_/c/v1-nonresponsive-footer.css, cfgov/unprocessed/css/cf-theme-overrides.less
Removing custom grid variables. We should be using the grid variables which are defined in Capital framework. 
- Modified `cfgov/unprocessed/css/cf-theme-overrides.less` to remove custom grid variables.
- Run `gulp styles`.
- Browse the site at various breakpoints. 
- PRs will need to be created for the sites that require the on-demand footer / header.
=> Removing custom grid variables

cfgov/jinja2/v1/events/_macros.html
Fix for agenda times on event page.
- Modified `cfgov/jinja2/v1/events/_macros.html` to allow for empty start / end times on event agenda page. 
- Visit `http://localhost:8000/admin/pages/3759/edit/` and remove an end date for any agenda item.
- Preview and be amazed.
- `{% if bound.start_time is not none % }` doesn't work. I had to cast to string.
=> Fix for empty agenda times on event page.

npm-shrinkwrap.json
Fix for shrinkwrap to remove optional dependencies
- Regenerated the `npm-shrinkwrap.json` file using `npm install --no-optional`.
- I have no way of telling you how to test this PR. This is an indication of the quality of shrinkwrap process.
=> Fix for shrinkwrap to remove optional dependencies

cfgov/cfgov/settings/base.py
Right now, even though www.consumerfinance.gov is served via HTTPS, automatically generated URL's still use plain old HTTP. This is because the final leg of the request is not encrypted. We need to send Django a hint about the true protocol of the request.
Django let's us send that hint using the SECURE_PROXY_SSL_HEADER setting. By configuring with a header name and expected value, we can tell Django that generated URL's should include https.
https://docs.djangoproject.com/en/1.8/ref/settings/#secure-proxy-ssl-header
We've gone with the example provided in the Django docs:
` SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')`
We will need to configure the CDN to include the X-FORWARDED-PROTO header.
- added SECURE_PROXY_SSL_HEADER to cfgov/settings/base.py
start the django …
=> Recognize requests proxied from HTTPS

requirements/optional-public.txt
Bumping Retirement version to 0.5.5
- Modified `requirements/optional-public.txt` to bump the version to 0.5.5.
- Install pip optional dependencies.
- Visit `https://www.consumerfinance.gov/retirement/before-you-claim/`.
- Verify that the site works as expected.
=> Bumping Retirement version to 0.5.5

requirements/optional-public.txt
This PR bumps the optional [regulations-site](https://github.com/cfpb/regulations-site) requirement from release 2.1.5 to [2.1.6](https://github.com/cfpb/regulations-site/releases/tag/2.1.6).
- Increases regulations-site version from 2.1.5 to 2.1.6.
- Run 
```sh
$ pip install git+https://github.com/cfpb/regulations-site.git@2.1.6#egg=regulations
```
from command-line without a local snyk setup and verify that install succeeds.
=> Bump regulations-site from 2.1.5 to 2.1.6

cfgov/cfgov/settings/base.py
This is basically an extension of #2747
On beta, I've got the X-Forwarded-Proto header working correctly, *mostly*. The (small) problem is that URL's include the port, which seems is kind of sloppy.
For example, the og:url on a blog post looks like:
https://beta.consumerfinance.gov:443/about-us/blog/cfpb-ombudsmans-office-2016-annual-report/
This is because (for whatever reason) when the CDN requests documents from the origin, the Host: header contains the port number, like beta.consumerfinance.gov:443
By enabling USE_X_FORWARDED_HOST, we can configure the CDN to send a X-Forwarded-Host header with our chose value (which will just be beta.consumerfinance.gov and www.consumerfinance.gov), and Django will respect that when generating URL's
The relevant Django logic is here: …
=> enable USE_X_FORWARDED_HOST

requirements/optional-private.txt
This PR updates the version of the optional private repository agreement_database from v2.2.5 to v2.2.6.
- Bump agreement_database from v2.2.5 to v2.2.6.
- Run unit tests in cfgov-refresh with:
```sh
$ pip install git+https://private.repo/CFPB/agreement_database.git@v2.2.6#egg=agreement-database
$ PYTHONPATH=cfgov DJANGO_SETTINGS_MODULE=cfgov.settings.test python cfgov/manage.py test agreements
```
- Test locally with a production data dump and visit http://localhost:8000/credit-cards/agreements/.
=> Bump agreement_database from v2.2.5 to v2.2.6

cfgov/jinja2/v1/_includes/organisms/snippet-list.html, cfgov/v1/migrations/0053_orderable_resource_snippets.py, cfgov/v1/migrations/0055_orderable_resource_snippets.py, cfgov/v1/models/snippets.py, cfgov/v1/tests/models/test_snippets.py
Snippet list output has previously been in a random order. This sets the default order to alphabetical by title, and enables the ability to order them manually by using the Resource snippet's `order` field.
- Adds `order` field to Resource snippet model
- Uses the `order` field to sort the output of a Snippet List module, defaulting to (and breaking ties with) alphabetical by title.
- Updates `help_text` for Resource's `tags` field.
1. Pull fork
1. Create some Resource snippets with various titles, if you don't have any yet. Don't give them an order value, but do give them a tag you can use in the Snippet List.
1. Create a Snippet List on a browse page using the name of the tag you gave to the snippets in the above step.
1. View the page and confirm that they are sorting alphabetically by …
=> Make Resource snippets orderable and update Snippet Lists to sort by order, then title

cfgov/legacy/views.py
- When PDFReactor reaches back to the web server to get the HTML to render, it shouldn't depend on request.scheme
=> PDFReactor scheme should always be http

cfgov/jinja2/v1/_includes/organisms/chart.html
Updates hard-coded date for the CCT monthly data sets. The footnote for each graph should say "December 2016" once the latest date goes live (slated for Tuesday 2/21).
=> update latest data month from november to december

cfgov/jinja2/v1/events/_event-detail.html, cfgov/unprocessed/css/video-player.less, cfgov/unprocessed/js/modules/UStreamPlayer.js, gulp/config.js, npm-shrinkwrap.json, package.json
Fixes for Ustream invalid certificate and Event copy changes
- Modified `cfgov/jinja2/v1/events/_event-detail.html` to fix copy changes. 
- Modified `package.json` to add ustream embed module. 
- Modified `cfgov/unprocessed/css/video-player.less`  to fix hierarchy bug.
- Modified `gulp/config.js` to add reference to static file. Static ustream file will be hot loaded when needed.
- run `npm install`
- run gulp build
- Modify the date on a future event to make it a live event.
- Enter `https://www.ustream.tv/embed/10414700?html5ui` as the live stream URL.
- Visit the `http://localhost:8000/about-us/events/`
- Select the event that should be live.
- Hit play and watch the event without any errors.
-
-
=> Fixes for Ustream invalid certificate and Event copy changes

cfgov/jinja2/v1/_includes/macros/video-player.html, cfgov/unprocessed/js/modules/UStreamPlayer.js, cfgov/unprocessed/js/modules/util/email-popup-helpers.js
Due to https issues we need to write some code to redirect users to the Ustream page. 
- Modified `cfgov/jinja2/v1/_includes/macros/video-player.html` and `cfgov/unprocessed/js/modules/UStreamPlayer.js` to redirect users to Ustream when the play button is clicked.
- Modified `cfgov/unprocessed/js/modules/util/email-popup-helpers.js` to fix linting error.
- Visit `http://localhost:8000/about-us/events/winter-2017-consumer-advisory-board-meeting-washington-dc/`
- Click the play button
- You should be redirected to the CFPB Ustream channel.
-
-
=> Fix for Ustream redirect on winter-2017-consumer-advisory-board-meeting-washington-dc/

cfgov/jinja2/v1/_includes/molecules/related-content.html, cfgov/unprocessed/css/organisms/full-width-text-group.less
Testing half-width related content within Full text width organism
- Modified `cfgov/jinja2/v1/_includes/molecules/related-content.html` to test `related link` molecule at half-width.
- Modified `cfgov/unprocessed/css/organisms/full-width-text-group.less` to add flag.
- Enable the `RELATED-LINKS-TEST` flag.
- Edit an existing blog page.
- Add the full-width text organism to the page.
- Add the `related-content` molecule to the page. 
- Enter the necessary fields.
- Publish and visit the page. 
- Verify the `related-content` molecule is at half width.
-
-
=> Testing half-width related content within Full text width organism

cfgov/templates/wagtailadmin/pages/create.html, cfgov/templates/wagtailadmin/pages/edit.html
Our custom Wagtail admin templates were missing a change [introduced in Wagtail 1.8](https://github.com/wagtail/wagtail/commit/2a76a30e7bd5b04941469d2498dfbda16364a131) that altered how breadcrumbs were rendered.
This PR restores breadcrumbs on Wagtail create/edit views.
- Modified our custom `create.html` and `edit.html` admin templates to properly render breadcrumbs.
- Run a local server and try creating and editing a page. Feast on delicious breadcrumbs.
=> Restore breadcrumbs to Wagtail create/edit views

cfgov/jinja2/v1/_includes/molecules/image-inset.html, cfgov/unprocessed/css/organisms/full-width-text-group.less
Fix for spacing issue on image inset
- Modified `cfgov/jinja2/v1/_includes/molecules/image-inset.html` to remove code that wasn't doing anything. 
- Modified `cfgov/unprocessed/css/organisms/full-width-text-group.less` to fix issue with margin spacing.
- Add an `image-inset` molecule to the full-text width organism.
- Add `content` molecule above the image inset.
- Add a some some paragraphs to the `content` molecule just added.
- Add `content` molecule below the image inset.
- Add a some some paragraphs to the `content` molecule just added.
- Publish and verify the spacing is correct above the paragraph adjacent to the image.
-
=> Fix for spacing issue on image inset

requirements/base.txt
[wagtail-sharing](https://pypi.python.org/pypi/wagtail-sharing/0.3) is on PyPI! (with an ugly README, sadly...) We should install it from there instead of from a GitHub URL.
- `requirements/base.txt` now includes `wagtail-sharing==0.3`.
- Fix the README on PyPI.
=> Install wagtail-sharing from PyPI

cfgov/scripts/archive_events.py
Our recent effort to `flake8` everything introduced unicode `...` characters into the source file for `cfgov/scripts/archive_events.py`, which causes that script to fail when run using `manage.py runscript`.
This PR replaces those characters with regular `...` strings.
- Convert unicode `...` characters to regular `...` strings.
- `python cfgov/manage.py runscript archive_events`.
=> Remove unicode characters from Python source

cfgov/jinja2/v1/_includes/organisms/full-width-text.html
Fix for alt tag text for the full width media molecule
- Modified `cfgov/jinja2/v1/_includes/organisms/full-width-text.html` to fix issue with using the image title instead of the image alt tag.
- Create a browse page.
- Add a `full width text organism` to the page.
- Add the `media` module to the page.
- Add an image.
- Insert `Image title` as the title.
- Preview and inspect the image in your browsers console.
- The image alt tag should be `Image title`.
- Edit the page in Wagtail.
- Edit the image you inserted earlier.
- Enter `Image alt` in the alt field.
- Preview and inspect the image in your browsers console.
- The image alt tag should be `Image alt`.
- I'll feature flag this if necessary.
-
=> Fix for alt tag text for the full width media molecule

requirements/base.txt
wagtail-flags 1.0.1 includes a fix for admin template inclusion. Bumping the version will fix our problems with our flags admin.
- wagtail-flags to 1.0.1
=> Bump wagtail-flags version to 1.0.1

requirements/base.txt
Wagtail-Flags 1.0.2 fixes an issue with admin site url resolution when flags exist with dashes (and other special characters. 
- Bump wagtail-flags to 1.0.2.
=> Bump wagtail-flags to 1.0.2

cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/events/index.html, cfgov/jinja2/v1/newsroom/index.html, cfgov/jinja2/v1/newsroom/press-resources/index.html, cfgov/unprocessed/css/organisms/prefooter.less
Convert pre-footer to atomic structure
- Modified files to convert them to the proper atomic structure. The pre footer currently sets it's own margin but I'll fix that at a later date.
- Run `gulp styles`
- Visit `http://localhost:8000/about-us/payments-harmed-consumers/` and verify the pre-footer works as expected.
=> Convert pre-footer to atomic structure

npm-shrinkwrap.json, package.json
This updates (and `npm shrinkwrap`s) the `cfpb-chart-builder` package to version 1.1.5.
- Updates `cfpb-chart-builder` to version 1.1.5
=> Updates cfpb-chart-builder to 1.1.5

cfgov/v1/util/util.py
Removing unneeded Leadership Calendar code
- Restart your server
- Visit `http://localhost:8000/about-us/the-bureau/leadership-calendar/` and verify that the navigation items work.
=> Removing Leadership Calendar code

cfgov/cfgov/settings/local.py, cfgov/cfgov/urls.py, docs/development-tips.md, requirements/local.txt
This PR adds the ability to enable [Django Debug Toolbar](https://django-debug-toolbar.readthedocs.io/en/stable/) for local development, which makes it easier to debug things like SQL queries, settings, template variables, and HTTP headers.
The toolbar is only supported when running locally using `cfgov.settings.local`, and only when the environment variable `ENABLE_DEBUG_TOOLBAR` is defined, e.g.
```sh
$ ENABLE_DEBUG_TOOLBAR=1 ./runserver.sh
```
~~Note that before using this for the first time on a new or restored database you will have to set up the required DB tables~~
- Added settings for Django Debug Toolbar to `settings.cfgov.local`.
- Added documentation for Django Debug Toolbar to development manual.
Homepage:
New documentation:
=> Optionally enable Django Debug Toolbar for local development

npm-shrinkwrap.json, package.json
This commit reverts `cfpb-chart-builder` to version 1.1.4 and npm shrinkwraps it.
We aren't quite ready to go ahead with the data changes that go with version 1.1.5, so we're reverting it for now.
- Reverts `cfpb-chart-builder` back to version 1.1.4
=> Reverts cfpb-chart-builder to v1.1.4

cfgov/jinja2/v1/_includes/molecules/related-content.html, cfgov/unprocessed/css/organisms/full-width-text-group.less
Updating CSS for the related links molecule with the full width organism
-
-
- Modified `cfgov/jinja2/v1/_includes/molecules/related-content.html` to remove the feature flag code.
- Modified `cfgov/unprocessed/css/organisms/full-width-text-group.less` to add margin to the related links molecule and cap the width;
- Visit `http://localhost:8000/about-us/blog/buying-home-first-step-check-your-credit/` and observe the width.
- <img width="828" alt="screen shot 2017-03-10 at 6 56 36 pm" src="https://cloud.githubusercontent.com/assets/1696212/23817722/52318f22-05c3-11e7-9033-5711feb3c62a.png">
-
-
=> Updating CSS for the related links molecule with the full width organism

cfgov/unprocessed/css/enhancements/layout.less
Design fix for Email Signup on Blog
- Modified `cfgov/unprocessed/css/enhancements/layout.less`
- Edit an existing blog page in Wagtail.
- Add an email signup organism to the blog. 
- Verify that the sign-up width doesn't exceed the 670px.
-
=> Design fix for Email Signup on Blog

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Resources for Older Adults and Their Families (Educational Resources), which just launched, replaces both Information for Older Americans (Consumer Tools) and Managing Someone Else's Money (Educational Resources).
Overdue updates to the canonical URLs for Youth Financial Education and Resources for Parents (Money as You Grow) are coming along for the ride.
- Link to Information for Older Americans in the Consumer Tools menu.
- Link to Managing Someone Else's Money in the Educational Resources menu becomes Resources for Older Adults and Their Families
- Pull, run server, open menu.
=> Update mega menu links for older adults

requirements/optional-private.txt
This PR increases the optional knowledgebase requirement from version 2.2.8 to 2.2.9. This improves handling of improper POSTs to question rating forms.
- Bump knowledgebase version in `requirements/optional-private.txt`.
```sh
(cfgov-refresh) $ pip install git+https://private.repo/CFPB/knowledgebase.git@2.2.9#egg=knowledgebase
(cfgov-refresh) $ PYTHONPATH=. DJANGO_SETTINGS_MODULE=cfgov.settings.test_nomigrations python cfgov/manage.py test knowledgebase
Creating test database for alias 'default'...
applying migration wagtail.wagtailcore.migrations.0002_initial_data
applying migration wagtail.wagtailcore.migrations.0025_collection_initial_data
.................................................
----------------------------------------------------------------------
Ran 49 tests in 2.721s
OK …
```
=> Bump optional knowledgebase requirement to v2.2.9

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Adds `Credit Reports & Scores` item to megamenu
- Adds `Credit Reports & Scores` item to megamenu
- Alphabetize `Credit Reports & Scores`, `Debt Collection`, and `Prepaid Cards` items in second column under `Consumer Tools`
- Move `Sending Money Abroad` item to next column to balance column heights
- Check out branch
- Verify that `Credit Reports & Scores`, `Debt Collection`, `Prepaid Cards`,  and `Sending Money Abroad` items all appear under Consumer Tools and work as expected
=> Add credit reporting item to megamenu

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
The PR adds a link to the megamenu for the CFPB Researchers filterable page.
Note: **the pages are not live yet.** Please hold on merging this PR until they are.
- Link to CFPB Researchers in the Data & Research menu
- Pull down this branch.
- Run the server.
- Open the megamenu, and look under the Data & Research vertical.
=> Add CFPB Researchers link to megamenu

requirements/optional-public.txt
This PR increases the version of the satellite [owning-a-home-api](https://github.com/cfpb/owning-a-home-api) repository from 0.9.94 to [the 0.9.95 release](https://github.com/cfpb/owning-a-home-api/releases/tag/0.9.95).
- Bump owning-a-home-api to version 0.9.95.
=> Bump owning-a-home-api to version 0.9.95

cfgov/jinja2/v1/_includes/organisms/full-width-text.html, cfgov/unprocessed/css/organisms/full-width-text-group.less
Fix for Related Links inset within full-text-width organism
- Modified code to fix copy / paste error. 
-
=> Fix for Related Links inset within full-text-width organsim

npm-shrinkwrap.json, package.json
Re-do of #2789 - upgrading `cfpb-chart-builder` to use the new data formats from [v1.1.5](https://github.com/cfpb/cfpb-chart-builder/releases/tag/v1.1.5).
=> Chart builder 1.1.5

frontend.sh
We have a list of steps we have to go through to update npm-shrinkwrap.json when we update a frontend dependency. This moves those steps to the frontend.sh script. The new process is:
1. Update the version in package.json
2. Run `./frontend.sh shrinkwrap`.
The second step will:
1. Clean up the existing shrinkwrap and node_modules
2. Run `npm install --production`
3. Run `npm shrinkwrap`
4. Add our dependency checksum file 
- Add `frontend.sh shrinkwrap`
- Edit a depedency version number in package.json - downgrade `cfpb-chart-builder` to 1.1.4, for example
- Run `./frontend.sh shrinkwrap`
=> Update frontend.sh to create npm-shrinkwrap.json

cfgov/jinja2/v1/_includes/organisms/full-width-text.html, cfgov/unprocessed/css/organisms/full-width-text-group.less
Fix for margin-top when using the text inset
- Modified `cfgov/unprocessed/css/organisms/full-width-text-group.less` to fix spacing issue with the inset.
- Run `gulp styles`
- Add feature flag named `INSET_TEST`
- Visit `http://localhost:8000/about-us/blog/buying-home-first-step-check-your-credit/`
=> Fix for margin-top when using the text inset

cfgov/jinja2/v1/_layouts/base.html
Removing jQuery CDN from base.html
- Removing jQuery CDN from `base.html`.
- Visit `http://localhost:8000/`
- View the page source.
- Click on the link script and verify that it loaded correctly.
=> Removing jQuery CDN from base.html

.env_SAMPLE, cfgov/cfgov/settings/base.py, cfgov/v1/management/commands/delete_page.py, cfgov/v1/models/akamai_backend.py, cfgov/v1/models/base.py, cfgov/v1/signals.py, cfgov/v1/tests/models/test_akamai_backend.py, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py, requirements/base.txt
- Entire site will no longer be flushed when publishing/unpublishing, but the specific page will be
- Related: https://github.com/cfpb/cfgov-refresh/pull/2798
- Uses Akamai's Fast Purge option (takes less than a minute!)
- Only invalidates the page being modified
- `flush` function now lives on Page model instead of in `wagtail_hooks.py`
- Removed the flush call from `unshare_all_revisions` and `unpublish_all_revisions` since we will be removing that code soon anyway (yay!), as well as `configure_page_and_revision` and instead hooked it up directly to the `page_published` and `page_unpublished` signals for clarity.
- Removed `should_flush` as this used to encapsulate more complex logic, and is now (and has been) a simple settings check
- Immediate:
- Longer-term
=> Updating Akamai invalidation

cfgov/v1/util/filterable_list.py
- Currently we flush the entire site because we don't have a way to easily flush filterable pages on changes to one of their objects. Rather than invalidating the entire cache every time we publish or unpublish, it'd be great to simply lower the TTL to something reasonable (I propose 10 minutes in this PR) for pages for which we regularly need to refresh. 
- I think this allows us to move away from flushing the entire site upon publish/unpublish (PR here -- https://github.com/cfpb/cfgov-refresh/pull/2801), bearing in mind that there are other dynamic pages that might still require a manual trigger to flush the entire site (e.g. pages that live outside Wagtail, job listing pages and snippets, though for some of these we can also automate it)
- GHE 704
- GHE 634
- GHE 550
=> Set a shorter TTL on filterable list pages

README.md
This PR fixes the project README to properly link to where contributors [can file a new bug report](https://github.com/cfpb/cfgov-refresh/issues/new).
- Fix bug report link in README.
- Click the link in the README.
- Thanks to @willbarton for noticing this!
=> Fix bug report link in README

cfgov/unprocessed/js/modules/UStreamPlayer.js
Adding redirect for Ustream Live event
- Modify `cfgov/unprocessed/js/modules/UStreamPlayer.js` to add redirect to Ustream for live events.
- Create a live event via Wagtail.
- View the live event on the site.
- Click the play button; you should be redirected to Ustream.
- This redirect will be in place until we have a permanent https solution for the live events.
=> Adding redirect for Ustream Live event

cfgov/unprocessed/css/enhancements/layout.less
Capping input width within the email signup organism
- Modified `cfgov/unprocessed/css/enhancements/layout.less` to limit the width of the email signup organism. 
- Add an email signup organism to the blog
- Resize your browser ensure the width is limited to `670px` until `601px`.
=> Capping input width within the email signup organism

cfgov/jinja2/v1/_includes/macros/time.html, cfgov/jinja2/v1/_includes/macros/util/format/datetime.html, cfgov/jinja2/v1/events/_event-detail.html, cfgov/jinja2/v1/events/_macros.html, cfgov/v1/__init__.py
TLDR: This PR replaces adds Django's `localtime` template tag/filter to our Jinja2 environment and then refactors the `time.render()` and `datetime.format_time()` macros to use `localtime` for timezone handling and changes everywhere that `time.render()` was called with a separate timezone. This should maintain the existing expectations of rendering.
Longer:
A side effect [our recent effort to remove the custom sharing code](https://github.com/cfpb/cfgov-refresh/pull/2827/commits/26e53bdd4ad786436e4457d54243323099263d85#diff-8e8a3e28d46ee12516bea4f5b50bf5a4L220) is that event starting times were showing up in UTC:
This is because the `get_appropriate_page_version()` method that was removed hide a quirk of timezone handling: By always getting the latest page revision from JSON and then …
=> Refactor datetime formatting to use Django's localtime

cfgov/ask_cfpb/migrations/0005_add_category_pages.py, cfgov/ask_cfpb/models/django.py, cfgov/ask_cfpb/models/pages.py, cfgov/ask_cfpb/scripts/migrate_knowledgebase.py, cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/ask_cfpb/tests/test_hooks.py, cfgov/ask_cfpb/wagtail_hooks.py, cfgov/jinja2/v1/ask-cfpb/answer-page.html, cfgov/jinja2/v1/ask-cfpb/category-page.html, cfgov/jinja2/v1/ask-cfpb/landing-page.html, cfgov/v1/atomic_elements/organisms.py, cfgov/v1/util/ref.py, cfgov/v1/util/util.py
To replicate the Ask CFPB landing page and category-driven sub-pages, we
add the following:
- A page type for the landing page that allows full-width presentation
- A page type for category pages
- A `featured` field on the Answer model so editors can check which
answers to feature in landing-page cards
- A `featured` filter for answers in the admin
This is prep work for front-end surgeons who will recreate knowledgebase pages as living Wagtail pages.
To see this locally, you need to do the migration dance
```
./drop-db.sh
./create-mysql-db.sh
mysql -uroot v1 < ~/Downloads/production_django.sql
python cfgov/manage.py migrate
python cfgov/manage.py runscript migrate_knowledgebase
```
The new category pages are just stubs, but they're starting to look like the real thing:
This code will …
=> Add page models to implement category-based pages

requirements/base.txt
This PR simply bumps wagtail-flags to 1.0.3 for supporting flagged URL includes.
https://github.com/cfpb/wagtail-flags/releases/tag/1.0.3
- wagtail-flags to 1.0.3
=> Bump wagtail-flags to 1.0.3 for flagged URL includes support

cfgov/jinja2/v1/_includes/macros/video-player.html, cfgov/v1/migrations/0062_modifying_video_player.py, cfgov/v1/models/learn_page.py
Modifying video player for live event to allow using youtube
- Modifed `cfgov/jinja2/v1/_includes/macros/video-player.html` to determine video type solely based on the URL. 
- Modified `cfgov/v1/models/learn_page.py` validation regex and help text to acommodate allowing youtube.
- Create an event page.
- Modify the event date / times to create an live event.
- Enter in a youtube live event url (https://www.youtube.com/embed/TY8bZHo6iRg).
- Preview.
- Play the event and verify it plays, stops, and restarts correctly. Check the console for errors.
- Edit the event again in Wagtail.
- Enter in a Ustream event (https://www.ustream.tv/embed/6540154?html5ui). 
- Preview.
- Play the event, you should be redirected to Ustream to view the event. 
- Visit …
=> Modifying video player for live event to allow using youtube

cfgov/cfgov/urls.py
This PR adds a feature flag around the `/complaint` URLs. `/complaint` and its child pages are moving to Wagtail with the Mosaic changeover. This will allow us to make that change with a feature flag.
The `flagged_url` condition is a little bit backwards. If `MOSAIC_COMPLAINT` is *not enabled*, then `/complaint` is handled by the "complaint" app. If `MOSAIC_COMPLAINT` is *enabled*, it falls back on letting Wagtail handle `/complaint`.
- `MOSAIC_COMPLAINTS` feature flag for `/complaint` URLs
=> Add feature flag for Mosaic complaint launch

cfgov/v1/migrations/0063_remove_validation_from_video_player.py, cfgov/v1/models/learn_page.py
Removing validation from the video player
- Due to the link format we will need to removed the validation from video player. It can be added back at a later time.
- Create an event page.
- Modify the event date / times to create an live event.
- Enter in a youtube live event url (https://www.youtube.com/embed/TY8bZHo6iRg).
- Preview.
- Play the event and verify it plays, stops, and restarts correctly. Check the console for errors.
- Edit the event again in Wagtail.
- Enter in a Ustream event (https://www.ustream.tv/embed/6540154?html5ui). 
- Preview.
- Play the event, you should be redirected to Ustream to view the event. 
- Visit `http://localhost:8000/about-us/events/archive-past-events/` and verify the archived events play.
- 
-
-
=> Removing validation from the video player

cfgov/unprocessed/css/enhancements/tables.less
This code fixes an issue with stacking tables in small screens, forcing cells in these stacked tables to be 100% width.
- LESS code which forces cells to be 100% width when stacked on small screens. (Currently, when the cells are set to a specific width using existing CF classes, those widths naturally carry over to stacked tables on small screens. However, it's intended that stacked cells should always be 100% width.)
=> LESS fix for stacked tables on small screens

requirements/optional-public.txt
This PR bumps the version of the complaint package to 1.3.0. I also removed the leading `v` in the tag name for this version.
- complaint to 1.3.0
=> Update complaint package to 1.3.0

cfgov/unprocessed/css/molecules/call-to-action.less
Removing padding and width from CTA
- Modified `cfgov/unprocessed/css/molecules/call-to-action.less` to remove padding and width from the Call to Action molecule. This brings it back inline with our Atomic philosophy. 
- Add a Call To Action to a Sub-landing page
- Preview and verify that it has no top / bottom margin or padding.
- 
- There is essentially no margin on the CTA within the Full Width Text organism.  You will have to control spacing using the Rich Text Editor.
- Wrapping everything in a block is a mistake, if you aren't going to allow editors to control spacing for the block from Wagtail. 
-
=> Removing padding and width from CTA

.env_SAMPLE, cfgov/cfgov/settings/base.py, cfgov/v1/management/commands/invalidate_all_pages.py, cfgov/v1/management/commands/invalidate_page.py, cfgov/v1/management/commands/invalidate_single_page.py, cfgov/v1/models/akamai_backend.py, cfgov/v1/tests/models/test_akamai_backend.py
- We want to be able to invoke flushes to Akamai (both fast purge, and entire site) via Jenkins; it makes sense to have these be management commands rather than defined in the Jenkins job itself 
- We want to use token-based credentials (rather than Ross's credentials) for purging the entire site, so this adds a new env var for that endpoint. Ansible PRs are up. 
- GHE 586
=> Add management commands for Akamai flushes

cfgov/templates/find_a_housing_counselor.html
Removing the google optimize code
- I'm not sure if this is the correct one or if it's the nemo one.
=> Removing the google optimize code from the Find a housing counselor page

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/unprocessed/css/organisms/filterable-list-controls.less, cfgov/unprocessed/js/organisms/FilterableListControls.js
Removing feature flag code from Multi-select
- Modified files to remove feature flag.
- Run `gulp build`
- Goto `http://localhost:8000/about-us/blog/` 
- Enter in some topics
- Observe the Filterable List Control expands to the correct height.
- 
- The flags need to be deleted from Wagtail.
-
=> Removing feature flag code from Multi-select

cfgov/v1/wagtail_hooks.py
This commit removes a custom rich text link handler (registered against the `register_rich_text_link_handler` hook) that is obsolete after the move to [wagtail-sharing](https://github.com/cfpb/wagtail-sharing).
Compare the code being removed against [the core Wagtail `wagtail.wagtailcore.rich_text.PageLinkHander` class](https://github.com/wagtail/wagtail/blob/v1.8.1/wagtail/wagtailcore/rich_text.py#L21); removing this should have no impact on how rich text links are rendered.
Our custom code was doing a `urlsplit(page.url)` which will fail if the page URL is relative or `None`. These cases would never happen pre-wagtail-sharing because there were always multiple Wagtail Sites defined, but now (and in standard Wagtail usage) this cannot be assumed to be the case.
This restores the default …
=> Remove obsolete custom link handler

cfgov/cfgov/settings/production.py
This PR adds a rotating file log handler to our production logging that will log `INFO` to `/var/logs/django.log` with a 10MB limit and 5 file backup (this is all @chosak — I just added it and tested locally).
See GHE/CFGOV/platform/issues/182 for more context.
- Log handler to log INFO to disk for the v1 app
=> Log INFO for v1 to /var/log/django.log

cfgov/unprocessed/css/enhancements/base.less, cfgov/unprocessed/css/organisms/mega-menu.less
The body font is now in CFv4 and the overflow is related to the menu, and won't be moved to CF.
Looking for feedback on how to properly note what is and isn't in Capital Framework and whether the menu organism really is the best place for that overflow rule.
- Moved the menu related overflow rule to the menu file
- Noted the code already in CF
=> Certify CF changes for enhancements/base

requirements/optional-public.txt
This PR bumps the version of [owning-a-home-api](https://github.com/cfpb/owning-a-home-api) from 0.9.95 to [0.9.96](https://github.com/cfpb/owning-a-home-api/releases/tag/0.9.96).
- Bump owning-a-home-api dependency from version 0.9.95 to 0.9.96.
- See release notes for owning-a-home-api PRs [115](https://github.com/cfpb/owning-a-home-api/pull/115) and [116](https://github.com/cfpb/owning-a-home-api/pull/116).
=> Bump owning-a-home-api to version 0.9.96

requirements/base.txt
This PR uses the PyPI version of govdelivery and pins it to 1.0.
- Use the PyPI 1.0 release of govdelivery
=> Pin govdelivery to 1.0

cfgov/jinja2/v1/_includes/organisms/snippet-list.html
When a heading isn't included the template prints an empty ID. Emtpy IDs are invalid and should be avoided.
- Conditioned the snippet ID to only print if the heading exists.
- Fixes https://github.com/cfpb/cfgov-refresh/pull/2898#issuecomment-299468182
=> Condition the snippet ID

cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py
This commit restores behavior that was removed in #2872.
When we insert internal Wagtail page links into rich text fields, we need them to always render as relative (not absolute) so as to maintain expected behavior across sharing/production sites. This new handler makes sure all internal Wagtail page links are always rendered as relative.
See [comments in `v1.wagtail_hooks.RelativePageLinkHandler`](https://github.com/cfpb/cfgov-refresh/compare/better-link-handler?expand=1#diff-44507cc860654b805baac659b58d2c53R118) for more details.
- New `v1.wagtail_hooks.RelativePageLinkHandler` that forces relative internal links in Wagtail rich text fields.
- New unit tests cover the new handler class; to manually test locally, [create a `BrowsePage`](http://localhost:8000/admin/pages/add/v1/browsepage …
=> Always use relative internal links in rich text fields

cfgov/jinja2/v1/_includes/organisms/table.html, cfgov/templates/wagtailadmin/js/table-block.js, cfgov/v1/atomic_elements/organisms.py, cfgov/v1/tests/atomic_elements/organisms/test_tables.py
The `v1.atomic_elements.organisms.AtomicTableBlock` block provides a rich text editor in the Wagtail admin, but doesn't currently store its content in the database in the same way that the built-in
`RichTextBlock` block type does. This causes some inconsistency, for example in how internal links are rendered.
This change modifies the way that table content is stored in the database, making sure that it is first cleaned using `DbWhitelister` and then restored using `expand_db_html`, consistently with how Wagtail does it for `RichTextBlock` content. See `wagtail.wagtailcore.richtext` for reference.
This change also renames and slightly refactors the `AtomicTableInput` to `RichTextTableInput` to be more explicit about how it is intended to work. The JavaScript `initAtomicTable` method is …
=> Store rich text table cells like rich text fields

cfgov/ask_cfpb/scripts/migrate_knowledgebase.py, cfgov/ask_cfpb/tests/models/test_pages.py
This adds a hero streamfield to the migration of the  English Ask
landing page, so that editors don't have to set this up
in every environment we deploy to. The hero image is left blank for now.
Also adds tests for the AskLandingPage `get_context` and `get_template` methods.
do the migration dance and check the English landing page:
http://localhost:8000/ask-cfpb/
It won't have a hero image.
=> Include hero in migration of Ask landing page

cfgov/core/management/commands/inactive_users.py, cfgov/core/tests/test_management_inactive_users.py
This PR simply adds the Django `EMAIL_SUBJECT_PREFIX` setting to the `inactive_users` management command's email subject.
- `settings.EMAIL_SUBJECT_PREFIX` to the `inactive_users` management command's email subject
=> Add EMAIL_SUBJECT_PREFIX to the inactive user email

cfgov/unprocessed/css/enhancements/base.less
Remove base list padding rule which was added for Ask landing page lists but is causing alignment issues in `full-width-text-group`.
- List padding rule
- Add a `list__flush-left` modifier for Ask landing page lists
=> Remove list alignment rule

cfgov/v1/models/akamai_backend.py, requirements/optional-private.txt
- Picard is updated to 1.7.0
- AkamaiBackend no longer removes the values from the `params` dictionary during instantiation. That behavior proved problematic when `params` is a reference to a settings variable, and  AkamaiBackend is instantiated more than once in a python process
Try out /tasks/ in your local install. Depending on If you have all of the necessary Akamai settings configured, you might observe "purge request submitted" or "Akamai is not configured on this server" when you try to flush Akamai.
=> bump picard to 1.7.0, and small fix to AkamaiBackend

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_layouts/base.html, docs/feature-flags.md, requirements/base.txt
Adds a feature flag for A/B testing around the Google Optimize code in `base.html`.
After this PR, to conduct an A/B test we will have to add a "path" condition for the `AB_TESTING` flag in the Wagtail Admin before the optimize code snippets are available on the page being tested.
This PR depends on https://github.com/cfpb/wagtail-flags/pull/12
- Wrap the Optimize code in a feature flag.
Install that Wagtail-Flags PR from its branch:
```
pip install git+https://github.com/cfpb/wagtail-flags.git@any-instead-of-all
```
Run the server:
```
./runserver.sh
```
Then go to http://localhost:8000/admin/flags/ and add a "path" condition for `AB_TESTING` with a path served from Wagtail, visit that path and verify that the Google Optimize code is in the header.
Travis will fail on this PR until …
=> Add AB_TESTING flag for Optimize code snippets

run_travis.sh, tox.ini
This commit cleans up and simplifies the list of available tox environments in `tox.ini`. There's now a single supported main environment (`py27`) which is run with `tox` whether or not you have the `TOXENV` environment variable set.
Documentation in the `tox.ini` file now describes the following available commands:
- `tox -e fast`: run all project unit tests, use the same virtual environment as standard `tox`, don't recreate the virtualenv each time. Also uses special Django settings that skip unneeded migrations.
- `tox -e acceptance`: use the same virtualenv but run browser tests instead of Python unit tests. Also skips unneeded migrations.
- `tox -e acceptance-fast`: same as `acceptance`, but don't recreate the virtual environment each time.
- `tox -e optional`: using a separate …
=> Tox environment cleanup

refresh-data.sh
With this commit, invoking the refresh-data script without any arguments will download the latest DB dump for you (if CFGOV_PROD_DB_LOCATION is defined).
```sh
export CFGOV_PROD_DB_LOCATION=http://<our-secret-location-check-ghe>/production_django.sql.gz
./refresh-data.sh
```
It should download `production_django.sql.gz` and then do the normal MySQL import process.
Running `./refresh-data.sh` without any arguments and without CFGOV_PROD_DB_LOCATION defined will show some help text.
=> Add DB dump download feature to refresh script

cfgov/cfgov/settings/base.py, requirements/optional-public.txt
This PR removes the MOSAIC_CCDB feature flag from configuration and updates the complaint app to 1.3.3.
- `MOSAIC_CCDB` feature flag
- complaint to 1.3.3
=> Remove MOSAIC_CCDB flag and update complaint to 1.3.3

cfgov/legacy/views/housing_counselor.py
This PR fixes an issue with accessing a local django-hud API using the request's hostname and port.
In theory using `request.build_absolute_uri` should work but it can fail if, for example, DNS resolution doesn't work as expected. This breaks behavior when running with the Django development server.
- Always connect using `localhost`.
=> Always connect to the django-hud API using localhost

cfgov/legacy/views/housing_counselor.py
Followup to https://github.com/cfpb/cfgov-refresh/pull/2935 -- `request.build_absolute_uri` doesn't work properly on deployed infrastructure so we have to use `localhost` as a workaround.
This unfortunately breaks local rendering of PDFs.
=> Always use localhost when rendering HUD PDFs

cfgov/legacy/views/housing_counselor.py
PDFReactor doesn't play well with unicode values for the license key.
This fixes the removal of [this line](https://github.com/cfpb/cfgov-refresh/commit/64f89b07cd6cceae3d4c53bbb0a9910008523271#diff-ce8b16726af60f2157fbb75fb8b61a7cL111) in #2924. When we pass the license key to PDFReactor, we need to make sure it's of type `str`.
- Cast PDFReactor license key to `str`.
=> Correct improper use of unicode PDFReactor license key

cfgov/cfgov/settings/test.py, cfgov/cfgov/test.py
The current test settings (`cfgov.settings.test` and related modules) override `settings.LOGGING` with an empty dict. This causes warning statements from the logging system if any logging statements are called.
This change was introduced in 59a9e5500d71ca25b69a6d2349d22c69cd0ce6a6. At a later date, in 5a80a5aface1852f1d5838d4db1ddb47cb51be79, the unit test runner (which is now also used by acceptance tests) was also changed to disable non-critical logging via `logging.disable(logging.CRITICAL)`.
This commit alters the acceptance test runner so that is also uses this method to disable non-critical logging, rather than just removing all logs. This prevents logging messages in the test output while still
avoiding warnings if loggers are invoked.
- `cfgov.settings.test` no longer removes all …
=> Disable logging below CRITICAL during acceptance tests

.travis.yml, config/environment.js, gulp/tasks/test.js, run_travis.sh, test/browser_tests/conf.js, test/browser_tests/default-suites.js, tox.ini
This commit adds the running of browser tests to our TravisCI integration, using the headless mode of Google Chrome. Currently this requires a custom installation of `google-chrome-beta` (version 59)
although this functionality should be coming to the stable release soon.
The various Protractor-related files have been modified to look for a `GOOGLE_CHROME_BINARY` environment variable; if this is set, running the browser tests (using `tox -e acceptance` or `gulp test:acceptance`) will try to invoke that path in headless mode.
Note: this is a suboptimal way to configure that headless mode is desired, but I've punted on a better way pending some ongoing discussions with @sebworks about a larger refactor of Protractor config.
To test locally on MacOS, download the beta version of Google …
=> Run acceptance tests on Travis w/headless browser

cfgov/templates/wagtailadmin/account/password_reset/confirm.html, cfgov/v1/auth_forms.py
I got tired of the message for an expired password not telling you that your password has expired and implying that simply waiting might fix it.
This also updates the button on the password reset confirmation form to be in line with standard Wagtail auth flow button styling.
- Reworded expired password error message to be helpful
- Updated password reset confirmation form button styling
I'm not sure how to fake an expired password, but here's how to see the new button styling:
1. Pull this branch
2. `./runserver.sh` if not already running
3. Go to https://localhost:8000/admin/
4. Log out if already logged in
5. Click "Forgotten it?" on the login form
6. Enter your email address and submit the form
7. View the console to see the email it _would_ be sending you
8. Copy the password reset …
=> Fix expired password message and reset password button styling

cfgov/cfgov/test.py, config/environment.js, gulp/tasks/test.js, npm-shrinkwrap.json, package.json
When I upgraded `is-reachable` to `3.0` then it broke the PSI gulp task due to API changes. This PR refactors the code to use the new API and upgrades PSI to version 3.0. 
- Modified `gulp/tasks/test.js` to use new PSI and `is-reachable` APIs. Also, switched to the `DJANGO_HTTP_PORT` variable.
- Run `gulp test:perf`
- <img width="663" alt="screen shot 2017-05-25 at 10 00 21 am" src="https://cloud.githubusercontent.com/assets/1696212/26453211/ff094b60-4130-11e7-9b42-7d8e2390180e.png">
- The JS size is due to GTM for some strange reason.
- We shouldn't have optional environment variables that gulp tasks depend upon.
=> Fix for PSI gulp task

docs/installation.md
Installation docs note contents were not included in their associated
note because their indent was not far enough in. Also, changes the note
to a warning because that’s what it is.
- Indents note contents in the installation doc so that they appear inside their associated note.
- Updates note type to warning, because that's what it is.
- To preview docs locally, first `pip install -r requirements/manual.txt`
- `mkdocs serve`
- go to http://127.0.0.1:8000/installation/ and scroll down to ES 1.7 warning.
Before:
After:
=> Fixes formatting issue in installation docs note

.env_SAMPLE, cfgov/cfgov/settings/base.py, cfgov/legacy/views/housing_counselor.py
- DJANGO_HUD_API_ENDPOINT setting, which can be populated from the
environment. The default matches what we use in production.
- a useful initial value for development is added to .env_SAMPLE
- the new setting is used to connect to the HUD API. The previous code had hardcoded "http://localhost" which doesn't work when developing on localhost, and depended on Django's URL reversing, which wouldn't work in a hypothetical future where the HUD API was running as a standalone service.
- After adding something like `export HUD_API_ENDPOINT=http://localhost:8000/hud-api-replace/` to your own .env file, (and re-sourcing it), you should be able to successfully search for zip codes at /find-a-housing-counselor/
=> Looser coupling between HUD API and code in cfgov/legacy/views/

refresh-data.sh
This is to prevent the `refresh-data` script's password prompt. The shorthand `-p` option doesn't work with blank passwords so I used the longer version.
=> Pass empty password to mysql import command

cfgov/unprocessed/css/molecules/related-posts.less, gulp/tasks/styles.js, gulp/utils/handle-errors.js
Adding exitProcess flag to the gulp error handler
- Modified `gulp/utils/handle-errors.js` to add an error handler.
- Run `gulp styles` and notice that the process exits as expected.
- Verify that the gulp error is causing the Travis builds to fail.
- 
-  :skull_and_crossbones:  **This PR has an intentional less error in order to test on Travis** :skull_and_crossbones:
-
=> Adding exitProcess flag to the gulp error handler

cfgov/unprocessed/css/organisms/featured-content-module.less
When a video was playing on smaller screens, the share buttons were being cut off. Limited the absolute positioning to only larger screens where the FCM visual is to the right of the text instead of below it.
- Limited the FCM video absolute positioning to larger screens
1. Build the assets, navigate to `about-us/the-bureau/` with the browser closed down a bit and play the video.
2. Navigate to `/consumer-tools/everyone-has-a-story/danieshia-threatened-with-jail/` with the browser closed down a bit and play the video.
Before:
After:
- I'd really like to rebuild the video player side of things, but that's far outside the scope right now.
=> Fix a layout issue in the FCM when a video plays at small screen

requirements/optional-public.txt
Push college-costs to 2.3.7 for a bug fix.
This is not critical and can ride to production any time.
=> bump college-costs to 2.3.7 for bug fix

test/browser_tests/cucumber/features/suites/wagtail-admin/publish-unpublish.feature, test/browser_tests/cucumber/step_definitions/publish-unpublish.js, test/browser_tests/cucumber/step_definitions/wagtail-admin-login.js, test/browser_tests/cucumber/step_definitions/wagtail-admin-pages.js, test/browser_tests/cucumber/step_definitions/wagtail-admin-rich-text-editor.js, test/browser_tests/page_objects/wagtail-admin-pages-page.js
This commit adds a few new acceptance tests for the following scenarios:
- A draft page isn't reachable at its slug-based URL
- A published page is reachable at its slug-based URL
- A published and then unpublished page isn't reachable at its slug-based URL
- New acceptance tests and related support classes.
1. `tox -e acceptance-fast specs=publish-unpublish.feature`
=> Acceptance tests for Wagtail publish/unpublish

gulp/tasks/styles.js
Adding back missing task which was removed when I rebased in my `gulp-bless` PR.
- Run `gulp styles`
- Verify everything looks as expected on `IE9`
- Visit the error console and verify that there are no errors.
=> Fix for missing gulp bless task

cfgov/v1/atomic_elements/organisms.py, cfgov/v1/migrations/0068_remove_cfgovrendition_filter.py, cfgov/v1/models/images.py, cfgov/v1/tests/models/test_images.py, cfgov/v1/tests/test_s3utils.py, requirements/base.txt
This PR upgrades Wagtail from v1.8.1 to v1.10rc1 (1.10 release is expected in the next week or so, marking this PR as **hold** until that time).
See release notes for these versions:
http://docs.wagtail.io/en/latest/releases/1.8.2.html
http://docs.wagtail.io/en/latest/releases/1.9.html
http://docs.wagtail.io/en/latest/releases/1.9.1.html
http://docs.wagtail.io/en/latest/releases/1.10.html
Notable changes include:
- Support for Django 1.11 and Python 3.6!
- New ability to [compare revisions](http://docs.wagtail.io/en/latest/releases/1.9.html#revision-comparisons) (see screenshot below).
- New ability to set up [many-to-many relations for pages](http://docs.wagtail.io/en/latest/releases/1.9.html#many-to-many-relations-on-page-models). I haven't looked into this much but the docs suggest …
=> Upgrade Wagtail to v1.10.1

requirements/base.txt
For some reason we get this error when trying to deploy on build:
`No matching distribution found for wagtail==1.10.1 (from -r cfgov/requirements/base.txt (line 44))`
which doesn't make sense since the package is on pypi.  I'm retrying with 1.10. If that fails too, I'll revert my PR.
=> Go back to Wagtail 1.10

test/browser_tests/cucumber/features/suites/wagtail-admin/wagtail-admin-publish-unpublish.feature, test/browser_tests/cucumber/step_definitions/application.js, test/browser_tests/cucumber/step_definitions/filterable-list-control.js, test/browser_tests/cucumber/step_definitions/multi-select.js, test/browser_tests/cucumber/step_definitions/wagtail-admin-pages.js, test/browser_tests/page_objects/wagtail-admin-pages-page.js, test/browser_tests/util/click-when-ready.js, test/browser_tests/util/screenshot.js
Tests Refactoring and minor cleanup
- Added `click-when-ready.js` utility to create a convenient method for click flows.
- Modified and renamed  `publish-unpublish.js` to make the steps more reusable. 
- Run `tox -e acceptance-fast specs=wagtail-admin-publish-unpublish.feature`.
=> Tests Refactoring and minor cleanup

requirements/optional-public.txt
This commit updates the external [django-hud](https://github.com/cfpb/django-hud) requirement from release 1.2 to release 1.3. See release details at:
https://github.com/cfpb/django-hud/releases/tag/1.3
- External django-hud release upgrade from 1.2 to 1.3.
1. All unit tests pass, see also unit tests at django-hud.
=> Update django-hud requirement to 1.3

cfgov/ask_cfpb/migrations/0003_add_answercategorypage.py, cfgov/ask_cfpb/models/pages.py, cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/jinja2/v1/ask-cfpb/category-page.html
This allows category pages to serve as the routable parent page of all
of its subcategories, allowing links to related subcategories and
eliminating the need to facet subcategories. In this way, audiences,
subcategories and categories all have their own pages to link to.
The category page template can serve both categories and subcategories, with the subcategory name taking the place of the category intro.
The subcategory slug is just appended to the category page's URL.
If you've migrated knowledgebase, you don't need to do that again. You just need to run a table migration with `python cfgov/manage.py migrate`
This sample subcategory page:  
http://localhost:8000/ask-cfpb/category-student-loans/understanding-student-loans/  
should look like this:
=> Make category pages routable to subcategories

docs/installation.md, frontend.sh
[The node_modules checksum](https://github.com/cfpb/cfgov-refresh/blob/master/frontend.sh#L84) in `frontend.sh` makes repeatedly downloading chromedriver less of an issue, so this PR removes the logic around installing protractor globally, as it may not be worth the complexity it introduces and the possibility global protractor make be outdated and break independent of changes in the codebase.
- Removes global protractor installation logic from `frontend.sh`
- Updates installation docs to reflect removal of global protractor option.
- Replaces mix of tabs and spaces with spaces.
1. Remove `node_modules`
2. Run `./frontend.sh`
3. Profit
=> Removes global protractor logic

test/browser_tests/conf.js, test/browser_tests/environment-test.js, test/browser_tests/jenkins_conf.js
- Updates `test/browser_tests/environment.js` to `test/browser_tests/environment-test.js` so that there aren't vaguely confusing imports like:
```
var environment = require( './environment.js' );
var envvars = require( '../../config/environment' ).envvars;
```
- Moves nested functions for `onPrepare` and `getMultiCapabilities` into top-level private functions and adds jsdocs.
- Updates variable syntax to use ES6 declarations.
- Fixes trivial jsdoc errors.
1. `gulp test:acceptance` should run no probs.
=> Updates environment configuration filename

npm-shrinkwrap.json, package.json
- Updates `gulp-autoprefixer` from `3.1.1.` to `4.0.0.`
1. Throw out `node_modules` and run `./frontend.sh`
2. `gulp build` should pass.
- It appears that some outside dependencies were out-of-date in npm-shrinkwrap, so that seems to include updates not related to this PR.
=> Updates gulp-autoprefixer from 3.1.1. to 4.0.0.

cfgov/v1/tests/test_filterable_list_form.py
The unit test [`v1.tests.test_filterable_list_form.TestFilterableListForm.test_filter_by_tags`](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/v1/tests/test_filterable_list_form.py#L40) (introduced in #2448) was relying on [`FilterableListForm.get_page_set`](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/v1/forms.py#L102) returning pages in a
particular order. That method returns pages ordered by `date_published` [which is a Django `DateField`](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/v1/models/learn_page.py#L48).
Two pages that are published on the same day won't necessarily always return in the same order. This commit changes this test so that it doesn't rely on any particular order.
- Refactor of unit test to avoid dependence on publishing order.
1. …
=> Fix date-dependent unit test that could break on occasion

cfgov/unprocessed/css/organisms/featured-content-module.less
The negative margin was causing the FCM to be pulled beyond the block container, which in turn caused the left hand border to be clipped on right sidebar templates. Removing the negative margin fixes this, but causes a slightly different issue of a double border on right sidebar templates. This turns out to be a rounding error, and is not something worth diving into at this exact moment due to discussion to remove the FCM to sidebar abutment. 
- Negative margin within the Featured Content Module
1. Run `./runserver.sh`
1. Navigate to `http://localhost:8000/about-us/the-bureau/`
1. Navigate to `http://localhost:8000/educational-resources/your-money-your-goals/`
=> Remove the negative margin on the FCM

cfgov/cfgov/test.py, gulp/tasks/test.js, test/browser_tests/conf.js
Modifying scripts associated with acceptance testing to pass arguments to Protractor appropriately.  It's still a dance, but I like dancing.
- Modified `cfgov/cfgov/test.py` to pass the necessary arguments to the gulp process.
- Modifed `gulp/tasks/test.js` to pass the the necessary arguments to the tox process.
1. Run `gulp test:acceptance --specs=multi-select.feature,filterable-page.feature` and verify that it works as expected.
2. Run `gulp test:acceptance --a11y`  and verify that it works as expected.
3. Run `tox -e acceptance-fast a11y` and verify that it works as expected.
3. Run any other protractor command line argument and verify that it gets passed as expected.
- 
- The tox / gulp dance is obviously a bit sub-optimal but minimal.
-
=> Modifying acceptance tests scripts to pass all the necessary arguments

cfgov/cfgov/settings/base.py, cfgov/transition_utilities/conditional_urls.py, cfgov/transition_utilities/tests/test_conditional_urls.py
Back in the days when we were transitioning to this new codebase, there was a need for to have some apps that were *enabled* (installed, accessible via Django admin, etc) but didn't have exposed URL's. This need no longer exists, and this feature further complicates the story around both feature flags and optional apps.
- LEGACY_APP_URLS and related logic and tests
=> remove LEGACY_APP_URLS and related logic and tests

npm-shrinkwrap.json, package.json
Prepares dependencies for babel-core@7.
- Update `babel-core` from `6.22.1` to `6.25.0`, which includes backported issues from babel-core@7.
- Update `babel-preset-es2015` from `6.22.0` to `6.24.1`.
- Update `babel-preset-stage-2` from `6.22.0` to `6.24.1`.
- Update `babel-loader` from `6.2.10` to `7.0.0`, which drops support for older node and webpack.
- Update `webpack` from `2.2.1` to `2.6.1`, which includes bugfixes.
1. Throw out `node_modules`
2. Run `./frontend.sh`
3. Site should build fine.
=> Update babel and webpack

.env_SAMPLE, cfgov/ccdb5/views.py, cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, requirements/optional-public.txt
This is to first integration with the [CCDB5-API](https://github.com/cfpb/ccdb5-api/) so we have access to the complaint data.
- Added index/doc_type environment variable template 
- Added basic calls from CCDB5-API
- Added repository to requirements
-
-
1. This will work after https://github.com/cfpb/ccdb5-api/pull/2 is merged
1. This assumes that you have accessed to the complaint data at this point through elasticsearch
1. Pip install `requirements/optional-public.txt` or just pip install ccdb5-api
1. Update the `COMPLAINT_ES_INDEX` and `COMPLAINT_DOC_TYPE` to the correct index and doctype
-
- 
@JeffreyMFarley @rosskarchner @willbarton @adamzarger 
cc @sephcoster
=> Integrate with CCDB5-API - very basic skeleton query

run_travis.sh
This commit modifies how Travis runs the Python unit tests, using `tox -e fast` instead of just `tox`. This skips most Django migrations (see [`cfgov.settings.test_nomigrations`](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/cfgov/settings/test_nomigrations.py)) which speeds up the tests
considerably.
Testing with full migrations has been added to the build/deploy pipeline as a replacement for this testing on Travis.
- Travis runs `tox -e fast` instead of just `tox`.
1. See Travis build!
=> Run Python tests in "fast" mode on Travis

package.json
Updates cucumber to a release from a release candidate. Major update to selenium-webdriver.
- Updates `cucumber` from `2.0.0-rc.9` to `2.3.0`.
- Updates `protractor` from `5.1.1` to `5.1.2`.
- Updates `protractor-cucumber-framework` from `3.1.0` to `3.1.2`.
- Updates `selenium-webdriver` from `2.53.3` to `3.4.0`.
1. Throw out `node_modules`
2. Run `npm install`
3. Run `gulp test:acceptance && gulp test:acceptance --a11y`
- Installation of modules gives warning `npm WARN axe-webdriverjs@0.2.0 requires a peer of selenium-webdriver@^2.46.1 but none was installed.`, because https://github.com/angular/protractor-accessibility-plugin/blob/master/package.json#L33 has outdated dependencies. However, the relevant accessibility task appears to still run as expected.
- Why is …
=> Update protractor and webdriver

cfgov/jinja2/v1/_layouts/base.html, cfgov/v1/migrations/0069_add_social_sharing_image.py, cfgov/v1/models/base.py, cfgov/v1/models/learn_page.py, cfgov/v1/tests/models/test_base.py, cfgov/v1/tests/models/test_learn_page.py
This adds a new image chooser field that populates the HTML Open Graph meta tags (which is what Facebook and Twitter use when you share a page).
The logic in our base template has been changed to:
```
IF page.social_image USE page.social_image
OTHERWISE IF page.preview_image USE page.preview_image
OTHERWISE USE default_cfpb_logo
```
I also added some logic to instruct Twitter to use large cards if the supplied social sharing image is large enough.
- Social image chooser in the settings panel of page's admin screen
- Large twitter card option
- `meta` image tag logic
- I added the field to the `CFGOVPage` class which means almost every page on the website will have it available. @ielerol @schaferjh Let me know if you think we should instead restrict it to certain page types (blog post, …
=> Add "social sharing image" image chooser to settings panel

cfgov/ask_cfpb/models/django.py, cfgov/ask_cfpb/scripts/migrate_knowledgebase.py, cfgov/ask_cfpb/scripts/publish_ask_pages.py, cfgov/ask_cfpb/wagtail_hooks.py, cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, cfgov/core/tests/test_views.py, cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/jinja2/v1/index.html, cfgov/v1/db_router.py
This puts code in place for the deployment, minus code for flagged URLs,
which will be dealt with separately.
Included:
- A fallback script for batch-deploying pages
- A fallback migration option for deploying with a set go-live date
- Making the WAGTAIL_ASK_CFPB flag an empty flag in settings so
that it can be controlled with simple admin change.
- removal of conditional code from ask_cfpb/wagtail_hooks.py
- setting up URLs so that removing knowledgebase from installed apps
will let all of the new ask-cfpb to go live.
- changes to megamenu and index to put new ask-cfpb links behind a
feature flag.
- adds ask_cfpb to the v1/dbrouter's list of cfgov apps so its tables
are shared between content and prod
If flags don't work out, we can deploy with a code push to remove knowledgebase URLs. …
=> Prep for ask_cfpb deployment

cfgov/v1/tests/models/test_base.py, cfgov/v1/tests/test_meta_image.py
Moved meta image tests into a dedicated file and added some notes.
=> Clean up meta image tests

cfgov/ask_cfpb/migrations/0004_add_ask_category_images.py, cfgov/ask_cfpb/models/django.py, cfgov/ask_cfpb/models/pages.py, cfgov/ask_cfpb/tests/models/test_pages.py
This feeds off #2952. Editors would like AskCFPB answer pages to have social media images corresponding to pages' categories. Logic has been added to pass the page's `social_sharing_image` to the template's meta tag if an image has been manually selected. Otherwise, use the page's category's image.
- Image chooser to both Answer and Category models
```
./drop-db.sh
./create-mysql-db.sh
mysql -uroot v1 < ~/Downloads/production_django.sql
python cfgov/manage.py migrate
python cfgov/manage.py runscript migrate_knowledgebase
```
1. Edit a category and add an image via the image chooser panel.
1. Load a live answer page that belongs to the above category.
1. View the page's source and look for `<meta property="og:image" content="*THE IMAGE YOU SELECTED*">`.
=> Add social media images to Ask categories

cfgov/scripts/http_smoke_test.py
For the next few days, environments may have different URL settings active for askcfpb and ask_cfpb.
Smoketests are too blunt to be useful in testing these environments, so this turns off the two URLs we test while deployment plays out.
=> turn off askcfpb smoketests while environments are in flux

cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/ask_cfpb/tests/test_views.py, cfgov/ask_cfpb/views.py, cfgov/cfgov/urls.py
This is the first of two staging steps for migrating knowledgebase
to Wagtail in production. This step prepares the content and
production servers for the migration of knowledgebase data
and pages into Wagtail, but without turning off the knowledgebase URLs.
Knowledgebase URLs should be active on Beta after this is merged (line 409 in `urls.py`), allowing us 
to confirm that current functionality will continue while we migrate data in production.
After the migration and testing, the second stage will turn off
KB URLs and switch navigation links to let Wagtail pages take over.
This also picks up a few missing tests.
=> Initial production deployment for ask_cfpb

cfgov/jinja2/v1/_layouts/base.html, config/webpack-config.js, gulp/config.js, npm-shrinkwrap.json, package.json
GTM tags and variables used across the site have had jquery references removed, so this removes it from the base template. 
- Remove universal jquery references.
1. `./frontend.sh` and check the site over. Outside apps (OAH, KBYO) should handle jquery themselves, if I understand correctly.
cc @kelleyholden
=> Remove universal jquery reference

docs/testing.md
Sauce connect links in documentation were outdated and didn't go anywhere useful.
- Updates outdated links in testing docs.
1. Updated links should go to sauce documentation.
=> Updates outdated link for sauce connect download

cfgov/jinja2/v1/_includes/organisms/email-popup.html, cfgov/unprocessed/css/organisms/email-popup.less, cfgov/unprocessed/js/modules/util/email-popup-helpers.js, cfgov/unprocessed/js/organisms/EmailPopup.js, cfgov/unprocessed/js/routes/owning-a-home/single.js
Removing jQuery from Email Popup
- Modified code to eliminate jQuery from email signup flow.
1. Delete your local storage value for `http://localhost:8000/owning-a-home/`.
2. Visit `http://localhost:8000/owning-a-home/`
3. Scroll to the bottom of the page.
4. Validate that the email signup worked as before.
=> Removing jQuery from Email Popup flow OAH landing page

cfgov/jinja2/v1/ask-cfpb/answer-page-spanish.html, cfgov/jinja2/v1/ask-cfpb/answer-page.html, cfgov/unprocessed/css/pages/ask.less
Add richtextfilter so images and videos are output correctly in Ask answer content
- Richtextfilter in answers
- Padding for media items in answers
2. Run `gulp styles`
3. Add image and video to an answer in admin, publish, and verify that media items display correctly
=> Ask CFPB: fix for answer images and videos

cfgov/jinja2/v1/_layouts/base.html, cfgov/v1/tests/models/test_base.py, cfgov/v1/tests/test_meta_image.py
In production the `image()` function in templates returns an absolute URL to the image's S3 location. In other environments it returns a relative URL. So prepending `{{ request.scheme }}://{{ request.get_host() }}` doesn't play nicely with production.
=> Keep uploaded meta image URLs relative

cfgov/ask_cfpb/models/django.py, cfgov/ask_cfpb/tests/test_views.py, cfgov/ask_cfpb/views.py, cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
This turns off knowledgebase URLs and turns on the redirects to send old
requests to the new cfgov-refresh ask_cfpb app.
Go-live also requires that the `WAGTAIL_ASK_CFPB` flag be set to True in
the admin after code is deployed, to change megamenu links.
We also pick add redirects to capture requests for legacy facet-built 
audience and tag pages.
The facet redirects give priority to category facets, then audience facets,
then tag facets. This should capture the great majority of old search links.
These legacy URLs should get redirected:  
- http://localhost:8000/askcfpb/search/?selected_facets=category_exact%3Abank-accounts-and-services 
- http://localhost:8000/askcfpb/search/?selected_facets=audience_exact%3AOlder+Americans
- http://localhost:8000/es/obtener-respuestas/buscar?selected_fac …
=> Ask cfpb go live

cfgov/sheerlike/__init__.py, cfgov/v1/tests/test_meta_image.py
This fixes some unit tests from #3036 that were breaking intermittently in a puzzling way. It turns out this is caused by how our [`SheerlikeContext`](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/sheerlike/__init__.py#L44) class (which is the default context class for Jinja templates) tries to handle and replace the context `request` object.
`SheerlikeContext` assumes that the current request is put on the local thread using [this](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/sheerlike/middleware.py#L26) middleware call, but in unit tests this doesn't always happen. Then when templates get rendered, `SheerlikeContext` tries to grab the local thread's request to stick it back in the context, but (since not every test updates this) it might be hanging around from an …
=> Don't let SheerlikeContext replace the context request.

cfgov/ask_cfpb/models/django.py, cfgov/ask_cfpb/models/pages.py, cfgov/ask_cfpb/tests/models/test_pages.py
Workaround for encoding issue for Spanish search tags
And encoding issue is preventing Spanish search tags with diacritical
marks from being found in Django `field__contains` queries and from
Elasticsearch indexing.  
This PR avoids both the `field__contains` search and
Elasticsearch in building the master list of valid tags and a mapping of tags-to-answers, 
which is more accurate than the previous method.
This code is currently running on Build (build `#763`), and can be tested there by going to a Spanish category page, seeing if accented tag links show up in the right sidebar and seeing if the tag links resolve.
http://build.consumerfinance.gov/es/obtener-respuestas/categoria-obtener-una-tarjeta-de-credito/
Any merge will overwrite Build, so it might not last long.
=> Ask spanish tag fix

cfgov/legacy/static/nemo/_/consumerstories/css/consumerstories.css, cfgov/unprocessed/css/enhancements/base.less, cfgov/unprocessed/css/enhancements/forms.less, cfgov/unprocessed/css/enhancements/media-queries.less, cfgov/unprocessed/css/enhancements/typography.less, cfgov/unprocessed/css/enhancements/utilities.less, cfgov/unprocessed/css/enhancements/vars.less, cfgov/unprocessed/css/lists.less, cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/misc.less, cfgov/unprocessed/css/molecules/global-header-cta.less, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/molecules/pagination.less, cfgov/unprocessed/css/organisms/bureau-structure.less, cfgov/unprocessed/css/organisms/featured-content-module.less, cfgov/unprocessed/css/organisms/mega-menu.less, cfgov/unprocessed/css/organisms/reg-comment.less, cfgov/unprocessed/css/organisms/secondary-navigation.less, cfgov/unprocessed/css/organisms/snippet-list.less, cfgov/unprocessed/css/pages/ask.less, cfgov/unprocessed/css/pages/event.less
Trying this workflow toward migrating to CFv4:
1. Add CF module classes to cfgov-refresh enhancements, module by module.
2. Check site against live site.
3. Once all modules are updated, update `package.json` to CFv4 and remove enhancements. 
- cf-core styles moved temporarily to enhancements.
- Updates `.webfont-*` to `.u-webfont-*` as needed for CFv4.
1. `./frontend.sh` and site should look the same as prod.
- Not sure if we want to merge this already or wait till all modules are in. I'll be opening PRs for each module that build on this one.
=> Migrate cf-core to cfv4

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/jinja2/v1/index.html, cfgov/scripts/http_smoke_test.py, requirements/optional-private.txt, tox.ini
This finalizes the retirement of knowledgebase and cleans up code needed
only for the migration.
Changes included:
- removal of knowledgebase from settings and requirements
- cleanup of urls.py to incorporate new URLs in the main pattern
- removal of tox DEPLOY_ENVIRONMENT variable
- retirement of the `WAGTAIL_ASK_CFPB` feature flag
- removal of the `WAGTAIL_ASK_CFPB` conditional code in
- `jinja2/v1/_includes/organisms/_vars-mega-menu.html`
-  `jinja2/v1/index.html`
- bump the smoketest timeout value to accommodate a slow
deployment completion. Normally the timeout is never reached, but just in case
the deployment needs a few more seconds to finish, this adds a cushion
so that the whole build doesn't fail.
These no-op cleanups should not have any effect on site.
=> Post-launch cleanup for Ask CFPB

cfgov/ask_cfpb/models/pages.py, cfgov/jinja2/v1/ask-cfpb/category-page.html, cfgov/unprocessed/css/pages/ask.less
Add notification of results count on English category page so users can tell results have changed when a subcategory is selected
- Results notification on English category pages
- Paginate results on subcategory pages
1. Check out branch and run `gulp styles`
2. Navigate to [category page](http://localhost:8000/ask-cfpb/category-auto-loans/) and verify that results notification update when subcategory is changed
=> Ask CFPB: Add category page results count notification

cfgov/scripts/test_data.py, gulp/tasks/test.js, gulp/utils/handle-errors.js, test/browser_tests/conf.js, test/browser_tests/cucumber/features/suites/default/global-search.feature, test/browser_tests/cucumber/features/suites/default/header.feature, test/browser_tests/cucumber/features/suites/default/mega-menu.feature, test/browser_tests/cucumber/features/suites/default/multi-select.feature, test/browser_tests/cucumber/features/suites/default/pagination.feature, test/browser_tests/cucumber/step_definitions/application.js, test/browser_tests/cucumber/step_definitions/global-search.js, test/browser_tests/cucumber/step_definitions/header.js, test/browser_tests/cucumber/step_definitions/mega-menu.js, test/browser_tests/cucumber/step_definitions/multi-select.js, test/browser_tests/cucumber/step_definitions/pagination.js, test/browser_tests/default-suites.js, test/browser_tests/environment-test.js, test/browser_tests/page_objects/wagtail-admin-pages-page.js, test/browser_tests/shared_objects/multi-select.js, test/browser_tests/shared_objects/pagination.js, test/browser_tests/util/index.js
Converting old acceptance tests to use new Cucumber framework
- Added files to convert old integration acceptance tests to use the new format.
-  Modified `cfgov/scripts/test_data.py` to create 11 records so that  a pagination molecule would be created on the filterable pages.
- Modified `test/browser_tests/conf.js` to exclude mobile and skip tags.
- Run `tox -e acceptance-fast` 
- Currently  not able to test the mobile scenarios.
- ~~Still need to pass tags from the command line.~~
- Need the ability to specify window size for headless chrome.
=> Converting old acceptance tests to use new Cucumber framework

cfgov/jinja2/v1/_layouts/404.html, cfgov/jinja2/v1/_layouts/500.html, cfgov/unprocessed/css/enhancements/typography.less, cfgov/unprocessed/css/meta.less, cfgov/unprocessed/css/pages/error.less
References to [`u-inline-block`](https://github.com/cfpb/capital-framework/blob/master/src/cf-core/src/cf-utilities.less#L55) can be replaced with native `display: inline-block` since the utility only adds a (now unsupported) hack for IE7 and below. We barely used it anyway. Should be deprecated in CF too I'd say.
- Replace calls to `u-inline-block` with `display: inline-block`. 
- Unused `btn__error-home` classes from the 404 and 500 pages.
1. In `urls.py` temporarily replace `template_name='test-fixture/index.html'), name='test-fixture'` with  `template_name='404.html'), name='404'`
2. Restart the server.
3. Visit `localhost:8000/test-fixture` to view the 404 page.
4. Repeat for `500.html`
5. Should appear unchanged from live site versions.
=> Remove references to u-inline-block

cfgov/cfgov/settings/production.py
Restores the disk-based logging config removed in 623a10f26ba502a6eb47a4217ff48bb0c937949b, but allows different behavior when django is being used interactively via manage.py or django-admin
- Logs INFO messages to disk, when sys.argv[0] is 'mod_wsgi'
- otherwise, those messages get logged to the console
- I'm not sure if there's a good way to test this locally, beyond manually hacking production.py to force disk logging.
=> Restore logging config, allow separate behavior when run interactively

cfgov/cfgov/settings/production.py
This is a refinement to the changes added in #3073. We were still creating the disk logger, even in situations where we don't plan to use it (interactive, CI, etc), which can create permissions issues.
=> Don't create the disk logger unless we plan to use it

cfgov/jinja2/v1/_includes/molecules/call-to-action.html, cfgov/jinja2/v1/_includes/molecules/related-content.html, cfgov/jinja2/v1/_includes/molecules/related-metadata.html, cfgov/jinja2/v1/_includes/molecules/related-posts.html, cfgov/jinja2/v1/_includes/molecules/related-topics.html, cfgov/jinja2/v1/_includes/organisms/email-signup.html, cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html, cfgov/jinja2/v1/_includes/organisms/sidebar-contact-info.html, cfgov/jinja2/v1/_includes/related-links.html, cfgov/jinja2/v1/_includes/templates/activities-feed.html, cfgov/jinja2/v1/_includes/templates/upcoming-events.html, cfgov/jinja2/v1/ask-cfpb/answer-page.html, cfgov/jinja2/v1/events/index.html, cfgov/jinja2/v1/index.html, cfgov/jinja2/v1/job-description-page/index.html, cfgov/jinja2/v1/newsroom/newsroom-page.html, cfgov/jinja2/v1/newsroom/press-resources/index.html, cfgov/unprocessed/css/enhancements/typography.less, cfgov/unprocessed/css/misc.less, cfgov/unprocessed/css/molecules/related-metadata.less, cfgov/unprocessed/css/molecules/related-posts.less, cfgov/unprocessed/css/organisms/sidebar-contact-info.less, cfgov/unprocessed/css/post.less, test/browser_tests/shared_objects/stay-informed-section.js
On the road to CFv4 migration…
- Updates `header-slug` to use `m-slug-header` syntax from CFv4.
2. Any page that has a header slug should be unchanged (though see note below).
- A template for the header slug could be created in the future, as all these instances use the same format.
- The old heading didn't have a bottom margin under the heading text, the new one does. Which is correct?
Before:
After:
=> Migrate slug header to CFv4

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
This PR removes the `MOSAIC_COMPLAINTS` feature flag used for the Mosaic launch. `/complaint` will always fall through to Wagtail now.
- `MOSAIC_COMPLAINTS` feature flag
=> Remove the MOSAIC_COMPLAINTS feature flag

cfgov/cfgov/settings/production.py
This adds a (parallel) logging configuration that utilizes the logging subsystem provided by the OS, instead of having Python and Django manage those files. This should prove more robust, since logging messages through syslog does not require any special privileges. 
If this works well, I think we should remove the 'disk' handler-- but there's no reason they can't live side-by-side until we make that call.
- a 'syslog' log handler
- a 'tagged' formatter, that adds some metadata for easier filtering
as things are right now, you should be set DJANGO_SETTINGS_MODULE=cfgov.settings.production, and do something that would write to the log. Perhaps in the django shell:
```
>>> import logging      
>>> logger = logging.getLogger(__name__)         
>>> logger.info("hey!") 
```
Unfortunately, on …
=> Add logging via syslog to production settings

cfgov/cfgov/settings/production.py
The 'disk' logger depends on the (apparently) fragile assumption that permissions won't change on the log file. In particular, it appears whenever the httpd packages is updated in RHEL6, ownership of those files is changed back to 'root'.
On Friday, we added the 'syslog' configuration that appears to be working pretty well, and depends on services provided by the operating system, instead of maintaining write-access to a particular file.
- the 'disk' logger and associated logic
=> remove disk logging, in favor of syslog

npm-shrinkwrap.json, package.json
- Updates `chai` to `4.0.2` from `3.5.0`.
- Updates `chai-as-promised` to `7.0.0` from `6.0.0`.
- Updates `cucumber` to `2.3.0` from `2.3.1`.
- Updates `jasmine-reporters ` to `2.2.1` from `2.2.0`.
- Updates `jasmine-spec-reporter ` to `4.1.1` from `3.2.0`.
- Updates `sinon ` to `2.3.5` from `1.17.7`.
1. `npm install && gulp test:unit && gulp test:acceptance` should pass.
=> Updates test dependencies

cfgov/jinja2/v1/_includes/atoms/input.html, cfgov/jinja2/v1/_includes/atoms/textarea.html, cfgov/unprocessed/css/cf-theme-overrides.less, cfgov/unprocessed/css/enhancements/typography.less
- Unused templates (redundant to some in https://github.com/cfpb/cfgov-refresh/pull/3084)
- Updates references to `micro-copy` to `a-micro-copy` and adds CSS from CF.
- Updates `@micro-copy-text` to `@micro-copy`.
Only place micro copy is currently used is on the non-live conference registration wagtail block from data and research.
1. Run `echo 'delete from django_migrations where app = "data_research"' | python cfgov/manage.py dbshell`
1. Run `python cfgov/manage.py migrate`
1. Create a browse page in Wagtail.
2. Add Conference registration form.
3. Preview the page.
micro-copy
a-micro-copy
- The text ends up larger because it is hardcoded to 14px in `micro-copy`, but uses ems in `a-micro-copy`.
=> Removes micro-copy

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_includes/organisms/table.html, cfgov/templates/wagtailadmin/css/table-block.css, cfgov/templates/wagtailadmin/js/table-block.js, cfgov/templates/wagtailadmin/table_input.html, test/browser_tests/cucumber/features/suites/wagtail-admin/wagtail-admin-sortable-tables.feature
This is step one of adding sortable tables to Wagtail. It includes the admin options, the front-end markup, and a feature flag to protect the front-end. The front-end won't work until the project has been updated to use cf-tables v4.x. When that work is complete, the feature flag should be removed.
- Added sortable code to admin template
- Added sortable code to front-end template
- Added scripting to allow user interaction and data saving
- Added feature flag to protect the rendered template until cf-tables v4.x is implemented
- Cleaned up some of the existing code to match our formatting standards.
I'm not sure how to test this programmatically, maybe a back-end dev could lend a hand? To test locally, run the site, log in to the admin, and create a table, then:
1. Select the checkbox …
=> Add the sortable table options to the Wagtail admin

cfgov/jinja2/v1/_includes/macros/category-slug.html, cfgov/jinja2/v1/_includes/organisms/featured-content.html, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/activity-log/_activity-list.html, cfgov/unprocessed/css/cf-theme-overrides.less, cfgov/unprocessed/css/enhancements/typography.less, cfgov/unprocessed/css/organisms/post-preview.less, cfgov/unprocessed/css/post.less
- `@heading__icon` and `@heading__icon__hover`.
- Unused `post_slug` class.
- Unused `@category-slug-text`, `@category-slug-hover`, `@header-slug-thin-border`, and `@header-slug-thick-border`.
- Migrates `category-slug` to `a-heading` from cfv4.
1. `./frondend.sh` and check /newsroom and /activity-log against the live site. They should be unchanged.
=> Migrate category-slug to cfv4

cfgov/cfgov/urls.py
URLs for eregs were being imported from the wrong project.
=> fixing mistaken url import for eregs

cfgov/ask_cfpb/migrations/0007_subcategory_prefixes.py, cfgov/ask_cfpb/migrations/0008_fix_verbose_name_plural.py, cfgov/ask_cfpb/models/django.py, cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/ask_cfpb/wagtail_hooks.py
Ask CFPB: Add prefixes to subcategory labels
To work around the lack of Wagtail widget helpers for many-to-many fields
(such as `filter_horizontal` and `filter_vertical`) we need to make
selections friendlier for Ask CFPB editors.
This PR adds category prefixes to subcategory __str__ representations,
plus some other helper-text improvements and code cleanup.
The [main change](https://github.com/cfpb/cfgov-refresh/blob/00e67ded9d3e57e1ae42a13bc65e16dcc3c5462a/cfgov/ask_cfpb/models/django.py#L231-L232) gives editors a way to more easily see and choose relevant subcategories:
=> Ask subcategory prefixes

docker-compose.yml, docker/docker-entrypoint-es-plugins.sh
We are using Data Format plugin for CCDB, so adding the installation instruction to the docker compose
- Add installation instructions for data-format plugin
-
-
1. Check out this branch
1. `docker-compose up`
1. Go to http://ip_for_your_elasticsearch:9200/_nodes/_all
1. You should see:
```
..."plugins":[{"name":"dataformat","version":"2.3.0","description":"This plugin provides several response formats.","jvm":true,"classname":"org.codelibs.elasticsearch.df.DataFormatPlugin","isolated":true,"site":false}]...
```
-
-
=> Add data format plugin for elasticsearch

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/unprocessed/css/enhancements/forms.less, cfgov/unprocessed/css/enhancements/typography.less, cfgov/unprocessed/js/molecules/Multiselect.js, cfgov/v1/forms.py
- Updates structure of filterable list controls to use cf-layout classes.
- Updates multiselect to work with CFv4 classes.
1. `gulp build` and visit /blog and compare the filter to the live site.
Live site:
This PR:
=> Migrate filter to CFv4

cfgov/core/tests/test_missing_migrations.py
The unit test `core.tests.test_missing_migration` was invoking the `check_missing_migrations` function and having it write to `sys.stdout`, which we don't want during unit tests. This change just fixes it so that output goes to a buffer instead.
- Unit test should invoke `check_missing_migrations` with in-memory buffer instead of `sys.stdout`.
1. Run unit tests using `tox -e fast` and note that no `"No changes detected"` message gets written to the console, unlike in the `master` branch.
=> Fix unit test that was writing to stdout

cfgov/cfgov/urls.py
Putting CCDB5-API behind CCDB5_RELEASE feature flag.  This app should only be release when the rest of the CCDB5 is ready.  This will prevent the unnecessary 500 error as we develop.
- Changed ccdb5-api url to be a flagged url under CCDB5_RELEASE
1.  Turn off CCDB5_RELEASE feature flag and see that http://localhost:8000/data-research/consumer-complaints/api/v1/ returns 404
=> Put CCDB5_API behind CCDB5_RELEASE feature flag

cfgov/cfgov/settings/production.py
```
export DJANGO_SETTINGS_MODULE=cfgov.settings.production                                                                                                                   
export STORAGE_ENGINE="SET default_storage_engine=MYISAM" 
cfgov/manage.py shell
>>> from django.conf import settings                     
>>> settings.DATABASES                                   
{'default': {'ENGINE': 'django.db.backends.mysql', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'v1', 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'UTC', 'OPTIONS': {'init_command': 'SET default_storage_engine=MYISAM'}, 'HOST': 'localhost.', 'USER': 'v1', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': 'v1', 'PORT': ''}}
```
(note the OPTIONS value)
-
-
=> Bug fix: allow us to specify default MYSQL engine when using production settings

cfgov/v1/db_router.py
- The database router now checks that  a legacy database exists, before trying to route queries to it.
=> Add missing self.has_legacy check

cfgov/legacy/static/hud/hud.css, cfgov/legacy/templates/hud/housing_counselor.html
This commit adds the standard Wagtail file download icon to the "Save list as PDF link" on the "Find a housing counselor" page. This change was suggested by @schaferjh.
It also removes some legacy link hover highlighting (suggested by @Scotchester).
- Adds PDF download link to the housing counselor results page.
- Removes custom Nemo link highlighting from housing counselor page.
1. Visit [http://localhost:8000/find-a-housing-counselor/?zipcode=18020&s3=True](http://localhost:8000/find-a-housing-counselor/?zipcode=18020&s3=True) locally and observe the PDF download icon, and that links no longer have a background color (compare against https://www.consumerfinance.gov/find-a-housing-counselor/?zipcode=18020&s3=True).
This required some hackery because this page uses the default Nemo styles …
=> Fix PDF download icon on housing counselor page

cfgov/unprocessed/css/molecules/global-eyebrow.less, cfgov/unprocessed/css/organisms/footer.less
These being relative and getting pulled into projects via the on-demand header and footer generated for cfgov-sheer-tempaltes was causing `collectstatic` to fail
- Changes relative CSS background image paths into root-relative paths
- From what I'm seeing locally, this may not be the only thing we need to do to fix the build, but let's get it going and see if the Jenkins output shows what I'm seeing locally for `collectstatic`. Maybe it's an issue particular to the local environment.
=> Make references to CSS background images root-relative

cfgov/unprocessed/js/molecules/Autocomplete.js, gulp/tasks/browser-sync.js, gulp/tasks/clean.js, gulp/tasks/copy.js, gulp/tasks/docs.js, gulp/tasks/lint.js, gulp/tasks/scripts.js, gulp/utils/handle-errors.js
- Convert remaining gulp tasks to ES6 syntax.
- Minor linter fixes.
=> Convert gulp tasks to ES6

cfgov/jinja2/v1/ask-cfpb/category-page.html
Change the way question links are built on category pages to fix broken link
- Generate question links on category page without using slugurl
2. Navigate to [first Credit card subcategory page](http://localhost:8000/ask-cfpb/category-credit-cards/applying-credit-card/) and verify that first question link works
=> Ask CFPB: Fix broken ask question link on subcategory page

.babelrc, config/environment.js, config/webpack-config.js, gulp/config.js, gulp/tasks/scripts.js, gulp/tasks/styles.js, npm-shrinkwrap.json, package.json
- `getSupportedBrowserList` function in `environment.js` for returning an array of supported browsers in a [browserlist](https://github.com/ai/browserslist) compatible format for use in the script and style build processes.
- Changes babel environment to `env` from `es2015` and `stage-2`, which then gets passed browserlist.
- Updates variables to `const.
- Removes babel presets from `.babelrc` since it's in the webpack-config.
2. `gulp styles:ondemand` should pass.
2. `gulp scripts:ondemand` should pass.
3. Ideally should be checked in the browsers we support and make sure there are no changes.
With `debug: true` set in the babel loader, this helpful output happens at build, which seems helpful to keep:
- The `'Edge >= 11'` was not in the original browser …
=> Implement global browser supported environment variable

cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py
Currently invalid `CFGOVPage` POSTs (those that don't include a proper `form_id` parameter) cause numerous 500 errors. This change makes the handling of invalid POSTs more robust. Invalid POSTs return a `400 Bad Response`, optionally via JSON if called via JSON.
All existing unit tests continue to pass and I've added a few new tests to demonstrate the better handling.
- `CFGOVPage.serve_post` has more robust handling of invalid POSTs.
1. See new unit tests.
2. Try running this command to verify that an invalid POST properly returns a 400; on `master` this will cause a 500 error.
```sh
$ curl -v -X POST -H 'REFERER: http://localhost:8000/' -H 'CSRF_COOKIE: foo' --cookie 'csrftoken=foo' -d "form_id=x&csrfmiddlewaretoken=foo" "http://localhost:8000/ask-cfpb/"
```
- This is the cause of the …
=> Better handling of invalid CFGOVPage POSTs

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/production.py, cfgov/v1/db_router.py, cfgov/v1/tests/test_db_router.py
This PR removes the legacy database routing functionality and settings. 
With the Ask CFPB migration completed the largest compelling reason for maintaining the legacy database split is gone. There is not need for the `agreements` and `comparisontool` apps to be stored in separate databases. 
This PR will be accompanied by a corresponding Ansible PR.
- `LEGACY` setting
- Legacy DB routing functionality in `CFGOVRouter`
=> Remove legacy database functionality from CFGOVRouter

cfgov/jinja2/v1/_includes/molecules/hero.html
Some of the hero images on Beta are being truncated. This is a temporary fix until we can resolve the issue through CF.
- Modified `cfgov/jinja2/v1/_includes/molecules/hero.html` to add the `background-image` cover property.
1. Add hero to page
2. Add background image to page.
3. Visit page using Chrome.
4. Verify image has the proper width.
=> Fix for hero images being truncated

cfgov/jinja2/v1/_includes/molecules/hero.html
The image doesn't need the cover property. I can't copy / paste worth a damn.
- Modified `cfgov/jinja2/v1/_includes/molecules/hero.html` to remove the cover property from the image.
=> Removing cover property from the image in the hero styles

cfgov/v1/__init__.py, cfgov/v1/tests/test_links.py
Fix for CF4 link styles in Wagtail content parser
-
-
- Modified `cfgov/v1/__init__.py` to fix add to CF4 styles to links.
1. Visit `http://localhost:8000/educational-resources/resources-for-tax-preparers/` and verify that the download links are present (shown is screenshot).
- 
-
-
=> Fix for CF4 link styles in Wagtail content parser

cfgov/jinja2/v1/_includes/organisms/table.html, cfgov/v1/tests/atomic_elements/organisms/test_tables.py
If `TableBlock` header values contain unicode characters, the logic that sticks the header value into the cell `"data-label"` attribute raises a `UnicodeEncodeError`.
This commit fixes that handling so that unicode content is properly placed in the page, and adds a regression test to cover this behavior.
- Don't use `"{0}".format(some_unicode_string)` in a Django template as the `"{0}"` part is a non-unicode string that you're trying to stick unicode characters into.
To reproduce, create a `TableBlock` and check "Stacked on mobile" and "Row header". Then enter some unicode characters into a column header and set some value in the next row. Previewing the page (or viewing a published version) should raise the exception on master but not with this fix.
Input:
Proper rendering:
- Partially …
=> Fix handling of unicode table block headers

cfgov/jinja2/v1/index.html
Figures were updated in #3159, but not the date stamp. This corrects that.
=> Update date stamp on homepage

gulp/config.js
Fix for post CF4 conversion font
- Modified `gulp/config.js` to 
1. Run `python cfgov/manage.py collectstatic --clear`
2. Run `gulp build`
3. Verify that the font directory exists in the `static_built` directory.
-
=> Fix for missing for fonts, post CF4 conversion

cfgov/cfgov/urls.py, requirements/optional-public.txt
This is to correct CCDB5 URLs and point to the latest version of CCDB5-API
- Previous URLs for CCDB5 are not correct, now setting to the right location
- Up CCDB5-API to the latest version
=> Correct the CCDB5 urls and up the version for CCDB5-API

cfgov/unprocessed/css/video-player.less
Fix for share icons on video player
- Modified `cfgov/unprocessed/css/video-player.less` to fix visual appearance of icons on video player.
1. Run gulp styles
2. Visit `http://localhost:8000/about-us/the-bureau/` and hit the play button.
Before:
After:
-
-
=> Fix for share icons on video player

cfgov/cfgov/urls.py
complaint database link was broken due to the move of CCDB4 to the new `data-research/consumer-complaints/search` URL.  Only CCDB5 should be moved to that new URL, not the current complaint database.
- Separated CCDB4 to its own URL and should remain the same URL as before
- CCDB5 should no longer need a fallback
=> Fix CCDB URLs

cfgov/jinja2/v1/_includes/snippets/reusable_text.html, test/browser_tests/cucumber/step_definitions/reusable-text-snippets.js
- Changes `header-slug` to `m-slug-header` in reusable text snippet.
1. Create a test Document detail page in Wagtail.
2. Click on the sidebar and add a Reusable Text.
3. Choose a Reusable Text, edit it to add "sidefoot heading" if absent (latest database dump appears not to have any reusable text snippets with a sidefoot heading set.
4. Preview the page.
Before
After
=> Updates deprecated header-slug

cfgov/unprocessed/css/organisms/full-width-text-group.less
Fix for image inset styling on IE11
GHE 1002
- Modified `cfgov/unprocessed/css/organisms/full-width-text-group.less` to fix issue with list when next to a floated container.
1. Run `gulp styles`
2. Add a `Full width-text-organism` to a page. 
3. Add the `Image Inset` molecule.
4. Add a image to the molecule.
5. Float the image to the left.
6. Add a content block beneath image.
7. Add a ul list to the content block, using the RTE.
8. Publish and verify that the block looks correct (using the IE 11).
Before
- 
- After
- The ol still gets clipped. We don't apply any CF styles to the Rich Text Editor lists.
-
=> Fix for image inset list styling on IE11

cfgov/jinja2/v1/_includes/molecules/image-inset.html, cfgov/unprocessed/css/molecules/inset.less, cfgov/v1/models/images.py
Fix for square image inset 
GHE/1002
- Modified `cfgov/jinja2/v1/_includes/molecules/image-inset.html` to use call method on `CFGOVRendition` model.
- Modified `cfgov/v1/models/images.py` to add orientation method and properties.
Square Image
1. Add an image inset to a page.
2. Upload a square image and verify, using Chrome dev tools, that the image has the `__square` modifier.
3. Resize browse to mobile width and verify that the padding bottom is 100%;
4. Verify that the image isn't being cropped.
Landscape Image
1. Add an image inset to a page.
2. Upload a landscape image and verify, using Chrome dev tools, that the image has the `__landscape` modifier.
3. Resize browse to mobile width and verify that the padding bottom is 56%;
Portrait Image
1. Add an image inset to a page.
2. Upload a …
=> Fix for square image within the image inset

cfgov/ask_cfpb/models/pages.py
Ask CFPB: consolidate pagination validation
Five Ask CFPB page types deliver answer sets that are paginated when
more than 20 answers are found. Each page type was individually validating 
pagination requests, introducing inconsistency and failing to make full use of
the Django paginator's validation. This PR introduces a helper function
that all pages use to validate a pagination request.
This also fixes broken pagination on Ask Audience pages, and should stop server errors 
generated by invalid pagination requests that were hitting build.
This addresses GHE issue `#1005`. Hat-tip to @virginiacc, who figured out the problem.
- page-validation function
- test for non-integer page numbers in a pagination request
Check these pages and play with pagination outside bounds (page=999) or …
=> Ask pagination fix

frontend.sh
Adding check to frontend.sh to print warning if Node 8 isn't used 
- Modifying 'frontend.sh` to add Node 8 warning.
1. Run `node -v ` to determine your version.
2. Run frontend.sh, if you aren't running `node 8` you should get a warning.
- 
-
-
=> Adding check to frontend.sh to print warning if Node 8 isn't used

cfgov/jinja2/v1/blog/blog_page.html
Fix for external links on blog page
- Fix for ` cfgov/jinja2/v1/blog/blog_page.html` for external link on blog page.
1. Visit `http://localhost:8000/about-us/blog/guides-public-service-loan-forgiveness/` and verify the links have the external link icons.
=> Fix for external links on blog page

cfgov/jinja2/v1/_includes/organisms/snippet-list.html
Fix for snippet-list link link icons
- Modified `educational-resources/library-resources/outreach-materials-to-use-in-the-library/` to fix issue rendering link icons.
1. Visit `educational-resources/library-resources/outreach-materials-to-use-in-the-library/` and verify that the link icons are present.
- 
- The spacing is a bit tight
=> Fix for snippet-list link link icons

cfgov/cfgov/settings/base.py
Required for the changes in complaints 1.4.x, which provide for enabling the "technical issues" banner at will.
- adds a new flag, 'CCDB_TECHNICAL_ISSUES', used by the complaints app
=> add a CCDB_TECHNICAL_ISSUES flag

cfgov/templates/wagtailadmin/js/table-block.js
Fixes one of the jquery deprecated load references in https://[GHE]/CFGOV/platform/issues/1006.
- Changes `load(` to `on('load'`
1. Put a console log above the line 196 in the changed file. 
2. Log into Wagtail and add a table-block.
3. open the dev console and hard reload the page and see that your console message logs.
=> Update jQuery load call

cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py
The `CFGOVPage.media` property returns a dictionary of JS files that were included by child blocks on the page. This logic had a slight bug (discovered by @jimmynotjim) where media files defined on blocks that were nested inside of a `StreamBlock` (or block descendant thereof) were not being included.
This change modifies the `CFGOVPage.media` logic to properly include `StreamBlock` children media in the same way that `StructBlock` children media is included. It also adds a couple of unit tests to
validate this behavior.
- Modifications to `CFGOVPage.media` to properly include `StreamBlock` child media files.
There's no easy way to replicate this right now without modifying an existing block to define a `class Media`; one example would be `v1.atomic_elements.organisms.AtomicTableBlock`. …
=> Properly include page StreamBlock children media

requirements/optional-public.txt
This updates `optional-public.txt` requirements to point to the latest version of the CCDB5 UI
=> Point to latest CCDB5 release

cfgov/jinja2/v1/es/es-base.html, cfgov/jinja2/v1/es/hogar/index.html, cfgov/jinja2/v1/es/nuestra-historia/index.html, cfgov/jinja2/v1/es/presentar-una-queja/index.html, cfgov/jinja2/v1/es/quienes-somos/index.html
Fix for `/es/` meta tags and minor spacing cleanup
- Modified template files to ensure each page had the proper meta tags and title.
1. Visit the `/es/` pages and view source. Compare the meta tags to those on consumerfinance.gov.
=> Fix for `/es/` meta tags and minor spacing cleanup

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Megamenu quick fix: rename `Low-to-Moderate Income` to `Economically Vulnerable Consumers` and move it to second column under `Practitioner Resources`
- Rename and move  `Low-to-Moderate Income` link
2. Verify that `Practitioner Resources` menu matches screenshot
=> Megamenu fix: Rename and move link

cfgov/cfgov/settings/base.py
This PR adds a hard-coded condition to the `BETA_BANNER` flag to always enable it when the Wagtail Site hostname is "beta.consumerfinance.gov".
- Condition on the `BETA_BANNER` feature flag
=> Add a hard-coded condition for the beta banner

cfgov/jinja2/v1/_includes/blocks/feedback.html
Addendum to https://github.com/cfpb/cfgov-refresh/pull/3216
- Converts `(Optional)` to `(optional)` in the feedback form.
- Adds `a-label_helper` class, which should be added to CF to set color of optional text. Currently this doesn't do anything.
=> Lowercase optional text in feedback component

cfgov/jinja2/v1/_layouts/content-base-sidebar-first.html, cfgov/jinja2/v1/_layouts/content-base.html
Currently the sidebar and pre-footer do not have their language set
correctly on pages with a custom language setting because they are not
within the section element that previously set the language.
- Moved the language setting from `content_main` to `content` to include the sidebar and prefooter.
I don't know of a good way to test this other than inspecting to make sure the language attribute is wrapping everything that's in Spanish on a page like http://localhost:8000/es/el-dinero-mientras-creces/la-adolescencia-y-la-juventud/
=> Move the lang attribute to the main element

cfgov/ask_cfpb/tests/test_hooks.py, cfgov/ask_cfpb/wagtail_hooks.py
The Ask CFPB editors discovered that even though some answers (imported from the old system) contained HTML tables, tables could no longer be added, and even the act of editing an answer that *had* a table would destroy them. This is because the editor only allows tags that have been included in a whitelist. This change extends the existing whitelist to include: 'table', 'tr', 'th', 'td', 'tbody', 'thead', 'tfoot', 'col',  and 'colgroup'
Thanks to @virginiacc and @higs4281 for showing me how to update the whitelist!
1. try to add a table to an AskCFPB answer, and observe that it survives being saved.
=> Extend editor whitelist to include table-related tags

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_includes/organisms/footer.html
Administrative Adjudication flag cleanup. This code has been in production long enough to remove the flag. 
- Modified code to remove the `OAA_FOOTER_LINK ` flag. 
-
=> Administrative Adjudication flag cleanup

.env_SAMPLE, cfgov/alerts/checks.py, cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, requirements/base.txt
[django-watchman](https://github.com/mwarkentin/django-watchman) is an app that lets us create a status endpoint with our own checks for system status.
- An `alerts` Python package that we'll use for alerting/monitoring/related code. Not currently a Django app.
- django-watchman dependency
- ntplib dependency
- django-watchman checks for caches, databases, and storages
- Custom watchman check for system clock drift
```shell
echo "export WATCHMAN_TOKENS=''" >> .env
pip install -r requirements/local.txt
./runserver.sh
```
Then visit http://localhost:8000/_status and http://localhost:8000/_status/dashboard.
JSON output at `/_status` looks like this:
```json
{  
"clock sync":{  
"ok":true
},
"caches":[  
{  
"api_cache":{  
"ok":true
}
},
{  
"default":{  
"ok":true
}
},
{ …
```
=> Add django-watchman and first check (for server time)

cfgov/core/static/robots.txt
This came out of the investigation of crawler errors (GHE 1015). It doesn't really provide us with any benefit for Google, etc to crawl every filter combination. Every page is accessible by paginating through the primary set of results.
- add the line `Disallow: *form-id=*` to robots.txt
=> Stop crawlers from trying filter combinations

cfgov/templates/wagtailadmin/js/table-block.js
Fix for table block on older browsers
- Modified `cfgov/templates/wagtailadmin/js/table-block.js` to remove usage of  ES5 default param code. 
(Use IE10 or an older Firefox version). 
1. Create a table block module in Wagtail.
2. Click the `Fixed-width columns` input and verify three drop-downs appear.
3. Click the `Sortable table` input and verify three drop-downs appear.
=> Fix for table block on older browsers

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py, cfgov/cfgov/settings/mysql_mixin.py, cfgov/cfgov/settings/production.py
This commit cleans up how MySQL database configuration is defined as centralizes it into a single Python module, `cfgov.settings.mysql_mixin`. This same mixin is included in both `settings.local` and `settings.production`, removing some redundancy that currently exists.
The `STORAGE_ENGINE` environment variable is still relied upon to (optionally) set the default MySQL storage engine.
This change should not modify any existing behavior, either for local development or in production. In local development, the suggested value for `STORAGE_ENGINE` ([as set in the `.env_SAMPLE` file](https://github.com/cfpb/cfgov-refresh/blob/master/.env_SAMPLE#L60)) is
`"SET default_storage_engine=MYISAM"`
This sets the MySQL `default_storage_engine` variable and is valid syntax in modern versions of MySQL. …
=> Simplify and cleanup MySQL database settings

cfgov/legacy/templates/front/base_nonresponsive.html, cfgov/legacy/templates/front/base_update.html
A few months ago, we updated our default images for Twitter and opengraph(facebook, etc). These changes were never applied to apps using our older base templates
- a "twitter:image" value, which better fits how Twitter crops images.
- og:image is now img/logo_open-graph_facebook.png
=> Better default social images for 'django' templates

cfgov/wellbeing/jinja2/wellbeing/results.html
- Put "Review your answers" in an expandable
- Moves the grouping select menu closer to the category radios for the combined histogram
1. Pull branch
1. Run server
1. Visit http://localhost:8000/consumer-tools/financial-well-being/results/?45
1. Observe the "review your answers" table now inside an expandable
1. Observe the select menu for the specific grouping of the histogram now floating 30px to the right of the radio buttons to select the category, rather than floating all the way to the right of the available space
=> wellbeing: A couple more small changes for Friday's round of usability testing

cfgov/jinja2/v1/ask-cfpb/answer-page-spanish.html, cfgov/jinja2/v1/ask-cfpb/audience-page.html, cfgov/jinja2/v1/ask-cfpb/category-page-spanish.html, cfgov/jinja2/v1/ask-cfpb/landing-page-spanish.html
Wagtail's `slugurl()` template function is handy, but it can cause
mischief in the Ask CFPB app if we pass an answer slug to it,
because we purposely don't keep answer slugs and page slugs in sync.
This PR sweeps the Ask CFPB templates for uses of `slugurl()` that involve 
answer object slugs. Uses for other slug types are fine.
Use of `slugurl()` was removed on these templates in `cfgov/jinja2/v1/ask-cfpb/`
- answer-page-spanish.html
- audience-page.html
- category-page-spanish.html
- landing-page-spanish.html
Previous PRs removed the function from these templates:
- answer-page.html
- landing-page.html
=> Ask CFPB: sweep out usages of slugurl()

requirements/optional-public.txt
This will point to the latest version of CCDB5-API
- Changed CCDB5-API from v0.6.0 to v0.7.0
=> Bump up the version of ccdb5-api

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, requirements/optional-public.txt
This change bumps the eregs-2.0 version from 0.0.2 to 0.0.4, and also turns it on by default if the `DEPLOY_ENVIRONMENT` environment variable is set to `build` (this avoids needing manual feature flag creation in the Wagtail UI).
This release includes some retroactive migration changes so before it is deployed it's recommended to fully destroy existing eregs-2.0 tables using these commands:
```sh
$ cfgov/manage.py migrate eregs_core zero
```
- Bump eregs-2.0 version to 0.0.4.
1. `pip install -r requirements/optional-public.txt`
2. `DEPLOY_ENVIRONMENT=build cfgov/manage.py migrate eregs_core`
3. `DEPLOY_ENVIRONMENT=build ./runserver.sh`
4. Visit http://localhost:8000/eregs2
=> Bump eregs-2.0 version to 0.0.4 release

cfgov/data_research/views.py
This only adds the national average to avoid the need for a separate API
request for map pages.
So a [state map request](http://localhost:8000/data-research/mortgages/api/v1/map-data/30-89/states/2009-01/) would start with an enhanced meta field. Same would apply to [county](http://localhost:8000/data-research/mortgages/api/v1/map-data/30-89/counties/2009-01/) or [metro](http://localhost:8000/data-research/mortgages/api/v1/map-data/30-89/metros/2009-01/) requests. [National](http://localhost:8000/data-research/mortgages/api/v1/map-data/30-89/national/2009-01/) requests do not change.
=> Add national average to meta field of map API calls

requirements/optional-public.txt
This version bumps the optional eregs-2.0 package from version 0.0.4 to version 0.0.5. This change mainly affects the static frontend assets that are contributed by that package.
- Bump eregs-2.0 from version 0.0.4 to version 0.0.5.
1. `pip install -r requirements/optional-public.txt`
2. `DEPLOY_ENVIRONMENT=build cfgov/manage.py migrate eregs_core`
3. `DEPLOY_ENVIRONMENT=build ./runserver.sh`
4. Visit http://localhost:8000/eregs2
=> Bump eregs-2.0 to version 0.0.5

requirements/optional-public.txt
Some of our apps aren't building yet under Node 8-- the replaces their optional-public.txt entries with absolute links to pre-built wheels, on Github.
- some (more) entries in optional-public.txt now point to pre-built wheels
=> Use pre-built satellite apps

config/environment.js, config/webpack-config.js, gulp/tasks/styles.js
@contolini found that the ie string in the browser support list was not doing anything. This changes the array to support IE9. It also splits the array into two for js and css to support different sets.
- Split `getSupportedBrowserList` into two arrays for css and js.
- Change browser list support list to properly include older IE support.
2. IE9 should not look blown up.
=> Fix browser support list IE support

docs/new-projects.md, requirements/manual.txt
This commit bumps the version of mkDOCter (the mkdocs theme) we use for documentation from 0.1.3 to 0.1.4, and also bumps mkdocs itself to the latest 0.16.3 version.
It also fixes a broken link in the documentation to point to our development standards.
- Bump mkdocs to latest version, and our theme mkdocter with it.
- Fix broken link.
1. Run `pip install -r requirements/manual.txt` then `mkdocs serve` to browse documentation locally.
- This PR first requires a 0.1.4 release of [mkDOCter](https://pypi.python.org/pypi/mkDOCter) on PyPI.
=> Update mkDOCter version, fix broken docs link

requirements/manual.txt
PR #3304 bumped the version of `mkdocs` used for the manual but neglected to also bump the required version of `Markdown`. This change bumps that package from 2.3.1 to 2.6.9.
- Bump version of `Markdown` in `requirements/manual.txt`.
To test, do `pip install -r requirements/manual.txt` and then `mkdocs serve`.
=> Bump Markdown version for manual

cfgov/alerts/post_sqs_messages.py
- Adds a space to # so it doesn't erroneously link to a Github issue
- Remove the `[Open]` syntax so that the link expands
See GHE 1146 as an example of how this looks like now, and 1148 as an example of how it will look like after these changes.
=> Improve formatting of Github issue created from SQS script

cfgov/alerts/post_sqs_messages.py
Previously, we were only looking at open issues when deciding whether to create a new issue or comment on an existing one.  After this PR, we will simply re-open matching closed issues and comment on them, so the record is all in the same place.  Reasons for this happening might be that an issue gets resolved by a human and they close it, but then it starts failing at some future date for other reasons.
=> Reopen a github issue if it was previously closed (SQS script enhancement)

cfgov/unprocessed/css/organisms/mortgage-performance-trends.less, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/map.js, package-lock.json, package.json
Tweaks the choropleth map to use the highcharts `select()` feature.
- Locations are highlighted after being selected in the dropdown.
- Bump cfpb-chart-builder to v3.0.1.
1. Set up the [mortgage performance API](https://github.com/cfpb/cfgov-refresh/pull/3189).
1. Create a [mortgage chart block and page](https://github.com/cfpb/cfgov-refresh/pull/3260).
=> Add MP map highlighting feature

cfgov/data_research/fixtures/mortgage_constants.json, cfgov/data_research/models.py, cfgov/jinja2/v1/_includes/organisms/mortgage-chart.html, cfgov/jinja2/v1/_includes/organisms/mortgage-map.html
This aligns chart and map footnotes with the latest content, as specified in GHE issue 167.
The footnotes'  download links and file sizes will stay in sync with the database, and the
notes string will be editable via the data_research admin.
You'll need to refresh your local data (even if you did so recently).
Download the latest data here: 
- http://files.consumerfinance.gov.s3.amazonaws.com/data/mortgage-performance/initial_data/mortgagedata.sql.gz
Load it:
```
gunzip -c ~/Downloads/mortgagedata.sql.gz | mysql -uroot v1
```
Footnotes under charts and maps should match content at GHE 167.
=> Data_research chart and map footnote content

cfgov/jinja2/v1/_includes/organisms/table.html
Jinja was outputting a paragraph tag wtihin the button causing layout
and scripting issues.
- Updated the markup template to remove the tags from the content within the sortable button.
1. Create a sortable table
2. Attempt to sort one column, observe the arrow on it's own line and that it doesn't stay displayed after activated.
3. Checkout this branch and observe the arrow stays displayed and doesn't break to it's own line.
__Before__
__After__
- The sortable tables code didn't consider a button that is more than one line. I have opened an [issue in Capital Framework](https://github.com/cfpb/capital-framework/issues/598) to explore a fix.
=> Correct the markup within the sorting buttons in sortable-tables

.travis.yml, codecov.yml, gulp/tasks/test.js, package-lock.json, package.json, requirements/travis.txt, run_travis.sh
This PR makes some changes to our codecov configuration, primarily:
- Adding `frontend` and `backend` flags to report Javascript and Python test coverage separately in PRs. (See below).
- Removing the independent `gulp-codecov` and `codecov` Javascript and Python libraries in favor of Codecov's recommended bash submission. `gulp-codecov` doesn't provide a way to flag the coverage that it's submitting (which is necessary for `frontend` vs `backend` coverage). This also keeps cloud services out of our gulp tasks.
I would recommend once this PR is merged that we make the [Codecov `patch` check](https://docs.codecov.io/docs/commit-status#section-patch-status) (which measures the coverage of lines changed in a PR) required for merges (like coveralls used to be), and keep backend and frontend …
=> Modify Codecov configuration to include frontend/backend flags

cfgov/v1/util/filterable_list.py
This change removes the logging statement that happens when a FilterableList is invoked, e.g. `Filtering by parent Foo`. This might be useful from a debugging POV but seems excessive for general use.
- Logging statement from FilterableList.
1. All unit tests continue to pass; this is a non-functional change.
=> Remove logging statement from FilterableList

config/webpack-config.js
Babel explicitly ignores JS in the node_modules directory but now that we're writing ES6 outside of cfgov-refresh we need to ensure we transpile external CFPB dependencies.
- Added node modules that start with `cf` to webpack's babel step.
1. `./runserver.sh`
1. Open `http://localhost:8000/about-us/budget-strategy/budget-and-performance/` and view the page's source. There should be no `const` declarations. The same page on master has `const` declarations
=> ES5ify all Capital Framework JavaScript

cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/chart.js
In one of our last PRs that modified how we displayed the county information, we missed making some needed changes in one file.
- Call the `name` variable rather than `county` in `chart.js`, to prevent the appearance of `undefined` as text.
1. Pull down the branch and load the page.
2. Select the "county" location type. The list of counties should have actual counties listed in it.
Current status on build:
Desired status after this PR lands:
=> Mortgage Performance: display county information using the right variable

cfgov/jinja2/v1/_includes/organisms/mortgage-map.html, cfgov/unprocessed/css/organisms/mortgage-performance-trends.less, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/map.js, package-lock.json, package.json
The MP map needs to show the selected location's delinquency rate alongside the national average. A tooltip formatting function is passed to cfpb-chart-builder that uses it to render HTML for the tooltip.
- `renderTooltip` function that returns HTML for the tooltip.
- CSS for the tooltip.
- Misc. font size cleanup.
- Updated cfpb-chart-builder to the latest version that supports custom tooltips.
- Renames the `location` variable to `loc` to avoid Checkmarx false positive. (I think it's confusing it with `window.location`).
1. Set up the [mortgage performance API](https://github.com/cfpb/cfgov-refresh/pull/3189).
1. Create a [mortgage chart block and page](https://github.com/cfpb/cfgov-refresh/pull/3260).
=> Add dynamic tooltip to Mortgage Performance map

cfgov/data_research/tests/test_views.py, cfgov/data_research/views.py
Previously non-MSA areas that contained no counties (such as New Jersey)
or that had counties that together didn't meet our display threshold (such
as Massachusetts) were not included in API responses for metro-area maps.
This PR makes sure the five invalid non-MSA objects are represented in data
with a json data value of `null` (represented as `None` in Python view
code).
The five non-MSA areas that should now show up with null values:
- Delaware
- District of Columbia
- Massachusetts
- New Jersey
- Rhode Island
Hit a metro map API endpoint and search for the Massachusetts non-MSA FIPS code, `25-non`, which previously was absent.
http://localhost:8000/data-research/mortgages/api/v1/map-data/90/metros/2009-01/
=> Mortgage-performance non-MSA invalid values

cfgov/jinja2/v1/_includes/organisms/mortgage-chart.html, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/actions.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/chart.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/stores/chart.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/utils.js, test/unit_tests/organisms/MortgagePerformanceTrends/actions-spec.js, test/unit_tests/organisms/MortgagePerformanceTrends/stores/chart-spec.js
This PR shows the "national average" dynamic title text for the default national view.
- Added a span to allow the "versus" comparison dynamic text to be treated differently from the "national average" dynamic text
- Renamed the variables for the "Compare to national average" checkbox
2. Set up the [mortgage performance API](https://github.com/cfpb/cfgov-refresh/pull/3189).
3. Create a [mortgage chart block and page](https://github.com/cfpb/cfgov-refresh/pull/3260).
Two items, but I wanted to get this PR up:
1. When you click on any other location and then return to nation, it doesn't show the default "national average" text.
2. When you uncheck the "compare to national average" checkbox, and then check it again, it doesn't show the words …
=> Mortgage Performance: show "national average" text on default view

cfgov/data_research/mortgage_utilities/fips_meta.py, cfgov/data_research/scripts/update_county_msa_meta.py, cfgov/data_research/tests/test_scripts.py
Since we display MSA and non-MSA data together, building drop-down lists
will be easier if we combine the metadata in one endpoint.
Toward the same end, we're adding drop-down info to the `non_msa_fips` endpoint.
This PR just changes the script that updates metadata once a quarter.
The new endpoints can be checked on build
- [BUILD]/data-research/mortgages/api/v1/metadata/state_msa_meta/
- [BUILD]/data-research/mortgages/api/v1/metadata/non_msa_fips/
=> MP: add non-msa metadata to msa endpoints

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/jinja2/v1/activity-log/index.html, cfgov/jinja2/v1/index.html, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/util/ref.py
Fixes https://[GHE]/CFGOV/platform/issues/1112
- Changes Activity Log page title to "Recent updates" (sentence case)
- Changes "Activity Log" in mega menu to "Recent Updates". Within the mega menu, moves "Recent Updates" to the top of the column, above Blog, Newsroom, Events.
- Changes "See all activities" link under "Latest updates" section at the bottom of the Homepage to "See all updates".
1. Visit homepage for "See all updates" change.
2. localhost:8000/activity-log/ to see change to page title, and to check mega menu.
=> Changes Activity Log to Recent updates

cfgov/alerts/github_alert.py, cfgov/alerts/mattermost_alert.py, cfgov/alerts/post_sqs_messages.py, cfgov/alerts/tests/test_github_alert.py, cfgov/alerts/tests/test_mattermost_alert.py, cfgov/alerts/tests/test_post_sqs_messages.py, requirements/test.txt
In addition to cleaning up some of this code, this was necessary for a branch I'm working on which needs to reuse the "post to github" functionality (see https://github.com/cfpb/cfgov-refresh/pull/3322/files#diff-a2de39d3ae75d0257afafb3cb2d587ce)
=> Refactor `post_sqs_messages` script

cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/chart.js
@marteki couple small fixes for the things we noticed this morn.
- Remove non-metros from metro dropdown.
- Don't show the "versus national" text when only national is selected.
2. Set up the [mortgage performance API](https://github.com/cfpb/cfgov-refresh/pull/3189).
3. Create a [mortgage chart block and page](https://github.com/cfpb/cfgov-refresh/pull/3260).
=> MP line chart fixes

cfgov/jinja2/v1/_includes/molecules/notification.html, cfgov/jinja2/v1/_layouts/content-base.html
A jinja typo was letting jinja markup into the output HTML 😱 
Also, whitespace was being removed from two attributes in jinja, leading to them having no space separation in the generated output HTML (`role="main"lang="en"`).
Both of these typos were causing errors in IE. 
- Fixes jinja typo of missing double bracket.
- Removes whitespace removal in jinja markup.
=> Bug: Fix template typos

config/webpack-config.js, package-lock.json, package.json
- Moves webpack configuration `module` to a constant shared by all webpack configurations so that each uses the same babel/browserlist pipeline.
- Updates webpack and babel npm modules to latest.
1. Run `npm install`
2. Run `gulp build`
3. Search the output JS in `static_built/js/` for `const`.
- I restructured the webpack configuration slightly to rename `rules` to `loaders` as I didn't find `module.rules` on https://webpack.github.io/docs/configuration.html#module (I guess maybe it worked before for backward compatibility??? Dunno). Also, I updated `use` to `loaders` per that same doc.
=>  Run all generated JS through Babel

cfgov/alerts/newrelic_alerts.py, cfgov/alerts/send_new_relic_messages_to_sqs.py, cfgov/alerts/tests/test_newrelic_alerts.py, cfgov/alerts/tests/test_send_new_relic_messages_to_sqs.py
This PR refactors the New Relic alert violation processing to make it more testable and to handle previously-seen violations differently.
We had been trying to use the New Relic `opened_at` and `duration` values for violations to track when a violation occurred. If we run every 60 seconds, our assumption was that violations that have been open for less than 60 seconds were new. This turns out not to be true — some violations are not available via the API until well after 60 seconds, but their duration still reflects when the condition began — they'd first appear with durations of 180+ seconds.
Instead, this script now takes a `--known_violations_file` in which to store violation ids, one per-line, and violations are added to this file when they are first observed by the script. That file …
=> Refactor New Relic alerts, use a local cache file of violations

cfgov/data_research/models.py, cfgov/jinja2/v1/_includes/organisms/mortgage-chart.html
In the chart template we need date ranges to carry no-break spaces to
avoid awkward breaks.
Check source on a chart page, and the chart label's date range should carry no-break spaces.
=> Mortgage performance: Reformat date range in chart

README.md
The Code Climate badge hasn't been updated in more than a year because the org permissions don't allow Code Climate and until GH allows finer grained control of permissions this doesn't look like it will updated any time soon.
- Removes outdated Code Climate badge from Readme :-(
=> Removes code climate badge

cfgov/data_research/scripts/update_county_msa_meta.py, cfgov/data_research/views.py
This alphabetizes the state MSA dropdown list and adds the non-MSA entry at the
bottom of the list, in case we haven't turned to other solutions.
The ordering in the API call can be checked on build:
[BUILD]/data-research/mortgages/api/v1/metadata/state_msa_meta/
=> Mortgage performance: Fix ordering of MSA dropdown

cfgov/cfgov/urls.py
Removing unnecessary flagged routes
- Modified `cfgov/cfgov/urls.py` to remove the flagged routes. These routes are controlled by the apache config file and we are ready for these pages to go live. 
Visit http://localhost:8000/es/ and verify the page renders.
Visit http://localhost:8000/es/presentar-una-queja/ and verify that the page renders.
Visit http://localhost:8000/es/quienes-somos/ and verify that the page renders.
Visit http://localhost:8000/es/hogar/` and verify that the page renders.
Visit http://localhost:8000/es/nuestra-historia/ and verify that the page renders.
-
-
=> Removing unnecessary flagged /es/ routes

cfgov/alerts/newrelic_alerts.py, cfgov/alerts/send_new_relic_messages_to_sqs.py, cfgov/alerts/tests/test_newrelic_alerts.py, cfgov/alerts/tests/test_send_new_relic_messages_to_sqs.py
This PR forces `known_violations` to be strings when writing to our cache file. This should fix caching of New Relic alerts.
=> Force known New Relic violations to be strings when caching

cfgov/alerts/tests/test_newrelic_alerts.py, cfgov/alerts/tests/test_send_new_relic_messages_to_sqs.py, run_travis.sh
I accidentally removed flake8 [when adding codecov](https://github.com/cfpb/cfgov-refresh/commit/369625e33f6196cea9dc17d9e477de0eb41cd7d9#diff-166a8c44f1ec1d519e437119223c84d5L13). This PR restores it (and fixes some failures introduced in the meantime, by me).
=> Restore flake8

cfgov/unprocessed/css/organisms/mortgage-performance-trends.less, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/map.js, package-lock.json, package.json
Adds the "insufficient data" tooltip to the county view and changes the insufficient data color from `@gray-10` to `@gray-5`.
- Tooltip when the map point has a value of `null`.
- Update lowest item in the color range from `@gray-10` to `@gray-5`.
- Use the full namespaced CSS classes instead of `.highcharts-color-0` to avoid conflicts with other CFPB charts.
1. Set up the [mortgage performance API](https://github.com/cfpb/cfgov-refresh/pull/3189).
1. Create a [mortgage chart block and page](https://github.com/cfpb/cfgov-refresh/pull/3260).
=> Add insufficient data tooltip to county map

requirements/optional-private.txt
This change bumps the version of the optional private eregs/ip repository from 1.1.1 to 1.1.2.
- Increment version of eregs/ip.
1. `pip install -r requirements/optional.txt` to install the optional private packages.
2. Navigate to http://localhost:8000/eregulations to view eRegs content.
=> Bump eregs/ip requirement to 1.1.2

cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/on-demand/footer.less, cfgov/unprocessed/css/on-demand/header.less, cfgov/unprocessed/css/on-demand/secondary-navigation.less
Fixes failing build on collectstatic step where icon font path and web font variables were not defined in the nonresponsive css files. See https://GHE/CFGOV/platform/issues/1189 for the build failure details.
-
-
- add licensed-fonts.css import and variables to the nonresponsive css files
- declare correct icon-font path for the same files (used to be in cf-brand-overrides.less, which was deleted in #3328)
1. `cfgov/manage.py collectstatic`
1. static files should be copied without errors
-
-
=> Fix icon font path + web font variables for nonresponsive CSS

cfgov/alerts/logging_handlers.py, cfgov/alerts/tests/test_logging_handlers.py, cfgov/cfgov/settings/production.py
- Adds a logging handler to intercept any logging statements of level `ERROR`
- Posts them to Github Enterprise as issues, as we are doing with Jenkins failures and New Relic incidents
=> Post Django errors to Github

codecov.yml, requirements/base.txt
Previously this was only in `scripts.txt` because it was only called from Jenkins, but with the introduction of https://github.com/cfpb/cfgov-refresh/pull/3322 it's needed in cfgov as well.  I didn't catch it because I already had the lib installed locally as well as in `test.txt` :(
=> Add github3 dependency to base.txt

cfgov/alerts/newrelic_alerts.py, cfgov/alerts/send_new_relic_messages_to_sqs.py, cfgov/alerts/tests/test_newrelic_alerts.py, cfgov/alerts/tests/test_send_new_relic_messages_to_sqs.py
Yet another attempt to fix the New Relic violation caching. This PR adjusts the way the cache file is written and the way it is read to ensure correctly formatted data all the way through the process.
The New Relic alert polling job is currently running (successfully now!) from this branch.
=> Fix New Relic alerts known violation caching

cfgov/alerts/mattermost_alert.py, cfgov/alerts/post_sqs_messages.py, cfgov/alerts/tests/test_mattermost_alert.py
This PR adds an option for an icon URL to our Mattermost alert posting class and SQS polling script. This will let us specify an alternative icon for the alerting bot.
=> Add an option for a Mattermost icon URL

cfgov/alerts/github_alert.py, cfgov/alerts/logging_handlers.py, cfgov/alerts/tests/test_logging_handlers.py
Some minor enhancements to the Django error handler
- Pass in the full message as a title to Github, letting the `GithubAlert` class deal with length limits
- Pass in the exception message as the body to Github
See GHE/richa/testbot/issues/122 as an example.
=> Django error handler enhancements

cfgov/cfgov/settings/base.py
Whitelisting google maps image src 
1. Visit `localhost:8000/about-us/events/` and verify that the map images appear.
=> Whitelisting google maps image src 

cfgov/cfgov/settings/base.py
Resolves some CSP errors that fire when you enable the debugger:
- Allow fonts from data: URL's and fonts.google.com
- allow images from gstatic.com
- allow stylesheets from 'fonts.googleapis.com'
=> Further whitelist additions to support Google Tag Manager debugger

cfgov/cfgov/settings/base.py
This should be the last GTM debugger fix
- Allow fonts from fonts.gstatic.com
=> Allow fonts from fonts.gstatic.com

cfgov/wellbeing/jinja2/wellbeing/results.html
When printing, we don't want to include the sidebar. The spectrum was
also printing wider than the image causing the scale to mis-align.
- Fixed the FWB print styles
1. Run through the questions and attempt to print your results.
- I can't figure out why Chrome is printing an extra page. That may have to happen post launch.
=> Fix issues when printing the FWB results page

cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/results/index.js, cfgov/wellbeing/jinja2/wellbeing/about.html, cfgov/wellbeing/jinja2/wellbeing/home.html, cfgov/wellbeing/jinja2/wellbeing/results.html
Our analytics team requested some updates to the events that fire on the financial well-being questionnaire and results pages.
- Event data for the categorization questions at the end of the questionnaire
- Event data for the Compare By buttons on the results page
- Renames event category from "Page Interaction" to "Financial Well-Being Tool Interaction"
I'm not sure if it's possible to test these locally. Anyone know how?
=> wellbeing: Update analytics event data

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Adds Financial Well-Being Survey links to the Data & Research portion of the mega menu. ~Uses a flag to stage these changes until go-live.~
- New "Financial Well-Being Survey" page placed at the bottom of column 3, underneath “Credit Card Surveys & Agreements”
- Moves “CFPB Researchers” to column 1 (underneath “CFPB Research Conference”)
1. Verify that the menu has changed to reflect the addition and changes above.
=> Add survey link to data & research mega menu

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
The URL for the Financial Well-Being Survey changed since the issue was filed, updating to the full path.
=> Fix incorrect URL

cfgov/unprocessed/css/organisms/chart.less
The Mortgage Performance footnotes were failing the WCAG 2.0 AA color contrast test. They were Gray 80, so we are changing them to CFPB Black.
- Change footnote color from Gray 80 to CFPB Black
2. Set up the [mortgage performance API](https://github.com/cfpb/cfgov-refresh/pull/3189).
3. Create a [mortgage chart block and page](https://github.com/cfpb/cfgov-refresh/pull/3260).
=> Change chart footnote color from Gray 80 to CFPB Black

cfgov/wellbeing/jinja2/wellbeing/results.html
For whatever reason Firefox isn’t expanding the table within the
expandable, even if it’s displayed on the user’s browser.
- Print specific styles for FWB
1. Open http://localhost:8000/consumer-tools/financial-well-being/ in Firefox and fill in the form, then try to print the page. The expandable content should be visible in your print preview.
=> Fix layout issues within Firefox when printing

cfgov/jinja2/v1/_layouts/base.html, cfgov/wellbeing/jinja2/wellbeing/about.html, cfgov/wellbeing/jinja2/wellbeing/home.html, cfgov/wellbeing/jinja2/wellbeing/results.html
Apps like Well Being are not able to set their own Open Graph Images.
Wrapping the OG Image code in a block allows a developer to override the
default images.
- OG Block wrapper to the `base.html` templates.
- OG Image block to each of the Well Being templates.
- OG Description block to each of the Well Being templates.
1. It's not possible to test Open Graph locally other than viewing the page source.
=> Add the option to swap out the OG Image in non-wagtail pages

cfgov/cfgov/test.py
`sheer.js` removed in https://github.com/cfpb/cfgov-refresh/commit/d74bc50d9247cd6152ca40bf80b4d8c8ae4b1498#diff-89b43ee86bbd4952dc44cf751cfd775c. This additional reference can be removed. 
- `sheer.js` reference.
1. run `tox`
=> Removes reference to sheer.js

requirements/optional-public.txt
This change updates the optional [regulations-site](https://github.com/cfpb/regulations-site) package to its [2.1.10 release](https://github.com/cfpb/regulations-site/releases/tag/2.1.10).
- Bump regulations-site from 2.1.8 to 2.1.10.
=> Update optional regulations-site package to 2.1.10

cfgov/cfgov/settings/base.py
This flag will be used to turn on new links in the megamenu's
data-research section.
=> Mortgage performance: Set a release feature flag

cfgov/jinja2/v1/_includes/organisms/mortgage-map.html, cfgov/unprocessed/css/organisms/mortgage-performance-trends.less, cfgov/unprocessed/js/routes/on-demand/mortgage-performance-trends.js
@marteki IE isn't rendering the legend because it requires SVG shapes to have an explicit height and width. This fixes that.
- The `MP_DEBUG` variable that enables logging of the state whenever it changes. It can be reenabled by uncommenting the line.
- The SVG `rect`s now have a height/width property.
- Text in the legend is a little larger on mobile devices. IMHO it needs to be even larger but we'll have to adjust the size of the SVG's bounding box to avoid the text getting cut off so I'm leaving it at 16px for now.
=> Mortgage Performance SVG fix for IE

cfgov/jinja2/v1/_includes/organisms/mortgage-performance-downloads.html
Our downloads page has visual clues to distinguish download links, but
the link text is the same, which doesn't help people using screen
readers. This adds aria-label attributes to download links with
specifics about what is being downloaded.
Changes are not visible but can be checked in dev tools on the [download
page](http://localhost:8000/data-research/mortgage-performance-trends/download-the-data/)
=> Mortgage performance: add aria-label attributes

cfgov/jinja2/v1/_includes/organisms/mortgage-map.html, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/map.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/utils.js, test/unit_tests/organisms/MortgagePerformanceTrends/utils-spec.js
Displays a message to the user if they've selected an invalid date. See https://GHE/CFGOV/mortgage-performance/issues/185.
@ajbush check out the screenshot below. I used the two line "[explanation](https://cfpb.github.io/capital-framework/components/cf-notifications/#explanation)" version that has a title and then text explaining the situation. What do you think? Should I just keep it at one line?
- `isDateValid` function to check if the user-selected date is less than or equal to the date we have the most recent data for. Used to show/hide the date error message to the user.
- [cf-notification](https://cfpb.github.io/capital-framework/components/cf-notifications/) with a message stating the selected date is invalid.
- JSDoc comments to all utility functions.
- Removed all the hardcoded …
=> Mortgage Performance: Add logic to date dropdowns

cfgov/jinja2/v1/es/presentar-una-queja/index.html, cfgov/legacy/templates/students/index.html, requirements/optional-private.txt
- 'help.consumerfinance.gov' doesn't exist anymore-- this PR fixes a few hard-coded links.
=> Update CR links

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/unprocessed/css/enhancements/forms.less, cfgov/unprocessed/css/organisms/form.less, cfgov/v1/forms.py
The filter controls are using old full-width styles that is removed as
part of this update.
- Removed old full width input styles
- Updated filter controls to use new full-width input styles
2. Run the site locally
3. Test filterable list controls "Item name" inputs (/blog/ and /newsroom/)
- There's an extra bit of space between the label and the input. I'm working on a fix for this in Capital Framework and will make sure it's updated here after the release.
=> Update filter controls to use CF full-width inputs

gulp/tasks/copy.js, gulp/tasks/images.js
Fix for gulp copy and cleaning up some other gulp tasks
- Modified `gulp/tasks/images.js` to fix issue with gulp copy process ending before all the images were copied. Removed `browserSync` which was causing async issues. I'll look into closer.
- Modified `gulp/tasks/copy.js` to simplify the code. 
1. Run `gulp clean && gulp build` and verify your existence.
=> Fix for gulp copy and cleaning up some other gulp tasks

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
The calendar is no longer filtered, this condition isn’t necessary
- Removed the calendar condition and it's related options.
1. Navigate to http://localhost:8000/about-us/the-bureau/leadership-calendar/ and observe the lack of filtering
=> Remove the calendar options from the filterable list

cfgov/unprocessed/js/routes/common.js, cfgov/unprocessed/js/routes/on-demand/video-player.js, cfgov/v1/atomic_elements/molecules.py, cfgov/v1/atomic_elements/organisms.py, cfgov/v1/models/learn_page.py
All pages which contain the video-player have been converted to Wagtail. This PR removes the video player from commons.js. It will result in the common.js bundle, which is on every page, being 5kb smaller. I have also removed the Ustream code from the bundle because it's no longer used. I'll remove the Ustream related code in a subsequent PR. 
- Modified files to remove vidoe player.js from commons.js. 
2. Visit `http://localhost:8000/about-us/events/archive-past-events/public-event-about-debt-collection-washington-dc/` and ensure the video player works.
3. Visit `http://localhost:8000/about-us/the-bureau/` and ensure that the video player works.
4. Visit `http://localhost:8000/about-us/careers/application-process/` and ensure the video player works.
=> Removing video player code from common.js

cfgov/unprocessed/css/enhancements/utilities.less, package-lock.json, package.json
- Removes `u-hidden` utility class that has been added to Capital Framework.
- Bumps to latest `cf-core` version (`4.5.0`).
1. run `npm update cf-core`
=> Remove u-hidden class

codecov.yml
Codecov keeps failing because of missing base branches to compare against. Supposedly this should fix it based on the very end of this thread https://github.com/SBoudrias/gulp-istanbul
- Codecov settings for missing base commit
1. ¯\_(ツ)_/¯
=> Updated codecov settings for missing base commit

.travis.yml
This PR changes our Travis config to add a whitelist for branches that we want to build when they're updated. This should enable us to turn on Travis for branch updates and it will only build updates to master. Hopefully this will solve our problem with missing base commits for codecov because Travis will build and submit coverage for each merge commit to master.
I don't really think we can test this without merging this change though, so I'd request just a sanity check.
- Enable branch update builds in Travis once this PR is merged (otherwise Travis will build feature/PR branches twice)
=> Tell travis to build only master when building branches

cfgov/unprocessed/js/apps/financial-well-being/fwb-questions.js, cfgov/unprocessed/js/apps/financial-well-being/fwb-results.js, test/unit_tests/apps/financial-well-being/fwb-questions.js
I, uh, forgot to add the `sendEvent` call from the questionnaire submit button 😳 
- Event listener on the "Get your score" button to fire an Analytics event
- A test for said event
- Generalizes the `handleRadioAnalytics` and `handleButtonAnalytics` to work generically for any passed element with the necessary data attributes.
1. Pull branch
2. `gulp test:unit` should pass
- We want to get this fix on prod pretty quickly, but advice is welcome for how to use a single `handleAnalytics` function, rather than the duplicate code that now exists in the two FWB JS files. Perhaps a new method in the `Analytics` module?
=> wellbeing: Send Analytics event from questionnaire submit button

cfgov/jinja2/v1/_includes/organisms/mortgage-map.html, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/map.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/stores/map.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/utils.js, test/unit_tests/organisms/MortgagePerformanceTrends/stores/map-spec.js, test/unit_tests/organisms/MortgagePerformanceTrends/utils-spec.js
See https://GHE/CFGOV/mortgage-performance/issues/202
- The month and year dropdowns default to the date of the most recent data.
1. Pull down this branch and `./frontend.sh`
2. Set up the [mortgage performance API](https://github.com/cfpb/cfgov-refresh/pull/3189).
3. Create a [mortgage chart block, mortgage map block, and page](https://github.com/cfpb/cfgov-refresh/pull/3260).
4. Open http://localhost:8000/data-research/mortgage-performance-trends/mortgages-30-89-days-delinquent/ and the map should default to whatever date you have the most recent data for.
-
-
=> Set Mortgage Performance map dropdowns to most recent date available

cfgov/ask_cfpb/models/pages.py
Our lists of links that 404 included links on some Spanish Ask CFPB tag-results pages.
Tags are applied to Answers, not pages (who came up with *that* idea?),
and the tag filters were not ensuring that found pages were live.
Adding the `live` test should knock off at least a few 404 links.
- The first inked answer on the Spanish SCRA tag results page.
- https://www.consumerfinance.gov/es/obtener-respuestas/buscar-por-etiqueta/SCRA/
- The fifth link on the HECM tag page (¿Mi pareja ...)
- https://www.consumerfinance.gov/es/obtener-respuestas/buscar-por-etiqueta/HECM/
=> Ask CFPB: prevent tag search from finding non-live pages

docs/testing.md, gulp/tasks/test.js
When refactoring an individual module it is helpful to be able to run only its associated unit tests. This PR adds support to run an individual unit test spec. Similar to what can be done with acceptance tests.
- Adds support for running individual unit tests to `gulp test:unit` command.
1. `gulp test:unit` should run all unit tests.
2. `gulp test:unit --specs=modules/o-table-row-links-spec.js` should run an indvidual test.
3. `gulp test:unit --specs=modules/transition/*.js` should run all transition and dependent unit tests.
=> Support running individual unit tests.

docs/testing.md
Sauce testing instructions were not current. This updates it.
- Update Sauce testing instructions to remove not applicable warnings, update links, and to update gulp command.
=> Update Sauce testing instructions to latest

cfgov/unprocessed/css/organisms/mortgage-performance-trends.less
@higs4281 discovered that Safari requires SVGs to have a set width or they'll overflow their bounding box.
Before:
After:
=> Give Mortgage Performance legend an explicit width

cfgov/ask_cfpb/models/django.py, cfgov/ask_cfpb/models/pages.py, cfgov/ask_cfpb/tests/models/test_pages.py
Redirected pages in Ask CFPB need to remain live in order to do their
job of redirecting requests to another page. But Category and
SubCategory pages were not excluding redirected pages from their
collection of associated pages, resulting in some duplication in the
list of answers offered.
Addresses GHE issue 1292.
=> Ask CFPB: Hide redirected pages from Category pages

cfgov/unprocessed/css/misc.less, test/browser_tests/cucumber/step_definitions/header.js
Removes transition class that was specific to tests but was being delivered to production code. Originally added in https://github.com/cfpb/cfgov-refresh/pull/2166.
Tests appear to pass fine without it. Perhaps an update to Protractor has helped ¯\_(ツ)_/¯
If for some reason it's discovered this is needed, it should be defined in the [test](test/browser_tests/cucumber/step_definitions/header.js), not the less with:
```js
const script = `
var style = document.createElement( 'style' );
style.type = 'text/css';
style.innerHTML = '.u-move-transition__disabled ' +
'.u-move-transition { ' +
'transition: transform 1ms ease; }';
document.getElementsByTagName( 'head' )[0].appendChild( style );
document.body.className = 'u-move-transition__disabled';
`;
browser.executeScript( script );
```
- Removes …
=> Remove test-specific class

cfgov/unprocessed/css/enhancements/layout.less, package-lock.json, package.json
Brings in latest cf-layout to include https://github.com/cfpb/capital-framework/pull/637
- Unneeded cf-layout enhancement CSS for setting max-width on global elements, which comes in via cf-layout now.
- Updates `cf-layout` to version `4.6.0`.
2. Paragraph, label, definition list, bulleted lists, and h3-h6 headings should be truncated to 41.875rem. There should be no change compared to the live site beyond long labels being truncated.
=> Brings in latest cf-layout

cfgov/data_research/scripts/export_public_csvs.py
Data from Puerto Rico has been deemed out of scope for this project's
launch. This ensures that Puerto Rico (and any other states we want to
exclude) don't show up in download CSV files.
The updated script has been run against our latest data, and our state-based CSVs are now free of Puerto Rico references.
- http://files.consumerfinance.gov.s3.amazonaws.com/data/mortgage-performance/downloads/StateMortgagesPercent-90-plusDaysLate-thru-2017-03.csv
- http://files.consumerfinance.gov.s3.amazonaws.com/data/mortgage-performance/downloads/StateMortgagesPercent-30-89DaysLate-thru-2017-03.csv
=> Mortgage performance: Exclude Puerto Rico from exports

cfgov/jinja2/v1/_includes/organisms/mortgage-chart.html, cfgov/unprocessed/css/organisms/mortgage-performance-trends.less, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/actions/chart.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/actions/default.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/chart.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/stores/chart.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/utils.js, package-lock.json, package.json, test/unit_tests/organisms/MortgagePerformanceTrends/actions/chart-spec.js, test/unit_tests/organisms/MortgagePerformanceTrends/actions/default-spec.js, test/unit_tests/organisms/MortgagePerformanceTrends/stores/chart-spec.js, test/unit_tests/organisms/MortgagePerformanceTrends/utils-spec.js
Alrighty @marteki pull this down when you have a second and lmk how it looks. I ended up removing the non-metro `<select>` element and using the same U.S. state element that metros and counties use.
In order to accommodate the different valid U.S. states for metros, non-metros and counties, there are three new fetch methods for each location type that connect to the API and grab a list of valid states.
When toggling between the different location types, it'll attempt to preserve the selected state *if* it's valid for the new location type. E.g. If you're viewing Wyoming's non-metro area and you click the `metro` radio button, it won't preserve Wyoming in the U.S. state dropdown because Wyoming isn't a valid metro area state. It instead resets to the first item in the dropdown.
- Action …
=> Persist U.S. state dropdown above Mortgage Performance line chart

cfgov/jinja2/v1/owning-a-home/mortgage-estimate/index.html, gulp/tasks/styles.js
Fix for oah style reference which is causing build problems
- Moved the base OAH stylesheet up a level so the file references work. 
1. Run gulp styles.
=> Fix for oah style reference which is causing build problems

cfgov/jinja2/v1/owning-a-home/mortgage-estimate/index.html, cfgov/unprocessed/css/apps/owning-a-home/form-resources.less, gulp/tasks/styles.js
Fix for asset references owning-a-home/mortgage-estimate/index.html
- Modified code to adjust asset references.
1. Run gulp build and visit `http://localhost:8000/owning-a-home/mortgage-estimate/`
-
-
=> Fix for asset references owning-a-home/mortgage-estimate/index.html

cfgov/core/tests/test_views.py, cfgov/core/views.py
We seem to be getting a lot of [CSP violation reports](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#Enabling_reporting) that aren't matching our expectations (a valid JSON dictionary, with a top-level 'csp-report'. This change will start logging those reports, giving us some visibility into what might be going on.
They will also raise a more appropriate HTTP status (400), instead of 403.
- Log un-parseable violation reports
- Raise 400 when this happens, instead of 403
=> Log CSP violation parsing failures

cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/chart.js
@higs4281 @marteki Now that we have a new state dropdown we need to hide it when not in use. There's some pretty stupid repetition here but I'll refactor it when I return into an element selecting utility function.
-
-
- Hide state dropdown when not in use.
=> Only show MP state container when necessary

cfgov/jinja2/v1/_includes/organisms/mortgage-chart.html, cfgov/jinja2/v1/_includes/organisms/mortgage-map.html
Our style calls for en dashes in certain range-like usages.
This picks up some hyphens missed in other updates.
=> Mortgage performance: Convert hyphens to en dashes

cfgov/data_research/mortgage_utilities/fips_meta.py, cfgov/data_research/scripts/update_county_msa_meta.py
In refactoring our data-processing pipeline, an update routine for our
global FIPS whitelist got left out. This restores it.
There was also a late decision to exclude Puerto Rico from our charts and maps for launch, and this also ensures Puerto Rico is excluded from metadata references for now.
You can check that the metadata are getting updated by running the update script and checking the API endpoint for state_county_meta:
```
python cfgov/manage.py runscript update_county_msa_meta
```
Then check http://localhost:8000/data-research/mortgages/api/v1/metadata/state_county_meta/ and search for "Bossier"
Bossier Parish's "valid" value should be "false"
=> Mortgage performance: restore whitelist update

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
We are moving this page into wagtail! By default, this PR doesn't change anything. Enable the WAGTAIL_COMPANY_SIGNUP flag to *disable* the existing company-signup page, and allow a wagtail page with that URL to shine through.
- WAGTAIL_COMPANY_SIGNUP
- urls.py changes to accomodate the new flag
- After we've switched this flag permanently , we should remove the 'selfregistration' app.
=> Wrap /company-signup/ page in a feature flag

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_includes/organisms/footer.html
Adds a footer entry and Wagtail flag for Whistleblower content.
1. Run `./runserver.sh`
1. Load http://localhost:8000/ and scroll to the bottom. Verify "Industry Whistleblowers" does not appear next to "CFPB Ombudsman".
1. Go to the Wagtail admin flags interface http://localhost:8000/admin/flags/ and enable `WHISTLEBLOWER_RELEASE`
1. Reload http://localhost:8000/ and verify "Industry Whistleblowers" now appears in the footer.
=> Whistleblower footer

cfgov/legacy/templates/students/index.html
Removing wp-content reference from /students page
- Modified `Removing wp-content reference from /students page` to remove `wp-content` reference.
=> Removing wp-content reference from /students page

cfgov/cfgov/settings/base.py
We no longer use sheer sites for "Fin Ed Resources" and "Know before you owe"
- two SHEER_SITES entries
=> Remove unused SHEER_SITES entries

requirements/optional-public.txt
This commit bumps the optional [regulations-site](https://github.com/cfpb/regulations-site) package from version 2.1.11 to 2.1.12. This fixes a minor issue with missing diffs.
- Bump regulations-site from version 2.1.11 to 2.1.12.
=> Bump regulations-site from 2.1.11 to 2.1.12

cfgov/unprocessed/js/organisms/EmailPopup.js
Fixing issue with double require for email popup module
- Modified code to require `email-popup-helpers` only once. 
1. Run gulp build and visit `http://localhost:8000/owning-a-home/mortgage-estimate/` and ensure email popup only runs once.
=> Fixing issue with double require for email popup module

cfgov/jinja2/v1/_includes/molecules/info-unit-2.html
Currently if the info unit link points to an outside resource it creates
an interstitial page warning the user they are leaving the site. The
linked image and heading were not getting that interstitial url and were
directing the user to the outside resource without warning.
- Updated the template to parse the links prior to outputting them.
1. Create a page with an 25/75 info unit and set the link to an outside resource (ex: a YouTube video). Note that the url printed to the page includes our interstitial page (https://www.consumerfinance.gov/external-site/)
=> Correctly output info unit image and heading links

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_layouts/base.html
To reduce the first paint time of the page we should reduce the size of the HTML page (see https://[GHE]/CFGOV/platform/issues/1824). Removing unused code comments is a way to do this. When we're not recruiting for a fellowship we don't need to show this code block. This flag could also be used to show other recruitment campaigns across the site.
- Adds a feature flag `CFPB_RECRUITING` for showing or hiding the recruitment code comment in the base template's HTML source.
1. Visit the site locally and view the source. There should be no recruitment code comment at the top.
2. Log into /admin Wagtail locally and set `CFPB_RECRUITING` flag boolean to true.
3. Re-visit site locally and view the source. There should be a recruitment code comment.
I think this can be off in production? We're …
=> Add feature flag for recruitment code comment

cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_layouts/base.html
Part of the effort to reduce the HTML page size (
https://[GHE]/CFGOV/platform/issues/1824).
- Moves code comments to server-side jinja comments so they aren't delivered into the HTML to production.
1. Run the site locally and view source and see that their aren't code comments in the output HTML anymore.
=> Move code comments to the server

package-lock.json, package.json
Release notes for package update: https://github.com/cfpb/cfpb-chart-builder/releases/tag/v3.2.0
- Bump cfpb-chart-builder version to 3.2.0 
1. Run `npm install` && `./frontend.sh`.
=> Bump cfpb-chart-builder version to 3.2.0

cfgov/alerts/github_alert.py, cfgov/alerts/logging_handlers.py
This PR changes the `GitHubAlert.post` to take an optional `labels` kwarg, and the logging handler to use that kwarg to assign the `logging` label instead of `alert`. This is because, as we've seen, some logged issues are not singularly actionable, instead they are all related to the same single problem. This is contrary to our alert policy, where we want each individual alert to be actionable. The practical effect of this is that a large number of issues opened by the logging handler obscures other issues when filtering for "alert" (and makes it very difficult, at least for me, to find other alert issues I'm looking for). Thus I am proposing that we open logged issues with a different tag, `logging`. 
This PR is currently based on #3516, when that PR is merged I'll rebase to master. …
=> Differentiate GHE issues posted via logging from alerts

test/unit_tests/apps/financial-well-being/fwb-questions-spec.js
JSDOM does not allow for a form to be submitted and will throw an error.
To avoid any issues we've prevented it from submitting. This change
relocates that code outside of the button click handler and expands on
the comment to make it clearer they are unrelated and that the submission
handler is an outside necessity.
- Relocated the form submission handler
1. Run `gulp test:unit`
=> Clean up form submission handler in test

cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/chart.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/map.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/utils.js, test/unit_tests/organisms/MortgagePerformanceTrends/utils-spec.js
To improve the readability of the trend chart when browsing counties we're adding the state abbreviation after county names. See https://GHE/CFGOV/mortgage-performance/issues/212
- Util function to get state abbreviation from county FIPS code.
- Append state abbreviation to trend chart title when in county mode.
1. `./front-end.sh`
1. Go to http://localhost:8000/data-research/mortgage-performance-trends/mortgages-90-or-more-days-delinquent/
1. Select `County` location type and see if the chart title shows the state's abbreviation.
Before:
After:
-
-
=> Append U.S. state abbreviation to county chart title

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_layouts/base.html, config/webpack-config.js, package-lock.json, package.json
To decrease the time to first paint of the page, we should aim to reduce the HTML page size. One step to doing that is removing the inlined JS. (Part of https://[GHE]/CFGOV/platform/issues/1824).
- `banner-footer-webpack-plugin` plugin.
- Removes inlined JS and moves it instead to external JS asset requests.
1. `./frontend.sh` and check
http://localhost:8000/about-us/careers/current-openings/ for testing template-level script (single.js)
http://localhost:8000/ask-cfpb/ for testing page-level script (index.js)
http://localhost:8000/about-us/the-bureau/bureau-structure/ for testing on-demand script (on-demand/bureau-structure.js)
**Note: I don't think you need `./cfgov/manage.py collectstatic`, but try that if the scripts 404.
HTML byte size before:
HTML byte size after:
=> Move inline JS to external requests

cfgov/v1/atomic_elements/organisms.py
- Modified  `cfgov/v1/atomic_elements/organisms.py` to move the Media class to the TableBlock class. 
- This is needed due to the current bug with assigning atomic components to the page.media property. PR #3551 fixes that issue so we should no longer have random Table.js camping out on our pages.
=> Moving the Media class to the TableBlock class

cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py, cfgov/v1/tests/test_meta_image.py
This change fixes some logic that was trying to include StreamField child block media. We want pages to include all child block media (block-specific JavaScript files) for any blocks that are on the page, but the existing logic includes any files for any blocks that could possibly be on the page.
This change leverages some logic in [wagtail-inventory](https://github.com/cfpb/wagtail-inventory) that lists the block types on a page, instead of incorrectly pulling in all possible child blocks of a parent block.
A few unit tests had to be changed because using `model_mommy.prepare` on Wagtail page types doesn't properly set the Django contenttypes id, which breaks use of `page.specific`.
This addresses the first issue in GHE#1264.
- Fix logic in `v1.models.base._add_streamfield_js` to …
=> Only include StreamField media for existing blocks

tox.ini
Adding tox environment for testing asset validation
- Modified `frontend.sh` to add a `dry-run` function.
1. Run `tox -e validate-assets -v` and hope you don't see `[object object]`.
2. You can run `tail -f ` on the log file to check the dependency build cycle.
-
-
=> Adding tox environment for testing asset validation

cfgov/ask_cfpb/models/pages.py, cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/jinja2/v1/_layouts/base.html, cfgov/v1/models/base.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/browse_page.py, cfgov/v1/models/learn_page.py, cfgov/v1/tests/models/test_base.py
This change flattens the `@media` property on `CFGOVPage` to return a simple list of JavaScript filenames instead of a dictionary. The dictionary keys were never used downstream in the template, so maintaining them serves no purpose and makes it harder to test for files by checking for an empty dictionary.
This change also slightly cleans up the class methods around this functionality, converting `CFGOVPage.add_page_js(js)` (which adds to a dictionary) into `CFGOVPage.page_js` (which just returns a list).
Several Ask CFPB classes and tests had to be modified for this; pinging @higs4281 for a quick review.
Note that this change somewhat strengthens the existing requirement that page/block JS filenames have to be globally unique.
- Cleanup of page media into simple list.
1. See new/changed …
=> Flatten CFGOVPage.media from dict to list

requirements/optional-public.txt
This commit bumps the optional regulations-site requirement from version 2.1.12 to [version 2.1.13](https://github.com/cfpb/regulations-site/releases/tag/2.1.13), to support more robust handling of section names.
- Version bump to regulations-site.
=> Bump regulations-site version to 2.1.13

config/webpack-config.js
Fix for charts not rendering on IE
- Fixes issue with charts not rendering on IE due to ES6 features in the build. Not sure why Babel doesn't run after the Uglifier but I will investigate.
- Run `gulp build`
- Visit `localhost:8000/data-research/mortgage-performance-trends/mortgages-30-89-days-delinquent/` and ensure it works on IE.
=> Fix for charts not rendering on IE

requirements/optional-public.txt
Bumps requirement for `owning-a-home-api` to 0.10.1
=> Bump OAH-api to 0.10.1

cfgov/core/tests/test_views.py, cfgov/core/views.py, cfgov/data_research/handlers.py, cfgov/data_research/tests/test_handlers.py, requirements/base.txt
This updates the govdelivery python package to 1.1, and takes advantage of the [new](https://github.com/cfpb/govdelivery/pull/1) ability to set send_notifications on calls to set_subscriber_topics (resolving a stakeholder concern, since they expected that notifications WERE being set)
- govdelivery updated in requirements/base.txt
- calls to set_subscriber_topics now include send_notificiation=True
=> Send notifications to govdelivery subscribers

package-lock.json, package.json
Because it was set to `"dev": true` in `package-lock.json`, gulp-changed was not getting installed when the `--production` flag was used in our Jenkins build jobs, causing the build to fail.
- gulp-changed removed from `devDependencies`
1. Merge and see that the next build job works
=> Remove duplicate gulp-changed dependency

requirements/optional-public.txt
This commit updates the optional regulations-site package from version 2.1.13 to new release ~~[2.1.14](https://github.com/cfpb/regulations-site/releases/tag/2.1.14)~~ [2.1.15](https://github.com/cfpb/regulations-site/releases/tag/2.1.15), which fixes an issue with mishandled URLs.
- Bump regulations-site version.
=> Update regulations-site to version 2.1.15

cfgov/unprocessed/css/enhancements/forms.less, cfgov/unprocessed/css/enhancements/notifications.less, cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/organisms/well.less, cfgov/wellbeing/jinja2/wellbeing/home.html
The FWB assets were living on their own within the app code instead of
the main cfgov assets. Tidied up the code and utilized existing asset
code where possible. Could still use some more more optimization before
moving the scale code to Capital Framework as well as a discussion about
the flush well styles.
- `o-well__flush` to pull a well left and right
- `o-well__stacked` to allow multiple wells to be stacked without spacing between them
- `o-scale` to control the default form element layouts within the wells
- `m-notification__subtle` to create less "in your face" notifications
1. Navigate to `http://localhost:8000/consumer-tools/financial-well-being/`, observe zero visible changes compared to `https://www.consumerfinance.gov/consumer-tools/financial-well-being/`
- I …
=> Move the FWB assets into the main cfgov assets

cfgov/ask_cfpb/search_indexes.py, cfgov/ask_cfpb/views.py, cfgov/cfgov/settings/base.py, cfgov/search/backends.py, cfgov/search/fields.py, cfgov/search/tests/test_backends.py, cfgov/search/tests/test_fields.py
This PR adds spelling suggestion support to the search backend of Ask CFPB (not yet used in the front-end) and support for hardcoded synonyms (with no synonyms defined yet) to Ask CFPB search. This is a first-step to support for spelling suggestions and synonym support for users of Ask CFPB search.
To provide synonym support based on Elasticsearch's synonym analyzer this PR adds a separate `search` package that includes a custom Elasticsearch Haystack backend that supports custom index settings and fields that specify analyzers other than the default analyzer. It also adds a `CharFieldWithSynonyms` field for Haystack indexes that uses a `"synonym"` analyzer that's specified in the settings.
- `search` package
- Custom `search.backends.CFGOVElasticsearch2SearchEngine` Haystack backend …
=> Add spelling suggestions and hardcoded synonym support to Ask CFPB search

mac-virtualbox-init.sh
This was somehow didn't make it with #3106 : this allows the application to be reached at localhost:8000, when running in docker-compose + docker-machine.
Without this, you would need to get the IP of the docker machine (`docker-machine ip`), and access the app there
- mac-virtualbox-init.sh now includes commands that map localhost:8000 to port 8000 on the docker machine VM.
1.
-
-
=> Re-add port forwarding localhost:8000

cfgov/jinja2/v1/_includes/ask/ask-search-bar.html, cfgov/jinja2/v1/_includes/organisms/search-bar.html, cfgov/jinja2/v1/ask-cfpb/answer-search-results.html
This PR adds `value.q` to the search bar organism so that the search bar can be pre-populated with a previous search query and uses that value in the Ask CFPB search bar for that exact purpose.
=> Include the previous query in the Ask CFPB search box

.gitignore, attach.sh, docs/installation.md, docs/usage.md, runserver.sh, setup.sh, shell.sh
This PR makes a few tweaks to our (wonderful) docker local development setup.
- Adds `eval $(docker-machine env)` to shell.sh and attach.sh in case the user forgets to run it (as I frequently find myself doing)
- Adds `.python_env` to `.gitignore`
- Adds a `docker` argument to `setup.sh` and `runserver.sh` to allow them to still be used for setup and running.
- Adds the ability to run a command directly with `shell.sh`, i.e. `./shell.sh cfgov/manage.py migrate`
- Fixes the link to the usage document in the installation instructions
- Fixes the comment formatting in the `.gitignore` file
- Updates the documentation for the above changes.
=> Tweak Docker setup for local development

CONTRIBUTING.md, config/browserList-config.js, config/environment.js, config/webpack-config.js, gulp/tasks/styles.js
As part of the FEWD Browser Support Working Group we have been
re-evaluating what browsers we're supporting. We had agreed to use a
browserlistrc file to track our needs, but as we looked closer we
realized our build process is broken up by browser and would necessitate
a complex browserlistrc setup.
- Converted browser config to a new separate config file.
- Reduced configs to only those necessary (many browsers are included in
"last2").
- Added human readable browser support notes to contributing doc.
1. Run `gulp clean`
1. Run `gulp scripts:ondemand`
Everything should build and none of the site styles or interactions should differ in any browsers.
- Explore whether the IE nemo and ondemand tasks are still necessary and if they are, can IE 9 be bundled with IE 8.
=> Update the browser list config and support documentation

config/browser-list-config.js, config/webpack-config.js, gulp/tasks/styles.js
Steven pointed out that the constants should be formatted in caps with
underscore separators.
1. Run `gulp clean`
1. Run `gulp scripts:ondemand`
Everything should build and none of the site styles or interactions should differ in any browsers.
=> Correct the naming conventions for the browser list config

cfgov/jinja2/v1/_includes/article.html, cfgov/jinja2/v1/_includes/molecules/related-metadata.html, cfgov/jinja2/v1/_includes/organisms/item-introduction.html, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/events/_event-detail.html, cfgov/v1/__init__.py, cfgov/v1/models/base.py, cfgov/v1/tests/util/test_ref.py, cfgov/v1/util/ref.py
This PR attempts to clean up some of the code around related modules by
- Moving functions onto the CFGOVPage class when possible, instead of as helper functions
- Rewriting `related_posts` so that it's more readable. Does not change functionality 
All tests still pass
=> Refactoring related modules for readability and usage

cfgov/unprocessed/css/main.less, docs/installation.md
Flips switch for `@use-font-cdn` so production pulls from self-hosted fonts, not fonts.net.
- Flips switch for `@use-font-cdn` to false, so that in production fonts are pulled from consumerfinance.gov/static/fonts
2. Check the site in localhost.
3. Check JS console to see that fonts are trying to be loaded from localhost.
4. ~~Contact @anselmbradford @Scotchester to get the fonts so you can install them locally.~~ ~~Download them from [GHE]/CFGOV/cfgov-fonts/~~
5. ~~Place font files in /cfgov/static_built/fonts~~
6. cd `/static.in/`
7. `git checkout [GHE]/CFGOV/cfgov-fonts/`
8. Restart the server.
9. Visit the page and see that the fonts load locally.
-  ~~You'll need tokeep the fonts handy in a directory other than cfgov-refresh, as `gulp clean` will wipe out …
=> Turn on self-hosted fonts

cfgov/cfgov/settings/production.py
If the python `next` operator has a default value, the generator statement must have parens around it.
=> Parenthizes `next` generator statement

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, requirements/optional-private.txt
The functionality of this app has been replaced by a Wagtail page and a PDF:
https://www.consumerfinance.gov/company-signup/
- the 'selfregistration' app.
- related settings and urls.py entries.
=> remove selfregistration app

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, cfgov/core/tests/test_views.py, cfgov/core/views.py
This never actually worked for us in production, and nobody seems to be poorer for not having that data. Exposing a URL that would allow arbitrary outside parties to log arbitrary (if correctly formatted) data to our server, also seems like a recipe for trouble.
This doesn't change the front-end experience of CSP: violations will still be logged to the javascript console
- views, tests, and configuration around Content Security Policy server-side logging.
-
1.
-
-
=> remove server-side CSP reporting

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
- Modifying menu to remove `The CFPB: Working for you` section
1. Visit `http://localhost:8000/` and verify the menu renders correctly.
-
=> Modifying menu to remove `The CFPB: Working for you` section

cfgov/unprocessed/css/organisms/bureau-structure.less
- Modified css to fix visual issues with the Bureau Structure on mobile.
1. Visit `http://localhost:8000/about-us/the-bureau/bureau-structure/`
and verify it looks as depicted below.
Before:
After:
-
-
=> Fixes for the Bureau Structure on mobile

cfgov/jinja2/v1/_includes/macros/activity-snippets.html, cfgov/v1/forms.py, cfgov/v1/models/base.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/models/sublanding_page.py, cfgov/v1/templatetags/activity_feed.py, cfgov/v1/tests/models/test_browse_filterable_page.py, cfgov/v1/tests/models/test_sublanding_page.py, cfgov/v1/tests/templatetags/test_activity_feed.py, cfgov/v1/tests/test_filterable_list_form.py, cfgov/v1/util/filterable_list.py, cfgov/v1/util/util.py
At some point we needed `hostname` in these functions, but we no longer do, so just doing a bit of clean-up.  Also removing two functions `get_next_appropriate_siblings` and `get_prev_appropriate_siblings` that don't appear to be used anywhere. 
Tests still pass.
=> Remove unused hostname from params & unused functions

cfgov/jinja2/v1/_includes/article.html, cfgov/jinja2/v1/_includes/macros/category-slug.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/jinja2/v1/_includes/organisms/item-introduction.html, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/_includes/tags.html, cfgov/jinja2/v1/activity-log/_activity-list.html, cfgov/jinja2/v1/activity-log/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/v1/models/base.py, cfgov/v1/models/sublanding_page.py, cfgov/v1/tests/models/test_sublanding_page.py, cfgov/v1/tests/test_filterable_list.py, cfgov/v1/util/filterable_list.py
At some point, we were supporting multiple filter controls on the same page, thus the need to assign them a form ID and ensure each form displays their respective data. However, we do not appear to have any pages with multiple filterable forms on them, and more importantly, if we were to, this doesn't work as intended -- the logic for how we append the form ID to authors vs. tags is in different places and actually results in different numbers (when you have multiple filterable forms).  For tags, we were always grabbing the index of the first filter controls on the page (regardless of if there were others), and for authors, we were grabbing the index of the block it's in directly within the template.  That's just one example -- this code was incredibly complex and supporting a use case we …
=> Remove misleading form_id from filterable params

runserver.sh
This PR adds a sourcing of `mac-virtualbox-init.sh` to `runserver.sh` so that when we run `./runserver.sh docker`, the docker machine is up and running and the env vars are `eval`ed and everything.
=> Ensure docker is setup before running

cfgov/v1/models/base.py
This fixes a bug we're seeing right now on the newsroom page - you can replicate it locally by going to this page /about-us/newsroom/?form-id=0&filter0_title=&filter0_topics=mortgage-origination&filter0_from_date=&filter0_to_date= on master, on production it will just 500.
I was planning to do a different fix, in which we get the filter page by directly getting the page we're on (and removing `get_filter_data` altogether), however it's a little more complicated than that because this code isn't only called on the newsroom and blog pages.   In the meantime I'm just reverting the change that I thought would be harmless from a recent refactor: https://github.com/cfpb/cfgov-refresh/pull/3589
=> Bug fix - Call get_site() on filter_page only if filter_page is not None

cfgov/cfgov/settings/base.py
I noticed that the our CSP whitelist wasn't allowing the federal register API to work here:
https://www.consumerfinance.gov/eregulations/
This adds the domain to our whitelist.
- 'www.federalregister.gov' is added to the CSP script whitelist
-
-
=> Add www.federalregister.gov to CSP script whitelist

cfgov/jinja2/v1/_includes/organisms/bureau-structure.html
Modified button label text to say `PDF` instead of `PNG`.
=> Fix button label text to reflect correct file type

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, cfgov/jinja2/v1/_includes/organisms/table.html, cfgov/wellbeing/tests/test_views.py
These two feature flags are no longer necessary and can be removed.
- `SORTABLE_TABLES` flag and it's associated code
- `FWB_RELEASE` flag and it's associated code
1. All tests should continue to pass
=> Remove old feature flags

cfgov/agreements/tests/test_management.py
The original tests made assumptions about the order that agreements are imported in, which don't seem to always hold.
- tests made a little more robust
1.
-
-
=> make agreements tests less sensitive to os.walk order

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
The Financial Coaching pages are approaching release and require
navigation to allow users to get to them. Hiding the menu item behind a
feature flag allows us to turn it on when the pages are published.
- Updated the list of available feature flags for Financial Coaching
- Updated the menu variables to conditionally add the Financial Coaching menu item when the feature flag is enabled.
1. Turn on the feature flag
2. Confirm the "Financial Coaching" item falls under Practitioner Resources -> Programs
- It's probably time to clean out some of these flags. I'm going to submit another PR doing that to keep this scope on point.
=> Add the Financial Coaching link to the mega menu

cfgov/jinja2/v1/_layouts/base.html, package-lock.json, package.json
- Add fonts.net tracker to footer.
- Needed after https://github.com/cfpb/capital-framework/pull/698 is merged, CF is released and CF is updated in this PR.
=> Moves fonts.net tracking code to footer

requirements/optional-private.txt, requirements/optional-public.txt
We've released 'comparisontool' as open source. This PR removes it from 'optional-private.txt', and adds it to 'optional-public.txt'
- add https://github.com/cfpb/django-college-costs-comparison/releases/download/1.5.1/comparisontool-1.5.1-py2-none-any.whl to optional-public.txt
-  remove comparisontool from optional-private.txt
-
-
=> Use the open source release of 'comparisontool'

requirements/optional-public.txt
Bump OAH API version, switch to wheel deployment and pick up a tweak to assist request troubleshooting.
- Adds a `raise_for_status` check to help identify cases where an external request is rejected.
=> bump oah api to 0.10.2 and switch to wheel deployment

cfgov/jinja2/v1/_includes/article.html, cfgov/jinja2/v1/_includes/macros/category-slug.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/jinja2/v1/_includes/organisms/item-introduction.html, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/_includes/tags.html, cfgov/jinja2/v1/activity-log/_activity-list.html, cfgov/jinja2/v1/activity-log/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/jinja2/v1/newsroom/index.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/v1/models/base.py, cfgov/v1/models/sublanding_page.py, cfgov/v1/tests/models/test_sublanding_page.py, cfgov/v1/tests/test_filterable_list.py, cfgov/v1/util/filterable_list.py
See https://github.com/cfpb/cfgov-refresh/pull/3603 for context -- I had merged that PR but then noticed a bug, so had to revert it.  I'm creating a new commit/ PR here (with the fix) since git otherwise doesn't handle reverting reverts smoothly.
Though the change is limited in scope to removing form_id from filterable params, this touches a lot of files that pass it around (and not always in an obvious way, for instance the bug I hadn't noticed before was that the `render` method on `organisms/filterable-list-controls.html` was still being passed a form ID from `newsroom/index.html`, but it's referred to as `flc` in many places and the form ID might be passed around as a `loop.index` or something like that.  Basically, the code in question is brittle and I don't have a lot of confidence …
=> Remove form_id from filterable params

requirements/optional-public.txt
This version contains the Swagger/Open API specification for the API.  It is available at the `<ccdb5-api>/docs` endpoint
=> Update CCDB5 API release number

cfgov/v1/feeds.py
Forgot to update this when updating related code in https://github.com/cfpb/cfgov-refresh/pull/3628.  Currently causing an error on  /about-us/blog/feed/.
=> Hotfix: Page sets is now page set

cfgov/v1/models/base.py
Somehow a line that got removed here https://github.com/cfpb/cfgov-refresh/pull/3621/files made its way back in, in a merge yesterday https://github.com/cfpb/cfgov-refresh/commit/f89dde83c6259a5dbb968bfdb53125703cdaef36#diff-8e8a3e28d46ee12516bea4f5b50bf5a4R209.  Fixing that.
=> Hotfix: Remove duplicate line in related_metadata_tags

requirements/base.txt
The main change here is that the `path` condition (which checked that a path started with a particular string) has changed to `path matches`, and accepts a regular expression to check the path against.
=> Update wagtail-flags to 2.0.7

cfgov/v1/models/base.py
Editors helped us discover a combination of page tags and the use of
"match-all-topic-tags" that locked up mysql. The offending query
was a string of filter queries, one for each page tag,
appended to a query composed of Q objects.
This here attempt uses Python sets instead of SQL to determine
whether all tags are shared.
Previously you could replicate the mysql lockup this way:
- With recent prod data, edit page at `/admin/pages/10848/edit/`
- Restore the revision from Oct 18 (12:12 p.m.)
- Choose the "match-all-topic-tags" box in the sidebar tab
- Save draft and preview, or publish ad view the live page
You could also replicate the crash with the most recent version of
10848:
- Edit the page and make sure it still has at least 9 tags listed
in the configuration tab
- Choose …
=> Stopping mysql lockups, take 2

cfgov/cfgov/settings/local.py, cfgov/cfgov/settings/production.py
This change modifies the two eRegs caches (`eregs_longterm_cache` and `api_cache`) so that they use the passthrough cache instead of a disk-based cache. These two caches are required by the optional [regulations-site](https://github.com/cfpb/regulations-site) app. Unfortunately that app requires that these caches be defined (including with a `TIMEOUT`) parameter and doesn't handle the fallback case where they aren't.
eRegs pages don't need to be specially cached to disk because the typical production deployment of cfgov-refresh has a comprehensive cache sitting in front of it. These caches thus add complexity without adding any benefit.
This change also modifies the `default` cache so that it uses Django's default of in-memory, instead of disk (if you don't define any caches at all, [you …
=> Deprecate file cache for eRegs and default caches

cfgov/agreements/management/commands/import_agreements.py, cfgov/agreements/management/commands/util.py, cfgov/agreements/tests/test_management.py
This change removes a `print` statement that was getting called in unit tests. As of #3381 the agreements app was moved into cfgov-refresh, but one of those unit tests included a `print` statement.
This change modifies those tests so that the management command instead does the logging, and respects its `verbosity` option to enable/disable the logging.
A new unit test has been added to verify that the print statement is properly called by the command.
- Small logic change to agreements unit tests to properly handle logging of S3 uploads.
1. `tox -e fast` and behold the nice output of dots without any print statements.
=> Remove print statement in agreements tests

.env_SAMPLE, .python_env_SAMPLE, Dockerfile, cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, cfgov/jinja2/v1/search/results.html, cfgov/search/dotgov.py, cfgov/search/tests/test_dotgov.py, cfgov/search/tests/test_views.py, cfgov/search/urls.py, cfgov/search/views.py
This PR is a start at building a wrapper around the Search.gov API to use for search. It adds to the `search` package a module that wraps the Search.gov search and typeahead APIs. It also adds two settings and env vars for the Search.gov affiliate name and our API key, as well as a stub view and template for search results and a feature flag that enables that view. Completing the view and template are not in scope for this PR, but they provide a starting point for using the API wrapper.
I've also added a `.python_env_SAMPLE` file for use with docker that corresponds to `.env_SAMPLE`. This is based on discussions with @rosskarchner.
- Search.gov API wrappers in `search.dotgov`
- Search results view and template stubs
- Sample `.python_env` file corresponding to `.env_SAMPLE` for our docker …
=> Wrapper around the Search.gov API

cfgov/jinja2/v1/es/comprar-casa/index.html, cfgov/jinja2/v1/es/es-base.html
The standard Spanish pages don't need the styles in `es-ask-styles`, and some recent changes to it have messed up a lot of styles on those standard pages.
- Removes Spanish Ask CFPB stylesheet from the base template for Spanish pages. Does not affect Spanish Ask CFPB pages.
1. Pull branch
1. Visit http://localhost:8000/es/ and see that the styling matches https://web.archive.org/web/20171208025835/https://www.consumerfinance.gov/es/
- Note: Some links have moved from the hero to the third column. That is expected. The only thing to observe is that the styles have returned to what they were before today's deployment.
1. Visit the other pages (excluding Obtener Respuestas) and see that nothing looks weird
=> Remove Spanish Ask CFPB stylesheet from non-Ask pages

.eslintignore, cfgov/unprocessed/js/modules/polyfill/class-list.js, cfgov/unprocessed/js/routes/about-us/careers/current-openings/index.js, cfgov/unprocessed/js/routes/ask-cfpb/single.js, cfgov/unprocessed/js/routes/common.js, cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/index.js, cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/results/index.js, cfgov/unprocessed/js/routes/es/obtener-respuestas/single.js, cfgov/unprocessed/js/routes/external-site/index.js, cfgov/unprocessed/js/routes/on-demand/ask-autocomplete.js, cfgov/unprocessed/js/routes/on-demand/bureau-structure.js, cfgov/unprocessed/js/routes/on-demand/chart.js, cfgov/unprocessed/js/routes/on-demand/email-signup.js, cfgov/unprocessed/js/routes/on-demand/expandable-group.js, cfgov/unprocessed/js/routes/on-demand/expandable.js, cfgov/unprocessed/js/routes/on-demand/feedback-form.js, cfgov/unprocessed/js/routes/on-demand/filterable-list-controls.js, cfgov/unprocessed/js/routes/on-demand/footer.js, cfgov/unprocessed/js/routes/on-demand/header.js, cfgov/unprocessed/js/routes/on-demand/mortgage-performance-trends.js, cfgov/unprocessed/js/routes/on-demand/notification.js, cfgov/unprocessed/js/routes/on-demand/secondary-navigation.js, cfgov/unprocessed/js/routes/on-demand/table.js, cfgov/unprocessed/js/routes/on-demand/video-player.js, cfgov/unprocessed/js/routes/owning-a-home/common.js, cfgov/unprocessed/js/routes/owning-a-home/mortgage-estimate/single.js, cfgov/unprocessed/js/routes/owning-a-home/single.js
- `.eslintignore` file.
- Runs autofix linting options on /route/ and class-list scripts.
2. Site should not have any errors in the console in IE9.
- I discovered `<!--[if IE 9]>` doesn't trigger in Browser Mode: IE9 Compatibility View, but does in Browser Mode: IE9. Also, our logo is blown up in Browser Mode: IE9. Anyone up on which is the default?
=> Remove ESLint ignore file

cfgov/unprocessed/js/organisms/MegaMenu.js, gulp/tasks/styles.js
There is a bug in IE9 (non-compatibility mode, which I believe is the default?) where the resize event will fire unexpectedly, causing the mobile menu to get stuck showing on load at mobile sizes. I believe this is because IE9 fires the resize event on resize of any elements on the page, not just the whole window. Instead of hacking around that, this PR turns off the mobile responsive view for IE9, like we do for IE8.
- Disable mobile responsive view for IE9-.
1. `gulp build` and check IE9 at mobile window sizes and observe it's still the desktop menu.
Before:
After:
=> No mobile view on IE9

cfgov/unprocessed/js/routes/common.js, cfgov/unprocessed/js/routes/es/obtener-respuestas/single.js, cfgov/unprocessed/js/routes/owning-a-home/common.js
Functions shouldn't be defined inside if statements, https://github.com/cfpb/cfgov-refresh/pull/3675, moved `sendEvent` to top-level, but forgot to restructure so that the variables it referenced were passed in.
- Passes in parameters for `sendEvent` analytics in spanish.js
1. `gulp scripts:spanish`
2. Should not have JS errors in console on /es/obtener-respuestas/como-puedo-consultar-el-saldo-de-mi-tarjeta-prepagada-es-503/
=> Fix for variable reference on spanish.js

cfgov/unprocessed/js/modules/util/email-popup-helpers.js
IE doesn't support Object.assign
- Modified code to use the utility function instead of `Object.assign`.
1. Run `gulp scripts`.
2. Visit `https://www.consumerfinance.gov/owning-a-home/` in IE.
3. Scroll to the bottom of the page and check for errors in the console.
-
-
=> Fix for object.assign in IE

cfgov/alerts/post_sqs_messages.py, cfgov/alerts/tests/test_post_sqs_messages.py
This change modifies how Mattermost alert failures are handled as part of the SQS alert consumption process.
Currently, when an alert is read off of an incoming SQS queue, the process goes like this:
1. Peek at alert on top of queue.
2. Post alert to GH.
3. Post alert to MM.
4. Delete alert from queue.
If Mattermost happens to be down (as happened recently) and an alert comes it, it'll be repeatedly posted over and over to GH, because a failure at step 3 prevents alert cleanup at step 4.
This change catches exceptions from MM posts and logs them, instead of allowing the alert to exit the process.
In practice that means that if this script is run from e.g. Jenkins the Jenkins job will not fail just because MM is down.
- Logic in [`alerts.post_sqs_messages.process_sqs_message`](https://githu …
=> Mattermost alert failures shouldn't be fatal

cfgov/cfgov/settings/base.py
We shouldn't be exposing the write API to eRegs publicly.
- Don't include the `regcore_write` API.
=> Disable regcore_write API

package-lock.json, package.json
The update to imagemin-svgo was optimizing the logo in an undesirable way by making it scale twice as large in IE9. @Scotchester is looking at revamping the approach to the logo overall in https://github.com/cfpb/cfgov-refresh/tree/remove_svg_logo
- Downgrade imagemin-svgo from 6.x to 5.x
=> Downgrade imagemin-svgo

cfgov/v1/models/sublanding_page.py, cfgov/v1/util/categories.py
This change modifies the logging in two places where pages get filtered. ~~Right now these filters get logged at the `INFO` level, which means they go to the console and log files by default.~~
~~This fills up the logs with filtering every time a filter is chosen, which seems overly verbose. If we want these to be logged, could we instead log them to `DEBUG`?~~ Per feedback from @richaagarwal below, I'm just removing these logging statements.
- ~~Reduce filter logging from INFO to DEBUG.~~ Remove filter logging.
=> Remove logging of page filtering

.travis.yml
This re-arranges our Travis yml to use the [build stages feature](https://docs.travis-ci.com/user/build-stages/), and adds config to generate our documentation and push it to https://cfpb.github.io/cfgov-refresh/ on every merge to master.
Build stages are necessary, so that the deploy only runs once, if the three testing jobs pass.
- deployment configuration
- adapt config to Travis's "build stages" feature.
- Moved the 'addons: chrome' declaration to the acceptance test job. This should make builds a bit faster, since Chrome will only be installed for the acceptance tests (it was previously running even on the backend tests, [for example](https://travis-ci.org/cfpb/cfgov-refresh/jobs/317128510))
Check any build from this PR to see build stages in action: …
=> Push docs to gh-pages on every merge to master

.travis.yml
PR #3688 contained a flaw, where the documentation deployment job didn't have access to the 'site' directory created in the documentation *build* job.
This should merge the two into a single job (I hope)
It seems to work, but (again) we can't tell for sure until it's merged: https://travis-ci.org/cfpb/cfgov-refresh/jobs/318150030
-
=> Travis: merge documentation build and deploy stages

requirements/optional-public.txt
This change bumps the version of the optional complaint requirement from 1.4.4 to [1.4.5](https://github.com/cfpb/complaint/releases/tag/1.4.5).
This removes some deprecated processing that was spamming the error log with harmless (but useless) errors.
- Bump the complaint app to 1.4.5.
=> Bump optional complaint requirement to 1.4.5

cfgov/ask_cfpb/tests/test_views.py, cfgov/ask_cfpb/views.py, cfgov/jinja2/v1/ask-cfpb/answer-search-results.html, cfgov/jinja2/v1/ask-cfpb/answer-search-spanish-results.html, cfgov/legacy/static/knowledgebase/less/es-ask-base.less
Ask CFPB search used to 404 if you didn't provide a search term. This PR is an attempt to fix that and prompt users to enter a search term.
- Prompt for an Ask CFPB search term instead of 404ing when none is given
=> Add prompt to Ask CFPB to enter search term if not given

.travis.yml
Due to issues with the acceptance tests hanging and other quirks, I'm disabling them until I can better analyze the issues surrounding their usage.
=> Disabling acceptance testing on Travis

cfgov/jinja2/v1/_layouts/base.html
It was possible for scripts to load before common.js, leading to an error that webpack's loader was not found.
- Makes template, component, and page-level scripts load within a callback after common.js load.
2. check blog and see that page has three scripts injected into the head: common, email-signup, and filterable-list-control.
=> Defer all scripts to after common.js load

requirements/optional-public.txt
This bumps the oahapi version to 0.10.3 for an annual update
=> Update owning-a-home-api release

cfgov/cfgov/settings/base.py, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py
This PR enables us to serve specific page primary keys specified in settings on beta.consumerfinance.gov. This is intended to be as non-invasive as possible as we come up with a more long-term solution for previewing content.
- `SERVE_LATEST_DRAFT_PAGES` added to settings and page pk 1288 configured on beta
- `serve_latest_draft_page` wagtail hook added that consumes `SERVE_LATEST_DRAFT_PAGES`
This code is all @chosak's. I'm just an ape swinging from git branch to git branch.
=> Serve latest draft page for specific pages via a wagtail hook on beta

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
This change defines a new feature flag, `WAGTAIL_SERVICEMEMBERS`, to serve two pages from Wagtail instead of from Django.
Without the flag, visiting the pages:
`/practitioner-resources/servicemembers/`
`/practitioner-resources/servicemembers/webinars/`
will be served by Django. With the flag defined and enabled, these will be served by Wagtail.
- New `WAGTAIL_SERVICEMEMBERS` flags, with no conditions defined.
1. Run a local server.
2. Create new Wagtail pages at `/practitioner-resources/servicemembers/` and `/practitioner-resources/servicemembers/webinars/`.
3. Visit http://content.localhost:8000/practitioner-resources/servicemembers/ and http://content.localhost:8000/practitioner-resources/servicemembers/webinars/ to see the legacy Django pages.
4. In the admin, define a new condition …
=> Add flag for servicemember pages in Wagtail

cfgov/cfgov/settings/base.py, requirements/optional-public.txt
This change bumps the version of the optional [regulations-site](https://github.com/cfpb/regulations-site) package from version 2.1.17 to version [2.2.0](https://github.com/cfpb/regulations-site/releases/tag/2.2.0). It also enables the optional functionality in this new version to use Python imports to communicate between regulations-site and [regulations-core](https://github.com/cfpb/regulations-core), instead of HTTP.
Unlike most version bumps, this has potential to have a significant performance impact on the way that eRegs is served. This new version does everything on a single Apache thread instead of farming out to multiple parallel threads for each request. This means that servers should have less threads but that each request may take slightly longer. Overall process stability …
=> Bump regulations-site to 2.2.0, use Python for regulations-core

.flake8, cfgov/cfgov/__init__.py, cfgov/cfgov/monkey_patch/__init__.py, cfgov/cfgov/monkey_patch/django.py
This change brings in the Django migration executor from version 1.9.1 (we are currently on v1.8.15). This produces a significant speedup in the planning and executing of migrations, which speeds up the running of unit tests that invoke migrations (e.g. running `tox`).
This change was inspired by this conversation:
https://github.com/tomturner/django-tenants/issues/113
It brings in these Django commits:
https://github.com/django/django/commit/5aa55038ca9ac44b440b56d1fc4e79c876e51393#diff-191c6b8087fd8fb2cc08a2d9f9bf44de
https://github.com/django/django/commit/fc584f06859b88474ea0db49bfe142e87428865d#diff-191c6b8087fd8fb2cc08a2d9f9bf44de
which represent a change in Django 1.9 and then a subsequent bug fix in Django 1.9.1.
You can see some discussion of this change in this Django ticket: …
=> Faster migrations with Django 1.9 monkeypatch

cfgov/cfgov/settings/base.py
Using direct Python to invoke regcore from regsite seems to have an unexpected negative effect on database performance which will take more investigation to nail down.
Reverting in the interest of restoring previous performance.
This reverts part of #3721.
=> Revert use of direct Python connection for eRegs

cfgov/alerts/github_alert.py, cfgov/alerts/logging_handlers.py, cfgov/alerts/send_new_relic_messages_to_sqs.py, cfgov/alerts/sqs_queue.py, cfgov/alerts/tests/test_github_alert.py, cfgov/alerts/tests/test_logging_handlers.py, cfgov/alerts/tests/test_send_new_relic_messages_to_sqs.py, cfgov/alerts/tests/test_sqs_queue.py, cfgov/cfgov/settings/production.py
See GHE/platform/2180 for more context.
Instead of posting 500s directly to GitHub, this PR makes use of our SQS queue and posts them there, so that the more intensive processing (e.g. finding a matching issue)in `GithubAlert` can be done asynchronously. 
While this leaves the current process mostly as-is, there are a few changes:
- Everything in the SQS queue (as configured in the Jenkins job's call to `post_sqs_messages`) gets posted to GitHub AND chat, whereas before we were not posting 500 errors to chat. Now we will be.
- The default `GithubAlert` configuration is to add the label `alert` to all issues created (note that @hillaryj requested we remove the `Maintenance and Response` label). Since there are no longer custom labels coming in through the logging handler code, 500s won't …
=> Post Django errors to SQS Queue instead of directly to GitHub

cfgov/alerts/logging_handlers.py, cfgov/alerts/tests/test_logging_handlers.py
The AWS credentials for SQS may be distinct from those used for S3, so they need to be specified separately. Specifically, the S3 credentials may not have permission to access SQS.
This change replaces the use of the `AWS_S3_ACCESS_KEY_ID` and `AWS_S3_SECRET_ACCESS_KEY` environment variables with `AWS_SQS_ACCESS_KEY_ID` and `AWS_SQS_SECRET_ACCESS_KEY`.
Additionally, the use of the `QUEUE_URL` environment variable is changed to `AWS_SQS_QUEUE_URL` to be more precise.
- Modifying use of environment variables.
1. See unit tests.
See related PR in Ansible deployment scripts.
=> Use SQS-specific AWS credentials for SQS

cfgov/alerts/post_sqs_messages.py, cfgov/alerts/tests/test_post_sqs_messages.py
Instead of posting full alerts to Mattermost, including stack traces and request content, we should only post the alert titles along with the GH issue for more detail.
- MM alerts should only receive alert titles, not full alert bodies.
See unit tests in `alerts.tests.test_post_sqs_messages`.
=> Only post alert titles to Mattermost

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/jinja2/v1/index.html
This change modifies the megamenu reference from "Owning a Home" to "Buying a House". It also changes the link on the homepage in the same way.
The change to the megamenu will hopefully be temporary pending migration of that menu into Wagtail, i.e. in #3396.
- Renaming "Owning a Home" to "Buying a House" on the home page and megamenu.
1. Run a local server and visit http://localhost:8000.
=> Rename megamenu/home page references to Owning a Home

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_includes/organisms/email-popup/base.html, cfgov/jinja2/v1/_includes/organisms/email-popup/debt.html, cfgov/jinja2/v1/_includes/organisms/email-popup/oah.html, cfgov/jinja2/v1/ask-cfpb/answer-page.html, cfgov/jinja2/v1/owning-a-home/mortgage-estimate/index.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/unprocessed/css/organisms/email-popup.less, cfgov/unprocessed/js/modules/util/email-popup-helpers.js, cfgov/unprocessed/js/organisms/EmailPopup.js, cfgov/unprocessed/js/routes/ask-cfpb/single.js, cfgov/unprocessed/js/routes/consumer-tools/debt-collection/index.js, cfgov/v1/jinja2tags.py, cfgov/v1/templatetags/email_popup.py, cfgov/v1/tests/templatetags/test_email_popup.py, cfgov/v1/tests/test_jinja2tags.py
This change modifies the existing JS email popup so that it can appear on a wider set of pages, and also supports multiple simultaneous popups at the same time with different content and target email lists.
It leaves the existing Owning a Home popup on these pages:
- /owning-a-home/
- /owning-a-home/mortgage-estimate/
and adds a new Debt Collection popup on these pages:
- /ask-cfpb/what-is-a-statute-of-limitations-on-a-debt-en-1389/
- /ask-cfpb/what-is-the-best-way-to-negotiate-a-settlement-with-a-debt-collector-en-1447/
- /ask-cfpb/what-should-i-do-when-a-debt-collector-contacts-me-en-1695/
- /consumer-tools/debt-collection/
This new popup will not turn on until February 1st, and can be configured using the `EMAIL_POPUP_DEBT` feature flag. The existing `EMAIL_POPUP` feature flag that was …
=> Add second email popup for debt collection pages

cfgov/jinja2/v1/_includes/organisms/expandable.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
See platform issue 2393 for context.
The expandable text we see on filterable list pages, such as https://www.consumerfinance.gov/about-us/blog, will now display "Show filters" and "Hide filters" instead of "Show" and "Hide".  Use of the expandable on non-filterable list pages will remain unaffected, as it is an optional parameter.
Screenshots:
=> Pass additional text to expandable cue label 

cfgov/jinja2/v1/_includes/organisms/email-popup/debt.html
This change modifies the GovDelivery code used on the debt email popup, changing it to `USCFPB_153`. See GHE#2396#issuecomment-146990 for some background.
- Change GovDelivery code on email popup.
1. Implement the popup and look at the source code of the page to verify form code.
=> Change email debt popup GovDelivery code

gulp/tasks/scripts.js, package-lock.json, package.json
`gulp-modernizr` is abandoned and doesn't work with gulp 4. Switches to using `gulp-modernizr-build`.
- Changes `gulp-modernizr` to `gulp-modernizr-build`.
- Removes `gulpRename` in polyfill task because it can be done in the modernizr task directly.
2. `gulp scripts` should pass.
=> Switch to using gulp-modernizr-build

cfgov/unprocessed/css/organisms/email-popup.less
- Add box-sizing style rule to fix input field width in pop-up.
1. See https://github.com/cfpb/cfgov-refresh/pull/3731
Before:
After:
=> Fix input text field width in popup

gulp/config.js, gulp/tasks/copy.js
Vendorimg appears to have been used over a year ago for the slick carousel ajax-loader image. It now has an empty src array and the copy task included renaming the ajax-loader in the PDF reactor CSS, which doesn't contain a reference to that image anymore.
- Removes `gulp copy:vendorimg` task and associated configuration.
=> Remove unused vendorImg task

cfgov/ask_cfpb/models/django.py, cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/ask_cfpb/tests/test_views.py
Ask category pages get metadata on related pages from Elasticsearch to
avoid heavy requests, and the metadata was allowing references to
non-live pages. This adds a filter that is invoked at index time,
and adjusts tests to check that facet_map pages are live.
Addresses GHE issue 2417
=> Ask CFPB: Make sure indexed pages are live

cfgov/v1/forms.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/models/sublanding_page.py, cfgov/v1/tests/models/test_browse_filterable_page.py, cfgov/v1/tests/test_filterable_list.py, cfgov/v1/tests/test_filterable_list_form.py, cfgov/v1/tests/util/test_ref.py, cfgov/v1/util/filterable_list.py, cfgov/v1/util/ref.py
This change modifies how the `FilterableListMixin` page mixin class selects and limits the pages that it filters, making sure that it only filters pages that are in the same Wagtail Site as itself.
Currently this mixin filters any live `AbstractFilterPage`, even those that are elsewhere in the page tree. This causes problems if, for example, a live page is moved to the Trash, or to some other Site running in the same Wagtail instance.
With this change, the default behavior of Page classes that inherit from `FilterableListMixin` is to only include pages in their same Site.
This change includes some minor refactoring of how the filterable queryset gets passed around, renaming some variables `filterable_` for clarity and using the page's own `Page.get_site` method for convenience. Some logic …
=> MakeFilterableListMixin respect Wagtail sites

cfgov/legacy/tests/housing_counselor/test_generator.py
When running the `tox` tests in a Docker container (filesystem behavior differences are my only guess as to why this has not come up before), I noticed that this test would sometimes break because of the ordering of the items in the first list. When we sort the lists, I can no longer observe the problem.
=> Fix unit test: always sort lists to keep ordering stable, avoid potential breakage

cfgov/unprocessed/css/organisms/expandable-group.less
See https://[GHE]/CFPB/hubcap/issues/76
1. Pull branch
2. `gulp styles`
3. Load http://localhost:8000/consumer-tools/prepaid-cards/choose-the-right-card/ and observe the lack of double-borders
- The correct fix will be to remove the custom expandable code and use only stock cf-expandables code, but that might take a bit. In the meantime, this fixes the issue.
=> Add temporary fix for double expandable borders

cfgov/cfgov/settings/base.py
Stakeholders have requested that we expand the "SERVE_LATEST_DRAFT_PAGES" setting on beta to two more pages:
https://www.consumerfinance.gov/policy-compliance/guidance/implementation-guidance/hmda-implementation/
https://www.consumerfinance.gov/policy-compliance/guidance/implementation-guidance/mortserv/
[GHE]/CFGOV/platform/issues/2420
- the requested page ID's have been added to SERVE_LATEST_DRAFT_PAGES
1.
-
-
=> expand SERVE_LATEST_DRAFTS on beta to 2 more pages

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
This commit fixes the ordering of "Buying a House" in the website megamenu. PR #3732 renamed this from "Owning a Home" but neglected to put in proper alphabetical order.
- Move "Buying a House" first in the megamenu.
1. Run a local server and look at the megamenu.
- Thanks to @stephanieosan for pointing out this bug.
- Ping @virginiacc in case the Wagtail megamenu PR #3396 needs something similar.
=> Properly alphabetize "Buying a House" in megamenu

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Add a link to the "Financial Well-Being Questinnaire" at URL [/consumer-tools/financial-well-being/](https://www.consumerfinance.gov/consumer-tools/financial-well-being/) in the megamenu.
This is added both with and without the `FINANCIAL_COACHING` feature flag.
- Add FWB link to the megamenu.
1. Run a local server and look at the megamenu.
- Ping @virginiacc in case the Wagtail megamenu PR #3396 needs something similar.
=> Add Financial Well-Being to the megamenu

cfgov/jinja2/v1/know-before-you-owe/index.html
- Corrected the heading and link for the real estate professionals guide
- Updated "Owning a Home" references to "Buying a House"
1. Pull branch
2. Visit http://localhost:8000/know-before-you-owe/
3. See the correctly-titled "Real estate professionals" section and click through to it
- Once the canonical URL has changed from `/owning-a-home` to `/buying-a-house`, update the URL references in this file, as well.
=> Fix some text from the move from Sheer, update OAH references to BAH

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, requirements/base.txt, requirements/optional-public.txt
This change removes references to the optional [eregs-2.0](https://github.com/cfpb/eregs-2.0) app from this repository, effectively reversing #3089.
- Removal of references to eregs-2.0 and its `eregs_core` app.
- Removal of `django-mysql` requirement which was only required for eregs-2.0.
- Pinging @lfatty as this is partially motivated by some security concerns he raised.
=> Remove optional eregs-2.0 app

cfgov/cfgov/settings/base.py
There seems to be an issue with the date-based flag, so enabling via boolean.
=> Enable EMAIL_POPUP_DEBT feature flag

cfgov/cfgov/settings/base.py, requirements/optional-public.txt
This commit bumps the optional regulations-site package to 2.2.1. That release adds support for a new Django setting, `EREGS_REGULATION_UPDATES`, that allows for placement of a message on the landing page of any regulation to let users know that we're working on incorporating the latest updates to that regulation. See cfpb/regulations-site#843
- `EREGS_REGULATION_UPDATES` Django setting
- Bump `regulations-site` to 2.2.1
1. Run a local server with `EREGS_API_BASE=https://www.consumerfinance.gov/eregs-api/ ./runserver.sh`
2. Pop on over to eRegs at http://localhost:8000/eregulations/
3. View any of the regs that have an update in progress but *don't* have new amendments effective in the future: 1002, 1010, 1011, 1012, 1013, 1024, or 1026. The landing page for those regs should look like …
=> Bump regulations-site to 2.2.1

requirements/base.txt
This change bumps the optional wagtail-flags package from version 2.0.7 to new [release 2.0.8](https://github.com/cfpb/wagtail-flags/releases/tag/2.0.8). The main user-visible change with this upgradte is that now flags and conditions are properly alphabetized in the Wagtail admin.
- Wagtail-flags to 2.0.8.
1. Browse admin and see proper alphabetization.
=> Bump wagtail-flags package to 2.0.8

requirements/optional-public.txt
This change bumps the optional ccdb5-ui package (https://github.com/cfpb/ccdb5-ui) from version 1.0.6 to new version 1.0.7 (https://github.com/cfpb/ccdb5-ui/releases/tag/v1.0.7). This fixes an issue where requests without a HTTP_USER_AGENT header were causing a 500 error.
- Bump ccdb5 to version 1.0.7.
1. See https://github.com/cfpb/ccdb5-ui/pull/129.
=> Bump optional ccdb5-ui package to version 1.0.7

cfgov/cfgov/settings/production.py
This PR adds `ALLOWED_HOSTS` to the production.py settings file and reads its value from an `ALLOWED_HOSTS` env var that contains a **JSON list** of allowed hosts. If that env var is not set, an attempt at a restricted but sane, functional default (`['.consumerfinance.gov']`) is made.
JSON seemed the lowest-effort and least invasive way to define a list in  an env var, since we use env vars for host-specific configuration in Ansible. There will be a corresponding PR to our Ansible role to define the env var.
Despite the fact that host validation is already done before any traffic reaches our web server, this is being done to put us in compliance with our security baseline.
=> Set ALLOWED_HOSTS in production with an env var

cfgov/cfgov/settings/production.py
This change modifies the production logging setting so that all loggers use the default logging handlers for level `INFO` and above. Currently the log only includes messages from `v1` and `core.views`, which not only omits logging from other apps but also means that we don't have logging for important things like `django.security.DisallowedHost` (more important as of `ALLOWED_HOSTS` in #3772).
- Add new catchall logger with an empty string (`''`) that uses default handlers in production.
- Remove specific loggers for `core.views` and `v1` since they fall under the catchall logger.
From a shell, try this:
```sh
$ DJANGO_SETTINGS_MODULE=cfgov.settings.production cfgov/manage.py shell
...
>>> import logging
>>> logger = logging.getLogger('something')
>>> logger.info('foo')
foo
```
In …
=> Add default catchall logging handler

cfgov/jinja2/v1/ask-cfpb/answer-page.html
We add the "Ask ID" to page titles, for the convenience of editors, like this:
This makes it a bad default for og:description
This PR makes it so that Ask pages will default to the "snippet" value, instead of the wagtail page title. (which has a pretty pleasing effect, I think)
(preview generated with [this chrome plugin](https://chrome.google.com/webstore/detail/open-graph-preview/ehaigphokkgebnmdiicabhjhddkaekgh)) 
- added an og_description block to the answer-page.html template, overriding that block's default definition (from base.html)
=> Better og:descriptions for Ask CFPB answer pages

cfgov/jinja2/v1/ask-cfpb/answer-page.html
I was following up on #3781 and noticed that for some Ask CFPB questions, the snippet included HTML <p> tags.
With this change, we run snippets through Django's [striptags](https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#striptags) filter, which produces clean snippets
- add |striptags filter to og:description on AskCFPB pages
-
-
=> strip HTML from og:description in Ask CFPB

cfgov/jinja2/v1/_includes/on-demand/footer.html, cfgov/jinja2/v1/_layouts/base.html
Requests to https://search.usa.gov/javascripts/remote.loader.js redirect to https://search.usa.gov/assets/sayt_loader.js, which has an effect on our loading time. We've consulted with the search.usa.gov, and they have advised that it's safe to use sayt_loader.js directly.
- references to remote.loader.js changes to sayt_loader.js
-
-
=> avoid unneccessary redirect on remote.loader.js

cfgov/cfgov/test.py, tox.ini
In the past we tried to enable running the Python unit tests of our optional apps (from requirements/optional-public.txt) using the settings of this cfgov-refresh project.
This practice has fallen out of favor, and instead we now try to make sure that optional packages themselves have robust and comprehensive tests, which negate the need for testing within cfgov-refresh.
This change removes the tox `optional` and `optional-fast`  environments that supported this kind of testing.
This change also removes the `OptionalAppsMixin` mixin class that we have in our test runner that enables testing of those apps. Motivation for this change is to pursue simplification and removal of unused code.
- Tox `optional` and `optional-fast` environments.
- Test runner no longer looks for optional app …
=> Deprecate Python unit testing of optional apps

cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/unprocessed/css/enhancements/typography.less, cfgov/unprocessed/css/organisms/post-preview.less, package-lock.json, package.json
Fixes for 2 post preview visual bugs, https://GHE/CFGOV/platform/issues/1089 and https://GHE/CFGOV/platform/issues/1090
This is dependent on https://github.com/cfpb/capital-framework/pull/757 getting released and cf-typography getting bumped here before it can get merged.
- `a-date` element in post-preview template gets vertical alignment tweaks to align text with the categories baseline on larger screens. fixes https://GHE/CFGOV/platform/issues/1090
- CSS from typography enhancements was ported to either Capital Framework at https://github.com/cfpb/capital-framework/pull/757/files#diff-fbe01bf95b92595df0d955810b71204d or to the post-preview parent stylesheet, since that is the main (and only, that I could tell) use case for this element
- HTML structure for post-preview template updated …
=> Post preview visual bug fixes: adjust whitespace and line break across screen sizes

cfgov/agreements/tests/test_management.py
This change removes some visible print output being generated by one of the agreements unit tests. It restores our pristine set of `....` when running Python unit tests.
- Pass `verbosity=0` to `call_command` calls in agreements unit tests, to avoid printing output to console.
1. `tox` and see a nice series of dots.
Thanks @Scotchester for pointing this out. Print was accidentally introduced [in this commit](https://github.com/cfpb/cfgov-refresh/commit/57fabfcd50524a83a4288d179cef4055f9412c07#diff-ed68be87bd57a8ef3375ac8943c89e64R50).
=> Remove print output from agreements unit test

.isort.cfg
Haivng six in `known_future_library` can cause some weirdness that breaks things. isort ends up wanting `import six` before `from __future__ import ...`.
=> Move six to the standard library imports

cfgov/jinja2/v1/_layouts/base.html
Refactor for script loading in base.html
- Modified `cfgov/jinja2/v1/_layouts/base.html` to use script detailed in https://www.html5rocks.com/en/tutorials/speed/script-loading/. Uses `async=true` for script tags to ensure proper loading order.  This should allow us to take advantage of loading scripts in parallel and executing sequentially.
1. Visit http://localhost:8000/about-us/blog and ensure the page works.
2. Visit http://localhost:8000/data-research/consumer-credit-trends/student-loans/borrower-risk-profiles/ and ensure the page works.
- We need a write up on manually testing pages. 
- We should add the ability to use the `rel="preload` attribute.
-
=> Refactor for script loading in base.html

gulp/tasks/styles.js
Temp fix for font path in apps code
- Modified code to fix issue with font path in app code.  Issue is occurring because the OAH `main.less` file is importing `main.less`. There doesn't look to be an easy way to override the `@cf-icon-path:` variable,  although I thought you could so because of Less lazy loading. 
1. Run gulp styles and view ` main.part1.css`. Search for `eot` in the file and ensure the path is absolute.
=> Temp fix for font path in apps code

test/unit_tests/apps/owning-a-home/ratings-form-spec.js
Fixes broken path in unit test. Not sure why Travis didn't pick this up?
- Changes path in owning-a-home ratings form test to point to new location added in https://github.com/cfpb/cfgov-refresh/pull/3806
1. `gulp test:unit` should pass.
=> Fix path in unit test

cfgov/unprocessed/css/main.less, gulp/tasks/styles.js
Let's try absolute path for the cf-icon-path variable!
- Changes `@cf-icon-path` variable from relative to absolute path.
- Unneeded font path replacement.
=> Try absolute path for cf-icon-path

tox.ini
Fix for validate-assets tox.ini
- Modified `tox.ini` to fix issue with task.
1. Run `tox -e validate-assets` and pray you dont' get any errors.
-
-
=> Fix for validate-assets tox.ini process

.eslintrc, cfgov/unprocessed/js/molecules/Multiselect.js
- `allowBlockStart` to `true` in eslint `lines-around-comment` rule.
- Autofixes quoted properties in `Multiselect.js`.
1. `gulp lint --fix` should have no changes and pass.
=> Adjust eslint setting

cfgov/unprocessed/js/modules/BreakpointHandler.js, gulp/tasks/test.js, package-lock.json, package.json
Fix for using import statements with Mocha / Instanbul
- Modified test script to fix issue with requiring scripts that contain import statements. 
1. Run `gulp test:unit`.
=> Fix for using import statements with Mocha / Instanbul

cfgov/jinja2/v1/owning-a-home/explore-rates/index.html, cfgov/unprocessed/apps/owning-a-home/js/dropdown-utils.js, cfgov/unprocessed/apps/owning-a-home/js/explore-rates.js
- Updates `hidden` class to `u-hidden`.
1. Log into local wagtail and set the flag `OAH_EXPLORE_RATES` to `true`
2. Restart the server.
3. Run `cp ./cfgov/unprocessed/apps/owning-a-home/example-config.json ./cfgov/unprocessed/apps/owning-a-home/config.json` (if needed) and `gulp build`.
3. View http://localhost:8000/owning-a-home/explore-rates/
4. See that warning icons aren't showing in the right-hand column
=> Update hidden class in owning-a-home/explore-rates

cfgov/unprocessed/css/organisms/post-preview.less
Fixes remaining visual bug/inconsistency for https://GHE/CFGOV/platform/issues/1089#issuecomment-147885
- divide previous margin-bottom value (which equates to 30px) by half to get 15px
1. check out branch
1. runserver
1. go to http://localhost:8000/about-us/blog/
1. inspect any missing image element - edit attribute with inspector to add image URL such as https://s3.amazonaws.com/files.consumerfinance.gov/f/images/cfpb_YouthResearch_blog.original.png (so you don't have to mess with wagtail)
1. once image is visible, confirm bottom margin is 15px 
-
-
=> Reduce margin by half for post preview images on small screens

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
https://github.com/cfpb/cfgov-refresh/pull/3514 was added before we started flagging OAH routes. With the changes to OAH assets this broke on prod. This PR adds flags for the two mortgage routes in OAH to pull off the old pages till prod it set up to install app package.json https://github.com/cfpb/cfgov-refresh/pull/3820 and handle rate checker's config.json file https://github.com/cfpb/cfgov-refresh/pull/3818
- Adds flags to the URLs for /owning-a-home/mortgage-closing/ and /owning-a-home/mortgage-estimate/
1. Restart the server. 
2. Check that /owning-a-home/mortgage-closing/ and /owning-a-home/mortgage-estimate/ loads.
3. Log into local wagtail and set flags `OAH_MORTGAGE_CLOSING` and `OAH_MORTGAGE_ESTIMATE ` and check that /owning-a-home/mortgage-closing/ and …
=> Flag OAH mortgage routes

cfgov/unprocessed/apps/cfgov/unprocessed/apps/owning-a-home/package-lock.json, gulp/config.js, package.json, scripts/npm/apps-install/index.js
- Adds `scripts/npm/apps-install/index.js` script for running `npm install` on `./cfgov/unprocessed/apps/[app namespace]/package.json`.
1. Throw out `./cfgov/unprocessed/apps/[app namespace]/node_modules`
2. Run `gulp build`, get `App dependencies not installed…` message. (Do not follow message.)
3. Run `npm install` from the project root.
4. Re-run `gulp build` and check that `./cfgov/unprocessed/apps/[app namespace]/node_modules` exists.
=> Add postinstall script for apps under cfgov-refresh

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
Modifying OAH flagged routes
- Modified code to group routes. Removed the flags from the static pages. They aren't necessary and will render properly when #3831 is merged.
1. Visit `http://localhost:8000/owning-a-home/closing-disclosure/` and ensure the route works with the flag `OAH_FORM_EXPLAINERS` set / unset. 
2. Visit `http://localhost:8000/owning-a-home/mortgage-closing` and ensure the route works .
3. Visit `http://localhost:8000/owning-a-home/mortgage-estimate` and ensure the route works .
-
-
=> Modifying OAH flagged routes

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
Legend had a `for` attribute from when it was migrated from being a label 😊 
- Remove `for` attribute from legend.
=> Remove for attribute from legend

cfgov/jinja2/v1/_includes/blocks/feedback.html
These forms were never updated to use the latest markup and classes
created in cf-forms to handle full width inputs. This fixes
`/platform/issues/1075`
- Updated the form markup to match the recommended pattern in cf-forms
1. Navigate to http://localhost:8000/practitioner-resources/servicemembers/
2. Navigate to http://localhost:8000/owning-a-home/help-us-improve/
=> Fix an issue with inputs that should be 100% in width

cfgov/unprocessed/apps/cfgov/unprocessed/apps/owning-a-home/package-lock.json, gulp/tasks/scripts.js, scripts/npm/apps-install/index.js
Address @Scotchester comments in https://github.com/cfpb/cfgov-refresh/pull/3831
- Removes erroneous `package-lock.json`.
- Corrects incorrect code comments in apps-install npm script.
- Wrap npm standard error output in an if statement.
1. See testing in https://github.com/cfpb/cfgov-refresh/pull/3831
=> Cleanup for apps-install script

cfgov/jinja2/v1/_includes/organisms/email-popup/debt.html
Per stakeholder, the email popups on debt-related pages should be changed from `USCFPB_153` to `USCFPB_152`. See GHE#2528.
1. Run a local server with a production dump.
2. Visit http://localhost:8000/consumer-tools/debt-collection/ in an incognito window and scroll to the bottom of the page. You should see an email popup appear.
3. Submit the popup form with an email address.
4. In the console, you should see a line like this:
```sh
GovDelivery(account_code=USCFPB).set_subscriber_topics(test@test.com, [u'USCFPB_152'], send_notifications=True)
```
indicating that the `USCFPB_152` code is the one being subscribed to.
=> Update debt email popup GovDelivery code

cfgov/unprocessed/apps/owning-a-home/package-lock.json, gulp/tasks/audit.js, gulp/tasks/docs.js, gulp/tasks/test.js, package-lock.json, package.json
gulp-util is deprecated and log should be migrated to fancy-log per https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5 
- Replace gulp-util.log with fancy-log.
- Replace gulp-util.colors with ansi-colors.
2. `gulp audit:perf` and `gulp audit:a11y` should log to the console as before (with server running).
3. `gulp test` and `gulp docs` should pass.
=> Replace gulpUtil with fancyLog
