_tests/browser_testing/features/environment.py
Previously, when using a proxy, the status wouldn't be sent to sauce labs.  Now it will check for proxy via the HTTP_PROXY environment variable and set it before sending the pass/fail status.
=> Allow for proxy when sending pass/fail status to saucelabs

events/_vars-events.html, events/index.html
Adds a mock blog post object for testing purposes on the events page
till the server-side events type is available. 
To inspect an actual blog post object, post the following inside https://github.com/cfpb/cfgov-refresh/blob/gh-pages/blog/_single.html#L24
```jinja
<p>
<dl>
{% for key, value in post.json_compatible().iteritems() %}
<dt>{{ key }}</dt>
<dd>{{ value }}</dd>
{% endfor %}
</dl>
</p>
```
Save, and visit `localhost:7000/blog/spring-2014-rulemaking-agenda/`
=> Adds mock blog post

_settings/lookups.json, events/_event.html, events/_single.html, events/_vars-events.html
Adds initial event detail page, with mocked data. URL is handled by creating a path in the lookups table for sheer that points to a blog post, while template is rendered using mocked data in the `events/_vars-event.html` file.
- Adds TEMP entry in `lookups.json` for events type.
- Adds `_single.html` template for viewing an individual event.
- Adds `_event.html` template analogous to `article.html` for rendering
individual events.
- Updates event mock data to clarify what fields are showing and fix issue
with the date. Also changes the mock name.
- Visit http://localhost:7000/events/spring-2014-rulemaking-agenda/
- @sebworks 
et al
=> Fixes DF-1463 - single event page

_includes/email-subscribe-form.html, events/_single.html
Updated the event sidebar to include some demo content
- None
- None
- Updated the object passed to `post_related.render()`
- Updated the list of related links
Navigate to
- events/spring-2014-rulemaking-agenda/
- @sebworks 
- Subscribe form can't currently support zip codes or event type
- Used existing Related Posts macro for code consistency
=> DF-1473 Event Sidebar

_includes/event-post-macros.html, _includes/events-posts.html, events/_event.html, static/css/event-meta.less
Display the Event Detail Venue 
- Updates 'meta.less' file to include patterns for displaying the venue.
- Updates '_events.html" file to display the venue and map.
- Updates 'events-posts" file to display the venue and map.
- Updates 'event-post-macros" file to display the venue and map.
et al
=> Fixes DF-1469/Event Detail Venue

README.md
Include available grunt sub-tasks in readme for easier discovery
- Added `grunt watch` sub-tasks to readme
- None
- None
- None
- @sebworks 
None
- `:css` and `:cssjs` sub-tasks are much faster and make working locally easier
- Fixes 283
=> 283-readme-add-subtasks

_includes/email-subscribe-form.html, _includes/post-macros.html
NOTE: There is a complementary sheer PR that should be merged at the same time as this one: https://github.com/cfpb/sheer/pull/88
Facets are deprecated in ElasticSearch and will be removed in a future release. This migrates them to aggregations which work pretty much the same way as facets.
This PR essentially makes the change from {"term": "term-you-want"} to {"key": "term-you-want"} to reflect the minor difference between the ElasticSearch results for facets and aggregations.
=> Switch from terms facet to aggregations

_includes/footer.html
Fixes typo in global footer and removes excess whitespace.
- Fixes DF-1498 - fixes typo in footer, "Accessiblity."
- Removes excess whitespace.
- Moves entire code block 4-spaces to the left.
- Visit the homepage and view in the footer the corrected text "Accessibility."
- @sebworks 
- The entire code block had an extra indent level. I removed this, but let me know if you can think of a reason why an include might need the entire file to be indented one level (such as to nest properly in the context where it's included?)
=> Fixes DF-1498 - fixes typo in footer

_includes/footer.html
Adds Open Government link to the footer.
- Fixes DF-1501 - adds footer link for “Open Government.”
- Visit homepage and note disabled "Open Government" link in the footer after "Ombudsman."
- @sebworks 
- @schaferjh 
- For now the link is disabled, but the expected URL is provided in a code comment above.
- The "Open Government" link doesn't fit on the same line as everything else on desktop sizes, so creates a new line in the footer, which isn't aesthetically the best.
=> Fixes DF-1501 - adds footer link

_lib/wordpress_contact_processor.py
Before, the processor was grabbing an index location of a list whether or not there exists anything at that location.  As a result, indexing items without all the required custom fields was failing.  This will make sure the index location is there before attempting to grab the value out of it.
=> Improve contact processor

_includes/article.html, _includes/macros.html, events/_event.html
Makes it so heading content in sharing macro is hidden, not removed, so that it still shows up in the document outline when hidden.
- Fixes #275 - hides, not removes, header in sharing macro.
- Visit http://localhost:7000/events/spring-2014-rulemaking-agenda/ and note that sharing heading "SHARE THIS PAGE" does not show up. View page source and notice `<h1 class="h5 u-visually-hidden">Share this page</h1>` exists. Change `false` parameter to `true` in https://github.com/cfpb/cfgov-refresh/blob/gh-pages/events/_event.html#L45 and reload the page and note that the heading "SHARE THIS PAGE" does show up.
- @sebworks 
- @jimmynotjim
Sharing macro looks like:
=> Fixes 275-hides, not removes, header.

_settings/lookups.json, events/_event-post-macros.html, events/_event.html, events/archive/_single.html
Add Events Archive page
- Updates '_events.html" file to add condition for omitting inset markup when even/archive path.
- Updates 'lookups.json" file to display the event archive post type.
- Updates 'event-post-macros" file to add condition for displaying image and text.
- Added 'archive/_single.html' file to display the event archive page. 
et al
=> Df 1505 archive events detail

events/_event-post-macros.html, static/css/event.less
Fixes for JIRA issues DF-1578 and DF-1579
- Adjust type sizes/weights so that they match the design files for a better hierarchy on the page.
- Make padding between rule and event text 30px and padding below event text and the follwing event post 60px
- Updates 'events/_event-post-macros.html' file to fix padding issue and font issue.
- Updates 'events.less' file to fix padding issue and font issue.
et al
=> Fix for DF-1579/DF-1578

_includes/sidenav.html, events/index.html
Fixes position of nav on mobile for Events landing page.
- Updates '_includes/sidenav.htm' file to allow for additional classes on nav.
- Updates ' events/index.html' file to show/hide mobile menus depending on context. 
et al
=> Fix for DF-1577 - Events Mobile Nav

newsroom/press-resources/index.html
Removes Mallory McLean info (she is no longer at the CFPB).
- Removes McLean section from press resources page.
- Visit /newsroom/press-resources/ and note McLean section is gone.
- @sebworks 
- @jimmynotjim
=> Fixes DF-1649 - removes McLean info

index.html
- Changes link to cf.gov from https to http.
- Visit landing page, click `Go to consumerfinance.gov`, note http:// is used.
- @sebworks 
- Just checking that we don't want to be directing people to https for some reason? cc @Scotchester
=> Fixes DF-1642 - changes https to http

_queries/events.json, _queries/events_archive.json, _settings/lookups.json, _settings/processors.json, events/_vars-events.html
Fixed url issues for Blog/Events/Event Archives
- Updates '_vars-events.html' file to use appropriate post type depending on path.
- Updates '/lookups.json' file to use appropriate post type.
- Updates '/processors.json' file to build mock events/events archives types.
- Adds '_queries/events_archive.json' file to allow for Elasticsearch query.
- Adds '_queries/events.json' file to allow for Elasticsearch query.
You will need to re-index Sheer by running :
sheer index --reindex
=> Fix for DF-1623-Blog/Events/Events Archive urls

_includes/header.html, index.html
Changes "for industry" text to "policy and compliance."
- Changes text, CSS and JS references to "for industry" into "policy and compliance."
- Minor code comment formatting consistency/grammar cleanup.
- Visit landing page and note "Policy and Compliance" where there was once "For Industry."
- @sebworks 
- @duelj 
Main header nav:
Progress chart:
=> Fixes DF-1661 - for industry text

_lib/wordpress_contact_processor.py, contact-us/general-inqueries.html, contact-us/submit-a-complaint.html
Fix expandable cue position for multi-line text on Small Business page.
- Updates ' _lib/wordpress_contact_processor.py' file to fix errors with email address and phone number.
- Updates 'contact-us/submit-a-complaint.html' file to populate correct content.
- @willbarton 
You will need to reindex Sheer by running :
Sheer index --reindex
Unsure on what field should be populating 'Address desc'
Document is available at http://localhost:9200/content/contact/submit-a-complaint
=> Fix for DF-1639:General Contact Info

blog/index.html, budget/financial-report/index.html, budget/funding-request/index.html, budget/performance-plan-report/index.html, newsroom/index.html, newsroom/press-resources/index.html, the-bureau/leadership-calendar/index.html
Short description explaining the highlevel reason for the pull request
None
None
- Added or un-hid titles on all pages
All pages
- @ajbush 
- @duelj 
- Page titles look great on most pages, but the two screenshots I posted above look really off. The Jira task says the titles should be under the hero, what do you think?
=> Added titles to pages that were missing them

_includes/email-subscribe-form.html
Disable the Topic Expansion on Blog or Event
- Updates '_includes/email-subscribe-form.html' to disable email topic functionality on blog/event pages.
- @anselmbradford  
- @jimmynotjim
=> DF-1625_Email_signup:Disable Topic Expansion

the-bureau/history/index.html
"of our current history" isn't as good for the older ones as it is for the work since July 21, 2011. So I just excised it.
=> Timeline expandable label

budget/financial-report/index.html, budget/funding-request/index.html, budget/performance-plan-report/index.html, budget/strategic-plan/interactive/index.html, doing-business-with-us/future-requests/index.html, doing-business-with-us/past-awards/index.html, doing-business-with-us/small-businesses/index.html
We're pulling content from pages by their ID.  Previously, we were pulling them from build, but now we need to be pulling them from prod.  Since they don't have the same auto-assigned IDs, this PR simply switches the IDs to match the new ones on prod.
@sebworks @anselmbradford @jimmynotjim @willbarton @kurtw this will break your local install for the following pages, until you re-index from www.cf.gov:
http://localhost:7000/budget/financial-report/
http://localhost:7000/budget/performance-plan-report/
http://localhost:7000/budget/strategic-plan/interactive/
http://localhost:7000/doing-business-with-us/future-requests/
http://localhost:7000/doing-business-with-us/past-awards/
http://localhost:7000/doing-business-with-us/small-businesses/
http://localhost:7000/budget/funding-request/
**You …
=> Change pages to the proper ID from prod (DF-1669)

_tests/processor_tests/README.md
Minor test readme cleanup.
- Removes excess whitespace.
- Fixes #406 - minor typo in Readme.
- @sebworks 
- @jimmynotjim
=> Fixes #406 - minor typo in Readme.

static/css/budget.less
Fixes #405 - reduces CSS specificity.
- Moves `a` outside `li` in Less file, since parent `ul` can only have `li` or a non-visual element as its child, so it's implied that `a` is the child of `li` even though that's not shown in the CSS.
- @sebworks 
- @jimmynotjim
=> Fixes #405 - reduces CSS specificity

newsroom/index.html
We don't send out all testimony or speeches, I don't believe, so I limited it to "press releases." I'd rather underpromise and overdeliver on our comms emails than the other way around. We can verify with comms about the language on future updates.
=> Changed email signup language

newsroom/press-resources/index.html, static/css/press-resources.less
DF-1679: Remove logo and usage section
- Updated 'newsroom/press-resources/index.html' to remove Press page logo section.
- Updated 'static/css/press-resources.less' to remove Press logo styling.
None
=> DF-1679: Remove logo and usage section on Press page

doing-business-with-us/past-awards/index.html, static/css/cf-enhancements.less
Till the multi-line link list pattern is fleshed out completely this PR
scopes the styles for that in cf-enhancements so it doesn’t conflict
with un-migrated styles on the press resources page.
- Scopes multi-line list styles. 
- Additionally, adds a class wrapper for the procurement history page
so styles can be targeted there as well.
- visit /budget/financial-report/,  /newsroom/press-resources/, and /doing-business-with-us/past-awards/ and all should look okay in the icon lists.
- @sebworks 
- This is a patch and will need to be re-worked to allow the multi-line icon lists to handle when the classes for them are added directly in the markup instead of in pure CSS.
=> Fixes DF-1677 - scopes multi-line list styles.

_lib/wordpress_post_processor.py
Previously, for Newsroom, we were indexing Press Release authors, which included some user names and other less than desirable outcomes.  This first checks to see if it's in the Press Release category, and doesn't index the author if it is a Press Release.
Review: @willbarton @kurtw
=> Do not index press release authors

README.md
Updates typo and adds more instructions for brew to the testing section
of the readme.
- Adds instructions for running `brew info` to find chromedriver installation path.
- Updates typo in `somewhere` text.
- @sebworks 
- @jimmynotjim
=> Minor update to testing readme

static/css/misc.less
Fixes symmetry issues with Step Slug #363 
- Updated 'static/css/misc.less' to fix issues with padding and size.
- @ajbush 
- @duelj 
- Removed the adjustment to the font-size of the circle for symmetry purposes. Wasn't able to adjust font-size without adding extra markup. 
- Will require Design sign-off
=> Fix for Step Slug symmetry

static/css/post.less
Adjust Blog Post spacing to be consistent with the FJ visual spacing rhythm
- Updated ' static/css/post.less' to adjust margins to be consistent with the FJ visual spacing rhythm.
- @duelj
=> Blog Post Spacing

_settings/eslint.yaml
Relaxes two eslint settings.
- Relaxes `no-process-exit` and `no-shadow` to warnings per https://github.com/cfpb/front-end/issues/15#issuecomment-86807412
- @sebworks 
- @cjfont
=> Relaxes eslint settings

_includes/post-macros.html
Fixed an issue within Newsroom and Activity Log filters where selecting "Blog" + another category would return zero results.
None
None
- Updated filter macro to set "Blog" options
Fork, open locally, and test category filters. "Blog" + another category should return results.
- /newsroom
- /activity-log
- @schaferjh 
- @dpford 
- @sebworks 
- when selected "Blog" was passing as a "format_type" instead of "filter_category"
- will need blog posts set correctly in prod content
=> DF-1735 Fixed "Blog" category issue

_queries/newsroom.json, _queries/posts.json
**This PR requires a slight modification to sheer which was made [here](https://github.com/cfpb/sheer/pull/95)**
This adds the required settings to the blog and newsroom files in `/_queries/` to enable RSS feeds.  This pattern can be followed for other post types that require feeds.
=> Feeds for blog, newsroom

newsroom/featured-topic.html
Fixed featured topic links
- None
- None
- Added `jump-link` with the `__right` modifier
Fork and navigate to /newsroom at a smaller browser size
- @duelj 
- @sebworks 
- links were missing jump-link and right styles
=> DF-1438 Fixed featured topic links

govdelivery-subscribe/error/index.html
* Fixed a couple typos in the existing language.
* Commented it out rather than deleted, since it's a good foundation for what we really want down the line. Anyone who will actually look at the source will get a suggestion of functionality that's coming, which is not a bad thing.
* Wrote new temporary language. Spent way more time than appropriate figuring out mobile-friendly line breaks for such a temporary need.
* @sarahsimpson09 
* Any dev who feels like it
=> Update email error page language

contact-us/contact-list.html, static/css/cf-enhancements.less, static/css/contact-us.less
Added full width button modifier for buttons on smaller screens
- added `btn__full` modifier to CF Enhancements
- removed set width on `contact-list_btn`
- added `btn__full` class to "show all" button
- navigate to /contact-us and test "show all" button
- @sebworks 
- useful for small screens where a button should fill the space left to right
- added to cf-enhancements for testing purposes, should be integrated with cf-buttons in the future
=> Added full width button modifier

newsroom/index.html
Fixed the related links module by replacing the WP `view` with a manual list of links
- none
- removed unnecessary `view` var
- created a manual list of related links in `/newsroom`
- navigate to `/newsroom` and check the related links at the bottom of the page
- @duelj 
- @sebworks 
- temporarily using a static list of links. BEWDs will need to update the data returned by the `view` to pull in the related links from WP
=> Fixing the related links module on /newsroom

_includes/email-subscribe-form.html, privacy-policy/_vars-privacy-policy.html, privacy-policy/index.html
Include privacy statement next to email sign-up fields 
- Updated ' _includes/email-subscribe-form.html' to include privacy act copy.
- Added  'privacy-policy/_vars-privacy-policy.html' to include privacy navigation.
- Added 'privacy-policy/index.html' to add privacy page.
- This hasn't been seen or vetted by the design team so will need to show in Design Review for approval.
- @duelj 
- @juidai
=> DF-1436_Privacy_page

CHANGELOG.md, _includes/posts-paginated.html, _lib/wordpress_post_processor.py, _queries/featured_topic.json, _queries/watchroom.json, _settings/lookups.json, _settings/processors.json, _tests/browser_testing/features/environment.py, _tests/browser_testing/fixtures/featured_topic.json, _tests/processor_tests/tests/test_wordpress_orgmember_processor.py, _tests/processor_tests/tests/test_wordpress_post_processor.py, _tests/processor_tests/tests/test_wordpress_post_processor_featured_topic.json, newsroom/index.html
This changes the name of "Watchroom" to "Featured Topic" to make it clear to the content editors what they are editing. The changes correspond to the Newsroom page where the latest "Featured Topic" is displayed at the top. 
This PR also corresponds to a change in the flapjack plugin that holds the post type and metabox. Both do renaming and should be reviewed/approved simultaneously. 
@dpford @willbarton @Scotchester @jimmynotjim @anselmbradford 
I can't find Steven's username. If someone could tag him that would be great.
=> Change the name "Watchroom" to "Featured Topic"

CHANGELOG.md, README.md
Moves semver info to top of the changelog.
- Fixes #460 - moves semver info to changelog.
- Check Readme and Changelog.
- @sebworks 
et al
=> Fixes #460 - moves semver info to changelog

_settings/eslint.yaml, static/js/app.js, static/js/breakpoint-handler.js, static/js/content-slider.js, static/js/jquery.cf_input-split.js, static/js/jquery.type-and-filter.js
ESLint file cleanup.
- Adds `align: value` property to `key-spacing` rule, which left-aligns values of properties in an object literal declaration.
- Generalizes comments to describe the rule not the state of the rule.
- @sebworks 
- @jimmynotjim
=> Eslint comments

INSTALL.md, README.md
Moves installation instructions to INSTALL.md to de-clutter Readme.
- Adds INSTALL.md
- Moves installation instructions from Readme to INSTALL.md.
- Downcases `NPM` > `npm`, since that's how it's written on npmjs.org.
- Fixes misnamed `sheer` virtualenv.
- Misc. minor copy updates.
- See that Readme and INSTALL.md order and content makes sense.
- @sebworks 
et al
=> Moves installation instructions to INSTALL.md

CHANGELOG.md, _layouts/base.html
In reviewing the code I did for the forthcoming campaign landing page, Beth Anne noticed that the ID in our GTM snipped is out of date. This fixes that.
- Google Tag Manager ID in `base.html`
- ???
- I will ask Beth Anne how it can be confirmed to be working once the code is deployed.
- @jimmynotjim
- @sebworks
=> Update Google Tag Manager ID to production account

.env_SAMPLE, INSTALL.md, README.md
Updated the project to use the same `.env` config OAH is using. Will hopefully simplify the on-boarding process for new team members.
- Adds .env example to get users started
- `$`s, because we work for the people
- Section on adding the `cfgov-refresh-venv` function
- Updates the relevant instructions in INSTALL
- Updates the relevant instructions in README
Uninstall everything and try getting the project running following the updated instructions (refer to the internal docs for the `.env` variables)
- @cfarm
- @sebworks 
- et al.
- I left out the public WP API endpoint from the `.env_SAMPLE` but I'd argue we should include it by default. Let's discuss the pros and cons of that in the comments.
=> Updating project to use environment config

_includes/email-subscribe-form.html, blog/index.html, events/index.html, newsroom/index.html
Fixed error when submitting an email subscription due to missing category IDs.
- None
- None
- Set list IDs when calling macro from each post type landing page
- Removed categories list from form options
Fetch branch and navigate to:
- `/blog/`
- `/newsroom/`
- `/events/`
You shouldn't see the "We're still building this" error page
- @sebworks 
- @dpford 
None
- The generic "We're working on this" error page will need updating. @jameshupp is working on content and I'll include that later.
- Although the error due to missing IDs is fixed, I'm now running into a GovDelivery server error. Not sure if this is expected due to running locally or something else. Any ideas @dpford?
=> Fixed email subscribe form ID error.

_includes/article.html, _includes/category-slug.html, _includes/post-macros.html, _includes/posts-paginated.html, _lib/wordpress_post_processor.py, _settings/mappings/posts.json, _tests/browser_testing/features/environment.py, _tests/browser_testing/features/pages/newsroom.py, blog/index.html
Right now, filtering for blog posts within the Newsroom is not working.  The checkbox for "Blog" in the Newsroom filters is being set manually.  There are similar manually-set code smells in the Activity Log.
This PR creates a new field for blog categories called `blog_category`.  All of the categories for blog posts (that were previously included in `category`) are now housed there.  All other categories (at this point, just Newsroom objects) still live in the `category` field.  From the Newsroom's and Activity Log's perspective, all blog posts have a category of Blog.
**To test**: try using the filter in the /blog/, /newsroom/, /activity-log/ sections of the site, including filtering for blog posts.  The browser tests have also been updated.
**Review**: @Scotchester @jimmynotjim …
=> Reconciled multiple categories for blog posts

_layouts/404.html, _layouts/500.html
400 and 500 error pages had unminified JS path for common.js. This
commit changes it to the minified version in use.
- Corrects JS path in 400 and 500 pages.
- @sebworks 
- @jimmynotjim
=> Hotfix: corrects JS paths for 400 and 500 error pages

_includes/category-slug.html, _includes/post-macros.html, activity-log/index.html
Fixing category icons on the blog. 
- Added new categories with their appropriate icons
- Removed old category names
- Made a small change to `action-log/index.html` to fix #511
- Visit /blog/ to see it in action
- This macro is also being used at /activity-log/, so test that page too.
- @sebworks 
- A lot of the posts don't have new categories and look blank like this. From my understanding, this is a longer-term issue and outside of the scope of the review.
=> Fixing category icons and small typo in activity log

_lib/wordpress_view_processor.py
This reverts the only change made to the view processor since the previous successful deploy to beta.  Indexing views tripped up the deployment process recently, so I'm hoping this fixes it.  We're not using the date field of this post type, so the formatting of the date isn't important.
=> Remove postprocessing of date field in view processor

CHANGELOG.md, _layouts/base.html
Since this code eventually gets pushed publicly to beta this is probably the time to remove the demo text from the title (or alternatively name it something that doesn't include cfgov-refresh)
- demo text suffix from page titles.
- Visit any page, note page title.
- @sebworks 
- @jimmynotjim
=> Removes demo text in title

CHANGELOG.md, Gruntfile.js
Adds `--quiet` grunt option so that CLI can suppress linter warnings, if desired.
- Adds `--quiet` grunt option, with false as a default value.
- Sets eslint `quiet` option to use value of `--quiet` flag.
- Run `grunt lintjs` and see warnings in the output, run `grunt lintjs --quiet` and see no warnings. It can also be attached to other commands, such as `grunt test --quiet` and `grunt jsdev --quiet`.
- @sebworks 
=> Eslint quiet flag

CHANGELOG.md, package.json, static/js/routes/common.min.js
Update grunt-browserify to 3.8.0 and removes redundant browserify dependency.
- Removes browserify module from package.json, because browserify is downloaded via grunt-browserify already.
- Fixes typo and order of grunt-browserify module to minimize conflicts with https://github.com/cfpb/cfgov-refresh/pull/527
- Update grunt-browserify to 3.8.0 from 3.7.0, which updates Browserify to 10.0.
- Throw out node_modules and re-install with `npm update`. Run `grunt vendor` and `grunt jsdev` to regenerate assets and see that the site doesn't break.
- @sebworks 
- @jimmynotjim
=> Update grunt-browserify to 3.8.0

govdelivery-subscribe/error/index.html
Adjusted copy to reflect:
1. The signup functions.
2. Signup errors are most likely to be about communicating with the vendor, so sending them to another signup is not going to be super helpful.
@jimmynotjim 
@sarahsimpson09 
The last line might be a little odd. I just thought it might be a way to get more business units excited about sending emails. Regular communication is good for us!
=> Changed copy on email signup error

CHANGELOG.md, offices/_offices-index.html
This fixes the jinja error on the Office Page template by updating the macro from #505.
- Changed email macro on office template
1. Index on a server that has the offices post_page type.
2. Navigate to /offices/students-2/
3. No more Jinja error!
- @sebworks 
- Resolves DF-1873
=> Fixed email subscribe on office page template

CHANGELOG.md, Gruntfile.js
Removes string-replace:static-legacy task. Fixes #543.
- Removes Grunt `string-replace:static-legacy` task and references to that task.
- Grunt should still work as expected. Grunt vendor will have one less task.
- @sebworks 
- @jimmynotjim
=> Removes string-replace:static-legacy task from Gruntfile

CHANGELOG.md, Gruntfile.js
Adds path variables to Gruntfile for consistency with generator-cf, with the addition of a test directory path. Part of DF-1857.
- Adds `loc.src`, `loc.dist`, and `loc.test` path variables to Gruntfile.
- All grunt tasks should not have changed.
- @sebworks 
- Paths in the gruntfile that are not prefixed with the path variables are the vendor paths, which will be moving to /src/, the CSS source paths, which will also be moving to /src/, and the legacy-static paths, which are special snowflakes.
=> Adds path variables to gruntfile

CHANGELOG.md, Gruntfile.js
Creates Grunt build task. Part of DF-1857.
- Adds Grunt build task.
- Sets build task to Grunt default.
- Changes `jsdev` and `cssdev` task names to `js` and `css`.
- Moves testing to build task.
- `grunt` and `grunt build` should both build the assets. `grunt js` and `grunt css` should work, and `grunt jsdev` and `grunt cssdev` should not.
- @sebworks 
- JS/CSS names are based on generator-cf https://github.com/cfpb/generator-cf/blob/master/app/templates/_Gruntfile.js#L296-L297
=> Creates Grunt build task

CHANGELOG.md, _lib/wordpress_view_processor.py
This relieves [this issue](https://jira.demo.cfpb.gov/browse/DF-1327) and fixes some formatting issues in the View processor. Basically, a View post would have a Hero's slug saved in a custom field. That slug is used to lookup and serve the content of the Hero, but when the Hero is deleted an indexing error occurs. That's because the slug used to do the lookup does not exist but the code does not account for this. Now it does.
@dpford @jimmynotjim @sebworks @anselmbradford @KimberlyMunoz
=> Fix sheer indexing error in views and fix some formatting

CHANGELOG.md, _includes/contact-macro.html
Updated key names in contact info condition. Fixes issue where some contacts weren't showing phone numbers and email addrs
- None
- None
- Updated contact condition in contact-macro 
- Checkout branch and check offices in `/contact-us`
- @sebworks 
- Hat toss to @dpford for finding this
=> Updated key names in contact info condition

Gruntfile.js
Converts `envQuiet` gruntfile  variable in `env` object so additional
environment variables may be added in the future in addition to
`envQuiet`.
- Changed `envQuiet` to `env.quiet`.
- `grunt lintjs --quiet` should still work as expected.
- @sebworks 
- Covered in existing changelog comments, no updated required.
=> Creates gruntfile env object

.eslintrc, CHANGELOG.md
Relaxes key-spacing rule to warning for consistency with space-in-parens and space-in-bracket settings.
- Changes key-spacing to warning.
- Removes unneeded newline.
- Misalignment of property values in an object literal should throw a warning, not an error, and thus won't break a build.
- @sebworks 
- Per update in https://github.com/cfpb/front-end/pull/50
=> Relaxes ESLint key-spacing rule to warning

CHANGELOG.md, INSTALL.md, README.md, setup.sh
Adds setup.sh script for bootstrapping the project and updates
installation instructions.
- Adds setup.sh script for bootstrapping the project.
- Updates README.md and INSTALL.md.
- From the root directory, run `./setup.sh`. That's all. YESSS! Want to re-install everything? Run `./setup.sh`.
Site should function/look the same.
- @sebworks 
- See background in https://github.com/cfpb/front-end/issues/49
- Sorry for the weekend update. Since I'm out most of next week I wanted to get it in before I forgot what on earth I was doing. Doesn't have to be in this sprint.
=> Adds setup.sh script for bootstrapping the project

CHANGELOG.md, Gruntfile.js, package.json
Removes legacy copy static-legacy task and associated package.
- Remove `copy:static-legacy` and `grunt-contrib-copy` package.
- No change.
- @sebworks 
- Like https://github.com/cfpb/cfgov-refresh/pull/544 this task appears only to be needed if the CF font was updated and the legacy pages at `/budget/strategic-plan/interactive/` needed those updated fonts, or if another legacy page was added. See https://github.com/cfpb/cfgov-refresh/issues/543#issuecomment-102077254
=> Remove `copy:static-legacy` and `grunt-contrib-copy`

CHANGELOG.md, _includes/header.html, _includes/nav-items-toplevel.html
Adds top and first-level nav items configuration file to remove hardcoded
navigation menu items.
- Added top and first-level navigation items config file for removing hardcoded navigation menu items in the main menu.
- Adds TODO comment for commented out Español code block.
- Builds main menu from global nav-items configuration file.
- Main menu should function/look the same.
- @sebworks 
- Part of DF-1963, because I need a list for the sidenav menu to build the structure from. This is a self-contained change so I wanted to spin it off for feedback while I worked on the sidenav implementation.
=> Adds top and first-level nav items configuration file

_layouts/layout-side-nav.html
Fixes #592 - removes legacy `section_vars`.
- Fixes #592 - removes legacy section_vars, which is unused.
- Updates URL in code comment to correct docs URL.
- Site should function the same.
- @sebworks
=> Fixes #592 - removes legacy section_vars

.eslintrc, CHANGELOG.md
Relaxes ESLint complexity to max 4 to conform to fewd standards setting.
- Relax ESLint complexity setting from max 3 complexity to 4. See https://github.com/cfpb/front-end/pull/51 for background reading.
- ESlint won't show warnings for cyclomatic complexity 4 code. (For example an if/elseif/elseif statement.)
- @sebworks 
- @jimmynotjim
=> Relaxes ESLint complexity to max 4

the-bureau/index.html
The existing text, "Our mission," is not 100% accurate and ended up confusing people in testing. After some discussion, we decided to change.
"The Bureau" was also under consideration, as it mirrors the sidebar text. But the video hero at the top made putting the title there seem a bit anticlimactic. And it felt like that intro paragraph would need a bit of rework. "Who we are" seems like we can leave that text as-is.
* @schaferjh
=> Changing text of H1 above The Bureau intro paragraph

CHANGELOG.md, _lib/wordpress_office_processor.py, _lib/wordpress_sub_page_processor.py, _settings/mappings/office.json, _settings/mappings/sub_page.json
Currently, we are associating FAQ's with sub-pages. We need them to be associated with offices as well, so it seems that forcing the sub_page and the office to specify the FAQ makes the most sense. This adds the related_faq field that contains the slug of the FAQ to retrieve. 
@dpford
=> Change processors and mappings to include specification of FAQ

.travis.yml, _tests/macro_testing/requirements.txt, _tests/macro_testing/tests/post-macros.json
Added our unit tests, the sheer installation and @willbarton's macro tests to Travis.
- Added travis.yml for Travis CI integration
- Fixed requirements for our macro tests
- Updated the macro tests. (I think I was the one who originally broke them before I realized these existed. 😳)
- If all goes according to plan there should be a green check mark below here in a couple minutes.
- @sebworks 
- @imuchnik & @contolini
- @willbarton
- Browser tests will be added to Jenkins after this
- The processor tests will need to be fixed before we add them
- I left the Sheer installation in there since processor changes can sometimes mess with sheer indexing and it'd be great to have a heads up for those changes. ~~However I noticed that Travis will sometimes error out while …
=> Automating our unit tests and macro tests

CHANGELOG.md, _lib/wordpress_sub_page_processor.py, _settings/mappings/sub_page.json
This merely adds the short_title and preview_text fields to the sub_page document for use in the templates.
- `short_title` is used for the `Our Work` section and the navigation so the actual title's of the sub_page's won't be too long for the module
- `preview_text` is the content used for specifying what the link to the sub_page should have as the text.
@sebworks @anselmbradford @dpford @KimberlyMunoz
=> Add short_title and preview_text fields to sub_page document

CHANGELOG.md, _includes/templates/activities-feed.html, offices/_single.html, sub-pages/_single.html, sub-pages/_vars-sub-pages.html
Normalizes office section titles and removes legacy code.
- Creates HTML template for activity feed that offices and sub-pages
templates share.
- Removes hardcoded values from sub-pages vars.
- Normalizes office section titles for activity feed and contacts.
- Offices pages and subpages should contain the text `LATEST ACTIVITIES` and `Contact Information` (NOTE: contacts aren't currently showing up, so that title can't be previewed).
- @sebworks 
- @kurtw 
- https://github.com/cfpb/cfgov-refresh/pull/644 will likely change the Contact Information to the same thing, so I'll just rebase here if needed.
=> Normalizes office section titles, removes legacy code

events/request-a-speaker/_faq.html, events/request-a-speaker/index.html
Updated request a speaker template w/ static content instead of relying on the CMS content
- None
- None
- Replaced placeholder content with true content
- navigate to `/events/request-a-speaker/`
- @sebworks 
- RaS is not related to an office, using static content until further notice
- All content copied from RaS sub-page and FAQ on WordPress
=> Updated request a speaker w/ static content

CHANGELOG.md, contact-us/index.html
Where did the sidebar go?
Oh, there it is!
- Fixed missing sidebar on `contact-us`
- Visit `/contact-us`
- @sebworks
Before:
After:
=> Bugfix: Re-adding missing content_sidebar

CHANGELOG.md, README.md, _includes/macros/activity-snippets.html, _lib/wordpress_office_processor.py, _lib/wordpress_sub_page_processor.py, _settings/mappings/office.json, _settings/mappings/sub_page.json, activity-log/index.html, blog/_vars-blog.html, contact-us/index.html, events/_vars-events.html, newsroom/_vars-newsroom.html, newsroom/index.html, offices/_single.html, offices/_vars-offices.html, sub-pages/_single.html, sub-pages/_vars-sub-pages.html, the-bureau/bureau-structure/index.html, the-bureau/history/index.html, the-bureau/leadership-calendar/index.html, the-bureau/leadership-calendar/print/index.html
The relationship between Offices and Subpages changed. The Office will now be designating which Subpage will associated with it, not the other way around. These changes reflect that.
To test, create two Subpages. One parent and one child. I'd put some info in the fields just so you know what you're looking at. Second, create an Office that points to the parent Subpage. The dropdown will only include parent Subpages so you shouldn't have to worry about choosing the wrong one.
**WARNING** This will not working without [this code pulled into sheer.](https://github.com/cfpb/sheer/pull/108)
Pull in production data, and make sure [you have pulled this into sheer](https://github.com/cfpb/sheer/pull/108). The navigation on Office's and Subpage's should be working properly. This, and if …
=> Fix Navigation for Office/Subpage

CHANGELOG.md, _settings/processors.json
This removes the event's processor that's causing the indexing error.
Tested and nav is working.
just index and serve
go to office pages
go to their sub-pages
@jimmynotjim @anselmbradford @KimberlyMunoz @dpford
=> Take out event processor to fix python indexing error

CHANGELOG.md, _queries/links.json, links.sh
When sending people to external links, we need the ability to check that the link originated on our site.  This script gathers all of the links from A) cfgov-refresh codebase, and B) the Elasticsearch index associated with the site, and indexes them as a new type called "link".   This requires [Sheer 3.0.0](https://github.com/cfpb/sheer/releases/tag/3.0.0) or greater.
To try it locally, simply run `./links.sh` from the root of cfgov-refresh.  Once merged, this will be placed into a Jenkins job to be run on each `sheer index` and each deploy of new code.
Here's an example usage from within a template:
```
{% set query = queries.links %}
{% set vetted_urls = query.possible_values_for('url') | possibles_to_list %}
{% if request.args.get('ext_url') and request.args.get('ext_url') | …
```
=> Add script to index all links on our site

careers/_vars-careers.html
Updates hierarchy and entries in the careers nav.
- Removes careers entries that are not a part of this sprint.
- Updates careers nav vars file to nest all careers entries under main careers landing page.
- e.g. `/careers/students-and-graduates` should show a hierarchy and reduced number of sidenav options.
- @sebworks 
- Part of DF-2099
=> Updates hierarchy of careers nav

CHANGELOG.md, _includes/templates/summaries/linkedin.html, careers/_template-careers-related-links.html, careers/_template-current-openings.html, careers/_template-job-app-process.html, careers/_template-students-and-graduates.html, careers/_template-working-at-cfpb.html, careers/students-and-graduates/index.html, careers/working-at-cfpb/index.html
Updates students-and-graduates page to use templates introduced in https://github.com/cfpb/cfgov-refresh/pull/686
- Added templates for career page summaries.
- LinkedIn text per @sarahsimpson09 comment.
- Minor apostrophe fixes.
- Moved careers-specific templates from the global _includes folder to the careers folder.
- Updated students and graduates page to:
- Remove wrapper `section`.
- Use templates for bottom half of page, for blocks that get reused elsewhere in careers.
- Changes title to "Students and Recent Graduates."
- Adds borders and removes bottom margin from footer.
- Adds disabled link styling.
- Updated working at the CFPB page to:
- Use related links template.
- Appearance of `/careers/working-at-cfpb/` and `/careers/students-and-graduates/` should be similar.
- …
=> Updates students-and-graduates page to use templates

CHANGELOG.md, offices/_vars-offices.html, sub-pages/_vars-sub-pages.html
This fixes the links in the navigation for offices and subpages on beta, and fixes the ordering of subpages in the nav on the office page.
Currently we don't know why, but the permalink feature of sheer is unstable on beta, though seems to act normally in staging. This removes that complexity and "hard-codes" the slug into the appropriate url pattern. We know the slug is available on beta, so we deem this appropriate to fix that issue. Additionally, the subpages in the navigation should be ordered based on the order given in the CMS. This is not happening when visiting an office page.
@jimmynotjim @sebworks @anselmbradford @KimberlyMunoz
=> HOTFIX nav links and order of nav items on office page

_includes/contact-macro.html, contact-us/general-inquiries.html
Fixes #688.
This is a tiny PR and should only affect `/contact-us/` to bring it in line with the new way we're doing labels.
=> Removing colons

CHANGELOG.md, _lib/wordpress_event_processor.py, _settings/mappings/event.json, _settings/processors.json
This adds in support for the [ICS file generator](https://github.com/cfpb/flask-eventics/pull/2) within the Event processor by creating a dictionary for the necessary information the generator needs. It also deletes the taxonomy data that isn't used afterwards, and sorts the data by key; both of which are for the purpose of readability when examining the event data.
Go to the linked ICS generator and clone it into your folder where cfgov-refresh lays. Then follow the instructions to install its dependencies and install it into your venv. After you've done that:
- Create a Event with the latest plugin code in Unitybox (wp-flapjack, cms-toolkit)
- Index it! (that being Unitybox)
- Make sure there's a dictionary in the data called `ics` after indexing. It should look like this
```json
"ics": …
```
=> Add in support for ICS file generator

CHANGELOG.md, _includes/macros/sub_pages.html, offices/_single.html, sub-pages/_single.html
Fixes issues with displaying grandchild pages on /sub-pages/.
- Updated  'offices/_single.html' to use macro for displaying sub pages.
- Updated  'sub-pages/_single.html' to use macro for displaying grandchild pages.
- Added  '_includes/macros/sub-pages.html' to display sub page excerpts.
- Visit 'http://localhost:7000/sub-pages/civil-penalty-fund/'
- Some of the content of the page needs to be updated.
- Links are currently inoperable and will be implemented in separate PR.
@jimmynotjim
@KimberlyMunoz
@kurtw
=> Fix for Grandchild pages on /sub-pages/.

CHANGELOG.md, _includes/templates/footer.html
Adding Open Government link to footer.
- Updated '_includes/templates/footer.html' to add link to footer.
- Visit 'http://localhost:7000/' and view footer.
-
@jimmynotjim
=> Adding Open Government link to footer.

CHANGELOG.md, _settings/mappings/events.json
Stop ES from analyzing tag data, which causes filtering on the Event's archive page to not return expected results.
@jimmynotjim @dpford
=> Fix Event tag filtering on Event Archives page

src/_includes/leadership-calendar-table.html, src/_includes/templates/office-contact.html, src/blog/_single.html, src/blog/index.html, src/careers/_macro-table-current-openings.html, src/contact-us/_template-contact-list.html, src/contact-us/_template-mailing-addresses.html, src/contact-us/_template-submit-a-complaint.html, src/events/_event-post-macros.html, src/events/_single.html, src/events/archive/_single.html, src/newsroom/_single.html, src/newsroom/index.html, src/newsroom/press-resources/index.html, src/privacy-policy/index.html, src/the-bureau/about-rich-cordray/index.html, src/the-bureau/about-steve-antonakes/index.html, src/the-bureau/history/index.html, src/the-bureau/index.html, src/the-bureau/leadership-calendar/index.html
We have been over-using u-mt0 and u-mb0. This fixes #696.
- Making changes to use block__flush-top or block__flush-bottom instead of u-mb0 and u-mt0
- @sebworks 
=> Changing to block__flush-top/bottom

TERMS.md
Forgot to remove requestAnimationFrame from Terms in https://github.com/cfpb/cfgov-refresh/pull/749
- Removes requestAnimationFrame from `TERMS.md` 
- @sebworks 
- **Question:** Should we remove all the entries in the Exceptions area in `TERMS.md` that are coming from third-party sources, such as Rainbow (part of cf-component-demo). Anything in that list only needs to be there if the third-party code is committed to this repo, right? When we move to having a /dist/ directory the majority of those can be removed.
=> Removes requestNextAnimationFrame from Terms

CHANGELOG.md, src/static/js/modules/jquery/cf_formValidator.js, src/static/js/modules/polyfill/array-filter-polyfill.js, src/static/js/modules/polyfill/array-map-polyfill.js, src/static/js/modules/polyfill/array-polyfills.js
Input validation is currently inoperable on IE8 when submitting forms. 
Closes issue https://github.com/cfpb/cfgov-refresh/issues/758
- Updated 'src/static/js/modules/jquery/cf_formValidator.js' to require array polyfills.
- Added 'src/static/js/modules/polyfill/array-filter-polyfill.js' to polyfill the array filter method.
- Added 'src/static/js/modules/polyfill/array-map-polyfill.js' to polyfill the array map method.
- Added 'src/static/js/modules/polyfill/array-polyfills.js' to group polyfills.
- Visit 'http://localhost:7000/blog', expand the filter and enter '01/11/2011' in the `From` field.
- 
@jimmynotjim
=> Adding map/filter Array polyfills

CHANGELOG.md, src/offices/_single.html, src/sub-pages/_single-grandchild-pages.html, src/sub-pages/_single.html
Fixes activity feed logic to only display when tags are present. 
- Updated 'src/sub-pages/_single.html' to display activity feed only when tags present.
- Updated 'src/offices/_single.html' to display activity feed only when tags present.
- Updated 'src/sub-pages/_single-grandchild-pages.html' to display activity feed only when tags present.
- Visit 'http://localhost:7000/offices/privacy/' and observe the activity feed.
- Visit 'http://localhost:7000/sub-pages/civil-penalty-fund/' and observe the activity feed.
@jimmynotjim
@KimberlyMunoz
=> Offices activity feed logic fix

CHANGELOG.md, src/careers/current-openings/opening.html, src/static/css/cf-enhancements.less, src/static/css/share.less
Initial template for the single career postings
- created initial template
- created 1/4 and 3/4 layout columns
- added DL styles to cf-enhancements
- None
- updated block-bg padding in cf-enhancements based on JJames feedback
- navigate to `/careers/current-openings/opening.html`
- @duelj 
- @ajbush 
- @sebworks 
- template should be renamed _single and tied to data when ready
=> DF 2146 career posting

CHANGELOG.md, src/offices/_single.html, src/static/js/routes/common.js, src/static/js/routes/offices/index.js
Fix for MobileOnlyExpandable on office page
Closes issue https://github.com/cfpb/cfgov-refresh/issues/642
- Updated 'src/offices/_single.html' to remove MobileOnlyExpandable code.
- Updated 'src/static/js/routes/common.js' to use page specific javascript for Office page.
- Added 'src/static/js/routes/offices/index.js' to use page specific javascript for Office page.
- Visit 'http://localhost:7000/offices/privacy/', open console, and observe error free goodness.
@jimmynotjim
@KimberlyMunoz
=> Fix for MobileOnlyExpandable on office page

src/_lib/django_calendar_event_processor.py, src/_lib/wordpress_contact_processor.py, src/_lib/wordpress_event_processor.py, src/_lib/wordpress_faq_processor.py, src/_lib/wordpress_featured_topic_processor.py, src/_lib/wordpress_history_processor.py, src/_lib/wordpress_newsroom_processor.py, src/_lib/wordpress_office_processor.py, src/_lib/wordpress_orgmember_processor.py, src/_lib/wordpress_page_processor.py, src/_lib/wordpress_post_processor.py, src/_lib/wordpress_sub_page_processor.py, src/_lib/wordpress_view_processor.py
**REQUIRES VERSION [3.3.1](https://github.com/cfpb/sheer/releases/tag/3.3.1) OF SHEER, RELEASED 7/9**
Instead of supplying the ES index name in the processors, sheer has been updated to respect the index name provided by the user (otherwise it'll use the default).  As such, we no longer need to be defining this in the processor files.
=> Don't specify index in processor files

CHANGELOG.md, src/offices/_single.html, src/sub-pages/_single.html
Updating Office pages for Advisory Group office
- Updated 'src/offices/_single.html' to surrounding nesting of `p` tags.
- Updated 'src/sub-pages/_single.html' to always display activity feed when tags present.  
- Updated 'src/sub-pages/_single.html' to display related documents.
- Reindex Sheer.
- Visit 'http://localhost:7000/offices/advisory-groups/'.
- This PR will cause  the "Related Documents" section (related_links) to appear on a number of sub pages. 
@jimmynotjim
@schaferjh
=> Updating Office pages for Advisory Group office

CHANGELOG.md, src/_includes/templates/nav/_vars-primary-nav.html, src/offices/_single.html, src/static/css/pages/offices.less
Adds changes for Project Catalyst
- Adds Project Catalyst to the mega menu. 
- Adds `office.content` block.
- Updates headings for `top_story` and `resource.title` to h2 to match heading level of `Our Work`.
- /offices/project-catalyst/
- @sebworks 
- There is a list of content updates that will go to Sarah after this PR, so if something doesn't look right, inspect element and see that it's not because of hardcoded inline styles coming from the CMS.
- Incorporates changes in https://github.com/cfpb/cfgov-refresh/pull/776, with the assumption that that PR will be merged first.
=> DF-2251 - Project Catalyst

CHANGELOG.md, src/_includes/macros/expandable.html, src/offices/_single.html, src/sub-pages/_single-grandchild-pages.html, src/sub-pages/_single.html
Update styling for FAQs.
Closes issue https://github.com/cfpb/cfgov-refresh/issues/778.
- Updated 'src/_includes/macros/expandable.htmll' to add specific arguments and logic for FAQs.
- Updated 'src/offices/_single.html' to move import statement block if condition.
- Updated 'src/sub-pages/_single.html' to pass in FAQ title.
- Updated 'src/sub-pages/_single-grandchild-pages.html' to pass in FAQ title.
- Visit 'http://localhost:7000/sub-pages/civil-penalty-fund/.
- @sarahsimpson09 , /sub-pages/frequently-asked-questions/ will need to be changed to remove some unnecessary copy. 
@jimmynotjim
@KimberlyMunoz
=> DF_2292 FAQ restyling

Gruntfile.js
I wonder if there's a way to make this more surgical: ie, only copy the file that
changed.
=> Adds a `grunt watch` config to watch for changes to .html files, and execute the copy task

test/browser_tests/jenkins_conf.js
This adds the saucelabs tunnel we need for saucelabs to access our servers from Jenkins.  It also makes the name more descriptive in saucelabs.
Review: @jimmynotjim @kurtw @imuchnik
=> Add sauce tunnel config for jenkins

CHANGELOG.md, src/offices/_single.html, src/static/css/pages/offices.less, src/static/css/pages/sub-pages.less, src/sub-pages/_single-grandchild-pages.html, src/sub-pages/_single.html
Fixes to the sub-pages and office pages.
- Adds `sub-page_content` and `sub-page_content-markup` classes.
- Adds office page specific class for consistency with the classes added in the sub-pages template.
- Moves page specific sub-page class to enclosing content area (it wasn't including the intro block).
- Set branded list styles on known areas where unordered lists appear.
- Observe branded lists on /offices/project-catalyst/ page and subpages.
- @sebworks 
- I hate that extra classes are needed for this, but some links are in lists in the CMS so I can't just blanket apply the branded list to the main content area.
=> sub-pages and offices fixes

src/_includes/templates/nav/_vars-primary-nav.html
Updating mega menu to add 'Advisory Groups'.
- Updated 'src/_includes/templates/nav/_vars-primary-nav.html' to add advisory group to nav.
- Visit 'http://localhost:7000/' and hover on 'About'. Observe the omnipotent mega menu. 
@jimmynotjim
@KimberlyMunoz
=> Updating mega-menu to add Advisory Groups

src/_includes/macros/activity-snippets.html, src/_includes/macros/sub_pages.html, src/_includes/related-links.html, src/about-us/index.html, src/budget/index.html, src/careers/_template-current-openings.html, src/careers/_template-job-app-process.html, src/careers/_template-linkedin.html, src/careers/_template-provide-feedback.html, src/careers/_template-students-and-graduates.html, src/careers/_template-working-at-cfpb.html, src/careers/index.html, src/contact-us/_template-submit-a-complaint.html, src/doing-business-with-us/_future-block.html, src/doing-business-with-us/_smbiz-block.html, src/doing-business-with-us/index.html, src/newsroom/featured-topic.html, src/newsroom/press-resources/index.html, src/offices/_single.html, src/static/css/misc.less, src/static/css/pages/sub-pages.less, src/sub-pages/_single-grandchild-pages.html, src/sub-pages/_single.html, src/the-bureau/about-rich-cordray/index.html, src/the-bureau/about-steve-antonakes/index.html, src/the-bureau/index.html
(Except on heroes). According to guidelines from @schaferjh, blog posts will remain un-underlined, but everything else should be underlined.
- Added `.jump-link__underline` for links that need to be underlined on desktop and block on mobile.
- Changed many links with right arrows to use underline links instead
- Tests should still pass
- Look at every page and there should be arrows only on heroes
- @sebworks 
- Related Design Manual Discussion and Oscar Nomination for Best Github Selfie by @duelj : https://github.com/cfpb/design-manual/issues/264
- JIRA Issue: DF-2211
- Fixes #679
=> No more arrows

src/careers/_template-block-social.html, src/careers/application-process/index.html, src/careers/current-openings/index.html, src/careers/index.html, src/careers/students-and-graduates/index.html, src/careers/working-at-cfpb/index.html
A batch of changes from @duelj based on his feedback in JIRA
- Changing job posting date heading level
- Adjusting spacing between sidebar modules
- Mobile Module spacing adjustment
- Fixing Horizontal rule spacing inconsistency
- Visit `/careers/` and look for the following
1. there should be appropriate spacing between modules on mobile
2. The job posting dates should be the same as the other job posting dates in the sidebar
3. All horizontal rules should be the same size
- This corresponds to JIRA issues: DF-2228, DF-2229, DF-2230, DF-2231
=> Career Pages Adjustments from Design

CHANGELOG.md, src/static/css/pages/offices.less
Closes #783.
- Removed extraneous css not in use by project 
- Visit any office page with an "Our Work" section
- @sebworks 
- @jimmynotjim
=> Removing office_initiatives styles

test/browser_tests/spec_suites/shared/shared_contact-us.js
I broke the test on `/contact-us/` when I changed all our arrow links in #793. I also spaced out that line and one other in the file to fix two eslint warnings.
- run `protractor test/browser_tests/conf.js`
- @sebworks
=> Fixed Contact-Us Page Test

CHANGELOG.md, src/static/css/pages/offices.less, src/sub-pages/foia-records/index.html
@sebworks brought up in #799 that there's an old class from the old office design. This PR removes the old `initiative` class and bringing foia-records in line with other sub-page templates. It also fixes the CHANGELOG update from #799 to make it more specific per @anselmbradford request.
=> Removing extra class from #799

CHANGELOG.md, src/_settings/lookups.json
Careers wasn't in lookups.py which caused permalinks for that document type to not work. This adds it in the the file.
@anselmbradford @jimmynotjim
=> Add career type to lookups.py

CHANGELOG.md, src/_settings/lookups.json, src/careers/_vars-careers.html, src/careers/current-openings/_single.html
Tied data into single career template
- Added query for careers to vars-careers
- None
- Fixed the url in lookups
- Updated name of single career template and replaced placeholder content with data from the API
- `sheer index -p careers`
- navigate to `/careers/current-openings/1853/`
- @sebworks 
- @ajbush 
- @schaferjh
- Currently forcing just one applicant type, will PR for the multiple applicant types post Sprint
- There's lorem ipsum in the "Before you apply" block and I don't know what I'm supposed to replace it with, @sarahsimpson09 any ideas?
=> DF-2293-single-careers-data

src/careers/index.html
Quick fix for this review. This was a change made in #795 that got accidentally reverted. The dates should look similar to the dates in the activity feed.
- @sebworks 
=> Adjusting date styles on careers index page.

CHANGELOG.md, test/browser_tests/conf.js, test/browser_tests/jenkins_conf.js, test/browser_tests/page_objects/page_events.js, test/browser_tests/page_objects/page_the-bureau.js, test/browser_tests/spec_suites/large_screen/large_contact-us.js, test/browser_tests/spec_suites/shared/shared_about-us.js, test/browser_tests/spec_suites/shared/shared_careers-students-and-graduates.js, test/browser_tests/spec_suites/shared/shared_contact-us.js, test/browser_tests/spec_suites/shared/shared_events.js, test/browser_tests/spec_suites/shared/shared_the-bureau.js
Added tests for events and events archive
- Added page objects for both pages
- Added specs for both pages
- None
- Updated the specs in `conf.js` because the shared spec was being fired on the desktop test, even though those tests had already been run in Chrome. Now the desktop test only runs the desktop spec
- `grunt build && protractor ./tests/browser_tests/conf.js`
- @sebworks 
- @imuchnik 
- The tests hang and crash if you search for an element that doesn't exist. I wanted to search for the map on the archive page knowing it shouldn't be there, but it seems this is an issue that needs to be fixed first.
=> Events Tests

src/static/js/modules/simple-table-row-links.js
Converts click event to `click` from `mousedown`
- Converts click event to `click` from `mousedown` on simple table.
- @sebworks
=> Converts mousedown to click event on simple table row links

src/_includes/macros/sub-nav.html, src/static/css/nav-primary.less, src/static/js/modules/desktop-primary-nav.js, src/static/js/modules/mobile-primary-nav.js
Fixed issue displaying About Overview page on mobile
- Updated src/static/js/modules/mobile-primary-nav.js to display sub-nav heading on desktop.
- Updated src/static/js/modules/mobile-primary-nav.js to display sub-nav heading on mobile.
-  Updated  src/static/css/nav-primary.less  to always display sub-nav heading and override background color.
- Visit 'http://localhost:7000/' on mobile and invoke the navigation. Observe the About Overview nav item.
@jimmynotjim
@KimberlyMunoz
=> Fixed issue displaying About Overview page on mobile

CHANGELOG.md, src/_includes/macros/active-filters.html, src/_includes/post-macros.html, src/the-bureau/leadership-calendar/print/index.html
Fixed issue with Active_Filters macro on the `/leadership-calendar/print/` page. Macro relied upon legacy code in which I removed when working on filters. This PR creates a separate activity filters macro and restores the legacy code.
- Added  `src/_includes/macros/active-filters.html` to separate logic and fix issue on  `/leadership-calendar/print/` page.
- Updated `src/_includes/post-macros.htm`  to separate logic.
- Updated `src/the-bureau/leadership-calendar/print/index.html` to fix activity filter rendering issue.
- Visit 'http://localhost:7000/the-bureau/leadership-calendar/print/?filter_calendar=Richard+Cordray&filter_range_date_gte=2014-01&filter_range_date_lte=2014-02' and observe the majestic leadership calendar with filters.
@jimmynotjim
@dpford
=> Fixed issue with Active_Filters macro 

CHANGELOG.md, Gruntfile.js, setup.sh
Decouples `grunt test` from `grunt build` and moves it to `setup.sh`.
The reason for this is:
- Now that we we're using /dist/, running `grunt build` happens more frequently.
- Our test suite is growing larger/slower, so having it on-demand becomes more important.
- Travis is running our tests so will catch errors if `grunt test` is forgotten to run before submitting a PR (which should be done before a PR is opened).
- Removes test task from `grunt build` pipeline and moves it to `setup.sh`.
- Moves order of test task below lintjs task in Gruntfile.
- `./setup.sh` should run test suites.
- `grunt build` should not.
- `grunt test` should.
- @sebworks
=> Moves testing to setup.sh

src/_includes/macros/sub_pages.html, src/_includes/templates/nav/about-us-media.html, src/careers/application-process/index.html, src/static/css/footer.less, src/the-bureau/index.html
Fixes minor issues for Sprint-32-2
- Updated  `src/_includes/macros/sub_pages.html` to fix issue with expendables on Office pages.
- Updated `src/static/css/footer.less`  to fix issue with footer margin.
- Updated `src/the-bureau/index.html`  and `src/careers/application-process/index.html` to fix double link issue on mobile.
- Updated  `src/_includes/templates/nav/about-us-media.html` to fix issue with relative path for About-Us image.
@jimmynotjim
@KimberlyMunoz
=> Minor Sprint 32-2 fixes

test/macro_tests/test_macros.py, test/macro_tests/tests/event-landing-macros.json
Update `tests/macro_tests/test_macros.py` for the new directory structure and adds a working example `event-landing-macros.json` file to test `_event-landing-macros.html`. The test may or may not be adequate to test `_event-landing-macros.html`, but it is intended to be a working starting point.
This PR requires using Macro Polo from this PR: cfpb/macropolo#3 (See Testing below).
- Example tests for `_event-landing-macros.html`
- None
- Changes the path to templates in `test_macros.py` to make templates discoverable.
- `pip install git+https://github.com/willbarton/macropolo@other-templates` (cfpb/macropolo#3)
- `python test/macro_tests/test_macros.py`
- @dpford 
- @kurtw  
- @imuchnik 
Because this PR depends on unmerged Macro Polo changes, I anticipate …
=> Update test_macros.py for new macro path and add working event-landing-macros

setup.sh
Changes `clear` task to `clean` in `setup.sh` to be more consistent with the wording use in grunt, gulp, etc.
- Changes `clear` task to `clean` in `setup.sh`.
- `./setup.sh` should still work as expected.
- @sebworks 
- Per https://github.com/cfpb/front-end/issues/49#issuecomment-125229214
=> Changes clear to clean in setup.sh

CHANGELOG.md, src/_includes/templates/nav/_vars-primary-nav.html, src/index.html
Updates text from "About" to "About Us"
- Site's "About" text to "About Us".
- Visit the homepage and observe the glory of the About Us text in the progress graph and the megamenu! 
- @sebworks 
- @jimmynotjim
=> Fixes DF-2307 - About Us text

src/static/css/pages/offices.less, src/sub-pages/_single.html
Feedback from @ajbush:
> Across the site there are different stylings of bullet points. We would like to make these as cohesive as possible by:
>
> -making bullet points green
> -not adding indentation to bullets so that they will align with the content block they exist in.
Luckily, @anselmbradford already took care of point 1, but this PR adjusts the indentation to bring them in with what design wants.
- To be merged in the next sprint.
=> Changing Bullet Points on Office Pages

CHANGELOG.md, src/static/css/footer.less
From @ajbush:
>Ideally all content in the first column where "FOIA, "Plain Writing", "Privacy, Policy, & Legal Notices" live will align left instead of having a slight indent.
- Fixes footer to be flush with sides.
- Look at it!
- Closes DF-2284
=> Fixing margins on footer

CHANGELOG.md, src/_includes/macros/sub_pages.html, src/offices/_single.html, test/browser_tests/page_objects/page_office.js, test/browser_tests/spec_suites/shared/shared_office-cfpb-ombudsman.js, test/browser_tests/spec_suites/shared/shared_office-foia-requests.js, test/browser_tests/spec_suites/shared/shared_office-open-government.js, test/browser_tests/spec_suites/shared/shared_office-payments-to-harmed-consumers.js, test/browser_tests/spec_suites/shared/shared_office-plain-writing.js, test/browser_tests/spec_suites/shared/shared_office-privacy.js, test/browser_tests/spec_suites/shared/shared_office-project-catalyst.js
Adds offices tests
- Adds page object and shared spec suite for /offices/ pages content.
- Follow `TEST.md` instructions for browser tests.
- @imuchnik 
- @sebworks 
- ~~So when I run these I get `FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory` and the Selenium browser instances remain open. A few notes:~~
- ~~The selectors are very long because I leaned toward not cluttering the markup with classes that are just used for test suite hooks. It didn't seem problematic to have them long since they can be recreated with inspect element > Copy CSS Path. But could this be the issue?~~ Fixed with `qa-` selectors.
- There are three different page options in the get method of the page object because not all office pages have all the …
=> Adds offices tests

test/browser_tests/page_objects/page_office.js, test/browser_tests/spec_suites/shared/shared_office-project-catalyst.js
Accidentally introduced some linting warnings in https://github.com/cfpb/cfgov-refresh/pull/786
- Fixed key-spacing and max-len warnings in office tests.
- `gulp lint`
- @sebworks
=> Lint fixes

CHANGELOG.md, src/_includes/templates/footer.html, test/browser_tests/page_objects/page_office.js, test/browser_tests/spec_suites/shared/shared_office-accessibility.js
Adds accessibility page.
- Adds link to accessibility page in footer.
- Adds acceptance tests for accessibility page in form of offices pattern.
- Reindex sheer, visit homepage, navigate to footer. Find `Accessibility` link and open to reach page. 
- Run tests with `gulp test`
- @sebworks 
- Add tests for subpages.
=> DF-2255 - adds accessibility page

CHANGELOG.md, src/_includes/templates/forms/amending-and-correcting-records-under-the-privacy-act-form.html, src/_includes/templates/forms/file-a-privacy-complaint-form.html
Right now a user that goes to `/sub-pages/file-a-privacy-complaint/` will face a form about amending a privacy record and a user that goes to `/sub-pages/amending-and-correcting-records-under-the-privacy-act-2/` will see a form to file a privacy complaint. This switches the two forms to fix the issue.
=> Switching Privacy forms

CHANGELOG.md, src/_includes/macros/activities-block.html, src/offices/_single.html, src/sub-pages/_single.html, test/browser_tests/page_objects/page_office.js, test/browser_tests/page_objects/page_sub-pages.js, test/browser_tests/spec_suites/shared/shared_office-accessibility.js, test/browser_tests/spec_suites/shared/shared_office-cfpb-ombudsman.js, test/browser_tests/spec_suites/shared/shared_office-foia-requests.js, test/browser_tests/spec_suites/shared/shared_office-open-government.js, test/browser_tests/spec_suites/shared/shared_office-payments-to-harmed-consumers.js, test/browser_tests/spec_suites/shared/shared_office-plain-writing.js, test/browser_tests/spec_suites/shared/shared_office-privacy.js, test/browser_tests/spec_suites/shared/shared_office-project-catalyst.js, test/browser_tests/spec_suites/shared/shared_subpage-accessibility-file-a-formal-accessibility-complaint-or-website-feedback.js, test/browser_tests/spec_suites/shared/shared_subpage-accessibility-social-media-accessibility.js, test/browser_tests/spec_suites/shared/shared_subpage-accessibility-submit-an-accommodation-request.js
Adds sub-page tests for accessibility pages.
- Adds acceptance tests for accessibility subpages.
- Creates `activities-block` template for activities feed on offices and subpages.
- Run `gulp test`
- @sebworks 
=> Adds accessibility sub-page tests

CHANGELOG.md, src/static/css/pages/bureau.less
Removes small bureau isocon sizes. 
- Removed 80px to 120px sizing for the isocon sizes on the-bureau page.
- visit `/the-bureau/`
- @sebworks 
- @duelj 
Before:
After:
=> Fixes DF-2212 - fixes the bureau isocon sizes

.gitignore
Cleans up gitignore
- Moves environment vars to its own section and out of the Sheer section.
- Removes `_site`, which is a Jekyll artifact.
- Removes superfluous "stuff".
- Removes `.grunt/` artifact.
- Minor grammar fixes.
- @sebworks
=> Cleans up gitignore

test/unit_tests/.eslintrc, test/unit_tests/modules/util/date-range-formatter-spec.js, test/unit_tests/modules/util/type-checkers-spec.js
This bumps our coverage of our utilities to about 67%.
- Adding `type-checkers-spec.js`
- Adding `date-range-formatter-spec.js`
- Creating util unit test folder to match structure of JS
- Run the unit tests!
- The Chai assertion `.to.be.true` kept returning eslint errors, so I've turned off the dot-notation rule for the unit testing folder
=> More Unit Tests

.eslintrc, CHANGELOG.md, gulp/tasks/test.js, package.json, src/static/js/modules/classes/ContentSlider.js, src/static/js/modules/clear-form-buttons.js, src/static/js/modules/desktop-primary-nav.js, src/static/js/modules/jquery/cf_notifier.js, src/static/js/modules/jquery/custom-select.js, src/static/js/modules/mobile-primary-nav.js, src/static/js/modules/util/date-range-formatter.js, src/static/js/modules/util/js-loader.js, src/static/js/modules/util/web-storage-proxy.js, src/static/js/routes/common.js, test/browser_tests/jenkins_conf.js, test/browser_tests/page_objects/page_office.js, test/browser_tests/page_objects/page_sub-pages.js, test/browser_tests/shared_objects/footer.js, test/browser_tests/spec_suites/shared/shared_subpage-civil-rights-reasonable-accomodation-request-policy.js
Updates ESLint to v1.0.0. and fixes errors/warnings.
- Adds `restParams: true` to ESLint config, to allow use of ...rest syntax.
- Adds `experimentalObjectRestSpread: false` to ESLint config.
- Adds `qunit: false` to environments.
- Adds `serviceworker: true` to environments to support use of serviceworker API.
- Adds `embertest: false` to environments.
- Adds new rules: `no-implicit-coercion`, `no-invalid-this`, `no-param-reassign`, `no-useless-call`, `callback-return`, `id-length`, `id-match`, `arrow-parens`, `arrow-spacing`, `no-class-assign`, `no-const-assign`, `prefer-spread`, `prefer-reflect`, `require-yield`.
- Removed deprecated `no-reserved-keys` rule.
- Changes `phantomjs` environment to `false` since this should be overridden if needed in a test directory eslintrc file.
- Fixed …
=> Eslint one point oh

CHANGELOG.md, src/_includes/article.html, src/_includes/leadership-calendar-table.html, src/_includes/macros/activity-snippets.html, src/_includes/macros/contact-layout.html, src/_includes/macros/time.html, src/_includes/macros/util/format/contact.html, src/_includes/macros/util/format/datetime.html, src/_includes/macros/util/format/url.html, src/_includes/popular-stories.html, src/_includes/posts-paginated.html, src/_includes/related-posts.html, src/activity-log/index.html, src/careers/_macro-table-current-openings.html, src/careers/current-openings/_single.html, src/careers/index.html, src/contact-us/_template-general-inquiries.html, src/contact-us/_template-mailing-addresses.html, src/contact-us/_template-promoted-contacts.html, src/contact-us/_template-submit-a-complaint.html, src/events/_event-landing-macros.html, src/events/_event-post-macros.html, src/events/_event.html, src/static/css/pages/event.less, test/browser_tests/page_objects/page_events.js
Creates time macro and converts datetime instances to use time macro. Also, breaks apart format macro into topical macros.
- Adds time macro.
- Converted time elements to use time template.
- Broke apart format macros into topical macros.
- `/activity-log/`, `/events/`, `/events/summer-consumer-advisory-board-meeting-in-omaha-ne/`, `/blog/`, `/blog/forum-on-know-before-you-owe-eclosing-pilot/`, `/the-bureau/leadership-calendar/`, `/offices/payments-to-harmed-consumers/`, `/careers/`, `/careers/current-openings/`, `/careers/current-openings/1873/`
- @sebworks 
- @schaferjh 
On beta:
This PR:
---
On beta:
This PR:
---
On beta:
This PR:
---
On beta:
This PR:
---
On beta:
This PR:
---
On beta:
This PR:
---
On beta:
This PR:
---
On beta:
This PR:
---
On beta:
This PR:
---
On …
=> DF-2204 - Creates time macro, breaks apart format macros

CHANGELOG.md, src/_includes/macros/activities-block.html, src/_includes/templates/office-contact.html, src/budget/index.html, src/newsroom/index.html, src/offices/_single.html, src/privacy-policy/index.html, src/sub-pages/_single.html, src/the-bureau/leadership-calendar/index.html
Issue #183 is one of the oldest Github issues we have in our project. This closes it once and for all.
- Fixes borders on sub-footers across the website
- Visit the Newsroom
- Visit the Budget
- Visit the leadership calendar
- Visit a couple different office and sub-pages
Make sure the borders look good.
- @sebworks 
Include any screenshots that will make reviewing/testing easier
_Newsroom_
_Office of Civil Rights_
_Leadership Calendar_
- Closes #183
=> Fixed borders on sub-footers across the website

CHANGELOG.md, src/static/css/footer.less
Fixes DF-2208. Design wants the "Return to top" button to span the full width of the screen. 
- Fixed 'Return to top' button width on footer
=> Fixed 'Return to top' button width on footer

CHANGELOG.md, src/static/css/cf-enhancements.less, src/the-bureau/bureau-structure/index.html
Updates disabled link to support button links.
- Adds `&.btn` class to `u-link__disabled` class.
- Properly disables download PDF button on the bureau-structure page.
- Visit `/the-bureau/bureau-structure/`, download PDF button should be disabled.
- @sebworks 
Before:
After:
=> Updates disabled link to support button links

CHANGELOG.md, src/static/js/config/breakpoints-config.js, src/static/js/modules/classes/MobileCarousel.js, src/static/js/modules/classes/MobileOnlyExpandable.js, src/static/js/routes/careers/application-process/index.js, src/static/js/routes/offices/index.js, src/static/js/routes/the-bureau/index.js
The PR is part of a move towards using config files, which may or may not be mirrored in Jinja/Less. 
- Added  `config/breakpoints-config.js` to add config file to mirror `cf-vars.less.`
- Updated `src/static/js/modules/classes/MobileOnlyExpandable.js` to use breakpoints config.
- Updated `src/static/js/routes/careers/application-process/index.js` to use breakpoints config.
- Updated `src/static/js/routes/the-bureau/index.js` to use breakpoints config.
- Updated `src/static/js/routes/offices/index.js` to use breakpoints config.
- Visit 'http://localhost:7000/the-bureau/` using a mobile emulator and observe the expandable/carousel.
@KimberlyMunoz
=> Adding Breakpoints Config File

CHANGELOG.md, gulp/tasks/default.js, gulp/tasks/lint.js
Fixed default gulp task and renamed script liniting to match the processing task
- None
- None
- updated default task for correct lint and test tasks
- updated name of lint:js to lint:scripts to match the script processing task
- run `gulp` and there should be no messages about tasks not being in your gulpfile
- @sebworks 
None
- Gulp is JS too, so naming the lint task `scripts` ties it to the type of JS files we're linting in this task
=> Bugfix for default gulp task

src/_includes/article.html, src/_includes/macros/contact-layout.html, src/_includes/posts-paginated.html
Fixes #669 - unnecessary var; wrong boolean case.
- Removes unnecessary jinja `First` var.
- Downcases boolean values, per jinja docs.
- `/contact-us/` should look the same.
- @sebworks 
- @jimmynotjim
=> Fixes #669 - unnecessary var; wrong boolean case

src/_includes/macros/active-filters.html
Fixes #836 - removes redundant ul block.
- Removes redundant ul block in `active_filters` macro.
- Places that use the `_active_filters_list` macro, ~~like `/blog/` should function the same.~~ Oops, only used on `/the-bureau/leadership-calendar/print/`
- @sebworks 
- @jimmynotjim
=> Fixes #836 - removes redundant ul block

CHANGELOG.md, gulp/tasks/clean.js
When running sheer from the `/dist` directory it crashes when you delete the directory during cleaning. This update fixes that so that only the files and folders within `/dist` and not the directory itself are removed.
=> Updated clean task to keep the dist dir

src/_includes/macros/util/format/contact.html
Fixes #520 - removes extraneous parens.
- Additional code comment on fields needed for object passed to format_address macro.
- Removes extraneous parens in format_address macro.
- `/contact-us/` addresses should look the same.
- @sebworks 
- @jimmynotjim
=> Fixes #520 - extraneous parens

README.md
Fixes #318 - adds available gulp tasks to readme.
- Adds available gulp tasks section to readme.
- @sebworks 
=> Fixes #318 - adds available gulp tasks to readme

CHANGELOG.md, gulp/tasks/browserSync.js
Pull browserSync port from environment variable if available.
- Use `HTTP_PORT` environment variable for port in `gulp watch`, if available.
- `gulp watch` should use the port number set in the `HTTP_PORT` value in `.env`, if it's set. `--port` command-line flag should still work and override the environment variable.
- @sebworks
=> Add browsersync port

CHANGELOG.md, src/doing-business-with-us/small-businesses/index.html, src/static/css/cf-enhancements.less, src/static/css/pages/business.less
Closes DF-2222 and brings multiple pages under the guidelines set in the design manual.
- Fixes icon links to correct guidelines in design manual
- Fixes `list__download` to show icons after links.
- Reindex sheer
- Test the following pages: 
- Performance Plan & Report
- Financial Reports & Updates
- Funding Requests
- Procurement History
- Small Businesses & Minorities
=> Fixed icon links for budget section and business section

test/browser_tests/conf.js
Refactors Protractor conf script to remove `newCapabilities` var.
- Refactors Protractor conf script to remove `newCapabilities` var.
- Casts capability.version to string so length can be accurately counted. 
- Testing should function the same. See https://github.com/cfpb/cfgov-refresh/pull/859#issuecomment-130801770
- @sebworks
=> Test refactor to remove newCapabilities var

CHANGELOG.md, src/_includes/macros/active-filters.html
Simple fixes to close the following issues:  ( https://github.com/cfpb/cfgov-refresh/issues/837, https://github.com/cfpb/cfgov-refresh/issues/835 )
- Updated `src/_includes/macros/active-filters.html`  to fix issues with active filters logic.
-  Visit 'http://localhost:7000/the-bureau/leadership-calendar/print/?filter_calendar=Richard+Cordray&filter_range_date_gte=2014-01&filter_range_date_lte=2014-02'. Should function as normal.
@jimmynotjim
@KimberlyMunoz
=> Fix for simple active filters issues

CHANGELOG.md, src/static/js/modules/util/assign.js, src/static/js/modules/util/date-range-formatter.js, test/unit_tests/modules/util/assign-spec.js
Copy Fixes/Unit Test for assign.js
- Updated `src/static/js/modules/util/assign.js` to add more code source information. Changed name to better match purpose.
- Added `test/unit_tests/modules/util/assign-spec.js` to add unit test for `assign.js`
- Updated `src/static/js/modules/util/date-range-formatter.js` to use `assign.js`
-  Run `gulp test:unit:js`. Unit test should complete successfully.
@jimmynotjim
@KimberlyMunoz
=> Fixes/Unit Test for assign.js

CHANGELOG.md, INSTALL.md, TEST.md, src/_includes/macros/activity-snippets.html, src/_includes/macros/filters.html, src/_includes/macros/util/format/datetime.html, src/_includes/templates/forms/accessibility-feedback-form.html, src/_includes/templates/forms/amending-and-correcting-records-under-the-privacy-act-form.html, src/_includes/templates/forms/file-a-privacy-complaint-form.html, src/_includes/templates/forms/form-eeo-issue.html, src/_includes/templates/forms/plain-writing-feedback-form.html, src/_includes/templates/forms/submit-a-request-form.html, src/about-us/index.html, src/events/_event-post-macros.html, src/offices/_single.html, src/static-legacy/js/functions.js, test/macro_tests/test_macros.py
Addresses comments from Sprint 34 and beta PRs. 
- Fixes typos.
- Removes incorrect copy from readme.
- Moves generation of HTML for director checkboxes in calendar filters to list instead of hardcoded values. 
- Updates timezone default to be consistent between datetime macros.
- Properly disables non-functional links.
- General code style formatting.
- Should be no change, but double-check `/the-bureau/leadership-calendar/` filter and `/budget/strategic-plan/interactive/`
- @sebworks 
=> Sprint PR cleanup

CHANGELOG.md, src/static/js/config/breakpoints-config.js, src/static/js/modules/classes/BreakpointHandler.js, src/static/js/modules/secondary-nav-toggle.js, src/static/js/modules/util/breakpoint-state.js, test/unit_tests/modules/util/breakpoint-state-spec.js
DF-1858 - Responsive Js
- Updated `src/static/js/config/breakpoints-config.js` to add min to mobile config.
- Updated `src/static/js/modules/classes/BreakpointHandler.js` to use `breakpoints-config` and pass back state param on `enter/leave` events.
- Updated `src/static/js/modules/secondary-nav-toggle.js` to use `get-breakpoint-state.js`.
- Added `src/static/js/modules/util/get-breakpoint-state.js` to create module for determining responsive state. 
-  Visit `http://localhost:7000/the-bureau/` and resize window. Observe secondary nav.
~~~- Will create a separate PR for unit tests.~~~~
Update: Unit test added in https://github.com/cfpb/cfgov-refresh/commit/6c9bd90cc9e4323b06358c5dd570f138d7474f6c
@jimmynotjim
=> DF-1858 - Responsive Js

README.md
Adds TravisCI, Coveralls, and Code Climate code quality badges to repo for flapjack branch.
- Adds TravisCI, Coveralls, and Code Climate code quality badges to repo for flapjack branch in README.md.
- Check URLs for badges.
- @sebworks 
- @jimmynotjim
=> Adds code quality badges to repo for flapjack branch

CHANGELOG.md, package.json, test/browser_tests/conf.js, test/browser_tests/page_objects/page_the-bureau.js, test/browser_tests/spec_suites/about-us.js, test/browser_tests/spec_suites/careers-students-and-graduates.js, test/browser_tests/spec_suites/contact-us.js, test/browser_tests/spec_suites/events.js, test/browser_tests/spec_suites/footer.js, test/browser_tests/spec_suites/office-accessibility.js, test/browser_tests/spec_suites/office-cfpb-ombudsman.js, test/browser_tests/spec_suites/office-foia-requests.js, test/browser_tests/spec_suites/office-of-civil-rights.js, test/browser_tests/spec_suites/office-open-government.js, test/browser_tests/spec_suites/office-payments-to-harmed-consumers.js, test/browser_tests/spec_suites/office-plain-writing.js, test/browser_tests/spec_suites/office-privacy.js, test/browser_tests/spec_suites/office-project-catalyst.js, test/browser_tests/spec_suites/subpage-accessibility-file-a-formal-accessibility-complaint-or-website-feedback.js, test/browser_tests/spec_suites/subpage-accessibility-social-media-accessibility.js, test/browser_tests/spec_suites/subpage-accessibility-submit-an-accommodation-request.js, test/browser_tests/spec_suites/subpage-civil-rights-diversity-policy.js, test/browser_tests/spec_suites/subpage-civil-rights-equal-opportunity-policy.js, test/browser_tests/spec_suites/subpage-civil-rights-no-fear-act.js, test/browser_tests/spec_suites/subpage-civil-rights-raise-an-eeo-issue.js, test/browser_tests/spec_suites/subpage-civil-rights-reasonable-accomodation-request-policy.js, test/browser_tests/spec_suites/subpage-civil-rights-whistleblowers.js, test/browser_tests/spec_suites/the-bureau.js
Updated protractor tests to pass in Sauce Connect
- Added framework setting to config
- Added timeout setting to config
- Removed failing bureau test that couldn't be easily traced (we can add back in later)
- Updated page loads to only happen once
- checkout branch and run `gulp test:acceptance --sauce=true` while connected to Sauce Connect
- @sebworks 
- @imuchnik 
__Look at those runtimes now!!!__
- It's insanely hard to debug Protractor issues in Sauce Connect
=> Fixes for Protractor Tests

gulp/tasks/copy.js
Consolidates similar code noted in https://codeclimate.com/github/cfpb/cfgov-refresh/gulp/tasks/copy.js
- In gulp copy task, consolidates similar code into a shared private function.
- `gulp build` and `gulp watch` should work fine.
- @sebworks 
=> Consolidates similar copy code

CHANGELOG.md, test/browser_tests/spec_suites/events.js
Fixes #840 - removes truthy from tests.
- Changes `toBeTruthy()` to `toBe( true )` in events tests.
- Disables tests for landing page events, since we don't currently have events.
- `gulp build && gulp test:acceptance --sauce=false`, should pass and have two pending tests.
- @sebworks 
- @jimmynotjim
=> Fixes #840 - removes truthy from tests

src/static/css/pages/offices.less
Fixes #928 - Removes unnecessary CSS.
Let me know if this merits a changelog update. 
Test by visiting Project Catalyst or Office of Civil Rights.
=> Fixes #928 - Removes unnecessary CSS

CHANGELOG.md, gulp/tasks/test.js
Fixes #931 - Standardizes calling js tests scripts
Test by running gulp:unit and checking for a green travis checkmark.
=> Fixes #931 - Standardizes calling js tests scripts

CHANGELOG.md, TEST.md, test/browser_tests/conf.js
Fixes #948 - makes specs flag accept array.
- Added ability for acceptance --specs test flag to accept list of test files.
- Add a comma-separated list to the `--specs` flag value. For example, to run two tests: `gulp build && gulp test:acceptance --sauce=false --specs=about-us.js,contact-us.js`
- @sebworks 
=> Fixes #948 - makes specs flag accept array

CHANGELOG.md, src/static/css/skip-nav.less
Ans pointed out that the skip nav link isn't working on Flapjack. Z-index got added to the beta-banner in the mega-menu refactor and is covering up the skip link. The fix is to give it a slightly higher z-index.
- Fixes skip-nav link
- Hit tab to see the skip-nav button
- @sebworks
=> Fixes skip-nav

CHANGELOG.md, src/activity-log/index.html, test/browser_tests/page_objects/page_activity-log.js, test/browser_tests/shared_objects/footer.js, test/browser_tests/shared_objects/header.js, test/browser_tests/spec_suites/activity-log.js, test/browser_tests/spec_suites/header.js
Adding Acceptance tests for the `activity-log` page.
- Updated `src/activity-log/index.html` to add qa hooks.
- Added `test/browser_tests/page_objects/page_activity-log.js` to support Acceptance testing.
- Added `test/browser_tests/spec_suites/activity-log.js` to support Acceptance testing.
-  Updated `test/browser_tests/shared_objects/footer.js` to support pages other than `/`.
-  Updated `test/browser_tests/shared_objects/header.js` to support pages other than `/`.
- Updated `test/browser_tests/spec_suites/header.js` to fix linting issues.
- This PR does add the `data-qa-hook` attribute as discussed in issue https://github.com/cfpb/cfgov-refresh/issues/930
@jimmynotjim 
@KimberlyMunoz
=> Adding Acceptance tests for the Activity Log page.

CHANGELOG.md, src/_includes/templates/nav/primary-nav.html, src/static/css/nav-primary.less, src/static/js/modules/nav-primary.js, src/static/js/modules/util/expanded-state.js, test/unit_tests/modules/nav-primary-spec.js, test/unit_tests/modules/util/expanded-state-spec.js
Updated the primary nav to move focus as appropriate
- Added focus triggers when opening nav levels, the focus moves to the first link in that level
- Added focus trigger when closing nav levels, the focus moves to the trigger that opened it
- Fixed callback timeout in expanded-state
- Fixed test for callback timeout in expanded-state-spec
- None
- Added focus triggers while navigating by tab
- Added tests to support new focus triggers
- Use the nav by keyboard, focus should move into and out of each level depending on which trigger you use
- Run `gulp test:unit:scripts`
- @sebworks 
=> Updated the primary nav to move focus as appropriate

src/static/js/routes/careers/working-at-cfpb/index.js
Remove default override for MobileCarousel noted by @sebworks in https://github.com/cfpb/cfgov-refresh/pull/968
- Unneeded default being passed to MobileCarousel constructor since it is being set in https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/classes/MobileCarousel.js#L20
- `/careers/working-at-cfpb/` JS should work at mobile.
- @sebworks 
- @jimmynotjim
=> Removes unneeded default override

CHANGELOG.md, gulp/tasks/test.js, gulp/utils/fsHelper.js
Moves getBinary method to gulp file system helper.
- Moves getBinary method to gulp file system helper.
- `gulp test` should work as expected.
- @sebworks
=> Moves getBinary method to filesystem helper

src/_layouts/404.html, src/_layouts/500.html
Runs JS paths through Jinja to ignore raw tags.
- Runs JS paths through Jinja to ignore raw tags.
- Error page should not throw a Jinja error.
- @sebworks 
=> Fix for error page paths

CHANGELOG.md, src/the-bureau/about-deputy-director/index.html, src/the-bureau/about-director/index.html, src/the-bureau/bureau-structure/index.html, src/the-bureau/history/index.html, src/the-bureau/index.html, src/the-bureau/leadership-calendar/index.html, test/browser_tests/page_objects/page_about-director.js, test/browser_tests/page_objects/page_bureau-history.js, test/browser_tests/page_objects/page_bureau-structure.js, test/browser_tests/page_objects/page_leadership-calendar.js, test/browser_tests/page_objects/page_the-bureau.js, test/browser_tests/spec_suites/about-deputy-director.js, test/browser_tests/spec_suites/about-director.js, test/browser_tests/spec_suites/bureau-history.js, test/browser_tests/spec_suites/bureau-structure.js, test/browser_tests/spec_suites/leadership-calendar.js, test/browser_tests/spec_suites/the-bureau.js, test/browser_tests/util/QAelement.js
Adding Acceptance tests for `the-bureau` pages
- Added acceptance tests for the `the-bureau` pages. 
- This PR does add the `data-qa-hook` attribute as discussed in issue https://github.com/cfpb/cfgov-refresh/issues/930
@jimmynotjim 
@KimberlyMunoz
=> Adding Acceptance tests for the-bureau pages

CHANGELOG.md, src/static/js/config/aria-states-config.js, src/static/js/modules/polyfill/object-defineproperty-polyfill.js, src/static/js/modules/util/aria-state.js, test/unit_tests/modules/util/aria-state-spec.js
Adding ARIA states and config code.
- Added `src/static/js/config/aria-states-config.j` to create ARIA states config file with valid elements lookup. 
- Added `src/static/js/modules/util/aria-state.js` to create ARIA states and update dom elements based on object properties. 
-  Still working on a Unit test for this PR.
Update: Added Unit Test in https://github.com/cfpb/cfgov-refresh/commit/0781acc7c56c707491c140fe78abc114ee6f06c8
- The basic use cases are as follows : 
```
var state = ariaState.create( 'expanded', element ); 
// 'aria-expanded' attribute is now created on the element and set to false.
// state has an `isExpanded` property which is also set to false;
state.isExpanded = true; 
//  'aria-expanded' attribute is now set to true on the element.
var obj = {'isSmall' : true}; …
```
=> Adding ARIA states and config code

cfgov/cfgov/wsgi.py
Right now WSGI points to the module init file that contains nothing so no settings are set. This replicates manage.py to give wsgi.py the same settings file to use.
@kave
=> Fix wsgi to use env settings

package.json
handlebars-loader needs handlebars to be added to the dependencies list as it won't handle the dependency itself.
- Adds handlebars 4.0.2 to package.json.
- `gulp build && gulp test` should run.
- @sebworks 
=> Adds handlebars dependency explicitly

.env_SAMPLE, CHANGELOG.md, TEST.md, gulp/tasks/test.js, gulp/utils/fsHelper.js, package.json
Adds accessibility testing.
- Adds `gulp test:a11y` accessibility testing using node-wcag.
- Adds binaryDirectory parameter to fsHelper.getBinary helper function.
- See bottom of `TEST.md`
- @sebworks 
- **NOTE: The change noted in https://github.com/cfpb/node-wcag/issues/35 needs to be fixed before merging this PR or this will only work with the homepage.**
=> Adds accessibility testing

.travis.yml, CHANGELOG.md, package.json
I can't build jsdom without updating to the latest (or at least 4+). I'm running the latest node `v4.1.0`.
- Updated jsdom from `3.1.2` to `6.5.1`.
- Updated mocha-jsdom from `0.3.0` to `1.0.0`.
- Updated istanbul from `0.3.13` to `0.3.20`.
- Updated TravisCI node version to `4.1.0`.
- Install Xcode 7 via Self Service.
- `brew update && brew doctor`
- `brew upgrade node`
- `./setup.sh local`
- `gulp test` should pass.
- @sebworks 
=> Updates jsdom, mocha-jsdom, istanbul, and node to latest

.eslintrc, CHANGELOG.md, gulp/tasks/lint.js, src/static/js/modules/util/assign.js, test/browser_tests/.eslintrc, test/browser_tests/conf.js, test/browser_tests/jenkins_conf.js, test/browser_tests/spec_suites/footer.js, test/browser_tests/spec_suites/header.js, test/browser_tests/spec_suites/subpage-accessibility-file-a-formal-accessibility-complaint-or-website-feedback.js, test/browser_tests/spec_suites/subpage-accessibility-social-media-accessibility.js, test/browser_tests/spec_suites/subpage-accessibility-submit-an-accommodation-request.js, test/browser_tests/spec_suites/subpage-civil-rights-diversity-policy.js, test/browser_tests/spec_suites/subpage-civil-rights-equal-opportunity-policy.js, test/browser_tests/spec_suites/subpage-civil-rights-no-fear-act.js, test/browser_tests/spec_suites/subpage-civil-rights-raise-an-eeo-issue.js, test/browser_tests/spec_suites/subpage-civil-rights-reasonable-accomodation-request-policy.js, test/browser_tests/spec_suites/subpage-civil-rights-whistleblowers.js, test/unit_tests/.eslintrc, test/unit_tests/modules/cf_notifier-spec.js, test/unit_tests/modules/focus-target-spec.js, test/unit_tests/modules/footer-button-spec.js, test/unit_tests/modules/nav-primary-spec.js, test/unit_tests/modules/util/aria-state-spec.js, test/unit_tests/modules/util/breakpoint-state-spec.js, test/unit_tests/modules/util/expanded-state-spec.js
Update ESLint config for  version 1.5.1 compatibility.
Fixes ESLint errors that were breaking on Travis.
- Added additional environments and rules for version 1.5.1 ESLint compatibility.
- Fixes linting errors:
- Formats tests to fix indenting errors.
- Moves requires to top of files in tests.
- Moves gulp linting implementation to a helper function.
- `gulp build && gulp lint` should have no errors
- @sebworks 
- ~~I have a PR open with gulp-eslint for updating that to [1.5.1](https://github.com/adametry/gulp-eslint/pull/96), but this doesn't appear to add any breaking changes so should be able to go in before that is merged.~~ Not necessary, the caret versioning actually already brings in `1.5.1` without an updated needed in gulp-eslint.
=> Update ESLint config for version 1.5.1 compatibility

CHANGELOG.md, package.json
Updates to latest chai.
- Updated chai from `2.3.0` to `3.3.0`.
- Updated sinon-chai from `2.7.0` to `2.8.0`.
- `./setup.sh local && gulp test` should pass.
- @sebworks 
- @jimmynotjim
=> Updates chai and sinon-chai

CHANGELOG.md, src/_includes/templates/nav/_vars-primary-nav.html
The Ombudsman's office has requested that they only appear in the site footer and would like to be removed from the mega menu.
=> Removed Ombudsman from nav for beta freeze

CHANGELOG.md, setup.sh
When the function `install()` is actually called, it has to be passed arguments that it uses.
@kave
=> Fix setup.sh to actually use the passed argument now

CHANGELOG.md, cfgov/v1/jinja2/v1/careers/_template-careers-related-links.html, cfgov/v1/jinja2/v1/careers/index.html, cfgov/v1/jinja2/v1/the-bureau/index.html, cfgov/v1/preprocessed/css/cf-enhancements.less
Adds block__flush, organizes block CSS.
Fixes https://github.com/cfpb/cfgov-refresh/issues/838
- Added `block__flush` to cf-enhancements to remove margin from all sides.
- Change hardcoded 50% grey to color variable.
- Consolidates `block` CSS in cf-enhancements.
- `./setup.sh local`
- Navigation to `/the-bureau/` there should be no change from refresh.demo.
- @sebworks
=> Adds block__flush, organizes block CSS

CHANGELOG.md, cfgov/v1/jinja2/v1/_includes/macros/filters.html, cfgov/v1/jinja2/v1/blog/_single.html, cfgov/v1/jinja2/v1/blog/index.html, test/browser_tests/.eslintrc, test/browser_tests/page_objects/page_blog-single.js, test/browser_tests/page_objects/page_blog.js, test/browser_tests/shared_objects/careers-social-section.js, test/browser_tests/shared_objects/filter.js, test/browser_tests/shared_objects/pagination.js, test/browser_tests/shared_objects/rss-section.js, test/browser_tests/shared_objects/stay-informed-section.js, test/browser_tests/spec_suites/blog-single.js, test/browser_tests/spec_suites/blog.js
Acceptance tests for the `blog` pages
- Added acceptance tests for the `blog` pages. 
- This PR does introduce the concept of mixins. This would allow us to have reusable page components.
@jimmynotjim 
@KimberlyMunoz
=> Adding Acceptance tests for the blog pages

CHANGELOG.md, cfgov/v1/jinja2/v1/newsroom/index.html, cfgov/v1/jinja2/v1/newsroom/press-resources/index.html, test/browser_tests/page_objects/page_careers-application-process.js, test/browser_tests/page_objects/page_newsroom-press-resources.js, test/browser_tests/page_objects/page_newsroom.js, test/browser_tests/spec_suites/newsroom-press-resources.js, test/browser_tests/spec_suites/newsroom.js
Acceptance tests for the `Newsroom` pages
- Added acceptance tests for the `Newsroom` pages. 
- This PR does introduce the concept of mixins. This would allow us to have reusable page components.
@jimmynotjim 
@KimberlyMunoz
=> Adding Acceptance tests for Newsroom pages

CHANGELOG.md, cfgov/v1/jinja2/v1/budget/index.html, test/browser_tests/page_objects/page_budget-financial-report.js, test/browser_tests/page_objects/page_budget-funding-request.js, test/browser_tests/page_objects/page_budget-performance-plan-report.js, test/browser_tests/page_objects/page_budget-strategic-plan.js, test/browser_tests/page_objects/page_budget.js, test/browser_tests/spec_suites/budget-financial-report.js, test/browser_tests/spec_suites/budget-funding-request.js, test/browser_tests/spec_suites/budget-performance-plan-report.js, test/browser_tests/spec_suites/budget-strategic-plan.js, test/browser_tests/spec_suites/budget.js, test/browser_tests/util/url-matcher.js
Adding Acceptance tests for the `Budget` pages
- Added acceptance tests for the `Budget` pages. 
@jimmynotjim 
@KimberlyMunoz
=> Adding Acceptance tests for Budget pages

cfgov/v1/jinja2/v1/doing-business-with-us/_vars-doing-business-with-us.html
Scott brought up that the breadcrumb didn't match the navigation. I think the thinking was that all words under four letters were lowercase, but I know there can be multiple interpretations on how "Doing Business with Us" should be capitalized. 
This pull request standardizes it with the navigation menu and page title. Tagging in Team Content to approve this.
- Tanya
=> Doing Business with Us title fix

CHANGELOG.md, cfgov/v1/jinja2/v1/_layouts/base.html
Hey all. I confirmed with @bethannenc that it's time to remove the extra Google Analytics code and we'll be relying on GTM from now on. I also asked about moving GTM to the footer of the page for performance reasons. After this PR is merged, Beth can test it on Flapjack to make sure GTM is working as it should.
- Removes duplicate Google Analytics code
- Moves Google Tag Manager code and jQuery to the bottom of the page
- This PR brings our Critical Path Rendering score from 77 to 95 out of 100, moves our DOM loaded time from 1324ms to 1100ms on my connection and from 4085ms to 3587ms on sitespeed.io's mobile emulator
=> Google Analytics Changes

CHANGELOG.md, config/environment.js, config/webpack-config.js, gulp/config.js, gulp/tasks/lint.js
Adds JS config to linter.
- Added JS in `./config` directory to `gulp lint:build` task and merged that and gulp config together in `config.build`.
- Fixes linter errors/warnings from JS config files.
- `gulp lint:build` should return no errors. `gulp build && gulp test` should pass.
- @sebworks 
- @jimmynotjim
=> Adds JS config to linter

CHANGELOG.md, cfgov/cfgov/urls.py, cfgov/v1/jinja2/v1/_includes/molecules/hero.html, cfgov/v1/jinja2/v1/_includes/organisms/image-and-text-50-50.html, cfgov/v1/jinja2/v1/landing-page-1/index.html, cfgov/v1/jinja2/v1/landing-page-2/index.html
Part of DFJR-327.
Added atomic landing page template prototypes so that we can add test atomic design components together in one landing page and then migrate them to pages that use them.
- Added atomic landing page template prototypes.
- Added `/organisms/` and `/molecules/` directories to includes directory.
- `./setup.sh local`
- Restart the server.
- `/landing-page-1/` and `/landing-page-2/` should work.
- @sebworks 
- @kurtw 
- Add testing to our test suites as these get moved from the prototype to actual page implementations.
- Added an example molecule and organism to fill in the paths, but the implementation of these are covered in subtasks of DFJR-327.
=> Added atomic landing page template prototypes

.gitignore, CHANGELOG.md, TEST.md, gulp/tasks/test.js, package.json
Adds a plug-in that checks against sitespeed.io performance rules for rule violations that may be slowing down the website. [Full list of rules are here](https://www.sitespeed.io/rules/). I disabled some rules on caching that we couldn't do much about on the front-end, but feel free to comment if you think a rule should be off or on. 
~~ This plugin will fail when run because some clean up is needed. ~~ 
- Adds sitespeed.io plugin with performance rules for Flapjack
- run `gulp test:perf`
- @sebworks 
- @jimmynotjim
=> Gulp Plugin for Sitespeed rules

cfgov/v1/preprocessed/css/cf-theme-overrides.less, cfgov/v1/preprocessed/css/main.less, gulp/config.js
Updates/fixes CSS paths.
- Moves `licensed-fonts.css` base path to `cf-theme-overrides.less` from `gulp/config.js`.
- Removes unused `@{loc-dist}` variable
- Should be no change in fonts between this PR and flapjack branch.
- @sebworks 
=> Updates/fixes CSS paths

gulp/tasks/test.js
Whoops! `gulp test:acceptance` got deleted in https://github.com/cfpb/cfgov-refresh/pull/1032 leading to `gulp test` breaking. Re-added. Also fixed some linting errors.
- @sebworks
=> Hotfix gulp:test task

.eslintrc, CHANGELOG.md
Relaxes key-spacing rule slightly.
The key-spacing rule can get a bit funky when properties in an object have other objects as values, reading to less readability than before the rule is applied! It also can cause issues with exceeding the max line length when it otherwise wouldn't if alignment was not happening on the property values. This tweak makes property keys have at least 1 space after the colon, allowing the values to aligned when it makes sense, or not when it doesn't.
- Changes `align: value` attribute in ESLint `key-spacing` rule to individual mode with `mode: minimum` option set.
- `gulp lint` shouldn't complain about key-spacing violations.
- @sebworks 
- @jimmynotjim
=> Relaxes key-spacing rule slightly

CHANGELOG.md, cfgov/v1/jinja2/v1/_includes/templates/nav/primary-nav.html
Adds URL to primary-nav href.
FIxes #967
- Added href URL to primary nav top-level menu link.
- No change, unless JS is turned off and menu item is clicked, in which case it should go to the About Us Landing page.
- @sebworks
=> Adds URL to primary-nav href

.env_SAMPLE, CHANGELOG.md, INSTALL.md, cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py, cfgov/cfgov/settings/test.py, create-mysql-db.sh, requirements/base.txt, setup.sh
- Created MYSQL database creation script
- edited settings conf to account for new backend
- MYSQL database creation script
- Changed DB backend from sqlite ==> MYSQL  
Ensure your databse is running. `mysql.server start `
Then run mysql creation script from root directory `./create-mysql-db.sh` 
If you would like to have a custom db setup then you can pass in the necessary args. NOTE be sure to update your local settings local.py to account for these changes. 
`./create-mysql-db.sh <db_name> <db_username> <db_password> `
- @kurtw
=> Integrated a MYSQL backend and included a database creation script

test/unit_tests/modules/focus-target-spec.js
I had an issue in https://github.com/cfpb/cfgov-refresh/pull/1026 that it would timeout and stall every. single. time. Moving the sinon sandbox creation from `before` to `beforeEach` as shown in https://gist.github.com/jgable/fd7fbd0516c849731404 seems to fix it.
Fixes https://github.com/cfpb/cfgov-refresh/issues/1047
- Moves the sinon sandbox creation from `before` to `beforeEach` in `focus-target-spec.js`
- `gulp test` should not stall or give the error shown in https://github.com/cfpb/cfgov-refresh/issues/1047
- @sebworks 
=> Fixes #1047 - focusTarget unit test timeout

.env_SAMPLE, .travis.yml, CHANGELOG.md, TEST.md, gulp/tasks/test.js, setup.sh
- Added `gulp test:unit:server` for running Django unit tests via gulp.
- Uncomment `TOXENV` in `.env`.
- `./setup.sh local && gulp test --sauce=false` or `./setup.sh local && gulp test` should pass.
- @sebworks 
- @kurtw
=> Add tox unit tests to gulp flow

CHANGELOG.md, cfgov/core/views.py
@kave 
@rosskarchner 
Before pulling, visit /blog/ and enter in an email to subscribe. It shouldn't respond. Looking on the access log will show that it returns a 403. Pull it down and then retry. It should succeed. Keep in mind you need the GOVDELIVERY_ACCOUNT_CODE, GOVDELIVERY_USER, and GOVDELIVERY_PASS set in the env. If you need the credentials, they're in the wsgi file on the server.
=> Exempt govdeliver_subscribe view from csrf protection

CHANGELOG.md, gulp/config.js, gulp/tasks/scripts.js, gulp/tasks/watch.js
Fixed up the watch task when saving source scripts
- Removed old copy:files task
- Replaced watch option from webpack-stream (was conflicting with gulp watch) with default gulp watch task
- run `gulp watch` and update any of the source JS files, it should compile them
- @sebworks 
=> Fixed watch task for scripts

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/image-and-text-50-50.html, cfgov/jinja2/v1/_includes/molecules/text-introduction.html, cfgov/jinja2/v1/landing-page-2/index.html, cfgov/preprocessed/css/cf-enhancements.less, cfgov/preprocessed/css/main.less, cfgov/preprocessed/css/molecules/text-introduction.less
Adds well organism architecture per [GHE]/flapjack/Modules-V1/wiki/Text-Introduction
- Added templates and CSS for the Text Introduction molecule.
- Updates Text Introduction Molecule on `/landing-page-2/`.
- @sebworks 
- Pending resolution of approval of how this architecture will look.
=> Adds text-introduction prototype

cfgov/cfgov/settings/base.py
@kurtw @rosskarchner 
Cannot have the same location of the static_root included in the static_dirs. tested & verified on flapjack server
=> removed reference to prod static folder location

CHANGELOG.md, cfgov/preprocessed/js/modules/classes/BreakpointHandler.js, test/unit_tests/modules/classes/BreakpointHandler-spec.js
Adding Unit test for BreakpointHandler
- Updated `cfgov/v1/preprocessed/js/modules/classes/BreakpointHandler.js` to remove jQuery dependency and unneeded code.
- Added `test/unit_tests/modules/classes/BreakpointHandler-spec.js` to add unit test for BreakpointHandler.
- Run `gulp test:unit`.
@jimmynotjim
=> Adding Unit test for BreakpointHandler

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/half-width-link-blob.html, cfgov/jinja2/v1/landing-page-1/index.html, cfgov/preprocessed/css/main.less, cfgov/preprocessed/css/molecules/half-width-link-blob.less, cfgov/preprocessed/css/organisms/link-blob-group.less
Added the half-width-link blob
- Added half-width-link-blob macro to automate creating blobs when given a heading, text and list of links from the CMS.
- Added styles to set up layout for link-blob molecule and organism (named link-blob-group).
- None
- None
- visit `/landing-page-1/` and check out the blobs
- @ajbush 
- @duelj 
- @sebworks 
__Sorry, wrong blob :)__
- Individual link blob uses link list molecule (yes, molecules in molecules)
- Must be used with the link-blob-group organism, even if there's only one blob
- Will always be 50% at tablet and above, even if there's only one blob
- For now content is limited to heading, text, and links
=> Added half width link blob

cfgov/core/management/commands/processors/eventpage.py, cfgov/v1/migrations/0003_add_tags-authors_for_cfgovpage.py, cfgov/v1/models/__init__.py, cfgov/v1/models/base.py, cfgov/v1/models/events.py
This adds the tags and authors members to the CFGOVPage for use in the Promote panel of all page models that inherit from CFGOVPage. It also adds them in the Event's import-data script.
This is so we can set up the filterable list in the view logic for the Event template logic conversion for this sprints' hypotheses.
Run the `import-data` command for events to see if they convert the tags and authors correctly. Note, there's only one author of these events.
`./cfgov/manage.py import-data events eventpage events -u <super_user> -p <super_user_pw>`
@kave 
@rosskarchner
=> Adds Authors and Tags to CFGOV Model and to the import-data script for Events

CHANGELOG.md, package.json
Fix handlebars path to pull from `node_modules` instead of `vendor`.
- Pulls in handlebars via npm instead of bower.
- `./setup.sh local` should pass.
- @sebworks 
=> Fix handlebars path

.gitignore, CHANGELOG.md, gulp/tasks/beep.js, package.json, setup.sh
Got sick of not being alerted when the build is done. Adds the ability to optionally add an mp3 file in your project root which plays when `setup.sh` completes.
- Adds `gulp beep` task.
- Includes `gulp beep` at the end of the `setup.sh` build process.
- Download a MP3 sound from freesound.org or whereever. I like [this one](www.freesound.org/data/previews/72/72129_1028972-lq.mp3)
- Rename it `build-beep.mp3`
- Place it in your project root directory.
- Try `gulp beep` to test.
- Run `./setup.sh local` and it should play at the end.
- @sebworks 
- @kurtw 
- @kave
=> Add gulp beep task

CHANGELOG.md, package.json
Updates gulp-sitespeedio to [0.0.7](https://github.com/dreamzmaster/gulp-sitespeedio/pull/5)
- Updates `gulp-sitespeedio` from `0.0.6` to `0.0.7`. Also adds caret so this'll autoupdate to minor versions in the future.
- `gulp build` should not log `Analyze your sites web performance`. `gulp test:perf` should log `Analyze your site’s web performance`.
- @sebworks 
- @jimmynotjim
=> Updates gulp-sitespeedio to 0.0.7

cfgov/jinja2/v1/_includes/organisms/full-width-text.html, cfgov/jinja2/v1/sublanding-page-1/_template-prototype-full-width-content.html, cfgov/jinja2/v1/sublanding-page-1/index.html, cfgov/preprocessed/css/main.less, cfgov/preprocessed/css/organisms/full-width-text.less, cfgov/preprocessed/css/organisms/full-width-well.less
- Added the full-width-text module in the same style Ans did the well module
- Added styles for the bullet points. We might want to eventually port these to CF or even all bullet points, but I want to make sure the styles get approved here first.
- Visit http://localhost:8000/sublanding-page-1/
- @sebworks 
=> Adding full-width-text module and styles for bullets

test/browser_tests/spec_suites/doing-business-with-us.js
Fixes broken test introduced in https://github.com/cfpb/cfgov-refresh/commit/93ebe6e35583ab89c7de87af5e1833ee85a1c83c
- Updates email address set in the doing business with us test.
- `gulp test` or `gulp test --sauce=false` should not have error with `The Doing Business with Us Page should have a contact link with main summary` test.
- @sebworks
=> Fixes broken test for email address

CHANGELOG.md, package.json
Removes npm warning.
- Added `license` field to `package.json`.
- `npm install` should not show `npm WARN package.json @ No license field.`
- @sebworks 
- @jimmynotjim
=> Adds license field to package.json

cfgov/cfgov/settings/base.py
The site app of wagtail was removed by accident. This adds it back in.
@kave
=> Add wagtailsites app back into settings

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/contact-address.html, cfgov/jinja2/v1/_includes/molecules/contact-email.html, cfgov/jinja2/v1/_includes/molecules/contact-phone.html, cfgov/jinja2/v1/_includes/organisms/sidebar-contact-info.html, cfgov/jinja2/v1/landing-page-1/index.html, cfgov/jinja2/v1/sublanding-page-1/index.html, cfgov/preprocessed/css/main.less, cfgov/preprocessed/css/organisms/sidebar-contact-info.less
Adds Sidebar contact info organism and contact method molecule.
- Added templates and CSS for the Contact Method molecule.
- Added templates and CSS for the Sidebar Contact Info organism.
- Visit `/sublanding-page-1/`
- @sebworks 
Desktop/Mobile:
Tablet:
=> Adds Sidebar contact info

cfgov/jinja2/v1/_includes/molecules/contact-address.html, cfgov/jinja2/v1/_includes/molecules/contact-email.html, cfgov/jinja2/v1/_includes/molecules/contact-phone.html, cfgov/jinja2/v1/_includes/organisms/sidebar-contact-info.html, cfgov/jinja2/v1/sublanding-page-1/index.html, cfgov/preprocessed/css/organisms/sidebar-contact-info.less
Fixes for sidebar contact organism based on feedback in https://github.com/cfpb/cfgov-refresh/pull/1099.
- Unneeded list classes.
- Unneeded `administrative_offices_map`.
- Code comment formatting, missing fax values, and grammatical errors.
- Replaces `@mobile-max` with `@tablet-min` in range value.
- Visit `/sublanding-page-1/`
Only change is email address link is no longer bold without the link classes, which I believe is correct anyway:
- @sebworks 
=> Fixes for sidebar contact organism

.env_SAMPLE, INSTALL.md, cfgov/cfgov/wsgi.py, cfgov/manage.py, tox.ini
Also, makes the default DJANGO_SETTINGS_MODULE suitable for local development,
cfgov.settings.local
=> This removes usage of DJANGO_ENV (which is generally a less-flexible than the built-in DJANGO_SETTINGS_MODULE)

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/contact-address.html, cfgov/jinja2/v1/_includes/molecules/contact-email.html, cfgov/jinja2/v1/_includes/molecules/contact-phone.html, cfgov/jinja2/v1/_includes/organisms/main-contact-info.html, cfgov/jinja2/v1/sublanding-page-1/index.html, cfgov/jinja2/v1/sublanding-page-2/index.html
[GHE]/flapjack/Modules-V1/wiki/Contact-Information-(Main-Content-Area)
- Adds templates and CSS for the Main Contact Info organism.
- Unneeded phone format imports.
- Adds logic for optional contact fields.
- Renames contact method title to label, to disambiguate address title and label.
- Fixes code comment grammar.
- Moves placeholder hero text to code comment.
- Visit `/sublanding-page-2/`
- @sebworks 
- @jimmynotjim
=> Adds main contact info organism

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/related-posts.html, cfgov/jinja2/v1/landing-page-2/index.html, cfgov/preprocessed/css/main.less, cfgov/preprocessed/css/molecules/related-posts.less
Adding Code for Related Posts molecule
- Adding Code for Related Posts molecule.
- Visit  `/landing-page-2/` and `landing-page-2/?layout=sideNav`.
- @sebworks 
- @Scotchester
=> Adding Code for Related Posts molecule

CHANGELOG.md, setup.sh
Fixes #1004 - Uses globally installed protractor, if available. Chromedriver takes awhile to download. With this PR if protractor is installed globally, it will be copied into the `node_modules` directory, instead of downloading it every time. This cuts the time of `setup.sh` by approximately 40%.
- Uses globally installed protractor in `setup.sh`, if available.
- `npm install -g protractor && webdriver-manager update` if you don't have global protractor.
- Run `./setup.sh local`. Time should be around 2.5min, depending on Internet connection.
- `npm uninstall -g protractor`
- Run  `./setup.sh local`. Time should be about 4min, depending on Internet connection.
- Re-install global protractor, if you want the faster build time.
- @sebworks
=> Fixes #1004 - Uses globally installed protractor, if available

cfgov/preprocessed/css/molecules/related-posts.less
Fix for Related Post molecule
- Updating `cfgov/preprocessed/css/molecules/related-posts.less` to fix half width issue on mobile.
- Visit  `http://localhost:8000/landing-page-2/?layout=sideNav` and resize window to 599px.
- @sebworks 
=> Fix for Related Post molecule

setup.sh
Replaces which statement with `is_installed` helper
- Switches to using `is_installed` function for checking if MYSQL is installed, per guidance in @sebworks [comment](https://github.com/cfpb/cfgov-refresh/pull/1108#discussion_r43390509)
- Changes `program_is_installed` to `is_installed`.
- `./setup.sh local` should handle MYSQL initialization as before.
- @sebworks 
- @kurtw 
- @jimmynotjim
=> Replaces which statement with is_installed helper

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/_includes/tags.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/preprocessed/css/cf-enhancements.less, cfgov/preprocessed/css/main.less, cfgov/preprocessed/css/meta.less, cfgov/preprocessed/css/organisms/post-preview.less
The Post Preview organism which will be used for newsroom, blog posts, events and notices. The map/calendar icon for the events is still being worked on in a separate PR, but wanted to get this in since it's a large organism.
- Added post-preview organism
- Fixed specs on topic tag 
- Fixed spacing for meta-header
- Visit http://localhost:3000/browse-filterable/
- @sebworks 
- DFJR-425
- GHE/flapjack/Modules-V1/issues/16
=> Post-Preview Organism

cfgov/jinja2/v1/_includes/organisms/post-preview.html
Something seemed missing. It was the body of the post-preview molecule!
- @sebworks 
=> Fixed missing text in post-preview organism

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/form-field-with-button.html, cfgov/jinja2/v1/_includes/organisms/email-signup.html, cfgov/jinja2/v1/landing-page-1/index.html, cfgov/jinja2/v1/landing-page-2/index.html, cfgov/preprocessed/css/main.less, cfgov/preprocessed/css/molecules/form-field-with-button.less, cfgov/preprocessed/css/molecules/related-posts.less, cfgov/preprocessed/css/organisms/content-sidebar.less, cfgov/preprocessed/css/organisms/email-signup.less
Added Email Sign-up Form Organism per [GHE]/flapjack/Modules-V1/wiki/Email-Sign-Up
- Added Email signup form Organism.
- Added Email Sign-up Form Organism on `/landing-page-1/`.
- @sebworks 
- I'm using `calc` to limit width of text input in `cfgov/v1/preprocessed/css/molecules/form-field-with-button.less`.
=> Added Email Sign-up Form Organism

.eslintignore, CHANGELOG.md, cfgov/preprocessed/js/modules/polyfill/.eslintrc, cfgov/preprocessed/js/modules/polyfill/array-filter-polyfill.js, cfgov/preprocessed/js/modules/polyfill/array-foreach-polyfill.js, cfgov/preprocessed/js/modules/polyfill/array-map-polyfill.js, cfgov/preprocessed/js/modules/polyfill/event-listener.js, cfgov/preprocessed/js/modules/polyfill/object-defineproperty-polyfill.js
Syntax changes to polyfills could potentially create bugs in older browsers that would go unnoticed, this excludes the 3rd party polyfills directory from linting.
- Excludes 3rd-party JS polyfills from linting.
- `gulp lint` should not have new errors.
- @sebworks 
- @jimmynotjim
=> Exclude 3rd-party polyfills from linting

cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/preprocessed/css/organisms/post-preview.less
This adds any event-specific styles to the post-preview organism
- Visit http://localhost:8000/browse-filterable/
- @sebworks
=> Adding event-specific calendar icon and location preview to post-preview organism

cfgov/jinja2/v1/sublanding-page-2/index.html
Sublanding page 2 has a error because of a missing hero. Someone call [Enrique Iglesias](https://www.youtube.com/watch?v=HnOlw8HdVIw).
- Adds missing macro to sublanding-page-2
- Visit http://localhost:8000/sublanding-page-2/
- Add your favorite song that mentions heros in the comments.
- If someone thinks [we don't need this hero](https://www.youtube.com/watch?v=dq4aOaDXIfY), I can rip the whole thing out.
=> Adding a missing hero to sublanding page 2

CHANGELOG.md, README.md, cfgov/core/management/commands/_helpers.py, cfgov/core/management/commands/import-data.py, cfgov/core/management/commands/processors/eventpage.py, cfgov/v1/processors/eventpage.py
This makes some changes to the `import-data` command that makes it more maintainable, object-oriented, pythonic and adds the ability to import data that won't be fully fledged pages into what wagtail calls snippets. [Here's some documentation on snippets](http://docs.wagtail.io/en/v1.1/topics/snippets.html). These are things that we want to define once in the CMS but use in multiple areas e.g. Contacts. 
There's also a change to the way that we execute the command.
```
usage: manage.py import-data [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color] [--parent PARENT] [--snippet] -u
USERNAME -p PASSWORD [--app APP] [--overwrite]
data_type wagtail_type
```
**Note** that the `--parent` has become an option, and that the `--parent` or …
=> Modifies the `import-data` management command

CHANGELOG.md, cfgov/jinja2/v1/wagtail/molecules/image-text-25-75.html, cfgov/v1/models/molecules.py
This uses the same **clean()** logic as the ImageText5050 molecule, but has slightly different fields.
@kave @rosskarchner @anselmbradford
=> Add ImageText2575 molecule backend and template

CHANGELOG.md, cfgov/jinja2/v1/wagtail/molecules/call-to-action.html, cfgov/v1/models/atoms.py, cfgov/v1/models/molecules.py
- Add Call to Action backend model
- Add template to use CtA model for rendering
- Remove unused imports in v1/models/__init__.py file
@kave 
@rosskarchner 
@sebworks
=> Add Call to Action and Hyperlink atom backend

CHANGELOG.md, cfgov/jinja2/v1/wagtail/molecules/contact-address.html, cfgov/jinja2/v1/wagtail/molecules/contact-email.html, cfgov/jinja2/v1/wagtail/molecules/contact-phone.html, cfgov/jinja2/v1/wagtail/organisms/main-contact-info.html, cfgov/jinja2/v1/wagtail/organisms/sidebar-contact-info.html, cfgov/v1/migrations/0006_contactsnippet_contactmolecules.py, cfgov/v1/models/__init__.py, cfgov/v1/models/molecules.py, cfgov/v1/models/organisms.py, cfgov/v1/models/snippets.py
- Add Contact snippet
- Add Contact molecule backends
- Change Contact templates for Wagtail rendering
- Add temporary folder for storing converted templates: `cfgov/jinja2/v1/wagtail/`
Run `./cfgov/manage.py migrate` then run the server. A "Snippets" option on the sidebar of the admin in Wagtail should appear with the option to create a Contact.
@kave 
@sebworks 
@rosskarchner
=> Adds Contact to the backend

.env_SAMPLE, CHANGELOG.md
Changes .env Project configuration workon control flow to direct stdout and stderr to /dev/null so that no output will show as a result of the `if` statement.
Seems that in zsh the `type` command outputs to stdout when a command cannot be found, not stderr.
@sebworks 
@kave
=> Changes .env Project configuration

cfgov/unprocessed/css/nav-primary.less
Fixes #1029. IE8 has some weird issues with painting and the visibility property. For example, on the pre-fix mega menu, everything would paint/render as soon as you highlighted or tabbed to a thing. The About Us link rendered because we shifted focus there for accessibility.
That's been your IE8 fun-fact for the day.
=> Fixes missing text on Navigation field in IE8

CHANGELOG.md, cfgov/jinja2/v1/_includes/sidenav.html, cfgov/unprocessed/css/nav-primary.less, cfgov/unprocessed/css/nav-secondary.less
Cleaned up and rebuilt the secondary nav to reduce complexity and fix bugs
- Reduced styles for simpler code management
- Updated nav macro for new styles
- Fixed font-size issue
- Fixed Jinja error when additional_classes weren't defined
- Moved font size variable to primary nav where it's used
- run `gulp build` and test any page w/ a left side nav
- @ajbush 
- @sebworks 
- Replaces PR #1128 
- Updates #637, but the `@font-size-large` still needs to be refactored out of the primary nav in another PR
=> Cleaned up and rebuilt the secondary nav

cfgov/jinja2/v1/_includes/molecules/call-to-action.html, cfgov/jinja2/v1/_includes/molecules/form-field-with-button.html
Fixes for Atomic macros
- Updated `cfgov/jinja2/v1/_includes/molecules/call-to-action.html` to fix issues with the settings names.
- Updated `cfgov/jinja2/v1/_includes/molecules/form-field-with-button.html` to fix issue with `required` attribute.
- @kave
=> Fixes for Atomic macros

CHANGELOG.md, package.json, setup.sh
- Updates protractor from 2.5.1. to 3.0.0.
- If you have global protractor installed run `npm uninstall -g protractor && npm install -g protractor`
- Run `./setup.sh && gulp test --sauce=false` or `./setup.sh && gulp test`. Should not have new issues (we have an existing test that times out).
- @sebworks 
=> Update to protractor 3.0.0.

CHANGELOG.md, package.json
Updates gulp-sitespeedio. This should automatically update in our current setup, but for some reason isn't without explicitly telling it to.
- Updates gulp-sitespeedio to 0.0.8 from 0.0.7.
- `./setup.sh && gulp test:perf` should run (though the performance tests will fail, which is expected).
- @sebworks
=> Update gulp-sitespeedio to 0.0.8

cfgov/jinja2/v1/_includes/molecules/related-posts.html, cfgov/unprocessed/css/molecules/related-posts.less
Refactoring Related-Posts macro to display various post types
- Updated `cfgov/jinja2/v1/_includes/molecules/related-posts.html` to display various post types. 
- Updated `cfgov/jinja2/v1/_includes/molecules/form-field-with-button.html` to display various post types.
- @kurtw 
=> Refactoring Related-Posts macro to display various post types

CHANGELOG.md, runserver.sh
If you reboot and don't run setup.sh, MYSQL won't be running leading you to start the server, then quit the server, then start MYSQL, then start the server again. I hate remembering all that, I just want the server up and running so I can get on with my work. This fixes that.
__Note:__ I removed the comment about the script being a duplicate, because at this point we all know. I personally just use the script so I don't have to type so much and don't have to switch to a new command when something inevitably changes. I can revert that part if everyone disagrees with me.
=> Updated runserver script for easier startup

CHANGELOG.md, cfgov/cfgov/urls.py, cfgov/jinja2/v1/_includes/molecules/expandable.html, cfgov/jinja2/v1/_includes/organisms/expandable-group.html, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/molecules/expandable.less, cfgov/unprocessed/css/organisms/expandable-group.less, cfgov/unprocessed/js/modules/polyfill/class-list.js, cfgov/unprocessed/js/modules/util/EventObserver.js, cfgov/unprocessed/js/molecules/Expandable.js, cfgov/unprocessed/js/organisms/ExpandableGroup.js, cfgov/unprocessed/js/routes/browse-basic/index.js
Adds browse-basic page, Expandable/ExpandableGroup prototypes. Re-submission of https://github.com/cfpb/cfgov-refresh/pull/1134
- Adds browse-basic prototype page and URL.
- Adds Expandable molecule.
- Adds ExpandableGroup organism.
- Adds `classList` JS polyfill.
- Adds `u-hide` utility class to hide an element.
- Adds `EventObserver.js` for adding event broadcaster capability to JS classes.
- Visit `http://localhost:8000/browse-basic/`
- @sebworks 
- There a a few TODOs in Expandables.js source code.
=> Adds browse-basic page, Expandable/ExpandableGroup protos

CHANGELOG.md, cfgov/unprocessed/js/modules/util/atomic-checkers.js, cfgov/unprocessed/js/molecules/Expandable.js, cfgov/unprocessed/js/organisms/ExpandableGroup.js
Adds atomic HTMLNode checker utility.
- Adds `atomic-checkers.js` and `validateDomElement` method for validating base atomic element base element and throwing a useful error if the incorrect CSS class name is used or not referenced properly.
- Pass an incorrect dom element to an Expandable or ExpandableGroup instance in `/unprocessed/js/routes/browse-basic/index.js`
- Run `gulp build`
- Check console in `localhost:8000/browse-basic/` for error thrown.
- @sebworks 
- @jimmynotjim
=> Adds atomic HTMLNode checker utility

INSTALL.md
- Adds note about how to install and initialize global protractor. If protractor is installed globally but chromedriver isn't downloaded setup.sh will fail.
- @sebworks
=> Updates INSTALL.md

setup.sh
- Quits setup.sh if Chromedriver hasn't been downloaded into global protractor.
- Throw out `/Users/[MAC OSX USERNAME]/homebrew/lib/node_modules/protractor/selenium`
- Run `./setup.sh` and follow prompts. Should show error 
```
ERROR: Please run `webdriver-manager update` and try again!
```
- @sebworks
=> Check that Chromedriver is downloaded

cfgov/v1/wagtail_hooks.py
wagtail hooks only return `Page` object, resolved by using id to get child `CFGOVPage` object and saving share field.
@kurtw 
@rosskarchner
=> Fixed issue with Publish data deleting saved content

CHANGELOG.md, cfgov/v1/__init__.py
As we finalize the templates to be used by Wagtail, it limits how we can use the template code because we won't be able to pass data into the included (or imported) template unless it's in the context ( see instances of `with context`). When rendering in Wagtail, `page` is passed into the context, while when prototyping it won't be. 
Essentially, this PR gives us an empty dictionary to modify that these included templates will have access too.
For example, related-posts.html template could be used like this:
```python
{# In prototype #}
...
{% set doc = get_document('doc-type', 'slug-of-something-in-es') %}
{% do global_dict.update({'page':  {
'related_posts': {
'posts': more_like_this(doc, search_types='posts', search_size=3),
'newsroom': more_like_this(doc, search_types='newsroom', …
```
=> Add global variable to Jinja2 context for easier prototyping

cfgov/jinja2/v1/_layouts/content-base-sidebar-first.html, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/unprocessed/css/breadcrumbs.less, cfgov/unprocessed/css/cf-enhancements.less
This adds breadcrumbs to the browse-basic and browse-filterable pages with the appropriate amount of spacing.
- Visit /browse-basic/ and /browse-filterable/ and check spacing in mobile and desktop sizes against GHE/flapjack/Modules-V1/wiki/Breadcrumbs
- @sebworks 
- All the styles for breadcrumbs were in pixels and not ems, is that because of something with layout or should they be converted over?
=> Adding breadcrumbs to browse pages

cfgov/jinja2/v1/careers/application-process/index.html, cfgov/jinja2/v1/the-bureau/index.html
The heros broke during the transition to wagtail. Updated where they were used to pass values to the hero macro.
- Updated `the-bureau` and `careers/application-process` to correctly pass data to the hero macro.
- checkout `/careers/application-process/` and `/the-bureau/` locally
- @kave 
- @kurtw 
=> Updated the two heros outside of wagtail and the prototype

cfgov/templates/wagtailadmin/pages/create.html, cfgov/templates/wagtailadmin/pages/edit.html, cfgov/v1/migrations/0012_share_perms.py, cfgov/v1/templatetags/share.py, cfgov/v1/wagtail_hooks.py
Adds Share page permission to the V1 CFGOVPage model and then adds it as an option for a Group.
@kave 
@rosskarchner
=> Add Share page permission

cfgov/v1/migrations/0012_share_perms.py
This fixes the unnecessary duplicate entry error.
@kave 
@jimmynotjim
=> Fix Share page permission migration

cfgov/jinja2/v1/landing-page/index.html
This was causing Jinja errors on `flajpack` and all up to date branches.
=> Fixed broken for loop in sidebar

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/related-posts.html, cfgov/jinja2/v1/events/event.html, cfgov/jinja2/v1/landing-page/index.html, cfgov/v1/__init__.py, cfgov/v1/migrations/0014_addshowheading_relatedposts.py, cfgov/v1/models/base.py, cfgov/v1/models/organisms.py, test/browser_tests/page_objects/page_blog-single.js
- Revert related_posts method logic to use tags instead of elasticsearch
- Fix jinja2 logic in related-posts.html
- Add `show_heading` boolean to Related Posts molecule backend
- Disable blog post and newsroom checkboxes temporarily
- Add related_posts_function to the global context in Jinja2 for prototyping of related posts
- Temporarily comment out related posts browser test for single blog page
- Keep commented out until BlogPage is in Wagtail
@kave
=> Fix Related Posts organism

cfgov/unprocessed/css/molecules/full-width-text.less, cfgov/unprocessed/css/molecules/inset.less, cfgov/unprocessed/css/organisms/full-width-text-group.less
Fixes issue where small amounts of text or strange placement would cause awkward floats
In #1209, we got really awkward floats if the full width text was too short or if the article ended with an inset. This fixes the issue with a few lines of CSS.
- @kurtw 
- @jimmynotjim
=> Fixes awkwardly floating insets

cfgov/jinja2/v1/_includes/macros/category-icon.html
Optimizes category-icon macro. Part of item introduction task.
- Removes redundant code in favor of lookup table.
- Removes `cfpb_report` entry because it was just including an empty span element.
- `/blog/` categories should be as before.
- @sebworks
=> Optimizes category-icon macro

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/form-field-with-button.html, cfgov/jinja2/v1/_includes/molecules/hero.html, cfgov/jinja2/v1/_includes/organisms/email-signup.html
Updated the `form-field-with-button` and `email-signup` to use proper prototyped data and remove extra conditional markup.
- Added prototype data to the `form-field-with-button` molecule
- Added prototype data to the `email-signup` organism
- Added the `email-signup` organism to `landing-page` template
- `gulp build` and navigate to `/landing-page/`
- @kave 
- @kurtw 
- @sebworks 
=> Converted two macros to use proper prototype data

cfgov/unprocessed/css/forms.less
Quick bugfix discovered during multi-select work.
Before:
After:
=> Fixed checkmark location inside the box

.travis.yml, CHANGELOG.md, frontend.sh
Explicitly sets g++ version on Travis for handling nan errors and sets loglevel on npm install to warning to remove `npm info` clutter from the output log.
- sets g++ version on Travis
- sets npm install loglevel to warn in `frontend.sh`.
- `./setup.sh` should have less output and Travis log in this PR should be shorter.
- @sebworks 
- @kave
=> Set g++ in TravisCI

cfgov/jinja2/v1/landing-page/index.html
In #1281, @Schlachtmeyer pointed out the spacing on one of the landing pages is off when there is no page intro. I moved over some code from the sublanding to fix this.
- @kave 
- @sebworks
=> Fixing spacing on top element in cases when page-intro isn't on the page

cfgov/jinja2/v1/sublanding-page/index.html
In #1277, @Schlachtmeyer pointed out a weird gap between the hero and content area. I've removed that by checking for a sidebar breakout before rendering since the introduction text in the pre-content area should always be paired with one. This might make debugging a little tricky for content people, so I'm open to other solutions.
- @kave 
- @sebworks 
=> Removes empty pre-content block when no breakout sidebar is present

cfgov/jinja2/v1/_includes/molecules/form-field-with-button.html, cfgov/jinja2/v1/_includes/molecules/half-width-link-blob.html, cfgov/jinja2/v1/_includes/organisms/email-signup.html, cfgov/unprocessed/css/molecules/half-width-link-blob.less, cfgov/v1/models/molecules.py
In #1277, Schlachtmeyer pointed out some spacing issues on the link blobs and email signup. This fixes them and also marks the label as required since this is necessary for accessibility.
- @sebworks 
- @kave
=> Fixing spacing for half link blob and email signup

cfgov/cfgov/urls.py, cfgov/core/services.py, cfgov/jinja2/v1/_includes/macros/filters.html, cfgov/jinja2/v1/the-bureau/leadership-calendar/index.html, cfgov/unprocessed/js/config/error-messages-config.js, cfgov/unprocessed/js/modules/post-filter.js, cfgov/v1/__init__.py, cfgov/v1/forms.py, cfgov/v1/util/util.py
Adds server side and client side validation for the Leadership Calendar PDF Form.
- Added client side/server side validation for the Leadership Calendar PDF Form.
- Turn off Javascript and browse to the `http://localhost:8000/the-bureau/leadership-calendar/` page. Submit the calendar PDF form without selecting any options. You should see error notifications once redirected.
- @kurtw 
- @kave 
- There is still some ongoing work related to converted the Filters to Django Forms.
=> Leadership Calendar PDF Form validation

bower.json, cfgov/jinja2/v1/_includes/molecules/notification.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/molecules/expandable.less, cfgov/unprocessed/css/molecules/notification.less, cfgov/unprocessed/css/organisms/expandable-group.less, cfgov/unprocessed/css/organisms/filterable-list-controls.less, cfgov/unprocessed/js/modules/post-filter.js, cfgov/unprocessed/js/molecules/Notification.js, cfgov/unprocessed/js/organisms/FilterableListControls.js, cfgov/unprocessed/js/routes/browse-filterable/index.js, package.json
Integrate notification into filter.
- Adds JS file for Notification instance to change content, show, and hide at runtime.
- Integrates notification into filter. 
- Moves validation library from bower to npm.
- Wraps notification content in a div so that it can be overwritten at once.
- Padding below the expandables. I don't think this is required and it messes things up for, e.g. the spacing of an expandable inside a filter.
- Submit filter on `/browse-filterable/`
- @sebworks 
- Validation needs to be added. This PR adds some of the skeleton for it, but the existing validation JS needs to be integrated.
=> Integrate notification into filter

cfgov/v1/__init__.py, cfgov/v1/util/util.py
Fixing get_unique_id method to return hex based time stamp
- Fixing get_unique_id method to return hex based time stamp
- View filter checkbox ids on the `http://localhost:8000/the-bureau/leadership-calendar/` page.
- @kave
=> Fix for get_unique_id method

cfgov/unprocessed/css/molecules/image-text-50-50.less
Last one! #1281 has an issue where the 50-50 images are distorted. This was because of a misunderstanding on how this molecule would be implemented. I talked it over with @duelj and now the spacing should be fixed.
- @duelj -- can you review the size and spacing? I couldn't find specs in the wiki.
- @sebworks
=> Fixing 50-50 image container to center circle images

CHANGELOG.md, cfgov/unprocessed/js/modules/nav-primary.js, cfgov/unprocessed/js/modules/util/aria-state.js, cfgov/unprocessed/js/modules/util/dom-traverse.js, cfgov/unprocessed/js/modules/util/expanded-state.js, package.json, test/unit_tests/modules/nav-primary-spec.js, test/unit_tests/modules/util/expanded-state-spec.js
Prep for global search to share JS with nav.
- `dom-traverse.js` for dom querying not covered by native dom.
- removes jquery from primary nav JS and replaces with native querying.
- Resize site to mobile size and navigate primary menu. Should work as before.
- @sebworks
=> Removes jQuery from nav-primary.

CHANGELOG.md, package.json
- Updates gulp-load-plugins to 1.2.0. I don't get why the caret isn't autoupdating this, but it isn't.
- @sebworks 
=> Updates gulp-load-plugins to 1.2.0

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/image-text-25-75.html, cfgov/jinja2/v1/_includes/organisms/full-width-text.html, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/document-detail/index.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/unprocessed/css/molecules/full-width-text.less
Fixes bugs reported in #1304 and #1206
- List style modifications (now defaults to CF styles)
- Added `sans` modifier option to global dict (this is temporary, BEWDs should plan on this changing to a `serif` modifier)
- navigate to `/sublanding-page/`
- @kave 
- @tnferrell 
- @sebworks 
- @duelj and I discussed the font-family of full-width-text and according to the latest decisions, the font-family should be Avenir (sans-serif) on all full-width-text molecules except learn pages (blog, newsroom, events, etc).
- I discussed changing the default font-family to Avenir with the rest of the v1 FEWDs and we agreed it makes the most sense, but want to bring it up with all FEWDs and possibly Designers in the Design Manual (@duelj has an [open issue …
=> Fixing wagtail and style bugs

.env_SAMPLE, CHANGELOG.md, backend.sh, cfgov/v1/migrations/0031_init_data.py, initial-data.sh
It was bothering me how many times i had to recreate my admin user every-time i dropped my db during branch switching. This data initialization should be helpful and it'll load the event pages & contacts from ES
- Data initialization script
- Appended data initialization during debug mode of `./setup.sh`
- set environment variable `WAGTAIL_ADMIN_PW`
- drop database
- run `./create-mysql-db.sh`
- run `./initial-data.sh`
- log into wagtail
@jimmynotjim 
@sebworks 
@rosskarchner 
@kurtw
=> DB data initialization

CHANGELOG.md, package.json
jQuery `1.12.0` changes cause jsdom to throw errors during unit tests.
- Pinning jQuery version to fix jsdom errors during unit tests
- run `./setup.sh` and `gulp test:unit:scripts`
- @sebworks 
- Update jsdom to `8.0.0` when it's released and retest with jquery `1.12.0`
=> Bugfix for jsdom errors in unit tests

cfgov/unprocessed/css/molecules/expandable.less
Fixing initial load state of Filter
-  Modified `cfgov/unprocessed/css/molecules/expandable.less` to target `.m-expandable_content[aria-expanded='true']`
- Visit `http://localhost:8000/browse-filterable/` and turn your js off. 
=> Fixing initial load state of Filter

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/full-width-text.html, cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/document-detail/index.html, cfgov/jinja2/v1/learn-page/index.html, cfgov/jinja2/v1/sublanding-page/index.html
Resolved san-serif font for full-text elements during wagtail rendering 
fixed richtext fields not being able to render images
@jimmynotjim 
- [Fixed 1320] (https://github.com/cfpb/cfgov-refresh/issues/1320)
- completes https://github.com/cfpb/cfgov-refresh/issues/1304
=> Image rendering issues in rich-text and San-serif fonts for Full-width-text

cfgov/jinja2/v1/browse-basic/index.html, cfgov/unprocessed/css/cf-enhancements.less
- ~~`input-contains-icon`~~ `input-contains-label` for placing an icon in front and at the end of an input field, plus modifiers for specific icons.
- Demo at bottom of `/browse-basic/`.
- @sebworks 
Mobile:
Tablet:
Desktop:
-  `btn-inside-input` in cf-forms is deprecated by `input-contains-icon`, so that the classes can follow the format of `input-with-btn`. Also, the modifiers are added so that the spacing is controlled. `btn-inside-input` allows a button and a label but doesn't adjust the input padding based on the content of button.
=> Adds input-contains-label class

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/related-metadata.html, cfgov/jinja2/v1/document-detail/index.html, cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/molecules/related-metadata.less
Adding Related Metadata Molecule
- Adding Related Metadata Molecule
- Visit  `http://localhost:8000/document-detail/`.
Mobile:
Tablet:
Desktop:
=> Adding Related Metadata molecule

CHANGELOG.md, cfgov/cfgov/settings/base.py, cfgov/v1/migrations/0032_cfgovimage_cfgovrendition.py, cfgov/v1/migrations/9999_init_data.py, cfgov/v1/models/base.py
- Added data migration for old images saved under previous type.
@kave 
@rosskarchner 
- **Before you run migrate** make sure you have images in your DB to see if they convert properly
- run migrate
- check images
- check to see if alt is there
- check to see if you can save alt data
- check that deletion deletes the instances from BOTH CFGOVImage and CFGOVRendition (just go into shell and query)
=> Added CFGOVImage and CFGOVRendition

cfgov/jinja2/v1/_includes/molecules/image-text-50-50.html, cfgov/unprocessed/css/molecules/image-text-25-75.less, cfgov/unprocessed/css/molecules/image-text-50-50.less, cfgov/unprocessed/css/organisms/image-text-50-50-group.less
Fixes #1235 by removing the spacing from the molecule to have it handled by `.block` and fixing the spacing on the header for the 50-50 molecule.
- @sebworks
=> Fixes to spacing on 50-50 and 25-75 text-image molecules

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/jinja2/v1/_layouts/base.html, cfgov/unprocessed/css/atoms/multi-select.less, cfgov/unprocessed/css/cf-enhancements.less, cfgov/unprocessed/css/cf-theme-overrides.less, cfgov/unprocessed/css/main.less, cfgov/unprocessed/js/modules/util/array-helpers.js, cfgov/unprocessed/js/molecules/Multiselect.js, cfgov/unprocessed/js/routes/browse-filterable/index.js
- Adds multi-select atom styles
- Adds multi-select atom scripting
- Updated browse-filterable demo
- Updated filterable-list-controls organism to allow for `multiple` option
- `gulp build` and navigate to `/browse-filterable/`
- @sebworks 
- @duelj 
- @schaferjh 
- Based on UK.gov checkbox multi-choice pattern
- Filtering script based on Awesomecomplete
- Needs 508 testing
- Doesn't support option groups yet
- There's a tab bug due to a change in visibility hidden handling in webkit
=> Prototyping a better multi-select

cfgov/cfgov/settings/base.py, cfgov/v1/views.py
Set settings.LOGIN_REDIRECT_URL field to get proper usage of Django is_safe_url which returns True when the URL is safe to be used as a redirect; in the case of a False return, you'd simply use a default path to redirect to.
Also edited request to get redirect_field_name from GET request only.
@kurtw
=> addressed,security concerns with redirect_field_name

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/global-search.html, cfgov/jinja2/v1/_includes/templates/header.html, cfgov/jinja2/v1/_layouts/content-base.html, cfgov/unprocessed/css/cf-enhancements.less, cfgov/unprocessed/css/header.less, cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/molecules/global-header-cta.less, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/routes/common.js
Adds Global Search, initial Submit a complaint CTA, & Header
- Atomic Global Search molecule.
- Initial atomic Submit a Complaint CTA.
- Initial atomic Header.
- Moves initial styling from non-atomic to atomic header.
- Visit the site, click on search, enter text, resize window.
- @sebworks 
Desktop size, contracted:
Desktop size, expanded:
Tablet size, contracted:
Tablet size, shows button text:
Tablet size, full suggestions width:
Mobile size, contracted:
Mobile size, smallest size, expanded:
Mobile size, expanded:
Entering text:
- **There's a bug in cf-forms where the button and input heights are different (https://github.com/cfpb/capital-framework/issues/261), which shows up in this PR.**
- Submit a complaint CTA needs to be incorporated into the Mega …
=> Adds Global Search, initial Submit a complaint CTA, & Header

cfgov/unprocessed/css/molecules/global-header-cta.less
- Visit the homepage in an incognito window. You should see the link color change on rollover:
@jimmynotjim You were right, the link color set on the Global Header CTA can be removed. The color change is due to the global header CTA being a visited link color.
=> Removes color variable

CHANGELOG.md, cfgov/jinja2/v1/wagtail/demo/index.html, cfgov/v1/migrations/0035_cfgovpage_language.py, cfgov/v1/models/base.py, cfgov/v1/models/ref.py
Included a Language selector for Pages, which defaults to English.
This was included because the use case for multiple languages on 1 page is not valid.
@kurtw 
- Template tag: {{ page.language }}
=> Language dropdown for pages, which defaults to english

CHANGELOG.md, package.json
- Updated `mocha` from `2.2.4` from `2.4.2` and Updated `sinon` from `1.14.1` from `1.17.3`.
- `npm install && gulp test --sauce=false` should work as before.
- @sebworks
=> Updated mocha and sinon

CHANGELOG.md, package.json, test/browser_tests/page_objects/page_blog-single.js, test/browser_tests/page_objects/page_blog.js, test/browser_tests/page_objects/page_careers-application-process.js, test/browser_tests/page_objects/page_careers-current-openings.js, test/browser_tests/page_objects/page_careers-working-at-cfpb.js, test/browser_tests/page_objects/page_careers.js, test/browser_tests/page_objects/page_newsroom-press-resources.js, test/browser_tests/page_objects/page_newsroom.js
- Updated `lodash` from `3.10.0` from `4.0.1` and requires `lodash.assign` as a module instead of importing the full lodash and calling the assign method.
- `npm install && gulp test --sauce=false` should work as before.
- @sebworks 
- @jimmynotjim
=> Updated `lodash` from `3.10.0` from `4.0.1`

cfgov/jinja2/v1/browse-basic/index.html
This was unnecessarily added and shouldn't be on this type of page. I just checked with @schaferjh to confirm.
This fixes the issues in #1370 that were all occurring on browse-basic pages.
- @sebworks
=> Removing social media from the top of browse pages.

cfgov/jinja2/v1/_includes/macros/accessible-languages.html, cfgov/jinja2/v1/_layouts/content-base-main-first.html, cfgov/jinja2/v1/_layouts/content-base-main-only.html, cfgov/jinja2/v1/_layouts/content-base-sidebar-first.html
This builds on the work in #1361 to allow content editors to specify a language for the main content to be in. This assumes that most of the sidebar content will remain in English or be dealt with separately. This also adds RTL support for arabic.
- Go to the admin panel and create a page in a different language and in arabic
- Arabic should render RTL and the appropriate `lang` tag should be added to main content section.
- @sebworks 
- @kave
=> Adding multi-language screenreader support

cfgov/jinja2/v1/_includes/molecules/half-width-link-blob.html, cfgov/jinja2/v1/_includes/molecules/image-text-50-50.html, cfgov/jinja2/v1/_includes/organisms/half-width-link-blob-group.html, cfgov/jinja2/v1/_includes/organisms/image-text-50-50-group.html, cfgov/jinja2/v1/_includes/organisms/layout-two-columns.html, cfgov/unprocessed/css/molecules/half-width-link-blob.less, cfgov/unprocessed/css/molecules/image-text-50-50.less, cfgov/unprocessed/css/organisms/image-text-50-50-group.less, cfgov/unprocessed/css/organisms/link-blob-group.less
- Creates two-column module for @kave and @kurtw to add to well organism
- Changes all the two-columns modules to use `content-l_col-1-2` and removes unnecessary LESS
- Less LESS!
- Check out the 50-50 text image module and the half link blob on the landing page
- @sebworks
=> Creating 50-50 module and using CF two-column css

cfgov/unprocessed/js/molecules/Expandable.js, cfgov/unprocessed/js/molecules/Multiselect.js
Adding code to refresh the height of the Expandable on DOM insertion/deletion. Also fixed some minor bugs so I could test on IE9/Firefox. 
Having written this I believe I took the wrong approach. @ans, how would you feel about exploring using css to handle showing/hiding the `m-expandable_content` instead of Javascript? This would probably involve using `margin-top ` instead of setting the height. 
- Visit  `http://localhost:8000/browse-filterable/`.
Firefox just recently added `innerText` and its better to use `textContent` per https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent. Of course this won't work in IE8 which I'm happy about. 
We should also consider throttling or debouncing `_refreshHeight`  to prevent costly reflows caused by accessing `offsetHeight`.
- …
=> Adding Expandable Observe

cfgov/unprocessed/css/brand-palette.less, cfgov/unprocessed/css/molecules/global-search.less
- Update the Global Search close button and content style to match the grays in https://github.com/cfpb/cfgov-refresh/pull/1399 for the mega menu hamburger menu.
- `gulp build`
- Visit any page, change size to mobile, expand and collapse the global search.
- @duelj 
- @sebworks 
=> Global search close button

cfgov/jinja2/v1/_includes/organisms/item-introduction.html
Fixes #1391, so the "By" is hidden when content enters a blank author.
- @sebworks 
- @jimmynotjim
=> Hiding extra markup when no author is given in item intro

cfgov/jinja2/v1/_includes/molecules/contact-email.html, cfgov/jinja2/v1/_includes/organisms/sidebar-contact-info.html
This fixes the issue where the email would appear as "email"
Fixes DFJR-745.
- Create a sublanding page with a "Contact Info" molecule in the sidebar
- Select a contact with email like "Accessibility Feedback"
- Preview page
- @sebworks
=> Fixing Email Links on Contact Info

cfgov/jinja2/v1/index.html, cfgov/unprocessed/css/footer.less
content_bar is not needed in homepage template as it's added by the header.
- content_bar div from homepage template.
- Narrows footer upper bar to 5px, per specs.
- `gulp build` and check homepage header and footer green bars. Should be 5px.
- @jimmynotjim
- @sebworks 
- @KimberlyMunoz  
- @duelj 
Header
Footer
=> Content bar fix

cfgov/unprocessed/css/molecules/global-header-cta.less
- Turns out the global header cta (and mega menu) shouldn't have visited link colors. This fixes the colors in the global header cta.
- Sets the padding on the link itself so that the "focus" state occupies the whole padded area.
- `gulp build`
- Check global header cta in header. It should always be pacific blue and shouldn't have a visited link color.
- @sebworks
=> Color and display fix for global header cta

CHANGELOG.md, cfgov/jinja2/v1/_layouts/base.html, cfgov/unprocessed/css/pages/beta.less, cfgov/unprocessed/js/modules/beta-banner-state.js, test/unit_tests/fixtures/StorageMock.js, test/unit_tests/modules/beta-banner-state-spec.js
Refactoring Beta Banner to use a general life cycle (`init`, `initEvents`, `destroy`). Also switched the code to use the Atomic Expandable.
- Visit  `http://localhost:3000/`.
- Currently working on the testing spec and trying to figure out how to test private functions.
- We should also consider passing boolean values instead of integers to set the initial state of the Expandable.
=> Refactoring Beta Banner

cfgov/jinja2/v1/_includes/molecules/global-search.html, cfgov/unprocessed/css/cf-enhancements.less, cfgov/unprocessed/css/misc.less, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/molecules/GlobalSearch.js
- Updates Global search to:
- Handle tabbing through the search
- Clicking off the search box to close it.
- Add basic no-js state.
- `gulp build`
Keyboard:
- Resize to mobile size.
- tab through to highlight search magnifying glass, continue tabbing to pass by hidden search input.
- click in beta banner.
- tab through to highlight search magnifying glass.
- Press spacebar to expand menu.
- Press tab to tab off of global search and observe it closes.
- Repeat for desktop
Mouse:
- Resize to mobile size.
- Click magnifying glass to expand search.
- Click off global search element to close it.
- Repeat for desktop.
- @sebworks 
- Basic no-js state is present but stacking and padding will need to be added when no-js hamburger menu is added.
=> Global search - keyboard + hiding

cfgov/jinja2/v1/budget/index.html, cfgov/jinja2/v1/careers/index.html
I was fixing an unrelated issue when I noticed two links to pages we hadn't changed.
- @sebworks 
- @jimmynotjim
=> Adding two missing links to Related Links section

cfgov/v1/views.py
Django `is_safe` would still allow with `http://` in the redirect which left us at risk. resolved by only allowing  https://www.djangoproject.com/weblog/2015/mar/18/security-releases/
@kurtw 
@rosskarchner 
@richaagarwal
=> implemented fix for xss attack possibility in login redirects

cfgov/unprocessed/js/modules/jquery/cf_notifier.js
Updating the notifier markup to use the atomic classes.
- Visit  `http://localhost:blog/` and enter invalid email address.
Before : 
After:
=> Fix for notifier classes

.travis.yml
Our travis build had been depending on g++48 from the [ubuntu-toolchain-r](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=precise) PPA, which no longer seems to carry it.
This PR switches us to the built-in clang++ compiler now, which appears to work fine.
=> use clang when NPM needs to compile c++

frontend.sh
Checks for protractor global install before npm installs a local protractor.
- `./frontend.sh`
- @jimmynotjim
=> Local protractor install fix

cfgov/v1/processors/contact.py
It was incorrectly setting all phone numbers to be fax's now correctly differentiates.
@kurt
@richaagarwal 
1) First load your contacts using the `Flapjack` branch
`./cfgov/manage.py import-data contact contact --snippet -u <wagtail_admin_username> -p <wagtail_admin_password>`
2) Verify Contact `Financial Institutions and Business Liaison` number are faxes
3) Checkout this `bug` branch and overwrite contacts
`./cfgov/manage.py import-data contact contact --snippet -u <wagtail_admin_username> -p <wagtail_admin_password> --o`
4) Verify Contact `Financial Institutions and Business Liaison` number is now phone
=> phones now getting set correctly in Import Data Script

CHANGELOG.md, cfgov/v1/models/base.py, cfgov/v1/wagtail_hooks.py
- Also solved memory leak of double revisions created for a single Page save
- Added comments for clarity
Explained in code comments.
If a page was published then it's content is updated and shared but not published, the published page will show the updated content.
- BEFORE pulling down, try publishing a page, then editing and sharing the updated page. You will see the update on both the live version and shared version of the page.
- Pull down the code. Repeat publishing, editing, and sharing. You should see the desired behavior.
@kave 
@richaagarwal 
@rosskarchner
=> Fix bug where publised pages were showing shared content

cfgov/unprocessed/css/molecules/expandable.less
Adds font family to button override on expandables. Fixes #1442!
- Create a document detail page with an expandable
- Fonts should no longer be "Sans Serif" but Avenir Medium
- @sebworks 
=> Fixes font on expandables

CHANGELOG.md, cfgov/unprocessed/js/modules/ClearableInput.js, cfgov/unprocessed/js/molecules/GlobalSearch.js
Spins clearable input behavior out of the Global Search molecule.
- Adds `ClearableInput` class for encapsulating `input-contains-label` clearable label behavior.
- Updates Global Search to use ClearableInput instance.
- `gulp build`
- Expand global search.
- Type something.
- Click (x) clear.
- Try at different screen sizes.
- Should work and be error-free.
- @sebworks 
- Note that since the clear label is a label of input, it is not directly tab accessible as tabbing to the clear button automatically moves to the associated input. I think this is okay because the delete key can be used to remove the input? This is existing behavior.
=> Spin off ClearableInput behavior

cfgov/jinja2/v1/_includes/molecules/text-introduction.html, cfgov/jinja2/v1/_includes/organisms/item-introduction.html
In item and text introductions, any hard enter will break the formatting
on rendered pages. This changes the p tags into divs to fix this.
Also resolves issue #1336 and #1466.
- Create a page with a text introduction and item introduction. The document detail page is the best place to do both at once.
=> Changing p tags in introductions to divs

cfgov/jinja2/v1/about-us/index.html, cfgov/jinja2/v1/budget/strategic-plan/index.html, cfgov/jinja2/v1/doing-business-with-us/past-awards/index.html, cfgov/jinja2/v1/doing-business-with-us/small-businesses/index.html, cfgov/jinja2/v1/doing-business-with-us/upcoming-procurement-needs/index.html, cfgov/jinja2/v1/the-bureau/about-deputy-director/index.html, cfgov/jinja2/v1/the-bureau/about-director/index.html, cfgov/jinja2/v1/the-bureau/bureau-structure/index.html, cfgov/jinja2/v1/the-bureau/index.html
A number of spacing fixes:
- About us page spacing fixes to bring things in line with #1396
- Fixed well spacing for new CF changes
- Made intro paragraphs as consistent with new wagtail intro paragraphs as possible with a light touch (since these might get ported to wagtail)
- Check about us page, budget, bureau and doing business pages
- @sebworks
=> Spacing fixes to intro molecule, about us page and wells

CHANGELOG.md, package.json
- Update jsdom from 7.2.2. to [8.0.4](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#800)
- `./setup.sh`
- `gulp test:acceptance --sauce=false` or `gulp test:acceptance`
- @sebworks 
- @jimmynotjim
=> Update jsdom from 7.2.2. to 8.0.4

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/main-contact-info.html
Jinja2 imports were unnecessary and breaking the page that the organism main contact info exists on.
- jinja2 imports that were unnecessary and breaking the page
- Go to a page with that organism.
- @kave
=> Fix main contact info breaking pages

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/expandable.html, cfgov/jinja2/v1/_includes/organisms/secondary-navigation.html, cfgov/jinja2/v1/_layouts/layout-side-nav.html, cfgov/unprocessed/css/cf-enhancements.less, cfgov/unprocessed/css/organisms/secondary-navigation.less, cfgov/unprocessed/js/organisms/SecondaryNavigation.js, cfgov/unprocessed/js/routes/common.js
Updated secondary navigation organism
- Adds new content flush sides on small modifier to fix an issue where margin was set on the molecule level instead of the template
- Removes prototype code from expandable
- Updated the secondary nav to utilize new expandable molecule instead of old CF Expandable
- checkout and `gulp build`, then visit `/the-bureau/`
- @sebworks 
- The expand/collapse icon displayed on smaller screens is now the default expandable icon/text
- Split Expandable into a base expandable styles and scripts to be adjusted by the main expandable and secondary nav, rather than overwriting the expandable styles in the sec nav styles
=> Updated secondary navigation organism

cfgov/jinja2/v1/landing-page/index.html, cfgov/jinja2/v1/sublanding-page/index.html
Sublanding pages were incorrectly showing elements due to multiple for loops
-
-
- removed duplicate for loops
- Create and preview a sublanding page. Should only show elements once
- @kurtw 
-
-
=> Fixed sublanding duplicate entries

cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/unprocessed/css/cf-enhancements.less, cfgov/unprocessed/css/organisms/post-preview.less
- Post preview headline is now a link to the post
- Adds .external_link_text and .external_link_url for the ability to add an additional link to post preview
- Fixes a few spacing issues with post-preview organism.
- Resolves issue #1434
- Create a browse filterable page and publish it locally with the "Amicus Brief" filter
- Create lots of document-detail pages under the browse-filterable page with "amicus brief" page types.
- Test~
- @kave 
- @sebworks 
=> Fixing post-preview organism

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/featured-content.html, cfgov/jinja2/v1/_includes/molecules/text-introduction.html, cfgov/jinja2/v1/_includes/templates/render_block.html, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/jinja2/v1/document-detail/index.html, cfgov/jinja2/v1/landing-page/index.html, cfgov/jinja2/v1/learn-page/index.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/jinja2/v1/wagtail/demo/index.html, cfgov/v1/models/molecules.py, cfgov/v1/models/organisms.py
- Included atomic element specific css modifier
- Create a Sublanding page, with any element first then a `Well` 2nd. 
- Should see that the grey background touches the sidebar
- @kurtw 
Before:
After:
=> Included atomic element specific css modifier

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/breadcrumbs.html, cfgov/jinja2/v1/_layouts/content-base-main-first.html, cfgov/jinja2/v1/_layouts/content-base-sidebar-first.html, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/jinja2/v1/document-detail/index.html, cfgov/jinja2/v1/learn-page/index.html, cfgov/v1/models/base.py, cfgov/v1/models/browse_page.py
- For page types:
- Learn
- Document Detail
- Browse
- Browse Filterable
Breadcrumbs appear on pages below landing/sub-landing pages. (Most often this means breadcrumbs first appear on "browse" type pages with a left-side nav.)
e.g
```
Landing Page
-> Sublanding Page
(Breadcrumbs appear here!)
-> Browse Page
-> Landing Page
```
- Wagtail pages that have breadcrumbs are now handled by Wagtail
- Just go to an existing page of the type listed above.
- @kave 
- Shouldn't include any of the parent pages (e.g. Policy and Compliance)
=> Convert breadcrumb handling to Wagtail

cfgov/jinja2/v1/events/event.html
Events page without a start/end date break the template
- View an imported event page without a start/end date
- @kurtw 
=> Accounts for missing start/end dates in Events

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/expandable.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/jinja2/v1/_includes/secondary-navigation.html, cfgov/jinja2/v1/_layouts/layout-side-nav.html, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/browse_page.py, cfgov/v1/util/util.py
Changes handling of secondary navigation for Wagtail pages so they're built by the backend.
- `get_secondary_nav_items()` to the util/util.py to build the nav items
- Diverts pages using Wagtail to the backend rendering while maintaining the original generation for non-Wagtail pages
`gulp build` then:
Verify it shows on
1. Browse page with siblings but no children
- verify that the nav does not show on mobile sizes
2. Browse page with children
- verify that the nav shows on mobile sizes
3. Visit a child page
- verify that the nav shows on mobile sizes (should be the same as before but with the current page modifier)
- Browse page with siblings and children
```
Landing Page
|---> Sublanding Page
|---> Browse Page 1: (test 1)
|---> Browse Page 2 (test 2)
|---> Browse Child Page (test 3)
``` …
=> Add Wagtail secondary navigation handling

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/v1/migrations/0051_abstractfilterpage_preview_link_url.py, cfgov/v1/models/learn_page.py
Add URL field to Post Preview Organism
- URL field to Post Preview Organism
- Go to a Learn, Doc Detail, or Event page that is a child of a browse filterable page
- Add a url and text to the post preview fields for a link
- Go to it's browse filterable page and filter for it
- Check that the link exists
- @kave 
=> Add URL field to Post Preview Organism

CHANGELOG.md, cfgov/unprocessed/js/routes/browse-basic/index.js, cfgov/unprocessed/js/routes/browse-filterable/index.js, cfgov/unprocessed/js/routes/common.js
The SecondaryNav script was trying to initialize on pages the nav isn't used.
- Updated JS routes to only init on the browse and browse-filterable page types.
- `gulp build` and check the console for `Uncaught Error: o-secondary-navigation not found on or in passed DOM node.` to be removed.
- @sebworks 
=> Fixes issue where secnav tries to init a non-existant nav

cfgov/jinja2/v1/landing-page/index.html
Fixed issue where hero displayed in main content
- Conditioned off hero from the `page.head` block loop.
- view `/data-research/`if you have content data. Otherwise view any landing page w/ a hero.
- @kave 
- @sebworks 
__Before__
__After__
=> Fixed issue where duplicate hero displayed in main content

cfgov/cfgov/urls.py
In a previous pull request, I commented out the line that serves all of wagtails URL's.
This uncomments it
=> restore wagtail URL patterns

CHANGELOG.md, cfgov/jinja2/v1/_layouts/base.html, cfgov/unprocessed/css/atoms/overlay.less, cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/mobile-carousel.less, cfgov/unprocessed/js/organisms/Header.js, cfgov/unprocessed/js/organisms/MegaMenu.js, cfgov/unprocessed/js/routes/common.js
Adds atom for covering the page content with a semi-opaque overlay that's shown when the mobile mega menu is shown.
- Added overlay atom
- Added `rootExpandBegin` and `rootCollapseEnd` events to the mega menu to respond when the base level menu is opened/closed so that events can be tied to when the menu first opens and completely closes.
- `gulp build`
- Resize page to mobile size.
- Click hamburger menu, observe overlay appear and menu slide in from left.
- Click hamburger menu, observe menu slide to left and overlay disappear.
- @sebworks 
- @duelj 
- @ajbush 
- @duelj @ajbush Since the overlay is a new atom it could be added to the wiki and the mega menu. Note that the mega menu doesn't include the overlay. The overlay reference is handed to the …
=> Added overlay atom

CHANGELOG.md, cfgov/v1/migrations/0052_remove_browsepage_side_navigation.py, cfgov/v1/signals.py, cfgov/v1/views.py
#1458 introduced a bug (while it was fixing another) because it changed the way that we're routing pages in the CFGOVPage model. So now what's going on is that `unpublish` doesn't work because it looks for  the last published version of the page. This will fix that by unpublishing every version in the history of the page.
Edit: this now does the same thing for "unsharing" pages.
- Signal handler to unpublish all page versions
- Signal handler to unshare all page versions
- Unpublishing unpublishes all versions of the page, instead of just creating a latest version that is not published. same for unsharing.
- Publish a page.
- Unpublish it.
- Make sure it's not there.
- Do the same for sharing/unsharing.
- @kave 
@rosskarchner
=> Add signal receiver to handle unpublish all revisions for a page when unpublishing.

cfgov/jinja2/v1/_layouts/base.html, cfgov/unprocessed/js/ie/common.ie.js, cfgov/unprocessed/js/modules/ClearableInput.js, cfgov/unprocessed/js/modules/util/atomic-checkers.js, cfgov/unprocessed/js/molecules/Expandable.js, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/molecules/Multiselect.js, cfgov/unprocessed/js/molecules/Notification.js, cfgov/unprocessed/js/organisms/ExpandableGroup.js, gulp/tasks/scripts.js
Adding specific script for IE legacy versions which allows us to remove legacy code for scripts. 
- Adding specific script for IE legacy versions.
- Removed conditional `class-list` check from various files.
- Browse site on IE9 virtual machine.
- Wasn't sure if other scripts should be included in the legacy build.
=> Adding specific script for IE legacy versions

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
Removing Email field which was added to test Filterable Control List. 
- Add a Filterable Control to a page. You should not see the email form field on the filter.
- @kave
=> Removing Email field which was added to test Filterable Control List. 

cfgov/unprocessed/css/organisms/info-unit-group.less
Bugfix adds proper spacing between two inline info-units at all sizes
- Removes the media query wrapping the defined top margin
- `gulp build` and if you have local data visit `/policy-compliance/`, otherwise build a page w/ multiple 25/75 molecules
- @sebworks 
__Before__
__After__
- Still uses the !important that I'd like to remove, but that's outside the scope
- Still uses the !important that I'd like to remove, but that's outside the scope
- Removes the media query wrapping the defined top margin
- Still uses the !important that I'd like to remove, but that's outside the scope
=> Bugfix adds proper spacing between two inline info-units at all sizes

cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/organisms/Header.js, cfgov/unprocessed/js/organisms/MegaMenu.js
- Removes `toggle` event from FlyoutMenu.
- Adds collapse queue to FlyoutMenu so that if `collapse()` is called while expand is animating, it'll call collapse after the animation has completed.
- On refresh.demo, click Search and immediately click Mega Menu. It's possible to have both expanded at the same time, which shouldn't happen:
- Now do the same thing with this PR. It should not be possible to show both the mega menu and search expanded.
- @sebworks 
- @jimmynotjim
=> Mega Menu/Search: Remove toggle / defer collapse

CHANGELOG.md, cfgov/jinja2/v1/blog/_single.html
- Blog posts now use sheerlike template to generate the related posts.
- `./cfgov/manage.py sheer_index`
- go to `localhost:8000/blog/` and then select any blog post
- verify that the related posts section is populated
- @kave
=> Fix related posts section of a blog post page to use sheerlike method

CHANGELOG.md, cfgov/unprocessed/js/routes/budget/single.js, cfgov/unprocessed/js/routes/offices/single.js, cfgov/unprocessed/js/routes/sub-pages/single.js
The secondary nav was not being initialized on some non-wagtail pages. This adds initialization scripts for those routes.
- Added js init scripts for non-wagtail pages at `/offices/`, `/sub-pages/`, and `/budget/` routes.
- `gulp build`
- visit `/offices/`, `/sub-pages/`, and `/budget/` URLs
- resize to mobile
- navigate section using the "In This Section" secondary nav.
- @sebworks 
- @kurtw 
- @schaferjh
=> Bugfix: added js init scripts for old pages.

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/global-search.html, cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/css/organisms/mega-menu.less, cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/modules/util/data-hook.js, cfgov/unprocessed/js/modules/util/standard-type.js, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/organisms/MegaMenu.js
Major structural update to the mega menu to accommodate the 3rd-level menu. 
- Added `data-hook.js` JS utility class for working with `data-*` attributes on DOM.
- Flyoutmenu behavior is added through a JS hook on the dom, so that it can do it's own lookups for the flyout menu trigger and content.
- Menu is made to be recursive, so that the content and underlying data structure of the first-level menu matches the second and third level.
- Featured Menu Content data is moved to its own variable so that an empty string wouldn't need to be delivered for the vast majority of menu items.
- Renamed the menu title, "overview" instead to follow how we talk about it.
- When the user is on a particular page, they will find that the associated link in the menu is not clickable.
- Weight change on …
=> Mega structure update of mega menu - initial 3rd level

cfgov/unprocessed/js/modules/util/assign.js, cfgov/unprocessed/js/modules/util/breakpoint-state.js, gulp/config.js, gulp/tasks/scripts.js
- Fixes errors in `gulp lint:build`
- `gulp lint:build` should show 0 errors and 2 TODO warnings.
- @sebworks 
- @jimmynotjim
=> Minor linter build file cleanup

CHANGELOG.md, cfgov/v1/forms.py, cfgov/v1/models/base.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/learn_page.py
Makes sure the right pages are served by adding a query method to get a set of pages according to their status and hostname.
- New manager
These should work. Look at the comments and change the command as needed.
```
./cfgov/manage shell
from v1.models import CFGOVPage, AbstractFilterPage
CFGOVPage.objects.shared() # should return shared pages
CFGOVPage.objects.live_shared('content.localhost') #should return shared or live pages 
pages = AbstractFilterPage.objects.live_shared('content.localhost')
```
- @kave 
=> Add new manager to deal with shared vs live appropriately

cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html
Weird happenings when `is_round` returns a boolean and the Jinja equality check fails. This fixes that by coercing to a string. 
- Modified `cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html` to fix boolean comparison issue. 
- Add a `sidebar breakbout` and toggle the `round` property. Preview. Check the width of the breakout image.
- @kave
=> Fix for boolean equality check - DFJR-933

cfgov/v1/processors/eventpage.py
There were some dates in the event processor that weren't being handled properly. This fixes that.
- Correctly handle date for live stream and date_published
- `./cfgov/manage.py sheer_index`
- `./cfgov/manage.py import-data events eventpage --parent events -u user -p pass`
- @kave
=> Fixes importing of date field for events

.env_SAMPLE, CHANGELOG.md, cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py, cfgov/scripts/archive_events.py, cfgov/v1/models/__init__.py
- enabled demo_page use in flapjack
- Fixed archive_events script to run in production
- Set `Debug=False` and verify you cannot create the `DemoPage`
- *Note* run server in insecure mode after a `collectstatic`
- `./cfgov/manage.py runserver --insecure`
- Set environment variable `export DEMO_PAGE=True` and verify you can create the `DemoPage`
- @kurtw 
…emo_page in flapjack
=> Fixed archive_events script & Created DemoPage availability flag

cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/v1/migrations/0055_auto_20160224_2201.py, cfgov/v1/models/sublanding_page.py
The text intro block was never being accessed in the template. Also, the sidebar-breakout organism template needs the context supplied to it. This fixes the issue by changing up the template quite a bit and moving the text introduction to only be located in the content streamfield. It does a data migration so nothing is lost.
- supplies context to call to sidebar-breakout
- conditional wrapping the blocks of a header
- text introduction from header streamfield on sublanding page
- Make or go to a sublanding page and create a text introduction in the header streamfield
- run `./cfgov/manage.py migrate`
- Return to the sublanding page and see if the text intro has moved to the content streamfield and that text intro has been removed from the header streamfield
- Go to the page and verify …
=> Fixes the Sublanding pages Text Introduction rendering bug

CHANGELOG.md, cfgov/cfgov/urls.py, cfgov/v1/util/password_policy.py, cfgov/v1/views.py
- Include Password Complexity to Admin Creation Flow
- Login as an admin user and navigate to the `Users` menu
- Create a new User
- Edit an old User and change their password
- @kurtw 
=> Include Password Complexity to Admin Creation Flow

CHANGELOG.md, cfgov/unprocessed/js/modules/form-validation.js
Limited the old form validation to email signups to avoid clashing with the filterable list controls
- Targets `#email-subscribe-form` instead of all forms
- `gulp build` and test email signups in both sidebars and pre-footers throughout the project
- @sebworks 
- This should be combined w/ the validation in filterable controls post launch.
=> Limited the old form validation to email signups

test/browser_tests/shared_objects/header.js, test/browser_tests/spec_suites/header.js
This fixes the browser tests for the header. Nothing was broken, but the refactoring made our selectors out of date.
- run `gulp test:acceptance --sauce=false`
- @sebworks 
A few of the selectors were out of date with recent refactoring. This
makes our test suite nice and green again. How sweet.
=> Fix the header tests

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/v1/forms.py, cfgov/v1/migrations/0056_auto_20160304_1651.py, cfgov/v1/models/learn_page.py
- Renamed preview_link_url/text => secondary_link_url/text
- Load refresh data locally and navigate to `http://content.localhost:8000/policy-compliance/amicus/briefs`
- Verify clicking a post title reroutes to their home page
- *Note* Don't forget to edit you wagtail sites to relate to your localhost
- @kurtw 
=> Post preview title now links to page link.

CHANGELOG.md, cfgov/unprocessed/css/cf-enhancements.less
Fixes an issue in the Menu Search Input
- Matches the input font-size and padding to the button
- Updates inputs to use the webfont
- `gulp build` and click the "Search" link in the nav. The input and button should be the same height and align.
- @sebworks 
=> Fixes an issue in the Menu Search Input

CHANGELOG.md, cfgov/cfgov/urls.py, cfgov/jinja2/v1/careers/_single.html
- Fixed urls document type for career pages
- run `./cfgov/manage.py sheer_index`
- navigate to  `/careers/` url
- Click on an career link on the `Newest Openings` sections.
- @kurtw 
=> Careers Pages now render correctly

cfgov/jinja2/v1/_includes/templates/upcoming-events.html
Rather than including a feed of the events, we're just including a button per @schaferjh's instructions.
- Visit localhost:8000/newsroom/press-resources/
- @sebworks 
- @jimmynotjim
=> Add a link to event page

cfgov/unprocessed/js/modules/util/data-hook.js, cfgov/unprocessed/js/modules/util/dom-traverse.js, cfgov/unprocessed/js/routes/common.js
- Removes unneeded classlist polyfill that is covered by the IE9 polyfill.
- Moves code comment above correct line it refers to in common.js
- Updates `attr` variables to `value` to more accurately reflect what it represents.
- Fixes TODO in data-hook.js `contains` method.
- Fixes issue in data-hook.js where if an element didn't already have a `data-js-hook` value, it would get one with a value of `null`.
- You can try this on any element and check the page source, such as the overlay in Header.js:
```
var dataHook = require( '../modules/util/data-hook.js' );
dataHook.add( _overlay, 'test' );
dataHook.remove( _overlay, 'test' );
console.log( dataHook.contains( _overlay, 'test' ) );
```
- @sebworks 
- When removing all the values from  `data-js-hook`, the …
=> Data-hook fixes + Minor cleanup

CHANGELOG.md, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/organisms/header.less
Positioning fixes to stop Search trigger and form from stacking while transitioning
- Adds absolute positioning to search form and a set width in the organism
- Removes z-index from search button (form should sit on top of the button).
- `gulp build` and test the menu in the header
- @sebworks
=> Positioning fixes for search

cfgov/jinja2/v1/_includes/macros/activity-snippets.html
Something happened to the limiting on Activity Feed. This fixes it with a break in the loop.
- Visit `/about-us/` or `/careers/` and make sure it's only showing 5 posts
- @sebworks
=> Fixed Activity Feed to properly limit posts

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/global-search.html, cfgov/unprocessed/css/misc.less, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/modules/transition/AlphaTransition.js, cfgov/unprocessed/js/modules/transition/BaseTransition.js, cfgov/unprocessed/js/modules/transition/MoveTransition.js, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/organisms/MegaMenu.js
Updates Global Search animation to use separate transition module, which eventually the mega menu will use also.
- Added utility classes for translation and opacity CSS transitions.
- Updates flyout menu to support transition utilities.
- Global search and mega menu should work the same as on refresh.demo.
- @sebworks 
- The flyout menu can either use no transition, in which case `expandBegin` and `expandEnd` are called subsequent to each other, or a transition can be added, in which case `expandEnd` is called after the `transitionEnd` event fires. The same architecture is present for the collapse methods. A different transition instance can be used for the expand and collapse, if, for example, a menu should move into view when opened, but fade out of …
=> Header: Adds transition utilities

CHANGELOG.md, cfgov/v1/wagtail_hooks.py
The wagtail_hooks.py file deletes the latest revision and creates a new one. It's not known why a new revision would lose the tag references, but modifying the latest instead of deleting it and creating a new one seems like a better choice anyway.
- sharing a page now modifies the wagtail created revision instead of deleting it and creating a new one
- Create, save, share, publish a page with tags.
- Verify that the tags are saved at each step.
- @kave
=> Fix sharing bug that would prevent the display of tags

cfgov/cfgov/settings/base.py
Explicitly calls out that we are using the default Django password hashing configuration
(this is useful for our security documentation)
=> use the django default password hashing

cfgov/jinja2/v1/_includes/organisms/secondary-navigation.html, cfgov/v1/forms.py, cfgov/v1/migrations/0058_auto_20160309_1813.py, cfgov/v1/models/base.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/browse_page.py, cfgov/v1/models/learn_page.py, cfgov/v1/util/util.py
The order field was unnecessary because Wagtail handles ordering itself!
- functions to retrieve appropriate siblings/children
- nav order field on browse type pages
- click the button to use the Wagtail ordering (pic below)
- order them hold you want by drag/drop
- look at a browse type page's secondary nav to see the appropriate order
- @kave 
=> Remove order field and let wagtail handle the ordering of pages

cfgov/v1/models/browse_filterable_page.py
@kurtw 
Accidentally deleted  your changes to the browse filterable `get_page_set` function. 
I've reverted and included changes to maintain the order by published date functionality now that `CFGOVPage` pages are used to get the status appropriate set.
=> resolved merge conflict override

cfgov/jinja2/v1/_includes/macros/category-icon.html, cfgov/jinja2/v1/_includes/molecules/related-posts.html, cfgov/sheerlike/query.py, cfgov/sheerlike/templates.py, cfgov/v1/models/base.py, cfgov/v1/models/learn_page.py
The related posts molecule retrieves Events, Blog posts, and Newsroom items. The last two of which are in the elasticsearch index. This incorporates their retrieval into the set of pages that are retrieved for the molecule.
- Custom manager for EventPage
- Logic to retrieve elasticsearch data for related-posts
- sheerlike query now has __getitem__ and __len__ methods
- molecule/related-posts.html is changed up a bit in response to this sheer data incorporation
- Go to/make a page with tags and a related post organism in the sidebar/footer
- Save/share/publish then visit the page to see if the related posts show
- @kave 
=> Incorporate sheer pages into a Wagtail served related posts organism

CHANGELOG.md, cfgov/jinja2/v1/careers/_single.html, cfgov/unprocessed/css/cf-theme-overrides.less
Changes to the job template page to make them match the wireframes at [ghe]/flapjack/careers/issues/5#issuecomment-70755
- Changed the page to one similar to the landing page
- Added sidebar widgets similar to the ones in the prefooter of other career pages
- Changed the blocks at the end to border each application process.
- Visit any of the job pages. "Reporting Analyst" is a good example of one with two ways to apply.
- @sebworks 
- @jimmynotjim
=> Job template page changes

cfgov/jinja2/v1/about-us/index.html
Since we don't have the Consumer Guides section, this just removes the link
- Visit http://localhost:8000/about-us/
- @schaferjh
=> Removed potential link to consumer guides section

CHANGELOG.md, cfgov/unprocessed/js/modules/external-site-redirect.js, test/unit_tests/modules/external-site-redirect-spec.js
Fixes/Test for External Site Redirect
- Added Unit test for External Site Redirect.
- Removed the need for jQuery.
- Changed the regex to fix an issue where it wasn't catching query-string params. 
- `Visit http://localhost:8000/` and click links in the footer. All non gov links should be redirected.
- This assumes there is only one level nested spans within an anchor element. 
- The redirect test is very expensive to run on every click. In a beautiful world this wouldn't exist.
=> Fixes/Test for External Site Redirect

cfgov/jinja2/v1/the-bureau/bureau-structure/_footer.html, cfgov/jinja2/v1/the-bureau/bureau-structure/_legend.html, cfgov/jinja2/v1/the-bureau/bureau-structure/_macro-branches.html, cfgov/jinja2/v1/the-bureau/bureau-structure/_macro-content-slider.html, cfgov/jinja2/v1/the-bureau/bureau-structure/_macro-node.html, cfgov/jinja2/v1/the-bureau/bureau-structure/_macro-role.html, cfgov/jinja2/v1/the-bureau/bureau-structure/_vars-division-data.html, cfgov/jinja2/v1/the-bureau/bureau-structure/_vars-office-data.html, cfgov/jinja2/v1/the-bureau/bureau-structure/index.html, cfgov/unprocessed/css/pages/bureau-structure.less, cfgov/unprocessed/css/pages/business.less, cfgov/unprocessed/js/modules/MobileCarousel.js, cfgov/unprocessed/js/routes/the-bureau/bureau-structure/index.js
Updating the Bureau Structure to match the new design
- Added Jinja, CSS, and JS to update the Bureau Structure to match the new design.
- Removed some legacy code related to IE8
- Visit `http://localhost:8000/the-bureau/bureau-structure/`.
- 
- There is a lot of css which hopefully can be reduced. 
- Ask for Gods forgiveness for writing jQuery.
=> Updating the Bureau Structure

CHANGELOG.md, cfgov/unprocessed/css/misc.less, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/organisms/header.less
Updates the global search for no-js and IE 8-10 fixes (Part 1 of Jira issue 816)
- Removes need for pointer events
- Sets up JS only styles instead of search styles globally scoped to js
- Reduces search styles for simplicity
- Updates drop-shadow after utility for simplified search styles
- `gulp build` and test the search at multiple browser styles, with JS on and off, it should look and function the same as before.
- @sebworks 
- I'm hiding the search altogether if JS is off for smaller screens because it's unusable otherwise
=> Updates the global search for no-js and IE 8-10 fixes

cfgov/unprocessed/css/misc.less, cfgov/unprocessed/css/pages/sub-pages.less
Any link with pdf, doc, docx, xls, xlsx, or zip will get the icon. Fixes #1390 
- Adds a download icon to certain links
- http://localhost:8000/blog/struggling-to-keep-up-with-student-loan-repayment-2/
- http://localhost:8000/sub-pages/privacy-impact-assessments-pias/
- @sebworks 
- @jimmynotjim
=> Adds icon to download icons

cfgov/scripts/archive_events.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/util/filterable_context.py, cfgov/v1/util/util.py
- Checking for class instances of Browse & BrowseFilterable Pages for Side Navigation
- Fixed events pages so it only renders non-archived events
- load latest refresh DB
- visit `http://content.localhost:8000/about-us/events2/`
- @kurtw 
=> Side Navigation now pulling in Archive Event Page correctly

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, cfgov/es_mappings/report.json, cfgov/jinja2/v1/_queries/reports.json, cfgov/processors/wordpress_cfpb_report.py, cfgov/scripts/report_slugs.py, cfgov/sheerlike/query.py
There are pages created in wagtail that have wordpress counterparts. Many of these pages have slightly different slugs and all of them are located under a different root path. This adds a django script to change the slugs on the wagtail pages to their counterparts' and adds a rule to redirect from the original path to the new one.
- Redirect path
- Script to change report slugs
- report mapping for elasticsearch
- sheer processor for report
- Change the sheerlike.query module to only use the get request when specifically told to do so.
- use a refresh db dump
- run `./cfgov/manage.py sheer_index`
- go to `http://content.localhost:8000/data-research/research-reports/using-publicly-available-information-proxy-unidentified-race-and-ethnicity/` and check the slug
- this slug should be …
=> Fix report slugs

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/css/organisms/mega-menu.less, cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/modules/Tree.js, cfgov/unprocessed/js/modules/transition/AlphaTransition.js, cfgov/unprocessed/js/modules/transition/BaseTransition.js, cfgov/unprocessed/js/modules/transition/MoveTransition.js, cfgov/unprocessed/js/organisms/MegaMenu.js, cfgov/unprocessed/js/organisms/MegaMenuDesktop.js, cfgov/unprocessed/js/organisms/MegaMenuMobile.js
- Added Tree and tree traversal algorithms (includes https://github.com/cfpb/cfgov-refresh/pull/1542, with code review revisions.)
- Added all launch-state mega menu links.
- Added hover-to-show behavior in desktop mega menu. Fixes DFJR 821.
- Renames transition `flush` method to `remove` and makes it so it removes all transition classes (including the base transition class).
- Adds mouseover the trigger event to the flyout menu.
- Adds `isAnimating` method to the flyout menu.
- `gulp build`
- Hovery hover and clickety click on the mege menu items at desktop sizes.
- Resize to mobile, repeat.
- Resize to desktop, repeat.
- Clickety click the search too.
- @sebworks 
- Includes https://github.com/cfpb/cfgov-refresh/pull/1542, with code review revisions.
- …
=> Mega Menu: DFJR-821 Adds full menu/desktop hover state

cfgov/jinja2/v1/_includes/molecules/contact-phone.html, cfgov/jinja2/v1/_includes/organisms/sidebar-contact-info.html
Fix for sidebar contact info
- Removed map from `sidebar-contact-info.html`. 
- Changed order of blocks in `sidebar-contact-info.html`.
- Visit `http://localhost:8000/office-civil-rights/no-fear-act/`.
- @kave
=> Fix for sidebar contact info

cfgov/jinja2/v1/_includes/macros/category-slug.html, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/_includes/posts-paginated.html
- Included a new flag to handle category slug creation for sheer page filtering
- Fixed links in Post Preview elements so they filter on the page correctly
- Import refresh db
- visit `http://localhost:8000/newsroom/` and click on a category
- visit `http://content.localhost:8000/policy-compliance/enforcement/actions/` and click on categories or tags to see page filter correctly:
- @kurtw 
=> fixed category filtering on sheer pages

cfgov/v1/models/learn_page.py, cfgov/v1/util/filterable_context.py
A new manager for the pages was necessary to get the `date_published` from the queryset. For whatever reason, even though the objects within the queryset had `date_published` the queryset itself was not filterable on that field. Go figure. 
@richaagarwal 
@kave
=> Fix filterable list page set retrieval

cfgov/jinja2/v1/_includes/macros/time.html, cfgov/jinja2/v1/_includes/macros/util/format/datetime.html, cfgov/sheerlike/__init__.py, cfgov/sheerlike/templates.py, cfgov/sheerlike/test_templates.py, cfgov/v1/forms.py
Dates were being output with the UTC timezone instead of the appropriate timezone (mainly Eastern). This fixes the functions that are used to convert the given timestamps into the correct timezones.
- helper function for DRYness
- The functions now use the same logic but return different types and their names reflect that (str vs date obj)
- Sheerlike tests for the templates are now being run 
- Run `tox`
- Check out a list page with dates. Really any date being outputted on the site.
- Check out a browsefilterablepage and filter using dates. That should also work.
- @kave 
- The other sheerlike tests need to be updated too, but that's out of scope for this PR
- Maybe more tests. See if we have time later or post launch
=> Fix sheerlike date functions bug for timezones

cfgov/jinja2/v1/_includes/organisms/post-preview.html
Fixed issue where links were not appearing and where subheading weren't
appearing.
- If you have the db dump, test on the Policy and Compliance Open Notice pages for the link. There isn't a good place to test subheading unfortunately.
- Otherwise create a learn page under a browse-filterable page and be sure to fill out all the post-preview settings. It's under `Configuration` tab >> `Page Preview Settings` expandable
- @kurtw 
- @sebworks 
=> Fixed two issues with post preview

CHANGELOG.md, cfgov/scripts/move_reports.py
Move all the reports under the browse filterable page `Research and reports` (http://localhost:8000/admin/pages/159/edit/) to the new sublanding filterable page they will be creating.
- Add a script `move_reports.py` to move all reports under a given SublandingFilterablePage
- Create a SublandingFilterablePage locally, name it whatever you want. e.g. Placeholder
- python cfgov/manage.py runscript move_reports --script-args=Placeholder
- (Replace Placeholder above with whatever you named it, if you didn't name it Placeholder :) )
- @kave @kurtw 
- Jira task mentioned several implementation details, one of which was "Creation of a script to take a list of id's as a parameter and move them to a destination id." That seems a bit burdensome in this case for the user, so I'm not going to do …
=> Script to move reports to a given page

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/organisms/MegaMenuDesktop.js
- Updates incorrect URL and replaces `and` with `&` in menu item text.
- Adds method to suspend/resume trigger events on a flyout menu.
- Suspends trigger events on the 3rd-level trigger at the desktop menu size so that the triggers (e.g. About Us > Careers) won't prevent the default link behavior.
- On refresh clicking About Us > Careers just closes the mega menu. Run `gulp build` and see that going from About Us > Careers goes to the careers overview page.
- @sebworks
=> Mega Menu: Suspend 3rd level menu at desktop

cfgov/jinja2/v1/_includes/macros/category-icon.html, cfgov/jinja2/v1/_includes/macros/category-slug.html
A couple of spacing issues were causing icons to not appear.
- Visit `/blog/` and `/newsroom/` and marvel at how the icons.
- @sebworks
=> Fixed spacing with category icon classes

cfgov/unprocessed/css/molecules/global-eyebrow.less
Quick fix to the global eyebrow on mobile. There's a line between the items and the eyebrow that was removed in #1586, this adds it back.
- `gulp build` and check on mobile. Compare it to Flapjack.
=> Adding back line between mobile eyebrow and items

cfgov/cfgov/settings/base.py, cfgov/es_mappings/newsroom.json, cfgov/es_mappings/posts.json, cfgov/jinja2/v1/_includes/templates/streamfield-sidefoot.html, cfgov/jinja2/v1/_queries/careers.json, cfgov/jinja2/v1/_queries/just_newsroom.json, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/jinja2/v1/document-detail/index.html, cfgov/jinja2/v1/landing-page/index.html, cfgov/jinja2/v1/learn-page/index.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/scripts/update_es_settings.py, cfgov/sheerlike/query.py, cfgov/v1/models/base.py
Phew. This one was a bit of a doozy. This does a few things but is all related to getting this related posts mechanism working once and for all. Basically, it's adding a script to update the ES index with new settings (something we didn't have) then updating the tags field in the mapping so we can perform lowercase searches for content while still maintain the original case in places like the filters, then it adds a new search method on the Query class in sheerlike to actually get the posts by the lowercase tag.
Then another commit updates the templates to actually render things properly, adding a generic streamfield template.
- New script to update es settings
- New method to find documents based on tags
- New newsroom query
- New analyzer for tags
- Template for generic rendering of …
=> Fix related posts

cfgov/jinja2/v1/the-bureau/bureau-structure/_vars-office-data.html
> Move Ombudsman out from under Deputy Director, to below the Administrative Law Judge. Deputy Director box will no longer have an expandable. Ombudsman box should look similar to Administrative law judge. 
- Breaks out ombudsman into its own node.
- Visit http://localhost:8000/the-bureau/bureau-structure/
- @sebworks 
=> Add Ombudsman as its own node in /bureau-structure/

CHANGELOG.md, cfgov/v1/wagtail_hooks.py
- registered cfgov link handler for rich text fields.
- This strips the hostname from internal links allowing them to be relative.
- refactored atomic element templates to not use `.source` attribute of rich text fields as this renders links & embedded data incorrectly and therefore doesn't allow full use of editor features.
- Create a `DemoPage` and create a text introduction.
- In the `Intro` field create an internal link and share it. Visit shared page and verify link has `content.localhost` associated with it
- Publish created page. Visit published page url and verify link has `localhost` associated with it
- @kurtw 
=> Rich text Internal links

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html
This PR adds a "#" link as a way to remove the blank href on the first
two subnav items. Anchor links without a href are not keyboard
navigable.
This is the method being used by 18F
https://github.com/18F/web-design-standards/issues/743
- Adds "#" and a check to make sure links to "#" don't link to non-existent overview pages.
- Using your keyboard, navigate to the first an item in the Consumer Resources section. [Quick guide here.](https://github.com/cfpb/front-end/blob/master/accessibility.md#keyboard-testing)
- @sebworks 
- @jimmynotjim
=> Add Tabbing to Consumer Resources + Education Navs

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/css/cf-enhancements.less, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/css/organisms/mega-menu.less, cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/modules/Tree.js, cfgov/unprocessed/js/organisms/MegaMenu.js, cfgov/unprocessed/js/organisms/MegaMenuDesktop.js, cfgov/unprocessed/js/organisms/MegaMenuMobile.js
- Adds `u-hidden-overflow` utility class.
- Adds behaviors for third-level mega menu.
- `gulp build` and then these are the possible states:
- **First-level:**
- Expand menu > Collapse menu with (x).
- Expand menu > Collapse menu by clicking body overlay.
- Expand menu > Collapse menu by clicking search button.
- **Second-level:**
- Expand menu > Click about us > Collapse menu by clicking (x).
- Expand menu > Click about us > Collapse menu by clicking body overlay.
- Expand menu > Click about us > Collapse menu by clicking search button.
- Expand menu > Click about us > Return to first-level by clicking back button.
- Repeat first-level steps.
- **Third-level:**
- Expand menu > Click about us > Click careers > Collapse menu by clicking (x).
- Expand menu > Click about us > Click careers > …
=> Mega Menu: DFJR-817 - Added behaviors for third level at mobile

CHANGELOG.md, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/jinja2/v1/wagtail/demo/index.html
From Jira: "When there's no content entered in the sidefoot area in Wagtail on a browse or browse filterable template, a small empty pre-footer well shows on page."
- Wrap the code that renders the prefooter in a conditional so it only displays if there is content in the sidefoot.
- 
- Replaced redundant code with a call to macro in `demo/index.html`
- Create or go to a Browse / Browse filterable page and remove the sidefoot content. Ensure there's no empty prefooter. 
- @kave @kurtw 
Before fix:
After fix:
=> Fix empty prefooter

CHANGELOG.md, test/browser_tests/page_objects/page_activity-log.js, test/browser_tests/page_objects/page_bureau-structure.js, test/browser_tests/page_objects/page_leadership-calendar.js, test/browser_tests/shared_objects/filter.js, test/browser_tests/spec_suites/bureau-structure.js
Fixing failing acceptance tests
- Removed Director image test, the image no longer exists.
- Removed the Director name/title tests, they are weak tests and we can circle back to these when we refactor these tests.
- Updated the Expandables tests to the atomic naming.
- run `gulp test:acceptance:browser --sauce=false`
- @sebworks 
- @kurtw 
- @kave 
- Refactor these tests, preferably as soon as we can after launch (if not before).
=> Fixing failing acceptance tests

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/css/organisms/mega-menu.less
- Temporarily removes and disables links in Consumer Tools and Educational Resources.
- `gulp build`
- Check menu at desktop and mobile. Consumer Tools and Educational Resources links should all be disabled styled.
- @jimmynotjim
- @sebworks
-@kimberlymunoz
=> Mega Menu: Fixes DFJR-1045 - disables links for non-functional areas of menu

CHANGELOG.md, cfgov/unprocessed/js/molecules/Multiselect.js
Fixed a bug in IE where value wasn't being correctly set
- Updated the order of options when creating an `input` to set the `type` before the `value`
- `gulp build` and check out `/blog` in an IE VM
- @sebworks 
- When creating input elements, the type must be set before a value can be set. This issue exists in all versions of IE
=> Fixed a bug in IE where value wasn't being correctly set

CHANGELOG.md, cfgov/unprocessed/css/molecules/global-search.less
Fixes a bug where the global search was bing transformed twice delaying the animation
- Removed duplicate transform in the styles.
- `gulp build` and click the search icon on a small screen. It shouldn't delay like it is on the demo server.
- @sebworks 
=> Fixes a bug with the global search positioning

cfgov/unprocessed/js/molecules/Multiselect.js
This fixes a tabbing issue with the multiselect and a missing id for
labels.
- Keyboard test the `/blog/` page. You should be able to navigate past the multiselects now and use the down arrow to select your options.
- Test the id by using a screenreader or an a11y checker like tota11y
- @sebworks 
- There's some enhancements in #1350 that _are not_ in this PR. This is all hotfixes.
=> Accessibility Fixes for Multiselect

cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/modules/transition/BaseTransition.js
- When no transition event is present `transitionEnd` was dispatched twice. This fixes that.
- Move public static constants outside constructor.
- Fix order of addEventListener on transition in FlyoutMenu when there is no transition support.
- `gulp build` and look at dev console in IE9. There should be no js script error. 
- @jimmynotjim
=> FlyoutMenu: No transition support fixes

cfgov/sheerlike/templates.py
Basically, timezones are saved as UTC which is usually the best idea but when converting to EST is a problem because data entry is in EST not UTC. This strips the UTC and replaces it with the desired timezone (usually EST) instead of converting from UTC.
@richaagarwal 
@kave
=> Datetimes now render with their entered times with the desired timezone

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/email-signup.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/unprocessed/js/modules/util/breakpoint-state.js, cfgov/unprocessed/js/molecules/Expandable.js
Expandables will collapse when page is loaded under 600px width, or if it is resized below 600px. If resized and collapsed, it won't remember that it was expanded at desktop sizes and won't expand when resizing back to desktop.
- Makes Expandables collapse under 600px window size.
- General code comment cleanup.
- Removes `addEventListener` check since IE8 is no-js state now.
- `gulp build`
- Create a browse filterable page in wagtail and add a filter.
- Check "Is Expanded" in wagtail admin.
- Load the page preview in a small window, note filter is collapsed.
- Load the page preview in a large window, note filter is expanded.
- Resize the page to a small size and note filter collapses.
- @kurtw 
- @sebworks 
- @kurtw Can we add a note next to the "Is …
=> DFJR 971 - Collapses expandable on mobile

cfgov/jinja2/v1/_includes/macros/filters.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
Fix for form reset button not submitting form field values.
- Changed the form reset button to be a link
- Visit the blog page and enter some criteria in the filter. Click on the apply filters link. After the page loads click on the reset link.
- Create a Filterable Control List and repeat the steps as above.
=> Fix for form reset button

CHANGELOG.md, cfgov/jinja2/v1/_includes/macros/category-icon.html
Categories without a set icon should not show any icon
- Added a condition to the category icon macro to avoid including any icon or the markup with the category doesn't have a matching icon
- If you have CMS data, navigate to `/policy-compliance/amicus/briefs/` and ensure the categories aren't showing the speech bubble icon
- @sebworks
=> Conditioned off the category icons

CHANGELOG.md, cfgov/unprocessed/js/molecules/Multiselect.js
After submitting the form, the page would load with the selected options, but the multiselect didn't display those options
- Added a 'defaultSelected' lookup to set the 'checked' state of inputs
- Added a 'checked' state lookup when creating the `_selected` array
- Added the items to the choices list that exist in the `_selected` array
- Use the multiselect on `/blog` on the demo server and make a selection in the multiselect. Notice that the selected options aren't persistent on form submission, but the params are correctly set in the url query. 
- Pull the branch locally and `gulp build`. Visit `/blog` and again make a selection in the multiselect. Choices should be persistent after form submission. Should also work on `/policy-compliance/amicus/briefs/` if you have CMS data locally.
- …
=> Bugfix for selected options in multiselect on form submission

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/css/organisms/mega-menu.less
Updates the mega-menu for no-js and IE 8-10 fixes (Part 2 of Jira issue 816)
- Removes need for pointer events
- Sets up JS only styles instead of menu styles globally scoped to js
- `gulp build` and test the menu at multiple browser styles, with JS on and off, it should look and function the same as before.
- @sebworks 
- We've decided to show the top level items as links by default on small screens when JS fails to deliver.
- ~~There are script errors from the BaseTransitions files in IE9. I'm having trouble debugging them, but we should discuss if transitions should even be supported in such an old browser. Progressively enhancing a simple toggle of show/hide is probably more appropriate than trying to add complicated scripting that the browser …
=> Updates the mega-menu for no-js and IE8-10 fixes **SEE NOTES**

cfgov/jinja2/v1/events/event.html
- removed erroneous Event buttons and added todo to resolve download button and verify reservation email at a future date
- Load Refresh Db
-  visit [here](http://content.localhost:8000/about-us/events/spring-2016-credit-union-advisory-council-meeting-washington-dc/) to verify download and reservation buttons do not render
- @kurtw 
before:
after:
=> Removed Event download & reserve buttons

CHANGELOG.md, test/browser_tests/spec_suites/bureau-structure.js, test/browser_tests/spec_suites/header.js
Removed JS trigger tests because they're failing on IE8
- Temp disabled the test that checks that the expandables are closed. They're open by default if the JS isn't triggered, like on IE8
- Make sure your Sauce Tunnel is open and your .env config is set up for testing
- run `gulp test:acceptance --sauce=true --browserName="internet explorer" --version=8.0`
- @sebworks 
- We need to figure out how to keep IE 8 from running any tests that depend on triggered JS when we refactor these.
-
=> Removed JS trigger tests because they're failing on IE8

cfgov/cfgov/urls.py, cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Per most recent URL tracker document from @schaferjh, complaint database will be at /data-research/consumer-complaints/
This moves it there.
- only edits urls.py
- install the CCDB4/CCDB-content app, start cfgov/manage.py runserver
- browse to /data-research/consumer-complaints/ and admire
- brose to /complaintdatabase and admire the 404
- @richaagarwal @kave @kurtw @schaferjh
=> change URL pattern for complaint database

CHANGELOG.md, cfgov/unprocessed/js/modules/util/dom-manipulators.js, cfgov/unprocessed/js/modules/util/dom-traverse.js, cfgov/unprocessed/js/molecules/Multiselect.js, test/unit_tests/modules/util/dom-manipulators-spec.js, test/unit_tests/modules/util/dom-traverse-spec.js
Abstracted create and queryOne out of the multiselect
- Creates elem creation helper for standardizing elem creation
- Adds option for creating an elem inside another (including in memory, reducing dom changes)
- Adds option for creating an elem around another
- Creates elem query helper for standardizing elem search (necessary for appending elems to others in memory)
- Adds tests for both of these
- Updated the multiselect to use the abstracted helpers
- `gulp build` and test the multiselect, shouldn't be any changes
- `gulp test:unit:scripts` and open `./test/unit_test_coverage/lcov-report/modules/util/index.html` to view the stats on both of these specs
- @sebworks 
__Before__
```
=============================== Coverage summary …
```
=> Abstracted create and queryOne out of the multiselect

cfgov/jinja2/v1/_includes/macros/video-player.html, cfgov/jinja2/v1/_includes/molecules/featured-content.html
Fix so close and share buttons don't hover over the video.
- Add the `featured-content-module_visual` class to the video player instead of around it so that the `left` attribute can be overwritten when the video is playing
- Visit http://localhost:8000/the-bureau/
- @sebworks 
- @jimmynotjim
=> Fix the way the fcm video expands

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/v1/models/browse_filterable_page.py
Adding a fix for determining when active the filters are active. This replaces using `request.GET` which will be populated with values during pagination.
- Added a method to `browse_filterable_page.py` which can be called from Jinja to determine if the filters are active.
- Visit a browse filterable page; click the next button. You shouldn't see any notification.
- Manually steps for creating a Browse Filterable Page:
- Add a Browse Filterable Page via Wagtail
- Add a `Filterable Control` to the page.
- Select `Amicus Brief` for the page type under `Categories`
- Select `Publish the page to WWW`
- Click `Add Child Page` when mousing over the page you just created.
- Click `Learn Page` and add some `General Content`. 
- Click on the `Configuration` tab and add `tags`, `authors` of your …
=> Adding Fix for Active Filter

cfgov/unprocessed/js/routes/sheer.js
Fixes issue with initializing the atomic Expandable on the Blog
- Adds code to scope the initializing of the Expandable
- Run `bulp build` and visit the `/blog`. Click on the filter; it should expand.
=> Fix for Expandables on Blog

cfgov/unprocessed/js/modules/Tree.js, test/unit_tests/modules/Tree-spec.js
- Adds tests to `Tree.js`
- Makes `getAllAtLevel` method always return an array, even if it's empty.
- `gulp test:unit:scripts` should pass.
- @sebworks 
- Not sure how to cover this if statement:
=> Adds test for Tree.js

cfgov/jinja2/v1/_includes/organisms/sidebar-contact-info.html
I noticed that there was an error printing out on the contact info section of a sidebar/footer.
@richaagarwal 
@sebworks
=> Fix printing of error for sidebar-contact-info.html

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/css/organisms/mega-menu.less
- Re-enables Consumer Tools and Education Resources links in the mega menu.
- Temporarily hides the overview links at desktop sizes for those two sections. (**Note:** they are still there—but disabled—at mobile.)
- `gulp build` and check the first two menu items.
- @sebworks 
- @schaferjh (please double-check link URLs in _vars-mega-menu.html below)
- The disabling link feature for the overview links needs to be updated because the fallback menu still only has a `#` URL for the top-level links that have disabled overview pages.
=> Re-enables consumer tools and ed resources

cfgov/unprocessed/js/routes/on-demand/secondary-navigation.js, cfgov/v1/models/base.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/browse_page.py
This adds the ability for us to instantiate page type specific js scripts just by overriding the `get_page_js()` method.
- `get_page_js()` method
- `secondary-nagivation.js` script to Browse/BrowseFilterablePage types
- `from sets import Set` because it's deprecated and replaced with the built-in `set/frozenset` type
- js file names are returned and stored in memory as lists instead of tuples because the intention of this is to update the names of files at will and tuples are supposedly immutable.
- `gulp build`
- Go to [`localhost:8000/about-us/events/`](localhost:8000/about-us/events/) and shrink window to tablet/mobile site. You should see the :heavy_plus_sign: button on the navigation and it should drop down a list of the sidenav.
- same goes for …
=> Page specific js

test/unit_tests/modules/Tree-spec.js
- Groups Tree tests by method with describe() blocks.
- `gulp test:unit:scripts` – no errors.
- @sebworks 
=> Update Tree-spec to use describe for methods

cfgov/unprocessed/js/modules/util/web-storage-proxy.js, test/unit_tests/modules/util/web-storage-proxy-spec.js
- Updates web-storage-proxy to fallback to an object literal for storage if cookies aren't available.
- Go to Preferences > Show Advanced Settings > Privacy > Content settings... > Cookies and disable them:
- Go to beta.consumerfinance.gov and open the console. Note SecurityError with web storage and beta banner does not work.
- Go to this PR and open localhost.
- Note that beta banner works, but on reload does not remember its state.
- @sebworks 
- @jimmynotjim
=> Fix: handle SecurityError around window.sessionStorage

cfgov/unprocessed/js/modules/FlyoutMenu.js
- I'm unclear on what should have aria-expanded when the triggers to show/hide some content are outside or inside the content to be shown. 
[This](https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions#Example_2:_Collapsing_and_expanding_subtrees_of_a_tree) makes it seem like it should only be on the content, while [this](http://v4-alpha.getbootstrap.com/components/collapse/#example) makes it seem like it should be on the content and the triggers.
We have this structure for flyout menus (in pseudocode):
```
.trigger
.content
.alt-trigger
```
So `.trigger` and `.content` are siblings and `.alt-trigger` is a child of `.content`.
Clicking either of the triggers toggles content.
This PR updates the FlyoutMenu to set `aria-expanded` on …
=> Flyout Menu: Adds aria-expanded on alt trigger

cfgov/sheerlike/query.py
The data retrieved from elasticsearch was not ordered by date so this fixes that by making the most recent related post first.
- Add `sort` list to the `Query.get_tag_related_documents` in sheerlike
- go to http://beta.consumerfinance.gov/about-us/operations/ and not that the orderiing is wonky
- go to http://content.localhost:8000/about-us/operations/ and note the ordering is date desc
=> Fix ordering of related posts to be date descending

cfgov/jinja2/v1/_includes/molecules/related-posts.html
In the related posts molecule, the Event dates are corresponding to the last updated date instead of the start date of the event. This fixes that by showing the date in the following priority if it exists on the post:
1. `start_dt`
2. `date_published`
3. `last_revision_created_at`
4. `date`
- More dates to try when rendering related posts
- Go to http://content.localhost:8000/policy-compliance/ and check one of the related event's date
- Go to that event's page and verify that the date before is also the start date.
- Go back to the poly com page and verify that the other related post types' dates match up still
=> Fix related posts dates

cfgov/jinja2/v1/_includes/molecules/breadcrumbs.html, cfgov/jinja2/v1/_includes/molecules/featured-content.html, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/v1/__init__.py
Live pages have the possibility of linking to pages that are not yet live, which is fine. However, what's not fine is the information that's leaked from that link. This protects that information by replacing non-live page links on the live site with `#`. It also fixes the 404 issue for Featured Content modules.
- context function that returns the protected URL
- page links should use `get_protected_url` instead of `get_page_state_url`
- Go to http://localhost:8000/data-research/research-reports/ and click on the See Full Report link on the featured content component to make sure that link is okay.
- Go to that full report's edit page and unpublish it. 
- go back to http://localhost:8000/data-research/research-reports/ and verify that the link to the full report has been replaced with a …
=> Protect URLs from potentially leaking unpublished pages

cfgov/scripts/setup_sites_prod.py
@kurtw 
@richaagarwal 
@rosskarchner 
- `./cfgov/manage.py runscript setup_sites_prod --script-args='flapjack.demo.gov'`
- verify wagtail sites have been updated to match param
=> setup sites for ec2 instances

cfgov/unprocessed/css/atoms/multi-select.less, cfgov/unprocessed/js/molecules/Multiselect.js
Previously, people who scrolled by clicking on the scrollbar would close
the multiselect search box. The blur event is a little more aggressive in IE. This
uses the blurskipped event to catch clicks on the container.
- Fix for IE Scrollbar #1712
- Fix for scrolling on IE with the multiselect.
- Visit /blog/ on Windows IE 11. Scroll to select a topic near the bottom and click anywhere on the page to dismiss the box.
- @sebworks
=> Fix focus on multiselect in IE

cfgov/unprocessed/css/molecules/full-width-text.less
- Set a max-width for full-text molecules
-  Visit `/privacy/digital-privacy-policy/` if you have the DB or just create a page with a full-width-text blob.
- @sebworks 
- @jimmynotjim
=> Set a max-width for full-text molecules

cfgov/jinja2/v1/_includes/article.html, cfgov/jinja2/v1/_includes/tags.html
The topic tag urls were using url parameters that are Wagtail page specific for every type of page. This changes up the tags.html code so that the topic tags will work for pages that are in sheer.
- New tags.html render() parameter to tell whether or not the page is a sheer page.
- Go to a blog post or a newsroom item and click on the topic tag that should now link back to the newsroom or blog landing page with a working url parameter to filter based on the tag selected.
- @kave 
=> Fix tag url for blogs and newsrooms

CHANGELOG.md, cfgov/unprocessed/css/organisms/mega-menu.less
Updated the layout for the level 1 menu items to match design
- Uses cf-grid to set each level 1 menu item as 1/5 of the header
- `gulp build` and check any page, only the level 1 items should be updated.
- @schaferjh 
- @sebworks
=> Updated the layout for the level 1 menu items to match design

CHANGELOG.md, cfgov/unprocessed/js/modules/util/dom-traverse.js, test/unit_tests/modules/util/dom-traverse-spec.js
Adding tests for dom-traverse functions
- Added tests for all the functions
- @sebworks 
- `not()` is failing unexpectedly. This needs a second set of eyes to see what I'm missing.
__Before__
```
Statements   : 27.17% ( 724/2665 )
Branches     : 22.92% ( 198/864 )
Functions    : 20.14% ( 86/427 )
Lines        : 27.33% ( 722/2642 )
================================================================================
```
__After__
```
Statements   : 27.88% ( 743/2665 )
Branches     : 23.96% ( 207/864 )
Functions    : 20.61% ( 88/427 )
Lines        : 28.01% ( 740/2642 ) …
```
=> Adding tests for dom-traverse functions

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/full-width-text.html
Removed Georgia usage for the time being
- Removed Georgia modifier from the full-width-text molecule macro.
- `gulp build` and navigate to `/plain-writing/plain-writing-act/`. It should not be Georgia.
- @schaferjh 
- @ajbush 
- @duelj 
- @sebworks 
- AJ and Justin will re-evaluate Georgia usage on the web after launch.
=> Removed Georgia usage for the time being

CHANGELOG.md, cfgov/unprocessed/js/modules/util/strings.js, cfgov/unprocessed/js/molecules/Multiselect.js, test/unit_tests/modules/util/strings-spec.js
Abstracted the string utils from the Multiselect for easier reuse and testing
- Renamed _regExpEscape to stringEscape and added tests
- Renamed _filterContains to stringMatch and added tests
- `gulp build` and navigate to `/blog` and use the filters (~~the expandable is broken, @sebworks is working on a fix, you'll need to inspect and force it open~~ it's fixed)
- @sebworks 
__Before__
```
Statements   : 29.04% ( 778/2679 )
Branches     : 24.25% ( 210/866 )
Functions    : 22.43% ( 96/428 )
Lines        : 29.19% ( 775/2655 )
================================================================================
```
__After__
``` …
```
=> Abstracted the string utils from the Multiselect for easier reuse and testing

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
- Updates menu text to `Information for Servicemembers & Veterans` from `Information for Servicemembers` 
- Link text should be updated in the menu.
- @schaferjh 
- @sebworks
=> Fix link text

cfgov/unprocessed/js/modules/FlyoutMenu.js
- Adds a `data-gtm_ignore="true"` to menu links that have their default behavior disabled so they don't actually work like links.
- `gulp build` and view the source for the desktop menu. The main links should have `data-gtm_ignore="true"` attributes set.
- @sebworks 
=> Disable GTM on menu links that don't go anywhere

cfgov/unprocessed/js/modules/FlyoutMenu.js, test/unit_tests/modules/FlyoutMenu-spec.js
- Adds unit tests for the FlyoutMenu
- Sets `_isAnimating` and `_isExpanded` before broadcasting `collapseBegin`.
- `gulp test:unit:scripts` should pass.
- Also, `gulp build` and mega menu should function the same. Hopefully moving the broadcast order hasn't affected anything!
- @sebworks 
- @jimmynotjim
=> Adds FlyoutMenu test

cfgov/jinja2/v1/about-us/index.html, test/browser_tests/spec_suites/about-us.js, test/browser_tests/spec_suites/footer.js
A bunch of fixes to the content of the about us page. Mostly changing things to sentence case.
While I was fixing a browser test, I also fixed a few broken ones in the footer.
- Visit /about-us/, half blob titles should be in sentence case now
- @sebworks 
=> About us page content fixes & browser test fixes

CHANGELOG.md, cfgov/unprocessed/js/modules/footer-button.js
- Addendum to https://github.com/cfpb/cfgov-refresh/pull/1729
- `gulp build`, resize to mobile, click back to top should still work.
- @sebworks 
- Footer code could remove jquery dependency. Dom lookups aren't needed and the animation can be covered in a function or two.
=> Disables GTM in return to top link

cfgov/v1/models/base.py
Initializing the blocks to get a Media.js attribute was more costly and error prone than just reusing the objects that contain it anyway.
- unnecessary and error prone block initialization
- Go to  http://localhost:8000/policy-compliance/amicus/briefs/ and make sure the JS is initialized properly
- Go to these to make sure they render properly:
- localhost:8000/privacy/
- localhost:8000/accessibility/
- localhost:8000/about-us/project-catalyst/
- localhost:8000/office-civil-rights/
- localhost:8000/policy-compliance/enforcement/
- @kave 
=> Fix JS bug

cfgov/jinja2/v1/_includes/related-posts.html, cfgov/v1/models/base.py
Related Posts for blog posts and newsroom items need to be sorted by date descending, and events need to be sorted by date_published descending on all pages that have a relation to them.
@kave 
@richaagarwal
=> Sheer served pages now sort related posts by date descending

cfgov/jinja2/v1/_includes/molecules/related-metadata.html, cfgov/v1/__init__.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/learn_page.py, cfgov/v1/models/sublanding_filterable_page.py
For AbstractFilterPage types, the code to get the links for the related metadata topics doesn't account for parents of the pages that are not BrowseFilterablePage or SublandingFilterablePage. This fixes that call.
- Logic to look through the ancestors of the current page for a filterable type to call the method on.
- The tag will not have a tag if none of the ancestors of the page that is in on are BrowseFilterablePage or SublandingFilterablePage.
-
- @kave 
=> Fix call to get_form_id method

cfgov/v1/forms.py, gulp/tasks/test.js
- Fixes https://github.com/cfpb/cfgov-refresh/issues/1760 with feedback from @rosskarchner 
- Exchanges running of macro unit tests via `exec` with `spawn` in hopes of making the macro unit tests more stable.
- `gulp test:unit:macro` should pass.
- `gulp test --sauce=false` (or `gulp test` shouldn't stall)
- @sebworks 
=> Fixes macro unit tests

gulp/tasks/styles.js
Fix for Android 4 `WebkitTransitionEnd` not firing due to lack of prefix.
- Added `Android 4` to the autoprefixer.
-  Run `gulp build` and inspect the dom. You should see that `o-mega-menu_content-1` is prefixed with `-webkit-transition`
-
-
=> Fix for nav not functioning on Android 4 devices

cfgov/v1/models/base.py
Expandables were not showing up correctly
- List block type blocks are now accessed correctly in page.media code
- Go [here](http://content.localhost:8000/cfpb-ombudsman/ombudsman-faqs/) and verify that expandables work right.
- @kave 
=> Fix bug in page.media code

cfgov/processors/processors_common.py, requirements/base.txt
adds lxml to requirements/base.txt, and ask for it when invoking beautifulsoup during sheer_index
- adds lxml to requirements
-
- explicitly invoke lxml when parsing blog/newsroom HTML
run sheer index under the current flapjack, and you'll notice some ugliness on blog and newsroom pages, for example on http://flapjack.demo.cfpb.gov/about-us/newsroom/cfpb-monthly-complaint-snapshot-examines-debt-collection-complaints/
checkout this code, do a `pip install -r requirements/base.txt`, and re-run sheer_index, and see the problem resolved:
- @kurtw @richaagarwal @kave @schaferjh 
… for links
to fix
=> add lxml (fix apostrophe issue)

CHANGELOG.md, cfgov/v1/migrations/0073_auto_20160331_1100.py, cfgov/v1/models/learn_page.py
Adding Validation for Youtube URLs on the Event Page.
- Modified the `EventPage` class to add validation for Youtube URLs. 
- Visit the Wagtail Admin and create an `Event Page`.  Enter `https://youtube.com/embed/zOV4R08i7b8` for the `Youtube URL`. Click `Save Draft`. You should get a validation error because `www` was ommited.
- 
- @kave 
- @kurtw 
- @tnferrell
=> Adding Validation for Youtube URL

cfgov/jinja2/v1/_includes/article.html
The links on the Category on the Newsroom item page or a Blog Post page are broken. This fixes that.
- Add the sheerpage argument to the call from the `article.html` file.
- go [here](http://localhost:8000/about-us/newsroom/cfpb-monthly-complaint-snapshot-examines-debt-collection-complaints/) and click the category link 
- @kave 
=> Fix category links on Blog posts and Newsroom items

cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/v1/models/sublanding_page.py, cfgov/v1/util/util.py
Updated FilterControls organism's `show_preview_categories` flag was broken on the front end. In fixing this, it unearthed another bug which is solved in here as well. Basically, the posts in the Post Preview Snapshot organism's tags and categories links would be broken because the form_id was never gotten from the pages that the posts existed on.
- The `get_browsefilterable_posts` now returns a tuple that is the id of the form where the post came from and the post.
- Go [here](http://content.localhost:8000/data-research/research-reports/) and see categories displayed on the post previews. Some don't have them because they don't have categories.
- Go [here](http://content.localhost:8000/policy-compliance/amicus/) and make sure that the posts have categories and that the categories and …
=> Fix filter controls and sublanding page

gulp/tasks/styles.js, package.json
- Updates autoprefixer version.
- Removes possibility of IE7-8 prefixing from non-ie stylesheet.
- `gulp build` should pass. If it doesn't you'll need to run `./frontend.sh`
- Site should still look fine on IE8.
- @sebworks 
=> Ensures IE prefixed styles aren't double-generated

cfgov/jinja2/v1/_includes/article.html, cfgov/jinja2/v1/_includes/macros/footer-global.html, cfgov/jinja2/v1/_includes/molecules/social-media.html, cfgov/jinja2/v1/about-us/careers/_single.html, cfgov/jinja2/v1/events/_event-detail.html
- social media molecule updates:
- Includes `is_share_view` in `options`.
- Makes related account `@CFPB` by default
- Trims URL so it's not padded with whitespace when handed to /external-site/.
- Share icons in the footer should not have "Share this"
- Share icons in careers, events, the bureau, and blog should have "Share this"
- Twitter share button URLs should have `&related=cfpb` in them (**note: /external-site/ seems to be stripping these**)
- @kave 
- @kurtw 
- @sebworks 
- The default title seems broken for tweets. Tagging bewds below...
=> social media sharing fixes

CHANGELOG.md, cfgov/unprocessed/css/atoms/multi-select.less, cfgov/unprocessed/js/molecules/Multiselect.js
Added a checker to the Multiselect for max selections
- Adds a max-selections class when user reaches five selections
- Removes the class once the user removes the fifth selection
- `gulp build` and navigate to `/blog` and make five selections in the Multiselect
- @schaferjh 
- @sebworks 
- Add tests (slowly working on this in other PRs)
=> Added a checker for max selections

CHANGELOG.md, cfgov/v1/models/sublanding_page.py
The Post Preview Snapshot page order is oldest to newest. This should be reversed.
- Add reverse flag to Post Preview Snapshot list to get most recent pages
- List search includes any page class ending with `FilterablePage` not just `BrowseFilterablePage`
- These pages should have the most recent pages
- Go [here](http://localhost:8000/policy-compliance/amicus/)
- And [here](http://localhost:8000/policy-compliance/amicus/)
- You can check their refresh/beta counterparts to view it in reverse
- @kave
=> Fix Post Preview Snapshot list to get most recent pages

config/webpack-config.js, gulp/tasks/scripts.js, gulp/tasks/styles.js
- Creates separate webpack config objects for modern and IE.
- Moves IE script uglifying to webpack Uglifier plugin instead of gulp.
- Moves modernizr generation to its own task `gulp scripts:polyfill`. (@jimmynotjim – you're right, this makes sense.)
- Moves task functions to named functions.
- Remove `replace` for chosen-sprite, since chosen has been removed in https://github.com/cfpb/cfgov-refresh/pull/1576
- `gulp build` site should work on modern browsers and IE9 as before.
- @sebworks 
- @jimmynotjim
=> Organize/cleanup style/scripts tasks

CHANGELOG.md, cfgov/jinja2/v1/events/_macros.html
Removed the ics download from the front-end
- Create an event in the future. Under the date, there should be no download option.
- @sebworks 
=> Removed the ICS download option from the front-end

cfgov/jinja2/v1/about-us/the-bureau/index.html
One line fix to switch the video on the Bureau Page. Part of DFJR-1117.
- Visit http://localhost:8000/about-us/the-bureau/ and play the video
- @sebworks
=> Change the video on the Bureau page

cfgov/processors/processors_common.py, requirements/base.txt
lxml resolved the problem it was introduced to solve (see #1777), but installation is error-prone and
- lxml is removed
- process_common.fix_links altered to use html.parser and explicitly use BeautifulSoup's html output formatter.
- Run `cfgov/manage.py sheer_index` and observe that the issue from #1777 hasn't regressed
- @kurtw @kave  @richaagarwal
=> lxml, perhaps not

test/browser_tests/page_objects/page_careers-application-process.js, test/browser_tests/page_objects/page_careers-current-openings.js, test/browser_tests/page_objects/page_careers-students-and-graduates.js, test/browser_tests/page_objects/page_careers-working-at-cfpb.js, test/browser_tests/page_objects/page_careers.js, test/browser_tests/page_objects/page_dbwu-past-awards.js, test/browser_tests/page_objects/page_dbwu-small-businesses.js, test/browser_tests/page_objects/page_dbwu-upcoming-procurement-needs.js, test/browser_tests/page_objects/page_doing-business-with-us.js, test/browser_tests/spec_suites/careers-application-process.js, test/browser_tests/spec_suites/careers-current-openings.js, test/browser_tests/spec_suites/careers-working-at-cfpb.js, test/browser_tests/spec_suites/careers.js, test/browser_tests/spec_suites/dbwu-past-awards.js, test/browser_tests/spec_suites/dbwu-small-businesses.js, test/browser_tests/spec_suites/dbwu-upcoming-procurement-needs.js, test/browser_tests/spec_suites/doing-business-with-us.js, test/browser_tests/spec_suites/footer.js
A lot of tests broke when career pages and Doing Business With Us moved. This fixes all those broken tests.
- Run `gulp test:acceptance --sauce=false`
- @sebworks 
=> Fixing browser tests

CHANGELOG.md, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/js/molecules/GlobalSearch.js, test/browser_tests/spec_suites/organisms/global-search.js
- Adds acceptance tests for the global search organism.
Tests will run 
- `gulp build`
- `gulp test:acceptance --specs=organisms/global-search.js --sauce=false`
- `gulp test:acceptance --specs=organisms/global-search.js --sauce=false --windowSize=610,700`
- @sebworks 
- @kurtw 
- This tests things at two window sizes, which need to be manually passed in. We'll want a mechanism to run the tests and have them run through the different sizes automatically *unless* `windowSize` is set.
=> Adds global search acceptance tests

CHANGELOG.md, cfgov/v1/__init__.py
Removes the inline CSS from the sheer_indexed content.
- Parsing data now removes inline CSS
- Go [here](http://localhost:8000/about-us/blog/take-a-tour-of-money-as-you-grow-our-new-resource-to-help-parents-and-caregivers-give-children-a-strong-financial-start/) and inspect the aside tag. (screenshot below)
- Run `./cfgov/manage.py sheer_index` 
- Go back to the page and see that inline CSS is gone
- @kave 
=> Removes inline CSS when running sheer_index

cfgov/unprocessed/js/molecules/Expandable.js
Fix for IOS Expandable resize bug
- Added some code to the expandable to check the contentHeight before resizing.
- Visit the blog on the IOS simulator (`http:127.0.0.1:8000/about-us/blog`) and click/scroll on the expandable. It shouldn't close. Rotate the simulator 360 degrees; it should close.
- Throttle the window.resize method.
- Calling `offsetHeight` will cause a reflow so we need to address that at some point.
=> Fix for IOS Expandable resize bug

cfgov/cfgov/settings/base.py, cfgov/processors/processors_common.py, cfgov/processors/wordpress_newsroom.py, cfgov/processors/wordpress_post.py, cfgov/sheerlike/external_links.py, cfgov/v1/__init__.py
.gov links should not be stripped of its hostname
- names of external link/icon pattern names
- processors_common now checks against a link pattern before stripping hostnames from links
- run `cfgov/manage.py sheer_index`
- go [here](http://localhost:8000/about-us/blog/3-tips-to-help-you-make-the-most-of-your-tax-refund/) and go to irs links. they should go straight to the irs.gov page
- @kave 
=> Fix .gov external links

CHANGELOG.md, cfgov/cfgov/urls.py
Updated urls.py for new location of about-us sub-directories to fix a few issues with `/about-us` urls
- Updated careers, doing-business-with-us, and the-bureau in urls.py to fix a few issues with `/about-us` urls
- navigate to the pages that have been updated, they shouldn't 404
- @kave 
- @kurtw 
- I'm wondering if /blog and /newsroom should be moved as well
=> Updated urls.py for new location of about-us sub-directories

cfgov/cfgov/urls.py, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_layouts/base.html, cfgov/jinja2/v1/templatetags/global_include.py, cfgov/jinja2/v1/test-fixture/index.html, cfgov/sheerlike/__init__.py, cfgov/unprocessed/css/enhancements/base.less, cfgov/unprocessed/css/enhancements/buttons.less, cfgov/unprocessed/css/enhancements/code.less, cfgov/unprocessed/css/enhancements/expandables.less, cfgov/unprocessed/css/enhancements/forms.less, cfgov/unprocessed/css/enhancements/grid.less, cfgov/unprocessed/css/enhancements/icons.less, cfgov/unprocessed/css/enhancements/layout.less, cfgov/unprocessed/css/enhancements/media-queries.less, cfgov/unprocessed/css/enhancements/print.less, cfgov/unprocessed/css/enhancements/tables.less, cfgov/unprocessed/css/enhancements/typography.less, cfgov/unprocessed/css/enhancements/utilities.less, cfgov/unprocessed/css/enhancements/vars.less, cfgov/unprocessed/css/on-demand/header.less, cfgov/unprocessed/js/routes/on-demand/header.js, config/webpack-config.js, gulp/tasks/scripts.js, gulp/tasks/styles.js
Adds a method for packaging and viewing an atomic component in (relative) isolation, for moving to other projects.
- Contains https://github.com/cfpb/cfgov-refresh/pull/1749 and https://github.com/cfpb/cfgov-refresh/pull/1795
- Adds header initialization script to /on-demand/ routes folder.
- Wraps header organism in a macro and allow passing in of option to hide banner (in addition to flag set in CMS).
- Adds /on-demand/ directory in unprocessed css directory for creating a custom stylesheet for a specific component.
- Adds a private `/test-fixture/` route for viewing a component in a stripped down webpage template.
- Run `gulp scripts:atomic && gulp styles:atomic`
- Visit `localhost:8000/test-fixture/?atomic=header`
There should be a functional header without any other content.
- …
=> Dfjr 930 non v1 header - PROTOTYPE

cfgov/jinja2/v1/_includes/macros/video-player.html, cfgov/unprocessed/css/video-player.less, cfgov/unprocessed/js/modules/VideoPlayer.js, cfgov/unprocessed/js/modules/YoutubePlayer.js, cfgov/unprocessed/js/modules/util/data-set.js
Certain youtube videos don't have a max res image. This fixes that by using Javascript to check for the image and using a default if not present.
- Made changes to the JS to create the image.
- Visit `http://localhost:8000/about-us/the-bureau/` and turn JS on and off.
-  
- This also fixes an error in the Jinja template due to no `else` condition.
- I will eventually replace this method with a call to the Youtube data API, which should return a list of available images. This method will however be slower, more complex, and require a API key.
=> Fix for no max res image

cfgov/sheerlike/__init__.py, cfgov/v1/templatetags/global_include.py
Sheerlike sites need to run in their own isolated template environments, to avoid collisions with v1 and other sheer sites (for example, they all have their own 'index.html')
Similarly, legacy django apps exist in another silo, in that they can't reference v1's Jinja2 templates.
With this, we provide a way of breaking out of those silos, and pulling in (rendered) templates from v1. This will primarily be useful for applying a single header/footer to all of these pages.
- a global_include function is made available across all Jinja2 pages (including Sheer sites)
- a similar django template tag is created
- clone django-cfgov-common, cfgov-selfregistration, and fin-ed-resources as siblings to your checkout of cfgov-refresh.
- build fin-ed-resources per it's instructions
- for the other two …
=> global_include in all supported template environments

cfgov/jinja2/v1/events/_macros.html, test/browser_tests/page_objects/page_wagtail_templates.js, test/browser_tests/spec_suites/wagtail-page-templates.js
Initially i want us to start basic with just testing page templates render with no elements. Then we can break up tasks by page and populate the individual pages with elements and test them.
- initial wagtail page template browser tests
- run server `./cfgov/manage.py runserver --settings='cfgov.settings.test'`
- initialize database with `./initial-test-data.sh`
- run `gulp test:acceptance --specs=wagtail-page-templates.js --sauce=false --windowSize=610,700`
- dropdb with `./drop-db.sh testdb`
- @kurtw 
=> intitial test suite for page templates

cfgov/jinja2/v1/_includes/related-posts.html
Header and relation logic for the blog's related posts have been updated.
[here](http://localhost:8000/about-us/blog/older-americans-are-not-alone-in-the-fight-to-stop-financial-abuse/) should be an updated slug and posts that are sorted based on date and have a high enough score to be related to the current post. 
@kave
=> Related posts header and related logic updated

cfgov/jinja2/v1/_includes/on-demand/footer.html, cfgov/jinja2/v1/_includes/on-demand/header.html, cfgov/jinja2/v1/test-fixture/index.html
- Adds on-demand templates for global include. 
- Updates test-fixture path to pull in on-demand templates.
- `/test-fixture/?atomic=header` should spit out the header.
- `/test-fixture/?atomic=footer` should spit out the footer (CSS will be broken because it's not atomic).
- @sebworks 
- footer.css needs to be generated with `styles:ondemand` task.
=> Adds on demand templates

cfgov/jinja2/v1/about-us/the-bureau/bureau-structure/_macro-node.html, cfgov/jinja2/v1/about-us/the-bureau/bureau-structure/index.html, cfgov/unprocessed/css/pages/bureau-structure.less
Two changes:
-  This shrinks the expandable target area on the bureau-structure page to make it easier to scroll without hitting a target area unintentionally. I talked through it with @schaferjh to make sure this reflects the intended UX behavior of having the expandable header section be the target.
- Updated the date to reflect the changes made in #1553 
- Visit http://localhost:8000/about-us/the-bureau/bureau-structure/ on mobile and note the target area
- Visit the same page on iOS simulator and try scrolling. @schaferjh noticed some strange behavior where it would close during scrolling. I assumed it was because of accidentally tapping the large target area, but please let me know if you see anything suspicious.
- @sebworks 
=> Shrinking expandables target area + updating date

CHANGELOG.md, cfgov/unprocessed/js/modules/util/strings.js, cfgov/unprocessed/js/molecules/Multiselect.js, test/unit_tests/modules/util/strings-spec.js
If the select contains an invalid value (an issue we've been seeing often), the scripts will terminate early and log the issue as a tip for developers.
- Adds stringValid function and tests
- Adds stringValid checker when sanitizing the list of options
- `gulp build` and publish Data & Research's child page Research Reports as well as it's child page Data point: Checking account overdraft then open the page. The error should be logged, but it shouldn't be an error which blocks the rest of the scripts on the page.
- @sebworks 
- @kurtw 
- Kurt and I have dealt with bad values more than once, this should help us avoid tearing out our hair if it happens again.
=> Bugfix for bad values in selects

gulp/tasks/test.js, test/browser_tests/spec_suites/wagtail/wagtail-page-templates.js
- Wagtail browser tests into gulp 
- Ensure your server is running in test mode
- `./cfgov/manage.py runserver --settings='cfgov.settings.test'`
- `gulp test:acceptance:wagtail --sauce=false`
- @kurtw 
=> tying wagtail tests into gulp tests flow

cfgov/jinja2/v1/about-us/the-bureau/about-director/index.html
Clicking "View the director’s public calendar” was showing all calendar results (which happened to be mostly Cordray). This updates it to filter out only Rich's results.
- Adds cordray filter to calendar link on About the Director page.
- Visit `/about-us/the-bureau/about-director/` and click "View the director’s public calendar”
The filter should be pre-checked with Richard Cordray.
- @sebworks 
- @jimmynotjim
=> Adds cordray filter to calendar link

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/header.html
Fixed the missing logo on IE 8
- Added conditional IE 8 logo
- `gulp build` and check the homepage in a modern browser with and without JS, and IE 8 with and without JS. A single logo should be displayed in all.
- @sebworks 
__IE 8__
- We are forcing no-js on IE 8, but the logo swaps to a backup with `noscript`, issue was that logo isn't loaded in IE 8 because the JS is actually still available
=> Fixed the missing logo on IE 8

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/v1/forms.py
- Updated the placeholders in wagtail filterable list controls
- Navigate to `/data-research/research/reports` and check 
- that the label for the text input is "Item name:"
- that the helper text for the text input is "Search for a specific word in item title"
- that the helper text for the date filters is "mm/dd/yyyy"
- @sebworks 
- @schaferjh 
- Also removed the chosen class while I was in there since Chosen is no longer used.
=> Updated the placeholders in wagtail filterable list controls

cfgov/jinja2/v1/blog/_single.html, gulp/tasks/test.js, initial-test-data.sh, test/browser_tests/environment.js, test/browser_tests/jenkins_conf.js, test/browser_tests/spec_suites/blog.js
- Minor config change needed to run test suites in subdirectories in `/test/browser_tests/spec_suites/` by default.
- Updated jenkins to use environment config for path.
- Updated functions in test gulp script to be named functions.
- Deprecated blog test.
- `gulp test:acceptance --sauce=false` should pass.
- @sebworks
=> Run subdirectory test suites

.gitignore, test/browser_tests/util/screenshot.js
Using this to check a test suite I'm building, so spinning it off here.
- Adds screenshot.js test utility for capturing a screenshot in a running test.
- In a test (such as `blog.js`) add `var screenshot = require( '../util/screenshot' );` (or whatever path is needed) and add `screenshot.capture()` to a test to observe, such as:
```js
it( 'should properly load in a browser', function() {
expect( page.pageTitle() ).toContain( 'Blog' );
screenshot.capture();
} );
```
- Find screenshot in `test/screenshot.png`
- @sebworks 
- @jimmynotjim
=> Add screenshot.capture() test utility

cfgov/jinja2/v1/about-us/the-bureau/index.html
In #1808, I didn't change the link everywhere which means the video didn't actually change, just the screenshot.
- Visit http://localhost:8000/about-us/the-bureau/ and make sure this is the displayed video.
https://www.youtube.com/embed/2Wy4AmMIAOU
- @sebworks 
Thanks to @schaferjh for catching this!
=> Fix video link from #1808

CHANGELOG.md, cfgov/unprocessed/js/modules/util/dom-events.js, cfgov/unprocessed/js/molecules/Multiselect.js, test/unit_tests/modules/util/dom-events-spec.js
Abstracted dom events for easier reuse throughout the project
- Creates public bind and fire events
- Creates private parse event helper for bind
- Adds tests for public bind events
- `gulp build` and test the Multiselect on `/blog`. It should function exactly the same
- @sebworks 
- Not a lot to gain in coverage, but it'll make testing the multiselect and anything else that uses events easier to test in the long run.
__Before__
```
Statements   : 27.28% ( 731/2680 )
Branches     : 23.34% ( 204/874 )
Functions    : 20.05% ( 86/429 )
Lines        : 27.38% ( 727/2655 )
================================================================================ …
```
=> Abstracted dom events for easier reuse throughout the project

CHANGELOG.md, package.json
Updating Capital Framework to 3.3.0
- Bumped CF to 3.3.0
- `gulp build`
- `gulp test:unit`
- `gulp test:acceptance --sauce=false`
- @sebworks 
- When updatinga a dep, run `npm install [dep name]@[version] --save[-dev]`.
- After install build the project and run tests to make sure nothing breaks.
- Check package.json, mostly likely npm has added `^` when saving the new version, make sure to remove it.
=> Updating Capital Framework to 3.3.0

cfgov/jinja2/v1/events/_macros.html, cfgov/unprocessed/css/pages/event.less
Removing default data from the event venue template. We are still defaulting the Google Map image to Washington DC when no venue info is present. This also fixes a 'comma' bug in the template which caused the map to display a weird location when no venue info was present.
- Added CSS to add a line break after the state if it wasn't empty.
- Modified the template to fix issues with default data, commas, and a line break on the street address.
-  Visit `http://localhost:8000/about-us/events/archive-past-events/summer-consumer-advisory-board-meeting-in-reno-nv/` and observe the address.
- This doesn't address the issue of Wagtail stripping leading zeroes from zip codes. @kave, can you take a look at that?
=> Adding Fixes for Event Detail display.

CHANGELOG.md, cfgov/unprocessed/css/molecules/global-eyebrow.less, cfgov/unprocessed/css/organisms/footer.less
As discussed with @anselmbradford, this PR sets the paths of the U.S. flag images to be root-relative. This allows sites that are relying on the on-demand versions of this CSS (such as my Sheer projects) to find those flag images in their canonical cfgov-refresh location, rather than having to add them to their static files, as well.
- Changed `us-flag` image paths to be root-relative.
1. Pull down this fork
2. Rebuild the CSS
3. Serve the site
4. Observe that the flag images still load
- @sebworks  
- This would allow me to revert the last commit in cfpb/cfgov-sheer-templates#8, which would be great.
=> Root-relative flags

cfgov/jinja2/v1/_includes/organisms/footer.html, cfgov/unprocessed/css/organisms/footer.less
- Adds `span.icon-link_text` into external links in footer to prevent their underlines from going under the icon.
- @sebworks 
=> Stop footer link underlines from going under icon

cfgov/unprocessed/css/organisms/mega-menu.less
- Add padding-right to menu items so that they wrap before colliding with the green arrow.
- Consolidates -content-2, -content-3 styles.
- Fixes padding issues on -grid styles where the menus where getting different padding at different levels.
- `gulp build` 'n' check the mobile menu.
- Desktop should be unaffected.
- @sebworks 
- @duelj @ajbush 
1st level
2nd level
3rd level
=> Menu CSS cleanup / spec feedback

cfgov/cfgov/settings/base.py, cfgov/v1/__init__.py
Download links were being set to relative links so `files.consumerfinance.gov` wouldn't have ever been hit. This prevents this from happening.
@rosskarchner @kave @richaagarwal
=> Fix download links from becoming relative

CHANGELOG.md, cfgov/v1/models/molecules.py
Fixed an issue w/ the spacing on the hero
- Changed the modifier on heros to `flush-top` and `flush-bottom`
- Open a page with a hero, ex `data-research/credit-card-data/` under 1000px there should be some gutter space on either side. The text shouldn't be flush against the browser edge.
- @sebworks 
- @duelj 
- @schaferjh 
__Before__
__After__
- The flush sides modifier on `block` was forcing a -30px margin on both sides
- This molecule doesn’t actually need a block wrapper at all, investigate removing it in the future
=> Fixed an issue w/ the spacing on the hero

cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/css/organisms/mega-menu.less
- Reduces height of mega menu and global search triggers.
- Creates `@mobile_trigger_ht__px` to track header height.
- Adds right-side border to mega-menu hamburger menu.
- `gulp build`
- Boot up the iOS simulator for an iPhone 5.
- C-c-check it out and click the menu and search buttons.
- @sebworks 
- @ajbush @duelj
=> Reduce mobile header height + add styles per spec feedback

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
These are URL configurations and settings to allow eregs, tax-time-savings, and know-before-you-owe to run within cfgov-refresh
- urls, SHEER_SITES, and some extra settings that eregs expects
- @kave @kurtw @richaagarwal @anselmbradford 
- clone [tax-time-saving](https://github.com/cfpb/tax-time-saving) and know-before-you-owe (internal) as siblings of cfgov-refresh
- follow the instructions to build both
- `cfgov/manage.py runserver`
- observe that you can reach http://localhost:8000/know-before-you-owe/ and http://localhost:8000/tax-time-saving/
The eregs stuff is complicated to get running, so for now, please just trust me. You can observe substantially the same settings in cfpb_django, and see the similarity to other "optional" apps in our settings and URL configs.
…-you-owe
=> URL's and settings to support eregs, tax-time-savings, and know-before-you-owe

cfgov/sheerlike/external_links.py
Looks like the `html` formatter from before caused some weird output for `>`-like symbols. This jsut removes formatting entirely so we're just getting back what was put in to begin with. Safe enough, though the docs say that it might output invalid html, but that seems to be the case if the html was invalid to begin with.
`cfgov/manage.py sheer_index`
http://localhost:8000/about-us/blog/mortgage-moves-what-kind-of-mortgage-will-you-get/ check for correct output of apostrophes
http://localhost:8000/about-us/the-bureau/leadership-calendar/ check descriptions for correct output of `>`'s
@rosskarchner @kave @richaagarwal
=> Remove output formatting to get back what was put in

cfgov/unprocessed/js/modules/util/assign.js, cfgov/unprocessed/js/modules/util/fnBind.js
Fix for the Bureau page on Android 4.1. The Mega Menu is currently breaking because of a null handling error in the assign utility function on `the-bureau` page. 
- Visit `http://localhost:8000/about-us/the-bureau/` on an Android device via Sauce Labs. (I'm still mad that Sauce labs doesn't have Blackberry).
- @jimmynotjim
=> Fix for the Bureau page on Android 4.1

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
Mistakenly thought we didn't need the jobs app-- this puts those URL's back
=> restore jobs URL's

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/hero.html
Table cells will fill the container even if a width is set if there are no other table cells. Even if there's no image, we need the div to keep the layout the same
- Moved the image div out of the condition
- `gulp build` and visit `/policy-compliance`. The text shouldn't be the entire width due to the CMS not having an image to use.
- @sebworks 
__Before__
__After__
=> Fixed issue where missing images were breaking the layout

cfgov/jinja2/v1/_queries/calendar_event.json
Change the query's sort field so we actually get calendar events by day.
@kave @rosskarchner @richaagarwal @sebworks @anselmbradford @jimmynotjim @KimberlyMunoz
=> Hotfix field sort

cfgov/es_mappings/calendar_event.json, cfgov/processors/django_calendar_event.py
_Some_ of the dates were a different format than what was expected.
- `./cfgov/manage.py sheer_index -r -p calendar_event`
- Go to [the event calendar](http://localhost:8000/about-us/the-bureau/leadership-calendar/)
- Filter by date and verify the results are accurate
@kave 
@jimmynotjim
=> Normalize calendar event dates to fix date filtering

cfgov/jinja2/v1/_includes/tags.html, cfgov/jinja2/v1/events/_event-detail.html, cfgov/v1/__init__.py
This event pages tags were not routing to the correct url. that has been fixed
e.g [here](http://localhost:8000/about-us/events/spring-2016-community-bank-advisory-council-meeting-washington-dc/)
=> updated tags to account for events

cfgov/unprocessed/css/atoms/overlay.less, cfgov/unprocessed/js/organisms/MegaMenuMobile.js
iOS was not dismissing the menu on click of the mega menu semi-opaque overlay.
BB was dismissing it too soon.
- Adds `cursor: pointer` to the styles for the overlay so that iOS bubbles the click event up to the body, which dismisses the menu in the mega menu script.
- Changes the event type to `click` instead of `mousedown`, so that a `mouseup` event is required to the dismiss the menu (hopefully this fixes the issue on BB).
- `gulp build`
- Load in iOS simulator (try iPhone 5)
- Click hamburger menu, scroll down till the menu isn't visible, and click the overlay. Menu should close
- @sebworks 
=> Hotfix: Changes overlay click behavior for iOS/BB

cfgov/v1/__init__.py
@kurtw @richaagarwal @jimmynotjim @sebworks @KimberlyMunoz @anselmbradford 
- view this [page](http://localhost:8000/about-us/blog/mortgage-moves-where-will-you-start/)
- Then run `./cfgov/manage.py sheer_index -r -p posts` 
should now look like this with all style tags and inline styles stripped:
=> removes style tags and all in-line style attributes

cfgov/unprocessed/js/modules/YoutubePlayer.js
Fix for Youtube Player on Desktop IE9/Safari. This sets the Youtube host to use https which resolves an issue allowing control of the Iframe on IE9 and Safari ( what a weird combo ). 
- Visit `http://localhost:8000/about-us/the-bureau/` on Safari or IE9. Click the play button.  Click the close button.  The video should start from the beginning. 
- @jimmynotjim
=> Hotfix: Fix for Youtube Player on Desktop IE/Safari

cfgov/jinja2/v1/_includes/macros/filters.html, cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/index.html, cfgov/unprocessed/js/organisms/FilterableListControls.js, cfgov/unprocessed/js/routes/sheer.js
Fix for validation on Leadership Calendar download
- Changed `cfgov/unprocessed/js/routes/sheer.js` to fix issue passing in the correct dom element.
- Changed `cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/index.html` to wrap the filter in a dom element.
- Removed unused classes.
- Visit `http://localhost:8000/about-us/the-bureau/leadership-calendar/` and expand the `Download options` filter. Enter in an invalid date. You should see the warning notification. 
=> Fix for validation on Leadership Calendar download

cfgov/unprocessed/js/organisms/MegaMenuDesktop.js, cfgov/unprocessed/js/organisms/MegaMenuMobile.js
Always go to the top of the page as navigating between menus.
- Scroll back to top on menu changes.
- Turn suspended checks into guard clauses.
- `gulp build`
- Open in mobile view.
- Go to About Us, scroll down till Careers button is at the top of the screen.
- Click Careers entries. 
Should scroll to top and slide careers menu into view.
- @sebworks
=> Scroll back to top on menu clicks

cfgov/unprocessed/js/organisms/MegaMenu.js
- Add listening for switch between mobile and desktop on orientation change.
- `gulp build`
- View in iPad simulator. 
- Use menu in landscape.
- Swap to portrait.
- Use menu in portrait. It should still work.
**Note: The simulator may show a flyout menu to the right. This may be a simulator bug and not occur on a device, but not sure till we push to beta and test on a device.**
- @sebworks 
- In some cases the `_resizeHandler` will fire twice on devices that support both orientation change and resize events. This shouldn't be a problem, because in the case of resize events they are firing continuously while resizing anyway. We could limit it to one or the other, but I think there will be cases where the page could be resized and have an orientation …
=> Support orientation change

cfgov/core/services.py
@rosskarchner realized my testing method was faulty -_- this fixes it.
@kurtw @richaagarwal for some odd reason, the PDFRECTOR_LICENSE environment variable was being returned as a unicode-string 👎
=> explicitly setting the license to a string

cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/modules/transition/AlphaTransition.js, cfgov/unprocessed/js/modules/transition/BaseTransition.js, cfgov/unprocessed/js/modules/transition/MoveTransition.js, cfgov/unprocessed/js/modules/util/assign.js, cfgov/unprocessed/js/modules/util/fn-bind.js, cfgov/unprocessed/js/molecules/Expandable.js, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/organisms/MegaMenu.js, cfgov/unprocessed/js/organisms/MegaMenuDesktop.js, cfgov/unprocessed/js/organisms/MegaMenuMobile.js
Fix for BB on non V1 pages. We have opted not to include a polyfill or shim for various reasons. Instead, we have chosen to use an internal function to augment `Function.prototype.bind`. I think this approach is the least invasive when including the header/footer modules on other sites. It's not a complete approach as we are using `.bind` instead of `fnBind` in other modules.
This fix doesn't work on the emulator but does on a real device. What a fun time that was discovering this fact. 
- Changed `Function.prototype.bind` instances to use internal function.
- Removed instances of `Object.seal` to avoid shimming/shamming/polyfill augmenting. We will address immutable constants at a later date.
- Browse the site paying close attention to the nav at various breakpoints. Visit …
=> Fix for BB on non V1 pages

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py
This will allow usage of Oracle's pure-python mysql connector. If it's not installed, we still attempt to use MySQL-Python.
This has the potential to ease development setup, and some deployment scenarios.
- adds a switch to settings that checks if 'mysql' can be imported, and if so, sets the mysql engine to 'mysql.connectors.django'
- download the platform-independent zip from [here](http://dev.mysql.com/downloads/connector/python/), and `pip install file.zip`, and verify that wagtail-backed pages continue to work.
- @kurtw @kave
=> mysql connector

INSTALL.md, README.md
- Fixed typos, etc., for `INSTALL.md` missed in https://github.com/cfpb/cfgov-refresh/pull/1534
- Brought back stand-alone install section as there's content that needs to be removed from `README.md` too, but I'm not sure we're off stand-alone installations team-wide yet.
- @sebworks 
- README.md and INSTALL.md should be updated to only be the Vagrant setup after a fresh run-through of those steps in INSTALL.md.
=> Fixes Install/Readme

cfgov/cfgov/urls.py, cfgov/core/services.py, cfgov/legacy/views.py, cfgov/templates/find_a_housing_counselor.html, cfgov/templates/hud_list.html
- This brings the "find a housing counselor" tool to Django, and which now uses Mapbox instead of Google Maps. Thank you @wpears!
- install the private repo 'django-cfgov-common' if you haven't already, and make sure you have a recent checkout of cfpb_nemo (also private) checked out as a sibling to cfgov-refresh
- check out https://github.com/cfpb/django-hud and `pip install -e ../django-hud` (or wherever you put it)
- you may need to `cfgov/manage.py migrate`
- get the mapbox API key, either from me from 'build.json' in the private 'website' repo.
- `export MAPBOX_ACCESS_TOKEN=[ the token ]`
- `cfgov/manage.py load_hud_data` to load the housing counselor data
- `cfgov/manage.py runserver` and go to http://localhost:8000/find-a-housing-counselor/ to give it a try.
- note that PDF …
=> bringing /find-a-housing-counselor/ to django + mapbox

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_includes/macros/active-filters.html, cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/print/index.html, cfgov/sheerlike/query.py, cfgov/v1/views.py
The redirect was tossing the `GET` request params, so i updated the url path created by the service.
Also created a ELASTICSEARCH_BIGINT variable as es doesn't currently have a way to return all documents without pagination of some sort which won't work for a pdf creation.
@kurtw @richaagarwal @rosskarchner 
- Testing this locally will be a pain for you, wait to test on flapjack after merging.
=> fixed leadership calendar filtering for pdf downloads

cfgov/v1/__init__.py
- Makes sure external link icon gets into any external link
- go to these pages and then go to localhost and compare the links. See [JIRA]/browse/DFJR-1229 for details on the links.
- http://beta.consumerfinance.gov/policy-compliance/guidance/implementation-guidance/tila-respa-disclosure-rule/
- http://beta.consumerfinance.gov/open-government/our-open-government-activities/
- http://beta.consumerfinance.gov/policy-compliance/guidance/implementation-guidance/tila-respa-disclosure-rule/
- http://beta.consumerfinance.gov/policy-compliance/notice-opportunities-comment/archive-closed/30-day-pra-loan-originator-compensation-amendment-regulation-z/
- run `./cfgov/manage.py sheer_index` and go to http://localhost:8000/about-us/blog/5-things-to-consider-before-you-collect-your-social-security-benef …
=> Add icon to back into external links that leave .gov

cfgov/jinja2/v1/_includes/molecules/text-introduction.html, cfgov/jinja2/v1/_includes/organisms/item-introduction.html
Added a check to avoid blank link lists on mobile.
- Visit http://localhost:8000/about-us/events/ on mobile
- @sebworks 
It should _not_ look like this
=> Fix mobile text intro

cfgov/cfgov/urls.py
These redirects resolve issues with certain static assets in the owning-a-home project
- two URL redirection rules, that grab /owning-a-home/static and owning-a-home/resources and redirect to /static/owning-a-home/[static or resources/]
- @kave @richaagarwal @kurtw
=> add some URL redirects for owning-a-home static assets

cfgov/unprocessed/css/organisms/header.less
The mega-menu background was being constrained on some older projects, such as Owning a Home and Everyone Has a Story. This fixes that by overriding those projects' `position` declaration on the first `.wrapper` inside the header to set it back to its initial value.
- `position: initial;` on `.o-header_content > wrapper`
- Pull
- Build
- Serve
- Visit `owning-a-home/` or `everyone-has-a-story/` and test
- @sebworks 
- This line could be removed if these older projects' dependencies are ever brought up to modern standards.
=> DFJR-1220: Fix constrained mega-menu bg on older projects

cfgov/cfgov/urls.py
Adds a URL ruls for the Django page at /credit-cards/knowbeforeyouowe 
- a url rule (pointing to a templateview)
- clone  django-cfgov-common (or update your existing checkout) and make sure that you're on master
- clone CFPB/agreement_database (or update your existing checkout) and make sure that you're on master
- `pip install -r path/to/django-cfgov-common`
- `pip install -r path/to/agreement_database`
- observe that http://localhost:8000/credit-cards/knowbeforeyouowe works
- @kurtw @kave @richaagarwal
=> add urls for legacy 'knowbeforeyouowe' pages

cfgov/jinja2/v1/about-us/careers/students-and-graduates/index.html, cfgov/jinja2/v1/about-us/index.html, cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/index.html, cfgov/jinja2/v1/newsroom/press-resources/index.html, cfgov/unprocessed/css/pages/press-resources.less
A few minor changes to wording requested by external affairs before the
www switchover.
A few changes on press-resources to bring them more in line with current
standards.
- `gulp build` and visit affected pages
- @sebworks 
- I talked with @ajbush and @duelj about the spacing between rows. I think EA thought there was no spacing and asked us to change it from 10px to 15px. I double-checked with Design and they said 30px was the correct spacing.  I also removed some unnecessary hardcoding of the titles while I was in there. @schaferjh
=> Content Edits and spacing from EA

cfgov/v1/util/ref.py
- Logic to `is_blog` that checks to see if the page is of blog type.
- Go to activity log and find Mortgage Moves: What kind of Mortgage Will You Get?
- http://localhost:8000/about-us/blog/mortgage-moves-what-kind-of-mortgage-will-you-get/ should have no category above the title
- @kave
=> Fix Blog posts that have no category

CHANGELOG.md, cfgov/unprocessed/js/molecules/Multiselect.js
When clicking outside the multiselect, it should close but wasn't. A click event necessary to allow scrollbar clicking on IE was the cause, limiting it to the fieldset allows IE users to click the scrollbar while also allowing the multiselect to close when clicking outside of it.
- Limited the click event to the fieldset to allow users to click off of the multiselect.
- `gulp build` and navigate to `/blog/` both in Chrome and IE 10 (SauceLabs is easiest).
- @sebworks 
- Write browser tests to ensure click events are properly scoped.
=> Fixed an issue where the multiselect couldn't be closed

CHANGELOG.md, cfgov/jinja2/v1/_includes/on-demand/header.html
Some of the django projects don't have their own no-js and js solution causing issues with the classes and scripts in the header. To fix this issue while avoiding creating new issues elsewhere, I’ve scopped the classes to just the on-demand header.
- Added no-js class wrapper to the on-demand header.
- Added script to swap the no-js class to js on load.
1. Clone django-cfgov-common from GHE as a sibling to cfgov-refresh
2. Clone django-college-cost-comparison from GHE as a sibling to cfgov-refresh
3. In the cfgov-refresh repo root run `pip install -e ../django-cfgov-common && pip install -e ../django-college-cost-comparison`
4. Restart the cfgov-refresh server.
5. Navigate to http://localhost:8000/paying-for-college/.
6. Click where the search button should be (it's there, but the text is …
=> Added no-js and js classes to the on-demand header

CHANGELOG.md, test/browser_tests/page_objects/page_activity-log.js, test/browser_tests/shared_objects/filter.js, test/browser_tests/shared_objects/pagination.js, test/browser_tests/shared_objects/stay-informed-section.js, test/browser_tests/spec_suites/activity-log.js, test/browser_tests/spec_suites/blog-single.js, test/browser_tests/spec_suites/blog.js, test/browser_tests/spec_suites/newsroom-press-resources.js, test/browser_tests/spec_suites/newsroom.js
The Blog, Newsroom and Activity Log were updated to Wagtail pages, which in turn updated the filter, post list, and pagination components. The tests started to fail due to the markup changes, this PR updates the hooks to search for the correct markup.
- Updated the pagination, filter, and email signup shared objects for the latest atomic components
- Updated Activity Log page objects to use shared objects
- Updated the specs to silence tests that need a bit more refactoring later
- Silenced the non-atomic components in Press Resources (this will be updated to Wagtail soonish)
- `gulp test:acceptance --sauce=false`
- @sebworks 
- @kurtw 
- @kave 
=> Updated the browser tests for the recent change to wagtail pages

test/browser_tests/page_objects/page_the-bureau.js, test/browser_tests/shared_objects/secondary-navigation.js, test/browser_tests/spec_suites/the-bureau.js
This test would catch #1801 and could be expanded wagtail pages to include #1673 as well 
- Test for the secondary Nav
- `gulp test:acceptance --sauce=false --windowSize=610,700`
- @sebworks 
- Any browser test with JS is failing on IE8, including this one, do we have a way to deal with those tests? @anselmbradford, I think you might have brought this up in chat?
=> Tests for In this section

cfgov/cfgov/settings/base.py, cfgov/es_mappings/pages.json, cfgov/processors/wordpress_page.py
Reverts cfpb/cfgov-refresh#1938
Changes the `page` processor to only get pages we need.
@rosskarchner @kave
=> Revert "Remove page from WordPress indexing"

cfgov/v1/models/base.py, cfgov/v1/util/ref.py
Creates a lookup function in ref.py and then uses it to create the related posts query in base.py.
@kave @rosskarchner
=> Related Posts now use category to filter out related content

.env_SAMPLE, CHANGELOG.md, cfgov/cfgov/settings/production.py, cfgov/v1/db_router.py
@kurtw @richaagarwal @rosskarchner 
- you will need some legacy apps installed. You can use `CFPB/agreement_database` from the internal github
- then `pip install -e ../agreement_database` from inside the cfgov-refresh repo
- Copy `production.py` database & routing settings into your `local.py`
- Create an extra database named whatever i used `legacy`, and drop and recreate `v1`
- run:
- `./cfgov/manage.py migrate`
- `./cfgov/manage.py migrate --database=legacy` (its always legacy regardless of your db name)
- Observe only cfgov-refresh tables are in `v1` and legacy apps are in your new db `legacy`
=> Databases routes for cfgov-refresh vs legacy apps

cfgov/cfgov/urls.py
So that 'sheer_index' keeps working when cfgov-refresh is powering the whole site
- if the 'cal' app  is installed, a URL route is created for /leadership-calendar/cfpb-leadership.json
- Trust me? No. OK. download this and hang on to your hat: [calendar.sql.zip](https://github.com/cfpb/cfgov-refresh/files/228024/calendar.sql.zip)
- `pip install djangorestframework==2.4.8`
- `pip install vobject==0.9.1`
- clone private repo CFPB/leadership-calendar
- clone private repo CFPB/django-cfgov-common
- `pip install -e ../leadership-calendar && pip install -e ../django-cfgov-common`
- unzip calendar.sql.zip
- `cfgov/manage.py dbshell < ~/Documents/calendar.sql`
- `cfgov/manage.py runserver`
- observe the beautiful json at http://localhost:8000/leadership-calendar/cfpb-leadership.json
- …
=> enable the leadership calendar API

CHANGELOG.md, cfgov/unprocessed/css/enhancements/base.less, cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/modules/transition/AlphaTransition.js, cfgov/unprocessed/js/modules/transition/BaseTransition.js, cfgov/unprocessed/js/modules/transition/MoveTransition.js, cfgov/unprocessed/js/organisms/MegaMenu.js, cfgov/unprocessed/js/organisms/MegaMenuDesktop.js, cfgov/unprocessed/js/organisms/MegaMenuMobile.js, test/unit_tests/modules/FlyoutMenu-spec.js, test/unit_tests/modules/transition/BaseTransition-spec.js
- Hides overflow at mobile sizes.
- Adds halt and clearTransitions methods for halting in-progress transitions and clearing transitions, respectively.
- Added brackets to single-line if statements, because CodeClimate prefers that.
- Cleanup on mobile mega menu suspend method.
- Open iPad Retina simulator portrait orientation.
- Navigate to `flapjack.demo.cfpb.gov`
- Open menu.
- Rotate to landscape.
- Click any menu link.
- Rotate to portrait.
- It should look like:
Now, `gulp build` and navigate to `localhost:8000` and repeat the steps above. Off-screen content should not be visible.
- @sebworks 
- There's a weird double-closure of the menu on iPad at mobile sizes, but is *kinda* looks like an intentional effect, so I think it'll be okay for launch. I …
=> Adds overflow:hidden to body at mobile + iPad fixes

CHANGELOG.md, cfgov/jinja2/v1/_includes/on-demand/header.html, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/unprocessed/css/on-demand/header.less
Due to the `.o-header` scoping, some base styles were overwriting our mega-menu styles. By scoping the mega-menu to the header organism I was able to match the specificity and set the cascade properly.
- Wrapped the mega-menu import in the header organism to match the scoping.
- `gulp styles:ondemand` and open http://localhost:8000/test-fixture/?atomic=header in a smaller browser window. The left side of the nav should have the proper gutter instead of being pushed up agains the window as we're currently seeing on `/complaint`
- @sebworks 
__Before__
__After__
=> Fixed the mobile menu for on-demand django pages

cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html
Sidebar breakout organism still had atoms in its selections that needed markup added to them.
- Markup handling for atoms in sidebar breakout
- Go to [refresh]/policy-compliance/rulemaking/ and compare to http://localhost:8000/policy-compliance/rulemaking/
- @kave 
before
after
=> Fix sidebar breakout template rendering

CHANGELOG.md, cfgov/jinja2/v1/_includes/on-demand/footer.html, cfgov/jinja2/v1/_layouts/base.html
Including this script allows Digital Gov to generate our global site search results. Do not edit, this script comes straight from Digital Gov - http://search.digitalgov.gov/manual/code.html
- Digital Gov search loader script
- navigate to any new page and inspect the `head`. Just after the IE conditional and jQuery loader should be two search.usa.gov scripts injected by this loader script in the footer.
- @sebworks 
=> Added the Digital Gov search script

cfgov/jinja2/v1/_includes/organisms/secondary-navigation.html, cfgov/unprocessed/css/organisms/secondary-navigation.less
Fix for hiding sibling nav items on the mobile/tablet
- Modified Jinja and Less to hide sibling nav items on mobile/tablet
- Added context function to determine if current or children nav items are active. 
- Run `gulp styles`. Visit `http://localhost:8000/policy-compliance/guidance/supervision-examinations/` and resize down to mobile. Sibling nav items should disappear below 900px.
- @kave 
- @kurtw 
-
=> Fix for hiding sibliing nav items on the mobile/tablet

cfgov/unprocessed/js/molecules/GlobalSearch.js
Fixes issue related to Android search element on legacy devices
- Modified `cfgov/unprocessed/js/molecules/GlobalSearch.js` to force a reflow when the search is beginning to expand. 
- Visit the site via sauce labs on a legacy Android device. Click on the `Search` icon. The search should expand/collapse as you click on the icon. 
=> Fixes issue related to Android search element on legacy devices

cfgov/v1/models/sublanding_page.py
this [page](http://localhost:8000/policy-compliance/notice-opportunities-comment/) was not getting the latest posts since it was overriding the 2nd browse filterable page since the form is was the same in both `0`
=> concantenation of lists of posts when the form id is the same

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py, cfgov/cfgov/urls.py, cfgov/templates/admin/base.html, picard_scripts/akamai_flush.sh, picard_scripts/picard_data_export.sh, picard_scripts/picard_synonyms_export.sh
Adds some final missing admin bits: picard, and the export tool that comes the selfregistration app.
- URL patterns, redirects, and OPTIONAL_APPS config for picard and selfregistration
- some sample scripts for picard
- adds 'task Launcher' (aka Picard) to django admin nav
-  check out CFPB/django-cfpb-common and `pip install -e <path>` it
-  check out CFPB/Picard and `pip install -e <path>` it
-  check out CFPB/cfgov-selfregistration and `pip install -e <path>` it
- `pip install django-braces==1.0.0`
- `cfgov/manage.py migrate`
- `cfgov/manage.py runserver`
- Observe that http://localhost:8000/picard/ redirects to localhost:8000/tasks/ (will require login if you aren't already logged in), and that running any tasks produce the expected output "this script only exists to prove that Picard …
=> final missing admin bits

cfgov/v1/models/sublanding_page.py, cfgov/v1/util/filterable_context.py
This is a terrible way to handle this and should be changed after launch. Excludes pages from being included in the `get_descendants` and `descendant_of` queries if their parent's title has `archive` (case insensitive) in it.
@kave
=> Stop archive pages from being included in FilterablePage lists

cfgov/jinja2/v1/_includes/organisms/full-width-text.html
Classname was just incorrectly set.
- Fixed the `full-width-media_image` classname
- gulp build and create a blog post with images (or trust the screenshot)
- @sebworks 
__Before__
__After__
=> Fixing the missing spacing below full-width images

cfgov/unprocessed/css/organisms/mega-menu.less, cfgov/unprocessed/js/modules/FlyoutMenu.js, cfgov/unprocessed/js/organisms/MegaMenu.js, cfgov/unprocessed/js/organisms/MegaMenuDesktop.js
- Delays hover state on header.
- `gulp build`
- if quickly moving over the menu it should not open.
- When over the menu item it should open after a short 150ms delay.
- Check in iPad simulator
- @sebworks 
- iPad simulator (Apple) has a slide down transition the first time each menu is opened, after which it works as expected where when switching between menus there is no slide down transition.
=> Delays hover state on menu

CHANGELOG.md, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/js/molecules/GlobalSearch.js
Fixed disappearing search close button when swapping device orientation.
- Makes trigger invisible when `aria-expanded` is `true` at desktop sizes (via CSS instead of JS).
- `gulp build`
- open in iPad simulator.
- in landscape, open search.
- rotate to portrait. Search close button should be visible.
- @sebworks 
=> Fixes disappearing search close button

cfgov/scripts/rossify_pages.py
I'm going to tack on the part of the script that adds the current Wagtail user data later.
- grab the `content` dump of auth tables (check group chat)
- grab the `refresh` dump from jenkins.
- make duplicate incase you have to start over
- modify the refresh dump file and remove the auth table creation sql and migrations
- then import `content` file into a fresh v1 database then:
- `cfgov/manage.py migrate auth --fake`
- `cfgov/manage.py migrate`
- Import the modified `refresh` dump into the v1 database then run:
- `cfgov/manage.py runscript rossify_pages`
- Check/Verify the users and groups tables to see `content` dump data is there (should have legacy users):
- look around, make users, assign permissions, etc
- you'll notice that the `Can share pages` permission is set for each auth …
=> Add rossify script

test/browser_tests/spec_suites/organisms/global-search.js
- Adds delay to search test to allow transition to complete
- `gulp build && gulp test:acceptance --sauce=false --specs=organisms/global-search.js` should pass
- @sebworks
=> Adds delay to search test to allow transition to complete

cfgov/unprocessed/js/modules/FlyoutMenu.js, test/unit_tests/modules/FlyoutMenu-spec.js
From https://github.com/cfpb/cfgov-refresh/pull/1942#discussion_r60522965
- Updates FlyoutMenu transition to use undefined default + updates relevant tests.
- Minor jsdoc/CodeClimate formatting updates.
- `gulp test:unit:scripts` should pass
- @sebworks 
- @jimmynotjim
=> Updates FlyoutMenu transition to use undefined default

cfgov/cfgov/settings/base.py
Knowledgebase and jobmanager need django-reversion in order for their admin to work.
=> enable reversion

cfgov/unprocessed/js/modules/util/fn-bind.js, gulp/tasks/scripts.js
- Removes unsupported fnBind (see https://github.com/Modernizr/Modernizr/pull/1278) from Modernizr.
- @sebworks 
- @jimmynotjim
=> Removes unused fnBind

cfgov/v1/forms.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/util/filterable_context.py
This should speed up the lists tremendously.
- `get_page_set` for each method has changed. I've made use of the Q object throughout and for regular filterable pages, I've simplified the method to a single line.
- getting the list of tags and authors was a HUGE slowdown in page loads. This uses a different query to get the data that cuts execution time by many orders of magnitude.
- Go to all the filterable list type pages and test out the filtering at each one:
- Newsroom, Blog, Activity log, Research Reports, and Enforcement actions
- @kave 
- Tests
=> Optimize queries for filter lists for fast page loads

CHANGELOG.md, cfgov/unprocessed/js/molecules/Multiselect.js, test/unit_tests/molecules/Multiselect-spec.js
Slowly increasing code coverage and preparing to do some cleaning in the Multiselect. The expand/collapse functionality will need to be tweaked to be testable, due to the aspects of jsdom, it's difficult to test for changes triggered by focus.
- Added tests!
- Removed unnecessary functions that were previously replaced by string utilities
- @sebworks 
- Rewrite the expand/collapse functionality to remove the dependency on `focus`
=> Added tests for the public methods in the Multiselect

cfgov/unprocessed/js/molecules/Multiselect.js
The array that tracked user selections wasn't needed after the `checked` value was added to the option data. This PR removes the selections array, reworking selection changes to use the `checked` value and tidies up the rest of the code a bit.
- Removed selections array and updated selections tracking to use `checked` value
- Updated var names for clarity.
- General file cleanup (ordering, line length, etc).
- `gulp build` and navigate to `http://localhost:8000/data-research/` Multiselect should function as before.
- @sebworks 
- #1982 should be merged before testing this to ensure nothing broke.
- Convert expand/collapse from `focus` to `click/tab`
=> Cleaning up and reducing complexity in the Multiselect

cfgov/jinja2/v1/about-us/careers/application-process/index.html, cfgov/jinja2/v1/about-us/careers/index.html, cfgov/jinja2/v1/about-us/careers/students-and-graduates/index.html, cfgov/jinja2/v1/about-us/the-bureau/index.html
Careers meta descriptions had TODOs for some pages. This makes them all have the same description (text taking from an existing description). 
- Adds meta description for careers pages that were missing it.
- ~~Fixes issue where homepage meta description would have a large gap of spaces after a comma.~~
- View `<head>` source on homepage and on careers pages.
- @schaferjh 
- @sebworks 
- @schaferjh We had this careers meta description already in some of the careers pages, but I'm not sure if the content needs approval? It could show up in search engine results I think.
=> Updates meta descriptions

cfgov/jinja2/v1/_includes/molecules/half-width-link-blob.html
Fix for empty `h3` tag on home page
- Added conditional statement to pass in empty string when `value.heading` is empty.
- Add a `Half Width Blob` to the homepage via admin ( leave the heading field blank ).
- Visit `http://localhost:8000/` and view source.  Find `m-info-unit_content` and observe it doesn't contain an empty `h3` tag. 
=> Fix for empty h3 tag on home page

cfgov/v1/models/base.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/util/filterable_context.py
Duplicate results are showing up in the Further Reading sections of pages. The same type of queries are happening on the filterable lists, so it's possible that it's happening there (though not observed yet).
Also, `descendant_of_q` is changed to `child_of_q`to prevent undesired results.
- `.distinct()` to queries to return unique rows in the results
- Go into wagtail to make a new page
- Add a Related Posts molecule to the Sidefoot with specified categories `Data, research, & reports` and `Press release`
- Add the tags to the page: `Academic research council`, `Research`, and `Payday loans`
- Publish and go to the page
- View repeated results
- Go to your page and see unique results
- @kave
=> Make further reading and list filter results distinct

TERMS.md, cfgov/unprocessed/js/routes/common.js, package.json
We no longer use `cf-expandable` or `JQuery easing` so I'm removing them. This is a move toward elimination of all external JS libraries and frameworks. 
- Run `npm install && bower install && gulp build`. Visit the site and browse; shouldn't see any errors in the console.
- @Scotchester
=> Removing cf-expandable and jquery easing

cfgov/legacy/forms.py
@rosskarchner @kurtw 
This resolves issues with people entering correct zipcodes with leading `0`'s but pdfreactor was stripping them on the backend.
=> refactored form to use USZipCodeField() inorder to not strip leading zeros

cfgov/cfgov/settings/local.py
I need `default_storage_engine` in my setup, and maybe others do too? 
If you need `storage_engine`, it's set to that by default, but double-check `STORAGE_ENGINE` is not being set to anything else in your `.env`
Testing:  Make sure you can still run the app
@kave 
@kurtw 
@rosskarchner
=> Allow init_command to be set by env

cfgov/unprocessed/css/misc.less
This takes care of the issue on http://www.consumerfinance.gov/policy-compliance/guidance/implementation-guidance/title-xiv-mortgage-rules/ where there are a couple pdfs with a .PDF (rather than .pdf) extension.  
This is a quick fix - Longer-term we probably want to lowercase these as part of the upload process.
To test locally, get the latest refresh dump, run `gulp build`, and ensure all the download icons are in place here: [http://localhost:8000/policy-compliance/guidance/implementation-guidance/title-xiv-mortgage-rules/](http://localhost:8000/policy-compliance/guidance/implementation-guidance/title-xiv-mortgage-rules/)
@kave 
@kurtw 
@rosskarchner
=> Ensure files uploaded as .PDFs get a download icon as well

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/footer.html
- Adds No Fear link to footer.
- Visit any page and it should have No Fear Act link in the footer links. @Scotchester / @rosskarchner - this should update it across the site through the global_include, is that right?
- @sebworks 
- @schaferjh
=> Adds No Fear Act link

requirements/base.txt
Animated gifs are supported for use in Wagtail, but you must follow Wand's [installation instructions](http://docs.wand-py.org/en/0.4.2/guide/install.html) to get it working.
- Wand
- go through the installation instructions to install ImageMagick
- `pip install -r requirements/base.txt`
- find a gif and upload it. add it to a page to see it in action
- @kave 
- the servers need to install `ImageMagick` before this can work
=> Add Wand for animated gif handling

cfgov/core/tests/test_views.py
I couldn't get these two tests to pass. At least on my machine, it turned out to be necessary to patch django.conf.settings instead of cfgov.settings.base.
@kurtw @richaagarwal @kave
=> Reg comment test fixes

cfgov/v1/tests.py, cfgov/v1/tests/test_links.py
This adds unit tests for the way we handle external and non CFPB links, functionality for which can be found in `cfgov/v1/__init__.py`.  
I removed `cfgov/v1/tests.py` since it was not being used and does not match the structure we're using elsewhere for unit tests.
To test, run `tox` (I don't know of a way that runs the test individually (that actually works), but if you know of a way, please comment!)
@rosskarchner 
@kave 
@kurtw
=> Add tests for external/internal link handling

cfgov/unprocessed/js/organisms/FilterableListControls.js, cfgov/unprocessed/js/routes/common.js
All sheer pages should be using the `FilterableListControl` so I'm moving the `Multiselect` out of `common.js`. 
- Moved code from `common.js` to `FilterableListControl.js`.
- Run gulp build and visit the blog. Expand the filter and use the Multiselect. It should function without error
=> Removing Multiselect from common.js

cfgov/jobmanager/static/jobmanager/js/supervision.js, cfgov/jobmanager/urls.py
Lamin pointed out that we need to clean the parameters passed to the govdelivery subscription urls.
- govdelivery jobs subscription view now require post requests
- reuse the core/views.py subscribe view
- cd into django-cfgov-common and pull down [GHE]/CFPB/django-cfgov-common/pull/81
- cd back into cfgov-refresh and pull this PR down
- Go to `http://localhost:8000/jobs/supervision/` and enter an email and subscribe. Success message is expected!
- @kave
=> Handle govdelivery job subscriptions via a Django form

test/browser_tests/spec_suites/organisms/footer.js
Oops, forgot to include this in my No FEAR Act PR.
- Adds no fear link to footer test.
- `gulp test:acceptance --sauce=false` should not have a footer test failure.
- @sebworks 
- @jimmynotjim
=> Adds no fear link to footer test

cfgov/unprocessed/js/modules/util/validators.js
- Creates private `_checkableInput()` method that both `checkbox()` and `radio()` share. This removes the public exposure of the `type` parameter, since it would have been possible to call `checkbox()` and pass in a type that was neither `checkbox` nor `radio`. Also moves variable default checks to the top of the method.
- Minor updates to jsdocs to add trailing periods, further explain return type, and adjust line lengths.
- Not 100% sure where this is used, but the `validators-spec.js` should pass with `gulp test:unit`.
- `gulp lint` should no longer have a complexity warning for `validators.checkbox()` method.
- @sebworks
=> Removes validators complexity warning

cfgov/scripts/initial_test_data.py, test/browser_tests/page_objects/page_wagtail_states_pages.js, test/browser_tests/spec_suites/wagtail/wagtail-page-states-pages.js
This is the beginning of testing Wagtail page states.
- Run `gulp test:acceptance:wagtail --specs=wagtail/wagtail-page-states-pages.js --sauce=false --windowSize=610,700`
- @kave 
=> Add browser tests for various page states

cfgov/unprocessed/js/modules/YoutubePlayer.js
Removes youtube player linter warnings.
- Returns `player` instance from `initPlayer` to make use of `player` variable.
- Removes unneeded quotes from a key and fixes some spacing.
- `gulp lint` should not show any warnings for YoutubePlayer.js.
- @sebworks 
- @jimmynotjim
=> Removes youtube player linter warnings

cfgov/unprocessed/js/modules/util/dom-traverse.js
- Moves prefixed matches() method lookup to private `_getMatchesMethod`.
- Adds inline if statement brackets to satisfy Code Climate.
- `gulp lint` should not show a complexity warning for `dom-traverse.js`.
- @sebworks 
- @jimmynotjim
=> Removes dom-traverse complexity warning

cfgov/v1/auth_forms.py, cfgov/v1/forms.py, cfgov/v1/tests/test_password_policy.py, cfgov/v1/util/password_policy.py, cfgov/v1/views.py, tox.ini
Good: refactored the password policy code and wrote tests, and I think it is well-covered now.
Bad: created a new module, that still needs some testing.
@richaagarwal you might be interested in this little bonus: I've included a tox configuration change that allows you to invoke tox with extra arguments, that are passed on to django's test runner. For example, you can now do:
`tox -- v1.tests` to only run the tests in v1.tests 
- `tox` or `cfgov/manage.py test` ought to do it.
- @kurtw @richaagarwal @kave 
-
-
=> Password policy testing

CHANGELOG.md, cfgov/jinja2/v1/_includes/macros/time.html, cfgov/jinja2/v1/_includes/macros/util/format/datetime.html, cfgov/jinja2/v1/events/_event-detail.html, cfgov/jinja2/v1/events/_macros.html
Timezones...for now we're going to show all event timezones as EDT to reduce confusion until we can add localized timezone support.
- Updated event times to show EDT
- Updated code comments to correctly show `none` as the timezone default
- navigate to http://localhost:8000/about-us/events/field-hearing-arbitration-albuquerque-nm/ and the time in the event venue details to show EDT.
- @sebworks
=> Updated event times to show EDT

cfgov/jinja2/v1/_includes/organisms/reg-comment.html, cfgov/unprocessed/css/organisms/reg-comment.less
Should have included this in the previous PR, but here it is now.
- Some classes and Less to control the styling of the disclaimer text a little bit more, as requested by @nataliafitzgerald.
- Bolded text is now Medium.
- Space between disclaimer and button is now 30px.
- @sebworks 
- @nataliafitzgerald
=> Tweak reg comment form disclaimer styling

cfgov/legacy/views.py
This one is pretty subtle.
The old behavior was, we were raising an Exception, and letting Django sort out the rest. This meant, in production, a 500 error. My main concern is that this was polluting the 'Error' rate in New Relic.
Also, I did some reading, and it seems like HTTP 400 is a more appropriate response.
So, when DEBUG is False, we now return a simple failure message with HTTP status 400. We may wish to create a full-fledged error template for 400, like we do 404 and 500-- but users of the /find-a-housing-counselor/ tool will never get this far, so I'm confident the error will mostly be seen by bots.
- Hit /save-hud-counselors-list/?zip=9021 and note the exception message you get
- temporarily set DEBUG to False in cfgov/settings/local.py
- Hit …
=> Bad zips should return 400 error

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/global-eyebrow.html, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/unprocessed/css/enhancements/layout.less, cfgov/unprocessed/css/molecules/global-eyebrow.less, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/css/organisms/mega-menu.less
Fixed an issue where the header only had 15px of spacing instead of 30
- Added `__match-content` modifier to header `wrapper`s
- Utilized existing list modifiers to reduce styles for the language list
- Reduced spacing between language and nav items at 901px
- `gulp build` and check out the header
- @duelj 
- @ajbush 
- @schaferjh 
- @sebworks 
__Before__
__After__
=> READY: Fixed an issue where the header only had 15px of spacing instead of 30

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/half-width-link-blob-group.html, cfgov/jinja2/v1/_includes/organisms/image-text-25-75-group.html, cfgov/jinja2/v1/_includes/organisms/image-text-50-50-group.html, cfgov/unprocessed/css/breadcrumbs.less
The info-unit groups were including headings even if no heading was provided and breadcrumbs had an extra margin above them that wasn't necessary. Wrapped the heading in a conditional so that it's skipped if the value doesn't exist and removed the extra margin on the breadcrumb.
- Removed headings when there's no value for it
- Removed the extra margin on breadcrumbs
- `gulp build` and check out http://localhost:8000/policy-compliance/rulemaking/final-rules/ for breadcrumb changes and http://localhost:8000/policy-compliance/ for 25/75 fixes
- @duelj 
- @sebworks 
__Breadcrumbs__
__25/75__
- This PR goes with https://github.com/cfpb/capital-framework/pull/306 for the 45px change.
=> 	Fixed the spacing around info-units groups and breadcrumbs 

cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/js/modules/FlyoutMenu.js, test/unit_tests/modules/FlyoutMenu-spec.js
- Adds aria-pressed to primary flyout menu trigger to prepare expandables to share transition code.
- `gulp test:unit` should pass.
- When inspecting mega menu hamburger menu at mobile, the trigger to show/hide the menu should toggle `aria-pressed` from false to true. The submenu links should as well. The back button _should not_, but maybe it should also? It's not clearly a toggle, but neither are the submenu links.
- @sebworks
=> Adds aria-pressed to primary flyout menu trigger

CHANGELOG.md, cfgov/unprocessed/css/breadcrumbs.less, cfgov/unprocessed/css/molecules/call-to-action.less, cfgov/unprocessed/css/molecules/featured-menu-content.less, cfgov/unprocessed/css/molecules/global-banner.less, cfgov/unprocessed/css/molecules/global-eyebrow.less, cfgov/unprocessed/css/molecules/global-header-cta.less, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/molecules/home-hero.less, cfgov/unprocessed/css/molecules/info-unit.less, cfgov/unprocessed/css/molecules/inset.less, cfgov/unprocessed/css/molecules/nav-link.less, cfgov/unprocessed/css/molecules/pagination.less, cfgov/unprocessed/css/molecules/social-media.less, cfgov/unprocessed/css/organisms/footer.less, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/css/organisms/mega-menu.less, cfgov/unprocessed/css/organisms/secondary-navigation.less, cfgov/unprocessed/css/print.less
- Adds print styles for major site features that aren't print applicable.
- Moves the logo on print so it is aligned correctly.
- Adds missing topdoc EOF comments.
- `gulp build` visit the homepage and go to File > Print and look at the preview. Should not include the mega menu, search, hero, social media icons, banner and footer buttons, or gaps for images that are background images.
- Check /about-us/careers/application-process/ for the hidden breadcrumbs and secondary nav too.
- @sebworks 
- @schaferjh 
- Heros in CF need print styles added to hide areas where background images appear.
=> Adds print styles for major site features that aren't print applicable

CHANGELOG.md, test/browser_tests/shared_objects/filter.js, test/browser_tests/shared_objects/pagination.js, test/browser_tests/spec_suites/blog.js, test/browser_tests/spec_suites/organisms/pagination.js, test/browser_tests/spec_suites/templates/browse-filterable.js
There are no tests for pagination interaction. Before taking on fixing the existing filter/pagination combo bug, I'm adding some baseline tests of the functionality.
- pagination organism tests
- filtering/pagination template tests
- `gulp test:acceptance --sauce=false --specs=blog.js,organisms/pagination.js,templates/browse-filterable.js`
- @sebworks 
- The last test is the reported bug, fix forthcoming.
=> Added base pagination test before working on pagination bugs

CHANGELOG.md, gulp/tasks/test.js, test/browser_tests/spec_suites/organisms/pagination.js, test/browser_tests/spec_suites/templates/browse-filterable.js
The acceptance test task was running duplicate sets of tests due to the Wagtail tests triggering the browser tests after installing the intial data DB. All Protractor acceptance tests are now combined and the intial data is conditionally loaded based on the passed spec params. Tests should run far faster making testing and development easier.
- Added `_shouldInstallInitialData` function to test whether specs were passed and if so if they contain a wagtail spec
- Removed the duplicate acceptance test trigger `testAcceptanceWagtail`
- Updated the `testAcceptanceBrowser` to conditionally load the initial data originally in `testAcceptanceWagtail` before triggering the tests
- `gulp test:acceptance --sauce=false` should install the data
- `gulp test:acceptance --sauce=false …
=> Fixed duplicate Protractor tests

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/pagination.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/jinja2/v1/_includes/post-macros.html, cfgov/jinja2/v1/events/_paginated.html, cfgov/unprocessed/css/molecules/pagination.less, test/browser_tests/spec_suites/templates/browse-filterable.js
All other filters are being cleared when entering a page number to the page jump form within the pagination. Added hidden inputs for each existing filter param to submit the form with the appropriate filters. Un-silenced the corresponding test and fixed the input interaction.
- Updated the pagination form to loop through any set url params as hidden inputs.
- Un-silenced and updated the corresponding browser test.
- `gulp test:acceptance --sauce=false --specs=templates/browse-filterable.js` should pass
- @sebworks 
=> Fixed issue with page jump form.

cfgov/v1/views.py
Currently, when users attempt to use the 'forgot my password' feature, we aren't actually saving it.
This adds the missing 'form.save()' call to make the password change permanent.
=> When the user resets their password, we should probably save it

cfgov/v1/models/blog_page.py
legacy blog: duplicate content panels were causing pages not to save correctly so additional edit boxes no longer override changed content
- duplicate content panels were causing pages not to save correctly so additional edit boxes no longer override changed content
- Load a db dump
- Edit and Publish a legacy blog page
- @kurtw
=> legacy blog: duplicate content panels were causing pages not to save correctly

test/browser_tests/spec_suites/organisms/header.js
- Adds header tests for overlay.
- `gulp test:acceptance --sauce=false --specs=organisms/header.js --windowSize=640,900` should pass.
- @sebworks 
=> Adds header tests for overlay

cfgov/scripts/initial_test_data.py, test/browser_tests/spec_suites/wagtail/molecules.js
Flapjack tests are failing because the pages that cause the failures are created as DemoPage's which are not available in that environment.
- Remove Demo Page from script
- Page status tests use LandingPage's
- Delete the page state pages titled: Live, Live Draft, Shared, Shared Draft, Draft
- Just to be sure, make sure the sites are for localhost
- `gulp test:acceptance:wagtail --specs=wagtail/molecules.js --sauce=false`
- `gulp test:acceptance:wagtail --specs=wagtail/wagtail-page-states-pages.js --sauce=false`
- @kave 
=> Fix initial test data script so it does not use DemoPage

CHANGELOG.md, npm-shrinkwrap.json, package.json
Update Capital Framework to get the 60px -> 45px main content change
- `npm install && gulp build` and check out http://localhost:8000/policy-compliance/rulemaking/final-rules/ There should be 45px padding on top of the main content instead of 60px
- @sebworks 
=> Update Capital Framework to latest

CHANGELOG.md, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py
This is the start of the unit testing. For now, this takes care of the v1/wagtail_hooks.py hook called `share_the_page` and its associated functions.
- Tests for `share_the_page` wagtail hook and associated functions 
- Refactored `share_the_page`
- Run `tox`
- @kave 
- Should be 18 additional tests for a total of 42
- Keep on testin'
=> Test share_the_page Wagtail hook and associated functions

cfgov/jinja2/v1/_includes/organisms/secondary-navigation.html, cfgov/unprocessed/css/on-demand/secondary-navigation.less, cfgov/unprocessed/css/organisms/secondary-navigation.less
- Simplifies secondary navigation internal macros to reduce from four to two per @Scotchester suggestion in https://github.com/cfpb/cfgov-sheer-templates/pull/16#issuecomment-218890307
- Fixes issue in on-demand secondary navigation where it was always mobile (thanks to @jimmynotjim for pointing that out).
- Updates documentation.
- `gulp build && gulp scripts:ondemand && gulp styles:ondemand`
Secondary navigation should work in the following contexts:
- wagtail: `/policy-compliance/rulemaking/final-rules/?page=6#o-pagination-content_list`
- non-wagtail: `/about-us/careers/application-process/`
- on-demand: `/test-fixture/?atomic=secondary-navigation`
- @sebworks 
=> Secondary navigation refactoring

CHANGELOG.md, cfgov/jinja2/v1/_includes/macros/filters.html
Acting officers shouldn't be listed in the leadership calendar. Removed them from the list of directors in the calendar filters.
- Silberman and Fuchs from leadership calendar
- Navigate to http://localhost:8000/about-us/the-bureau/leadership-calendar/ and make sure the two acting deputy directors are no longer listed as options. There were no results for them to begin with.
- @sebworks 
- @schaferjh
=> Removed Silberman and Fuchs from Leadership calendar filter

CHANGELOG.md, cfgov/unprocessed/js/modules/util/strings.js, test/unit_tests/modules/util/strings-spec.js
When an author (or any string) contains a period, it is not a valid value. Updated the string validator to check strings for periods. Now the Multiselect will skip initialization and log a helper message if the value contains a period.
- Added period to string validation regex.
- Added a test for the string validation using a period in the test string.
- @kurtw 
We really should get these values fixed in the DB to properly stringified values
=> Fixed a validation bug in the Multiselect

cfgov/jinja2/v1/index.html
Fixes outdated 98% number on homepage to match the current number on the [CCDB landing page](http://www.consumerfinance.gov/data-research/consumer-complaints/): 97%.
- change static text from 98% to 97% to match CCDB landing
- this is a short-term fix in the static content. the permanent fix would update the homepage to reuse the same code that gets this number from the database in the CCDB landing.
=> update 98% to 97% of consumers

cfgov/jinja2/v1/about-us/careers/_macro-table-current-openings.html, cfgov/jinja2/v1/about-us/careers/_single.html, cfgov/jobmanager/models.py, cfgov/jobmanager/urls.py, cfgov/jobmanager/views.py
**I'm going to be gone next week, someone else will probably need to merge it, or make changes if needed**
- use the long region description on the 'current openings' page
- add "office" to the information at the top of job listing, and EEO notice at the bottom
- Restore the usage of URL slugs instead of numeric ID's
- fixes a logic flaw that was causing missing or expired jobs to generate errors (instead of 404's)
Addresses: DFJR-1420, DFJR-1404, most of DFJR-1416, 
@schaferjh this does not fix the spacing issues in 1416
- load this SQL: [jobs.sql.zip](https://github.com/cfpb/cfgov-refresh/files/263953/jobs.sql.zip)
- observe that http://localhost:8000/about-us/careers/current-openings/ shows "Washington, DC" instead of "HQ".
- Click a job, and observe that the 'Office' is listed, and …
=> Jobs fixes

cfgov/unprocessed/js/organisms/FilterableListControls.js, cfgov/v1/atomic_elements/organisms.py
- Updates FilterableListControls to instantiate its internal expandable.
- Removes redundant script includes in the wagtail ondemand script include.
- `gulp build` and `/blog/` should still work.
- @kurtw 
- Organisms should instantiate their own molecules. `expandable.js` should only ever need to be included when there is a standalone expandable on the page.
=> Removes redundant script includes

CHANGELOG.md, test/browser_tests/page_objects/page_blog.js, test/browser_tests/shared_objects/multiselect.js, test/browser_tests/spec_suites/molecules/multiselect.js
There were no tests, fixing that with some baseline tests of: initialization, default results, filtering, clearing results, and keyboard highlighting.
- Multiselect objects for testing
- Tests of basic behaviors
- `gulp test:acceptance --sauce=false --specs=molecules/multiselect.js`
- @sebworks 
- Hit me with other behaviors you think we should test! These seemed like the most important to start with.
- Add even more tests (but don't get so out of hand it becomes brittle).
=> Added browser tests for the multiselect

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/form-field-with-button.html
- Removed wrapping `<p>` tag on a form field's description field output, since it's a rich text field that provides its own markup.
1. Pull down branch
2. Go to any page with an Email Signup organism
3. View source on the info below the field and verify that you're no longer seeing stuff like this:
```html
<p><p>
The information you provide will permit the Consumer Financial Protection Bureau
to process your request or inquiry.
<a href="http://beta.consumerfinance.gov/privacy/privacy-policy/">See More</a>.
</p></p>
```
- @sebworks 
- @jimmynotjim
=> Remove p tag wrapping rich text field

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/half-width-link-blob.html, cfgov/jinja2/v1/_includes/molecules/image-text-25-75.html, cfgov/jinja2/v1/_includes/molecules/image-text-50-50.html, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/_includes/organisms/table.html, cfgov/jinja2/v1/events/_event-detail.html
Rich text fields can have links that need to be dealt with. This also removes that annoying `div class="rich-text"`.
- `parse_links` calls
- Go to each changed module and verify they render safely
- cfgov/jinja2/v1/_includes/molecules/half-width-link-blob.html
- cfgov/jinja2/v1/_includes/molecules/image-text-25-75.html
- cfgov/jinja2/v1/_includes/organisms/post-preview.html
- cfgov/jinja2/v1/_includes/organisms/table.html
- cfgov/jinja2/v1/events/_event-detail.html
- @kave 
=> Wrap parse_links for every RichTextField/Block instance

CHANGELOG.md, cfgov/jinja2/v1/about-us/careers/_single.html
There is extra spacing at the bottom of individual careers between the "Interested in Applying" text and the content that followed. Removed the extra blocks so that the content follows the proper flow.
- Updated markup to remove excess block div.
- ¯\_(ツ)_/¯ I can't seem to get the individual careers locally, but this worked when making the same modifications in the console on www. See screenshot below.
- @schaferjh 
=> Fixed issue with single careers layout

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/global-search.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/js/modules/behavior/FlyoutMenu.js, cfgov/unprocessed/js/modules/util/atomic-helpers.js, cfgov/unprocessed/js/modules/util/standard-type.js, cfgov/unprocessed/js/molecules/Expandable.js, cfgov/unprocessed/js/molecules/GlobalBanner.js, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/molecules/Multiselect.js, cfgov/unprocessed/js/molecules/Notification.js, cfgov/unprocessed/js/organisms/ExpandableGroup.js, cfgov/unprocessed/js/organisms/FilterableListControls.js, cfgov/unprocessed/js/organisms/Footer.js, cfgov/unprocessed/js/organisms/Header.js, cfgov/unprocessed/js/organisms/MegaMenu.js, cfgov/unprocessed/js/organisms/SecondaryNavigation.js, test/browser_tests/spec_suites/organisms/global-search.js, test/unit_tests/modules/FlyoutMenu-spec.js, test/unit_tests/modules/util/atomic-helpers-spec.js
- Adds initialization flag for atomic components so that they bail out of their `init` function if it has already been called.
- `gulp build` and inspect the page. Any atomic component should have `data-js-hook="[atomic base class] init"` attributes.
- In Wagtail, it should be possible to add an expandable and an expandable group to a page, or expandable and secondary navigation, and they will both still work.
- @kave
- @kurtw 
- @sebworks
=> DFJR-994 Adds initialization flag for atomic components

cfgov/jinja2/v1/newsroom/press-resources/index.html, test/browser_tests/spec_suites/newsroom-press-resources.js
Adding Fix for email address on Press Resource page
- Changed the email address on the Press Resource page. 
- Visit `http://localhost:8000/about-us/newsroom/press-resources/` and click on the `press@consumerfinance.gov`. It should a mail client with the address set to `press@consumerfinance.gov`.
=> Adding Fix for email address on Press Resource page

.env_SAMPLE, CHANGELOG.md, cfgov/cfgov/settings/base.py, cfgov/v1/wagtail_hooks.py, requirements/base.txt
There was a need to purge the akamai cache when a page was published, this integrates the work done here https://github.com/cfpb/publish_eccu to purge the cache by url.
It will then either send an email to the publishing user to alert them of a successful cache flush or IT rep email set.
- Ability to refresh akamai cache on page publish
- Keep in mind this style of flushing can take upto 20-40mins to resolve vs the entire cache flush of < 10mins
- Reach out to me for environmental variables for beta site
```
#export ENABLE_AKAMAI_CACHE_PURGE=<boolean_enable_purging_akamai_cache>
#export AKAMAI_USER=<akamai_username>
#export AKAMAI_PASSWORD=<akamai_password>
#export AKAMAI_NOTIFY=<akamai_notify_email>
#export AKAMAI_HOST=<akamai_hostname>
```
- Import Refresh db dump
- login into beta …
=> Automate content updates from Wagtail

CHANGELOG.md, cfgov/cfgov/urls.py, cfgov/legacy/views.py
- Missing token provider for forms submitted by JS
- Ensure self-registration is installed
- clone private repo as a sibling CFPB/cfgov-selfregistration
- `pip install -e ../cfgov-selfregistration`
- visit this [page](http://localhost:8000/company-signup/)
- submit information
=> Missing token provider for forms submitted by JS

CHANGELOG.md, cfgov/jinja2/v1/_includes/macros/video-player.html, cfgov/unprocessed/js/modules/UStreamPlayer.js, cfgov/v1/models/learn_page.py
Adding Validation code and url param fix for UStream player
- Added validation code to Wagtail to validate Ustream embed  link.
- Changed `cfgov/jinja2/v1/_includes/macros/video-player.html` logic to add `html5` param so the user doesn't have to via Wagtail.
- Changed `cfgov/unprocessed/js/modules/UStreamPlayer.js` to fix broken uStream script embed link.
- Changed `cfgov/jinja2/v1/_includes/macros/video-player.html` to fix issue displaying default image.
-  Create a live Event via wagtail by altering the start date/end date. Enter the following url `http://www.ustream.tv/channel/1524` under the `LIVE STREAM INFORMATION` section. Click `Save Draft`. You should get a validation error.
- Change the url to `http://www.ustream.tv/embed/1524`. Click `Save Draft`. It should have saved the …
=> Adding Validation code and url param fix for Ustream player

test/browser_tests/page_objects/page_careers-application-process.js, test/browser_tests/page_objects/page_the-bureau.js, test/browser_tests/shared_objects/video-player.js, test/browser_tests/spec_suites/careers-application-process.js, test/browser_tests/spec_suites/the-bureau.js
Adding Acceptance tests for the Video Player
- Added `test/browser_tests/shared_objects/video-player.js` to allow pages that have video player functionality to easily add the video-player element references. 
- Added basic interaction tests for the video player to `test/browser_tests/shared_objects/video-player.js`, and `test/browser_tests/spec_suites/the-bureau.js`.
- @kave 
- Not sure how to test the video player on Wagtail pages ( Events ). Maybe you can help me with that @kave?
- Add video player tests to the Archive/Live Events page.
=> Adding Acceptance tests for the Video Player

CHANGELOG.md, cfgov/unprocessed/css/enhancements/typography.less, cfgov/unprocessed/css/molecules/full-width-text.less
The full-width text molecule always lives within a block, which has 60px of bottom spacing. The addition of bottom spacing to the last child of the full-width text molecule was being stacked with the block’s 60px increasing the space more than spec’d. Removing the bottom margin from the last child of the full-width text molecule fixes this issue.
- Forced the last child of a full-width text molecule to remove any set padding.
- `gulp build` and check out http://localhost:8000/about-us/project-catalyst/. The paragraph wrapping `Get the data` should have 0 bottom margin.
- @sebworks 
- Thanks to @Scotchester for reporting this bug
=> Fixes issue with spacing after the last item in a full-width component

CHANGELOG.md, cfgov/unprocessed/js/modules/ContentSlider.js, cfgov/unprocessed/js/modules/util/atomic-helpers.js, cfgov/unprocessed/js/molecules/Expandable.js, cfgov/unprocessed/js/organisms/ExpandableGroup.js, cfgov/unprocessed/js/routes/about-us/the-bureau/bureau-structure/index.js, test/browser_tests/page_objects/page_bureau-structure.js, test/browser_tests/spec_suites/bureau-structure.js, test/unit_tests/modules/util/atomic-helpers-spec.js
- Adds `destroyInitFlag()` method to `atomic-helpers.js`.
- Adds `destroy()` method to `Expandables.js` to allow reversing calls to `init()`.
- Fixed issue where cloned expandables were not initializing on the bureau structure page.
- Removed `self` references in ContentSlider. (Part of https://github.com/cfpb/cfgov-refresh/issues/571)
- Adds extra small tests to bureau structure page.
- `gulp test:acceptance --sauce=false --specs=bureau-structure.js --windowSize=480,900` should pass.
- http://localhost:8000/about-us/the-bureau/bureau-structure/ at mobile and desktop should work as expected (nodes and expandables expand).
- @sebworks 
=> Fixes init flag issue in cloned nodes

CHANGELOG.md, cfgov/v1/models/base.py
View more link to Activity log from a page with tags that are not in the Activity log causes filter to give error.
- Generates the list of tags to check against when forming the link
-Visit http://www.consumerfinance.gov/policy-compliance/rulemaking/final-rules/fair-credit-reporting-act-disclosures/
http://www.consumerfinance.gov/policy-compliance/ , go to the View more link, notice the error
- go to them locally and visit the link without problems on the activity log
- @kave 
=> Check against Activity Log topics when generating View More link

test/browser_tests/page_objects/page_leadership-calendar.js, test/browser_tests/spec_suites/leadership-calendar.js
More browser tests for filters on sheer pages. (Which are only on the leadership calendar page as far as I know.)
- `gulp test:acceptance --sauce=false --specs=leadership-calendar.js`
- @sebworks 
- I'd ideally like to test the filters themselves, but I ran into a roadblock testing the page when the page changes and decided against adding a potentially fragile test.
=> Sheer filters Acceptance Tests

CHANGELOG.md, cfgov/v1/__init__.py
This should fix the issue along with the other fields that we haven't been catching either.
- Use bare value of RichText field if value type is not RichText
- Add link to a Contact's body field and view it in a sidebar on a page. Make sure the link is valid.
=> Use bare value of RichText field if value type is not RichText

CHANGELOG.md, cfgov/v1/__init__.py
This fixes the viewing of internal links in contact snippets.
Note: you will need to make sure the below page is published locally if it isn't already.
On flapjack, if you navigate to [http://localhost:8000/policy-compliance/guidance/interstate-land-sales-registration/](http://localhost:8000/policy-compliance/guidance/interstate-land-sales-registration/), you'll notice that the "FOIA office" link under Contact Information is broken.
On this branch, navigate to it and the link should work.
@kave @kurtw
=> Wagtail requires a richtext filter for richtext fields

.gitignore, CHANGELOG.md, README.md, gulp/tasks/docs.js, gulp/tasks/test.js, gulp/utils/fs-helper.js, package.json
Put together while traveling. Adds initial ability to generate docs from code jsdocs.
- Adds `gulp docs` task to generate code docs for JavaScript.
- `./frontend.sh`
- `gulp docs`
- open html page in `docs/scripts/index.html`
- @sebworks 
- @Scotchester
=> Adds task to generate JS docs

cfgov/jinja2/v1/_includes/molecules/social-media.html
- Add default value for `value` back in from https://github.com/cfpb/cfgov-refresh/pull/2117, otherwise non-wagtail pages that use the social media molecule fail (e.g. /about-us/the-bureau/about-director/)
- `gulp test:acceptance --sauce=false`
- @kave 
- @kurtw 
- Not sure if there's a better way to provide the default, but this seems to work inside and out of wagtail.
=> Hotfix: Add value default back

CHANGELOG.md, cfgov/jinja2/v1/events/_event-detail.html
@sarahsimpson09 said that the email reservations for the Events is deprecated and will be replaced by a form unique to the event in the future.
- RSVP button
- Visit a future event page and witness the page without the button.
- @kave 
- @sebworks
=> Removes the RSVP button on Event pages

CHANGELOG.md, cfgov/unprocessed/js/modules/ClearableInput.js, cfgov/unprocessed/js/modules/ExternalSite.js, cfgov/unprocessed/js/modules/util/atomic-helpers.js, cfgov/unprocessed/js/molecules/Expandable.js, cfgov/unprocessed/js/molecules/GlobalBanner.js, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/molecules/Notification.js, cfgov/unprocessed/js/organisms/ExpandableGroup.js, cfgov/unprocessed/js/organisms/FilterableListControls.js, cfgov/unprocessed/js/organisms/Footer.js, cfgov/unprocessed/js/organisms/Header.js, cfgov/unprocessed/js/organisms/MegaMenu.js, cfgov/unprocessed/js/organisms/SecondaryNavigation.js, test/unit_tests/modules/util/atomic-helpers-spec.js
`atomicName` parameter was passed around purely to provide a more descriptive error message. However, the class name can be used instead, since—if the atomic naming is correct—the class name will include the atomic name. This simplifies the atomic helper utilities.
- `atomicName` parameter from `atomicHelpers.checkDom`.
- Updates associated calling code and tests.
- `gulp test:unit:scripts` should pass. `gulp build` and no change in site functionality.
- @sebworks 
- @jimmynotjim
=> Remove `atomicName` parameter

test/unit_tests/modules/ClearableInput-spec.js
Oops, noticed a console.log slipped through and is logging "value" in the unit test output.
- Removes console.log statement from unit test.
- `gulp lint:tests` should have no errors.
- @sebworks 
- @jimmynotjim
=> Removes console.log statement

cfgov/jinja2/v1/test-fixture/index.html
Remove meta stuff from private test-fixture path.
meta elements for open graph and favicon aren't needed on private path for on-demand components.
- open graph meta.
- description meta.
- favicon.
- @sebworks
=> Remove meta stuff from private test-fixture path

test/unit_tests/modules/util/data-set-spec.js
Adding unit tests for data-set utility
- Adding unit tests for data-set utility
- Run `test:unit:scripts`
- This unit test doesn't include referencing the native dataset property, as it's not supported by jsdom. I don't have a great way to test that yet.
=> Adding unit tests for data-set utility

CHANGELOG.md, cfgov/jinja2/v1/_includes/organisms/secondary-navigation.html, cfgov/jinja2/v1/_layouts/content-base-sidebar-first.html, cfgov/v1/__init__.py, cfgov/v1/models/base.py, cfgov/v1/tests/test_util.py, cfgov/v1/util/util.py, tox.ini
This PR fixes two bugs brought up by @Scotchester. 
- Breadcrumb and sidenav generation used to get the page titles from the Page table in the database, leaking saved edits to `title` that were not shared or published.
- Breadcrumb and sidenav items that were previously shared but then had edits saved would return `None` as their URL. 
- `get_appropriate_page_version` function in utils.py that grabs the page version based on revision history and request hostname.
- `get_breadcrumbs` method on CFGOVPage and `get_secondary_nav_items` function in utils.py now use `get_appropriate_page_version`.
- Get the latest from prod database OR share a Sublanding page with a Browse page as a child. The breadcrumb should be in the top left under the mega menu.
- **BEFORE PULLING DOWN**
- Edit the title …
=> Breadcrumb and sidenav generation gets most appropriate page version

gulp/tasks/browser-sync.js, gulp/tasks/watch.js
All our gulp tasks are lowercase, except for `gulp watch:browserSync` ... seems like when we're talking about typing in the command line, keeping everything lowercase will be easier.
- downcases `gulp watch:browserSync` to `gulp watch:browsersync`
- `gulp --tasks` are all lowercase.
- @sebworks
=> Downcase gulp tasks

cfgov/unprocessed/js/modules/behavior/FlyoutMenu.js, cfgov/unprocessed/js/modules/util/atomic-helpers.js, cfgov/unprocessed/js/modules/util/behavior.js, cfgov/unprocessed/js/modules/util/data-hook.js, cfgov/unprocessed/js/organisms/MegaMenu.js, test/unit_tests/modules/FlyoutMenu-spec.js, test/unit_tests/modules/util/behavior-spec.js
- Removes unneeded constant exports from FlyoutMenu.
- Moves behavior DOM check to utility method.
- Removes TODO for atomic-helper, as behavior shouldn't use that for clarity.
- `gulp build && gulp test:unit && gulp test:acceptance --sauce=false`
- @sebworks 
- Adds to `/util/behavior.js` created in https://github.com/cfpb/cfgov-refresh/pull/2118
=> Moves behavior dom check to utility

cfgov/jinja2/v1/_includes/molecules/text-introduction.html, cfgov/jinja2/v1/_includes/templates/render_block.html, cfgov/jinja2/v1/browse-basic/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/jinja2/v1/landing-page/index.html, cfgov/jinja2/v1/learn-page/index.html
The "Has rule" option in the Text Introduction module wasn't actually doing anything. This PR fixes that.
- Documentation of `has_rule` option to Text Introduction template
- Updates the `render_block` macro to add `.block__padded-bottom.block__border-bottom` to the `div` if it finds a truthy `has_rule` option in the block it's rendering.
- Updates several template files to use `render_block` in all cases where they should be.
- Standardizes `import` rules at the top of the file. _(Let me know if this was a bad idea.)_
Verifying bug:
1. Check the "Has rule" option in a Text Introduction module in any Wagtail page.
2. Preview the page and see that no rule is added below the module.
Verifying fix:
1. Pull branch.
2. In your local Wagtail, 
3. Publish the page and view the result. It now has …
=> Make TextIntroduction's has_rule functional

cfgov/jinja2/v1/_layouts/content-base-main-first.html
This fixes an issue we were seeing on several pages that `'Site' object has no attribute 'site'`. @kurtw I assume when you renamed `site` to `request`, this was simply an oversight. https://github.com/cfpb/cfgov-refresh/commit/b30c2ec6c6223f9557aab57588fa529e0c66593c  Tests should all pass now! 
@rosskarchner @jimmynotjim
=> Fix issue that probably came about from renaming site --> request 

CHANGELOG.md, cfgov/jinja2/v1/_includes/molecules/featured-content.html
There's too much spacing between the FCM category slug and the FCM heading. In accordance with the updated markup recommendations in cfpb/capital-framework#320, this PR fixes that.
- FCM category markup from `p.h4` to `div.category-slug`
- Some minor CHANGELOG cleanup
1. Pull branch
1. Reload a local page with an FCM
- @sebworks 
See cfpb/capital-framework#320
=> Change class of FCM category slug to remove extra spacing

CHANGELOG.md, cfgov/jinja2/v1/test-fixture/index.html, gulp/tasks/styles.js
As part of #2156, we need a stylesheet without the small screen styles for limited sections of the site that aren't yet updated. Updated the ondemand gulp task to write a separate nonresponsive stylesheet.
- Updated gulp task to write both responsive and non-responsive styles for ondemand needs.
- Updated the test fixture for ondemand includes to allow for the nonresponsive stylesheet to be loaded for visual testing.
- `gulp styles:ondemand` and navigate to `http://localhost:8000/test-fixture/?atomic=header&suffix=nonresponsive`. Header should keep the large screen styles (though the menu will still go offscreen due to JS, upcoming fix for that).
- It's looking like we'll need to separate out the small screen vs large screen menus to …
=> Created non-responsive on-demand styles for non-v1 sections of the site.

CHANGELOG.md, cfgov/jobmanager/views.py
Nothing is using it.
- Jobmanager view function 
- @kave 
=> Remove unused jobmanager view function for gov delivery

cfgov/v1/forms.py, cfgov/v1/tests/test_forms.py
- tests for FilterableListForm in v1/forms.py
- Run `tox -- v1.tests.test_forms`
- @kave 
- Make tests for `FilterableListForm.render_with_id` work
=> Add tests for FilterableListForm

CHANGELOG.md, cfgov/v1/models/base.py
`set` makes the JS files list from the unique but since it is unordered it can interfere with the JS instantiation. This uses OrderedDict (since python has no built-in implementation of something like OrderedSet) to get both order and uniqueness.
- OrderedDict replaces set in use of maintaining uniqueness and order.
- Add ExpandableGroup to a page and test its functionality.
- @Scotchester
=> Change page.media to use OrderedDict

test/browser_tests/spec_suites/activity-log.js, test/browser_tests/spec_suites/blog.js, test/browser_tests/spec_suites/leadership-calendar.js, test/browser_tests/spec_suites/newsroom.js, test/browser_tests/spec_suites/organisms/mega-menu.js
This updates failing tests at the small breakpoint for filters and adds
tests for the mega menu at small breakpoints. 
Finishes up with a failing test for keyboard tabbing on mobile. Ideally,
tabbing should trap focus on a menu until something is selected.
`gulp test:acceptance --sauce=false --windowSize=400,610`
- @jimmynotjim
=> Updating mobile tests and adding mega menu tests

cfgov/cfgov/settings/base.py
- Removes check for 'condition' flag on optional apps b/c it is no longer used
- Updates imports of optional apps
- @kave @kurtw @rosskarchner
=> Updating imports of optional apps.  Condition flag is no longer used.
