cfpb/consumerfinance.gov

- README.md
Fixes typo in Readme screenshot URL.
> Fixes typo in Readme screenshot URL

- Gruntfile.js
- _includes/event-post-macros.html
- _includes/events-posts.html
- events/index.html
- static/css/event-docs.less
- static/css/main.less
Added the Event list pattern 
- Added events-docs.less
- Added event-post-macros.html
- Added events-posts.html
- None
- Updated the object passed to `post_related.render()`
- Updated the list of related links
Navigate to
- events/spring-2014-rulemaking-agenda/
- @sebworks 
- Wasn't Able to convert UTC to local for time element
- Calendar Icon/Title needs some cleanup
> Fixes df-1461/ Event List

- static/css/event-docs.less
> Fix for line break on mobile

- the-bureau/about-rich-cordray/index.html
- the-bureau/about-steve-antonakes/index.html
Updated directors Download/Request section
- None
- Removed hide on mobile style for D Antonakes
- Reorganized links to use link-list pattern
Navigate to:
- /the-bureau/about-rich-cordray/
- /the-bureau/about-steve-antonakes/
- @duelj 
- @sebworks 
- Fixes #281
> DF-1502-directors-pattern

- _includes/tags.html
- events/_event-post-macros.html
Refactoring Event related macros
- Updates '_event-post-macros.html' file to allow for more flexible date, time, and address formats.
- Updates 'tags.html" file to simplify logic and Fix #295.
> DF-1531-Refactoring Event related macros

- _includes/tags.html
- events/_event-landing-macros.html
- events/_event-post-macros.html
- events/_event.html
- events/index.html
- static/css/calendar-icon.less
- static/css/cf-enhancements.less
- static/css/event.less
- static/css/modification-date.less
Clean up for the events landing and detail page
- Update '_event-landing-macros.html' file to clean up line lengths and unnecessary arguments being passed.
- Update 'tags.html" file to simplify logic.
- Update '_event.html' file to remove pad from modification date and add make video link block.
- Update 'index.html' file to add top padding to event list.
- Update 'calendar-icon.less' file to cleanup styles.
- Update 'event.less' file to cleanup styles.
- Update 'modification-date.less' to cleanup styles.
> DF-1545-Events-page-cleanup

- budget/index.html
- doing-business-with-us/index.html
- the-bureau/index.html
Update static content from Content Team
- None
- None
- Updated `/the-bureau` with static content changes
- Updated `/budget` with static content changes
- Updated `/doing-business-with-us` with static content changes
Locally navigate to:
- /the-bureau
- /budget
- /doing-business-with-us
- @jameshupp 
- @sebworks 
- There's some extra markup that could use some cleaning. Kind of outside the scope here but I'm going to add it to the Github issue tracker before merging this
> Df 1503 update content

- events/_event-post-macros.html
- events/archive/index.html
Adding pagination to Event Archvie landing page
> Adding pagination to Event Archvie landing page

- _includes/tags.html
- static/css/calendar-icon.less
Minor code cleanup.
- Removes minor topdoc comment typo.
- Fixes #296 - moves CSS comment.
- @sebworks
> Code cleanup

- _includes/tags.html
- events/index.html
- static/css/event.less
Fixes for the events landing and detail pages
- Update 'tags.html' file to make booleans lowercase.
- Update 'index.html" to move import statement outside loop.
- Update 'events.less' file to remove font value and replace within mixin. Closes #299
> Fixes for Df-1506

- events/_event-landing-macros.html
- events/_event-post-macros.html
- static/css/event.less
Fix Event List markup
- Updates '_event-landing-macros.html" file to change markup for new media object.
- Updates 'events/_event-post-macros.html' file to change google image size.
- Updates 'event.less' file to accomodate to new media object.
et al
> Fix for Events list markup

- static/css/event.less
Replacing '@' with em dash
- Updates '/event.less' file to change @ to em dash.
et al
> Revisions for Sprint Review

- events/archive/index.html
- events/index.html
Fixes for JIRA issue DF-1600
- Adjusts spacing on Archive Landing page filters to match mockup.
- Fixes issue with filter results displaying no results.
- Updates 'events/archive/index.html' file to spacing and results issue.
- Updates 'events.less' file to fix spacing issue.
> Fix for Filter Issues

- the-bureau/about-rich-cordray/index.html
Updates blog and calendar minicons on Director Cordray's page.
- Changes blog minicon to speech bubble.
- Changes calendar minicon to calendar date.
- Visit /the-bureau/about-rich-cordray/
- @sebworks 
- @duelj
> Fixes DF-1586 - corrects minicons

- newsroom/press-resources/index.html
Fixes broken link on press resources page.
- Updates broken link.
- Visit /newsroom/press-resources/
- @sebworks 
- @jimmynotjim
> Fixes DF-1635 - broken link

- newsroom/_single.html
Updated press resources link to domain relative url
None
None
- Updated press resources link to domain relative url in single template
Navigate to the following and click the press resources link after the article
- /newsroom/cfpb-takes-action-against-realtysouth-for-mortgage-disclosure-violations/
- @jameshupp 
- @sebworks 
None
None
> Updated press resources link to domain relative url

- doing-business-with-us/index.html
- static/css/business.less
- static/css/main.less
Add rule and adjust spacing on mobile for 'Doing Business with Us' pages.
- Updates 'doing-business-with-us/index.html' file to add rule and adjust spacing on mobile.
- Updates 'static/css/main.less' file to include new less file.
- Adds 'static/css/business.less' file to add rule and adjust spacing on mobile. 
et al
> Fix for DF-1567

- _includes/header.html
Updates link text.
- Changes header navbar text "Working with us" to "Doing business with us."
- Visit the landing page and hover over the navbar.
- @sebworks 
- @jimmynotjim
> DF-1646 - Fixes header link text

- _settings/eslint.yaml
Very minor code comment update in eslint file.
- Adds missing period in code comment.
> Add period to code comment.

- doing-business-with-us/small-businesses/index.html
- static/css/bureau-structure.less
- static/css/business.less
Fix expandable cue position for multi-line text on Small Business page.
- Updates 'doing-business-with-us/small-businesses/index.html' file to add additional class.
- Updates 'static/css/business.less' file to adjust position of expandable cue.
> Fix for DF-1576: Small Business page nav

- contact-us/_vars-contact-us.html
- contact-us/mailing-addresses.html
Display hard coded contact information :
- Updates ' contact-us/_vars-contact-us.html' file to add hard coded data.
- Updates 'contact-us/submit-a-complaint.html' file to display hard coded data.
> DF-1643: Hard Code Contacts

- static/css/header.less
Disable header link 
- Updates ' static/css/header.less' file to disable link.
> Fix for Espanol link

- _includes/footer.html
- static/css/footer.less
- static/css/header.less
Update Footer to match new design
- Updates ' _includes/footer.html' file to match new design.
- Updates ' static/css/footer.less' file to match new design.
- @ajbush
> DF-1664: Footer Update

- activity-log/index.html
Replaced Lorem with intro sentences for Activity Log.
> Activity log intro text

- _lib/wordpress_post_processor.py
- _tests/browser_testing/fixtures/newsroom.json
- _tests/processor_tests/tests/test_wordpress_post_processor_post.json
- events/_vars-events.html
Fixes issue caused by new Author taxonomy
- Updates ' _lib/wordpress_post_processor.py' file to use new taxonomy.
- Updates ' _tests/browser_testing/fixtures/newsroom.json' file to use new taxonomy.
- Updates ' events/_vars-events.html' file to use new taxonomy.
- @dpford 
- @Scotchester
> Fixes issue caused by new Author taxonomy

- _includes/footer.html
- _includes/header.html
- index.html
████████ ████ ████ 
- ██████
- ████████
- ████ 
- ██████
- ████ ████ ████████ 
- @███
- @██████
- @████
████ ██████ ██
- ████ ██ ████████
> Redact the things

- the-bureau/index.html
It should always be "Richard" in formal descriptions.
> Edit on Cordray intro for The Bureau

- the-bureau/leadership-calendar/index.html
* Make intro more accurate
* Real language for download instructions
> Update calendar text

- budget/performance-plan-report/index.html
Real text for lorem ipsum
Added "annual" and "and" to the title, which more accurately reflect both the contents and the reason someone might want to look at it, having ever looked at it before
> Updated performance plan report

- budget/strategic-plan/index.html
* Strategic plan doesn't contain any performance plan or report, so changed the labeling text
* Added real content for the intro
> Content changes to strategic plan

- doing-business-with-us/index.html
Fixes readability issue #407 
- Updates 'doing-business-with-us/index.html' file to stack classes for readability purposes.
@jimmynotjim 
None
None
> Fixes readability issue #407

- index.html
- the-bureau/about-rich-cordray/index.html
- the-bureau/about-steve-antonakes/index.html
Replaces unneeded HTML escape codes.
- Removes excess whitespace.
- Fixes #404 - replaces unneeded HTML escape codes with actual apostrophes. Not needed since page is in
utf-8.
- @sebworks
> Fixes #404 - unneeded HTML escape codes.

- _layouts/base.html
Updates disclaimer text.
- Fixes DF-1678 - updates beta disclaimer text.
- Visit landing page.
- @sebworks 
- @juidai
> Fixes DF-1678 - updates beta disclaimer text

- budget/financial-report/index.html
Updated placeholder text at `/financial-report` with true text from content team.
- intro at /financial-report
Navigate to:
- /financial-report
- @jameshupp 
- @juidai 
- @sebworks 
None
> Bugfix - Updated Lorem content at /financial-report

- static/css/footer.less
Adjust font-size of label in footer to adhere to design spec.
- Updated 'static/css/footer.less' to adhere to design spec.
- @sebworks 
None
> Footer Adjustment

- index.html
> Fixing typo - "learn about out projects"

- _includes/post-macros.html
Fixes issue #430 (Filter breaking on space)
- Updated '_includes/post-macros.html' to fix whitespace issue.
> Filter Breaking on Whitespace

- _includes/popular-stories.html
- _includes/related-posts.html
- newsroom/index.html
- static/css/post.less
Update Newsroom and Blog post sidebars
- Updated ' _includes/popular-stories.html' to add description and date.
- Updated ' _includes/related-posts.html'  to add description and date.
- Updated ' newsroom/index.html' to add class.
- Updated ' static/css/post.less' to change link style in sidebar.
> Fixes #DF-1732 Blog/Newsroom Sidebar Update

- the-bureau/index.html
Fixes HTML issues in the-bureau page.
- Removes extraneous whitespace.
- Fixes #443 - fixes typo.
- Fixes unclosed `<p>`.
- Visit /the-bureau/
- @sebworks 
- @jimmynotjim
> Cleans up bureau HTML

- _includes/popular-stories.html
- _includes/related-posts.html
Removing Copy from sidebar
- Updated '  _includes/popular-stories.html' to remove copy text.
- Updated '  _includes/related-posts.html' to remove copy text.
> Removing Copy form sidebar

- doing-business-with-us/index.html
Making a language change on the DBWU main page to mirror the internal edit.
> Doing Business with Us stakeholder edits 2

- doing-business-with-us/future-requests/index.html
* Edits to intro paragraph
* Fixed one typo from earlier language
* Rename page (will have to make a separate edit/file an issue on the sidebar title)
> Doing Business with Us stakeholder edits

- _layouts/404.html
* Moves the pun to the title in place of "Oops" and softens it a bit.
* Softens the instructional nature of the intro.
* More accurate on why to contact us, given the nature of this status message.
* @sarahsimpson09 
* @sebworks
> 404 content edit

- _lib/wordpress_event_processor.py
- _settings/blueprints.json
- _settings/events_mappings.json
- _settings/processors.json
- _tests/processor_tests/tests/test_wordpress_event_processor.json
- _tests/processor_tests/tests/test_wordpress_event_processor.py
This is the initial work on the event processor. It takes an event from the WordPress API, pulls out the WordPress custom fields and exposes them at the top-level of the document that will be stored in Elasticsearch. This includes a test case that ensures that all the custom fields are added as such. 
This PR also includes the addition of the [flask-eventics](https://github.com/cfpb/flask-eventics) blueprint.
**Additions**
- Event content processor
- Test case for the content processor
- Event icalendar file generation (via flask_eventics
**Testing**
To run Sheer with this PR, flask-eventics will have be installed. That can be done using
`pip install git+https://github.com/cfpb/flask-eventics`
From the root of a cfgov-refresh clone, with a virtualenv capable of running Sheer and serving …
> Initial event content processor

- _layouts/404.html
* Updated the title and description to be slightly more descriptive, if not excitingly so.
* Made the 404 error message the h1, similar to the 500.
@Scotchester 
@jimmynotjim
> Putting the 404 back in 404 pages

- _layouts/500.html
* More 500-specific intro
* @sarahsimpson09 
* @sebworks 
* I don't think I've mis-described a 500 error.
* Until further notice, the FEWD I'm going to include as reviewer is the most recent person to edit it.
> 500 content edit

- static/js/app.js
- static/js/main.js
Fix for code consistency
- Updated '  static/js/app.js' to provide better code consistency.
- @jimmynotjim
> Fix for code consistency

- CHANGELOG.md
- _includes/footer.html
- _includes/header.html
Added Contact Us to navigation
- None
- None
- Reverted navs from Contact Us redacting
- Find Contact Us in header and footer navigation
- @sebworks 
- None
> Added Contact Us to navigation

- budget/_vars-budget.html
- budget/financial-report/index.html
- budget/funding-request/index.html
- budget/index.html
- budget/performance-plan-report/index.html
- budget/strategic-plan/index.html
* adding ampersands to H1s and side nav titles
* pluralizing reports and requests and any other words like that in H1s
* changing B&S index language to more accurately reflect proactive values
* fixing other minor copy issues like noun/pronoun incongruities, extra periods, incorrect capitalization
@sarahsimpson09 
@jimmynotjim 
No rush on this. But at some point these updates needed to happen.
> Budget strategy update

- CHANGELOG.md
Updating change log for :
PR #528 
PR #529 
- Updated  ' CHANGELOG.md' .
> Adding Change Log comments

- CHANGELOG.md
- initiatives/foia-faqs/index.html
- offices/_single.html
- offices/foia-requests/index.html
A few tweaks on the front-end for FOIA Requests and the FOIA Faq placeholder page
- Added a custom FOIA Faqs page with all placeholder content.
- Made a few tweaks to the office template
- Pulling in "FOIA" themed posts on that office page.
- Visit /offices/foia-requests
- Click on FOIA Faqs.
- @sebworks 
> Foia tweaks

- README.md
Updated wording for `setup.sh` file
- Added a better description to what `setup.sh` is doing
None
None
Checkout the readme
- @sebworks 
None
None
> Updated wording for setup.sh file

- CHANGELOG.md
- external-site/index.html
> Fixing typo and incorrect entry to changelog

- README.md
- external-site/index.html
- src/static/js/modules/jquery/cf_formValidator.js
- sub-pages/submit-a-request/index.html
Minor cleanup from comments in https://github.com/cfpb/cfgov-refresh/pull/606
- Fixes various spacing, code comment and readme updates from the last sprint PR.
- No change.
- @sebworks
> Sprint cleanup

- external-site/index.html
"Reload" isn't accurate, at least from user's perspective.
> Small copy tweak

- CHANGELOG.md
- _includes/contact-macro.html
- _lib/wordpress_contact_processor.py
- _lib/wordpress_featured_topic_processor.py
- _lib/wordpress_office_processor.py
- _lib/wordpress_post_processor.py
- _lib/wordpress_sub_page_processor.py
- _lib/wordpress_view_processor.py
- _settings/mappings/history.json
- _settings/mappings/newsroom.json
- _settings/mappings/orgmember.json
- _settings/mappings/posts.json
- contact-us/general-inquiries.html
- contact-us/index.html
- contact-us/submit-a-complaint.html
- newsroom/featured-topic.html
Fixes some bugs in some processors and fix a link in the newsroom's featured topic section.
@dpford
> Fix some bugs

- CHANGELOG.md
- _lib/wordpress_faq_processor.py
- _settings/mappings/faq.json
- _settings/processors.json
This adds the FAQ post type in Wordpress into the elasticsearch index.
@dpford 
@sebworks
> Add FAQ processor and mapping

- CHANGELOG.md
- _lib/wordpress_sub_page_processor.py
- _settings/mappings/sub_page.json
This adds the field to determine if the sub-page has a form to show. The field can be accessed like so: sub_page.use_form`. 
@dford
@sebworks
> Add use_form field for sub-pages that have forms

- sub-pages/_single.html
- Added body_content block
- Added content_main modifier
- Stacked css classes
- Added check for empty sub_pages.
- Updated  'sub-pages/_single.html' to add content block and add minor tweaks.
- Visit 'http://localhost:7000/sub-pages/file-a-privacy-complaint/'
- @anselmbradford  
- @kurtw
> Fixes for /sub-pages

- offices/_single.html
- offices/foia-requests/index.html
- Added code to display preview text
- Added code to use tags for activity feed
- Added code to make office titles dynamic
- Updated  'offices/_single.html' to fix links and tags.
- Removed 'offices/foia-requests/index.html'  as it is no longer necessary because using tags for the activity feed.
- Visit 'http://localhost:7000/offices/*'
- @anselmbradford  
- @kurtw
> Fixes for Offices Page

- CHANGELOG.md
I forgot to include this in #680. :fearful:
> Changelog update for students page

- _includes/templates/forms/amending-and-correcting-records-under-the-privacy-act-form.html
- _includes/templates/forms/file-a-privacy-complaint-form.html
Adds TODO comments to incomplete markup.
- Adds `TODO:` comments to forms.
- @sebworks 
- Sprint 30 cleanup.
> Adds TODO comments for incomplete markup

- _includes/templates/footer.html
Updating Footer links
- Updated  '_includes/templates/footer.html' to include links for CFPB Ombudsman, Careers, FOIA, Plain Writing, and Privacy.
- Visit 'http://localhost:7000/'
@jimmynotjim
@KimberlyMunoz
@schaferjh
> Updating Footer Links

- _includes/post-macros.html
Fixes typo in macro. 
- Fixes https://github.com/cfpb/cfgov-refresh/issues/670 - typo in code.
- @sebworks 
> Fixes typo

- CHANGELOG.md
- careers/application-process/index.html
- transcripts/how-to-apply-for-a-federal-job-with-the-cfpb/index.html
Adding the transcript for the application process
- Added Transcript folder and a transcript for *Applying for a federal job with the CFPB*
- http://localhost:7000/transcripts/how-to-apply-for-a-federal-job-with-the-cfpb/
- @sebworks 
- I create a separate folder for these transcripts and it's very barebones. Is this enough? Do we add breadcrumbs? Leave your feedback below in emoji.
> Adding transcript for Application Process

- CHANGELOG.md
- index.html
Updated the progress charts on the homepage to be more in line w/ where we're at
None
None
Updated percentages based on recent updates
- homepage
- @schaferjh 
- @sebworks 
- These are guesstimates based on today's In-Progress Review, feel free to question them
> Updated the progress charts

- CHANGELOG.md
- _includes/post-macros.html
Fix for filters
- Updated  '_includes/post-macros.html' to add fix for filters.
- Visit 'http://localhost:7000/blog' and select some filter criteria. 
@jimmynotjim
@KimberlyMunoz
@kurtw
> Fix for filters

- CHANGELOG.md
- _lib/django_career_processor.py
- _queries/careers.json
- _settings/mappings/career.json
- _settings/processors.json
This pulls the django job data into elasticsearch for availability in the jinja2 templates.
@dpford @jimmynotjim
> Create Job processor/mapping from django rest api

- src/_includes/contact-macro.html
- src/_includes/macros/util/format.html
- src/_includes/post-macros.html
This was #748-- I thought I could re-create the branch without closing the pull request.
> Support for django-sheerlike: less code this time

- CHANGELOG.md
Changelog entries were erroneously in the latest release when they should have been in the unreleased section.
- Moves changes not on beta to unreleased section.
- @sebworks 
> Fixes erroneous Changelog ordering

- CHANGELOG.md
- Gruntfile.js
- test/browser_tests/.eslintrc
- test/browser_tests/conf.js
- test/browser_tests/environment.js
- test/browser_tests/page_objects/page_careers-students-and-graduates.js
- test/browser_tests/page_objects/page_contact-us.js
- test/browser_tests/page_objects/page_the-bureau.js
- test/browser_tests/spec_suites/large_screen/large_contact-us.js
- test/browser_tests/spec_suites/shared/shared_careers-students-and-graduates.js
- test/browser_tests/spec_suites/shared/shared_contact-us.js
- test/browser_tests/spec_suites/shared/shared_the-bureau.js
Lint, Lint, Lint. :notes:  Lint, Lint, Lint. :notes: Lint yer tests :musical_note: 
- Added the browser tests to ESLint
- Created an eslintrc file for special-cases specific to browser tests
- Fixed linting errors on browser tests
- Follow the directions in the testing readme
- @sebworks 
> Adding ESLint to browser tests and removing linting errors

- CHANGELOG.md
- src/_lib/django_career_processor.py
- src/_queries/careers.json
- src/_settings/mappings/career.json
- src/_settings/processors.json
This is the processor that takes in the Jobs API data and uses it for the Careers section. 
@dpford @jimmynotjim
> Add Careers processor/mapping/query

- CHANGELOG.md
- test/browser_tests/page_objects/page_about-us.js
- test/browser_tests/spec_suites/shared/shared_about-us.js
> Adding tests to about landing page.

- CHANGELOG.md
- src/static/js/modules/classes/BreakpointHandler.js
- src/static/js/modules/classes/ContentSlider.js
- src/static/js/modules/classes/MobileCarousel.js
- src/static/js/modules/desktop-primary-nav.js
- src/static/js/modules/init-chosen.js
- src/static/js/modules/jquery/cf_formValidator.js
- src/static/js/modules/jquery/cf_notifier.js
- src/static/js/modules/jquery/cfpb-aria-button.js
- src/static/js/modules/jquery/custom-input.js
- src/static/js/modules/jquery/custom-select.js
- src/static/js/modules/jquery/type-and-filter.js
- src/static/js/modules/pagination-validation.js
- src/static/js/modules/post-filter.js
- src/static/js/modules/secondary-nav-toggle.js
- src/static/js/modules/simple-table-row-links.js
- src/static/js/modules/util/date-range-formatter.js
- src/static/js/modules/util/js-loader.js
- src/static/js/modules/youtube.js
- src/static/js/routes/careers/application-process/index.js
- src/static/js/routes/contact-us/index.js
- src/static/js/routes/offices/index.js
- src/static/js/routes/the-bureau/index.js
Got tired of all the warnings, figured it'd be good to get down to the real ones (like complexity) so we know where to concentrate when hopefully refactoring some of the JS next month.
> Simple lint warning fixes

- .travis.yml
- gulp/tasks/test.js
- package.json
My first gulp task. This adds coveralls to .travis.yml.
> Adding Coveralls to Travis

- src/_includes/macros/active-filters.html
- src/about-us/index.html
- src/budget/index.html
- src/careers/current-openings/_single.html
- src/contact-us/_template-contact-list.html
- src/offices/_single.html
- src/the-bureau/leadership-calendar/print/index.html
Fixes for minor issues surfaced in 8/3 beta review.
- Fixed incorrect code comment in active-filters macro.
- Fixed grammar issues.
- Fixed indentation and spacing issues.
- Added missing links to /about-us/ landing page.
- @sebworks
> Beta review fixes

- CHANGELOG.md
- src/_includes/macros/contact-layout.html
- src/_includes/templates/office-contact.html
- src/contact-us/_template-contact-list.html
- src/contact-us/index.html
- test/browser_tests/page_objects/page_office.js
- test/browser_tests/spec_suites/shared/shared_office-accessibility.js
- test/browser_tests/spec_suites/shared/shared_office-cfpb-ombudsman.js
- test/browser_tests/spec_suites/shared/shared_office-foia-requests.js
- test/browser_tests/spec_suites/shared/shared_office-plain-writing.js
- test/browser_tests/spec_suites/shared/shared_office-privacy.js
- test/browser_tests/spec_suites/shared/shared_office-project-catalyst.js
Fixes office contact email address.
- Add check in tests for the office contact email addresses.
- Fixed incorrect email href reference in contacts template.
- Minor code style cleanup.
- Run `gulp test`.
- @sebworks
> DF-2348 - fixes office's contact email addresses

- test/browser_tests/spec_suites/shared/shared_subpage-accessibility-file-a-formal-accessibility-complaint-or-website-feedback.js
- test/browser_tests/spec_suites/shared/shared_subpage-accessibility-social-media-accessibility.js
- test/browser_tests/spec_suites/shared/shared_subpage-accessibility-submit-an-accommodation-request.js
Accidentally doubled up two tests in in the subpage tests.
- Removes redundant test check for FAQ in subpages.
- @sebworks 
> Removes redundant test check

- CHANGELOG.md
- src/_includes/templates/forms/accessibility-feedback-form.html
- src/static/css/forms.less
- src/sub-pages/_vars-sub-pages.html
- test/browser_tests/spec_suites/shared/shared_subpage-accessibility-file-a-formal-accessibility-complaint-or-website-feedback.js
Adds accessibility subpage complaint form and tests update.
- Adds accessibility subpage complaint form.
- Updates accessibility subpage test to look for form.
- Visit `/sub-pages/file-a-formal-accessibility-complaint-or-website-feedback/`, see form
- @sebworks
> Added accessibility complaint form

- test/browser_tests/page_objects/page_office.js
- test/browser_tests/page_objects/page_sub-pages.js
- test/browser_tests/spec_suites/shared/shared_office-of-civil-rights.js
- test/browser_tests/spec_suites/shared/shared_subpage-civil-rights-diversity-policy.js
- test/browser_tests/spec_suites/shared/shared_subpage-civil-rights-equal-opportunity-policy.js
- test/browser_tests/spec_suites/shared/shared_subpage-civil-rights-no-fear-act.js
- test/browser_tests/spec_suites/shared/shared_subpage-civil-rights-raise-an-eeo-issue.js
- test/browser_tests/spec_suites/shared/shared_subpage-civil-rights-reasonable-accomodation-request-policy.js
- test/browser_tests/spec_suites/shared/shared_subpage-civil-rights-whistleblowers.js
What it says on the title.
- Rebuild the site to make sure the form for OCR appears
- Run gulp test
- @sebworks
> Adding Office of Civil Rights tests

- test/browser_tests/.eslintrc
- test/browser_tests/shared_objects/footer.js
- test/browser_tests/spec_suites/shared/shared_footer.js
Adding Test for Footer.
- Added 'test/browser_tests/page_components/footer.js'  to add footer component.
- Added 'test/browser_tests/spec_suites/shared/shared_footer.js' to add footer tests. 
- Run 'grunt build && protractor ./test/browser_tests/conf.js'
- @anselmbradford had to disable the` max-nested-callbacks` rule. 
@jimmynotjim
@imuchnik
> Footer Test

- src/_includes/templates/footer.html
What it says above
- @sebworks
> Add Office of Civil Rights link to footer

- README.md
- gulp/tasks/scripts.js
Minor tweak to the readme copy. See https://github.com/cfpb/cfgov-refresh/pull/865#discussion_r36682476
- @sebworks
> Minor readme edit

- gulp/tasks/test.js
- src/static/js/modules/jquery/cf_notifier.js
- src/static/js/modules/jquery/custom-select.js
- src/static/js/modules/util/web-storage-proxy.js
- test/browser_tests/page_objects/page_office.js
- test/browser_tests/page_objects/page_sub-pages.js
- test/browser_tests/spec_suites/shared/shared_footer.js
Footer tests were looking for Office of Civil rights.
- Adds OCR to shared footer test.
- Linting indent errors.
- @sebworks
> Hotfix: adds OCR to checked footer links

- CHANGELOG.md
- src/about-us/index.html
Doesn't need to be merged this sprint.
- Made copy edits to `/about-us/` per @sarahsimpson09's email
- Visit localhost:7000/about-us/
> Copy edits to /about-us/

- package.json
Fixes #876, remove gulp-jshint
- @sebworks 
> Remove gulp-jshint

- CHANGELOG.md
- src/_layouts/content-base-main-first.html
- src/blog/_single.html
- src/blog/_vars-blog.html
- src/budget/_vars-budget.html
- src/budget/financial-report/index.html
- src/budget/funding-request/index.html
- src/budget/performance-plan-report/index.html
- src/budget/strategic-plan/index.html
- src/careers/_vars-careers.html
- src/careers/application-process/index.html
- src/careers/current-openings/_single.html
- src/careers/current-openings/index.html
- src/careers/students-and-graduates/index.html
- src/careers/working-at-cfpb/index.html
- src/doing-business-with-us/_vars-doing-business-with-us.html
- src/doing-business-with-us/past-awards/index.html
- src/doing-business-with-us/small-businesses/index.html
- src/doing-business-with-us/upcoming-procurement-needs/index.html
- src/newsroom/_single.html
- src/newsroom/_vars-newsroom.html
- src/newsroom/press-resources/index.html
- src/the-bureau/_vars-the-bureau.html
- src/the-bureau/about-rich-cordray/index.html
- src/the-bureau/about-steve-antonakes/index.html
- src/the-bureau/bureau-structure/index.html
- src/the-bureau/history/index.html
- src/the-bureau/leadership-calendar/index.html
[aw yisss breadcrumbs](https://www.youtube.com/watch?v=0XpaLzRuhSg)
- Added breadcrumbs to blog, newsroom and career pages
- @sebworks 
- http://localhost:7000/blog/forum-on-know-before-you-owe-eclosing-pilot/
- http://localhost:7000/newsroom/prepared-remarks-of-cfpb-director-richard-cordray-on-the-citizens-bank-enforcement-action-press-call/
- http://localhost:7000/careers/current-openings/1865/ and all other career pages
- Closes DF-2249
- Closes DF-2250
- Closes DF-2241
> Adding breadcrumbs to blog, newsroom and careers

- src/_includes/macros/util/format/datetime.html
- src/static/css/cf-enhancements.less
- src/static/css/pages/business.less
More Sprint PR cleanup...
- Code style formatting.
- Set timezone default to `'America/New_York'`, as stated in the code comment.
- @sebworks 
> Sprint PR cleanup, part deux

- README.md
> Coveralls doesn't work on default branches not named master

- src/static/css/cf-enhancements.less
Fixes #934. No changelog entry should be needed for this one.
> Fixing #934 - fixes css order on cf-enhancements

- src/_includes/macros/time.html
Fixes #938: consolidating macro use on time.html
Test by visiting any page with a date like the events.
> Fixes #938: consolidating macro use on time.html

- .eslintrc
- CHANGELOG.md
- src/static/js/modules/jquery/custom-input.js
- src/static/js/modules/jquery/custom-select.js
- src/static/js/modules/jquery/type-and-filter.js
- test/browser_tests/default-suites.js
- test/browser_tests/jenkins_conf.js
ESLint update for indent rule introduced in FEWD standards in https://github.com/cfpb/front-end/pull/82
- Added indent rules for `var`, `let`, and `const` in ESLint config file.
- @sebworks 
> ESLint update for indent

- CHANGELOG.md
- src/_includes/breadcrumbs.html
- src/_includes/category-slug.html
- src/_includes/macros/activity-snippets.html
- src/_includes/macros/expandable.html
- src/_includes/macros/sub-nav.html
- src/_includes/macros/sub_pages.html
- src/_includes/macros/subscribe.html
- src/_includes/macros/util/common-form-fields.html
- src/_includes/macros/util/form.html
- src/_includes/macros/util/format/url.html
- src/_includes/macros/video-player.html
- src/_includes/post-macros.html
- src/_includes/related-links.html
- src/_includes/sidenav.html
- src/_includes/tags.html
- src/_includes/templates/forms/amending-and-correcting-records-under-the-privacy-act-form.html
- src/_includes/templates/forms/file-a-privacy-complaint-form.html
- src/_includes/templates/forms/form-eeo-issue.html
- src/_layouts/base.html
- src/events/_event-landing-macros.html
- src/events/_event-post-macros.html
- src/events/_event.html
- src/static/css/cf-enhancements.less
- src/static/css/nav-primary.less
- src/static/css/video-player.less
- src/static/js/modules/util/expanded-state.js
- test/macro_tests/tests/form.json
- test/unit_tests/modules/nav-primary-spec.js
- test/unit_tests/modules/util/expanded-state-spec.js
Sprint 0 PR cleanup.
- Code comment and style cleanup.
- Changes `big_radio` macro to `radio_big` and `checkbox_bg` to `checkbox_big`.
- @sebworks
> Sprint PR cleanup

- CHANGELOG.md
- README.md
Updated readme with better gulp watch directions.
- Updates readme with better directions for `gulp watch`
- Fixes #922
- @sebworks
> Updated readme with better gulp watch directions.

- requirements/base.txt
> Add version for requests package

- CHANGELOG.md
- src/the-bureau/about-deputy-director/index.html
Updated the dep dir page title to include "Acting"
Navigate to `/the-bureau/about-deputy-director/`
- @sebworks 
> Updated the dep dir page title to include "Acting"

- .gitignore
- Ignores `npm-debug.log` in gitignore.
- @sebworks
> Ignore npm-debug.log

- CHANGELOG.md
- src/_includes/article.html
- src/_includes/macros/video-player.html
- src/_includes/templates/nav/primary-nav.html
- src/careers/current-openings/_single.html
- src/events/_event.html
- src/the-bureau/about-deputy-director/index.html
- src/the-bureau/about-director/index.html
- src/the-bureau/history/index.html
- src/the-bureau/leadership-calendar/index.html
> included with context flag for macros that make a call to request object

- test/browser_tests/spec_suites/about-deputy-director.js
Fixes failing test for change in https://github.com/cfpb/cfgov-refresh/pull/997
- Adds `(Acting)` content to test.
- `gulp build && gulp test:acceptance` should pass.
- @sebworks
> Fixes failing test

- src/static/js/modules/nav-primary.js
Simple fix for [PR Comment](https://github.com/cfpb/cfgov-refresh/pull/971#discussion_r39411061), not much to it.
> Fixed naming of non-jq variable for clarity

- src/static/js/modules/beta-banner-state.js
- src/static/js/modules/classes/BreakpointHandler.js
- src/static/js/modules/clear-form-buttons.js
- src/static/js/modules/external-site-redirect.js
- src/static/js/modules/external-site.js
- src/static/js/modules/focus-target.js
- src/static/js/modules/footer-button.js
- src/static/js/modules/form-validation.js
- src/static/js/modules/init-chosen.js
- src/static/js/modules/init-mobile-only-expandables.js
- src/static/js/modules/nav-primary.js
- src/static/js/modules/post-filter.js
- src/static/js/modules/scroll-on-history-collapse.js
- src/static/js/modules/secondary-nav-toggle.js
- src/static/js/modules/show-hide-fields.js
- src/static/js/modules/youtube.js
Adds some missing jsdocs. Still a few outstanding.
- Adds missing jsdocs to methods that were missing them.
- @sebworks 
- @jimmynotjim
> Adds jsdocs

- src/static/js/modules/show-hide-fields.js
Oops, fixes one ESLint error that got through.
- Adds jsdoc parameter name.
- `gulp lint` should show no errors.
- @sebworks
> ESLint fix

- CHANGELOG.md
- src/static/js/modules/util/web-storage-proxy.js
- test/unit_tests/modules/util/web-storage-proxy.js
Added testing for web-storage-proxy.js
- Added tests to increase coverage to 100% across the board
- Refactored code to be less complex and allow for easier testing
- Updated code to utilize storage object instead of boolean to allow for storage options outside the window object
- Run `gulp test:unit:scripts` see the green across the board for this file
- @sebworks 
__Before__
Statements   : 26.51% ( 321/1211 )
Branches     : 21.84% ( 90/412 )
Functions    : 22.49% ( 56/249 )
Lines        : 26.75% ( 321/1200 )
__After__
Statements   : 28.37% ( 343/1209 )
Branches     : 24.27% ( 100/412 ) …
> Added testing for web-storage-proxy.js

- CHANGELOG.md
- src/budget/index.html
- src/doing-business-with-us/_future-block.html
- src/doing-business-with-us/_process-block.html
- src/doing-business-with-us/_smbiz-block.html
- src/doing-business-with-us/index.html
- Missed a couple pages with the old html5 headings, this fixes those pages
- I'd like to get this in after #992 #995, since I'm sure it'll change some of the selectors there, so no rush to review.
> More heading fixes to budget and business section

- CHANGELOG.md
- cfgov/v1/jinja2/v1/careers/_template-block-social.html
- cfgov/v1/jinja2/v1/careers/application-process/index.html
- cfgov/v1/jinja2/v1/careers/current-openings/index.html
- cfgov/v1/jinja2/v1/careers/index.html
- cfgov/v1/jinja2/v1/careers/working-at-cfpb/index.html
- test/browser_tests/page_objects/page_careers-application-process.js
- test/browser_tests/page_objects/page_careers-current-openings.js
- test/browser_tests/page_objects/page_careers-working-at-cfpb.js
- test/browser_tests/page_objects/page_careers.js
- test/browser_tests/shared_objects/careers-social-section.js
- test/browser_tests/shared_objects/related-links-section.js
- test/browser_tests/spec_suites/careers-application-process.js
- test/browser_tests/spec_suites/careers-current-openings.js
- test/browser_tests/spec_suites/careers-working-at-cfpb.js
- test/browser_tests/spec_suites/careers.js
- test/browser_tests/util/url-matcher.js
Acceptance tests for the `Careers` pages
- Added Acceptance tests for the `Careers` pages. 
@jimmynotjim 
@KimberlyMunoz
> Adding Acceptance tests for the Careers pages

- CHANGELOG.md
- cfgov/v1/jinja2/v1/doing-business-with-us/small-businesses/index.html
Fixing the title on Small & Minority Businesses
- Fixed title on small and minority businesses
- Visit http://localhost:8000/doing-business-with-us/small-businesses/
- @sebworks 
- I confirmed with @sarahsimpson09 that only the title on the top should be changed. Navigation items should stay the same.
- DFJR-81 on the JIRA board
> Title fix for Small & Minority Businesses

- CHANGELOG.md
- cfgov/v1/jinja2/v1/doing-business-with-us/_process-future-footer.html
- cfgov/v1/jinja2/v1/doing-business-with-us/_process-smbiz-footer.html
- cfgov/v1/jinja2/v1/doing-business-with-us/index.html
- cfgov/v1/jinja2/v1/doing-business-with-us/past-awards/index.html
- cfgov/v1/jinja2/v1/doing-business-with-us/small-businesses/index.html
- cfgov/v1/jinja2/v1/doing-business-with-us/upcoming-procurement-needs/index.html
- test/browser_tests/page_objects/page_dbwu-past-awards.js
- test/browser_tests/page_objects/page_dbwu-small-businesses.js
- test/browser_tests/page_objects/page_dbwu-upcoming-procurement-needs.js
- test/browser_tests/page_objects/page_doing-business-with-us.js
- test/browser_tests/spec_suites/dbwu-past-awards.js
- test/browser_tests/spec_suites/dbwu-small-businesses.js
- test/browser_tests/spec_suites/dbwu-upcoming-procurement-needs.js
- test/browser_tests/spec_suites/doing-business-with-us.js
Acceptance tests for the `Doing Business with Us pages` pages
- Added Acceptance tests for the `Doing Business with Us pages` pages. 
@jimmynotjim 
@KimberlyMunoz
> Adding Acceptance tests for the Doing Business with Us pages

- CHANGELOG.md
- package.json
- Updated gulp-autoprefixer to 3.0.2.
- `./setup.sh local && gulp test` should pass.
- @sebworks 
> Updated gulp-autoprefixer to 3.0.2.

- cfgov/v1/jinja2/v1/about-us/index.html
- cfgov/v1/jinja2/v1/careers/index.html
Minor code style cleanup.
- Adds missing space after comma in macro call.
- Adds correct indent for stacked classes.
- Stacks three classes on div.
- @sebworks
> Minor code style cleanup

- test/unit_tests/.eslintrc
Adding Unit Test lint exceptions
- Changed ` test/unit_tests/.eslintrc` to add `nested-callbacks` and `max-statements` lint exceptions
@jimmynotjim 
@KimberlyMunoz
> Adding Unit Test lint exceptions

- .env_SAMPLE
- INSTALL.md
- README.md
- cfgov/cfgov/settings/base.py
- cfgov/cfgov/settings/local.py
- cfgov/cfgov/urls.py
- cfgov/cfgov/wsgi.py
- cfgov/manage.py
- cfgov/v1/jinja2/v1/_includes/macros/sub-nav.html
- cfgov/v1/jinja2/v1/_includes/macros/util/common-form-fields.html
- cfgov/v1/jinja2/v1/_includes/post-macros.html
- cfgov/v1/jinja2/v1/careers/application-process/index.html
- cfgov/v1/jinja2/v1/doing-business-with-us/_process-future-footer.html
- cfgov/v1/jinja2/v1/doing-business-with-us/_process-smbiz-footer.html
- cfgov/v1/jinja2/v1/doing-business-with-us/index.html
- cfgov/v1/jinja2/v1/events/_event-post-macros.html
- cfgov/v1/jinja2/v1/the-bureau/index.html
- cfgov/v1/models.py
General code style cleanup from beta PR https://github.com/cfpb/cfgov-refresh/pull/1041.
- Fixes grammar.
- Normalizes quotes in python.
- Normalizes key-spacing in JS.
- Normalizes notes in readmes.
- Normalizes some stacked CSS classes.
- @sebworks 
- @kurtw 
- @kave
> General code style cleanup

- .eslintrc
- CHANGELOG.md
- test/browser_tests/jenkins_conf.js
Updates ESLint per https://github.com/cfpb/front-end/pull/88
- Changes `quote-props` rule attribute to `consistent-as-needed`.
- `gulp lint` should have not errors.
- @sebworks 
- @jimmynotjim
> Updates eslint per standards

- cfgov/v1/jinja2/v1/_includes/organisms/well.html
- cfgov/v1/jinja2/v1/landing-page-1/_template-prototype-well-content.html
- cfgov/v1/jinja2/v1/landing-page-1/index.html
- cfgov/v1/preprocessed/css/main.less
- cfgov/v1/preprocessed/css/organisms/well.less
Adds well organism architecture per [GHE]/flapjack/Modules-V1/wiki/Well
- Added templates and CSS for the Well organism.
- Updates Well organism on `/landing-page-1/`.
- @sebworks 
> Adds Well organism

- .env_SAMPLE
- cfgov/cfgov/settings/base.py
> changed static root to global variable

- cfgov/cfgov/urls.py
- cfgov/jinja2/v1/sublanding-page-1/index.html
- cfgov/jinja2/v1/sublanding-page-2/index.html
This is similar to #1036 in that it creates the sample pages we'll be using for the molecules on the sublanding page
- Visit http://localhost:8000/sublanding-page-2/ and http://localhost:8000/sublanding-page-1/
- @sebworks 
- Ans, if you're reading this, you should be enjoying your vacation. 🌴
> Add sample sublanding pages

- cfgov/cfgov/settings/base.py
seems the previous path failed in the dev environments
> edited default path for pdfreactor

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/molecules/call-to-action.html
- cfgov/jinja2/v1/landing-page-1/index.html
- cfgov/preprocessed/css/main.less
- cfgov/preprocessed/css/molecules/call-to-action.less
Adding Call to Action molecule
- Adding Call to Action molecule.
- Visit  `/landing-page-1/`.
- @sebworks 
- @Scotchester
> Adding Call to Action molecule

- cfgov/v1/models/molecules.py
Implementing Validation for Molecules
- Molecule specific validation
- Create a demo page & add molecules testing validation requirements
- @kurtw 
> Business Logic for Molecules

- cfgov/cfgov/urls.py
> Move catch-all URL pattern to below the other patterns.

- test/browser_tests/spec_suites/events.js
The events pages are inaccessible at the moment. This sets the associated tests to pending.
- Sets events tests to pending.
- Acceptance testing should pass.
- @sebworks 
- @jimmynotjim
> Sets event tests to pending

- cfgov/jinja2/v1/_includes/molecules/image-text-50-50.html
The 50/50 molecule was accidentally removed in 4241811, this reverts that.
> Corrects 50/50 removal in 4241811

- CHANGELOG.md
- cfgov/cfgov/urls.py
- cfgov/jinja2/v1/browse-filterable/index.html
Visit http://localhost:8000/browse-filterable/ to see the browse-filterable page.
This will be the future home of the post-preview and filter box modules.
- @sebworks
> Add browse-filterable page

- .env_SAMPLE
- CHANGELOG.md
- cfgov/cfgov/settings/local.py
- cfgov/cfgov/settings/production.py
- cfgov/v1/models/base.py
- cfgov/v1/templatetags/share.py
- cfgov/v1/wagtail_hooks.py
> Move staging hostname variable from django settings to environment variable

- cfgov/v1/templatetags/share.py
> Fix one more place where STAGING_HOSTNAME uses settings

- cfgov/jinja2/v1/landing-page-1/index.html
Fix for Call to Action params
- Updated `cfgov/jinja2/v1/landing-page-1/index.html` to fix issue with Call to Action params.
- @kurtw
> Fix for Call to Action params

- test/browser_tests/default-suites.js
Adjusts Sauce Connect settings per https://docs.saucelabs.com/reference/platforms-configurator/
- Slightly adjust case of Sauce Connect settings.
- No change when testing on sauce labs.
- @kurtw
> Adjusts Sauce Connect settings

- CHANGELOG.md
- README.md
> Add instruction to create superuser for admin access.

- cfgov/jinja2/v1/landing-page-1/index.html
> Fixed settings key for half-link-blob body text

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/molecules/related-posts.html
- cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html
- cfgov/jinja2/v1/sublanding-page-1/index.html
- cfgov/unprocessed/css/main.less
- cfgov/unprocessed/css/organisms/sidebar-breakout.less
Adding Sidebar Breakout Organism
- Adding Sidebar Breakout organism.
- Visit  `http://localhost:8000/sublanding-page-1/`.
- @sebworks 
> Adding Sidebar Breakout Organism

- CHANGELOG.md
- cfgov/cfgov/settings/base.py
- cfgov/templates/wagtailadmin/pages/create.html
- cfgov/templates/wagtailadmin/pages/edit.html
- cfgov/v1/__init__.py
- requirements/base.txt
Upgrade wagtail to 1.2 and included a context processor for handling stream children
@kurtw 
@rosskarchner
> wagtail upgrade to 1.2

- cfgov/cfgov/urls.py
- cfgov/jinja2/v1/_layouts/content-base-main-first.html
- cfgov/jinja2/v1/learn-page/index.html
- cfgov/unprocessed/css/breadcrumbs.less
- Added a prototype learn page with all the molecules that are already prepared.
- Added modifier to breadcrumbs to fix spacing based on layouts
- @sebworks 
- I'm working on insets on another branch, but will break out those changes in another PR
> Added learn page and adjusted breadcrumbs

- INSTALL.md
- README.md
- Updates `README.md` and `INSTALL.md` to reflect evolution of the project. Notably: removes Sheer references from installation steps.
- @sebworks 
- @kurtw 
- @kave 
> Updates readme

- cfgov/cfgov/urls.py
> included permanent flag to redirect to suppress django 1.9 warning

- backend.sh
- frontend.sh
- requirements/base.txt
- setup.sh
> broke setup script into front/backend scripts

- cfgov/core/management/commands/_helpers.py
- cfgov/v1/models/events.py
- cfgov/v1/processors/eventpage.py
Adds a new function to the PageDataConverter that includes the defaults of any of the pages being converted.
@kave
> Fix Event processor for additional fields

- CHANGELOG.md
- cfgov/cfgov/settings/local.py
> Add Wagtail Styleguide to local settings

- .env_SAMPLE
- cfgov/cfgov/settings/base.py
- requirements/base.txt
> Enabled S3 media capability for wagtail

- cfgov/cfgov/settings/base.py
- cfgov/v1/s3utils.py
> ability to store in specific directorys

- cfgov/unprocessed/js/molecules/Expandable.js
- cfgov/unprocessed/js/organisms/ExpandableGroup.js
- cfgov/unprocessed/js/routes/browse-basic/index.js
- test/browser_tests/page_objects/page_budget.js
- test/unit_tests/modules/focus-target-spec.js
- test/unit_tests/modules/footer-button-spec.js
- test/unit_tests/modules/nav-primary-spec.js
- test/unit_tests/modules/util/assign-spec.js
- test/unit_tests/modules/util/breakpoint-state-spec.js
- test/unit_tests/modules/util/expanded-state-spec.js
- test/unit_tests/modules/util/web-storage-proxy.js
Fixes JS linting errors
- Fixes several minor linting errors (max-len mostly). Adds `BASE_JS_PATH` constant where applicable.
- No change other than less linting warnings.
- @sebworks
> Fixes linting errors

- cfgov/cfgov/urls.py
- cfgov/jinja2/v1/document-detail/index.html
This adds a basic document detail page for us to build on. Missing molecules and organisms are in the To Do notes.
- Adds Document Detail Page
- @sebworks
> Adding basic Document-Detail Page

- cfgov/cfgov/urls.py
- cfgov/jinja2/v1/_includes/molecules/call-to-action.html
- cfgov/jinja2/v1/_includes/molecules/half-width-link-blob.html
- cfgov/jinja2/v1/_includes/molecules/hero.html
- cfgov/jinja2/v1/_includes/molecules/image-text-25-75.html
- cfgov/jinja2/v1/_includes/molecules/image-text-50-50.html
- cfgov/jinja2/v1/_includes/molecules/text-introduction.html
- cfgov/jinja2/v1/_includes/organisms/email-signup.html
- cfgov/jinja2/v1/_includes/organisms/well.html
- cfgov/jinja2/v1/browse-filterable/index.html
- cfgov/jinja2/v1/document-detail/index.html
- cfgov/jinja2/v1/landing-page/_template-prototype-well-content.html
- cfgov/jinja2/v1/landing-page/index.html
- cfgov/jinja2/v1/learn-page/index.html
Refactored the way we create prototypes, so they are contained within the molecules and helps readability of atomic element with less duplication of code in the if cases
@jimmynotjim 
@sebworks
> setting up landing page demo and refactoring molecules/organisms

- cfgov/cfgov/settings/base.py
> fixed conditionals for s3 upload enabling

- cfgov/jinja2/v1/_includes/molecules/half-width-link-blob.html
- cfgov/jinja2/v1/_includes/molecules/hero.html
- cfgov/jinja2/v1/_includes/molecules/image-text-25-75.html
- cfgov/jinja2/v1/_includes/molecules/image-text-50-50.html
- cfgov/jinja2/v1/_includes/molecules/text-introduction.html
- cfgov/jinja2/v1/_includes/organisms/post-preview.html
- cfgov/jinja2/v1/browse-filterable/index.html
> changed p tags to divs to account for wagtail richtext rendering

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
- cfgov/jinja2/v1/browse-filterable/index.html
- cfgov/unprocessed/css/forms.less
- cfgov/unprocessed/js/organisms/FilterableListControls.js
- cfgov/unprocessed/js/routes/browse-filterable/index.js
[GHE]/flapjack/Modules-V1/wiki/Filter-(filterable-list)
- Adds filterable list controls organism.
- Slight adjustments to form.less styles:
- Nest forms as sub-grid by default.
- Use new breakpoint variables.
- Adjust styles for nested labels.
- Visit http://localhost:8000/browse-filterable/
- @sebworks 
- The form styles need to be fleshed out further in work done for the form organism.
> Adds filterable list controls organism

- test/browser_tests/spec_suites/blog-single.js
Fixes the failing tests that have been plaguing us for a week
- Temporarily disabled a test due to macro flux with the change to Wagtail. Will see about updating for it in another PR.
- run `./setup.sh && gulp test:acceptance:browser --sauce=false`
- @kave 
- @kurtw 
- @sebworks 
- Fix the related links in the blog sidebar
> Fixing acceptance tests

- cfgov/v1/migrations/0013_add_sublanding.py
> Fix migrations

- CHANGELOG.md
- cfgov/v1/migrations/0012_share_perms.py
> edited migration script to account for fresh db

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html
- cfgov/jinja2/v1/sublanding-page/index.html
- If Hero exists, hero will always be rendered.
@kave
> Fix page header rendering for Sublanding Page

- cfgov/jinja2/v1/learn-page/index.html
- cfgov/unprocessed/css/molecules/inset.less
The learn page has been erroring out due a broken table macro which is blocking stuff on my form work. Also I noticed the insets were the wrong size and this fixes that.
- @sebworks
> Fixing learn page errors and a wrong size for insets

- CHANGELOG.md
- cfgov/v1/migrations/0014_add_fields_sublanding.py
- cfgov/v1/models/sublanding_page.py
> Add Image Text 25/75 and Full Width Text into SublandingPage

- cfgov/v1/migrations/0015_addshowheading_relatedposts.py
> fix migrations dependency

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/organisms/image-text-25-75-group.html
- cfgov/jinja2/v1/landing-page/index.html
- cfgov/jinja2/v1/sublanding-page/index.html
- cfgov/v1/migrations/0016_merge_landingpage_streamfields.py
- cfgov/v1/models/landing_page.py
- cfgov/v1/models/organisms.py
- cfgov/v1/models/sublanding_page.py
- Merge LandingPage Streamfields
- Update template with new StreamFields
- Add lambda function into the context that returns fake related posts data for prototyping
- Fix small error in Text Introduction prototype data
NOTE: This pulled in the commit from #1223 to work. 
@kave 
@jimmynotjim
> Merge LandingPage Streamfields

- cfgov/unprocessed/css/nav-secondary.less
Had this on the back burner, didn't want to loose it during my two weeks out.
> Fixed code documentation for the secondary navigation

- cfgov/jinja2/v1/_includes/macros/footer-global.html
- cfgov/jinja2/v1/_includes/molecules/social-media.html
- cfgov/jinja2/v1/_layouts/base.html
Missing context in macro imports
@rosskarchner 
> included context for social-media macro

- cfgov/jinja2/v1/_includes/macros/activity-snippets.html
- cfgov/jinja2/v1/_includes/macros/category-icon.html
- test/browser_tests/page_objects/page_about-director.js
- test/browser_tests/page_objects/page_bureau-history.js
- test/browser_tests/page_objects/page_leadership-calendar.js
- test/browser_tests/spec_suites/about-us.js
Fixes for Acceptance Tests
- Run 'gulp test:acceptance'
- @kave
> Fixes for Acceptance Tests

- cfgov/jinja2/v1/_includes/atoms/select.html
- cfgov/jinja2/v1/_includes/templates/forms/accessibility-feedback-form.html
One of the old selects didn't get converted on the file an accessibility complaint page. Luckily the tests caught it and here we have a fix.
- @sebworks 
- @kave
> Fixed the accessibility office page

- cfgov/jinja2/v1/_includes/molecules/expandable.html
- cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
- cfgov/jinja2/v1/browse-filterable/index.html
- Fix/convert filters' expandable prototype to use global value setting.
- Visit `/browse-filterable/` and note the page loads without error and the filter works.
- @sebworks 
- @kave
> Fix/convert filters' expandable prototype

- cfgov/jinja2/v1/_includes/molecules/notification.html
- cfgov/jinja2/v1/browse-filterable/index.html
- Converts the notifications to use the `global_dict`. Continued work integrating notifications into filters.
- `/browse-filterable/`
- @sebworks 
- @kave
> Convert notifications to use global_dict

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/macros/filters.html
- cfgov/v1/__init__.py
Adding context method to return unique id
- Adding context method to return unique id.
- Visit  `http://localhost:8000/the-bureau/leadership-calendar/` and click on labels on the two filters. Should check/uncheck boxes on both filters.
- @kave 
I am using a closure but it may make more sense to use a generator or iterator.
> Adding context method to return unique id

- cfgov/jinja2/v1/sublanding-page/index.html
Fixes/implements /sublanding-page/
- Fixes and adds missing atomic elements to sublanding page prototype.
- Visit `/sublanding-page/`
- @sebworks
> Fixes/implements /sublanding-page/

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/molecules/pagination.html
- cfgov/jinja2/v1/browse-filterable/index.html
- cfgov/unprocessed/css/main.less
- cfgov/unprocessed/css/molecules/pagination.less
Adding Pagination Molecule
- Adding Pagination Molecule
- Visit  `http://localhost:8000/browse-filterable/`.
Needs work to display notification when a non number is entered into the form.
> Adding Pagination Molecule

- cfgov/jinja2/v1/_layouts/base.html
- cfgov/jinja2/v1/browse-basic/index.html
This will fix the rendering of JS for prototype pages i.e the browse-page
@KimberlyMunoz
> fixed JS loading for prototype pages

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html
- cfgov/jinja2/v1/landing-page/index.html
- cfgov/jinja2/v1/sublanding-page/index.html
Handles styling and rendering issues [Fixed 1278] (https://github.com/cfpb/cfgov-refresh/issues/1278)
> fixes styling and rendering issues

- cfgov/unprocessed/js/modules/external-site-redirect.js
- cfgov/unprocessed/js/modules/post-filter.js
- cfgov/unprocessed/js/modules/util/expanded-state.js
- cfgov/unprocessed/js/organisms/FilterableListControls.js
- gulp/tasks/scripts.js
- gulp/tasks/test.js
- test/unit_tests/modules/nav-primary-spec.js
- test/unit_tests/modules/util/expanded-state-spec.js
- Fix general linting warnings.
- `gulp lint` will have less warnings.
- @sebworks 
- @jimmynotjim
> Fix linting warnings

- cfgov/jinja2/v1/_includes/molecules/featured-content.html
- cfgov/jinja2/v1/sublanding-page/index.html
- Adds FCM to sublanding prototype
> Adds FCM to sublanding prototype

- CHANGELOG.md
- cfgov/jinja2/v1/browse-basic/index.html
- cfgov/jinja2/v1/browse-filterable/index.html
- cfgov/jinja2/v1/document-detail/index.html
- cfgov/jinja2/v1/learn-page/index.html
- cfgov/v1/models/base.py
- cfgov/v1/wagtail_hooks.py
> included reference to page parent for breadcrumb generation

- cfgov/jinja2/v1/_includes/organisms/full-width-text.html
Forgot to update full width text prototype data.
@jimmynotjim
> fixed prototype data for full width text

- cfgov/jinja2/v1/_includes/molecules/image-text-25-75.html
> Bugfix for passed markup in 25/75

- CHANGELOG.md
- cfgov/v1/migrations/0031_addrelatedlinks_sidefoot.py
- cfgov/v1/migrations/9999_init_data.py
- cfgov/v1/models/base.py
> Add Related Links molecule to Sidebar/Footer

- initial-data.sh
Name was updated in environment, but not in initial-data.sh.
@rosskarchner
> Bugfix: Updates env name

- .env_SAMPLE
- CHANGELOG.md
- cfgov/cfgov/settings/base.py
- cfgov/cfgov/settings/production.py
- cfgov/cfgov/urls.py
- cfgov/cfgov/util.py
- cfgov/templates/wagtailadmin/account/password_reset/confirm.html
- cfgov/templates/wagtailadmin/login.html
- cfgov/v1/migrations/0034_failedloginattempt.py
- cfgov/v1/migrations/10000_failedloginattempt.py
- cfgov/v1/migrations/9999_init_data.py
- cfgov/v1/models/base.py
- cfgov/v1/util/__init__.py
- cfgov/v1/util/password_policy.py
- cfgov/v1/views.py
@rosskarchner @kurtw 
- Login
- Account password change flow
- forgot my password flow
- Type in multiple wrong passwords to be locked out
- Go through "Forgot my password" flow
- goto Account Page, and try to change your password
- should see password policy is enforced
> Password Policy & Lockout

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/molecules/global-header-cta.html
- cfgov/jinja2/v1/_includes/templates/header.html
- cfgov/jinja2/v1/_includes/templates/nav/primary-nav.html
- cfgov/unprocessed/css/main.less
- cfgov/unprocessed/css/molecules/global-header-cta.less
- cfgov/unprocessed/css/organisms/header.less
- cfgov/unprocessed/css/organisms/mega-menu.less
Adds Submit a Complaint CTA, initial Header/Mega Menu
- Atomic Submit a Complaint CTA.
- Initial atomic Header (duplicate of https://github.com/cfpb/cfgov-refresh/pull/1342).
- Initial atomic Mega Menu.
- Visit the site, resize window, expand primary nav hamburger menu. Submit a Complaint appears in upper-right in header and bottom of mega menu primary nav.
- @sebworks 
Desktop size:
Mobile size:
> Adds Global Header CTA, initial Header/Mega Menu

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/molecules/global-eyebrow.html
- cfgov/jinja2/v1/_includes/templates/header.html
- cfgov/jinja2/v1/_includes/templates/nav/primary-nav.html
- cfgov/unprocessed/css/brand-palette.less
- cfgov/unprocessed/css/footer.less
- cfgov/unprocessed/css/header.less
- cfgov/unprocessed/css/main.less
- cfgov/unprocessed/css/molecules/global-eyebrow.less
- cfgov/unprocessed/css/nav-primary.less
- cfgov/unprocessed/css/organisms/header.less
- cfgov/unprocessed/css/organisms/mega-menu.less
- cfgov/unprocessed/css/pages/beta.less
- Adds Global Eyebrow molecule.
- Visit any page, resize page, note eyebrow at top of page and in mega menu at mobile sizes.
- @sebworks 
Desktop size:
Mobile size:
> Adds Global Eyebrow

- cfgov/v1/views.py
Fixed issue with error messages not being displayed during incorrect logins with false Usernames
- @kurtw
> Fixed issue with error messages not being displayed during incorrect Login with false Username

- cfgov/unprocessed/js/molecules/GlobalSearch.js
Updates global search var names for tab key presses. See https://github.com/cfpb/cfgov-refresh/commit/3157fd75fb9b397c8d4b22f2ae79827e4510414d#commitcomment-15588805
- Updates names in global search script.
- @jimmynotjim
> Updates global search var names

- test/browser_tests/page_objects/page_blog-single.js
- test/browser_tests/page_objects/page_blog.js
- test/browser_tests/page_objects/page_careers-application-process.js
- test/browser_tests/page_objects/page_careers-current-openings.js
- test/browser_tests/page_objects/page_careers-working-at-cfpb.js
- test/browser_tests/page_objects/page_careers.js
- test/browser_tests/page_objects/page_newsroom-press-resources.js
- test/browser_tests/page_objects/page_newsroom.js
Fixing lodash dependency error
@kave 
Run `gulp test`
> Fixing lodash dependency error

- cfgov/jinja2/v1/browse-basic/index.html
- cfgov/jinja2/v1/browse-filterable/index.html
- Also fixes spacing between modules in pre-footer
- Fixes #1383 
- @sebworks 
- Log in and create a Browse-Basic page
- Create different sidefoot molecules and organisms
- The atoms in the Browse pages, and really all the pages, are going away so some of the code is temporary until then. A TODO has been added for that.
> Adds background to the pre-footer on browse pages

- cfgov/jinja2/v1/_includes/molecules/featured-content.html
Fixes https://github.com/cfpb/cfgov-refresh/issues/1379
- @sebworks 
- @KimberlyMunoz  
- Add an FCM to a sublanding page and preview.
> FCM link fix

- cfgov/jinja2/v1/_includes/molecules/global-eyebrow.html
- cfgov/jinja2/v1/_includes/molecules/global-header-cta.html
- cfgov/jinja2/v1/_includes/templates/header.html
- cfgov/jinja2/v1/_includes/templates/nav/primary-nav.html
- Fix to help #1393 along.
- There may be other areas we need to replace value where we were improperly manipulating it.
> Removed manipulation of the `value` constant passed by the CMS

- cfgov/jinja2/v1/_includes/molecules/global-eyebrow.html
Fix for line break. Fixes issue #1415 
@jimmynotjim 
> Fix for line break

- cfgov/unprocessed/js/organisms/Header.js
- cfgov/unprocessed/js/routes/common.js
- Add Header.js organism
- `gulp build` should have no errors.
- @sebworks 
- @jimmynotjim
> Add Header.js organism

- INSTALL.md
- README.md
Adds delete db instruction to readme
@jimmynotjim 
@kurtw
> Adds delete db instruction to readme

- CHANGELOG.md
- cfgov/jinja2/v1/_layouts/base.html
- Makes it so when viewing a page while logged in will give you page controls
It's a convenience but a nice one at that.
@richaagarwal 
@kave 
@jimmynotjim 
> Add wagtailuserbar to the base.html

- cfgov/jinja2/v1/browse-basic/index.html
- cfgov/jinja2/v1/document-detail/index.html
- cfgov/jinja2/v1/landing-page/index.html
- cfgov/jinja2/v1/learn-page/index.html
- cfgov/unprocessed/css/molecules/image-text-25-75.less
- cfgov/unprocessed/css/organisms/image-text-50-50-group.less
- cfgov/unprocessed/css/organisms/link-blob-group.less
Fixes a number of spacing issues, specifically with the text-image molecules, the first block of the page on several templates and spacing at the end of pages.
Fixes #1396 and a lot of #1366 
- @sebworks
> Bringing the layouts in line with spacing standards

- cfgov/jinja2/v1/_includes/molecules/home-hero.html
- cfgov/jinja2/v1/index.html
Update with cleared content for the home page
- Updated home page content based on feedback from clearance process
- `gulp build` and view the home page
- @schaferjh 
- @tnferrell 
- @sebworks 
> Update with cleared content for the home page

- cfgov/jinja2/v1/_includes/macros/activities-block.html
- cfgov/jinja2/v1/_includes/macros/sub_pages.html
- cfgov/jinja2/v1/_includes/templates/office-contact.html
- cfgov/jinja2/v1/browse-basic/index.html
- cfgov/jinja2/v1/browse-filterable/index.html
- cfgov/jinja2/v1/budget/index.html
- cfgov/jinja2/v1/careers/_template-careers-related-links.html
- cfgov/jinja2/v1/events/index.html
- cfgov/jinja2/v1/newsroom/press-resources/index.html
- cfgov/jinja2/v1/offices/_single.html
- cfgov/jinja2/v1/sub-pages/_single.html
- cfgov/jinja2/v1/the-bureau/about-deputy-director/index.html
- cfgov/jinja2/v1/the-bureau/about-director/index.html
- cfgov/jinja2/v1/the-bureau/leadership-calendar/index.html
- cfgov/unprocessed/css/main.less
- cfgov/unprocessed/css/organisms/prefooter.less
This goes back in the project to make sure spacing in the about pages matches the rest of the wagtail project.
- Check budget, career and another office page to make sure the spacing matches those on wagtail.
- @sebworks
> Fixing prefooter spacing across project

- cfgov/cfgov/urls.py
- cfgov/jinja2/v1/_includes/organisms/sidebar-contact-info.html
- cfgov/jinja2/v1/browse-basic/index.html
- cfgov/jinja2/v1/browse-filterable/index.html
- cfgov/jinja2/v1/document-detail/index.html
- cfgov/jinja2/v1/landing-page/index.html
- cfgov/jinja2/v1/learn-page/index.html
- cfgov/jinja2/v1/sublanding-page/index.html
- cfgov/jinja2/v1/wagtail/demo/index.html
@richaagarwal I went and lifted your changes specifically to the page templates from your https://github.com/cfpb/cfgov-refresh/pull/1393 into a separate PR. due to some bugs creeping in with the sidebar-contact-molecule.
@kurtw 
- Create individual Pages in wagtail and verify they don't break
- landing page
- sublanding page
- browse page
- browse filterable page
- document detail page
- learn page
> removed prototype data from page templates to resolve bugs

- cfgov/jinja2/v1/_includes/macros/category-slug.html
- cfgov/jinja2/v1/_includes/molecules/notification.html
> Hotfix for /blog/ that corrects string concatenation and category lookup

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Updates the project w/ PR and Issue templates for Github
- Adds new PR template
- Adds new Issue template
- I have no idea
- @sebworks 
- @kave 
I can't until it's merged :cry: 
- See https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
-
> Updates the project w/ PR and Issue templates for Github

- .eslintrc
- CHANGELOG.md
- cfgov/unprocessed/js/config/error-messages-config.js
- cfgov/unprocessed/js/modules/ContentSlider.js
- cfgov/unprocessed/js/modules/ExternalSite.js
- cfgov/unprocessed/js/modules/external-site-redirect.js
- cfgov/unprocessed/js/modules/jquery/cf_formValidator.js
- cfgov/unprocessed/js/modules/jquery/cf_notifier.js
- cfgov/unprocessed/js/modules/jquery/type-and-filter.js
- cfgov/unprocessed/js/modules/util/EventObserver.js
- cfgov/unprocessed/js/modules/util/js-loader.js
- cfgov/unprocessed/js/modules/util/standard-type.js
- cfgov/unprocessed/js/modules/youtube.js
- cfgov/unprocessed/js/molecules/Multiselect.js
- gulp/tasks/beep.js
- package.json
- test/browser_tests/conf.js
- test/browser_tests/default-suites.js
- test/browser_tests/page_objects/page_budget.js
- test/browser_tests/spec_suites/budget.js
- test/browser_tests/spec_suites/newsroom-press-resources.js
- test/unit_tests/modules/classes/BreakpointHandler-spec.js
- test/unit_tests/modules/util/expanded-state-spec.js
- Updates ESLint to 2.0 and fixes linting errors and some warnings.
- `./setup.sh && gulp lint` should show 0 linting errors (it will show warnings tho).
- @sebworks
> Updates ESLint to 2.0

- cfgov/v1/processors/eventpage.py
Some events in WP don't have fields that are required in Wagtail. Rather than make then non-required, I've refactored the code so it doesn't fail the imports, but will still not convert the page over.
- Changed eventpage.py processor to check to see if start and end dates exist before assignment.
- `./cfgov/manage.py import-data events eventpage --parent events -u user -p pass`
- @kave 
- There are currently 12 events that don't have the necessary fields for conversion.
- Add import-data to our build flow and send email notifications on errors
> Fix WP events processor to import events data

- cfgov/v1/models/base.py
> Fix breaking Landing pages

- cfgov/jinja2/v1/_includes/organisms/sidebar-contact-info.html
- Removed unnecessary imports for sidebar contact organism
- View a page with a sidebar contact that and it does not break
- @kurtw
> removed unnecessary imports from sidebar contact

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
- cfgov/jinja2/v1/_layouts/base.html
- cfgov/unprocessed/css/organisms/filterable-list-controls.less
- cfgov/unprocessed/js/config/error-messages-config.js
- cfgov/unprocessed/js/modules/post-filter.js
- cfgov/unprocessed/js/modules/util/dom-traverse.js
- cfgov/unprocessed/js/modules/util/type-checkers.js
- cfgov/unprocessed/js/organisms/FilterableListControls.js
- cfgov/unprocessed/js/routes/on-demand/filterable-list-controls.js
- cfgov/v1/forms.py
- cfgov/v1/models/organisms.py
Adding validation logic for FilterableListControls
-  Goto Wagtail Admin and create a `Browse Filterable Page`
- Add a `Learn Page` as a child of the page you just created.
- Publish the `Browse Filterable Page`. 
- Visit the `Browse Filterable Page` and enter in `043`. You should get an error message.
- Edit the entry to be `04`. The form should now submit. 
- Need to write unit test and fix JSDoc comments.
> Adding validation logic for FilterableListControls

- cfgov/jinja2/v1/_includes/molecules/global-header-cta.html
- cfgov/jinja2/v1/_includes/molecules/global-search.html
- Adds `/complaint/` URL to submit a complaint CTA. Note: URL is not currently active on our testing servers. CC @rosskarchner 
- Adds URL and hidden inputs for hooking up global search to our existing search engine.
- Global search should expand, contract, and clear as expected and entering text and clicking search or pressing enter should send you to the search portal.
- @sebworks 
- @jimmynotjim
> Updates search and complaint links

- cfgov/jinja2/v1/_includes/macros/share.html
- cfgov/jinja2/v1/_includes/macros/video-player.html
- cfgov/jinja2/v1/_includes/molecules/featured-content.html
- cfgov/jinja2/v1/browse-basic/index.html
- cfgov/jinja2/v1/browse-filterable/index.html
- cfgov/jinja2/v1/careers/application-process/index.html
- cfgov/jinja2/v1/sublanding-page/index.html
- cfgov/jinja2/v1/the-bureau/index.html
- cfgov/unprocessed/css/cf-enhancements.less
- cfgov/unprocessed/css/video-player.less
Added video to the FCMs.
- Added video to FCMs
- Added video FCMs to the-bureau page and careers/application-process
- CSS changes to handle video breakpoints (check them out on events pages)
- Test it on pages by creating FCMs in wagtail
- Visit `the-bureau` and `careers/application-process`
- Visit an event page with a livestream
- @sebworks 
- If you have any tips on removing the black bars, hit me up on chat and we can talk through some solutions, otherwise I'm leaving it for another PR.
> Featured Content Modules - Now with video!

- test/browser_tests/page_objects/page_about-director.js
- test/browser_tests/spec_suites/about-deputy-director.js
- test/browser_tests/spec_suites/about-director.js
- test/browser_tests/spec_suites/newsroom-press-resources.js
- test/browser_tests/spec_suites/the-bureau.js
Fixed failing tests after merging in changes to new Deputy Director bio.
Switched some references of Fuchs to Silberman, but also removed or
changed some tests to not require an exact string match to the deputy
director for the next change.
- run `gulp test:acceptance --sauce=false`
- @sebworks 
> Fixing Deputy Director Tests

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/molecules/global-search.html
- cfgov/unprocessed/js/ie/common.ie.js
- cfgov/unprocessed/js/modules/ClearableInput.js
- cfgov/unprocessed/js/modules/ExternalSite.js
- cfgov/unprocessed/js/modules/FlyoutMenu.js
- cfgov/unprocessed/js/modules/util/EventObserver.js
- cfgov/unprocessed/js/modules/util/atomic-helpers.js
- cfgov/unprocessed/js/molecules/Expandable.js
- cfgov/unprocessed/js/molecules/GlobalSearch.js
- cfgov/unprocessed/js/molecules/Notification.js
- cfgov/unprocessed/js/organisms/ExpandableGroup.js
- cfgov/unprocessed/js/organisms/FilterableListControls.js
- cfgov/unprocessed/js/organisms/Header.js
- cfgov/unprocessed/js/organisms/MegaMenu.js
- cfgov/unprocessed/js/organisms/SecondaryNavigation.js
- cfgov/unprocessed/js/routes/common.js
- Shortened atomic dom checker module and method name so that the call would fit on one line more often.
- Fixed missing flyout data-* attribute for global search.
- Fixed missing aria-hidden value on global search.
- Added some todos and code comments.
- `gulp build` should work and site shouldn't have errors.
- @sebworks 
- @jimmynotjim
> Bugfix and Minor cleanup

- cfgov/unprocessed/js/modules/util/validators.js
- cfgov/unprocessed/js/organisms/FilterableListControls.js
- test/unit_tests/modules/util/validators-spec.js
Abstracted the validators in FilterableListControls to make them testable
- Adds new validators.js for reuse and testing.
- Adds unit tests for validators.js (passes 100% across the board).
- Updates FilterableListControls to use new validators.
- Updates FilterableListControls to do all dom querying for fieldsets.
- Sneaks in linting error fixes.
- `gulp lint:scripts && gulp test:unit:scripts`
- @sebworks 
- This is a spin-off of #1521 making testing the email regex change possible
- Updates in testing coverage to:
__Before__
```
Statements   : 30.44% ( 589/1935 )
Branches     : 23.37% ( 154/659 )
Functions    : 23.19% ( 77/332 )
Lines        : 30.5% ( 586/1921 ) …
```
> Abstracted the validators in FilterableListControls

- .env_SAMPLE
- CHANGELOG.md
- cfgov/cfgov/settings/production.py
- Enabled email backend for Production settings
- TODO on flapjack
- @kurtw 
> Enabled email backend for Production settings

- cfgov/v1/forms.py
> missing hostname param

- cfgov/jinja2/v1/newsroom/press-resources/index.html
- Updated with new contact information for the press team
- Make sure information on /newsroom/press-resources matches http://www.consumerfinance.gov/newsroom/
- @sebworks 
Added new contact information and removed the outdated information.
> Updating press contacts on press resources page

- cfgov/v1/migrations/0057_auto_20160304_1651.py
> migration fix

- cfgov/jinja2/v1/careers/students-and-graduates/index.html
Minor content fixes to the Student and Graduates page to update the year where necessary.
- Visit this page: http://localhost:8000/careers/students-and-graduates/
- @sebworks
> Content fixes to the students and graduates page

- CHANGELOG.md
- cfgov/v1/migrations/0058_auto_20160309_2007.py
- cfgov/v1/migrations/0060_auto_20160310_1523.py
- cfgov/v1/models/browse_filterable_page.py
- cfgov/v1/models/learn_page.py
- Fixed ordering for Filterable results to be newest => oldest by published_date
- Import Refresh Db
- visit page `policy-compliance/guidance/implementation-guidance/` to verify 
- @kurtw 
> Fixed ordering for Filterable results 

- cfgov/scripts/archive_events.py
Event archive pages now have a specific form & model, so updating script to account for this
- @kurtw
> Fixing Archive Events Script

- cfgov/v1/models/molecules.py
Adding a CSS class to the Hero fixes the weird spacing issues we've been
seeing.
- Visit a page in wagtail with a hero. You shouldn't see the issues in #1556.
- @kave 
- @kurtw
> Simple fix to #1556

- cfgov/jinja2/v1/_includes/organisms/post-preview.html
- cfgov/jinja2/v1/sublanding-page/index.html
- cfgov/v1/models/sublanding_page.py
- Post preview snapshot is rendering correctly.
- Import Refresh Db
- visit page `policy-compliance/amicus/` to verify 500 error is gone and post preview items render correctly
- @kurtw 
> post preview snapshot is now fixed.

- cfgov/jinja2/v1/index.html
- cfgov/v1/migrations/0064_auto_20160311_1727.py
- cfgov/v1/models/home_page.py
> Fixed Dates and removed render all activites

- CHANGELOG.md
> Fix resolved changelog

- cfgov/v1/models/browse_page.py
- Removed unnecessary elements function from Browse Page
- Import Refresh Db
- visit this page `http://content.localhost:8000/about-us/payments-harmed-consumers/civil-penalty-fund/` and verify the expandable works correctly
- @kurtw 
Was:
Now:
> Fixed Browse Page JS loading

- cfgov/v1/models/base.py
- cfgov/v1/models/sublanding_page.py
> Fix post preview rendering correct pages by state

- CHANGELOG.md
- cfgov/unprocessed/js/modules/Tree.js
- cfgov/unprocessed/js/modules/util/tree-traversal.js
Adds Tree data structure for more easily querying the submenus of the mega menu. Also adds utility tree traversal algorithms.
- JS Tree data structure.
- JS Tree traversal algorithms.
- Can be tested by adding the following snippet to a page's JS (common.js or Header.js, or whatever):
```
var Tree = require( '../modules/Tree' );
var treeTraversal = require( '../modules/util/tree-traversal' );
/**
* Make this Tree:
*        R
*       / \
*      A   B
*    / | \
*   C  D  E
*/
var tree = new Tree();
tree.init( 'R' );
var nodeR = tree.getRoot();
var nodeA = tree.add( 'A', nodeR );
var nodeB = tree.add( 'B', nodeR );
var nodeC = tree.add( 'C', nodeA );
var nodeD = tree.add( 'D', nodeA );
var nodeE = tree.add( 'E', nodeA );
var level1 = tree.getAllAtLevel( 1 );
for ( var i = 0, len = …
```
> Mega Menu: Adds Tree and Tree traversal data structure

- cfgov/unprocessed/js/modules/secondary-nav-toggle.js
- cfgov/unprocessed/js/modules/util/data-hook.js
- gulp/config.js
- test/browser_tests/jenkins_conf.js
- Fixes a few linter errors and warnings.
- @sebworks 
- @jimmynotjim
> Minor linter cleanup

- cfgov/jinja2/v1/_includes/macros/active-filters.html
> Fix paginator bug

- cfgov/jinja2/v1/_includes/molecules/global-eyebrow.html
- cfgov/unprocessed/css/molecules/global-eyebrow.less
Adds the phone number to the global eyebrow :eyes: 
- Test on any page both desktop/mobile
- @sebworks
> Adding phone number to global eyebrow

- cfgov/jinja2/v1/_queries/careers.json
> Fix current openings query

- cfgov/jinja2/v1/_includes/macros/footer-global.html
- test/browser_tests/spec_suites/footer.js
- Add working with tribal governments link to the footer
- Check out the footer.
- @sebworks 
- @schaferjh
> Add working with tribal governments link

- cfgov/jinja2/v1/_includes/molecules/global-eyebrow.html
- Fixed links for language pages on global eyebrow
- Visit the eyebrow links! They should match up with what's in DFJR-1039.
- @sebworks 
- @jimmynotjim
> Fixed links for language pages on global eyebrow

- cfgov/v1/util/util.py
- removed page reference and calling function from its util location
- @kurtw 
- visit [here](http://content.localhost:8000/policy-compliance/guidance/implementation-guidance/supervisory-matters-appeal-process/)
- verify clicking tag in the side bar routes you to the appropriate filtered page
> Fixes Tags on related metadata

- test/browser_tests/spec_suites/newsroom.js
> We've stopped featuring a topic on the Newsroom

- cfgov/jinja2/v1/doing-business-with-us/small-businesses/index.html
Added a link to the diversity statement to the Small Minority-owned Business page.
- Visit http://localhost:8000/doing-business-with-us/small-businesses/. Note the new link
- @tnferrell 
- @sebworks 
- @jimmynotjim
> Adding link to Doing Business with Us Page

- cfgov/jinja2/v1/browse-filterable/index.html
> closed conditional correctly

- cfgov/jinja2/v1/_includes/molecules/expandable.html
- cfgov/jinja2/v1/wagtail/demo/index.html
- cfgov/v1/__init__.py
-
-
- provided a conditional to handle raw html passed into parse_links
- fixed related links to return the correct value
-
- @user
-
-
> Refresh hotfixes

- test/browser_tests/spec_suites/dbwu-small-businesses.js
This content seems to have changed in the CMS. Silenced the test so we can look into it when we rewrite these tests.
> Silenced failing small business test, needs refactoring w the rest

- cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
BEWD portion of https://github.com/cfpb/cfgov-refresh/pull/1643
> Filters stay expanded after submitting 

- cfgov/core/services.py
- cfgov/jinja2/v1/_includes/macros/filters.html
- cfgov/v1/forms.py
Filter id changes had render PDFReactor non-functional. The generator was refactored to account for these changes
- refactored filter input ids and date formatter
- @kurtw 
- @sebworks
> fixes for leadership calendar downloads

- cfgov/scripts/publish_shared_pages.py
Does what it says
- Run `./cfgov/manage.py runscript publish_shared_pages`
@kave 
@richaagarwal 
@rosskarchner
> Add script to publish all pages that have been shared.

- cfgov/scripts/publish_shared_pages.py
The actual page object in the database wasn't being set to live. This should do the trick.
@kave
> Fixup the publish all script

- cfgov/jinja2/v1/_includes/molecules/global-search.html
- Adds hardcoded suggested search URLs.
- Resize to tablet size, expand search, and click suggested search links.
- @sebworks 
- @schaferjh 
> Adds hardcoded search URLs

- cfgov/jinja2/v1/_includes/molecules/related-posts.html
- Updates helper method to remove multiple lookups within block object of helper.
- Updates code comment for missing argument.
- @kurtw 
- @kave 
> Updates helper method to remove multiple lookups

- cfgov/unprocessed/js/modules/MobileCarousel.js
- cfgov/unprocessed/js/modules/form-validation.js
- cfgov/unprocessed/js/modules/jquery/cf_formValidator.js
- cfgov/unprocessed/js/modules/jquery/cf_notifier.js
- cfgov/unprocessed/js/modules/util/data-set.js
- cfgov/unprocessed/js/modules/util/validators.js
- cfgov/unprocessed/js/modules/util/web-storage-proxy.js
- cfgov/unprocessed/js/molecules/Multiselect.js
- cfgov/unprocessed/js/organisms/MegaMenu.js
- test/browser_tests/page_objects/page_blog-single.js
- test/browser_tests/shared_objects/header.js
- test/browser_tests/spec_suites/bureau-structure.js
- test/browser_tests/spec_suites/header.js
- Adds missing jsdocs.
- Fixes eslint errors and some warnings.
- `gulp lint` shouldn't show errors.
- @sebworks 
> dfjr-33 - jsdoc/linter cleanup

- cfgov/jinja2/v1/_includes/macros/filters.html
> Pass id_prefix to category options for sheer page filters

- cfgov/scripts/setup_sites.py
@kave just an addition to your changes, so that I can run this from `refresh-data.sh` :)
> Make setup_sites param optional

- CHANGELOG.md
- cfgov/unprocessed/js/modules/util/array-helpers.js
- cfgov/unprocessed/js/molecules/Multiselect.js
- test/unit_tests/modules/util/array-helpers-spec.js
Based on https://github.com/cfpb/cfgov-refresh/pull/1668#issuecomment-200021403 I simplified the code in the Multiselect that keeps track of the user's selections and updates the dom accordingly.
- Adds tests for searchArrayObjects helper.
- Uses the native indexOf when available.
- Updates valInArray to searchArrayObjects which return an index when searching for a key:value match instead of the boolean|object confusion.
- `gulp build` and use the multiselect (`/blog` is a good spot). It should work as before.
- @sebworks 
__Before__
```
Statements   : 26.62% ( 712/2675 )
Branches     : 21.97% ( 192/874 )
Functions    : 19.58% ( 84/429 )
Lines …
```
> Simplified how the Multiselect does array searches.

- cfgov/unprocessed/js/modules/util/tree-traversal.js
- test/unit_tests/modules/util/tree-traversal-spec.js
- Adds unit tests for tree-traversal.
- Corrects issue where `this` could be undefined in the tree traversal methods.
- `gulp test:unit:scripts`, tests should pass.
- @sebworks 
> Adds tests for tree-traversal

- test/unit_tests/modules/util/atomic-helpers-spec.js
- Adds spec for atomic-helpers utility method.
- `gulp test:unit:scripts` should pass.
- @sebworks 
> Adds atomic-helper spec

- test/unit_tests/modules/util/array-helpers-spec.js
- test/unit_tests/modules/util/dom-manipulators-spec.js
- test/unit_tests/modules/util/dom-traverse-spec.js
- Removes some unused variables and requires from tests.
- `gulp lint` warnings should be below 100.
- @sebworks 
- I'll get the warnings in the GlobalBanner and Tree separately.
> Fixes linter warnings

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/macros/footer-global.html
- Add Digital Privacy Policy to the footer
- @sebworks 
> Add Digital Privacy Policy to the footer

- cfgov/v1/models/base.py
@richaagarwal 
@kave 
@rosskarchner
> Change date order for events in related posts

- test/unit_tests/modules/util/atomic-helpers-spec.js
- test/unit_tests/molecules/GlobalBanner-spec.js
- Fixes linter issues in tests.
- `gulp lint` < 100 warnings, no errors.
- `gulp test:unit:scripts` passes.
- @sebworks 
> linter fixes

- CHANGELOG.md
- cfgov/jinja2/v1/index.html
Updated the homepage links
- Updated the links on the homepage
- `gulp build` and hover each link, cross reference the slugs with DFJR-1093
- @sebworks 
> Updated the homepage links

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/article.html
- cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
- cfgov/jinja2/v1/_includes/organisms/full-width-text.html
- cfgov/jinja2/v1/_includes/tags.html
- cfgov/jinja2/v1/_layouts/base.html
- cfgov/jinja2/v1/index.html
- cfgov/scripts/setup_sites_prod.py
- cfgov/unprocessed/css/atoms/multi-select.less
- cfgov/unprocessed/css/molecules/full-width-text.less
- cfgov/unprocessed/css/organisms/mega-menu.less
- cfgov/unprocessed/js/modules/FlyoutMenu.js
- cfgov/unprocessed/js/modules/util/dom-traverse.js
- cfgov/unprocessed/js/modules/util/strings.js
- cfgov/unprocessed/js/molecules/Multiselect.js
- cfgov/v1/models/base.py
- cfgov/v1/models/browse_filterable_page.py
- cfgov/v1/models/browse_page.py
- cfgov/v1/models/molecules.py
- cfgov/v1/models/organisms.py
- test/unit_tests/modules/util/atomic-helpers-spec.js
- test/unit_tests/modules/util/dom-traverse-spec.js
- test/unit_tests/modules/util/strings-spec.js
- test/unit_tests/molecules/GlobalBanner-spec.js
> Flapjack to Refresh push

- cfgov/unprocessed/js/modules/FlyoutMenu.js
- cfgov/unprocessed/js/modules/util/strings.js
- test/unit_tests/modules/util/strings-spec.js
- Fixes minor linter errors/warnings.
- `gulp lint` - no errors.
- @sebworks 
> Minor jsdoc/linter fixes.

- cfgov/jinja2/v1/careers/_template-careers-related-links.html
- cfgov/jinja2/v1/careers/_template-provide-feedback.html
- cfgov/jinja2/v1/careers/application-process/index.html
- cfgov/jinja2/v1/careers/current-openings/index.html
- Updates content in the careers section
- Updates `/careers/` noted in gdoc linked in DFJR-1122 task.
- @tnferrell 
- @schaferjh
> DFJR-1122-career section content updates

- cfgov/jinja2/v1/_includes/macros/filters.html
- cfgov/jinja2/v1/events/_filter.html
- test/browser_tests/page_objects/page_activity-log.js
- test/browser_tests/page_objects/page_leadership-calendar.js
- test/browser_tests/shared_objects/filter.js
- test/browser_tests/spec_suites/blog.js
- test/browser_tests/spec_suites/footer.js
Fixes for Acceptance Tests
- Run `gulp test:acceptance`
- @jimmynotjim
> Fixes for Accceptance Tests

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/molecules/hero.html
- cfgov/unprocessed/css/molecules/home-hero.less
Update the Hero Macro for the new overlay hero styles
- Adds `overlay` and `white-text` modifiers to the hero options
- Adds `lg_image` for the background to the hero options
- Changes the `image` option to `sm_image`
- Fixes naming in the home-hero stylesheet
- Will need the CMS side to really test this, but you could create a hero manually on a static page with the following options.
```
{
'is_overlay': true,
'is_white_text': true,
'heading': 'Test Overlay Hero',
'body': 'Test overlay hero body content',
'lg_image': 'http://beta.consumerfinance.gov/static/img/home-hero_lg.jpg`,
'sm_image': 'http://beta.consumerfinance.gov/static/img/home-hero_sm.jpg`,
}
```
- @sebworks 
- This is using the Homepage image even though it's not the homepage. It's what …
> Update the Hero Macro for the new overlay hero styles

- .gitattributes
Testing merge=union on CHANGELOG to avoid conflicts
- gitattributes file with merge rule for CHANGELOG
- Let's merge some PRs :D
- @sebworks 
- See https://github.com/cfpb/capital-framework/issues/304
> Testing merge=union on CHANGELOG to avoid conflicts

- cfgov/unprocessed/css/molecules/global-banner.less
- Fixes banner CSS to remove top border from expand/collapse button, fixes transition, and fixes padding at table/mobile.
- `gulp build`, resize to mobile, see that left/right padding prevents text from going to edges.
- @sebworks
> Fixes banner CSS

- cfgov/jinja2/v1/index.html
- Fixes missing activity-log link.
- @schaferjh 
- @sebworks
> DFJR-1147 - Adds missing link

- cfgov/jinja2/v1/_layouts/404.html
- Fixes contact us link and styles on 404 page.
- Removes jump styles.
- Can't be tested locally unless you turn off DEBUG=true.
- @schaferjh 
- @sebworks 
> DFJR-1100 - Fixes contact us link on 404

- cfgov/jinja2/v1/_includes/templates/upcoming-events.html
- cfgov/jinja2/v1/newsroom/press-resources/index.html
- test/browser_tests/page_objects/page_newsroom-press-resources.js
- test/browser_tests/spec_suites/newsroom-press-resources.js
- Updates copy.
- Adds Walter Suskind
- Adds dep. director bio link.
- Updates bio links and events link.
- Visit /newsroom/press-resources/
- links for the director biography's don't work for me locally, but I'm told they will on the live site at the /about-us/ URL.
- @schaferjh 
- @sebworks 
> Updates press resources page

- gulp/tasks/styles.js
- Adds BB to autoprefixer settings
- `gulp build` should pass.
- @sebworks 
- Looking to test this out on refresh and see if it makes a difference for BB.
> Adds BB to autoprefixer settings

- cfgov/unprocessed/js/routes/on-demand/expandable.js
- cfgov/unprocessed/js/routes/on-demand/notification.js
> Hotfix: set correct constructor

- cfgov/jinja2/v1/_layouts/base.html
Looks like I forgot the bureau's title.
@kave 
@richaagarwal
> Add CFPB to page title

- gulp/tasks/styles.js
- gulp/tasks/test.js
- test/browser_tests/page_objects/page_activity-log.js
- test/browser_tests/page_objects/page_leadership-calendar.js
- test/browser_tests/shared_objects/filterable-list-control.js
- Fixes linter error.
- @sebworks
> Minor linter fix

- cfgov/jinja2/v1/_includes/article.html
- cfgov/jinja2/v1/careers/_single.html
- cfgov/jinja2/v1/events/_event-detail.html
> Add sharing titles

- cfgov/jinja2/v1/_layouts/500.html
- Same update as https://github.com/cfpb/cfgov-refresh/pull/1759 for the 500 error page.
- @schaferjh 
- @sebworks
> Fixes contact us format on 500 error page

- CHANGELOG.md
- cfgov/jinja2/v1/about-us/the-bureau/index.html
- test/browser_tests/page_objects/page_the-bureau.js
- test/browser_tests/spec_suites/the-bureau.js
- Remove the bureau leadership section
- Other content fixes
- Remove related browser tests
- Visit http://localhost:8000/about-us/the-bureau/
- @sebworks 
- @schaferjh
> Content Changes to the Bureau page

- cfgov/unprocessed/js/routes/sheer.js
Fix for In This Section expandable. Closes issue #1801.
- Changed selector to include the nav. 
-  Run `gulp build` and visit `http://localhost:8000/about-us/doing-business-with-us/` at mobile sizes.
- @jimmynotjim
> Fix for In This Section expandable

- cfgov/unprocessed/js/modules/FlyoutMenu.js
- test/browser_tests/spec_suites/organisms/mega-menu.js
- test/unit_tests/modules/FlyoutMenu-spec.js
- Adds initial mega menu tests at desktop size.
- `gulp test:acceptance --specs=organisms/mega-menu.js --sauce=false` should pass.
- @sebworks 
- @jimmynotjim
> Adds initial mega menu tests - desktop size

- CHANGELOG.md
- cfgov/jinja2/v1/about-us/the-bureau/about-deputy-director/index.html
- cfgov/jinja2/v1/about-us/the-bureau/about-director/index.html
- Updated director and deputy director bios
- Visit http://localhost:8000/about-us/the-bureau/about-director/
and http://localhost:8000/about-us/the-bureau/about-deputy-director/
- @sebworks 
- @schaferjh
> Update director and deputy director bios

- CHANGELOG.md
- cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/index.html
- Updated the leadership calendar copy 
- Updated links in leadership calendar page and removed History link
- Visit http://localhost:8000/about-us/the-bureau/leadership-calendar/ and test the links in the footer!
- @sebworks
> Updated the leadership calendar copy and links

- cfgov/cfgov/settings/test.py
- cfgov/scripts/initial_test_data.py
- gulp/tasks/test.js
- initial-test-data.sh
Merging this but wanted to keep you in the loop. We are now transitioning to use flapjack as the test server the init data will just create the pages side-by-side our refresh data.
Also added conditionals to the init-data so theres no need to drop the db anymore
> prep for jenkins test builds

- cfgov/jinja2/v1/blog/index.html
Just get rid of Popular posts for now, since it's causing problems.
@kave 
@richaagarwal
> Remove popular posts for now

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/on-demand/footer.html
- cfgov/jinja2/v1/_includes/on-demand/header.html
- cfgov/jinja2/v1/_includes/organisms/footer.html
- cfgov/jinja2/v1/_layouts/base.html
- cfgov/unprocessed/css/main.less
- cfgov/unprocessed/css/on-demand/footer.less
- cfgov/unprocessed/css/organisms/footer.less
- cfgov/unprocessed/css/organisms/prefooter.less
- cfgov/unprocessed/js/organisms/Footer.js
- cfgov/unprocessed/js/routes/common.js
- cfgov/unprocessed/js/routes/on-demand/footer.js
- cfgov/unprocessed/js/routes/on-demand/header.js
- package.json
- test/browser_tests/shared_objects/footer.js
- test/browser_tests/spec_suites/organisms/footer.js
- test/browser_tests/spec_suites/organisms/global-search.js
- Updated footer to be atomic.
- run `gulp scripts:ondemand && styles:ondemand` and check `http://localhost:8000/test-fixture/?atomic=footer`
- run `gulp build` and site footer on the site should look/function the same (return to top at mobile should work).
- @sebworks 
- @jimmynotjim
> Adds atomic footer

- cfgov/scripts/initial_test_data.py
> runscript didn't like non-specific imports on the server

- cfgov/jinja2/v1/_layouts/base.html
- cfgov/unprocessed/js/modules/VideoPlayer.js
- cfgov/unprocessed/js/molecules/Expandable.js
- cfgov/unprocessed/js/shims/es5-shim.js
- gulp/tasks/scripts.js
- package.json
Adding Fixes for BB7 and BB10.  Fixes issue https://github.com/cfpb/cfgov-refresh/issues/1672.
-  Added entry in `package.json` for `ES5-Shim`. 
-  Added `Shim/Sham` ES5 scripts to support BB7 and BB10.
-  Added build script for ES5.
- Modified `Expandable.js` to fix issue adding transition without a prefix.
- Modified `YoutubePlayer.js` to fix issues surrounding lack of polyfill support for Object literal getters/setters.
- Modified `Base.html` to load es5 shim scripts. 
- ~~Visit the site via Sauce Labs using a BB7 or BB10.~~ I'm working on an alternative solution for testing that doesn't make you hate Blackberry. If you were so inclined you could download the 9930 simulator and install it on your IE VM. http://swdownloads.blackberry.com/Downloads/contactFormPreload.do?code=060AD92489947 …
> Adding Fixes for BB7 and BB10

- cfgov/jinja2/v1/_layouts/base.html
- cfgov/unprocessed/js/modules/VideoPlayer.js
- cfgov/unprocessed/js/molecules/Expandable.js
- cfgov/unprocessed/js/shims/es5-shim.js
- gulp/tasks/scripts.js
- package.json
- Adding Fixes for BB7 and BB10
> Update Refresh from Flapjack Branch

- frontend.sh
Fix for ondemand script
-  run `./frontend.sh production`
> Fix for ondemand script

- .travis.yml
- cfgov/cfgov/settings/test.py
- cfgov/sheerlike/test_templates.py
> Use sqlite for test database

- cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
- Updates incorrect link in mega menu.
- Visit link in beta.
- @schaferjh
> Updates incorrect link

- gulp/tasks/scripts.js
Added uglification step to the ES5 shim process.
- Run `gulp build`.
> Uglify ES5 shim

- cfgov/jinja2/v1/_includes/on-demand/header.html
- Adds overlay to on-demand header. WHhhoooops
- http://localhost:8000/test-fixture/?atomic=header at mobile should not be broken.
- @sebworks 
- @jimmynotjim
> Adds overlay to on-demand header

- Vagrantfile
- ansible/cfgov_refresh_setup.yml
- bin/cfgov
- bin/cfgovd
- frontend.sh
- piped gulp watch output to developer
- installs gcc to remove optional dependency failures
- None
- Re-wrote some spacing.
- @vickumar1981 @kave
> Gcc update to 48

- cfgov/jinja2/v1/events/event.html
- cfgov/jinja2/v1/events/request-a-speaker.html
> Hotfix page.seo_description

- cfgov/core/services.py
request POST param names had changed
> fixed request param names for leadership pdf downloads

- cfgov/processors/processors_common.py
go [here](http://localhost:8000/about-us/project-catalyst/run-trial-disclosure/) an click step 1 or 3 in the middle of the page.
> fixed mailTo link rendering in richtext

- cfgov/v1/__init__.py
@kurtw 
didn't compare the classname like i intended
> added full classnames back in

- cfgov/unprocessed/js/organisms/MegaMenuDesktop.js
- Removes five MegaMenuDesktop lint warnings.
- `gulp lint:scripts` should show no remaining complexity warnings for MegaMenuDesktop script.
- `gulp build` and menu should still work as before.
- @sebworks 
- @jimmynotjim
> Fixes menu complexity warnings

- cfgov/sheerlike/test_filters.py
So...these just haven't been running. This fixes it.
@kave 
@richaagarwal 
@rosskarchner
> Fix some sheerlike tests

- cfgov/cfgov/settings/base.py
- cfgov/cfgov/urls.py
- this adds a few settings that eregs requires
-
-
> Some extra settings needed for eregs

- cfgov/unprocessed/js/modules/transition/AlphaTransition.js
- cfgov/unprocessed/js/modules/transition/BaseTransition.js
- cfgov/unprocessed/js/modules/transition/MoveTransition.js
- cfgov/unprocessed/js/organisms/MegaMenuDesktop.js
- test/unit_tests/modules/FlyoutMenu-spec.js
- test/unit_tests/modules/transition/BaseTransition-spec.js
- Adds unit test for BaseTransition
- Updates transition methods to return false if they're called before the transition is initialized.
- @sebworks
> Adds unit test for BaseTransition

- CHANGELOG.md
- bower.json
- cfgov/core/services.py
- cfgov/unprocessed/js/modules/FlyoutMenu.js
- cfgov/unprocessed/js/modules/transition/AlphaTransition.js
- cfgov/unprocessed/js/modules/transition/BaseTransition.js
- cfgov/unprocessed/js/modules/transition/MoveTransition.js
- cfgov/unprocessed/js/modules/util/assign.js
- cfgov/unprocessed/js/modules/util/fn-bind.js
- cfgov/unprocessed/js/molecules/Expandable.js
- cfgov/unprocessed/js/molecules/GlobalSearch.js
- cfgov/unprocessed/js/organisms/MegaMenu.js
- cfgov/unprocessed/js/organisms/MegaMenuDesktop.js
- cfgov/unprocessed/js/organisms/MegaMenuMobile.js
- test/unit_tests/modules/FlyoutMenu-spec.js
- test/unit_tests/modules/transition/BaseTransition-spec.js
- Adds unit test for BaseTransition
- explicitly setting the PDFreactor license to a string, to fix the leadership bureau calendar download
- Support orientation change
- Fix for BB on non V1 pages
> Beta Update from Refresh

- cfgov/scripts/initial_test_data.py
- test/browser_tests/spec_suites/wagtail/molecules.js
Run `gulp test:acceptance:wagtail --specs=molecules.js` to test. 
@kave @rosskarchner @kurtw
> Add a test for text intro

- cfgov/scripts/initial_data.py
- initial-data.sh
> cleaned up init data

- cfgov/jinja2/v1/_layouts/base.html
- cfgov/jinja2/v1/events/event.html
- cfgov/jinja2/v1/events/request-a-speaker.html
Sets it up for `page`
@kave @richaagarwal @rosskarchner
> Set up seo description content for pages

- cfgov/core/services.py
- cfgov/legacy/views.py
- included an additional check for pdfReactor to render a better exception message for local developers 
- fixed imports for PDFreactor in HousingCounselorPDFView breaking the views.
- @kurtw 
@richaagarwal @rosskarchner
> Pdfreactor Exception message

- cfgov/jinja2/v1/about-us/careers/_template-linkedin.html
- Linkeden link is now an external link [here](http://localhost:8000/about-us/careers/current-openings/)
> made linken url an external link

- cfgov/legacy/forms.py
- cfgov/legacy/views.py
@rosskarchner 
created the form, and included some missing imports that we're likely breaking that [url](http://localhost:8000/save-hud-counselors-list/?zip=22153)
i'll verify on the build site, when this is merged
> resolved request param validation by wrapping in a form

- cfgov/legacy/views.py
> returning a pdf instead of zip

- cfgov/processors/processors_common.py
- Verify you can view the pdf [here](http://localhost:8000/policy-compliance/amicus/briefs/sheriff-gillie/)
> included netloc in the url

- .env_SAMPLE
- cfgov/cfgov/settings/base.py
- cfgov/cfgov/settings/local.py
- cfgov/cfgov/urls.py
@kurtw @rosskarchner @richaagarwal
> included a flag to allow/disallow access to Django-Admin & Wagtail Admin

- cfgov/cfgov/urls.py
@kurtw @richaagarwal @rosskarchner 
- Log into Django-Admin and create a new user
> django admin now uses wagtail user creation, consistent with change password

- cfgov/cfgov/settings/base.py
- cfgov/templates/admin/base.html
- cfgov/templates/wagtailadmin/home.html
- cfgov/templates/wagtailadmin/login.html
- cfgov/templates/wagtailadmin/shared/main_nav.html
- requirements/base.txt
@kurtw @rosskarchner @richaagarwal
> Links for Wagtail/Django Admin navigation + Branding

- cfgov/v1/__init__.py
- get the latest refresh dump
- observe this [page](http://localhost:8000/policy-compliance/rulemaking/small-business-review-panels/arbitration-agreements/) now loads correctly
> return None if no viable ancestor is found

- cfgov/jinja2/v1/newsroom/index.html
- cfgov/v1/models/browse_filterable_page.py
> Add static footer content to Newsroom Landing page

- cfgov/v1/__init__.py
> added conditional to account for none pages

- CHANGELOG.md
- cfgov/jinja2/v1/events/_event-detail.html
Added the correct link for livestream help
- Livestream FAQ link
- Kind of hard while without any live events, but if you edit one to be live right now in the admin, it'll show up.
- @sebworks 
> Added the correct link for livestream help

- cfgov/jinja2/v1/_includes/molecules/text-introduction.html
> incorrect field

- CHANGELOG.md
- cfgov/jinja2/v1/about-us/doing-business-with-us/index.html
- cfgov/jinja2/v1/about-us/doing-business-with-us/upcoming-procurement-needs/index.html
These edits come straight from EA and have been approved for release.
- Updated `doing-business-with-us` and `doing-business-with-us/upcoming-procurement-needs`
- navigation to `/doing-business-with-us/` and `/doing-business-with-us/upcoming-procurement-needs/`. Content should match the doc in Jira DFJR-1284
- @schaferjh 
- @sebworks 
- @sarahsimpson09
> Content updates from EA

- cfgov/legacy/views.py
@rosskarchner @kurtw @richaagarwal 
url had to be relative to the localhost, it had problems resolving the `build` hostname
> our final battle

- cfgov/jinja2/v1/_includes/molecules/related-posts.html
I think this bit of code got incorrectly rolled back in a rebase or something.
@kave @rosskarchner @richaagarwal
> Add view more back in

- test/browser_tests/spec_suites/careers.js
Updated title casing for carees info section
- `gulp test:acceptance --sauce=false`
- @sebworks
> Updated title casing for carees info section

- test/browser_tests/spec_suites/organisms/mega-menu.js
- Adjusts tests to account for delay in menu on hover.
- `gulp build && gulp test:acceptance --sauce=false --specs=organisms/mega-menu.js` should pass.
- @sebworks
> Updates menu tests to account for delay

- cfgov/v1/util/filterable_context.py
- view [here](http://localhost:8000/about-us/events/archive-past-events/) to see archived pages now render. and non archived pages display where they should
> handles archived and non-archived pages

- cfgov/unprocessed/js/modules/transition/BaseTransition.js
- gulp/tasks/scripts.js
Minor fixes to improve our Code Climate grade.
- Add brackets in single-line if statements (CC prefers this, we should prob align our linter with it).
- Consolidates redundant code in scripts.js gulp task.
- `gulp build` should build and not break the site.
- @sebworks
> Code climate fixes

- TERMS.md
- bower.json
- package.json
Removes unused packages + updates TERMS exceptions
- Added Modernizr license exception for code derived from modernizr codebase.
- From TERMS.md exceptions section:
- rainbow.js
- Brackets Theme
- Chosen
- history.js
- String Scoring Algorithm
- From package.json and bower:
- history.js
- Chosen
- String Scoring Algorithm
- `./frontend.sh` should build and site should not be changed.
- @sebworks 
- @jimmynotjim
> Removes unused packages + updates TERMS exceptions

- cfgov/jinja2/v1/_layouts/base.html
Not prototyping anymore!
- Fallback meta description text
- @schaferjh
> Update fallback meta description text

- cfgov/core/tests/test_views.py
- cfgov/core/views.py
- cfgov/jinja2/v1/_includes/organisms/reg-comment.html
- cfgov/jinja2/v1/regulation-comment/error/index.html
- Also update form layout slightly
- Remove tests that are no longer needed
**Review:**
- @kurtw
- @sebworks
- @amymok
> Make name fields optional for reg comment form

- cfgov/jinja2/v1/regulation-comment/success/index.html
> Modify success response text

- cfgov/jinja2/v1/_includes/on-demand/footer.html
- cfgov/jinja2/v1/test-fixture/index.html
- Added code comment for digital gov script.
- Consolidated if statement in on-demand landing page.
- @sebworks 
> Minor code cleanup

- cfgov/unprocessed/js/molecules/GlobalSearch.js
- cfgov/unprocessed/js/molecules/Multiselect.js
- test/browser_tests/spec_suites/organisms/mega-menu.js
- test/browser_tests/spec_suites/wagtail/molecules.js
- test/unit_tests/molecules/Multiselect-spec.js
- Fixes linter errors and warnings
- @sebworks
> Fixes linter errors

- cfgov/v1/util/util.py
- Removes unused parameter from `get_secondary_nav_items` function.
- @kave 
- @kurtw
> Removes unused parameter

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/molecules/contact-phone.html
- cfgov/jinja2/v1/_includes/molecules/form-field-with-button.html
- cfgov/jinja2/v1/activity-log/index.html
- cfgov/scripts/initial_test_data.py
- test/browser_tests/page_objects/page_wagtail_states_pages.js
- test/browser_tests/page_objects/page_wagtail_templates.js
- test/browser_tests/spec_suites/wagtail/wagtail-page-states-pages.js
- test/browser_tests/spec_suites/wagtail/wagtail-page-templates.js
- Included additional page template tests for new page types
- No longer need to refresh your db when test data has had content updated.
- `gulp test:acceptance:wagtail --specs=wagtail/wagtail-page-templates.js` all tests pass
- @kurtw @richaagarwal
> updated init data script and included page template tests

- test/unit_tests/modules/util/standard-type-spec.js
- Implements standard-type unit tests
- `gulp test:unit` should pass
- @sebworks 
- @jimmynotjim
> Implements standard-type unit tests

- test/browser_tests/page_objects/page_wagtail_states_pages.js
- test/browser_tests/spec_suites/wagtail/wagtail-page-states-pages.js
> Fix linter warnings

- cfgov/cfgov/settings/local.py
accidently stomped on this change
@richaagarwal
> reverted local db options setting

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/molecules/contact-address.html
- cfgov/jinja2/v1/_includes/molecules/contact-email.html
- cfgov/jinja2/v1/_includes/molecules/contact-phone.html
- cfgov/jinja2/v1/_includes/molecules/expandable.html
- cfgov/jinja2/v1/_includes/molecules/form-field-with-button.html
- cfgov/jinja2/v1/_includes/organisms/half-width-link-blob-group.html
- cfgov/jinja2/v1/_includes/organisms/image-text-25-75-group.html
- cfgov/jinja2/v1/_includes/organisms/image-text-50-50-group.html
- cfgov/scripts/initial_test_data.py
- test/browser_tests/spec_suites/wagtail/molecules.js
- Additional Molecule Tests
- `gulp test:acceptance:wagtail --specs=molecules.js`
- @kurtw @richaagarwal
> Completes Browser Molecule tests

- cfgov/scripts/initial_test_data.py
sidefoot data wasn't being published correctly. This is now resolved
> simplified data creation for sidefoot

- .travis.yml
- package.json
- Updated travis/package node version
> Upgrade node version to match jenkins

- cfgov/unprocessed/js/modules/FlyoutMenu.js
- test/browser_tests/spec_suites/wagtail/molecules.js
- Minor linter fixes to clear errors and line length warnings.
- @sebworks 
- @jimmynotjim
> Minor linter fixes

- cfgov/jobmanager/admin.py
- cfgov/jobmanager/models.py
- fixed url used by jobs url's for career detail pages
- checkout jira story DFJR-1408 for steps
- @rosskarchner @kurtw @richaagarwal
> fixed view_site redirect to career details page

- CHANGELOG.md
- cfgov/v1/migrations/0084_auto_20160510_1832.py
- cfgov/v1/models/blog_page.py
- Image Text 50 50 Organism to Blog Page
- Create a blog page with this molecule
- @kurtw @richaagarwal
> included Image5050Text to blog pages

- cfgov/v1/models/blog_page.py
- cfgov/v1/views.py
- Fixed Password Reset Flow
- Fixed saving of Legacy Blog Pages
> Update Beta from Flapjack Branch

- cfgov/unprocessed/css/on-demand/secondary-navigation.less
- cfgov/unprocessed/js/routes/on-demand/secondary-navigation.js
- Updates on-demand secondary navigation CSS to use CF resources by reference.
- Updates on-demand secondary navigation JS to check for presence of dom before initializing.
- Needed updates for fin-ed-resources that have already been tested in https://github.cfpb.gov/CFGOV/fin-ed-resources/pull/70
- @Scotchester
> Updates on-demand secondary navigation

- cfgov/v1/models/browse_filterable_page.py
@sebworks 
- Verify event archive page is renderable and filters are working correctly
> missing template assignment

- CHANGELOG.md
- cfgov/jinja2/v1/_includes/organisms/post-preview.html
- cfgov/jinja2/v1/events/_event-detail.html
- cfgov/v1/migrations/0085_auto_20160519_1855.py
- cfgov/v1/models/learn_page.py
- Rename Events body field => Subheading 
- Switch render location of live/future body fields to under the map (new body location)
- Change date used for post preview from date published to actual event date. 
> Events Updates

- requirements/base.txt
@rosskarchner @richaagarwal @kurtw
> missing publish_eccu requirements

- cfgov/jinja2/v1/_includes/macros/time.html
- Fixes https://github.com/cfpb/cfgov-refresh/issues/936
- @sebworks
> Fixes #936 - updates show_only name

- cfgov/v1/migrations/0086_auto_20160523_1709.py
Adding migration for live stream validation
- Adding migration for live stream validation
- @kave 
-
-
> Adding migration for live stream validation

- CHANGELOG.md
- cfgov/v1/models/sublanding_page.py
hotfix for bad call to get_page_set from changing its location in #2085 
- @kave
> Fix Notices and Comment

- CHANGELOG.md
- cfgov/v1/models/sublanding_page.py
> resolved notices page 500s, due to filtering refactorings

- CHANGELOG.md
- cfgov/v1/models/sublanding_page.py
- get_browsefilterable_posts() call to get_page_set
> Beta hotfix

- ansible/cfgov_refresh_setup.yml
- bin/cfgov
- Adds yum dependencies for lxml to vagrant vm
-
-
-
- @kave @anselmbradford 
-
-
> Adding yum dependencies for lxml requirement.

- test/unit_tests/modules/ClearableInput-spec.js
Adding unit tests for clearable input
- Adding unit tests for clearable input
- Run `gulp test:unit:scripts`.
-
-
> Adding unit tests for clearable input

- INSTALL.md
- ansible/cfgov_refresh_setup.yml
- ansible/requirements.yml
- ansible/vars/db.yml
- bin/cfgov
- bin/cfgovd
-
-  Inital data loading steps removed from ansible provisioning (import events, initial data, contact data, etc).  Users will have to better maintain those scripts.
-  Uses fork of ansible mysql repository
-  Updates /bin/vagrant scripts
-
- @user
-
-
> Forked mysql repo.  Fixed /bin/cfgov scripts.

- cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Adds "Getting an Auto Loan" to the Consumer Tools section of the main menu.
- Pull branch
- Load a page
- Observe new link in menu
- @kurtw 
- @kave 
- **This needs to go live as close to 9:00 a.m. EDT tomorrow (Thursday, 6/9) as possible.**
> Add Auto Loans to sitewide navigation

- CHANGELOG.md
- cfgov/jinja2/v1/index.html
- Updated home page stats and date per request from Jen Lee
- open the homepage and check the stats toward the bottom
- @schaferjh 
- Should we update this to be editable in the CMS?
> Updated home page stats per request from Jen Lee

- cfgov/v1/migrations/0091_cfgovpage_has_unshared_changes.py
Whoops. Forgot to update the new migration to point to the latest script.
@rosskarchner
> Fix migration

- cfgov/v1/migrations/0057_auto_20160304_1651.py
-
- Removes a migration that doesn't appear to work when loading the database from an initial state.
-
- Create a blank mysql database.  Configure cf.gov settings to use your mysql database.  Run `python cfgov/manage.py migrate`.  Notice if migrations work/don't work with intended changes.
- @kave @rosskarchner @kurtw 
-
-
> Fixing broken migration #57.

- cfgov/v1/tests/test_wagtail_hooks.py
Apologies for the broken python tests. This change fixes the tests that I broke with #2195 
- Unnecessary tests
- Updates tests for new function logic
- Run `tox`
> Fix wagtail hooks tests from page statuses PR

- cfgov/jinja2/v1/_layouts/404.html
- cfgov/jinja2/v1/_layouts/500.html
Updating email addresses on the error pages.
- Updating email addresses on the error pages.
- Change `DEBUG` to `False` in `local.py` and visit http://localhost:8000/test/. Click on the `contact-us` link. 
- @virginiacc 
- @contolini
> Updating email addresses on the error pages

- test/browser_tests/page_objects/page_activity-log.js
- test/browser_tests/spec_suites/content/activity-log.js
Minor activity log test js cleanup
- Minor line length cleanup
- @virginiacc 
- @sebworks 
- @contolini
> Minor activity log test js cleanup

- CONTRIBUTING.md
- bower.json
- config/environment.js
- config/webpack-config.js
- create-mysql-db.sh
- drop-db.sh
- frontend.sh
- gulpfile.js
- initial-data.sh
- initial-test-data.sh
- package.json
- Adds/removes/cleans up comments.
- Removes trailing whitespace.
- Updates `bower.json` and `package.json` with current changelog version.
- @sebworks 
- @virginiacc
> Minor cleanup

- cfgov/legacy/templates/front/base_update.html
- Updates base_update.html code commenting and code block order to that used in base.html.
- Updates `{% static ` jinja prefix to django `{{ STATIC_PREFIX }}`
- Removes Google Analytics scripts as those should be superseded by Google Tag Manager.
- @higs4281 
- @sebworks 
> Reformats base_update.html for consistency w/ base.html

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- Updated documentation npm module to version `4.0.0-beta5` from `4.0.0-beta2`.
- @virginiacc 
- @sebworks 
- @contolini
> Updates documentation npm module to beta5

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- Update gulp-uglify to new major version 2.0.0 from 1.5.3.
- @sebworks 
- @contolini 
- @virginiacc
> Update gulp-uglify to 2.0.0

- CHANGELOG.md
- cfgov/cal/views.py
- cfgov/jinja2/v1/_includes/molecules/social-media.html
- cfgov/jinja2/v1/_includes/organisms/expandable.html
- cfgov/jinja2/v1/about-us/the-bureau/leadership-calendar/print/index.html
- cfgov/unprocessed/css/molecules/social-media.less
- cfgov/unprocessed/css/organisms/expandable.less
This will move recent hostfixes into master
https://github.com/cfpb/cfgov-refresh/pull/2339
https://github.com/cfpb/cfgov-refresh/pull/2335
https://github.com/cfpb/cfgov-refresh/pull/2337
https://github.com/cfpb/cfgov-refresh/pull/2338
> 3.7.2 backports

- npm-shrinkwrap.json
Updating `npm-shrinkwrap.json` file to fix build issue regarding `glob-all`.
- Updating `npm-shrinkwrap.json`  file to fix build issue
- ` run ./frontend.sh production`. It should finish without errors.
- @willbarton 
> Updating shrinkwrap file to fix build issue

- .bowerrc
Removing the last remnants of Bower
- Removing `.bowerrc` file
> Removing .bowerrc file

- CHANGELOG.md
- cfgov/templates/find_a_housing_counselor.html
Once merged, we'll release 3.8.1
> Bringing Google Optimize changes (#2370) into the 3.8 branch

- npm-shrinkwrap.json
For some reason shrinkwrap was outdated. I don't get why, but it was :(
- Re-generated shrinkwrap because ./frontend.sh was failing.
- `./frontend.sh` should pass.
- @contolini 
- @sebworks 
- @virginiacc
> Updates shrink-wrap

- CHANGELOG.md
- cfgov/jinja2/v1/about-us/careers/students-and-graduates/index.html
Brandeis Honors Attorney Program application window has closed; DFA window is about to open.
It was requested to publish these changes by COB Wednesday.
- Updated copy on Students and Recent Graduates Careers apge
1. Pull branch
2. Run server
3. Visit <http://localhost:8000/about-us/careers/students-and-graduates/>
> Hotfix: Update Students and Recent Graduates Careers page

- .travis.yml
- README.md
Intended to see if parallel coveralls setting is effective
- env variable for parallel coveralls
> test parallel coveralls setup

- CHANGELOG.md
- cfgov/jinja2/v1/about-us/careers/students-and-graduates/index.html
- package.json
Changelog updates, and copy changes from @Scotchester
> 3.8.2 backports

- docs/installation.md
- docs/usage.md
Documentation spellcheck: Installation.md. 
Couple of small spelling amendments:
Github -> GitHub
Reinstall -> Re-install. 
No functional changes to code.
> Spellcheck: Installation.md

- docs/notes-on-atomic-design.md
Spellcheck for documentation file: docs/notes-on-atomic-design.md
Amended two spelling mistakes: 
partialy -> partially
playgroud -> playground
No functional changes to code.
> Spellcheck: notes-on-atomic-design.md

- docs/notes-on-js.md
Spell-check: docs/notes-on-js.md
- Amended couple of spelling issues:
Javascript -> JavaScript
Github -> GitHub
No functional changes to code.
> Spellcheck: notes-on-js.md

- CHANGELOG.md
- cfgov/scripts/fix_links_in_tableblocks.py
Applies changes in #2458 (Hotfix: fix links in TableBlocks) to `3.10` branch.
See discussion in #2458 for details.
- @rosskarchner @willbarton @richaagarwal
> 3.10 Hotfix: Fix links in TableBlocks

- cfgov/templates/find_a_housing_counselor.html
Will merge when Travis passes.
> Fix a bad static tag on the housing counselor tool

- requirements/optional-private.txt
This addresses internal issue 376
> comparisontool 1.2.7

- CHANGELOG.md
This brings in changelog updates from 3.11 and some 3.10 hotfixes that never made it this far.
> Add changelog updates from 3.10 and 3.11

- docs/release-cadence.md
Spellcheck for file docs/release-cadence.md.
Typo fix in documentation.
proceedures -> procedures.
No functional changes to code.
> Spellcheck: release-cadence.md

- cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
This PR restores the Prepaid menu item in master.
Restore Prepaid links in mega-menu
> Restore Prepaid menu update

- CHANGELOG.md
- requirements/optional-private.txt
Upgrade to picard version 1.5.
The latest picard decouples the requested task from the specific mechanism (shell) being executed.  Once tested to work correctly with the existing shell mechanisms, we plan to activate Jenkins as the mechanism for the near future.
-
-
- Picard updated to version 1.5, which should have no functional change, but refactors how the shell scripts run.
- Unit tests were created to validate picard functionality, which brings picard coverage from 0% to 86%.
- @willbarton 
-
-
> Upgrade picard to version 1.5

- requirements/optional-public.txt
It's a cherry-pick of 1abdf448af637625dcdb9c7f8895be30e4608bb8
> Port djangorestframework app updates back to master

- requirements/optional-private.txt
The current `requirements/optional-private.txt` uses an invalid egg name for the (private) agreement_database repo. It tries to install using `#egg=agreements` but the setup.py for that repo specifies `name='agreement_database'`.
Currently if you do `pip install -r requirements/optional-private.txt`, you get a warning like this:
> egg_info for package agreements produced metadata for project name agreement-database. Fix your #egg=agreements fragments.
The package does get installed, but under `agreement-database`, not `agreements`:
```sh
~/Projects/cfgov-refresh master* $ pip freeze | grep agree
agreement-database==1.0
```
This prevents you from uninstalling using the same requirements file:
```sh
~/Projects/cfgov-refresh master* $ pip uninstall -r requirements/optional-private.txt …
```
> Fix agreement_database install egg to be consistent with repo setup.py

- CHANGELOG.md
move all of the previously "unreleased" changes to 40
> 4.0 changelog update

- CHANGELOG.md
- requirements/optional-private.txt
Update comparisontool to latest version which includes Google Analytics removal
- bump comparisontool version 
> Bump comparisontool version

- CHANGELOG.md
- cfgov/cfgov/settings/base.py
- cfgov/cfgov/settings/test.py
- requirements/base.txt
Bringing these changes to master: #2512
> Disable htmlmin

- requirements/optional-private.txt
> bump knowledgebase to 2.1.4

- CHANGELOG.md
- requirements/optional-private.txt
Upgrade Picard to version 1.5.2
-
-
- The task return value in the /tasks/ page will now display text instead of `None`
- A test was created to validate the string value is saved to the database
- @willbarton 
-
-
> Update picard to version 1.5.2

- cfgov/v1/tests/test_wagtail_hooks.py
- cfgov/v1/wagtail_hooks.py
4.1 branch version of Akamai cache logic change in #2529.
- @richaagarwal @rosskarchner @willbarton
> Simplify publish logic to always flush Akamai cache (4.1)

- cfgov/v1/forms.py
- cfgov/v1/models/browse_filterable_page.py
- cfgov/v1/models/sublanding_filterable_page.py
- cfgov/v1/models/sublanding_page.py
- cfgov/v1/tests/test_filterable_list.py
- cfgov/v1/tests/test_filterable_list_form.py
- cfgov/v1/util/filterable_list.py
Getting the changes from #2536 into 4.1
> Exclude reports from showing up on the Newsroom Landing Page

- cfgov/v1/forms.py
- cfgov/v1/models/base.py
- cfgov/v1/models/browse_filterable_page.py
- cfgov/v1/models/sublanding_filterable_page.py
- cfgov/v1/models/sublanding_page.py
- cfgov/v1/tests/test_filterable_list.py
- cfgov/v1/tests/test_filterable_list_form.py
- cfgov/v1/util/filterable_list.py
See https://github.com/cfpb/cfgov-refresh/pull/2536
> Hotfix - Newsroom update 4.1

- cfgov/v1/db_router.py
Hotfix for release this morning. Makes data + research conference registration form share a db with other cfgov apps + content 
@chosak @rosskarchner
> add data_research app to shared db list

- requirements/optional-public.txt
Here's what's new: https://github.com/cfpb/complaint/releases/tag/v1.2.8
> upgrade complaint package to 1.2.8

- CHANGELOG.md
- requirements/optional-private.txt
Bumping version of College Comparison Tool 
- Bumping version of College Comparison Tool 
> Bumping version of College Comparison Tool 

- CHANGELOG.md
- cfgov/v1/signals.py
See https://github.com/cfpb/cfgov-refresh/pull/2564
> Hotfix - Flush Akamai when unpublishing or unsharing a page

- CHANGELOG.md
- npm-shrinkwrap.json
s/http/https/ in `npm-shrinkwrap.json`.
@sebworks
> Upgrade npm shrinkwrap endpoints to HTTPS

- cfgov/jinja2/v1/_includes/organisms/mega-menu-for-ia-testing.html
Small updates to mega menu for IA user testing on 12/14 & 12/15
- `Consumer Tools > Auto loans` link goes to `/consumer-tools/auto-loans-topic/`
- `Consumer Tools > Payday loans` link goes to `/consumer-tools/placeholder/`
- `Consumer Tools > Shopping for an auto loan` link goes to `http://www.consumerfinance.gov/consumer-tools/auto-loans/`
- `Educational Resources` section becomes `Resources for Practitioners`
- Check out branch
- Run gulp
- Log in to the wagtail admin and add an IA_USER_TESTING_MENU feature flag
- Verify the link changes listed above
> Updates to IA user testing mega menu

- requirements/optional-public.txt
- Bump the version of regulations-site to 2.1.4
> Bump regulations-site version

- cfgov/unprocessed/js/modules/ExternalSite.js
- cfgov/unprocessed/js/modules/YoutubePlayer.js
- cfgov/unprocessed/js/modules/util/scroll.js
- cfgov/unprocessed/js/organisms/BureauStructure.js
- gulp/tasks/docs.js
- test/browser_tests/spec_suites/content/bureau-structure.js
- test/browser_tests/spec_suites/content/careers-application-process.js
- test/browser_tests/spec_suites/content/careers-current-openings.js
- test/browser_tests/spec_suites/content/careers-working-at-cfpb.js
- test/browser_tests/spec_suites/content/careers.js
- test/browser_tests/spec_suites/content/dbwu-past-awards.js
- test/browser_tests/spec_suites/content/dbwu-small-businesses.js
- test/browser_tests/spec_suites/content/dbwu-upcoming-procurement-needs.js
- test/browser_tests/spec_suites/content/doing-business-with-us.js
- test/browser_tests/spec_suites/integration/footer.js
- test/unit_tests/modules/util/data-set-spec.js
- Fixes minor JS linter errors/warnings
- `gulp build` should pass.
> Fix minor linter errors/warnings

- requirements/optional-private.txt
Based on the last 7 days, the fixes in this update should reduce our error rate by about 1/3rd (as measured by New Relic). It improves how we handle erroneous categories and audiences ("no results found" instead of 500 errors), and removes dependencies on session ID's and csrf tokens.
- updates knowledgebase (AskCFPB) to 2.2.0
> bump knowledgebase to 2.2.0

- CHANGELOG.md
This PR contains just the changelog updates for 4.5.1.
> 4.5.1 Changelog update, for real this time

- cfgov/v1/migrations/0045_update_story_categories.py
- cfgov/v1/util/ref.py
Since my initial implementation, the name of one category changed. Also, new future categories needed to be added.
- New story categories
- Renamed one category
- Pull the branch and verify the contents of a category dropdown.
> Update story categories

- CHANGELOG.md
Bring 4.5.2 into the master CHANGELOG.
- 4.5.2 to the CHANGELOG
> 4.5.2 changelog

- requirements/optional-public.txt
Bump college-costs version to 2.3.0 for first student usage
> bump college-costs to release 2.3.0 for hotfix

- CHANGELOG.md
> backport changelog from 4.5.3 hotfix

- CHANGELOG.md
As it says, updates the CHANGELOG for the 4.6.0 release.
> Update CHANGELOG for 4.6.0

- cfgov/legacy/templates/front/base_update.html
Typo in css reference
- Missing closing brace
> add missing brace

- requirements/optional-public.txt
> bump college-costs version to 2.3.1 for hotfix

- requirements/optional-public.txt
> bump PFC to 2.3.2

- CHANGELOG.md
This PR updates the changeling in master for the 4.6.1 release.
> Update CHANGELOG.md for 4.6.1

- CHANGELOG.md
This PR brings release notes for [version 4.6.2](https://github.com/cfpb/cfgov-refresh/releases/tag/4.6.2) into the CHANGELOG.
- Added release notes for 4.6.2.
> 4.6.2 changelog

- CHANGELOG.md
- cfgov/v1/models/snippets.py
- cfgov/v1/tests/models/test_snippets.py
Snippets need str method with python 2 handling
> add decorator to help model __str__ method in python 2

- CHANGELOG.md
> Update CHANGELOG.md for 4.6.4

- .travis.yml
Use Travis's containerized builds.
- `sudo: false` in .travis.yml.
> Use travis's containerized build

- .travis.yml
- npm-shrinkwrap.json
- package.json
> Move es5-shim into deps from dev deps

- npm-shrinkwrap.json
- package.json
> Bump chart builder dep

- requirements/optional-public.txt
> Bump regulations-site to 2.1.7

- cfgov/jinja2/v1/_includes/molecules/info-unit.html
Fix for null value be passed to the info unit
> Fix for null value being passed to the info unit molecule

- cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
Updating filters to use sentence case
> Updating filters to use sentence case

- requirements/optional-public.txt
> Update regulations-site to 2.1.8

- cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
- cfgov/unprocessed/css/organisms/filterable-list-controls.less
- cfgov/unprocessed/js/molecules/Multiselect.js
- cfgov/unprocessed/js/organisms/Expandable.js
- cfgov/unprocessed/js/organisms/FilterableListControls.js
Fix for multi-select issues on Filterable list control 
- Modified the files to fix display issues with the multi-select.
- This is feature flagged. Add the `'MULTI-SELECT-TEST'` flag to test.
- This PR is just giving interested parties the ability to test on build.  I don't think this will be the final solution.
> Fix for multi-select issues on Filterable list control

- cfgov/unprocessed/js/modules/UStreamPlayer.js
Removing temporary code for archived live Winter event
> Removing temporary code for archived live Winter event

- cfgov/unprocessed/css/organisms/full-width-text-group.less
Adjustment for image inset margin
> Adjustment for image inset margin

- cfgov/cfgov/settings/base.py
- cfgov/cfgov/urls.py
- tox.ini
> Uppercase DEPLOY_ENVIRONMENT var to match ansible

- requirements/optional-private.txt
The agreements database 2.2.7 adds a download link for the Q4 2016 agreements.
- Bumps agreements to 2.2.7
> Update agreements database to 2.2.7

- cfgov/jinja2/v1/_includes/organisms/chart.html
CCT chart manual update until this step is automated.
> Updates chart footer for March

- npm-shrinkwrap.json
- package.json
- Bumped `cfpb-chart-builder` to v1.2.0.
> Update cfpb-chart-builder dependency

- requirements/optional-public.txt
This PR updates the complaint app to [1.3.1](https://github.com/cfpb/complaint/releases/tag/1.3.1).
- Updated the complaint app version to 1.3.1
> Update complaint app to 1.3.1

- requirements/optional-public.txt
Also adds new Feedback model methods
> Bump college-costs version to 2.3.3 for bug fixes

- cfgov/cfgov/settings/production.py
- Log to a location specified in an environment variable.
> Change log file location to an environment variable

- requirements/optional-private.txt
This PR just bumps the knowledgebase version to 2.3.0.
- Update knowledgebase to 2.3.0
> Update knowledgebase to 2.3.0

- requirements/optional-public.txt
This PR updates the complaintdatabase app to 1.3.2.
- Update complaintdatabase to 1.3.2
> Update complaintdatabase to 1.3.2

- requirements/optional-private.txt
This PR updates the knowledgebase app to 2.3.1.
- Update knowledgebase to 2.3.1
> Update knowledgebase to 2.3.1

- requirements/optional-public.txt
Minor update to model structure to help troubleshooting.
> bump college-costs to 2.3.4 for model changes

- cfgov/jinja2/v1/_includes/organisms/chart.html
New data release for CCT, updating footers to match.
> CCT footer date update

- cfgov/unprocessed/css/enhancements/buttons.less
The full width button for small screens is now in CFv4 and can be deleted as this project is updated.
- Added CFv4 note to the `enhancements/buttons.less` file
> Certify CF changes for enhancements/buttons

- cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Your Money, Your Goals is moving to Wagtail!
New URL. New Content. Same great money goals, right here on consumerfinance.gov :tada:
- Added `educational-resources` sub-dir to YMYG url in mega menu
- Click.That.Link.
> Update the YMYG URL in the mega menu

- cfgov/unprocessed/css/organisms/featured-content-module.less
Fix for missing semicolon
- Run `gulp build`
> Fix for missing semicolon

- requirements/optional-public.txt
Bumping college costs to 2.3.5
> Bumping college costs to 2.3.5

- cfgov/scripts/http_smoke_test.py
Our lists had gotten a little out of date with new canonical URLs and a little out of sync with each other.
- Default base now uses HTTPS
- Updated YMYG and Library URLs to use their new `/educational-resources` parent
1. `cd cfgov/scripts`
2. `python http_smoke_tests.py --full -v`
- If you run this against beta.consumerfinance.gov before the next database refresh from prod (which happens nightly, I think?), it will fail because the new Library Resources page isn't in the Beta DB yet. Should we do anything to protect the smoke tests from failing in cases like that?
> Tidy up smoke tests

- .github/PULL_REQUEST_TEMPLATE.md
Minor pull request template update.
> Point pull request template to correct repo

- cfgov/cfgov/settings/local.py
That should not have been removed in #2908. Work on actual switching to Innodb is happening in #2963
> Bug fix: restore erroneously removed MyISAM default

- requirements/optional-public.txt
Bumping college costs to version 2.6
> Bumping college costs to version 2.6

- requirements/base.txt
Reverts cfpb/cfgov-refresh#2980
> Revert "Go back to Wagtail 1.10"

- cfgov/v1/atomic_elements/organisms.py
- cfgov/v1/migrations/0068_remove_cfgovrendition_filter.py
- cfgov/v1/models/images.py
- cfgov/v1/tests/models/test_images.py
- cfgov/v1/tests/test_s3utils.py
- requirements/base.txt
This reverts commit d36ace7aac9ebc4a380a9859bece833a34b702ec. (Re-submitting the Upgrade Wagtail PR basically)
> Revert "Revert "Upgrade Wagtail to v1.10.1""

- .travis.yml
Caching node modules on Travis
- Modified `travis.yml` to do the following:
- Cache the local node_modules directory, allowing us to use the checksum logic in `front-end.sh` to avoid installing npm modules, if unnecessary.
- Cache the global node_modules directory to prevent unnecessarily installing npm and gulp.
- Switch the beta chrome config to match the documentation on Travis
- Delete the cache for this PR using the Travis gui
- Restart the build
- Verify that npm install runs for the front-end and acceptance builds.
- Verify that caches are created for node_modules and pip ( should see green console messages, alien like)
- Once the build finishes, restart the build
- Verify that npm install doesn't run and you see a 'Dependencies are up to date.' message in the console ( you may …
> Caching node modules on Travis

- package.json
- Updates wcag to latest version.
1. `npm install wcag && gulp test:a11y`
> Updates to latest wcag

- docs/testing.md
- gulp/tasks/test.js
- test/browser_tests/conf.js
- Fixes code block typo in testing.md that was not closing the code block.
- Minor code comment clarification and indenting in test.js
- Updates variable declarations in test.js to ES6 format.
> Fixes typo in docs + code cleanup

- cfgov/unprocessed/css/organisms/chart.less
- Removes empty CSS classes from chart.less.
> Removes empty CSS

- cfgov/ask_cfpb/models/pages.py
- cfgov/jinja2/v1/_layouts/spanish-ask-base.html
- cfgov/jinja2/v1/ask-cfpb/answer-page-spanish-printable.html
- cfgov/jinja2/v1/ask-cfpb/answer-page.html
- cfgov/jinja2/v1/ask-cfpb/answer-search-results.html
- cfgov/jinja2/v1/ask-cfpb/audience-page.html
- cfgov/jinja2/v1/ask-cfpb/category-page.html
- cfgov/unprocessed/css/pages/ask.less
Fixes based on QA
- Landing page
- Order audiences by name
- Answer page
- Make sure subcategories only appear once in `Related Subjects` section
- Search results page
- Fix answer preview spacing
- Fix bottom padding on search bar on mobile
- Move `About us` banner to top
- All English pages
- Fix spacing around `Legal disclaimer`
- Spanish pages
- Fix `obtener respuestas` link in footer
Before:
After:
> Ask CFPB -- QA fixes

- docs/development-tips.md
- Updates shrinkwrapping documentation to current workflow process.
> Updates shrink-wrap documentation

- cfgov/unprocessed/css/misc.less
Replaces https://github.com/cfpb/cfgov-refresh/pull/2761#issuecomment-298882841
> 3dtransforms

- cfgov/unprocessed/css/meta.less
- cfgov/unprocessed/css/organisms/sidebar-content.less
Updates to tag and sidebar spacing based on Ask CFPB QA
- Match left/right padding on sidebar to that of surrounding content when stacked at small screen sizes 
- Update `tags` spacing on xs screen sizes
1. Check out branch and run `gulp styles`
2. Navigate to [enforcement page](http://localhost:8000/policy-compliance/enforcement/) and check that sidebar spacing matches surrounding content when stacked at small screen sizes (600-900px)
3. Navigate to [a blog page](http://localhost:8000/about-us/blog/snapshot-complaints-made-older-consumers/) and check spacing of `Topics` at mobile screen sizes
> Update spacing of tags and stacked sidebar content

- cfgov/ask_cfpb/models/django.py
- cfgov/jinja2/v1/ask-cfpb/category-page-spanish.html
- cfgov/jinja2/v1/ask-cfpb/category-page.html
- cfgov/unprocessed/css/pages/ask.less
Fix subcategory nav and search bar padding on mobile 
- Fix search bar bottom padding on mobile
- Fix subcategory nav padding on mobile
- Only display Spanish category tag links if there's more than one associated answer
- Show Spanish tag panel in admin
2. Run `gulp styles`
3. Navigate to [category page](http://localhost:8000/ask-cfpb/category-auto-loans/) and verify subcategory nav and search bar padding on mobile
> Ask CFPB: spacing fixes and a few tag updates

- cfgov/ask_cfpb/models/pages.py
- cfgov/jinja2/v1/ask-cfpb/answer-page-spanish.html
- cfgov/jinja2/v1/ask-cfpb/answer-page.html
- cfgov/unprocessed/js/modules/Analytics.js
- cfgov/unprocessed/js/routes/ask-cfpb/single.js
- cfgov/unprocessed/js/routes/es/obtener-respuestas/single.js
Send Analytics Virtual Pageview events on Ask answer pages
- Send analytics event with category, title, and action (configured to match old url structure) on answer pages  
1. Check out branch and run `gulp scripts`
2. Navigate to [English](http://localhost:8000/ask-cfpb/what-information-do-i-have-to-provide-a-lender-in-order-to-receive-a-loan-estimate-en-1987/) and [Spanish](http://localhost:8000/es/obtener-respuestas/me-gustaria-poder-tener-la-ayuda-de-mis-amigos-o-familiares-con-el-pago-de-mis-facturas-y-actividades-bancarias-cuales-son-mis-opciones-es-1145/) answer pages and inspect the `dataLayer` object in console to verify that pageview event has been added
> Ask CFPB: Send Virtual Pageview events on answer pages

- cfgov/ask_cfpb/models/django.py
Uses the tags_es property for collecting tags.
> simplify top-10 tag collection

- cfgov/jinja2/v1/job-description-page/index.html
This PR makes two changes to the job description template.
- Fixes a case error, "Applying" to "applying"
- Adds a link to the application checklist
- Adds link to application checklist
- Fixes a case error ("Applying" to "applying")
1. Get this branch and run `cfgov-refresh`
2. Add an active job opening
- Go to About Us >> Careers >> Current Openings.
- Choose a job opening page, open it up, and change its expiry date in Configuration to a date in the future
- Choose the job opening from `[localhost]/about-us/careers/current-openings` and check it out!
- The other links present were styled with the `jump-link` class, so I did the same here
- The PDF link has already been uploaded and is live
> Add Apply Checklist PDF to Job Descriptions pages
