cfpb/consumerfinance.gov

cfgov/ask_cfpb/models/pages.py, cfgov/scripts/http_smoke_test.py
Temporarily remove tag links while we resolve issue with accents
=> Ask CFPB: Temporarily remove tag links on Spanish category pages

cfgov/ask_cfpb/migrations/0006_update_help_text.py, cfgov/ask_cfpb/models/django.py
Improves explainer text across Ask CFPB models.
Note: This creates a migration.
cc @sonnakim
=> Ask CFPB: Update admin helper text

requirements/optional-private.txt
This PR updates the credit card agreement database to 2.2.8 for the Q1 2017 update.
- Bump credit card agreements database to 2.2.8
=> Update agreements database to 2.2.8

requirements/optional-private.txt
This pull request updates __Paying for College__ to version 1.3.1, which will update interest rates and limits in the Comparison Tool, and in the text of the 'About this tool' page. 
- `requirements/optional-private.txt` updated
1. Kick out the jams with this rad branch
2. Clone the latest super-dank version `django-college-costs-comparison` from GHE
3. `pip install -e /path/to/django-college-costs-comparison/`
4. Load up the Comparison Tool and check out the tight changes to federal interest rates!
=> Paying for College - Update to version 1.3.1

cfgov/ask_cfpb/models/django.py, cfgov/ask_cfpb/tests/models/test_pages.py
We need to make sure a new Answer object has an ID before it generates a new
answer page, because the page will need that ID for slug purposes.
This PR also adds slug shortening to keep slugs
in the 100-character range, at the request of our analytics team.
1. In Wagtail, go to **Ask CFPB > Answers** and create a new Answer object (button at top right).
2. Check **Send to English page for review**
3. Enter some content in the English **Question** and **Answer** fields.
4. Go to the bottom and save
5. Enter the new answer's ID in the search box under the Wagtail logo. It should find your new page.
6. Edit the page and click the Configuration tab.
7. The slug should end with your new answer's ID.
- Repeat steps 1 and 2 from the first test.
- Enter this string (it's over 100 characters) in …
=> Ask CFPB: Fix slug generation for new Answer pages

cfgov/jinja2/v1/govdelivery-subscribe/success/index.html, cfgov/jinja2/v1/regulation-comment/success/index.html
Fixes typo of "successfuly" on two form submission pages.
- Fixes two template typos.
=> Fix typo: successfuly -> successfully

requirements/optional-private.txt
Updating django-college-cost-comparison dependency to 1.3.2
=> Updating django-college-cost-comparison dependency to 1.3.2

cfgov/jinja2/v1/_includes/organisms/mega-menu-for-ia-testing.html
- Fix typos of extra `m-` on list item classes.
=> Fix erroneous class name

cfgov/jinja2/v1/_includes/blocks/feedback.html
Adds `o-feedback` wrapper div to feedback form for `feedback-form.js` 
- `o-feedback` wrapper div
1. Check out branch & run gulp
2. Verify that [feedback form](https://www.consumerfinance.gov/ask-cfpb/what-effect-will-shopping-for-an-auto-loan-have-on-my-credit-en-763/) submits without page reload
=> Add wrapper div to feedback form for feedback js

cfgov/jinja2/v1/_includes/molecules/hero.html
Fix for hero image
- Modified `cfgov/jinja2/v1/_includes/molecules/hero.html` to remove `image-set` properties.
1. Add hero to page
2. Add background image to page.
3. Visit page using Chrome.
4. Verify image has the proper width.
=> Fix for hero image

docs/development-tips.md, docs/front-end-build.md
Updating documentation to remove shrinkwrapping references
- Modified  documentation files to remove references to shrinkwrapping.
-
-
=> Updating documentation to remove shrinkwrapping references

cfgov/jinja2/v1/index.html
This updates the complaint and relief numbers on the home page.
- 11.9 billion 
- 1.2 million+ complaints
1.
-
-
=> Copy edits to reflect updated complaint and relief numbers on the homepage

package-lock.json, package.json
Upgrades to latest chart-builder at v2.0.0 with CSS media queries to make responsive charts. Also includes a bug fix for the projected date labels on charts, which was off by one month.
See [release notes](https://github.com/cfpb/cfpb-chart-builder/releases/tag/v2.0.0) for more info!
1. check out branch, run `./setup.sh` to make sure you get dependencies + latest database
1. `./runserver.sh`
1. look at pretty responsive charts at the following URLs:
- http://localhost:8000/data-research/consumer-credit-trends/auto-loans/borrower-risk-profiles/
- http://localhost:8000/data-research/consumer-credit-trends/auto-loans/origination-activity/
- http://localhost:8000/data-research/consumer-credit-trends/auto-loans/lending-neighborhood-income-level/
- …
=> Responsive Consumer Credit Trends charts with CSS: upgrade to cfpb-chart-builder version 2.0.1

frontend.sh
Removing exit in frontend build process until Jenkins until box gets updated
=> Removing exit in frontend build process until Jenkins until box gets updated

requirements/optional-public.txt
This will change the version of CCDB5-UI to its latest version
- Updated CCDB5-UI version
=> Up the version of CCDB5-ui

requirements/optional-public.txt
- Updates the complaint database package to 1.4.0
=> bump complaints to 1.4.0

test/browser_tests/cucumber/features/suites/default/global-search.feature, test/browser_tests/cucumber/features/suites/default/multi-select.feature, test/browser_tests/cucumber/features/suites/default/pagination.feature
Temp fix for broken tests on Travis
=> Temp fix for broken tests on Travis

cfgov/v1/tests/models/test_base.py
This commit rolls back a change in #3220 ([bd44933e1c61f52681b0affa9af29cd979b515590](https://github.com/cfpb/cfgov-refresh/pull/3220/commits/bd44933e1c61f52681b0affa9af29cd979b51559)) that tried to create a temporary model for use in a unit test. This may be causing some problems with running the unit tests in isolation.
This change rewrites those tests to unfortunately be less comprehensive but just use existing models to test the functionality.
- Rewritten unit test from #3220.
See #3220.
=> Roll back model creation in unit test

cfgov/jinja2/v1/_includes/macros/category-slug.html
- Adds code comment for missing `index` parameter.
- `sheerpage` parameter in category slug macro did not appear to be used.
1. Search codebase for `category-slug.html` and check that `sheerpage` parameter is unused.
=> Removes unused parameter, adds comments

requirements/optional-public.txt
Up the version of CCDB5-API
- Changed API to 0.5.0
=> Update ccdb5-api to the latest version

package-lock.json, package.json
- Updates webpack and webpack-stream to latest. 
=> Update webpack deps

requirements/optional-public.txt
In this pull request, we increment the version for the first pre-release of sprint 6 to include the latest changes.
- None
- None
- Updated CCDB-UI optional requirement version to 0.6.0 from 0.5.173
1. N/A
- 
- None
=> Version Bump CCDB to include latest UI templates

cfgov/templates/wagtailadmin/table_input.html
This corrects a misspelling of "numerical"
- Correctly spell Numerical
=> Fix typo: "Numberical"

requirements/optional-public.txt
Updates college-costs version to 2.3.8
- Updates college-costs version to 2.3.8
1. Version 2.3.8 of `college-costs` can be tested using instructions in [this PR](https://github.com/cfpb/college-costs/pull/308).
=> Updates college-costs version to 2.3.8

cfgov/data_research/urls.py
Just a tweak to the URL fields.
=> Make the api endpoint pattern consistent: `/days_late/geo/`

requirements/optional-public.txt
- None
- None
- Version bump
1. N/A
-
-
=> Version Bump for CCDB Search

cfgov/alerts/post_sqs_messages.py
- Fix `matching_issue` function to return value
- delete messages from queue after they're processed
- Add appropriate labels to github issue
=> SQS queue script - fixes 

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Update two Consumer Tools menu links to go to newly created portal pages
- Link locations
=> Mega menu: update links to new Consumer Tools portal pages

cfgov/data_research/models.py, cfgov/jinja2/v1/_includes/organisms/mortgage-chart.html, cfgov/jinja2/v1/_includes/organisms/mortgage-map.html, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/actions.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/chart.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/map.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/index.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/stores/chart.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/stores/map.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/stores/store.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/utils.js, cfgov/unprocessed/js/routes/on-demand/mortgage-performance-trends.js, config/webpack-config.js, package-lock.json, package.json, test/unit_tests/organisms/MortgagePerformanceTrends/actions-spec.js, test/unit_tests/organisms/MortgagePerformanceTrends/stores/chart-spec.js, test/unit_tests/organisms/MortgagePerformanceTrends/stores/map-spec.js
This is a first pass at migrating the Mortgage Performance JS into cfgov-refresh in preparation for upcoming user testing. The "apps" are a series of interdependent dropdowns, radio buttons and checkboxes that change the values of a line chart and a map of the U.S. At this stage it's just a copy-and-paste from the static site repo we've been using for rapid prototyping. Both the JS and HTML will be cleaned up in future PRs. The goal here is just to establish where the code will live.
The JS will only be included on pages that have [Mortgage Performance blocks](https://github.com/cfpb/cfgov-refresh/pull/3260) (which will be a couple pages in the `data-research` section of cf.gov).
- Mortgage Performance JS into a new `MortgagePerformanceTrends/` organisms directory.
-
- @higs4281 I changed …
=> First pass at Mortgage Performance Trends apps

cfgov/jinja2/v1/_includes/organisms/mortgage-map.html
The H2 can be matched to the days_late value on render.
- template var in the H2
=> Fix the H2 element of map block to pick up days-late

cfgov/alerts/send_new_relic_messages_to_sqs.py
This fixes the New Relic duration threshold check and adds an option for verbose logging.
- `--verbose` option for `DEBUG` logging
- Fixed duration threshold checking
=> Add verbose logging to New Relic polling, fix violation duration threshold

cfgov/legacy/templates/service-members/index.html
Fixing issue with /service-members/ asset reference
- Modified template to fix issue with /service-members/ asset reference.
1. Visit ` /service-members/` and ensure all the assets work.
=> Fixing issue with /service-members/ asset reference

cfgov/jinja2/v1/_includes/organisms/mortgage-map.html, cfgov/unprocessed/css/organisms/mortgage-performance-trends.less, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/actions.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/map.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/utils.js, test/unit_tests/organisms/MortgagePerformanceTrends/actions-spec.js
Handful of improvements to the Mortgage Performance Map.
- MSAs are filtered by state (similar to counties).
- Location name is dynamically added to map title.
- Fixes bug where counties weren't being highlighted.
- Misc. visual clean up.
-
-
=> Mortgage Performance map updates

.babelrc
- Removes unneeded `.babelrc` file.
=> Removes babelrc file

requirements/optional-public.txt
- None
- None
- Version bump for API / UI
1. N/A
N/A
- None
- None
=> Updated CCDB5 optional installs

cfgov/cfgov/settings/production.py
Fixes error introduced in #3322
=> Add necessary comma to production.py

cfgov/wellbeing/jinja2/wellbeing/about.html, cfgov/wellbeing/jinja2/wellbeing/error.html, cfgov/wellbeing/jinja2/wellbeing/results.html
While reviewing the content a few errors were noted in issue 258 issuecomment-130753. This PR fixes most of them.
- Updated content and styles to fix errors.
1. Run the branch and go through the corresponding list in GHE
=> Fix errors to FWB found in review

cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/results/index.js, cfgov/wellbeing/jinja2/wellbeing/results.html
Short description explaining the high-level reason for the pull request: I'm dumb.
- `sendEvent` function to FWB results JS file
- Removes "radio" from comparison button event action names
1. `gulp build` and watch the console while toggling the comparison buttons. No error should appear.
=> wellbeing: Fix analytics events on results page

requirements/optional-public.txt
Updates required versions of college-costs and retirement optional apps.
=> Bumps required versions

.github/PULL_REQUEST_TEMPLATE.md
We should write tests when functionality has changed in any way (which could be due to changed code, deleted code, or added code).  In the case of changed or deleted, codecov wouldn't fail the PR, but it's still valuable to add tests in those situations.
This PR simply modifies the checklist we display when creating a PR to:
=> Tests should be for changed functionality, not just new functionality

requirements/optional-private.txt, requirements/optional-public.txt
Updates version for retirement and college cost satellite apps.
=> Version bumps for satellite apps

cfgov/jinja2/v1/_includes/organisms/mortgage-chart.html, cfgov/jinja2/v1/_includes/organisms/mortgage-map.html
Adding start-date and end-date as data attributes on page render will
save API calls.
=> Mortgage performance: Add data attributes for start/end dates

test/unit_tests/organisms/MortgagePerformanceTrends/utils-spec.js
Fixing issue with linter by adding semi-colon
-
-
- Modified `test/unit_tests/organisms/MortgagePerformanceTrends/utils-spec.js` to fix linter issue with missing semi-colon.
1.
-
-
=> Fixing issue with linter by adding semi-colon

requirements/optional-public.txt
- None
- None
- CCDB Version bumped to 0.7.19
1. N/A
- N/A
- N/A
=> Bumping CCDB-UI version.

cfgov/unprocessed/js/apps/financial-well-being/fwb-questions.js, cfgov/unprocessed/js/apps/financial-well-being/fwb-results.js, cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/index.js, cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/results/index.js, cfgov/wellbeing/jinja2/wellbeing/home.html, cfgov/wellbeing/jinja2/wellbeing/results.html, test/unit_tests/apps/financial-well-being/fwb-questions.js, test/unit_tests/apps/financial-well-being/fwb-results.js
The script had trouble keeping the state of the form correctly saved
when returning to the page after submission. To better track each
individual question the script sets up an object and tracks the radio states in
relation to their parent fieldset. In addition I made some optimizations
and broke code up into smaller testable bites where possible.
- Added onload checker to fix issue with IE not immediately recognizing inputs as checked when returning to the page after submission
- Modularized the functionality as much as possible to make testing easier
- Grouped radios by parent fieldset to simplify completion checks
1. Open `10.0.2.2:8000/consumer-tools/financial-well-being/` in IE 9
2. Verify the submit button is disabled
3. Randomly select a radio from each fieldset group (I just use …
=> Optimize FWB JS and fix an IE error

cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/utils.js, test/unit_tests/organisms/MortgagePerformanceTrends/utils-spec.js
Fixes https://GHE/CFGOV/mortgage-performance/issues/200
- Mortgage Performance date logic.
1. `gulp test:unit`
=> Update Mortgage Performance date logic

cfgov/unprocessed/js/config/error-messages-config.js, cfgov/unprocessed/js/modules/util/ajax-request.js, cfgov/unprocessed/js/modules/util/expanded-state.js, cfgov/unprocessed/js/modules/util/scroll.js, cfgov/unprocessed/js/modules/util/strings.js, cfgov/unprocessed/js/molecules/Autocomplete.js, cfgov/unprocessed/js/organisms/FilterableListControls.js, gulp/utils/scripts-manifest.js
Fixed as many as I could, there's a lot of complexity issues I didn't dare touch. We will also want to take a look at Mortgage Performance in the future, but I didn't want to mess with it since it's in development.
1. run `gulp test`
=> Moar lint fixes

cfgov/jinja2/v1/_includes/organisms/mortgage-performance-downloads.html
=> Mortgage performance: Change hyphens to en-dashes

requirements/optional-public.txt
Bumping versions to the latest repo releases for deploy.
- Company type-ahead / Aggregation
- None
- None
1. 💯 
-
-
=> CCDB Version Bump

docs/atomic-structure.md
=> Fix some typos

cfgov/templates/jobmanager/supervision.html
Adding privacy statement to jobmanager/supervision.html
- Modifed `cfgov/templates/jobmanager/supervision.html` to add privacy act statement. 
1. Visit `http://localhost:8000/jobs/supervision/` and verify the privacy link works as expected.
-
=> Adding privacy statement to jobmanager/supervision.html

requirements/optional-public.txt
=> Bump college costs to 2.3.12 for script fix

requirements/optional-public.txt
Optional Public incremental updates for CCDB5
- None
- None
- Version bump for optional-public for CCDB5
1.
- None
- None
=> CCDB Optional Public Version Bumps

requirements/optional-public.txt
Fixes a build issue that was appending empty font paths and causing issues with collect static (in the version that has been bumped)
- None
- None
- Font paths skipped in webpack build
1. 
-
-
=> CollectStatic fix - Version Bump

requirements/base.txt
bumping wagtail flags to version 2.0.6
=> bumping wagtail flags to version 2.0.6

requirements/optional-public.txt
Reviewed for object in build assets, just in case.
Version bump including polyfill for .include() for IE browsers and streaming CSV in the API
- None
- None
- Version bump
1. 💯 
- None
- None
=> Version Bump.

cfgov/core/management/commands/inactive_users.py, cfgov/core/tests/test_management_inactive_users.py
Saves user states when deactivating them. Includes updated test coverage with additional tests and updated warning email text to remove copypasta.
=> Deactivation update

cfgov/templates/jobmanager/supervision.html
Updating privacy act statement
=> Updating privacy act statement on supervision/jobs page

requirements/optional-public.txt
Include the latest versions of these Django application dependencies.
- None
- None
- Version numbers.
1.
-
-
=> Version bump on includes

cfgov/core/management/commands/inactive_users.py
Updates the text for the warning email to include a call-to-action of what to do next.
=> Update warning text per stakeholder for users approaching inactivity limit

requirements/optional-public.txt
Version bump to incorporate the latest code from CCDB Search application in applicable environments.
- None
- None
- optional-public versions for CCDB API and UI
1. N/A
- None
- None
=> CCDB5 version bump

requirements/optional-public.txt
A minor fix that improves the Clear Filters function.
- None
- None
- CCDB5 Search UI package update.
1. 
- None
- None
=> CCDB Search UI Bump

requirements/optional-public.txt
Updating version to resolve an issue with a URL redirect
- None
- None
- Version of CCDB-ui software
1.
- None
- None
=> CCDB UI version bump

requirements/optional-public.txt
Bumping CCDB to major versions.
- None
- None
- Updated CCDB to v1.0.0 on API / UI
1. 
-
-
=> CCDB5 Version Update

requirements/optional-public.txt
=> Update CCDB-API to latest release.

requirements/optional-public.txt
This PR bumps the complaint app to 1.4.4
=> Bump complaint app to 1.4.4

requirements/optional-public.txt
Version bump for minor CSS / Mobility fixes.
=> Mobile CSS / Interaction Fixes

requirements/optional-public.txt
Increases the suggester API character limit to 100 from 10
- None
- None
- ![bump](https://cdn.instructables.com/FWI/21L0/ERFETVPKSTS/FWI21L0ERFETVPKSTS.RECT2100.jpg)
1.
- None
- None
* [] Visually tested in supported browsers and devices
=> Minor update to CCDB Search API

requirements/optional-public.txt
Version bump resolves incorrect "back to search" link issue when referrer = direct
- None
- None
- CCDBUI 1.0.3
1. Same
- BUMP
- None
=> CCDB Bump - Back Button Referrer Fixes

cfgov/jinja2/v1/index.html
Modifying language on homepage
- Before
- After 
-
-
=> Modifying language on homepage

requirements/optional-public.txt
Updated CCDB Search to change last updated dates and add narrative maxes / warnings.
- None
- None
- Version numbers.
1. Same
-
-
=> Version bump for CCDB5 Search

requirements/optional-private.txt
- Bumps the version of the agreements app to 2.2.10. This updates the links for 2017-Q2
=> Update to agreements database to 2.2.10

cfgov/cfgov/settings/production.py
The syslog files occasionally temporarily do not exist or are unable to be accessed. This fix adds a None default parameter and to prevent a StopIteration error on the server when this occurs.
=> Fixes occasional syslog StopIteration error

cfgov/jinja2/v1/sublanding-page/index.html
=> Remove request param, fixing bug introduced in #3615

cfgov/jinja2/v1/_includes/article.html, cfgov/jinja2/v1/_includes/macros/category-slug.html, cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/jinja2/v1/_includes/organisms/item-introduction.html, cfgov/jinja2/v1/_includes/organisms/post-preview.html, cfgov/jinja2/v1/_includes/tags.html, cfgov/jinja2/v1/activity-log/_activity-list.html, cfgov/jinja2/v1/activity-log/index.html, cfgov/jinja2/v1/browse-filterable/index.html, cfgov/jinja2/v1/sublanding-page/index.html, cfgov/v1/models/base.py, cfgov/v1/models/sublanding_page.py, cfgov/v1/tests/models/test_sublanding_page.py, cfgov/v1/tests/test_filterable_list.py, cfgov/v1/util/filterable_list.py
Reverts cfpb/cfgov-refresh#3603
This is causing some unforeseen issues so reverting for now.
=> Revert "Remove misleading form_id from filterable params"

.travis.yml, run_travis.sh
Fix for chrome bug on Travis
- This is temporary until https://github.com/travis-ci/travis-ci/issues/8836 gets resolved.
-
=> Fix for chrome bug on Travis

cfgov/jinja2/v1/_includes/tags.html
Removing tag logic that displayed tags without an href
=> Removing tag logic that displayed tags without an href

.travis.yml
Run acceptance tests again, now that the Chrome issue is fixed on Travis.
=> Enable acceptance tests to run on Travis

install_travis.sh, run_travis.sh
Removing NVM related code from Travis build
=> Removing NVM related code from Travis build

cfgov/cfgov/settings/local.py, cfgov/cfgov/settings/production.py
Reverts cfpb/cfgov-refresh#3658
=> Revert "Deprecate file cache for eRegs and default caches"

cfgov/legacy/static/knowledgebase/less/es-ask-base.less
This PR reverts some Spanish Ask CFPB style changes from #3617.
=> Revert Spanish Ask CFPB style changes

cfgov/jinja2/v1/_includes/macros/time.html, cfgov/jinja2/v1/_includes/macros/util/format/datetime.html
Add default for text_format parameter to prevent issues loading events archive page
1. Navigate to [Events archive](http://localhost:8000/about-us/events/archive-past-events/) and verify that the page loads without error
=> Fix date macro issue 

package-lock.json, package.json
Bumping version of the chart builder to fix error
=> Bumping version of the chart builder to fix error

cfgov/jinja2/v1/_includes/organisms/email-popup.html, cfgov/jinja2/v1/owning-a-home/_layouts/email-signup.html, cfgov/unprocessed/js/organisms/EmailPopup.js
Change instances of USCFPB_127 to USCFPB_128, per stakeholder request.
See internal issue: 2398
- hardcoded instances of USCFPB_127 changed to to USCFPB_128,
1.
-
-
=> Configure Owning a Home pop-up email prompt to use correct list

cfgov/agreements/templates/agreements/index.html
The 2017-Q3 credit card agreements have been loaded-- this updates the homepage with the latest bulk download
- Link to Q3 agreements added
-
=> Add 2017 Q3 download link to Agreements homepage

.travis.yml, requirements/base.txt, requirements/test.txt, tox.ini
Our new [SQS logging](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/alerts/sqs_queue.py) depends on it
-
-
-
1.
-
-
=> add boto3 to requirements

cfgov/v1/tests/test_filterable_list.py, cfgov/v1/tests/test_fragment_cache_extension.py, cfgov/v1/util/filterable_list.py
See GHE/platform/issues/2403 for context and https://developers.google.com/search/reference/robots_meta_tag
=> Do not index filterable list queries unless it's a single topic tag

cfgov/core/static/robots.txt, cfgov/jinja2/v1/robots.txt
This PR, along with the already merged https://github.com/cfpb/cfgov-refresh/pull/3751, satisfies the requirements in GHE/platform#2403.  
Additionally, this removes an unused robots.txt file.
=> Do not index page results

.env_SAMPLE
This change removes the unused `AKAMAI_HOST` and `AKAMAI_NOTIFY_EMAIL` environment variables from the `.env_SAMPLE` sample environment file, and adds in the `AKAMAI_OBJECT_ID` variable.
It also does some minor reordering of the remaining variables.
=> Update .env_SAMPLE to reflect current Akamai variables

cfgov/jinja2/v1/_layouts/base.html
Fixes https://GHE/CFGOV/platform/issues/2380#issuecomment-148851
This fixes a bug in our canonical URL implementation which allows mixed case or uppercase characters in URL paths to be set as the canonical URL, which we don't want. 
- Uses Jinja2 `lower` filter to convert the request URL string to all lowercase characters
check out this branch and
1. `./runserver.sh`
1. visit http://localhost:8000/policy-coMpliance/EnfOrceMent/ (one of the only mixed-case URLs that doesn't redirect as expected locally, [see this GHE issue for the details there if you're curious](https://GHE/CFGOV/platform/issues/297#issuecomment-148780))
1. View Source and check line 24 to confirm the `link` element's `href` URL appears in all lowercase:
`<link rel="canonical" …
=> Always convert canonical url to lowercase to avoid making duplicate URLs canonical

cfgov/jinja2/v1/job-description-page/index.html
Pay grade link is currently broken
- Update pay grade link
=> Update pay grade link on job listing page

gulp/tasks/build.js, gulp/tasks/clean.js, gulp/tasks/copy.js, gulp/tasks/default.js, gulp/tasks/docs.js, gulp/tasks/images.js, gulp/tasks/lint.js, gulp/tasks/scripts.js, gulp/tasks/styles.js, gulp/tasks/test.js, gulp/tasks/watch.js, gulpfile.js, package-lock.json, package.json
Reverts cfpb/cfgov-refresh#3746 due to non-support of gulp4 in Jenkins build process.
=> Revert "Update to gulp 4"

cfgov/unprocessed/css/pages/error.less, cfgov/unprocessed/css/video-player.less
- Modified file to fix issue with relative path.
1. Run `tox -e validate-assets`
=> Fix for relative image path in less files

cfgov/unprocessed/apps/financial-well-being/js/fwb-questions.js, cfgov/unprocessed/apps/financial-well-being/js/fwb-results.js, cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/index.js, cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/results/index.js, test/unit_tests/apps/financial-well-being/fwb-questions-spec.js, test/unit_tests/apps/financial-well-being/fwb-results-spec.js
Now that there's an unprocessed/apps directory, let's consolidate "apps" code there. This moves /unprocessed/js/apps to /unprocessed/apps.
- Moves /unprocessed/js/apps to /unprocessed/apps.
2. `gulp test:unit`
3. http://localhost:8000/consumer-tools/financial-well-being/ should have no errors.
=> Move js/apps to /apps

.gitignore
- Removes unneeded/redundant gitignores
=> Remove redundant gitignores

cfgov/jinja2/v1/owning-a-home/mortgage-closing/index.html, cfgov/jinja2/v1/owning-a-home/mortgage-estimate/index.html
Fix for static asset location for OAH templates.
=> Fix for static asset location for OAH templates.

.gitignore, cfgov/unprocessed/apps/owning-a-home/config.json, cfgov/unprocessed/apps/owning-a-home/example-config.json
Fix for OAH API config file
- Modified files to add the config.json API endpoints
1. Run `frontend.sh` and verify there are no errors.
=> Fix for OAH API config file

package-lock.json, package.json
- Remove extraneous gulp-babel
=> Remove extraneous gulp-babel

backend.sh, cfgov/agreements/templates/agreements/index.html, cli-flag.sh, frontend.sh, travis_install.sh
Adds Q4 credit card agreements to the archive listing.
- 2017 Q4 credit card agreements zip file and link
1. Verify the page runs under cfgov at https://localhost:8080/credit-cards/agreements/
1. Verify the download link starts correctly (very large file, recommend canceling)
=> Add Q4 agreements to page

test/unit_tests/js/modules/util/email-popup-helpers-spec.js, test/unit_tests/js/modules/util/web-storage-proxy-spec.js, test/util/mock-web-storage.js
- Adds additional code coverage for email popup helpers.
- Moves local/sessionStorage mock in tests to shared utility module.
1. `gulp test:unit` should pass and show coverage on `util/email-popup-helpers.js`
=> Adds email popup helpers coverage

cfgov/jinja2/v1/_layouts/base-common.html
Performance fix --- load fast.fonts.net.css using async method. Currently, this is a render blocking script.
- Modified code to load `fast.fonts.net/t/1.css` using async method.
1. Visit `https://www.consumerfinance.gov/`.
2. Run the audit tool via the Chrome dev tools
3. Notice that the `//fast.fonts.net/t/1.css` script is render blocking.
4. Visit `localhost:8000` and verify that rerun the audit.
5. Bring up the Chrome dev tools and verify that the script is no longer render blocking.
-
-
=> Performance fix --- load fast.fonts.net.css using async method

requirements/optional-public.txt
Update TDP version to pull in the latest work for testing.
- Update TDP version to v0.1.0-alpha.
=> Update TDP version

package-lock.json, package.json
- Updates `webpack` to `4.3.0`.
- Updates `webpack-stream` to `4.0.3`.
1. `npm install && gulp clean && gulp build` should pass.
=> Updates web pack

requirements/optional-public.txt
Hopefully fixed issues causing build errors.
- Update TDP version to 0.1.1
=> Bump TDP release version

cfgov/jinja2/v1/_includes/organisms/email-popup/debt.html
=> Update govdelivery code for debt pages

cfgov/unprocessed/apps/analytics-gtm/js/youtube-event-listeners-older-style.js
[Youtube Flash player has been deprecated since 2015](https://developers.google.com/youtube/player_parameters). This PR removes reference to the player.
- Code comment cleanup.
- Removes code in youtube enterprise analytics that converts old Youtube Flash Player to iframe.
1. Open https://www.consumerfinance.gov/practitioner-resources/library-resources/ in IE8 Sauce Labs and note that clicking video opens it in a new window to youtube.com. So existing behavior is not to convert the embedded player.
1. `gulp clean && gulp build` should pass.
=> Remove reference to deprecated Youtube Flash Player

cfgov/unprocessed/apps/analytics-gtm/js/bah-closing-disclosure-listeners.js
- Updates closing-disclosure analytics code to use `o-expandable`
=> owning-a-home: Updates expandable class reference in closing-disclosure analytics

cfgov/unprocessed/apps/analytics-gtm/webpack-config.js, cfgov/unprocessed/apps/owning-a-home/webpack-config.js, config/webpack-config.js
Fix for using rest spread operator, until Jenkins gets upgraded
- Modified files to fix issue using rest spread operator.
=> Fix for using rest spread operator, until Jenkins gets upgraded

cfgov/unprocessed/apps/analytics-gtm/js/bah-closing-disclosure-listeners.js, cfgov/unprocessed/apps/analytics-gtm/js/youtube-event-listeners-older-style.js, cfgov/unprocessed/apps/analytics-gtm/js/youtube-overlay-click-detection.js
- Removes unused ajax utility function.
- Minor lint cleanup.
- Converts error throwing code to analytics log code.
- Explicitly set call to youtube iframe api as https (reported by @lfatty).
- Uses track() utility function where applicable.
=> Analytics tweaks

test/unit_tests/apps/financial-well-being/js/fwb-questions-spec.js, test/unit_tests/apps/financial-well-being/js/fwb-results-spec.js, test/unit_tests/apps/owning-a-home/js/explore-rates/tab-spec.js, test/unit_tests/apps/owning-a-home/js/ratings-form-spec.js, test/unit_tests/js/modules/ClearableInput-spec.js, test/unit_tests/js/modules/footer-button-spec.js, test/unit_tests/js/modules/o-table-row-links-spec.js, test/unit_tests/js/molecules/Multiselect-spec.js, test/util/simulate-event.js
- Moves simulated event utility functions in tests to shared utility function.
1. `gulp test:unit` should pass.
=> Create event test utility

requirements/optional-public.txt
Added start page, new content pages, and more unit tests.
- Updated TDP version to 0.3.0
=> Bump TDP release version to 0.3.0

requirements/optional-public.txt
Added more features for QA review.
- Updated TDP version to 0.3.1
=> Bump TDP release version to 0.3.1

requirements/optional-public.txt
Updated content and added functionality.
- Updated TDP version to 0.3.4
=> Bump TDP release version to 0.3.4

requirements/optional-public.txt
Updated content and added functionality.
- Updated TDP version to 0.4.0
=> Bump TDP release version to 0.4.0

requirements/optional-public.txt
Updated content and styles.
- Updated TDP version to 0.4.1
=> Bump TDP release version to 0.4.1

requirements/optional-public.txt
Updated content and styles.
- Updated TDP version to 0.4.1
=> Bump TDP release version to 0.4.2

gulp/tasks/test.js
Fix for jests tests on Travis
- This is an experiment based on https://github.com/facebook/jest/issues/5989
1.
-
-
=> Fix for Jest tests on Travis

requirements/optional-public.txt
Bump OAH-api version to update data load process
- Update oah-api release version
=> Bump oah-api version

requirements/optional-public.txt
- Updated TDP version to 0.5.0
=> Bump TDP release version to 0.5.0

requirements/optional-public.txt
Fixed functionality bugs.
- Updated TDP version to 0.5.1
=> Bump TDP release version to 0.5.1

requirements/optional-public.txt
- Updated TDP version to 0.5.2
=> Bump TDP release version to 0.5.2

docs/caching.md
Minor update to specify doing this from the django shell.
=> Update documentation on clearing post preview cache

requirements/optional-public.txt
- Updated TDP version to 0.5.4
=> Bump TDP release version to 0.5.4

requirements/optional-public.txt
CCDB-UI has been updated to incorporate a small font fix, and update a node package dependency that indicated a potential security issue. (Described below under changes)
- None
- None
- Demi => Medium
- Updated Moment.js dependency to avoid potential injection issue identified in previous package
1. 💯 
- None
- None
=> CCDB UI Version Update

requirements/optional-public.txt
Updated content and styles.
- Updated TDP version to 0.5.5
=> Bump TDP release version to 0.5.5

requirements/optional-public.txt
- Updated TDP version to 0.5.6
=> Bump TDP release version to 0.5.6

requirements/optional-public.txt
- Updated TDP version to 0.5.7
=> Bump TDP release version to 0.5.7

requirements/optional-public.txt
Fixed bug preventing IE testing.
- Updated TDP version to 0.5.8
=> Bump TDP release version to 0.5.8

requirements/optional-public.txt
- Updated TDP version to 0.5.9
=> Bump TDP release version to 0.5.9

gulp/utils/handle-errors.js
- Removes unneeded browsersync reference from gulp utility.
=> Remove browsersync reference

requirements/optional-public.txt
=> Bump retirement to 0.6.0

requirements/optional-public.txt
- Updated TDP version to 0.5.10
=> Bump TDP release version to 0.5.10

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
Teachers Digital Platform has multiple sub tools they need to individually turn on and off.  This request adds 3 new Flags and uses 2 of them and we will be using the other in the near future.
- Three New Feature Flags:
- TDP_CRTOOL
- Used for the Customer Review Tool (turn on and off)
- TDP_CRTOOL_PROTOTYPES
- Used for the prototype pages for the Customer Review Tool (turn on and off)
- TDP_SEARCH_INTERFACE
- Will be used for the Search Interface we are starting to develop right now
- N/A
- N/A
- @hillaryj @Scotchester
=> TDP: Implemented Feature flags for each TDP component

cfgov/jinja2/v1/_includes/organisms/bureau-structure.html
Changing copy on bureau structure
-
-
=> Changing copy on bureau structure

cfgov/jinja2/v1/_layouts/base.html
Removing async from script tag
-
-
=> Removing async from script tag

cfgov/legacy/templates/hud/housing_counselor.html
Satisfies Jira issue INTAKE-2387.
- Updates link to HUD.gov's list of housing counselors to a non-broken link
1. Pull branch
1. Visit http://localhost:8000/find-a-housing-counselor/ and try the updated link
=> Update link to HUD.gov's list of housing counselors

requirements/libraries.txt
- Bumps wagtail-inventory to latest version
=> Bump wagtail-inventory version

cfgov/jinja2/v1/_includes/organisms/bureau-structure.html, cfgov/jinja2/v1/blog/blog_page.html, cfgov/jinja2/v1/job-description-page/index.html, cfgov/jinja2/v1/know-before-you-owe/compare/index.html, cfgov/jinja2/v1/know-before-you-owe/index.html, cfgov/jinja2/v1/know-before-you-owe/timeline/index.html, cfgov/jinja2/v1/regulation-comment/success/index.html, cfgov/jinja2/v1/your-story/index.html, cfgov/v1/__init__.py, cfgov/v1/tests/test_links.py, cfgov/wellbeing/jinja2/wellbeing/about.html, cfgov/wellbeing/jinja2/wellbeing/results.html
Update all found existence of link icons (other than heading links) to use SVG icons. Includes parsed-links and it's related tests.
Co-authored-by: Scott Cranfill <scott.cranfill@cfpb.gov>
- Updated any files currently using link icons to use their SVG equivalent.
1. Check out external and download parsed links at `http://localhost:8000/practitioner-resources/library-resources/`
1. Check out email link at the bottom of `http://localhost:8000/about-us/the-bureau/bureau-structure/`
1. Check out the external links at the bottom of `http://localhost:8000/about-us/blog/3-common-credit-issues-and-what-you-can-do-fix-them/`
1. Check out the download link at `http://localhost:8000/about-us/careers/management-and-program-analyst-workforce-planning-93mp …
=> Convert link icons to SVG icons

cfgov/jinja2/v1/_includes/molecules/social-media.html, cfgov/jinja2/v1/owning-a-home/_templates/social-media.html
- Fixes issue where Flickr was getting YouTube icon.
- Fixes issue where OAH social media template had some old-style icons that needed updating to SVG
=> Fixes erroneous / missing SVG updates

frontend.sh
- Removes if condition for generating checksum.
1. Run `./frontend.sh`
2. Run `./frontend.sh` again. It should output that dependencies are up-to-date.
3. Run `./frontend.sh production`
3. Run `./frontend.sh production` again. It should output that dependencies are up-to-date.
=> Remove unneeded condition

requirements/optional-public.txt
Added analytics and updated styles.
- Updated TDP version to 0.5.13
=> Bump TDP release version to 0.5.13

requirements/optional-public.txt
Added analytics, bug fixes, and documentation.
- Updated TDP version to 0.5.14
=> Bump TDP release version to 0.5.14

requirements/optional-public.txt
Updated Analytics. (Just final tweaks, now that its all working)
Changes
Updated TDP version to 0.5.15
=> Bump TDP release version to 0.5.15

.env_SAMPLE, .python_env_SAMPLE, docs/installation.md, docs/usage.md, homebrew-deps.sh, pgloader_shell.sh, refresh-data.sh
The main goal here is to shift the local dev setup/docs (both stand-alone and Docker-based) in the direction of Postgres and away from MySQL. Apologies for the slightly haphazard nature of the cleanup here – not all of it is strictly related to the task at hand.
=> Updates to support move to Postgres for local dev

cfgov/unprocessed/apps/analytics-gtm/js/hdma-explore-event-listeners.js
- Removes jquery from HDMA analytics Google Tag Manager tag.
=> Removes jquery from HDMA custom tag

cfgov/cfgov/settings/base.py
- Fixes "techical" typo in code comment.
=> Fixes "techical" typo in code comment

requirements/optional-public.txt
Additional 508 compliance additions for modal dialogs
Changes
Updated TDP version to 0.5.18
=> Bump TDP release version to 0.5.18

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
Updating menu to add diversity and inclusion item
1. Place mouse over `About Us` in the menu. 
2. Verify that the `Diversity & Inclusion` nav item is present.
-
-
=> Updating menu to add diversity and inclusion item

cfgov/jinja2/v1/events/_macros.html
Switch event link from the test link to the live link
1. Visit `http://localhost:8000/about-us/events/town-hall-topeka-kan-fighting-elder-financial-exploitation-your-community/` and view the event.
2. It should play as expected. 
-
-
=> Switch event link from the test link to the live link

cfgov/jinja2/v1/events/_macros.html
1. Load http://localhost:8000/about-us/events/town-hall-topeka-kan-fighting-elder-financial-       exploitation-your-community/
1. Edit it to ensure the Live Stream Information URL field is empty and Go Live Date is earlier    today
1. Note the height of the iframe now fitting the video ideally, borders no longer pushing outside  the gray box, and the gray bar no longer under the iframe
(showing previously coded test video, not the true event video you'd see now on localhost)
=> Improve styling of Yorkcast livestream iframe

requirements/optional-public.txt
=> Updating the CCDB5 version

requirements/optional-public.txt
- Bumps regs site version to 2.2.4
=> Bump regs site version to 2.2.4

cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_layouts/content-base.html
- Removes unnecessary role `banner` from header element.
- Removes unnecessary role `main` from main element.
=> Removes unnecessary role attributes from header and main elements

cfgov/jinja2/v1/ask-cfpb/landing-page.html, cfgov/jinja2/v1/index.html
Missing some role="main" attributes in https://github.com/cfpb/cfgov-refresh/pull/4265
- Removes unnecessary role main from main element.
- Why do we have so many templates 😭 😭 😭
=> Clean up additional role main attributes

cfgov/agreements/templates/agreements/index.html
It's time for the quarterly update to the archive list.
Data are deployed, so this should go out soonish.
=> Credit card agreements: Quarterly update

requirements/optional-public.txt
Access the version with better error handling
=> Bump the CCDB5-API version

requirements/optional-public.txt
Fixed accessibility bugs.
- Updated TDP version to 0.5.23
=> Bump TDP release to 0.5.23

frontend.sh, package.json, travis_install.sh, travis_run.sh
Closes #4254
- A `gulp` npm script that allows the local gulp executable to be run
- `npm remove gulp-cli -g && which gulp`
- Should be `gulp not found`
- `npm run gulp`
- Ensure gulp runs the build task
- `npm run gulp clean`
- Ensure gulp runs with passed arguments
=> Add gulp npm script

requirements/optional-public.txt
Brings in https://github.com/cfpb/retirement/pull/222
- Bump retirement to 0.6.2
=> Bump retirement to 0.6.2

docs/installation.md, docs/usage.md
Like https://github.com/cfpb/cfgov-refresh/pull/4280/, but through the proper channels. Adds docs update for usage of local gulp.
=> Add docs for local gulp usage

cfgov/v1/handlers/blocks/feedback.py, cfgov/v1/tests/handlers/blocks/test_feedback.py
The migration from MySQL to Postgres introduced a bug where submissions to the feedback form would cause a 500 error if the referrer exceeded 255 characters. See platform#2857 for additional detail.
This change adds manual truncation of overly-long referrers so that these never get sent down into the database. This is done in a very minimal way by modifying the existing logic; a better way to do this would be to refactor the feedback forms to leverage Django form validation. I implemented the fix in this minimal way for expediency's sake.
New unit tests have been added that verify the new behavior. To properly run these tests against Postgres locally, use a command line like:
```
TEST_DATABASE_URL=postgres://user@localhost/db tox
```
Travis always runs unit tests using Postgres, so that …
=> Truncate overly-long referrers in feedback forms

requirements/optional-public.txt
Added error messages functionality and fixed bugs.
- Updated TDP version to 0.6.0
@Scotchester @cfarm @willbarton @higs4281 @hillaryj
=> Bump TDP release to 0.6.0

cfgov/jinja2/v1/_includes/organisms/mega-menu.html
HTML validation is failing in part to missing or incorrect role
attributes. This change fixes both the missing DIV roles and the missing
parents to the existing menuitems.
- Adds appropriate role attributes to menu containers.
1. Install the [Chrome HTML Validator](https://chrome.google.com/webstore/detail/html-validator/mpbelhhnfhfjnaehkcnnaknldmnocglk/related?hl=en-US) if you haven't already.
1. Run `./runserver.sh`
1. Navigate to `http://localhost:8000/`
1. Open the Chrome Inspector and click the "HTML validator" tab
1. Click the "W3C Online" button at the top right
1. Verify that there are no role errors for menu items
1. Celebrate 🙌 🎉 
Before
After
- W3C includes a [great menu example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html) that I …
=> Add menu role to the containers for each nav level

test/unit_tests/js/modules/ExternalSite-spec.js
- Adds unit test for ExternalSite JS class.
1. `gulp test:unit --specs=js/modules/ExternalSite-spec.js` should show coverage.
=> Add test for ExternalSite

requirements/optional-public.txt
Fixed bugs.
- Updated TDP version to 1.0.1
@Scotchester @cfarm @willbarton @higs4281 @hillaryj
=> Bump TDP release to 1.0.1

requirements/optional-public.txt
Removed unfinished work.
- Updated TDP version to 1.0.2
@chosak
=> Bump TDP release to 1.0.2

cfgov/unprocessed/apps/analytics-gtm/js/retirement-before-you-claim-listeners.js
Refactors retirement form submission analytics to use one event handler and to not depend on jquery. Also adds mouseflow capture script on form submission.
- Mouseflow start capture on form submission.
- Consolidates and removes jquery from form submission tracking code.
1. Will need to test after this PR is submitted on build.cf.gov
- `var mouseflowAutoStart = false;` needs to be on this page before where the mouseflow script is added to the page.
=> Refactor and add mouseflow

cfgov/cfgov/settings/base.py, requirements/optional-public.txt
Added TDP Activity models
Reverted BCFP logo changes
- Added mptt and haystack to installed apps
- Updated TDP version to 1.0.5
@chosak @willbarton  @higs4281
=> Bump teachers_digital_platform app to version 1.0.5

requirements/optional-public.txt
* Added data migration for initial data 
@chosak @willbarton  @higs4281 @Scotchester
=> Bump TDP app to version 1.0.6

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, requirements/optional-public.txt
Add a feature flag for the building blocks tool.
- Feature flag for the building blocks tool
- Url to use for the building blocks tool feature flag
=> Add BB Tool feature flag for Teacher's Digital Platform

cfgov/regulations3k/jinja2/regulations3k/inline_interps.html, cfgov/unprocessed/apps/regulations3k/css/reg-inline-interpretations.less
@willbarton This adds additional expandable improvements to your SVG fix.
=> Update Regs3K expandable to match new format

requirements/optional-public.txt
Bump TDP release to 1.0.10 to fix deployments to build
@Scotchester  @willbarton @higs4281 @chosak
=> Bump TDP release to 1.0.10

requirements/optional-public.txt
Bump version of TDP up to 1.0.14
- @Scotchester @chosak @willbarton @higs4281
=> Bump TDP release to 1.0.14

requirements/optional-public.txt
CC: @chosak @ascott1 @willbarton @higs4281
=> Bump TDP to version 1.0.15

requirements/optional-public.txt
Bump TDP to version 1.0.16
- @Scotchester @higs4281 @willbarton @chosak
=> TDP: Bump TDP version to 1.0.16

requirements/optional-public.txt
Bump teachers_digital_platform from version 1.0.16 to 1.0.17
=> [TDP] Bump TDP to version 1.0.18

requirements/optional-public.txt
Deploying IE and Edge fixes to TDP Search Tool
- @Scotchester @chosak @willbarton @higs4281
=> Bump TDP version to 1.0.20

requirements/optional-public.txt
Updated content and styles for the search landing page.
- Updated TDP version to 1.0.21
=> Bump TDP release to 1.0.21

requirements/optional-public.txt
Bump TDP version from 1.0.21 to 1.0.22
- @Scotchester @willbarton @higs4281 @chosak
=> [TDP] Bump TDP version to 1.0.22

cfgov/cfgov/settings/base.py, package-lock.json, package.json
- Rollback https://github.com/cfpb/cfgov-refresh/pull/4452, since https://github.com/cfpb/cfpb-chart-builder/pull/126 was merged.
=> Remove unneeded URL

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html, cfgov/regulations3k/jinja2/regulations3k/landing-page.html, cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
I updated the Regs3K icons but failed to update the templates causing some 404 errors. 😓
=> Update Regs3K icon path names

requirements/optional-public.txt
Updated content and styles for the search landing page.
- Updated TDP version to 1.0.23
=> Bump TDP release to 1.0.23

cfgov/search/templates/search/external_links.html
- Adds `rel` attribute to target blank links.
=> Add noopener noreferrer rel attribute to target blank links

cfgov/jinja2/v1/events/_macros.html
Sets the video embed link for a town hall event on October 18
- Video embed link from vendor
1.
-
-
=> Update video iframe for new event

requirements/optional-public.txt
Updated content on activity detail pages.
- Updated TDP version to 1.0.25
=> Bump TDP release to 1.0.25

cfgov/core/middleware.py, cfgov/core/tests/test_middleware.py
The parse_links method used by the ParseLinksMiddleware was using string logic that wasn't compatible with Python 3, and was causing a test failure when running Python tests against Python 3.
To run relevant tests against Python 2.7:
`tox -e unittest-py27-dj111-wag113-fast core.tests.test_middleware`
To run relevant tests against Python 3.6:
`tox -e unittest-py36-dj111-wag113-fast core.tests.test_middleware`
Specifically, in Python 3 the value coming into parse_links may be either a string (the str type) or bytes. The current logic that calls html.decode doesn't handle the bytes case.
=> Add Python 3 support to parse_links

cfgov/jinja2/v1/_includes/organisms/mortgage-chart.html
- Fixes incorrect closing heading tag.
- Stacks attributes.
=> Fix wrong heading closing tag

cfgov/unprocessed/js/modules/util/FormModel.js, cfgov/unprocessed/js/organisms/FilterableListControls.js, test/unit_tests/js/modules/util/FormModel-spec.js, test/unit_tests/js/organisms/FilterableListControls-spec.js
- Adds FormModel as a representation of form fields and move all initial field validation logic to that module.
- Adds initial tests for FilterableListControls module.
1. `./frontend.sh` should pass and filters such as on the blog page should work as before.
2. `gulp test:unit` should pass.
=> Filters: Moves form validation code to FormModel module and adds initial tests

.travis.yml
Attempting to make Travis deploy the docs when tags are pushed
See https://[GHE]/CFGOV/platform/issues/3023 for more info
-
-
-
1.
-
-
=> Run Travis build on tags

.travis.yml
=> add missing regex slashes to build tags on Travis

requirements/optional-public.txt
Reverts 5K export issue.
- Version bump for CCDB5 API.
- None
- 
1.
-
-
=> Bump CCDB5 API to Revert 5K Limit

cfgov/v1/tests/jinja2tags/test_fragment_cache.py
This is a working version of the unit tests in #4399. It adds additional unit tests for the `{% cache %}` Jinja2 tag, specifically around multiple cache support added in #4384.
=> Add additional unit tests for fragment caching

requirements/optional-public.txt
Updated to latest version of Capital Framework.
- Updated TDP version to 1.0.28
=> Bump TDP release to 1.0.28

cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/actions/map.js
- Fixes import statements in MPT util import.
=> Fixes utils import

docs/housing-counselor-tool.md, mkdocs.yml
An overview of the Find a Housing Counselor tool.
- a documentation page under the "Back End Guidelines" category, called "Housing Counselor Data Processing" 
- I'm not up to speed on our documentation standards. Feedback welcome on where this should live, its organization, formatting, and content, and anything else.
=> Documentation for hud_generate_json management command

cfgov/cfgov/settings/base.py
See GHE/CFGOV/platform/issues/3061
=> Adds mouseflow to connect-src

cfgov/jinja2/v1/_includes/blocks/feedback.html, cfgov/unprocessed/js/molecules/Notification.js, cfgov/unprocessed/js/organisms/FormSubmit.js, cfgov/unprocessed/js/routes/on-demand/feedback-form.js
Pulls in changes from https://github.com/cfpb/cfgov-refresh/pull/3117 (rebased onto master) with updated PII language from GHE/CFGOV/platform/issues/3114.
The underlying template for `cfgov/jinja2/v1/_includes/blocks/feedback.html` has changed quite a bit since this PR was first proposed, so I'd recommend going back over it carefully to make sure it looks/operates as expected.
=> Feedback form on success w/ PII language

cfgov/ask_cfpb/scripts/export_ask_data.py
In https://github.com/cfpb/cfgov-refresh/pull/4732, I introduced an option to export Ask data from the Wagtail admin.  Unfortunately, it was timing out on production as it was taking longer than a minute to run (locally it would take about 30 seconds).  
Thanks to feedback from other developers and much help from @chosak, I was able to significantly reduce the runtime by modifying the queries.  Instead of making several subqueries on each answer, we do a couple bulk queries upfront to get all the attributes we need.  There's a bit more code to specify the `prefetch_fields`, pair each answer with its answer pages, and construct the lists of `ManyToMany` objects (e.g. subcategories) -- but it means we only have to make 2 queries (one set of answers and one set of answer pages) versus over …
=> Optimize Ask Export queries

cfgov/v1/handlers/blocks/feedback.py, cfgov/v1/tests/handlers/blocks/test_feedback.py
Quit trying to fix bad referrer strings and skip them instead.
=> Trap feedback encoding error

cfgov/wellbeing/jinja2/wellbeing/about.html
#4788
- New link to sidebar of the about page on the financial well-being tool, which is hard-coded in a template file
1. Pull branch
1. Load http://localhost:8000/consumer-tools/financial-well-being/about/
1. See the new link at the top of the sidebar
1. Click it (may need to enable `FINANCIAL_WELLBEING_HUB` flag)
=> Update sidebar content on FWB tool about page

refresh-data.sh
Correction to documented usage of refresh data script.
=> Corrects refresh-data.sh usage

requirements/requirements.txt
This file's purpose is to be checked for vulnerabilities by Snyk, which requires a file named `requirements.txt`.
- `requirements.txt` file for Snyk
We won't be able to test this until we merge and use the Snyk UI to try and add this file to watch it.
- I'm not certain Snyk will use the `-r` directive to pull in the dependencies from the other files. I guess we'll have to try it and see.
- Another potential solution would be to put each requirements file in a subdirectory of its name, and then have the files all be named `requirements.txt`. We could then add one or more of those files to what Snyk is monitoring. Both that and the solution proposed here are inelegant, but this seems preferable to me.
=> Add requirements.txt file for Snyk to consume

docs/feature-flags.md
Fixes minor typos in flags documentation.
=> Fixes minor typos in flags documentation

docs/satellite-repos.md
link to the otherwise-hidden documentation about local satellite repo set up/ usage
-
-
-
1.
-
-
=> Add link to usage from satellite repo page

requirements/optional-public.txt
Updates Paying for College app to 1.9.1, which includes updated federal loan rates and other constants.
- Changes PFC version in `requirements`
1. Pull down this branch and make sure it installs the latest Paying for College (1.9.1)
=> Update Paying for College to release 1.9.1

cfgov/core/static/robots.txt
This should avoid crawler traffic to these two deprecated URL paths.
=> Add /yourstory and /hud-api-replace to our robots disallows

requirements/optional-public.txt
Updated Capital Framework to v.8.0.0.
- Updated TDP version to 1.0.30
=> Bump TDP release to 1.0.30

.yarnrc
Fixes small bug in .yarnrc file
=> Uncomment errant comments left in .yarnrc

requirements/optional-public.txt
Send search term and results count to Analytics after keyword searches
@Scotchester @chosak @higs4281 @willbarton
=> [TDP] Bump version to 1.0.31

requirements/optional-public.txt
This will release the fix for checkbox styling
=> Bump ccdb-ui release

docs/python-unit-tests.md, docs/travis.md
This change makes two minor documentation fixes:
1. Corrects name of the [environment variable](https://github.com/cfpb/cfgov-refresh/blob/5903485227013234d582087f6c00f593de2bdc1f/cfgov/cfgov/settings/test.py#L7) to use to test against an alternate database, and a typo in the same line.
2. Fixes bulleted list.
Corrected "Python unit testing":
Corrected "How we use Travis CI":
=> Minor documentation fixes

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/index.html
Closes https://GHE/CFGOV/platform/issues/3384
1. Pull branch
1. Load http://localhost:8000/
1. See "Recent updates" instead of "Latest updates"
=> Change "Latest updates" heading on homepage to "Recent updates"

cfgov/legacy/static/nemo/_/js/main.js, cfgov/legacy/static/nemo/_/js/plugins.js
Reported by Lamin (@lfatty), this converts some remaining `http` to `https` values in the legacy script.
=> Update http to https in legacy youtube script

cfgov/hmda/resources/hmda_data_options.py
=> Fix typo: Plan -> Plain

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
@higs4281 found that using `flag_enabled` this way is inconsistent and the redirects aren't reliable.  Going to revert for now.
Reverts cfpb/cfgov-refresh#4979
=> Revert "Add redirects for Ask CFPB Category/subcategory pages"

cfgov/cfgov/urls.py
Adds redirects for Ask category and subcategory pages, which are being replaced by portal and search pages.
=> Add Ask category redirects.

test/browser_tests/cucumber/features/suites/default/pagination.feature
Restore two cucumber tests that were errantly deleted.
=> restore errantly dropped tests.

test/browser_tests/cucumber/features/suites/default/pagination.feature
Some acceptance tests in the pagination feature are failing despite the fact that these features are working. This PR will disable these failing tests until a suitable solution is found.
- Skip some tests in `pagination.feature`
- Make it so that there are not weird intermittent failures on these acceptance tests.
=> Skip some acceptance tests

gulpfile.js
=> Ignore new acceptance tests in production

requirements/optional-public.txt
Fixes income question's "yes" answer text.
=> Bump retirement to 0.8.2 for translation fix

requirements/optional-public.txt
Updated information sent for analytics.
- Remove inset scrolling on journey page
=> Bump TDP release to 1.1.2

requirements/optional-public.txt
- Bump college-costs to 2.7.0 from 2.6.2
=> Bump college-costs to 2.7.0 from 2.6.2

requirements/optional-public.txt
- Bump college-costs to 2.7.1 from 2.7.0
- Bump django-college-costs-comparison to 1.10.1 from 1.11.2
=> Bump college-costs to 2.7.1 and comparisontool to 1.11.2

requirements/optional-public.txt
- Bump college costs to 2.7.2 from 2.7.1
=> Bump college costs to 2.7.2 from 2.7.1

cfgov/unprocessed/css/on-demand/footer.less, cfgov/unprocessed/css/on-demand/header.less
- Update header/footer `@cf-icon-path` variables to be /icons/ instead of /fonts/
=> Update header/footer cf-icon-path variables

requirements/optional-public.txt
- Bump ccdb5_ui to 1.3.2 from 1.3.1
=> Bump ccdb5_ui to 1.3.2

requirements/optional-public.txt
- Version bump.
- None
- Version bump for CCDB5-UI
-
- Deploy.
=> Bump CCDB5-UI to 1.3.3 for Icon Path Fix.

requirements/optional-public.txt
Bumps the CCDB-UI requirement to resolve an issue with checkbox labels.
=> Version bump for CCDB to 1.3.4

cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/unprocessed/apps/find-a-housing-counselor/css/hud.less, cfgov/unprocessed/apps/find-a-housing-counselor/css/main.less
Our changes to the Featured Content Module styling unintentionally affected the FAHC search box and map layout. This commit de-FCMs that and adds some basic styling to get it back close to what we had before.
See CFGOV/platform bug: https://GHE/CFGOV/platform/issues/3492
- New styling specific to FAHC search/map
- Removed FCM classes from FAHC search/map
1. Pull branch
1. Open http://localhost:8000/find-a-housing-counselor/ and view at different widths 
- This solution uses flexbox, and for that reason (I believe), the map does not load on IE 10 and below. This was already the case since at least the time that this page was moved into cfgov-refresh, as the previous iteration of the FCM also used flexbox. Unsure if we should be concerned about this or not. …
=> Fix size of map on Find a Housing Counselor

requirements/libraries.txt
=> Bump retirement to 0.10.2

cfgov/unprocessed/root/akamai-sureroute-test-object.html
We use [Akamai SureRoute](https://developer.akamai.com/legacy/learn/Optimization/SureRoute.html) to help accelerate our production website. Currently the site serves a "SureRoute test object" at
https://www.consumerfinance.gov/akamai/sureroute-test-object.html
We currently store and configure this file in our internal Ansible repository. This PR moves that file to this public repository. A related PR will be opened internally to change our Apache configuration to serve using this file instead.
Per the (behind a login) Akamai documentation on SureRoute, this file:
1. Must return a HTTP 200 response and not require authentication
2. Should be a static text file of content text/html, about the size of
an average page, but no less than about 8 KB.
3. Should not contact a database or do other …
=> Add Akamai SureRoute test file to this repository

cfgov/apache/conf.d/wsgi.conf, cfgov/apache/conf.modules.d/00-base.conf
(tbh since autoindex was already commented out, this PR shouldn't really have any effect, but it is more explicit about disabling indexing)
Companion to a-c-f#319
=> Companion to a-c-f changes, this cleans up indexing behavior a tad

requirements/libraries.txt
This fixes an error with CSV export of complaints containing non-ASCII characters.
=> Bump ccdb5-api from 1.1.10 to 1.1.11

cfgov/jinja2/v1/youth_employment_success/budget-form.html, cfgov/jinja2/v1/youth_employment_success/goals.html, cfgov/jinja2/v1/youth_employment_success/goals/goal.html, cfgov/jinja2/v1/youth_employment_success/index.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less
HTML needed both to convey the content to the user, and to provide form components for them to interact with.
- Adds goals setting form fields and associated content
-
-
1. Content should load in the browser. Styling doesn't need to be exact but should match mockups — ask and I'll provide them!
- Images not yet finalized, empty `<img>` tags are there for placeholders
-
=> YES tool — Adds basic html for goal-setting section

cfgov/jinja2/v1/youth_employment_success/index.html, cfgov/jinja2/v1/youth_employment_success/route-questions/average-total-cost.html, cfgov/jinja2/v1/youth_employment_success/route-questions/days-per-week.html, cfgov/jinja2/v1/youth_employment_success/route-questions/miles.html, cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less, cfgov/unprocessed/apps/youth-employment-success/js/index.js, cfgov/unprocessed/apps/youth-employment-success/js/input-view.js, cfgov/unprocessed/apps/youth-employment-success/js/util.js, cfgov/unprocessed/js/organisms/BureauStructure.js
~To check for supported JS environments, I'm checking for `classList`. The code makes use of passing multiple arguments to `classList.add`, which is not supported by IE 11. If there is a more standard feature to check for,  I'm happy to use that!~
Now using the `no-js` class modernizr adds to the `html` element.
- Add `no-js` class to `main` element
- Add `u-js-only` classes to each check box.
-
-
1. Either load the page using IE 11 or lower, or remove the check for `classList` on line 37 of this project's `index.html` file.
2. Each of the 'I'm not sure' checkboxes in the image below should be hidden:
-
-
=> YES tool — Hides checkboxes in a no-js environment

cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html
Error prevents template and tool from rendering properly!
- Adds missing ','
-
-
1. Page should load
-
-
=> YES tool— Fix syntax error in template

cfgov/jinja2/v1/_layouts/404.html
- Fix straight quote on 404 template
=> Fix straight apostrophe on 404 template

cfgov/jinja2/v1/_includes/molecules/notification.html
- Adds missing comment for notification links
=> Adds missing comment for notification links

cfgov/jinja2/v1/index.html, cfgov/jinja2/v1/index_es.html
- Removes last updated date.
- Updates data snapshot numbers on the homepage.
1. Pull branch, run local server and check localhost homepage.
2. Spanish homepage should be updated with the same values.
Before:
After:
=> Homepage: Update data snapshot numbers

cfgov/jinja2/v1/youth_employment_success/alert-icon.html, cfgov/jinja2/v1/youth_employment_success/alert.html, cfgov/jinja2/v1/youth_employment_success/route-option-form.html, cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html, cfgov/unprocessed/apps/youth-employment-success/js/index.js, cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js, cfgov/unprocessed/apps/youth-employment-success/js/todo-notification.js, cfgov/unprocessed/apps/youth-employment-success/js/views/average-cost.js, cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js, cfgov/unprocessed/apps/youth-employment-success/js/views/miles.js, cfgov/unprocessed/apps/youth-employment-success/js/views/transit-time.js, test/unit_tests/apps/youth-employment-success/fixtures/todo-alert.js, test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js, test/unit_tests/apps/youth-employment-success/js/todo-notification-spec.js, test/unit_tests/apps/youth-employment-success/js/views/average-cost-spec.js, test/unit_tests/apps/youth-employment-success/js/views/days-per-week-spec.js, test/unit_tests/apps/youth-employment-success/js/views/miles-spec.js, test/unit_tests/apps/youth-employment-success/js/views/transit-time-spec.js, test/unit_tests/apps/youth-employment-success/mocks/todo-notification.js, test/unit_tests/mocks/store.js
Adds behavior for showing and hiding alerts that inform the user when an item has been added to, or removed from, their action plan to-do list.
- `TodoNotification` component
1. Specs pass
2. Clicking the `not sure` checkboxes displays an affirmative message. That message should persist until the checkbox is clicked again. Then, the message should change, and disappear
3. Toggling the visibility of a component by selecting another `transportation` radio option should also clear the notification, if the previous option is selected again, the notification should be gone.
-
-
=> YES tool — Add todo notification behavior

requirements/libraries.txt
Updated design of journey page with new illustrations and animations.
- New sub-sections for the Building Blocks section
- Animations for the Building Blocks illustration
- Jumplinks for the Building Blocks section
- Accordion for Building Blocks
- Illustrations for all of the sections on the Journey Page
- Remove 15px offset from smooth scroll JavaScript
@Scotchester @willbarton @chosak
=> Bump TDP release to 1.1.4

cfgov/unprocessed/js/modules/Analytics.js, cfgov/unprocessed/js/modules/TabTrigger.js, cfgov/unprocessed/js/modules/behavior/FlyoutMenu.js, cfgov/unprocessed/js/molecules/GlobalSearch.js, cfgov/unprocessed/js/organisms/FormSubmit.js, cfgov/unprocessed/js/routes/data-research/prepaid-accounts/search-agreements/index.js
- Fixes incorrect code comment.
- Fixes some import order linter warnings.
=> Minor comment and linter fixes

cfgov/v1/forms.py
Previously, filterable lists would return a 500 error when they received a query string with a 'topics' value containing a null character (`%00` in URL encoding). This would happen in waves occasionally, presumably because of bot activity.
This PR adds validation to the 'topics' field, so instead of querying the database with the faulty string, causing an error, we return an error to the user saying "Topics: Select a valid choice. [your input] is not one of the available choices".
- In the `FilterableListForm`, update the `topics` field from using custom `MultipleChoiceFieldNoValidation` to using a standard `MultipleChoiceField` from the Django Forms library.
2. Visit a filterable list form, e.g.:
- http://localhost:8000/about-us/events/archive-past-events/
- …
=> Filterable List: Ensure topics query string doesn't contain malicious characters

cfgov/jinja2/v1/youth_employment_success/budget-form.html, cfgov/jinja2/v1/youth_employment_success/goals.html, cfgov/jinja2/v1/youth_employment_success/goals/goal.html, cfgov/jinja2/v1/youth_employment_success/index.html, cfgov/jinja2/v1/youth_employment_success/line-item.html, cfgov/jinja2/v1/youth_employment_success/review/review.html, cfgov/jinja2/v1/youth_employment_success/route-details.html, cfgov/jinja2/v1/youth_employment_success/route-option-form.html, cfgov/jinja2/v1/youth_employment_success/route-options.html, cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html, cfgov/jinja2/v1/youth_employment_success/route-questions/days-per-week.html, cfgov/jinja2/v1/youth_employment_success/route-questions/driving-cost-estimate.html, cfgov/jinja2/v1/youth_employment_success/route-questions/input.html, cfgov/jinja2/v1/youth_employment_success/route-questions/miles.html, cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less, cfgov/unprocessed/apps/youth-employment-success/js/budget-form-view.js, cfgov/unprocessed/apps/youth-employment-success/js/todo-notification.js, test/unit_tests/apps/youth-employment-success/fixtures/todo-alert.js, test/unit_tests/apps/youth-employment-success/js/budget-form-view-spec.js
Further refinements based on design feedback session. 
1. The app should still behave as it did, these changes are purely cosmetic.
=> YES tool — Further design refinements

cfgov/jinja2/v1/youth_employment_success/budget-form.html, cfgov/jinja2/v1/youth_employment_success/index.html, cfgov/jinja2/v1/youth_employment_success/review/print.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less
This PR introduces several small tweaks to the layout that were revealed during QA testing.
- Align hours and minutes line item with money
- Fix weird visual bug with `( - )` label on safari
=> YES tool — minor layout updates following QA testing

cfgov/jinja2/v1/youth_employment_success/budget-form.html, cfgov/jinja2/v1/youth_employment_success/goals.html, cfgov/jinja2/v1/youth_employment_success/index.html, cfgov/jinja2/v1/youth_employment_success/route-option-form.html, cfgov/jinja2/v1/youth_employment_success/route-options.html, cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html, cfgov/jinja2/v1/youth_employment_success/route-questions/days-per-week.html, cfgov/jinja2/v1/youth_employment_success/route-questions/driving-cost-estimate.html, cfgov/jinja2/v1/youth_employment_success/route-questions/miles.html, cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less, cfgov/unprocessed/apps/youth-employment-success/js/budget-form-view.js, cfgov/unprocessed/apps/youth-employment-success/js/todo-notification.js, cfgov/unprocessed/apps/youth-employment-success/js/util.js, cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js, test/unit_tests/apps/youth-employment-success/js/budget-form-view-spec.js, test/unit_tests/apps/youth-employment-success/js/util-spec.js, test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
Fixes issues raised in latest round of designed feedback.
- Use consistent spacing between sections `goals` and `budget` and `budget` and `transportation tool`
- Expandable now slightly wider
- All questions in transportation form are now full width columns to prevent undesirable line breaks
- `small` uses same `max-width`s as `p` elements, etc
- `small` tag forced to `14px` as browsers are calculating them slightly smaller
- Use HTML entity `8722` for minus signs to improve legibility
=> YES tool — Next design feedback pass

requirements/libraries.txt
Remove rate-checker-fees endpoint and Fee model from owning-a-home-api
1. Add ratechecker migration to remove_fee_loader
2. Add fix_fee_product_index to remove_fee_loader migration
1. Remove FeeLoader Class from loader.py
2. Delete fee from views.py and test_views.py
3. Remove FEE, TestFeeLoader, Fee model and view tests
4. Delete rate-checker-fees endpoint URL
5. Remove rate_checker_fees from view
1. Update Loader class to filter out duplicate rates in loader.py
2. Reduce load call_count from 5 to 4 in test_load_daily_data
3. Update API and README documentation
1. Running migrations:
Applying ratechecker.0002_remove_fee_loader... OK
Setting up initial data
Running script initial_data
Configuring superuser, username: admin
Configured default Wagtail Site: www.consumerfinance.gov:8000 …
=> Update owning-a-home-api to 0.12.2

cfgov/jinja2/v1/_includes/organisms/carousel.html
Follow up from #5371.
@contolini
=> Add missing space to template parentheses

cfgov/v1/models/home_page.py
Updating info unit order and minor content tweaks.
=> New home page content edits

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/unprocessed/css/organisms/carousel.less
Finally Googled enough and fiddled with the table-based layout enough to get it working in pretty much every browser, at all screensizes, I think! 🤜 🌲 
Also fixes the issue of buttons and thumbnails incorrectly appearing in IE8 no-js layout.
=> Carousel: Update layout code for cross-browser compatibility

cfgov/jinja2/v1/_includes/molecules/quote.html
Adds `aria-hidden="true"` to pull quotes template, which should repeat the body's content.
- Adds `aria-hidden="true"` to pull quotes template.
=> Add aria-hidden to pull quotes

docs/installation.md
=> Fix docker doc numbering and add a note about re-sourcing the  .env file

cfgov/unprocessed/root/data.json
Updating deprecated URLs for CCDB API polled by data.gov according to the open data API standards.
- None
- None
- Updated JSON file with new URLs for updated API documentation and download locations for CCDB.
1. Passed validation on [labs.data.gov validation site](https://labs.data.gov/dashboard/validate)
- I have updated some temporal metadata with values that I believe are accurate to mean the last time we updated our source files, but I am not 100% sure how data.gov will use each of these updates. If preferred, I can leave those as-is.
- None
=> Updated Data.gov JSON metadata for CCDB

cfgov/apache/conf.d/redirects.conf
Add redirects for broken links, that includes policy-compliance pages and the old Ask CFPB search URL
Created permanent apache redirects for the following:
/about-us/advisory-groups/ -> /about-us/advisory-committees/
/askcfpb/search/ -> /ask-cfpb/search/
/complaints/ -> /data-research/consumer-complaints/
/foia/quarterly/ -> /foia-requests/foia-electronic-reading-room/cfpb-foia-quarterly-reports/
/how-to-prepare-your-finances-for-buying-a-home/ -> /owning-a-home/process/prepare/
/owning-a-home/loan-options/FHA-loans/ -> /owning-a-home/loan-options/fha-loans/
/practitioner-resources/students/repay/ -> /paying-for-college/repay-student-debt/
/supervision/ -> /jobmanager/supervision.html
/wp-content/uploads/ - > https://s3.amazonaws.com/files.consumerfinance.gov/f
=> Added apache redirects requested in #3484

cfgov/templates/wagtailadmin/shared/page_status_tag.html
- Add `rel="noopener noreferrer"` to target blank link
=> Add `rel="noopener noreferrer"` to target blank link

cfgov/jinja2/v1/_includes/organisms/item-introduction.html
Blog posts and other pages with authors currently use "and" to combine multiple names [even if there are more than two](https://www.consumerfinance.gov/about-us/blog/small-business-lending-and-great-recession/), e.g.
By Daisy Duck and Donald Duck and Mickey Mouse
We should be consistent with how we use commas on page previews when there are more than two authors (see also recent PR #5488).
This change fixes multiple author display so it works like this:
One author: By Daisy Duck
Two authors: By Daisy Duck and Donald Duck
Three or more authors: By Daisy Duck, Donald Duck, and Mickey Mouse
Visit these pages locally to confirm things are working as expected:
- http://localhost:8000/about-us/blog/know-your-data-our-updated-reporting-companies-list/
- …
=> Fix commas for multi-author posts

cfgov/jinja2/v1/_includes/organisms/omwi-salesforce-outage-banner.html
Update the text of the OMWI outage banner to fit on two lines when the banner is displayed at full width.
- Change the text of the OMWI outage banner to fit on two lines instead of four when the banner is at full width.
1. Enable the `OMWI_SALESFORCE_OUTAGE` flag
2. Visit http://localhost:8000/about-us/diversity-and-inclusion/ and http://localhost:8000/about-us/diversity-and-inclusion/self-assessment-financial-institutions/ and make sure the outage banner at the top of those two pages matches the screenshot and fits on two lines when at full width.
=> Update OMWI outage banner

requirements/libraries.txt
To incorporate the layout fixes in cfpb/django-college-costs-comparison#30
See https://GHE/CFGOV/platform/issues/3676
- Upgrades the comparisontool requirement from 1.13.0 to 1.13.1
1. Observe broken layout on https://www.consumerfinance.gov/paying-for-college/choose-a-student-loan/
1. Pull branch
1. `pip install -r requirements/local.txt` or `docker-compose build python`
1. Load up http://localhost:8000/paying-for-college/choose-a-student-loan/ and see the layout has returned to normal.
=> Update comparisontool to 1.13.1

cfgov/unprocessed/css/organisms/carousel.less
This code accidentally slipped into https://github.com/cfpb/cfgov-refresh/pull/5483 and is test temp code that should be removed.
=> Remove erroneous temp code

travis_run.sh
=> Add linting to travis check

requirements/libraries.txt
- Update version of `django-localflavor` in `requirements/libraries.txt` from `2.2` to `3.0`
1. tox -e lint
2. tox -e unittest-current
3. tox -e unittest-future
=> Update django-localflavor to 3.0

cfgov/agreements/jinja2/agreements/index.html
We received the quarterly update to the Credit Card Agreements archive for 2019 Q4. Update the page to reflect that.
1. Running this branch, visit http://localhost:8000/credit-cards/agreements/
2. Make sure the links to the archive files for Q4 and Q3 2019 work
=> Link to new quarter of Credit Card Agreements (2019 Q4)

requirements/libraries.txt
Minor version bump to include front-end bugfixes
- None
- None
- 2.0.2 => 2.0.3
1. Same
=> Update ccdb5-ui to 2.0.3 and ntplib to 0.3.4

cfgov/apache/conf.d/redirects.conf
- Reggie 2.0 IA redirects from old locations
=> implement reggie 2.0 redirects for new IA

cfgov/alerts/newrelic_alerts.py, cfgov/ask_cfpb/views.py, cfgov/cfgov/urls.py, cfgov/regulations3k/views.py, cfgov/search/backends.py
It looks like an update to flake8 is catching more linting errors now, which is good! This fixes the new ones it's found.
=> Fix newly surfaced Python linting errors

Dockerfile
Add the label maintainer using the `tech@cfpb.gov` email address in the Dockerfile.
=> Add Label Maintainer in Dockerfile

requirements/libraries.txt
Releasing https://github.com/cfpb/teachers-digital-platform/pull/390
@Scotchester
=> [TDP] Bump TDP to version 1.4.2

cfgov/cfgov/settings/base.py
This pull request is one of three PRs required to implement a new feature.
- [CCDB Data Pipeline]()
- [CCDB UI](https://github.com/cfpb/ccdb5-ui/pull/251)
A full explanation of the feature is [here](https://github.com/cfpb/ccdb5-ui/pull/251)
=> Add new URL to whitelist

requirements/libraries.txt
Update for worksheet server errors
=> Push the comparisontool version to 1.15.1

requirements/libraries.txt
Update the CCDB5-API with the latest release to resolve an issue with aggregation filtering.
---
=> Bump for CCDB-API with bugfix

Jenkinsfile
Adding timeout to docker deploy step
=> Add timeout to Docker stack deployment in Jenkinsfile

cfgov/agreements/jinja2/agreements/index.html
This is the quarterly request from RMR to publish credit card agreements to the Bureau's online public [credit card agreement](https://www.consumerfinance.gov/credit-cards/agreements/) database. This quarter includes a disclaimer statement regarding the completeness of the data.
- Added the 2019 Q4 agreements to the list of "archived" agreements
- Added new link to 2020 Q1 agreements, along with a disclaimer and a link to the [Covid regulatory flexibility statement](https://files.consumerfinance.gov/f/documents/cfpb_data-collection-statement_covid-19_2020-03.pdf)
2. Visit http://localhost:8000/credit-cards/agreements/
3. Test that the link to "Download all most recent agreements (Q1-2020)" works and downloads a zip file
4. Test that the link to "regulatory flexibility …
=> Update Credit Card Agreements page with 2020 Q1 data

requirements/libraries.txt
Updates CCDB `requirements/libraries.txt` .whl dependency to latest codebase for master.
=> CCDB version increment to 2.1.1

requirements/libraries.txt
Increments the CCDB API .whl inclusion to ensure the latest code is deployed to cf.gov
=> CCDB API increment

cfgov/research_reports/jinja2/index.html, cfgov/unprocessed/apps/research-reports/css/main.less
See conversation on super-regular issues 85, 86, 87
=> Improve report title, subheading, and author names styles

.github/PULL_REQUEST_TEMPLATE.md
- Remove linebreaks that GH for some reason maintains in PR/issue comment fields
- Remove excessive indentation in documentation checklist item
=> Clean up new PR template

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/16-save-and-finish.html, cfgov/unprocessed/apps/paying-for-college/js/dispatchers/update-models.js, cfgov/unprocessed/apps/paying-for-college/js/util/analytics.js, cfgov/unprocessed/apps/paying-for-college/js/util/debt-calculator.js, cfgov/unprocessed/apps/paying-for-college/js/util/url-parameter-utils.js, cfgov/unprocessed/apps/paying-for-college/js/views/navigation-view.js
These are fixes to our Google Analytics tracking in Paying for College's "Financial Path to Graduation" tool.
- Fix `import` statement for Analytics code
- Change event action name
- Fix Restart button link to work as intended
1. Pull down the PR and getting the repo running.
2. Create a college-costs page in Wagtail and open it.
3. Navigate the tool. Check Google Tag Manager if possible. (The functionality was checked internally by our Analytics team.)
=> Paying for College: Analytics fixes

Jenkinsfile
As discussed today, with the stack janitor in place, we think it's time to turn on auto-deploying (not just building the image) for PR stacks.
I think this is the change that will do that? But I admit, I'm a Jenkinsfile novice.
- Updates default value of `DEPLOY` param in multibranch Jenkinsfile to `true`
1. Will the building of this PR branch actually prove the change successful?? Let's find out!
- [This repo’s docs](https://cfpb.github.io/cfgov-refresh/) (edit the files in the `/docs` folder) – for basic, close-to-the-code info on working with this repo
=> DEV Docker stacks: Always deploy PR builds

cfgov/research_reports/management/commands/parse_research_report.py
🚧  This is a Reports as Webpages PR, not going into the main branch (...yet) 🚧 
Extract some content fields from the report and save them to the Report.
=> Reports as Webpages: Parse front page content of report

cfgov/unprocessed/apps/paying-for-college/js/models/financial-model.js
Ensure that the correct cap value is used for all situations. See CFI 243 for details
- Use the unsubCap value when enforcing limits
1. Check out branch and run gulp
2. Verify unsubsidized loan caps are applied correctly:
- grad student = 20, 500
- undergrad = 5500 (less the  subsidized loan amount)
-
- CFPB/hubcap wiki on GHE – for internal …
=> Paying for College: Caps calculation fix

cfgov/jinja2/v1/_includes/organisms/sidenav-toc.html, cfgov/unprocessed/apps/research-reports/css/main.less, cfgov/unprocessed/apps/research-reports/js/index.js
PR into reports-as-webpages branch
Closes /CFPB/super-regular/issues/128
Closes GHE/CFPB/super-regular/issues/129
Just minor styling updates as described in the linked issues
=> Style current selection as black & fix ToC alignment

Dockerfile
Includes the refresh data in the final prod image for the cfgov application.
---
- refresh-data script
-
-
1. Deployed Pr's should refresh db correctly.
=> Add refresh-data to cfgov-prod image

requirements/libraries.txt
Updates to the newest version of the Retirement API. 
---
- Retirement Version 0.13.0 to 0.14.0
1.
-
=> Updating Retirement satellite app to version 0.14.0

Dockerfile, cfgov/cfgov/tests/test_urls.py, cfgov/cfgov/urls.py, cfgov/v1/tests/views/test_documents.py, cfgov/v1/views/documents.py, docker-stack.yml
Reverts cfpb/consumerfinance.gov#5923
=> Restore Document Serve View

requirements/wagtail.txt, tox.ini
Upgrades Wagtail from 2.9.3 to 2.10.1
---
- Wagtail Version
1. Run the app locally.
- 
=> Update to Wagtail 2.10.1

test/cypress/pages/admin/admin.js
Fix  makes sure entire search value is typed in search field and that document search waits long enough for results to be returned before proceeding
---
-
-
-
1.
-
=> Draftables Cypress Test Fix

cfgov/jinja2/v1/_layouts/base.html, cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py
Add remove_html_tags to preview description and check to make sure its not empty
---
-
-
-
1.
-
=> Wagtail Search Fallback Bug Fix

cfgov/apache/conf.d/redirects.conf
Addresses https://github.local/CFPB/super-regular/issues/182
(target branch is `ia-direct-apache-redirects`, to be merged on launch day)
=> Update amicus redirects to point to compliance

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/02-costs.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/05-federal-loans.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/06-school-loans.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/07-other-resources.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/09-make-a-plan.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/11-cost-of-borrowing.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/12-affording-your-loan.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/13-school-results.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/15-action-plan.html, cfgov/unprocessed/apps/paying-for-college/js/dispatchers/update-models.js, cfgov/unprocessed/apps/paying-for-college/js/models/expenses-model.js, cfgov/unprocessed/apps/paying-for-college/js/util/url-parameter-utils.js, cfgov/unprocessed/apps/paying-for-college/js/views/chart-view.js, cfgov/unprocessed/apps/paying-for-college/js/views/school-view.js
- Add other debt payments to expenses budget
- Fix expenses calculation error
- Expenses region now changes to school's region on school selection (or loading URL values)
- Update content
=> Paying for College - Financial Path updates

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/15-action-plan.html, cfgov/unprocessed/apps/paying-for-college/js/models/expenses-model.js, cfgov/unprocessed/apps/paying-for-college/js/util/url-parameter-utils.js
- Fix bug which breaks URL querystring updates
- Fix content issue
- Remove monthly loan payment from "Average Monthly Spending" on budget page
1. Pull it down and get it running!
2. Navigate to http://0.0.0.0:8000/paying-for-college/your-financial-path-to-graduation/
And you may ask yourself:
- Does going through the app update the URL querystring?
- Does the budget page no longer include 
- Is the "Action Plan" content updated properly? (See team issue 276)
- Well... how did I get here?
=> Paying for College - Bug Fixes

cfgov/jinja2/v1/_includes/molecules/archived-related-content.html
Updates related content text for archiving
- Archiving related content
2. Mark blog page as archived
3. Verify sidebar text
- Since it seems like this is subject to change, we should update it so the content is in a snippet
=> Archiving: update sidebar language

cfgov/ask_cfpb/models/search.py, cfgov/ask_cfpb/views.py, requirements/libraries.txt
We were not accounting for the desired language when returning autocomplete suggestions.
---
- Now provides the desired language to the autocomplete function, to limit our results.
1.  Search on ask-cfpb home page with terms that can match both english and spanish (like resp) and confirm you are only seeing results for your desired language.
- CFGOV/platform wiki on GHE – for internal CFPB developer …
=> Fix language specific autocomplete

test/cypress/pages/policy-compliance/regulations-search.js, test/cypress/pages/practitioner-resources/activity-search.js
- Updates paths in Cypress tests following IA refresh
1. `yarn cypress run`
=> Update Cypress URLs that have changed post-refresh

cfgov/unprocessed/root/financial-intuition.xml
Correcting EST/EDT typos
---
Not a huge priority; can roll into whatever other code release makes the most sense.
=> Update financial-intuition.xml (EDT/EST)

cfgov/unprocessed/js/routes/on-demand/table.js
- Update Table module import to fix initialization.
1. https://www.consumerfinance.gov/ask-cfpb/what-do-i-do-if-i-think-i-have-been-a-victim-of-identity-theft-en-31/ should have an init error in the dev console.
2. Pull branch and `gulp clean && gulp build` and http://localhost:8000/ask-cfpb/what-do-i-do-if-i-think-i-have-been-a-victim-of-identity-theft-en-31/ should not have an error.
=> Bugfix: Update Table module import to fix initialization

cfgov/unprocessed/apps/paying-for-college/js/models/financial-model.js, cfgov/unprocessed/apps/paying-for-college/js/models/state-model.js, cfgov/unprocessed/apps/paying-for-college/js/util/debt-calculator.js, cfgov/unprocessed/apps/paying-for-college/js/util/url-parameter-utils.js, cfgov/unprocessed/apps/paying-for-college/js/views/school-view.js
This PR will fix bugs created by misnaming of the student dependency variable.
- Fix misnaming of student dependency variables
- Fixes internal issues 338 and 339.
1. Get this branch running!
2. Make sure your total debt numbers work, and you can enter numbers in the unsubsidized loans field.
=> Paying for College - Bug Fix

cfgov/jinja2/v1/_includes/molecules/enforcement-action-metadata.html
=> Temporarily suppress new enforcement fields

cfgov/jinja2/v1/_includes/molecules/enforcement-action-metadata.html
=> Reintroduce total consumer relief to enforcement action sidebar

cfgov/v1/views/enforcement_api.py
Helpful comments for future developers.
=> Enforcement API: Developer notes

docs/caching.md
Fix broken link to a file that moved.
=> Docs: Fix broken link

cfgov/search/elasticsearch_helpers.py, cfgov/v1/tests/test_filterable_list_form.py
This commit adds a new TestCase mixin for use during tests of Elasticsearch using django-elasticsearch-dsl. By default, updates to Elasticsearch are not blocking. This can lead to some unpredictability if we do tests like this:
1. Put some data in the database
2. Index this data into Elasticsearch (e.g. by calling `manage.py search_index`)
3. Do some tests that query Elasticsearch
This is because, even though the code in step 2 may return, there's no guarantee (by default) that the Elasticsearch index has finished and will be reflected in queries.
ES does provide the ability to force this, by using [`refresh='wait_for'`](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-refresh.html), but unfortunately currently dj-es-dsl does not provide a way to specify this option …
=> Block on Elasticsearch updates during tests

cfgov/unprocessed/css/print.less
Hide search and feedback organisms when printing. Show the american flag icon in the footer.
2. Print a page (like an [ask page](http://0.0.0.0:8000/ask-cfpb/how-quickly-can-i-get-money-after-i-deposit-a-check-into-my-checking-account-what-is-a-deposit-hold-en-1023/)) that has a feedback form or search form and they should no longer exist. The American flag in the footer should now exist.
| <img width="363" alt="before" src="https://user-images.githubusercontent.com/1060248/110512864-9ae3b080-80d3-11eb-8fcc-696c205a4cc7.png">   | <img width="364" alt="after" src="https://user-images.githubusercontent.com/1060248/110512858-99b28380-80d3-11eb-8074-6bed580ae296.png">  |
-
- PR titles are used to generate the change log in …
=> Hide some things, show others, when printing

cfgov/unprocessed/js/routes/on-demand/simple-chart/chart-hooks.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/datetime-styles.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js
Continual design improvements to simple-chart to support CCPI work
=> Series labelling, quarter-based tooltip, and always enabled rangeSelector buttons

cfgov/v1/models/enforcement_action_page.py
(instead of the sometimes buggy looking value which is output from ENForce)
Closes https://github.local/CFGOV/platform/issues/4031
=> Render enforcement product display name

Jenkinsfile, docker-compose.e2e.yml
- Update Cypress to 7.0.1 on Jenkins
=> Update Cypress to 7.0.1 on Jenkins

docker/deployable-zipfile/Dockerfile
This corresponds to changes in #6387 to require Node 14.
=> Update the deployable zip file Docker container to Node 14

cfgov/agreements/jinja2/agreements/index.html
Update the [credit card agreements page](https://www.consumerfinance.gov/credit-cards/agreements/) with a link to the newest quarter of files, Q4 2020.
- Hold this PR until our approved publishing day, 4/16.
=> Credit card agreements: Add link to Q4 2020 download

Jenkinsfile
=> Disable Docker BuildKit and add Docker Hub credentials to fix image builds

cfgov/ask_cfpb/tests/test_views.py, cfgov/ask_cfpb/views.py
This change enables our Ask CFPB answer pages to be previewed on the sharing site if they're new and have never been published.
Previously, such pages would 404, because of the `answer_page.live` check. This change reorganizes the code to check for the existence of a sharing site for the request first.
=> Enable previewing of unpublished Ask answers on a Wagtail-Sharing sharing site

cfgov/jinja2/v1/_includes/organisms/expandable.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html, cfgov/unprocessed/apps/teachers-digital-platform/js/expandable-facets.js, cfgov/unprocessed/apps/teachers-digital-platform/js/expandable-mobile.js, cfgov/unprocessed/apps/teachers-digital-platform/js/index.js, cfgov/unprocessed/apps/teachers-digital-platform/js/search.js, test/unit_tests/apps/teachers-digital-platform/js/expandable-mobile-spec.js, test/unit_tests/apps/teachers-digital-platform/js/search-spec.js
* Moves logic to own module
* Adds option to the "expandable" template
* Makes the search module a better team player by not initializing itself and instead allowing the index module to do this.
=> Formalize logic into feature of the template organism

cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js
Fixes tooltip text breaking out of its container
=> Remove fixtooltip chart callback

cfgov/jinja2/v1/_layouts/base.html
- Update optimize.js snippet and move up in the document HEAD (see [google docs](https://support.google.com/optimize/answer/10106536?hl=en&ref_topic=6197443)) .
1. Will be testing after merge with analytics team.
=> Update optimize.js snippet and move up in the document HEAD

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_layouts/base.html
- Add googleoptimize.com to base.py allowlist
1. Will be tested next deploy.
=> Add googleoptimize.com to base.py allowlist

cfgov/unprocessed/css/organisms/simple-chart.less, cfgov/unprocessed/js/routes/on-demand/simple-chart/chart-hooks.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/datetime-styles.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/tilemap-styles.js
Fixes the remaining issues in https://github.local/CFPB/super-regular/issues/317
Mostly alignment and labeling adjustments.
=> Respond to ccpi feedback

cfgov/jinja2/v1/_layouts/base.html
Edits a code comment in the base template to hopefully invalidate the cache.
- Edit Google optimize code comment to reflect updates to code
=> Edit code comment to reflect updates to code

cfgov/agreements/jinja2/agreements/index.html
Add a link to the latest quarter of credit card agreements.
- This update is scheduled for publication tomorrow, 7 July.
=> Update list of credit card agreements with q1-2021 files

cfgov/teachers_digital_platform/assessment-data/results-content.csv, cfgov/teachers_digital_platform/assessments.py, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/assess/results-9-12.html, cfgov/teachers_digital_platform/resultsContent.py, cfgov/teachers_digital_platform/urlEncode.py, cfgov/teachers_digital_platform/views.py
=> Inject results page content into template

requirements/wagtail.txt
Reverts cfpb/consumerfinance.gov#6514
=> Revert "Pin Wagtail to 2.13"

cfgov/jinja2/v1/_includes/molecules/info-unit.html, cfgov/unprocessed/css/molecules/info-unit.less
- info-unit: Remove unused is_button class and associates CSS.
=> info-unit: Remove unused is_button class

.github/workflows/backend.yml, docs/python-unit-tests.md, tox.ini
Simplifying testing process and pipeline to try and avoid futher issues with missed tests, and dependency updates.
Also removes `-current` in favor for just `lint` and `unittest`
---
-
-
-
1.
-
=> Remove `-future` from tox testing and pipeline

.github/workflows/backend.yml, tox.ini
Removes dangling `-current` that we missed.
---
-
-
-
1.
-
=> Tox future removal #2

cfgov/agreements/jinja2/agreements/index.html
Our stakeholder requested that we add the regulatory flexibility statement to the latest quarter of credit card agreements.
- They would like this to go live tomorrow, 12 August, along with updates to the Q1-Q4 2020 archive files.
=> CCA: Add regulatory flexibility statement to Q1 2021 agreements

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-3-5.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-6-8.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-9-12.html, cfgov/unprocessed/apps/teachers-digital-platform/js/survey/grade-level-page.js, cfgov/unprocessed/apps/teachers-digital-platform/js/survey/result-page.js
- Can start over from the Results page
- Initials display matches design
- ES results content
- Clear session on entry to the grade-level page
=> Assorted TDP survey changes

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-3-5.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-6-8.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-9-12.html
- ES results: remove download attribute
- MS and HS results page content
=> More TDP survey changes

cfgov/unprocessed/apps/teachers-digital-platform/css/pages/survey.less
=> [WIP] TDP surveys focus

cfgov/unprocessed/apps/teachers-digital-platform/css/pages/survey-results.less
=> [WIP] Expand print styles, add label print for mobile

cfgov/teachers_digital_platform/tests/test_resultsContent.py
Improving coverage of TDP python code
---
Added unit tests for 
- resultsContent.py
- TBD
1. In your python container run `tox -e lint -e unittest -e coverage teachers_digital_platform`
=> [WIP] Tdp surveys python unit tests

cfgov/teachers_digital_platform/tests/test_UrlEncoder.py, cfgov/teachers_digital_platform/tests/test_resultsContent.py
Bring UrlEncoder.py and resultsContent.py to 100% test coverage
=> Tdp surveys python unit tests

cfgov/housing_counselor/jinja2/housing_counselor/index.html
Updates the intro paragraph (and adds a second intro paragraph) per this document: 
[Find a housing counselor - final.docx](https://github.com/cfpb/consumerfinance.gov/files/7188441/Find.a.housing.counselor.-.final.docx)
Visually tested in the following supported …
=> Update to opening paragraph (INTAKE-4927)

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/form-page.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/grade-level-3-5.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/grade-level-6-8.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/grade-level-9-12.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-3-5.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-6-8.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-9-12.html, cfgov/unprocessed/apps/teachers-digital-platform/js/tdp-analytics.js, cfgov/unprocessed/js/modules/Analytics.js, test/unit_tests/apps/teachers-digital-platform/html/grade-level-page-analytics.js, test/unit_tests/apps/teachers-digital-platform/html/results-page-analytics.js, test/unit_tests/apps/teachers-digital-platform/html/results-page.js, test/unit_tests/apps/teachers-digital-platform/html/survey-page-analytics.js, test/unit_tests/apps/teachers-digital-platform/html/survey-page.js, test/unit_tests/apps/teachers-digital-platform/js/survey/grade-level-page-analytics-spec.js, test/unit_tests/apps/teachers-digital-platform/js/survey/results-page-analytics-spec.js, test/unit_tests/apps/teachers-digital-platform/js/survey/shared-results-page-analytics-spec.js, test/unit_tests/apps/teachers-digital-platform/js/survey/survey-page-analytics-spec.js
- minor test clean, eliminating errors 
- Ignore for coverage testing-related code
- No need to test for markup we know exists
- unneeded code
- Add more analytics testing
=> [TDP survey] Additions to analytics testing

cfgov/privacy/forms.py
Fix some Checkmarx findings on the Privacy Forms feature that got merged on Friday. Also clean up some duplicated code.
1. Make sure no functionality changed from #6759 
- I'm still planning to write more tests, but this was higher priority.
=> Fix Checkmarx errors

cfgov/unprocessed/root/data.json
Adds information about our post-2017 HMDA data sets to `data.json` so it will be picked up by data.gov.
---
- Post-2017 HMDA data sets to `data.json`
1. Take a look at the new data set entry to make sure it makes sense (the [DCAT-US](https://resources.data.gov/resources/dcat-us/) schema docs have good explanations on all the fields)
2. Make sure `data.json` is valid JSON in your favorite JSON validator
3. Make sure the info in `data.json` is valid DCAT-US 1.1 in the [Project Open Data validator](https://labs.data.gov/dashboard/validate)
- I need to check with the data team on a couple of open questions about the info before this PR is fully ready for a review (answers in *italics*):
- Do we want to add more distributions? Right now only the snapshot national loan-level dataset is in …
=> Add post-2017 HMDA data to data catalog

cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js
Previously this was hardcoded, now it's automatically detected.
=> support multiple short_code formats

babel.config.js
The patch is from a babel [issue](https://github.com/babel/babel/issues/12731#issuecomment-819158117)
=> add sourceType param to babel config

cfgov/agreements/jinja2/agreements/index.html
Quarterly update to the Credit Card Agreements Database to add Q3 2021.
- Add a link to download the Q3 2021 credit card agreements archive .zip file.
- To be deployed tomorrow, December 7.
=> Credit card agreements: Update for Q3 2021

cfgov/jinja2/v1/_layouts/base.html, cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html, cfgov/paying_for_college/jinja2/paying-for-college/disclosure_technote.html
Chrome struggles to keep track of the absolutely positioned megamenu
unless a minimum scale value is provided for the user's viewport. I'm
unsure why this is and additional testing needs to be done to ensure
there are no accessibility implications.
See https://stackoverflow.com/a/44680066
- Add `minimum-scale=1` to viewport meta element.
1. Try the steps in the below gif on production.
2. Try the same steps w/ the PR preview link.
Here's a gif of the bug on production:
-
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` …
=> Add minimum viewport scale to fix mobile Chrome mega menu bug

Jenkinsfile
Also fixes a bug that prevented updated es images from being pushed to dockerhub
=> Update jenkinsfile es_image_tag to match dockerfile

cfgov/unprocessed/js/routes/on-demand/simple-chart/chart-hooks.js
Addresses https://github.local/CFGOV/platform/issues/4293
=> Fixes bug in enforcement relief formatter

docs/index.md, docs/installation.md
Two minor corrections to our public documentation.
- We've updated from python 3.6 to 3.8. Update the Introduction section to reflect that.
- We've updated the `./refresh-data.sh` script to automatically re-index ElasticSearch. Update the Installation section with that info.
- CFPB/hubcap wiki on GHE – for internal CFPB design and content …
=> Documentation corrections

cfgov/v1/jinja2/v1/home_page/_hardcoded_en.html
See recent edits from https://github.local/CFPB/el-camino/issues/558; minor text updates to new homepage for testing
---
- Modified hardcoded homepage content
1. Run `./frontend.sh`
2. Visit http://localhost:8000/?home_page_2021=True&home_page_2021_minimal=True
- …
=> Edit new homepage hero and highlights text

.git-blame-ignore-revs
Add the squash merge commit from black to main as an ignore git blame ignored commit.
=> Add black squash merge to main commit

test/cypress/integration/consumer-tools/before-you-claim/before-you-claim.js
Trying the before each command to force the page to open before clicking on links.
---
-Using before each command to force a page load before trying the other commands
-
1.this PR will test if the changes don't break the PR functional test but this PR won't fix the Jenkins Staging portion of the test till after it is merged.
-
- …
=> Before you claim test fix

.pre-commit-config.yaml
Update `.pre-commit-config.yaml` to use black `22.3.0`
=> Bump black to 22.3.0

cfgov/jinja2/v1/_layouts/base.html
Fixes https://github.local/CFGOV/platform/issues/4387
=> Fixes the too-fancy no-js code to work in ie11

cfgov/unprocessed/root/code.json
This technology is no longer used
=> trim pdf-reactor reference

cfgov/search/elasticsearch_helpers.py
There is currently a bug related to the moving of pages: when a filterable page is moved within the Wagtail page tree, it is deleted from its old location but not reindexed at its new location.
This causes problems e.g. when an event page is moved from the list of future events to the list of past events; it fails to show up in its new location because it is not being reindexed.
This happens because the django-elasticsearch-dsl index is configured to [index models that are of type AbstractFilterPage](https://github.com/cfpb/consumerfinance.gov/blob/bc3e2164b6758e4cca7af76af8985ae05e6ffdd1/cfgov/v1/documents.py#L99), but Wagtail page signals can be called with instances of the base Page class, for example [when a page is moved](https://github.com/wagtail/wagtail/blob/ed6365ac0ff97505acdc876 …
=> Fix: Update Elasticsearch when pages are moved

requirements/wagtail.txt
=> Bump Wagtail to 2.15.5

esbuild/scripts.js
This page was left out of the build in error.
=> Build pfc disclosures page

cfgov/agreements/jinja2/agreements/index.html
Link to the .zip download for the latest quarter of credit card agreements, Q4-2021. 
- One new entry in the CCA archive page.
- This is scheduled to go live today or tomorrow. When this change is deployed, I'll also run the automation that expands the individual agreement PDFs into their storage locations.
- CFPB/hubcap wiki on GHE – for …
=> Credit card agreements: Add Q4-2021 link

test/cypress/integration/data-research/credit-card-agreements-search/credit-card-agreements-search-helpers.js, test/cypress/integration/data-research/credit-card-agreements-search/credit-card-agreements-search.js
Credit card agreement tests were failing because test data was different than production data. Made the selection process more generalized to help the tests to not rely on specific site data or formatting.
- Addition of one method to retrieve issuer
- Generalized issuer selection process
1. Make sure functional tests pass
=> made credit card agreement tests more robust

cfgov/unprocessed/js/routes/on-demand/simple-chart/utils.js
Big numbers are missing commas in simple chart tooltips. Using
toLocaleString() will format the tooltip's value for the user's
locale (using commas, periods, whatever is appropriate).
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
1. `yarn build` and try hovering over a chart showing values in billions.
- CFGOV/platform wiki on GHE – for internal …
=> Format simple chart tooltip values for the user's locale

cfgov/unprocessed/css/on-demand/simple-chart.less
@ielerol requested a faster transition when clicking on the legend icons and this PR resolves that
=> Implemented faster transition on simple-chart legend

cfgov/unprocessed/js/routes/on-demand/simple-chart/chart-hooks.js
- Added a new cct hook to account for age data shape
=> Add new cct hook for different data shape

cfgov/v1/jinja2/v1/home_page/_hardcoded_en.html
This PR modifies the homepage content per a request from Public Affairs to replace the link to "junk fees" with a link to our story page on small business lending.
---
- A comment in the code of `_hardcoded_en.html` to note a character limit that can be implemented when this page is converted to a proper editable Wagtail page type.
- Homepage content changes
1. localhost
2. Check homepage to ensure that content renders properly per `_hardcoded_en.html`
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, …
=> Change to homepage featured link

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/index.html, cfgov/unprocessed/apps/filing-instruction-guide/css/main.less, esbuild/styles.js
Increases the size of all FIG headings to improve the usability of long
pages and renames/relocates the app's stylesheet to emphasize that it is
specific to FIGs.
See https://github.local/CFPB/1071-data-collection/issues/120
1. Pull down branch
2. `yarn styles` should run a-okay
3. Visit a local FIG page and all the headings should be bigger
- CFGOV/platform wiki on GHE – for internal CFPB developer …
=> Increase size of FIG headings, move FIG stylesheet

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/index.html, cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/section.html, cfgov/unprocessed/apps/filing-instruction-guide/css/main.less
Adds a CSS class for each FIG section type to make them easy to target
and cleans up the HTML markup. Also adds a horizontal rule above level 3
subsections and adjusts some padding.
See https://github.local/CFPB/1071-data-collection/issues/120
2. `yarn styles`
3. Visit a local FIG page and things should look nearly identical but there will be some horizontal lines and info unit groups shouldn't have any mysterious scrollbars.
- More improvements are on their way.
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in …
=> Add FIG section CSS classes, simplify template markup

.dockerignore, .github/workflows/publish_cfgov.yml
Made slight modifications to the `.dockerignore` file, due to suspecting that it is the culprit behind certain files and directories not being pushed to the images created and stored in GHCR.
=> Make dockerignore changes

cfgov/cfgov/urls.py
Closes https://github.com/cfpb/consumerfinance.gov/issues/7197
=> Remove unnecessary oah redirect (already covered in wagtail)

cfgov/v1/jinja2/v1/home_page/_hardcoded_en.html
This homepage content is hardcoded and thus this change requires a PR. This content change has been approved to go live ASAP. The link will point to [this page](https://www.consumerfinance.gov/about-us/events/save-the-date-cfpb-field-hearing-with-director-chopra-on-nursing-home-debt-collection-practices/).
=> Update homepage content for field hearing today

cfgov/v1/jinja2/v1/home_page/_hardcoded_en.html
This reverts commit bc1964c0fcc2156c1add90f88e8024c3403e4f4a.
The hearing has passed and so we can revert back to the former content.
=> Revert "Update homepage content for field hearing today (#7227)"

helm/cfgov/Chart.yaml, helm/cfgov/values.yaml
This changes `archive-wagtail-events` cronJob to `@daily`.
=> Set Archive Events to @daily

cfgov/unprocessed/apps/teachers-digital-platform/js/modals.js, cfgov/unprocessed/apps/teachers-digital-platform/js/survey/result-page.js, cfgov/unprocessed/apps/teachers-digital-platform/js/tdp-analytics.js, test/unit_tests/apps/teachers-digital-platform/js/expandable-mobile-spec.js
- Remove unused arguments and variables from TDP assets.
1. TDP should work as before. Tests should pass.
=> Fix TDP linter errors

cfgov/unprocessed/apps/paying-for-college/js/college-costs/dispatchers/get-model-values.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/dispatchers/update-models.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/models/constants-model.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/models/expenses-model.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/models/financial-model.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/models/school-model.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/models/state-model.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/util/debt-calculator.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/util/number-utils.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/util/other-utils.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/views/financial-view.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/views/navigation-view.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/views/school-view.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/dispatchers/get-api-values.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/index.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/models/expenses-model.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/models/school-model.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/utils/Analytics.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/utils/handle-string-input.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/utils/query-handler.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/financial-view.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/links-view.js
- Fix jsdoc typos
- Remove unused imports, variables, and arguments.
- Convert hasOwnProperty syntax to satisfy no-prototype-builtins eslint rule.
1. PfC should work the same.
=> Fix Paying for College JS linter errors

cfgov/unprocessed/apps/paying-for-college/js/college-costs/views/chart-view.js
- Remove unused `text` variable that is created but not referenced.
=> PfC: Remove unused `text` variable

test/unit_tests/apps/teachers-digital-platform/js/obfuscation-spec.js
- TDP: Update obfuscation-spec.js to import methods individually
1. PR checks should pass. `yarn test` should pass.
=> TDP: Update obfuscation-spec.js to import methods individually

esbuild/scripts.js
Fix Wagtatil typo in code comment
=> Fix Wagtatil typo in code comment

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/data_points.html, test/cypress/integration/compliance/small-business-lending/filing-instruction-guide-helpers.cy.js, test/cypress/integration/compliance/small-business-lending/filing-instruction-guide.cy.js
Fixes a bug that causes some data field table rows to not have enough columns.
Currently, some tables look like this (values 1, 2 and 4 have no third cell):
```
| Valid values | Codes                  | Instructions                |
|--------------|------------------------|-----------------------------|
| 1            | Code 1 - Some thing    |
| 2            | Code 2 - Another thing |
| 3            | Code 3 - Cool thing    | Do not enter more than once |
| 4            | Code 4 - Neat thing    |
```
This PR ensures they all have the same number of cells as the header row:
```
| Valid values | Codes                  | Instructions                |
|--------------|------------------------|-----------------------------|
| 1            | Code 1 - Some thing    | …
```
=> Ensure FIG data field table rows have correct number of columns

cfgov/mega_menu/blocks.py, cfgov/mega_menu/tests/test_frontend_conversion.py, requirements/wagtail.txt, test/cypress/integration/admin/admin-helpers.cy.js
(Note: this PR is against an upgrade/wagtail branch, not against main.)
This PR bumps the version of Wagtail from 2.15.5 to 2.16.3.
=> Bump Wagtail version to 2.16.3

cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/pages/external-site.less, cfgov/unprocessed/js/routes/external-site.js
More code simplification, less built into main.less
=> Remove external-site less, inlining a single style

cfgov/unprocessed/apps/filing-instruction-guide/js/fig-search.js
Standardizes the FIG analytics naming conventions and uses functions from our internal analytics module.
- Tracks FIG events based on names recommended by DA team.
- Imports methods from our [`analytics-gtm`](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/apps/analytics-gtm/js/util/analytics-util.js) app instead of reinventing the wheel.
1. PR checks pass.
1. You can use [dataslayer](https://github.com/sean-adams/dataslayer) to check GTM's data layer.
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the …
=> Update FIG analytics to use new names and cf.gov utils

.env_SAMPLE
See three commits:
1. Remove unused DEMO_PAGE environment variable.
2. Remove unused EXTERNAL_LINK_CSS environment variable.
3. Remove unused GovDelivery environment variables.
=> Cleanup .env_SAMPLE

cfgov/housing_counselor/jinja2/housing_counselor/index.html
- Removed outdated PRA
Before:
After:
=> Find a housing counselor: Remove outdated PRA

cfgov/v1/jinja2/v1/home_page/home_page.html
This PR makes changes to some content on the CF.gov homepage per a request from the Office of Public Affairs.
---
- Content hard-coded on `home_page.html`
1. localhost
2. view the homepage at /
3. confirm that changes render properly vs. www.cf.gov
=> Content changes to homepage

cfgov/jinja2/govdelivery-subscribe/success/index.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/macros/financial-item-expandable.html, cfgov/unprocessed/js/molecules/Notification.js
- Migrate `check` icon to canonical `approved` icon.
=> Migrate `check` icon to canonical `approved` icon

.github/workflows/backend.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/filter-backend.yml, .github/workflows/filter-frontend.yml, .github/workflows/frontend.yml, .github/workflows/functional-tests.yml, .github/workflows/helm_lint.yml, .github/workflows/publish_cfgov.yml, esbuild/scripts.js, esbuild/styles.js
Hey it takes forever to get a bunch of PRs merged. Let's add a queue! 🇬🇧 
- Add merge queue CI settings
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
=> Add merge queue CI settings

cfgov/retirement_api/jinja2/retirement_api/claiming-es.html, cfgov/retirement_api/jinja2/retirement_api/claiming.html
If the template has a newline after the icon and the next character is a comma or a period, there will be a space between the icon and the comma or period.
- Retirement: remove space between icons and commas or periods.
1. Visit http://localhost:8000/consumer-tools/retirement/before-you-claim/ and http://localhost:8000/consumer-tools/retirement/before-you-claim/es/ and fill out the age and income. Expand the middle bottom tip and see that there is no period between the icons and the periods or commas. 
Before:
After:
=> Retirement: remove space between icons and commas or periods

cfgov/unprocessed/apps/retirement/js/views/graph-view.js, cfgov/unprocessed/apps/retirement/js/wizards/fetch-api-data.js
Closes #7390
Testing:
- navigate to http://localhost:8000/consumer-tools/retirement/before-you-claim/
- `Get your estimates` should still work
=> Switch before-you-claim to use fetch instead of jquery ajax

requirements/wagtail.txt
(This PR is against the upgrade/wagtail4 branch.)
This commit upgrades the version of Wagtail to 4.1.4:
https://docs.wagtail.org/en/stable/releases/4.1.4.html
=> Upgrade Wagtail from 4.1.3 to 4.1.4

cfgov/unprocessed/css/organisms/secondary-nav.less
Perform adjustments to the secondary navigation so that it aligns correctly on arabic pages.
- RTL secondary nav
1. Visit layout-1-3 pages in english and arabic and ensure the secondary nav looks correct across mobile and desktop
e.g.
http://localhost:8000/language/ar/coronavirus/mortgage-and-housing-assistance/help-for-homeowners/avoid-foreclosure/
http://localhost:8000/enforcement/payments-harmed-consumers/
=> RTL secondary nav

cfgov/unprocessed/css/molecules/social-media.less, cfgov/unprocessed/css/organisms/video-player.less
Review suggestions to social-media.less
Differences to production are:
- Existing spacing between icons is 11px. This updates it to 10px for consistency.
- Existing spacing between icons and label is ~5px when it stacks. This updates it to 10px.
- Existing share component does not wrap on https://www.consumerfinance.gov/owning-a-home/explore-rates/, whereas it wraps in this PR. I think it's preferable to wrap.
LTR 
Blog heading area, video player, footer
http://localhost:8000/about-us/blog/addressing-racial-inequities-consumer-finance-markets/
"share & print" at bottom
http://localhost:8000/consumer-tools/educator-tools/resources-for-older-adults/financial-security-as-you-age/planning-for-diminished-capacity-and-illness/
"share this"
http://localhost:8000/credit-cards/agreements/ …
=> Review suggestions to social-media.less

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
These filters don't do what they were written to do (and are actually a huge antipattern)
=> Fixup tdp template to remove unneeded filters

cfgov/jinja2/rural-or-underserved/index.html
See https://[GHE]/CFGOV/platform/issues/4326
- Update list of related links on rural or underserved tools.
1. Compare related links in http://localhost:8000/rural-or-underserved-tool/ vs https://www.consumerfinance.gov/rural-or-underserved-tool/
Before:
After:
=> ROUT: Update related links

cfgov/paying_for_college/models/disclosures.py
Update best practice for tests from https://www.flake8rules.com/rules/E721.html
- Fix ruff linting error
1. `tox -e lint` should pass.
=> Fix ruff linting error

cfgov/v1/jinja2/v1/home_page/home_page.html, cfgov/v1/util/ref.py
This PR makes minor changes to `home_page.html` to reflect updated Bureau statistics.
---
- Minor text tweaks within `home_page.html`
1. View homepage on localhost
=> Homepage update, August 2023

cfgov/unprocessed/apps/financial-well-being/css/main.less
- Financial Well-Being: Replace hardcoded hex values with color variables.
- Financial Well-Being: Replace hardcoded ems with unit helper.
1. Refer to https://cfpb.github.io/design-system/foundation/color to see that the hex values align with their color codes.
2. `yarn build` should pass.
3. http://localhost:8000/consumer-tools/financial-well-being/ should be unchanged in regard to the colors and font sizes.
=> Financial Well-Being: Replace hardcoded hex values with color variables | Replace hardcoded ems with unit helper

cfgov/jinja2/know-before-you-owe/index.html
The hard-coded page `/know-before-you-owe` currently has links to two guides that are no longer available on the site, leading to 404s. This PR removes the info units that link to these guides entirely.
---
- Info unit items including 404 links
1. localhost
2. Compare `know-before-you-owe` to production site
Before:
After:
- This page can and should ultimately be brought into Wagtail rather than hard-coded. I have an in-progress version of such a page in the content database; if we can get it approved, expect a new PR soon to remove this page entirely.
- [This repo’s …
=> Removing 404 guide links

cfgov/jinja2/know-before-you-owe/timeline/index.html
This PR removes one 404 and corrects several other links on `/know-before-you-owe/timeline/` so that they do not rely on internal redirects.
1. localhost
2. `/know-before-you-owe/timeline/`
=> Fixing links on Know Before You Owe timeline page

cfgov/v1/jinja2/v1/home_page/home_page.html
This PR updates the "The CFPB is standing up for you" subsection of the homepage to reflect the latest numbers and information.
1. localhost
2. review homepage (/)
=> Homepage updates (11/15/2023)

requirements/libraries.txt
This reverts commit e4af342692227ec2ae2c80ed25d42e81569a08ad in PR #8034.
This didn't fix our issue. See for more context:
https://github.com/cfpb/consumerfinance.gov/pull/8034#issuecomment-1832632076
=> Revert "Pin Pillow to 10.1.0 to make Snyk happy"

cfgov/paying_for_college/views.py
Code scans picked up unsanitized values in the /verify process. 
We have value verification code in the view, so we just need to use it for PID, OID and IPED (school ID) values.
- PFC tests pass and EFIP code runs locally
- Front end not affected
=> Verify all values passed by the Dynamic Disclosures /verify endpoint

cfgov/v1/models/learn_page.py
This PR modifies the "Structured Data" field, a field on the Configuration tab that is rarely used and requires technical expertise but which is very large and imposing, so that it is collapsed by default.
---
- Added classname "collapsed" to Structured Data FieldPanel
1. localhost
2. Check the Configuration tab of any page editor
- …
=> Collapse Structured Data field by default

cfgov/data_research/jinja2/data_research/mortgage-performance-downloads.html
=> Update MPT download language

requirements/docs.txt, requirements/libraries.txt
Changelog https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-3
- Update `Jinja2` from `3.1.2` to `3.1.3`
=> Update `Jinja2` to `3.1.3`

cfgov/wellbeing/jinja2/wellbeing/home.html
Adds a reference to `apps/financial-well-being/css/main.css` to the Financial Well-Being `home.html` template
- As described above, adds stylesheet to template
Busted:
After this PR:
-
=> Fix Financial Well-Being stylesheet

cfgov/unprocessed/css/on-demand/simple-chart.less, cfgov/unprocessed/js/routes/on-demand/simple-chart/common-styles.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/datetime-styles.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/tilemap-styles.js
=> Tweak responsive layout to stop projected clipping

cfgov/tccp/jinja2/tccp/landing_page.html
The alignment issue is caused by a missing opening `p` tag.
1. The link should now be properly centered at all screen sizes.
=> Fix TCCP paragraph alignment bug

cfgov/tccp/situations.py
Remove some editorializing that was added in #8172. Real situation content will be added in future.
=> TCCP: Minor update to situation text

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/situations.py, cfgov/tccp/tests/test_situations.py, cfgov/tccp/tests/test_views.py
- Change "Card" to "Credit card" in table
- Change "Have a lower monthly payment" to "Pay less interest"
=> TCCP: Minor text changes

cfgov/paying_for_college/jinja2/paying-for-college/disclosure_technote.html, cfgov/tccp/jinja2/tccp/card.html
- Move disclosure technote to layout-2-1 template.
- Minor update to TCCP to use single quotes for layout-2-1 template reference (to align with use elsewhere).
1. http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/about-this-tool/ is unchanged across screen sizes.
=> PfC: Move disclosure technote to layout-2-1 template

cfgov/unprocessed/apps/tccp/css/main.less
See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/253#issuecomment-351180
=> Change color of TCCP progress indicator

cfgov/tccp/jinja2/tccp/card.html
Add rewards, services, and card features to the card details page.
---
- Rewards
- Services
- Card features
As usual, lots of variations you can test out.
- [Cash back](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/united-bank-visa-platinum/)
- [Travel + other](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/university-bank-visa-credit-card/)
- [All three](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/td-bank-na-td-first-class/)
- [No rewards](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/truist-bank-truist-future-card/)
- [Only standard services](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/bank-of-tampa-the-minaret-visa-black-relationship-banking/)
- [Standard + other …
=> TCCP: Add rewards and perks to card details page

cfgov/tccp/jinja2/tccp/card.html
Add grace period, minimum finance charge, and balance computation method to the TCCP card details page. Note that this is mostly just to get the data on the page for usability testing—I fully recognize that these three things need a ton of plain language work to make them understandable to consumers. We'll do that after we see how people are understanding the card details during testing.
---
- Grace period
- Minimum finance charge
- Balance computation method
Same as always, lots of variations you can take a look at:
- [25 days](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/interra-credit-union-standard-mastercard/)
- [None](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/credit-human-federal-credit-union-rate-preferred-mastercard/)
- …
=> TCCP: Add fine print to card details page

cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/unprocessed/apps/tccp/css/main.less
Minor update to TCCP landing page.
To test, run a local server and visit
http://localhost:8000/consumer-tools/credit-cards/explore-cards/
=> TCCP: Landing page content update

cfgov/tccp/jinja2/tccp/includes/filter_form.html, cfgov/unprocessed/apps/tccp/css/main.less
=> Align nested TCCP bullet points

cfgov/tccp/jinja2/tccp/situations/results/build-credit.html
Adds placeholder results content for the "build credit" scenario.
To test, run a local server and visit:
http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/?credit_tier=Credit+scores+from+620+to+719&location=NY&situations=Build+credit
=> TCCP: Placeholder "build credit" results content

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/jinja2/tccp/includes/fields.html, cfgov/unprocessed/apps/tccp/css/main.less, test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js
This is a total redesign of the initial, very basic TCCP card details page. This is not the final code for this page! Consider this a prototype that we'll use for review and usability testing. While those are happening, we're planning to go back and refactor much of this code (see notes section below for some specifics). In other words, probably not worth too detailed of a code review at this point—once we refactor this, it'll be in much better shape for a thorough review.
---
- Total redesign of the card details page
1. Visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/ and look at the details of some cards.
2. There are a million variations and outliers (maybe even some we still have to handle), but for now, the details page for any card you look at should look …
=> TCCP: Redesign card details page

cfgov/v1/apps.py
We no longer need this code, per FEWDs.
=> Remove obsolete staticfiles override code

cfgov/data_research/jinja2/data_research/mortgage-performance-downloads.html
=> Update CT note

cfgov/tccp/jinja2/tccp/about.html, cfgov/tccp/tests/test_views.py, cfgov/tccp/urls.py, cfgov/tccp/views.py
See internal https://github.local//Design-Development/Design-Thinking-and-User-Research/issues/288 for context.
To test, run a local server and visit:
http://localhost:8000/consumer-tools/credit-cards/explore-cards/about/
See also page live on internal https://dev4.local/consumer-tools/credit-cards/explore-cards/about/.
=> TCCP: Add "About this tool" page

cfgov/tccp/jinja2/tccp/situations/select/make-a-big-purchase.html
Found more relevant Ask question
=> Update make a big purchase link

cfgov/tccp/jinja2/tccp/card.html, test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js
Update the content of the TCCP card details page based on stakeholder review. See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/272 for the full list of content changes.
---
- Various content changes
1. Check some card detail pages and make sure the changes show up as in the screenshot below.
- There are a few functionality changes to the card details page that aren't implemented here; we'll do those in a subsequent PR.
- Once all the content changes are done, we're also planning to refactor this page to simplify the Jinja and move complex logic to the back end as much as possible
- Consider prefixing, e.g., "Mega Menu: fix layout bug", or …
=> TCCP: Update card details content

cfgov/tccp/jinja2/tccp/landing_page.html
Update "Credit card companies are required..." link to point to About this tool page
=> Update link to consumer friendly About this tool page

cfgov/jinja2/owning-a-home/explore-rates/index.html, cfgov/unprocessed/apps/owning-a-home/css/brand-header.less, cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less
- Update `page-intro_col`, `page-intro_cols`, `page-intro_col-right`, `page-intro_col-left` to `page-intro__col`, `page-intro__cols`, `page-intro__col-right`, `page-intro__col-left`.
- Update `m-notification__borderless` to `m-notification--borderless`.
- Update `brand-header__1-2-container-with-icon` to `brand-header__1-2-container--with-icon`
1. PR checks should pass. Rate explorer should be unchanged.
=> BAH: update BEM

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/14-summary.html, cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html, cfgov/unprocessed/apps/paying-for-college/css/college-costs/financial-item.less, cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/financial-view.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/metric-view.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/question-view.js, test/unit_tests/apps/paying-for-college/disclosures/fixtures/overview.js
- PfC: Fix some incorrect BEM classes.
1. Disclosures tools should work as expected.
=> PfC: Fix incorrect BEM

cfgov/v1/jinja2/v1/includes/molecules/feature-card.html, cfgov/v1/jinja2/v1/includes/organisms/feature-cards.html
#8274 seems like it swapped the contents of these two files around. This change switches them back.
1. Visit http://localhost:8000/ask-cfpb on `main`. Observe the lack of feature cards
2. Checkout this branch, then refresh, and observe the feature cards have returned.
=> Fix feature cards by swapping files around

cfgov/ask_cfpb/jinja2/ask-cfpb/see-all.html, cfgov/v1/jinja2/v1/landing-page/index.html
See for yourself at http://localhost:8000/es/herramientas-del-consumidor/cobro-de-deudas/respuestas/lo-basico/
Before:
After:
=> Add translation links to portal search pages in the see-all.html template

cfgov/v1/jinja2/v1/home_page/home_page.html
This PR updates one of the hard-coded numbers in the "The CFPB is standing up for you" subsection of the homepage HTML.
---
1. localhost
2. View `/`
=> Homepage: Minor edit to update statistic

cfgov/retirement_api/es_urls.py, cfgov/scripts/http_smoke_test.py
=> Smoke test the new retirement spanish url

cfgov/unprocessed/apps/filing-instruction-guide/js/fig-sidenav.js
@anselmbradford noticed this in https://github.com/cfpb/consumerfinance.gov/pull/8458#pullrequestreview-2102969980
=> Handle case where span is clicked

requirements/scripts.txt, requirements/wagtail.txt
1. Bump Wagtail from 6.0.2 to 6.0.5, fixing https://github.com/cfpb/consumerfinance.gov/security/dependabot/94.
2. Bump Requests from 2.31.0 to 2.32.0, fixing https://github.com/cfpb/consumerfinance.gov/security/dependabot/93.
Addresses internal https://github.local/CFGOV/platform/issues/4572.
=> Fix dependabot backend issues

cfgov/unprocessed/apps/paying-for-college/css/college-costs/state-based.less, cfgov/unprocessed/apps/paying-for-college/js/college-costs.jsx, cfgov/unprocessed/apps/paying-for-college/js/college-costs/util/analytics.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/views/chart-view.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/views/navigation-view.js
Fixed errors flagged by `yarn lint`.
- PfC: Linter fixes
1. Paying for College app should work as before.
=> PfC: Linter fixes

cfgov/unprocessed/root/data.json
College Banking Agreements
Tuition Payment Plans
Costs of Electronic Payments in K-12 Schools
College Banking Agreements
Tuition Payment Plans
Costs of Electronic Payments in K-12 Schools
Consumer Complaint Database
Financial Wellbeing in America (2017)
Home Mortgage Disclosure Act (HMDA) Public Data from 2007-2017
Credit Card Agreements Database
College Credit Card Marketing Agreements Data
HMDA Public Data (Starting in 2017)]
Prepaid Product Agreements Database
Terms of Credit Card Plans (TCCP) Survey
=> Added a dataset and updated a title

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/02-school-costs.html, cfgov/unprocessed/apps/paying-for-college/css/college-costs/state-based.less, cfgov/unprocessed/apps/paying-for-college/js/college-costs/dispatchers/update-models.js
This pull request will add a notification for schools marked as "under investigation" in the College Scorecard data.
- Add content and flag for schools under investigation
1. Pull up this version and check a school which is currently under investigation by Dept of Ed to see if the notification appears.
=> P4C - Schools under investigation

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/02-school-costs.html
Follow up to https://github.com/cfpb/consumerfinance.gov/pull/8535
This makes the link point to the intended URL
=> Add correct key to notification link

docs/installation.md
To be fair, it is a *little* fun.
=> Fix installation docs typo

cfgov/unprocessed/apps/filing-instruction-guide/css/main.scss, cfgov/unprocessed/apps/paying-for-college/css/cf-enhancements.scss, cfgov/unprocessed/apps/paying-for-college/css/college-costs/financial-item.scss, cfgov/unprocessed/apps/paying-for-college/css/disclosures.scss, cfgov/unprocessed/apps/prepaid-agreements/css/main.scss, cfgov/unprocessed/apps/regulations3k/css/reg-search.scss, cfgov/unprocessed/css/molecules/social-media.scss, cfgov/unprocessed/css/organisms/post-preview.scss, cfgov/unprocessed/css/organisms/secondary-nav.scss
This is mostly so I can find these in the future and hopefully handle the overrides differently.
- Add code comments for places we're overriding the heading mixins.
=> Organize heading overrides comments

cfgov/unprocessed/apps/ccdb-search/package.json, cfgov/unprocessed/apps/ccdb-search/yarn.lock
This fixes:
- Data issue in line chart when toggling back and forth between Area Chart and Stacked Area Chart
- Color contrast in buttons is improved
- Charts resize correctly when browser window is resized
-
-
-
1. Pull code down
2. run code
3. Confirm buttons appear lighter than what is on production now
4. Go to line chart in Trends view
5. Count the date periods that appear
6. Toggle between Area and Line chart and confirm that we are not losing date periods when we swap the charts
7.  Resize the browser window width
8. Confirm that the charts are actually resizing to fit the page
https://github.com/user-attachments/assets/e8de4e76-10ac-4a64-bd2b-a15f0601dac2
-
- Consider …
=> Update CCDB to latest, fix chart issues

cfgov/unprocessed/apps/tccp/js/index.js
Here's a sampling of the objects being pushed:
=> Push tccp filter analytics to the datalayer

cfgov/unprocessed/apps/ccdb-search/package.json, cfgov/unprocessed/apps/ccdb-search/yarn.lock
Please refer to https://github.com/cfpb/ccdb5-ui/releases/tag/v2.13.2 for full changelog
- Updates to CFPB Design System 3.2.2
- Convert to redux stores to Redux Toolkit
- Bug fixes
-
-
1. go to dev2 and review the site
=> Update CCDB to latest

cfgov/unprocessed/apps/analytics-gtm/js/tab-navigation-tracking.js, cfgov/unprocessed/apps/cfpb-chart-builder/js/utils/session-storage.js, cfgov/unprocessed/apps/regulations3k/js/search.js, cfgov/unprocessed/apps/teachers-digital-platform/js/search.js, cfgov/unprocessed/js/modules/util/web-storage-proxy.js, cfgov/unprocessed/js/organisms/FormSubmit.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js
- Remove `(err)` from catch blocks that don't use `exceptionVar`.
- Combine utils imports in SimpleChart.
=> Minor JS cleanup

cfgov/v1/jinja2/v1/includes/organisms/chart.html
=> Add information to chart source

cfgov/unprocessed/js/routes/on-demand/simple-chart/tilemap-chart.js
As per stakeholder. Makes reading negative values a bit nicer.
=> Update tilemap legend

cfgov/tccp/jinja2/tccp/about.html, cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/tccp/views.py
Update TCCP with cleared content
---
- Content on landing and about pages
1. Check `/consumer-tools/credit-cards/explore-cards/` and `/consumer-tools/credit-cards/explore-cards/about/` to make sure the updated content looks OK.
- We discovered a hero bug that vertically centers the hero text when the text is short enough to not run the full width of the container. We're working on a fix for that separately in the Design System, so you can ignore the misaligned hero for now.
=> TCCP: Update content

cfgov/v1/jinja2/v1/home_page/home_page.html
This PR updates statistics displayed on the (hard-coded) home page.
---
1. localhost
2. View `/` and compare to live website
=> Home page statistic updates (December 3, 2024)

cfgov/jinja2/rural-or-underserved/index.html
Adds label text so Axe is happy. This is a kinda funny construction with a "real" file input overlaying a false button input, which is why I had to add the visually hidden span.
=> Add label test to rout file label

cfgov/searchgov/forms.py, cfgov/searchgov/test/test_views.py, cfgov/searchgov/views.py
=> Encode queries before sending them to search.gov

cfgov/retirement_api/utils/ss_update_stats.py, cfgov/retirement_api/utils/ss_utilities.py
The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
Run tests.
Check the current browser support cutoff …
=> Modernize logger interface

cfgov/searchgov/jinja2/searchgov/index.html
per https://github.local/Design-Development/External-Products/issues/662
=> Remove search page language switcher per research

test/cypress/integration/components/header/header.cy.js, test/cypress/integration/paying-for-college/your-financial-path-to-graduation/url-params.cy.js
- Lint files.
1. PR checks should.
=> Fix linting errors

cfgov/agreements/management/commands/import_agreements.py, cfgov/agreements/tests/test_management.py
This change makes the `import_agreements` management command's `--path` argument take either a URL or a local file path. If it's a URL, it will fetch the file from that URL to a temporary location, then import agreements from that temporary location, and remove the temporary files when done.
I've also followed the suggestion of a comment while I'm here, and replaced the use of an `AGREEMENTS_S3_UPLOAD_ENABLED` environment variable with a command-line switch instead. This change will require a change to our automations that I'll have open momentarily, but I think that can be merged asynchronously to this since this is a manually run command.
=> Allow import_agreements management command to take a URL

requirements/libraries.txt
Release notes: https://github.com/cfpb/wagtail-sharing/releases/tag/2.14
=> Update wagtail-sharing version from 2.13 to 2.14

requirements/deployment_container.txt
This adds New Relic to our container image requirements.
=> Add New Relic to container requirements
