.flake8
cfgov/cfgov/tests/test_urls.py
cfgov/cfgov/urls.py
picard_scripts/akamai_flush.sh
picard_scripts/picard_data_export.sh
picard_scripts/picard_synonyms_export.sh

This change removes some unused scripts and references to the now-deprecated Picard repository, which was removed in https://github.com/cfpb/cfgov-refresh/pull/3110.
- Removes defunct `picard_scripts` directory.
- Removes all references to `/picard` URLs.
Check [public GH usage](https://github.com/search?q=user%3Acfpb+picard&type=Code&utf8=%E2%9C%93) of Picard to see these aren't used anywhere, and also search on GHE to see similarly that these are deprecated.

Cleanup unused Picard files/references

---

cfgov/legacy/templates/front/base_update.html

A visual "flicker" was occurring when a Google Optimize A/B was turned on for our retirement "Before You Claim" tool. These changes will serve as a temporary fix for the duration of the experiment.
- A `style` and `script` tag were added to `base_update.html`
You can test this PR by pulling it in and making sure nothing changes on any pages that use `base_update.html`. Ideally, nothing should happen on any of these pages, although you may notice the page appears all at once.
Once the experiment starts (after this PR is merged), we will further verify that the new code is seamless on the live site.

Fix for "flicker" in retirement due to Google Optimize

---

test/unit_tests/js/modules/BreakpointHandler-spec.js

- Remove breakpoint tests related to testing IE8 JS code that is no longer applicable.
1. `gulp test:unit`

Remove tests that check IE8 JS

---

test/unit_tests/apps/financial-well-being/js/fwb-questions-spec.js
test/unit_tests/apps/financial-well-being/js/fwb-results-spec.js

`window.tagManagerIsLoaded` doesn't appear to be checked, but instead `window.google_tag_manager` is checked https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/js/modules/Analytics.js#L38
- Changes mocked variable `window.tagManagerIsLoaded` to `window['google_tag_manager']`.
1. `gulp test:unit --specs=apps/financial-well-being/js/fwb-results-spec.js` and `gulp test:unit --specs=apps/financial-well-being/js/fwb-questions-spec.js` fails on master, but pass on this PR.

Changes analytics variable in fwb tests

---

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html

This is a correction to #3856 that added a link to `/consumer-tools/fraud` from the mega menu. Instead of being "Frauds & Scams" it should have been "Fraud & Scams". See GHE#2524 for details.

Fix megamenu typo: should be "Fraud" not "Frauds"

---

cfgov/jinja2/v1/_includes/molecules/related-posts.html

The current logic in the Related Posts template is using the built-in Wagtail
[`slugurl`](http://docs.wagtail.io/en/v2.0/topics/writing_templates.html#slugurl) template tag, which returns an undetermined link if there are multiple pages with the same slug anywhere in the site.
This change fixes GHE#2533 which was generating an incorrect link due to two pages having the same slug. It instead uses the built-in `page.url` property which returns the best URL for the page.
- Use `page.url` instead of `slugurl(page.slug)` in related posts template.
To test, use a production dump and visit http://localhost:8000/data-research/ and observe that the "2018 CFPB Research Conference" link properly points to an event page, not the conference landing page.
1. Note that due to the current way we have our …

Fix related posts URLs for duplicate slugs

---

gulp/tasks/scripts.js
gulp/tasks/watch.js
gulp/utils/handle-errors.js

Modifying code to fail build or error
- Modified scripts to fail build on error.
1. Modify a js file within the `unprocessed` directory to cause a build error.
2. Run`frontend.sh` and verify that the build fails.
3. Modify a less file within the `unprocessed` directory to cause a build error.
4. Run`frontend.sh` and verify that the build fails.
5. Run `gulp watch` and cause an error as requested above.
6. Verify the watch process is still active.
-  I removed the images watch command.
-  The watch doesn't always catch files changes.
-

Modifying code to fail build on script error

---

test/unit_tests/apps/owning-a-home/js/explore-rates/dom-values-spec.js
test/unit_tests/apps/owning-a-home/js/explore-rates/params-spec.js

Moves code out of rate-explorer script for handling rate explorer parameters and DOM lookup interaction.
- Removes chai from dom-value test.
- Adds check for undefined value to increase code coverage to 100% for dom-value test.
1. `gulp test:unit:scripts --specs=apps/owning-a-home/js/explore-rates/`

owning-a-home/explore-rates/ params tests

---

cfgov/unprocessed/apps/owning-a-home/js/explore-rates/index.js

- Group 3rd party dependencies together at the top of OAH rate checker index file.
- Remove relative path to 3rd party modules. 
- Turn modules `var` to `const`.

Group and simplify dependency calls

---

docs/testing-fe.md

- Outdated `gulp test:a11y` was still in the docs. Updated to `gulp audit:a11y`.
- Docs showed using globs for unit testing. A directory path just needs to be supplied without the glob.

Updates testing fewd docs test and audit commands

---

cfgov/v1/models/base.py

Feedback export was failing due to an unhandled Unicode character in the output.
- Adds encoding for the referrer URL, which may contain a unicode checkbox.
1. Go to your local admin in the feedback: http://localhost:8000/django-admin/v1/feedback/
1. Select all rows.
1. Click "Select all 87233 feedbacks" in the table header area
1. Select the export option in the drop down and click "Go".
You should get a message that a CSV file has been sent and not a 500 error.
- In the python3 future, we'll be able to specify the coding for the csv writer instead.

Handle unicode characters in feedback output when exporting

---

cfgov/unprocessed/js/routes/ask-cfpb/single.js

- Removes unused `categorySlug` variable from ask-cfpb.

Remove unused variable from ask-cfpb

---

test/unit_tests/apps/owning-a-home/js/dropdown-utils-spec.js

- Add test for owning-a-home/js/dropdown-utils
1. `gulp test:unit --specs=apps/owning-a-home/js/dropdown-utils-spec.js` should pass and show 100% coverage for dropdown-utils.

Adds owning-a-home/dropdown-utils test

---

gulp/tasks/test.js
jest.config.js

- Utilize `coveragePathIgnorePatterns` regex in Jest config, instead of negated globs in `collectCoverageFrom`.
- Remove `process.env.NODE_ENV = 'test'` call in gulp unit test task (needed independent of https://github.com/cfpb/cfgov-refresh/pull/3874)
1. `gulp test:unit`
2. View coverage from `test/unit_test_coverage/lcov-report/index.html` and see that js/routes isn't included.
- JS in the routes scripts should **only** call methods on other modules, if it's not doing so that code should be moved to a tested module outside of the routes directory.

Ignore routes JS in test coverage

---

jest.config.js

- Adjust Jest coverage regex to exclude webpack-config.js.
1. `gulp test:unit` should not include coverage for apps/owning-a-home/webpack-config.js

Ignore webpack-config in code coverage

---

cfgov/unprocessed/apps/owning-a-home/js/explore-rates/index.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/template-loader.js
cfgov/unprocessed/apps/owning-a-home/templates/explore-rates/chart-tooltip-multiple.hbs
cfgov/unprocessed/apps/owning-a-home/templates/explore-rates/credit-alert.hbs
cfgov/unprocessed/apps/owning-a-home/templates/explore-rates/down-payment-warning.hbs
cfgov/unprocessed/apps/owning-a-home/templates/explore-rates/fail-alert.hbs
cfgov/unprocessed/apps/owning-a-home/templates/explore-rates/result-alert.hbs
gulp/config.js
gulp/tasks/test.js
jest.config.js
test/unit_tests/apps/owning-a-home/js/explore-rates/template-loader-spec.js
test/util/preprocessor-handlebars.js

- Moves handlebar templates from rate-checker to their own module and adds unit tests.
- Edits handlebar templates to adjust long line lengths and fix errors like `</text>` and missing `</p`>.
1. `gulp test:unit --specs=apps/owning-a-home/js/explore-rates/template-loader-spec.js` should pass.

Adds template-loader

---

cfgov/unprocessed/js/modules/util/atomic-helpers.js
test/unit_tests/js/modules/util/atomic-helpers-spec.js

- Adds unit test for atomic-helper instantiateAll  method.
- Makes atomic-helper test reference o-footer instead of o-expandable, since that's less likely to move to CF.
1. `gulp test:unit --specs=js/modules/util/atomic-helpers-spec.js` should pass.
2. `gulp build` should pass.

Add missing coverage for atomic-helpers

---

requirements/local.txt
requirements/test.txt
requirements/travis.txt
tox.ini

Currently when running backend tests via `tox`, in the default mode, we recreate the `tox` virtualenv each time. This is necessary because we otherwise cannot guarantee that we'll have the correct dependencies installed. It's a known issue with `tox` -- see https://github.com/tox-dev/tox/issues/149
In that thread you can read that a `tox` contributor recommends a solution involving [venv-update](http://venv-update.readthedocs.io/en/master/), and also provides [a tox plugin](https://github.com/tox-dev/tox-pip-extensions) to make it easy -- and this is what we're attempting to adopt here. When using this plugin, `tox` will now use `venv-update` and `pip-faster` to ensure that the virtualenv is synced with our requirements, but will do so without having to recreate the virtualenv from …

Use venv-update/pip-faster with tox to avoid recreating virtualenv

---

test/browser_tests/cucumber/step_definitions/webpack-build.js

Fix for `webpack-build` feature regex
- Modified `test/browser_tests/cucumber/step_definitions/webpack-build.js` feature to fix issue with regex.

Fix for webpack-build feature regex

---

cfgov/cfgov/settings/base.py
cfgov/v1/tests/test_links.py

The current logic that applies the download icon (class="cf-icon-download") to certain links only works if the link file extension is all lowercase. For example, "foo.pdf" will get the icon but "foo.PDF" will not.
The list of extensions that triggers the download icon is defined in `settings.DOWNLOAD_LINK_PATTERN`. This change adds case insensitivity `(?i)` to the regular expression that matches against links, so that all files with the specified extensions get the icon.
This change fixes platform#788.
- Add case insensitivity to download link pattern by modifying regex to be
`r'(?i)(\.pdf|\.doc|\.docx|\.xls|\.xlsx|\.csv|\.zip)$'`.
See the new unit test that validates this behavior. Additionally, using a production dump you can visit
[this …

Apply download icon to links regardless of case

---

cfgov/jinja2/v1/_layouts/base-common.html
cfgov/jinja2/v1/_layouts/base.html
cfgov/jinja2/v1/es/es-base.html

IE9 script removal changes added in https://github.com/cfpb/cfgov-refresh/pull/3693/files were overridden with the old template when `base-common.html` was added. This re-adds the removal of IE9-specific coding.

Re-remove ie9-specific checks

---

cfgov/unprocessed/apps/owning-a-home/config.json

Fix for rate checker API urls
-  Modified code to fix issue with rate checker urls `cfgov/unprocessed/apps/owning-a-home/config.json`.

Fix for OAH rate-checker API urls

---

cfgov/unprocessed/apps/owning-a-home/config.json

Fix for OAH API url
- Modified `cfgov/unprocessed/apps/owning-a-home/config.json` to fix issue with url.

Fix for OAH API url

---

test/unit_tests/js/modules/util/email-popup-helpers-spec.js

- Changes tests that rely on run-speed to use `toBeCloseTo` instead of `toBe`
1. `gulp test:unit --specs=js/modules/util/email-popup-helpers-spec.js` should pass.

Adjusts tests to be approximate

---

test/unit_tests/js/modules/util/email-popup-helpers-spec.js

Compared values are timestamps that were divided by 100 so toBeCloseTo can be used to make them less brittle since we only care if they are way off. Default for toBeCloseTo is to use two decimal places, so the timestamps actually need to be divided by 10000 to create four decimal places that'll drop the last two digits. (Alternately, the signature of `toBeCloseTo` could be passed `0` as the second parameter, but this allows us to keep the default behavior.)
- Increase decimal range to make toBeCloseTo less brittle
1. `gulp test:unit --specs=js/modules/util/email-popup-helpers-spec.js`

Increase decimal range to make toBeCloseTo less brittle

---

cfgov/cfgov/settings/test.py
docs/testing-be.md
tox.ini

The Python unit tests in this project use a SQLite database. It would be useful to support alternate databases, for example for testing test compatibility with Postgres.
This change allows users to define the `DATABASE_URL` environment variable to test against different databases, for example:
```sh
$ DATABASE_URL=postgres://user@localhost/cfgov tox -e fast
```
This makes use of the [dj-database-url](https://github.com/kennethreitz/dj-database-url) library.
I've updated the manual to describe this change:
Note that in future it might be interesting or desirable to consider simplifying our DB configuration so that we always use a database URL. For example, tox could pass in different URLs for testing instead of having numerous settings files with different DBs. I considered this but …

Support DATABASE_URL to customize test database

---

gulp/tasks/lint.js
gulp/tasks/test.js
package-lock.json

Removing warning messages when running ESLint  on Travis
- Modified code to only display ESLint errors on Travis, not warnings.
1. Run `gulp lint --travis` and verify that you see no warnings.
2. Run `gulp lint` and verify that warnings appear.
3. Check the Travis console log and verify you see no linter warnings.
-
-

Removing warning messages when running ESLint on Travis

---

gulp/tasks/test.js

Moving Jest code comment to proper location

Moving Jest code comment to proper location

---

cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html
cfgov/jinja2/v1/_includes/templates/streamfield-sidefoot.html

It is unclear what the original intention of this code was, but currently it breaks if you hit this block more than once (which would happen if you have two or more empty related posts blocks) by causing the error `maximum recursion depth exceeded in cmp`
See discussion in GHE/platform/issues/2576
UPDATE: I haven't been able to figure out what `loop()` is supposed to be doing -- there's no real jinja documentation on it, and when I play around with it locally, it seems to expect a Wagtail block-like object (if I pass in an array or dictionary, it complains that it doesn't have the attribute 'block', 'meta', or 'value'). 
I also found this same logic in [`sidebar-breakout.html`](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html#L97) …

Fix empty related posts bug 

---

cfgov/ask_cfpb/search_indexes.py

Redirected pages need to be left in the "live" state so that they can
redirect themselves if an editor sets up a redirect. But their live status
left their related question open to being indexed, which allowed
the redirected answer to show up in search results.
This adjusts the query used to create the elasticsearch index so that
answers for redirected pages are excluded.
Since we index answer objects, and we need to consult the related pages
to determine whether they are redirected, the query is relatively
expensive. But that's not an issue here, because the query only runs
once at index time, and that is once a day.
I confirmed locally that answer 1535, which is currently the first
result for the query "spouse credit card debt," disappears from search
after re-indexing with this new …

Ask CFPB: Exclude redirected pages from index

---

cfgov/jinja2/v1/owning-a-home/explore-rates/index.html
cfgov/unprocessed/apps/owning-a-home/css/tab.less
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/index.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/tab.js
test/unit_tests/apps/owning-a-home/js/explore-rates/tab-spec.js

- Removes jquery from OAH rate checker tabs.
- Adds ~~100%~~ 95.24% test coverage for OAH rate checker tabs code.
2. http://localhost:8000/owning-a-home/explore-rates/ and interact with the tabs half-way down the page.
3. `gulp test:unit` should pass.
- There will be a flash of both tab content showing before the JS runs. In this case it doesn't matter because the tabs are below the page fold, but it could be bothersome in another context. However, here I think it's worthwhile to remove the js CSS that's needed to prevent the flash.
- These tabs should be re-written in the markup so that when JS is disabled the tab link text is laid out immediately above its contents (this is existing behavior):

Removes jQuery from OAH tabs and adds coverage

---

requirements/optional-public.txt

Simplified release and wheel name. Verified that it can be pip-installed and has assets.

bump TDP release

---

cfgov/v1/migrations/0103_update_resource_order_help_text.py
cfgov/v1/models/snippets.py
cfgov/v1/tests/models/test_snippets.py

These tests promise functionality that is specific to MySQL.  With our impending move to PostgreSQL, the behavior in these two tests will no longer be the case (sorting NULLs first).
However, we don't actually rely on this ordering anywhere, so we can just remove the tests and not promise this behavior.
See platform issue 2569 for discussion on this. 
Note that the migration is because we updated the help text on the `order` field.

Remove tests that rely on how NULLs are sorted 

---

.travis.yml

Fix for caching `apps/analytics-gtm` code on Travis
- Modified `.travis.yml` to fix issue caching code on Travis
1. View the log on Travis and verify that the directory is being cached.

Fix for caching apps/analytics-gtm code on Travis

---

cfgov/unprocessed/js/modules/VideoPlayer.js

Fix for Video Player images not loading
- Visit `https://www.consumerfinance.gov/about-us/careers/application-process/` and notice that the video player images are not loading'
1. Visit `https://www.consumerfinance.gov/about-us/careers/application-process/` and notice that the youtube max res image is loading.
2. Visit `http://localhost:8000/about-us/events/archive-past-events/public-event-student-loan-servicing-raleigh-nc/` and verify that the youtube max res image is loading.

Fix for Video Player images not loading

---

cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js

Modifying rate-checker code to use import statements
- Modifying `rate-checker.js` code to use import statements. 
1.  Run `gulp clean && gulp build`
2.  Visit `http://localhost:8000/owning-a-home/explore-rates/` and ensure the tools works as expected.
3. Check the console for errors.

Modifying rate-checker code to use import statements

---

tox.ini

The tox `fast` and `slow` environments should get the `PASSENV` directive from the `unittest` environment, so that you can do something like
```sh
$ DATABASE_URL=postgres://user@localhost/cfgov tox -e fast
```
It looks like the tox refactor in #3894 broke this functionality which was introduced in #3910.
Try the above command line with a local Postgres database.

Properly pass env to tox slow/fast

---

cfgov/core/static/robots.txt

We've had a lot of robot traffic to eRegulations recently. We'd like to avoid web crawlers crawling all the different versions of regulations and all the possible links within eRegs. This should be a relatively temporary thing until Regulations 3000 launches or we come up with something that's a little less ham-handed.
See GHE/CFGOV/platform/issues/2645 for further discussion.

Disallow robots for /eregulations

---

cfgov/jobmanager/tests/models/test_panels.py

This commit modifies some of the jobmanager app's unit tests so that they properly rollback the DB changes that are made during tests. Instead of inheriting from `unittest.TestCase`, these tests need to inherit from `django.test.TestCase` so that the database changes happen in a transaction.
This fixes the usage of these tests when running against a Postgres DB, as described in platform#2619.
This can be verified by running, e.g.:
```sh
$  DATABASE_URL=postgres://user@localhost/cfgov tox -e fast jobmanager.tests
```
(This requires the fix to the Tox config in #3954.)
This PR also fixes a tiny bug (which may not have been causing the failures) around not properly calling the parent `setUpClass`.
- Fix jobmanager unit tests.
Use command line above to run tests against a Postgres DB, and …

Fix jobmanager unit tests DB usage

---

cfgov/unprocessed/apps/analytics-gtm/js/bah-check-rates-listeners.js
cfgov/unprocessed/apps/analytics-gtm/js/bah-closing-disclosure-listeners.js
cfgov/unprocessed/apps/analytics-gtm/js/bah-loan-estimate-listeners.js
cfgov/unprocessed/apps/analytics-gtm/js/enterprise-attribution-cookies.js
cfgov/unprocessed/apps/analytics-gtm/js/enterprise-hash-url-listener.js
cfgov/unprocessed/apps/analytics-gtm/js/event-listener-scroll-tracking.js
cfgov/unprocessed/apps/analytics-gtm/js/hdma-explore-event-listeners.js
cfgov/unprocessed/apps/analytics-gtm/js/pfc-comparison-tool-listeners.js
cfgov/unprocessed/apps/analytics-gtm/js/retirement-before-you-claim-listeners.js
cfgov/unprocessed/apps/analytics-gtm/js/util/analytics-util.js
cfgov/unprocessed/apps/analytics-gtm/js/youtube-event-listeners-older-style.js
test/unit_tests/apps/analytics-gtm/js/util/analytics-util-spec.js

There is lots of redundant utility code in the analytics scripts. This moves some of that functionality to a utility module. It also makes it so that the console logs in the scripts only show up when the `debug-gtm=true` query string appears in the URL. 
The `track` utility script can likely be consolidated with `Analytics.js` in the future (which should perhaps move into the `analytics-gtm` app?
- Add `analytics-util.js` and initial test spec.
- Moves `delay` and `track` functions to the utility script.
- Adds helper function to check that an element exists before adding an event listener.
- Renames `bottom` variable `bottomPos` to fix New Relic error.
- Makes script that push to the dataLayer utilize the `track` function.
To see that the logging function works, add this to `common.js` …

Adds analytics util script

---

docs/testing-fe.md
gulp/tasks/test.js
package-lock.json
package.json
test/browser_tests/conf.js
test/browser_tests/cucumber/features/suites/default/pagination.feature
tox.ini

Acceptance tests updates part deux
- Adds `protractor-retry` to retry test failures.
- Modifies `tox.ini` to add the ability to recreate the acceptance testing env when running gulp.
1. Run `gulp test:acceptance` and ensure it works.
2. Run `gulp test:acceptance` --recreate and ensure it recreates the virtual environment.
-
-

Acceptance tests updates part deux

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

The Journey sources page is still being migrated to Wagtail, so this adds a flagged route to temporarily serve the Sheer version.
- Flag & flagged route for sources page
1. Turn on `OAH_JOURNEY_SHEER_SOURCE_PAGE` flag and verify that Sheer version of sources page is served.

BAH: Temporarily serve Sheer journey sources page

---

cfgov/scripts/tests/test_unpublish_closed_jobs.py

Fix order dependency in jobmanager test mock side effect
- Update jobmanager tests
1. Run tests against Postgres database and verify that they don't error

Fix issue in jobmanager tests

---

frontend.sh

This change modifies the frontend.sh script so that instead of only warning if a version of Node besides 8 is being used, it fails.
This behavior was originally introduced as a failure in #3177 but then removed in #3178 due to Jenkins version incompatibility. Jenkins is now properly using Node 8 so this can be changed back to a failure.
If a user isn't using Node 8, there's no point in continuing the script, as the build will fail.
1. `nvm use 6 && ./frontend.sh` - should fail.
1. `nvm use 8 && ./frontend.sh` - should work.

Fail frontend.sh script if not using Node 8

---

cfgov/unprocessed/apps/analytics-gtm/js/event-listener-scroll-tracking.js

Scroll tracking analytics had some deprecated code https://stackoverflow.com/questions/19635188/why-is-body-scrolltop-deprecated
It also could be condensed to reuse code via helper functions.
Additionally, it tracked total page height instead of a percentage of hidden page height, which would be the area that scrolls.
- Consolidated code to allow function to track any percentage of page scrolling area.
- Changes reporting to show number of seconds since page load, not since start of scrolling.
2. Visit http://localhost:8000/about-us/blog/?debug-gtm=true and check the dev console and scroll.
Start of scroll is not currently reported. Should it be, @kelleyholden ?

Updates scroll tracking analytics

---

cfgov/ask_cfpb/tests/models/test_pages.py
cfgov/ask_cfpb/tests/test_hooks.py

This change fixes two `ask_cfpb` Python unit tests that were failing when being run against a Postgres database. In both cases this seems to be due to differences in how predictable model IDs are when generated by Model Mommy - when using SQLite this seems to reliably start at 1 but with Postgres that isn't predictable.
At a high level these tests were failing because they were testing an assumed model ID instead of explicitly setting it in the test.
@richaagarwal and I paired on this; we broke up `AnswerModelTestCase.test_facet_map` into three smaller tests that more explicitly test a single piece of functionality and rely less on common setup being done in the test case `setUp`.
To validate these changes against a local Postgres DB:
```sh
$ DATABASE_URL=postgres://user@localhost/db tox …
```

Make ask_cfpb tests compatible with PostgreSQL

---

.env_SAMPLE
.travis.yml
docs/testing-be.md

As a followup to #3894, the use of the `py27` environment for tox is now deprecated and so references to it should be removed. The invocation of just plain `tox` now aliases to both `lint-py27` and the equivalent `unittest-py27-dj18-wag110-slow` environment.
- Removed outdated references to `py27` tox environment.
- Developers should remove `TOXENV` if they have it set in their existing `.env` file, unless they want to take the opportunity to set it to `fast`.

Cleanup references to TOXENV env variable

---

cfgov/jinja2/v1/_includes/molecules/social-media.html
cfgov/jinja2/v1/owning-a-home/_templates/social-media.html
cfgov/jinja2/v1/owning-a-home/closing-disclosure/closing-disclosure-1-data.html
cfgov/jinja2/v1/owning-a-home/closing-disclosure/closing-disclosure-2-data.html
cfgov/jinja2/v1/owning-a-home/closing-disclosure/closing-disclosure-4-data.html
cfgov/jinja2/v1/owning-a-home/explore-rates/index.html
cfgov/jinja2/v1/owning-a-home/loan-estimate/loan-estimate-1-data.html
cfgov/jinja2/v1/owning-a-home/loan-estimate/loan-estimate-2-data.html
cfgov/jinja2/v1/owning-a-home/loan-estimate/loan-estimate-3-data.html
cfgov/legacy/templates/hud/housing_counselor_pdf_selfcontained.html
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js

Addresses security issue in [GHE]/CFGOV/platform/issues/2522
- Adds `rel="noopener noreferrer"` to "_blank" href targets.
- Fixes issue in social media molecule where "_blank" was not quoted.
1. Ensure `OAH_FORM_EXPLAINERS` flag is true.
2. Visit /owning-a-home/loan-estimate/ (e.g.) and inspect the links in the right-hand sidebar that open in a new window and see that they have `rel="noopener noreferrer" in the link.

owning-a-home: Adds rel="noopener noreferrer" to targets

---

requirements/optional-public.txt

Manually brought in .cf-icon-svg styles to fix collectstatic breakage.
- Update TDP version to 0.2.1

Bump TDP release version to 0.2.1

---

cfgov/unprocessed/apps/analytics-gtm/js/bah-closing-disclosure-listeners.js
cfgov/unprocessed/apps/analytics-gtm/js/event-listener-scroll-tracking.js

Whooops! Due to sloppy copy pasting, bah-closing-disclosure-listeners.js ended up containing a copy of bah-check-rates-listeners.js!
- Update to correct missing bah-closing-disclosure-listeners.js file contents.
- Update scroll tracking analytics to capture 25% and 75%.

Analytics fixes

---

cfgov/unprocessed/apps/know-before-you-owe/js/kbyo-timeline.json

- Adds rel="noopener noreferrer" to "_blank" href targets.
- Converts tabs to spaces in kbyo timeline json.
2. Links in http://localhost:8000/know-before-you-owe timeline should work. (e.g. `Prototype A` link in e.g. http://localhost:8000/know-before-you-owe/#5 should work and have `rel=` attribute on the link.)

Converts tabs and adds noopener noreferrer to kbyo timeline

---

requirements/libraries.txt

This change removes a deprecated dependency on [simplejson==3.8.2](https://pypi.python.org/pypi/simplejson/3.8.2).
There's one remaining reference to this library in the optional [cfpb/retirement](https://github.com/cfpb/retirement) app; however that reference is only used as a fallback when `json` is not defined. That was added in Python 2.6 and this repository requires Python 2.7, so that fallback is no longer needed. Additionally that code [only exists](
https://github.com/cfpb/retirement/blob/46f0610392fd94fcf52e87cf83275c63f75e55c7/browser_testing/features/environment.py#L17) as part of some browser testing code.
This library was used in various other libraries which are no longer part of cfgov-refresh ([see search
here](https://pypi.python.org/pypi/simplejson/3.8.2)).

Remove deprecated simplejson requirement

---

requirements/libraries.txt

This change removes a deprecated dependency on [pbr==1.9.1](https://pypi.python.org/pypi/pbr/1.9.1).
This library was previously required by our django-sheerlike and publish_eccu packages, but those are no longer used by cfgov-refresh.
A [further search](https://github.com/search?utf8=%E2%9C%93&q=user%3Acfpb+pbr&type=Code) of CFPB code shows no other dependencies in any active satellite apps.

Remove deprecated PBR requirement

---

.travis.yml
travis_run.sh

See platform issue 2618.  As part of our work in preparation for migrating to PostgreSQL, we want to start running our unit tests regularly against a Postgres database. 
I modified `.travis.yml` according to set-up instructions [here](https://docs.travis-ci.com/user/database-setup/#PostgreSQL) as well as modified our `travis_run.sh` script to pass the Postgres `DATABASE_URL` (introduced in https://github.com/cfpb/cfgov-refresh/pull/3910) into `tox -e fast`.  
I tested this without the changes to `.travis.yml` and it still passed, so I'm not actually sure the config there is doing anything -- or perhaps it runs its default version of psql.  
However, I also tested this on a commit that I expected to fail and it did, so I think this is overall working. See …

Run Travis unit tests against Postgres DB

---

cfgov/unprocessed/js/organisms/MegaMenuMobile.js

Fixes [GHE]/CFGOV/platform/issues/2470
- Scroll page to the top of the page when navigating to a submenu in the mega menu.
1. Visit consumerfinance.gov on iOS 11
2. Navigate to About Us > Careers. **Be sure to scroll down on the About Us 2nd-level menu**
3. Note third-level menu is not showing.
4. Hit "X" button.
5. Repeat steps 1 through 4 on this branch and note menu is not missing.
Before:
After:
- This jumps to the top of the page on clicks of the submenu. Since this is immediately before sliding to the right there may be jump apparent as the page goes to the top, but it didn't strike me as bothersome. cc @schaferjh

Scroll to top of page when in submenu

---

gulp/tasks/watch.js

- Removes unused parameter and simplifies event functions to be arrow functions.
1. `gulp watch`
2. Edit a source JS file and see that the Terminal reports the file you changed was changed.
3. Edit a source CSS file and see that the Terminal reports the file you changed was changed.

Simplify gulp watch syntax

---

cfgov/legacy/templates/hud/housing_counselor.html

- Adds missing closing span tag to website field in find-a-housing-counselor.
1. There shouldn't be warnings in IE11 for "unmatched end tag" for /find-a-housing-counselor/?zipcode=05201 or similar.

Bugfix: Adds missing closing span in housing counselor

---

package-lock.json
package.json

- Updates autoprefixer to 8.x ([changelog](https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md#82-ad-astra-per-aspera))
- Updates gulp-modernizr-build ([changes](https://github.com/madlandproject/gulp-modernizr-build/commit/296ecae43d9363eb15c72618c2ba48edb7452f22))

Updates autoprefixer to 8 and gulp-modernizr-build to 0.0.6

---

.gitignore
cfgov/cfgov/settings/base.py
cfgov/core/jinja2tags.py
cfgov/core/templatetags/svg_icon.py
cfgov/core/tests/staticfiles/icons/invalid.svg
cfgov/core/tests/staticfiles/icons/test.svg
cfgov/core/tests/templatetags/test_svg_icon.py
cfgov/core/tests/test_jinja2tags.py

This change adds a new `svg_icon` template tag for both Django and Jinja templates, that allows users to render the contents of a static SVG file in their templates.
Usage in Django templates is like this:
```html
{% load svg_icon %}
{% svg_icon "test" %}
```
And in Jinja templates like this:
```html
{{ svg_icon("test") }}
```
(This requires the filter to be added to the environment in the `settings.TEMPLATES` Jinja engine.)
In both cases the tag will look for a file named `icons/test.svg` in the regular Django staticfiles search path.
This PR is intended to implement some groundwork to enable the use of Capital Framework icons as in #3887.
See new unit tests that demonstrate the use of this template tag. This PR does not include any uses of this tag in any existing website templates.

Add new svg_icon template tag to render SVG icons

---

cfgov/core/tests/testutils/test_mock_staticfiles.py
cfgov/core/testutils/mock_staticfiles.py

This change introduces a new helper class for use in Python unit tests:
`core.testutils.mock_staticfiles.MockStaticfilesFinder`
This finder can be added to the list of Django staticfiles finders [in the `STATICFILES_FINDERS` setting](https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-STATICFILES_FINDERS).
This class gives you the ability to mock the existence of static files for test purposes even if those files to not exist in the repository at test time. Generally this is useful when some other process (e.g. the frontend build) will be generating those files, and we don't want to make the backend tests dependent on that process. In particular this PR is being introduced to support the work in #3887 to add Capital Framework icons to this repository.
See the documentation and …

Add ability to mock static files in tests

---

cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/util.js
test/unit_tests/apps/owning-a-home/js/explore-rates/util-spec.js

- Move isVisible and checkIfZero to utils
1. `gulp build` should pass and entering zero for the house price on http://localhost:8000/owning-a-home/explore-rates/ should produce an error dialog on the chart.
2. `gulp test:unit` should pass.

owing-a-home/rate-checker: Move isVisible and checkIfZero to utils

---

cfgov/unprocessed/apps/analytics-gtm/webpack-config.js

Polyfilled scripts are throwing errors in Chrome and perhaps other browsers. This turns off the polyfilling so we can address the root cause of why they're necessary at all.
- Turns off polyfilling in analytics scripts.

Turn off polyfilling in analytics

---

cfgov/cfgov/settings/base.py
cfgov/jinja2/v1/_layouts/base.html
cfgov/unprocessed/js/routes/on-demand/turbolinks.js
package-lock.json
package.json

Turbolinks speeds up page loads by fetching and caching content. Is it a good idea? Who knows. We've been experimenting with it on eRegs and it might be appropriate for the larger cf.gov ecosystem. This PR will enable turbolinks across cf.gov when the TURBOLINKS feature flag is enabled.
https://github.com/turbolinks/turbolinks
- Turbolinks on-demand JS file.
- `TURBOLINKS` feature flag that loads the above file on cf.gov pages when enabled.
1. Enable the `TURBOLINKS` feature flag.
1. Load http://localhost:8000/ and click around to a few random pages. You should see a new progress bar at the top of the screen. Subsequent visits to the same pages should be instantaneous.
- I am not endorsing the use of turbolinks. It's kind of scary and would require a lot of testing to …

Add Turbolinks JS library behind a feature flag

---

.travis.yml
travis_run.sh

Instead of building the docs in a separate Travis stage, do it as part of the Travis backend stage. This will save time because Travis doesn't have to spin up a new instance, re-clone the repo, etc.

Build docs as part of Travis backend build

---

cfgov/v1/static-legacy/css/styles.css
cfgov/v1/tests/test_page_validation.py

Removing remaining wp-content references from repo
- Modified files to remove remaining references from repo.
1. Run `tox -e fast`
2. Visit `https://www.consumerfinance.gov/static/nemo/_/img/mortgage-sign-icon.png` and ensure the image exists.

Removing remaining wp-content references from repo

---

test/unit_tests/apps/owning-a-home/js/explore-rates/util-spec.js

Currently if you reside West of the Eastern time zone this test will
fail, updated to a sane time check to ensure all US time zone workers
are covered. (Discovered in #3887)
- Updates tested time stamp
1. Run `gulp test:unit`, all tests should pass
Before:
After:

Fixed timestamp so all US timezones will pass

---

cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/util.js
test/unit_tests/apps/owning-a-home/js/explore-rates/rate-checker-spec.js
test/unit_tests/apps/owning-a-home/js/explore-rates/util-spec.js

- Move `removeDollarAddCommas` to util modules.
- Removes jquery references from id lookups.
1. `gulp test:unit` should pass.
2. `gulp build` should pass.
3. Should be able to enter 20000 or whatever in the down payment field and it gets formatted as 20,000.

owning-a-home/rate-checker: Move add commas util to util module

---

cfgov/jinja2/v1/_includes/macros/subscribe.html
cfgov/jinja2/v1/_includes/organisms/reg-comment.html

We should always use example.com for filler domains, mail.com is a spammy actual domain.
- Changes `mail.com` to `example.com` in email signup.

Updates fake emails

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/settings/local.py

The changes in #4013 (c94b26e) introduced a warning message about database environment variables being deprecated. Placing this message in `settings.base` unfortunately means that it is logged even in production, where we still use those legacy variables.
We still want this warning, but only locally and in tests.
This change moves the warning from `settings.base` to `settings.local`.

Only warn about deprecated database variables locally

---

cfgov/unprocessed/apps/owning-a-home/js/dom-tools.js
test/unit_tests/apps/owning-a-home/js/dom-tools-spec.js

- Adds initial BAH dom-tools spec.
- Minor refactoring of dom-tools:
- Remove unnecessary nesting.
- Removes returns of applyAll, which runs forEach, which doesn't appear to return anything but undefined.
- Changes `return div.firstChild` to `div.children[0]` to avoid returning text nodes.
- Returns boolean from `applyAll`
- Don't run split on arrays on `applyAll`.
- Make isEl method internal.
- Documents methods.
1. `gulp test:unit` should pass and show 20% coverage in dom-tools.
2. `gulp clean && gulp build` should pass and form explainers should be unchanged in functionality.

Dom tools tests

---

cfgov/unprocessed/js/organisms/FormSubmit.js
test/unit_tests/js/organisms/FormSubmit-spec.js

Currently notifications are initialized within the formSubmit which lead
to errors where the notifications weren't being updated correctly (a new 
instance was created every submission). Moving them to their direct 
parent and passing them into the formSubmit resolves the issue.
- Moves notification init to it's parent function
- Passes notification into the formSubmit function
1. Run `gulp test:unit` and everything should continue to pass

Init notifications in the correct location

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

Removing form explainer flags
- Modified code to remove form explainer flags and fixed pattern regex.
1. Visit `http://localhost:8000/owning-a-home/closing-disclosure/` and ensure it works.
2. Visit `http://localhost:8000/owning-a-home/loan-estimate/` and ensure it works.

Removing form explainer flags

---

cfgov/jobmanager/tests/models/test_panels.py
tox.ini

PR #4013 (bbaa311) mistakenly broke tox testing against a MySQL database. This adds the MySQL dependencies back to the tox environment.
Confirm that this command works properly to run the unit tests against a MySQL database, with necessary dependencies installed in the tox environment:
`DATABASE_URL=mysql://root@localhost/v1 tox -e fast`
(Note that there may be some test failures that are MySQL-specific. This PR is just making sure that the tests can be run against MySQL.)

Restore MySQL to tox testing environment

---

cfgov/v1/tests/test_meta_image.py
cfgov/v1/tests/test_s3utils.py
requirements/libraries.txt
requirements/test.txt

Back in 80c7c7e88b4b82953728aedc7156307ea980dd7e we downgraded `moto` to 0.4.27 to fix some conflicting dependency versions that had surfaced through the addition of `venv-update` to the tox setup. At the time, I submitted a PR to `moto` to address the problem with their dependencies, and that eventually got merged. But we had not yet gotten round to bumping `moto` back up to a more recent version.
Now we have no choice: our old version of `moto` specifies an unpinned version of `flask`, and `flask` released version 1.0 today. In flask 1.0, the Jinja2 dep is bumped, meaning that we now have another Jinja2 version conflict when attempting to run `tox`.
All of which is to say, we are now bumping `moto` back up to a more recent version, and fixing a few related tests that needed to be …

Bump moto to more recent version and make related fixes

---

requirements/optional-public.txt

As a followup to https://github.com/cfpb/cfgov-refresh/pull/4059 and https://github.com/cfpb/regulations-site/pull/852, this PR bumps the version of regulations-site from 2.2.2 to [2.2.3](https://github.com/cfpb/regulations-site/releases/tag/2.2.3).
This will ensure consistency of versions for the requests package.
FYI @acrewdson.

Bump regulations-site from 2.2.2 to 2.2.3

---

cfgov/cfgov/settings/base.py

This change fixes the BETA_NOTICE feature flag so that it appears properly on beta.consumerfinance.gov when being served over HTTPS.
Currently this flag is configured with a "site" condition against "beta.consumerfinance.gov". The logic in wagtail-flags here:
https://github.com/cfpb/wagtail-flags/blob/master/flags/conditions.py#L132
matches against both host and port. On beta.consumerfinance.gov the Wagtail Site is configured with port 443, but the flag condition doesn't include a port. Because wagtail-flags defaults to matching against port 80, the flag doesn't match properly.

Fix beta banner feature flag

---

cfgov/jinja2/v1/_includes/organisms/table.html
cfgov/templates/wagtailadmin/table_input.html

Currently it's unclear that you can sort when a table has the sortable
options set. Adding default sorting options gives the user a clue the
table is sortable and how it's been sorted on page load.
- Added default number and string options to the admin
- Added sort value checker to the table template
1. Add a table to the page
1. Add sorting options to each column, choosing `Numerical - Default` for one of them (preferably one with reversed number values (see screenshot)
1. Load page and see the values are sorted on page load
I can't seem to find the Cucumber feature I wrote for the sortable tables originally. Can anyone point me to where those moved?

Add default sorting options to the wagtail table editor

---

cfgov/cfgov/settings/test.py
tox.ini
travis_run.sh

This change modifies how the Python/Django unit test database isspecified. Instead of using `DATABASE_URL` (which is also used to configure the Django server), the tests now use `TEST_DATABASE_URL`.
If not provided, the tests default to using an in-memory SQLite database.
This allows developers to run a local server against MySQL or PostgreSQL but still run their tests quickly against SQLite.
Automated PR testing on TravisCI will continue to run against Postgres.
- New `TEST_DATABASE_URL` environment variable can be used to specify Django test database.
- `DATABASE_URL` environment variable no longer specifies Django test database.
1. Run `tox -e fast` and you'll see the tests complete successfully (and quickly) against SQLite.
2. Run something like …

Use TEST_DATABASE_URL to specify Django test database

---

cfgov/unprocessed/apps/analytics-gtm/js/youtube-event-listeners-older-style.js
cfgov/unprocessed/js/modules/YoutubePlayer.js

Google analytics youtube script adds the youtube iframe_api to all pages. We should only add it if there's a youtube video on the page. This change checks the page for iframes and if none are found aborts the analytics script.
- Checks for existence of iframes on the page before injecting youtube's iframe_api script.
- Minor reformatting of youtube script to avoid dangling comma starting a new line.
2. Visit http://localhost:8000/about-us/blog/video-a-message-from-director-cordray/
3. Open the dev console and note that the iframe_api script has loaded in the network tab.
4. Visit the homepage.
5. Note that the iframe_api script has not loaded.
- You can add `?debug-gtm=true` to the URL and see in the console that it'll say `ANALYTICS DEBUG MODE: There are no …

Prevent iframe_api loading on pages without iframes

---

cfgov/jinja2/v1/_includes/organisms/info-unit-group-2.html

The data-attr was left over from the previous info unit group and not necessary. Removing so that we won't be printing todos in production markup.
- Removed data-attr from info unit group

Remove unnecessary data attr from info unit groups

---

cfgov/jinja2/v1/_includes/organisms/bureau-structure.html

Fix for Bureau structure copy. GHE issue 2713.
- Modified code to fix issue with `cfgov/jinja2/v1/_includes/organisms/bureau-structure.html` copy.

Fix for Bureau structure copy

---

cfgov/jinja2/v1/_includes/molecules/info-unit-2.html

`image_alt_value` was added in #2920, but for some reason (possibly related to parallel development of the InfoUnitGroup feature?), it never made it into the InfoUnit template. This PR rectifies that.
- `alt` output on an InfoUnit's image is now handled by the `image_alt_value` Jinja tag.
1. Pull branch
1. Create a new InfoUnitGroup with four InfoUnits with varying alt text data
1. No alt
1. Alt on upload
1. Alt in InfoUnit module, not on upload
1. Alt on upload and in InfoUnit module
1. Observe the expected output of (respectively):
1. Image is set as CSS `background-image`
1. Image has alt text of what was set on upload
1. Image has alt text that was set in the InfoUnit module
1. Image has alt text that was set in the InfoUnit module

Update InfoUnit template to use image_alt_value template tag

---

refresh-mysql.sh

After the changes in #4013 (c94b26e), the database refresh script will fail if the Django database user doesn't have sufficient privileges to import the database dump. For MySQL this can happen if the dump contains the `CREATE ALGORITHM` statements that are used for a view. In practice this shouldn't happen, but as an artifact of the current production database, it does.
This change adds a new `refresh-mysql.sh` script that wraps the existing `refresh-data.sh` script with a new preface that first ensures that the Django database user has super privileges.
Once the site transitions to Postgres, this will no longer be an issue. Either at that time, or when those views are removed from production data dumps, this script can be removed.
See platform#2711 and comments by @higs4281 there.
- New …

Add MySQL-specific refresh script

---

cfgov/cfgov/settings/base.py

This change reverts #4069 (9ecb41b) that added the youth financial education page to the list of draft pages on beta.
See GHE/platform#2720 for details/justification.

Revert addition of youth fined page to beta drafts

---

cfgov/unprocessed/css/images.less
cfgov/unprocessed/css/main.less

Currently richtext images are printed to the markup with static height
and width attributes. When the image is resized in one dirction, it
can be distorted in the opposite direction. Resetting the height and
width to auto avoids this issue allowing the image to take up the
dimensions of it's container without causing distortion.
- New global `images.less` file because this change is limited to Wagtail and not necessary to be moved to CF. This file will also be the future home of whatever Wagtail high-dpi/responsive image solutions we explore.
1. Gulp build
1. Create a table with fixed dimensions
1. Add an image to one of the columns (best if the column is narrow, like 20%)
1. Observe the image is not distorted in the way you can [see it is …

Fix an issue where richtext images are being distorted

---

tox.ini

This PR removes Wagtail 1.10 from our Tox testing matrix. All backend tests now default to Wagtail 1.13.

Remove Wagtail 1.10 from our test matrix

---

cfgov/jinja2/v1/_includes/organisms/table.html
cfgov/templates/wagtailadmin/css/table-block.css
cfgov/templates/wagtailadmin/js/table-block.js
cfgov/templates/wagtailadmin/table_input.html

When a user adds a table that is outside the full width text module,
there is no way to add a heading without relying on another block and
the spacing that goes with it (typically 60px). To alleviate this issue
I have added the heading block as a custom entry to the Table Block JS
as well as a necessary style fix to the Table Block CSS.
- Adds heading block markup to table block template
- Adds JS handlers for new text input and select fields
- Adds heading inputs to table input template
- Adds CSS necessary to align heading block inputs
1. Add or edit a table in Wagtail
2. Add heading text, select a level, and add an icon name
3. Save and view page, the appropriate heading level should be used with the text and icon entered in the admin.
- Due to the nature of the table block, we could …

Add optional heading block to the table block

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py
cfgov/legacy/templates/hud/housing_counselor.html
requirements/optional-public.txt

We are officially deprecating use of [django-hud](https://github.com/cfpb/django-hud) (see GHE platform issue 2719).  There are two additional PRs needed as documented in the GHE issue -- this should not be merged until those are merged.

Remove django-hud support

---

cfgov/unprocessed/apps/analytics-gtm/package-lock.json
cfgov/unprocessed/apps/owning-a-home/package-lock.json
cfgov/unprocessed/apps/regulations3k/package-lock.json
package-lock.json

I had tried npm 6, but it has bugs. This reverts the changes to package-lock files from npm 6.
- Revert npm 6 formatting of package-lock files

Revert npm 6 formatting of package-lock files

---

cfgov/unprocessed/apps/analytics-gtm/js/bah-explainers.js
cfgov/unprocessed/apps/analytics-gtm/js/util/analytics-util.js

Follow up to https://github.com/cfpb/cfgov-refresh/pull/4085 to remove `closest` utility method.
- Removes `closest` analytics util.
2. Visit /owning-a-home/closing-disclosure/?debug-gtm=true.
3. Click details and definition tabs and see that they log to the dev console.
4. Repeat for /owning-a-home/loan-estimate/?debug-gtm=true

Remove closest analytics util

---

cfgov/legacy/templates/hud/housing_counselor.html
cfgov/legacy/templates/hud/housing_counselor_pdf.html
cfgov/legacy/templates/hud/housing_counselor_pdf_selfcontained.html
cfgov/templates/wagtailadmin/js/table-block.js
cfgov/unprocessed/js/organisms/FilterableListControls.js

There are instances of the codebase where `</br>` is present, which should be corrected to `<br>` or `<br/>`. This PR fixes those instances. IE11 logs `</br>` as incorrect.
- Change `</br>` to `<br>`

Fix incorrect </br> tags

---

cfgov/jinja2/v1/_includes/organisms/email-popup/debt.html

See platform issue 2735
- Changes the govdelivery mailing list code on debt page popup solicitations
- Per stakeholder request, reverses the change made in PR #3951

Update govdelivery code for debt pages

---

cfgov/cfgov/urls.py
requirements/optional-public.txt

The current release of the Teachers Digital Platform needs the base url to be:
https://www.consumerfinance.gov/practitioner-resources/youth-financial-education/curriculum-review/
- None
- None
- Changed 'tdp' to 'practitioner-resources/youth-financial-education/curriculum-review/' in the urls.py
1. Verify the new url redirects to the current tdp develop-apps/teachers-digital-platform app

Updated Teachers Digital Platform URL for release

---

gulp/tasks/test.js
package-lock.json
package.json

Red output was only used in one error state place. Probably not worth having the dependency for that (which includes a bunch of colors and bold, etc.).
- Removes `ansi-colors` dependency in favor of inlining red color.

Remove ansi-colors

---

cfgov/cfgov/urls.py

The Teachers Digital Platform flagged-url for search refers to a URL conf that doesn't yet exist, which currently hoses beta and build.
This comments out the URL until code is lined up.

comment-out TDP search url

---

cfgov/jinja2/v1/owning-a-home/explore-rates/index.html
cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less
test/unit_tests/apps/owning-a-home/js/explore-rates/RateCheckerChartMenu-spec.js

Rate checker design feedback fixes GHE/19
1. Visit `http://localhost:8000/owning-a-home/explore-rates/` and compare to mockup.
- 
-

Rate checker design feedback fixes

---

cfgov/scripts/http_smoke_test.py
cfgov/scripts/tests/test_smoke_tests.py

Our smoketests sometimes fail because the initial test can time out
while servers are restarting. This PR allows one timeout to occur
without failing the build.
Also added a test of the test.

Let smoketests pass if only one timeout occurs

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py
cfgov/legacy/templates/hud/housing_counselor.html
requirements/optional-public.txt

This change restores the legacy django-hud API that was removed in #4086 (10766f1). This restores the dependency on https://github.com/cfpb/django-hud and restores the legacy API available
at, for example, https://www.consumerfinance.gov/hud-api-replace/20005.json.

Restore django-hud API

---

cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js

Fixes for rate checker
- Modified code to fix tab visibility issue. Tabs were disappearing when the rate checker `updateView` method was called. `.Tab.init` was already invoked in `init` method.
- Minor design change for the drop down.
1. Visit `http://localhost:8000/owning-a-home/explore-rates/#tab2` 
2. Click on the tabs and ensure that they work.
3. Click on the slider and cause an error.
4. Click on the sider, so the error is no longer created.
5. Verify that the tabs are still visible.
-
-

Fixes for rate checker

---

cfgov/legacy/static/hud/hud.js
cfgov/unprocessed/apps/analytics-gtm/js/bah-explainers.js
cfgov/unprocessed/js/molecules/Notification.js
test/unit_tests/js/molecules/Notification-spec.js

Some autofixable linter warnings crept into the codebase. This fixes them. Also,
```js
$('.show-hide-link').click(function() {
$('.show-hide-icon').toggleClass('icon-minus-alt icon-plus-alt');
});
```
Can be removed from `hud.js`, as the associated markup was removed in https://github.com/cfpb/cfgov-refresh/pull/3581
- Removes icon toggle code in `hud.js`.
- Autofixes linter warnings.
- Converts tabs to spaces in `hud.js`.
1. /find-a-housing-counselor/ should still work.

Autofix linter warnings | errors

---

cfgov/jinja2/v1/_includes/macros/category-icon.html
cfgov/jinja2/v1/_includes/macros/category-slug.html
cfgov/jinja2/v1/_includes/molecules/related-posts.html
cfgov/jinja2/v1/ask-cfpb/category-page.html
cfgov/jinja2/v1/ask-cfpb/landing-page.html
cfgov/jinja2/v1/index.html

Update all found existences of category icons to use SVG icons.
Co-authored-by: Scott Cranfill <scott.cranfill@cfpb.gov>
- Updated any files currently using category icons to use their SVG equivalent.
1. Check out category icons in the post titles at `http://localhost:8000/about-us/blog/`
1. Check out the category icons in the sidebar related posts at `http://localhost:8000/about-us/blog/3-common-credit-issues-and-what-you-can-do-fix-them/`
1. Check out the category icons in the related posts at the bottom of `http://localhost:8000/`
- This is just one part of the SVG Icon update. It's a lot easier to call these out individually than in the main PR.

Convert category icons to SVG

---

test/browser_tests/cucumber/step_definitions/global-search.js

The wrong test was removed in https://github.com/cfpb/cfgov-refresh/pull/4125 😱 
This fixes things.
- Add erroneously removed global search acceptance test back.
- Removes global search clear button acceptance test and associated variables.
1. `gulp test:acceptance --headless` should pass.

Fix erroneously removed test

---

test/unit_tests/apps/financial-well-being/js/fwb-results-spec.js

Fix fo Travis race condition in unit test
- Modified spec to move require statement to beforeEach method. It might require forcing Jest to wait until the module resolution has completed. 
1. Run `gulp test:unit`.
-
-

Fix fo Travis race condition in unit test 

---

cfgov/unprocessed/js/organisms/MegaMenu.js

https://github.com/cfpb/cfgov-refresh/pull/4154 adds SVG nodes in the mega menu. SVG nodes return `undefined` in IE11, so this loop fails in IE11 https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/js/organisms/MegaMenu.js#L112. This PR adds a check for whether the node it's processing has children.
- Fix issue in IE11 SVG icons in menu by adding a check when first traversing the menu dom to skip dom nodes that don't have children.
1. Visit the homepage in IE11 in the master branch. Note the mega menu is broken and covers the page's content.
2. Pull down this branch.
3. Visit the homepage in IE11 and note the mega menu is not broken.
4. Check that menu is navigable. Resize to tablet and mobile size and see that menu is still navigable.
Without fix:

Fix for SVG not having children in IE11

---

cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/data-loader.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/index.js

Minor rate checker cleanup
- Modified code to move the promise polyfill to be included only when axios is required. Provided a background color for ie10. 
1. Visit `http://localhost:8000/owning-a-home/explore-rates/` on ie10 and ie11.
2. Verify the rate checker works as expected.
-
-

Minor rate checker cleanup

---

cfgov/regulations3k/regdown.py
cfgov/regulations3k/tests/test_regdown.py

Very similar to #4105 but with regulation appendices. As [noted](https://GHE/eregs/regulations-3000/issues/42#issuecomment-159459) by @niqjohnson, appendices have confusing paragraph markers in the current implementation of eRegs. This PR accommodates the current structure of the appendix markers but once we start user testing we should reevaluate them.
- Have indenter ignore appendix prefixes
1. `tox -e fast regulations3k.tests.test_regdown`
1. Load a reg section page and see if the expandable inline interps no longer have wonky margins.

Properly indent regulation appendices paragraphs

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

Removing sheer from urls.py
- Removed test eregs form code, which wasn't being used. OK'ed with @Scotchester.
- Modified `urls.py` to remove Sheer references and flagged routes. 
1. Visit `localhost:8000/owning-a-home/explore-rates/` and ensure it renders.
2. Visit `localhost:8000/transcripts/how-to-apply-for-a-federal-job-with-the-cfpb/` and ensure it renders.
3. Visit `localhost:8000/owning-a-home/process/` and ensure it renders.
-
-

Removing sheer from urls.py

---

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html
cfgov/unprocessed/css/organisms/mega-menu.less

Adds underlines requested in [GHE]/CFGOV/platform/issues/2747
- Adds underlines to links in mega menu footer.
1. Pull branch down.
2. `gulp clean && gulp build`
3. Check `Consumer Tools` and `Practitioner Resources` in desktop and mobile sizes and verify they have dotted underlines.

Adds underlines to mega menu footer links

---

cfgov/jinja2/v1/govdelivery-subscribe/success/index.html
cfgov/jinja2/v1/owning-a-home/_templates/form-explainer.html
cfgov/jinja2/v1/owning-a-home/_templates/ratings-form.html
cfgov/jinja2/v1/regulation-comment/success/index.html

The name is `check-round`, not `checked-round`.
- It'd be nice if this silently failed instead of raising a 500, maybe? I suppose it would've taken a lot longer for us to notice the issue if it silently failed...

Fix typo in check-round icon name

---

cfgov/jinja2/v1/_includes/organisms/mega-menu.html

- Change mega menu aria-label to `main menu` from `main navigation`.
- Remove `role="navigation", which is covered by the HTML5 `nav` tag.
1. Press Cmd+F5 to activate VoiceOver
1. Press Ctrl+Opt+U to activate rotor mode
1. Press the right arrow until you reach the Landmarks menu
1. Press the down arrow to cycle through and hear "main menu navigation"
- We could remove the `aria-label` completely ([it's optional](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/landmarks/navigation.html)), however, if we had another `role="navigation"` on the page we'd want to have a label, so safer to include it.

Change navigation landmark label

---

gulp/tasks/scripts.js

Betsy spent more time than she should have trying to debug why the mega menu was open on top of the page on Paying for College. The reason was because we don't run `gulp scripts:ondemand` with a default `gulp scripts` run. Seems like we should just do that, otherwise, devs have to know that they have to run that ondemand subtask manually.
It's also worth noting that we include the ondemand styles in the default `gulp styles` run, so this makes the behavior consistent.
- `gulp scripts:ondemand` subtask to `gulp scripts` default task
1. `rm -rf cfgov/static_built`
1. Visit http://localhost:8000/paying-for-college/ and see the mega menu open on top of everything
1. Pull branch
1. Refresh the page and see the mega menu functioning normally

Run ondemand subtask with default gulp scripts run

---

cfgov/jinja2/v1/_includes/organisms/mega-menu.html

When the "Overview" text was stripped from `nav_overview` it broke the condition for the FMC stopping it from being rendered. Removing the "Overview" text there and comparing the `nav_overview` to the `parent_name` fixes everything.
- Removed the string concat with "Overview" text from the FMC condition
1. Startup local server and check all the main menu items for an FMC (all but About Us should have one).

Fix condition for rendering the FMC

---

README.md
docs/django-to-wagtail.md

.@Scotchester expressed a preference (one I endorse) the other day for not including a simulated prompt (`$`) when capturing shell commands in docs. The `$`s make copying-and-pasting these commands more difficult than necessary – you can't triple-click to get the whole line.
Also adding a couple typo fixes in one of the docs pages while I'm here.

README and docs fixes

---

cfgov/jinja2/v1/_includes/organisms/mega-menu.html

Currently the headings in the mega menu are part of the document outline. Replaces the `h3` tag with a `span` and relying instead on the default `h5` styles.
- Swapped `h3` for `span` 
1. Check out the nav and make sure it looks the same.
Before
After

Fix heading markup in mega menu

---

cfgov/templates/wagtailadmin/table_input.html

The help text for the heading icon in AtomicTableBlock was missing the link to see the list of icons.
1. Pull branch
1. Add a TableBlock to a FullWidthText and see the clickable link in the header icon field.

Fix AtomicTableBlock heading icon help text

---

cfgov/cfgov/settings/base.py
cfgov/regulations3k/fixtures/regdata.json
cfgov/regulations3k/models/django.py
cfgov/regulations3k/tests/test_hooks.py
cfgov/regulations3k/wagtail_hooks.py
requirements/libraries.txt

This PR uses [wagtail-treemodeladmin](https://github.com/cfpb/wagtail-treemodeladmin) for the Regulations3k models within the Wagtail Admin. This makes navigating them similar to navigating the Wagtail page tree explorer.
It also makes modifications to the admin hooks for Regulations3k to use TreeModelAdmin and the tests as a result.

Regulations3000: Use wagtail-treemodeladmin

---

requirements/libraries.txt

This PR bumps wagtail-treemodeladmin to 1.0.2, which adds some CSS to fix an annoying text alignment issue.

Bump watail-treemodeladmin dependency to 1.0.2

---

cfgov/regulations3k/regdown.py
cfgov/regulations3k/tests/test_regdown.py

This PR adds the official Python-Markdown table extension to the `regdown()` convenience function's extension list with our `RegulationsExtension`. This enables tables when using `regdown()` to convert Regdown text to HTML.
Leaving this out was probably an oversight, since tables [don't actually exist in the Markdown spec](https://daringfireball.net/projects/markdown/syntax). With this in mind, there may be [other official Python-Markdown extensions](https://python-markdown.github.io/extensions/#officially-supported-extensions) that we might want to enable.
- `markdown.extensions.tables` to `regdown()`

Regulations 3000: Add Markdown table extension

---

frontend.sh

These are all now run in the default [`gulp scripts`](https://github.com/cfpb/cfgov-refresh/blob/rm-prod-gulp-tasks/gulp/tasks/scripts.js#L264-L266) and [`gulp styles`](https://github.com/cfpb/cfgov-refresh/blob/rm-prod-gulp-tasks/gulp/tasks/styles.js#L297-L298) tasks.
- Extra build steps for `ondemand` and `nemo` stuff in production in `frontend.sh`
🤷‍♂️ I suppose we wait to see it get merged and deployed onto Build?

Remove extra production build steps from frontend.sh

---

cfgov/jinja2/v1/_includes/molecules/featured-menu-content.html

Use correct urls for featured menu content images in hard-coded mega menu version
- Use static filter with hard-coded featured menu content image urls
2. Verify that images show in the mega menu's featured menu items

Mega menu: fix for hard-coded fmc images

---

cfgov/regulations3k/regdown.py
cfgov/regulations3k/tests/test_regdown.py

This adds `__` syntax to Regdown for pseudo-forms, sample forms that exist in the regulation text.
It currently outputs `Date: <span class="pseudo-form">__</span>` for `Date: __` in Regdown. Any number of `_` from 2 to 50 is supported. It supports `__` form entries at the beginning of paragraphs, inline in paragraphs, and at the end of paragraphs. It preserves the number of underscores and outputs them within the `span` element (because sometimes a specific number of underscores is part of the regulation text
This also removes standard Markdown support for using underscores for emphasis by replacing the regulation expressions for those inline patterns with ones that do not contain underscores. Asterisk emphasis syntax is preserved.
@contolini There's currently no styling for the …

Add support for pseudo-form __ syntax to Regdown

---

cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu.html

- Adds aria- attributes to menu footer links.
2. Visit the site locally.
3. `Cmd`+`F5` to start VoiceOver
4. Tab through to Consumer Tools (scrolling down slightly and clicking "Consumer Tools" and then tabbing from there may be the easiest)
5. `Enter` to open Consumer Tools
6. Tab to `Ask CFPB` and listen that it reads a complete sentence.
7. Tab to `Submit a complaint` and listen that it also reads a complete sentence.
- With the move to Mega Menu in Wagtail, the `_vars-mega-menu.html` template is deprecated, so we'll need a solution that works in Wagtail, but the changes here can be used as a reference for what's needed in Wagtail.

Mega menu: Add aria attributes to menu footer links

---

cfgov/unprocessed/css/organisms/full-width-text-group.less

Deprecation of some Media block code caused images in those blocks to be vertically stretched and lose their margin. This temporary fix will restore that until we can complete a data migration to move Media block images to the new unified ContentImage block.
- CSS to fix Media images
1. With a recent database dump, go to http://localhost:8000/admin/pages/11594/edit/ and replace the image with one from your computer that is significantly wider than 770px.
1. Preview the page and notice that the image is stretched vertically.
1. Refresh the preview and see the image back to normal height, with 30px margin under it.
- Write data migration to move data from Media to ContentImage (not in this PR)

Hotfix to repair img height and margin on extant Media blocks

---

cfgov/jinja2/v1/_includes/organisms/mega-menu.html
cfgov/unprocessed/css/organisms/mega-menu.less

Fix `three-col` mega menu classes so they work correctly in header.css
- Updates to `three-col` classes in mega menu template and less file
2. Run `gulp styles`
3. Verify that FMC column displays correctly on   
- http://localhost:8000 
- http://localhost:8000/data-research/consumer-complaints/search/ 
(mega menu text will still be bold on search page)

Mega menu FMC column fix

---

package.json

Simpler version of #4209 
We introduced a webpack method that requires Node version 8.5+. This
commit introduces a preinstall script that prevents `npm install` from
continuing if the user's version of Node is less than what's specified
in package.json.
- npm preinstall script
- Required node version in `package.json` is now 8.5.
1. `nvm use 7` (or any version lower than 8.5)
1. Installation should fail.

Enforce specific Node version

---

cfgov/unprocessed/apps/analytics-gtm/js/hdma-explore-event-listeners.js

HDMA explorer events were relying on the "change" event on select drop-down menus that were hidden, so the event was never firing. This adjusts the scripts to listen on "mouseup" on the faux drop-downs that are created on top of the native drop-downs.
- Removes unnecessary "closest" helper.
- Moves event firing to faux drop-down instead of hidden native drop-down.
1. We'll test on build after merging.

Fix HDMA explorer non-firing "change" events

---

cfgov/scripts/http_smoke_test.py

Previously, the automated smoke testing script didn't cover all of the top 25 most visited pages on cf.gov. This PR updates the script to add the remaining pages.
This PR adds several URLs to the `FULL_RUN` list of paths in `http_smoke_test.py`. This means that when we run automated smoke tests (e.g. via Jenkins), we can directly confirm that all of the most popular pages on cf.gov return a `200`. 
Added URLs include:
-  several specific ask-cfpb pages
- some specific compliance guidance pages
- eRegs and a specific regulation page
This change is being tested on the Staging server with an automated Jenkins job.
This PR does not affect any cf.gov functionality.

Full smoke test script covers the top 25 most visited pages

---

cfgov/jinja2/v1/_includes/macros/video-player.html

A change to string concatenation in the video player template broke the preview images for videos within Featured Content Modules, e.g., https://www.consumerfinance.gov/practitioner-resources/library-resources/. This PR remedies that.
- Fixes FCM video preview images
1. Pull branch
1. Open a page with an FCM, like http://localhost:8000/practitioner-resources/library-resources/, and confirm that the preview image now loads (you should see a person, not just the CFPB logo)
1. Confirm that other uses of the video player macro still correctly show their preview images:
- Events: http://localhost:8000/about-us/events/archive-past-events/fall-2017-consumer-advisory-board-meeting-tampa-fla/
- Standalone organism: http://localhost:8000/consumer-tools/everyone-has-a-story/ana-debts-you-dont-owe/
- …

Fix FCM video preview images

---

cfgov/regulations3k/wagtail_hooks.py

One-line change for admin display.
Should produce this:

regs3k: expose section_range in subpart admin

---

requirements/optional-public.txt

Changed modal dialogs to set aria-hidden to false when shown for 508 compliance
Changes
Updated TDP version to 0.5.17

Bump TDP release version to 0.5.17

---

cfgov/regulations3k/regdown.py
cfgov/regulations3k/tests/test_regdown.py

Inline interps have an erroneous margin at the top caused by the presence of an empty paragraph element.
The empty paragraph comes from opening interp labels in the regdown.
I was originally thinking we should remove empty paragraphs but in retrospect we want to keep the IDs so that users can jump to those sections on the page. By replacing empty paragraphs with divs they naturally disappear from view but remain linkable.
Unrelated: I tweaked the inline interp pattern to support longer label prefixes (`12-b-1-Interp-2` instead of just `12-b-Interp-2`).
- Empty regdown paragraphs are now divs instead of paragraphs.
- Inline interps can have longer prefixes.

 Hide empty regdown paragraphs

---

cfgov/jinja2/v1/_layouts/base-common.html

The invalid media attribute on the font stylesheet causes HTML validation errors. Added a note to the layout template so future developers know the intent.
- Add a note on intent of invalid attribute

Add a note for invalid media attr

---

requirements/libraries.txt

1. requests specifies urllib3<1.23
1. edgegrid-python specifies any version of urllib3
1. edgegrid-python is installing urllib3 before requests's requirements are evaluated, causing a version conflict
This should fix it.
- Pins urllib3 to version 1.22 temporarily

Pin urllib3

---

cfgov/jinja2/v1/_includes/eregs/regulations3k-secondary-navigation.html
cfgov/regulations3k/models/pages.py

Opens relevant subpart expandable in the side nav on page load (instead of all the expandables being closed by default).
- Adds an 'expanded' key to subpart dictionaries that is True if any of the subpart's sections are active.
1. Open `http://localhost:8000/regulations/1005/5/` and `Subpart A` should be expanded in the secondary navigation with a green border next to 1005.5

Expand current subpart in side nav on page load

---

cfgov/jinja2/v1/_includes/molecules/global-header-cta.html
cfgov/jinja2/v1/_includes/organisms/mega-menu.html

- Moves `aria-popup` from `li` to `a` links in the submenus.
- Adds `role="menuitem"` to global CTA complaint link at mobile size.
- Adjust whitespace on attributes by adding `-`.
1. Using desktop voiceover on the menu at mobile size you should hear "1 of 6" etc for the menu items.

Move aria-haspopup from list items to links

---

cfgov/templates/wagtailadmin/table_input.html

I neglected to include a closing `</a>` tag in #4183, which is making it impossible to edit table contents right now 😳

Add closing tag to table header icon help link

---

.python_env_SAMPLE

In Django < 1.9, `manage.py dbshell` won't pass the Postgres DB password automatically when connecting. To avoid getting prompted for the password, we can set the `PGPASSWORD` environment variable.
Here we set the sample .python_env file `PGPASSWORD` to `cfpb` because that is the password set in the `docker-compose.yml` file for the Postgres container.
1. Start your Docker containers with `docker-compose up`.
2. Connect to the Python container with `./shell.sh`.
3. Run a Django dbshell with `cfgov/manage.py dbshell`. Note that you are not prompted for a password.

Add PGPASSWORD to .python_env_SAMPLE

---

.travis.yml
cfgov/cfgov/settings/test.py
cfgov/cfgov/test.py
cfgov/cfgov/tests/test_test.py
tox.ini

This PR is a proposal for capturing stdout while unit tests run and then failing the tests if anything writes to it. It does this by capturing all stdout during the test run and asserting that it is empty at the end. It uses `redirect_stdout` from Python 3's `contextlib` and a function that approximates it in Python 2.
One disadvantage to this approach is that you don't know where the text came from necessarily. The test run looks like this:
```
Creating test database for alias 'default'...
applying migration wagtail.wagtailcore.migrations.0002_initial_data
applying migration wagtail.wagtailcore.migrations.0025_collection_initial_data
.
----------------------------------------------------------------------
Ran 1 test in 0.113s
OK
Traceback (most recent call last):
File "manage.py", line …
```

Fail Python unit tests if anything writes to stdout

---

cfgov/regulations3k/fixtures/graftest.xml
cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html
cfgov/regulations3k/models/django.py
cfgov/regulations3k/models/pages.py
cfgov/regulations3k/scripts/ecfr_importer.py
cfgov/regulations3k/scripts/patterns.py
cfgov/regulations3k/tests/test_ecfr_importer.py
cfgov/regulations3k/wagtail_hooks.py

Appendices and interpretations share the same DIVs in our source XML.
This change teases them out and processes them separately.
In the pursuit of small PRs, this is an incremental change, focusing on parsing just the main text of appendices with subheadings, and recognizing when they're using a different indentation scheme.
This code doesn't work for all regs yet, nor does it properly handle our oddities: pseudo-forms, tables and images.
Some other improvements included:
- A fix to the Section model's "numeric_label" property so that it doesn't choke on appendices, which have alpha section labels.
- A fix to the ordering of side navigation subparts and sections.
- The addition of "label" field to list display for sections in the admin, to help identify appendices.
Appendix imports aren't …

regs3k: Update ecfr_importer to handle appendices

---

docs/usage.md

PR #4242 (88bffb0) broke a section link in the docs by renaming a section.
See [the live docs](https://cfpb.github.io/cfgov-refresh/usage/#2-run-elasticsearch) for the currently broken link.

Fix doc link to Elasticsearch instructions

---

cfgov/legacy/templates/hud/housing_counselor.html

Changes the text in the sidebar for the "Find a Housing Counselor" tool to link to the HUD page and information.
- Enacts only the text change from #4086
1. Visit your local version of https://www.consumerfinance.gov/find-a-housing-counselor/
1. Verify the text in the gray box has changed

Text change for HUD API

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

The legacy HUD API (powered by https://github.com/cfpb/django-hud) should only be enabled for the production environment. Other environments (those using Postgres) do not support that app, and accessing the legacy API endpoints will cause 500 errors.
This change creates a new (temporary) feature flag, `LEGACY_HUD_API`, that is only enabled in production.
To test, run a local server and visit http://localhost:8000/hud-api-replace/20005.json/. With this change, you'll get a 404 at that location. Then re-run your server, first setting the environment variable `DEPLOY_ENVIRONMENT` to `production`. At that page you'll either get results (if using MySQL and a valid dump) or an (expected) Postgres error if you're missing the table from the dump.

Disable legacy HUD API for non-prod environments

---

cfgov/ask_cfpb/migrations/0016_modify_help_text_social_sharing_image.py
cfgov/ask_cfpb/models/django.py
cfgov/v1/migrations/0113_modify_help_text_social_sharing_image.py
cfgov/v1/models/base.py
cfgov/v1/tests/test_social_sharing_image_validation.py
cfgov/v1/util/util.py

We want to prevent social sharing images that are too large from getting saved to a page (currently they get saved and then don't display at all on Twitter).
See GHE/CFGOV/platform/issues/2377 for more context. 
- Saving a non-Ask page displays the specific error, like so:
- While saving an Ask answer (a Django model) shows something more generic:
I think this is related to this issue https://github.com/wagtail/wagtail/issues/3441  which was only recently fixed, so it would not be fixed in our current version of Wagtail.  As part of this work, I also updated the help text (hence the migrations), so I feel like it's not too big of a deal, but just wanted to flag.

Invalidate pages if their social sharing image is too large

---

cfgov/regulations3k/models/django.py
cfgov/regulations3k/tests/test_models.py
requirements/libraries.txt

This PR updates Wagtail-TreeModelAdmin to 1.0.3, which uses the parent's string representation as the breadcrumb. This PR also slightly modifies the `__str__` methods of some of our Regulations 3000 models so that make more sense in that context.

Upgrade Wagtail-TreeModelAdmin to 1.0.3

---

cfgov/regulations3k/migrations/0005_add_sortable_label_subpart_type.py
cfgov/regulations3k/migrations/0006_set_sortable_label_subpart_type.py
cfgov/regulations3k/migrations/0007_make_sortable_label_required.py
cfgov/regulations3k/models/django.py
cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py
cfgov/regulations3k/wagtail_hooks.py

Subparts and sections of regulations have some human-friendly sorting keys attached to them, but they're not friendly for database sorting. This PR makes two changes to enable us to sort these in our database queries:
- Adds `subpart_type` to `Subpart`, with possible values of `Subpart.BODY`, `Subpart.APPENDIX`, and `Subpart.INTERPRETATION`. Subparts are now sorted based on the subpart type and then their label.
- Adds `sortable_label` to `Section`, which will be automatically populared with a "-"-joined result of a call to our `sortable_label()` function, which was already in use for sorting on the front-end. Sections are now sorted based on this field.
These two changes are accompanied by changes to the front-end to end our sorting in the `RegulationPage` object and rely instead on the …

Regulations 3000: Use database fields for sorting sections and subparts

---

requirements/optional-public.txt

Added more Analytics, fixed Node Module versions, Added many more unit tests
Changes
Updated TDP version to 0.5.22

Bump TDP release version to 0.5.22

---

cfgov/ask_cfpb/tests/test_hooks.py
cfgov/ask_cfpb/wagtail_hooks.py
cfgov/templates/wagtailadmin/css/question-tips.css
cfgov/v1/static/css/question_tips.css
cfgov/v1/wagtail_hooks.py

This CSS should probably live with the rest of the custom Wagtail admin CSS.
- Moves `cfgov/v1/static/css/question_tips.css` to `cfgov/templates/wagtailadmin/css/question-tips.css`
- Minor updates to rendered link markup for admin CSS files
1. Pull branch
2. Edit an Ask CFPB answer that has a tip, e.g., http://localhost:8000/admin/ask_cfpb/answer/edit/779/
3. See that the tip is still styled correctly in the rich text editor
4. `tox -e fast` to confirm tests still pass

Move Wagtail admin CSS for Ask question tips to usual location

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py
requirements/optional-public.txt

The Housing Counselor API is being permanently decommissioned after June 15, 2018. We recommend using the official public [HUD API](https://data.hud.gov/housing_counseling.html)  as a permanent solution for locating housing counselors, which is what the Bureau uses for our [Find a Housing Counselor](https://www.consumerfinance.gov/find-a-housing-counselor/) tool. 
If you need some of the features that we have developed on top of the HUD API, feel free to explore the code of our [legacy API](https://www.consumerfinance.gov/external-site/?ext_url=https%3A%2F%2Fgithub.com%2Fcfpb%2Fdjango-hud&signature=inr5Ee5f4rgTCpzaOLfAHG4Y9QQ  or the code that powers the current implementation of the page, which can be found in the [cfgov-refresh](https://github.com/cfpb/cfgov-refresh/) project.
- …

Deprecate HUD API

---

cfgov/jinja2/v1/_includes/molecules/global-header-cta.html
cfgov/jinja2/v1/_includes/organisms/mega-menu.html

https://validator.w3.org/nu/?showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fwww.consumerfinance.gov/
Flagged attributes that were missing spaces between them.
- Adjusts whitespace stripping in jinja to fix attributes in the menu that had no whitespace separation.
1. You can check this branch locally with https://chrome.google.com/webstore/detail/html-validator/mpbelhhnfhfjnaehkcnnaknldmnocglk?hl=en-US It will have errors, but shouldn't have errors related to lack of space between attributes.

Adjust jinja whitespace removal to fix lack of spaces

---

cfgov/jinja2/v1/_includes/molecules/global-search.html

The id for the query has been updated to `m-global-search_query`, so this outdated `query` value needs to be updated.
- Fix bug where delete label in global search had an outdated for attribute value.
- When in the mobile size of the homepage, enter text into the search input (an "x" should appear). Click the "x" to clear the text.

Fix incorrect for attribute value

---

cfgov/jinja2/v1/_includes/organisms/footer.html

According to the html validator contentinfo is unnecessary for the role in the footer.
- Remove contentinfo unnecessary role from footer.
1. You can check this branch locally with https://chrome.google.com/webstore/detail/html-validator/mpbelhhnfhfjnaehkcnnaknldmnocglk?hl=en-US
2. Open the dev console.
3. Click "HTML Validator"
4. Reload the page.
5. Click "W3c online" button. See that the info message shown in the screenshot is not present. Can be compared to master to see the difference.

Remove unnecessary contentinfo role from footer

---

cfgov/jinja2/v1/_includes/macros/util/format/datetime.html

Milliseconds were causing an HTML validation error because of the number of decimal places they used. Easiest to just remove them because it doesn't look like they are utilized anyway.
- Removes milliseconds from timestamp.
2. Visit homepage.
3. View source.
4. Search for `datetime` and see that `datetime=` attribute only contains seconds in the time, such as `2018-05-23T19:55:00-0400`.

Remove milliseconds from timestamp

---

cfgov/jinja2/v1/_includes/molecules/global-header-cta.html

- Fix incorrect aria role attribute name that was `aria-role` instead of `role`.
1. You can check this branch locally with https://chrome.google.com/webstore/detail/html-validator/mpbelhhnfhfjnaehkcnnaknldmnocglk?hl=en-US
2. Open the dev console.
3. Click "HTML Validator"
4. Reload the page.
5. Click "W3c online" button. See that it doesn't report that the aria-role is incorrect on `a`.

Fix incorrect aria role attribute name

---

cfgov/jinja2/v1/ask-cfpb/answer-page.html

`pubdate` boolean attribute has been removed from the html spec. We could use microdata schema https://www.sitepoint.com/5-obsolete-features-html5/#2-the-pubdate-attribute, but since we don't use that elsewhere it's probably best to remove it altogether for now.
- Remove obsolete `pubdate` boolean attribute

Remove obsolete pubdate boolean attribute

---

cfgov/unprocessed/css/organisms/mega-menu.less
cfgov/unprocessed/js/modules/transition/BaseTransition.js

When an item is animating there are situations where we need temporary
style changes. Adding an `u-is-animating` class to the base transition
gives us a hook to add those temporary styles.
- Adds `u-is-animating` class during the animation
- Reorganized the related styles a bit to make it easier to understand what's going on.
1. Run `./runserver.sh` and navigate to the website
1. With a narrow browser window, click the menu button and then tab through the items
1. Open an item by clicking on it or hitting enter why it's focused.
1. Navigate to the sub-items by tabbing
1. Repeat these steps with your mobile device using localtunnel and swiping in place of tabbing.
When tabbing the top level items, the focus should not enter the sub-items unless you hit enter or click a …

Add is animating class to extend style options

---

requirements/deployment.txt
requirements/local.txt
requirements/mysql.txt
tox.ini

Now that we have migrated all environments to Postgres, we no longer need to test on mysql or develop for it.
- `requirements/mysql.txt` and the 3 references to it that I found in the codebase
This does not change any cf.gov functionality.

Remove mysql.txt requirements file and all references to it

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/settings/local.py

This change removes support for configuration of a Django MySQL database via environment variables like `MYSQL_NAME`, `MYSQL_USER`, etc. The Django database configuration must now be specified exclusively via the `DATABASE_URL` environment variable.
These lines are mentioned [here](https://github.com/cfpb/cfgov-refresh/pull/4241#pullrequestreview-127955375) as being a MySQL cleanup change not covered by #4241.

Remove support for legacy MySQL environment variables

---

cfgov/v1/models/snippets.py
cfgov/v1/tests/models/test_snippets.py

The SnippetList organism lets users specify tags that limit which snippets are returned in the list. The help text for this organism [claims](https://github.com/cfpb/cfgov-refresh/blob/81fd2fb9a5142bd2ad825ec7c385697e0b9e0c12/cfgov/v1/atomic_elements/organisms.py#L1009) that case-insensitive matching is used, but currently it is not. This happens to work properly on MySQL but is broken on PostgreSQL.
This change explicitly uses Django's [`iexact`](https://docs.djangoproject.com/en/dev/ref/models/querysets/#iexact) matching for case-insensitive tag matching, and adds a regression unit test to cover this behavior.
With a local production dump, verify that [this page](http://localhost:8000/practitioner-resources/resources-for-tax-preparers/outreach-materials-encourage-saving/) on your local …

Enforce case-insensitive tag matching for snippets

---

cfgov/jinja2/v1/_includes/organisms/mega-menu.html

Fix for url issue after removal of overview external_link field from MenuItem.
- Set default for link urls in mega-menu.html
2. Turn on Wagtail version of menu (flip `WAGTAIL_MENU` flag)
3. Run `python cfgov/manage.py runscript migrate_mega_menu` if necessary to set up Wagtail menu items
4. Verify that `href` of `Consumer Tools` link is set to `#`

Mega menu: set default value for link url

---

cfgov/legacy/static/nemo/_/c/v1-nonresponsive-header.css

They were breaking `collectstatic`, though you wouldn't see it when deploying to environments that have stale copies of `boxsizing.htc` under the static root. I discovered the problem when deploying to a local Vagrant instance.
The references were originally removed in 085ec579cffb46289e72e0650cee68d8feaf89e3 but got added back in 112aef22532aec651483743eaffef36003c6b7bb.
See also: https://github.com/cfpb/django-college-costs-comparison/pull/13

Remove boxsizing.htc references

---

test/unit_tests/js/organisms/MegaMenu-spec.js

There have been acceptance tests but no unit tests for the mega menu. Adding a basic outline of tests gives us a small amount of assurances that we don't break something with a future update. These are just a very basic outline, but a place to start for now.
- Mega menu unit tests
1. run `npm run -- gulp test:unit --specs=js/organisms/MegaMenu-spec.js`

Add unit tests for the mega menu

---

cfgov/unprocessed/css/organisms/mega-menu.less
cfgov/unprocessed/js/organisms/MegaMenuMobile.js
test/unit_tests/js/organisms/MegaMenuMobile-spec.js

When opening and closing menu states the focus is hidden on the trigger
that moves out of view. This change addresses the issue by moving the
focus to the logical trigger of the panel that comes within view.
There's also a bit of cleanup to avoid setting/unsetting all transitions
on the sibling submenus and narrow the focus (pun intended) to only the
child of the parent trigger.
- Added `handleExpandEnd` function to manage the animating state class and focus changes after animations have completed.
- Added logic to only set transitions to the intended child menu.
- Removed the logic that set transitions on all child menus.
-Updated the expand begin, collpase begin, and collapse end functions to manage the animating state class to better target styles and focus changes to just the child …

Add focus management to the mobile menu open/close interactions

---

cfgov/regulations3k/scripts/ecfr_importer.py
cfgov/regulations3k/tests/test_ecfr_importer.py

The ecfr_importer was errantly checking individual appendix paragraphs
for interpretation references, resulting in doubled refs in some cases.
Example: `/regulations/1002/C/`
Can also be seen in `/1026/F/` and `/1026/O/`
After checking out this branch, running the importer for 1002 (and unsetting "draft" on the resulting new effective_version) should result in only one interp reference in `/1002/C/`
```
./cfgov/manage.py runscript ecfr_importer --script-args 1002
```

regs3k: Remove duplicate interp references in appendices

---

cfgov/jinja2/v1/events/_macros.html
cfgov/sheerlike/__init__.py
cfgov/sheerlike/filters.py
cfgov/sheerlike/tests/test_filters.py
cfgov/v1/jinja2tags.py
cfgov/v1/tests/test_jinja2tags.py

This change moves where the `is_filter_selected` Jinja function is defined, from the sheerlike app to the v1 app. This function is used in the filterable list rendering logic.
To test locally using a production dump, run a local server and visit http://localhost:8000/about-us/blog/. Test and verify that filtering by various options continues to work properly.
This change also removes the deprecated `event_filter_args` macro which is not used anywhere in the codebase. It also removes the `selected_filters_for_field` tag which is also not used.
This change is part of a larger goal to remove the deprecated sheerlike app, initially by reducing dependencies on the `sheerlike.get_request` method.

Move is_filter_selected jinja tag to v1 app

---

requirements/libraries.txt
requirements/scripts.txt
requirements/test.txt

Bumps `requests` to 2.19.1 and `github3` to `1.1.0`.
We ran into issues with our SQS messages for alerts which stemmed from an out of date `requests` library.
Please note: There is a separate `requests` entry in [libraries.txt](https://github.com/cfpb/cfgov-refresh/blob/master/requirements/libraries.txt). This requirements file is not used to run any cfgov specific code, just by Jenkins to log messages, so these versions may differ without causing errors due to version mismatch.

Update scripts.txt requirement versions

---

cfgov/processors/processors_common.py
cfgov/v1/__init__.py

As part of the removal of the deprecated sheerlike app, this change removes the `fix_link` method and its inclusion in Wagtail link markup logic.
This method uses [`urlparse.urlsplit`](https://docs.python.org/2/library/urlparse.html#urlparse.urlsplit) to split a URL into five components (scheme, netloc, path, query, and fragment) and then uses [`urlparse.urlunsplit`](https://docs.python.org/2/library/urlparse.html#urlparse.urlunsplit) to join them back together. This is effectively a noop:
```py
>>> urlunsplit(urlsplit('https://www.consumerfinance.gov/?foo=bar#test'))
'https://www.consumerfinance.gov/?foo=bar#test'
```
with one exception, the case of a completely empty query string:
```py
>>> urlunsplit(urlsplit('https://www.consumerfinance.gov/?'))
'https://www.consumerfinance.gov/'
``` …

Remove deprecated fix_link function

---

cfgov/jinja2/v1/_includes/organisms/mega-menu.html

there was an attempt to make another element the label, but that element was removed
-
-
-
I tested this on VoiceOver and there was no difference in the text that was read aloud for this element 🤷‍♀️ 
-
-

Revert to previous aria attribute

---

requirements/wagtail.txt

This change increases the version of Wagtail used from 1.13.1 to 1.13.2. This patch release fixes several bugs, including a set of 500 errors caused by null characters in URLs.
To confirm this fix, visit http://localhost:8000/foo/?x=%00 against a local server and note that it returns 404, not 500 as before.
Release notes for this version are at http://docs.wagtail.io/en/v2.1.1/releases/1.13.2.html.
All unit tests continue to pass; as this is a patch release, there are no major changes to functionality.

Bump Wagtail version to 1.13.2

---

cfgov/regulations3k/search_indexes.py

This will allow proper sorting when "order by regulation" is chosen
on our search page. It also fixes the section query so that only
sections that belong to a live effective version are indexed.
This requires current work from the `regs3k-search-filters` branch to see search ordering in action, but you should be able to run the index command without errors:
```
./cfgov/manage.py update_index regulations3k --remove
```

Add sortable_label to index and fix section query

---

cfgov/jinja2/v1/_includes/atoms/radio-button.html
cfgov/jinja2/v1/_includes/eregs/regulations3k-search-bar.html
cfgov/jinja2/v1/_includes/organisms/expandable.html
cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
cfgov/regulations3k/models/pages.py
cfgov/unprocessed/apps/regulations3k/css/reg-search.less
cfgov/unprocessed/apps/regulations3k/js/search.js

Adds a 'Results per page' and 'Order' section to the Regs3k sidebar. 
cc @rrstoll @dcmouyard who are building a similar search interface for TDP. You can find most of our search markup in [`search-regulations.html`](https://github.com/cfpb/cfgov-refresh/blob/4c888cfd07b2bb8d2f3afd274430810ae3c8854b/cfgov/regulations3k/jinja2/regulations3k/search-regulations.html). Feel free to reach out if you have any questions about our approach.
- Sorting and pagination radio buttons to the Regs3k sidebar.
- Radio button atomic component.
1. [Set up Regs3k search](https://github.com/cfpb/cfgov-refresh/pull/4266).
1. Search for something and try changing the results per page and sorting order.
- Teeeeeeeests :grimacing:

regs3k: Add sorting and pagination options to Regs3k search

---

requirements/optional-public.txt

This adds Django 1.11 compatibility to django-college-costs-comparison.
This does not change any cf.gov-refresh functionality.

Bump django-college-costs-comparison version to 1.7

---

.travis.yml
travis_install.sh
travis_run.sh

The master branch doesn't need to run the test suites on ever PR merge, but the docs deploy currently relies on the master branch. Additionally, the docs should only deploy when a tag is released, otherwise the docs don't represent what's on production. This PR moves the docs to it's own stage that relies on a tagged release condition.
- Reorganize travis for docs install and script tasks to live within docs stage.
- Reduce the depth of git commits to something reasonable.
1. ¯\\_(ツ)_/¯ [Travis confirms it's not running the docs stage](https://travis-ci.org/cfpb/cfgov-refresh/builds/400606760), but there's no way to test the docs deploy without a tag 
- There's more we can do to speed up the front-end side of the tests but this does drop about 30secs of every backend build and removing …

Reduce Travis queue by moving docs deploy to its own stage

---

cfgov/cfgov/settings/base.py

This change modifies how various feature flags are triggered to enable functionality that should only be live on beta.cf.gov. Instead of relying on the Wagtail Site (which requires a database modification each time the beta DB is refreshed), the flags now use the Django setting `DEPLOY_ENVIRONMENT`, which is part of the beta system configuration.
To test, run a local server and notice that you don't see a beta banner. Then run again like this:
```sh
DEPLOY_ENVIRONMENT=beta ./runserver.sh
```
and you'll see the banner. Similarly, the TDP pages behind the TDP flags will work, if you have the [teachers-digital-platform](https://github.com/cfpb/cfgov-refresh/blob/master/requirements/optional-public.txt#L10) optional requirement installed.

Beta feature flags now based on DEPLOY_ENVIRONMENT

---

cfgov/jinja2/v1/_includes/templates/header-without-nav.html

-
- Remove unneeded banner role.
-
1. Have the HTML Validator chrome extension installed https://chrome.google.com/webstore/detail/html-validator/mpbelhhnfhfjnaehkcnnaknldmnocglk?hl=en-US
1. Visit a blog article. 
2. Click any of the share buttons.
3. _Quickly_ inspect the page and open the HTML Validator tab and click "w3c online".
4. See that banner role warning is not in list of issues.
Before:

Remove uneeded role

---

cfgov/core/management/commands/inactive_users.py

- Fixes misplaced space in Wagtail account expiry email.
Before:

Fix typo in expiry email message

---

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html

Update the label for regulation effective dates from "Effective date:" to "Most recently amended"
- Label for regulation effective dates changed from "Effective date:" to "Most recently amended"
1. Fire up Regulations 3000 as usual
2. Go to any section, appendix, or interpretation of any regulation
3. Verify that the effective date that shows under the page's `h1` reads "MOST RECENTLY AMENDED [DATE]" as in the screenshot below

Change label for regulation effective dates

---

.eslintrc
cfgov/unprocessed/apps/owning-a-home/js/Expandable.js
cfgov/unprocessed/apps/owning-a-home/js/dom-tools.js
cfgov/unprocessed/apps/regulations3k/js/search.js
cfgov/unprocessed/js/organisms/MegaMenuMobile.js
cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/actions/chart.js
package-lock.json
package.json
test/unit_tests/js/modules/Analytics-spec.js

- Removes deprecated `experimentalObjectRestSpread` from eslintrc file.
- Update to ESLint 5.
- Adds new `max-classes-per-file` rule.
- Adds new `max-lines-per-function` rule.
- Adds new `implicit-arrow-linebreak` rule.
- Adds new `prefer-object-spread` rule.
- Autofixes linter errors and warnings.
1. `gulp lint` should show no errors.
1. `gulp clean && gulp build && gulp test:unit` should pass.
- development and capital-framework repos need their eslintrc file updated after this PR is approved.

Update to ESLint 5

---

cfgov/jinja2/v1/owning-a-home/closing-disclosure/closing-disclosure-1-data.html
cfgov/jinja2/v1/owning-a-home/closing-disclosure/closing-disclosure-2-data.html
cfgov/jinja2/v1/owning-a-home/closing-disclosure/closing-disclosure-3-data.html
cfgov/jinja2/v1/owning-a-home/closing-disclosure/closing-disclosure-4-data.html
cfgov/jinja2/v1/owning-a-home/closing-disclosure/closing-disclosure-5-data.html
cfgov/jinja2/v1/owning-a-home/loan-estimate/loan-estimate-1-data.html
cfgov/jinja2/v1/owning-a-home/loan-estimate/loan-estimate-2-data.html
cfgov/jinja2/v1/owning-a-home/loan-estimate/loan-estimate-3-data.html
cfgov/sheerlike/__init__.py

As part of deprecation/cleanup of the sheerlike app, this change removes the custom `url_for` template function in favor of the standard Django `static` tag, which we pass into the Jinja2 environment.
To verify locally, visit:
- http://localhost:8000/owning-a-home/closing-disclosure/
- http://localhost:8000/owning-a-home/loan-estimate/
and verify that all images in the various steps load properly.
These images are all available to the static tag because we include the `static_built` directory in `settings.STATICFILES_DIRS`:
https://github.com/cfpb/cfgov-refresh/blob/3e3aed43d3cef23701ed9d4aaae45c199c4454be/cfgov/cfgov/settings/base.py#L230
The source images are located in `unprocessed/img` and get copied into `static_built` as part of the frontend build. Note that this does require that …

Deprecate sheerlike.url_for Jinja2 function

---

cfgov/regulations3k/jinja2/regulations3k/inline_interps.html
cfgov/unprocessed/apps/regulations3k/css/main.less
cfgov/unprocessed/apps/regulations3k/css/reg-inline-interpretations.less

Align inline interpretations to the text of the paragraph they interpret
- `inline-interpretation` class to inline interpretation expandables
- LESS to style inline interpretation expandables
1. Fire up Regulations 3000 as normal
2. Go to any section that has inline interpretations
3. Verify that inline interpretation styles match those seen in the screenshot below; namely:
- Inline interpretations are only as wide as the main column of text (i.e. they don't bleed past the right edge of the paragraph text)
- Each Inline interpretation is indented to the same level as the interpreted paragraph right above it
- These styles rely on inline interpretations always directly following the paragraph they interpret, which I believe will always be the case. If we don't think the next sibling …

Align inline interpretations to paragraph text

---

requirements/optional-public.txt

Bumps `ccdb5-ui` to the latest release, 1.0.11. This should have no perceptible effect on anything, and only makes the `ccdb5-ui` app explicitly compatible with Django 1.11.

Bump ccdb5-ui version to 1.0.11

---

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html
cfgov/regulations3k/models/pages.py
cfgov/unprocessed/apps/regulations3k/css/reg-text.less

Move the search link on regulations section pages a little further down the page and point it to the correct URL.
- Added `search_url` to the section page's context
- Ditched the search icon at the beginning of the link
- Reorganized the HTML for a section page's metadata elements
- Moved the search link below the `h1`
- Underlined the search link
1. Fire up Regulations 3000 as you usually do
2. Go to any section of any regulation
3. Make sure the search link now appears underneath the effective date, reads "Search 12 CFR Part [NNNN] (Regulation [X])" and matches the style shown in the screenshot.
4. Make sure the search link points to regulations/search-regulations/results/?regs=[NNNN]. When you do a search on the page that link points to, you should initially only see results from the …

Update regulations search link

---

cfgov/regulations3k/jinja2/regulations3k/base.html
cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py

This is a relatively simple option that makes search terms bold, leaves a reasonable window of text around the search term for context and thus isn't too jarring when jumping to the result's reference link.
The highlighting can be test-driven on dev5 at`/regulations/reg-search/results/?q=appraisal+fee`
Other Haystack options remove content up to the first instance of the search term, which has  drawbacks:
- Highlighting of the first instance of the term becomes redundant, since the terms are always the first words of a result.
- It often fails to provide reasonable context and can be disorienting when clicking on the result link.

Regs3k: Add search-term highlighting

---

cfgov/unprocessed/apps/regulations3k/js/search-utils.js
cfgov/unprocessed/apps/regulations3k/js/search.js
test/unit_tests/apps/regulations3k/js/search-spec.js
test/unit_tests/apps/regulations3k/js/search-utils-spec.js

Clear all regs checkbox filters and remove the filter tags when the red 'Clear all filters' button is clicked.
1. Select regs filters.
1. 'Clear all filters' link should appear next to filter tags.
1. Clicking link should clear all filters.

regs3k: Build out 'clear all filters' button

---

refresh-data.sh

This change modifies the `refresh-data.sh` script so that the console output from the database load step is suppressed via redirection to `/dev/null`. The current process echoes many, many lines of output when loading a database dump which is not particularly useful.
This only redirects stdout, and so error messages should still get displayed (if any occur).

Suppress database load output in refresh script

---

cfgov/jinja2/v1/owning-a-home/explore-rates/index.html
cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less
cfgov/unprocessed/apps/owning-a-home/css/helpers.less
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js
package-lock.json
package.json

The existing errors and warnings in OaH were essentially duplicates of
the new form-alert from cf-forms. Updating the markup, styles, and JS to
allow them to work with the existing infrastructure.
- Updated the cf-forms version in package.json
- Replaced existing OaH warnings and alerts with the new `a-form-alert`
1. Run `npm install && gulp build`
1. Run `./runserver.sh`
1. Open http://localhost:8000/owning-a-home/explore-rates/
1. Set the credit score as low as it will go, you should get an error like this
1. Reset the credit score to somewhere in the middle
1. Set your state to IL (this will work with any state/county combo, but I know this specific combo shows what we're looking for)
1. Set the house price to $0 and the down payment to $1, you should get a warning like this
1. Set the …

Update to use the new a-form-alert from CFv5.3.0

---

cfgov/jinja2/v1/_includes/organisms/email-popup/oah.html

This change fixes a bug with the privacy act link in the email popup organism that appears on OaH/BaH links. See platform#2889 reported by @jordanafyne.
Link should go to https://www.consumerfinance.gov/owning-a-home/privacy-act-statement/, not the broken https://www.consumerfinance.gov/owning-a-home-privacy-act-statement/.

Fix Buying a House email popup privacy act link

---

cfgov/cfgov/settings/base.py
cfgov/core/__init__.py
cfgov/core/apps.py
cfgov/core/feature_flags.py
cfgov/core/jinja2tags.py
cfgov/core/tests/test_feature_flags.py
cfgov/core/tests/test_jinja2tags.py
cfgov/sheerlike/__init__.py

This change deprecates the use of Wagtail Site-based feature flags, instead using a new flag condition based on the value of `settings.DEPLOY_ENVIRONMENT`.
Two new feature flag conditions are defined: "environment is" and "environment is not". These can be set to match or not match against the value of `DEPLOY_ENVIRONMENT`, as the user prefers.
We currently set the value of this setting by environment variable, and it differs depending on the cf.gov environment. For example, this value is "production" in production, "beta" for beta.cf.gov, etc.
This change unblocks the cleanup of our legacy second Wagtail Site for content.cf.gov, which will simplify some workarounds that we have in the code.
As a related change, this also moves the inclusion of `flag_enabled` and `flag_disabled` in Jinja2 …

Add new environment-based feature flag condition

---

cfgov/cfgov/urls.py
requirements/optional-public.txt

This PR bumps the version of the optional retirement app (https://github.com/cfpb/retirement) from 0.6.2 to version 0.7.0. This new version adds support for Django 1.11, among other things.
This PR should be held until [retirement#225](https://github.com/cfpb/retirement/pull/225) has been merged, and a new 0.7.0 release has been made.
Because this new version isolates the retirement_api templates under a new "retirement_api" Django namespace, this upgrade requires a small change to urls.py to specify that namespace.
To test, verify that these URLs work when running locally:
- http://localhost:8000/consumer-tools/retirement/before-you-claim/
Go through the entire flow, verify that the API calls work. Also
verify that the "Where do these numbers come from?" link works properly
to go to the …

Bump retirement app to version 0.7.0

---

cfgov/jinja2/v1/_includes/atoms/checkbox.html
cfgov/jinja2/v1/_includes/eregs/regulations3k-search-bar.html
cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
cfgov/unprocessed/apps/regulations3k/js/search-utils.js
cfgov/unprocessed/apps/regulations3k/js/search.js
jest.config.js
test/unit_tests/apps/regulations3k/js/search-spec.js
test/unit_tests/apps/regulations3k/js/search-utils-spec.js

Uses `window.history.replaceState` to update the search results page's URL whenever a filter is changed.
Also fixes GHE issue 122 and uses `replaceState` to [cut the mustard](https://justmarkup.com/log/2015/02/cut-the-mustard-revisited/) (if a browser doesn't support `replaceState` it gets the no-JS experience).
1. Select some regs filters.
1. Verify that the browser's URL correctly updates to reflect your chosen filters.
1. Change the search term and hit enter.
1. The page should reload with the same regs filters pre-selected.

regs3k:  Update Regs3K search URL when filters are changed

---

docs/installation.md

- Adds missing file suffix to broken markdown link.

Fix link to usage doc

---

cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py

The Haystack queries had acquired some cruft, including defining the base query twice.
Unfortunately we can't get by with a single query, because we need to capture
counts for all regulations before narrowing down to the chosen regulation(s).
The best we can do with Haystack is avoid evaluating the big base query, so that we get a 
speedy page if the reg choices are narrowed down, which they will be by default.
I tried 'optimizing' by capturing the overall counts with a Counter object run against the 
base query, but that actually slows things down by evaluating the base query before its time.
It's actually faster to call `count()` on 11 individual Haystack queries, one for each reg.

regs3k: Clean up haystack query sequence.

---

cfgov/regulations3k/fixtures/parts.json
cfgov/regulations3k/parser/paragraphs.py
cfgov/regulations3k/regdown.py
cfgov/regulations3k/scripts/ecfr_importer.py
cfgov/regulations3k/tests/test_ecfr_importer.py
requirements/libraries.txt

QA testers identified some recurring format errors:
* Improper boldface on references such as **see** and **et seq.**
* Hyphens where em dashes should be.
* Interp graph references that didn't match the content (GHE issue 209)
* Some interp sections were not broken out in Reg X because of non-standard section naming.
This PR adjusts the importer and adds a paragraph linting routine to fix such cases.
Neither unicode nor html entities work as-is for passing an em dash character
from regdown to our templates, and either would sprinkle code through our regdown.  
To give editors a friendly way to handle em dashes, this PR adds a requirement for 
a Markdown extension,  `markdown-emdash`. It translates a triple hyphen 
--- a convention used in other flavors of Markdown and LaTex --- into an em …

regs3k: Lint paragraphs for italics and dashes.

---

Dockerfile

Currently the Python Docker container (that runs the Django code) installs the PostgreSQL 9 client. This is sufficient for using Postgres from Django, and for running `psql`, but fails with this error if you try to run `pg_dump` from inside the Python container:
```
$ pg_dump $DATABASE_URL
pg_dump: server version: 10.3 (Debian 10.3-1.pgdg90+1); pg_dump version: 9.2.23
pg_dump: aborting because of server version mismatch
```
@schbetsy and I discovered this while pairing.
This change upgrades the version of the Postgres client in the Python container to version 10. It follows the CentOS installation instructions from this page:
https://www.postgresql.org/download/linux/redhat/
To test, shut down and delete all running Docker containers:
```
$ docker-compose kill
$ docker-compose rm
```
and …

Update Python Docker container to use Postgres 10

---

cfgov/jinja2/v1/_includes/atoms/checkbox.html
cfgov/jinja2/v1/_includes/atoms/tag.html
cfgov/jinja2/v1/_includes/eregs/regulations3k-search-result-item.html
cfgov/regulations3k/jinja2/regulations3k/search-regulations-results.html
cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
cfgov/regulations3k/models/pages.py
cfgov/unprocessed/apps/regulations3k/css/reg-search.less
cfgov/unprocessed/apps/regulations3k/js/search.js
test/unit_tests/apps/regulations3k/js/search-spec.js

Adds `Showing X matches out of XXX total results` text per [GHE#106](https://github.cfpb.gov/eregs/regulations-3000/issues/106):
<hr>
Adjusts the tags that appear under search results per [GHE#113](https://GHE/eregs/regulations-3000/issues/113):
<hr>
Makes the search results page a little nicer on smaller screens by shortening `Regulation X` into `Reg X`:
1. Visit the regs3k search page and search for something.
1. Verify the above screenshots match your experience.

regs3k: Add results count to search header

---

cfgov/regulations3k/fixtures/tree_limb.json
cfgov/regulations3k/migrations/0010_rename_acquired_field.py
cfgov/regulations3k/models/django.py
cfgov/regulations3k/parser/payload.py
cfgov/regulations3k/tests/test_models.py
cfgov/regulations3k/wagtail_hooks.py

User testing raised some issues with sorting and labeling in Wagtail.
* Subparts were not properly ordered when a reg had more than one section subpart.
* The "acquired" column heading for EffectiveVersion was confusing.
* The "draft" column for EffectiveVersion was confusing (red meant active)
* If more than one version were active, the live version wasn't obvious.
In addition to fixing the subpart sorting, this patch creates a new "status" column
for effective verisons that will distinguish between live, draft, previous, and future versions. 
So a reg with versions in each state might look like this:
This patch includes a migration to rename the "acquired" field for EffectiveVersion, so first run the  migration:
```
./cfgov/manage.py migrate --noinput
```
Then:
- Dive into a reg with …

regs3k: Adjust admin sorting and labeling

---

cfgov/jinja2/v1/_includes/molecules/featured-menu-content.html

Updates the requested image size for Featured Menu Content images so that they're high-res on 2x displays.
- Calls the `original` rendition for FMC images instead of `width-270`
1. Pull branch
1. Ensure you have an FMC image uploaded locally
1. Reload a page
1. Inspect the image and see that it's using the original 540x300 image, scaled down to 270x150

Fix FMC image size for 2x displays

---

cfgov/.coveragerc
cfgov/regulations3k/copyable_modeladmin.py
cfgov/regulations3k/tests/test_copyable_modeladmin.py
cfgov/regulations3k/wagtail_hooks.py

This PR adds a button to the Effective Version admin to allow copying an effective version and all its subparts and their sections to another version, giving regulations content editors the ability to duplicate an effective version instead of creating a new one from scratch.

Regs3k: Add support for copying Effective Versions

---

requirements/libraries.txt

So we can restore sanity to the list of blocks in the select menus.
- Bump wagtail-inventory requirement to the latest release, 0.5
1. If using Docker, rebuild your Python container (`docker-compose build python`); if using virtualenv, `pip install -r requirements/local.txt`.
1. Open http://localhost:8000/admin/inventory/
1. Open one of the big select menus at the top
1. See all the blocks sorted nicely in alphabetical order

Bump wagtail-inventory to 0.5

---

cfgov/cfgov/settings/base.py
cfgov/unprocessed/apps/regulations3k/package-lock.json
cfgov/unprocessed/apps/regulations3k/package.json
cfgov/unprocessed/apps/regulations3k/webpack-config.js

Regs3K was experiencing some peculiar service worker behavior (it was caching wagtail admin pages). This PR migrates us away from the now sunset [sw-precache](https://github.com/GoogleChromeLabs/sw-precache/) to the new-and-improved [Workbox](https://developers.google.com/web/tools/workbox) via the official Google guidance.
It fixes the problem for me locally but we'll keep an eye on things to confirm it works for everyone. If the problem doesn't go away we can add a `runtimeCaching` rule that sets all `/admin/*` requests to `networkOnly` to force admin pages to skip cache.
Workbox comes with some nice localhost debugging features:
See [migration guide](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw) and …

Migrate from sw-precache to Workbox for service worker management

---

refresh-data.sh
requirements/optional-public.txt

Bump owning-a-home-api to the latest version. This adds django 1.11 compatibility to the satellite app.
Also, modify the `./refresh-data` script to use the `--fake-initial` flag when running migrations. This matches the functionality that already exists in our deploy scripts.
This is necessary because some tables (e.g. the `ratechecker` and `countylimits` tables used in the owning-a-home api) were created outside of django, but we have since updated to track those tables in django-migrations. When the `--fake-initial` flag is present, django will see that the tables already exist and will not try to re-create them, allowing the `refresh-data` script to run without issues.

Upgrade version of owning-a-home-api satellite app

---

cfgov/regulations3k/management/commands/update_regulation_index.py
cfgov/regulations3k/models/django.py
cfgov/regulations3k/scripts/ecfr_importer.py
cfgov/regulations3k/tests/test_models.py
cfgov/regulations3k/tests/test_search_indexes.py

regs3k: Update regulation indexing components
This makes minor changes to the indexing routine to better capture
duplicate paragraph IDs, which has proven useful for troubleshooting.
It also makes a minor change in the importer to remove stray line-endings
inside paragraphs caused by how eCFR renders fractions.
Using this code, indexing was run against cleaned data on build5, with these results:
```
16849 were created, 0 were unchanged, 0 were deleted, and 0 dupes were found
```
If you run it locally, you shouldn't notice much change, although you should encounter some dupes.
```
./cfgov/manage.py update_regulation_index
```

Regs3k indexing update

---

cfgov/jinja2/v1/_includes/eregs/regulations3k-secondary-navigation.html
cfgov/jinja2/v1/_includes/eregs/regulations3k-side-nav.html
cfgov/jinja2/v1/_includes/organisms/expandable.html
cfgov/unprocessed/apps/regulations3k/css/reg-navigation.less
cfgov/unprocessed/apps/regulations3k/css/reg-search.less
cfgov/unprocessed/apps/regulations3k/js/index.js

@jimmynotjim This adds the specific Regs3K secondary nav expandables functionality that we discussed yesterday. The changes below only affect Regs3K pages with the exception of the `hide_cue_label` option that I added to the expandable organism.
Instead of nesting expandables I faked it by having the outer container just show/hide the inner expandables when clicked.
I didn't want to push directly to your branch so this is a PR for your PR #4365.

Update Regs3K secondary nav expandable

---

cfgov/v1/tests/test_fragment_cache_extension.py

This commit adds additional unit tests for the Jinja {% cache %} template tag, and its support for multiple caches in #4384.

Add additional unit tests for fragment caching

---

cfgov/jinja2/v1/_includes/organisms/post-preview.html
cfgov/v1/__init__.py
cfgov/v1/fragment_cache_extension.py

This generalizes the fragment cache extension code slightly so that what was previously the `fragment_cache` (defined in the environment) is not hardcoded to use the `post_preview` cache.  Instead, we explicitly pass in the name of the cache in the template, and use that to look up the cache.  
The reason for this change is to support additional caches, so that we're not using `post_preview` for different types of fragment caching.  Specifically, @virginiacc will be using fragment caching on the mega menu template, so this PR will allow us to set up a new cache - whether it's a more generic cache or one specific to the mega menu, it needs to be separate from the current `post_preview` cache.
For more context, this is the PR in which fragment caching was introduced: …

Support multiple caches for fragment cache extension

---

cfgov/jinja2/v1/_includes/article.html
cfgov/jinja2/v1/_includes/macros/category-slug.html
cfgov/jinja2/v1/_includes/organisms/item-introduction.html
cfgov/jinja2/v1/_includes/organisms/post-preview.html
cfgov/jinja2/v1/_includes/tags.html
cfgov/jinja2/v1/activity-log/_activity-list.html
cfgov/jinja2/v1/ask-cfpb/answer-page.html
cfgov/jinja2/v1/ask-cfpb/landing-page.html
cfgov/jinja2/v1/events/_event-detail.html

See GHE/CFGOV/platform/issues/2825 for bug report. 
This fixes a bug introduced by https://github.com/cfpb/cfgov-refresh/pull/3596, in which certain information on a post preview (such as the icon displayed) was getting cached across blog and newsroom pages, which displayed the icon differently, and with no way to differentiate.  This PR resolves it by moving that logic out of the cache.  
I also identified another issue where the author URLs were incorrectly getting cached, and this PR resolves it by ensuring a relative link is used on the blog and newsroom pages since it's unnecessary to pass in an absolute URL. 
First, to view the bug locally, check out the `master` branch locally and run it with the cache enabled, e.g. `ENABLE_POST_PREVIEW_CACHE=1 ./runserver.sh`. You do not need to …

Fix post preview cache

---

cfgov/templates/wagtailadmin/css/general-enhancements.css

Fix alignment of multiple choice field labels.
- CSS to fix alignment of multiple choice field labels.
1. In the Wagtail admin, create a new page using the TDP Activity search page type.
2. Create a new child page of the newly created TDP Activity search page.
3. Look at the Topic field.
- We’re duplicating the following CSS in Wagtail’s core.css to also apply multiple field labels, which I believe come from the `django/mptt` library we recently added for TDP.
```
.choice_field .input li label, 
.model_multiple_choice_field .input li label {
display: block;
width: auto;
float: none;
padding-top: 0;
}
```
- @Scotchester

Fix alignment of multiple choice field labels

---

cfgov/regulations3k/regdown.py
cfgov/regulations3k/tests/test_regdown.py
cfgov/regulations3k/tests/test_resolver.py

There doesn't seem to be a clean way to clear markdown extension config options in between tests, so this change is to always use the default block renderer (instead of another custom one) in all tests when testing things that are not the block renderer support.
This should stop some inconsistent test failures we were seeing in the resolver tests (the ultimate cause of those failures is still something I'm troubleshooting, but new tests should be written to test for that).

Regulations 3000: Enforce using the default block renderer in regdown/resolver tests

---

gulp/tasks/audit.js

Lighthouse module is run from within node_modules, so the module doesn't need to be referenced in the audit script.
- Removes unused reference to `lighthouse` module.
1. `gulp audit:perf` should run.

Remove unused reference

---

cfgov/regulations3k/jinja2/regulations3k/regulations-listing.html
cfgov/regulations3k/tests/test_blocks.py

The changes in #4395 added a new `RegulationsList` block that included a `more_regs_page` field that can be used to select a Wagtail page to link to for a full set of regulations. The template for the block erroneously refers to `more_regs_url`.
This commit fixes that error and properly provides a value for the page for the existing unit tests. It also fixes the block template to properly refer to block fields using `value.attribute`. See Wagtail
documentation here:
http://docs.wagtail.io/en/v2.1.1/topics/streamfield.html#template-rendering

Regs3k: Fix reference to more regs link

---

cfgov/jinja2/v1/_includes/organisms/expandable.html

Found a typo from yesterday's big expandables PR. The current code erroneously results in `<span class="u-visually-hidden-on-mobile class=u-visually-hidden">`.
- Fix `value.hide_cue_label` output.

Fix expandable cue label

---

cfgov/cfgov/settings/base.py

Currently, an email signup breaks silently because the request to GovDelivery is blocked by CSP. This should fix that by adding the domain to the CSP list.
- Adds `public.govdelivery.com` to CSP connect list

Add govdelivery to CSP allow list

---

cfgov/cfgov/settings/base.py

The `regulations3k` app is part of this repository and so is not optional. Its dependency `treemodeladmin` is also not optional. This change moves these apps into `settings.INSTALLED_APPS`.
In future it would be nice to more properly sort and order the list of apps, but I have kept the scope of this PR as small as possible.

Make regulations3k a required Django app

---

cfgov/v1/tests/test_fragment_cache_extension.py

This change fixes the unit test `v1.tests.test_fragment_cache_extension.TestFragmentCacheExtension.test_cache_gets_called_when_visiting_filterable_page`.
For some reason defining the cache outside of the test case can sometimes cause the mock to not work as expected if the unit tests are run in a certain order.
Defining the cache inside the test does work - this might be because if defined outside the cache gets accessed at module import time, but I'm not sure why this would cause mocking to work differently.
Either way this change makes the tests work in any order.

Fix fragment cache unit test

---

cfgov/core/middleware.py
cfgov/core/tests/test_management_inactive_users.py
cfgov/core/tests/test_middleware.py
cfgov/core/tests/test_missing_migrations.py
cfgov/core/tests/test_views.py
cfgov/core/utils.py

The `parse_links` updates introduced some test failures when running the tests on Python 3 because of `bytes`/`str` differences in Python 2 and 3 (Django's `response.content` is `bytes` on Python 3). Because `parse_links` is done in middleware now this caused unrelated tests that use the Django test client to fail on Python 3 (like `regulations3k`, where @higs4281 and I have been trying to maintain Python 3-compatibility). This PR fixes that by decoding/encoding the `response.content` using the `response.charset`.
While I was in `cfgov/core`, I also updated the rest of the tests that were failing on Python 3 so that they will pass too, to get one more corner of cfgov-refresh ready for the inevitable.

Fix `parse_links` middleware so that Python 3 tests pass

---

requirements/libraries.txt

Yesterday django-taggit released a new version (0.23.0) that is incompatible with Django <1.11:
https://github.com/alex/django-taggit/blob/master/CHANGELOG.txt#L6
django-taggit is normally pulled in by Wagtail's setup.py, but unfortunately in the version of Wagtail we are on (1.13.2) the setup.py specifies `>=0.20,<1.0`, which pulls in this incompatible version:
https://github.com/wagtail/wagtail/blob/v1.13.2/setup.py#L26
Edit to add: this manifests itself in failing unit tests with the error message `ImportError: cannot import name lazy_related_operation`.
This change pins django-taggit to its previous version (0.22.2) to retain Django compatibility. This line should be removed once we upgrade to Django 1.11.
Edit again: l've opened …

Pin django-taggit for Django version compatibility

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

This removes the settings condition from the REGULATIONS3K flag so that
it can be flipped on by environment via the admin.
The plan is that we can use `environment is not` ... `production` to allow
regs3k URLs to be active on dev servers and on Beta, for user testing and
for a pilot run of the new app. But the flagged URL will return 404
on production for any regs3k page.
You can test this locally by using the Wagtail admin to add the 'environment is not' ... 'production'
condition to the REGULATIONS3K flag. This should allow the regs3k pages
to render locally (unless you have a local evironment variable set to
`DEPLOY_ENVIRONMENT=production`).
Set or unset the flag and visit:
<http://localhost:8000/policy-compliance/rulemaking/regulations/>
If you add no flag, the pages should also …

Regs3k: Use flag to disable URLs in production

---

cfgov/regulations3k/jinja2/regulations3k/landing-page.html
cfgov/regulations3k/jinja2/regulations3k/recent-notices.html
cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py
cfgov/unprocessed/apps/regulations3k/js/index.js
cfgov/unprocessed/apps/regulations3k/js/recent-notices.js
cfgov/unprocessed/apps/regulations3k/js/regs3k-utils.js
cfgov/unprocessed/apps/regulations3k/js/search-utils.js
cfgov/unprocessed/apps/regulations3k/js/search.js
test/unit_tests/apps/regulations3k/js/recent-notices-spec.js
test/unit_tests/apps/regulations3k/js/regs3k-utils-spec.js
test/unit_tests/apps/regulations3k/js/search-utils-spec.js

Adds recent notices to landing page's sidebar via AJAX. They are pulled from the federalregister.gov API. Unfortunately, their API has no `Access-Control-Allow-Origin` header so we can't have the browser fetch the data directly from them (eregs uses a [JSONP hack](https://github.com/cfpb/regulations-site/blob/092bd0ef21a78b7bbabb019953adff6c70953f34/regulations/static/regulations/js/landing.js#L18)). Instead, we set up a cf.gov view to proxy the data to the front-end.
- `regulations/recent-notices-json/` route
- `recent-notices.js` file that fetches JSON from the above view
- I moved the regs3k `fetch` utility into its own file to share it across the app.
1. Visit http://localhost:8000/policy-compliance/rulemaking/regulations/ and see if the recent regulations appear
- …

Regs3K: Add recent notices to landing page

---

cfgov/v1/tests/test_wagtail_hooks.py
cfgov/v1/wagtail_hooks.py

This commit removes our custom page link handler that makes it so that all Wagtail page URLs inserted into rich text fields are always relative.
It reverts behavior restored in #2904.
As of #4367 we no longer maintain two distinct Wagtail Sites, and so this behavior is no longer needed.
Thanks to @richaagarwal for pointing out this legacy code.

Remove custom Wagtail relative page link handler

---

cfgov/v1/jinja2tags/datetimes.py

This PR adds an import for [`six.string_types` as `basestring`](https://pythonhosted.org/six/#six.string_types) to our `v1.jinja2tags.datetimes` module to ensure that its use of `basestring` doesn't cause errors when running tests that use the Django test client on Python 3.

Fix v1.jinja2tags.datetimes for running tests on Python 3

---

cfgov/regulations3k/blocks.py
cfgov/regulations3k/tests/test_blocks.py

This PR makes two small fixes to the regulation list on the regulations landing page:
- Ordering is now done by regulation page title, which should follow the CFR part number ordering
- The regulations list will no longer list Regulation Page objects that exist but have never been published.

Regs3k: Fix regulation list ordering and ensure only live pages get listed

---

cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py

This PR fixes the Regulation page breadcrumbs to include parents above its  Regulation Landing page parent. It also removes the subpart from the breadcrumb entirely.

Regs3k: Fix breadcrumbs

---

cfgov/unprocessed/apps/owning-a-home/css/form-explainer.less

A little code review fix that didn't get fully tested slipped into the PR that updated all the expandables, causing giant text and icons in the Form Explainer expandables.
- Correctly calculate size of text and icons in Form Explainer expandable labels
1. Pull branch
1. Run the server
1. Go to http://localhost:8000/owning-a-home/loan-estimate/ and see appropriately-sized expandable labels on the right side.

Fix sizing mistake in Form Explainer styles

---

cfgov/jinja2/v1/_includes/organisms/featured-content.html
cfgov/jinja2/v1/sublanding-page/index.html

This commit fixes an issue introduced by #4380 that introduced more strict requirements on page/block templates using the "request" context variable.
The `video-player.html` template [requires this variable](https://github.com/cfpb/cfgov-refresh/blob/481c446afd5439683e094df69b51c5f2905f4e3b/cfgov/jinja2/v1/_includes/macros/video-player.html#L45), but wasn't being loaded with context. This change fixes that.
To test, use a production dump and visit http://localhost:8000/practitioner-resources/library-resources/ as an example page using the video player. This will load successfully, unlike on master where you will get a 500 error.

Properly pass Jinja2 template context to video player

---

cfgov/cfgov/urls.py
requirements/optional-public.txt

Releasing improvements to the TDP Activity detail page and initial search page development behind a feature flag.
- Removed unused urls.py feature flag and added it directly to the routable SearchIndexPage
- Bumped TDP from release 1.0.8 to 1.0.9

Bump TDP release to 1.0.9

---

cfgov/cfgov/settings/base.py
requirements/libraries.txt

This PR updates Wagtail-Flags to 3.0.0 and adds the new dependency Django-Flags 3.0.0.
To make it possible to use our feature flag library independently of Wagtail, we've isolated the Wagtail-specifics in [Wagtail-Flags](https://github.com/cfpb/wagtail-flags) and put all the general-purpose Django code in [Django-Flags](https://github.com/cfpb/django-flags). There is no change to the feature flag functionality in these releases, just changes to the way the code is organized. https://github.com/cfpb/wagtail-flags/pull/29 explains the changes.
1. Checkout this `django-wagtail-flags` branch
2. Install Django-Flags and Wagtail-Flags:
- Docker:
1. `./shell.sh`
2. `pip install wagtail-flags==3.0.0`
- Standalone local virtualenv:
1. Activate your virtualenv (i.e. `workon cfgov-refresh`)
2. `pip …

Add Django-Flags requirement and bump Wagtail-Flags

---

cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py

This PR makes some changes to the `RegulationPage` to allow us to view more than just the current effective version of a regulation. It does that by adding an optional date component to the URL pattern for the section page and index page. 
With this change, the following URLs have the following results:
- `/policy-compliance/rulemaking/regulations/1002/`: Reg B landing page with links to sections in the currently effective version
- `/policy-compliance/rulemaking/regulations/1002/2018-01-01/`: Reg B landing page with links to sections in the 2018-01-01 version explicitly
- `/policy-compliance/rulemaking/regulations/1002/02`: Section 2 of the currently effective version of Reg B
- `/policy-compliance/rulemaking/regulations/1002/2018-01-01/02`: Section 2 of the 2018-01-01 version of Reg B …

Regs3k: Support viewing multiple effective versions

---

requirements/optional-public.txt

Bump TDP release from 1.0.10 to 1.0.11
- Added missing templates/* directory to the whl
- Enforcing feature flag on the Haystack search index file
@chosak @Scotchester @willbarton @higs4281

Bump TDP version to 1.0.11

---

cfgov/core/middleware.py
cfgov/core/tests/test_middleware.py

Fixes a bug introduced in https://github.com/cfpb/cfgov-refresh/pull/4363, which refactored `parse_links` and removed a call to `expand_db_html`.   As a result, I had added a call to the `richtext` filter [here](https://github.com/cfpb/cfgov-refresh/pull/4363/files#diff-6a8e044564accdfeb5d0bd4c115b59afL52) but as reported in GHE/CFGOV/platform/issues/2956, this is not comprehensive.  
- Instead of adding several `richtext` calls across templates, which I believe would be hard to maintain for the same reasons our previous usage of `parse_links` was, I thought it would be best to add back in the call to `expand_db_html`.  
- We'll want to do some additional clean-up if we go with this approach, which is removing any template calls to `richtext`, since those would no longer be needed.  I'd …

Parse links middleware fix: Add back expand_db_html call

---

cfgov/legacy/templates/common/reset_password_email.html
cfgov/templates/wagtailadmin/account/password_reset/email.txt

Changes password reset link from `http` to `https`.
We still need to figure out why `domain` is returning the site plus `:443`, but until then we will include the instructions to remove it in the password reset email.
1. Open your local instance and go to the password reset page
- e.g. http://0.0.0.0:8000/admin/password_reset/
1. Enter your email address and click the `reset password` button
1. Check your console - an email will have printed there
1. Check that the email includes a note about `:443` and `https`

Change to https, adds note about domain

---

cfgov/jinja2/v1/browse-basic/index.html
cfgov/jinja2/v1/browse-filterable/index.html
cfgov/jinja2/v1/newsroom/index.html
cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html

This change was made on Sublanding Pages in #4429 but also needs to be applied on these templates.
- Updates Browse, BrowseFilterable, Newsroom, and BrowseRegulation templates to pass the context into the FCM macro
1. Visit http://localhost:8000/about-us/careers/application-process/ and see a 500
1. Pull branch
1. http://localhost:8000/about-us/careers/application-process/, play the video, and see it working properly

Fix missing context in FCMs, part 2

---

cfgov/v1/tests/views/test_documents.py

This change fixes a unit test which is now failing in #4419. Note that this is a PR to that PR's branch (`no-s3-overwrite`). It more appropriately tests our custom `v1.views.documents.DocumentServeView` logic in isolation without relying on S3-specific behavior.
1. `tox v1.tests.views.test_documents`

Better unit test for DocumentServeView

---

cfgov/cfgov/settings/base.py
cfgov/v1/tests/views/test_documents.py

Per decision in GHE/CFGOV/platform/issues/2750, we will no longer (theoretically) allow files to overwrite files of the same name when being uploaded to S3 via Wagtail's Documents and Image libraries. (This has been broken since the upgrade to 1.13, anyway.)
- Django setting of `AWS_S3_FILE_OVERWRITE = False`
Not 100% sure how to test this, but I think @chosak knows how.

Stop overwriting when uploading files to S3 that already exist

---

cfgov/regulations3k/jinja2/regulations3k/inline_interps.html
cfgov/unprocessed/apps/regulations3k/css/reg-inline-interpretations.less

A couple of small fixes to inline interpretation styles to match the designs
- Style the header as paragraph (instead of an `h4`)
- Adjust bottom padding to 15px (instead of 30px)
- Adjust bottom margin to 30px (instead of 15px)
1. Fire up Regulations 3000 as you normally do
2. Go to any regulations section with inline interpretations, like `/policy-compliance/rulemaking/regulations/1005/2/`
3. Verify that:
- The text in `.o-expandable_label` is 16px Avenir Next 500
- There's 15px of padding at the bottom of the expandable
- There's 30px of margin between the bottom of an expandable and the subsequent paragraph
- This PR only fixes the styles of the inline interpretation. We may want to consider changing the markup to make `.o-expandable_label` something more semantic than a `span`, but …

Fix inline interpretation styles in regulations

---

requirements/wagtail.txt

Fixes incompatibility reported in https://github.com/wagtail/wagtail/issues/4725.
Following the instructions in that that issue as reported by @chosak, but with 1.13.3 swapped for 1.13.2 should report no errors.

Bump Wagtail to 1.13.3

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/settings/test_nomigrations.py
cfgov/cfgov/urls.py
cfgov/v1/wagtail_hooks.py
requirements/libraries.txt

Currently when trying to run Python unit tests against Django 1.11, for example with this command:
`tox -r -e unittest-py27-dj111-wag113-slow`
the test runner command fails immediately, before any tests are run. This change fixes a few things that are incompatible with Django 1.11, which allows the test command to run, and individual test failures to be reported. This does not actually make the tests work, but at least lets them run.
All tests continue to pass with Django 1.8.
Specific changes are:
- As of 1.9, the use of `settings.MIGRATION_MODULES` to disable migrations has changed, and so our logic in cfgov.settings.test_nomigrations must as well. See Django docs at https://docs.djangoproject.com/en/2.1/releases/1.9/#migrations.
- As of 1.10, support for string view paths to `url()` …

Support running unit tests against Django 1.11

---

cfgov/core/tests/test_management_inactive_users.py

Some unit tests were failing under Django 1.11 because they were testing whether email was being sent to users that didn't have email addresses. In Django 1.8, emails can be (improperly) sent to users with empty string addresses. This was fixed in https://github.com/django/django/pull/7535, which made it into Django 1.11. Because these tests didn't properly provide email addresses for users, they start to fail on Django 1.11.
To test, run:
```
tox -e unittest-py27-dj111-wag113-fast core.tests.test_management_inactive_users
```
On this branch, all 11 of these tests will pass. On master, 3 of these tests will fail.

Fix email-related tests that fail on Django 1.11

---

cfgov/jinja2/v1/_includes/organisms/expandable.html

Fix button within expandable Jinja template to allow it to work within forms. 
Since the button element defaults to `type="submit"` anytime an expandable button is clicked within a form it submits that form even though it has nothing to do with that form. By setting the type to button it no longer automatically submits the form.
You can see an example of this behavior on the eregs search page: https://beta.consumerfinance.gov/policy-compliance/rulemaking/regulations/search-regulations/results/?q=test&regs=1002&results=25&order=relevance
- Add `type="button"` to the button element within the expandable Jinja template
- @Scotchester

Fix expandable button type

---

.env_SAMPLE
cfgov/cfgov/settings/local.py

It was unclear to me that a setting in the local Django settings was preventing me from testing the GovDelivery integration on my local machine. It looked like all I needed to do was set my env vars, but no!
This PR updates the setting in `local.py` to only be set if the `GOVDELIVERY_BASE_URL` env var has _not_ been set.
- `GOVDELIVERY_API` setting that mocks the API locally is only set if `GOVDELIVERY_BASE_URL` env var is not set
Can't test it without some credentials, so contact me for a walkthrough if you want to see it in action.

Only set mock GovDelivery API if GOVDELIVERY_BASE_URL is not set

---

cfgov/cfgov/settings/base.py

For now, will allow the http-endpoint access to files.cf.gov for loading chart data on `build`.
This should be removed in the future when we move to https on `build`. I left a comment to that effect.
- Remove this endpoint once https://github.com/cfpb/cfpb-chart-builder/pull/126 is merged.

Add the http endpoint for CCT charts

---

cfgov/regulations3k/jinja2/regulations3k/inline_interps.html
cfgov/unprocessed/apps/regulations3k/js/analytics.js
cfgov/unprocessed/apps/regulations3k/js/index.js
test/unit_tests/apps/regulations3k/js/analytics-spec.js

This migrates analytics tracking from [regulations-site](https://github.com/cfpb/regulations-site) to Regs3K. The majority of the events tracked by eRegs are no longer relevant:
- ~~`link:followCitation`~~
- `interpexpandables:open` (migrated)
- `interpexpandables:close` (migrated)
- ~~`definition:open`~~
- ~~`definition:followCitation`~~
- ~~`searchVersion:change`~~
- ~~`drawer:switchTab`~~
- ~~`drawer:open`~~
- ~~`drawer:close`~~
- ~~`sxs:open`~~
- ~~`sidebarexpanable:open`~~
- ~~`sidebarexpanable:close`~~
- `toc:click` (migrated)
We can track more events if desired if anything surfaces in GHE#287. All the standard cf.gov metrics like unique sessions, referral URLs, pageviews, etc. are automatically tracked alongside any custom events we add.
- `regs3k/analytics.js` file to assist with …

Regs3k: Migrate Google Analytics events

---

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html
cfgov/regulations3k/jinja2/regulations3k/inline_interps.html
cfgov/regulations3k/jinja2/regulations3k/landing-page.html
cfgov/regulations3k/jinja2/regulations3k/regulations-listing.html
cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
cfgov/regulations3k/models/pages.py
cfgov/unprocessed/apps/regulations3k/css/main.less
cfgov/unprocessed/apps/regulations3k/css/reg-listing.less
cfgov/unprocessed/apps/regulations3k/css/reg-navigation.less

Some improvements to the Regs3K landing page and secondary nav. See [GHE#325](https://[GHE]/eregs/regulations-3000/issues/325).
1. View the Regs3K landing page and confirm it matches the screenshot below (and no longer looks like what's on beta).

Improve Regs3K landing page

---

cfgov/data_research/forms.py
cfgov/data_research/handlers.py
cfgov/data_research/jinja2/data_research/conference-registration-form.html
cfgov/data_research/research_conference.py
cfgov/data_research/tests/management/commands/test_conference_export.py
cfgov/data_research/tests/management/commands/test_conference_notify.py
cfgov/data_research/tests/test_blocks.py
cfgov/data_research/tests/test_forms.py
cfgov/data_research/tests/test_handlers.py
cfgov/data_research/widgets.py
cfgov/unprocessed/css/organisms/form.less

We'll be registering folks for a new type of conference soon. Here are some changes to the existing conference registration functionality that will be needed for that.
- New radio field for whether attending in person or virtually
- Sets the form up to still allow virtual registration once in-person
capacity has been reached
- Hides `sessions` field, which is not needed for this conference
- Fixes a couple styling issues related to margins & padding
1. Pull branch
1. Add a Conference Registration Form to a Browse Page with a capacity of 1
1. Fill in the message fields so you know what they are when they appear on the page
1. Submit a virtual attendee registration and see that you can still register a physical attendee
1. Register a physical attendee and see that you can no longer register …

Modify conference registration form for FinEx conf

---

requirements/optional-public.txt

Bump TDP release to 1.0.12 
Please run "manage.py update_index -r teachers_digital_platform" after it is deployed to build.
- @Scotchester @willbarton @higs4281 @chosak

Bump TDP release 1.0.12

---

cfgov/regulations3k/migrations/0015_rename_regpage_part_related_field.py
cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_hooks.py
cfgov/regulations3k/wagtail_hooks.py

This PR adds a button to the Regulations3k Section model admin to allow a user to view or preview a section whether the effective version it belongs to is live or not. This uses the functionality added in #4426 to allow for viewing an effective version that is not yet live if the user has permission to edit the regulation page.

Regs3k: Preview sections from the admin

---

cfgov/data_research/forms.py
cfgov/data_research/widgets.py
cfgov/unprocessed/css/organisms/form.less

The conference registration form block currently makes use of some Python code that customizes how its field widgets are rendered, to make them compatible with Capital Framework.
Unfortunately, the hooks that this code (primarily in `cfgov/data_research/widgets.py`) used are no longer compatible with Django 1.11. As part of our Django 1.8 -> 1.11 upgrade, this PR removes
this customization, instead falling back on the standard widget rendering for checkboxes and radio buttons (we can still keep our customizations for text/email inputs and Textareas).
Some additional CSS styling is added to improve the look of these buttons. Unfortunately this is no longer compatible with CF.
To test, create a BrowsePage in Wagtail and then add a Conference Registration Form block to the Content field. Add …

Remove Django 1.11-incompatible form widget code

---

cfgov/core/scripts/missing_migrations.py
cfgov/core/tests/test_missing_migrations.py

- Updates `missing_migrations.py` to handle both Django 1.8 and 1.11 (where it used to only handle 1.8, and would always fail on 1.11). 
To test locally, pull down this branch and:
1. Make a change to a django model (for example, changing a default value for a model field in `cfgov/vi/models/base.py`)
2. Run `tox -e missing-migrations-py27-dj111-wag113`
3. Run `tox -e missing-migrations-py27-dj18-wag113`
On both commands, you should see an error message like this:
```
Missing migrations found:
Migrations for 'v1':
v1/migrations/0121_auto_20180821_1818.py
- Alter field shared on cfgovpage
ERROR: InvocationError: '/Users/lortone/dev/cfgov-project/cfgov-refresh/cfgov/manage.py runscript missing_migrations'
```
If you discard the model change and re-run those commands, both Tox commands …

Missing Migrations script now handles Django 1.11

---

cfgov/cfgov/settings/base.py
cfgov/data_research/mortgage_utilities/s3_utils.py
cfgov/data_research/tests/test_s3_utils.py
cfgov/v1/s3utils.py
cfgov/v1/tests/test_meta_image.py
cfgov/v1/tests/test_s3utils.py
requirements/libraries.txt
requirements/scripts.txt
tox.ini

These set of changes change the AWS S3 package used by this project to boto3 from boto. See this post discussing differences:
https://boto3.readthedocs.io/en/latest/guide/migration.html
Generally, boto3 is a more modern library which is better maintained.
Direct uses of boto have been replaced with boto3, and relatedly this change modifies the django-storages backend to use its boto3 backend. The django-storages dependency has been bumped in version from 1.1.8 to 1.5.0; unfortunately we cannot yet use the most recent version, see
`requirements/libraries.txt` for an explanation.
Some of the Django settings have been simplified or ordered alphabetically related to this change. Specifically, we previously used an `AWS_S3_ROOT` environment variable to set an `AWS_S3_ROOT` setting that was …

Use boto3 instead of boto for Django 1.11 compatibility

---

requirements/optional-public.txt

Bump TDP release to 1.0.13
Please run "manage.py update_index -r teachers_digital_platform" after it is deployed to build.
- @Scotchester

TDP bump release to 1.0.13

---

package.json

`dom-delegate` was added in https://github.com/cfpb/cfgov-refresh/pull/4365, but appears to be unused.
- Removes `dom-delegate` dependency.
- `./frontend.sh` should pass.

Remove dom-delegate

---

requirements/libraries.txt

`djangorestframework` 3.6.4 is the latest version that supports both Django1.8 and 1.11. 
This is part of our preparation for upgrading cfgov-refresh to Django 1.11.
- Updates library version: djangorestframework. Doesn't change any behavior.
Doesn't change any cf.gov functionality..

Upgrade djangorestframework to support Django 1.11

---

cfgov/v1/migrations/0116_single_wagtail_site.py

The cfgov/v1/migrations/0116_single_wagtail_site.py file seems to have had a mix of tabs and spaces. This PR replaces the tabs with spaces.

Replace tabs with spaces

---

cfgov/regulations3k/migrations/0016_require_effective_date.py
cfgov/regulations3k/models/django.py
cfgov/regulations3k/tests/test_hooks.py
cfgov/regulations3k/tests/test_models.py
cfgov/regulations3k/wagtail_hooks.py

This PR makes two changes related to our previewability of effective versions:
- Effective versions that are created through the admin now validate the uniqueness of their effective dates within their part. This means a user cannot create two effective versions in the same part with the same effective date.
- The "Preview" button sections will now either say "View Live" for sections that belong to the "Live" effective version or "View Draft" for sections that belong to a non-live effective version.

Regs3k: Preview iteration

---

requirements/libraries.txt

Allows https://github.com/cfpb/teachers-digital-platform to be included in cfgov-refresh without a separate `pip install`.

Adds django-mptt to libraries.txt

---

requirements/optional-public.txt

This fixes a library incompatibility issue between cfgov-refresh and
retirement. cfgov-refresh requires djangorestframework 3.6.4 (in order
to support both django 1.8 and 1.11). requests was requiring
django-filters 0.9.2, which is incompatible with drf 3.6.4. This version
bump removes that django-filters dependency.
- retirement `0.7.0` -> `0.7.1`
Doesn't affect any cfgov-refresh functionality.

Upgrade retirement satellite app to 0.7.1

---

cfgov/v1/forms.py

Our `v1.forms.FilterableListForm` form class has a custom method `render_with_id` that renders a form field with a custom `id` attribute. This is used in templates like this:
`{{ form.render_with_id(form.field_name, desired_field_id) }}`
instead of using the default
`{{ form.field_name }}`
This adds an `id="desired_field_id"` when the form's `<input>` tag is rendered.
The existing code is incompatible with Django 1.11 due to this change:
https://docs.djangoproject.com/en/1.11/ref/forms/widgets/#django.forms.Widget.render
In Django 1.11, the signature for the `Widget.render` method was changed to add another parameter.
This commit modifies the code to be more generic and handle both method signatures.
To verify that this still works, you can run a local server using a production dump and …

Add Django 1.11 support to custom field id render

---

cfgov/alerts/logging_handlers.py
cfgov/alerts/tests/test_logging_handlers.py

Django 1.9 modified some of the code used to generate error messages:
https://docs.djangoproject.com/en/dev/releases/1.9/#httprequest-details-in-error-reporting
We currently rely on some of this code to generate the alert error messages that we log to SQS. In order to make this code compatible with Django 1.11 (and fix a failing unit test), this PR pulls forward the Django 1.8 methods that were used.
This change also adds some additional unit tests to ensure 100% code coverage of the methods that were pulled in.
To run relevant tests against Django 1.8 and Django 1.11:
`tox -e unittest-py27-dj18-wag113-fast alerts.tests.test_logging_handlers.TestLoggingHandlers`
`tox -e unittest-py27-dj111-wag113-fast alerts.tests.test_logging_handlers.TestLoggingHandlers`

Add Django 1.11 support to custom alert logging

---

cfgov/agreements/tests/test_legacy.py
cfgov/ask_cfpb/tests/models/test_pages.py

Running the Python tests against Django 1.11 (using the test command `tox -e unittest-py27-dj111-wag113-fast`) was generating a BeautifulSoup-related warning message:
```
/Projects/cfgov-refresh/.tox/unittest-py27-dj111-wag113-fast/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
The code that caused this warning is on line 11 of the file /Users/chosaka/Projects/cfgov-refresh/.tox/unittest-py27-dj111-wag113-fast/bin/coverage. To get rid of this warning, change code that looks like this:
BeautifulSoup([your …
```

Fix BeautifulSoup-related test warnings in Django 1.11

---

package-lock.json
package.json

Brings in latest chart builder, which changes default behavior of y-axis values.
- Bump `cfpb-chart-builder` to `3.5.0`.
1. Run `./frontend.sh`
2. Log into local wagtail.
3. Create a new Browse page.
4. Add a ChartBlock.
5. Add required fields (set `consumer-credit-trends/auto-loans/inq_data_AUT.csv` as data source).
6. Save and preview and see that the y-axis values are integers. (If y-axis values are still millions or billions, inspect the page and reload to not use the cache.)

Bump cfpb-chart-builder to 3.5.0

---

cfgov/cfgov/settings/test_nomigrations.py
cfgov/core/tests/test_utils.py
cfgov/core/utils.py

PR #4444 (014df5a7) attempted to add the ability to run Python tests against Django 1.11, but did not properly disable migrations when running with `settings.test_nomigrations`.
This commit fixes testing without migrations (e.g. with `tox -e unittest-py27-dj111-wag113-fast`) in Django 1.11.
To test this change, you can run that command and notice how much faster the tests run, because the migrations aren't being run.

Properly disable migrations in Django 1.11

---

cfgov/cfgov/settings/base.py

Per the overextends documentation at https://github.com/stephenmcd/django-overextends, we need to add the overextends tags to the base Django settings in order to be able to use the `overextends` tag in templates.
These URLs raise 500s on Django 1.11 on master but work with this PR:
http://localhost:8000/login/
http://localhost:8000/django-admin/

Add Django 1.11 support for use of overextends

---

cfgov/cfgov/urls.py

We erroneously include the Django admin URLs twice in our main URL file (lines [444](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/cfgov/urls.py#L444) and [461](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/cfgov/urls.py#L461)). On Django 1.11 this results in the following warning:
> ?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace
This commit removes the second definition. You can confirm that the Django admin URLs still work locally by visiting http://localhost:8000/django-admin/ with a local server (although note this will require the change in #4474 to work properly).

Remove duplicate definition of Django admin URLs

---

cfgov/scripts/test_data.py
cfgov/v1/tests/models/test_author_names.py
cfgov/v1/tests/models/test_related_posts.py
cfgov/v1/tests/models/test_snippets.py
cfgov/v1/tests/test_filterable_list_form.py

Previously, running unit tests on Django 1.11 produced the following warning:
```
.tox/unittest-py27-dj111-wag113-fast/lib/python2.7/site-packages/unidecode/__init__.py:47:
RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing
an encoded string will likely have unexpected results.
_warn_if_not_unicode(string)
```
The warning occurred when adding authors and tags (fields provided by
django-taggit) on instances of CFGOVPage in tests, e.g.
`page.authors.add('unencoded string')`.
To prevent this, we use `from __future__ import unicode_literals` where
possible. It was not possible in one test file that contains tests for
unicode conversion. So, in that file, we explicitly use unicode strings
in the tests that are affected by the warning.
[Short description explaining the …

Silence runtime warning in tests on dj111

---

cfgov/unprocessed/css/organisms/read-more.less

"Read More" expandables (which collapse the bulk of the content of certain pages, such as Ask CFPB answers and job postings, on small screens) were showing as collapsed when printing the page. See https://GHE/CFGOV/platform/issues/2965
This PR addresses that.
- Restricts media query in `read-more.less` to `screen` only (note the change to an explicit `@media` directive instead of our `respond-to-` mixin), to ensure that they are open when printed.
1. Visit any Ask CFPB answer in Chrome
1. Activate the print function and see the "read more" expandable _collapsed_ in the preview
1. Pull branch
1. Hard refresh the answer page
1. Activate the print function and see no sign of the "read more" expandable in the preview
- This is a **Tier 1** bugfix. I have to leave for the …

Fix the printing of Read More expandables

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

This PR will disable the eRegulations URLs if the `REGULATIONS3K` feature flag is on. 
This will allow us to create and test redirects from eRegulations to Regulations3k.
Not difficult, per se, but cumbersome. These instructions *should* work in either Docker or local venvs (I think).
1. Install `regulations-core` and `regulations-site`:
```
pip install https://github.com/cfpb/regulations-core/releases/download/1.2.6/regcore-1.2.6-py2-none-any.whl
pip install https://github.com/cfpb/regulations-site/releases/download/2.2.5/regulations-2.2.5-py2-none-any.whl
```
2. Add `EREGS_API_BASE` to your .env file:
```shell
export EREGS_API_BASE=http://localhost:8000/eregs-api/
```
3. Check out https://github.com/cfpb/regulations-stub/ to get some data to load
4. Load data:
```shell
./cfgov/manage.py …
```

Disable eRegs if the REGULATIONS3K flag is turned on

---

cfgov/regulations3k/fixtures/reg_d.regml
cfgov/regulations3k/migrations/0017_set_default_created_date.py
cfgov/regulations3k/models/django.py
cfgov/regulations3k/scripts/regml_importer.py
cfgov/regulations3k/tests/test_regml_importer.py

This PR adds a Django script to import a single RegML file as a Regulations3k EffectiveVersion with all the appropriate child models.
This is an initial attempt, and the output should be considered a work-in-progress. It's likely some hand-editing of the resulting Regdown will be required. 
This is intended to give us a head-start on version history in the new interactive bureau regulations tool.
1. Check out https://github.com/cfpb/regulations-xml
2. Run the script on any single RegML file:
```shell
./cfgov/manage.py runscript regml_importer --script-args ../regulations-xml/regulation/1026/2011-31715.xml
```
- Validate that content comes through alright.

Regs3k: Initial attempt at a RegML importer

---

cfgov/jinja2/v1/_includes/molecules/hero.html

Correcting my laziness when setting up the OG bleeding illustration on Prepaid Cards and subsequently not following up on the TODO I left in the template.
Such a simple fix. Shame I didn't realize at the time how easy it was.
- Small hero image height is now determined by calculation based on the actual image dimensions
This is a PITA to test on localhost. Take my word for it and we'll confirm it on Beta before deploying to Prod 😁 
(You can see the `img.height` and `img.width` code pattern working in [Info Unit images](https://github.com/cfpb/cfgov-refresh/blob/fix-hero-sm-img-height/cfgov/jinja2/v1/_includes/molecules/info-unit-2.html#L75).)

Fix height of Hero images on small screens

---

requirements/libraries.txt

The new [0.5.1 release](https://github.com/cfpb/wagtail-inventory/releases/tag/0.5.1) of wagtail-inventory fixes a bug with broken pagination links (next/previous) in search results.
In the Wagtail admin, navigate to Settings, Block Inventory. Do a search for a common block type, like `wagtail.wagtailcore.blocks.field_block.CharBlock`. You should get multiple result pages. Verify that the next/previous links work properly.

Bump wagtail-inventory version from 0.5 to 0.5.1

---

requirements/libraries.txt

This PR updates Django-Flags and Wagtail-Flags to their latest releases ([3.0.2](https://github.com/cfpb/django-flags/releases/tag/3.0.2) and 3.0.1](https://github.com/cfpb/wagtail-flags/releases/tag/3.0.1) respectively).
This should fix a problem with custom conditions not showing up in the admin (the conditions are registered, but not available to be selected in the form). See https://github.com/cfpb/django-flags/pull/4 for more.

Update Django-Flags and Wagtail-Flags to latest releases

---

cfgov/.coveragerc

Currently all templatetags directories are excluded from Python test coverage. They should not be -- this is Python code that we (sometimes) include in our templates, and it should be tested like other code.
There numerous tests either directly against these tags or that invoke these tags in their processing, so we should include them in coverage.
This will likely cause our coverage numbers to drop slightly.
(I'm opening this because I'm making changes to template tags in another branch and was wondering why they weren't included in coverage. I isolated this as its own PR to keep things separate when possible.)

Add templatetags to Python test coverage

---

.env_SAMPLE

Docker needs `ES_HOST` to be `elasticsearch`.

Change default ES host

---

cfgov/jinja2/v1/_includes/macros/video-player.html
cfgov/unprocessed/js/modules/VideoPlayer.js
cfgov/unprocessed/js/modules/YoutubePlayer.js

As reported in https://GHE/CFGOV/platform/issues/2895, our current video player implementation is preventing native Google Tag Manager tracking of YouTube videos. We want to use this native tracking to reduce the amount of custom tracking code we have to use. This PR should fix the issue.
- Attach and init the video on first load, not after the user clicks the play button, but leave it hidden
- This necessitates _not_ having videos autoplay, contrary to our previous guidance. The `video_url` modification in the template has been changed to _remove_ `autoplay=1` if found, rather than adding it if missing.
Full testing requires GTM access, but if you want to ensure nothing's broken:
1. Pull branch
1. `gulp scripts`
1. Visit a page with a video, like …

Fix video player so that native GTM tracking works

---

cfgov/cfgov/urls.py
cfgov/legacy/tests/views/test_views.py
cfgov/legacy/views/__init__.py

The CSRF token endpoint view (at /token-provider/) is not compatible with Django 1.11. This change fixes that and adds tests for this view.
To run tests against Django 1.11, run:
`tox -e unittest-py27-dj111-wag113-fast`
To access the view locally, run:
`curl -X POST http://localhost:8000/token-provider/`
This view is used by django-college-costs-comparison, for example at:
https://www.consumerfinance.gov/paying-for-college/compare-financial-aid-and-college-cost/

Add Django 1.11 compatibility to CSRF view

---

cfgov/unprocessed/apps/owning-a-home/webpack-config.js
cfgov/unprocessed/apps/regulations3k/webpack-config.js
cfgov/unprocessed/js/molecules/Multiselect.js
cfgov/unprocessed/js/organisms/FilterableListControls.js
config/webpack-config.js

As reported in https://GHE/CFGOV/platform/issues/2981, the height of a Filterable List Controls expandable is not being correctly adjusted when interacting with the multiselect filters inside. This PR takes care of that.
- Added a new event dispatch when selections on a multiselect are updated, which I didn't end up using, but it might still be useful in the future.
- Added `resolve: { symlinks: false }` in `webpack-config.js` files, which I needed to test with an `npm link`ed cf-expandables. This PR no longer needs any changes in cf-expandables, but this will be useful to anyone in the future who wants to test local updates to CF components within cfgov-refresh.
- Bind the instance of the FLC expandable's `transition` to the `expand` calls within `window.setTimeout`, because if not, …

Fix FLC height adjustment when interacting with multiselect filters

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

Add feature flags for TDP related wagtail (static) pages. Add feature flag for TDP Search Interface and Activity Detail pages.
@chosak @willbarton @higs4281 @Scotchester

Tdp feature flags update

---

cfgov/cfgov/urls.py
cfgov/regulations3k/tests/test_views.py
cfgov/regulations3k/views.py

We need to rescue as many eregulations requests as possible and
send them to the appropriate regulations3k page. The URL formats
have some crucial differences.
* The base URL changes
* Section references change
* Versions are now referenced by effective date, not by notice document ID
old | new
:-- | :---
/eregulations/ | /policy-compliance/rulemaking/regulations/
/eregulations/1002 | /policy-compliance/rulemaking/regulations/1002/
/eregulations/1002-1 | /policy-compliance/rulemaking/regulations/1002/1/
/eregulations/1002-1/2017-20417_20180101 | /policy-compliance/rulemaking/regulations/1002/2016-07-11/1/

Redirect eregulations to regs3k

---

cfgov/regulations3k/jinja2/regulations3k/search-regulations-results.html
cfgov/unprocessed/apps/regulations3k/js/search-utils.js
cfgov/unprocessed/apps/regulations3k/js/search.js
cfgov/unprocessed/js/modules/util/dom-traverse.js
test/unit_tests/apps/regulations3k/js/search-spec.js
test/unit_tests/js/modules/util/dom-traverse-spec.js

Handful of fixes that came out of accessibility testing.
1. `gulp test:unit --specs=apps/regulations3k` and verify all automated tests pass
1. Visit the [search page](http://localhost:8000/policy-compliance/rulemaking/regulations/search-regulations/results/?q=disclosure&regs=1003&regs=1004&results=25&order=relevance) and manually toggle some filters to double check everything looks good

Regs3k accessibility improvements

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

Remove unnecessary CR tool prototypes feature flag.
- Feature flag for CR tool prototypes
- Flagged url for CR tool prototypes
@Scotchester @chosak @willbarton @higs4281

Remove unnecessary CR tool prototypes feature flag

---

cfgov/cfgov/urls.py

Fix bug that caused the CR tool pages to display page not found.
URLs to test:
- https://www.consumerfinance.gov/practitioner-resources/youth-financial-education/curriculum-review/
- https://www.consumerfinance.gov/practitioner-resources/youth-financial-education/curriculum-review/tool
- https://www.consumerfinance.gov/practitioner-resources/youth-financial-education/curriculum-review/before-you-begin
@atuggle @Scotchester @chosak @willbarton @higs4281

TDP: don't check for wagtail URLs below curriculum-review page

---

cfgov/regulations3k/jinja2/regulations3k/recent-notices.html
cfgov/unprocessed/apps/regulations3k/js/recent-notices.js

Change "BCFP" to "Bureau" in the list of recently issued notices on the interactive Bureau regulations landing page
- "BCFP" to "Bureau" at the end of the list of recently issued notices on the interactive Bureau regulations landing page
1. Fire up cf.gov as usual
2. Go to `/policy-compliance/rulemaking/regulations/`
3. Check to make sure the link at the bottom of the list of recently issued notices in the sidebar says "More Bureau notices" instead of "More BCFP notices"
4. Quintuple check to make sure I spelled "bureau" right 😄
Previous | Updated
-------- | ---------

Change "BCFP" to "Bureau" in recent notice list

---

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html
cfgov/regulations3k/jinja2tags.py
cfgov/regulations3k/models/pages.py
cfgov/regulations3k/resolver.py
cfgov/regulations3k/tests/test_jinja2tags.py
cfgov/regulations3k/tests/test_models.py
cfgov/regulations3k/tests/test_resolver.py
cfgov/unprocessed/apps/regulations3k/css/reg-text.less

This PR makes it possible to navigate versions in the Regulations 3000 UI and makes changes to the way effective dates are shown to users on the current law version of a regulation.
This PR will replace the use of the Text Introduction heading and links with the hard-coded use of the page's title and generated links to versions and search. So all of those should be removed from the Text Introduction block on a Regulation page otherwise you'll see double.
1. Load past versions JSON or a database dump containing them (see chat), or create copies of effective versions with future or past effective dates.
2. Browse the regulation and navigate between versions using the "View all versions of this regulation" links.
- **Current law**
- Landing page: 
- Section page: 
- **Past version**
- …

Regs3k: Navigate effective versions of regulations

---

requirements/optional-public.txt

This change bumps the version of the optional satellite app college-costs from version 2.3.12 to the new version 2.4.0:
https://github.com/cfpb/college-costs/releases/tag/2.4.0
This new version adds Django 1.11 support, fixes functional tests, and modernizes the build.
To test with a local server, pip install the new wheel:
```
pip install https://github.com/cfpb/college-costs/releases/download/2.4.0/college_costs-2.4.0-py2-none-any.whl
```
After doing this, re-pip-instal the cfgov-refresh requirements:
```
pip install requirements/libraries.txt
```
Then test these pages locally to verify functionality:
http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/test/
http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/api/search-scho …

Bump college-costs version from 2.3.12 to 2.4.0

---

requirements/optional-public.txt

Reverts cfpb/cfgov-refresh#4504.
This might introduce some breakage into the build due to missing CF icons. In combination with [these changes](https://github.com/cfpb/cfgov-refresh/commit/b5d8455c24c9183e11306c01ba3ac3f2a2d1f3ec) in the as-yet-unmerged `eot-icons` branch, the college-costs bump seems to lead to a `collectstatic` error in the builds.

Revert "Bump college-costs version from 2.3.12 to 2.4.0"

---

cfgov/unprocessed/apps/regulations3k/js/index.js
cfgov/unprocessed/apps/regulations3k/js/regs3k-utils.js
test/unit_tests/apps/regulations3k/js/regs3k-utils-spec.js

The old eRegs had paragraph IDs in a different format than the new
Regs3K. After the page loads, convert the paragraph markers to the new
format and jump the user to the correct paragraph (if found).
1. Visit http://localhost:8000/eregulations/1003-4/2017-18284_20180101#1003-4-a-9-ii-C and see if it redirects you to the correct regs3k paragraph
1. Visit http://localhost:8000/eregulations/1003-Subpart-Interp/2017-18284_20180101#1003-2-f-Interp-3 and see if it redirects you to the correct interp paragraph.

Redirect Regs3K paragraph hashes

---

cfgov/legacy/static/nemo/_/c/less/es-styles.less
cfgov/legacy/static/nemo/_/c/less/icons.less

There's a giant icon on the Spanish homepage caused by the page now being run through the `parse_links` middleware, adding an external link icon to a link that didn't used to have one. This PR copies the standard `.cf-icon-svg` Less into the Spanish styles so that the icon is sized and colored appropriately.
- SVG icon styles added to the Spanish stylesheet
1. Pull branch
1. Load http://localhost:8000/es/ and see a normally sized icon, in the same color as the link

Fix big icon on Spanish site

---

cfgov/cfgov/urls.py
cfgov/regulations3k/tests/test_views.py
cfgov/regulations3k/views.py

Our redirect URL wasn't greedy enough, and some interpretation requests weren't matching.
Interp matching still needs work.

regsek: Fix redirect errors

---

cfgov/unprocessed/apps/regulations3k/regulations3k-manifest.json

Forgot to update the URL that's used when Regs3K is added to a user's home screen.

Update Regs3K homepage in app manifest

---

cfgov/regulations3k/jinja2/regulations3k/search-regulations-results.html

The search results template barfs if either `current_count` or `paginator` are undefined. This happens when no query is provided by the user.
The solution is to only render those parts of the template if `current_count` is defined, meaning they provided a search query.
See if http://localhost:8000/policy-compliance/rulemaking/regulations/search-regulations/results/?q=&partial=&regs=1024 returns `No results match your filters` instead of a 500 error.

Check for a search count before rendering Regs3K results

---

cfgov/jinja2/v1/_layouts/base-common.html
cfgov/jinja2/v1/ask-cfpb/answer-page-spanish-printable.html
cfgov/jinja2/v1/es/es-base.html
cfgov/legacy/templates/front/base_nonresponsive.html
cfgov/legacy/templates/front/base_update.html
cfgov/v1/jinja2/v1/footer.html
cfgov/v1/jinja2/v1/header.html
cfgov/v1/jinja2/v1/modernizr.html
cfgov/v1/templatetags/base_elements.py
cfgov/v1/tests/templatetags/test_base_elements.py

Currently multiple cf.gov base page templates include Modernizr.js (and use it to disable JS) in different ways. This PR consolidates this logic and unifies it across the templates. This change is motivated by, and also removes, reference to a deprecated `common.ie9.js` file that was removed in 9afbc47.
The three base templates involved in this change are:
1) [cfgov/jinja2/v1/_layouts/base-common.html](https://github.com/cfpb/cfgov-refresh/blob/modernize-modernizr/cfgov/jinja2/v1/_layouts/base-common.html): This is a Jinja2 template rendered by Django with the Jinja2 template engine. This is used as the base template for most, if not all, of the Wagtail page templates.
2) [cfgov/legacy/templates/front/base_nonresponsive.html](https://github.com/cfpb/cfgov-refresh/blob/modernize-modernizr/c …

Consolidate base template Modernizr code

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/settings/local.py
cfgov/cfgov/settings/production.py
cfgov/cfgov/urls.py
cfgov/core/static/robots.txt
requirements/optional-public.txt

This PR removes the eRegulations dependencies and related configuration. This should enable us to proceed with the Django 1.11 upgrade.
~~I'm putting a hold label on this for right now until the launch dust clears for Regs3k.~~
- eRegulations

Remove eRegulations

---

cfgov/cfgov/tests/test_urls.py
cfgov/cfgov/urls.py

The `flagged_wagtail_only_view` helper from urls.py is not compatible with Django 1.11 due to a signature change in Django 1.9:
https://docs.djangoproject.com/en/1.9/ref/views/#the-404-page-not-found-view
This change adds Django 1.11 compatibility to this helper, improves the docstring, and adds unit tests.
@schbetsy and I paired on this change. Shoutout to @willbarton for the very slick `@override_settings(ROOT_URLCONF=__name__)` trick.
FYI @atuggle.

Add Django 1.11 compatibility to Wagtail only URLs

---

requirements/optional-public.txt

This change bumps the version of the optional [college-costs](https://github.com/cfpb/college-costs) dependency from 2.3.12 to the new 2.4.1 release:
https://github.com/cfpb/college-costs/releases/tag/2.4.1
This change modernizes the frontend build and adds Django 1.11 support.
To test, pip install the new wheel file and visit the test page:
http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/test/

Bump optional college-costs version to 2.4.1

---

cfgov/ask_cfpb/models/pages.py
cfgov/ask_cfpb/tests/models/test_pages.py
cfgov/ask_cfpb/tests/test_template_tags.py

The ask_cfpb category page had a faulty check for results. It naively
checked for the existence of an unevaluated query, instead of checking
that the *evaluated* query produced results.
It's not clear why zero-result category queries sporadically crop up on the servers, 
and I can't seem to replicate that behavior locally. 
But I've added tests to check that we handle results of 0 and 1 properly, 
and, it is hoped, prevent the index errors.
Since templatetags were recently exposed to testing, this also adds a
test for ask_cfpb's accent stripper.

Ask CFPB: Add count check to avoid index errors

---

.env_SAMPLE
cfgov/cfgov/settings/local.py

This PR adds `10.0.2.2` to `INTERNAL_IPS` when `ENABLE_DEBUG_TOOLBAR` is set. This will allow usage of the Django Debug Toolbar in our Docker setup.
~~This PR makes the `INTERNAL_IPS` setting configurable to allow us to use Django Debug Toolbar in Docker when `ENABLE_DEBUG_TOOLBAR` is enabled.~~
~~This is a WIP because: @wpears @rosskarchner I'm not sure where the `10.0.2.2` IP address comes from, or whether it's specific to my machine. I discovered it by printing `request.META['REMOTE_ADDR']` in a request cycle to discover what IP requests from my Mac were coming from inside the python container. Is there a way we can make that information more easily discoverable? Is `10.0.2.2` consistent for everyone using our Docker setup?~~
1. Add the following variable to your `.env` file:
``` …
```

Add 10.0.2.2 to INTERNAL_IPS to support Django Debug Toolbar in Docker

---

requirements/optional-public.txt

Bring in new versions of owning-a-home, retirement, and django-college-costs-comparison. These include updates to python requirements lists, so they are compatible with django1.11 and with the versions required in cfgov-refresh.

Bump oah, retirement, and django-college-costs

---

requirements/optional-public.txt

Updated content and styles for the building blocks tool.
- Updated TDP version to 1.0.19

Bump TDP release to 1.0.19

---

cfgov/regulations3k/blocks.py
cfgov/regulations3k/jinja2/regulations3k/regulations-listing.html
cfgov/regulations3k/tests/test_blocks.py
cfgov/unprocessed/apps/regulations3k/css/reg-listing.less

This PR adds future effective versions to the regulations listing, for example:
- The styling could use some work. Currently the future version `li` is inheriting the `h4` class from the parent `li`.

Regs3k: Add future effective versions to regulations listing

---

cfgov/templates/wagtailadmin/shared/page_status_tag.html

The Wagtail admin "Live" links use the `page.url` property which is normally a relative URL when Wagtail has only a single Site (as we have). When accessing the admin from a different domain (e.g.
content.consumerfinance.gov), these "live" links don't actually point to the correct URL.
This change overrides the Wagtail admin page status tag template to use the page's absolute URL instead of its relative URL. This corrects the "Live" links so that they point to the right place.
This is the Wagtail template we are overriding:
https://github.com/wagtail/wagtail/blob/v1.13.4/wagtail/wagtailadmin/templates/wagtailadmin/shared/page_status_tag.html
Run a local server, access it via something like http://content.localhost:8000 (this works in Chrome, might not in other browsers), and note that …

Use absolute page URL in Wagtail admin live links

---

cfgov/regulations3k/tests/test_views.py
cfgov/regulations3k/views.py

Interpretation redirects were not working for past versions of
appendix and section references after our launch-day hot-fixing.
This was not a pressing issue, because we have yet to turn past
versions on in production, but we hope to soon, and this PR restores
past-version redirects for interpretations.
We also lost some test coverage in the hot-fix, and this restores test coverage.
Addresses GHE issue 375.
Interp version redirects should work locally (if you have non-draft versions loaded)
or on the build5 server. Sample eregs version URLs:
* /eregulations/1002-Interp/2016-16301
* /eregulations/1026-Appendices-Interp/2016-30730

Regs3k: Improve interpretation redirects

---

cfgov/wellbeing/jinja2/wellbeing/results.html

This change fixes a reference to a static image on the wellbeing results page. This missing reference causes a 500 error in Django 1.11.
Visit http://localhost:8000/consumer-tools/financial-well-being/results/ locally and confirm that the rainbow spectrum image loads.

Fix missing static wellbeing image

---

cfgov/cfgov/settings/base.py

Our regulations themselves should not have links in them that receive any special markup outside of what is entered in RegDown. This change ensures that doesn't happen in theory.
In practice the reason for this change is that the `ParseLinksMiddleware` is a full 1/5 of the total time spent rendering some of our largest regulation sections, and it's time that's wholly unnecessary.
I did not blacklist all of `'/policy-compliance/rulemaking/regulations/'` because there could still be links on the main landing page that need to be munged.
As a side-note, it'd be lovely to be able to specify this list as a regular expression, but that would probably add that little bit more overhead to all requests.

Regs3k: Add regulations to PARSE_LINKS_BLACKLIST

---

cfgov/cfgov/tests/test_urls.py
cfgov/cfgov/urls.py

New Relic is passing an `exception` kwarg to our `handle_error` function. The function wasn't set up to take that argument, so it's raising a TypeError.
This change adds the `exception` kwarg and adds tests for `handle_error`. Until we do this, all our error analytics in New Relic are obscured by this `TypeError`.

Add exception as a kwarg to handle_error

---

cfgov/jinja2/v1/events/_macros.html

Google recently began requiring an API key to use the Google Maps Static API, resulting in an unfortunate error message in place of where we used to have maps on event pages. This is a hotfix for an event getting published today that simply hides the map. In the future, we should replace the Google Maps Static API call with Mapbox integration.
- Comments out map display on event pages
1. Create a new event page with a venue city and state
1. Preview the page and see the alt text of the map, not the map itself
1. Pull branch
1. Refresh the page and see nothing

Temporarily hide event maps until we can replace the Google Maps Static API with Mapbox

---

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html
cfgov/unprocessed/apps/regulations3k/js/permalinks-utils.js
cfgov/unprocessed/apps/regulations3k/js/permalinks.js
cfgov/unprocessed/apps/regulations3k/js/regs3k-utils.js
test/unit_tests/apps/regulations3k/js/permalinks-spec.js
test/unit_tests/apps/regulations3k/js/permalinks-utils-spec.js

Update the URL's hash to point to the currently-viewed paragraph as you scroll.
- `permalinks.js` file that is loaded only on browse regs pages.
On page load we grab every regdown paragraph (`.regdown-block`) and cache its `id` attribute and Y coordinate. We regenerate this array if the user resizes the window or clicks on an expandable (because both those actions cause paragraphs to change positions on the page).
As users scroll through the page we search the array for the paragraph closest to the top of the viewport and update the URL hash accordingly.
1. `gulp test:unit --specs=apps/regulations3k/` and verify all automated tests pass.
1. Scroll through your [favorite reg](http://localhost:8000/policy-compliance/rulemaking/regulations/1026/47/) and verify that the URL …

Regs3K: Add URL permalink hash updating to Regs3K

---

cfgov/ask_cfpb/models/pages.py

Since we can't replicate or predict when Ask CFPB's haystack request cycle
will produce an IndexError, we can instead capture it when it happens and deliver
a slower but guaranteed-success option.
Someday I'll understand how a request with > 0 results has no first result.
Haystack defines its own query `__getitem__` method, and I wonder if [this assumption](https://github.com/django-haystack/django-haystack/blob/master/haystack/query.py#L319) can sometimes be wrong when using Elasticsearch.
This is in response to recently bumped GHE cfgov-alerts issues 298, 721, and 766.

Ask CFPB: Handle IndexError explicitly

---

cfgov/cfgov/settings/base.py
cfgov/core/tests/test_utils.py
cfgov/core/utils.py

Now that we're on Django 1.11, we can remove logic that checks `django.VERSION` to support both 1.8 and 1.11. This PR includes two such changes:
1. Simplifies inclusion of overextends templatetags implemented in #4474. Test by visiting the Django admin locally, e.g. http://localhost:8000/django-admin/.
2. Simplifies disabling migrations logic introduced in #4477. Test by running Python tests without migrations, e.g. `tox -e fast`, and note that migrations don't get run.

Deprecate django.VERSION conditionals

---

cfgov/v1/management/commands/makemessages.py
cfgov/v1/tests/management/commands/test_makemessages.py
cfgov/v1/tests/management/commands/test_makemessages_data/__init__.py
cfgov/v1/tests/management/commands/test_makemessages_data/jinja2/test.html
cfgov/v1/tests/management/commands/test_makemessages_data/templates/test.html
docs/installation.md
docs/translation.md

This change adds a Python test for the v1 app's custom `makemessages` Django management command, which overrides the default one documented at
https://docs.djangoproject.com/en/1.11/ref/django-admin/#django-admin-makemessages
Our custom makemessages command adds support for block tags like this:
```
{% trans %}
Multi-line
statement
here
{% endtrans %}
```
which is not supported in Django templates.
This change also removes support in this command for Django 1.8 now that this project is solely targeted at Django 1.11.
To test this locally, you can verify that the unit test passes, and then remove our custom makemessages command (including the .pyc file if on Python 2). The built-in command will fail as it does not detect the multi-line Jinja2 tag.
Additionally, you can run through the …

Add tests to custom makemessages command

---

requirements/optional-public.txt

In all satellite apps:
- Specify Django 1.11 in setup.py
- Remove tests for Django 1.8 from Tox
- Update documentation where necessary
- Update all satellite apps to latest release

Bump satellite apps: Bring in post-Django 1.11 upgrade cleanup

---

cfgov/jinja2/v1/_includes/organisms/chart.html
cfgov/scripts/_atomic_helpers.py
cfgov/v1/tests/atomic_elements/organisms/test_organisms.py
cfgov/v1/tests/management/commands/test_update_chart_block_dates.py

- Updates charts footer to set footer source text to "BCFP Consumer Credit Panel" and moves download to its own line.
- Fixes template file indenting.
1. Run local server.
2. Check CCT charts and see the footer is updated (e.g. http://localhost:8000/data-research/consumer-credit-trends/auto-loans/origination-activity/)

Updates chart source footer

---

CONTRIBUTING.md
config/webpack-config.js

IE9 is given the `no-js` class so we shouldn't need to add IE9 to babel. 
- Don't run IE9 through Babel.
- Update contributing doc to fix a typo, minor formatting, and browser support sections.
2. Pages like the /blog/ should work as before.

Updating contributing doc and adjust transpiling

---

cfgov/cfgov/test.py
cfgov/cfgov/tests/test_test.py
docs/testing-be.md

This change updates the logic in our custom [StdoutCapturingTestRunner](https://github.com/cfpb/cfgov-refresh/blob/337f9a69aba8f56eb0791d4554463088c482d878/cfgov/cfgov/test.py#L195) class to simplify it a bit and remove a reference to Django 1.8.
Unfortunately this change actually has the side effect of making the unit tests for this custom test runner a bit more complicated.
Between 1.8 and 1.11, a change was made to address this Django ticket:
https://code.djangoproject.com/ticket/26981
The ability was added for Django TestRunner classes to provide custom kwargs to the underlying unittest test runner, which is the thing that actually runs the tests. This was implemented in this PR:
https://github.com/django/django/pull/7009
That PR added the ability for Django TestRunner classes to …

Update StdoutCapturingTestRunner to Django 1.11

---

tox.ini

Remove references to Django 1.8 in tox.ini

---

cfgov/ask_cfpb/models/pages.py
cfgov/search/forms.py
cfgov/search/templates/search/external_links.html
cfgov/search/tests/test_views.py
cfgov/search/views.py
cfgov/search/wagtail_hooks.py
cfgov/v1/models/base.py
cfgov/v1/models/blog_page.py
cfgov/v1/models/browse_filterable_page.py
cfgov/v1/models/browse_page.py
cfgov/v1/models/home_page.py
cfgov/v1/models/landing_page.py
cfgov/v1/models/learn_page.py
cfgov/v1/models/sublanding_filterable_page.py
cfgov/v1/models/sublanding_page.py

This introduces a new view in the Wagtail admin, called "External Links" in the sidebar, to search across all pages and snippets.  The use case is to search for an external link, but it can technically be used to search any text. See GHE/CFGOV/enhanced-cms/issues/4 for the user story & its related issues.
Specifically, these are the columns on each model it's searching:
- Search `content`, `sidefoot`, and `header` sections of pages (except EventPage which is different - see next line).  Pages are any page that inherit from `CFGOVPage` - these are mostly defined in the `v1` app but there are also pages defined outside of `v1`.
- Search `body`, `archive_body`, `live_stream_url`, `flickr_url`, `youtube_url`, `future_body`, and `agenda_items` of EventPages
- Search `snippet` and `answer` of …

Search pages & snippets for external links

---

cfgov/cfgov/settings/base.py

This PR makes a few changes to our [Django middleware](https://docs.djangoproject.com/en/1.11/topics/http/middleware/) as part of cleanup after the recent upgrade to Django 1.11.
1. Removes inclusion of the now-deprecated SessionAuthenticationMiddleware.
2. Removes inclusion of the unused SecurityMiddleware (this sounds scarier than it is).
3. Updates how we generate ETags (see #2454 for previous implementation and discussion).
See commits for some additional details and testing instructions for the ETag change.

Post-Django 1.11 middleware cleanup

---

docs/installation.md

This change removes a troubleshooting section from the installation docs which is a bit outdated.
First, now that we're on Django 1.11, it's been quite some time since we've used South, so the instructions pertaining to it should no longer be needed.
Second, the recommendation to globally uninstall all Python packages (including virtualenv) seems overly broad, especially now that some people are using the Docker workflow. If not using Docker, all work should be done in a virtual environment, so the recommendation to uninstall all packages feels too strong.
To test, `pip install -r requirements/manual.txt` then `mkdocs serve`, and navigate to http://localhost:8000/installation/.

Remove outdated section from installation docs

---

cfgov/cfgov/urls.py

Change the url for the building blocks tool.
- Updated url to practitioner-resources/youth-financial-education/journey

Building blocks tool url

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/wsgi.py
docs/wagtail-migrations.md

A few different comments and docs have links to relevant django documentation. They were still pointing to Django 1.8 docs. Now that we're on Django 1.11, we link to the version that we're on, and we don't have to see a scary red "deprecated" banner on the documentation pages when we visit.
No code changes!

Upgrade django documentation links to 1.11

---

requirements/libraries.txt
requirements/local.txt
requirements/manual.txt
requirements/test.txt
requirements/travis.txt

Upgrade python libraries where possible.
Note: I did not touch any libraries that are elasticsearch related. I also only touched libraries that are in the `test` and `libraries` requirements collections, since those are covered by unit tests.

Upgrade Python Libraries

---

requirements/libraries.txt

Because of an oversight, I included `beautifulsoup4==4.6.3` in #4564, but wagtail is only compatible with `<4.6.1`. This caused `tox` to fail with a version conflict, which breaks deploys. This PR replaces it with `beautifulsoup4==4.6.0`, so `tox` passes again.
`tox -e fast` installs in the following order (wagtail comes before libraries.txt?). Installing in this order gets us `beautifulsoup4==4.6.3` with no errors.
```
deps=
-r{toxinidir}/requirements/django.txt
-r{toxinidir}/requirements/wagtail.txt
{[unittest]deps}
```
`slow`, which runs when we run `tox` without an environment, appears to install in the opposite order (libraries.txt before wagtail? idk, I might have these backward). Installing this way results in a version conflict error: `version conflict: beautifulsoup4 4.6.3 …

Fix library version, which should fix deploys

---

requirements/libraries.txt

The upgraded version was requiring a version of Python that is newer than what we have installed on cf.gov servers.

Revert upgrade of edgegrid-python

---

cfgov/cfgov/settings/base.py
requirements/libraries.txt

Upgrade django-storages library from 1.5.0 to its latest version (1.7.1), which requires updating the `AWS_DEFAULT_ACL` setting.
`AWS_DEFAULT_ACL` determines what permissions (ACL, Access Control List) are added to individual files when they are uploaded to our S3 bucket. That file's permissions are also dictated by the permissions of the bucket that contains it.
Version 2.0 of django-storages will change the default value of `AWS_DEFAULT_ACL` from `public-read` to `None`, to improve security. When set to `None`, it will not add the public-read ACL directly to each file; intstead, files fall back on the bucket's ACL. We added `AWS_DEFAULT_ACL = None` to silence a warning in 1.7.1, and to adopt the newly preferred behavior early.
@chosak and I tested and found that this update will not …

Upgrade django-storages to latest

---

cfgov/unprocessed/css/organisms/footer.less

Closes #3575 
Does so by zeroing out the border-top-width of all list items except in the first column, which corresponds to the top of the footer in the collapsed mobile view.
To see the fix:
- Pull branch
- `npm run gulp styles`
- Open any page, shrink browser to a mobile view, and bask in the non-doubled borders

Fix doubled border in mobile footer

---

cfgov/data_research/fixtures/conference_registrants.json
cfgov/data_research/forms.py
cfgov/data_research/models.py
cfgov/data_research/research_conference.py
cfgov/data_research/templates/data_research/conference_notify_email.txt
cfgov/data_research/templates/data_research/conference_notify_subject.txt

The conference registration notification email template was not updated to support the new option for in-person or virtual attendee registration, and the way in which that affects the capacity. This PR corrects that.
- Updates `ConferenceNotifier` so that it has the information it needs about the different attendee counts and the question of being at capacity
- Updates the email body and subject templates to output the information accurately
1. With a recent DB dump, edit http://localhost:8000/admin/pages/11796/edit/ to change the capacity to `1`.
1. Submit a registration for a virtual attendee
1. Run `./cfgov/manage.py conference_notify 11796 -t a@b.c --dry-run` to see the resulting email
1. Submit a registration for a physical attendee
1. Run `./cfgov/manage.py conference_notify 11796 …

Update conf reg email notification format to support in-person/virtual attendance

---

cfgov/cfgov/settings/base.py

Adds ga to connect-src to fix a CSP bug in Safari.
See GHE/CFGOV/platform/issues/3084 for more.

Add ga to connect-src

---

requirements/libraries.txt

urllib3 1.24 broke compatibility with the `requests` library. Here's an example bug report:
https://bugs.archlinux.org/task/60436
You can duplicate the issue locally by running `tox`. Pinning urllib3 to 1.23 resolves the error
- added urllib3 to requirements/libraries.txt

pin urllib3 to 1.23

---

cfgov/unprocessed/js/modules/VideoPlayer.js

Fixes rogue `childElement` errors

Bail from video-player init if element isn't present

---

cfgov/scripts/http_smoke_test.py

This URL changed without a redirect put in place, so the test started failing. I put the redirect in place, but we should still change the canonical URL in the test.

Fix smoke test for changed URL

---

cfgov/cfgov/tests/test_urls.py

This PR adds `bytes` casts for strings that test against a Django Response object's `content` in the `cfgov` package tests. This makes the `cfgov` package tests pass with Python 3.6.

Make cfgov URL tests work with Python3

---

cfgov/alerts/tests/test_send_new_relic_messages_to_sqs.py

This PR changes the mocking of `builtin` in the alerts package to make its tests pass with Python 3.6.

Make alerts tests work with Python3

---

cfgov/legacy/housing_counselor/cleaner.py
cfgov/legacy/housing_counselor/fetcher.py
cfgov/legacy/housing_counselor/generator.py
cfgov/legacy/housing_counselor/geocoder.py
cfgov/legacy/tests/housing_counselor/test_generator.py

This is a cleanup of map/filter generators and translating unittest `assertItemsEqual` to `assertCountEqual`.

Make legacy tests work on Python 3

---

cfgov/ask_cfpb/templatetags/accent_stripper.py
cfgov/ask_cfpb/tests/models/test_pages.py
cfgov/ask_cfpb/tests/test_template_tags.py

Refactor tests and code for Python3 compliance.
Tests should run in python 2 and 3:
```
tox -e unittest-py36-dj111-wag113-fast ask_cfpb
tox -e fast ask_cfpb
```

ask-cfpb in python3

---

cfgov/jinja2/v1/_includes/macros/video-player.html

The fact that we don't have a reliable way to produce this `origin` string across different environments is probably causing us some issues.
See https://GHE/CFGOV/platform/issues/2895#issuecomment-186171 for further explanation.

Change method of setting origin param on YouTube URLs

---

requirements/optional-public.txt

Updated content on search interface landing page.
- Updated TDP version to 1.0.26

Bump TDP release to 1.0.26

---

cfgov/jinja2/v1/_includes/molecules/related-posts.html
cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html
cfgov/jinja2/v1/_includes/templates/streamfield-sidefoot.html
cfgov/v1/atomic_elements/organisms.py
cfgov/v1/models/base.py
cfgov/v1/tests/atomic_elements/organisms/test_related_posts.py

This change modifies the way that the RelatedPosts StreamField block is included and rendered in page sidebars. Instead of rendering it using a macro (as we do most of our blocks), this change renders it using the [standard Wagtail `{% include_block %}` method](http://docs.wagtail.io/en/v2.3/topics/streamfield.html#template-rendering).
This change moves the related posts logic from the page class to the block. This consolidates all related posts logic into a single place. Python tests have also been moved accordingly.
To test this, you can visit these two pages using a local server running against a production dump:
http://localhost:8000/data-research/credit-card-data/
http://localhost:8000/about-us/blog/askcfpb-your-questions-about-credit-reports-and-scores/
These two pages represent …

Convert RelatedPosts block to use include_block

---

requirements/optional-public.txt

Add two improvements to the ratechecker data-loading routine:
- Fix an IndexError that led to server errors.
- Re-sequence data loading to catch partial-load conditions.

bump owning-a-home-api version to 0.11.3

---

cfgov/cfgov/settings/base.py
cfgov/housing_counselor/jinja2/housing_counselor/improved_index.html
cfgov/housing_counselor/views.py

This PR adds a feature flag for the Find a Housing Counselor page, which the UI improvements team is in the process of remaking.
When the flag, called `HUD_TOOL_IMPROVEMENTS`, is not enabled (which is the default behavior), we show the existing Find a Housing Counselor page.
When the flag is enabled, we show the new template, which is stored in `jinja2/housing_counselor/improved_index.html`. When the new page is enabled and a `zipcode` parameter is included in the GET request, show the context values returned in the response, to aid in
future front-end development.
- `HUD_TOOL_IMPROVEMENTS` flag
- `jinja2/housing_counselor/improved_index.html`
*^ I'm open to feedback on the names of both of those things, by the way. I wasn't sure how best to name them.*
1. With this branch running, visit …

Add Feature Flag for Housing Counselor page improvements

---

cfgov/housing_counselor/jinja2/housing_counselor/improved_index.html

Adding an initial setup for the find-a-housing counselor page to use the base template. Merging right away so I can work on this with @mistergone easier.

Adds initial base template to HUD

---

cfgov/jinja2/v1/_includes/organisms/half-width-link-blob-group.html
cfgov/jinja2/v1/_includes/organisms/info-unit-group.html
cfgov/jinja2/v1/_includes/organisms/third-width-link-blob-group.html
cfgov/regulations3k/jinja2/regulations3k/regulations3k-search-bar.html
cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
requirements/libraries.txt

Upgrade our package version of Jinja2 from 2.7.3 to 2.10, the latest released version.
The [`tojson` filter](http://jinja.pocoo.org/docs/2.9/templates/#tojson) is a new feature on Jinja 2.9.x that would be very useful for my work on the UI Improvements project, so I'm taking this opportunity to upgrade cfgov-refresh, if possible.
- Upgrade our version of jinja2. This required updating the order of arguments for a few method calls.
- ~~I did a quick search and didn't find any satellite apps that explicitly require jinja2.~~ TDP uses jinja2, and initial automated and manual testing seems to indicate that this change won't break it. Is there anywhere else I need to look to make sure this doesn't cause a version mismatch or break things?
Should not change any cf.gov functionality

Upgrade Jinja2 to latest

---

cfgov/jinja2/v1/_includes/organisms/bureau-structure.html

Bugfix: jinja 2.10 requires optional arguments come after required arguments. Some of the code that creates the org chart didn't follow that rule.
- visit https://www.consumerfinance.gov/about-us/the-bureau/bureau-structure/. See that it's no longer a python error, and it looks correct.
- Write a smoke test to cover this page (but we should get this fix out the door first)
Should not change any cf.gov functionality

Fix the Bureau Structure page after jinja upgrade broke it

---

cfgov/housing_counselor/jinja2/housing_counselor/improved_index.html
cfgov/unprocessed/apps/find-a-housing-counselor/browserslist
cfgov/unprocessed/apps/find-a-housing-counselor/css/hud.css
cfgov/unprocessed/apps/find-a-housing-counselor/css/hud_print.css
cfgov/unprocessed/apps/find-a-housing-counselor/css/main.less
cfgov/unprocessed/apps/find-a-housing-counselor/js/hud.js
cfgov/unprocessed/apps/find-a-housing-counselor/package-lock.json
cfgov/unprocessed/apps/find-a-housing-counselor/package.json
cfgov/unprocessed/apps/find-a-housing-counselor/webpack-config.js
config/webpack-config.js
test/unit_tests/apps/regulations3k/js/analytics-spec.js
test/unit_tests/apps/regulations3k/js/permalinks-utils-spec.js

Moves mapbox into new template with minimal cleanup, so future cleanup is easier to review.
- Adds mapbox map and dependencies to improved finding-a-housing-counselor template.
1. `./frontend.sh` and http://localhost:8000/find-a-housing-counselor/?zipcode=05201 should show a map

Add mapbox dependencies

---

requirements/optional-public.txt

This change bumps the version of the optional [retirement](https://github.com/cfpb/retirement) satellite app from 0.7.4 to the latest [0.7.5](https://github.com/cfpb/retirement/releases/tag/0.7.5). This fixes a problem in the 0.7.4 release where the use of local webfonts was used as the default frontend configuration. This broke Django `collectstatic` when used with ManifestStaticFilesStorage.

Bumps retirement satellite app to 0.7.5

---

cfgov/housing_counselor/jinja2/housing_counselor/improved_index.html
cfgov/housing_counselor/templates/housing_counselor/index.html
cfgov/unprocessed/apps/owning-a-home/package-lock.json

Update the work-in-progress improvements to Find a Housing Counselor by adding iteration that creates the list of the 10 closest housing counselors.
- Add iteration through results, which creates HTML structure for the results of the search
1. This only works if the `HUD_TOOL_IMPROVEMENTS` flag is on.
2. Check results at, for example, http://localhost:8000/find-a-housing-counselor/?zipcode=52246
3. Also check the search box

Find a Housing Counselor Improvements: Add iteration of results

---

cfgov/housing_counselor/jinja2/housing_counselor/improved_index.html
cfgov/unprocessed/apps/find-a-housing-counselor/js/hud.js
test/unit_tests/apps/find-a-housing-counselor/js/hud-spec.js

Housing counselor: 
- Updates zipcode input form and map to use featured content module.
- Removes hero block in jinja template.
- Exports utility methods from hud.js and adds unit test coverage for those methods. Also adjusts their logic to return consistent types.
1. Visit http://localhost:8000/find-a-housing-counselor/ and resize window to see how zipcode form and map stack.
2. `gulp test:unit` should pass.

Change map layout to use featured content module

---

cfgov/search/templates/search/external_links.html
cfgov/search/tests/test_views.py
cfgov/search/views.py

This is a more simplified version of addressing what https://github.com/cfpb/cfgov-refresh/pull/4611 was attempting to address, by removing duplicates at the time of the search. 
See PR above and GHE/CFGOV/enhanced-cms/issues/39 for more context.
In addition to removing the duplicates:
- We've updated the help text (thank you @marteki and @nataliafitzgerald)
- Added tests (if you run those same tests off master currently, they will fail, as expected)

Remove duplicates from external links search results

---

cfgov/cfgov/settings/base.py
cfgov/core/jinja2tags.py
requirements/libraries.txt

This change makes use of the Django-Flags middleware introduced in https://github.com/cfpb/django-flags/pull/11, which should reduce the number of database queries per request made for checking flag state.
Before checking out this branch, do some benchmarking with the Django Debug Toolbar without the middleware:
1. Enable the Django Debug Toolbar. 
Add `export ENABLE_DEBUG_TOOLBAR=True` to your .env file.
2. Restart your Docker Python container or re-source your .env file and restart your local running cfgov-refresh.
3. Visit the homepage and observe the number of SQL queries for flag_state. Particularly the number of duplicated flags.
With the middleware:
1. Checkout this branch and make sure to update the requirements in the docker container:
- Docker:
```shell
./shell.sh
...
pip …
```

Use Django-Flags middleware and bump Django-Flags and Wagtail-Flags versions

---

cfgov/housing_counselor/jinja2/housing_counselor/improved_index.html
cfgov/unprocessed/apps/find-a-housing-counselor/css/hud.less
cfgov/unprocessed/apps/find-a-housing-counselor/css/main.less
cfgov/unprocessed/apps/find-a-housing-counselor/js/hud.js

Results list had hardcoded results count and non-functional PDF and print buttons. It also didn't work with invalid zipcode values.
Error message should close out [GHE]/CFGOV/platform/issues/2580
- Make results list summary text dynamic based on result count and zip code.
- Update print button JS to remove jQuery.
- Update hud.css to hud.less and add less rule for abbr tag wrapping PDF.
- Wrap long paragraphs.
- Remove unused CSS.
- Updates "5-digit" copy to "five-digit".
- Updates "zip code" to "ZIP code" per our style guides.
2. Visit http://localhost:8000/find-a-housing-counselor/
3. Enter a valid ZIP code.
4. Click "Print list" button and see that print dialog shows up.
5. Click "Save list as PDF" link and see that PDF saves.
6. Enter an invalid ZIP code. …

Finding housing counselor: Fix results behavior

---

requirements/libraries.txt

This PR bumps the version of django-flags to fix a `TypeError` when conditions for flags are configured but those conditions don't exist (a function isn't registered for the condition name). This is described in more detail in cfpb/django-flags#15.
It also bumps wagtail-flags to 4.0.1 to expose such conditions in the UI. A screenshot can be found in cfpb/wagtail-flags#33.

Bump Django-Flags and Wagtail-Flags

---

cfgov/unprocessed/apps/find-a-housing-counselor/css/hud.less

All credit to @niqjohnson !
- Adds `no-js` styles to `hud.less` for hiding the map when JS is not available and changing the ZIP code input box layout.
2. Open http://localhost:8000/find-a-housing-counselor/
3. Open dev console and go to the `Settings` and check `Disable JavaScript`
4. Reload the page and see that you can still retrieve a list of housing counselors without JS.

Housing counselor: Hides map in no-js state

---

.travis.yml
cfgov/cfgov/settings/test.py
requirements/libraries.txt
travis_run.sh

Per cfpb/django-flags#16, this PR uses the latest release of Django-Flags to stop repeated `No condition registered for name "site" ` messages in favor of a Django system check. Now if there are non-existent conditions (like "site") they will be reported only when Django starts up. You should be able to see this with a recent database dump, i.e.:
```
Performing system checks...
System check identified some issues:
WARNINGS:
?: (flags.E001) Flag MOSAIC_CCDB has non-existent condition "site"
HINT: Register "site" as a Django-Flags condition.
?: (flags.E001) Flag MOSAIC_CCDB has non-existent condition "site"
HINT: Register "site" as a Django-Flags condition.
?: (flags.E001) Flag MOSAIC_COMPLAINTS has non-existent condition "site"
HINT: Register "site" as a Django-Flags condition.
?: …
```

Bump Django-Flags to 4.0.2

---

cfgov/housing_counselor/jinja2/housing_counselor/improved_index.html

Fixes issue where heading level was skipped.
- Changes h3 heading to h2 to fix heading order. 
1. You can use the WAVE chrome plugin to see that "Paperwork Reduction Act statement"

Housing counselor: Fix heading

---

cfgov/agreements/templates/agreements/index.html

Quarterly update to increment the most-recent download reference and add an archival reference.
- Most-recent link is now https://files.consumerfinance.gov/a/assets/Credit_Card_Agreements_2018_Q2.zip
- New archival link is https://files.consumerfinance.gov/a/assets/Credit_Card_Agreements_2018_Q1.zip
The `cf.gov-load-agreements-data` Jenkins can be run after this code is deployed.

Update credit-card-agreements page with new zip URLs

---

cfgov/unprocessed/apps/find-a-housing-counselor/js/common.js
cfgov/unprocessed/js/modules/util/validators.js

A DOM lookup was happening every time a map marker was clicked. This caches the lookups so they only happen on the first time the item is clicked.
- Cache result list item DOM references when the map markers are clicked.
2. Visit http://localhost:8000/find-a-housing-counselor/
3. Enter a ZIP and find results.
4. Click on a map marker to scroll to the results list item.
5. Click on the same map marker again.
6. Click on a different map marker.
7. Search for a different ZIP code.
8. Click on a marker and see that it scrolls to the results list item.
If you want, you can add a `console.log` where the DOM lookup happens and see that it will only be called once per ZIP code query.

Housing counselor: cache the map marker DOM lookups

---

cfgov/unprocessed/js/organisms/FilterableListControls.js

`_getLabelText` method is used internally within the FilterableListControl organism and has an argument of `selector`, but it is unused. Since this method is internal, this logic can be removed.
- `selector` argument from the FilterableListControl organism's `_getLabelText` method.
2. Filters, such as on http://localhost:8000/about-us/blog/, should work as before.

FilterableListControl: Removed unused selector logic

---

cfgov/unprocessed/js/modules/util/validators.js
cfgov/v1/forms.py
test/unit_tests/js/modules/util/validators-spec.js

Allow dashes or slashes as delimiter in date fields. This involved a minor refactor of front-end date validation to use shorter regexes, for readability and maintainability.
- Allow dates with `/` or `-` (rather than just `/`) in the "to" and "from" filter fields in filterable lists.
1. Running this branch, visit any filterable list. e.g. http://localhost:8000/about-us/newsroom/
2. Expand the filter controls, try putting several different date formats in the "to" and "from" date fields
- Dates in these formats should not produce a "invalid date" error message: 1/22/2017, 11/4/09, 3-31-20, 1-1-1900, 5/2018, 12/18, 05-2010, 1/17, 2016
- Date with these formats should prevent the form from submitting, and show a "invalid date" error message: 305-20-2018, 8//2018, 90, 4/20000
No visual …

Filterable Lists: Allow - or / as delimiter in date fields

---

package-lock.json
package.json

We already depend on highcharts transitively via cfpb-chart-builder. This PR just makes this dependency explicit which allows yarn & npm installs to generate `node_modules` with highcharts as a direct dependency (ie, `node_modules/highcharts` exists).
This allows us to [import highcharts directly](https://github.com/cfpb/cfpb-chart-builder/pull/156) in both npm and yarn.

Include highcharts directly

---

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
cfgov/unprocessed/js/organisms/FilterableListControls.js
test/unit_tests/js/modules/util/atomic-helpers-spec.js

Multiselect initialization was scoped inside `if ( _dom.classList.contains( 'o-filterable-list-controls' ) ) {`, however, the `checkDom` utility already checks this, so this will always evaluate to true. Instead the length of the initialized multiselects array should be checked, but in that case since the if statement encloses a forEach loop, we can just call the loop and if it's empty it won't run.
- Unused `_filter_option` macro.
- Unneeded if statement.
- Add test to `instantiateAll` that ensures it returns an empty array when nothing to initialize is found.
2. `gulp test:unit` passes.
2. http://localhost:8000/about-us/blog/ should work as before.

Filters: fix incorrect multiselect initialization logic and remove unused macro

---

package-lock.json
package.json

- Bumps chart builder to 5.1.0, giving us full yarn/npm compat via https://github.com/cfpb/cfpb-chart-builder/pull/156

Bumps chart builder to 5.1.0

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py
requirements/optional-public.txt

Step one of two for consolidating TDP URL files and removing TDP feature flags.
- TDP related feature flags have been removed
- Started the process of consolidating the TDP URL files. Once this branch is merged into master,
I can go back and remove the extraneous bb_url, begin_url, and tool_url files.
- Bumped the version of TDP to 1.0.27
All the following URLs should continue working as expected.
practitioner-resources/youth-financial-education/learn/
practitioner-resources/youth-financial-education/teach/
practitioner-resources/youth-financial-education/teach/activities/
practitioner-resources/youth-financial-education/glossary/
practitioner-resources/youth-financial-education/resources-research/
practitioner-resources/youth-financial-education/curriculum-review/ …

[TDP] consolidate urls remove feature flags

---

cfgov/unprocessed/js/routes/es/obtener-respuestas/single.js
cfgov/unprocessed/js/routes/external-site/index.js

https://github.com/cfpb/cfgov-refresh/pull/4635 missed converting these imports, which are showing up as errors in New Relic.
- Convert `require` to `import` in Analytics modules.
- Convert `require` to `import` in ExternalSite module.
1. Pull the branch down and `gulp clean && gulp build`
2. http://localhost:8000/es/obtener-respuestas/como-puedo-recuperar-mi-dinero-despues-de-descubrir-una-transaccion-no-autorizada-o-la-falta-de-dinero-de-mi-cuenta-bancaria-es-1017/ should have no errors related to addEventListener.
3. Visit http://localhost:8000/policy-compliance/rulemaking/regulations/ and click "introduction to regulations" and see that it goes to the external site page and counts down and redirects correctly without error.

Fix imports on Spanish page and external site page

---

requirements/libraries.txt

This release of Django-Flags fixes a problem where `ProgrammingError`s and `OperationalErrors` could occur during the Django system checks when Django-Flags migrations hadn't been run yet (including when trying to run them for the first time).

Bump Django-Flags to 4.0.3

---

.travis.yml

Instead of just limiting the docs to deploy when we do a release to production, we want the docs to be in sync with the latest codebase on master. Anytime someone PRs then merges to master a documentation change, the doc site will deploy those changes.
- add condition to docs deployment to only run if the build is not triggered by a pull request. this is so the docs don't deploy when pull requests are created! but they should when master branch build is triggered.
- builds on tagged releases (the regex) - with this change, Travis builds will run on the master branch only when Travis Setting "Build pushed branches" is on. Pushes to other branches should not trigger Travis builds. Since yesterday this is true for master AND tags. With this PR, it will only be true for master.
- limiting doc …

Deploy docs on all builds on master instead of just tagged releases

---

requirements/optional-public.txt

Updating the version of satellite app `ccdb5-api` to version 1.1.7
- Updated version in `optional-public.txt`

Bump ccdb5-api version to 1.1.7

---

cfgov/unprocessed/apps/financial-well-being/js/fwb-questions.js
cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/index.js
cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/results/index.js

Missed in https://github.com/cfpb/cfgov-refresh/pull/4635
- Converts missed financial well-being exports to es6 modules.
1. `gulp clean && gulp build` and visit http://localhost:8000/consumer-tools/financial-well-being/
and see that there is not a `'exports' of object '#<Object>'` error in the dev console.

Fix exports error in financial well-being

---

mkdocs.yml

As a followup to #4688, this adds an "Edit on GitHub" link to the documentation to make it easier for people to maintain this documentation.
1. `pip install -r requirements/docs.txt`
2. `mkdocs serve`
3. http://localhost:8000/

Add "Edit on GitHub" link to docs

---

cfgov/v1/forms.py
cfgov/v1/tests/test_forms.py
cfgov/v1/tests/util/test_date_filter.py
cfgov/v1/util/date_filter.py

Improve the user experience of the date filters on Filterable Lists pages by making the behavior more transparent and intuitive.
- When the user enters an ambiguous date (e.g. "2017" or "6/18" instead of a full date), show what we've interpreted the date as by replacing their input in the form with the full date.
- When the user enters an ambiguous date in the "from" field, interpret it as the beginning of the time period (e.g. "1/1/2017" or "6/1/2018" respectively)
- When the user enters an ambiguous date in the "to" field, interpret it as the end of the time perod (e.g. "12/31/2018" or "6/30/2018" respectively)
- When the user leaves the "from" field blank (but fills in the "to" field), use the publication date of the earliest possible search result as the "from".
- When the user leaves …

Filterable Lists: Improved date filter behavior

---

requirements/docs.txt
requirements/local.txt

The current project requirements included some dependencies on the [django-livereload](https://pypi.org/project/django-livereload/) project, which gets installed as the `livereload` package. This conflicts with the [livereload](https://pypi.org/project/livereload/) package, which also gets installed as `livereload`, and is needed by the latest version of MkDocs.
This conflict means that if, as part of setting up your environment, django-livereload gets installed second, doc building doesn't work:
```sh
$ mkdocs serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
Traceback (most recent call last):
...
File "/Users/me/.virtualenvs/cfgov-refresh/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 36, in _livereload
from livereload import Server …
```

Fix livereload conflict with docs requirements

---

cfgov/jinja2/v1/_includes/molecules/social-media.html

Fixes [GHE]/CFGOV/platform/issues/3196
- Converts urlencoded spaces `%0A%0A` to actual spaces. They get urlencoded further on at https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/molecules/social-media.html#L56
1. Visit https://consumerfinance.gov/find-a-housing-counselor/ and click the share via email link at the bottom and check the email that's produced. There will be `%0A%0A` at the end of the URL in the email body.
2. Pull this branch and visit http://localhost:8000/find-a-housing-counselor/ and click the share via email link at the bottom and check the email that's produced. There will be no urlencoded things in the email body.
Before:
After:

Fix URL encoding in email share

---

docs/testing-be.md

This PR adds a link to our upcoming [Unittesting Django and Wagtail](https://github.com/cfpb/development/blob/unittesting-django-wagtail/guides/unittesting-django-wagtail.md) documentation and updates the documentation about our tox environments to match current reality. It also removes some of the linting documentation and instead links to the development repo where that info is maintained.

Add links to the new unit testing doc and update tox info

---

.gitignore

This commit removes a deprecated `.gitignore` entry for `docs/scripts` (because there are no scripts in this location) but adds one for `site/`, the [target directory for the MkDocs build](https://www.mkdocs.org/#building-the-site).
Because Travis builds the documentation from the source Markdown files, and creates its own `site/` directory which then gets pushed to gh-pages, local changes to `site/` should never be committed. Adding this directory to the `.gitignore` means that local documentation builds won't show up in a `git diff`.
1. `pip install -r requirements/docs.txt` to install documentation requirements.
2. `mkdocs build` to build the documentation locally.
3. `git status` - note no local changes detected.

Update documentation .gitignore

---

cfgov/jinja2/v1/_includes/organisms/featured-content.html
cfgov/jinja2/v1/browse-basic/index.html
cfgov/jinja2/v1/browse-filterable/index.html
cfgov/jinja2/v1/newsroom/index.html
cfgov/jinja2/v1/sublanding-page/index.html
cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html
cfgov/v1/atomic_elements/molecules.py
cfgov/v1/atomic_elements/organisms.py
cfgov/v1/models/browse_filterable_page.py
cfgov/v1/models/browse_page.py
cfgov/v1/models/sublanding_filterable_page.py
cfgov/v1/models/sublanding_page.py

This PR addresses a few things, most urgently the inability to compare revisions on any page that has an FCM (due to the outdated `FeaturedContent` `template` property). 
It moves the Python code to organisms to be consistent with that change in the front-end code, and removes the `macro`-based rendering setup to the more standard Wagtail `include_block` method. 
It also corrects a lingering template issue with empty link list markup when no link was set up.
- Moves the `RelatedPosts` class from `molecules.py` to `organisms.py`
- Updates page templates to render `RelatedPosts` blocks via `include_block` instead of `macro.render()`
- Fixes `related-posts.html` template logic to not render empty link list markup if no links are present
- Unused `macro_link` stuff in `related-posts.html`
1. …

Move FCM class to organisms, convert rendering of it to include_block

---

cfgov/housing_counselor/jinja2/housing_counselor/index.html
cfgov/unprocessed/apps/find-a-housing-counselor/css/main.less

Fixes [GHE]/CFGOV/platform/issues/3200
CF should be imported by reference NOT directly or we end up with two copies!
We're going to stick with the default CF appearance for `dl`, instead of making the contact details look like before (e.g. have lowercase text). Checked this with @schaferjh 
- Changes cf-core import to an import by reference.
- Changes paragraph to `dl` list markup.
- Adds schema.org microdata markup.
1. Pull branch and visit http://localhost:8000/find-a-housing-counselor/?zipcode=20002
1. See changed contact details to result items.
1. Microdata can be tested by inspecting the DOM and copying a result entry HTML as a snippet and pasting into https://search.google.com/structured-data/testing-tool
Before:
After:

Housing counselor: update markup semantics and CF importing

---

cfgov/housing_counselor/jinja2/housing_counselor/index.html

- Adjusts erroneous sharing text in sharing buttons.
1. Pull branch and visit http://localhost:8000/find-a-housing-counselor/?zipcode=20002
2. Click social media sharing links at the bottom of the page and check output. 
- I'm not logged into Facebook and Linkedin on my work machine so can't verify these. Anyone else logged in? I'll be able to check on another machine after this hits prod.

Housing counselor: Update sharing text

---

cfgov/jinja2/v1/_includes/organisms/featured-content.html

If you don't include `if value.links[0]`, the check won't resolve before getting to `[if] value.links[0].text` and you get an error that there is no `value.links[0]` to check for having a `text` property.
1. Visit http://localhost:8000/adult-financial-education/ to see the error
1. Pull branch
1. Reload the page and see it working

Revert overly aggressive condition simplification in FCM template

---

cfgov/jinja2/v1/_includes/organisms/email-popup/base.html
cfgov/unprocessed/css/organisms/email-popup.less

Closes GHE/CFGOV/platform/issues/3129
- Switches close button to an actual button. This inserts it into the tab index and is more semantically correct.
- Adjusts styling to match current anchor styling
1. Pull branch and `yarn run gulp styles`
2. Go to http://localhost:8000/owning-a-home
- You may need to localStorage.clear() and refresh if the "Buying A House?" popup doesn't activate on scroll.
3. Once the popup is activated, you should be able to tab to the close button and close the popup with enter.
4. Styling of the close button should match the one at https://consumerfinance.gov/owning-a-home

Switches email-popup close widget from an anchor to a button.

---

cfgov/v1/forms.py

Fix a `500` error that is currently happening on the [Events page](https://www.consumerfinance.gov/about-us/events/) when the user enters a "to" date but not a "from" date in the filter controls. 
Since there are no upcoming events scheduled, the set of upcoming events is empty. We try to use the date of the first page in the filterable page list to fill in the "from" date field, which doesn't work when the first page was `None`.
- Default the "from" date to 1/1/2010 when there isn't an actual "first post" whose date we can use.
1. Running this branch, visit http://localhost:8000/about-us/events/
2. If your data is up-to-date, the list of Events on the page will be empty
3. In the filter controls, enter a "to" date but not a "from" date
See that you don't receive a `500` error, though you …

Bugfix: When there are no filterable pages, use reasonable default

---

cfgov/unprocessed/apps/find-a-housing-counselor/js/common.js

IE11 doesn't support `parseInt` on the `Number` object, but instead only has the global `parseInt`. This adds a small polyfill to add it to the `Number` object.
- Adds `Number.parseInt` polyfill to housing counselor script.
2. Perform a search on the housing counselor page in IE11.
3. Clicking a map icon should not produce an error and should scroll the page to a result list item.

Housing counselor: Polyfill parseInt for IE11

---

cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/chart.js
cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/apps/map.js

Fixes [GHE]/CFGOV/platform/issues/3211
When converting to ES6 modules the map was erroneously importing the chart's store and actions.
- Update import statements to use actual name of class that is imported.
- Fix incorrect import of chart store on maps.
2.  Visit http://localhost:8000/data-research/mortgage-performance-trends/mortgages-90-or-more-days-delinquent/
3. Change state or date drop-downs and see that map updates.
- `actions` should really not be generic across chart and map and instead should be named after what is being imported, namely `chartActionCreators` and `mapActionCreators`.

Mortgage Performance Trends: Fix incorrect store

---

docker-compose.yml
docker/docs/Dockerfile
docker/docs/entrypoint.sh
docs/development-tips.md
requirements/docs.txt

This PR adds another Docker container called "docs" that will run `mkdocs serve` on port 8888. This means that we always have a running copy of the docs along side the running cfgov-refresh on port 8000.
The "docs" container runs Python 3.6 to run MkDocs.
Because of the version of Python 3.6 (3.6.6 from EPEL), I had to downgrade the "futures" requirement. That does not seem to cause any problems for MkDocs or other pacakges.
This is a proof-of-concept PR for your consideration.
1.  Run `docker-compose up`. The "docs" container should get built along with the others.
2. View cfgov-refresh at http://localhost:8000/ as usual
3. View docs at http://localhost:8888/

Add a docs Docker container that serves the docs on port 8888

---

cfgov/housing_counselor/jinja2/housing_counselor/index.html

Social media molecule was inside full-width-text organism, however, the [template for full-width-text organism](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_includes/organisms/full-width-text.html) does not contain a social media molecule.
This change fixes [GHE]/CFGOV/platform/issues/3205 in Safari.
- Moves social media molecule outside of the full width text organism.
1. Check bottom of https://www.consumerfinance.gov/find-a-housing-counselor/ in Safari 12.0.1 and see extra scrollbar.
2. Check this branch in http://localhost:8000/find-a-housing-counselor/ in Safari 12.0.1 and see that extra scrollbar is absent and otherwise page is the same.

Housing counselor: Moves social media out of full-width-text organism

---

docs/contributing-docs.md
docs/development-tips.md
mkdocs.yml

This PR moves the documentation documentation from the "Development Tips" document into its own document and fleshes that document out a bit with some links to our Markdown extensions and some information about how to build and run the documents.
The running documentation assumes that #4709 will be merged.
Rendered by GitHub: https://github.com/cfpb/cfgov-refresh/blob/contributing-docs/docs/contributing-docs.md

Add "Contributing to Docs" doc

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

Add a feature flag, FINANCIAL_WELLBEING_HUB so we can run user testing the week of January 2nd, before launching the pages. When the flag is enabled, the new financial well-being hub will be published only the Beta server.

Add feature flag to publish new financial well-being hub to Beta

---

cfgov/cfgov/urls.py

`/practitioner-resources/financial-well-being-resources/` should show a 404 page, but instead it is causing a 500 error. This PR fixes the bug that was causing the error.
The issue was that the code used `fallback=page_not_found`, which doesn't work. Instead, we can use a convenience method called `flagged_wagtail_only_view`, which has the correct fallback as the default.
- Use `flagged_wagtail_only_view` to conditionally show Wagtail content when a flag is enabled, rather than duplicating its code.
1. Running this branch, visit http://localhost:8000/practitioner-resources/financial-well-being-resources/
2. If you have `debug = True` in your Django settings, you'll see a 404 page with the message "flag FINANCIAL_WELLBEING_HUB not set". You won't see a 500 error page.
(optional steps)
3. …

Fix 500 error on Financial Wellbeing page

---

docs/atomic-structure.md
docs/editing-components.md

- A new how-to on creating a new component
- Instructions on using wagtail-inventory in the data migration how-to
- General tidying-up on the `atomic-structure.md` and `editing-components.md`
1. Pull branch
1. Follow the steps at https://cfpb.github.io/cfgov-refresh/contributing-docs/#running-the-docs-locally
1. View the two changes pages

Improve component docs

---

cfgov/housing_counselor/jinja2/housing_counselor/index.html
cfgov/unprocessed/apps/find-a-housing-counselor/css/hud.less
cfgov/unprocessed/apps/find-a-housing-counselor/js/common.js

"Print list" link was showing when JS was turned off, which is non-functional without JavaScript. ~~This PR hides that link and shows it via JS.~~
- Makes housing counselor "print list" link hidden via CSS in `no-js` state.
1. Pull this branch and `gulp clean && gulp build`
2. Load http://localhost:8000/find-a-housing-counselor/?zipcode=12345 and see that "Print list" link is visible.
3. Go into dev console settings and disable JS and reload the page. See that the "Print list" link is hidden.

Housing counselor: Hide print list button on no-js state

---

docs/development-tips.md

This section of the development tips page is outdated and incorrect.
Django doesn't do this kind of global template matching by default unless the urls.py has been configured that way. We don't have that set up -- Wagtail handles any URLs that aren't otherwise specified in urls.py.

Remove outdated docs on simple static templates

---

docs/testing-be.md

One of the links on the backend testing page is broken, as it refers to a branch of the [cfpb/development](https://github.com/cfpb/development/) repo that no longer exists. That branch has been merged to master, so this PR updates the link.
To test, run the docs locally and then visit http://localhost:8888/testing-be/#linting.

Fix broken documentation link

---

cfgov/unprocessed/css/main.less
cfgov/unprocessed/css/molecules/multiselect.less
cfgov/unprocessed/css/organisms/filterable-list-controls.less
cfgov/unprocessed/js/molecules/Multiselect.js
docs/testing-fe.md
test/browser_tests/cucumber/features/suites/default/multiselect.feature
test/browser_tests/cucumber/step_definitions/multiselect.js
test/browser_tests/page_objects/base-filterable-page.js
test/browser_tests/shared_objects/filterable-list-control.js
test/browser_tests/shared_objects/multiselect.js
test/unit_tests/js/molecules/Multiselect-spec.js

We have a mix of multi-select and multiselect. To standardize on the non-hyphen, this changes references and filenames to multi-select to multiselect.
- Change references and filenames from "multi-select" to "multiselect"
1. `gulp build && gulp test:unit` should pass. Also Travis should pass here.

Rename multi-select references multiselect

---

cfgov/ask_cfpb/scripts/export_ask_data.py
cfgov/ask_cfpb/templates/admin/export.html
cfgov/ask_cfpb/tests/models/test_pages.py
cfgov/ask_cfpb/wagtail_hooks.py

This introduces a self-service option for downloading Ask CFPB data.  See GHE/CFGOV/enhanced-cms/issues/86 for more context.
Currently, this is done by a developer via a management script, and the spreadsheet is then shared with the team requesting it.  This PR adds a self-service option via the Wagtail admin. The spreadsheet produced will remain the same. 
- Download interface
- Add test coverage

Add option to Export Ask data from Wagtail admin

---

cfgov/core/management/commands/inactive_users.py
cfgov/core/tests/test_management_inactive_users.py

Our current method for detecting inactive users relies on the `last_login`
value, which can languish if a user doesn't log out for a while.
To help keep user accounts active in such a case, we add a check for
the most recent page update made by the user. A user who hasn't logged out
in a while but *has* edited a page won't get deactivated.
Related internal issue: 3186.
To run tests and see coverage:
```bash
tox -e fast core
coverage report -m | egrep "Stmts|core/man"
```

Improve inactive-user detection

---

.github/PULL_REQUEST_TEMPLATE.md

This PR changes the name of the link in the PR template checkbox for code changes that meet our standards to be consistent with how we refer to the target of that link elsewhere. It is now "CFPB development guidelines" instead of "development playbook."

Rename the "development playbook" checkbox link for consistency

---

cfgov/jinja2/v1/_includes/organisms/search-bar.html
cfgov/unprocessed/css/enhancements/forms.less

Closes GHE/CFGOV/platform/issues/3131
-
- CSS rule disabling the default outline for `.input-with-btn input`
- Moves ask search-bar_label to a true label
1. Pull & yarn run gulp build
2. Navigate to /ask-cfpb/ and focus on the search bar. The default dotted outline should appear.
3. Note that stylistically the search-bar_label is unchanged (although now it is more semantically correct).
Slight caveat to point 3, you'll note that clicking on the label text will now focus on the search input. I think this is a feature, so I didn't disable this behavior, although it is different from live. Also note that the cursor remains `default` over the label rather than `text`. I think this makes sense as well (and seems to match other labels on the site) but is another slight difference from live.

Switch ask search div to label and show outline on focus

---

cfgov/jinja2/v1/_includes/organisms/search-bar.html

Updates name of `search-bar.html` input to match query term expectations in [Ask search view](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/ask_cfpb/views.py#L116).
- Update search bar input name
2. Navigate to http://localhost:8000/ask-cfpb/search/ and verify that search works as expected

Update name of search bar input for Ask search

---

requirements/optional-public.txt

This change bumps the version of the optional django-college-costs-comparison satellite app from 1.8.0 to 1.8.1.
This fixes a 500 error related to invalid POSTs to a certain API endpoint.

Bump django-college-costs-comparison to 1.8.1

---

cfgov/jinja2/v1/ask-cfpb/answer-page-spanish-printable.html

Greatly assists with GHE/CFGOV/platform/issues/2574 and GHE/CFGOV/platform/issues/3185
On spanish ask-cfpb print pages (which have mostly identical content but simpler styles), the back link is broken. This fixes it by setting the backlink url to the parent page `../` which will always be correct as the print page for a given `url` is generated at `url/imprimir`. Visiting `../` from `url/imprimir` returns you to `url`.
- Instead of trying to get the appropriate page with a Wagtail `slugurl` call, just reference the parent page relatively.
1. Visit any spanish ask page (eg /es/obtener-respuestas/despues-de-pagar-mi-hipoteca-en-total-como-reviso-si-el-gravamen-lien-fue-liberado-es-206/imprimir/) and the back link ("Regresar al respuesta") should return to the standard spanish ask page.

Reference parent page relatively in backlink from spanish ask print page

---

cfgov/jinja2/v1/_includes/organisms/chart.html
cfgov/jinja2/v1/_includes/organisms/email-signup.html
cfgov/jinja2/v1/_includes/organisms/featured-content.html
cfgov/jinja2/v1/_includes/organisms/full-width-text.html
cfgov/jinja2/v1/_includes/organisms/image-text-25-75-group.html
cfgov/jinja2/v1/_includes/organisms/image-text-50-50-group.html
cfgov/jinja2/v1/_includes/organisms/mortgage-performance-downloads.html
cfgov/jinja2/v1/_includes/organisms/sidebar-breakout.html
cfgov/jinja2/v1/_includes/organisms/video-player.html

Code comments reference deprecated component wiki docs on flapjack repo. This updates those comments to point to the hubcap docs, where those equivalent docs exist.
Missing equivalents are:
[GHE]/flapjack/Modules-V1/wiki/Item-Introduction (is found in design manual)
[GHE]/flapjack/Modules-V1/wiki/Contact-Information-(Main-Content-Area)
[GHE]/flapjack/Modules-V1/wiki/Mortgage-Chart
[GHE]/flapjack/Modules-V1/wiki/Mortgage-Map
[GHE]/flapjack/Modules-V1/wiki/Contact-Information-(Sidebar)
[GHE]/flapjack/Modules-V1/wiki/Tables (is found in design manual)
[GHE]/flapjack/Modules-V1/wiki/Well (is found in design manual)
- Changes links from flapjack to hubcap repo, where there are equivalent pages.
- Fixes some wonky whitespace.

Update code comments to reference hubcap, where possible

---

cfgov/v1/templates/cdnadmin/index.html
cfgov/v1/tests/test_admin_views.py

We should be more clear that when flushing Akamai for a specific page, it is necessary to enter a full URL.
Also includes some formatting cleanup.
1. Pull branch
1. Replace your [Akamai settings in `cfgov/cfgov/settings/base.py`](https://github.com/cfpb/cfgov-refresh/blob/Scotchester-patch-1/cfgov/cfgov/settings/base.py#L479-L489) with:
```py
ENABLE_AKAMAI_CACHE_PURGE = True
if ENABLE_AKAMAI_CACHE_PURGE:
WAGTAILFRONTENDCACHE = {
'akamai': {
'BACKEND': 'v1.models.akamai_backend.AkamaiBackend',
'CLIENT_TOKEN': 'fake',
'CLIENT_SECRET': 'fake',
'ACCESS_TOKEN': 'fake',
},
}
```
1. Visit http://localhost:8000/admin/cdn/ and see the updated message.

Add explicit note about using a full URL when clearing the cache

---

cfgov/v1/forms.py

Add 'of' to error message copy per @schaferjh approval.
- Add 'of' to FilterableListControl date error message copy.
1. Visit `http://localhost:8000/about-us/newsroom/?title=&from_date=1%2F1%2F1800` and note error message.

Filter: Add 'of' to error message copy

---

cfgov/unprocessed/js/organisms/FilterableListControls.js

Fixes issue where the notification is shown in the default styling (error introduced in https://github.com/cfpb/cfgov-refresh/pull/4760)
- Get notification state from class, not instance.
1. http://localhost:8000/about-us/blog/?title=&from_date=asdf should show a red error notification, not a grey one.

Filter: Fix default styling of notification

---

cfgov/scripts/test_data.py
cfgov/unprocessed/js/organisms/FormSubmit.js
test/browser_tests/cucumber/features/suites/default/feedback-form.feature
test/browser_tests/cucumber/step_definitions/feedback-form.js

A couple of Notification module references in `FormSubmit.js` are breaking feedback form replacement on production -- the form can be submitted, but an error prevents its replacement with a success notification, leaving a large blank space where the form had been (see an [Ask CFPB question](https://www.consumerfinance.gov/ask-cfpb/i-would-like-to-be-able-to-have-my-friend-or-family-member-help-with-my-bill-paying-and-banking-what-are-my-options-en-1145/) for an example). This PR updates the references and adds acceptance tests for feedback form notifications and replacement.
- Acceptance tests for feedback form replacement
- Notification module references in `FormSubmit.js`
1. Check out branch and run `gulp scripts`
2. Navigate to [an Ask CFPB answer …

Fix issue with feedback form replacement and add acceptance tests

---

cfgov/v1/models/browse_filterable_page.py
cfgov/v1/models/sublanding_filterable_page.py

This change modifies the behavior of BrowseFilterablePage and SublandingFilterablePage to ensure that at most one FilterControls ~~or Feedback block~~ is entered into the page's content StreamField. Thanks to @anselmbradford for suggesting this change.
We only ever want at most one of these blocks on a page. After this change, trying to save a page with multiple blocks of these types will produce a validation error like this:
Unfortunately there's currently no client-side validation in Wagtail, i.e. it still lets you add the block and only prevents saving. Client-side validation of block limits will be added as part of the Wagtail StreamField rewrite being done in https://github.com/wagtail/wagtail/issues/4473.
This logic could probably be expanded to other pages and blocks. I did an …

Enforce only one filterable list per page

---

cfgov/ask_cfpb/templates/admin/export.html

We can remove the line that states it will take up to a minute now that we've modified the script (in https://github.com/cfpb/cfgov-refresh/pull/4769) to run much faster (completes in a few seconds on production).  
Purely visual changes -- see screenshot below.

Update Ask CFPB export help text 

---

cfgov/v1/util/util.py

Since the structure of newsroom/press resources is identical to events/request a speaker, it looks like we can follow the structure there and fix the issue where "Press resources" doesn't get highlighted in the side navigation menu.
- Legacy logic for the secondary navigation menu when the newsroom page was not in wagtail.
1. Visit your local wagtail admin and set the following:
- On the "newsroom" page in Wagtail, check this setting in the sidefoot:
- On the "press resources" page in Wagtail, uncheck this setting in the config:
Publishing both pages should show a menu like below…
- When this goes to production the wagtail steps in the "testing" section above need to be performed. I'm not certain what the best way to do this is?

Remove non-wagtail newsroom logic from utils.py

---

docs/migrations.md

This moves the formerly internal "Recreating migrations" document into our existing public "Django and Wagtail migrations" document. It re-works the introductory content of the "Recreating migrations" section to reference the rest of the document and ensure the information that it needs to reference is there. Otherwise this is a straight forward move of the existing content.

Add recreating migrations to migration doc

---

requirements/optional-public.txt

comparisontool-1.9.0 removes feedback code so that Wagtail can handle feedback duties.

bump comparisontool requirement

---

cfgov/ask_cfpb/tests/test_hooks.py
cfgov/ask_cfpb/wagtail_hooks.py
cfgov/unprocessed/css/rich-text.less
cfgov/v1/tests/test_wagtail_hooks.py
cfgov/v1/wagtail_hooks.py

This is needed to experiment with some schema markup to improve search result formatting.
- New allowed HTML elements in rich text fields: `div`, `h4`, `p`, `span`
- New allowed HTML attributes in rich text fields: `itemprop`, `itemscope`, `itemtype`
1. Open an Ask CFPB answer for editing
1. Click the HTML editor button in its rich text field
1. Add in some of the new elements and attributes
1. Save the answer
1. Reopen the HTML editor in the RTF to see that the new stuff has not been stripped
1. Go to the answer's page and preview it
1. Inspect the answer content to see the elements are present on the rendered page
- ~~Though I have added `div` here, for reasons I don't understand, `div` elements still get stripped~~ Explained below.

Add some styling and new allowed HTML markup to RichTextField to support schema markup

---

cfgov/jinja2/v1/_includes/organisms/filterable-list.html
cfgov/jinja2/v1/_includes/organisms/post-preview-snapshot.html
cfgov/jinja2/v1/_includes/organisms/post-preview.html
cfgov/jinja2/v1/sublanding-page/index.html
cfgov/v1/atomic_elements/organisms.py
cfgov/v1/util/ref.py

This change proposes an alternative to #4772 and #4790.
This change makes it possible to disable the rendering of post preview tags and dates when rendered as part of a filterable list. This is now possible via [code in the `FilterableList` StreamField block](https://github.com/chosak/cfgov-refresh/blob/98b59e44bdb6783005dc0f87f30e7c904dbad6f3/cfgov/v1/atomic_elements/organisms.py#L918), and is dependent on the "page_type" set on the FL, which is an optional setting that a page editor can define.
This change adds a new page type of "cfpb-researchers" and disables rendering of post preview dates for it (#4790). It also disables rendering of post preview tags for the "foia-freq-req-record" page type (#4772).
A side effect of this change is to add a proper Wagtail StreamField block template …

Allows page type-specific post preview rendering

---

requirements/libraries.txt

This commit removes the unpinned [pytz](https://pypi.org/project/pytz/) from our requirements. Pytz is installed by Django:
https://github.com/django/django/blob/1.11.18/setup.py#L50
And so we don't need to specify it explicitly.
Note that pytz was unpinned and is unpinned by Django; this is intentional as it gets updated with every timezone change, which happens [quite frequently](https://github.com/stub42/pytz/blob/master/tz/NEWS).
See also [this excellent talk](https://www.youtube.com/watch?v=qabriMQ1SYs) from DjangoCon US 2018.

Removes pytz from project requirements

---

cfgov/jinja2/v1/owning-a-home/_templates/no_js.html
cfgov/jinja2/v1/owning-a-home/_templates/ratings-form.html
cfgov/jinja2/v1/owning-a-home/closing-disclosure/index.html
cfgov/jinja2/v1/owning-a-home/explore-rates/index.html
cfgov/jinja2/v1/owning-a-home/loan-estimate/index.html
cfgov/unprocessed/apps/owning-a-home/browserslist
cfgov/unprocessed/apps/owning-a-home/css/no-js.less

https://consumerfinance.gov/owning-a-home/explore-rates/ has a no-js banner in IE10, but the text is erroneous (see [GHE]/CFGOV/platform/issues/3045). 
https://www.consumerfinance.gov/owning-a-home/closing-disclosure/ and https://www.consumerfinance.gov/owning-a-home/loan-estimate/ are accessible in IE10, but do not work. Additionally, the bottom gap below the feedback form on these two pages differs.
This PR updates to the OAH/BAH no-js state banner to be applicable to both when JS is turned off and also when a legacy browser is used. 
- Updates markup structure so the rate-explorer and form-explainers are in their own div container and aren't mixed with `content_main`.
- Updates no-js notification text to "This tool is not supported in your browser. Please try a newer browser and check …

Updated OAH/BAH to align IE10 support

---

cfgov/cfgov/settings/base.py

I accidentally committed hard-coded date ranges for the complaint intake maintenance banner. This PR removes them.

Remove hard-coded dates for complaint banner

---

cfgov/jinja2/v1/owning-a-home/explore-rates/index.html
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/RateCheckerChart.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/RateCheckerChartMenu.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/Slider.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js
test/unit_tests/apps/owning-a-home/js/explore-rates/RateCheckerChartMenu-spec.js

- Adds missing jsdocs to BAH methods.
- Adds missing MIME type for PNG in chart export.
- Removes "RateCheckerChartMenu.STATES" export as it was only exported for the tests.
- Removes test of internal private method "_setState".
- Unused references in Slider.js.
- Converts open/closed state of chart download menu to simple strings from an object to remove need for Object.assign.
- Converts logic stored in data- attributes to directly use textContent of list nodes in download menu.
- Removes complexity warning from exportChart method by converting switch into if/else and an object lookup hash.
- Update RateCheckerChartMenu test markup structure to follow that of production.
1. Pull the branch and `gulp clean && gulp build`
2. The "Download chart" options in the upper-right of the chart on …

Simplify RateCheckerChartMenu and fix BAH linter warnings

---

cfgov/jinja2/v1/owning-a-home/closing-disclosure/index.html
cfgov/jinja2/v1/owning-a-home/loan-estimate/index.html

Unreferenced or documented `subnav` variable appears to be unused in this template and is not present in the sibling template at https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/owning-a-home/closing-disclosure/index.html#L46
- Remove logic to add `col-9` class when `subnav` variable is present in the template.
- Remove unnecessary newline.
1. http://localhost:8000/owning-a-home/loan-estimate/ should work like production.

BAH: Loan explainer, remove col-9 logic

---

cfgov/unprocessed/apps/find-a-housing-counselor/browserslist
cfgov/unprocessed/apps/owning-a-home/browserslist
cfgov/unprocessed/apps/regulations3k/browserslist
config/browser-list-config.js

IE10 gets the no-js treatment. This update aligns the find-a-housing counselor and regs3k browserlists to this support level.
- Removes IE11 and below support from find-a-housing counselor and regs3k browserlists.
- Downcases `IE_Mob` to `ie_mob`
1. /find-a-housing-counselor should still work in IE10 (without a map) and should have a map in IE11.
1. /policy-compliance/rulemaking/regulations/ should still work in IE10 (with expanded expandables) and should have collapsed expandables in IE11.
- I'm not super familiar with what to test in regs3k no-js/js functionality, so I've tagged you @contolini

Update app browserlists to exclude IE10

---

cfgov/unprocessed/css/molecules/multiselect.less
cfgov/unprocessed/js/molecules/Multiselect.js
cfgov/unprocessed/js/molecules/MultiselectModel.js
test/browser_tests/shared_objects/multiselect.js
test/unit_tests/js/molecules/Multiselect-spec.js
test/unit_tests/js/molecules/MultiselectModel-spec.js

Fixes https://[GHE]/CFGOV/hmda-migration/issues/16
- Adds MultiselectModel for managing state of the multiselect items, including filtering, selection, and highlighting.
- Changes the search behavior to remove the minimum characters needed to perform a search (was 3, now it's 1).
- Prefixes multiselect filter utility classes with `u-`.
1. `gulp test:unit --specs=js/molecules/MultiselectModel-spec.js` should have 100% passing coverage.
2. No errors in `gulp test:unit`.
3. `gulp clean && gulp build`
4. Compare filter on http://localhost:8000/about-us/newsroom/ to production. The one difference should be that when you start typing into the input, the list filters, whereas on production it will only filter after minimum of three characters are entered. Try hitting "enter" and tabbing and …

Multiselect: Add model

---

cfgov/v1/models/akamai_backend.py
docs/caching.md

The Akamai v2 API that we used for full-site invalidation is being deprecated and will go away on March 1, 2019. This PR changes our Akamai backend's `purge_all` method to use the v3 API's CP (content provider) code invalidation instead.
Once this PR is merged we'll need to update the `akamai_purge_all_url` value in ansible-consumer-finance before deploying.
I've also added documentation for how to check the cache state of URLs to our cache document.
The existing tests for `AkamaiBackend` do not include tests for `purge()` and `purge_all()`, and I'm of the opinion that this is fine — I'm not sure there's anything to test there except that the requests library properly constructs a request. But this means the coverage test for this PR's diff will fail at less than 100%.
1. Check the …

Use Akamai v3 API for purging the entire site

---

cfgov/unprocessed/js/molecules/Multiselect.js
test/unit_tests/js/molecules/Multiselect-spec.js

Fixes https://[GHE]/CFGOV/platform/issues/3282
Introduced in https://github.com/cfpb/cfgov-refresh/pull/1684
- Fixes issue where checkbox input was incorrectly dispatching a string as an event, not an event object.
- Removes `dom-traverse` dependency from Multiselect.
- Enabled keyboard interaction unit test.
1. Visit /blog
2. Expand filter and click into Topic multiselect.
3. Open the dev console.
3. Hit "enter" key once.
4. Hit the "enter" key again.
5. There should be no error in the console and the checkbox should check and add a selection.
Before:
After:

Multiselect: Fix incorrect event dispatching error

---

cfgov/jinja2/v1/owning-a-home/closing-disclosure/index.html
cfgov/jinja2/v1/owning-a-home/loan-estimate/index.html
cfgov/unprocessed/apps/owning-a-home/js/form-explainer/dom-tools.js
cfgov/unprocessed/apps/owning-a-home/js/form-explainer/form-explainer.js
cfgov/unprocessed/apps/owning-a-home/js/form-explainer/index.js
cfgov/unprocessed/js/routes/owning-a-home/closing-disclosure/index.js
cfgov/unprocessed/js/routes/owning-a-home/loan-estimate/index.js
cfgov/unprocessed/js/routes/owning-a-home/mortgage-estimate/index.js
test/unit_tests/apps/owning-a-home/js/form-explainer/dom-tools-spec.js

It appears that the BAH landing page and the mortgage-estimate page should be showing [a popup](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/cfgov/settings/base.py#L724-L725), however, mortgage-estimate is not showing a popup.
Also, the page-specific form-explainer initialization code in the /routes/ path can be consolidated in the BAH apps code, since those pages have their own templates and /routes/ is only for pages that don't have specific templates.
- Adds add-email-popup initialization code to BAH landing page and mortgage-estimate page.
- Move form-explainer initialization code to BAH apps code and imports into the closing-disclosures and loan-estimate templates.
- Minor linter fixes.
1. `gulp clean && gulp build` should pass.
2. http://localhost:8000/owning-a-home/ and …

Untangle BAH apps and routes paths

---

cfgov/jinja2/v1/owning-a-home/_templates/brand-footer.html
cfgov/jinja2/v1/owning-a-home/_templates/email-signup.html
cfgov/jinja2/v1/owning-a-home/_templates/oah-email-signup.html
test/unit_tests/js/organisms/FormSubmit-spec.js

Buying a home had a duplicate email signup template that contained the same values. It also had a padding issue.
- Redundant oah-email-signup template.
- Hardcodes values in BAH email-signup template.
- Adds `m-form-field-with-button_info` class to privacy link to fix missing padding.
- Minor fix of email address in HTML snippet in FormSubmit-spec.js
1. Visit http://localhost:8000/owning-a-home/loan-estimate/ and check email signup in the footer. Enter an incorrect and a correct email address and see that notifications appear.
Before:
After:

Removes unnecessary code from BAH email signup

---

cfgov/unprocessed/apps/owning-a-home/js/explore-rates/Slider.js
cfgov/unprocessed/js/modules/behavior/FlyoutMenu.js
cfgov/unprocessed/js/modules/util/standard-type.js
cfgov/unprocessed/js/molecules/Autocomplete.js
cfgov/unprocessed/js/molecules/GlobalSearch.js
cfgov/unprocessed/js/molecules/Multiselect.js
cfgov/unprocessed/js/molecules/Notification.js
cfgov/unprocessed/js/organisms/EmailPopup.js
cfgov/unprocessed/js/organisms/FilterableList.js
cfgov/unprocessed/js/organisms/FilterableListControls.js
cfgov/unprocessed/js/organisms/Footer.js
cfgov/unprocessed/js/organisms/Header.js
cfgov/unprocessed/js/organisms/MegaMenu.js
test/unit_tests/js/modules/util/standard-type-spec.js

Our linter flags `undefined` values because of the https://eslint.org/docs/rules/no-undefined rule. 
To get around this we utilize an uninitialized variable to hold the value of `undefined`. However, we inconsistently handle this, sometimes defining a `let UNDEFINED` variable in a module and sometimes importing the standard-type module and referencing the one in there. While it may make sense to always use the one from the standard-type module, the additional dependency complexity of doing that versus the cost of creating a new variable each time does not make sense, at very least from a pure number-of-lines-of-code perspective.
- Removes `UNDEFINED` value from the `standard-type` module.
1. Tests should pass and site should load error-free.

Remove UNDEFINED from standard-type

---

cfgov/unprocessed/apps/financial-well-being/js/fwb-questions.js
cfgov/unprocessed/apps/financial-well-being/js/fwb-results.js
cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/index.js
cfgov/unprocessed/js/routes/consumer-tools/financial-well-being/results/index.js
test/unit_tests/apps/financial-well-being/js/fwb-questions-spec.js
test/unit_tests/apps/financial-well-being/js/fwb-results-spec.js

- Updates fwb modules to support default exports.
- Removes fwb page load logic since the script is added in the footer.
- Initializes expandables in `init` function of fwb-results module, instead at module load-time.
2. http://localhost:8000/consumer-tools/financial-well-being/ should be able to be filled out and submitted and the results page expandable should work.

Remove unnecessary code from financial-well-being and fix init logic

---

cfgov/v1/tests/util/test_migrations.py
cfgov/v1/util/migrations.py
docs/migrations.md

This PR adds some recursion to our Wagtail StreamField-specific data migration utilities to ensure that we can migrate blocks that are children of other blocks.
By way of illustration, [`FullWidthText` block](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/v1/atomic_elements/organisms.py#L712) itself contains a variety of other blocks that could also exist within a StreamField directly. So if we want to migrate all `EmailSignUp`s, we would previously have had to look inside the `FullWidthText` separately for its `EmailSignUp`. 
For example, `LearnPage` contains an `email_signup` `EmailSignUp` block in its `content` StreamField. `BlogPage` has both a `FullWidthText` and a `EmailSignUp` block in its `content` StreamField. If we wanted to perform the same migration on the …

Ensure our data migrations migrate blocks that are children of other blocks

---

cfgov/legacy/templates/common/reset_password_email.html

This PR modifies the password reset email template to remove the "Note" line about removing :443 and changing http to https in the link now that the underlying issue is mitigated.

Remove the note about :443 in password reset links

---

cfgov/unprocessed/apps/owning-a-home/js/explore-rates/data-loader.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/params.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js
cfgov/unprocessed/apps/owning-a-home/js/explore-rates/util.js
cfgov/unprocessed/apps/regulations3k/js/search-utils.js
cfgov/unprocessed/js/modules/transition/BaseTransition.js
cfgov/unprocessed/js/modules/util/assign.js
cfgov/unprocessed/js/modules/util/breakpoint-state.js
cfgov/unprocessed/js/modules/util/dom-events.js
cfgov/unprocessed/js/modules/util/dom-manipulators.js
cfgov/unprocessed/js/organisms/FilterableListControls.js
config/webpack-config.js
test/browser_tests/conf.js
test/unit_tests/js/modules/util/breakpoint-state-spec.js

Turns out IE11 does not support initialization of `const` within a for loop. This changes the code slightly to change `const` values that are initialized in for loops into `let` values before the loop.
- Change `const` value into `let` value for IE11 support.
1. `gulp clean && gulp build` should pass.
2. This was appearing on /owning-a-home/closing-disclosure/ in IE11, but the values in CF would need to be fixed before you will see the error go away (this can be manually done by searching the cf node_modules for `( const` and replacing that line as shown in this PR.
Needs to be fixed and released in CF too. PR here https://github.com/cfpb/capital-framework/pull/890

Fix const in for value for IE11

---

docs/migrations.md

Per a decision made by the backend team in our last huddle, backward data migrations are not required in cfgov-refresh. This change adds a note to that effect in the migration documentation.

Add a note that backward migrations are not required

---

cfgov/jobmanager/models/django.py
cfgov/jobmanager/models/pages.py
cfgov/jobmanager/models/panels.py
cfgov/jobmanager/tests/models/test_blocks.py

This PR makes the jobmanager tests pass with Python 3. 
Two tests continue to fail because there seems to be a bug in the `AtomicTableBlock` rendering that differs between Python 2.7 and 3.6. The `AtomicTableBlock` tests also fail the same way, so I am making the choice to fix the problem when we get to those tests.

Make jobmanager tests work with Python3

---

cfgov/agreements/management/commands/_util.py
cfgov/agreements/management/commands/import_agreements.py
cfgov/agreements/tests/test_legacy.py
cfgov/agreements/tests/test_management.py

The agreements tests and code makes some assumptions about text encoding in zip files that needs to be more explicit in Python 3.
This PR also cleans up some bytes-to-string comparisons, generators-to-lists, and import moves.

Make agreements tests work with Python 3

---

cfgov/cfgov/settings/local.py
docs/development-tips.md

This commit adds the ability to (optionally) log Django database queries to the console by defining a new `ENABLE_SQL_LOGGING` environment variable.
This is useful when trying to debug database interactions, and works against the Django server, interactive shell, and management commands.
The documentation on developer tips has been updated to include this ability.
New documentation section:
This is similar to some functionality that [django-extensions](https://github.com/django-extensions/django-extensions) already provides through its `shell_plus` and `runserver_plus` commands, but doing it via our local settings lets us more easily turn this on globally for things like management commands.

Add ability to log DB queries to console

---

requirements/libraries.txt

This change bumps the version of [wagtail-flags](https://github.com/cfpb/wagtail-flags) used by this project from 4.0.1 to [4.0.2](https://github.com/cfpb/wagtail-flags/releases/tag/4.0.2). This adds a fix that auto-registers the "site" condition, eliminating numerous warnings that currently appear when running the Django shell and local server.

Bump wagtail-flags dependency to version 4.0.2

---

cfgov/jinja2/v1/_includes/organisms/post-preview.html
cfgov/unprocessed/css/organisms/post-preview.less
cfgov/v1/atomic_elements/organisms.py
gulp/tasks/styles.js

This PR contains the LESS changes necessary to implement a new design across the variety of Filterable List pages on our site.
- Added code to hide dates for the Consumer Reporting Companies list
- Added code so that the "categories" element will not appear when there are no categories in a post preview entry.
- Added code so that the pipe ("|") separator appears within a `SPAN`, allowing it to be styled.
- Added LESS to use `grid` for better placement of the category and date (previously used `float`), and for rearrangement in mobile view.
1. Pull down this branch and get it running.
2. Check out filterable list pages!
- http://localhost:8000/administrative-adjudication-proceedings/administrative-adjudication-docket/
- http://localhost:8000/policy-compliance/notice-opportunities-comment/a …

Filterable List: Redesign and Updates

---

cfgov/ask_cfpb/models/pages.py
cfgov/ask_cfpb/tests/models/test_pages.py

The two most recently created answers, 2094 and 2092, have Spanish content but no
created Spanish page. This creates some 404 errors on Spanish category pages,
which find Spanish content in the Answer model and assume there's a page.
- https://www.consumerfinance.gov/es/obtener-respuestas/categoria-ensenar-a-otros/
- https://www.consumerfinance.gov/es/obtener-respuestas/categoria-manejar-una-cuenta-bancaria/
- https://www.consumerfinance.gov/es/obtener-respuestas/categoria-enviar-dinero/
The top entry on each of those pages currently returns a 404.
Visit the above pages locally, and the errant entries should be gone.
If they're not at the top of the list, they aren't there, because the
results are sorted by latest created, and the troublemaker pages are the
most recently created Answers. …

Remove errant Ask entries on Spanish category pages

---

cfgov/ask_cfpb/scripts/export_ask_data.py
cfgov/ask_cfpb/scripts/replace_unsupported_characters.py
cfgov/ask_cfpb/tests/models/test_pages.py

See GHE issue GHE/CFGOV/Ask-Evo/issues/40
Now that https://github.com/cfpb/cfgov-refresh/pull/4818 has been merged (!!), we need to update the Ask export to pull certain fields from the `AnswerPage` instead of the `Answer` (specifically, `answer`, `question`, and `snippet`).  We will further update this with upcoming work to migrate all fields to the `AnswerPage`, but for now we need to do this so that the export continues to be accurate and up-to-date.
I've updated the `test_export_script_assemble_output` test so that it lives with the rest of the `ExportAskDataTests` tests, both for improved readability and to minimize conflicts with the setUp data in the `AnswerModelTestCase`. 
The only functional change this introduces is that the export will now output live versions of what's on a …

Update Ask CFPB export fields 

---

cfgov/v1/tests/util/test_util.py

Travis's run of isort did not catch this, for some reason, so it broke the build on dev.

Fix import sorting that Travis didn't catch

---

cfgov/v1/migrations/0119_rename_image_inset_data.py
cfgov/v1/migrations/0142_migrate_pas_link_data_to_pagechooserblock.py

The email sign-up standardization issue seems to have altered the order in which Django tries to execute migrations when they are all run. According to @chosak, this is because the migration executor tries to optimize the order of the migrations it runs. This started causing our back-end test suite in Jenkins, which runs all migrations front-to-back, to fail.
This PR should rectify that.
1. Prior to pulling this branch, run `tox -e unittest-py27-dj111-wag113-slow` against the latest master to observe the issue.
1. Pull branch
1. Run `tox -e unittest-py27-dj111-wag113-slow` again and see that it passes.

Fix migration dependency errors

---

cfgov/v1/migrations/0142_migrate_pas_link_data_to_pagechooserblock.py
cfgov/v1/tests/migrations/test_0142_migrate_pas_link_data_to_pagechooserblock.py

This should fix the deployments to Build.
1. Pull branch
1. `./refresh-data.sh` to reapply the migrations to last night's database dump and confirm all still works
1. `tox -e fast v1.tests.migrations.test_0142_migrate_pas_link_data_to_pagechooserblock` to confirm that the migration will work for any possible state of `form_field`.

Add more robust fallback for incomplete data in v1 migration 0142

---

cfgov/unprocessed/js/modules/VideoPlayer.js

This PR addresses https://GHE/CFGOV/platform/issues/3287, which reports that YouTube videos are no longer showing their correct preview images, but instead are all showing the fallback CFPB logo.
I traced the cause back to [this change](https://github.com/cfpb/cfgov-refresh/commit/50170057f0fc808d2b6aebc9984b9650d378af31#diff-75e5fea40be00a78d02194824cce179aR44). As noted by [our `assign` util's JSDoc description](https://github.com/cfpb/cfgov-refresh/blob/fix-youtube-thumbnails/cfgov/unprocessed/js/modules/util/assign.js#L17-L19), "fields of every next source will override same named fields of previous sources", so by removing the placeholder `dataSet` variable that was in place prior to that change, the `id` of `this.iFrameProperties` was replacing the `id` in …

Fix missing YouTube video preview images

---

cfgov/housing_counselor/tests/test_views.py

This PR makes it possible to run the `data_research` app's tests with Python 3.6. And, as a result, it starts nibbling around the edges of `v1`. 
1. Run `tox -e unittest-py36-dj111-wag113-fast housing_counselor`

Make the housing_counselor tests comptaible with Python 3.6

---

requirements/requirements.txt
requirements/snyk/README.md
requirements/snyk/django/requirements.txt
requirements/snyk/libraries/requirements.txt
requirements/snyk/postgres/requirements.txt
requirements/snyk/wagtail/requirements.txt

As discussed in https://GHE/CFGOV/platform/issues/3289, this implements [the workaround suggested by the Snyk VP of Engineering](https://github.com/snyk/snyk-python-plugin/issues/21#issuecomment-463514410) for monitoring Python requirements files: creating symlinks that link back to the original requirements files.
The files in the subdirectories of the `requirements/snyk/` directory are symlinks back to the original requirements files in the main `requirements/` directory. They are needed for the current version of the Snyk.io service to be able to check the requirements, since (as of today) it
can only check files named exactly `requirements.txt` and it cannot follow `-r` references to other requirements files.
- Four symlinked `requirements.txt` files for our production Python …

Add symlinked requirements files that Snyk.io can pick up

---

cfgov/regulations3k/models/pages.py

To view draft versions of a regulation using our "View Draft" button, we had been requiring permission to edit the regulation's routable page in Wagtail. The way we configure permissions for regulations editors however is not to give them permission to the Wagtail pages, but just the regulation models.
This PR changes the "View Draft" permission to depend on section edit permission, rather than page edit permission.

Regulations3k: Make draft version permission depend on model permissions not pages

---

cfgov/jinja2/v1/sublanding-page/index.html

FCM contained an if statement without an else block, which led to this error in markup if the FCM was not the first component on the page:
- Adds else block to FCM if statement.
1. Add a sublanding page and add a FCM and any component before it.
2. Preview the page and inspect the markup and see that there is no error message in the markup for the FCM's container.

Fix missing else block in FCM logic

---

cfgov/jinja2/v1/_includes/organisms/email-popup/base.html

Fixes the bug that I recently introduced that prevented the close button on email popups from working.
- Restores the separation of `.o-email-signup` and `.o-email-popup` DOM nodes so that their components' JS does not try to initialize on the same node
1. Load a page with the email popup on it, e.g., http://localhost:8000/owning-a-home/
- You may need to erase your local storage for localhost to get the popup to appear, if you've previously seen it.
1. Scroll down to reveal the popup
1. Observe the close button not working
1. Pull branch
1. Clear local storage and refresh the page
1. Scroll down to reveal the popup
1. Observe that the close button now works

Fix email popup close buttons

---

cfgov/jinja2/v1/_includes/organisms/filterable-list.html

Preview images in 50/50-style filterable lists unfortunately got lost in the shuffle when we broke out the controls template from the list template. This PR fixes that problem.
- Corrects the image data being passed to the info unit template by the filterable list template
1. Load up http://localhost:8000/consumer-tools/everyone-has-a-story/ and see no images
1. Pull branch
1. Reload the page and see empty space where the images would appear, if they were uploaded to your local Wagtail instance
- If you want to double-check things, you can upload a new preview image (on the Configuration tab) to one of the listed stories, then reload the list page and see that it appears.

Fix missing preview images on 50/50-style filterable lists

---

cfgov/ask_cfpb/models/__init__.py
cfgov/ask_cfpb/models/django.py
cfgov/ask_cfpb/models/pages.py
cfgov/ask_cfpb/tests/models/test_pages.py
cfgov/jinja2/v1/_includes/blocks/feedback.html

With a tweak to the v1 feedback template, we can use the
standard feedback module without any customization.
Current pages will pick up the content changes in the
v1 feedback forms.
For new pages, editors will need to add a feedback module, but they
won't have to change any values.
Code coverage is back to 100%!

Use standard feedback module

---

cfgov/ask_cfpb/scripts/answer_to_answerpage_migration.py
cfgov/ask_cfpb/scripts/replace_unsupported_characters.py

Currently, the script is skipping any draft revisions that exist, since by default querying for a page gives back the live version.  This fixes that. 
I've included an updated sanitization script as well.

Update migration script so that it's working off of latest revision

---

cfgov/agreements/templates/agreements/index.html

This PR adds a link to the 2018 Q3 credit card agreements zip as the most recent and relegates 2018 Q2 to archived status.

Add link to Credit Card Agremeents for Q3 2018

---

docs/wagtail-pages.md

Should be "separate" not "seperate".

Fixes typo in docs

---

cfgov/cfgov/settings/base.py
cfgov/housing_counselor/views.py

Python contains a built-in [`format`](https://docs.python.org/3/library/functions.html#format) function:
```
>>> format(123, "06d")
'000123'
```
The use of `format` as a variable in [this method](https://github.com/cfpb/cfgov-refresh/blob/0b3986ca025eb2fe32d6f24057d9c2df94381f58/cfgov/housing_counselor/views.py#L42) confuses our static code analysis tool (Checkmarx) because of this. This commit changes that variable to something more specific, `file_format`.
To test, visit [a housing counselor URL](http://localhost:8000/find-a-housing-counselor/?zipcode=22203) locally and confirm that the data continues to load properly. Also confirm that the "Save list as PDF" link continues to work properly.
Thanks to Lamin for flagging this.

Rename format variable in housing counselor view

---

cfgov/jinja2/v1/_includes/organisms/email-popup/oah.html
cfgov/jinja2/v1/owning-a-home/_templates/brand-footer.html

Making these headers consistent with the other updated sign-up modules.

Update headers on hardcoded BAH email signups

---

cfgov/jinja2/v1/ask-cfpb/answer-page.html

Some of the answer page snippets have internal links which aren't being output correctly
- richtext filter on answer snippet in answer page template
2. Navigate to [answer 1931](http://localhost:8000/admin/pages/5992/edit/)
3. Verify that link in snippet is output correctly

Add richtext filter for answer page snippet

---

cfgov/jinja2/v1/_includes/organisms/table.html
cfgov/v1/admin_views.py
cfgov/v1/handlers/blocks/feedback.py
cfgov/v1/management/commands/update_data_snapshot_values.py
cfgov/v1/migrations/0142_migrate_pas_link_data_to_pagechooserblock.py
cfgov/v1/models/menu_item.py
cfgov/v1/tests/handlers/blocks/test_feedback.py
cfgov/v1/tests/models/test_base.py
cfgov/v1/tests/models/test_resources.py
cfgov/v1/tests/models/test_snippets.py
cfgov/v1/tests/test_forms.py
cfgov/v1/tests/test_wagtail_hooks.py
cfgov/v1/tests/util/test_ref.py
cfgov/v1/tests/views/test_documents.py
cfgov/v1/tests/wagtail_pages/test_page_states.py
cfgov/v1/tests/wagtail_pages/test_page_titles.py
cfgov/v1/util/util.py

This PR makes it possible to run the v1 app's tests with Python 3.6.
With #4866 and #4867 this PR should mean all tests run with Python 3.6 except noted below.
1. Run `tox -e unittest-py36-dj111-wag113-fast v1`

Make the v1 tests compatible with Python 3.6

---

cfgov/scripts/http_smoke_test.py

The page https://www.consumerfinance.gov/about-us/advisory-groups/
no longer exists, which causes the smoke tests to fail when run with `--full` option.
To test, run this command from within a cf.gov Python environment:
```sh
$ python cfgov/scripts/http_smoke_test.py --base https://www.consumerfinance.gov --full -v
```
It will fail on master because of this page, but pass with the change proposed here.

Remove deprecated URL from smoke tests

---

cfgov/data_research/forms.py
cfgov/data_research/mortgage_utilities/s3_utils.py
cfgov/data_research/research_conference.py
cfgov/data_research/scripts/export_public_csvs.py
cfgov/data_research/tests/test_s3_utils.py
cfgov/data_research/tests/test_scripts.py
cfgov/data_research/tests/test_views.py

This PR makes it possible to run the `data_research` app's tests with Python 3.6. And, as a result, it starts nibbling around the edges of `v1`. 
1. Run `tox -e unittest-py36-dj111-wag113-fast data_research`

Make the data_research tests compatible with Python 3.6

---

.travis.yml
docs/python-unit-tests.md
tox.ini
travis_install.sh
travis_run.sh

This PR ensures that we're running all our tests that have been made to pass with Python 3.6 in Travis with every PR. As we make more tests compatible with Python 3.6, we'll add them. This is to ensure we don't backslide on any of the Python 3.6 compatibility work we've already done.

Run the Python 3.6 tests in Travis and tox by default

---

cfgov/v1/models/menu_item.py

This minor change fixes some (untested) logic in the MenuItem class that assumes that filter() returns a list, which it does in Python 2, but not in Python 3.
This change allows us to load the site in a local Django server running Python 3!
Set up a cfgov-refresh virtual environment using Python 3. Try running the local server and load the home page. It'll fail on master, but work on this branch.

Fix broken filter usage in Python 3

---

cfgov/jinja2/v1/_includes/organisms/header.html

This commit fixes a problem with the beta notification banner where the link to the real site shows up as HTML tags instead of as a proper link. This was caused by the change in #4879 that removed a `|safe` tag from the notification module.
To fix this, we just apply `|safe` directly to the string being passed to the notification.
To test, run this locally and confirm that the banner looks correct on this branch but wrong on master:
```sh
$ DEPLOY_ENVIRONMENT=beta ./runserver.sh
```

Fix beta banner by marking notification safe

---

cfgov/data_research/mortgage_utilities/s3_utils.py
cfgov/data_research/scripts/process_mortgage_data.py
cfgov/data_research/tests/test_scripts.py

As part of reviewing #4866, I tried running the process_mortgage_data script under Python 3, both to verify that it still works properly but also to educate myself on how it works. I found a couple of minor issues that I've opened this PR to address. See specific commits for more details on what was changed.
For the record, I used this command to test:
```sh
$ cfgov/manage.py runscript process_mortgage_data --script-args 2018-09-01 /tmp/mp_countydata
```
Note that you should make sure that your `AWS_STORAGE_BUCKET_NAME` environment variable is **not** pointing to the production S3 bucket when running this! One of the changes in this PR makes it possible to run this script against an alternate bucket. You'll also need to set the appropriate S3 credentials in your environment as well. …

Mortgage performance processing pipeline improvements

---

cfgov/wellbeing/jinja2/wellbeing/results.html

This commit fixes a problem with a notification module on [the Financial Wellbeing Results page](https://www.consumerfinance.gov/consumer-tools/financial-well-being/results/). When accessing the results page directly, without results, the warning message currently shows raw HTML due to a change in #4879. The message needs to be marked with `| safe`.
This is a similar fix to #4897.
To test, visit http://localhost:8000/consumer-tools/financial-well-being/results/ locally.

Fix safe HTML in wellbeing notification

---

cfgov/ask_cfpb/models/pages.py

- add `answer_id` to answer page context 
2. Navigate to [English](http://localhost:8000/ask-cfpb/what-was-the-national-mortgage-settlement-en-2071/) or [Spanish](http://localhost:8000/es/obtener-respuestas/que-es-el-acuerdo-hipotecario-nacional-es-2071/) answer page
3. View page source and verify that `data-answer-id` value is populated on `analytics-data`div
- this data is passed to analytics in a virtual pageview event

Pass answer id to Ask answer page template

---

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html
cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py
cfgov/v1/tests/test_wagtail_hooks.py
cfgov/v1/wagtail_hooks.py

This PR does two things:
- Adds a `served_by_wagtail_sharing` attribute to the `request` object when the latest Wagtail revision is being served by Wagtail-Sharing. This means all Wagtail requests on the sharing site have this attribute.
- Uses that attribute to serve draft regulation content on the Wagtail-Sharing site. 
Previously, draft content was only visible to superusers and users with edit permissions on regulation sections. This lets anyone browse draft regulation content on the sharing site like any other draft wagtail content. 
Compare http://localhost:8000/policy-compliance/rulemaking/regulations/1002/ and http://content.localhost:8000/policy-compliance/rulemaking/regulations/1002/. There should be three additional draft versions available in addition to the live version when …

Regs3k: Serve draft regulation versions on the Wagtail-Sharing site

---

cfgov/ask_cfpb/fixtures/auto_loans.json
cfgov/ask_cfpb/fixtures/bank_accounts.json
cfgov/ask_cfpb/fixtures/credit_cards.json
cfgov/ask_cfpb/fixtures/credit_reports.json
cfgov/ask_cfpb/fixtures/debt_collection.json
cfgov/ask_cfpb/fixtures/fraud_and_scams.json
cfgov/ask_cfpb/fixtures/money_transfers.json
cfgov/ask_cfpb/fixtures/mortgages.json
cfgov/ask_cfpb/fixtures/payday_loans.json
cfgov/ask_cfpb/fixtures/prepaid_cards.json
cfgov/ask_cfpb/fixtures/reverse_mortgages.json
cfgov/ask_cfpb/fixtures/student_loans.json
cfgov/ask_cfpb/scripts/migrate_tagging.py

CE identified Ask CFPB answer pages to tag with multiple portal topics,
and this brings them into the fold and marks a primary topic when needed.
- Load the latest prod db and migrate portal tags:
```bash
./cfgov/manage.py runscript migrate_tagging
```
Then edit pages to see tags applied.
Pages with multiple portal topics (and thus a primary topic designated):
- http://localhost:8000/admin/pages/6224/edit/
- http://localhost:8000/admin/pages/7798/edit/
Pages with single topics (and thus no primary): 
- http://localhost:8000/admin/pages/5928/edit/
- http://localhost:8000/admin/pages/6588/edit/
The script also has an option to run against a single Ask ID.  
To test this option, pass `--script-args` and an Ask ID:
```bash
./cfgov/manage.py runscript migrate_tagging --script-args 321
```
This …

Update portal-tag-migration to handle multiple topics

---

cfgov/jinja2/v1/ask-cfpb/category-page-spanish.html

Currently the links to Spanish answers on category pages are constructed using `slug_es` instead of `slug`, so they all go to the main `Obtener respuestas` page.
- Use `slug` instead of `slug_es` to construct Spanish answer page links
2. Navigate to a [Spanish category page](http://localhost:8000/es/obtener-respuestas/categoria-comprar-un-vehiculo/)
3. Verify that answer previews link to answer pages

Fix answer page links on Spanish Ask category template

---

refresh-data.sh

- adds the -z flag to to the curl command in refresh-data.sh, which will make it compare the timestamps of the remote and local file, and only download if the remote file is newer.
- also adds the -R flag to preserve the remote timestamp
```
-z, --time-cond <time>
(HTTP FTP) Request a file that has been modified later than the given time and date,
or one that has been modified before that time. The <date expression> can be all sorts
of date strings or if it doesn't match any internal ones, it is taken as a filename
and tries to get the modification date (mtime) from <file> instead. 
See the curl_getdate(3) man pages for date expression details.
Start the date expression with a dash (-) to make it request for a document that is
older than the given date/time, default is a document that is …
```

Only download database dump it neccessary

---

cfgov/ask_cfpb/models/pages.py
cfgov/ask_cfpb/search_indexes.py

Our refactoring of category/subcategory handling allowed redirected pages to leak into subcategory answer listings. This stops the leak and fixes some errant usages of `redirect_to` that should be `redirect_to_page`.
Answer 59 should not show up in the answer results on the 'fees' subcategory for credit cards.
To test, search for 'I was charged an overlimit fee last month' on these pages:
- The subcategory page on www: <https://www.consumerfinance.gov/ask-cfpb/category-credit-cards/fees-credit-cards/> (or on master locally).
- The same page locally, using the `stop-redirect-leak` branch: <http://localhost:8000/ask-cfpb/category-credit-cards/fees-credit-cards/>

Fix subcategory query to stop redirect leak

---

requirements/optional-public.txt

This change bumps the version of the ccdb5-ui satellite app from 1.1.0 to 1.2.0.
[This release](https://github.com/cfpb/ccdb5-ui/releases/tag/1.2.0) adds support for Python 3, and fixes a minor pagination bug.

Bump ccdb5-ui to 1.2.0

---

requirements/optional-public.txt

This includes python-3 compliance and updates countylimit data for 2019.

Update oah-api version to 0.12.1

---

cfgov/hmda/jinja2/hmda/hmda-explorer-controls.html
cfgov/hmda/jinja2/hmda/hmda-explorer-institutions.html
cfgov/hmda/jinja2/hmda/hmda-explorer-results.html
cfgov/hmda/resources/hmda_data_options.py
cfgov/hmda/tests/test_pages.py

We need subtitles under three of the HMDA data download fields. Instead of creating a custom form field type with a custom widget, it's easier to conditionally add the text in the template.
- Adds subtitles to several of the HMDA data download fields.
- Fixes the institution links to point to zips instead of CSVs.
- Adds aria labels to institution files.
- Couple language corrections.
1. Create a `Hmda historic data page` page.
1. Optionally add any content to the page.
1. Publish the page and you should see the subtitles under three of the form fields.

Add helper text to HMDA data download form fields

---

cfgov/cfgov/settings/base.py
cfgov/hmda/jinja2/hmda-outage-banner.html
cfgov/hmda/templatetags/hmda_banners.py
cfgov/hmda/tests/test_legacy_pages.py
cfgov/hmda/tests/test_outage_banner.py
cfgov/jinja2/v1/_includes/organisms/header.html
cfgov/v1/jinja2tags/__init__.py

We will be periodically taking down both HMDA's API and the HMDA Explorer page over the next few months. During outages we will redirect users to a not-yet-completed Data & Research page that will have info about our our plans to retire the HMDA API. When we automatically redirect users to this page, we'd like to add a banner at the top that mentions the outage. We're doing this with a feature flag triggered by a GET parameter called `hmda-outage`.
- `HMDA_OUTAGE` feature flag
- Banner in `header.html` that sits alongside our other optional banners.
1. Visit http://localhost:8000/data-research/?hmda-outage=True and you should see a banner at the top.
1. Visit http://localhost:8000/data-research/ and there should not be a banner at the top.
- Related to …

Add HMDA outage banner behind feature flag

---

cfgov/cfgov/urls.py

This change removes two deprecated admin URL redirects:
/tasks/foo -> /admin/cdn/foo
/d/admin/foo -> /django-admin/foo
I believe that these redirects are obsolete; /tasks went away with Picard. I don't know of anything that (still) uses /d/admin. This looks to have been a legacy way of accessing the Django admin.

Remove deprecated admin URL redirects

---

cfgov/ask_cfpb/models/pages.py
cfgov/jinja2/v1/ask-cfpb/answer-search-results.html

Search-by-tag results are used mainly for Spanish Ask pages, but they were available for English pages to capture legacy links, some of which, it turns out, were getting heavy traffic.
The English results pages were turned off in a recent migration. This restores them.
This English tag-results link (a popular one) blanks out on our site:
<https://www.consumerfinance.gov/ask-cfpb/search-by-tag/credit_score/>
It should now render locally: 
<http://localhost:8000/ask-cfpb/search-by-tag/credit_score/>
cc @kimson

Restore search-by-tag for English Ask pages

---

cfgov/v1/management/commands/invalidate_all_pages.py
cfgov/v1/tests/management/commands/test_invalidate_all_pages.py

#4905 moved the `AkamaiBackend` class and broke our `invalidate_all_pages` management command. This PR fixes that import and adds a simple test to ensure that the management command is tested.

Fix invalidate_all_pages AkamaiBackend import

---

cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py
cfgov/regulations3k/tests/test_search_indexes.py

Prior to this change, trying to access a version of a regulation that does not exist would cause a 500 error. This PR makes it raise a 404 instead.
Fixes CFGOV/cfgov-alerts/issues/3571
1. Visit http://localhost:8000/policy-compliance/rulemaking/regulations/1026/2019-10-31/17/ to see a 500
2. Check out this branch.
3. Visit http://localhost:8000/policy-compliance/rulemaking/regulations/1026/2019-10-31/17/ again to see a 404

Raise a 404 if an effective version doesn't exist, not a 500

---

cfgov/v1/models/learn_page.py

Blog pages' parent class, the AbstractFilterPage, hides a page's language
value. This may have been an oversight, but it's becoming an unfortunate choice
as we translate more site pages, including blogs, into other languages.
This PR just exposes the existing `language` field in the page admin,
allowing editors to set the proper language for a translated page.
This in turn will enable automatic translation of template labels and
other microcopy to match the chosen language.
Exposing `language` on the CONFIGURATION panel should have no immediate effects itself.
Open a blog page, such as <http://localhost:8000/admin/pages/10404/edit/>, and scroll to the bottom of the page's CONFIGURATION tab. You should be able to see and change the language value.

Expose language value on blog pages.

---

cfgov/ask_cfpb/scripts/export_ask_data.py
cfgov/ask_cfpb/tests/models/test_pages.py

This PR brings the Ask CFPB spreadsheet export up to date with the latest code.
Currently, the export still refers to some fields on the `Answer` model that are now instead reflected on the `AnswerPage` (`related_questions` and `related_resource`) or are about to be deprecated (`category`, `subcategory` and `audiences`).  Additionally, we have added new metadata fields `portal_topic` and portal_category` onto the `AnswerPage` that should be reflected in the export.  
cc @sephcoster for awareness 
- Since Spanish and English fields no longer exist side by side on the same AnswerPage, but instead each have their own page, they now are separate rows in the spreadsheet as well, as opposed to on a single row together.  I felt this looked cleaner and easier to navigate the spreadsheet, but if …

Update Ask export script with latest updates to metadata fields

---

.travis.yml
docs/migrations.md
requirements/travis.txt
tox.ini
travis_install.sh
travis_run.sh

This change modifies how the Python tests are run on Travis so that the "slow" version is run instead of the "fast" version. The "slow" version runs the full set of Django migrations.
It also modifies our Travis configuration to use [tox-travis](https://tox-travis.readthedocs.io/en/stable/), which allows us to simplify the .travis.yml a bit. This PR also removes the separate `missing-migrations` environment in favor of moving the migrations check into the standard `unittest` environment, but only having it run on Travis using Python 2.7. This is accomplished via a bit of environment variable trickery.
- When running `tox -e fast` locally, backend tests will run against Python 2 without running migrations and without checking for missing migrations.
- When running `tox` locally, backend …

Run full tox tests on Travis

---

requirements/docs.txt
requirements/libraries.txt

GitHub makes two security alerts for Jinja2 https://github.com/cfpb/cfgov-refresh/network/alerts
This patch version fixes those alerts https://github.com/pallets/jinja/blob/master/CHANGES.rst#version-2101 
- Updates `Jinja2` to `2.10.1` from `2.10`.
1. Run `./backend.sh`
2. Run `./runserver` and check that site pages load.

Update jinja2 to 2.10.1

---

cfgov/cfgov/settings/base.py
cfgov/core/middleware.py
cfgov/core/tests/test_middleware.py

We use a custom middleware (`core.middleware.ParseLinksMiddleware`) to, among other things, decorate external links with icons.
Currently this behavior is suppressed on any URLs that start with /admin/, which prevents link decoration from working on Wagtail page previews or draft links.
This change updates the middleware logic to use regular expressions as filters instead of URL prefixes. ~~It adds an inclusion list that takes priority over the exclusion list, allowing us to apply the middleware to child pages of /admin/.~~ Edit: I removed this based on feedback below.
To test, visit http://localhost:8000/login/welcome/ when logged in, and notice that link parsing (properly) does not occur. Try previewing a draft page that has an external link, and notice that link parsing (properly) does …

Update parse links URL exclusion rules

---

requirements/libraries.txt

This commit removes inclusion of the third-party [address](https://pypi.org/project/address/) Python package. In the past we required this [as part of our django-hud satellite app](https://github.com/cfpb/django-hud/blob/cd5bce3c22c122251ee171af10d6910731969f63/setup.py#L22), but we no longer do.
Additionally, this package [appears to be Python 2 only](https://github.com/SwoopSearch/pyaddress/blob/master/setup.py#L18).

Remove deprecated address package

---

cfgov/cfgov/settings/base.py

This is to allow wagtail-sharing to recognize when requests are coming in on the sharing domain, originating on port 443. See discussion on internal PR SoftwareDevelopment/dynamic_proxy/pull/131 for background.
- `USE_X_FORWARDED_PORT = True` in settings.base
1.
-
-

Allow X-Forwarded-Port

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py
cfgov/hmda/tests/test_legacy_pages.py

We needed the  `HMDA_LEGACY_REVIEW` feature flag while preparing to launch new pages at `/hmda` and `/hmda/explore`. Now that the pages are launched, we no longer need to provide the content for review at an alternate URL, so the flag is not necessary.
- The `HMDA_LEGACY_REVIEW` feature flag and all code that interacted with it.
1. Running this branch, visit `/data-research/hmda/explore`.
- It should 404 when the `HMDA_LEGACY_PUBLISH` flag is disabled.
- It should show the orange Explore page when the flag is enabled.

Remove unused feature flag

---

cfgov/v1/models/caching.py
cfgov/v1/tests/models/test_caching.py

Automatic document cache invalidation based on our `post_save` signal receiver was not invalidating the correct URL. This PR changes it to invalidate the `document.file.url` instead of `document.url` (which was the Wagtail-served URL instead of the Django-Storages URL). The tests are updated to try to simulate production conditions as best as possible.
I don't know that there is a good way to test this, since we don't have an S3 bucket dedicated to testing and we certainly don't have a Cloudfront distribution for testing. To properly test that the correct Cloudfront URLs are invalidated, we almost need to use the env vars from production, but that's inadvisable. 
Hopefully the tests populated with those env vars prove that this should work.

Fix document cache invalidation

---

cfgov/v1/models/browse_filterable_page.py
cfgov/v1/tests/models/test_browse_filterable_page.py
cfgov/v1/util/ref.py

Remove blog posts from the Newsroom page, by request from Comms.
- Remove blog posts from the list of posts included in the Newsroom
- Remove the "Blog" category from the Newsroom Filterable List control
1. Running this branch, visit http://localhost:8000/about-us/newsroom/
- There should be no posts labeled "blog" in the results
"Blog" was removed from the category list:

Remove blog posts from the Newsroom page

---

cfgov/jinja2/v1/_layouts/base.html
cfgov/v1/jinja2tags/__init__.py
cfgov/v1/templatetags/app_urls.py
cfgov/v1/tests/templatetags/test_app_urls.py

This PR moves `request.path` splitting from inside the base template to template tags. It also forces ascii-encoding on the result of the splitting to avoid issues where paths have non-ascii characters and subsequent template lookups based on those paths cause encoding errors resulting in a 500 for end-users. See discussion in the cfgov-alerts channel.

Move request.path handling from base template to template tags

---

cfgov/ask_cfpb/models/search.py
cfgov/ask_cfpb/tests/test_views.py

Adding a list of unsafe characters and a function to remove them from queries.
This satisfies internal issue #50.
I removed the "Clean" import and usage from search.py, because Clean is [included by default](https://django-haystack.readthedocs.io/en/master/inputtypes.html#clean) when passing a string to SearchQuerySet.

Make seach terms safe by disallowing unsafe characters.

---

cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py

This resolves a potential vulnerability found by Checkmarx.
- Sanitize the list of regulation IDs before processing the search request
1. Running this branch, visit http://localhost:8000/policy-compliance/rulemaking/regulations/search-regulations/results/?regs=1003
2. Enter a search term and press "search". Check different check boxes under "Regulation" and search again. The search should work as normal. (If you don't have elasticsearch running, "as normal" will still mean "no results". That's okay)
3. Try manually updating the `?regs=<regID>` part of the URL and put weird stuff in it, like symbols. The page should ignore that param and work as normal.

Validate regulation part numbers in GET request params

---

cfgov/regulations3k/models/pages.py
cfgov/regulations3k/tests/test_models.py

This PR resolves a potential vulnerability found by Checkmarx by validating the `order` parameter for interactive regulations search.

Add validator for regulations search order

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

Add redirects for Ask CFPB Category/subcategory pages
- Redirects to portal pages if they exist,
- Otherwise to the portal topic search page ("see all" topic page)
- Under a feature flag `ASK_CATEGORIES_OFF`
See GHE/CFGOV/Ask-Evo/issues/107 for more context.  Redirects will go live once this code is deployed and the feature flag `ASK_CATEGORIES_OFF` is turned on.  Category pages can be unpublished and code removed as a follow-up PR.

Add redirects for Ask CFPB Category/subcategory pages

---

cfgov/cfgov/settings/base.py

The flags removed in this PR are no longer evaluated in any code in cfgov-refresh (and I presume not in any of our satellite apps, either). Credit for the inspiration (or motivation by shame) for this PR to Caitlin Rubins excellent talk, ["Intentional Deployment: Best Practices for Feature Flag Management"](https://us.pycon.org/2019/schedule/presentation/183/) at PyCon 2019.
- A half-dozen flag definitions:
- `WAGTAIL_COMPANY_SIGNUP`
- `IA_USER_TESTING_MENU`
- `ES_CONV_FLAG`
- `MORTGAGE_PERFORMANCE_RELEASE`
- `FINANCIAL_COACHING`
- `LEGACY_HUD_API`
1. Search the cfgov-refresh codebase for references to any of the above flags
1. Find none
- Found some other flags that are still being checked but can be deprecated, but will address them in their own PRs:
- `INSET_TEST`: Requires some Less …

Clean up flags that are no longer being checked

---

cfgov/cfgov/settings/base.py

We're working to allow debug mode to be turned out when users are deploying to internal dev environments. You can see how it will be enabled at:
GHE/cfpb-infra/ansible-consumer-finance/pull/277
- if DJANGO_DEBUG is in os.environ, and set to the literal string 'True', then enable Django's debug mode.

enable DEBUG mode if environment variable DJANGO_DEBUG is 'True'

---

requirements/libraries.txt

This change upgrades our version of [wagtail-inventory](https://pypi.org/project/wagtail-inventory/) from 0.5.1 to 0.7. The later versions support more modern versions of Django (2.1, 2.2) and Wagtail (2.3, 2.4, 2.5).
This doesn't impact us as we're not on those versions yet but it's nice to keep up to date.
To test, run a local server and visit http://localhost:8000/admin/inventory/ to verify that the inventory search still works.

Update wagtail-inventory to 0.7

---

cfgov/jinja2/v1/index.html
cfgov/v1/jinja2tags/__init__.py
cfgov/v1/util/ref.py

In the "Recent Updates" section of the homepage, posts that are Events weren't getting the correct header and icon above them.
- A method, used in the index template, to check whether a "recent update" post is an event
1. Running this branch, enter the Wagtail admin and create a new `EventPage` under Events
2. Visit the http://localhost:8000.
3. The event you created should show up in the "Recent Updates" section, and it should be visually consistent with the other posts in that section, including a header that says "Events", with a calendar icon.

Add "Events" category label in Recent Updates section of homepage

---

cfgov/ask_cfpb/models/pages.py
cfgov/ask_cfpb/tests/models/test_pages.py

It's possible to manually enter a bad portal category in a portal see-all URL
and produce a server error. These URLs are normally generated by our code,
but a manually introuced typo should be caught and return a 404,
rather than cause a server error.
We already have a dictionary of category slugs available on the page,
so the fix is easy: Check any incoming category slug against the
white list before proceeding, and raise 404 if there's a mismatch.
Try this URL locally before and after loading this branch:
<http://localhost:8000/consumer-tools/debt-collection/answers/know-your-righ/>
Before: You should get a server error.
After: You should get a 404 page.

Fix bug in portal search-page routable URL handling

---

cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less
cfgov/unprocessed/apps/owning-a-home/css/form-explainer.less
cfgov/unprocessed/apps/owning-a-home/css/helpers.less
cfgov/unprocessed/apps/owning-a-home/css/hero.less
cfgov/unprocessed/apps/owning-a-home/css/tab.less

Owning a home still used some webfont mixins that are removed in https://github.com/cfpb/capital-framework/pull/907
- Remove webfont mixins in owning a home and replace with `font-weight` where needed.
1. Pull branch and run a local server.
2. http://localhost:8000/owning-a-home/closing-disclosure/ and http://localhost:8000/owning-a-home/explore-rates/ should be unchanged, other than bolding changes noted below in the screenshots.
Before:
After:

Buying-a-house: Remove webfont mixins

---

requirements/optional-public.txt

The new college-costs wheel name has `.py3` in it, our `optional-public.txt` requirements did not. This PR fixes that.
~~I'm not sure why Travis didn't fail on this in #5021.~~ I forget — Travis doesn't install our `optional-public.txt`.

Fix college-costs wheel name

---

requirements/optional-public.txt

- Bump retirement to 0.8.1
1. `./backend.sh` should pass.
2. `pip install -r ./requirements/optional-public.txt` should pass.

Bump retirement to 0.8.1

---

cfgov/ask_cfpb/models/pages.py
cfgov/ask_cfpb/tests/models/test_pages.py
cfgov/cfgov/urls.py
cfgov/jinja2/v1/_includes/organisms/_vars-mega-menu-spanish.html
cfgov/jinja2/v1/_includes/organisms/footer.html

As part of the Ask CFPB update, we are moving a number of formerly hard-coded
Spanish pages in to Wagtail.
This PR turns off the upstream URL conf that intercepted the hard-coded page URLs
before they fell through to Wagtail. We're now ready to let Wagtail take over.
This can be merged and deployed when hard-coded pages are ready to roll.
Here's our running URL list:
Current URL | Wagtail URL | Redirect
:----------- | :-------- | :---------
/es/ | /es/ | | 
/es/presentar-una-queja/ | /es/enviar-una-queja/  | √
/es/quienes-somos/ | /es/quienes-somos/ |
/es/nuestra-historia/ | NONE | √ (/es/quienes-somos/)
/es/comprar-casa/ | /es/comprar-casa/ |

Turn off upstream URLs for hard-coded Spanish pages.

---

.env_SAMPLE
README.md
cfgov/scripts/initial_data.py

This commit makes several minor changes to the initial_data Python script that lives at cfgov/scripts/initial_data.py and is runnable using
```sh
cfgov/manage.py runscript initial_data
```
or, to run Django migrations first,
```sh
./initial-data.sh
```
This work is part of a larger effort to make this initial_data script run on each cf.gov deploy, to setup environment-specific variables in our different environments.
To verify that this works as desired against an empty database, first completely delete your local database. If using Postgres, something like:
```sh
dropdb cfgov && dropuser cfpb; createuser cfpb && createdb -O cfpb cfgov
```
If using SQLite, just delete the local sqlite database file.
Next, run the initial data script:
```sh
./initial-data.sh
```
You should see the …

Minor improvements to initial_data script

---

.env_SAMPLE
.travis.yml
cfgov/scripts/initial_data.py
config/environment.js
docs/installation.md
tox.ini

This followup to #5039 makes additional minor changes to the initial_data script. We want to be able to run this against any cf.gov environment, including production, so this change makes superuser
creation optional. A superuser will only be created if the `DJANGO_ADMIN_USERNAME` and `DJANGO_ADMIN_PASSWORD` environment variables are set ([as we suggest](https://github.com/cfpb/cfgov-refresh/blob/c62699d4097ad410d95c3d251a180d819314e0c3/.env_SAMPLE#L12) in our .env_SAMPLE file).
This commit also updates the environment variable used to define the sharing hostname, from `DJANGO_STAGING_HOSTNAME` to a more descriptive `WAGTAIL_SHARING_HOSTNAME`.
Additionally, this change slightly modifies when the legacy Wagtail "hello world" page is deleted. This should only be necessary once, the single …

More minor improvements to initial_data script

---

requirements/optional-public.txt

Translations for Spanish retirement's Step 3 are failing. This restores them.

Bump retirement to 0.8.3 to fix Spanish translations.

---

cfgov/ask_cfpb/search_indexes.py
cfgov/ask_cfpb/templates/search/indexes/ask_cfpb/answerpage_text.txt
cfgov/ask_cfpb/views.py
cfgov/jinja2/v1/ask-cfpb/answer-search-results.html

Indexing broke when we moved answer content into streamfields.
This adjusts the indexing routine to extract content out of the streamfield blocks.
With a recent db load (and a running elasticsearch instance), pull in
the branch and update the elasticsearch index:
```bash
./cfgov/manage.py update_index ask_cfpb --remove
```
The index run should complete, and you should get results on local search pages: 
- <http://localhost:8000/ask-cfpb/search/?q=negotiate>
- <http://localhost:8000/es/obtener-respuestas/buscar/?q=credito+meses>

Fix indexing for Ask CFPB answers

---

cfgov/ask_cfpb/scripts/export_ask_data.py
cfgov/ask_cfpb/tests/models/test_pages.py

In https://github.com/cfpb/cfgov-refresh/pull/4982, we introduced a new StreamField `answer_content`, to replace the RichTextField `answer` on an `AnswerPage`.  In https://github.com/cfpb/cfgov-refresh/pull/5024 we did some clean-up and removed the deprecated `answer` field.  However, the changes I made to the export script in that PR introduced a bug, since I wasn't parsing the streamfield properly.  This PR fixes that.
There's not a great way to convert streamfields with many different possible blocks / fields into an easy-to-read cell in an Excel spreadsheet, so I decided to only grab the `text` block.  However, we have a few AnswerPages with FAQ and HowTo blocks that don't define `text`, so in those cases I needed to grab the `description` from those blocks.  
This might be a bit …

Fix Ask CFPB export script to work with new answer_content streamfield

---

cfgov/jinja2/v1/_includes/blocks/feedback.html

Fixes https://[GHE]/CFGOV/platform/issues/3329
- Changes feedback form heading to h3 from a form legend.
- Removes small and em tags from description paragraph.
- Fixes indenting.
1. Pull branch and visit http://localhost:8000/consumer-tools/credit-reports-and-scores/sample-letters-dispute-credit-report-information/ and compare to https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/sample-letters-dispute-credit-report-information/

Adjust feedback form appearance

---

cfgov/scripts/initial_data.py

The initial_data script doesn't need to update the default site unless its current state doesn't match the desired state. This minor change removes an unnecessary database write and logging statement from this script when it's not needed, which is most of the time.

Minor improvement to initial_data script

---

requirements/optional-public.txt

Pull in changes from https://github.com/cfpb/retirement/pull/242
- Bump retirement app from 0.8.3 to 0.9.0

Bump retirement app from 0.8.3 to 0.9.0

---

cfgov/alerts/newrelic_alerts.py

The send_new_relic_messages_to_sqs script used in our cf.gov-alerts-poll-newrelic job doesn't check to make sure that the API call to New Relic succeeds before it tries to access its JSON. We've seen quite a few job failures with unhelpful error messages ("ValueError: No JSON object could be decoded") and it would be more helpful to actually see what happens when this request fails.
This change uses the built-in [`raise_for_status()`](https://2.python-requests.org/en/master/user/quickstart/#json-response-content) method to first ensure that the response was successful.

Raise exceptions on New Relic status check failure

---

cfgov/scripts/http_smoke_test.py
cfgov/scripts/tests/test_smoke_tests.py

This pares down the SHORT_RUN list to just URLs that resolve in a brand new site database (post migrations and after running initial_data, removes a bunch of commented-out URLs, and slightly re-organizes the script itself.
This effort was only subtractive-- I did not go looking for new URLs to add.
Open question: is short list still useful at this point?
- URL's that 404 when run against a fresh site database have been removed from SHORT_RUN
- A bunch of commented-out URLs
- URL's that exist in both lists, have been removed from FULL_RUN. Running with `--full` now tests the URLs in both lists.
- Running with `--full` now tests the URLs in both lists, meaning we don't need to duplicate URLs.
`python http_smoke_test.py --base http://localhost:8000 -v` and 
`python http_smoke_test.py --base …

smoke test cleanup

---

docs/installation.md

Our live cf.gov environments connect to AWS RDS Postgres instances that are configured with a "cfpb" user and also a "cfpb" schema. The existence of this schema means that all new database tables (e.g. ones created by Django) are created in this cfpb schema.
Production database dumps thus refer to tables named "cfpb.something", and include a statement to create the "cfpb" schema. When running the local refresh-data.sh script, that loads one of these dumps, tables are created in this schema.
On the other hand, if you run the initial-data.sh script, that attempts to create tables locally without using a production dump, if you don't have a "cfpb" schema, the tables are instead created in the "public" schema. See https://www.postgresql.org/docs/10/ddl-schemas.html for documentation on why …

Recommend creation of cfpb Postgres schema

---

requirements/optional-public.txt

- Bump ccdb5-ui to 1.3.1 from 1.2.1
1. `./backend.sh` should pass.
2. `pip install -r ./requirements/optional-public.txt` should pass.
3. Icons should look relatively the same. There may be slight changes due to differences in the webfont icons and the SVG icons.

Bump ccdb5-ui to 1.3.1

---

cfgov/jinja2/v1/_includes/ask/ask-search.html

Our ask-search.html template makes a search request without a trailing slash,
which invokes Django's [APPEND_SLASH](https://docs.djangoproject.com/en/dev/ref/settings/#append-slash) default setting.
The result is a redirect for every base search request.
Adding a slash to the template stops the 301s.
- Pull in the branch locally and go to <http://localhost:8000/es/obtener-respuestas/> 
- Open dev tools to the network panel, then enter a search term on the page (such as `credito`) and enter.
The network panel should show a 200 response, not 301 as happens currently on the live page.
- The search URL in the template is translated for Spanish pages, but we don't need to touch the django.po file because there was already a translation for the search URL that included the slash.
- Thanks to …

Stop redirects for Ask search

---

requirements/optional-public.txt

Bumps the version of the college-costs satellite app from 2.7.2 to the latest release [2.7.3](https://github.com/cfpb/college-costs/releases/tag/2.7.3).

Bump college-costs from 2.7.2 to 2.7.3

---

requirements/optional-public.txt

This followup to #5075 should fix a collectstatic issue with college-costs.

Bump college-costs from 2.7.3 to 2.7.4

---

requirements/optional-public.txt

This change bumps the retirement satellite app to the newest release [0.10.0](https://github.com/cfpb/retirement/releases/tag/0.10.0).
This adds Python 3 support to this package. 🍰 🍟 
To test, visit http://localhost:8000/consumer-tools/retirement/before-you-claim/ locally.

Bump retirement from 0.9.0 to 0.10.0

---

cfgov/agreements/jinja2/agreements/index.html

The new agreements were just provided by RMR and uploaded to S3.
When this change is deployed, we should also run the script to load the new data.
- Link to latest set of quarterly Credit Card Agreements data
- When this change is deployed, I will run the `cf.gov-load-agreements-data` job to load the latest agreements into the finder.

Add link to credit card agreements for Q4 2018

---

requirements/optional-public.txt

This change will update the ccdb5-api package to version 1.1.9, which brings Python 3.6 support with it.

Update ccdb5-api to 1.1.9 for Python 3 support

---

requirements/optional-public.txt

Uses new universal wheel for Python 2/3 support.
Visit http://localhost:8000/paying-for-college/compare-financial-aid-and-college-cost/. For search to work you'll have to populate your local search index using the instructions [here](https://github.com/cfpb/django-college-costs-comparison#installation).

Update comparisontool from 1.11.2 to 1.12.0

---

requirements/libraries.txt

The [TDP satellite app](https://github.com/cfpb/teachers-digital-platform/) includes pinned package dependencies for `django-mptt==0.9.0` and `django-js-asset==1.1.0`. Currently cfgov-refresh only includes the pinned dependency on django-mptt.
The django-mptt dependency includes [an unpinned dependency](https://github.com/django-mptt/django-mptt/blob/615cd547625bef2ce86c46d7e071787f194ac924/setup.py#L20) on django-js-asset. There have been [several releases](https://pypi.org/project/django-js-asset/#history) of django-js-asset since the 1.1.0 version. This means that, depending on how the cfgov-refresh and TDP dependencies are installed, you might end up with a later version of django-js-asset, that doesn't match what is specified in TDP.
For this reason, this PR fixes the django-js-asset …

Pin django-js-asset package to match TDP

---

cfgov/unprocessed/css/video-player.less

When a video is playing there is an invisible image on the page that overlays content. This prevents any links in that content from being clickable.
- Add `pointer-events: none;` to hidden image's container.
1. `gulp build` should pass. I'm not sure how to test this without a livestream happening.

Video player: Prevent cursor interaction on a hidden image

---

cfgov/unprocessed/css/video-player.less

For some reason we were only adjusting video iframe's height and video controls position on larger screens. They are now adjusted on all screen sizes.
I have tested these changes on a handful of FCM and non-FCM videos and it seems okay but I could use more eyes if anyone's able.
- http://0.0.0.0:8000/consumer-tools/managing-someone-elses-money/
- http://0.0.0.0:8000/about-us/blog/mortgage-closing-scams-how-protect-yourself-and-your-closing-funds/
- https://[mattermost]/cfpb/pl/841dszdrrtfx5dpamz7tq7j89h
**Before:**
**After:**

Expand our videos' iframe container on all screen sizes

---

cfgov/core/static/BingSiteAuth.xml
cfgov/core/static/lln8595c61g9qnvuwvtlcwo1k6kem8.html

This commit adds two domain verification files used by FB and Bing to confirm our ownership of this website. We already serve these files on cf.gov, but currently they come from another internal repository.
To verify, visit these URLs with a local server:
http://localhost:8000/static/BingSiteAuth.xml
http://localhost:8000/static/lln8595c61g9qnvuwvtlcwo1k6kem8.html
Our Apache configuration already contains Alias directives that will make these work at the site root:
https://www.consumerfinance.gov/BingSiteAuth.xml
https://www.consumerfinance.gov/lln8595c61g9qnvuwvtlcwo1k6kem8.html
This follows the existing pattern of similar site-root files robots.txt and favicon.ico, which also live in cfgov/core/static.

Add domain verification files for FB and Bing

---

requirements/libraries.txt

Wagtail-Flags 4.1.0b1 did not include CSS files in the package. This caused errors with ManifestStaticFilesStorage when trying to access the Wagtail admin. This PR bumps Wagtail-Flags to 4.1.0b2 to fix this.

Bump wagtail-flags to 4.1.0b2

---

requirements/libraries.txt

This change reverts to previous versions of Django-Flags and Wagtail-Flags to mitigate a potential issue with boolean conditions.

Revert Django-Flags and Wagtail-Flags updates

---

requirements/libraries.txt

Now that Django-Flags 4.1.2 is released and fixes the critical bug that broke our database flags, this change restores the latest versions.
This reverts the reversion in #5100.

Restore new versions of Django and Wagtail Flags

---

requirements/optional-public.txt

This PR bumps the version of the optional ccdb5-api package from 1.1.9 to the new [1.1.10](https://github.com/cfpb/ccdb5-api/releases/tag/1.1.10) release. This release makes only minor changes including one required to fix a failing test to support #5083.

Bump ccdb5-api from version 1.1.9 to 1.1.10

---

cfgov/paying_for_college/admin.py

When college-costs was ported to cfgov-refresh, I neglected to include the admin file so that product owners could edit some of the constant values we use on the page.
This restores the admin file.

restore the admin access to PFC constants

---

cfgov/jinja2/v1/_includes/macros/video-player.html
cfgov/unprocessed/css/pages/ask.less
cfgov/unprocessed/css/video-player.less
cfgov/unprocessed/js/modules/VideoPlayer.js
cfgov/unprocessed/js/modules/YoutubePlayer.js
cfgov/unprocessed/js/routes/on-demand/video-player.js
test/browser_tests/shared_objects/video-player.js

- Video player: Adds `@standard-btn-height__px` variable for "standard" button height magic number.
-  Video player: Removes seemingly unused `@share-width__px` and `@video-width__px` variables.
-  Video player: updates class name to have `o-` prefix for consistency with how other organism's CSS is formatted.
- Adds space in parentheses and removes some extraneous whitespace. Minor comment updates too (missing period, spelling out FCM acronym).
1. `gulp clean && gulp build` should pass. Videos should work as before.

Video player styles cleanup

---

cfgov/jinja2/v1/job-description-page/index.html

The download icon for the pay scale PDF is currently misplaced.
- Corrects the placement of the pay scale PDF's download icon
1. Pull branch
1. Ensure you have a recent database dump
1. Load up a current opening, like http://localhost:8000/about-us/careers/current-openings/chief-experience-officer-175-176p/
1. Observe that the icon is now on the right

Fix placement of the download icon for a job's pay scale PDF

---

docker/drama-free-django/travis.sh

The drama-free-django build using a Docker container that runs in Travis (introduced recently in #5110) seems to fail strangely sometimes, e.g.
https://travis-ci.org/cfpb/cfgov-refresh/jobs/560138901#L1314
This works locally. I suspect this is some kind of timeout, but am not sure. This change modifies the way that the Travis script works, so that it runs the container in detached mode and then attaches to the logs. I've verified that this works (at least once) on my fork.
This change is intended to fix the Travis failures currently happening on #5116.

Run Docker DFD build in Travis in detached mode

---

docker/drama-free-django/_build.sh
docker/drama-free-django/_test.sh
docker/drama-free-django/travis.sh

This commit moves the Docker-based drama-free-django build on Travis out of detached mode, but tries to set `PYTHONUNBUFFERED` to hopefully allow the logs to be properly reported.
It also adds `set -x` to the scripts so that the commands are helpfully echoed for better debugging.
This is a followup to #5110 and #5117. See conversation starting [here](https://github.com/cfpb/cfgov-refresh/pull/5117#pullrequestreview-263302819) for motivation behind this change. Hopefully this should provide better debugging for any future DFD build failures on Travis.
I tested this on a fork and it passed Travis [here](https://travis-ci.org/chosak/cfgov-refresh/jobs/560182676#L7815); this doesn't guarantee this will never fail, because the original #5110 passed and I'm not sure why Travis was failing on …

Improve logging of drama-free-django builds

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/tests/test_urls.py
cfgov/cfgov/urls.py

This flag will allow us to set up automatic refreshes of the Beta database, like so:
1. Someone on M&R manually enables the `BETA_EXTERNAL_TESTING` feature flag when Beta is being used for a test.
2. The flag controls the `/beta_external_testing` endpoint on cf.gov, which returns a 200 when enabled and a 404 when disabled.
3. The Beta refresh Jenkins job checks the endpoint whenever it runs. If the endpoint returns 404, refresh Beta. If 200, Beta is in use, so don't refresh.
This way, the Jenkins job can run automatically on a schedule (e.g. daily), and not overwrite the testing environment when it's in use.
- `BETA_EXTERNAL_TESTING` feature flag
- `/beta_external_testing` endpoint
2. From a terminal, `curl -I localhost:8000/beta_external_testing/`
- Should return HTTP …

Add flag and endpoint to signal when Beta is in use for testing

---

cfgov/jinja2/v1/_includes/molecules/global-search.html

Partial fix for  https://GHE/CFGOV/platform/issues/2655
-
-
- There is a label on mobile that when clicked on, clears any typed text inside the search field. This label currently says "Close" which is not that it does. This PR makes it say "Clear search" instead. This is helpful for screen reader users, who will hear the text read out loud.
1. Resize your browser window to mobile layout size
1. tab to the search field 
1. You can't actually tab to the "Clear search" button right now (that's another PR coming) but you can right click, inspect the text to make sure the label says "Clear search" inside it.
-
-

Make clear search label say "clear search" instead of "close"

---

cfgov/v1/atomic_elements/organisms.py
cfgov/v1/tests/atomic_elements/organisms/test_related_posts.py

The PR fixes a bug where events show up as related posts, they would show up with the published date instead of the event start date, despite template logic that looked for the state date of events. 
So, a listing of related events on the site right now (on this page for example: https://www.consumerfinance.gov/about-us/events/archive-past-events/town-hall-baton-rouge-la-preventing-elder-financial-exploitation/) looks like this:
These are published dates. After this change this same listing looks like:
This change adds a call to Wagtail's `specific` property on each returned page in the `RelatedPosts` organism that will fetch the actual model class and fields for the page.

Ensure that related_posts returns specific pages

---

cfgov/jinja2/v1/_layouts/base.html
cfgov/jinja2/v1/_layouts/content-base-sidebar-first.html

Skip links are currently all skipping to `#main`. On pages with left side nav, this means that they weren't skipping over that nav. This change skips them to `#content_main` on pages with a left sidebar.
Fixes GHE/CFGOV/platform/issues/2704
- Added `id="content_main"` to the `div` with the class of the same
- Added a new template block of `skip_nav_target` wrapping the `href` value in the skip link in `base.html`, which is overridden in the `content-base-sidebar-first.html` template to point to `#content_main`
1. Pull branch
1. Visit a page with left side nav, e.g., http://localhost:8000/about-us/newsroom/
1. Press Tab to reveal the skip link and Enter to activate it
1. Confirm that it targets `#content_main` instead of `#main`
1. Try it on any other type of page and see that it still …

Skip over left side nav when using skip link on pages with left side nav

---

cfgov/jinja2/v1/_layouts/base-common.html

Closes GHE/2877
- Open your local instance of cfgov to the homepage and view the html element. It should have a `lang` attribute set to `en`.
- Navigate to `localhost:8000/es` and view the html element. It should have a `lang` attribute set to `es`.

Set the html lang attribute based on the language variable

---

cfgov/core/tests/test_middleware.py
cfgov/core/utils.py

This change refactors the way `<img>` tags were being matched in links to prevent icons being added for external links. Instead of matching an `img` tag name in a `for` loop, it uses BeautifulSoup's CSS `select()` method. 
(As a personal aside, I'm much happier with this as a way to filter the links.)
This change also adds additional elements that can be contained within a link that do not get icons. That list is currently, `img`, `svg`, `div`, `h1`, `h2`, `h3`, `h4`, `h5`, and `h6`.
This is intended to fix this issue on production:
https://www.consumerfinance.gov/equifax-settlement/
On localhost, without the image file itself, this looks like:
http://localhost:8000/equifax-settlement/
With this change:
http://localhost:8000/equifax-settlement/

Expand tags inside a link that don't get an icon

---

requirements/libraries.txt

This should fix the failing sections on the retirement app.

Bump retirement to 0.10.1 for hotfix

---

cfgov/cfgov/settings/base.py
cfgov/jinja2/v1/_includes/organisms/footer.html

Addresses https://GHE/CFGOV/platform/issues/3505
- Adds Information Quality Guidelines link to global footer
- Removes `WHISTLEBLOWER_RELEASE` flag that is no longer needed
1. Pull branch
1. Visit http://localhost:8000/
1. See the new link and click through to the page

Add Information Quality Guidelines link to global footer

---

cfgov/paying_for_college/admin.py

The paying_for_college settlement disclosure tool had only two school systems
since launching in 2017, so contacts needed minimal management.
Now that original school system, EDMC, has broken apart, through a sale and
then a receivership, surviving schools are breaking away as
independent entities, requiring new contact entries.
This admin tweak makes it easier to see details of the school contacts in our system.

Add admin class for PFC contacts

---

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html

Fix a typo and missing margin in the iRegs notification
- Fixed the typo: "ammendments" is now "amendments"
1. Go to any previous or future version of any regulation, like the previous version of Reg C at http://localhost:8000/policy-compliance/rulemaking/regulations/1003/2018-01-01/
2. Make sure "amendments" is spelled correctly in the notification box and that the notification box is separated from the view links by 30px
3. Hit "view this version" to go to the first page of the regulation
4. Make sure "amendments" is spelled correctly in the notification box (the box was already separated from the content by the correct amount, so no need to test that)
Current | Fixed
---- | ----

Fix iRegs notification typo

---

cfgov/regulations3k/jinja2/regulations3k/search-regulations-results.html
cfgov/regulations3k/jinja2/regulations3k/search-regulations.html

This change removes all remaining references to `letter_code` in the Regulations 3000 search templates. Both instances were mistakenly left in place.

Remove remaining references to letter_code

---

cfgov/scripts/static_asset_smoke_test.py

We've recently added referer checking to some of our static assets (fonts). This caused the static asset smoke test to throw warnings like:
`
Light FAIL!2 static links failed for https://www.consumerfinance.gov: [(u'/static/fonts/2cd55546-ec00-4af9-aeca-4a3cd186
da53.457e94a5b665.woff2', 403), (u'/static/fonts/627fbb5a-3bae-4cd9-b617-2f923e29d55e.24932ad03d18.woff2', 403)] 
`
This small tweak makes it so that the 'referer' header is set to an appropriate value when static assets are fetched/
- we send a referer header when requesting static assets.
1. `python cfgov/scripts/static_asset_smoke_test.py --base https://beta.consumerfinance.gov -v`
1. `python cfgov/scripts/static_asset_smoke_test.py -v`
(not the lack of "light failures"
-
-

(smoke tests) set the referer header when requesting static assets

---

cfgov/unprocessed/apps/owning-a-home/js/explore-rates/Slider.js
cfgov/unprocessed/js/molecules/Autocomplete.js
cfgov/unprocessed/js/molecules/GlobalSearch.js
cfgov/unprocessed/js/molecules/Multiselect.js
cfgov/unprocessed/js/molecules/Notification.js
cfgov/unprocessed/js/organisms/EmailPopup.js
cfgov/unprocessed/js/organisms/FilterableList.js
cfgov/unprocessed/js/organisms/Footer.js
cfgov/unprocessed/js/organisms/FormSubmit.js
cfgov/unprocessed/js/organisms/Header.js
gulpfile.js
test/unit_tests/apps/owning-a-home/js/explore-rates/Slider-spec.js
test/unit_tests/js/molecules/Multiselect-spec.js
test/unit_tests/js/molecules/Notification-spec.js
test/unit_tests/js/organisms/EmailPopup-spec.js
test/unit_tests/js/organisms/Footer-spec.js
test/unit_tests/js/organisms/FormSubmit-spec.js

The  atomic component `init()` method would return `undefined` if it was called a second time. This allows checking in tests whether `init` has been run already. However, I'm thinking it's better to have a [consistent return](https://eslint.org/docs/rules/consistent-return), and if we wanted to verify that `init` has already been called, check whether the attribute `data-js-hook="state_atomic_init"` is set. This was originally set up so logic could check whether initialization was already called, but we don't do that anywhere and could add a `isInitialized()` method if that was needed.
- Make `init()` method of atomic components return the component instances on all calls to the method.
1. `gulp test:unit` should pass.
2. `gulp clean && gulp build` should pass.

Change init method to return consistent type

---

cfgov/cfgov/settings/base.py

Closes GHE/CFGOV/ship-it-better/issues/173
Currently wagtail image upload preview is broken due to the image being injected as a `blob:` url. This change allows images to be injected as blobs, which doesn't create any additional risk (blobs have to be created at the same-origin where they are accessed, meaning if someone is running arbitrary code to generate a blob: url for an image, they already have script access!)

Allow blob images via csp

---

cfgov/apache/conf.d/wsgi.conf

Currently drama-free-django [sets up two virtual environments](https://github.com/cfpb/drama-free-django/blob/113003e842ab93059b8f15de2828d24051f7e009/no_drama/build_skel/activate.sh#L13) for each deploy. One contains project requirements, and one is empty. To simplify a bit, this commit stops using the empty virtualenv, because we don't need the protection that it is intended to provide.
See mod_wsgi documentation [here](https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html).
The empty virtual environment is only needed and recommended "when activating the Python virtual environment from within the WSGI script file". We don't do that. Because we don't have multiple WSGI apps being run within the same daemon process group, we can use a single virtual environment. …

Stop using drama-free-django empty virtual environment

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/settings/production.py
docker/drama-free-django/_build.sh

We want to instead set the Django static root through a simple environment variable read into cfgov-refresh settings.
This PR depends on some other internal PRs, including https://github.com/cfpb/drama-free-django/pull/26.
In the local/test settings, [we use an alternate local path for `STATIC_ROOT`](https://github.com/cfpb/cfgov-refresh/blob/ef52570d709dbb831a607e7ab2a77619438ceb1c/cfgov/cfgov/settings/local.py#L15). This change makes the production setting more explicit.

Stop using drama-free-django to set static root

---

gulp/config.js

This change will cause `gulp scripts` to add all files matching `cfgov/unprocessed/apps/**/js/*.js`to its `otherBuildTriggerFiles` setting. This will have the effect of causing all files in an app folder to be rebuilt when one file in that app's `/js/` directory, and thus the final compiled JavaScript files for that ap will have all changes to imported files correctly rebuilt.
- Add unprocessed/apps to the gulp config file in the scripts section, under 'otherBuildTriggerFiles'
1. Work on a JS file in one of the `/unprocessed/apps/` JavaScript directories
2. Run `gulp scripts`
3. Check to see if your changes were properly rebuilt

Add unprocessed/apps to gulp config trigger files

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/settings/local.py
docker/drama-free-django/_build.sh

This project currently includes a static.in subdirectory for specifying additional staticfiles directories for Django besides those explicitly listed in settings. This is currently used only when using settings.local.
In production, this same directory is configured via some behavior in drama-free-django. To reduce dependence on drama-free-django, this commit instead modifies settings.base so that static.in is always included, both in local and production settings.
This change depends on https://github.com/cfpb/drama-free-django/pull/27 which allows DFD to be used while skipping its static.in behavior.
This change can best be tested using a version of drama-free-django with the changes in https://github.com/cfpb/drama-free-django/pull/27 merged in, either by waiting until that PR is …

Stop using drama-free-django to use static.in

---

docker/drama-free-django/Dockerfile
docker/drama-free-django/build.sh
docker/drama-free-django/test.sh

This addresses the problem andy described in https://github.com/cfpb/cfgov-refresh/pull/5173, but with a **COOL HACK** that allows us to use most of the cache while always getting fresh code from drama-free-django.
Follow the instructions [here](https://github.com/cfpb/cfgov-refresh/tree/master/docker/drama-free-django) two times in a row. You'll note that for at least the second attempt, the first 9 steps should use the cache, but no others (depending on if you've run these commands before the first 8 images will likely be cached on your first run as well).

Don't cache the dfd install in the dfd docker build

---

.dockerignore
Dockerfile
cfgov/cfgov/settings/minimal_collectstatic.py

This adds an additional stage to the Dockerfile that installs Node 10, yarn, runs the front-end build, and runs collectstatic in production mode (putting the resulting files in /var/www/html/static )
This will not change life for docker-compose users, since the python containers are [pinned to to the cfgov-dev stage](https://github.com/cfpb/cfgov-refresh/blob/docker-multistage/docker-compose.yml#L25)
- cfgov-build docker stage
`docker build . --build-arg scl_python_version=rh-python36 --target cfgov-build -t tmp && docker run -it tmp:latest bash` should run the whole build, and drop you in a shell session where you can inspect the results. You can see the built (and post-processed) static files in /var/www/html/static
-
-

new docker stage that builds and collects frontend assets

---

cfgov/jinja2/v1/_includes/organisms/bureau-structure.html

Opening on behalf of @niqjohnson.
The Bureau wishes to restore the PDF download capability for our org chart, now that it has stabilized for a while.
- Replaces placeholder statement with a new download button.
1. Pull branch
1. View http://localhost:8000/about-us/the-bureau/bureau-structure/ and verify that the download button shows. If it does not, you may need to either get a fresh database dump, or just choose a file in the "Download image" field on http://localhost:8000/admin/pages/4611/edit/
- It might be nice to make the `download_image` field optional, and output a similar "Currently under revision" message if it's not present. That would prevent needing PRs like this or the one that came before if we have a similar situation in the future.

Restore org chart download

---

cfgov/jinja2/v1/_includes/organisms/bureau-structure.html
cfgov/unprocessed/css/organisms/bureau-structure.less

One of the changes to the org chart requires a new note to be added to the legend. This does that.
- Adds `**** Position has direct reporting responsibilities to the Policy Associate Director for External Affairs` to the Bureau Structure legend.
1. Pull branch
1. Visit http://localhost:8000/about-us/the-bureau/bureau-structure/ and scroll down to the legend
- It'd be nice if these could be editable in Wagtail someday.
- Four asterisks is getting a little ridiculous. Should consider switching to alternate symbols or superscript numbers, perhaps.

Add fourth note to Bureau Structure chart legend

---

cfgov/cfgov/urls.py

The YES page introduced in #5176 introduces a Django warning due to a leading slash in the URL pattern. Using a leading slash in URL patterns is unnecessary and generates this Django warning:
```
WARNINGS:
?: (urls.W002) Your URL pattern '/resources-youth-employment-programs/transportation-tool/$' [name='youth_employment_success'] has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
```
(You can see this warning in the Travis run [here](https://travis-ci.org/cfpb/cfgov-refresh/jobs/575079458).)
Running locally against this branch, confirm that you can still visit the YES page successfully: http://localhost:8000/resources-youth-employment-programs/transportation-tool/.

Remove leading slash from YES URL

---

cfgov/cfgov/settings/base.py
cfgov/cfgov/urls.py

The new YES page added in #5176 is not yet ready for production release and thus should be guarded behind a feature flag.
This change adds a new feature flag named `YOUTH_EMPLOYMENT_SUCCESS`, which protects this page. By default this is disabled everywhere, unless enabled via the Wagtail admin.
This change also moves the existing URL pattern down in urls.py to be located near other educational pages.
1. Run locally and notice that [the new page](http://localhost:8000/resources-youth-employment-programs/transportation-tool/) returns a 404.
2. Go into the [Wagtail flags](http://localhost:8000/admin/flags/) area, and edit the new flag for [`YOUTH_EMPLOYMENT_SUCCESS`](YOUTH_EMPLOYMENT_SUCCESS).
3. Click "Enable YOUTH_EMPLOYMENT_SUCCESS for all requests".
4. You should now be able to access …

Put Youth Employment Success page behind flag

---

cfgov/cfgov/urls.py
cfgov/unprocessed/apps/youth-employment-success/js/reducers/budget-reducer.js
cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
cfgov/unprocessed/apps/youth-employment-success/js/util.js
test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
test/unit_tests/apps/youth-employment-success/js/util-spec.js

- Specs for `routeOptionReducer`
- Specs for `actionCreator` utility function
N/A
- Adds proper path to YES url
1. If the YES flag is enabled, the following URL should serve the in progress transportation tool page:  `practitioner-resources/resources-youth-employment-programs/transportation-tool/`
N/A
N/A
N/A

Adds reducer and specs for routeOptionReducer

---

cfgov/cfgov/wsgi.py

Our wsgi.py file points to a New Relic config file using a relative path, based on our knowledge of where these two files are related to each other in the file tree.
Using the new deployable zipfile functionality recently introduced in #5179, we put a symlink from a wsgi.py file in the root of the deploy directory pointing to the real wsgi.py. This means that when wsgi.py is accessed, its `__file__` may be a symlink. This causes the relative location of the New Relic configuration file to be wrong, which can prevent the website from working right when NR is enabled.
This change modifies an [`os.path.abspath`](https://docs.python.org/2/library/os.path.html#os.path.abspath) call to change it to an [`os.path.realpath`](https://docs.python.org/2/library/os.path.html#os.path.realpath) call, …

Help symlinked wsgi.py find New Relic config file

---

cfgov/apache/conf.d/wsgi.conf
cfgov/apache/conf.modules.d/00-base.conf

Currently the Apache configuration is hardcoded to use the Python 2.7 version of mod_wsgi. We want to optionally support running with the Python 3.6 version instead.
Currently we install mod_wsgi using the python27-mod_wsgi package, which installs a `mod_python27-wsgi.so` module. If we also install the rh-python36-mod_wsgi package, it installs the Python 3.6-compatible version alongside, named `mod_rh-python36-wsgi.so`.
In order to toggle between these two, this change relies on the presence of a `PYTHON_VERSION` environment variable that needs to be passed to Apache. See internal Ansible repo PR 321 that adds this variable. This PR is blocked until that one is merged.

Add support for running Apache with Python 3.6

---

cfgov/jinja2/v1/_includes/molecules/related-posts.html
cfgov/v1/tests/atomic_elements/organisms/test_related_posts.py

This change changes a use of [`iteritems()` to `items()`](https://python-future.org/compatible_idioms.html#iterating-through-dict-keys-values-items) to make the related posts template compatible with both Python 2 and Python 3. 
Currently the related posts module doesn't work in Python 3 because of this. I've added a test case to cover this behavior.
In Python 2, going from `iteritems()` (an iterator) to `items()` (a list) could in theory be slightly slower, but in practice the related posts module only has a maximum of 9 items, so this shouldn't have a big impact on performance.
See new unit test. Also visit [any page](http://localhost:8000/about-us/blog/protect-yourself-credit-card-fraud-register/) locally that has a related posts module in the sidebar.

Fix Python 3-incompatible code in Related Posts

---

cfgov/deployable_zipfile/extract.py
cfgov/deployable_zipfile/tests/test_extract.py

The old drama-free-django-based deploys would always extract the release zip into a "current" subdirectory on the target server.
For example, if a deploy zipfile were extracted by running:
```
/tmp/cfgov.zip -d /srv/cfgov/versions/20190828171038
```
then the zipfile contents would be extracted under a `/srv/cfgov/versions/20190828171038/current` subdirectory, not under `/srv/cfgov/versions/20190828171038` as one might expect. This would mean, for example, that the virtualenv was at `/srv/cfgov/versions/20190828171038/current/venv`, etc.
To simplify the zipfile code, and its deployment, this change stops extracting to a "current" subdirectory.
This PR is **held** until our Ansible code is modified to support it; see internal Ansible PR 323.
To test this independently, the best way is to …

Stop use of "current" subdirectory in deploy zipfiles

---

cfgov/jinja2/v1/youth_employment_success/index.html
cfgov/unprocessed/apps/youth-employment-success/js/index.js
cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
cfgov/unprocessed/apps/youth-employment-success/js/route.js
cfgov/unprocessed/apps/youth-employment-success/js/store.js
test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
test/unit_tests/apps/youth-employment-success/js/route-spec.js

This pull request add support for multiple routes in the route option reducer. Each `routeOptionView` gets passed the index of the route it is responsible for.
- Add a route factory function to build new route data objects
-
- Since the tool will only allow for two routes for now, explicitly initialize
each view and expandable in `index.js`
- Update reducer to handle multiple route objects
1. Just unit tests at this point
- I don't love all the manual selecting of `expandables` and `views` in the `index.js` file, but we only need two route options for the tool and this is the simplest way to ensure that all the data goes to the right places and all the JS objects get initialized correctly
-

Add multiple route options to reducer

---

cfgov/jinja2/v1/youth_employment_success/index.html
cfgov/jinja2/v1/youth_employment_success/route-option.html
cfgov/unprocessed/apps/youth-employment-success/js/index.js
cfgov/unprocessed/apps/youth-employment-success/js/route-option-toggle-view.js
cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
test/unit_tests/apps/youth-employment-success/js/route-option-toggle-view-spec.js
test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js

So the user can compare two routes and find the most cost-effective one, add a button that shows the second route form.
- Button to handle toggling the second route
- JS view to manage button and expandable
- Expandable route options no longer function like an accordion, the user may have both open at once if they want
-
1.
- ~Depends on #5196~ 
- The toggle view being responsible for an expandable and a form is a little backwards.
Ideally, I'll refactor this to follow a structure similar to the below code block. Sorry for using `JSX` syntax, but I think it is a genuinely helpful way to expose the hierarchical relationships between JS views of DOM elements
```
<TransportationView>
<ExpandableView> -> this wraps the exposed expandable api
<RouteOptionFormView />
</ExpandableView> …
```

JS view to manage showing second route option

---

cfgov/jinja2/v1/_includes/atoms/checkbox.html
cfgov/jinja2/v1/_includes/atoms/radio-button.html
cfgov/jinja2/v1/youth_employment_success/budget-form.html
cfgov/jinja2/v1/youth_employment_success/route-option-form.html
cfgov/jinja2/v1/youth_employment_success/route-questions/average-daily-cost.html
cfgov/jinja2/v1/youth_employment_success/route-questions/average-total-cost.html
cfgov/jinja2/v1/youth_employment_success/route-questions/days-per-week.html
cfgov/jinja2/v1/youth_employment_success/route-questions/miles.html
cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html
cfgov/unprocessed/apps/youth-employment-success/js/index.js
cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js

To facilitate a no-js compatible experience, we are disabling all input elements on page load. The inputs will be enabled if a supported level of JS is detected. 
-
-
- Disable all form fields by default
- Add the `disabled` property to `checkbox.html` and `radio.html`
1.
- This will be used in conjunction will a button and message encouraging users to print the page
-

YES tool — Disable all inputs by default

---

cfgov/unprocessed/apps/youth-employment-success/js/reducers/goal-reducer.js
test/unit_tests/apps/youth-employment-success/js/reducers/goal-reducer-spec.js

Adds reducer for handling goals data.
- `goalReducer` function
-
-
1. Just unit tests here
-
-

YES tool - Adds reducer for goals

---

cfgov/jinja2/v1/youth_employment_success/route-questions/average-total-cost.html
cfgov/jinja2/v1/youth_employment_success/route-questions/input.html
cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html
cfgov/unprocessed/apps/youth-employment-success/css/main.less
cfgov/unprocessed/apps/youth-employment-success/js/input-view.js
cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
cfgov/unprocessed/apps/youth-employment-success/js/route-option-toggle-view.js
cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
cfgov/unprocessed/apps/youth-employment-success/js/route.js
cfgov/unprocessed/apps/youth-employment-success/js/views/transit-time.js
test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
test/unit_tests/apps/youth-employment-success/js/views/transit-time-spec.js

This PR adds a new view to handle a group of input elements, in this case two text inputs and a checkbox.
- View to control inputs related to transit times
- Additional properties to route and route reducer
-
- Fixes bug where input atom adds an extra set of "" to data-js attributes
- Adds override for `u-hidden` class
1.
-
-

YES tool — Adds new combo field view for transit time

---

cfgov/unprocessed/apps/youth-employment-success/js/input-view.js
cfgov/unprocessed/apps/youth-employment-success/js/util.js
test/unit_tests/apps/youth-employment-success/js/util-spec.js

Centralizes the several instances of duplicated functionality into a single `entries` function. This allows the codebase to continue supporting IE 11 
- Adds `entries` utility function
- Removes duplicated `entries` behavior from views / `combineReducers`
-
1. Just unit tests here
-
-

YES tool — Add entries helper function

---

cfgov/housing_counselor/management/commands/hud_generate_json.py
cfgov/housing_counselor/results_archiver.py
cfgov/housing_counselor/tests/management/test_results_archiver.py
docs/housing-counselor-tool.md

The Office of Innovation needs the Bureau to retain a copy of each day's list of HUD-approved housing counselors.
- Add a step to the `hud_generate_json` management command that takes the full set of results and saves them to a .zip file.
- Add a test for this functionality
- Update public documentation of the Housing Counselor data processing
1. `cfgov/manage.py hud_generate_json jsons --archive-file-name ./test-archive.zip`

Save a full list of housing counselor results

---

README.md
cfgov/apache/conf.d/user-testing.conf
cfgov/hmda/templates/hmda/orange-explorer.html
cfgov/jinja2/v1/rural-or-underserved/index.html
cfgov/legacy/templates/front/base_nonresponsive.html
cfgov/paying_for_college/disclosures/scripts/load_programs.py
cfgov/paying_for_college/static/paying_for_college/feedback/css/comparison-tool.css
cfgov/paying_for_college/templates/paying_for_college/disclosure.html
cfgov/paying_for_college/templates/paying_for_college/disclosure_technote.html
cfgov/unprocessed/root/data.json
test/unit_tests/js/organisms/MegaMenu-spec.js

Change http to https for www.consumerfinance.gov links
From the June crawl report, there were still a number of internal CF.gov links that point to http instead of https).
PDFs on the Consumer Advisory Board page pointed to http instead of https.

Make sure pages point to HTTPS instead of HTTP

---

cfgov/jinja2/v1/rural-or-underserved/index.html
cfgov/unprocessed/apps/rural-or-underserved-tool/js/common.js

- Uses the `table` tag rather than the `.table` class for the download selector. Looks like this was changed in the move to wagtail.
1. Pull branch, build.
2. Enter an address, hit "Check addresses"
3. Click "Download results"
The resulting file should be populated with data. Following these steps on cf.gov will result in a file with only headers.

Fix download on rural or underserved tool

---

cfgov/unprocessed/apps/youth-employment-success/js/validators/route-option.js
test/unit_tests/apps/youth-employment-success/js/validators/route-option-spec.js

Previously, the warning alert dialog in the route option detail pane was disappearing when the form hadn't validated. This PR fixes a bug in the logic that treated invalid data as valid.
-
-
- Uses a `for` loop to return early once a field fails validation
1. In the browser, fill in the following form fields:
* monthly budget
* monthly expenses
* select a transportation radio button
* Select `not sure` checkbox in the `transit time` section
-
-
Observe that the warning dialog disappears

YES tool — FIxes bug in route-option validator

---

requirements/libraries.txt

Bump retirement to 0.10.3
- Bump retirement to 0.10.3, a new version with a bunch of English content changes
1. The content of http://localhost:8000/consumer-tools/retirement/before-you-claim/ should match the screenshots from https://github.com/cfpb/retirement/pull/246
See https://github.com/cfpb/retirement/pull/246
- We'll need to run the management command to update the production database as soon as this is deployed.

Bump retirement to 0.10.3

---

initial-data.sh

This commits modifies the initial-data.sh script so that it calls [the Django createcachetable command](https://docs.djangoproject.com/en/1.11/ref/django-admin/#createcachetable).
When running either with production settings OR when one of the database caches is enabled via environment variables, this command needs to be called manually in order to create the necessary tables. This doesn't happen as part of the normal migrate command.
The Apache-in-Docker setup uses production settings which enables one of these caches, so this command is necessary for that to work right.
If the tables already exist, or if database caching isn't enabled, this command is a no-op.

Add createcachetable command to initial-data.sh

---

cfgov/prepaid_agreements/scripts/write_prepaid_agreements_data_to_csv.py

This was working locally but when I tested generating these files on the DEV2 server, I would get encoding errors.  These changes seem to fix it and I've been able to successfully generate them on the DEV2 server.

Encode prepaid fields in CSV

---

cfgov/prepaid_agreements/tests/test_models.py

The prepaid_agreements Python tests currently generate a few warnings like this:
> RuntimeWarning: DateTimeField PrepaidAgreement.created_time received a naive datetime (2019-09-13 13:33:33.192472) while time zone support is active.
See for example [this Travis log](https://travis-ci.org/cfpb/cfgov-refresh/jobs/584699066).
This change fixes the use of datetimes from naive ones to ones with time zones. It also adds what seems to be a missing model save statement, which doesn't affect the outcome of the tests.
Run `tox`, see no warnings.

Fix naive datetime warnings in prepaid agreements tests

---

cfgov/legacy/views/complaint.py

#5234 inadvertently added a line of Python code that exceeds our linter standard (79 characters).
This was merged while Travis CI checks were temporarily disabled, but now that it has been re-enabled, all PRs (and master) are failing the linter checks ([for example](https://travis-ci.org/cfpb/cfgov-refresh/jobs/585836350)).
`tox -e lint-py27`

Fix line-too-long linter error

---

cfgov/jinja2/v1/_includes/organisms/ask-search.html
cfgov/unprocessed/css/organisms/ask-search.less
cfgov/unprocessed/css/pages/ask.less

- Remove `input-with-btn__bar` class that was setting input height to 35px.
- Refactor ask search to include icon and responsive styling
1. Log into local Wagtail.
1. Create a new sublanding page.
1. Add a "Full width text" 
1. Add a "Well with ask search"
1. Fill in the options and Preview the page. Check at mobile and desktop.
1. Check search fields in Ask CFPB search (/ask-cfpb/) at mobile and desktop.
Desktop
Before (bottom)
After (top)
Mobile
Before (bottom)
After (top)

Refactor ask search to include icon and responsive styling

---

cfgov/jinja2/v1/youth_employment_success/route-option-form.html
cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html
cfgov/unprocessed/apps/youth-employment-success/js/data/todo-items.js
cfgov/unprocessed/apps/youth-employment-success/js/index.js
cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
cfgov/unprocessed/apps/youth-employment-success/js/views/average-cost.js
cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js
test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
test/unit_tests/apps/youth-employment-success/js/views/average-cost-spec.js
test/unit_tests/apps/youth-employment-success/js/views/transit-time-spec.js

Adds a view to handle the `average cost` fieldset. View controls updating the average cost input, whether or not the cost reflects a monthly or daily cost, and if the user isn't sure about the cost (thereby adding a todo to the user's action plan).
- Updates `routeOptionReducer` to handle:
* `averageCost` value
* adding an average cost field to the user's todo list
* a selector function to access the `actionPlanItems` property
- Adds JS view to manage `averageCost` inputs
-
- Minor updates to DOM structure
- Average cost fieldset now toggles itself, vs being toggled by the `routeOptionView` 
1.
-
-

YES Tool — Average cost combo field

---

travis_run.sh

This disables the acceptance tests that depend on WebDriver and Chrome. Once those issues are resolved we can revert this change, but this will ensure we don't have to keep disabling Travis to merge PRs.
@anselmbradford suggested running `test:unit` as a way to do this.

Disable acceptance tests temporarily in Travis

---

cfgov/unprocessed/apps/youth-employment-success/js/index.js

I left in an `import` of a file I removed, which causes the gulp compile action to error.
- Remove invalid ref to `polyfills`
1. Compile command should run without error
-
-

Remove invalid polyfills ref

---

cfgov/unprocessed/apps/youth-employment-success/js/index.js
cfgov/unprocessed/apps/youth-employment-success/js/views/expandable.js
test/unit_tests/apps/youth-employment-success/js/views/expandable-spec.js

So the user can be reminded of what the outcome of their route option choices, display the `route-details` view to them when the `route-option-form` expandable is closed.
- Adds a view to wrap an expandable and coordinate events between it and the DOM
1. Specs should pass
2. In the transit tool, toggle an expandable. You should see the `route-details` view below the expandable click area.
3. Toggle the expandable again, the additional details view should be removed from the DOM.

YES tool — Add view for closed route option

---

cfgov/jinja2/v1/youth_employment_success/goals.html
cfgov/jinja2/v1/youth_employment_success/goals/goal.html
cfgov/unprocessed/apps/youth-employment-success/js/budget-form-view.js
cfgov/unprocessed/apps/youth-employment-success/js/index.js
cfgov/unprocessed/apps/youth-employment-success/js/reducers/goal-reducer.js
cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js
cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
cfgov/unprocessed/apps/youth-employment-success/js/store.js
cfgov/unprocessed/apps/youth-employment-success/js/views/average-cost.js
cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js
cfgov/unprocessed/apps/youth-employment-success/js/views/goals.js
cfgov/unprocessed/apps/youth-employment-success/js/views/input.js
cfgov/unprocessed/apps/youth-employment-success/js/views/miles.js
cfgov/unprocessed/apps/youth-employment-success/js/views/transit-time.js
test/unit_tests/apps/youth-employment-success/js/input-view-spec.js
test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js
test/unit_tests/apps/youth-employment-success/js/views/goals-spec.js

So that the application can store a reference to the user's answers to our questions related to a user's long-term transportation goals, adds a view to update the `goalReducer` when the user interacts with the form controls in this section.
- View + specs for goals section
-
-
1. Unit tests
-
-

YES Tool - Adds view for managing goals section form controls

---

cfgov/prepaid_agreements/jinja2/prepaid_agreements/detail.html
cfgov/prepaid_agreements/jinja2/prepaid_agreements/search_results.html
cfgov/prepaid_agreements/tests/test_views.py
cfgov/prepaid_agreements/views.py

Updates to prepaid search.
- Preserve query string in breadcrumb link from detail to search page.
- Pull prepaid disclaimer text from two reusable text snippets.
2. Navigate to [prepaid search](http://localhost:8000/data-research/prepaid-accounts/search-agreements/) and verify that disclaimer text appears below results
3. Click on link to detail page for first search result. Verify that disclaimer text appears in sidebar.
4. Click breadcrumb on detail page and ensure that it links back to search page.
5. On search page, select and apply a filter. When page reloads, navigate to first result's detail page.
6. Click breadcrumb on detail page and ensure that it links back to search page with selected filter still applied.

Prepaid: disclaimer and breadcrumb

---

cfgov/jinja2/v1/youth_employment_success/goals/goal.html
cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js
cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js
cfgov/unprocessed/apps/youth-employment-success/js/views/miles.js
test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js
test/unit_tests/apps/youth-employment-success/js/views/days-per-week-spec.js
test/unit_tests/apps/youth-employment-success/js/views/miles-spec.js

Due to a bit of PR churn, I needed to clean up code I had mistakenly left in some previously work.
1. Specs should pass.
2. Tool should load in browser

YES tool — Light cleanup and tweaks

---

cfgov/unprocessed/apps/youth-employment-success/js/money.js
cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js
test/unit_tests/apps/youth-employment-success/js/money-spec.js
test/unit_tests/apps/youth-employment-success/js/views/days-per-week-spec.js
test/unit_tests/apps/youth-employment-success/js/views/miles-spec.js

This fixes two bugs in the route details view. We round all calculations to avoid having decimal logic and to give the user more of the feel of an estimate, rather than an exact figure. This PR also fixes a bug where the `Money left in your monthly budget` line item didn't subtract monthly expenses from money earned.
-
-
- Properly display money remaining line item as monthly money earned - money
spent
- Round all calculations up to the nearest whole number
1. In the transportation tool, fill in the budget section
2. Select `Drive` as the method of transportation
3. Fill in `miles` and days per week` fields
4. In the details section, see that money remaining is calculated correctly, and that all numbers are rounded
-
-

YES tool — Fixes budget calculation bugs
