cfpb/consumerfinance.gov

cfgov/ask_cfpb/scripts/export_ask_data.py
Previously, if any of the Ask CFPB answer pages was blank in the 'text', 'how_to_schema', and 'faq_schema' fields (e.g. a blank draft page), the export_ask_data command would result in a 500 error.
Allow these blank drafts to be exported along with the rest of the
pages.
- Prevent a ` IndexError: list index out of range` when exporting a blank page by catching cases where `answer_schema` has no contents.
2. Log in to the Wagtail admin using `admin`/`admin`
3. On the left-hand sidebar, scroll down to select the second-to-last option, "Export Ask data"
4. Press the "Download CSV" button
5. The action should complete without any python errors, and you should get a CSV file of all Ask answer pages.
=> Prevent error on export of blank Ask CFPB pages

cfgov/jinja2/v1/youth_employment_success/review/your-plan.html, cfgov/unprocessed/apps/youth-employment-success/js/index.js, cfgov/unprocessed/apps/youth-employment-success/js/money.js, cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js, cfgov/unprocessed/apps/youth-employment-success/js/util.js, cfgov/unprocessed/apps/youth-employment-success/js/views/review/details.js, cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js, test/unit_tests/apps/youth-employment-success/js/money-spec.js, test/unit_tests/apps/youth-employment-success/js/util-spec.js, test/unit_tests/apps/youth-employment-success/js/views/review/details-spec.js
This PR adds a JS view for the details review section  — it displays the same data as the details section (minus the todo list) and shows the todo list in a separate area.
- View to manage the above-mentioned sections
- Fixes bug in `money` utility where  negative numbers didn't subtract properly
1. Unit tests
2. Information entered into the transportation tool should also update the details area of the review section
3. A notification should appear when there are pending todo list items in a route.
** Details **:
** Notification when to-do list items **:
** Notifications without to-do list items **:
- Certain elements are not being shown at this point, e.g. the text after `Your first choice is` because that is controlled by user input for which there is not yet javascript code.
=> YES Tool - Add detail review view

cfgov/jinja2/v1/youth_employment_success/index.html, cfgov/jinja2/v1/youth_employment_success/review/index.html, cfgov/jinja2/v1/youth_employment_success/review/review.html, cfgov/jinja2/v1/youth_employment_success/review/your-plan.html, cfgov/unprocessed/apps/youth-employment-success/js/index.js, cfgov/unprocessed/apps/youth-employment-success/js/reducers/choice-reducer.js, cfgov/unprocessed/apps/youth-employment-success/js/store.js, cfgov/unprocessed/apps/youth-employment-success/js/views/review/choice.js, test/unit_tests/apps/youth-employment-success/js/reducers/choice-reducer-spec.js, test/unit_tests/apps/youth-employment-success/js/views/review/choice-spec.js
PR adds logic and user input handling around the review choice section detailed in the screenshots section
- View to handle user input
- Reducer to supply data to application
- The review plan is now hidden by default. It is only shown when the `Review your plan` button is clicked.
1. Specs
2. 
* In the transportation tool, select a transportation option for both routes
* Scroll down to the `review your plan` section.
* Select one of the two radio buttons
* Click the `review your plan` button
* The remainder of the plan review section should be visible.
=> YES too - View and specs for review choice section

cfgov/jinja2/v1/youth_employment_success/review/your-plan.html, cfgov/unprocessed/apps/youth-employment-success/js/data/transportation-map.js, cfgov/unprocessed/apps/youth-employment-success/js/views/review/choice.js, cfgov/unprocessed/apps/youth-employment-success/js/views/review/details.js, cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js, test/unit_tests/apps/youth-employment-success/js/route-option-view-spec.js, test/unit_tests/apps/youth-employment-success/js/views/review/details-spec.js, test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
Previously, the review section displayed the route details information in the order in which those routes were entered by the user, ignoring the user's choice of which route they preferred to use to get to work. Now, this choice is properly reflected in the review section.
- Display route details in review section in user-indicated order of preference
- Display transportation type in `h3` `p` tags in review section
- Display success alert in `route-option` form when route information is complete and
option is in-budget
- Hides todo lists in review section when there are no todos.
1. Specs pass
2. Fill in both route options
* Select a primary route
* Click `review your plan`
* Your selected plan should be the first one shown in the review section
* Choose a the second plan, the former step …
=> YES tool — Map primary route choice to plan review

cfgov/jinja2/v1/youth_employment_success/index.html, cfgov/jinja2/v1/youth_employment_success/line-item.html, cfgov/jinja2/v1/youth_employment_success/review/index.html, cfgov/jinja2/v1/youth_employment_success/review/print.html, cfgov/jinja2/v1/youth_employment_success/review/review.html, cfgov/jinja2/v1/youth_employment_success/review/your-plan.html, cfgov/jinja2/v1/youth_employment_success/route-details.html, cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html, cfgov/jinja2/v1/youth_employment_success/route-questions/days-per-week.html, cfgov/jinja2/v1/youth_employment_success/route-questions/driving-cost-estimate.html, cfgov/jinja2/v1/youth_employment_success/route-questions/miles.html, cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less, cfgov/unprocessed/apps/youth-employment-success/js/index.js, cfgov/unprocessed/apps/youth-employment-success/js/views/print-button.js, test/unit_tests/apps/youth-employment-success/js/views/print-button-spec.js
Hides non-critical elements when user prints their review plan.
- Class to control hiding elements irrelevant to the user's review plan
1. Clicking the `Print your plan` button brings up the system print dialog; the user should only see the `your plan` review section.
=> YES Tool - Initial pass at review page print

cfgov/jinja2/v1/youth_employment_success/review/your-plan.html, cfgov/jinja2/v1/youth_employment_success/route-details.html, cfgov/jinja2/v1/youth_employment_success/route-option.html, cfgov/unprocessed/apps/youth-employment-success/js/reducers/choice-reducer.js, cfgov/unprocessed/apps/youth-employment-success/js/views/review/details.js, test/unit_tests/apps/youth-employment-success/js/views/review/details-spec.js, test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
When the user selects the `I want to complete items in my to-do list before deciding` option in the review choice section, hide the 'Primary option' and 'Possible option' headings.
- User will only see plan details section when they elect to complete todo list
items before making a decision
- Fixes spacing issues in details plans
1. Unit tests
2. Select a mode of transportation for both route options.
* In the review choice section, choose the `wait` option
* The displayed plans should just show the todo lists (if they exist) and the route option detail breakdown
=> YES tool — Hides review plan choice headings on wait option

cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html, cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less, cfgov/unprocessed/apps/youth-employment-success/js/budget-form-view.js, cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js, cfgov/unprocessed/apps/youth-employment-success/js/todo-notification.js, cfgov/unprocessed/apps/youth-employment-success/js/views/input.js, cfgov/unprocessed/apps/youth-employment-success/js/views/transit-time.js, test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js, test/unit_tests/apps/youth-employment-success/js/views/review/details-spec.js, test/unit_tests/apps/youth-employment-success/js/views/transit-time-spec.js
To Improve the user's quality-of-life while interacting with the tool, fill in defaults of `0` for either `hours` or `minutes` fields in the transit time section of the form when one is present and the other is omitted.
For example, if it takes the user 45 minutes to get to work, automatically fill the `hours` field with a `0`
- Transit time fields now update on `blur`
- Add a zero in the `minutes` field when `hours` is filled in and `minutes` is not, and vice versa.
1. Unit tests should pass
2. Filling in either of the two time fields fills in the other with a zero. The fields can each still be filled in normally.
=> YES tool — Set default values of transit time fields

cfgov/unprocessed/apps/youth-employment-success/js/validators/route-option.js, cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js, cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js, test/unit_tests/apps/youth-employment-success/js/views/days-per-week-spec.js
So that the user can correctly indicate how many days per week they expect to travel for work, always show the `daysPerWeek` field, unless the  user indicated the cost of
transportation should be calculated on a per month basis
- Show `daysPerWeek` form controls for all transportation types
- Properly detect if `miles` and `daysPerWeek` form controls have the to-do list checkbox selected in the route option form validator
1. Specs pass
2. The `How many days per week will you make this trip?` form controls appear when the transportation tool is loaded.
3. The aforementioned field stays on screen when different transportation types are selected.
4. The field is removed from the screen is `per month` is selected in the `averageCost` form controls.
5. The field returns, and is cleared, if the …
=> YES tool — Refines when daysPerWeek field is shown

cfgov/jinja2/v1/youth_employment_success/goals.html, cfgov/jinja2/v1/youth_employment_success/index.html, cfgov/jinja2/v1/youth_employment_success/no-js.html, cfgov/jinja2/v1/youth_employment_success/review/index.html, cfgov/jinja2/v1/youth_employment_success/review/next-steps.html, cfgov/jinja2/v1/youth_employment_success/review/print.html, cfgov/jinja2/v1/youth_employment_success/review/review.html, cfgov/jinja2/v1/youth_employment_success/review/your-plan.html, cfgov/jinja2/v1/youth_employment_success/route-details.html, cfgov/jinja2/v1/youth_employment_success/route-options.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less, cfgov/unprocessed/apps/youth-employment-success/js/index.js, cfgov/unprocessed/apps/youth-employment-success/js/views/print-button.js, test/unit_tests/apps/youth-employment-success/js/views/print-button-spec.js
To help the user make the choice to either use a different browser or print the page, display an alert in a `no-js` env. 
- Alert message when javascript is not detected / unsupported
- Changes print behavior. Now, JS will run to hide all certain elements when the `print your plan` button is clicked. Otherwise, all elements not tagged to hide on print will print in a `no-js` env.
1. When printing without JS, images, the red `danger` alert, and buttons should not appear in the print dialog box
2. When printing from the `print your plan` button, everything but the plan review section should be hidden.
=> YES tool — Display alert in no-js environment

cfgov/jinja2/v1/youth_employment_success/budget-form.html, cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html, cfgov/jinja2/v1/youth_employment_success/route-questions/days-per-week.html, cfgov/jinja2/v1/youth_employment_success/route-questions/input.html, cfgov/jinja2/v1/youth_employment_success/route-questions/miles.html, cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less, cfgov/unprocessed/apps/youth-employment-success/js/budget-form-view.js, cfgov/unprocessed/apps/youth-employment-success/js/views/average-cost.js, cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js, cfgov/unprocessed/apps/youth-employment-success/js/views/input.js, cfgov/unprocessed/apps/youth-employment-success/js/views/miles.js, cfgov/unprocessed/apps/youth-employment-success/js/views/transit-time.js, test/unit_tests/apps/youth-employment-success/js/input-view-spec.js
So that the user doesn't enter invalid characters and get confused when calculations don't reflect
the input, sanitize all data numeric input to strip out any non-digit characters.
- Adds input sanitization to text inputs with a `pattern` attribute
1. Specs
2. Entering anything other than numbers into any of the text inputs should display only numbers. With no javascript, the fields will still be disabled
=> YES Tool - Adds input sanitization

cfgov/jinja2/v1/youth_employment_success/review/your-plan.html, cfgov/jinja2/v1/youth_employment_success/route-details.html, cfgov/jinja2/v1/youth_employment_success/route-option-form.html, cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less, cfgov/unprocessed/apps/youth-employment-success/js/index.js, cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js, test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
Another round of design feedback for improved look + feel.
- Hide To-do list section when there are no items in the list
- Add spacing between `content-line` and the first to-do list item
- In the reviewing your plan section, for the to-do list headings (`Option 1`, `Option 2`, etc), classes should be `h5`
- Spacing between hours and minutes fields should be 30px. *Note*: I've tightened this up but am constrained by the core grid of `capital-framework`.
- The width of the totals for each option in the `reviewing your plan` section should match the width of the text in that same section.
- Alert box widths should all be 100% of their containers
=> YES tool — Implements further design tweaks

requirements/libraries.txt
- Journey Page updates
- CRTool unit test updates
- Polyfill for position: sticky
- CRTool: Added react-app-polyfill
- CRTool: Removed babel-polyfill
- Updated CRTool packages and fixed CRTool unit tests (Changes can be seen here: https://github.com/cfpb/teachers-digital-platform/pull/354/files)
- Content for building blocks
- CSS layout fix for IE11
- Sticky layout fix for Android
@Scotchester @willbarton  @higs4281 @chosak
=> Bump TDP release to 1.1.7

cfgov/cfgov/settings/base.py, cfgov/legacy/templates/complaint/complaint-landing.html, cfgov/legacy/views/complaint.py
The September 2019 CCDB feature flag was only needed to prevent content from going live before the go-live date. That date has now passed, so the flag is no longer needed.
- Removed the feature-flagged parts of `complaint-landing.html` 
- Renamed the CCDB landing page feature flag to be more generic 
1. Visit http://localhost:8000/data-research/consumer-complaints/ and make sure it matches exactly what's live at https://www.consumerfinance.gov/data-research/consumer-complaints/
2. Put some content behind the newly named `CCDB_CONTENT_UPDATES` feature flag in the landing page template
3. With the feature flag disabled, visit http://localhost:8000/data-research/consumer-complaints/ and make sure the content doesn't appear
4. Enable the `CCDB_CONTENT_UPDATES` flag, visit …
=> Remove September 2019 CCDB feature flag

cfgov/jinja2/v1/youth_employment_success/budget-form.html, cfgov/jinja2/v1/youth_employment_success/route-questions/average-cost.html, cfgov/jinja2/v1/youth_employment_success/route-questions/days-per-week.html, cfgov/jinja2/v1/youth_employment_success/route-questions/input.html, cfgov/jinja2/v1/youth_employment_success/route-questions/miles.html, cfgov/jinja2/v1/youth_employment_success/route-questions/transit-time.html, cfgov/unprocessed/apps/youth-employment-success/js/sanitizers/index.js, cfgov/unprocessed/apps/youth-employment-success/js/util.js, cfgov/unprocessed/apps/youth-employment-success/js/views/average-cost.js, cfgov/unprocessed/apps/youth-employment-success/js/views/input.js, test/unit_tests/apps/youth-employment-success/js/input-view-spec.js, test/unit_tests/apps/youth-employment-success/js/sanitizers/sanitizer-spec.js, test/unit_tests/apps/youth-employment-success/js/util-spec.js, test/unit_tests/apps/youth-employment-success/js/views/average-cost-spec.js
To better improve user experience, the follow changes are being made to the input sanitization
* Sanitizing is now a more robust chain of functions vs. a single pattern
* Strip leading zeros from all numbers
* Allow decimals back in
* Format all money numbers to a fixed decimal precision of 2
1. Specs
2. Inputs should behave as outlined in specs when data is manually entered.
=> YES tool - Address QA feedback issues around input sanitizing

cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js, test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
Due to a code oversight, the current uses a default of 5 days per week to calculate the total monthly cost of the user's selected transportation option. This PR removes the default and fills in a `0` unless the user specifically indicates the number of days per week they expect to make their commute.
- Removes default days per week value
- Calculations for a full month are now multiplied by a straight `4`, instead of a slightly higher value to accommodate months that may have 5 weeks.
1. Specs pass
2. In the tool, the estimated cost line item should be 0 unless the days per week field is filled in, or the average cost is a monthly cost.
=> YES Tool — Use actual daysPerWeek value input by user

cfgov/jinja2/v1/youth_employment_success/route-option-form.html, cfgov/unprocessed/apps/youth-employment-success/js/data/transportation-map.js, cfgov/unprocessed/apps/youth-employment-success/js/route-option-view.js, cfgov/unprocessed/apps/youth-employment-success/js/views/driving-cost-estimate.js, cfgov/unprocessed/apps/youth-employment-success/js/views/review/details.js
Adds option for `rideshare` in transportation options 
- Adds ridesahre option
1. Specs
2. `Rideshare or cab` should be a selectable mode of transportation; it behaves the same as the non `Drive` options
=> YES tool — Adds missing rideshare transportation option

cfgov/prepaid_agreements/tests/test_views.py, cfgov/prepaid_agreements/views.py
A blank search of prepaid agreements (/data-research/prepaid-accounts/search-agreements/) currently results in a 500 error. This PR fixes that.
This is because the `get_available_filters` is being passed `products` as a `Manager` object that's empty. Attempting to iterate it will raise a `TypeError`. This means blank searches will 500. This fix uses `products.all()` when iterating over the manager passed to `get_available_filters` that results from searching products.
It also fixes the test to catch this issue. This function gets the queryset in code but was getting `objects.all()` in the test.
=> Prepaid: fix blank search 500s

cfgov/unprocessed/apps/youth-employment-success/js/data/todo-items.js, cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js, test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js, test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
Previously, with multiple items in the to-do list, clearing one item would clear out the entire list. Now users can toggle list items and be confident that only the toggled item is getting removed.
- Added the second argument to `splice` in the `updateActionPlan` method of the `route-option-reducer`, the reducer will now correctly remove a single item.
1. Specs
2. In the transportation tool, select 2 or more `not sure` checkboxes. Then, deselect one. The to-do list section should remain visible, and correctly reflect the number of checked items.
=> YES tool — Fixes bug where to-do list was cleared on single item removal

cfgov/jinja2/v1/_includes/molecules/featured-menu-content.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html
This change alters the templates used to render the site mega menu so that they use Wagtail's [`pageurl`](https://docs.wagtail.io/en/v1.13.4/advanced_topics/jinja2.html#pageurl) template tag instead of the [`Page.url`](https://github.com/wagtail/wagtail/blob/v1.13.4/wagtail/wagtailcore/models.py#L849) method to get URLs for Wagtail pages.
When using the local development setup (which disables any Django caching used during Wagtail page lookups), this reduces the number of database queries required to render the mega menu from 243 to 147.
To test, run a local server with the Django debug toolbar:
```
ENABLE_DEBUG_TOOLBAR=1 ./runserver.sh
```
Visit http://localhost:8000 on master and on this branch, and compare the number of queries. (Note that the first request when using the Django …
=> Use pageurl tag to reduce mega menu DB queries

cfgov/agreements/jinja2/agreements/index.html
@cfarm 
- Makes Q1-2019 the most recent agreement download and archives Q4-2018.
1. Visit http://localhost:8000/credit-cards/agreements/
2. Note the updated Q1-2019 and Q4-2018 links
=> Add Q1-2019 as most recent agreement dump and archive Q4-2018

cfgov/jinja2/v1/youth_employment_success/review/your-plan.html, cfgov/unprocessed/apps/youth-employment-success/css/main.less, cfgov/unprocessed/apps/youth-employment-success/js/sanitizers/index.js, cfgov/unprocessed/apps/youth-employment-success/js/util.js, cfgov/unprocessed/apps/youth-employment-success/js/views/review/goals.js, cfgov/unprocessed/apps/youth-employment-success/webpack.config.js, test/unit_tests/apps/youth-employment-success/js/views/review/details-spec.js, test/unit_tests/apps/youth-employment-success/js/views/review/goals-spec.js
This PR fixes several bugs / design inconsistencies related to some of the new work
- incorrect `small` tag changed to `p`
- background color for to-do list well now matches expandable background color
- `goals` in review section now updates properly on first render
- commas properly preserved when formatting money
1. Specs
2. All money inputs should preserve commas when focus is lost
3. All money line item (totals) nodes should preserve commas
4. All money line item nodes should have two decimals places.
=> YES tool — Bug roundup

cfgov/paying_for_college/disclosures/scripts/load_programs.py
In September we changed some http URLs used in code to https.
Most of the changes were good as-is, but one related to an S3 resource made
a Jenkins job fail, because the S3 URL was not designed to be used with https.
In this case, the old URL was:
`http://files.consumerfinance.gov.s3.amazonaws.com/pb/paying_for_college/csv/validated_program_data/[SLUG]`
Using that URL with https raises a certificate error when a Jenkins job requests it.
The https form that we can use (as pointed out by @rosskarchner) is:
`https://s3.amazonaws.com/files.consumerfinance.gov/pb/paying_for_college/csv/validated_program_data/[SLUG]`
To load an S3 resource locally and confirm that the S3 file is fetched using https without error, run
```bash
./cfgov/manage.py load_programs --s3 true CFPB_EDMC_20191017.csv
``` …
=> Paying for college: Fix the https URL of S3 resources

cfgov/jinja2/v1/youth_employment_success/line-item.html, cfgov/jinja2/v1/youth_employment_success/route/route-details.html, cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js, test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
So the user doesn't get confused by situational text, remove the `Based on the {n} days a week you will make this trip` text when the user indicates that their average cost of getting to work is calculated on a monthly basis.
- Hide this text when the user indicates their average cost to get to work is
a monthly cost
1. Specs should pass
2. In a route option form, select the `monthly` radio button choice in the `average cost` fieldset
=> YES Tool — Conditionally hide the days per week copy

cfgov/unprocessed/apps/youth-employment-success/js/reducers/route-option-reducer.js, cfgov/unprocessed/apps/youth-employment-success/js/validators/route-option.js, cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js, test/unit_tests/apps/youth-employment-success/js/reducers/route-option-reducer-spec.js, test/unit_tests/apps/youth-employment-success/js/validators/route-option-spec.js
This PR fixes the following issues around which alert notifications should be displayed:
* When `averageCost` is entered but `per month` or `per day` is not, the yellow incomplete alert
should be displayed.
* When `averageCost` is entered and `per day` is selected, but `daysPerWeek` is empty, the yellow incomplete alert should be displayed.
* When a to-do list item is selected, and all other data is filled in, and the user moves to a different transportation type, the green success alert `looks good, but with todos` should show.
- Adds validations for all transportation types other than `drive`, to capture the behavior of the `averageCost` and associated fields
- Adds `isEmpty` method to determine if a value is empty, rather than relying on a straight boolean check (`!value`)
* Updates …
=> YES tool — Updates validation, fixes reducer splice logic

cfgov/jinja2/v1/youth_employment_success/line-item.html, cfgov/jinja2/v1/youth_employment_success/route/route-details.html, cfgov/unprocessed/apps/youth-employment-success/js/util.js, cfgov/unprocessed/apps/youth-employment-success/js/validators/route-option.js, cfgov/unprocessed/apps/youth-employment-success/js/views/days-per-week.js, cfgov/unprocessed/apps/youth-employment-success/js/views/route-details.js, cfgov/unprocessed/js/routes/on-demand/youth-employment-programs/buying-a-car/index.js, test/unit_tests/apps/youth-employment-success/js/util-spec.js, test/unit_tests/apps/youth-employment-success/js/validators/route-option-spec.js, test/unit_tests/apps/youth-employment-success/js/views/days-per-week-spec.js, test/unit_tests/apps/youth-employment-success/js/views/route-details-spec.js
To avoid confusing the user with calculations made from incomplete data, always display a `-` in the line item break totals of `Average monthly cost of x` and `Total left in your budget after x`.
- Always show a `-` in the aforementioned totals unless all fields necessary for calculation are present. Previously, the field defaulted to  `$0.00` once the user started entering values.
1. Specs
2. With `Drive` selected and the budget fields filled in:
* Enter `numberOfMiles`, totals should be `-`
* Enter `daysPerWeek` totals should calculate
* Delete `numberOfMiles`, totals should be `-`
3. Now, select a new mode of transportation:
* Totals should be `-`
* Fill in `averageCost`, totals should be `-`
* Select `per month`, totals should calculate
* Select `per day`, remove `daysPerWeek`, totals …
=> YES Tool — Adds new default of '-' when line item totals cant be calculated

requirements/libraries.txt
Remove manual SQL action from migration
The manual SQL action didn't work as intended anywhere except production for reasons that are not entirely obvious. We think it's safest just to remove it, and we'll manually work on any databases we might need to.
=> Update owning-a-home-api to 0.12.3

cfgov/cfgov/settings/base.py, cfgov/housing_counselor/tests/test_views.py
Previously, when there was an error fetching a file from the bucket (a 500 error in S3), CloudFront would cache the error for five minutes, meaning that even if the underlying error was resolved, end users would still receive an error when trying to visit that page in the FAHC tool.
We have code to retry a request to S3 if it receives a 5XX error, which was not useful when CloudFront was caching responses. By bypassing CF, requests that 500 will be retried immediately, which may reduce the number of user-facing 500 errors.
- From the Housing Counselor tool, use `https://s3.amazonaws.com/files.consumerfinance.gov` to directly access the files.consumerfinance.gov S3 bucket, instead of accessing it via CloudFront.
2. Visit http://localhost:8000/find-a-housing-counselor/
3. …
=> Bypass CloudFront when accessing HUD search results in S3

cfgov/jinja2/v1/job-description-page/index.html
Limit read more functionality to mobile screens.
- Update read-more class
2. Navigate to a job posting page locally
3. Verify that that job description is not displayed in an expandable at desktop screen size
4. Verify that job description is truncated and expandable at mobile screen sizes
=> Job posting expandable fix

requirements/libraries.txt
This upgrade doesn't affect functionality, but does keep us up to date.
[The 0.8 release](https://pypi.org/project/wagtail-inventory/) adds support for Wagtail 2.6.
=> Bump wagtail-inventory version from 0.7 to 0.8

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/jinja2/v1/home-page/index_new.html, cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/organisms/carousel.less, cfgov/unprocessed/js/organisms/Carousel.js, cfgov/unprocessed/js/routes/on-demand/home-page.js, cfgov/unprocessed/js/routes/single.js, cfgov/v1/models/home_page.py
Adds an initial front-end architecture for a carousel organism, for cycling through a sequence of blocks of content.
- Adds Carousel organism JavaScript, CSS, and jinja template.
- Adds `single.js` script for scripts only on the homepage route.
1. Pull branch, run `gulp clean && gulp build`
2. Enable alternate homepage design (via instructions in https://github.com/cfpb/cfgov-refresh/pull/5335)
3. Visit http://localhost:8000/?nhp=True and see there's a barebones carousel that you can click forward and backward through.
=> Homepage: Add initial carousel organism

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/unprocessed/css/organisms/carousel.less, cfgov/unprocessed/js/organisms/Carousel.js
Hides carousel by default on page load and then shows it when the JS has initialized. Shows the carousel stacked in the no-js state.
- Hides carousel by default till JS is initialized.
- Stacks carousel in no-js state.
1. Pull branch, run `gulp clean && gulp build`
2. Load http://localhost:8000/?nhp=True and see that Carousel is hidden till JS is initialized.
3. Inspect the page and change the `js` class on the `html` element to `no-js` and see that the carousel items stack on top of each other and the buttons disappear.
=> Homepage: Carousel no-js state

cfgov/unprocessed/apps/find-a-housing-counselor/css/hud_print.css, cfgov/unprocessed/css/main.less
The stylesheet for the forthcoming YES car buying guide was a little too aggressive in hiding things on print, and it was being applied globally. Since that page hasn't launched, I have commented it out of the global `main.less` file to fix the immediate problem. Further consideration will need to be given to how to scope the styles that the car buying guide will need to only that page.
1. Visit http://localhost:8000/find-a-housing-counselor/?zipcode=12306
2. Print preview (the easiest way to do this in Chrome is to use the Print command and look at the preview); see that the list of counselors is missing
3. Pull this branch
4. `yarn run gulp styles`
5. Hard refresh the page
6. Print preview again and see that the content appears
- Figure out a better solution for scoping CSS to a …
=> Restore content on print

cfgov/prepaid_agreements/views.py
Prepaid agreement search throws a 500 error in Python 3
- Added iterlists import from django.utils.six in views.py
1. http://localhost:8000/data-research/prepaid-accounts/search-agreements/
2. http://localhost:8333/data-research/prepaid-accounts/search-agreements/
=> Added iterlists import from django.utils.six to fix 500 error in Python 3

cfgov/jinja2/v1/_includes/organisms/info-unit-group-2.html, cfgov/jinja2/v1/home-page/index_new.html, cfgov/v1/models/home_page.py
This commit adds some hardcoded InfoUnits to the new homepage design, using the 33/33/33 InfoUnitGroup template. This content is hardcoded pending implementation as editable Wagtail blocks. Content is placeholder and is the same in both English and Spanish right now.
@contolini 
To test, visit the English and Spanish versions of the new homepage:
- http://localhost:8000/?nhp=True
- http://localhost:8000/es/?nhp=True
For this to work correctly you need to have the referenced image locally; see #5365 for one way to pull down production images to your local storage.
The colored box above is the in-progress carousel; @anselmbradford do you have any suggestions for the right way to add some margin between it and this new content?
=> Add hardcoded InfoUnits to new homepage design

cfgov/v1/management/commands/sync_image_storage.py, docs/installation.md
When developing locally using a production database dump, it can be distracting and difficult to work with Wagtail images. Images (and their renditions) are stored in the database, but in production the image files themselves are stored in S3. When developing locally with a dump, you have the references to those files, but not the files themselves. This means missing images when browsing pages, which can break layout and make it hard to debug and develop visual styles.
This commit adds a new Django management command, `sync_image_storage`, that can be used to download in bulk all images and renditions referenced in the database.
```sh
cfgov/manage.py sync_image_storage https://files.consumerfinance.gov/f/ ./cfgov/f/
```
Note that this can take a little while as it downloads quite a few …
=> Add helper script to sync local image storage

cfgov/v1/atomic_elements/organisms.py
Landing-page cards are now built from topic tags, not categories.
Hat-tip to @chosak for catching this.
=> This commit removes ask-cfpb code that is no longer used.

cfgov/unprocessed/js/routes/on-demand/home-page.js
This commit fixes a bug with the prototype carousel created for a new home page design. When running the current production home page, there's no carousel element, so this causes a JS console error.
This change handles the case where there is no carousel organism, while still properly handling the case when there is one.
@contolini
To test: `gulp clean && gulp build`, visit http://localhost:8000.
=> Handle missing carousel organism on home page

cfgov/v1/management/commands/sync_image_storage.py
The sync_image_storage management command introduced in #5365 logs the images and renditions that it tries to download. This change modifies the log output so that the primary key is also logged, making it easier to debug any failures.
New log output looks like:
```
1/100 (123) Saving https://files.consumerfinance.gov/f/original_images/foo.png to ./cfgov/f/original_images/foo.png
1/100 (123) 1/3 (456) Saving https://files.consumerfinance.gov/f/images/foo.max-800x600.png to ./cfgov/f/images/foo.max-800x600.png
...
```
=> Better logging for sync_image_storage script

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/jinja2/v1/home-page/index_new.html, cfgov/v1/models/home_page.py
This change adds some placeholder content for the carousel in the new home page design.
@contolini 
Run a local server and visit http://localhost:8000/?nhp=True.
The design still needs some work to properly handle image sizing, I think?
=> Prepare placeholder carousel data for Wagtail

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/unprocessed/css/organisms/carousel.less
- Changes next/previous buttons in the carousel slideshow to use standard `a-btn` CF classes.
1. Pull branch, run `gulp clean && gulp build`
2. Visit http://localhost:8000/?nhp=True and see that buttons are standard blue buttons.
=> Homepage: Convert to standard button for carousel slideshow

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/unprocessed/css/organisms/carousel.less
- Incorporates flexbox into thumbnail layout for a flexible responsive layout for the thumbnails.
1. Pull branch, `gulp clean && gulp build`
2. Visit http://localhost:8000/?nhp=True and edit content to add longer text and see that all thumbnails have single pixel borders and are top aligned at all screen sizes.
With taller content:
Responsive:
- Focus states are not ready.
- We'll likely want to add flexbox to modernizr and hide it when flexbox is not supported (legacy IE)
=> Homepage: Flexible thumbnail layout in carousel

cfgov/unprocessed/css/organisms/carousel.less
Fix issue introduced when merging https://github.com/cfpb/cfgov-refresh/pull/5377 and https://github.com/cfpb/cfgov-refresh/pull/5376 one after the other. One used the default button styles and the other set those styles to zero padding. The zero padding should only be applied to buttons in the thumbnails.
- Move zero padding of buttons to thumbnails only.
=> Fix button padding

cfgov/unprocessed/css/organisms/carousel.less
- Set focus state on carousel thumbnails.
- Vertical-align the slide text content to the top.
- Remove unneeded `display: table-row` rule.
1. Pull branch, `gulp clean && gulp build`
2. Visit http://localhost:8000/?nhp=True
3. Click into the carousel and then use the tab key to navigate to the thumbnails. Note that they get a focus border around them. Use the spacebar to "click" them. Use shift+tab key to go in the reverse order.
=> Homepage: Set focus styles on carousel thumbnails

cfgov/jinja2/v1/_includes/molecules/card.html, cfgov/jinja2/v1/_includes/organisms/card-group.html, cfgov/jinja2/v1/home-page/index_new.html, cfgov/v1/models/home_page.py
This commit adds placeholder content for the cards in the new home page design, along with some stub frontend code for rendering them (desperately in need of styles).
@contolini 
Run a local server and visit http://localhost:8000/?nhp=True.
Currently renders like this:
I took a stab at creating an organism/molecule for these, but defer to FEWDs as to the right way to do this.
- Needs automated tests.
=> Add placeholder content for home page cards

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/unprocessed/css/organisms/carousel.less, cfgov/unprocessed/js/organisms/Carousel.js
- Add breakpoints for thumbnails and showcase items in carousel.
- Fix gray border colors.
- Add fade animation.
1. http://localhost:8000/?nhp=True and resize the page. Note change in width of showcase item image width and that thumbnails have three layouts: 4 across, 2 on 2, and 4 stacked.
- The border on the thumbnails is throwing off the width by 1px making the focus state outline off by a pixel. It would be nice to fix this.
=> Homepage: Carousel add breakpoints

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/unprocessed/css/organisms/carousel.less
- Add mobile carousel appearance.
2. Visit http://localhost:8000/?nhp=True and resize the page and see that the thumbnails lose their selected state and show links.
3. Focus state should be the whole button at desktop when tabbing. It should be the image and links at mobile size.
- I originally used the same markup for both mobile and desktop, however, to get the focus behavior to work correctly when tabbing through the content we'd need to set the tabindex to ignore the thumbnail text and image links at desktop sizes, these would then need to be removed via JavaScript from the mobile size. I opted instead to duplicate the markup, which is unfortunate, but I think it is more maintainable. The original commit can be viewed at …
=> Homepage: mobile carousel items

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/v1/models/home_page.py
This PR updates the (harcoded) images on the new homepage design.
First, the info units are all updated to be more appropriate. These are now hardcoded to Wagtail image IDs that exist in our production database. For these to work locally, you'll need all of the relevant image and rendition files locally. These can be grabbed as part of the full dump using the process described [here](http://cfpb.github.io/cfgov-refresh/installation/#sync-local-image-storage).
Second, the carousel image logic has been changed incrementally to also rely on a Wagtail image instead of a hardcoded URL, as a step towards the larger change being worked on in #5383. This makes use of [Wagtail image template tags](https://docs.wagtail.io/en/v2.7/topics/images.html) with a `fill-50x50` filter to generate the square …
=> New homepage image updates

cfgov/unprocessed/css/organisms/carousel.less
- Makes currently visible carousel item layered above other hidden slides.
1. Pull branch and build
2. Visit http://localhost:8000/?nhp=True and text in the slide should be selectable and right-clickable.
=> Homepage: Fix issue with layering in carousel items

requirements/libraries.txt
The final piece of the get-govdelivery-up-to-snuff work!
1. Pull branch
1. `docker-compose build python2 python3`
1. See that it installs govdelivery 1.3
1. `docker-compose up`
1. Visit http://localhost:8000/about-us/blog/ and test the email signup form (ask me if you need staging environment credentials)
=> Update govdelivery package to v1.3

cfgov/unprocessed/css/organisms/carousel.less
Carousel was busted in the no-js state, this fixes it.
- Fix layout when in the no-js state so mobile thumbnails show up and carousel items are stacked at desktop.
1. Pull branch and build
2. http://localhost:8000/?nhp=True and turn JS off. Carousel items should stack at desktop and be thumbnail links at mobile.
=> Homepage: Fix carousel no-js state

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/v1/models/home_page.py
This change modifies the (not final) hardcoded content for the new homepage design. It also removes the use of custom alt text on carousel images; we've decided not to support that and instead just use the image's default alt text, if it has any.
Testing requires a production dump as well as some images that are not yet public; ping me if you want to reproduce. This branch is also currently running on (internal) DEV5.
FYI @sonnakim.
=> Content updates for the new homepage design

cfgov/unprocessed/css/organisms/carousel.less
Sets the large images to `display: block` to eliminate the inherent vertical line height of inline images. Also comments out the red background color which still appears at anything less than max page width.
1. Pull branch
1. `yarn run gulp styles`
1. Load up the homepage and see no more red bar
=> Carousel: Eliminate extra vertical space (the red bar) below large images

cfgov/unprocessed/css/organisms/carousel.less
We want the top bar on the active item's thumbnail to stay green, even when it's being hovered.
1. Pull branch
1. `yarn run gulp styles`
1. Reload homepage and try hovering over the active item
- Another thing to consider would be removing the hand cursor on that item.
/cc @huetingj
=> Carousel: Keep bar on active item green on hover

cfgov/unprocessed/js/organisms/Carousel.js
- Adds analytics code to carousel interactions.
1. Pull branch
2. Add console.log statements above the `Analytics.sendEvent` entries in this PR with the value of the `label`.
3. `gulp clean && gulp build`
4. Visit http://localhost:8000/?nhp=True and click the next/previous buttons and/or the thumbnails in the carousel. You should see outputs like:
Once all slides are seen you will see "All Items Seen"
- Once all slides are seen the "All Items Seen" event will fire each time the slide is changed since there's no logic to reset the count. I'm not sure if this is the desired behavior or not.
=> Homepage: Add analytics code to carousel

cfgov/jinja2/v1/ask-cfpb/answer-page.html
Per stakeholder request (GHE issue link available upon request), we are temporarily removing the "Next steps module" from Ask CFPB answer pages. The simplest solution seemed to be removing the block altogether, although I am open to other solutions.
- Remove code which creates "Next steps" content well
1. Run this branch and check to see if the Next Steps content is still there. It shouldn't be!
- Since the stakeholder indicates this is intended as "temporary," maybe we could just make it evaluate to `false` or something, but I tend to err towards removal because, hey, the git history is always there!
=> Ask CFPB - Remove "Next Steps" content well

cfgov/paying_for_college/tests/test_scripts.py
Tests that involve Postgres-only features, such as the JSONField column setting,
need to be skipped if we're running unit tests that create a database other than Postgres, 
such as SQLite, which is the Django default test db.
This change allows users to run tests without setting a TEST_DATABASE_URL env var.
Try running PFC tests without a specified test database:
```bash
unset TEST_DATABASE_URL
tox -e fast paying_for_college
```
Four tests should be skipped, and coverage will go down a bit.
To see the full PFC test suite run against a Postgres database, restore the var:
```bash
export TEST_DATABASE_URL=postgres://cfpb@localhost/test_cfgov
tox -e fast paying_for_college
```
All tests should run.
This change won't affect our Travis CI tests, which use Postgres by default.
=> Skip some unit tests when using an SQLite db

cfgov/jinja2/v1/_includes/organisms/carousel.html
The new homepage design includes the word "Featured" above the carousel when viewed at narrow screen widths (mobile). We want this word to translate properly for Spanish versions of the page.
To test, run a local server and visit http://localhost:8000/es/?nhp=True at a mobile width. You should see the translation "Destacado". This comes from [the existing translations for this project](https://github.com/cfpb/cfgov-refresh/blob/aaf5405c55aef08f424f86d4a63b9736f26ccaf7/cfgov/locale/es/LC_MESSAGES/django.po#L78).
Ping @sonnakim.
=> Add Spanish translation for "Featured" on homepage

requirements/libraries.txt
Bumping release version of TDP
- Added Similar Resources block to TDP Activity Detail page
- Removed Age Range from TDP Activity search results
@Scotchester @chosak @willbarton @higs4281
=> [TDP] Bump teachers_digital_platform to version 1.1.9

docs/deployment.md
Fix minor typo in deployment docs.
Current:
Fixed:
=> Fix minor typo in deployment docs

cfgov/jinja2/v1/_includes/molecules/card.html, cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/unprocessed/css/molecules/card.less
They should be medium, not regular.
Addresses https://GHE/CFPB/el-camino/issues/60#issuecomment-232097
1. Pull branch
1. `yarn gulp styles`
1. Reload the homepage (open it in a new tab & toggle between to see the difference more clearly)
=> New Homepage: Fix link font weight in carousel and cards

cfgov/unprocessed/css/organisms/card-group.less
These browsers don't support flexbox and needed some fallback styling.
Fixes https://GHE/CFPB/el-camino/issues/50
- Float-based layout for homepage cards in IE < 10
- Switches to left margin and overriding that on `:first-child` because older IEs don't support `:last-child`
1. Pull branch
1. `yarn gulp styles`
1. Load page in IE 8 or 9 (or their emulation modes)
1. See cards appearing in columns again
- The icons are still missing on IE 8, as are all of our SVG icons.
=> New Homepage: Fix card layout in IE 8 & 9

cfgov/unprocessed/apps/analytics-gtm/js/tab-navigation-tracking.js
We've got an ongoing situation where the following JS error is being thrown frequently:
> Failed to execute `setItem` on 'Storage': Setting the value of `_nav_path` exceeded the quota.
[View the alert in New Relic](https://alerts.newrelic.com/accounts/670562/incidents/98587488/violations)
It seems like someone (or more likely some bot) is trying to hit tons of our pages with limited `sessionStorage` and it's unable to update that value each time a new page is visited.
Based on [a little](https://www.raymondcamden.com/2015/04/14/blowing-up-localstorage-or-what-happens-when-you-exceed-quota) [research](https://michalzalecki.com/why-using-localStorage-directly-is-a-bad-idea/), it seems like wrapping that `setItem` call in a `try`/`catch` might be the best way to handle the error for now. …
=> Attempt to stop sessionStorage quota exceeded errors

cfgov/unprocessed/css/organisms/card-group.less
Also fixes excessive space at the bottom of the WWTHFY box.
Fixes https://GHE/CFPB/el-camino/issues/68
1. Pull branch
1. `yarn gulp styles`
1. Reload
Before | After
------ | -----
=> Homepage cards: Fix left margin regression on small screens

cfgov/v1/handlers/blocks/feedback.py, cfgov/v1/tests/handlers/blocks/test_feedback.py
This change restores a Python 3 test for handling non-ascii referrer values
in v1 feedback. The previous test was trying too hard to manage string types,
and we were skipping the test in Python 3.
The solution was to leave the Python unicode sandwich alone.
With unicode_literals turned on, both Python versions happily pass
unicode to the request object for handling downstream.
This addresses platform issue 3613.
22 unit tests for v1/handler code should succeed in Python 2 and 3, and there
should be no skips.
```bash
tox -e fast v1.tests.handlers.blocks
tox -e unittest-py36-dj111-wag113-fast v1.tests.handlers.blocks
```
=> Unskip Python 3 test for feedback handling

config/webpack-config.js
- Adds missing `mode` configuration to webpack config.
- Move webpack mode ~~and minimization~~ settings to constants.
1. `gulp build` on `master` shows a warning for `mode`.
2. `gulp build` on this branch does not.
3. If you have `export NODE_ENV=development && gulp clean && gulp build` the code should be unminimized. If you `export NODE_ENV=production && gulp clean && gulp build` the code should be minimized.
Fixes this warning
=> Fix webpack mode warning

jest.config.js
I have teachers-digital-platform cloned within my develop-apps folder for Docker-based development. When running `gulp test:unit` from the root of cfgov-refresh, Jest was finding the unit tests inside there and trying to run them, causing failures related to bad paths.
- `testPathIgnorePatterns` added to `jest.config.js` with the default rule of `node_modules` and the new addition of `develop-apps`
1. To reproduce the problem:
1. Clone teachers-digital-platform into `develop-apps/`
1. In the TDP folder, `./setup.sh` to install all of its stuff
1. Back in the root of cfgov-refresh, `yarn gulp test:unit`
1. Observe the failures coming from under `develop-apps/teachers-digital-platform/`
1. Pull down this branch
1. Run `yarn gulp test:unit`
1. See no failures
=> Prevent running unit tests on things in develop-apps

cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_includes/organisms/mega-menu-var-1.html, cfgov/jinja2/v1/_includes/organisms/mega-menu-var-2.html
- Adds `MEGA_MENU_VAR_1` and `MEGA_MENU_VAR_2` flags for viewing mega menu variations.
1. Add and enable `MEGA_MENU_VAR_1` flag and reload local homepage to view variation 1 menu.
2. Disable `MEGA_MENU_VAR_1` flag and enable `MEGA_MENU_VAR_2` flag and reload local homepage to view variation 2 menu.
=> Mega menu: Add flags for viewing variations

cfgov/jinja2/v1/ask-cfpb/answer-search-results.html
The search-by-tag Ask CFPB page has been subtly broken since the last code refactoring, hiding parts of the search results. This change restores the full intended results list.
The URLs for search-by-tag have not been actively used, but were preserved to maintain legacy links to them. Two new links are being added (see internal issue 3646 for more context).
- In [production](https://www.consumerfinance.gov/ask-cfpb/search-by-tag/money-as-you-grow/), result snippets silently fail to render:
- If you render the page [locally](http://localhost:8000/ask-cfpb/search-by-tag/money-as-you-grow/), with DEBUG=True, the error can be seen:
- And with the fix, the snippets render as intended:
=> Restore answer snippets to search-by-tag pages

cfgov/unprocessed/css/molecules/global-banner.less
🚧Holding until after the code freeze ends on January 3. 🚧
The current beta banner's background color is set to `@gold-20`, but the background color of warning notifications is now `@gold-10`, which is causing a multi-colored beta banner. This change matches the beta banner background to the standard notification background.
- Change beta banner background from `@gold-20` to `@gold-10`
1. Enable the beta banner locally by going to http://localhost:8000/admin/flags/BETA_NOTICE/ and hitting the "enable BETA_NOTICE for all requests" button.
2. Visit any local page, like http://localhost:8000/, and notice the multi-colored beta banner.
3. In this branch, run `./frontend.sh`
4. Reload the local page you're looking at, and notice the beta banner should now be the same color
Before | After
---- | …
=> Fix beta banner background color

cfgov/unprocessed/apps/regulations3k/js/permalinks-utils.js, test/unit_tests/apps/regulations3k/js/permalinks-utils-spec.js
Certain paragraphs in iRegs have odd `data-label` values, e.g., the first five paragraphs on 
https://www.consumerfinance.gov/policy-compliance/rulemaking/regulations/1002/Interp-9/. This commit puts certain statements containing methods that were assuming other formats for that attribute inside conditionals to prevent those methods from erroring on the unexpected input.
/cc @contolini, @cfarm 
1. Visit https://www.consumerfinance.gov/policy-compliance/rulemaking/regulations/1002/Interp-9/
1. Open the dev tools console and start scrolling down
1. Observe errors popping in, e.g., `Uncaught TypeError: Cannot read property 'split' of undefined`
1. Pull this branch
1. `yarn run gulp scripts:apps`
1. Visit http://localhost:8000/policy-compliance/rulemaking/regulations/1002/Interp-9/
1. Open …
=> Fix iRegs wayfinder JS errors on odd paragraphs

cfgov/v1/tests/models/test_resources.py, cfgov/v1/tests/models/test_snippets.py, cfgov/v1/tests/templatetags/test_app_urls.py
Since are transitioning to Python 3 and stopping support of Python 2, update the specs to remove any tests that are skipped in Python 3.
🚧  Do not merge until after January 3. 🚧 
- Remove Python 2-specific tests for Resources and Snippets.
- Update templatetags tests to test Python 3 functionality instead of Python 2.
1. `tox`
- I believe this addresses all tests that were being skipped in Python 3.
=> Remove or update Python3-incompatible tests

cfgov/cfgov/settings/base.py
Data team was unable to view the Mouseflow Live Heatmaps feature because it was blocked by our CSP. Add that domain to the whitelist, as requested by the Mouseflow support contact.
- add `us.mouseflow.com` to the CSP whitelist
- There are several different CSP whitelists. Let's confirm that I've added the domain to the correct list.
=> Whitelist a mouseflow domain to allow the Live Heatmaps feature to load

cfgov/jinja2/v1/ask-cfpb/answer-search-results.html, cfgov/unprocessed/js/routes/ask-cfpb/single.js, cfgov/unprocessed/js/routes/on-demand/ask-analytics.js
This adds code to help our Analytics team track search requests for Ask CFPB which have no results.
- Add ask-analytics.js, which adds an event to the Google Tag Manager dataLayer object when it finds an element with a specific data attribute. (Data attributes are preferable to classes for Google analytics functions.)
- Add 'data-gtm_ask-no-results' data attribute to the "No results" element so that the analytics JavaScript can identify "No results" content.
1. When you load an Ask CFPB with null results, you can open the JS console and check the contents of the `window.dataLayer` Array. You should see an Object in that Array, with properties like: `{event: "Complaint Search", action: "noSearchResults", ...}`. The `label` property of that Object should be the search term which resulted in …
=> Ask CFPB: Track null results in Analytics

cfgov/unprocessed/root/robots.txt
Our English and Spanish search pages occasionally get hammered by bots
entering nonsense searches. This doesn't help anyone, so let's disallow it.
It's OK that the base search pages will be disallowed as well, because
they aren't used as stand-alone pages without a search parameter.
In fact, the search-by-tag pages return 404 if there is no parameter.
The four pages added:
- /ask-cfpb/search/
- /ask-cfpb/search-by-tag/
- /es/obtener-respuestas/buscar/
- /es/obtener-respuestas/buscar-por-etiqueta/
=> Disallow robots from Ask CFPB search pages

.travis.yml, tox.ini
This change removes Python 2.7 from our Tox environments and from our Travis tests.
Note: https://github.com/cfpb/cfgov-refresh/pull/5439 removes the Tox environments from the unit testing documentation.
=> Remove Python 2.7 from Tox and Travis

cfgov/cfgov/settings/local.py, docs/running-virtualenv.md
This change will cause an exception to be raised if the local settings are loaded with Python 2. This is intended to prevent local development from continuing with Python 2.
This change also adds documentation on how to remove and reinstall a local virtualenv-based installation of cfgov-refresh.
=> Raise an exception when running in Python 2

cfgov/apache/conf.d/wsgi.conf
This change sets the lang and locale explicitly to en_US.UTF-8 on the WSGI daemon process. This ensures that Django uses a UTF-8 locale.
This is intended to fix `UnicodeEncodeErrors` we're seeing with URLs with unicode characters in them that result in tracebacks ending like this:
```
File "/srv/cfgov/versions/20200109110904/cfgov/jinja2/v1/_layouts/base.html", line 317, in template
{% include 'js/routes/' + app_page_url(request) + 'index.js' ignore missing %}
File "/srv/cfgov/versions/20200109110904/cfgov/v1/jinja2_environment.py", line 52, in join_path
if os.path.exists(filesystem_path):
File "/srv/cfgov/current/venv/lib64/python3.6/genericpath.py", line 19, in exists
os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 65: ordinal not in range(128) …
```
=> Set the WSGI locale explicitly

cfgov/housing_counselor/generator.py
This is a quick fix for HTML generation from HUD JSON. Previously, to ensure we were writing out UTF-8 HTML, we would encode the result from the Django template's `render()` method as UTF-8. This is not necessary in Python 3, as the returned HTML is UTF-8 encoded already.
Prior to this change attempting to generate the HTML (in our Jenkins jobs as well as locally) would result in:
```
$ ./cfgov/manage.py hud_generate_html ./jsons ./htmls
Found 41140 input files
Traceback (most recent call last):
File "./cfgov/manage.py", line 11, in <module>
execute_from_command_line(sys.argv)
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
utility.execute()
File …
```
=> Fix HUD HTML generation in Python 3

cfgov/ask_cfpb/scripts/export_ask_data.py
This change fixes the Ask CFPB data export that was broken in Python 3 because of a difference in the way the `filter()` function works.
`filter()` in Python 2 returns a list, and so could be called with list indices. `filter()` in Python 3 returns an iterable `filter` object that cannot be treated like a list.
Since we want to first object resulting from the filter, the fix is a single call to `next()` in place of `[0]`.
1. Visit http://localhost:8000/admin/export-ask on `master` and try to export data. You'll see an error with a traceback that ends with:
```
answer = answer_schema[0].get('value').get('description')
TypeError: 'filter' object is not subscriptable
```
2. Checkout this branch and try again. You should successfully get a CSV export of Ask data.
=> Fix Ask CFPB data export in Python 3

requirements/libraries.txt
New releases all remove python 2 compatibility and only provide python 3 compatibility
- Update to the latest release of all consumerfinance.gov satellite apps.
=> Update all satellite apps to remove python 2 compatibility

cfgov/jinja2/v1/_includes/organisms/header.html
- Shortens beta banner text to one line.
1. Pull branch, enable BETA_NOTICE flag, check site to see new banner.
=> Shorten beta banner text

cfgov/jinja2/v1/_includes/organisms/mega-menu-var-1.html
- Add hardcoded external link icon to variation 1 menu.
1. Enable `MEGA_MENU_VAR_1` flag and visit homepage and go to the second tab.
=> Mega menu: Add hardcoded external link icon to variation 1

cfgov/cfgov/test.py, cfgov/data_research/mortgage_utilities/s3_utils.py, cfgov/data_research/scripts/export_public_csvs.py, cfgov/data_research/tests/management/commands/test_conference_delete.py, cfgov/data_research/tests/management/commands/test_conference_notify.py, cfgov/data_research/tests/test_s3_utils.py, cfgov/data_research/tests/test_scripts.py, cfgov/jobmanager/tests/models/test_pages.py, cfgov/prepaid_agreements/jinja2tags.py, cfgov/prepaid_agreements/views.py, cfgov/v1/admin_forms.py, cfgov/v1/atomic_elements/organisms.py, cfgov/v1/models/home_page.py, cfgov/v1/models/images.py, cfgov/v1/tests/management/commands/test_export_feedback.py, cfgov/v1/util/datetimes.py, requirements/docs.txt, requirements/libraries.txt
Remove Python 2 code relating to six library
- from six import
- basestr -> str
- Use from io import StringIO
$ tox
...
unittest-py36-dj111-wag113-slow runtests: commands[2] | coverage run --source=. manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...
Ran 1511 tests in 74.149s
OK (skipped=9)
Destroying test database for alias 'default'...
______________________________________________________ summary _______________________________________________________
lint-py36: commands succeeded
unittest-py36-dj111-wag113-slow: commands succeeded
congratulations :)
=> Remove Python 2 code from six import

cfgov/unprocessed/css/molecules/nav-link.less
- Breaks secondary nav items when word is too long and gets truncated.
1. Open a Browse Page like https://www.consumerfinance.gov/policy-compliance/guidance/supervision-examinations/ in Chrome.
2. Open Settings (Chrome > Preferences…)
3. Search for "appearance"
4. Change font size to a larger size or go into Customize fonts and move the Font size slider to the right until it indicates under “Standard font” that the base size is 32 (200% of the default of 16)
5. Return to the page and observe the sidenav
Before:
After:
=> Break words in secondary nav when text is too long

cfgov/unprocessed/js/modules/footer-button.js, test/unit_tests/js/modules/footer-button-spec.js
- Set focus on header element when return to top button is clicked.
1. Pull branch, run `gulp clean && gulp build`
2. Resize window to mobile size.
3. Scroll to bottom of the page and click "Back to top" button.
4. Press tab to see that the focus is in the header, not the footer (compare to behavior on production).
- ~Ideally the focus should be BEFORE the skip link, so that the first click of the tab key ends up on the skip link. However, to move the focus from the footer, we need to move focus to another focusable element. The skip link is the first of these on the page. We don't want the skip link to show (I don't think?) when returning to the top as the user has not yet hit the tab key, so we set it to the skip link and then blur the `activeElement`. The consequence of this is that …
=> Move focus to header on return to top button

cfgov/jinja2/v1/_includes/organisms/mega-menu-var-1.html, cfgov/unprocessed/css/organisms/mega-menu-var-1.less, cfgov/unprocessed/css/organisms/mega-menu-var-2.less
- Fix top padding above the overview link, so that the hover has correct height.
- Change order brochure link icon to be a document instead of a complaint.
- Hide redundant menu item group header.
1. Pull branch and `gulp clean && gulp build`
2. Enable `MEGA_MENU_VAR_1` flag.
3. Visit homepage and resize desktop to view extra large and regular desktop sizes and see that hover for overview link is equal height on the top and bottom. Also see that second column in menu item groups has a hidden heading. Also see that the Order Brochures icon has changed to a document.
=> Mega Menu: Fix top padding. Fix brochure icon. Hide menu column header.

cfgov/jobmanager/models/django.py, cfgov/jobmanager/tests/models/test_pages.py
This is a fix for job listings that have multiple USAJobs links in them. With Python 3's stricter comparisons, attempting to order the `USAJobsApplicationLink` objects using `applicant_type` was failing with `ApplicantType` not supporting `<` operations.
This fix adds `__gt__` and `__lt__` to `ApplicantType` to support `>` and `<` operations.
Generally this appears to come from django-modelcluster and behavior that differs from the Django expectation, possibly related to https://github.com/wagtail/django-modelcluster/issues/45.
1. Create or edit a job listing to have multiple USAJobs application links
2. Try to preview the page and notice a 500
3. Checkout this branch
4. Preview the job listing again and notice it works as expected
=> Fix job listings with multiple USAJobs links

cfgov/prepaid_agreements/views.py
The prepaid index view expects that query params will be in `dict` form (so that params can be `pop`ed). This change restores that.
=> Fix prepaid search by wrapping query in a dict

cfgov/ask_cfpb/tests/test_views.py, cfgov/ask_cfpb/views.py
Our [Ask CFPB search redirect view](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/ask_cfpb/views.py#L145)
was tasked with handling many legacy knowledgebase combinations, but one was left out: a search with no query string.
We don't normally send users to the bare search page, but rather send requests there, with a query string, from search boxes on the Ask landing page and on all answer pages.
But the bare search page exists and is functional, and we get requests for it, so this change routes those requests to /ask-cfpb/serach/, even if it has no query string, or a blank one like `/?q=`
The legacy bare search URL should return 404 without a query string: <http://localhost:8000/askcfpb/search/>
After loading this branch, the legacy request above (and a legacy request with a …
=> Redirect bare calls to /askcfpb/search/

cfgov/housing_counselor/jinja2/housing_counselor/index.html
- Moves housing counselor links with accompanying icon to one line so that space between icon and text is not included in the link underline.
1. Pull branch and compare links with icons between http://localhost:8000/find-a-housing-counselor/?zipcode=20002 and https://www.consumerfinance.gov/find-a-housing-counselor/?zipcode=20002 
Examples:
Before:
After:
Before:
After:
=> Adjust housing counselor links to remove extended underline

cfgov/jinja2/v1/rural-or-underserved/index.html
Sibling PR to https://github.com/cfpb/cfgov-refresh/pull/5464
- Adjusts rural and underserved links with accompanying icon to one line so that space between icon and text is not included in the link underline.
- Removes nonbreaking space from the end of link.
1. Pull branch and compare http://localhost:8000/rural-or-underserved-tool/ to https://www.consumerfinance.gov/rural-or-underserved-tool/ (you'll need to load addresses to see the download link)
Before:
After:
Before:
After:
=> Adjust rural and underserved links to remove space between text and icon

cfgov/v1/models/home_page.py
#5452 improperly removed the metaclass for the HomePageForm class as part of Python 2 cleanup. This broke the ability to edit HomePage model instances in the Wagtail editor. This commit corrects that.
Note [this specific change](https://github.com/cfpb/cfgov-refresh/pull/5452/files#diff-3af357132db430d649cd7e73b69b113fL38). Previously this code was using [`six.with_metaclass`](https://six.readthedocs.io/#six.with_metaclass) to define a metaclass; the PR incorrectly made the metaclass one of the base classes.
Try to edit the site homepage at http://localhost:8000/admin/pages/319/edit/; this causes a TypeError on master but works properly on this branch.
=> Restore metaclass for HomePageForm class

cfgov/ask_cfpb/tests/test_views.py, cfgov/ask_cfpb/views.py, cfgov/cfgov/urls.py
Some of our broken internal links originate as knowledgebase-era
querystring-based category searches, which we routed to category pages
in 2016. But Some links request uppercase category names with spaces, and
the redirects break down.
This change slugifies the requested category so that the redirects can complete.
Two legacy URLs that currently return 404:
- [http://localhost:8000/askcfpb/search/?selected_facets=category_exact:Prepaid Cards](http://localhost:8000/askcfpb/search/?selected_facets=category_exact:Prepaid%20Cards)
- [http://localhost:8000/askcfpb/search/?selected_facets=category_exact:Student Loans](http://localhost:8000/askcfpb/search/?selected_facets=category_exact:Student%20Loans)
After pulling in this branch, the URLs above should relevant to portal pages under …
=> Redirect legacy Ask URLs with uppercase categories

docker/deployable-zipfile/_build.sh
The changes in #5434 removed Python 2 from the Docker process to build a deployable zipfile, documented at http://cfpb.github.io/cfgov-refresh/deployment/#generating-a-deployment-artifact.
However, that change neglected to remove the parameter that made the build script run with two versions of Python (now both Python 3), leaving behind an unnecessary step.
This change removes that extra parameter. The build still successfully builds artifacts with Python 3 support. To test, run `./docker/deployable-zipfile/build.sh`.
See internal Jenkins PR 562 for a similar change there.
This process isn't used in the production build, but is a way of locally generating deploy artifacts.
=> Remove unneeded parameter from Docker-based build

tox.ini
Add support in tox.ini for unit testing with Wagtail 2.3 and Wagtail 2.7
Remove support in tox.ini for unit testing with Wagtail 2.0
Update Django from 2.0 to 2.2 in tox.ini
- wag23
- wag27
- dj22
- wag20
- dj20
1. tox -e unittest-py36-dj111-wag23-slow
2. tox -e unittest-py36-dj111-wag27-slow
3. tox -e unittest-py36-dj22-wag23-slow
4. tox -e unittest-py36-dj22-wag27-slow
Unit Tests are expected to fail, but will not cause Travis builds to fail
Tests will fail as code does not currently support Wagtail 2.x
=> Add Wagtail 2.3, Wagtail 2.7, and Django 2.2 in tox.ini

requirements/libraries.txt
Various CR Tool updates: https://github.com/cfpb/teachers-digital-platform/releases/tag/1.2.1
@Scotchester
=> [TDP] Bump TDP to version 1.2.1

cfgov/core/tests/test_middleware.py, cfgov/core/utils.py
Our link markup logic adds download and external link icons to links, but it doesn't work right for links that already contain SVGs, like these:
```html
<a class="a-link a-link__icon" href="[external link]"
<span><svg ... ></span>
<span class="a-link_text">some text</span>
</a>
```
We want the logic to do this:
```html
<a class="a-link a-link__icon" href="[external link]">
<span><svg ... ></span>
<span class="a-link_text">some text <svg ...></span>
</a>
```
But currently links like these get skipped because they already contain an SVG. On the other hand, we don't want to markup links that already end with an SVG.
This commit fixes the logic so that links containing SVGs get marked up as long as they don't end with an SVG.
=> Fix link markup for links containing SVGs

cfgov/jinja2/v1/_includes/organisms/mega-menu-var-1.html, cfgov/unprocessed/css/organisms/mega-menu-var-1.less
Currently proposed mega menu variation 1 always shows the caret even if the menu has no child items, as would happen with the Spanish menu.
This change hides the up/down carets if no children exist.
This can't be tested on the Spanish menu without using #5471, but can be tested in English by deleting all contents from one of the submenus.
First, enable the proposed menu variation 1:
1. Go to http://localhost:8000/admin/flags/create/ and create a feature flag named `MEGA_MENU_VAR_1`.
1. Enable it at http://localhost:8000/admin/flags/MEGA_MENU_VAR_1/ by clicking "ENABLE MEGA_MENU_VAR_1 FOR ALL REQUESTS".
1. Visiting a page on the site like http://localhost:8000/ should show the proposed variation 1, including down and up carets when menus are opened.
Now, delete all content from one of the …
=> Mega menu variation 1: hide caret if no items

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_includes/organisms/omwi-salesforce-outage-banner.html, cfgov/v1/jinja2tags/__init__.py, cfgov/v1/templatetags/banners.py, cfgov/v1/tests/templatetags/test_banners.py
As with several other of our Salesforce things, OMWI would like to have the option to turn on a notification banner if their form/community is down. This commit adds that, toggleable with the new `OMWI_SALESFORCE_OUTAGE` flag.
Addresses GHE/CFGOV/platform/issues/3649
- OMWI outage banner behind `OMWI_SALESFORCE_OUTAGE` flag, which gets applied to the exact paths `/about-us/diversity-and-inclusion/` and `/about-us/diversity-and-inclusion/self-assessment-financial-institutions/`
- Adds the `$` control character to the end of @wpears's just-added `COLLECT_OUTAGE` banner path arguments (#5469), after I noticed that it wasn't there and he agreed that it should be.
1. Pull branch
1. Visit http://localhost:8000/about-us/diversity-and-inclusion/ and see no banner
1. Enable the …
=> Add flagged banner for OMWI Salesforce stuff outages

tox.ini
Add support for latest version of Wagtail 2.8 for tox
- Wagtail 2.8
- Wagtail 2.7
- Add Python 3.8 (py38)
1. tox
=> Change Wagtail 2.7 to 2.8 in tox.ini

cfgov/jinja2/v1/_includes/organisms/post-preview.html
Post previews for posts with multiple authors [currently have extra spacing](https://www.consumerfinance.gov/about-us/blog/) around the commas. In addition, per the CFPB Voice and Style Guide (internal wiki page), we should be using the Oxford comma here.
This change fixes post preview author display so it works like this:
One author: By Daisy Duck
Two authors: By Daisy Duck and Donald Duck
Three or more authors: By Daisy Duck, Donald Duck, and Mickey Mouse
With a recent production dump, going through the pages on http://localhost:8000/about-us/blog/ should show some examples of all of these.
Current production site:
This fix:
=> Fix spacing and commas for multi-author post previews

cfgov/jinja2/v1/ask-cfpb/see-all.html, cfgov/unprocessed/css/pages/ask.less
Using [DefinedTerm](http://schema.org/DefinedTerm) and [DefinedTermSet](http://schema.org/DefinedTermSet) schema markup should improve the performance and display of our content in search results.
Addresses https://GHE/CFGOV/platform/issues/3644
- Updates template that outputs Key Terms on portal pages to use `dl` markup with `DefinedTerm` schema attributes
1. Visit http://localhost:8000/consumer-tools/auto-loans/answers/key-terms/ and inspect the markup for a term
2. Compare with https://www.consumerfinance.gov/consumer-tools/auto-loans/answers/key-terms/ – there should be no visible difference
- There's a small text formatting bug in IE that will be fixed when cfpb/design-system#422 is merged and pulled into cfgov-refresh.
- ~~Get third party confirmation that these are the correct …
=> Mark up Key Terms lists with DefinedTerm schema

cfgov/jinja2/v1/_includes/organisms/item-introduction.html
The change in #5489 incorrectly updated the author link URL; this fixes that.
To test, visit a blog page URL like:
http://localhost:8000/about-us/blog/small-business-lending-and-great-recession/
=> Fix: use proper URL for blog post author links

requirements/libraries.txt
Released a new tagged version of `ccdb5-api` and updated the tagged version in `libraries.txt`
- Use version 1.2.2 of ccdb5-api
=> Update ccdb5-api version to 1.2.2

codecov.yml
Per [https://docs.codecov.io/docs/pull-request-comments#section-disable-comment](the documentation), Codecov might be commenting because we're using `comment: off` instead of `comment: false`.
This is an attempt to fix that.
=> Disable Codecov comments

cfgov/jinja2/v1/_includes/molecules/global-header-cta.html, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_includes/organisms/mega-menu-var-1.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html
Pass the page's language to the global header macro to link Spanish-speaking users to the Spanish version of "Submit a complaint".
- `language` parameter and conditional statement added to global header macro.
2. Go to http://0.0.0.0:8000/es/ and see if "Enviar una queja" in the header links to the correct page.
=> Dynamically change language of "complaint" link

cfgov/jinja2/v1/_includes/molecules/info-unit-2.html, cfgov/unprocessed/css/molecules/info-unit.less
Fixes lack of focus state for info unit images and groups their images and headings so there's only one link in
- Wraps info unit image and heading text in a single anchor tag.
- Removes image alt text if heading text is provided to prevent redundant screen reading.
- Only renders heading if text is provided (to prevent empty `h2`s).
1. Pull down branch
1. Visit pages with 50/50 and 25/75 info unit groups like the ones listed in the [original issue](GHE/CFGOV/platform/issues/2936).
From https://www.consumerfinance.gov/practitioner-resources/your-money-your-goals/booklets-talk-about-money/
|------|------|
| ![before](https://user-images.githubusercontent.com/1060248/74113933-3de69580-4b75-11ea-80e0-20cbca059c86.gif)  | …
=> Info unit group accessibility improvements

cfgov/jinja2/v1/_includes/molecules/card.html, cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/unprocessed/css/molecules/card.less, cfgov/unprocessed/css/organisms/carousel.less
- Make cards on homepage fully clickable at mobile size.
1. Pull branch and build. Visit homepage and resize the page to see the behavior of the cards at desktop and mobile.
2. Use the tab key to tab through content and see where the focus falls on the cards.
Mobile card with focus rectangle:
=> Homepage: Make cards fully clickable at mobile size

cfgov/unprocessed/js/organisms/MegaMenuDesktopVar1.js
Click to close body click listener was not being removed so was throwing an error when the menu was closed. This PR fixes that.
- Remove body click listener when a menu is closed.
1. Pull branch and `gulp clean && gulp build`
2. Turn on `MEGA_MENU_VAR_1` flag if it is not on.
3. Open the menu and click elsewhere on the page to close it.
4. Click again elsewhere. There should NOT be an error in the dev console.
=> Mega menu: Clean up body click listener

gulp/tasks/copy.js
This appeared to be unused.
- Removes prepaid icons gulp task
=> Removes prepaid icons gulp task

cfgov/unprocessed/css/organisms/carousel.less
Removes the intermediary 50/50 carousel layout that occurred betwixt 600px and 900px. It now jumps straight to mobile layout at 900px.
2. `gulp build`
3. Verify the carousel items stack at 900px.
|------|------|
| ![carousel2](https://user-images.githubusercontent.com/1060248/74364033-bfb70880-4d99-11ea-9dd8-8c19741d4b35.gif)  | ![carousel](https://user-images.githubusercontent.com/1060248/74363911-8c747980-4d99-11ea-869d-46bf688d23cf.gif)  |
- GHE/CFPB/el-camino/issues/119
=> Stack homepage carousel items at 900px instead of 600px

cfgov/jinja2/v1/_includes/organisms/mega-menu-var-1.html, cfgov/unprocessed/css/organisms/mega-menu-var-1.less, cfgov/unprocessed/js/organisms/MegaMenuVar1.js
- Revert mobile menu in variation 1 mega menu to that on production.
1. Pull branch and build `gulp clean && gulp build`
2. Run site and go to mobile menu and see that you can click into the levels.
=> Revert mobile menu in variation 1 mega menu

cfgov/legacy/templates/students/knowbeforeyouowe/index.html
- Fixes incorrect AWS bucket URL
1. Fixes link URL on https://www.consumerfinance.gov/practitioner-resources/students/knowbeforeyouowe/ page.
=> Fix URL to disclosure PDF

cfgov/unprocessed/css/organisms/mega-menu-var-1.less
When hovering, the focus state rectangle was too short. This fixes that by moving the hover from a box-shadow to an absolutely positioned `:after` selector.
- Changes `box-shadow` hover to an `:after` hover.
- Adjusts height of featured link area to better match specs.
2. Test var 1 menu.
3. When clicking a menu item, the focus rectangle should be offset outside 2px around all edges. Hover should work across states of hover, active, and focus and combinations of each.
=> Mega menu: Fix focus state

requirements/libraries.txt, tox.ini
This PR adds the 1.2.2 release of TDP to cfgov-refresh so that the tests can pass against Wagtail 2.3.
It also bumps the versions of our custom Wagtail libraries to ones that are unittested with Wagtail 2.3.
Finally, it adds Wagtail 2.3 to the default `tox` environment list so that when we run `tox` and when `tox` runs in Travis test will be required to pass in Wagtail 2.3.
=> Bump TDP and Wagtail libraries and test against Wagtail 2.3

cfgov/jinja2/v1/_includes/organisms/footer.html
Adds a new link to `/data` in cf.gov's footer and rearranges the order of
the links.
See GHE/CFPB/el-camino/issues/127
=> Rearrange footer links

requirements/libraries.txt
Bumping the TDP app to version 1.2.3
- Added a modal confirmation to the Remove Efficacy Study Link in the CR Tool
- https://github.com/cfpb/teachers-digital-platform/compare/1.2.2...1.2.3
- @Scotchester
=> [TDP] Bump version to 1.2.3

cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_layouts/base.html, cfgov/mega_menu/jinja2tags.py, cfgov/mega_menu/models.py, cfgov/mega_menu/tests/test_jinja2tags.py, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/js/organisms/Header.js
If no mega menus have been defined in Wagtail, the new mega menu implementation (introduced in #5471 via the `MEGA_MENU_BACKEND_V2` feature flag, and now turned on in production) will raise an exception. This is problematic because it prevents us from running Python tests with defining some placeholder menu, and prevents use of cfgov-refresh on an empty database without defining a menu.
To better handle these cases, it would be better if we could instead just fallback to showing no menu if none are defined. Additionally, this opens up the possibility of deliberately hiding the menu on certain pages in an organized way, as opposed to via custom base templates.
This change makes that possible, and makes the necessary frontend code changes to handle the case where the menu is not displayed. …
=> Better handle header layout with no mega menu

requirements/libraries.txt
TDP 1.2.4 restores Wagtail 1.13 as supported in setup.py. This will fix warnings about installing it with Wagtail 1.13.
=> Update TDP to 1.2.4

cfgov/v1/management/commands/update_data_snapshot_values.py
The management command `update_data_snapshot_values` is failing because
it now encounters a BrowsePage that has no content.streamfield content.
This change skips a page if it has no such content.
- Store a local copy of this json file: https://github.com/cfpb/consumer-credit-trends-data/blob/master/data_snapshot.json in your develop-apps/ directory.
- Change the dates in the json file to 2020
- Check the current state of the Credit Cards browse page locally: http://localhost:8000/data-research/consumer-credit-trends/credit-cards/
- run the management command: `./cfgov/manage.py update_data_snapshot_values --snapshot_file develop-apps/data_snapshot.json`
- Note that four pages get changed and published, then check the local credit card page again to see that dates have changed to 2020.
=> Fix data-snapshot parsing of BrowsePage data

cfgov/unprocessed/css/molecules/nav-link.less
Our side nav links are blue on large screens but gray on mobile. We no longer want this to be the case. This PR makes them black/blue on all screen sizes.
See: GHE/CFGOV/platform/issues/3691
- Mixin within media query.
1. Go to http://0.0.0.0:8000/about-us/the-bureau/about-director/
1. Resize your screen and click "In this section" to see blue links.
| Desktop | Mobile |
|---|------|
| <img width="614" alt="Screen Shot 2020-02-27 at 12 33 47 PM" src="https://user-images.githubusercontent.com/1060248/75469856-b3b47480-595d-11ea-8eea-7a241af9ec9d.png"> | <img width="372" alt="Screen Shot 2020-02-27 at 12 34 01 PM" src="https://user-images.githubusercontent.com/1060248/75469864-b7e09200-595d-11ea-86a0-7cb86d1a8c94.png"> |
=> Remove disparity between mobile/desktop side nav colors

cfgov/jinja2/v1/_includes/organisms/carousel.html, cfgov/unprocessed/css/organisms/carousel.less
It's unclear to screen readers that the carousel is a set of featured items. Grouping them under a visually hidden heading and improving the hierarchy helps distinguish it.
https://www.w3.org/WAI/tutorials/carousels/structure/
- Changes `h5` above carousel to an `h2` and makes its visually hidden but available to screen readers.
- Changes `Featured` heading to read `Featured content`.
1. Load homepage.
1. Everything should visually look the same as https://www.consumerfinance.gov/ except small screens should now read `Featured content` above the featured content.
- Not sure if "Featured content" is the correct language. "Featured items", "Showcase items", etc. might be more appropriate.
=> Improve homepage carousel hierarchy

cfgov/ask_cfpb/wagtail_hooks.py
This PR removes two Hallo.js plugins: the ask-tips Hallo plugin (which isn't being used anymore as of #4982 and #5024) and the edit-html (which was removed for users in #5055).
=> Remove unused Hallo.js plugins

cfgov/agreements/jinja2/agreements/index.html
We have some Django middleware that adds necessary decorations to links (wraps them in a span and adds the download icon if it is a PDF link)
This is better than hardcoding the decorations everywhere.
=> Let middleware decorate links

requirements/libraries.txt, requirements/wagtail.txt
This PR pins our version of Wagtail to version 2.3.
Docker users will need to [update their Python containers](https://cfpb.github.io/cfgov-refresh/running-docker/#update-python-dependencies).
Virtual environment users will need [update their dependencies](https://cfpb.github.io/cfgov-refresh/running-virtualenv/#updating-all-dependencies).
=> Update Wagtail to 2.3

requirements/libraries.txt, tox.ini
Now that we're on Wagtail 2, we don't need to pin django-modelcluster to version 4+. This pin was only needed when we were still on Wagtail 1.13.
This removes one of the inconsistent packages that was preventing the restoration of tox extensions; however there are now two other ones that need to be resolved.
This requirement relates to the use of InlinePanel in Wagtail. A good way to test compatibility is to confirm that page categories still work as expected, for example by viewing and editing categories on a blog post like [this](http://localhost:8000/admin/pages/1492/edit/).
As of Wagtail 2 we now see these two other warnings:
> ERROR: wagtail 2.3 has requirement django-treebeard<5.0,>=4.2.0, but you'll have django-treebeard 3.0 which is incompatible.
> ERROR: wagtail 2.3 has …
=> Remove pinned django-modelcluster requirement

cfgov/jinja2/v1/_includes/organisms/mega-menu.html
#5564 introduced a bug where an overview link would be added even if there was no overview page for a submenu. This fixes that.
@contolini
=> Mega menu: Don't show broken overview links

tox.ini
Remove the ability to run unit tests with Wagtail 1.13
- None
- `wag113: wagtail>=1.13,<1.14`
- replaced `wag113` with `wag23`
- replaced `wag{113,23}` with `wag{23}`
1. tox
=> Removal of Wagtail 1.13 from tox.ini

cfgov/paying_for_college/models/disclosures.py
The disclosures model tries to format a byte string in a message. This makes the message unicode on both sides.
=> Fix byte comparison mismatch in PFC disclosures model

cfgov/jinja2/v1/_includes/organisms/mega-menu.html, test/unit_tests/js/organisms/MegaMenu-spec.js, test/unit_tests/js/organisms/MegaMenuMobile-spec.js
Unused `o-mega-menu_content-grid__three-col` class, which is no longer needed as there will always be four columns.
- Unused `o-mega-menu_content-grid__three-col` class.
- Unneeded `m-list` classes.
- Remove `additional_suffix` argument from `_classes` helper.
- Adds missing `o-mega-menu_content-item` class to menu `li` items.
1. Pull branch and build
2. Compare to production. The only difference should be that the featured items at mobile get separator lines:
Before:
After:
=> Mega Menu: Remove unused classes and add missing ones

cfgov/agreements/tests/test_legacy.py
Fix test that called `str` on a bytes object
The remaining warnings come from our elasticsearch library, which is ancient.  
Unfortunately, upgrading elasticsearch to the latest doesn't fix it.
=> Fix test that called 'str' on a bytes object

.travis.yml, cfgov/cfgov/settings/test_acceptance.py, cfgov/cfgov/settings/test_nomigrations.py, cfgov/cfgov/test.py, cfgov/core/tests/test_utils.py, cfgov/core/utils.py, docs/python-unit-tests.md, requirements/local.txt, requirements/test.txt, requirements/travis.txt, tox.ini
This is a proposal to replace our version-specific factors for tox environments with a simpler `current` and `future` nomenclature.
This means to run the unittests on the current production version of Python, Django, and Wagtail, one would use:
```
tox -e unittest-current
```
To run them against upcoming versions of Python, Django, and Wagtail:
```
tox -e unittest-future
```
I've also added a convenience `tox -e unittest` (🎩 @higs4281) that runs identically to `unittest-current`.
I've removed the `fast` and `slow` factors here and environments here; everything will run "slow," i.e. with migrations. As part of this, I've also removed the `NoMigrations` `MIGRATION_MODULE` and its dependencies. The acceptance test env will now run with full migrations (again, 🎩 @higs4281).
The intent here is …
=> Tests: Replace complex tox dependency factors with "current" and "future" factors

cfgov/agreements/tests/test_legacy.py, cfgov/paying_for_college/models/disclosures.py, tox.ini
Because Django 2.0 [removes support for bytestrings in some places](https://docs.djangoproject.com/en/2.0/releases/2.0/#removed-support-for-bytestrings-in-some-places), this change uses [Python's `-b` switch](https://docs.python.org/3/using/cmdline.html#cmdoption-b) to warn on these comparisons during test runs.
Run `tox`. You'll see warnings like:
```
/Users/bartonw/repos/cfgov-refresh/.tox/unittest-py36-dj111-wag23-fast/lib/python3.6/site-packages/elasticsearch/client/utils.py:47: BytesWarning: Comparison between bytes and string
quote_plus(_escape(p), b',*') for p in parts if p not in SKIP_IN_PATH)
```
=> Tests: warn on byte comparison to strings

cfgov/jinja2/v1/_includes/molecules/card.html
WAVE was showing an error about empty headings for the homepage cards. These cards have heading elements that contain only icons, but are in heading content for consistency with the cards on https://www.consumerfinance.gov/ask-cfpb/ . This PR adds textual content to these headings but visually hides it.
- Add visually hidden heading content to homepage cards.
1. WAVE should show only one error on the homepage, not four.
=> Cards: Add visually hidden heading content to homepage cards

cfgov/scripts/enforcement_transfer.py
Depends on https://github.com/cfpb/cfgov-refresh/pull/5523
- Adds a script that converts all enforcement action pages from DocumentDetail to EnforcementAction page types. The metadata tab should be properly populated, while the content, sidebar, and settings panels should be largely unchanged (saved where fields were moved into the metadata panel in #5523)
1. Get the latest production dump (this is important as corrections have been made to typos/omissions which will, in older dumps, print errors and cause some pages to not transfer).
2. `./cfgov/manage.py runscript enforcement_transfer` many messages will print as new pages are saved.
3. Visit `/admin/pages/1327/` locally and note that all enforcement action sub-pages have been converted to `EnforcementActionPage`s
4. Inspect a few …
=> Introduce enforcement action transfer script

cfgov/jinja2/v1/_includes/molecules/global-eyebrow.html, cfgov/jinja2/v1/_includes/molecules/global-header-cta.html, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/css/molecules/global-eyebrow.less, cfgov/unprocessed/css/molecules/global-header-cta.less, cfgov/unprocessed/css/organisms/mega-menu.less
- Left align all items in the mobile menu, including global CTA.
- Add green hover to mobile menu items.
- Convert global CTA link to a native link in the menu.
- Rename menu `_classes` helper to `_content_classes` as works on `o-mega-menu_content`
- Add `o-mega-menu_content-list-group` container.
2. Visit http://localhost:8000/policy-compliance/ and resize to mobile.
3. Note currently selected item and hover state.
4. Desktop should be unchanged from production.
=> Mega menu: Update mobile hover state

cfgov/jinja2/v1/_includes/organisms/post-preview.html
Currently, in Production on the Enforcement Actions page, each page preview says "Date filed", but shows the published date instead of the actual `date_filed` value. This PR updates the page preview to show the `date_filed` instead.
1. Run this branch with the most recent database dump
2. Visit http://localhost:8000/policy-compliance/enforcement/actions/
3. See that the "Date filed" date on each page preview is actually the date_filed of the page object
4. Compare that to Production (https://www.consumerfinance.gov/policy-compliance/enforcement/actions/), where the page preview has the published date as the "date filed", which is incorrect
- Filterable results are still ordered by `date_published` instead of `date_filed`, which probably isn't what we want. I can work on that in the next …
=> Display date_filed on EnforcementActionPage previews

cfgov/jinja2/v1/_includes/organisms/post-preview.html
Fixes current errors when this field is not present on posts
=> guard reference to date_filed in post preview for enforcement actions

cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/organisms/mega-menu.less
- Add gray-20 hover state to (x) close buttons and "back" button of the mobile menu and global search.
2. Visit localhost and resize to mobile view.
3. hover over (x) close buttons and "back" button.
@huetingj
=> Mega Menu and Global Search: Adds hover states for mobile buttons

cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/unprocessed/css/organisms/mega-menu.less
We had the structure:
```
.o-mega-menu_content-wrapper
.o-mega-menu_content-grid
```
Which just adds padding. So these containers can be combined. One markup change is that the "back" button was a child of the `-wrapper` container and has been moved to be a sibling.
- Removes `o-mega-menu_content-grid` container.
2. Mega menu layout should be unchanged from production at all screen sizes.
=> Mega Menu: Remove `o-mega-menu_content-grid` container

cfgov/jinja2/v1/_includes/organisms/mega-menu.html, cfgov/mega_menu/frontend_conversion.py, cfgov/mega_menu/tests/test_frontend_conversion.py, cfgov/unprocessed/css/organisms/mega-menu.less
This PR improves how mega menu link highlights work depending on the current page being visited. With this change, the top-level menu gets a highlight if you are on either any of its links or any of its links' children (deliberately excluding featured links, which may point to a different menu). Similarly, a specific menu link gets a highlight using the same logic.
These changes only apply to desktop, and do not affect the mobile design.
See below for some specific examples.
@contolini 
First you'll need to rebuild using `gulp clean && gulp build`. The links below can be tested using a recent production dump.
[Homepage](http://localhost:8000/) highlights nothing:
[Overview page](http://localhost:8000/consumer-tools/) highlights that menu, and the overview link:
[Menu link …
=> Improved desktop mega menu link highlighting

cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/ask_cfpb/tests/test_views.py, cfgov/data_research/tests/test_models.py, cfgov/data_research/tests/test_scripts.py, cfgov/data_research/tests/test_views.py, cfgov/hmda/tests/test_pages.py, cfgov/jobmanager/tests/models/test_pages.py, cfgov/jobmanager/tests/models/test_panels.py, cfgov/jobmanager/tests/test_blocks.py, cfgov/regulations3k/tests/test_blocks.py, cfgov/regulations3k/tests/test_copyable_modeladmin.py, cfgov/regulations3k/tests/test_hooks.py, cfgov/regulations3k/tests/test_models.py, cfgov/regulations3k/tests/test_resolver.py, cfgov/regulations3k/tests/test_views.py, cfgov/v1/tests/jinja2tags/test_jinja2tags.py, cfgov/v1/tests/test_email.py, cfgov/v1/tests/test_meta_image.py, cfgov/v1/tests/test_signals.py, cfgov/v1/tests/test_social_sharing_image_validation.py, requirements/test.txt
The model-mommy project was recently [renamed to model-bakery](https://model-bakery.readthedocs.io/en/latest/index.html#model-bakery-smart-fixtures-for-better-tests). Our version was also a little bit out of date. This change uses the new package name and brings it up to date.
=> Replace use of model-mommy with model-bakery

cfgov/unprocessed/css/organisms/mega-menu.less
Adds utilities for creating a hover bar and a focus rectangle for the menu link hover and focus states, which can be fine-tuned independent of each other.
- Adds hover state bar in :before pseudo-element.
- Adds focus state rectangle in :after pseudo-element.
- Adds utilities for desktop and mobile link types different states. 
2. Visting site and interact with menu links across desktop and mobile. 
3. Tab through the menu items and hover at the same time and note appearance.
4. Click an internal page link and note current link appearance, by default and in the hover and focus states.
=> Mega Menu: Add menu state helper utililities

requirements/libraries.txt
This change updates our satellite apps in bulk to versions that have been made Django 1.11 through 2.2-compatible.
This is intended to make #5582 easier to work with.
=> Update satellite apps with Django 2.2 support

cfgov/unprocessed/css/on-demand/header.less
Removes scoping added in https://github.com/cfpb/cfgov-refresh/commit/0a57d03c9d409e7ac93f2ce7929b5f8f3460b6cb for legacy pages. Those page weren't showing the arrows in mobile, e.g. 
- Removes mega menu scoping added in https://github.com/cfpb/cfgov-refresh/commit/0a57d03c9d409e7ac93f2ce7929b5f8f3460b6cb
2. Compare to http://localhost:8000/data-research/consumer-complaints/ to production in mobile.
This makes the hover on the featured item pretty yuck. But possibly this is better than the missing arrows on mobile:
=> Mega Menu: Remove header scoping on legacy pages

cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py
The CFGOVPage.serve_post method expects a certain format for the `form_id` parameter. Certain form_ids could trigger a 500, when they should be handled and instead return 400.
This change is similar to the one in #3143, which in turn related to internal platform#665.
This error can currently be reproduced in production with a URL like this, which requires a valid CSRF token:
> curl -v -X POST -H 'REFERER: https://www.consumerfinance.gov' -H 'X-Requested-With: XMLHttpRequest' --cookie 'csrftoken=CSRFTOKENHERE' -d "form_id=form-content-EVIL&csrfmiddlewaretoken=CSRFTOKENHERE" "https://www.consumerfinance.gov/owning-a-home/process/close/close-deal/"
=> Fix 500 errors due to invalid form_id on POSTs

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html, cfgov/regulations3k/models/django.py, cfgov/regulations3k/models/pages.py, cfgov/regulations3k/tests/test_models.py
Right now, pretty much all iRegs pages have the default cf.gov meta and Open Graph description ("Our vision is a consumer finance marketplace that works for American consumers, responsible providers, and the economy as a whole.") and a title that is just the name of the regulation, even on section/appendix/interp pages. That's been causing alerts in our SEO audits (lots of pages with the same description is bad) and makes search results harder to read.
These changes give every regulation page a title that matches whatever the page's heading is and an informative description that's unique to that page.
See GHE/CFGOV/platform/issues/3723 for more details.
- `{% block title %}`, `{% block desc %}`, and `{% block og_desc %}` to the template that renders regulation pages along with logic in …
=> Give iRegs pages better titles and descriptions

cfgov/unprocessed/apps/ccdb-landing-map/js/TileMap.js, cfgov/unprocessed/apps/ccdb-landing-map/js/landing-map.js
Fixing an ie11 bug.  Object doesn't support .remove()
=> CCDB Landing page: IE11 remove node patch

requirements/libraries.txt
This change bumps the version of wagtail-sharing from 1.0 to [2.1](https://github.com/cfpb/wagtail-sharing/releases):
https://pypi.org/project/wagtail-sharing/2.1/
This new version adds support for Django 2.2, adds black formatting, and improves error messages when views raise an exception.
=> Bump wagtail-sharing to version 2.1

.github/workflows/docs.yml, mkdocs.yml
In our docs action we did not have a copy of the gh-pages branch, so one was being created. When mkdocs tried to push it, it was rejected because there were changes on gh-pages upstream that we didn't have. This change will fetch the last commit on gh-pages to prevent that from happening.
See https://github.com/cfpb/cfgov-refresh/runs/567993361 for a successful run from this branch.
=> Ensure we have a copy of gh-pages in the docs GitHub Action

cfgov/ask_cfpb/scripts/export_ask_data.py
Our Ask CFPB CSV export expected all questions to have an answer of some kind, be it a text block, or FAQ, or How To. If a question is created as a draft, but does not have any answer text yet, the export will fail.
This change fixes that issue.
An example page that was created and saved as a draft but without any answer text is 13831 (per the nightly database dump from 4/7/20).
1. Using `master`, attempt to export Ask CFPB data from http://localhost:8000/admin/export-ask
2. Observe a `StopIteration` exception from the call to `next()` on the `filter` object without a next result.
3. Checkout `allow-ask-export-questions-no-answers`, and attempt to export Ask CFPB data from http://localhost:8000/admin/export-ask
4. Observe the export completes as expected and the data exists as expected
=> Ask CFPB: Handle questions with no answers in export

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py, cfgov/core/middleware.py, cfgov/core/tests/test_middleware.py
This change updates our middleware from the old pre-Django 1.10 style to the new post-Django 1.10 style. As part of this we'll be using `MIDDLEWARE` instead of `MIDDLEWARE_CLASSES` on Django 1.11 as well as 2.0.
This fixes middleware errors when running the tests with Django 2.0.
It also adds tests for `DownstreamCacheControlMiddleware`.
This is the result of pairing that @cwdavies and I did.
=> Update old-style middleware

.env_SAMPLE, .github/workflows/backend.yml, .travis.yml, cfgov/cfgov/settings/test.py, docker-compose.yml, docs/installation.md, docs/python-unit-tests.md, tox.ini
We now use a Postgres-specific Django db field, JSONField, and to test this feature 
we can't use SQLite. So we need to specify our test database as Postgres, 
rather than providing that option.
This adds an uncommented line to our `.env_SAMPLE` file to specify Postgres
for local development and testing.
Documentation is updated to note that we're dropping support for SQLite and
to change setups so that Django ~~can create~~ creates test Postgres databases.
**UPDATE**
We don't need to "specify" Postgres; we can remove options for SQLite and let Django use Postgres by default. So we don't need a `TEST_DATABASE_URL`.
=> Use Postgres as the default test database

cfgov/v1/tests/test_admin_views.py
Since Django 1.8, [redirects are not forced to be absolute URLs](https://docs.djangoproject.com/en/1.11/topics/testing/tools/#django.test.SimpleTestCase.assertRedirects). `assertRedirects` fails in 2.0 with the absolute URL in this test.
This change fixes that by removing the host component of the URL.
1. Comment out TDP in `requirements/libraries.txt`
2. `tox -e unittest-future` will show that `v1.tests.test_admin_views.TestCDNManagementView. test_requires_authentication` no longer fails.
=> Fix an assertRedirects that's failing in Django 2.0

cfgov/core/utils.py
Prior to this change we were using `request.path` as a part of a regular expression compilation. This depends on the request path being a valid regular expression. We encountered an issue where a request path in production was not.
This change, suggested by @wpears, does a straight string comparison between an link href and the request path looking for an anchor's `#`.
This causes the bad request path we saw in production (`/about-us/blog/worried-about-making-your-auto-loan-payments-your-lender-may-have-options-to-help/%20)`) to 404 instead of 500.
To test this requires the production-like Docker setup that uses Apache. You can [use the docs to get it up and running](https://cfpb.github.io/cfgov-refresh/running-docker/#docker-compose). Then visit …
=> Simplify anchor link handling in parse links middleware

cfgov/core/utils.py
A prior change to address a production issue left an `r` prefix to the string matching anchor links. This change removes it.
=> Remove `r` prefix to string that's not a regex

cfgov/ask_cfpb/wagtail_hooks.py
This change uses `re_path` for the Ask CFPB Export URL definition instead of `path`.
`re_path()` and `url()` should be interchangeable because they both take a regular expression. `path` takes a slightly different non-regex string. When it doesn't have a trailing slash `'export-ask/` it breaks the expectation that the URL ends with a `/`.
I've chosen to revert to using a regular expression for maximum compatibility — this way there's no unexpected difference between Django 1.11 and 2.0.
1. Comment out TDP in `requirements/libraries.txt`
2. `tox -e unittest-future` will show that `ask_cfpb.tests.models.test_pages.ExportAskDataTests.test_export_from_admin_get` and `ask_cfpb.tests.models.test_pages.ExportAskDataTests.test_export_from_admin_post` no longer fail.
=> Use `re_path` for Ask CFPB export URL

cfgov/unprocessed/css/print.less
Removals
- Remove the global eyebrow on print (wasn't printing in Chrome for reasons I don't understand, but was printing in Safari and it's pretty rough with the `href` output on)
- Prevent `href` output for author links
- Prevent `href` output for the logo link
1. Pull branch
1. Load up something like http://localhost:8000/about-us/blog/avoid-scams-find-help-during-quarantine/ in Safari and print it
=> Fix some additional print style issues

cfgov/unprocessed/css/organisms/mega-menu.less
Bring the top of the mega menu link groups closer to the horizontal rule
under MM overview headings. A negative top margin is used instead of removing
the top padding so that the side border on hover keeps the proper padding.
https://GHE/CFPB/el-camino/issues/153
- MM link margin.
- The bottom margin of the optional group headings like "Money tools" is enlarged to compensate when they're present.
1. Pull down and build.
2. Open the mm and check out the spacing. See screenshots below.
| Before | After |
| <img width="1050" alt="Screen Shot 2020-03-13 at 12 53 19 PM" src="https://user-images.githubusercontent.com/1060248/76642620-f2cff180-6529-11ea-9f72-5d63a46aa33b.png">   | <img width="1050" alt="Screen Shot 2020-03-13 at 12 52 19 PM" …
=> Mega menu: Improve link group spacing

cfgov/cfgov/urls.py, cfgov/diversity_inclusion/urls.py, cfgov/wellbeing/urls.py
Add (?i) to wellbeing and diversity_inclusion so URLs are case-insensitive
=> Fix wellbeing and diversity_inclusion so URLs are case-insensitive

cfgov/v1/tests/views/test_login_views.py, cfgov/v1/views/__init__.py
Django 2.0 removes the ability to call `User.is_authenticated` as a method. It was deprecated in Django 1.10. It is not usable only as a property.
https://docs.djangoproject.com/en/3.0/releases/2.0/#features-removed-in-2-0
1. Edit `requirements/django.txt` to pin 2.0.13
2. Rebuild your virtualenv or [Python Docker container](https://cfpb.github.io/cfgov-refresh/running-docker/#update-python-dependencies)
3. Run cfgov-refresh **from `master`**
4. Visit https://localhost:8000/admin and observe the following error:
5. Run cfgov-refresh **from `fix-is-auth-method-dj2`** (this PR)
6. Visit https://localhost:8000/admin and observe the following error:
7. Note the above error *is not* a `TypeError` and does not happen with a check of `is_authenticated()`
This PR only corrects the calls of …
=> Fix deprecated usage of is_authenticated as method

cfgov/cfgov/settings/base.py, cfgov/templates/modeladmin/create.html, cfgov/templates/registration/logged_out.html, cfgov/templates/wagtailadmin/access_denied.html, cfgov/templates/wagtailadmin/login.html, cfgov/templates/wagtailadmin/pages/edit.html, cfgov/templates/welcome.html, requirements/libraries.txt
Since 1.9, Django's built-in `extends` template tag does everything that the django-overextends library's `overextends` template tag did, and django-overextends no longer appears to be maintained.
This change removes django-overextends and uses `extends` in place of `overextends`. The practical effect of this is to fix errors caused by API incompatibilities in django-overextends with Django 2.0.
1. Edit `requirements/django.txt` to pin 2.0.13
2. Rebuild your virtualenv or [Python Docker container](https://cfpb.github.io/cfgov-refresh/running-docker/#update-python-dependencies)
3. Run cfgov-refresh **from `master`**
4. Visit https://localhost:8000/admin and observe the following error:
5. Run cfgov-refresh **from `remove-django-overextends`** (this PR)
6. Visit https://localhost:8000/admin …
=> Remove django-overextends

cfgov/unprocessed/css/print.less
Firefox cuts off `inline-block` elements after 1 page when printing. These changes, extracted from. never-completed PR #2526, solve that problem for our main content and sidebar elements.
Thanks to @virginiacc for the original research and code!
- Print styles to override the display of `.content_main` and `.content_sidebar` in Firefox
1. In Firefox, visit https://www.consumerfinance.gov/about-us/blog/avoid-scams-find-help-during-quarantine/ and print preview to see the bug in question
1. Pull this branch
1. Use Sauce Connect to test http://localhost:8000/about-us/blog/avoid-scams-find-help-during-quarantine/ in Firefox
1. Print preview and confirm that you can see all of the main and sidebar content now
=> Fix Firefox cutting off content after 1 page when printing

cfgov/jinja2/v1/_includes/molecules/info-unit-2.html, cfgov/jinja2/v1/_includes/organisms/filterable-list.html
This is an attempt to fix filterable info units on sublanding filterable pages like https://www.consumerfinance.gov/consumer-tools/everyone-has-a-story/. These info units are constructed rather than actual info unit blocks. 
It tries to work around a change in https://github.com/cfpb/cfgov-refresh/pull/5497 that expects `value.heading` to be a block.
This is a draft PR to get it up on UPC to test.
=> Fix sublanding filterable page info units

cfgov/prepaid_agreements/scripts/write_prepaid_agreements_data_to_csv.py, cfgov/prepaid_agreements/tests/test_scripts_write_prepaid_agreements.py
This change encodes the entire prepaid agreements CSV files as UTF-8 rather than individual fields.
The encoding on individual fields was causing them to be included in the CSV as bytestrings. The effect of this is that when someone opened the file in Excel, the field would appear as `b'Issuer Name'`, etc, since our upgrade to Python 3. This fixes that issue.
1. On `master`, in either the Docker container or virtualenv, run:
```shell
./cfgov/manage.py runscript write_prepaid_agreements_data_to_csv --script-args './'
```
2. Observe that the values in the "issuer_name" and "product_name" columns in the output files are rendered Python bytestrings (`b'Issuer Name'`) rather than just a string (`Issuer Name`).
3. On this branch, `fix-prepaid-csv-encoding`, in either the Docker container or …
=> Update prepaid CSV export encodings

cfgov/ask_cfpb/search_indexes.py, cfgov/ask_cfpb/templates/search/indexes/ask_cfpb/answerpage_autocomplete.txt, cfgov/ask_cfpb/templates/search/indexes/ask_cfpb/answerpage_url.txt
Currently when we index Ask CFPB AnswerPages into Elasticsearch, both the URL and autocomplete text have extra newlines at the end due to the use of templates. This doesn't affect the functionality of the site in practice, but can be observed by inspecting the HTML on certain Ask pages, and would be good to fix for purposes of index cleanliness.
To test, if you query an example document using the master branch, you'll see something like this:
```
$ curl "http://localhost:9200/content_haystack/_search?size=1&fields=autocomplete,url&pretty=true"
{
...
"hits" : {
...
"hits" : [ {
"_index" : "content_haystack",
"_type" : "modelresult",
"_id" : "ask_cfpb.answerpage.5782",
"_score" : 1.0,
"fields" : {
"autocomplete" : [ "What should I do if my EBT card or PIN is lost or stolen or I see …
```
=> Ask CFPB: Remove extra newlines from AnswerPage search index

cfgov/prepaid_agreements/tests/test_scripts_write_prepaid_agreements.py
#5658 (specifically 4169aa4c0072583507ed658e94627dcc343c3b3c) introduced some new tests that generate warnings like:
> RuntimeWarning: DateTimeField PrepaidAgreement.created_time received a
naive datetime (2020-04-01 00:00:00) while time zone support is active.
This change fixes that warning by ensuring that `created_time` gets a timezone-aware datetime.
Run `tox`, no warnings about timezones.
=> Fix naive datetime warning in Python test

requirements/libraries.txt
Fix the following when running tox:
`ERROR: wagtail 2.3 has requirement django-treebeard<5.0,>=4.2.0, but you'll have django-treebeard 3.0 which is incompatible.`
- Update version of `django-treebeard` in `requirements/libraries.txt` from `3.0` to `4.2.0`
1. tox -e lint
2. tox -e unittest-current
3. tox -e unittest-future
=> Update django-treebeard to 4.2.0

cfgov/unprocessed/css/organisms/read-more.less, cfgov/unprocessed/css/organisms/secondary-navigation.less
cfpb-expandables 0.1.0 added the `.u-hidden` utility class to expandable 
content on init, in order to prevent focus from entering collapsed 
expandables. This was inadvertently hiding the content that should 
always be visible at certain screen sizes on these two special types of 
"expandables", secondary navigation and read-more.
- `display: block !important` overrides added to sidenav and read-more `o-expandable_content` at the screen sizes where they should always been open
=> Override new .u-hidden class on sidenav and read-more "expandables"

.github/workflows/backend.yml, requirements/libraries.txt, tox.ini
This change will enable unittest-future, which currently tests Python 3.6, Django 2.0, and Wagtail 2.3, in GitHub Actions, with Django 2.0 being the new thing. This means any changes that fail against Django 2.0 will fail the backend unit tests.
This PR also updated TDP to 1.3.0, which supports Django 2.0.
=> Enable `unittest-future` in GitHub Actions

cfgov/jinja2/v1/_includes/article.html, cfgov/jinja2/v1/_includes/molecules/social-media.html, cfgov/jinja2/v1/_includes/organisms/item-introduction.html, cfgov/unprocessed/css/molecules/social-media.less
Now that we have improved print styles, we want to add a print button to page types that visitors are likely to want to print (namely, blog posts and newsroom articles). This PR does that by adding a new option to the social media molecule to show the print button in particular contexts.
See GHE/CFGOV/platform/issues/3751 for more details.
- `value.is_printable` variable in the social media molecule to set whether or not the print button should appear
- Markup and styles for the print button
- `data.social_options` to the article template to pass `true` to the social media molecule's `value.is_printable` via the item introduction template
- `value.social_options` to the item introduction template to be able to pass `value.is_printable` to the social media molecule
- Render the social …
=> Add print button to articles

cfgov/paying_for_college/templates/paying_for_college/disclosure.html
The logic in the last section of the EFIP disclosure tool is failing and always
calls the program's document a certificate, regardless of the degree earned.
This can be misleading, and we need a hot fix to remove the reference to certificate.
A longer-term solution will be to rewrite js code to pick up program level information.
=> Change the final estimation paragraph to avoid use of "certificate"

cfgov/jinja2/v1/_includes/macros/util/url_parameters.html
Because modern browsers recognize HTML character entities (e.g., `&reg;`) without their semicolons, for backwards compatibility, we need to escape the ampersand when rendering pagination URLs to prevent the combination of the ampersand and an unulucky parameter name (like `reg`) from rendering a special character in the URL and breaking the pagination buttons.
See: https://GHE/CFGOV/platform/issues/3763
- Escapes the ampersand in the `url_parameters()` Jinja macro
1. Visit [a production regulation search](https://www.consumerfinance.gov/policy-compliance/rulemaking/regulations/search-regulations/results/?q=transfer&regs=1005&results=25&order=relevance), try to click the Next button in the pagination, and observe the `®` rendered in the URL, resulting in 0 results.
1. Pull this branch
1. …
=> Fix encoding of pagination URL parameters

cfgov/alerts/logging_handlers.py, cfgov/alerts/tests/test_logging_handlers.py, cfgov/jobmanager/tests/models/test_pages.py, cfgov/v1/admin_forms.py, cfgov/v1/tests/handlers/blocks/test_feedback.py, cfgov/v1/tests/test_admin_views.py, tox.ini
This PR makes a few modifications to support Django 2.2:
- The undocumented `request._post_parse_error`, used in our logging alert handler, was removed in Django 2.1. This PR simply removes the check for it, as we have a generic `Exception` handler for formatting post data.
- `None` is no longer encoded in post data by `RequestFactory`, and values that would be `None` should. instead be omitted. This PR makes a modification to the feedback tests where `referrer` and `is_helpful` were being passed as `None` if no other value was given.
- `schema_json` must have a JSON-parsable value. In the jobmanager tests we perform a post to the Wagtail admin and `schema_json` was not defined. This PR defines it with a blank string.
- Django 2.1+ enforces the use of positional arguments when calling …
=> Support Django 2.2

cfgov/mega_menu/jinja2tags.py, cfgov/mega_menu/tests/test_jinja2tags.py
Currently it's possible for request headers to impact the language that the mega menu displays in. Specifically, setting the `HTTP_ACCEPT_LANGUAGE` header to Spanish could cause the menu to appear in Spanish on certain English pages using a legacy base template.
To test, update your browser settings to prefer Spanish (e.g. in Chrome, Settings, Advanced, Languages, Language) and visit
http://localhost:8000/data-research/consumer-complaints/
On master, the mega menu will be in Spanish. On this branch, it'll be in English.
! Note that other parts of the page may still incorrectly be in Spanish -- this is a separate issue unrelated to the mega menu code.
=> Fix: Ignore request headers for mega menu language

cfgov/unprocessed/apps/regulations3k/js/permalinks-utils.js, test/unit_tests/apps/regulations3k/js/permalinks-utils-spec.js
The iRegs wayfinder broke when we started adding `u-hidden` classes to collapsed expandable content in https://github.com/cfpb/design-system/pull/406 and added to cfgov-refresh in #5617. The `u-hidden` class gives those elements a `display: none`, which means their positions can't be correctly calculated for the map of all paragraphs on the page that powers the wayfinder. That was causing the wayfinder to always show the ID of the last interpretation paragraph on the page no matter where you scrolled.
This change fixes that by toggling the `u-hidden` class off while the map of paragraph positions is being constructed, then toggling it back on again after the map is done.
- Changed `updateParagraphPositions` to only get the positions of *visible* paragraphs instead of all paragraphs (i.e. …
=> Fix the iRegs wayfinder to account for newly hidden expandable content

cfgov/alerts/mattermost_alert.py, cfgov/alerts/tests/test_mattermost_alert.py
Mattermost seems to have gotten more particular about the `Content-Type` header of incoming webhooks in the upgrade from 5.18 to 5.22.
We were seeing errors of this kind:
```json
{
"level": "error",
"ts": 1588614108.121396,
"caller": "mlog/log.go:175",
"msg": "Could not decode the multipart payload of incoming webhook.",
"path": "/hooks/<hook_id>",
"request_id": "wsb5g1xiqine7knmgj9yo9887w",
"ip_addr": "<ip>",
"user_id":"",
"method": "POST",
"err_where": "incomingWebhook",
"http_code": 400,
"err_details": "mime: no media type"
}
```
This change switches our alert webhook's `requests.post` call from using Requests' `data` param to using its `json` param, which sets the `Content-Type` to `application/json`, as Mattermost now requires.
See: …
=> Fix Mattermost alert webhook call

cfgov/cfgov/settings/base.py
Because we always activate Spanish-language content via the inclusion of 
an `/es/` path segment that triggers the setting of the `language` 
context variable to `es`, we do not need this middleware for anything 
currently, and its presence can cause unwanted appearance of Spanish on 
English pages if a user has set their browser's primary language to 
Spanish.
- `django.middleware.locale.LocaleMiddleware` removed from `MIDDLEWARE` in our base settings file
1. Pull branch
1. Visit various Spanish-language pages on your local server and compare to how they look in production
1. Update your browser settings to prefer Spanish (e.g. in Chrome, Settings, Advanced, Languages, Language)
1. Visit `/data-research/consumer-complaints/` using your favorite way to bypass Akamai, observe some parts of …
=> Remove Django's LocaleMiddleware from the app

cfgov/jinja2/v1/_includes/organisms/full-width-text.html, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_layouts/base.html, cfgov/jinja2/v1/ask-cfpb/answer-page.html, cfgov/jinja2/v1/ask-cfpb/answer-search-results.html
A [PR to django-flags a year and a half ago](https://github.com/cfpb/django-flags/pull/14) made the passing of `request` to the `flag_enabled()` and `flag_disabled()` template tags unnecessary.
The inclusion of `request` breaks Wagtail revision comparisons for pages that include a template with such, because the Wagtail revision comparison view has no `request`.
- Removes extraneous `request` params from our `flag_enabled()` template tags
1. With a fresh database dump, try to view http://localhost:8000/admin/pages/13866/revisions/compare/212395...212582/ on the master branch and observe a 500 error.
1. Pull branch
1. Refresh http://localhost:8000/admin/pages/13866/revisions/compare/212395...212582/ and see that it now works
=> Remove unnecessary request params from flag_enabled template tags

cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/organisms/header.less
I've had enough of looking at this issue, and turns out it's an easy fix!
- Fix cropped search focus rectangle.
2. Click into the global search and see that the focus rectangle is not cropped on the left-hand side. Compare to production.
Before:
After:
=> Global Search: Fix cropped search focus rectangle

cfgov/cfgov/settings/base.py, requirements/libraries.txt, requirements/test.txt, tox.ini
This PR does two major things:
1. Re-enables `tox_pip_extensions_ext_venv_update` in tox, which will automatically update our local test envs with dependency changes, and will enforce dependency resolution, and updates dependencies based on what they collectively require to achieve a set of dependencies that match.
2. Pins Wagtail to `<2.6` in `unittest-future`. Wagtail 2.5 is the first version to support Django 2.2, so this satisfies `venv-update`'s requirement for matching version ranges.
There is one other minor change as well:
- `OPTIONAL_APPS` in settings has been removed as part of the dependency/app updates. There's no practical change here, as our satellite apps have been non-optional for a while now.
And there's one thing to highlight:
- `venv-update` is not exactly under …
=> Re-enable venv-update and resolve dependencies for Django 2.2

cfgov/cfgov/settings/base.py
Django Rest Framework was accidentally removed in #5709. This restores it.
=> Restore missing rest_framework

cfgov/regulations3k/jinja2/regulations3k/inline_interps.html
We're adding inline interpretations to Regulation D. Unlike all of our other regs, Reg D houses its interpretations in Appendix A instead of Supplement I. We had "Supplement I" hardcoded into the text of the links at the end of all inline interpretations, which didn't make sense for inline interps in Reg D. This PR fixes that by making the reference to the location of the interps in those links a variable and sets up a special case for Reg D interps.
- The part of the link in inline interpretations that points to the interp in the regulation text is now a variable that will be "Appendix A" only for Reg D and "Supplement I" everywhere else.
1. Make sure you have the latest production database.
2. Go to the version of Reg D that has inline interpretations in it, …
=> Make interpretation location a variable in iRegs

requirements/docs.txt, requirements/libraries.txt
This PR is identical to #5713. Snyk refused to run on that PR for reasons that their support were unhelpful in determining. This PR is an attempt to get around that by opening a new PR.
--
This upgrade is to address CVE-2017-18342. As of #5714 it's no longer required in libraries.txt.
There was a vulnerability in PyYAML 3.1.13 that we determined didn't effect us in the way we use the library, but the vulnerability still gets flagged. Previously we couldn't upgrade PyYAML because non-vulnerable versions did not support Python 2. Now we can!
=> Remove PyYAML from libraries and update it in docs

cfgov/apache/conf.d/redirects.conf
Redirect for placeholder browse page created to appear in the side nav of other coronavirus child pages to sublanding page at `/coronavirus/mortgage-and-housing-assistance/`.
=> Coronavirus page redirect

Dockerfile, cfgov/ask_cfpb/models/pages.py, requirements/libraries.txt
This change is required for the following:
* Add Django 3.0 support
* Remove Wagtail 1.x support (Wagtail 2.3 or later now required)
Replace `page_type` keyword argument with more accurate `target_model` keyword argument.
The old argument still works, but is deprecated.
Deprecate `is_single option`, make `target_model` optional.
`AutocompletePanel` will now automatically derive these attributes from the field.
https://wagtail-autocomplete.readthedocs.io/en/latest/changelog.html
1. tox -e unittest-current
1. tox -e unittest-future
=> Update wagtail-autocomplete from 0.1.1 to 0.5

cfgov/ask_cfpb/models/pages.py, requirements/libraries.txt
wagtail-autocomplete 0.5's README.st is UTF-8 encoded, and somewhere along our build pipeline the README.st is not being opened UTF-8 encoded (I believe because the locale is not set to UTF-8 in a way that it needs to be). This downgrades to unbreak the build while we figure that out.
=> Downgrade wagtail-autocomplete

cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/ask-cfpb/answer-page.html
Since modifying the HowTo block to be usable on BlogPage (chiefly, adding in a `title` field that outputs the overall HowTo's `name` property, this flag's effects are no longer helpful, and are, in fact, causing errors in how the HowTo markup on Ask pages is being interpreted.
In truth, I screwed up by not fully understanding how the HowTo implementation within Ask CFPB worked when I extended it to BlogPage, causing this situation we're in now with the double markup. But, it seems like the HowTo schema will be fairly stable and worthwhile, so it makes sense to take this out of a flag-based setup and have it be controlled exclusively by the presence of the block, anyhow.
/cc @kelleyholden 
- `HOW_TO_SCHEMA` flag and related code
1. To reproduce the problem with a database dump prior to the …
=> Remove HOW_TO_SCHEMA flag and its effects on AnswerPages

cfgov/v1/models/base.py
We only want to test for direct children of the homepage, not descendents.
=> Correct is_descendant_of to is_child_of in CFGOVPage breadcrumbs

cfgov/apache/conf.d/headers.conf
We can't recall why we would have done that, and can't think of a good reason to still be doing it.
- Apache configuration directive setting the `Edge-Control: no-store` header for `/consumer-tools/prepaid-cards/` and its children
- Makes comment that preceded that a little more explicit
=> Remove Apache configuration preventing prepaid-cards section from being cached

cfgov/jinja2/v1/_includes/organisms/ask-search.html, cfgov/jinja2/v1/ask-cfpb/landing-page.html, cfgov/unprocessed/css/pages/ask.less
Move the Ask search to the top of the Ask landing page. See [GHE]/CFGOV/platform/issues/3779 for more details.
- Added the `label_level` parameter to the `ask-search` template. The `ask-search` template is used in a number of places. Previously, all of those places either didn't show the label (using `show_label=False`) or situated the form under an `h2`. Now that the search form is at the top of the Ask landing page, it needed an `h2` to be semantically correct. The new `label_level` parameter lets you set the heading level in the label to something other than `h3` if you need it.
- The Ask search now appears at the top of the Ask landing page.
- Previously, the Spanish search button label, "búsqueda," was cut off (see the [current Spanish Ask landing …
=> Move search to the top of the Ask landing page

cfgov/ask_cfpb/scripts/export_ask_data.py, cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/data_research/blocks.py, cfgov/data_research/mortgage_utilities/fips_meta.py, cfgov/data_research/mortgage_utilities/s3_utils.py, cfgov/data_research/scripts/export_public_csvs.py, cfgov/data_research/scripts/process_mortgage_data.py, cfgov/data_research/tests/test_blocks.py, cfgov/data_research/tests/test_scripts.py, cfgov/data_research/urls.py, cfgov/scripts/export_enforcement_actions.py, cfgov/scripts/tests/test_export_enforcement_actions.py, requirements/libraries.txt
Now that we can use Python3's csv module, we no longer need unicodecsv.
This removes a dependency originating from a Python2 weakness and also restores functionality 
to the export-enforcement-actions script, which had stopped working.
- Removes unicodecsv from requirements/libraries.txt
- Imports the Python3 csv package instead of unicodecsv
- Keeps byte strings out of our code
- Fixes tests that weren't running
- Fixes the enforcement actions export script, which stopped working
when we introduced EnforcementActionPages in March. The script was written to
harvest content from DocumentDetailPages. Currently, the export produces a blank CSV.
- In the Wagtail admin, run the Enforcement Actions and Ask CFPB exports before and after. There should be no change in Ask, but the Enforcement …
=> Drop the use of unicodecsv

cfgov/v1/models/banners.py, cfgov/v1/tests/models/test_banners.py
This will display the title of the banner in various places in the Wagtail admin, instead of generic text like "Banner object (2)".
- `__str__` method added to `Banner` model
With a recent database dump:
1. Visit http://localhost:8000/admin/v1/banner/edit/2/ and see that the header reads: "EDITING Banner object (2)"
1. Pull branch
1. Refresh the page and see that the header now reads: "EDITING Interagency mortgage and housing assistance pages"
=> Add __str__ method to Banner model

cfgov/v1/admin_forms.py, cfgov/v1/admin_views.py, cfgov/v1/tests/test_admin_views.py
Fix the use of`call_command` in the admin feedback export by passing the the page slugs to `call_command` instead of looking up the slugs first and passing the page objects.
The one side-effect of this is to requires the hard-coded slugs to exist and be unique (where previously if they didn't, the lookup in `_get_pages_from_slugs` would ignore `DoesNotExist` and `MultipleObjectsReturned`). This is consistent with the behavior of the management command, and I think that's okay — if we want to allow for ignorable errors, I think we should do it there instead of in the admin, so that the behavior is consistent.
=> Fix feedback export from admin

cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py
Previously, attempted form POSTs on pages where the main content StreamField had no form were not correctly returning a 400 response. This change fixes that.
See errors from the evening of 5/31/20 documented at https://GHE/CFGOV/cfgov-alerts/issues/23 and Mattermost discussion at: https://MM/cfpb/pl/bdqukr8frtynbkimq43jbbgu5w
- Moves result = `form_module.block.get_result(…)` into `try`/`except` block to ensure that an improperly-derived `form_module` doesn't throw a 500 there.
Tests pass; new test added for this particular scenario.
=> Handle bad POSTs when StreamField has no form

cfgov/unprocessed/css/organisms/mega-menu.less
@chosak noticed the featured link area was off, and we realized https://github.com/cfpb/cfgov-refresh/pull/5578 moved the featured link up. This omits the featured link from the selector in that PR and adds margin between multiple featured links.
- Make featured link top/bottom margin equal and add margin between links when there are more than one.
2. Compare local mega menu featured link to production.
3. Add a second or more featured link and see that there is a gap between them.
Production with simulated second link:
Local changes:
=> Mega Menu: Fix featured link area spacing

cfgov/cfgov/settings/base.py
This will allow administrators to control when the CCDB Trends feature is actually rolled out to users
=> Add a Wagtail flag for CCDB5 Trends

cfgov/jinja2/v1/_includes/organisms/table.html
Striped tables weren't actually getting striped because of a slightly wrong class getting applied.
- The `table__striped` class that was being applied to striped tables is now the correct `o-table__striped`  
1. Add a table to a page in Wagtail and check the "striped rows" option.
2. Preview that table and make sure the table is striped as [shown in the Design System](https://cfpb.github.io/design-system/components/tables#striped-table).
- PR titles are used to generate the change log in [releases](../../releases),
so good ones make that easier to scan.
- Consider prefixing with the feature/section you're addressing,
e.g., "Mega Menu: fix layout bug" or "Paying for College: Update content on Repay tool"
=> Tables: Fix striped tables

cfgov/cfgov/settings/base.py, cfgov/research_reports/models.py
❗ Note: This PR is for the Reports as Webpages project and is not going into Master! If merged, it will go into the `reports-as-webpages` branch. ❗ 
I think this is all we need to start a new sub-app. `research_reports` sub-app will hold all code related to the Office of Research Reports as Webpages project.
- You can still use atomic elements from v1
- Templates specific to reports-as-webages can go in `cfgov/research_reports/jinja2/`
- I created the `models.py` with the sample command for how to run migrations (since it's slightly different for a new app, which confused me when I did this for my proof-of-concept)
=> Create new sub-app for research reports

cfgov/unprocessed/apps/paying-for-college/css/main.less
Restores removed PfC LESS files to fix broken layout on Dynamic Disclosures.
- Restored LESS file imports in paying for college app's `main.less` file
2. Run `yarn gulp styles`
3. Navigate to [Dynamic Disclosures](https://www.consumerfinance.gov/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=154022&pid=BAHCA&totl=70950&tuit=14160&hous=7109&book=1150&tran=500&othr=4743&pelg=0&schg=&stag=&othg=&mta=&gib=&wkst=0&ppl=&parl=&perl=&subl=3500&unsl=6000&gpl=&prvl=&prvi=&prvf=&insl=&insi=&inst=&oid=4D0B9265B45716DF4B81EEB4BE117E1DF69871AF) on production and verify layout is broken
4. Navigate to [Dynamic Disclosures locally](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=154022&pid=BAHCA&totl=70950&tuit=14160& …
=> PfC: Dynamic Disclosures layout fix

docker/elasticsearch/Dockerfile
This change ensures the synonym files are placed correctly in the Elasticsearch Dockerfile. Previously they were overwriting `config/analysis` as a file rather than being places inside `config/analysis` as a directory.
```shell
docker-compose build elasticsearch
docker-compose up
```
In a separate terminal:
```shell
docker-compose exec python bash
./cfgov/manage.py rebuild_index
```
Observe the **lack** of any errors about the synonym file location from the elasticsearch container:
```
elasticsearch_1  | [content_haystack] IndexCreationException[failed to create index]; nested: IllegalArgumentException[IOException while reading synonyms_path_path: /usr/share/elasticsearch/config/analysis/synonyms_en.txt (Not a directory)];
```
=> Fix Elasticsearch synonyms in Dockerfile

requirements/libraries.txt
To support Wagtail 2.9 update versions of the following:
* wagtail-flags
* wagtail-inventory
* wagtail-sharing
* wagtail-treemodeladmin
1. git checkout wagtail29
2. source .env
3. ./setup.sh
4. tox
- Consider prefixing with the feature/section you're addressing, e.g., "Mega Menu: fix layout bug" or "Paying for College: Update content on Repay tool"
- [This repo’s docs](https://cfpb.github.io/cfgov-refresh/) (edit the files in the `/docs` folder) – for basic, close-to-the-code documentation on working with this repo
_[When new or …
=> Release satellite apps and libraries with Wagtail 2.9 support

cfgov/cfgov/settings/base.py, cfgov/core/middleware.py, cfgov/core/tests/test_middleware.py
Currently we have various places in our code where we call [`translation.activate`](https://docs.djangoproject.com/en/2.2/ref/utils/#django.utils.translation.activate) to activate Django translations. We do this both for English and Spanish; for example [our base `CFGOVPage` makes this call every time it gets served](https://github.com/cfpb/cfgov-refresh/blob/50c67eb1917c2b02f9f1efff1ae6ac26895ae3ac/cfgov/v1/models/base.py#L248).
Under the hood, Django translations work by setting the current language [on the local thread](https://github.com/django/django/blob/69e0d9c553bb55dde8d7d1d479a78bfa7093f406/django/utils/translation/trans_real.py#L279). Unfortunately, subsequent Django requests may be handled by that same thread, meaning they incorrectly inherit that language.
As a simple test, …
=> Always deactivate Django translations after each request

cfgov/ask_cfpb/templates/search/indexes/ask_cfpb/answerpage_text.txt, cfgov/cfgov/settings/base.py
This PR will add Ask CFPB FAQ and HowTo blocks to the Ask CFPB "text" search field to make their content searchable by the Ask CFPB search box just like other answer content.
This PR also corrects a couple of issues with the Elasticsearch settings:
- The synonym analyzers (used for the "text" field) were using the `whitespace` tokenizer, which left punctuation in place for tokens. That resulted in searches for words at the end of sentences, for example, to fail unless the search term included the period. I've changed the tokenizer to `standard` for these.
- The ["side" parameter was deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/analysis-edgengram-tokenizer.html#_literal_side_literal_deprecated)
1. Add a unique term to the HowTo block on a page with one, for …
=> Add FAQ and HowTo blocks to Ask CFPB search "text" field

cfgov/unprocessed/js/organisms/VideoPlayer.js
Certain YouTube videos don't make thumbnails available via the URL pattern that we use. The recent changes in #5781 broken the appearance of the player for these videos; this commit fixes that.
To test, use a video like R0rp_LIUTLQ, where this thumbnail URL 404s:
https://img.youtube.com/vi/R0rp_LIUTLQ/maxresdefault.jpg
Using a recent production dump, try visiting http://localhost:8000/coronavirus/mortgage-and-housing-assistance/rent-protections-covid-19/ on master and on this branch (after building the JS assets).
It would be better to use the YouTube JS API to retrieve the proper thumbnail (as the comment in the code says), but this would require a YouTube API key. Alternatively we could do an AJAX request for the thumbnail and check the status code, but it'd be slower with no real …
=> Properly handle missing YouTube thumbnail images

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, requirements/libraries.txt
Version 1.5.0 of the teachers_digital_platform package moved the Curriculum Review Tool into its own separate crtool Django app. This commit updates the teachers_digital_platform requirement to 1.5.0 and installs crtool as a separate app, including the necessary addition to the main project `urls.py` file.
- `crtool` added to `INSTALLED_APPS`
- `crtool.urls` imported in `urlpatterns` 
- teachers_digital_platform requirement updated to 1.5.0
1. Pull branch
1. `pip install -r requirements/local.txt` or `docker-compose build python`
1. Run your local server and visit http://localhost:8000/practitioner-resources/youth-financial-education/curriculum-review/
1. Go through some of the curriculum review process and verify that everything continues to work as expected.
=> Update TDP requirement to 1.5.0 and install separate crtool app

cfgov/core/tests/test_middleware.py
I'm not sure what changed, but our translation middleware tests are failing in master because of a state issue. 
~~If we start the test with a clean slate by deactivating all translations, the test can't be tripped up by another test.~~
Since the test is checking deactivation, it would make more sense to explicitly set the language first, rather than first deactivating.
=> Fix middleware test by starting with clean state

Jenkinsfile, cfgov/core/tests/test_middleware.py
Builds running concurrently can sometimes hang, so let's not do that.
=> Disable concurrent builds in Jenkins multibranch pipeline

cfgov/core/middleware.py, cfgov/core/tests/test_middleware.py, cfgov/core/tests/test_utils.py, cfgov/core/utils.py
This change makes our `ParseLinksMiddleware` only parse links within the HTML `body` tag. This should avoid inserting the external link SVG icon in header meta tags.
It does this by added step to fetch the `body` tag and then discovering `a` tags within that.
I've tried to genericize the original `a` tag matching regular expression for this purpose — so we have a RE that can match any specific tag name.
1. On the `master` branch, visit any page with a link in its `meta name="description"` tag and notice the external link icon appearing at the very top of the page, for example: http://localhost:8000/ask-cfpb/i-am-tired-of-receiving-credit-card-mailings-what-can-i-do-en-7/
2. Checkout this branch, `fix-parse-links`, and visit the same page. Note the external link icon is gone.
Before this …
=> Parse links only within HTML body

requirements/libraries.txt
Fixes an issue with missing static assets in the wheel.
=> Update TDP to 1.5.1 to fix missing activity search static assets

cfgov/paying_for_college/disclosures/scripts/notification_tester.py, cfgov/paying_for_college/tests/test_scripts.py
We've had to check our PFC notifications a lot in the past few days. These changes will make that easier.
Originally we got back json responses from schools, but they stopped doing that, and the absence was obscuring test success.
The script can only be fully tested from a productions server, because otherwise your outbound IP may be blocked.  
However, you can test it locally against httpbin, and you can see it time out for requests to schools that use a blocklist.
To test:
```bash
./cfgov/manage.py shell
```
```python
from paying_for_college.disclosures.scripts.notification_tester import *
print(send_test_notifications(url=BINPOST))
print(send_test_notifications())
```
- The httpbin request should succeed, and the response's 'origin' field should reflect your outbound IP.
- The bare …
=> Adjust notification tester and comments

cfgov/cfgov/settings/base.py
The production website is currently not allowing iframes from surveys.consumerfinance.gov. Chrome console error:
> Refused to frame 'https://surveys.consumerfinance.gov/' because it violates the following Content Security Policy directive: "frame-src 'self' *.googletagmanager.com *.google-analytics.com optimize.google.com www.youtube.com *.doubleclick.net universal.iperceptions.com www.facebook.com staticxx.facebook.com mediasite.yorkcast.com".
- Adds `*.consumerfinance.gov` to all CSP allowlists
- Adds `*.qualtrics.com` to image and frame CSP allowlists
=> Hotfix: Update CSP allowlists for intercept survey

.isort.cfg, cfgov/cfgov/settings/base.py, cfgov/v1/tests/management/commands/test_add_images.py, tox.ini
We may have assumed that '*.consumerfinance.gov' would cover it,
but our CCDB map is proving that wrong.
This is a hotfix.
=> Restore 'files.consumerfinance.gov' to CSP allowlists

.isort.cfg, tox.ini
Our tox file did not pin the isort version, and GitHub actions started using the latest version for our CI tests, which started failing 7/6. There are at least two deprecated options/configs that we'll need to adjust:
- the `--recursive` flag, which is deprecated
- the `not_skip` configuration, which is deprecated
These two settings were removed in an attempt to get past linting failures for a hotfix. This restores them and pins isort at 4.3.21 until we can sort out the changes in 5.x.
=> pin isort version until we handle new deprecations

cfgov/scripts/http_smoke_test.py
Our list of most popular pages has been transformed by the pandemic,
so it was time to update our lists.
- The S3 json [list of popular URLs](https://files.consumerfinance.gov/build/smoketests/smoketest_urls.json), which is the default, is updated here and changed from http to https.
- The hard-coded fallback list, used if S3 is unavailable, is also updated.
You can run the script locally and watch the parade of URLs go by:
```
./cfgov/scripts/http_smoke_test.py -v
```
=> Update the smoke tests to use the most current top-25 pages

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/01-school-search.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/10-max-debt-guideline.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/12-affording-your-loan.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/14-summary.html, cfgov/unprocessed/apps/paying-for-college/css/college-costs/state-based.less, cfgov/unprocessed/apps/paying-for-college/js/dispatchers/get-api-values.js, cfgov/unprocessed/apps/paying-for-college/js/dispatchers/get-model-values.js, cfgov/unprocessed/apps/paying-for-college/js/dispatchers/update-models.js, cfgov/unprocessed/apps/paying-for-college/js/models/financial-model.js, cfgov/unprocessed/apps/paying-for-college/js/models/school-model.js, cfgov/unprocessed/apps/paying-for-college/js/models/state-model.js, cfgov/unprocessed/apps/paying-for-college/js/util/number-utils.js, cfgov/unprocessed/apps/paying-for-college/js/util/url-parameter-utils.js, cfgov/unprocessed/apps/paying-for-college/js/views/chart-view.js, cfgov/unprocessed/apps/paying-for-college/js/views/financial-view.js, cfgov/unprocessed/apps/paying-for-college/js/views/school-view.js, cfgov/unprocessed/apps/teachers-digital-plaform/css/main.less
This pull request adds program selection and handling of program-specific salaries for graduate students (where data is available). 
- A dropdown menu that appears when school data is available
- Content that appears when a program is selected, or when program data is unavailable
- Fix content for undergraduates with regards to salary figures
- Fix empty/short calls to the API
1. Pull down the PR and fire up `cfgov-refresh` locally.
2. Get the latest data loaded in there (`refresh-data.sh`)!
3. navigate to `localhost/paying-for-college/your-financial-path-to-graduation/`
4. Try out different graduate programs. Schools where we have program data (try George Washington University) should allow you to select a program and show a different salary than if you select undergrad. Schools with no …
=> Paying for College - Add program salaries to front-end

.github/workflows/backend.yml, docs/python-unit-tests.md, tox.ini
This change removes our custom env-var based migrations check that only occurs in CI and moves it to a separate tox env that can be invoked along side linting and unit testing. It also runs the migrations check only against the production settings, so it only catches apps that we use in production.
=> Separate out check for missing migrations in CI

cfgov/v1/atomic_elements/atoms.py
This custom StructBlock [isn't used anywhere in the codebase](https://github.com/cfpb/cfgov-refresh/search?q=ImageBasicUrl), and seemingly never has been.
_[Feel free to delete any checkboxes that are not applicable to this PR.]_
- Consider prefixing with the feature/section you're addressing, e.g., "Mega Menu: fix layout bug" or "Paying for College: Update content on Repay tool"
- [This repo’s docs](https://cfpb.github.io/cfgov-refresh/) (edit the files in the `/docs` folder) – for basic, close-to-the-code documentation on working with this repo
- CFPB/hubcap wiki on GHE – for internal CFPB design and …
=> Deprecate unused ImageBasicUrl

cfgov/unprocessed/js/organisms/MegaMenuDesktop.js
https://github.com/cfpb/cfgov-refresh/pull/5770 neglected the case where the user resized without ever opening a menu, which meant `_activeMenu` was null and was throwing an error when its state was updated. This PR adds logic to check that `_activeMenu` has a value before resetting its state.
Additionally, the new mega menu added in https://github.com/cfpb/cfgov-refresh/pull/5550 does not use `type` in the `_updateMenuState` method any more, so that parameter has been removed in this PR.
- Checks `_activeMenu` value before resetting its state.
- Removes unused `type` parameter from `_updateMenuState` method.
2. View the site at desktop size and resize to mobile without opening the menu. There should be no JS error (this will produce an error on production …
=> Mega Menu: Fix issue with updating menu state

cfgov/cfgov/urls.py
In order to let Wagtail take over serving the paying-for-college
landing page, we need to remove the URL entry that sent PFC requests 
to comparisontool.
We need to retain three downstream comparisontool pages for now, so
this patch adds explicit URL entries for those pages.
After checking out the branch, make sure these pages render properly:
- http://localhost:8000/paying-for-college/ should show the new wagtail landing page:
These three pages should be unchanged, and show a hero with pencils:
- http://localhost:8000/paying-for-college/repay-student-debt/
- http://localhost:8000/paying-for-college/choose-a-student-loan/
- http://localhost:8000/paying-for-college/manage-your-college-money/
=> Remove the comparisontool URL include

cfgov/unprocessed/apps/paying-for-college/js/dispatchers/update-models.js, cfgov/unprocessed/apps/paying-for-college/js/models/financial-model.js, cfgov/unprocessed/apps/paying-for-college/js/util/url-parameter-utils.js
This is a small and quick fix. The url tracking parameters (things like ?utm_source=press%20release&utm_medium=email&utm_campaign=gradpath) are being overwritten by this app's URL rewrite code _before_ they go to analytics. This fix stores those values and puts them back into the URL.
- Add url parameters to preserve so that campaign tracking works properly
=> Paying for College - Fix campaign tracking

cfgov/cfgov/urls.py
The Django URLs have an entry for [/credit-cards/knowbeforeyouowe/](https://www.consumerfinance.gov/credit-cards/knowbeforeyouowe/), which renders a nonexistent tool.html template. This URL is already being handled by Apache redirects [here](https://github.com/cfpb/cfgov-refresh/blob/2c7440bc23c3c74bfd1f449b98128b79176fce0c/cfgov/apache/conf.d/redirects.conf#L521), which returns a permanent redirect to [/data-research/credit-card-data/know-you-owe-credit-cards/](https://www.consumerfinance.gov/data-research/credit-card-data/know-you-owe-credit-cards/). Thus, this URL can be removed from urls.py.
If you visit http://localhost:8000/credit-cards/knowbeforeyouowe/ using the Django dev server, it will 404, but that's okay. If you visit it using an Apache setup (like Docker), it should redirect …
=> Remove unused Django URL for KBYO page

requirements/libraries.txt
2.0.1 fixes a lingering call to a now-missing, unnecessary JS file.
- Upgrade curriculum-review-tool requirement to 2.0.1
=> Update crtool to 2.0.1

requirements/libraries.txt
This change temporarily pins cryptography to 2.9.2. Akamai's edgegrid-python has an open-ended dependency on PyOpenSSL, which in turn has an open-ended dependency on cryptography. cryptography 3.0 currently doesn't build in our build environment. This pins the last release that  does until we can solve that problem.
=> Pin cryptography temporarily to 2.9.2

.github/workflows/codeql-analysis.yml
I think the lack of one or both of these may have been preventing results from being stored.
Currently, one of the code scanning checks on PRs is always erroring with messages like this:
My theory is that this is because there was no on-push trigger that caused a scan on the master branch after a PR is merged and no on-schedule trigger to create one on a regular basis otherwise.
- Trigger to run code scans on pushes to master
- Trigger to run code scans nightly at 7 a.m. UTC
1. Merge it and see what happens!
=> Restore push and cron triggers for GitHub code scanning workflow

requirements/libraries.txt
1. Now that the teachers_digital_platform app has been moved into this repo, the django-mptt package is now [required by cfgov-refresh](https://github.com/cfpb/cfgov-refresh/search?q=mptt&unscoped_q=mptt).
2. The django-js-asset package is no longer needed by TDP (now renamed to [curriculum-review-tool](https://github.com/cfpb/curriculum-review-tool)), so this entry can be removed. See https://github.com/cfpb/curriculum-review-tool/pull/399.
=> Update library requirements post-TDP rename

cfgov/scripts/fix_links_in_tableblocks.py, cfgov/v1/tests/views/test_documents.py, cfgov/v1/views/documents.py
[`get_document_model` moved in Wagtail 2.8](https://docs.wagtail.io/en/latest/releases/2.8.html#wagtail-documents-models-get-document-model-has-moved) from `wagtail.documents.models` to `wagtail.documents`, and importing it from `wagtail.documents.models` is deprecated and will be removed in Wagail 2.10 
I've changed all the places where we import it from the deprecated location.
This will fix warnings like:
```
RemovedInWagtail210Warning: wagtail.documents.models.get_document_model has been moved to wagtail.documents.get_document_model 
```
=> Import get_document_model from its new location in Wagtail 2.8+

cypress.json
Alters the default command timeout for Cypress from 15s to 25s. This will alleviate potential failures due to long searches
---
- Default Command Timeout from 15s to 25s.
1. Run Cypress Tests
=> Change Cypress Default Command Timeout to 25s

cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less
Somewhere in some update it looks like Highcharts started adding `overflow: hidden` to the top-level chart container in addition to the Highcharts-specific container. That caused tooltips and chart labels that ran over the bounds of the chart to get clipped. This change fixes that.
See GHE/CFGOV/platform/issues/3603 for more info.
- Added the `.chart-area` container to the `overflow: visible !important` rule
1. In production, check rates for a state that has a rate bar with nine or 10 results. (With the current data, Illinois has a bar with 10 results.) Note how some or all of the tooltip for those bars is clipped and all of the label for bars with 10 results is clipped.
2. Check the same rates locally in this branch and confirm that the tooltip and bar labels are fully visible for tall …
=> Fix clipped tooltips in the rate explorer

cfgov/research_reports/jinja2/index.html, cfgov/research_reports/models.py
PR against `reports-as-webpages` branch
Adjusts research report appendix labelling according to GHE/CFPB/super-regular/issues/57
All linking between the ToC and headers should still function appropriately.
=> Research Reports Appendix Level Two

cfgov/unprocessed/js/molecules/Multiselect.js
Right now, there's no autocomplete attribute set on the multiselect's typeahead text input, which means that a browser's autocomplete interface can pop up and obscure the multiselect checkboxes until you dismiss the autocomplete suggestions. Since the multiselect's text input is meant as a typeahead way to filter the options to find what you're looking for, turning the autocomplete off doesn't take away from the intent of that field.
See GHE/CFGOV/platform/issues/3568 for more details.
---
- `autocomplete="off"` attribute to the multiselect's typeahead text input
1. In production (or locally on the main branch), visit a page with a multiselect. Any filterable list page with the topics field will do (the blog landing page, for example).
2. Enter a term in the multiselect text input but …
=> Turn autocomplete off on multiselect's typeahead input

cfgov/jinja2/v1/_includes/molecules/social-media.html
When used in its non-sharing configuration, our social media molecule links to the Bureau's English Facebook (cfpb) and Twitter (cfpb) accounts. On Spanish pages, these links should go to the appropriate Spanish Facebook (CFPBespanol) and Twitter (CFPBespanol) accounts.
We always import this social-media template `with context` so it should have the proper `language` variable set.
To test, run a local server and visit these pages, and observe the links in the footer. These should be English:
- http://localhost:8000/
- http://localhost:8000/about-us/blog/receive-your-unemployment-benefits-options/
And these will be Spanish:
- http://localhost:8000/es/
- http://localhost:8000/about-us/blog/opciones-recibir-beneficios-desempleo/
There's some additional potential work to be done here when the …
=> Link Spanish pages to Spanish social media

.github/workflows/backend.yml, frontend.sh, tox.ini
We've had a `validate-assets` tox environment for ages that collects our assets and then runs Django's `collectstatic` on them. Because we use `ManifestStaticFileStorage` in production, if static assets are missing, this `collectstatic` will fail.
Because our webfonts are not public, we have not been able to run this in CI.  I've pulled in [a workaround for this] (https://github.com/cfpb/cfgov-refresh/pull/5110/files#diff-300249821afbbfcb945e6fbe141d0bb8R32-R55) created by @chosak in another context in #5110.
I think the `frontend.sh` file is right place for this to live, but I'm open to moving it.
This PR is in draft so we can see it run.
=> Validate our static assets in CI

cfgov/v1/jinja2_environment.py, requirements/libraries.txt
This change bumps the version of the Jinja2 package we use from 2.10.2 to 2.11.2, released on 4/13/2020.
See changelog here: https://jinja.palletsprojects.com/en/2.11.x/changelog/
There are various changes; the one in particular motivating me to make this change is the addition of the `{% debug %}` tag which makes it easier to debug template context. Use of this tag prints out a bunch of template debugger context as a JSON blob:
https://jinja.palletsprojects.com/en/2.11.x/extensions/#debug-extension
Because we don't want to accidentally do this in production, I've set this up so that this extension only gets turned on when DEBUG is True. See the code comment for a little more detail.
Another nice change in this release is greater flexibility around using logic like
`{{ 'foo' if bar }}` …
=> Bump Jinja2 version from 2.10.1 to 2.11.2

cfgov/research_reports/jinja2/index.html, cfgov/unprocessed/apps/research-reports/css/main.less, cfgov/unprocessed/apps/research-reports/js/index.js
PR against reports-as-webpages branch
Closes:
GHE/CFPB/super-regular/issues/108
GHE/CFPB/super-regular/issues/109
GHE/CFPB/super-regular/issues/119
GHE/CFPB/super-regular/issues/120
(switches headers to h2/h3 instead if h3/h4 for the former two, and compare the screenshots in the latter two issues with the attached one)
=> Aligns ToC with eyebrow, fixes ToC indent and report body header priority

.gitignore
This commit adds the .vscode folder to .gitignore so that Visual Studio Code workspace settings aren't tracked in source control.
=> Ignore Visual Studio Code workspace settings

cfgov/core/jinja2tags.py, cfgov/core/templatetags/signed_redirect.py, cfgov/core/utils.py, cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/jinja2/v1/_includes/molecules/social-media.html, cfgov/jinja2/v1/blog/blog_page.html
This commit deprecates the definition and use of two template tags: `signed_redirect` and `unsigned_redirect`. These template tags are used to modify external linked URLs so that they go through an interstitial view. Because we apply URL rewrite logic globally through [middleware that processes all Django requests](https://github.com/cfpb/cfgov-refresh/blob/d48b4a5af6e928bf35fe982f7eeb96793c497e46/cfgov/cfgov/settings/base.py#L118), using these tags in templates is  redundant and can be misleading; for example, using `unsigned_redirect` in a template gets converted to a signed_redirect in the middleware.
It turns out that `unsigned_redirect` isn't really used: anywhere that we redirect through the interstitial, we want to sign the URL so that we only redirect to intended destinations. So …
=> Deprecate signed_redirect, unsigned_redirect tags

.env_SAMPLE, cfgov/research_reports/management/commands/parse_research_report.py, cfgov/research_reports/management/commands/trigger_jenkins_build.py, cfgov/research_reports/models.py
🚧  This is a Reports as Webpages PR, not going into cfgov-refresh yet 🚧 
---
Two changes here:
1. On Build and Production, use the Jenkins API to trigger the report processing job remotely
- I've opened a PR to our ansible repo to supply values for the given environment variables in the Build and Production envs.
- Unfortunately there's not a good way to locally test this change. I tested by using my personal Jenkins credentials and setting `RESEARCH_REPORT_JENKINS_JOB` to a test job I put up on our test jenkins server. 
- Once this branch is merged in to the main branch and deployed to Build, it'll be testable there.
2. When saving the draft of a report, associate a user with the revision, to make revision history more understandable. Previously the associated user was `None`.
- You can …
=> Reports as Webpages: Connect Jenkins API

requirements/libraries.txt
Eliminates a warning about an unused dependency.
- Updates crtool package to 2.0.2
=> Update curriculum-review-tool to 2.0.2

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html, cfgov/unprocessed/apps/regulations3k/css/reg-text.less
Currently, there's no bottom margin between the notification on an iRegs landing page and the links that follow it. There should be a 30px margin between the notification and links.
See GHE/CFGOV/platform/issues/3513 for more details.
---
- Change the HTML and CSS that control the margin between notifications and the list of links on iRegs landing pages
1. Visit the landing page of a previous or future version of a regulation in production, like https://www.consumerfinance.gov/policy-compliance/rulemaking/regulations/1005/2019-04-01/. Note the lack of margin between the "This version is not the current regulation" notification and the link list below it.
2. Visit the same regulation landing page in this branch and make sure there's 30 px margin between the notification and the link list. …
=> Fix spacing around iRegs notifications

test/cypress/pages/admin/admin.js
Correct the name of the "Page Metadata" menu item in the admin functional test for the page metadata reports.
=> Fix name of Page Metadata in admin tests

Jenkinsfile
Moves to a shared label between the docker-agent and docker-backup-agent. This will double the number of executors we can run on.
=> Move to generic docker label to expand jenkins agent options

tox.ini
We had the tox venv update plugin commented out. This change uncomments to restore it to use.
=> Restore tox venv update plugin

.github/workflows/backend.yml, .github/workflows/frontend.yml
For some reason, our existing attempt to checkout the master branch in the coverage checks to compare coverage of the current branch against master stopped working.
So that coverage checks stop failing, this change fetches all branches and tags in that job. It seems to add about 40s to the run time.
**This is temporary** until we can find a way to checkout  just the current branch and master in this job. This will stop our coverage check from erroring.
=> Temporarily fetch all tags and branches when checking coverage

requirements/libraries.txt
In order to prepare to support Wagtail 2.10 openpyxl version needs to be newer than 2.5.8
Refer to https://openpyxl.readthedocs.io/en/stable/changes.html#id9 for the bug fixes
=> Update openpyxl from 2.5.8 to 3.0.3

cfgov/v1/wagtail_hooks.py
Previously the Page Metadata report was admin-only. This change ensures anyone with access to the Wagtail Admin can see the page metadata report for live Wagtail pages.
1. Login as a user that's not `admin` but does have access to "CFGov" pages in permissions (like "Internal Editor") and observe that the "Reports" menu does not include "Page Metadata"
2. Check out this branch.
3. Refresh, and notice "Page metadata" now appears, can be viewed, and can be exported.
=> Allow any admins to view page metadata report

cfgov/legacy/templates/front/base_update.html
The legacy base_update.html template currently includes a header link to a [/comments/feed/](https://www.consumerfinance.gov/comments/feed/) URL that no longer exists and returns 410 gone.
An example live page that uses this template is https://www.consumerfinance.gov/data-research/consumer-complaints/.
This commit removes the link to this feed.
=> Remove broken feed from legacy base template

cfgov/cfgov/urls.py
Originally added the documents route to a section that was only loaded if we enable the admin, this moves it to always be provided.
---
- Where we define the document URL.
1.
- Resovles a production issue with some links.
=> Move where we add the documents url

cfgov/core/middleware.py, cfgov/core/tests/test_middleware.py
Prevents 500s when content-type is mysteriously unset
=> ParseLinksMiddleware shouldn't error if responses don't contain Content-Type

requirements/wagtail.txt
We're not *quite* ready to ship 2.10. This change temporarily reverts to 2.9.3.
=> Revert to Wagtail 2.9.3 for now

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
Since the Notification block has been removed from the TDP Activity Search page, the top border is no longer necessary between the hero and the the search form.
---
- Removed the top border from the search block on the TDP Activity Index page.
=> [TDP] Remove the top border on the TDP Activity Index page

cfgov/hmda/templates/hmda/orange-explorer.html
Now that we have a date for the HMDA Explorer sunsetting, we need to update our messages about the sunset to show the date and links to additional resources.
Some slight content tweaks might still be coming, so we can hold on this review for now.
- Update HMDA Explorer sunset message
1. Visit `/data-research/hmda/explore`.
2. Make sure the banner at the top matches the screenshot below.
3. Make sure the links in the banner go to the right places.
=> HMDA Explorer: Update sunset message

requirements/libraries.txt
Fixes translation error in the global search box, which recently started using a translation from the retirement app.
=> Update the version of retirement to 0.15.0

cfgov/jinja2/v1/_includes/molecules/global-search.html, cfgov/locale/es/LC_MESSAGES/django.po, cfgov/unprocessed/js/molecules/GlobalSearch.js
The button that expands the search contains the text "Search" … but for mobile use-cases, it also contain the "Close". This PR adds logic to set the aria-label attribute of that button to whatever state the global search is in (expanded or collapsed).
- Set `aria-label` on global search button.
1. Visit the live homepage and run a lighthouse report and see "Buttons do not have an accessible name" error.
2. Pull and run this branch and generate a lighthouse report for it and see that the accessibility error is gone.
=> Global Search: Set aria-label on search/close button

cfgov/v1/tests/views/test_login_views.py, cfgov/v1/views/__init__.py
Addresses https://github.local/CFGOV/platform/issues/3863
Very well may be that a more global solution to this problem is preferred, but this fixes the bug as it stands with no side-effects that I'm aware of.
=> Redirect to /admin/ from /login/ when already logged in

cfgov/v1/templates/v1/_list_page_metadata.html, cfgov/v1/tests/views/test_metadata_report_view.py, cfgov/v1/views/reports.py
This satisfies https://github.local/CFGOV/platform/issues/3862, a request to add
category and tag fields to the Wagtail page metadata report.
visit http://localhost:8000/admin/reports/page-metadata/ and note two new
columns at top right, TAGS and CATEGORIES.
The XLSX and CSV download options should deliver spreadsheets with the new fields.
The download of all cfgov pages takes up to a minute.
=> Add category and tag fields to the page metadata export

cfgov/cfgov/settings/base.py
This is needed to be able to use our new audio players that serve files uploaded to the Wagtail Media library, landing on files.consumerfinance.gov.
- `CSP_MEDIA_SRC` setting for django-csp
- `files.consumerfinance.gov` entries in other CSP lists, when the `*.consumerfinance.gov` wildcard should handle it just fine (we had added the explicit reference in a fit of haphazard troubleshooting, but the problem was not that)
Don't think we really can until it gets to production, unless the buildfiles bucket actually works somewhere that this branch can be deployed to.
=> Create new CSP allowlist for media files

requirements/libraries.txt
Updates the CCDB5-UI package to include IE11 bugfixes.
---
- None
- None
- CCDB5-ui Library package update
1. Make sure CCDB5 Search loads in IE11
=> Bump for ccdb5-UI IE11 Bugfix

requirements/libraries.txt
We need to temporarily install a CFPB fork of wagtail-autocomplete to
facilitate the editing of Ask CFPB content while the project's origin repo 
works on [a PR](https://github.com/wagtail/wagtail-autocomplete/pull/77) we pushed to them.
The PR has been approved, but it may take some time to get it merged and for
a new release to be issued to PyPI.
This is a temporary fix for https://github.local/CFGOV/platform/issues/3862
1. In current master, open http://localhost:8000/admin/pages/5804/edit/ and note the server error(s) generated by the autocomplete API calls. They will show up in your local server window and in the network pane of dev tools.
Also note that the related-questions and redirect-to-page fields don't work.
2. Pull in this branch, install libraries with `pip install -r …
=> Install wagtail-autocomplete from fork

Jenkinsfile
This change replaces all references to the `master` branch in our `Jenkinsfile` to `main`.
=> Replace master branch with main

cfgov/cfgov/settings/test.py
This is causing a problem over on #5984 by activating the placeholders in tests, and it may have been hiding other problems.
Felt worthy of its own PR, so it didn't go unnoticed in #5984. 
- `settings/test.py` now imports from `base.py`, not `local.py`, and a few necessary settings from `local.py` have been copied over
1. `tox`
=> Stop importing from local settings in test settings

cfgov/ask_cfpb/documents.py, cfgov/ask_cfpb/models/__init__.py, cfgov/ask_cfpb/models/pages.py, cfgov/ask_cfpb/tests/models/test_pages.py, cfgov/ask_cfpb/tests/test_views.py, cfgov/ask_cfpb/views.py, cfgov/cfgov/settings/test.py, cfgov/cfgov/urls.py, cfgov/legacy/views/complaint.py, cfgov/search/backends.py
This adjusts ask_cfpb unit tests to run using configuration
for the django-elasticsearch-dsl package.
- A strip-tags helper to prevent the "mortgageA" problem, wherein some headings
can get mashed together with following text after tags are stripped
for indexing.
- Some linting and debugging
There were some bugs around the json api that have been fixed, but there are still three related tests commented out because of a mocking issue.
=> Add Elasticsearch 7 tests

cfgov/ask_cfpb/models/pages.py, cfgov/jinja2/v1/ask-cfpb/see-all.html
Our contacts at Google alerted us to an oversight of mine when I implemented our DefinedTerm markup: the URL for each term that goes in the `<link itemprop="url" href="{URL}">` tag was missing the `key-terms/` part of the URL. Turns out, our use of RoutablePageMixin to generate the Key Terms pages meant that the `page.full_url` tag was not including that `key-terms/` part of the URL.
~~I tried using the `routablepageurl` template tag, but that only returns a root-relative URL, whereas we need an absolute URL, and it required hardcoding a `category='key-terms'` kwarg, anyway, so we might as well just hardcode it this way.~~
/cc @kelleyholden 
1. Visit http://localhost:8000/consumer-tools/auto-loans/answers/key-terms/, inspect the markup for a term, and see that the `<link itemprop="url" …
=> Add missing `key-terms` slug to DefinedTerm URL tag

cfgov/jinja2/v1/_includes/organisms/sidenav-toc.html, cfgov/unprocessed/apps/research-reports/js/index.js
Take two on #5797 
MVP table of contents for small screens on Reports pages
---
GHE/CFPB/super-regular/issues/74
this is based on the reports-as-webpages branch
- add expandable js to Reports js
- extraneous css & list classes in the table of contents markup
- add expandable to table of contents template
1.
- not sure if anything broke JS-wise so let me know
_[Feel free to delete any checkboxes that are not applicable to this PR.]_
- Consider prefixing with the feature/section you're addressing, e.g., "Mega Menu: fix layout bug" or "Paying for College: Update content on Repay tool"
- [This repo’s docs](https://cfpb.github.io/cfgov-refresh/) (edit the files in the `/docs` …
=> Reports as webpages: Table of contents for small screens, with sticky nav & expandables

cfgov/mega_menu/management/commands/export_mega_menu.py, cfgov/mega_menu/management/commands/import_mega_menu.py, cfgov/mega_menu/tests/management/commands/test_export_mega_menu.py, cfgov/mega_menu/tests/management/commands/test_import_mega_menu.py
This commit adds two new management commands for exporting and importing mega menu content to and from JSON. These commands will enable easier and more repeatable updating of menu content.
To export:
`cfgov/manage.py export_mega_menu language output.json`
OR
`cfgov/manage.py export_mega_menu language` (writes to stdout)
For example:
`cfgov/manage.py export_mega_menu en current.json`
To import:
`cfgov/manage.py import_mega_menu language input.json`
OR
`cfgov/manage.py import_mega_menu language` (reads from stdin)
For example:
`cat new.json | cfgov/manage.py import_mega_menu en`
The JSON format used is the content of the existing [`Menu` object's `submenus` StreamField](https://github.com/cfpb/consumerfinance.gov/blob/a1a0b05f239ce348eea5e937956042d570803993/cfgov/mega_menu/models.py#L18). …
=> Add management commands to export/import mega menu

Jenkinsfile, docker-stack.yml, docker/elasticsearch/Dockerfile
This replaces the 2 separate ES 2.3 / 2.4 images, used in docker-compose.yml and docker-stack.yml, with a single image.
This image is based on CentOS7 and downloads and installs ES 2.3.5 from Elastic. It ensures the same image is used in both local development and in a docker cluster. We hypothesize this _may_ help with ES flakiness in the docker cluster, though that is admittedly a long shot.
Addresses APPOPS-1201
We have had success with an identical approach to older ElasticSearch images, in a different stack. It's _possible_ that this approach will be more stable in the docker cluster. It also has the benefit of using the exact same image for both local development and in the cluster.
1. Follow the documented procedures for creating a local docker development environment for …
=> Replaces the ElasticSearch 2.3 and 2.4 images with a single 2.3.5 image

cfgov/mega_menu/frontend_conversion.py, cfgov/mega_menu/tests/test_frontend_conversion.py
We want a mega menu submenu to be highlighted (i.e. appear visually selected) when users are on a child page of that submenu.
The current logic assumes that we can determine this by comparing URL paths; for example, if a submenu contains a link to /foo/, and the user is on /foo/bar/, then we should highlight the submenu.
For increased flexibility, we also want to support the case when menu items point to links with query strings, for example /foo/?something. In this case, we want a page like /foo/bar/ to also mark the submenu as selected. This commit alters the logic so that we strip off the menu link query string before comparing it to the request path.
Note that this logic only applies to the top-level highlighting of submenus (for example Consumer Tools on the current site). This …
=> Improve mega menu submenu highlighting

requirements/libraries.txt
This change removes comparisontool code and haystack indexing code,
so that indexing no longer hits the comparisontool tables.
This will allow us to archive and drop the comparisontool tables from our
production database.
There are only 3 static pages left that are served from the satellite repo.
- https://www.consumerfinance.gov/paying-for-college/choose-a-student-loan/
- https://www.consumerfinance.gov/paying-for-college/manage-your-college-money/
- https://www.consumerfinance.gov/paying-for-college/repay-student-debt/
=> Bump the django-college-costs-comparison version to 1.17.0

cfgov/mega_menu/frontend_conversion.py, cfgov/mega_menu/tests/test_frontend_conversion.py
This change modifies the existing mega menu logic to prevent duplicate highlights in the mega menu, for cases where a menu link is duplicated between submenus.
The code now ensures that only at most one submenu and at most one link gets highlighted.
Edit the mega menu to duplicate a link between two submenus. Internally, see UCP PR deployment for this running live with an example.
=> Prevent duplicate highlights in mega menu

cfgov/scripts/validate_mega_menu.py
This new command line script allows for checking of mega menu links on a running cf.gov server. To run against www.consumerfinance.gov:
```
cfgov/scripts/validate_mega_menu.py
```
or to run against an alternate server:
```
cfgov/scripts/validate_mega_menu.py http://localhost:8000
```
The script checks each link in the mega menu (as it appears on the homepage) and validates that the link can be fetched with a 200.
To test, run a local server, edit the English menu (http://localhost:8000/admin/mega_menu/menu/edit/en/) and add a broken link. Run this script against localhost and it will fail.
- Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker …
=> Add script for mega menu link checking

cfgov/scripts/validate_redirects.py
This new script allows for validation of a set of redirects as defined in a CSV or XLSX file. The first line of the file will be ignored as headers. The "from" and "to" paths default to being read from the 6th and 7th column of the input file, respectively.
To run against www.consumerfinance.gov, using an input XLSX:
```
cfgov/scripts/validate_redirects.py redirects.xlsx
```
To run against localhost, using an input CSV:
```
cfgov/scripts/validate_redirects.py redirects.csv http://localhost:8000
```
To specify alternate CSV columns for the "from" and "to" paths:
```
cfgov/scripts/validate_redirects.py redirects.xlsx --from-index=1 --to-index=2
```
To test, run without one of the redirects and observe that the check fails. Now add the redirect and note that the check passes as long as it …
=> Add script for validating redirects

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
The `FINANCIAL_WELLBEING_HUB` is out of Beta testing and is now a permanent feature in Wagtail. We won't need to turn off the pages via a feature flag, so we may as well remove it.
This will simplify the IA refresh migration.
- `FINANCIAL_WELLBEING_HUB` flag and flagged url
1. Run this branch, see that the "Financial well-being" pages still work
=> Remove unused FINANCIAL_WELLBEING_HUB feature flag

cfgov/legacy/templates/front/base_nonresponsive.html
`page_js` is used by the supervision page http://localhost:8000/jobs/supervision/ 
`app_modal` is unused.
- Re-add erroneously deleted `app_js` block.
- Remove unused `app_modal` block.
1. Buttons should scroll page on http://localhost:8000/jobs/supervision/
=> Replace app_modal with page_js

cfgov/apache/conf.d/redirects.conf, cfgov/cfgov/urls.py
(This PR is to the ia-direct-apache-redirects branch, not main!)
This commit moves three redirects from Django to Apache:
1. (required due to IA changes)
From: /educational-resources/*
To (before): /practitioner-resources/*
To (after): /consumer-tools/educator-tools/*
2. (not needed due to IA changes, still belongs in Apache)
From: /practitioner-resources/money-as-you-grow/*
To: /consumer-tools/money-as-you-grow/*
3. (not needed due to IA changes, still belongs in Apache)
From: /practitioner-resources/resources-for-older-adults/managing-someone-elses-money/*
To: /consumer-tools/managing-someone-elses-money/*
Run using the local [production-like Docker setup](https://cfpb.github.io/consumerfinance.gov/running-docker/#production-like-docker-image), and test these redirects, using for …
=> Move certain Django redirects to Apache

cfgov/apache/conf.d/redirects.conf, cfgov/cfgov/urls.py
This PR is going into the `ia-direct-apache-redirects` branch, not `main`!
- Some corrections to `redirects.conf` to remove duplicate redirects and remove redirect chains
- Move `practitioner-resources` paths defined in `urls.py` to the new URL structure
=> IA refresh: Move non-Wagtail pages

cfgov/jinja2/v1/_includes/organisms/footer.html
HOLD until IA launch
Adds "About Us" and "Events" to the global footer & removes "Newsroom"
=> Add about us and events to footer; remove newsroom

cfgov/scripts/add_wagtail_redirects.py, cfgov/scripts/move_wagtail_pages.py, cfgov/scripts/pages_to_redirect.py
Add three scripts that we will use to update consumerfinance.gov to its new IA next week.
1. `pages_to_redirect`, which takes a CSV of top-level pages that will move along with their children. Generates a full list of all URLs that will require Wagtail redirects.
2. `add_wagtail_redirects`, which takes the output of `pages_to_redirect` and uses it to add all necessary Wagtail redirects
3. `move_wagtail_pages`, which takes the same CSV as `pages_to_redirect` and moves all Wagtail pages to their new URLs.
1. Get a copy of our latest "Current redirects" spreadsheet and convert the first tab to CSV. There's a link to it in GHE/CFPB/super-regular/issues/148.
2. Get a recent Production database dump.
3. On this branch, from the project root, run the following: `cfgov/manage.py runscript …
=> IA Refresh: Scripts to add redirects and move Wagtail pages

cfgov/scripts/validate_redirects.py
The current redirects validation script (validate_redirects.py) assumes  that the server responds with redirects pointing to relative paths, like Django returns. Apache instead returns absolute paths, which fails the script. This change makes it so that the script properly handles either case.
You can test this using an input spreadsheet that includes an Apache-served redirect; internally this can be demonstrated now on UCP stack 6024.
=> Fix validate_redirects.py to handle absolute paths

cfgov/unprocessed/css/organisms/mega-menu.less
Closes https://github.local/CFPB/super-regular/issues/162
Previously, between 901px and 1260px, the width of the mega menu flyout could change based on the content. This was somewhat hard to reproduce  and resolved around `display: table-cell` weirdness of the child columns.
This now sets an explicit `width: 100%;` between those dimensions, which keeps the flyout a constant width, not matter the number of columns/presence of an overview link, etc.
Before:
After:
=> Make mega-menu content-2 flyout width content-independent

requirements/libraries.txt
This hotfix is needed to fix legacy PFC pages' references to the now-deleted jQuery 1.9.1.
See: https://github.com/cfpb/django-college-costs-comparison/pull/38
=> Update django-college-costs-comparison to 1.17.1 to fix missing jQuery

test/cypress/integration/pages/ask-cfpb.js, test/cypress/pages/ask-cfpb/search.js
This change adds integration tests that test for the Ask CFPB autocomplete and spelling suggestion search features.
Run `yarn run cypress open` and then select `ask-cfpb.js` under `pages` in the Cypress dialog. Observe that it tests autocomplete, that there are search results, and that a misspelled search is corrected.
=> Add functional tests for Ask CFPB search features

docker-compose.yml
postgres:10.3 is old and not updated. postgres:10-alpine is frequently updated.
We're already using postgres:10-alpine in docker-stack.yml, so this change creates consistency in the local and dev stack use cases
APPOPS-1192
=> Replaces old postgres:10.3 with postgres:10-alpine

cfgov/cfgov/settings/base.py, docker-compose.yml, requirements/libraries.txt
Decomposes more of the Ask-CFPB work we've been doing into smaller PRs. This builds onto #6052 which now involves deploying ES7 as part of our docker stack. We've setup a flag in our ansible configuration to determine if we should configure connections to an AWS ES Cluster, or if we should default back to our standard configuration and default to an empty connection string if there is no configured ES7 Host.
---
- Configure and include django-elasticsearch-dsl connection in `base.py` including working configuration with an AWS ES Cluster if provided.
- Forked elasticsearch-dsl dependency where we reference elasticsearch as elasticsearch7
- requests_4awsauth to connect with AWS ES.
1. App should be able to run locally, on docker enterprise, and on a DEV server even if configuration is …
=> Add libraries for django-elasticsearch-dsl and deploy configuration

cfgov/v1/tests/management/commands/test_add_images.py, requirements/ci.txt
Must've missed this a while back when we ditched Python 2.
1. See that the tests continue to pass
=> Remove last vestiges of the six library

cfgov/jinja2/v1/_includes/molecules/pagination.html
Closes #2199 from over 4 years ago!
The problem here stemmed from the use of `request.GET.items()`, which returns only the last value when multiple params have the same key, by design.
See https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.QueryDict.items
Changing to `.lists()` and updating the logic a bit to handle the resulting lists stops params from being dropped.
Also, filtering out the 'page' param prevents the other bug here which was repeated page params in the querystring.
=> Keep duplicated filterable list params when paginating

cfgov/v1/jinja2tags/__init__.py
The image placeholder library, introduced in #5984, will sometimes replace the `image` object, expected by `alt_text`
handling logic in our `jinja2tags/__init__.py`, with a `Placeholder` object with a different interface. This PR slightly extends that logic to exit gracefully when the image interface is not as expected.
- On main visit http://localhost:8000/about-us/blog/?categories=at-the-cfpb&categories=directors-notebook&page=3
- Should 500
- Pull branch
- Visit the same page, should see a bunch of blog posts (some with kitten images) and no 500.
=> Fixes bug introduced by #5984

cfgov/agreements/jinja2/agreements/index.html
Add Q2-2020 data to the Credit Card Agreements database. Also adds a statement about possible omissions in the data set, as requested by the stakeholder.
1. Visit http://localhost:8000/credit-cards/agreements/
2. Ensure the links to Q1-2020 and Q2-2020 data work, as well as the links to the Regulatory Flexibility Statement.
- The dropdown on the Credit Card Agreements page still contains Q1-2020 data. Updating that doesn't require a PR, and will happen soon.
=> Update Credit Card Agreements with Q2-2020 data

cfgov/templates/wagtailadmin/reports/site_history.html, cfgov/v1/templates/v1/page_metadata_report.html
The XLSX download option was error-prone for page metadata reports,
possibly because of their size. The XLSX option required that the data be
held in memory before output, whereas the CSV option allows
for a more efficient streaming process.
In any case, not much is lost by removing the option, because the CSV can be
opened in Excel, which then saves the result as an .xlsx file by default.
The XLSX option was also removed from the site-history report.
There should be no change in the CSV download option, which takes a bit of time to download.  
But the icon at the top right of the report page at `Reports -> Page Metadata` should change to a single choice:
Before:
Using this branch:
=> Remove option to export page metadata as an .xlsx file

cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py
This may not be much more efficient or elegant, but the order of preference seems clearer.
We don't lint v1 tests, but I also cleaned up some trailing-space issues in the tests.
=> Break meta-description ranking into function

cfgov/data_research/mortgage_utilities/s3_utils.py
Not sure why this cropped up now, but along the way we lost the ability
to feed a file object to boto3 for uploading to S3. Boto creates a
hash of the content and expects bytes in making the hash, and
our previous routine delivered unicode.
The solution is to pass the bytes instead of the file object to boto,
by calling `getvalue()` on the file object.
I ran the zusa prep job `cf.gov-nmdb-data-prep` against this branch, and it succeeded. The charts on DEV5 and CSV downloads on S3 look good.
=> Fix the nmdb CSV export by calling getvalue()

cfgov/v1/models/filterable_list_mixins.py
This commit alters the default pagination size for filterable lists from 10 to 25.
1. Visit http://localhost:8000/about-us/blog/ and see that 25 results are shown, as opposed to https://www.consumerfinance.gov/about-us/blog/ where only 10 are shown.
Assessment of backend performance / database queries associated with this change.
=> Change default filterable list results to 25

cfgov/cfgov/settings/base.py, cfgov/regulations3k/documents.py, cfgov/regulations3k/models/pages.py, cfgov/regulations3k/tests/test_documents.py, cfgov/regulations3k/tests/test_models.py
Places ES7 search functionality behind a toggle.
---
- Moving search code to work with ES7 behind flag.
- Add short_name to index to reduce need to query DB for data needed.
- configure boost for text field to improve results
- swap section_order to Keyword Field so we can sort by it.
1. Enable `ELASTICSEARCH_DSL_REGULATIONS` flag
2. Load up ES7 index `cfgov/manage.py search_index --rebuild -f --parallel`
3. Search regulations
- Seeing a large discrepancy in search result counts. "mortgage" is off by nearly 300 records.
- [This repo’s …
=> Add Elasticsearch 7 support to regulations search behind a flag

cfgov/ask_cfpb/documents.py, cfgov/search/elasticsearch_helpers.py
The analyzers and filters are generic and can be used by both ask_cfpb and paying_for_college
- Add analyzers and filters in search `elasticsearch_helpers.py`
- Delete analyzers and filters from ask_cfpb `documents.py`
- Moved analyzers and filters from ask_cfpb `documents.py` to search `elasticsearch_helpers.py`
1. tox -e unittest-current ask_cfpb.tests.test_documents
- CFGOV/platform wiki on GHE – for …
=> Moved analyzers and filters from ask_cfpb to elasticsearch_helpers.py

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py
The current use of `os.path.join` in base and local settings results in a malformed host
value (below), in which the port signifier ':' is surrounded by slashes:
```python
{
'ELASTICSEARCH_DSL': {'default': {'hosts': 'http://localhost/:/9200'}}
}
```
Elasticsearch then reads the ':' as an index name and raises a naming error:
```bash
"Invalid index name [:], must not contain ':'")
```
The error was repeated in the `local.py` settings, but I don't think we need the setting there, because it will get picked up from  from `base.py`. So I removed it.
- On main, enable one of the DSL flags and try running `./cfgov/manage.py search_index --rebuild`
Currently you should get an error.
- Running an ES7 index job on this branch should succeed.
=> Fix the ELASTICSEARCH_DSL settings

Jenkinsfile, docker-compose.yml, docker/elasticsearch/7.7/Dockerfile
Upgrades our local Elasticsearch version from 7.4 to 7.7 to reduce the number of twistlock vulnerabilities being reported.
---
- Alpine Elasticsearch base image from 7.4 -> 7.7
- Alpine Kibana image from 7.4 -> 7.7
1. Run the stack locally
=> Upgrade local Elasticsearch from 7.4 to 7.7

docs/debugging-monitoring.md, requirements/deployment.txt
This change bumps the version of the New Relic Python agent from 4.18.0.118 to [5.20.1.150](https://github.com/newrelic/newrelic-python-agent/releases/tag/v5.20.1.150). Release notes for the agent are [here](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes).
A couple of notable improvements that stand out:
- Real-time event streaming (5.2.0.127): data is now sent to New Relic every five seconds, instead of every minute.
- Support for Python 3.8 (5.2.3.131) and 3.9 (5.20.1.150)
To test this locally, see [here](https://cfpb.github.io/consumerfinance.gov/debugging-monitoring/#monitoring-using-new-relic).
Updated docs:
=> Bump New Relic Python agent version to 5.20.1.150

requirements/libraries.txt
We've fixed a couple of bugs in the retrirement app: preventing the retirement translations from leaking into other parts of the site and getting the Spanish mega-menu showing on the Spanish about page. See GHE/CFGOV/platform/issues/3912 for more details.
---
- Bump retirement to [0.15.1](https://github.com/cfpb/retirement/releases/tag/0.15.1)
- Match the cfgov plurals config for translations (https://github.com/cfpb/retirement/pull/263)
- Show the Spanish mega-menu on about page (https://github.com/cfpb/retirement/pull/265)
1. Go to the the retirement tool's Spanish about page, `/consumer-tools/retirement/before-you-claim/about/es/`. Verify that the Spanish mega-menu is showing on that page.
2. Fill out the Spanish financial wellbeing survey, `/consumer-tools/financial-well-being/es/`, …
=> Bump retirement to 0.15.1

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html, cfgov/v1/forms.py, cfgov/v1/jinja2tags/__init__.py, cfgov/v1/models/filterable_list_mixins.py, cfgov/v1/tests/jinja2tags/test_jinja2tags.py, cfgov/v1/tests/models/test_filterable_list_mixins.py, cfgov/v1/tests/test_filterable_list_form.py
This PR adds the ability to filter based on the archive status of pages to our filterable list controls.
If the filterable pages in the filterable list contains archived pages, the option to either exclude, include, or only filter archived pages will be presented to users (defaulting to exclude).
1. Visit a filterable list page, i.e. http://localhost:8000/data-research/research-reports
2. Observe that the option to filter based on archived items does not appear
3. Archive a page that is within that filterable list page and publish the change
4. Observe that the option to filter based on archived items does appear
5. Observe that the newly archived page is excluded from the results by default
This PR intentionally preserves for now the ability to set filterable pages to include archived …
=> Add archive options to Filterable List Controls

test/cypress/pages/admin/admin.js
Test should no longer fail occasionally since it now waits for the search result ID instead of just 3 seconds which should account for slow search results
---
-
-
-
1.
-
=> Try to fix Cypress test race condition by waiting for search results id to be visible

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, cfgov/prepaid_agreements/forms.py, cfgov/prepaid_agreements/tests/test_views.py, cfgov/prepaid_agreements/views.py
This change uses Django forms to validate and sanitize the prepaid agreements search parameters.
It adds two forms. `SearchForm` and `FilterForm` that handle the search fields and the filter fields, respectively. These are two separate forms because the filter choices depend on the results from the search.
At present this does not present any information to users on the validity of the form submission — default results will be returned for search if the search query, field, or results page number are not valid; the default filter selection (i.e. no filters) will be returned if any filter option is invalid.
The motivation for this change is to prevent a 500 error on invalid filters.
This change also removes the `PREPAID_AGREEMENTS_SEARCH` feature flag.
Compare the results from a search …
=> Use Django forms to sanitize and validate prepaid search parameters

cfgov/v1/forms.py, cfgov/v1/models/learn_page.py
This started throwing a 500 with the addition of #6080. It needed its custom `get_query_strings` method to get the same `is_archived` addition as the general `FilterableListForm`.
I'm not sure why this doesn't also need to be done for the `EventArchiveFilterForm` just below this one.
---
-
-
-
1.
-
- CFPB/hubcap wiki on GHE – for internal …
=> Fix EnforcementActionsFilterForm

cfgov/prepaid_agreements/views.py
This changes moves where we get the page number from the search form up into the same block where we ensure the form is valid.
If the form was not valid, we were still trying to get the `page` from the form's cleaned_data, and that could fail. This fixes that issue.
Try to give the prepaid search an invalid `page`, i.e.: 
http://localhost:8000/data-research/prepaid-accounts/search-agreements/?page=3?page=3
And notice this 500s on `main`, but does not on this branch.
=> Prepaid: Ensure that the paginator is always getting a valid page

cfgov/unprocessed/css/molecules/multiselect.less
Chrome barfs when the multiselect fieldset has a background color and
its child unordered list doesn't. I haven't been able to figure out *why*
it barfs but moving the bg color fixes it.
Demo: https://codepen.io/contolini/pen/KKMoPEY
| ![multi-before](https://user-images.githubusercontent.com/1060248/97896961-ce689580-1d03-11eb-9e68-fbdae0d5cb87.gif)   | ![multi-after](https://user-images.githubusercontent.com/1060248/97896973-d294b300-1d03-11eb-8ee4-e7365a6884be.gif)  |
- Move `background-color` from multiselect fieldset to unordered list.
1. Visit the [blog](https://www.consumerfinance.gov/about-us/blog/) in Chrome (I'm on v86).
1. Open the Topic multiselect and scroll through the long list. Notice how Chrome struggles to paint the list of options. …
=> Tweak multiselect background color to prevent browser bug

cfgov/unprocessed/apps/paying-for-college/js/util/url-parameter-utils.js
Currently a few of the college costs app user-entered values are not being preserved in the URL. This PR updates the variable names in the URL map so the values will be correctly added to the query string.
- Updates to URL map
2. Run `gulp scripts:apps`
3. Navigate to [college costs app](http://localhost:8000/paying-for-college/your-financial-path-to-graduation/?iped=131469&houp=onCampus&typp=bachelors&lenp=4&depp=dependent&cobs=n&tuit=55230&hous=13850&book=1325)
4. Enter values in the following fields
- Costs page: Additional financial obligations
- Grants & scholarships: Other federal grants, Military tuition assistance, GI Bill, Other (Yellow Ribbon, etc)
- Other sources: Other funding
5. Copy the URL, open it in another tab, and verify that the values entered in …
=> P4C: Fix URL map

cfgov/unprocessed/apps/paying-for-college/js/dispatchers/update-models.js
This PR fixes a bug occurring when user loads a school from the URL but the expenses region does not match the school's default region.
- Add line to `updateSchoolData` that updates the expenses model with appropriate region data
1. Bring it down.
2. Choose a school in Texas, for instance.
3. Check that the Region on the "Can I afford my payment?" page is "South" (if you picked a school in Texas, for instance)
4. Copy the URL of your page and load it in a new window (or reload the page, that should work). Check again that the region on the "Can I afford my payment?" page is "South."
=> Paying for College - Fix Expenses Selection

cfgov/jinja2/v1/_includes/atoms/checkbox.html, cfgov/jinja2/v1/_includes/atoms/radio-button.html, cfgov/jinja2/v1/_includes/organisms/email-popup/base.html, cfgov/jinja2/v1/_includes/organisms/email-signup.html, cfgov/jinja2/v1/_includes/organisms/full-width-text.html, cfgov/jinja2/v1/owning-a-home/_templates/brand-footer.html, cfgov/regulations3k/jinja2/regulations3k/search-regulations.html, cfgov/v1/jinja2tags/__init__.py, cfgov/v1/templatetags/email_popup.py, cfgov/v1/tests/jinja2tags/test_jinja2tags.py
The new `unique_id_in_context` method will replace the use of `get_unique_id` method to generate unique identifiers for form inputs. `get_unique_id` would generate a random sequence of characters on each page load, meaning the input id would always change. This caused an issue for our web archive, since it caused unnecessary diffs on pages that didn't have substantive changes.
With `unique_id_in_context`, the markup for input forms should remain consistent between page loads, which will allow the web archive to be more useful and not contain superfluous diffs.
- `unique_id_in_context()` method and jinja tag
- Update several templates to use `unique_id_in_context()` instead of `get_unique_id()`
2. Visit a page that contains an email sign-up form, such as …
=> Consistent IDs for form inputs

Dockerfile
I'm noticing our docker deployments are failing to spin up healthy python containers. It looks like it could be due to indexing all our elasticsearch servers is taking longer than the currently allocated 15 minutes and 15 seconds. While unclear why this is taking additional time recently, this seems like an opportunity to add some additional resiliency.
---
- Start Period 15s -> 300s
1. Changes to docker deploy, will be done via monitoring deployments.
-
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for …
=> Increase docker start period to improve deployments.

cfgov/prepaid_agreements/scripts/write_prepaid_agreements_data_to_csv.py
This change will catch the exclusion that was not happening in the CSV files creation
Added a check for the product's `deleted_at` status in the `write_prepaid_agreements_data_to_csv` and not write agreements whose products have been deleted to the CSV files
1. git checkout fix-3913
1. cd cfgov
1. ./manage.py runscript write_prepaid_agreements_data_to_csv
Use the following url to search for agreements matched for a specific product:
https://www.consumerfinance.gov/data-research/prepaid-accounts/search-agreements/?search_field=all&issuer_name=Sunrise+Banks%2C+National+Association
Verify the number of matches are identical to that in the CSV file using grep as follows:
```
$ grep "Sunrise Banks, National Association" prepaid_metadata_recent_agreements.csv|wc -l
92
```
- PR titles are used …
=> Prepaid search: Handle product deletions when writing CSV files

docker-compose.yml
This prevents your running Docker containers from being hit by network-wide security scans.
1. Pull branch
1. Ensure `docker-compose up` continues working as expected
- I believe this causes a conflict between the Postgres container and a running local Postgres service, if you happen to have both. As far as I can tell, the best workaround is simply to stop the local service when firing up the container.
=> Add explicit 127.0.0.1 IP addresses to docker-compose.yml

cfgov/search/elasticsearch_helpers.py
Fixes variable name typo, use "synonym" instead of "synonynm".
=> Fix typo: synonynm -> synonym

cfgov/paying_for_college/models/disclosures.py, cfgov/paying_for_college/tests/test_models.py
The newish [financial-path tool](https://www.consumerfinance.gov/paying-for-college/your-financial-path-to-graduation/) is ready to start helping undergraduate users. The initial launch was aimed solely at
graduate programs, so undergrad programs were left out of the API.
This just opens the gate for the `undergrad` portion of the schools' `programCodes` endpoint.
It helps to have a json viewing extension installed in your browser.
- Visit the current school endpoint for Texas Tech (ID 229115), and note that programCodes[undergrad] is an empty list.  
<https://www.consumerfinance.gov/paying-for-college2/understanding-your-financial-aid-offer/api/school/229115/>
- Check out the branch and visit the local endpoint for Texas Tech (ID 229115): …
=> Expose undergraduate programs in the paying-for-college API

cfgov/paying_for_college/static/paying_for_college/feedback/js/feedback.js
https://www.consumerfinance.gov/paying-for-college2/understanding-your-financial-aid-offer/feedback/ has the error `Uncaught ReferenceError: jQuery is not defined`. The jquery script disables the submit button till something is typed into the textarea input. This PR migrates that script off jquery.
- Migrate Paying for College feedback script off jQuery.
1. Visit https://www.consumerfinance.gov/paying-for-college2/understanding-your-financial-aid-offer/feedback/ and see an error in dev console for jquery and the submit button is not disabled.
2. Pull branch and run locally and visit http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/feedback/ and see that submit button is disabled till typing into the textarea input, and there should be no dev console error.
=> Paying for College: Migrate feedback script off jquery

cfgov/apache/conf.d/redirects.conf, cfgov/cfgov/urls.py, cfgov/jinja2/v1/_includes/organisms/footer.html
Addresses:
- https://github.local/CFPB/super-regular/issues/150
- https://github.local/CFPB/super-regular/issues/149
- https://github.local/CFPB/super-regular/issues/167
- https://github.local/CFPB/super-regular/issues/157
1. Add all necessary Apache redirects for the IA Refresh migration
2. Update any existing redirects that are affected by the IA Refresh migration, to ensure we aren't creating redirect chains
3. Update URLs that are defined in Django's `urls.py` to move them to their new URLs.
4. Move some redirects that are defined in Django to Apache's `redirects.conf` instead, to start to reduce the number of places we're managing redirects.
5. Update the global footer to reflect the new IA
We'll be merging and deploying this PR as part of the IA Refresh migration on Wednesday, …
=> IA Migration day: Update Apache redirects, URLs, and site footer

cfgov/scripts/update_existing_redirects.py
The IA migration adds new redirects to Apache's redirects.conf. These make some existing Wagtail redirects outdated. This script fixes the ones we know about immediately. After the migration, we can do a more complete accounting of which redirects are still legitimate.
- `update_existing_redirects` script to correct the set of outdated redirects that causes smoke test failures
- This is a hotfix to get the IA Migration out the door. Once that deadline has passed, we will take more time to create a more effective system around managing redirects and ensuring that all of them are effective.
=> IA Migration: Script to update outdated Wagtail redirects

cfgov/unprocessed/apps/analytics-gtm/webpack-config.js, cfgov/unprocessed/apps/ccdb-landing-map/webpack-config.js, cfgov/unprocessed/apps/find-a-housing-counselor/webpack-config.js, cfgov/unprocessed/apps/form-explainer/webpack-config.js, cfgov/unprocessed/apps/owning-a-home/webpack-config.js, cfgov/unprocessed/apps/paying-for-college/webpack-config.js, cfgov/unprocessed/apps/rural-or-underserved-tool/webpack-config.js, cfgov/unprocessed/apps/teachers-digital-platform/webpack-config.js, cfgov/unprocessed/apps/youth-employment-success/webpack-config.js, config/webpack-config.js
Webpack was not transpiling `@cfpb` node modules coming from the design system.
- Fix incorrect webpack exclude regex to properly include `@cfpb` node modules in webpack transpiling.
1. Pull branch and `gulp clean && gulp build`.
2. Built files in `cfgov/static_built/js/` should not contain `const`.
=> Fix incorrect webpack exclude regex

cfgov/regulations3k/models/pages.py
Implements the AND operator logic for iregs searches to improve the number of results returned for multi word queries. 
---
- Replaced default OR operator with AND for iregs ES7 search.
1. Search phrases instead of single words on iregs with ES7 search enabled. You should see only results all words present be returned.
-
- CFPB/hubcap …
=> Add AND operator to regulations search for Elasticsearch 7

cfgov/ask_cfpb/models/pages.py
The ask_cfpb.ArticlePage model defines a custom search field for the 'title' field, but this field is already included [in the base
Page.search_fields](https://github.com/wagtail/wagtail/blob/cc13aecd7d25163a5deac60c9aea6df3e0a45e1b/wagtail/core/models.py#L494).
Redefining the field like this causes problems when trying to use Wagtail search with an Elasticsearch backend, because it's not possible to change a mapping once it has been created. See [this related Wagtail issue](https://github.com/wagtail/wagtail/issues/4717).
I do note that the base Page definition of the index is slightly different:
`index.SearchField('title', partial_match=True, boost=2)`
as opposed to the simpler form used here:
`index.SearchField('title')`
The git blame doesn't indicate that this change was deliberate in …
=> Remove redundant ArticlePage search field

.github/workflows/backend.yml
Currently we install gettext on all of our backend GitHub Actions runs, even though it is only needed for the 'validate-translations' matrix run. This change modifies the configuration to only install gettext as needed, which should speed up the other matrix runs.
This logic was added in https://github.com/cfpb/consumerfinance.gov/pull/5939.
=> Only install gettext as needed for GitHub Actions

cfgov/jinja2/v1/youth_employment_success/index.html
The title on [the YES transportation tool page](https://www.consumerfinance.gov/consumer-tools/educator-tools/resources-youth-employment-programs/transportation-tool/) is wrong. It says:
> Consumer Financial Protection Bureau Planning how you’ll get to work | Consumer Financial Protection Bureau
but should just be
> Planning how you’ll get to work | Consumer Financial Protection Bureau
=> Fix title on YES transportation tool page

docs/search.md, mkdocs.yml
This change modifies some previous documentation we had writen about Elasticsearch and updates it with some general-purpose usage guidelines based on how we've implemented search in Ask CFPB.
The intent is to help build similar searches based on our Wagtail pages and Django models. To that end I've tried to separate out what's necessary for indexing and what's necessary for searching, and the specific ways in which we've implemented it.
The examples are not fully-functioning code, but pseudo-code, meant to illustrate the specifics being discussed rather than be complete. This cuts down on the lines of code in the docs, at the expense of being able to paste it into an interpreter and run it.
Here is the document rendered in GitHub: …
=> Document how to use Elasticsearch in cf.gov

cfgov/scripts/http_smoke_test.py
Previously, the smoke test list contained several URLs that are redirected as a result of the Nov 25 IA migration. As of #6145, individual servers (which we target in smoke tests) can no longer serve URLs that redirect in Apache, so smoke tests were failing. This PR updates these URLs to their new locations. I also updated the s3 list of URLs that the smoke test job uses by default. Smoke tests are now passing on Beta.
Our smoke tests ensure that the most important pages on cf.gov return a 200. Validating redirects is out of scope for the smoke test job. We're planning to find another way to validate redirects, outside of the smoke test job.
- Update smoke test URLs to use their new locations as of the IA migration of November 25.
1. `cfgov/scripts/http_smoke_test.py --base …
=> Use canonical URLs in smoke tests

cfgov/paying_for_college/disclosures/scripts/notification_tester.py, cfgov/paying_for_college/fixtures/test_contacts.json, cfgov/paying_for_college/tests/test_scripts.py
We have sporadically needed to change EFIP endpoints, and having
the notification_tester script up to date helps in testing and
troubleshooting new endpoints.
In the latest round of changes, new endpoints were added for 2 school systems:
- South University
- Art Institutes
These two new endpoints fully replace the original edmc endpoint, so it can be retired.
Running the script's `send_test_notificaions` function with no arguments
will now send tests to the two new endpoints, as well as to the third
remaining endpoint, BPI.
Testing
The script can be tested locally, but requests may time out,
because the school systems may block them if they don't come from one
of our production servers.
To test locally, open a Django shell with `./cfgov/manage.py shell` and run the following:
```python …
```
=> Update EFIP notification endpoints for test-runner

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py, cfgov/cfgov/settings/test.py, cfgov/core/testutils/runners.py, cfgov/paying_for_college/disclosures/scripts/nat_stats.py, cfgov/paying_for_college/disclosures/scripts/update_ipeds.py, requirements/libraries.txt
This commit deprecates use of the third-party Unipath package and instead uses the built-in Python pathlib package.
Unipath [is now in maintenance mode](https://github.com/mikeorr/Unipath). We used it previously with Python 2. Python 3.4 introduced [pathlib](https://docs.python.org/3/library/pathlib.html) which has the same functionality for our purposes.
We currently use Unipath for path-handling logic, but `pathlib.Path` can do the same thing. The default Django project settings file [uses pathlib in this way](https://github.com/django/django/blob/45f4282149e13a2c1548a579f60d098e397a33d7/django/conf/project_template/project_name/settings.py-tpl#L13-L16).
There are [no other uses](https://github.com/search?q=user%3Acfpb+unipath&type=code) of pathlib in any of the cf.gov satellite apps. …
=> Use Python pathlib instead of third-party Unipath

cfgov/unprocessed/apps/ccdb-landing-map/package.json, cfgov/unprocessed/apps/ccdb-landing-map/yarn.lock
- Updates highcharts from 7.2.1 to 7.2.2 to fix security warning.
1. Pull branch, run `./frontend.sh`, and visit http://localhost:8000/data-research/consumer-complaints/ and all should be as it was.
=> CCDB: Update highcharts to 7.2.2 to fix security warning

docker-compose.override.yml
Follow-up to https://github.com/cfpb/consumerfinance.gov/pull/6121
This prevents django from being opened across the network on 8000, which was missing in the previous PR.
=> Only expose django on localhost

Jenkinsfile
This changes adds GitHub status API calls for our internal Jenkins deploy and functional test runs. This should allow us to see in GitHub PRs when our internal deploys fail and when our automated functional test runs that depend on those deploys fail.
This is imperfect right now because it depends on our Jenkins polling GitHub, but it gets the information into the PR where it's most relevant.
This will require editing our `/etc/hosts` files to ensure the "Details" link works.
=> Have Jenkins report PR build/functional test status to GitHub

docker-stack.yml
The MAPBOX_ACCESS_TOKEN env var is missing on UCP stacks, causing functional test
failures on /find-a-housing-counselor/
This should add the missing var, which is available in the cluster.
=> Add mapbox token for docker stacks

Jenkinsfile
This small change uses the Jenkins Blue Ocean URL for the "Details" link in our Jenkins GitHub status checks. Previous we were only using it for failures. But it's prettier than standard Jenkins, and is always specific to the run rather than the parent job.
=> Use the Jenkins Blue Ocean URL for "Details"

cfgov/scripts/update_internal_regs3k_links.py
Links within the Interactive Bureau Regulations tool are stored in the reg markdown as literal `a` tags, like this: `<a href="/policy-compliance/rulemaking/regulations/1002/2/#l" data-linktag="0">1002.2(l),</a>`. All of those pages moved as part of the IA migration on Nov 25 from `/policy-compliance/rulemaking/regulations/` to `/rules-policy/regulations/`, so we need to update the links to their new destinations.
This PR updates those links to use relative paths, to prevent this issue in the future. Example:
`<a href="/policy-compliance/rulemaking/regulations/1002/2/#l" data-linktag="0">1002.2(l),</a>`
Within reg 1002, changes to: `<a href="../2/#l" data-linktag="0">1002.2(l),</a>`
Within another reg, changes to: `<a href="../../1002/2/#l" data-linktag="0">1002.2(l),</a>`
See …
=> IA migration cleanup: Script to update links within Regs3k

cfgov/regulations3k/tests/test_hooks.py, cfgov/regulations3k/wagtail_hooks.py
This change overrides the TreeModelAdmin URL Helper for Regulations breadcrumbs. in #5703 we ensured that the regs models' `__str__` methods included their parents, so that one could see what regulation and version a particular section object belongs to in the model drop-downs and anywhere else Django renders the model to string.
Unfortunately the `__str__` is the same mechanism TreeModelAdmin uses to generate the breadcrumbs at the top. This seems reasonable, which is why I don't want to change it there.
So to eliminate the duplicity in the breadcrumbs, this change overrides the TreeModelAdmin URL helper class to remove the parent's string if the URL helper is generating a breadcrumb for a specific model and a parent instance is given.
Before:
After:
=> Override the TreeModelAdmin URL Helper for Regs breadcrumbs

cfgov/jinja2/v1/_includes/macros/accessible-languages.html, cfgov/jinja2/v1/_includes/templates/render_block.html, cfgov/jinja2/v1/_layouts/content-base.html
We have a [macro](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/jinja2/v1/_includes/macros/accessible-languages.html) that swaps the language direction for Arabic. We currently use it on a page's container element which causes all children inline elements to flow from right to left, breaking our inline-block layout and making the site unusable for Arabic speakers. Adding it to individual children blocks preserves the layout while still reversing text flow.
1. `./refresh-data.sh`
1. Compare the [new Arabic content](http://content.localhost:8000/language/ar/coronavirus/mortgage-and-housing-assistance/) before and after this PR.
| <img width="1156" alt="before" src="https://user-images.githubusercontent.com/1060248/102388275-8776ec80-3f9f-11 …
=> Move language macro from main container to blocks

test/cypress/integration/pages/consumer-complaints.js, test/cypress/pages/data-research/consumer-complaints.js
Add Cypress tests to CCDB landing page (/data-research/consumer-complaints/) to test dynamic parts
Run `yarn run cypress open` and select the cypress integration test `consumer-complaints.js`
=> CCDB: Add consumer-complaints functional tests

cfgov/jinja2/v1/_includes/molecules/enforcement-action-metadata.html
EnforcementActionPages are currently structured to allow the date_filed to be updated in the final_disposition section in Wagtail. This updates the template to match that expected behavior.
=> Prefer date_filed from final_dispostion for enforcement actions

.gitignore, cfgov/unprocessed/apps/regulations3k/webpack-config.js
This change fixes the capitalization of `StaleWhileRevalidate` and `modifyURLPrefix` in our regulations service worker. This seems like a recent change upstream that started requiring specific capitalization.
I've also gitignore'd additional files that it has started generating.
This should fix a `TemplateDoesNotExist` error we're seeing because the service worker was no longer building.
=> Fix capitalization in regulations service worker

cfgov/v1/forms.py
Fixes an issue where the currently inconsistent `date_filed` field was causing enforcement actions to appear out of order
=> Update sorting for enforcement actions filter page to match publishing date

cfgov/jinja2/v1/_includes/blocks/heading.html, cfgov/jinja2/v1/_includes/molecules/info-unit-2.html, cfgov/jinja2/v1/_includes/organisms/filterable-list.html, cfgov/jinja2/v1/_includes/organisms/info-unit-group-2.html, cfgov/v1/template_debug/__init__.py, cfgov/v1/template_debug/heading.py, cfgov/v1/wagtail_hooks.py
Currently if an info unit contains an empty heading block (meaning empty text), an empty `<div class="m-info-unit_heading-text"><h3></h3></div>` gets rendered on the page:
If a heading has empty text, it should not be rendered as part of an info unit. This commit removes the branch of logic that does this.
To test, visit a page with an empty heading, for example in production:
http://localhost:8000/consumer-tools/educator-tools/adult-financial-education/
Alternatively, create a new e.g. Sublanding page with an info unit group, then add an info unit with an empty heading.
Fixes internal platform#3854.
- Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update …
=> Fix: Don't render empty info unit heading blocks

cfgov/unprocessed/apps/paying-for-college/js/models/financial-model.js
This PR addresses a bug we're seeing in the Your Financial Path to Graduation app. 
- Change old calculation which was causing errors with loan caps
1. Pull down this PR!
2. Check out http://0.0.0.0:8000/paying-for-college/your-financial-path-to-graduation/
3. As an undergraduate dependent student, try to add $9,999 in subsidized loans (it will be brought down to $5,500) and then see if you can successfully add any amount of unsubsidized loans.
=> Paying for College - Fix bug in loan caps

Jenkinsfile, docker-compose.yml, docker/elasticsearch/7.7/Dockerfile, docker/elasticsearch/7/Dockerfile
This clears out a few vulnerabilities in the 7.7 image. Tested and working in my local Docker environment.
Also renames the ES7 image folder to just `7` so we don't have to keep updating it if there are more minor version updates before we get rid of the ES2 image.
1. Pull branch
2. `docker-compose build elasticsearch`
3. `docker-compose up`
4. `docker-compose exec python bash`
5. `./cfgov/manage.py search_index --rebuild --parallel -f`
6. Visit the various ES-powered things and confirm that they still work
=> Update ES7 Docker image to 7.10.1

cfgov/jinja2/v1/_includes/molecules/info-unit-2.html
This commit modifies how Info Unit image alt text is set. With this change, the following logic is used:
- If the image is not a link, use its alt text. This might be the alt text configured on the Info Unit, or, as a fallback, the alt text set on the image when added to Wagtail.
- If the image is a link, and the Info Unit has a heading, don't set any alt text. The link will already include the heading text, and we don't want there to be duplicate text in the link.
- If the image is a link, and the Info Unit doesn't have a heading, make the alt text equal to the link text. If we used image-specific alt text here, then we'd have two links going to the same place, but with
different text. Using the link text means that both links are the same. This is consistent with how the carousel links …
=> Improve Info Unit image alt text logic

cfgov/paying_for_college/models/disclosures.py
In refactoring paying-for-college data for the financial-path tool, we dropped
an outdated model method that returned a program level name. It appeared to be
unused, but it was in fact called from the legacy EFIP template for use as a label.
This restores the method so that we don't need to touch EFIP front-end code.
Before pulling in the branch, go to a recent EFIP disclosure and note that the
**PROGRAM TYPE** field is blank on the opening page:
http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=475121&pid=5460&oid=D52A4D6A8D320E7C8E7CD6AFB3E483BF2508D54B&book=1503&gib=0&gpl=0&hous=7101&insi=0.0000&insl=0&inst=37&leng=0&mta=0&othg=0&othr=4338&parl=0&pelg=6345&perl=0&ppl=0&prvl=0&prvf=0.0000&prvi=0.0000&schg=0&stag=0&subl=3465&totl=65825&tran=2322& …
=> Restore model method for EFIP program type

requirements/libraries.txt
This commit bumps the version of our wagtail-sharing package from version 2.3.0 to the new release 2.4.0. See the release notes for details on changes: https://github.com/cfpb/wagtail-sharing/releases/tag/2.4.0
Run a local server and verify that [sharing pages](http://content.localhost:8000/) continue to work, that sharing links are correct (see "View sharing link" under MORE under a page title in [a listing view](http://localhost:8000/admin/pages/319/)), and that the sharing banner now works properly [on interactive regulations pages](http://content.localhost:8000/rules-policy/regulations/1002/).
=> Update wagtail-sharing to version 2.4.0

cfgov/jinja2/v1/_includes/organisms/video-player.html, cfgov/unprocessed/js/organisms/VideoPlayer.js
This commit improves keyboard navigation of the VideoPlayer module by changing which elements are assigned tabstops.
This fixes https://github.com/cfpb/design-system/issues/1124 which reports that tabbing through the video player pauses on invisible elements. This is because currently both the close button and video iframe can be tabbed to even when they are invisible because the video is not playing. An example live page where this behavior can be seen is https://www.consumerfinance.gov/consumer-tools/managing-someone-elses-money/.
This commit adds `tabindex="-1"` to both the iframe and close button so that, in the initial page load state, neither of these invisible elements can be tabbed to.
The JS code is altered here so that, when the video is played, the `tabindex` attribute is …
=> Improve keyboard navigation of VideoPlayer

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
If `WATCHMAN_TOKENS` is not defined in the environment, the Django setting will default to `None` and the Watchman `_status/` URL will not added the URL patterns.
=> Only add Watchman URL if WATCHMAN_TOKENS is defined

cfgov/cfgov/urls.py, cfgov/v1/models/enforcement_action_page.py, cfgov/v1/tests/views/test_enforcement_api.py, cfgov/v1/views/enforcement_api.py
New API endpoint at /api/enforcement_actions/v1/ returns a JSON serialization of all Enforcement Action Pages that are children of the `EnforcementActionFilterPage` in the page tree.
This will be used to power the charts displaying data about enforcement actions over time.
2. Visit this URL in the browser or in code: [http://localhost:8000/api/enforcement_actions/v1/](http://localhost:8000/api/enforcement_actions/v1/)
=> Enforcement actions API

cfgov/cfgov/settings/base.py, cfgov/v1/tests/views/test_enforcement_api.py
Serialize DecimalFields as numerals. This will make conversion to a chart simpler on the front end.
- Update django rest framework settings to serialize DecimalFields as numerals instead of strings.
1. Visit http://localhost:8000/api/enforcement_actions/v1/
```json
{
"public_enforcement_action": "Sample Action, LLC.",
"initial_filing_date": "2020-11-30",
"defendant_types": [],
"court": "",
"docket_numbers": [
"2020-BCFP-3333"
],
"settled_or_contested_at_filing": "Settled",
"products": [
"Short Term, Small Dollar",
"Other Consumer Lending"
],
"at_risk_groups": [
"Servicemembers"
],
"enforcement_dispositions": [
{
"final_disposition": "Sample Sample, LLC.",
"final_disposition_type": "Final Order",
"final_order_date": "2020-11-30",
"dismissal_date": null,
"final_order_consumer_redress": 0.0, …
```
=> Enforcement API: Serialize DecimalFields as numerals

cfgov/v1/apps.py, cfgov/v1/signals.py
Invalidate Akamai cache for EnforcementAPI endpoint when the collection of EnforcementActionPages changes.
- A listener to the "publish" and "move" signals for the EnforcementActionPage now triggers a `purge_url_from_cache` action (the same action that the `cf.gov-flush-akamai-cache` job uses)
- To do: Add tests.
- CFPB/hubcap wiki on GHE …
=> Invalidate Akamai cache for EnforcementAPI endpoint

cfgov/unprocessed/css/organisms/mega-menu.less
https://github.com/cfpb/consumerfinance.gov/pull/6005 reduced the padding on the top-level mega menu items. There exists a 10px window in window sizes where the top-level items wrap (https://[GHE]/CFGOV/platform/issues/3953). This PR increases the amount of padding reduction to handle that window. 
- Mega-menu: Reduce item padding to 4px from 2px to accommodate long nav item titles.
1. `gulp clean && gulp build` and visit any page and resize the window and observe the mega menu appearance in the 901-911px window width. Compare to production. This PR will have 2px narrower top-level nav items in the desktop mega menu.
=> Mega-menu: Reduce top-level padding further by 2px to accommodate long titles

cfgov/cfgov/settings/test.py, cfgov/core/testutils/runners.py, docs/python-unit-tests.md, tox.ini
This commit restores the ability to optionally skip (most) Django migrations during Python tests. This repository used to have the ability to do this using `tox -e fast`, but this feature was removed some time ago.
With this commit, by setting the `SKIP_DJANGO_MIGRATIONS` environment variable, the Django [`settings.MIGRATION_MODULES`](https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-MIGRATION_MODULES) will be set to a special object that skips all migrations. Our custom test runner will then run a few specific data migrations which create required test data, for example a single Wagtail Site object.
Running tests this way significant speeds up testing because you avoid the time required to run migrations. This is noticeable during the testing step:
"Creating test database …
=> Optionally skip Django migrations during tests

test/cypress/integration/pages/tdp-activity-search.js, test/cypress/pages/practitioner-resources/activity-search.js
Adds more cypress tests to cover common issues with tdp search (filters show, clear filters, search with no results shows no results message)
1. Ensure all cypress tests pass
=> Cypress Rests: Add TDP activity search 

cfgov/unprocessed/apps/paying-for-college/css/main.less
Paying for college CSS is importing `cfpb-` less files, which is leading to strange behavior in the header and layout. Instead this PR changes those imports to references so that only the parts required elsewhere will be included.
- Paying for College: change less imports to reference.
1. Pull branch and run `gulp clean && gulp build`
2. Visit http://localhost:8000/paying-for-college/your-financial-path-to-graduation/ and compare to https://www.consumerfinance.gov/paying-for-college/your-financial-path-to-graduation/
Before:
After:
Before:
After:
=> Paying for College: Don't double-import design system packages

cfgov/cfgov/settings/test.py
By default any configured Wagtail search indexes have `AUTO_UPDATE=True`, meaning that any changes to indexed model instances [get automatically re-indexed](https://docs.wagtail.io/en/stable/topics/search/backends.html#auto-update).
We currently have two Wagtail search indexes configured: a default one using the database backend (which doesn't actually use an index) and a "fulltext" one using the PostgreSQL backend (which does).
Because we have `AUTO_UPDATE` set to its default value of `True`, this latter index gets updated any time a Python test creates or updates a Page model instance. We don't need this functionality because we don't have any tests that rely on it.
Turning of auto update results in a non-trivial speedup to tests. Anecdotally before this change I can run `tox -e …
=> Don't auto update Wagtail search indexes in tests

cfgov/cfgov/settings/base.py
In order to view heat maps for cf.gov pages, we need to allow images from Mouseflow's domains.
---
- Mouseflow's domains to the list of valid image sources
This isn't really testable locally; you have to be logged into the Mouseflow admin to see the heat maps that need images.
=> Add Mouseflow to valid image sources

cfgov/v1/models/sublanding_page.py
The SublandingPage class has a `get_browsefilterable_posts` method that is used to generate a list of posts to display if the page has a PostPreviewSnapshot module.
There are only two live pages on the site that use this functionality now:
https://www.consumerfinance.gov/compliance/amicus/
https://www.consumerfinance.gov/rules-policy/notice-opportunities-comment/
As part of broader work on filters, this commit removes the use of FilterableListForm here. Invoking the form does nothing because there are no form filters being specified. Removing this use of FLF will make it easier to make changes to that code.
You can visit these two pages and confirm that post order doesn't change.
Additionally, I wrote a simple Python script that dumps the list of all SublandingPages on the site (even …
=> Remove unnecessary use of FilterableListForm

cfgov/search/elasticsearch_helpers.py, cfgov/v1/documents.py, cfgov/v1/tests/atomic_elements/test_molecules.py, cfgov/v1/tests/jinja2tags/test_fragment_cache.py, cfgov/v1/tests/models/test_filterable_list_mixins.py, cfgov/v1/tests/models/test_sublanding_page.py, cfgov/v1/tests/test_documents.py, cfgov/v1/tests/test_filterable_list_form.py
Suggestions for #6262:
- Simplifying tests and removing some duplication.
- Removing indexing of content field since we're not using it yet and it'll require a more complicated implementation to handle different fields (the header) on different pages.
- Use [`PageQuerySet.specific()`](https://docs.wagtail.io/en/stable/reference/pages/queryset_reference.html#wagtail.core.query.PageQuerySet.specific) to optimize indexing.
=> Elasticsearch-based filters suggestions

cfgov/unprocessed/css/enhancements/layout.less, cfgov/v1/jinja2/v1/home_page.html
The homepage's jumbo hero is unusual in that it doesn't have a background color yet still uses white text. This causes extra small screens to see white-on-white text.
It also has a long subhead that overflows the hero on smaller screens. Instead of writing a one-off fix for this, I modified the jumbo hero code to show a reduced heading and subhead on both small and medium screens.
- One-off media query that turns the homepage hero text black on small screens.
- Reduced the size `.m-hero_heading` and `.m-hero_subhead` on small and medium screens.
1. Compare content's Spanish homepage to your [local homepage](http://0.0.0.0:8000/es/) at various widths. (Log into wagtail locally and publish the latest draft of the homepage to see the new hero).
| <img …
=> Improve the homepage's jumbo hero layout

cfgov/legacy/views/complaint.py, cfgov/v1/jinja2/v1/header.html
It disappeared due to the global header change in #6244.
This also restores the Beta banner for this page when on Beta.
- Sets default values for `show_mega_menu`, `show_banner`, and `language` when Django pages call the `header.render()` macro
1. Load up http://localhost:8000/data-research/consumer-complaints/ and see no mega menu
1. Pull branch
1. Reload and see mega menu
1. Go to https://beta.consumerfinance.gov/data-research/consumer-complaints/ and see no Beta banner
1. Enable `BETA_NOTICE` flag for all requests at http://localhost:8000/admin/flags/BETA_NOTICE/
1. Reload http://localhost:8000/data-research/consumer-complaints/ and see the Beta banner
- Consider …
=> Restore mega menu and banners on Django pages

cfgov/cfgov/settings/base.py
Link icons are intrusive on API pages handled by Django Rest Framework.
Since the API pages are not aimed at routine users, we can exclude
them from link-insertion middleware via settings.
- https://www.consumerfinance.gov/oah-api/county/?state=FL
- https://www.consumerfinance.gov/oah-api/rates/rate-checker?loan_amount=200000&price=400000&state=va&loan_type=conf&maxfico=720&minfico=700&loan_term=30&rate_structure=fixed
----
----
- http://localhost:8000/oah-api/county/?state=FL
- http://localhost:8000/oah-api/rates/rate-checker?loan_amount=200000&price=400000&state=va&loan_type=conf&maxfico=720&minfico=700&loan_term=30&rate_structure=fixed
=> Exclude API pages from link-icon insertion

cfgov/search/elasticsearch_helpers.py, cfgov/search/tests/test_elasticsearch_helpers.py
Elasticsearch requires lowercase names for indexes, and we add prefixes, 
based on the DEPLOY_ENVIRONMENT var, to index names to keep them separate.
The DEPLOY_ENVIRONMENT vars on servers are lowercase, but we're not indexing
from servers anymore. We index from Jenkins, where the vars are configured as uppercase.
Our `elasticsearch_helpers` shouldn't assume the case of the variable.
=> Handle uppercase env vars when naming indexes

requirements/libraries.txt
This small change updates our pins for [Django Flags](https://github.com/cfpb/django-flags/releases) and [Wagtail Flags](https://github.com/cfpb/wagtail-flags/releases) to their latest released versions.
=> Update django-flags and wagtail-flags pins

cfgov/core/tests/test_utils.py, cfgov/core/utils.py, cfgov/unprocessed/css/print.less
To improve printed pages' usability, we append link URLs to link text in parentheses. Unfortunately, our external links point to an interstitial page that is long and ugly when printed.
This PR saves the original external URL as a data attribute on the anchor element for later retrieval by our print stylesheet.
See https://github.local/CFGOV/platform/issues/3812
- `data-orig-href` attribute to keep track of original external URL.
- Replaced `consumerfinance.gov` in relative URLs with the shorter `cfpb.gov`.
- The `:not()` pseudo-classes were increasing the specificity of their rule and overriding the latter `a[href^="/external-site"]` rule so I split them out.
1. [Emulate print media queries](https://developers.google.com/web/tools/chrome-devtools/css/print-preview) in Chrome.
1. Visit a …
=> Clean up external links when printing

Jenkinsfile
Hoping that this eliminates the pattern of the functional tests timing out and the process being killed.
Now that we've got a healthy number of these tests, we should probably take a harder look at best practices and performance.
=> Increase timeout for running functional tests on dev Docker stacks

cfgov/unprocessed/apps/rural-or-underserved-tool/js/get-rural-counties.js
The `axios` `get` call in this instance was (1) not returning the data structure the code was expecting and (2) causing CORS problems on Chrome. Replaced with `cross-fetch`, already included in our root `package.json`
The reason this was working at all was that there's a fallback check from the object lookup where the Census API is queried. The underlying data structure issue meant that *NO* county was being pulled from the FIPS array, but instead was always falling back to what was designated rural by the census, which is sometimes different than our designations.
Testing:
- Pull branch and run the frontend build
- Search for `300 N Main Kingfisher OK` in the tool at `http://localhost:8000/rural-or-underserved-tool/`
- Should be rural
- Search for `1700 G St NW Washington DC`
- Should …
=> Update fetch method to provide expected response type

cfgov/unprocessed/apps/paying-for-college/css/main.less
https://github.com/cfpb/consumerfinance.gov/pull/6259 turn design-system imports in paying for college in references, however, we need some classes from cfpb-layout, so this PR reverts that portion of the PR.
- Paying for College: Import cfpb-layout instead of referencing it.
1. Compare http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/test/ to production.
Before:
After:
=> Paying for College: Import cfpb-layout instead of reference

cfgov/unprocessed/css/print.less
Iterates on https://github.com/cfpb/consumerfinance.gov/pull/6263.
Increase the weight of all links (not just external ones with an icon) when a user prints a page and don't underline the URL that gets generated in an :after pseudo element.
In order to "remove" the pseudo element's border, I set its color to white. This works but causes URLs on a gray background to have a barely visible white underline when printing. The alternative solutions involved adding markup to the page and I didn't feel the performance hit of wrapping every link in a span was justified. I'm happy to discuss other options.
See https://stackoverflow.com/a/21478325
See https://github.local/CFPB/el-camino/issues/299
- Print link styles.
1. [Emulate print media …
=> Embolden links when printed but not their URLs

test/cypress/components/filterable-lists.js
Cypress test had outdated ID for topics in the blog filters.
- Update topics ID in broken Cypress test.
=> Cypress tests: Fix topics filter ID query

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html, cfgov/regulations3k/jinja2/regulations3k/landing-page.html, cfgov/regulations3k/jinja2/regulations3k/search-regulations.html, cfgov/regulations3k/models/pages.py, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py, requirements/libraries.txt
Draft content on regulation pages that have been previous published is not shared by wagtail-sharing because of how `RoutablePageMixin` resolves page routes before rendering. This is fixed in https://github.com/cfpb/wagtail-sharing/pull/43 with the introduction of `ShareableRoutablePageMixin`. 
This change uses that class in place of `RoutablePageMixin` in regulations.
~~This PR must wait on https://github.com/cfpb/wagtail-sharing/pull/43 to be merged and a new release of wagtail-sharing before it can be merged.~~ (This has happened).
To test this:
- Log into your local running cf.gov. 
- Make a change to a regulation landing page and save it as draft, for example, http://localhost:8000/rules-policy/regulations/1002/
- Observe that the change does not show when viewing the page at …
=> Fix draft regulation landing pages not being shareable

cfgov/unprocessed/apps/paying-for-college/js/repay.js
`hashes` variable wasn't declared in the original code this came from in https://github.com/cfpb/consumerfinance.gov/pull/6307
- Paying for College: define `hashes` variable in repay.js
=> Paying for College: define `hashes` variable in repay.js

cfgov/cfgov/settings/base.py
`FlagConditionsMiddleware` has been deprecated in Django-Flags. This change removes the middleware to eliminate the deprecation warning.
See [the Django-Flags release notes for more details on the deprecation](https://cfpb.github.io/django-flags/releasenotes/#deprecations).
Observe that you no longer see:
```
FutureWarning: FlagConditionsMiddleware is deprecated and no longer has any effect. It will be removed in a future version of Django-Flags.
```
Warnings.
=> Remove deprecated FlagConditionsMiddleware

cfgov/ask_cfpb/forms.py, cfgov/ask_cfpb/tests/test_forms.py, cfgov/ask_cfpb/tests/test_search.py, cfgov/ask_cfpb/views.py, cfgov/regulations3k/forms.py, cfgov/regulations3k/models/pages.py, cfgov/regulations3k/tests/test_views.py, cfgov/regulations3k/views.py, cfgov/v1/tests/views/test_login_views.py, cfgov/v1/views/__init__.py
This PR is intended to fix the errors that CodeQA has flagged. These were predominantly around where we pass parts of URLs off from parameters to redirects without performing any sanitization/validation on them. Most of these changes are in redirects for legacy Ask CFPB and eRegulations URLs to their replacements. 
For the most part, I've fixed this by using Django forms for handling the cleaning/validating of the fields. In Ask CFPB, this means I've created an `AutocompleteForm` and a `SearchForm`, and moved some of the sanitizing that we were doing multiple times in multiple places to the `clean_q` method on that form. 
I've taken a similar approach to the eRegs redirects in creating a `SearchForm`. 
The other place where that CodeQL flagged is in our `check_permissions` method, which …
=> Fix CodeQA-flagged errors in Python

docs/running-docker.md
This change fixes the line in our docs for the `docker attach` command when you need to interact with a `pdb` session. I think when we renamed this repo from `cfgov-refresh` to `consumerfinance.gov`, we mistakenly broke this command. It should not have the dot in the container name; it should be `consumerfinancegov_python_1`.
=> Fix the Docker attach line in docs

cfgov/jinja2/v1/_includes/organisms/post-preview.html
The enforcement action filter page should use `initial_filing_date` in their post previews, but they were using `date_filed` instead. This PR fixes that error.
This was happening because the `post` variable is an instance of `AbstractFilterPage`, which doesn't have an `initial_filing_date`. In this template, in order to access that field, which is specific to the `EnforcementActionPage`, we need to use `page.specific` to treat the page as an `EnforcementActionPage`.
1. Visit the enforcement actions filter page and filter by date. Notice that the dates above the previews now match the dates in the filter, where they didn't before. 
[This filter shows it well](http://localhost:8000/enforcement/actions/?title=&from_date=2019-11-01&to_date=2019-12-31). Previously, all of the posts in that …
=> Bugfix: Enforcement Actions were using date_filed in post previews

cfgov/teachers_digital_platform/models/__init__.py
The latest version of isort fixes a bug that resulted in this import list being split across multiple lines when it didn't hit the line length limit. This quick change fixes the resulting isort errors.
=> Fix an import sorting flagged by the latest isort release

cfgov/cfgov/settings/base.py, cfgov/core/tests/test_views.py, cfgov/core/views.py, cfgov/jinja2/v1/external-site/index.html, cfgov/unprocessed/js/modules/ExternalSite.js
This change removes POST support from the external site interstitial view.
The POST was being used to POST URLs that didn't necessarily match the URL in the GET. This was causing issues in production.
The POST also seems unnecessary, as it adds another step through our servers before the redirect, when we can simply link directly to the external site from the button.
This change does require adding `/external-site/` to the parse links exception list, because without it, the user ends up in an endless loop of being sent to /external-site/ when `ParseLinksMiddleware` parses the rendered interstitial page.
=> Remove the POST from external site interstitial view

cfgov/apache/conf.d/headers.conf, cfgov/apache/conf/httpd.conf
This PR adds Apache [`LimitRequestBody`](https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestbody) if `LIMIT_REQUEST_BODY` is provided in the environment.
There is a corresponding PR to our automations to add this value.
=> Allow limiting of request body sizes

cfgov/legacy/templates/complaint/complaint-landing.html
The 2020 Consumer Response annual report is being published. We need to update links on the CCDB landing page to point to the 2020 report.
---
- The links to the Consumer Response annual report on the CCDB landing page now point to the 2020 report instead of the 2019 report.
If you're testing locally, publish the draft report in the latest database dump and make sure the link works. If you're testing in the PR preview environment, I'll publish the report in the admin, so the link should work.
=> Update Consumer Response report links

cfgov/unprocessed/root/robots.txt
This change disallows robots from our old `/askcfpb/search` endpoint. This should stop robot queries like:
```
GET /askcfpb/search/?selected_facets=audience_exact:Older+Americans&selected_facets=audience_exact:Students&selected_facets=category_exact:debt-collection-and-rehabilitation&selected_facets=category_exact:getting-student-loan&selected_facets=category_exact:other-student-loans-questions&selected_facets=category_exact:protections-and-benefits-servicemembers-students&selected_facets=category_exact:repaying-student-loan&selected_facets=category_exact:student-loans&selected_facets=tag_exact:federal+student+loans&selected_facets=category_exact:co-signing-student-loan
```
that end up in a 301 anyway.
=> Add the old /askcfpb/search URL to robots.txt

Dockerfile
This corresponds to the change in 9a5ee5472 to add this variable in production.
We'll see if this successfully deploys when it gets built.
=> Add the LIMIT_REQUEST_BODY variable for Docker

cfgov/cfgov/settings/base.py, cfgov/legacy/views/complaint.py
This flag appears unused as it doesn't appear in the complaint-landing template.
- Remove unused `ccdb_content_updates` flag.
=> Remove unused ccdb_content_updates flag

requirements/libraries.txt
The django-localflavor package is now used by [code in this repo](https://github.com/cfpb/consumerfinance.gov/search?q=localflavor) directly. Additionally django-college-costs-comparison [is no longer a requirement](https://github.com/cfpb/consumerfinance.gov/commit/02141df0194a2e676ecad3794f037a2c0dfce4ce#diff-14c508ad072c1940d467c724f21c7706d13183e51185b0424b797b8c8225b561) either.
=> Remove outdated comment about django-localflavor

cfgov/jinja2/v1/complaint/complaint-landing.html
Carrying over the link update from #6353 to the new CCDB landing page template.
---
- New annual report link
1. Make sure the link points to the 2020 annual report.
=> Fix CR annual report links

cfgov/cfgov/settings/base.py, cfgov/jinja2/v1/_includes/organisms/simple-chart.html, cfgov/jinja2/v1/browse-basic/index.html
If the page is being served via wagtail-sharing (i.e. the request's `served_by_wagtail_sharing` attribute is set to `True`), replace any instances of `production` in the `data_source` field with `staging`. If the page is not being served via wagtail-sharing, do not modify the `data_source` field.
This allows us to provide a staged version of a page with different data than is on production. We're assuming that we can have production and staging data sources that exactly parallel each other in URL structure, but replacing 'staging' with 'production'. We're initially building this with CCPI in mind, but hope this feature is general enough to be used for other charts.
- Allow Ajax requests to `raw.githubusercontent.com`, since that's where CCPI data will be stored
- Ensure …
=> Simple Chart: Use staging data on wagtail-sharing pages

README.md, docs/index.md
- Update node versions in docs from 12 to 14.
- Remove version from node and gulp in section where other software version number are not provided.
=> Update node versions in docs

cfgov/unprocessed/js/routes/on-demand/simple-chart/chart-hooks.js
As requested by OR.
To test:
Make a chart based on CCPI data. View the x axis both at max range and at 3 & 5 year ranges.
Then, in the style overrides in Wagtail, add the following:
```
{
"tooltip.formatter": "fn__ccpi_quarterLabels",
"xAxis.labels.formatter": "fn__ccpi_xAxisLabels",
"xAxis.tickPositioner": "fn__ccpi_tickPositioner"
}
```
Re-examine the xAxis at various time scales. Note also that at short time scales the tooltip is properly aligned specific tick marks.
=> Allow CCPI chart x axes to be quarter-based

requirements/libraries.txt
We can cap this timeline now:
- July 2020: we noticed wagtail-autocomplete was causing server errors
- August 2020:
- We opened a PR with wagtail-autocomplete, and it was approved but not merged
- We forked the repo with our fix, so that we could stop the server errors
- January 2021: our PR was merged
- April 12, 2021: version 0.6.3 was released, allowing us to use the main repo again.
- Check out the branch and run `pip install -r requirements/libraries.txt`
- Locally edit an Ask CFPB answer page that has "related quesions" attached,
such as [en-1793](http://localhost:8000/admin/pages/6208/edit/), and make sure you can remove 
and add related questions and save without server errors.
- At the bottom of the edit page, make sure you can search for, select, and remove
a "redirect to page" …
=> Drop our fork of wagtail-autocomplete and upgrade to 0.6.3

cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html, cfgov/paying_for_college/jinja2/paying-for-college/disclosure_technote.html, cfgov/paying_for_college/tests/test_views.py, cfgov/paying_for_college/views.py
This PR fixes three bits of the technote rendering.
Jinja2 templates run Python code in a more Pythonic way than do Django templates.
Django allows templates to call functions without the standard `()` evocation,
whereas Jinja executes functions with `()` and arguments.
The Django test client also does not populate the `context` variable in
Jinja2 responses, so tests can't check `context` for expected values.
In this case, we can just as easily check the `content` of the response
for the values we're expecting.
The PFC technote template performed a bunch of span replacement actions to pull in and format 
constants that are stored in the database. These swaps were not working in the jinja2 template. 
Since the constants are available to the technote's view, it seems simpler to format them …
=> Fix the PFC view and tests for jinja2 use

requirements/local.txt
This PR updates Django Debug Toolbar to 3.2.1. This bumps us up a few versions (we were on 1.11) and addresses [this security vulnerability](https://www.djangoproject.com/weblog/2021/apr/14/debug-toolbar-security-releases/).
=> Update Django Debug Toolbar to address security vulnerability

Dockerfile, cfgov/cfgov/settings/production.py
This change removes our production file-based default cache in favor of a default database cache.
There will be a corresponding PR to remove permission-setting on `eregs_cache` from our automations, but we already run `createcachetable` for our database post preview cache.
=> Switch from file-based to DB cache

cfgov/unprocessed/css/organisms/video-player.less
Due to a flex box alignment issue, video player preview images are stretched vertically on Safari at small screen sizes. This PR applies `align-self:center` to the class to prevent the stretching.
- Apply `align-self:center` generally to `.o-video-player_image` class to prevent image stretching in Safari
1. Check out branch and run gulp
2. Navigate to [housing assistance forbearance page locally](http://localhost:8000/coronavirus/mortgage-and-housing-assistance/help-for-homeowners/learn-about-forbearance/) on Safari with browser width reduced and verify that image is not stretched
- Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation …
=> Fix video player image stretching in Safari

docker-stack.yml
In an attempt to eliminate an error we're seeing on launch:
```
django.db.utils.ProgrammingError: relation "cfgov_default_cache" does not exist
```
1. We'll see if the Docker stack for this PR deploys successfully.
[skip-ci]
=> Add `createcachetable` command to Python Docker service

tox.ini
Commit 13ca4101153f14fe7f507a543894db96f8af9be1 modified how and when we validate Django migrations as part of CI, but it left behind this dangling line. This line can be removed without any side effects:
https://github.com/cfpb/consumerfinance.gov/search?q=CI_CHECK_MIGRATIONS
=> Remove unused reference to CI_CHECK_MIGRATIONS

cfgov/unprocessed/css/organisms/summary.less, cfgov/unprocessed/css/print.less
Latest (and last, for now) batch of print stylesheet improvements.
- Info unit headings no longer append ugly URLs.
- Stand-alone links now look like regular links with an underline and proper spacing.
- Columns (50/50, 33/33/33, 25/75) within info unit groups are preserved when printing instead of stacking a la our mobile layout.
- FCM layouts are preserved instead of stacking.
- Video player containers are shrunk into a 50/50 column with the youtube link in the right column.
2. Compare the production print preview of the [consumer resources](https://www.consumerfinance.gov/consumer-tools/) page with the localhost version. The localhost version should have columns.
3. Print preview a [page](https://www.consumerfinance.gov/coronavirus/mortgage-and-housing-assistance/help …
=> Print styling improvements

.env_SAMPLE, cfgov/cfgov/settings/local.py
This change enables our default cache locally based on an environment variable. This will enable us to use the default cache in local development more easily.
Set `ENABLE_DEFAULT_CACHE` in `.env` (see `.env_SAMPLE` in this PR).
Run `./cfgov/manage.py createcachetable`
Run `./cfgov/manage.py shell` and:
```python
from django.core.cache import cache
cache.set('my_key', 'hello, world!', 10)
cache.get('my_key')
```
You should get hello, world! back.
Then wait 10 seconds and try again:
```python
cache.get('my_key')
```
And you should get nothing.
- We should settle on use cases of the Django cache and document them, along with this env var to enable the cache locally.
=> Enable default cache locally based on env var

cfgov/unprocessed/root/robots.txt
We don't need or want the CRT completion pages indexed for search.
Users should always start upstream.
=> Disallow the curriculum review tool completion pages in robots.txt

cfgov/apache/conf.d/headers.conf
CFPB should be a trusted resource for all of our visitors. They should be able to trust they won't be placed into an advertising cohort to have, for example, high-interest loans advertised at them if they use our mortgage information and tools.
This change sets the `Permissions-Policy: interest-cohort=()` to declare consumerfinance.gov should not be included in a browser's cohort calculation, per [web.dev's FLoC explainer](https://web.dev/floc/#how-can-websites-opt-out-of-the-floc-computation).
=> Opt consumerfinance.gov out of Google's FLoC cohorts

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/01-school-search.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/02-costs.html, test/cypress/integration/pages/paying-for-college/your-financial-path-to-graduation.js, test/cypress/pages/paying-for-college/your-financial-path-to-graduation.js
P4C browser tests are failing due to recently released grad path tool updates. This PR updates the tests to reflect the interface changes.
- ID updates in grad path tool
- Updates to grad path tests
- Handle new progress question on first screen
- Update costs question handling to reflect new radio + button format
- Remove PELL and SEOG entries from graduate test
1. Check out branch 
2. `yarn run cypress open` and run `your-financial-path-to-graduation` tests under Paying for College
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in …
=> P4C: update browser tests to reflect interface changes

cfgov/jinja2/v1/_includes/organisms/filterable-list.html, cfgov/v1/apps.py, cfgov/v1/documents.py, cfgov/v1/forms.py, cfgov/v1/management/commands/archive_pages.py, cfgov/v1/management/commands/restore_archive_pages.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/filterable_list_mixins.py, cfgov/v1/signals.py, cfgov/v1/tests/models/test_browse_filterable_page.py, cfgov/v1/tests/models/test_filterable_list_mixins.py, cfgov/v1/tests/test_documents.py, cfgov/v1/tests/test_filterable_list_form.py, cfgov/v1/tests/test_forms.py, cfgov/v1/tests/test_signals.py
This PR makes a number of changes to our filterable lists.
- The `FilterablePagesDocumentSearch` class has been refactored to more easily share an instance.
- The `FilterablePagesDocumentSearch` object is now shared between `FilterableListMixin` and `FilterableListForm` (instead of two separate instances being used).
- `FilterableListForm` now uses the Django cache to cache the list of authors, topics, and all filterable pages to avoid repeatedly fetching and querying the information when it has not changed.
- We have a signal handler that will purge the Django cache and the frontend Akamai cache when a filterable page for has been published or unpublished.
All of these changes should improve the overall performance of our filterable lists. This reduces duplicate queries that we previous …
=> Improve filterable list performance

cfgov/regulations3k/scripts/insert_section_links.py
The path to regulations has recently been changed.
This is a simple one line change to replace `/policy-compliance/rulemaking/regulations/` with `/rules-policy/regulations/`
1. tox -e unittest-current regulations3k
=> Update REG_BASE in regulations3k insert_section_links.py script

cfgov/wellbeing/jinja2/wellbeing/about.html
Adds a paragraph and link to an additional report to the end of the financial well-being survey's about page.
---
- Paragraph and link to an additional report
- The single jump link that was at the end of the page is now a link list to get the margin between that and the new paragraph that follows it correct (`.a-link__jump + p` has no margin in between them).
1. Fire up /consumer-tools/financial-well-being/about/es/ and make sure it looks like the screenshot below
2. Make sure the new link points to /data-research/research-reports/measuring-financial-well-being-hispanics-2018-benchmarks/
3. Make sure the English about page, /consumer-tools/financial-well-being/about/, is unchanged from what's in production
- There is no change needed for the English about page; this content should only …
=> Update Spanish content for FWB about page

requirements/libraries.txt
Security Update for the Curriculum Review Tool. Update from release 2.1.3 to 2.1.4. 
See [PR #420](https://github.com/cfpb/curriculum-review-tool/pull/420)
=> CR Tool: update crtool release number to 2.1.4

docs/profiling-django.md
The "Profiling Django" document has a broken image because the image path has a leading slash. This change removes it.
=> Remove leading slash from image in Profiling Django docs

cfgov/jinja2/v1/_includes/organisms/mega-menu.html
- Mega Menu: translate submit a complaint text to spanish on spanish-version of page.
1. Pull branch and build
2. visit homepage or any other standard page. 
3. Resize to mobile and open the hamburger menu.
4. See that "Submit a Complaint" at that top of the menu is in english.
5. Visit /es/ spanish page open the hamburger menu and see that the complaint link is translated into spanish.
Before:
After:
=> Mega Menu: translate submit a complaint text to spanish on spanish-version of page

cfgov/unprocessed/apps/paying-for-college/css/college-costs/state-based.less, cfgov/unprocessed/apps/paying-for-college/js/models/financial-model.js, cfgov/unprocessed/apps/paying-for-college/js/util/debt-calculator.js, cfgov/unprocessed/apps/paying-for-college/js/views/app-view.js, cfgov/unprocessed/apps/paying-for-college/js/views/school-view.js
This Pull Request fixes problems with the calculations of federal Direct loans for non-first-year students. It also fixes the limits enforced on Direct subsidized loans based on "progress" of the student (years they have spent in a program).
- Change calculations to fix non-first-year debt totals
- Change Direct loan limits to match non-first-year limits
- Change CSS to fix some errors in non-first-year content
* Pull it down and get it running.
* The following should be true:
* The limit for first-year students Federal Direct subsidized loans should be $3500
* Second-year should be $4500
* Third year should be $5500
* Debt totals should reflect that we are assuming the user increases their subsidized loan amount each year (so that the percentage of total subsidized loan limit is taken …
=> Paying for College - Non-first-year fixes

cfgov/cfgov/settings/base.py
Googleoptimize was added to the CSP settings in https://github.com/cfpb/consumerfinance.gov/pull/6454, but it is still being blocked. This adds it to the frame and ajax settings.
- Add googleoptimize to CSP frame and ajax items
1. Will be tested on production.
=> Add googleoptimize to CSP frame and ajax items

cfgov/jinja2/v1/_layouts/base.html
When testing the A/B optimize script, the change in the hero flicker was apparent, so we should add the anti-flicker script detailed in https://support.google.com/optimize/answer/7100284
Also, remove the inline optimize script as we're delivering it via GTM.
- Remove inline optimize script.
- Adds optimize anti-flicker script.
1. Will be tested on production :-\
=> Add google optimize anti-flicker script

cfgov/unprocessed/apps/paying-for-college/css/college-costs/search.less, cfgov/unprocessed/apps/paying-for-college/js/views/school-view.js, test/cypress/integration/pages/paying-for-college/your-financial-path-to-graduation.js, test/cypress/pages/paying-for-college/your-financial-path-to-graduation.js
This pull request fixes a bug which causes the results of the school search remain on screen when a school is deleted from the box. 
- Adds a check for an empty string in the search bar, and hides the results list when found
- Prevents requests to the search API when the string length is less than 2. This simply reinforces code already found in the API call function.
1. Pull this PR down.
2. Search for a school, but don't select a result. Instead, delete characters. The results box should disappear once your search term reaches 2 characters or less.
=> Paying for College - School search dropdown fix

cfgov/unprocessed/css/enhancements/layout.less
W/r/t https://github.com/cfpb/consumerfinance.gov/pull/6465, We only want to bump headings within full width text blocks and not components like FCMs.
=> Scope oversized headings to full width text groups

docs/python-unit-tests.md, requirements/ci.txt, requirements/test.txt, tox.ini
This small change adds a tox env that will run `diff-cover` on the coverage generated by `unittest-current` or `unittest-future`. This is intended as a convenience means of reporting out the change in test coverage vs `main` that doesn't require running `diff-cover` directly.
I have not changed the GitHub actions for now, as I think it's important to maintain consistency between the backend and frontend actions.
1. Run `tox -e unittest-current` on a branch with changes from `main`, and then run `tox -e coverage`. Alternatively, run `tox -e unittest-current,coverage`. Observe that coverage is reported out like it is in our GitHub Actions.
=> Add a tox env for backend test coverage

cfgov/jinja2/v1/_layouts/base.html, cfgov/legacy/templates/front/base_update.html
Closes https://github.com/cfpb/consumerfinance.gov/issues/3531
- Removes recruiting code comment that is on a legacy page and is not under a flag.
- Removes reference to `https://www.consumerfinance.gov/jobs/technology-innovation-fellows/` that is now redirecting to the careers page, which is also linked to earlier in the code comment.
1. Since these are code comments, just look at the changes in the PR.
=> Removed outdated job link comment

Jenkinsfile
Use hub.docker.com.
Fixes authentication failures at registry.hub.docker.com. POSTing to that domain returns HTTP 503.
=> Update public Docker Hub domain name

cfgov/jinja2/v1/_includes/organisms/filterable-list-controls.html
- Moves the filters to their own code blocks.
- Move the date filters to the left-hand column.
1. Visit the following filters pages and compare to localhost. They should be the same as production other than the dates should be moved to the left (and on the FOIA page filter, the dates should be on their own line):
https://www.consumerfinance.gov/activity-log/
https://www.consumerfinance.gov/about-us/newsroom/
https://www.consumerfinance.gov/about-us/blog/
https://www.consumerfinance.gov/enforcement/actions/
https://www.consumerfinance.gov/administrative-adjudication-proceedings/administrative-adjudication-docket/
https://www.consumerfinance.gov/compliance/supervisory-guidance/
https://www.consumerfinance.gov/data-research/research-reports/ …
=> Filters: Organize optional filters into their own blocks and move date filters to the left-hand column

cfgov/newrelic.ini, requirements/deployment.txt
This change adds 429: Too Many Requests to our list of ignored status codes for New Relic. We occasionally have [`rest_framework.exceptions.Throttled`](https://www.django-rest-framework.org/api-guide/exceptions/#throttled) show up in our error violations, when it shouldn't because that's a valid exception to throw when we intend to throttle API requests.
Per the [New Relic documentation](https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration/#error-ignore-status-codes), it sounds like this should work, because Django does use exceptions to return HTTP responses. If this doesn't work, we can add the exception to [`error_collector.expected_classes`](https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration/#error-ignore). …
=> Have New Relic ignore exceptions that generate HTTP 429

cfgov/agreements/jinja2/agreements/index.html
Previously, the breadcrumbs on the Credit Card Agreement Database page contained a link to a non-existent page, `/credit-cards/`. Redirects.conf redirects that URL to `/data-research/credit-card-data/`. Now, the breadcrumbs will point to the canonical path instead of a redirect.
- CFPB/hubcap wiki on GHE – for internal CFPB design and …
=> Update breadcrumbs to use canonical path

requirements/wagtail.txt
Pin Wagtail to 2.13.3. This will upgrade us to Wagtail 2.13.
=> Pin Wagtail to 2.13

.env_SAMPLE
Based on recent onboarding feedback, the final section of the .env_SAMPLE file should be simplified. 
- The DATABASE_URL fails for people who don't have a PGPASSWORD set, and is unnecessary for those who do.
- We're reworking how we manage virtual environments, and we can drop the closing activation line.
This won't affect anyone's current environment, only those who are starting fresh.
=> Fix the closing local section of .env_SAMPLE

Jenkinsfile
This change has our dev Docker deploys run our internally defined functional test job against the newly deployed stack and report back to PRs.
This should give us the benefit of running the functional test suite against PRs again.
=> Run our internal functional test job against PR deployments

cfgov/ask_cfpb/models/search.py, cfgov/ask_cfpb/tests/test_search.py
Occasionally we hit an `elasticsearch7.exceptions.RequestError` in the Ask CFPB autocomplete search method because the `search_phase_execution_exception` character limit is reached. This change catches that error so that it doesn’t propogate, and returns an empty of list of autocomplete results instead.
I've also added explicit tests for `AnswerPageSearch.autocomplete`.
=> Catch an ElasticSearch RequestError in autocomplete

cfgov/unprocessed/js/admin/table-block.js
We enable only a subset of available rich text features in the editor we use for table content; currently line breaks are not enabled. We now need line breaks for a couple of tables, so we're enabling them. See GHE/CFGOV/platform/issues/4096 for more details.
---
- Enable line breaks in table cells
1. Go to a page with a table on it. /consumer-tools/educator-tools/resources-for-older-adults/financial-security-as-you-age/ is a great example (and the reason we need to enable line breaks).
2. Add some line breaks to some table cells either with the Draftail line break button or with `shift + return`.
3. Preview the page and make sure the line breaks show up. Note! For some reason tables with line breaks in them render with two `<br>`s. This doesn't happen in non-table rich text content, so …
=> Enable line breaks in table cells

cfgov/ask_cfpb/tests/test_blocks.py, cfgov/jinja2/v1/_includes/ask/content-block.html
Prior to [Wagtail 2.12.5](https://docs.wagtail.io/en/stable/releases/2.12.5.html) `include_block` was improperly escaping HTML, resulting in CVE-2021-32681 (🎩  to @niqjohnson for catching this). Unfortunately we were relying on that behavior for rendering of table blocks in Ask CFPB content.
This fix explicitly turns off autoescape for table blocks in Ask CFPB content blocks.
=> Fix Ask CFPB table block rendering

docker-compose.yml, docker/elasticsearch/7/Dockerfile
Security vulnerabilities were discovered in version 7.10.1
- Stop using blacktop docker images as they have not been updated for months
- Start using official elasticsearch and kibana docker images which were updated last month
- The following files are impacted:
1. Dockerfile
2. docker-compose.yml
3. Jenkinsfile
Verify applications that use elasticsearch7 are not impacted:
1. AskCFPB
2. Filterable lists
3. Paying For College
4. Regulations
5. Teachers Digital Platform
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` …
=> Upgrade elasticsearch and kibana docker images to 7.13.3

cfgov/legacy/templates/front/base_update.html, cfgov/unprocessed/css/on-demand/footer.less, cfgov/unprocessed/css/on-demand/header.less, gulp/tasks/styles.js
Our legacy base template that ccdb-ui uses has special non-responsive styles for the header and footer that appear to do nothing. The page is unusable in IE9 anyway. 
- non-responsive header and footer CSS and associated gulp tasks.
1. Pull branch, build and run a local server.
2. Boot up Sauce Connect.
3. In Sauce Labs IE9 compare http://localhost:8000/data-research/consumer-complaints/search/ to https://www.consumerfinance.gov/data-research/consumer-complaints/search/
4. There should be a menu (albeit difficult to see with all the reloading that happens)
=> CCDB: Remove non-responsive header and footer CSS

cfgov/paying_for_college/disclosures/scripts/update_colleges.py, cfgov/paying_for_college/models/__init__.py, cfgov/paying_for_college/models/disclosures.py, cfgov/paying_for_college/tests/test_scripts.py
We've had an obviously fictional school – Example University – in our paying_for_college database for several years, for demo purposes. Now we want to have three more options, in order to show schools typical of different sizes.
This change adds three demo-school primary keys to be excluded from updates
and most other live operations. So the former `FAKE_SCHOOL_PK` constant becomes a list.
This should have no effect on the legacy EFIP tool or the financial-path tool.
=> Expand fake-school options

cfgov/v1/models/home_page.py
Currently HomePages can only be created at the site root. We want themto be able to exist elsewhere for better multi-language support. This commit removes this restriction to allow for creation of HomePages at any location in the page tree.
See platform#4103 for additional context.
=> Allow HomePages to be created anywhere

mkdocs.yml
#6356 added a new documentation page about filterable lists, but neglected to add it to the mkdocs configuration, so it doesn't show up in the sidebar. This commit adds it to the "Supporting Features" part of the documentation.
=> Add filterable lists page to documentation sidebar

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py, cfgov/cfgov/settings/production.py, cfgov/v1/forms.py
#6532 added a new Elasticsearch aggregation to filterable list search results, but neglected to account for cached ES results that may not have that aggregation.
This commit adds a check so that old cached data won't cause search pages to 500. The cache will still need to be manually cleared for now to get the language choices to properly update.
As discussed with @willbarton, this is a temporary fix that can hopefully be improved with a smarter strategy overall around these caches (including perhaps getting rid of them altogether).
I've also included a setting change here to make it easier to enable Django caches locally.
=> Handle filterable list results without aggregation

cfgov/unprocessed/apps/rural-or-underserved-tool/js/call-tiger.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/common.js
We built this tool for some prior year version of the tigerweb API, but pegged it to current. In the years since it has updated and the layer mappings don't work anymore.
- Change API version and layer mappings from current to 2019.
1. Pull branch, `gulp clean && gulp build`, and visit http://localhost:8000/rural-or-underserved-tool/ and enter an address and see that it resolves. Compare to production where it hangs and has a console.log error.
=> Rural or underserved tool: Update tigerweb API version mappings

cfgov/v1/jinja2/v1/home_page_2021.html, cfgov/v1/models/home_page.py, cfgov/v1/tests/models/test_home_page.py
#6560 added a new stub template for a new 2021 version of the website home page. This commit adds the ability to preview this new version directly from the Wagtail editor, without having to publish it, and in the production environment where the new template is not yet enabled.
On the page edit view, the Preview button now becomes a dropdown with the ability to preview the new template:
This commit also includes a minor edit to the stub template to make it easier to distinguish from the current one.
=> Add ability to preview the 2021 home page version

cfgov/jinja2/v1/rural-or-underserved/index.html, cfgov/unprocessed/apps/rural-or-underserved-tool/js/call-census.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/common.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/content-control.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/file-input.js
When the census API calls don't return what we expect the app just logs an error to the console. This PR changes that to show an error notification.
- Add error notification logic when the call to the census API fails.
- Remove unused content JS.
- Change camel case `id` names to dashes.
- Wrap process error notification text in a paragraph so it's spaced adequately from the list of addresses.
- Move the error notifications to their own blocks outside of the search tool (so they show up on the results view too).
1. Pull branch and enter an address. The API is returning an error right now so it should show an error notification.
=> Rural or underserved tool: Show error when API call is down

cfgov/regulations3k/wagtail_hooks.py
It appears that in Django 3.2, the removal of an instance's primary key breaks access to related models. 
By capturing the key before copying, we can get to the related models again.
=> capture pks before copy operations

cfgov/unprocessed/apps/teachers-digital-platform/css/pages/survey.less
mobile breakpoint for survey questions
---
-
-
-
1.
-
=> Add mobile styles for survey quesitons

cfgov/jinja2/v1/your-story/index.html
Updates the relief amount on the Tell Your Story landing page to the current amount.
---
-  $4 billion -> $14.4 billion
1. Confirm the text on `/your-story/` says "Since we began in 2011, we’ve helped return $14.4 billion to American consumers as a result of our enforcement actions."
=> Update Tell Your Story relief stats

cfgov/unprocessed/js/organisms/MegaMenuMobile.js
Follow on to https://github.com/cfpb/consumerfinance.gov/pull/6568
The :not selector in that code is actually invalid, per https://www.w3.org/TR/selectors-3/#negation (simple selectors only in negation, the white space in a combinator).
I just changed the selector here to match the same set of links that were being matched by the :not() selector in lenient browsers.
To test this equivalence in devtools:
```
const menu =document.getElementsByClassName('o-mega-menu')[0]
let a = menu.querySelectorAll( 'a:not(.o-mega-menu_content-2 a)' )
let b = menu.querySelectorAll( 'a.o-mega-menu_content-1-link,.m-global-eyebrow a' )
;(() => {
if(a.length !== b.length) return console.log('UNEQUAL')
for(let i = 0; i <a.length; i++){
if(a[i] !== b[i]) return console.log('UNEQUAL')
}
console.log('All links …
```
=> Change invalid :not selector to an equivalent selector

cfgov/unprocessed/apps/retirement/css/claiming.less
See https://[GHE]/CFGOV/platform/issues/3177
- Change color of tooltip icons from black to blue. 
- Adjust tooltip icon size to make them small in the body copy.
1. Visit http://localhost:8000/consumer-tools/retirement/before-you-claim/ and check the (?) tooltip icons. They should be pacific instead of black and slightly smaller (except the top one, which gets a little larger).
Before:
After:
=> Retirement: Fix actionable tooltips color and size

cfgov/jinja2/v1/owning-a-home/_templates/brand-footer.html
- Ending quote was on the wrong line and was messing up the markup.
1. Check the markup for links on http://localhost:8000/owning-a-home/closing-disclosure/
=> Buying a House: Fix misplaced closing quote in disclosures template

cfgov/unprocessed/apps/teachers-digital-platform/css/pages/survey.less
=> [WIP] Reduce padding so that answers fit on one line

cfgov/jinja2/v1/rural-or-underserved/_templates/expandable.html
A link in one of the expandables on the rural and underserved tool page was getting rendered with escaped HTML. This PR adds the `safe` filter to the `expandable.render` macro to get the HTML to render. Technically the `safe` filter was only needed on `{{ content }}`, but I added it on ``{{ heading }}`` for good measure.
---
- `safe` filter to `expandable.render` macro
1. Load up `/rural-or-underserved-tool/`
2. Open up the "I typed in an address and a different address was found. Why?" expandable
3. Make sure the link in that content renders as a link instead of escaped HTML
4. Make sure nothing else on the page has changed
Before | After
---- | ----
- Consider prefixing, …
=> Fix rural and underserved tool content

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-3-5.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-graph.html, cfgov/unprocessed/apps/teachers-digital-platform/css/pages/survey-results.less, cfgov/unprocessed/apps/teachers-digital-platform/img/marker.svg
=> [WIP] fix spacing for car/labels

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/form-page.html, cfgov/unprocessed/apps/teachers-digital-platform/css/pages/survey.less, cfgov/unprocessed/apps/teachers-digital-platform/js/expandable-mobile.js, test/unit_tests/apps/teachers-digital-platform/js/expandable-mobile-spec.js
=> [WIP] Add form mobile, increase expandable mobile to the 900px bp

cfgov/ask_cfpb/forms.py, cfgov/ask_cfpb/models/search.py, cfgov/ask_cfpb/tests/test_search.py, cfgov/ask_cfpb/tests/test_views.py, cfgov/ask_cfpb/wagtail_hooks.py, cfgov/jinja2/v1/_includes/organisms/ask-search.html, cfgov/search/models.py, cfgov/v1/jinja2_environment.py
Most of long autocomplete entries will be blocked by front-end code,
but if bots or mischief-makers send long autocomplete requests to our back end,
this change will happily ignore anything over 50 chars.
The constant, `AUTOCOMPLETE_MAX_CHARS`, will live in cfgov/search/models.py.  
It is used to limit the autocomplete queries sent to Elasticsearch to 50 characters,     
and gets delivered to the template and JS via jinja2.environment.globals.
Turn on readable Elasticsearch logging by setting this env variable locally (courtesy of @chosak):
```
export ENABLE_ES_LOGGING=1
```
This lets you easily see the request that the back end sends to Elasticsearch in the runserver console.
Then send way more than 50 characters to the ask_cfpb autocomplete API:
``` …
```
=> Add a back-end 50-character limit to autocomplete submissions

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/form-page.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-3-5.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-6-8.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-9-12.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-save.html
- Adds a horizontal line above share/print section of results pages.
- Replaces HRs with borders.
- Changes inline error text.
=> [TDP Survey] Add line above last section, no hr

.github/workflows/frontend.yml
Not totally sure of the implication of this, but the docs show `@v2` with node 14, which is the version we have set https://github.com/actions/setup-node
- Update actions/setup-node to v2 from v1
=> Update actions/setup-node to v2 from v1

cfgov/cfgov/urls.py, cfgov/core/decorators.py, cfgov/core/tests/test_decorators.py
This commit adds an Edge-Control: no-cache header to the sitemap.xml view, which changes how Akamai will cache the sitemap.
Currently, the sitemap is cached like most every other page on the site: served from cache for 7 days without revalidation with the origin, then revalidated after that and re-sent from origin if necessary. This is problematic for the sitemap because it should be updated whenever a new page is published.
With this change, the Akamai-specific Edge-Control header is used, described thusly [in the Akamai docs](https://techdocs.akamai.com/start/docs/caching):
> The Edge-Control header is an Akamai-specific HTTP response header header that provides controls and parameters on content served through the edge network. On the Akamai network, Edge-Control settings settings …
=> Limit Akamai caching of sitemap.xml

cfgov/cfgov/urls.py, cfgov/core/decorators.py, cfgov/core/tests/test_decorators.py, cfgov/teachers_digital_platform/tests/test_views.py, cfgov/teachers_digital_platform/views.py
Followup to #6647; use no-store instead of no-cache for the cf.gov sitemap.xml file. Consolidate logic that does this with existing TDP view logic that does the same thing.
```
$ curl -Is http://localhost:8000/sitemap.xml | grep Edge-Control
Edge-Control: no-store
```
=> Consolidate decorator to prevent Akamai caching

cfgov/mega_menu/tests/test_model_admin.py, cfgov/mega_menu/views.py
Currently, the mega menu preview view ([for example](http://localhost:8000/admin/mega_menu/menu/preview/es/)) doesn't properly render using non-English translations.
This is because even though translations are activated during the view render call itself, TemplateViews return a TemplateResponse that isn't actually rendered until after the view logic has ended. Wagtail has [some custom logic](https://github.com/wagtail/wagtail/blob/cf064f2b9990e90f5c5ca5d4405fe75a16604e0a/wagtail/admin/auth.py#L174-L191) that ensures that admin views render in the user's default language, which overrides custom languages as in the menu preview.
This commit manually renders the template view response so that it gets rendered while the proper translation is activated.
Fixes internal platform#4190.
[Create a …
=> Properly translate mega menu previews

cfgov/v1/atomic_elements/atoms.py, cfgov/v1/atomic_elements/molecules.py, cfgov/v1/atomic_elements/organisms.py, cfgov/v1/tests/atomic_elements/test_molecules.py
This pull request is to replace an older validation error with its newer version for when we update wagtail. The point is to make sure when new page previews are being made incorrectly the error is still reported correctly.
---
instead of using ValidationError in atoms molecules and organisms, we will now use StructBlockValidationError. It functions more or less the same, the big differences is the removal of the first string and changing params into block_errors
1.go to the admin wagtail page
2.click add a new page
3. create an error in the page like adding a red header with no header and click preview
4. there should be an error on the header now saying a header is required
-
- PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to …
=> Wagtail: Error Update

cfgov/regulations3k/tests/test_blocks.py, cfgov/regulations3k/tests/test_pages.py, cfgov/regulations3k/tests/test_views.py
This should have no effect on the tests or any other code.
=> Remove dead flag from regulations3k tests

requirements/libraries.txt
CCDB is the last consumerfinance.gov app using Elasticsearch 2, and this change
moves all operations to our AWS Elasticsearch 7 service.
The CCDB code imported here is running on our DEV5 server for testing.
~This PR needs to **HOLD** until we get a release date.~
Release date is 9/13. PR should **not be merged** until then.
=> Update the ccdb5-api and ccdb5-ui releases for Elasticsearch 7

requirements/libraries.txt
Until bugs are resolved, we need to go back to the ES2 CCDB releases.
=> revert CCDB5 update

requirements/libraries.txt
Release 2.4.4 resolves a UI bug in two filter choices, ZIP codes and companies, when pagination is in play.
=> Update ccdb5-ui release for bug fix

docker-compose.yml, docker-stack.yml, docker/elasticsearch/7/Dockerfile, docker/elasticsearch/Dockerfile, docker/elasticsearch/docker-entrypoint-es-plugins.sh
Now that consumer complaints are being indexed in Elasticsearch-7, we no longer
need to support operations in the unsupported version 2.
This change removes references to Elasticsearch-2 from configurations
and stops building ES2 containers.
To test, you'll need to take down your local cfgov Docker environment and bring it up again.
I tested by removing all containers, networks, etc with `docker system prune -af`, and starting fresh with this configuration, and it delivered a working set of services minus ES2.
For testing, you should be able to just take your local stack down and up, but be aware that you'll probably have to restore postgres and elasticsearch data after this:
```bash
docker-compose down
docker-compose up
```
Then check `docker-compse ps` to see that Elasticsearch2 is no …
=> Remove Elasticsearch2 from Docker configs

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py
These feature flags are no longer needed, but have references in code:
- `CCDB5_RELEASE`
- `CCDB5_TRENDS`
- `INSET_TEST`
- `YOUTH_EMPLOYMENT_SUCCESS`
Once this change is merged, we can delete the flag references in Wagtail
to complete the removal from code and database.
=> Remove code for retired feature flags

cfgov/unprocessed/js/organisms/VideoPlayer.js
Currently, Lighthouse will consistently timeout when run against any website page that uses our VideoPlayer module. This is because of a potential infinite loop in its JS code that can be triggered by a certain Lighthouse test. This commit fixes that bug and allows for successful audits of these pages with Lighthouse.
See [here](https://github.com/cfpb/cfgov-lighthouse/runs/3715284303?check_suite_focus=true) for an example of a failing Lighthouse test on [one of these pages](https://www.consumerfinance.gov/about-us/blog/economic-impact-payment-prepaid-card/).
The reason for the failures is down in the Lighthouse code -- currently LH runs an audit called `redirects-http` that verifies that a request to a URL with HTTP always gets redirected to HTTPS. Instead of using a HEAD request or …
=> Fix Lighthouse timeout on pages with video players

cfgov/unprocessed/css/pages/ask.less
-Changed contrast to meet WCAG 2.1 AA criteria
1. Go to /ask-cfpb/how-do-i-find-an-attorney-in-my-state-en-1549/
2. Open dev tools and hover over "Last Reviewed" section
3. Notice there is no more contrast warning
Related [ghe]/CFGOV/platform/issues/4159
=> Fixed color contrast to meet WCAG 2.1 AA criteria

cfgov/v1/jinja2/v1/template_debug.html
- Changes template debug view example outline to an actual offset outline.
1. Visit a template debug view and see there's a light dashed outline around examples.
=> Create new template debug outline

requirements/libraries.txt
This is the last vestige of our use fo the custom elasticsearch7 library.
Now that ccdb5-api is no longer importing it, we can remove it from requirements.
=> Update ccdb5-api version to 1.6.2 to remove elasticsearch7 imports

cfgov/agreements/jinja2/agreements/index.html
Add a link to Q2 2021 credit card agreements. This update does not include the regulatory flexibility statement, because the stakeholder let us know that it does not apply beginning in Q2 2021.
We are set to publish this change (along with the updated set of credit card agreements in the dropdown) on Monday, 10/4/2021.
- Link to Q2 2021 credit card agreements.
=> Quarterly update to credit card agreements page

cfgov/templates/wagtailadmin/css/table-block.css, cfgov/unprocessed/js/admin/rich-text-table.js, cfgov/v1/atomic_elements/tables.py
This is truly the hackiest hack I have ever hacked, but this seems to be a reliable way to be able to interact with the Wagtail link picker while editing a table cell. The main change is the `_handleModalClicks` event handler that stops `mousedown` propagation when both a table editor is open and a modal is showing. No propagation means the table editor's `close` method never gets called when you click anything with a Wagtail modal showing, which was the only reliable way I could find to make the link picker work when editing a table cell.
I was hoping to use something less hacky like [Handsontable hooks](https://handsontable.com/docs/api/hooks/), but (a) I couldn't actually get a hook working (probably a better JS developer could) and (b) I didn't see a hook that would prevent the editor …
=> Fix the link picker for table blocks

cfgov/cfgov/settings/base.py, requirements/libraries.txt
This PR adds the [django-cors-headers](https://pypi.org/project/django-cors-headers/) package to automatically add Cross-Origin Resource Sharing (CORS) headers via settings and middleware to allow origins specified in the `CORS_ALLOWED_ORIGINS` environment variable.
The intended use of this is to permit GovDelivery subscriptions from the [HMDA pages](https://ffiec.cfpb.gov/).
To test the CORS Access-Control-Allow-Origin header, set the `CORS_ALLOWED_ORIGINS` environment variable to a valid JSON array of origins:
```bash
export CORS_ALLOWED_ORIGINS=[\"https://example.com\"]
./runserver.sh
```
Then send the `Origin` header in a test request with one of those origins:
```bash
curl -I -H "Origin: https://example.com" http://localhost:8000
```
And observe the `Access-Control-Allow-Origin` …
=> Add django-cors-headers and env var for origins

docs/functional-testing.md
After I forgot how to run Cypress tests for the millionth time I took a pass at updating our functional testing docs with better instructions for running tests from the command line. While I was in there I also made some changes that hopefully improve organization and readability.
---
- Revise functional testing docs
1. Fire up the docs page locally at http://localhost:8888/functional-testing/ (automatically running if you're using Docker, started with `mkdocs serve -a :8888` if you're running locally)
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) …
=> Update functional testing docs

docker/deployable-zipfile/Dockerfile
Fixes the weird `[Errno -1] Package does not match intended download.` issue on build by grabbing the package directly beforehand.
=> Grab the node rpm package directly, prevently mirror mismatch trouble

requirements/libraries.txt
Version 1.6.3 removes references to `ES7_HOST` and `COMPLAINT_DOC_TYPE` from the API.
=> Update ccdb5-api version to 1.6.3 to sync env vars

.env_SAMPLE, cfgov/cfgov/settings/base.py, cfgov/search/elasticsearch_helpers.py, docker-compose.yml, docker-stack.yml
This commit tries to simplify how we configure Elasticsearch via environment variables, for virtualenv/local Docker/deployed Docker.
Currently, as of #6695, Django will use the combination of ES7_HOST and ES_PORT to configure the Elasticsearch client. ES_HOST is no longer used anywhere, since our migration to Elasticsearch 7.x. In Django settings, these default to localhost/9200 if the environment variables are not defined.
This PR changes this so we standardize everywhere to ES_HOST and ES_PORT.
With this change, the following configurations are still supported:
1. Local virtualenv - these settings are now no longer set in .env, but default to localhost/9200 for a locally-running Elasticsearch. The definitions have been left in .env_SAMPLE commented out for documentation purposes.
2. …
=> Simplify Elasticsearch environment variables

cfgov/v1/models/learn_page.py, cfgov/v1/tests/models/test_event_page.py
This commit adds the HTTP Expires header to EventPages if they have a state change in the future, for example before an event begins or during an event with an end timestamp.
This header will allow for (a) client browsers to properly refetch the page when its state has changed and (b) downstream caches like Akamai to automatically expire cached versions of the page.
HTTP Expires headers are of the form "Tue, 04 Jan 2011 00:00:00 GMT".
Addresses internal platform#4081.
The unit tests validate that calling `page.serve()` on EventPages in the past, present, and future all return the proper and expected `Expires` header (or lack thereof). This is also confirmable manually if you use the Django server and create EventPages in Wagtail that are past, present, or future. I've also confirmed that …
=> Add HTTP Expires header to EventPages if needed

cfgov/v1/atomic_elements/atoms.py, cfgov/v1/tests/atomic_elements/test_atoms.py, cfgov/v1/tests/atomic_elements/test_molecules.py
**Note**: Two try/except clauses in `atoms.py` tried to catch `StructBlockValidationError`, but I don't think that error will ever be raised at that point, so I removed the clauses. I can force other errors to occur –`ValueError` or `KeyError`, for example – but there doesn't appear to be any validation defined for `StructBlockValidationError`, other than in `atoms.py` itself or in wagtail's `telepath` js, which runs clent-side.
=> add tests to meet coverage requirements

cfgov/unprocessed/root/data.json
Our data.json file was invalid JSON because of some trailing commas, but the [data.gov validator was still seeing it as valid](https://labs.data.gov/dashboard/validate).
This change removes those trailing commas, and the file parses as valid JSON and passes the data.gov validator.
1. Confirm that the contents of the data.json file are valid JSON with https://jsonlint.com/
2. Confirm that the contents of the data.json file are valid for the federal data.json schema with https://labs.data.gov/dashboard/validate
=> Remove some trailing commas in our data.json file

cfgov/cfgov/settings/base.py, cfgov/privacy/forms.py, cfgov/privacy/tests/test_forms.py, cfgov/privacy/tests/test_views.py
Add tests for Django views and for additional form behavior. Improve some forms code to reduce passing unnecessary variables.
- Tests
- Refactor `forms.py`
1. Make sure no functionality changed from #6759 
=> Refactor privacy forms and improve tests

cfgov/privacy/jinja2/privacy/disclosure-consent-form.html, cfgov/privacy/jinja2/privacy/records-access-form.html
A leading slash can bork staticfiles manifests
=> Fix static files bug in privacy app

cfgov/cfgov/settings/local.py
The Django setting `ELASTICSEARCH_SYNONYMS_HOME` is no longer needed, now that we have transitioned from Elasticsearch 2.
The setting was introduced in #6098 and then removed in #6122, but this one mention was left behind.
[It's not used anywhere in our code.](https://github.com/search?q=ELASTICSEARCH_SYNONYMS_HOME+user%3Acfpb&type=code)
=> Delete deprecated Elasticsearch 2 synonyms setting

cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js
Excel will sneak in quotes when saving as csv (appropriate) but this can break our comment-detection logic if it makes a line start with a quote.
=> [simple-chart] Remove leading quotes from comment strings when excel sneaks them in

cfgov/teachers_digital_platform/surveys.py, cfgov/teachers_digital_platform/tests/test_surveys.py
Handles unexpect missing survey answers by grading them as the first choice.
I examined the cookie `wizard_survey_wizard` contents that resulted in one answer being read as empty string, and--in the cookie--all expected question values were present as a digit string 0 to 4. So I can only conclude that in some cases formtool's FormWizard class or their cookie storage adapter has a bug. I've never experienced this bug testing locally.
Handling of non-numeric string answers before the integer cast.
=> Don't allow formtools bug to cause internal errors

cfgov/privacy/jinja2/privacy/disclosure-consent-form.html, cfgov/privacy/jinja2/privacy/records-access-form.html
Minor content edits in the Privacy forms: change "agency" and "Bureau" to "CFPB".
=> Privacy forms: minor content edits

cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, cfgov/jinja2/v1/_includes/molecules/global-search.html, cfgov/jinja2/v1/_includes/organisms/header.html, cfgov/jinja2/v1/_includes/snippets/search_gov.html, cfgov/jinja2/v1/_layouts/base.html, cfgov/jinja2/v1/robots.txt, cfgov/v1/jinja2/v1/header.html, cfgov/v1/jinja2tags/__init__.py, cfgov/v1/tests/jinja2tags/test_jinja2tags.py, docs/feature-flags.md
This PR modifies the behavior of the website when deployed to beta.consumerfinance.gov, so that global site searches use beta-specific search indexes. Recall that our global site search currently uses Search.gov and has two indexes: `cfpb` for regular English-language pages and `cfpb_es` for Spanish-language pages.
This change modifies how the website works on beta such that it uses `cfpb_beta` and `cfpb_beta_es`. This is reflected two ways: first, the header search now queries Search.gov with those affiliate codes; and second, the Search.gov [JavaScript snippet](https://search.gov/manual/code.html) now uses these codes as well. Under the hood this behavior relies on our existing `DEPLOY_ENVIRONMENT` Django setting.
In order to support search on beta, this PR also modifies how we serve …
=> Introduce distinct search for beta.consumerfinance.gov

cfgov/apache/conf.d/alias.conf
#6788 tried to move robots.txt into Django, but neglected to remove the existing Apache rule for that alias. That was an oversight, which is corrected by this commit.
Run a local server and verify that http://localhost:8000/robots.txt still works as expected.
=> Don't serve robots.txt from Apache

docs/page-search.md, docs/site-search.md, mkdocs.yml
We don't currently have any documentation about our use of Search.gov for global site search. This commit adds some.
New page available under http://localhost:8000/site-search/:
=> Add documentation for Search.gov site search

cfgov/cfgov/tests/test_urls.py, cfgov/cfgov/urls.py
We use the flagged endpoint `/beta_external_testing/` to signal that
testing is in progress on the beta site. When the flag is taken down,
we want the endpoint to immediately return 404, but the 200 response is getting cached.
This adds an `Akamai-Cache-Control: no-store` header to the 200 response so that
it is never cached.
This satisfies internal GHE platform issue `#4286`
- Locally enable the [BETA_EXTERNAL_TESTNIG](http://localhost:8000/admin/flags/BETA_EXTERNAL_TESTING/) flag.
- Open dev tools' network panel and hit <http://localhost:8000/beta_external_testing/>
- Confirm that the endpoint returns a 200 response with a response header of "Akamai-Cache-Control: no-store".
=> Stop Akamai from caching the beta_external_testing endpoint

cfgov/unprocessed/css/organisms/simple-chart.less, cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/tilemap-styles.js
Currently the range selector layout on safari is quite buggy and legend/tilemap labels are overly bold.
This commit fixes both problems.
Testing:
pull and build, open in safari, should look fine. Compare against content (which looks busted).
=> Fix safari boldness and alignment bugs

cfgov/v1/models/__init__.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/caching.py, cfgov/v1/signals.py, cfgov/v1/tests/atomic_elements/organisms/test_email_signup.py, cfgov/v1/tests/models/test_browse_filterable_page.py, cfgov/v1/tests/models/test_caching.py, cfgov/v1/tests/test_signals.py
The goal is to invalidate Akamai cache on all flavors of the newsroom landing page 
– including all variations of query-string faceting that have been cached – 
when a child page has been published.
The standard cache strategy of purging by URL doesn't work in this case,
because there are limitless query string combinations for categories,
topics, languages, date ranges and keywords.
Applying an Edge-Cache-Tag to all renderings of the NewsroomLandingPage
allows Akamai to invalidate all the variations it has cached at once.
Cache_tag invalidation is triggered when a NewsroomPage or a LegacyNewsroomPage
gets published.
We plan to test the triggered cache invalidation on beta.consumerfinance.gov.
In the meantime, you can see that the Edge-Cache-Tag is getting applied to all
variations of …
=> Apply "Edge-Cache-Tag" to NewsroomLandingPage headers

test/cypress/integration/components/filterable-lists/filter-blog-posts.js
Cypress tests are failing because it checks that the last entry on the first page of results is a 2020 dated post, but they are all 2021 at this point. This PR adds 1/1/2021 as the To date to bound the date range so the test will be consistent with added posts in the future.
- Cypress: Add To filter date to bound date range in test
2. `yarn run cypress run` should pass.
=> Cypress: Add To filter date to bound date range in test

cfgov/jinja2/v1/_layouts/base.html
According to https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch#best_practices, we shouldn't need to prefetch from our own domain, only for cross-domains. Also, it's suggested to pair the `preconnect` with the `dns-prefetch` hints, at least the most important ones.
- `dns-prefetch` for consumerfinance.gov URLs.
- Adds `preconnect` hint to fonts, google analytics, and search.usa.gov requests.
1. We'll probably want to just see how this performs on https://github.com/cfpb/cfgov-lighthouse (and—although unlikely—roll back, if necessary).
=> Base template: Edit prefetching section

cfgov/regulations3k/tests/test_blocks.py, cfgov/retirement_api/utils/tests/test_ss_utilities.py, cfgov/v1/management/commands/purge_by_cache_tags.py, cfgov/v1/models/caching.py, cfgov/v1/signals.py, cfgov/v1/tests/management/commands/test_purge_by_cache_tags.py, cfgov/v1/tests/models/test_caching.py, cfgov/v1/tests/test_signals.py
Currently we have signals that trigger a cache-tag purge
for newsroom searches when news items change, but we need
to be able to issue cache-tag purges from Jenkins, via
a management command.
This provides the command to handle automated purge requests.
The intial goal is to enable daily purges of complaint search
URLs in all their query-string varieties.
The actual application of cache tags to complaint response headers
will be in following PRs.
=> Add a managemant command for purging Akamai by cache tag

backend.sh
The existing test is [specific to](https://stackoverflow.com/questions/1871549/determine-if-python-is-running-inside-virtualenv) the virtualenv package that we no longer use.
This uses a generic venv test appropriate for Python 3.
Activate a pyenv virtualenv and run `./backend.sh`
You should get an incorrect error message: "Please activate your virtualenv before running this script."
Try running `./backend.sh` on this branch, and you should see requirements install.
=> Fix the test for a virtual environment in backend.sh

requirements/libraries.txt
When updating from psycopg 2.7 to 2.8, the way the binary package is included [has changed](https://www.psycopg.org/docs/install.html#change-in-binary-packages-between-psycopg-2-7-and-2-8).
This restores our 2.7 behavior.
=> manually specify psycopg-binary, now required in >= 2.8.x

cfgov/apache/conf.d/wsgi.conf
We need to temporarily roll back the wsgi config for Python 3.9 while we iron out deployment.  
This will unblock dev server deployments in the interim.
=> restore former wsgi config

cfgov/jinja2/v1/_layouts/base.html, cfgov/v1/blocks.py
https://github.com/cfpb/consumerfinance.gov/pull/6793 added dotted app asset paths, which broken in production. This PR changes the logic of how the paths for the assets are resolved.
- Bugfix: Remove dotted asset path by adding fork in the road for app JS vs on-demand JS
2. `./frontend.sh` and http://localhost:8000/coronavirus/mortgage-and-housing-assistance/renter-protections/find-help-with-rent-and-utilities/ should load.
=> Bugfix: Remove dotted asset path by adding fork in the road for app JS vs on-demand JS

cfgov/jinja2/v1/_includes/atoms/tagline.html, test/unit_tests/mocks/megaMenuSnippet.js
https://github.com/cfpb/design-system/pull/1314 added `Put tagline text in a container so we can inline-block it for IE11 legacy support.`, however, this change never made it outside of the DS example. 
- Add `a-tagline_text` class to tagline text to handle non-grid support scenarios.
1. In IE11, the tagline should not wrap.
before:
after:
=> Tagline: Add IE11 fix

requirements/libraries.txt
This change enables cache tags for CCDB API responses, which should resolve
internal GHE 4306.
The code has been pushed to DEV4, and an API response like the one below should show `Edge-Cache-Tag: complaints` in the response header.
DEV4/data-research/consumer-complaints/search/api/v1/?date_received_max=2022-01-18&date_received_min=2011-12-01&field=all&size=25&sort=created_date_desc&size=0
=> Bump ccdb5-api to version 1.6.4

cfgov/newrelic.ini
This change adds `rest_framework.exceptions:MethodNotAllowed` to our list of exceptions that are allowed to include their message in New Relic.
=> Allow Django Rest Framework MethodNotAllowed exception messages in New Relic

cfgov/v1/tests/test_wagtail_hooks.py
This change removes our mocking of a page, a request, and `hasattr` in the tests for the `form_module_handler` context hook. I've kept the mock of `get_streamfields` as it seems a decent way to inject only the field we want to test with into the handler.
This change also removes several superfluous tests that appear to have been built around the mocking.
This should fix some recursion errors we're seeing in backend tests since Python 3.8.
=> Mock less in form_module_handlers tests

docker-entrypoint.sh, refresh-data.sh
This change adds `./cfgov/manage.py search_index --rebuild -f` to our `refresh-data.sh` script so that we update the search indexes with the contents of the newly refreshed data when we refresh it.
This also moves the command out of the `docker-entrypoint.sh` script that gets run in our Python container. That script includes a call to `refresh-data.sh`.
=> Update the search index as part of refresh-data.sh

dump-data.sh
This change adds a script to make it easy to dump the local database. This is intended to be part of the workflow for creating and updating test data to use in the functional tests now that #6400 is. merged.
A database dump for the functional tests, and the process of creating and updating its contents will be documented separately.
The roughly intended usage is:
```shell
./dump-data.sh
./refresh-data.sh test.sql.gz
```
=> Add script to dump the local database

docs/translation.md
This adds a quick bit of troubleshooting help to our translation documentation around the version of gettext that Django invokes.
gettext below 0.20 [had an issue where a `POT-Creation-Date` field in the `.po` file would continue through into the `.mo` file](https://savannah.gnu.org/bugs/?59658#comment0). Django updates that date string every time `makemessages` is run. This will fail our validate-migrations check.
The fix is to ensure a version of gettext > 0.20.
=> Add troubleshooting around gettext and dates

docker-compose.yml
The current config of 128m doesn't allow indexing of our
current consumer complaint data, which is needed
for data products development.
We could probably return to the smaller value once
we have more robust dev and staging environments available
that include kibana and complete indexes.
=> Bump the ES_JAVA_OPTS config to 512m

cfgov/cfgov/urls.py, cfgov/legacy/tests/views/test_complaint.py, test/cypress/integration/data-research/consumer-complaints/consumer-complaints-helpers.js, test/cypress/integration/data-research/consumer-complaints/consumer-complaints.js
We're getting rid of the custom CCDB landing page template and using a standard Wagtail page instead. This is the first part of that work: removing the routing that points the CCDB landing page URL to the custom template and updating functional tests to match. There will be follow-up work to clean up the old template detritus later.
---
- Custom routing that directs `/data-research/consumer-complaints/` to the custom CCDB landing page template
- Unnecessary functional tests now that the CCDB landing page will be just a bunch of standard links on a standard page
- Functional test selectors to get new button names
1. Create a new page in Wagtail under "Data & Research" with the slug `consumer-complaints`
2. Visit `/data-research/consumer-complaints/` and make sure it resolves to that new …
=> Direct CCDB landing page to Wagtail

requirements/libraries.txt
This ccdb5-api release reduces pagination depth to 1K to make searches quicker.
=> Bump ccdb5-api to version 1.6.5

Dockerfile
Copy in `initial-data.sh` for the final prod image. This fixes deploying a fresh prod stack on local dev machines.
=> Copy initial-data.sh to prod image

cfgov/v1/models/filterable_list_mixins.py
This change enables draft sharing in `FilterableListMixin` by changing its inheritance from `RoutablePageMixin` to wagtail-sharing's `ShareableRoutablePageMixin`. We do the same for [`RegulationLandingPage`](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/regulations3k/models/pages.py#L156). Without `ShareableRoutablePageMixin`, wagtail-sharing can't share draft content on the sharing site. See https://github.com/cfpb/wagtail-sharing/pull/43 for more details.
=> Enable draft sharing in FilterableListMixin

cfgov/regulations3k/models/pages.py, cfgov/regulations3k/tests/test_pages.py
We’ve been seeing attempts to access regulation versions with the format YEAR-DAY-MONTH. This isn’t a valid date string, and raises a `ValidationError`, which we don’t catch, so the user sees a 500. This change catches that `ValidationError` and raises a 404.
=> Catch errors from badly formatted date strings in regulation versions

requirements/libraries.txt
A new release of MarkupSafe is incompatible with how Jinja 2.11 uses it, however Jinja doesn't include an upper bound on its pin and pulls it in anyway. This change pins the last working version until we can either upgrade Jinja to > 3, or there's an upstream patch release.
=> Pin Jinja 2.11's MarkupSafe dependency

cfgov/apache/conf.d/uploads.conf
Fixes the bug @chosak found in https://github.local/CFGOV/platform/issues/4338
File uploading should still work as expected locally, in dev servers, and in staging.
=> Make apache /f/ rewriting more accurate

cfgov/cfgov/settings/base.py
Updates wagtail backends to new database search backend
- default and fulltext wagtail search backends updated to not rely on deprecated search backends
1. Ensure that queries from wagtail backends still run successfully
=> Fix nightly housing counselor job

cfgov/ask_cfpb/models/answer_page.py, cfgov/ask_cfpb/models/pages.py, cfgov/data_research/models.py, cfgov/form_explainer/models.py, cfgov/hmda/models/pages.py, cfgov/paying_for_college/models/pages.py, cfgov/regulations3k/models/pages.py, cfgov/teachers_digital_platform/models/activity_index_page.py, cfgov/teachers_digital_platform/models/pages.py, cfgov/v1/models/__init__.py, cfgov/v1/models/base.py, cfgov/v1/models/blog_page.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/browse_page.py, cfgov/v1/models/campaign_page.py, cfgov/v1/models/enforcement_action_page.py, cfgov/v1/models/home_page.py, cfgov/v1/models/landing_page.py, cfgov/v1/models/learn_page.py, cfgov/v1/models/newsroom_page.py, cfgov/v1/models/story_page.py, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/models/sublanding_page.py
This commit deprecates the custom `v1.models.base.CFGOVPageManager` class, which was set as the default manager on CFGOVPages. This class was introduced back when CFGOVPage QuerySets needed [custom behavior around the sharing of drafts](https://github.com/cfpb/consumerfinance.gov/commit/968e4e76641138040870c0df5e345450c05d22bd), but this functionality was removed long ago. Currently the CFGOVPageManager is exactly the same as the base Wagtail PageManager, so it can be removed.
Additionally, this commit removes the now-unnecessary definition of page managers on almost all of our page models. In the past, due to some behavior in Django < 1.10, page models [had to explicitly specify their manager class](https://docs.wagtail.org/en/latest/releases/1.6.1.html#multi-level-inheritance-and-custom- …
=> Deprecate unnecessary custom page managers

cfgov/cfgov/settings/base.py
This change restores the removal of “environment is not” “production” flag conditions for the home page, from 8a25df0.
=> Restore home page flag changes from #6933

gulp/tasks/copy.js
Background: https://github.com/cfpb/consumerfinance.gov/pull/4119
The relative reference problem has since been removed from the design-system, so this hack is no longer needed.
Testing:
- collectstatic should run without erroring
=> Trim copy task hack, put in place to solve former relative reference

cfgov/jinja2/v1/_includes/molecules/global-header-cta.html
The `/complaint/` page has a link at the top to itself. This causes some users to click through, expecting to see a different page, and becoming confused.
This PR adds a conditional in jinja to suppress the Complaint link at the top of the page **only** when viewing the `/complaint/` url.
- Add conditional to `global-header-cta.html`
1. Pull it down and get it running.
2. Make sure the Complaint link at the top of the page doesn't appear on `/complaint/` but does appear on other pages.
=> File a Complaint: Remove "File a Complaint" link from /complaint

.github/workflows/backend.yml, .github/workflows/docs.yml, .github/workflows/frontend.yml
Swaps out Python 3.6 -> 3.8 in all GitHub Action workflows.
=> Use Python 3.8 in GitHub Actions

requirements/libraries.txt
Updates the CRC to contain https://github.com/cfpb/curriculum-review-tool/pull/426, which should eliminate some false-positive Checkmarx flaggings.
---
Several string constants used in the UI are turned into React components to allow the same inline markup, but without the dangerouslySetInnerHTML prop. The resulting markup in the app should be identical.
=> Bump curriculum-review-tool version to 2.1.7

cfgov/jobmanager/jinja2/jobmanager/job_listing_page.html
#6989 added the ability to specify an hourly salary for job postings. JobListingPages include JSON schema which also needs to be updated appropriately:
https://developers.google.com/search/docs/advanced/structured-data/job-posting
This change modifies the JSON schema to indicate that a posting has an hourly wage instead of an annual one.
Schema for annual salary:
Schema for hourly salary:
=> Properly set job listing schema for hourly salary

requirements/ci.txt, requirements/test.txt
This commit bumps the version of the Python `coverage` package from 4.5.1 to 6.3.2. See the `coverage` changelog [here](https://coverage.readthedocs.io/en/6.3.2/changes.html).
In my experience the newer version gives much more accurate coverage reporting. See for an example a recent PR coverage check like [this](https://github.com/cfpb/consumerfinance.gov/runs/5979266809?check_suite_focus=true).
This fails coverage reporting these lines:
```
cfgov/v1/tests/test_documents.py (78.6%): Missing lines 325,328,338-340,346
```
but an inspection of those lines shows that some of them are comments and some can't possibly be getting skipped:
https://github.com/cfpb/consumerfinance.gov/blob/aa3557fe249a4368e575e95ca18393903f072f36/cfgov/v1/tests/test_documents.py#L325-L346
The 6.x version of …
=> Bump coverage version to 6.3.2

esbuild/copy.js, esbuild/utils.js
In some Unix environments, the current way files were resolved was not correct.
This updated logic will work in all cases.
=> Resolve 'getFiles' to absolute paths and adjust string replacement logic

cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html
Fix for pfc disclosures not working correctly in staging. Not sure why this wasn't broken before.
- Changed string formatting
1. Ensure all tests still pass
=> fix improperly formatted string in pfc disclosures

package.json, scripts/preinstall.js
- Add build scripts JS to linting
1. `yarn lint` should show no errors and should include build script JS in warnings.
=> Add build scripts JS to linting

cfgov/ask_cfpb/tests/test_search.py, cfgov/search/models.py
Now that there's no longer an Ask search field on the submit a complaint page, we can loosen the character limit on searches a little. See GHE/CFGOV/platform/issues/4399 for more details.
---
- Raise the character limit of Ask searches from 50 to 75 chracters
- Update the unit test for the new higher limit
1. Visit a page with the Ask search on it, like `/ask-cfpb/`
2. Inspect the source on the search field. It should have a `maxlength="75"` set.
3. Try typing in a long search. When you hit 75 characters, you should get an error message that says "Searches are limited to 75 characters."
- Note that the unit tests in `test_search.py` that use `mock_search.called_with()` aren't working as intended right now—they'll always pass regardless of the input. We're fixing that separately; see …
=> Raise Ask search limit to 75 characters

esbuild/copy.js
If returning absolute paths, the current regex attempting to target hidden files won't work. This fixes that.
Also causes makes the regex case-insensitive, which it should be.
=> Better regex for targeting hidden files (to ignore)

cfgov/prepaid_agreements/scripts/import_prepaid_agreements_data.py
Missed one AGMNT- prefix replacement in the previous fix for this script.
- Added an additional replace command from "AGMNT-" to ""
1. Ensure cf.gov-prepaid-agreements-data-load-and-write-csv Jenkins job passes
=> Add final prefix replacement

cfgov/unprocessed/js/modules/util/behavior.js
- Use unused `error` argument in error message.
1. The mega menu should show up in legacy browsers (e.g. Chrome 65).
=> Use unused error argument in error message

cfgov/alerts/newrelic_alerts.py, cfgov/alerts/tests/test_newrelic_alerts.py
Check out one of our New Relic alerts in GHE and see that the violation ID shown doesn't show up in the incidents ID column, so it can be annoying to find the incident referenced in a particular alert. This PR changes the violation ID to the incident ID and does some minor formatting fixes.
- Changes the New Relic alert violation ID to the incident ID.
-  Minor formatting fixes to add a leading space before the visit link and to capital ID.
1. Not sure how to test. Probably just merge and wait till the next alert?
=> Update newrelic_alerts.py to point to incident ID instead of violation ID

docker/deployable-zipfile/_build.sh
In #7025 added our private font files to this repository, I missed this part of the build script that would add extra arguments for our webfonts path.
=> Remove extra arguments for custom font files

docker/deployable-zipfile/_build.sh
This change partially reverts #7039, which removed the `static.in` directory from our build entirely. This restores it but ensures that it is always included in our `build_args`.
=> Move webfonts path to build_args

cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js
- Changed the positioning of the projected value label when there is a projected value present in the chart
1. Pull PR
2. `yarn build`
3. Go to http://localhost:8000/admin/pages/4481/edit/
4. Add Simple-Chart block, add projected months value
5. Preview and see new label positioning
With projected months:
With projected months:
Without projected months:
=> Simple-chart label positioning

cfgov/v1/atomic_elements/organisms.py
https://github.com/cfpb/consumerfinance.gov/pull/7030 added some simple-chart admin css, but did so in two ways, [the first way](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/wagtail_hooks.py#L133) works fine, and the second way (removed in this PR) is both broken and unnecessary. Thus, I'm removing it!
=> remove broken admin simple-chart-css reference

cfgov/paying_for_college/disclosures/scripts/update_ipeds.py, cfgov/paying_for_college/tests/test_scripts.py
Replaces the `subprocess.call` on `rm` with `os.remove`.
=> Remove exec rm call

cfgov/ask_cfpb/tests/models/test_pages.py
#7060 introduced Bandit and made some changes to satisfy its checks. One of those changes was to use `tempfile.gettempdir()` rather than a hard-coded `/tmp` in Ask CFPB exports.
This had the effect of breaking our unittests when the `TMPDIR` envvar isn’t set to `/tmp` itself, because we hard-coded that path in the unit tests, as [@chosak noted](https://github.com/cfpb/consumerfinance.gov/pull/7060#issuecomment-1130320885).
This change fixes that by reusing the value of `tempfile.gettempdir()` for that test.
=> Fix temp directory path in unittests

cfgov/apache/conf.d/redirects.conf
The path set in the previous PR https://github.com/cfpb/consumerfinance.gov/pull/7077 is incorrect -- the path should be /rules-policy/innovation/, rather than just /innovation/. This PR corrects the previous.
---
- Modified line in redirects.conf
1. localhost
2. Navigate to /rules-policy/innovation
3. Confirm that you are properly redirected to /rules-policy/competition-innovation
- CFGOV/platform wiki …
=> Fix new redirect path

cfgov/jinja2/v1/_layouts/base.html, cfgov/v1/tests/models/test_base.py
This is a bug!
@brandon-rusk can test via his cct/simple-chart setup
=> Broken jinja made only a single media_css file get included on a page

cfgov/scripts/http_smoke_test.py
#7077 added a redirect for /rules-policy/innovation/ to /rules-policy/competition-innovation/. This quick change fixes the smoke test for /rules-policy/innovation/.
=> Fix smoke tests after #7077

cfgov/unprocessed/css/on-demand/simple-chart.less, cfgov/unprocessed/js/routes/on-demand/simple-chart/common-styles.js
Highcharts includes a [CSS rule](https://github.com/highcharts/highcharts/blob/9d0110b6ae677708989e3a908ebaef56c43834ac/css/highcharts.scss#L441-L445) that sets the color of hidden legend
elements using an !important attribute. This prevents our hover color
from showing when a legend  item is hidden. We can unset it in our
stylesheet.
| hover state | non-hover state |
| <img width="723" alt="image" src="https://user-images.githubusercontent.com/1060248/171266766-7e0fc95b-a43b-4c51-abed-c194aee6f9cd.png"> | <img width="723" alt="image" src="https://user-images.githubusercontent.com/1060248/171266890-e48ec2f9-6ec7-4951-a853-71bdee6ec31b.png"> |
- This causes hidden legend items to appear colored when not hovered because the `#ccc` color is now `unset`. It should be set to …
=> Override highcharts hidden legend hover color

cfgov/unprocessed/js/routes/on-demand/simple-chart/common-styles.js
-Added y-xis label formatter to ensure charts properly display number types
Before:
After:
=> Add formatter to y-xis to properly display number types

cfgov/jinja2/v1/_includes/molecules/global-search.html
This changes removes the `utf8=✓` parameter from our search base URL. This will remove that parameter from our no-JS fallback link used by IE that links directly to the search.gov search page for CFPB. Its removal shouldn't impact JS-enabled search as there is a hidden input that adds the parameter on lines [55-57](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/jinja2/v1/_includes/molecules/global-search.html#L56-L58). 
In IE, with this parameter, we're seeing 400 Bad Request errors on following the link that appear down to the UTF-8 `✓` character. This is an attempt to solve that issue.
=> Remove utf8 param from search base URL

requirements/libraries.txt
Updates the CRT to contain https://github.com/cfpb/curriculum-review-tool/pull/430, to limit title to 150 characters.
- Validate title and pub_date string len directly instead of the combined JSON input size.
- Refactors views to use return-early for easier reading.
- Eliminates pass_code input handling as this is no longer used.
=> Bump curriculum-review-tool version to 2.1.8

cfgov/unprocessed/apps/filing-instruction-guide/js/fig-sidenav.js, cfgov/unprocessed/css/on-demand/reports-sidenav.less
As a follow-on to https://github.com/cfpb/consumerfinance.gov/pull/7087, this addresses the underlying clipping issue in a simpler way. Namely, instead of using `position: fixed` and adding a class with js + setting the width as a percentage of the body (which `position: fixed` forces you to do), this uses `position: sticky` (relatively new but supported in all browsers we serve js), which just requires the parent element to have a `height` set. Doing this also allowed me to remove the `scrunch` logic.
Also included in this PR:
- reenable eslint on the js file and add docstrings
- fixed a bug where sub-headers weren't properly being shown/hidden if a level-3 header was present
- updated the `headerOffset` and keyed it off the `main` tag's `offsetTop` so it will always be correct.
Testing: …
=> Handle fig sidenav sizing in css and clean up/document js

cfgov/jinja2/v1/_includes/organisms/expandable.html
The template for the Expandable module mentions a "paragraph" variable, but this is unused.
Any paragraph in an expandable is now part of its regular content:
https://github.com/cfpb/consumerfinance.gov/blob/ec8a43459910ef3bca6d53ed10b7b3b41d2fb7d5/cfgov/v1/atomic_elements/organisms.py#L634
This help text was left behind in [this commit](
https://github.com/cfpb/consumerfinance.gov/commit/9de95a6798923e3253c550bd1c4ab5d88ff0e709) from 2016, but can be removed.
=> Remove outdated docs from Expandable template

.github/workflows/functional-tests.yml
This PR is a quick fix for failures we've just started seeing with the Cypress tests in GHA.
First it updates the Cypress action to the latest version.
Second, it adds the `DJANGO_ADMIN_USERNAME` and `DJANGO_ADMIN_PASSWORD` variables to the action so that they are defined our [our `initial_data` script](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/scripts/initial_data.py#L22-L23). I'm unsure at this point why this was working previously, and why it stopped working. But this should get our functional tests back to passing in GitHub.
=> Update Cypress action and add admin username/password

cfgov/unprocessed/js/routes/on-demand/simple-chart/datetime-styles.js
This allows them to start on the first instance of data, meaning data will extend all the way to the left of the chart.
Testing:
- Data should extend the full width of the chart on load.
- Play with the rangeSelector buttons, data should continue to fill the chart (even/especially on 'All')
- Data display and interaction is still correct
=> Removes 'startOnTick' for datetime simple charts

cfgov/jobmanager/models/pages.py, cfgov/jobmanager/tests/models/test_pages.py
This change fixes some weirdness in our [“Current openings” table](http://localhost:8000/about-us/careers/current-openings/) that lists CFPB’s current job openings. Those job openings are typically set to unpublish at midnight on their closing date (so, a job listing that closes on June 28 will unpublish at 00:00 June 29). This happens in our configured `TIME_ZONE`, which is `America/New_York`.
The `JobListingPageQuerySet` has an `open()` method that returns listing pages that are “open” for applications. This method uses [Django’s `timezone.now().date`](https://docs.djangoproject.com/en/3.2/ref/utils/#django.utils.timezone.now) to determine whether the job is open or closed. `timezone.now()`, per the Django docs, returns a datetime object in UTC.
This means the “Current openings” table …
=> Fix the current job openings table timezone handling

cfgov/regulations3k/models/pages.py, cfgov/v1/models/base.py, cfgov/v1/tests/management/commands/test_archive_events.py
The `CFGOVPage.parent()` method duplicates functionality already available via the base treebeard [`Node.get_parent()`](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.get_parent) method.
This commit also removes an unnecessary `app_label` on v1.CFGOVPage.
Unit tests continue to pass.
For the iRegs change, run a local server and visit a page like [this](http://localhost:8000/rules-policy/regulations/search-regulations/results/?regs=1002&q=housing) to confirm that search results URLs are constructed properly.
=> Deprecate duplicate CFGOVPage.parent() method

cfgov/jinja2/v1/_includes/organisms/post-preview-snapshot.html
#7128 tried removing a custom `parent()` method in favor of using Wagtail's built-in `get_parent()`, but missed this one reference.
Thanks to @willbarton (and our acceptance tests!) for the catch.
To test, run a local server and visit:
http://localhost:8000/compliance/amicus/
=> Fix broken get_parent() in post preview template

cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/utils.js
- Change `getProjectedDate` to `convertEpochToDateString` to better describe what it does, and only return one string value, not an object.
1. SimpleChart functionality should be unchanged.
=> SimpleChart: Change `getProjectedDate` to `convertEpochToDateString` to better target its intention

cfgov/unprocessed/apps/filing-instruction-guide/css/main.less
Commit that I failed to push up to https://github.com/cfpb/consumerfinance.gov/pull/7146.
=> Maintain the visual hierarchy of FIG info unit headings

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/section.html, cfgov/filing_instruction_guide/models.py, cfgov/jinja2/v1/_includes/organisms/sidenav-toc.html
Previously, a section ID for a part of a FIG document would be something like `3.1.2.` (including the trailing dot). Now, the section ID for the same section would be `3.1.2` (without a trailing dot).
With this PR, an anchor link to an individual section of the FIG won't include a trailing dot (which was weird), but the body of the page will still have the dot in headers and the table of contents. Now, the dot is added by the Jinja template.
1. Make a FIG Content page
2. Add a few sections at different levels
3. View or preview the page
4. See that the section headers (in both the table of contents and the main body of the page) still have a dot after the section ID
5. Click a TOC link or section header, see that the anchor ID in the URL does not have a dot at the end
- PR titles are used …
=> FIG: Don't include a trailing dot in section IDs

cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/unprocessed/apps/find-a-housing-counselor/css/hud.less, cfgov/unprocessed/apps/find-a-housing-counselor/js/common.js
Currently, we load the mapbox map on the find-a-housing-counselor page before a search has been performed. This is unnecessary and possibly distracting, as the only reason to show the map is to display the results of a search for housing counselors.
This change makes keeps the map element out of the page unless there is a valid zipcode and adds a check for this element in the JS before attempting to initialize the map.
There's also a small CSS tweak to keep everything consistent across JS/no-js views
Update: also clamps the input to 30em (480px).
default page:
valid zip:
invalid zip:
- visit [fahc page](http://localhost:8000/find-a-housing-counselor/) and note appearance. Check requests to mapbox don't exist (other than pulling in the api js/css).
- Make a search, note …
=> Only show fahc map if a valid zipcode has been entered

cfgov/unprocessed/css/main.less
This syncs font appearance between MacOS and mobile/windows/linux.
- Open localhost:8000 in one tab and https://www.consumerfinance.gov/ in another
- Note the sharper lines in localhost
- From an internal phone or citrix session, compare dev5 (where this branch is deployed) to https://www.consumerfinance.gov/. They should appear identical. This shows that this change is bringing webkit browsers on MacOS in line with how everyone else already experiences the site.
=> Set font-smoothing to anti-aliased

test/cypress/integration/components/email-signup/email-signup.js
This small change adds a `wait` to our email signup tests between the signup submission and checking for the success notification. Previously, we were seeing occasional failures to find the success notification, and observing the results in Cypress, it seems to be because Cypress gets to the success check before the success notification has rendered.
This wait seems to fix it against staging, which is the only place I was able to reproduce the issue with any regularity.
=> Add a `wait` to email signup functional test

helm/README.md
Added documentation around manually loading data into Postgres and ElasticSearch in Kubernetes for Local Development.
=> Add 'manually adding data' section

cfgov/agreements/jinja2/agreements/index.html
Link to the .zip download for the latest quarter of credit card agreements, Q4-2021. 
Note: this change is staged on our development server #4.
- One new entry in the CCA archive page.
- This is scheduled to go live today or tomorrow. When this change is deployed, I'll also run the automation that expands the individual agreement PDFs into their storage locations.
- CFGOV/platform wiki on GHE – for …
=> Credit card agreements: Add Q1-2022 link

docker/deployable-zipfile/Dockerfile
It looks like there’s an upstream issue with `nodejs-16.13.1-1nodesource.x86_64.rpm` at NodeSource. Installing this RPM directly results in a “Package does not match intended download” error from rpm.
It’s [not just us having the issue](https://github.com/nodesource/distributions/issues/1432), and from the directory listing, that file was updated yesterday.
Removing the direct install, which was added in #6747 mitigates the issue, and I don’t see a return of that error message without it that #6747 intended to fix.
`docker/deployable-zipfile/build.sh` should successfully build the deployable zip file.
=> Remove direct RPM install from NodeSource

test/cypress/integration/compliance/small-business-lending/filing-instruction-guide.cy.js
Added a beforeEach hook to the FIG cypress test file which tests the page response. If the status is not 2xx or 3xx, the beforeEach hook will fail, causing the remaining tests to be skipped, but the first test will show a failure.
- Added beforeEach hook in filing-instruction-guide.cy.js
=> added beforeEach hook to FIG tests to test page response

cfgov/unprocessed/css/molecules/multiselect.less
Closes https://github.local/CFGOV/platform/issues/4366
Testing:
- pull and build
- go to localhost:8000/about-us/blog/
- select five items in one of the limited fields
- note no bullet in message (in SS below)
=> Don't add bullet to 'reached maximum of five selections' note

.github/workflows/publish_cfgov.yml, helm-install.sh, helm/cfgov/templates/NOTES.txt
Adds GitSHA tagging to Docker tags pushed to GHCR.
Canonical tags are still in place (`pr-#`, `latest`, `release`).
=> Add GitSHA image tagging

.eslintrc
JSX looks like HTML and we double-quote attributes in HTML, so it seems like we should double-quote them in JSX as well.
- Prefer double quotes in JSX
1. `yarn lint` should show no errors.
=> ESLint: Prefer double quotes in JSX

helm/cfgov/templates/_helpers.tpl, helm/cfgov/templates/postgres-secret.yaml, helm/cfgov/values.yaml, refresh-data.sh
Some interesting finds with this one. When I am using a database where `PGUSER` does not match the dump files schema (the username from the dump), things don't work out so well. After the dump file is ingested, migrations apply to `public` schema, and not the dump username schema. After doing some research, Django doesn't have a great way to support having a different schema. There is an `OPTIONS` key that you can set, but found it to be more problematic with how we are ingesting the dump file that has the schema name hard coded. 
Instead, I have modified `refresh-data.sh` to do a quick lightweight check to get the schema name from the dump file, and check to see if it matches `PGUSER`. If not, it will delete `PGUSER` schema (since this is a dump ingestion, this is what happens with the …
=> External DB support, support for any db username with db dumps

helm/cfgov/templates/cronjob.yaml
This truncates the generated CronJob name to 52 characters to adhere to the naming limitation for CronJobs. Also removes the redundant "cronjob" part of the name.
> When creating the manifest for a CronJob resource, make sure the name you provide is a valid [DNS subdomain name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names#dns-subdomain-names). The name must be no longer than 52 characters. This is because the CronJob controller will automatically append 11 characters to the job name provided and there is a constraint that the maximum length of a Job name is no more than 63 characters.
=> Fix CronJob name when longer than 52 char

helm/README.md, helm/cfgov/templates/cronjob.yaml, helm/cfgov/values.yaml
This adds the `successfulJobsHistoryLimit` and `failedJobsHistoryLimit` options to the `cronjob.yaml` template.
Also sets the default value for both of these, to `1`. This helps to keep from having 3 successful pods for each cronjob sitting there.
=> CronJob History Limits

helm/README.md, helm/cfgov/templates/cronjob.yaml, helm/cfgov/values.yaml, helm/overrides/local-dev.yaml
We used to use an array to define CronJobs. This had limitations, especially in regards to override files. This PR swaps out the array, for mappings.
Array
```YAML
cronJobs:
- name: job-a
command: blah
- name: job-b
command: blah-b
```
Mapping
```YAML
cronJobs:
job-a:
command: blah
job-b:
command: blah-b
```
To override `job-a` before, you would have to redefine all CronJobs within the override file, or use `--set`, and select the job based on integer index. This is unreliable and can lead to problems, as well as being a pain to use. Now, to override `job-a`, you can just override the specific values of `cronJobs.job-a`, and no longer will you have to redefine the entire CronJobs list. 
In this example, we want to override `job-a` command.
Old override (using example from above), having …
=> Switch to mapping for CronJobs

helm/README.md
Adds the following to `helm/README.md`
We like to use OpenLens to manage the Kubernetes stack.
There is a more commonly known Lens app, but Lens requires an account to use.
Lens is the commercialized version built on top of the OpenLens source.
To install OpenLens, create an alias in your shell profile. For example,
if using `zsh`, add it to `.zshrc`. This alias is used to install and to
update OpenLens.
alias install_openlens="curl -o- https://gist.githubusercontent.com/jslay88/bf654c23eaaaed443bb8e8b41d02b2a9/raw/install_openlens.sh | bash"
Source your shell profile or restart your terminal. Then run the alias.
install_openlens
=> Add OpenLens Info to Documentation

docker-entrypoint.sh
Fixes an issue where `.env` doesn't get sourced on application start. We used to only force sourcing `.env` with `docker-entrypoint.sh` in Kubrenetes, but there is no reason we can't just always do it.
=> Always source .env

test/cypress/integration/components/filterable-lists/filter-blog-posts.cy.js
This change removes a check for the `title` parameter in the URL after the `title` field is checked in the filterable list controls. The `title` parameter check was failing occasionally due to URL-encoding of the title. The title parameter check seems redundant given that we’re checking the title field of the control after applying the filters.
=> Remove redundant title check in filter-blog-posts functional test

cfgov/search/wagtail_hooks.py, cfgov/v1/views/reports.py, cfgov/v1/wagtail_hooks.py, test/cypress/integration/admin/admin-helpers.cy.js
We've added a lot of Wagtail reports in the last year or so, but we haven't done much to keep the reports and the reports menu consistent and organized. This PR cleans up reports by doing a few things:
- Alphabetizes and title cases items in the reports menu
- Gives each report a unique icon for easier scanning
- Makes report titles more consistent
- Moves the external link search into the reports menu (the link search tool is still the same, this just moves it's menu item into the reports menu rather than hanging out at the bottom of the main menu)
---
- `construct_reports_menu` Wagtail hook to keep items in the reports menu title cased and alphabetized no matter where they come from
- `order` attribute from all of our custom reports since order is now handled automatically in …
=> Clean up Wagtail reports

test/cypress/integration/components/filterable-lists/filter-blog-posts.cy.js
This change removes some additional checks for the `title` parameter in the URL after the `title` field is checked in the filterable list controls. The `title` parameter check was failing occasionally due to URL-encoding of the title. The title parameter check seems redundant given that we’re checking the title field of the control after applying the filters.
This is a follow-up to #7234, which removed one of these checks but not all.
=> Remove additional redundant title check in filter-blog-posts functional test

test/cypress/integration/data-research/mortgage-performance-trends/mortgage-performance-trends.cy.js
This small change temporarily disables our mortgage performance tests on staging while we try to troubleshoot the strange intermittent failures we’re seeing on Jenkins.
=> Temporarily skip the mortgage performance tests on staging

.github/workflows/helm_lint.yml, ct.yaml, helm-install.sh, helm/cfgov/Chart.yaml, helm/cfgov/templates/_helpers.tpl, helm/cfgov/values.yaml, helm/overrides/required.yaml
Adds the following labels:
* `release.cfpb.gov/product` - Set to `.Chart.Name`, used for identifying what product the release is associated with.
* `release.cfpb.gov/auto-delete` - Used by the CI/CD pipeline to know what releases it should delete, based off `branch` label
* `release.cfpb.gov/auto-upgrade` - Used by the CI/CD pipeline to know what releases it should upgrade, based off `branch` label
* `release.cfpb.gov/branch` - Used by the CI/CD pipeline to know what git ref the release is associated with, to know what to upgrade when an update comes through for the specified seed. `<branch>` for a branch, `release` for release.
* `release.cfpb.gov/git-sha` - Just another place to store what Git commit SHA this is associated with for all deployed resources
* `release.cfpb.gov/owner` - …
=> Add release labels for EKS CI/CD

cfgov/unprocessed/apps/regulations3k/css/main.less, cfgov/unprocessed/apps/regulations3k/css/reg-landing-page.less, cfgov/unprocessed/apps/regulations3k/css/reg-text.less
Regulation landing pages (like [Reg F's](https://www.consumerfinance.gov/rules-policy/regulations/1006/)) are meant to have a lead paragraph that briefly introduces the regulation. Sometimes when we add a new regulation to iRegs, though, we have to temporarily put up a blank landing page while the landing page content—including the lead paragraph—is still being written ("temporarily" can sometimes be months,  however). But the landing page template wasn't designed with the no-lead-paragraph case in mind, so some elements were squished together on regs landing pages without a lead paragraph (see GHE/CFGOV/platform/issues/4162 and GHE/CFGOV/platform/issues/4138 for examples). This change makes sure that regs landing page elements are always properly spaced regardless of whether the page has …
=> Fix alignment on blank regulation landing pages

cfgov/unprocessed/css/molecules/global-search.less
Currently the "Search" button in our global search doesn't handle some translations well:
- In [Vietnamese](https://www.consumerfinance.gov/language/vi/), "search" translates into two words, "tìm kiếm," which causes the button text to wrap into two linens (see GHE/CFGOV/platform/issues/4195 for that bug report)
- In [Chinese](https://www.consumerfinance.gov/language/zh/) and [Korean](https://www.consumerfinance.gov/language/ko/), the slightly larger x-heights of characters cause the button to extend a little below the bottom of the adjoining text input
These changes fix those issues by having the global search form use a `flexbox` layout to allow the text input and button to grow a little to fit translations while still mostly maintaining the 75/25 input/button split of the [text input …
=> Allow global search button to adapt to translations

cfgov/apache/conf.d/redirects.conf, cfgov/cfgov/settings/base.py, cfgov/cfgov/urls.py, requirements/libraries.txt
The Curriculum Review Tool has been deprecated and its repo archived. Links to the tool have already been removed from the curriculum review homepage.
This PR removes our inclusion of the tool in the codebase and adds an Apache redirect for all former crtool subpages.
=> Remove crtool dependency and routing. Also institute redirect

cfgov/jinja2/v1/_layouts/base.html
Updates our qualtrics snippet to point to the new id.
Testing:
- Pull
- Navigate to an ask page or consumer tools landing page (with no ad blocker)
- scroll to the bottom of the page, click the feedback tab, note that everything works
- (you may have to clear localStorage/site data to get the tab to show up)
=> Update qualtrics snippet

cfgov/jinja2/v1/_includes/molecules/hero.html
In the course of working on getting Cypress tests running in an EKS environment, we discovered there's a possible divide-by-zero error lurking in the hero template. If a hero has an image set in Wagtail but the image file itself is missing, `img.width` and `sm_img.width` will come back as `0`, causing a 500 error and preventing the page from rendering. Up until now this has been masked by using placekitten locally to plop in a placeholder image, but EKS uses production settings *and* doesn't have any image files loaded, so any page with a hero in that environment will 500. There's also a small chance this could pop up in production if something goes wrong with the image file, so best to pop in a quick check for `img.width` to make sure we're never dividing by zero.
---
- Check that …
=> Prevent possible divide-by-zero error in hero

cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html
The EFIP tool's last page has links to federal help sites for students, and the FAFSA website has moved.
This was missed in #7282.
- One hyperlink in disclosure.html
=> Fix a reference to the FAFSA website, which has moved.

cfgov/cfgov/settings/base.py, cfgov/login/forms.py
In `cfgov/login/forms.py` the `LOGIN_FAIL_TIME_PERIOD` wasn't cast to an `int` everywhere it was used. This does the casting where the setting is defined instead (and does the same for `LOGIN_FAILS_ALLOWED`).
=> Moves login-associated type conversion to where settings are defined

cfgov/jinja2/v1/_includes/organisms/secondary-navigation-fig.html, cfgov/unprocessed/apps/filing-instruction-guide/js/fig-sidenav.js, test/cypress/integration/compliance/small-business-lending/filing-instruction-guide-helpers.cy.js, test/cypress/integration/compliance/small-business-lending/filing-instruction-guide.cy.js
Currently, the interactive FIG desktop side nav and mobile accordion nav are initialized on page load based on the user's viewport width. They are not re-initialized if the user changes the width of their browser. This PR uses [`matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) to listen for viewport resizing and enable/disable FIG features as needed.
I also instructed the FIG browser tests to not run unless a `CYPRESS_FIG_URL` environment variable is defined because the FIG URL is a moving target until we launch so it probably shouldn't be hardcoded.
- Moved the FIG mobile nav logic into its own function so it can be enabled/disabled if/when the user resizes their browser window.
- Simplified the FIG browser test file to skip the FIG tests if the user …
=> Improve handling of FIG viewport resizing

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/data_points.html
Some data points want bullet points or multiple paragraphs of explanation. The existing data points template only allows single paragraphs. Update to allow custom html in certain parts of the template that will sometimes have more complex text.
- Mark a few fields as `safe` in the jinja template.
1. Use a data points JSON file that has HTML styling in a `intro_text` or `instruction_text` field. (There's an example in the `test` branch of our private repo)
2. Import it into your test FIG as usual
3. See that it displays as rendered HTML
-  If this is too much of a risk (e.g. for XSS attacks), help me think of a better solution.
- Consider prefixing, e.g., "Mega Menu: fix …
=> FIG data points: Allow html tags in certain fields

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/section.html, cfgov/jinja2/v1/_includes/organisms/secondary-navigation-fig.html
Move FIG search bar outside loop, set default search data attribute.
The search bar container was inside a loop and being rendered multiple times (this went unnoticed because it's smart enough to only initialize once) and some FIG sections had a raw `{{ data_attr }}` in their markup because no default empty value was specified.
1. I deployed this branch to dev4, https://<dev4>.cfpb.gov/data-research/small-business-lending/filing-instruction-guide/202x-filing-instructions-guide/ should look and behave normlly.
=> Minor FIG markup improvements

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/data_points.html
This is an expansion to #7296. Now we're allowing html formatting within table cells, and improving formatting for instruction text.
- Minor spacing improvement with a `<p>` tag
- Use `safe` to allow html in table cells
- Better compartmentalization of code
1. Use a data points JSON file that has HTML styling in a valid_values field. (There's an example in the test branch of our private repo)
2. Import it into your test FIG as usual
3. See that it displays as rendered HTML
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` …
=> FIG: Allow HTML in table cells 

cfgov/unprocessed/apps/retirement/js/utils/handle-string-input.js, cfgov/unprocessed/apps/retirement/js/utils/num-to-money.js, cfgov/unprocessed/apps/retirement/js/views/graph-view.js, cfgov/unprocessed/apps/retirement/js/views/tooltips-view.js
- Remove or comment out unused variables.
- Remove extraneous escaped regex characters.
- Move scope of variable that was out of scope.
1. `yarn build` and visit /consumer-tools/retirement/before-you-claim/ and make sure the app still works.
=> Fix retirement linter errors

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/data_points.html
Certain data fields want a more specific rule citation than their parent data point. This PR allows them to show on the page, if they're included in the JSON as a `citation` property of a `data_field` object.
- "Rule section: {{ citation }}" where present in the JSON
- CFPB/hubcap wiki on GHE – for internal CFPB design and content …
=> FIG data points: Add optional field "citation"

Dockerfile
This change splits up the `cfgov-frontend-builder` image in our `Dockerfile` so that we use a dedicated `node:18-alpine` image for the steps that require Node.js instead of installing the `nodejs` package into the `python:3.8-alpine` image. This should let specify separately the version of Node that’s used in the build.
This uses the `node:18-alpine` image specifically, and this PR targets @anselmbradford's PR #7326 branch upgrading to Node 18.
=> Use a dedicated Node image for the frontend build

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/data_points.html
Field type and Conditionality are now the top bullet points under the "Instructions" header, since they need to be easy to find.
- Minor change to the data points template in the FIG page
[See internal GH ticket 269]
=> FIG: Improve layout of information about data points

cfgov/unprocessed/apps/regulations3k/js/permalinks-utils.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/common.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/dom-tools.js, cfgov/unprocessed/js/modules/youtube-api.js, cfgov/unprocessed/js/organisms/EmailPopup.js, test/unit_tests/js/modules/Analytics-spec.js, test/unit_tests/js/modules/util/behavior-spec.js
Last follow up to https://github.com/cfpb/consumerfinance.gov/pull/7328 to correct warnings.
- Set correct param types.
- Fill in TODOs and empty comments.
- I've left much of the TDP and buying a car linting warnings, custom return type warnings, and absent return types (which would require more checks to get right).
=> Fix a few straggling jsdoc lint warnings

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/data_points.html, cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/section.html, cfgov/unprocessed/apps/filing-instruction-guide/css/main.less
The spacing on the FIG page is wonky. The main culprit is that we unnecessarily wrap every section in a `block` class. This PR removes that class (and another unnecessary `report-header` class) and fixes the spacing.
I also linted our CSS file to be in line with our new syntax standards which is why that file is showing a lot of changes.
1. `yarn styles`
1. Nothing should substantially be different on your local FIG page except the spacing will be a little smaller between sections.
- [This repo’s …
=> Remove unnecessary block class from FIG content

.vscode/settings.json, docs/installation.md
PR #7325 configured the VSCode settings for this repository so that Prettier is the default code formatter. This doesn't work for Python files. This commit changes the VSCode settings to set the Python extension as the default formatter; this lets VSCode users use black to format Python files.
This commit also adds documentation about these VSCode extensions.
=> Configure default Python formatter for VSCode
