cfpb/consumerfinance.gov

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/data_points.html
A usability improvement, driven by user tests. Users did not recognize the "short name" label.
=> FIG: Rename "column name" header

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/data_points.html, cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/section.html, cfgov/unprocessed/apps/filing-instruction-guide/js/fig-sidenav-utils.js, cfgov/unprocessed/apps/filing-instruction-guide/js/fig-sidenav.js, test/cypress/integration/compliance/small-business-lending/filing-instruction-guide.cy.js
The table of contents in the sidenav highlights the section that the
user is currently viewing. It was doing so by tracking the position of
each section heading in the main content. Now that some sections are
looooooooong, headings can be few and far between, causing the nav
to not get highlighted until a heading is reached.
The section container divs are now being tracked instead of just the
headings to make the scrollspy more accurate.
Fixes https://github.local/CFPB/1071-data-collection/issues/291
- Adds the `data-scrollspy` attribute to FIG section containers instead of their headings.
- Unrelated, it makes the FIG tables responsive (see https://github.local/CFPB/1071-data-collection/issues/317)
(This branch has been deployed to dev4.)
1. Functional tests …
=> Improve 1071 FIG TOC scrollspy accuracy

cfgov/unprocessed/apps/regulations3k/js/search-utils.js, cfgov/unprocessed/apps/teachers-digital-platform/js/search-utils.js, test/unit_tests/apps/regulations3k/js/search-utils-spec.js, test/unit_tests/apps/teachers-digital-platform/js/search-utils-spec.js
I could only find a reference to `clearCheckbox` in the tests.
- Remove unused `clearCheckbox` method
=> Regs3k/TDP: Remove unused `clearCheckbox` method

cfgov/jinja2/v1/_includes/organisms/item-introduction.html
Item introduction categories originally linked back to a filtered version of their parent filter, when the item introduction configuration option "Show category" is checked.
This was broken by [this commit](https://github.com/cfpb/consumerfinance.gov/commit/705d8f0f9cad6f4aa807bd2f9147d4649fcc96aa) back in 2018 (by yours truly).
We use "Show category" sparingly on item introductions. An example production page with this option checked is [this one](
https://www.consumerfinance.gov/foia-requests/foia-electronic-reading-room/2017-student-banking-report-correspondence/).
Note that currently the category renders as a plain text "Record" that doesn't link anywhere. With this commit, the category renders as a bold link that links back to the parent filterable list.
|Before|After|
|-|-|
|<img …
=> Fix: Item introduction categories don't link

README.md, TEST.md, docs/running-docs.md, mkdocs.yml
We renamed `testing.md` five years ago in https://github.com/cfpb/consumerfinance.gov/pull/3602, so the contents of `TEST.md` have been 404s. This PR removes that markdown file and moves the readme contents regarding running documentation locally to within the documentation site itself.
- Remove unused and broken `TEST.md` file.
- Moves instructions for running the doc site locally to within the doc site itself.
- Removes redundant reference to docs site in the main readme file.
- Adds note on changing mkdoc port number, if you already have cfgov running at the same time.
- Formatting autofix for the docs TOC that indents markdown bullet lists one level.
1. Run `mkdocs serve -a localhost:8001` and visit http://localhost:8001/ and see that there's a new `Running documentation site locally` …
=> Remove broken TEST.md file and update docs structure

.prettierignore
Prettier was messing with our jinja. This sets it to ignore HTML.
- Set Prettier to ignore HTML.
1. Editing a jinja template should not cause it to be autoformatted on save.
=> Set Prettier to ignore HTML

.prettierignore, cfgov/unprocessed/apps/filing-instruction-guide/css/main.less, cfgov/unprocessed/apps/owning-a-home/config.json, cfgov/unprocessed/root/site.webmanifest, docker-compose.override.yml, docker-compose.prod.yml, docker-compose.yml, docker-stack.yml, test/unit_tests/js/organisms/MortgagePerformanceTrends/utils-spec.js
- Exclude fixtures and app data JSON files from Prettier. Also exclude Helm config files. 
2. Check PR with whitespace changes off.
- Do any of the changes to config files that wrong to you? We can exclude them too! Let me know.
- Both `cfgov/unprocessed/root/code.json` and `cfgov/unprocessed/root/data.json` will be hit by the linter, but I did not adjust them here or ignore them. They will be formatted in future runs of the linter. Does that matter?
=> Adjust Prettier linting exclusions and lint some things

cfgov/unprocessed/apps/regulations3k/js/index.js, cfgov/unprocessed/apps/regulations3k/js/recent-notices.js, cfgov/unprocessed/apps/regulations3k/js/regs3k-utils.js, cfgov/unprocessed/apps/regulations3k/js/search.js, test/unit_tests/apps/regulations3k/js/recent-notices-spec.js, test/unit_tests/apps/regulations3k/js/regs3k-utils-spec.js, test/unit_tests/apps/regulations3k/js/search-spec.js
- Regs3k: Use native fetch in place of xhr wrapper.
1. `yarn build` and the sidebar on http://localhost:8000/rules-policy/regulations/ should work. 
2. Regs search at http://localhost:8000/rules-policy/regulations/search-regulations/results/ should work.
3. PR checks should pass.
=> Regs3k: Use native fetch

cfgov/v1/tests/util/test_ref.py
This commit adds a new Python test that fails if there are duplicate page category slugs in the hardcoded list in ref.py.
This test will fail until #7366 is merged, which resolves some existing duplicate categories, so this PR should not be merged in until that one is.
=> Enforce unique page category slugs

cfgov/v1/jinja2/v1/home_page/_hardcoded_en.html, cfgov/v1/jinja2/v1/home_page/home_page.html
Following #7408, this hardcodes the new structure into the homepage and removes a couple unnecessary uses of `| safe`, which we should avoid when possible.
=> Remove use of safe in homepage template

cfgov/v1/jinja2/v1/includes/organisms/post-preview.html, test/cypress/integration/components/filterable-lists/filter-blog-posts.cy.js
Our filterable list tests for language selection are currently failing because they're looking for specific text from specific blog posts in Spanish and in Tagalog. The Tagalog post in question has disappeared behind the blog's pagination, and so the test can't find the text it's looking for (there is a second Tagalog post in the combined results, as of this writing). 
This PR makes two changes intended to fix our failing filterable list language selection tests:
1. Adds a `lang` attribute to post previews. 
Because we currently include posts in multiple languages, include a lang attribute with the post-preview to allow us to select based on the language of the post.
2. Changes content-dependent filterable language tests to use that attribute in selection.
Our language tests now use that …
=> Fix filterable language tests

cfgov/v1/jinja2/v1/sublanding-page/index.html
This PR removes an unused template import.
=> Remove unused template import

requirements/libraries.txt
This commit bumps the version of the Jinja2 templating library from 2.11.3 to 3.0.3. Version 3.1.x of Jinja2 is not supported until Wagtail 3.x (we are still on 2.15.x).
This allows for removal of a pinned MarkupSafe dependency.
See Jinja2 changelog here:
https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-0-3
To check whether this version upgrade introduces any template changes, I rendered every Wagtail page using [wagtail-bakery](https://github.com/wagtail/wagtail-bakery) on `main` and then with this change. Diffing the two batches of HTML showed no differences.
=> Bump Jinja2 version from 2.11.3 to 3.0.3

cfgov/ask_cfpb/models/answer_page.py, cfgov/ask_cfpb/models/snippets.py, cfgov/form_explainer/models.py, cfgov/teachers_digital_platform/models/pages.py, cfgov/v1/models/base.py, cfgov/v1/models/blog_page.py, cfgov/v1/models/browse_filterable_page.py, cfgov/v1/models/browse_page.py, cfgov/v1/models/enforcement_action_page.py, cfgov/v1/models/landing_page.py, cfgov/v1/models/learn_page.py, cfgov/v1/models/snippets.py, cfgov/v1/models/sublanding_filterable_page.py, cfgov/v1/models/sublanding_page.py
This commit cleans up some unused Wagtail search configuration that is no longer necessary after 2c793d2305e33230d1af24dab5f3ef33cbb82dba.
Defining `search_fields` on models are only necessary if we want them to be searched using Wagtail search, but we no longer use Wagtail search to search pages.
All tests continue to work.
I've left behind the one supported place where we actually rely on Wagtail search, which is our [`IndexedPageRevision`](https://github.com/cfpb/consumerfinance.gov/blob/54dddc061b5f843a575a6887bb412a4033de8365/cfgov/v1/models/indexed_page_revision.py#L5) class.
=> Deprecate unused Wagtail search fields

test/cypress/integration/consumer-tools/youth-financial-education/survey-errors.cy.js, test/cypress/integration/consumer-tools/youth-financial-education/survey-progress.cy.js
Several Youth Financial Education tests are skipped on headless mode. However, I removed the skips and the tests passed locally. Maybe this has been rectified through updates to Cypress, so this PR removes the gates to see how they perform on GH actions. 
- Remove skipOn headless gates from some Youth Financial Education tests.
1. PR functional tests for the Youth Financial Education tests should pass.
=> Youth Financial Education: Remove headless skips on tests

test/unit_tests/apps/teachers-digital-platform/js/survey/grade-level-page-spec.js, test/unit_tests/apps/teachers-digital-platform/js/survey/results-page-spec.js, test/unit_tests/apps/teachers-digital-platform/js/survey/survey-page-spec.js, test/unit_tests/apps/teachers-digital-platform/js/tdp-surveys-spec.js
Mostly keeps test logic intact while replacing spies
=> Update tdp spy tests for esm

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/section.html, test/cypress/integration/compliance/small-business-lending/filing-instruction-guide-helpers.cy.js, test/cypress/integration/compliance/small-business-lending/filing-instruction-guide.cy.js
Most of our level 3 FIG sections are auto-generated from the data points JSON. However, when we manually create them, their TOC highlighting is semi-broken because they don't correctly identify their level 2 parent. You can see the issue when you visit the draft FIG on content, open your browser console and scroll to section 4.
This PR fixes that by correctly attributing level 3 sections to their level 2 parent in the TOC.
- Fixed a jinja template
- Added a smoke test to confirm there are never console errors
- Improved the reliability of an unrelated test
1. Import a prod DB dump if you haven't recently to get the FIG draft that's currently staged on content.
1. Publish the FIG page locally with whatever slug you'd like, e.g. …
=> Fix FIG TOC highlighting with manually created FIG sections

cfgov/jobmanager/jinja2/jobmanager/job_listing_list.html, cfgov/jobmanager/jinja2/jobmanager/job_listing_page.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/macros/financial-item-expandable.html, cfgov/prepaid_agreements/jinja2/prepaid_agreements/detail.html, cfgov/regulations3k/jinja2/regulations3k/inline_interps.html, cfgov/v1/jinja2/v1/activity-log/_activity-list.html, cfgov/v1/jinja2/v1/activity-log/index.html, cfgov/v1/jinja2/v1/includes/molecules/contact-address.html, cfgov/v1/jinja2/v1/includes/molecules/contact-phone.html, cfgov/v1/jinja2/v1/includes/organisms/data_snapshot.html, cfgov/v1/jinja2/v1/includes/organisms/expandable.html, cfgov/v1/jinja2/v1/includes/organisms/info-unit-group.html, test/unit_tests/apps/filing-instruction-guide/fixtures/sample-fig-page.js, test/unit_tests/apps/teachers-digital-platform/js/expandable-mobile-spec.js, test/unit_tests/apps/teachers-digital-platform/js/search-spec.js, test/unit_tests/apps/teachers-digital-platform/js/tdp-analytics-spec.js
We pepper this into our markup in a few places but never actually target it (or, rather, don't target it anymore).
=> Remove unused data-qa-hook used in a couple places

cfgov/cfgov/settings/base.py
We're ramping up to restart A/B testing on cf.gov using Google Optimize. Optimize and the Optimize Chrome extension require some third-party scripts and styles from domains that weren't included in our CSP. See https://support.google.com/optimize/answer/7388531 for Google's official list of what needs to be included in the CSP and GHE/Design-Development/Design-Thinking-and-User-Research/issues/63 for more details. That internal issue has a screenshot of the error we get right now when trying to run the Optimize Chrome extension.
---
- Entries to the CSP to allow Google Optimize and the Optimize Chrome extension to run
As far as I can tell, there's no good way to test this until it's deployed and we can see if we can run Optimize A/B tests and the Optimize Chrome extension.
- The addition …
=> Add CSP entries for Google Optimize

cfgov/cfgov/settings/base.py
This change adds a comment to our CSP settings so that anyone changing them knows the modified values will not be returned by Akamai unless either a page's content changes or a delete-purge is performed.
=> Add a comment about CSP headers and `ETag`s

test/cypress/integration/consumer-tools/youth-financial-education/survey-errors.cy.js
This TDP test is meant to check that the financial education survey tool scrolls to the error message at the top of the page if there's an error on submission. That test has always been flaky, and we've tried various fixes and workarounds (see #7243, #7424, #7447). Despite all of that, the test continues to fail intermittently on headless runs in our CI/CD pipeline, preventing automatic releases and deployments. At this point, we've decided the test is more trouble than it's worth, so we're going to mark it as pending with `xit` so it won't run for the time being.
---
- Skip troublesome TDP scroll test (and add a TODO comment noting why)
1. Run Cypress tests however you like: `yarn cypress open` to run them in the Cypress UI, `yarn cypress run` to run them all headless, or `yarn cypress …
=> Skip troublesome TDP functional test

cfgov/v1/jinja2/v1/browse-basic/index.html
This commit adds the translation-links module to BrowsePages, placing it between the header section and content sections of the page (also above the "share and print" module, if that is added).
Using a production dump with our internal set of translation links, a good URL to test this with is
http://localhost:8000/coronavirus/mortgage-and-housing-assistance/help-for-homeowners/
Note that the styling, language, and order of the translation links still needs some work; those things are to be addressed in other PRs.
Auto-generated links are circled in red:
=> Add translation links to BrowsePage template

cfgov/v1/management/commands/import_translation_links.py, cfgov/v1/tests/management/commands/test_import_translation_links.py
This commit updates the import_translation_links management command:
- Excel-generated CSV files can now be read, by opening the file using Python's `utf-8-sig` encoding.
- New `--ignore-missing` option lets the script ignore any URLs in the input CSV that don't exist (yet).
- New `--skip-header` option lets the script skip the first row of the CSV.
Unit tests have been updated to cover the new behavior.
Download the Excel file at internal D&CT/issues/122#issuecomment-329066, then save as CSV, then run:
> cfgov/manage.py import_translation_links --revision-username your.username --republish --skip-header --ignore-missing import-spreadsheet.csv
The script will work properly, skipping the header row, and ignoring the URLs in the CSV that don't exist yet.
=> Minor improvements to import_translation_links

cfgov/cfgov/settings/base.py, cfgov/mega_menu/models.py, cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py, cfgov/v1/views/reports.py
This commit updates the CFGOVPage.get_translations method to adjust the order of returned page translations. Instead of returning translations by the alphabetical order of their language (ar, en, es, ...), they are now returned in a deliberate arbitrary order to be consistent with the website header:
en, es, zh-Hant, vi, ko, tl, ru, ar, ht
~~Similarly, the link text returned by CFGOVPage.get_translation_links is also changed so that instead of returning the English name of the language, as defined in settings (English, Spanish, ...), it returns a deliberate arbitrary set of language name translations:~~
~~English, Español, 繁體中文, Tiếng Việt, 한국어, Tagalog, Pусский, العربية, Kreyòl Ayisyen~~
Technically, this is achieved by annotating the PageQuerySet returned by CFGOVPage.get_translations …
=> Fix ordering of translation links

cfgov/v1/jinja2tags/__init__.py, cfgov/v1/util/ref.py
Remove unused `is_event` Jinja function.
Grep the codebase, this wasn't used anywhere.
=> Remove unused "is_event" Jinja function

cfgov/cfgov/settings/base.py, cfgov/core/jinja2tags.py, cfgov/core/tests/test_jinja2tags.py, cfgov/v1/jinja2/v1/includes/molecules/translation-links.html, cfgov/v1/models/base.py
This commit introduces a new Jinja {% language %} tag modeled after the Django {% language %} tag, and uses it to ensure that page translation links always get rendered in the destination language (e.g. links to a Spanish translation always say "Español" regardless of the language of the page being viewed).
To test using a production dump with translation links imported using the method described in #7461, a good page to test with is http://localhost:8000/es/coronavirus/asistencia-hipotecas-y-viviendas/:
The lack of translation for "Chinese (Traditional)" is to be expected; that will come with the new translations added in #7392.
Alternatively, to test with our test database (`./refresh-data.sh ./test.sql.tz`), a good page to test with is …
=> Render translation links in their own language

docs/translation.md
In #7392 we removed the `cfgov/locale` directory. This quick change fixes one last reference to it.
=> Correct docs missed in locale move

cfgov/core/jinja2tags.py, cfgov/mega_menu/jinja2tags.py, cfgov/regulations3k/jinja2tags.py, cfgov/regulations3k/models/pages.py, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html, cfgov/v1/jinja2/v1/template_debug.html, cfgov/v1/jinja2tags/__init__.py, cfgov/wellbeing/jinja2/wellbeing/results.html, requirements/libraries.txt
(Note: this PR is going to the upgrade/wagtail branch, not main.)
This PR upgrades the version of the [Jinja2](https://pypi.org/project/Jinja2/) Python library from 3.0.3 to 3.1.2. 3.0.3 is the latest version we can be on with Wagtail 2.15.x, so this PR is going into our Wagtail 3.x upgrade branch.
See Jinja2 release notes [here](https://jinja.palletsprojects.com/en/3.1.x/changes/). See specific commits below for details of the changes; there are no user-facing differences.
Addresses internal D&CT#113.
The only template change is migrating some use of `dict.items()` to `dict | items`. We had three uses of `.items()`; the proper functionality of these pages can be verified locally at:
- http://localhost:8000/admin/template_debug/v1/featured_content/
- …
=> Bump Jinja2 version from 3.0.3 to 3.1.2

cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/molecules/translation-links.less, cfgov/v1/jinja2/v1/includes/molecules/translation-links.html
- Convert `div` enclosed list of translation links into an unordered list.
- Add `dir`, `translate`, and `lang` attributes to markup.
- Add CSS to lay out links in a flexbox and handle rtl layout.
1. Pull branch, run `yarn build`.
2. Visit https://[GHE]/Design-Development/Design-and-Content-Team/issues/147#issue-110288 to see places to check the language links. Resize page to see how it wraps.
=> Translation links: Add less file and rework markup to be a list

cfgov/v1/management/commands/publish_pages.py, cfgov/v1/tests/management/commands/test_publish_pages.py
This commit adds a new `publish_pages` management command which allows for the bulk publishing of multiple Wagtail pages, given a list of URLs in a text file.
See command file comments and management command help for usage details. Unit tests have been added to cover the command's functionality.
See internal D&CP#122 for additional context.
=> Add new publish_pages management command

cfgov/jobmanager/wagtail_hooks.py
This commit deprecates some unnecessary custom admin code related to the jobmanager.JobCategory model. This code was necessary at one point when this model used a custom editor which required its own JavaScript (TinyMCE). That functionality was removed in 1458acdf43fb5a2627f994a109d104ae1f80812d, which migrated the "blurb" field to a standard Wagtail rich text field. This removed the need for any custom ModelAdmin code.
To test locally: http://localhost:8000/admin/jobmanager/jobcategory/ and then try to edit a category (Using a production data, one with blurb content is http://localhost:8000/admin/jobmanager/jobcategory/edit/33/).
=> Deprecate custom JobCategory admin code

cfgov/core/__init__.py, cfgov/jobmanager/__init__.py, cfgov/v1/__init__.py
Django 3.2 removed the need to define a default_app_config in an app's \_\_init__.py file:
https://docs.djangoproject.com/en/4.1/releases/3.2/#automatic-appconfig-discovery
This is deprecated as of 3.2 and defining it triggers warnings like:
> RemovedInDjango41Warning: 'v1' defines default_app_config = 'v1.apps.V1AppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
This commit removes our default_app_config definitions to remove those deprecation warnings.
=> Remove definitions of default_app_config

cfgov/v1/models/filterable_list_mixins.py, cfgov/v1/tests/models/test_filterable_list_mixins.py
This removes a set of overrides in `FilterableListMixin`’s `render` method. Prior to [Wagtail 2.11](https://docs.wagtail.org/en/stable/releases/2.11.html#other-features), `RoutablePageMixin`, which `FilterableListMixin` inherits from, did not make use of the `context_overrides` keyword argument, so we overrode template rendering.
That’s no longer the case, so this override code can be removed.
The `render` method is preserved for use of our `X-Robots-Tag` setting only.
=> Remove pre-Wagtail 2.11 `FilterableListMixin` render overrides

cfgov/v1/models/banners.py
This change removes our `BannerContent` steam block model, which existed to enforce a `min_num` and `max_num` count on the notification content of a `Banner`. Since [Wagtail 2.13](https://docs.wagtail.org/en/stable/releases/2.13.html#other-features), Wagtail has supported passing those values from the `StreamField` itself.
Perhaps unintuitively, this change does not require a migration, because the overall structure of the `StreamField` in the database is unchanged.
There is one subtle difference between the way the content block behaved prior to this change and after it:
Before this change, you could click the "+" above and below an existing `content` block, and the option to add a new content block would be greyed-out:
After this change, the ability to click the "+" above and below an …
=> Set `min_num` and `max_num` on banner `content` field

requirements/libraries.txt
No functional changes; only addresses a deprecation warning.
See ccdb5-api v1.7.0 release notes:
https://github.com/cfpb/ccdb5-api/releases/tag/1.7.0
=> Bump version of ccdb5-api from 1.6.6. to 1.7.0

cfgov/unprocessed/apps/filing-instruction-guide/js/fig-search.js, cfgov/unprocessed/apps/filing-instruction-guide/js/fig-sidenav.js
Instead of just reporting the HTML ID of the element selected by the user, report the full innerText. Also, track table of contents clicks.
1. Import a prod DB dump if you haven't recently to get the FIG draft that's currently staged on content.
1. Publish the FIG draft locally so that it’s viewable and no longer a draft.
1. Tests should pass headlessly:
`yarn cypress run --spec test/cypress/integration/compliance/small-business-lending/ --env FIG_URL=/data-research/small-business-lending-data/filing-instructions-guide/2024-guide/`
1. Tests should pass with your local copy of Chrome (click on filing-instruction-guide.cy.js):
`yarn cypress open --e2e --browser chrome --env FIG_URL=/data-research/small-business-lending-data/filing-instructions-guide/2024-guide/`
- …
=> Report full link text w/ FIG analytics

cfgov/wagtailadmin_overrides/templates/wagtailadmin/pages/listing/_button_with_dropdown.html
Commit cd92d27c71c5d8ef23aa788a734867dd09b22984 accidentally exposed a weird "Delete' as delete_label" string that was appearing in the Wagtail admin. This commit fixes that.
Fixes internal D&CT#156.
Browse the page tree, for example: http://localhost:8000/admin/pages/319/
|Before|After|
|-|-|
|<img width="581" alt="image" src="https://user-images.githubusercontent.com/654645/216418696-a9cd8b4d-7bc9-40b6-97b8-842cfcd7afdc.png">|<img width="583" alt="image" src="https://user-images.githubusercontent.com/654645/216418621-23195c4f-1428-4f27-8ed0-8f6526c3f067.png">|
=> Re-hide "Delete" link on page actions dropdown

.env_SAMPLE, docker-compose.prod.yml, helm/overrides/dev-vars.yaml
This commit removes the definition of an unused WATCHMAN_TOKENS environment variable. This was needed when this project used the django-watchman package, but support for that was removed in April 2022:
https://github.com/cfpb/consumerfinance.gov/commit/b7676c26ffa611ce616a6fe426cc9a8b5d0c4d87
This commit removes a few references that were left behind.
=> Remove WATCHMAN_TOKENS environment variable

cfgov/unprocessed/apps/filing-instruction-guide/css/main.less, cfgov/v1/jinja2/v1/includes/organisms/secondary-navigation-fig.html
The effective date was being shown on mobile even if a status wasn't set. Also, really long validation IDs like `amount_applied_for_flag.invalid_enum_value` were forcing a horizontal scrollbar so now they break to the next line on smaller screens.
1. If a FIG's version status is `Current` there should be no `Effective...` sentence at the top of the table of contents. If it's not `Current`, the sentence should exist.
| <img width="472" alt="Screen Shot 2023-02-02 at 12 57 40 PM" src="https://user-images.githubusercontent.com/1060248/216407669-1273283b-35bb-48f5-ab8c-275ebdc38726.png"> | <img width="472" alt="Screen Shot 2023-02-02 at 12 58 03 PM" …
=> Fix couple FIG mobile bugs

docs/consumer-complaint-database.md
The original docs link provided a way to specify a config file for the documentation, which opens the docs to mischief.
The new link removes the config selection box.
You can preview the safer API link via my fork of cfgov, where I've published the new link to gh-pages.
https://higs4281.github.io/consumerfinance.gov/consumer-complaint-database/
=> Change the CCDB API link to a more secure rendering

cfgov/cfgov/settings/base.py, cfgov/login/email.py, cfgov/login/tests/test_email.py
(This PR is against the upgrade/wagtail branch, not the main branch.)
As of Wagtail 3.0, we need to define a Django setting named [`WAGTAILADMIN_BASE_URL`](https://docs.wagtail.org/en/stable/reference/settings.html#wagtailadmin-base-url) to tell Wagtail the base URL of the running website (example: https://www.consumerfinance.gov).
Without defining this, Django reports this warning when it runs:
> ?: (wagtailadmin.W003) The WAGTAILADMIN_BASE_URL setting is not defined HINT: This should be the base URL used to access the Wagtail admin site. Without this, URLs in notification emails will not display correctly.
This commit sets a default of "http://localhost:8000" for this value, or uses the environment variable `WAGTAILADMIN_BASE_URL` if it is defined.
Ideally we would be able to put …
=> Define WAGTAILADMIN_BASE_URL setting

cfgov/wagtailadmin_overrides/templates/wagtailadmin/pages/listing/_button_with_dropdown.html, cfgov/wagtailadmin_overrides/templates/wagtailadmin/shared/page_status_tag.html
This change updates our overrides of the Wagtail admin’s built-in:
-  `page_status_tag.html` template that is intended to use `page.full_url` instead of `page.url` as the destination for the “Live” status link.
This brings the template up-to-date with Wagtail’s as of the [`stable/3.0.x` branch](https://github.com/wagtail/wagtail/blob/stable/3.0.x/wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html). The change to the base Wagtail template is simply replacing `page.url` with `page.full_url`.
- `_button_with_dropdown.html` template that is intended to hide the “delete” option.
This brings the template up-to-date with Wagtail’s as of the [`stable/3.0.x` branch](https://github.com/wagtail/wagtail/blob/stable/3.0.x/wagtail/admin/templates/wagtailadmin/pages/listing/_button_with_dro …
=> Update two of our Wagtail admin template overrides

cfgov/v1/jinja2/v1/browse-basic/index.html, cfgov/v1/jinja2/v1/includes/article.html, cfgov/v1/jinja2/v1/includes/molecules/text-introduction.html, cfgov/v1/jinja2/v1/includes/molecules/translation-links.html, cfgov/v1/jinja2/v1/includes/organisms/item-introduction.html, cfgov/v1/jinja2/v1/learn-page/index.html, cfgov/v1/jinja2/v1/sublanding-page/index.html, cfgov/v1/models/sublanding_page.py, cfgov/v1/tests/models/test_sublanding_page.py
This commit moves Wagtail page translation links so that they sit below the `<h1>` tag on all page types. It does this by moving the inclusion of the translation-links.html template out of some of our page templates and into the ItemIntroduction and TextIntroduction modules, which render the `<h1>`.
With this change, the links get rendered:
- In an ItemIntroduction or TextIntroduction, if the heading is defined.
- Or, on SublandingPages, if a hero has been added. On some SLPs we use a TextIntroduction instead of a hero, but we should never use both.
Note that this PR doesn't include changes to the link margin; that is implemented in #7516.
To test this, run a local server with a production dump. Here are some example pages to visit to verify functionality is working properly:
- BlogPage: …
=> Move translation links below `<h1>` tags

cfgov/unprocessed/css/molecules/translation-links.less, cfgov/v1/jinja2/v1/includes/molecules/translation-links.html
This commit makes three minor style changes to how we render Wagtail page translation links:
1. Font weight is set to 500.
2. Links get underlines.
3. The links `<ul>` is wrapped in a `<div class="block block__sub">` to ensure 30px of collapsible margin above and below.
These changes come from @jenn-franklin's guidance on internal D&CP#122#issuecomment-328946.
To test locally, `yarn run build` then visit:
- template debug view: http://localhost:8000/admin/template_debug/v1/translation_links/
- BlogPage: http://localhost:8000/about-us/blog/know-your-rights-and-protections-when-it-comes-to-medical-bills-and-collections/
- BrowsePage: http://localhost:8000/coronavirus/mortgage-and-housing-assistance/help-for-homeowners/
- LearnPage: http://localhost:8000/admin/pages/15468/view_draft/
- …
=> Translation links style iteration

cfgov/v1/jinja2/v1/includes/molecules/translation-links.html
0ee2655b8e4145c2a9e8ca6eeea82c68427befca inadvertently broke how the current page language gets rendered in our translation links, [for example](https://www.consumerfinance.gov/language/vi/mortgages-key-terms/) here the Vietnamese page should not be a link because we are currently viewing it.
This PR fixes that; if the `language` variable isn't defined when rendering the translation links template, try to grab it off of the page object by using `page.language`.
=> Use page language for translation links

cfgov/v1/jinja2/v1/includes/atoms/tagline.html
Just noticed this code comment was missing.
- Add missing tagline argument code comment
=> Tagline: Add missing `is_large` argument code comment

cfgov/v1/templates/v1/active_users_report.html, cfgov/v1/tests/views/test_reports_view.py, cfgov/v1/views/reports.py, cfgov/v1/wagtail_hooks.py
As a way to understand who we need to inform about upgrades (as well as maybe helping when we want to explore more about our users), I’ve added a new Wagtail report that just lists the username, first, last, and email of each active user (has logged in within the last 90 days).
This puts in the Wagtail admin the information we’d usually go to the Django admin for, but Excel-exportable. This should let us compare multiple environments more directly with spreadsheets.
1. Pull this PR
2. Visit http://localhost:8000/admin/reports/active-users/ to view the report
=> Add an active users report

cfgov/ask_cfpb/models/pages.py
Currently any pages that inherit from SecondaryNavigationJSMixin only include the secondary navigation JS on English language pages. But the secondary navigation is also used for the "In this section" expandable component rendered on BrowsePages on mobile.
So, on these Spanish pages the JS is currently missing, causing the expandable to render as open (and be un-closeable). For example, visit this page at a mobile width and notice the fixed "En esta sección" component:
https://www.consumerfinance.gov/es/herramientas-del-consumidor/prestamos-del-dia-de-pago/respuestas/
Compare to a comparable English page:
https://www.consumerfinance.gov/consumer-tools/reverse-mortgages/answers/
|Before|After|
|-|-|
|<img width="884" alt="image" src="https://user-images.githubusercontent.com/654645/22108482 …
=> Add missing secondary navigation JS to Spanish pages

cfgov/unprocessed/js/organisms/FormSubmit.js
Follow up to https://github.com/cfpb/consumerfinance.gov/pull/7462 that adds the missing initial class to the AlphaTransition.
- Adds (now required) missing initial class to the AlphaTransition in the FormSubmit module.
1. The codepath for this code is unused, but it would be if `replaceForm` is passed as an option into `new FormSubmit(…)`. You can manually do this by replacing:
```
const formSubmit = new FormSubmit(emailSignup, BASE_CLASS, {
validator: (fields) =>
validators.email(fields.email, '', { language: language }).msg,
language: language,
});
``` 
with 
```
const formSubmit = new FormSubmit(emailSignup, BASE_CLASS, {
validator: (fields) =>
validators.email(fields.email, '', { language: language }).msg,
language: language,
replaceForm: true,
});
```
In …
=> Bugfix: Add initial class to FormSubmit AlphaTransition

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/index.html, cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/jinja2/ccdb-complaint/ccdb-search.html, cfgov/jinja2/owning-a-home/explore-rates/index.html, cfgov/jinja2/rural-or-underserved/index.html, cfgov/paying_for_college/jinja2/paying-for-college/college-costs.html, cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html, cfgov/prepaid_agreements/jinja2/prepaid_agreements/detail.html, cfgov/privacy/jinja2/privacy/disclosure-consent-form.html, cfgov/privacy/jinja2/privacy/records-access-form.html, cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html, cfgov/regulations3k/jinja2/regulations3k/landing-page.html, cfgov/regulations3k/jinja2/regulations3k/search-regulations.html, cfgov/retirement_api/jinja2/retirement_api/claiming.html, cfgov/wellbeing/jinja2/wellbeing/home.html, cfgov/wellbeing/jinja2/wellbeing/results.html
We have a common pattern in our templates where we load individual scripts via our JavaScript loader function, jsl: first, we check to make sure that the page isn't being rendered in no-js mode. The idea behind this check is that we might have no-js even if JavaScript is enabled, in cases where the browser doesn't support fetch.
Here's where we set no-js if the browser doesn't support fetch:
https://github.com/cfpb/consumerfinance.gov/blob/c19933a38d413a313ba39edc53a4f94c7cc819d5/cfgov/v1/jinja2/v1/layouts/base.html#L210-L212
But our jsl function already checks for window.fetch support:
https://github.com/cfpb/consumerfinance.gov/blob/c19933a38d413a313ba39edc53a4f94c7cc819d5/cfgov/v1/jinja2/v1/layouts/base.html#L201-L204
So current logic:
1. Browser doesn't support fetch, we set no-js on …
=> Remove unnecessary no-js check before using jsl

cfgov/mega_menu/jinja2/mega_menu/mega-menu.html, cfgov/unprocessed/css/molecules/global-eyebrow.less, cfgov/v1/jinja2/v1/includes/molecules/global-eyebrow.html
Follow up to https://github.com/cfpb/consumerfinance.gov/pull/7522
I realized we could tie the tagline inclusion logic to the layout, for which we already had the `is_horizontal` argument. This means that it wouldn't be possible to have a list (vertical) layout AND have a tagline, meaning we can remove its styling as well. Much better!
- Tie presence of the tagline in the global eyebrow to the layout format of the eyebrow.
- Add some missing documentation in the code.
1. Pull branch and see that there are only two a-taglines in the markup (header and footer).
=> Eyebrow: Tie tagline logic to layout

.github/workflows/codeql-analysis.yml
Per [this GitHub changelog entry](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/), CodeQL v1 actions are deprecated. This updates those actions to v2.
=> Update CodeQL Action versions

cfgov/unprocessed/apps/admin/js/rich-text-table.js
Currently we’re giving the same id to every rich text table editor on a page. Because of the way Handsontable cell editors are constructed, there’s one editor per table, but when we have multiple tables per page they’re all creating table cell editors with the same id. This seems to be behind the weirdness we’re seeing with multi-table page editing.
As far as I can tell, the field id that gets passed to our `initAtomicTable` function doesn’t easy pass through Handsontable (whos constructor takes an element that we lookup by that id) to the cell editor. So my fix here is to crawl up the dom to where I can see we have an id that’s unique to this table and use that.
I don’t know if this is the right approach, but it demonstrates a fix.
1. Edit tables on …
=> Use a unique ID for each rich text table editor

cfgov/ask_cfpb/migrations/0045_set_max_num_on_notifications.py, cfgov/v1/management/commands/publish_pages.py, cfgov/v1/tests/management/commands/test_publish_pages.py, cfgov/v1/tests/views/test_reports_view.py
(This PR is to upgrade/wagtail, not to main.)
Re-run `wagtail updatemodulepaths` per the Wagtail 3 upgrade notes:
https://docs.wagtail.org/en/latest/releases/3.0.html#changes-to-module-paths
This reflects changes to the Wagtail module import paths.
We ran this previously in bf2dbcd70e3ec972233440b72ad3fc7b5a187e69 a few weeks back, but since then more code has been merged into cf.gov main.
=> Re-run updatemodulepaths for Wagtail 3 upgrade

cfgov/jobmanager/jinja2/jobmanager/job_listing_table.html, cfgov/jobmanager/tests/test_blocks.py, cfgov/v1/jinja2/v1/includes/organisms/contact-us-table.html, cfgov/v1/jinja2/v1/includes/organisms/table.html, cfgov/v1/tests/atomic_elements/organisms/test_tables.py
Currently we allow unsafe HTML to be entered into any uses of our underlying table template (table.html), whether it is being rendered by our Wagtail AtomicTableBlock or manually rendered via some other template.
I recently added a custom ContactUsTable in #7533, but I realized that because it uses the underlying table template, it also supports unsafe HTML -- but there's no reason to allow it to do so.
Hopefully someday we can eliminate all uses of unsafe HTML, but in the meantime maybe we can prevent some specific uses.
In this PR I've added the ability to prevent unsafe HTML when rendering using table.html, and blocked unsafe HTML in two use cases: the new Contact Us Table and the existing job listings table. All other uses of table.html, including our AtomicTableBlock, still allow …
=> Prevent some uses of unsafe HTML in tables

cfgov/unprocessed/apps/teachers-digital-platform/css/pages/survey-results.less, cfgov/unprocessed/css/organisms/secondary-navigation.less
This class does not exist in the expandable CSS https://github.com/cfpb/design-system/blob/main/packages/cfpb-expandables/src/cfpb-expandables.less
I can't find any markup for the TDP reference, even in the crawler, so it appears it can be removed from the TDP CSS.
- Remove `o-expandable_header-left` references.
=> Remove o-expandable_header-left reference

cfgov/jobmanager/jinja2/jobmanager/job_listing_table.html, cfgov/jobmanager/tests/test_blocks.py
=> Restore ability to use usafe HTML in job listings table

test/cypress/integration/components/header/header.cy.js
Header tests check visibility of mega menu and global search when clicking between them, but we need to check that they have stopped animating. Hopefully this takes care of the flaky header test.
- Add checks for the completion of animation of the global search and mega menu in the header tests.
=> Attempt to fix flaky header test

test/cypress/integration/components/header/header.cy.js, test/cypress/integration/consumer-tools/ask-cfpb/answer-helpers.cy.js, test/cypress/integration/consumer-tools/ask-cfpb/ask-cfpb.cy.js
Follow up to https://github.com/cfpb/consumerfinance.gov/pull/7550 to check that the content is not hidden on clicks of links inside the summary component on desktop when it is suspended.
- Break ask-cfpb tests into desktop and mobile and perform additional tests to catch focusin issues.
=> Add more ask-cfpb cypress tests

cfgov/cfgov/settings/base.py, test/cypress/integration/admin/admin.cy.js
With the upgrade to Wagtail 3.0 we noticed that search in the Wagtail admin is no longer working as expected; specifically, autocomplete and substring searches don't seem to work the way they used to.
This is because in 3.0, behavior changed such that if you don't define `WAGTAILSEARCH_BACKENDS`, a different search backend is used (https://github.com/wagtail/wagtail/commit/00582ba35a2368890586c167636c9c2aad21cab3#diff-b3aaeb336b53eef65cb0d229f42fcc97756ab3d233fa9d3128c5ab34cdb942c5).
This is also related to https://github.com/wagtail/wagtail/issues/7720, fixed by https://github.com/wagtail/wagtail/pull/9900 in version 4.2, at least for the PostgreSQL database backend.
As a workaround for now, we can use the Wagtail "fallback" database search which uses a simpler substring-based search. If …
=> Restore Wagtail fallback database search

pyproject.toml
Bandit [1.7.5 adds a test for calls to `requests.get()` that do not include a `timeout` parameter](https://bandit.readthedocs.io/en/1.7.5/plugins/b113_request_without_timeout.html). This PR adds that test to our skipped tests.
We have several of these, and we need to address them, but that can happen without our linting being blocked for all PRs at the moment.
=> Temporarily skip Bandit test for `requests.get()`

cfgov/agreements/jinja2/agreements/search.html, cfgov/jinja2/owning-a-home/explore-rates/index.html, cfgov/jinja2/rural-or-underserved/index.html
Remove unused and unnecessary definitions of `page_js` and `active_page` in a few templates.
=> Tiny bit of template cleanup

cfgov/unprocessed/css/organisms/footer.less
This class in the footer doesn't appear in the crawler. 
- Remove `o-footer_share-icon-list`
=> Remove `o-footer_share-icon-list`

requirements/libraries.txt
The [new 2.8 release of wagtail-sharing](https://github.com/cfpb/wagtail-sharing/releases/tag/2.8) adds support for Wagtail 4.x. This doesn't affect anything with how cf.gov runs today, but we want to be able to upgrade to Wagtail 4, so we should bump this version.
=> Bump wagtail-sharing version from 2.7 to 2.8

cfgov/cfgov/settings/base.py, requirements/libraries.txt, test/cypress/integration/admin/admin-helpers.cy.js
This updates wagtail-inventory to the recently released version 2.0.0. This converts the block inventory into a Wagtail report, reviewable in the "Reports" menu.
=> Update wagtail-inventory to 2.0.0

test/cypress/integration/admin/admin-helpers.cy.js
This change makes some improvements to our block inventory Cypress tests to ensure they’ll pass.
It selects the first available `ask_cfpb.models.block` block, rather than a specific one. I’ve also made it ensure that not only is the result table visible, it has at least 1 item in it.
I have confirmed this fixes our functional test run in Jenkins.
=> Minor improvements to block inventory Cypress tests

cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html
- Paying for College disclosures: Replace hardcoded icons with standard icon loader
1. Visit the [disclosures tool](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=154022&pid=BAHCA&totl=70950&tuit=14160&hous=7109&book=1150&tran=500&othr=4743&pelg=0&schg=&stag=&othg=&mta=&gib=&wkst=0&ppl=&parl=&perl=&subl=3500&unsl=6000&gpl=&prvl=&prvi=&prvf=&insl=&insi=&inst=&oid=4D0B9265B45716DF4B81EEB4BE117E1DF69871AF) 
1. start the tool and enter a huge number for the pell grant field to get an error message with a red error icon.
2. Scroll down to see "Add another private loan" and icon.
3. click through to the end of the tool to see print button and icon.
=> Paying for College disclosures: Replace hardcoded icons with standard icon loader

cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less, cfgov/unprocessed/apps/owning-a-home/css/helpers.less, cfgov/unprocessed/css/enhancements/layout.less
Minor adjustment to add `()` to mixins in equal height columns, as we do in other locations.
- Add `()` to mixins in equal height columns.
- Add `()` to reset mixin in owning-a-home styles.
This is only used on https://www.consumerfinance.gov/your-story/, so depending on how https://github.com/cfpb/consumerfinance.gov/pull/7409 is threshed out, these layout classes could be removed entirely.
=> Identify mixins in equal height columns layout and in owning-a-home

cfgov/regulations3k/jinja2/regulations3k/inline_interps.html, requirements/libraries.txt
- eregs: convert hardcoded icons to use standard loader
1. Visit http://localhost:8000/rules-policy/regulations/1002/10/ and see that the expandable in the content has a show/hide icon.
=> eregs: convert hardcoded icons to use standard loader

show_coverage.sh
This was added in https://github.com/cfpb/consumerfinance.gov/pull/2468, but our instructions have since been updated to show coverage with `tox -e lint -e unittest -e coverage` or to directly call the `coverage` command https://github.com/cfpb/consumerfinance.gov/blob/main/docs/python-unit-tests.md#coverage
- Remove `show_coverage.sh` script.
=> Remove `show_coverage.sh` script

cfgov/v1/jinja2/v1/events/_macros.html
Event archives can have a link to a flickr album, a video transcript, and a speech transcript. 
These three event archive pages have one of these:
https://www.consumerfinance.gov/about-us/events/archive-past-events/cfpb-rental-assistance-finder-tool-webinar/
https://www.consumerfinance.gov/about-us/events/archive-past-events/field-hearing-arbitration-albuquerque-nm/
https://www.consumerfinance.gov/about-us/events/archive-past-events/june-2016-consumer-advisory-board-meeting/
The flickr option creates an image that links to the flickr album URL, which isn't a valid image URL, so it shows as a broken image. 
- Remove extraneous layout nesting.
- Remove unused `event-archive_media-container` and `speech_link-container` classes.
- Remove `content-l__large-gutters` class.
- Place each option …
=> Event archive: Cleanup and simplify event links

requirements/libraries.txt
This brings Regdown to 1.0.7, fixing an issue that results from our previous attempt to address SVG rendering in #7614. 
Regdown 1.0.6 fixed the SVG rendering, but introduced a placement bug for rendered block references. Regdown 1.0.7 fixes that.
Before:
After:
=> Bump regdown to 1.0.7

cfgov/housing_counselor/jinja2/housing_counselor/index.html
There were two of these classes mistakenly applied.
- Housing counselor: remove extraneous `block__flush-top`
=> Housing counselor: remove extraneous `block__flush-top`

cfgov/mega_menu/jinja2/mega_menu/mega-menu.html, cfgov/unprocessed/css/organisms/mega-menu.less, test/cypress/integration/components/header/mega-menu-helpers.cy.js, test/cypress/integration/components/header/mega-menu.cy.js
https://github.com/cfpb/consumerfinance.gov/pull/7534 was a little too zealous in converting `aria-expanded` to `data-open`. We did need to remove some of them (https://github.com/cfpb/design-system/pull/1595), but the ones on the links remain and control highlighting the tab when it is open. 
- Revert back to targeting aria-expanded on menu links, from data-open.
- Add some Cypress testing for the styles to catch this kind of bug.
2. Pull branch 'n' build, and visit any page and see that the tab in the desktop menu is highlighted when it is clicked.
before:
after:
=> Adjust mega menu attributes to fix open bug

cfgov/ask_cfpb/templates/admin/export.html, cfgov/v1/management/commands/makemessages.py, cfgov/v1/templates/cdnadmin/disabled.html, cfgov/v1/templates/cdnadmin/index.html, cfgov/v1/templates/v1/_list_translated_page.html, cfgov/v1/templates/v1/export_feedback.html, cfgov/v1/templates/v1/page_metadata_report.html, cfgov/v1/templates/v1/report_no-xlsx_base.html, cfgov/v1/templates/v1/translated_pages_report.html, cfgov/v1/tests/management/commands/test_makemessages_data/templates/test.html, cfgov/wagtailadmin_overrides/templates/wagtailadmin/login.html, cfgov/wagtailadmin_overrides/templates/wagtailadmin/shared/page_status_tag.html, docs/translation.md
Django replaced these in Django 3.1.
I've left in-place some translation tags that... I'm not sure we need, mostly to keep this scoped to just template changes, rather than regenerating our message files and recompiling them.
=> Replace old Django i18n tags with `translate`/`blocktranslate`

cfgov/v1/jinja2/v1/layouts/layout-1-3.html, cfgov/v1/jinja2/v1/layouts/layout-2-1.html
These are two temporary classes for the crawler to see if breadcrumbs are used within the child templates of content-base.html
- Add temporary classes for the purposes of searching for breadcrumb uses.
- The idea is to add these, wait a day, check the crawler, and then remove these whole blocks if nothing comes up.
=> Add temporary classes to search for breadcrumb uses

cfgov/jobmanager/models/pages.py, cfgov/teachers_digital_platform/models/pages.py, cfgov/v1/models/campaign_page.py, cfgov/v1/models/story_page.py
Wagtail page model will automatically search for a template name based on the class name. Very cool! However, we explicitly set a template name in each model except the story page and campaign page, which means if you search the codebase for those templates, their usage location is not found. Since we set the templates for the majority of things, let's set them for these two also. 
- Add template references for story and campaign page types.
1. You should be able to log into wagtail and create a story and campaign page without error.
=> Wagtail: Explicitly reference templates

cfgov/jinja2/owning-a-home/_templates/brand-header.html, cfgov/jinja2/owning-a-home/explore-rates/index.html, cfgov/unprocessed/apps/owning-a-home/css/brand-header.less, cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less, cfgov/unprocessed/apps/owning-a-home/css/helpers.less
While looking into page layout tweaks, I noticed we sprinkle `wrapper` around many places. This class is almost identical to `content_wrapper`. I'm trying to untangle them a bit to help simplify layout tasks. OAH's rate checker tool uses `wrapper` a lot, which shouldn't be necessary. This PR removes those uses and several other pieces of unused CSS.
- Remove unused `content-banner` CSS class.
- Remove `wrapper` CSS class from rate checker tool, as well as sole extraneous wrapper divs.
- Remove unused `about` CSS class.
- Remove unused `about-data` CSS class. (Markup removed in https://github.com/cfpb/consumerfinance.gov/pull/7046)
- Remove unused `alert-positive`, `alert-warning`, `alert-neutral` CSS classes.
- Remove unused `alert-container` CSS class.
- Remove duplicate `block__bg` and …
=> OAH: Remove extraneous CSS

cfgov/v1/migrations/0199_2022_squash.py
Wagtail 4 supports django-taggit>=2.0,<4.0. But django-taggit 3.x changes slugs to allow for unicode storage, which alters how the model is defined in Django and can potentially require migration changes.
This caused the failure here: https://github.com/cfpb/consumerfinance.gov/actions/runs/4598094330/jobs/8121660413?pr=7638
See this Wagtail commit where they ran into the same issue:
https://github.com/wagtail/wagtail/commit/5b4242df3ca5636206d89e134f85725b41fe89cc
If you try this command `cfgov/manage.py makemigrations --check --dry-run`, it'll show no changes both on django-taggit 2.x and 3.x.
=> Support django-taggit 3.x

cfgov/teachers_digital_platform/tests/models/test_activity_index_page.py
Per the Wagtail 4.1 release notes, the WagtailPageTests test case class has been renamed to WagtailPageTestCase:
https://docs.wagtail.org/en/stable/releases/4.1.html#recommend-wagtailpagetestcase-in-place-of-wagtailpagetests
We only use this in one place. This commit updates that usage.
=> Change WagtailPageTests to WagtailPageTestCase

test/cypress/integration/admin/admin-helpers.cy.js, test/cypress/integration/admin/admin.cy.js
The admin functional tests of table functionality fail in Wagtail 4 because the rich text interface is completely different. Instead of the various formatting buttons (h3, h4, etc) being always visible, they only appear if users type '/'. Additionally, the link button functionality is different.
This PR simplifies those tests -- removing some that only test the rich text internals -- and ensures that the remaining tests work properly under Wagtail 4.
=> Fix admin functional tests for Wagtail 4

cfgov/permissions_viewer/wagtail_hooks.py
Wagtail 4 [removes `.button-secondary` from `UserListingButton` by default](https://docs.wagtail.org/en/stable/releases/4.1.html#button-styling-class-changes). This change restores that.
User listing buttons in Wagtail 4 before this change:
And after:
Wagtail 3 appearance for reference:
=> Add button-secondary to View Permissions button

cfgov/core/middleware.py, cfgov/core/tests/test_middleware.py
Page previews are currently broken on Wagtail 4. This fixes them.
Previews are currently broken because the preview sidebar loads the preview content in an iframe, and listens for the load event before showing the preview content to the user.
But the load event never fires for preview requests, which you can test directly in the browser by visiting a URL like:
http://localhost:8000/admin/pages/12893/edit/preview/?mode=&in_preview_panel=true
Why doesn't the load event fire? Because the length of the HTTP response doesn't match what gets sent in the Content-Length HTTP header. The header is slightly longer than the actual content. So the browser is waiting for more content which never comes, which keeps the page loading, which prevents the preview content from appearing.
So why is the …
=> Fix page previews on Wagtail 4

cfgov/v1/jinja2/v1/layouts/base.html
In the sidebar live preview panel in Wagtail 4.0+, links clicked in the preview panel should open in a new tab, per the release notes:
https://docs.wagtail.org/en/stable/releases/4.0.html#opening-links-within-the-live-preview-panel
Note: this change requires the fix in #7643 to properly test the live preview panel!
Edit a page, and click a link the sidebar preview panel. It should open in a new tab. Click on a link on a live page. It should open in the same tab.
=> Always open preview panel links in a new tab

cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py
Wagtail 4.0 decoupled the Page.serve and Page.serve_preview methods, which means that serve() code that would previously run at preview time no longer does:
https://docs.wagtail.org/en/stable/releases/4.0.html#changes-to-page-serve-and-page-serve-preview-methods
Practically, we override Page.serve in order to activate translations for the page language. In Wagtail 4.0, we need to make sure that this same code runs in Page.serve_preview. This commit does so.
To observe how this is broken on the current Wagtail 4 branch, edit a non-English page (for example, on a production dump, http://localhost:8000/admin/pages/17009/edit/) and look at the sidebar preview. If you click in the site search in the header, you'll see the blue search button says "Search" in English, which is wrong -- it should …
=> Fix language activation in Wagtail 4 page previews

cfgov/core/middleware.py, cfgov/core/tests/test_middleware.py
This PR cherry-picks a commit from #7643, which was intended to fix page previews on Wagtail 4, but also fixes a browser error around a content-length mismatch. See that PR for more details on the fix here, but essentially it makes sure that our link rewriting middleware only runs once on a single response.
=> Fix content-length mismatch error

cfgov/cfgov/settings/base.py, cfgov/v1/jinja2/v1/layouts/base.html
This is a followup to #7643 that tries to actually fix sidebar page previews in Wagtail 4; the previous PR was insufficient. (This is also a redo of #7647 which I accidentally force-pushed over as part of trying to rebase upgrade/wagtail4 against main.)
There are two independent commits here that combine to fix sidebar page previews.
First, this PR changes the Django setting for X-Frame-Options from DENY to SAMEORIGIN. Having it set to DENY prevents any cf.gov page from being loaded in an iframe; setting it to SAMEORIGIN instead lets that work as long as the parent page is on the same origin. Changing to SAMEORIGIN complies with our Django baseline.
Second, this PR disables the loading of Google JS (GA and GTM) when the page is viewed in the sidebar preview panel. We don't want to load …
=> Really fix page previews in Wagtail 4

cfgov/v1/templates/v1/_list_page_drafts.html, cfgov/v1/templates/v1/page_draft_report.html, cfgov/v1/views/reports.py, cfgov/v1/wagtail_hooks.py
This PR creates a new report in the Wagtail administrator panel for un-published pages. This allows content managers to assess and clean up unused sandbox or test pages and improve page database health.
---
- "Draft Pages" report
1. localhost
2. Check under the Reports sidebar item for "Draft Pages"
- CFPB/hubcap wiki on GHE – for …
=> Create new report for draft pages

cfgov/login/tests/test_auth_forms.py
Luv the demo email, but it's possibly a malicious site, so we should likely always use `example.com` for example domains, lest it seem like we're promoting shady domains.
- Change test example email address. 
=> Update test_auth_forms.py example email address

cfgov/v1/jinja2/v1/layouts/base.html
(This PR is to the upgrade/wagtail4 branch.)
The base template includes duplicate code about the preview panel:
https://github.com/cfpb/consumerfinance.gov/blob/4f927a4abce7eef3bb4418d6b3a59613468024c5/cfgov/v1/jinja2/v1/layouts/base.html#L59-L62
and
https://github.com/cfpb/consumerfinance.gov/blob/4f927a4abce7eef3bb4418d6b3a59613468024c5/cfgov/v1/jinja2/v1/layouts/base.html#L106-L109
We only need one of these.
To test, preview a page in the Wagtail 4 sidebar and verify that links still open in a new tab.
=> Remove duplicate `<base>` tag in base template

cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py
Currently users who don't have permission to access the Django admin (i.e. non-staff users) still see a "Django Admin" link in the Wagtail sidebar, which points to /django-admin/.
If those users click on that link, they get stuck in an infinite redirect loop: /django-admin/ bumps them to the Wagtail login with a ?next parameter, Wagtail sees that they're already logged in, and sends them back the Django admin, etc.
It doesn't seem easy/possible to avoid that infinite loop unfortunately. The best we can do is hide the Django admin link for those users, which is what this PR does.
=> Hide Django admin link from non-staff users

cfgov/apache/conf.d/headers.conf
see https://developer.mozilla.org/en-US/docs/web/http/headers/x-xss-protection and https://owasp.org/www-project-secure-headers/#x-xss-protection
=> Remove deprecated X-XSS header

cfgov/prepaid_agreements/jinja2/prepaid_agreements/search_results.html, cfgov/unprocessed/css/search.less
Prepaid agreements uses a customized expandable for its filter sections. It should be refactored in the future to use an dedicated expandable facet pattern (see https://github.com/cfpb/design-system/pull/1628)
- Move prepaid agreement `filter-section`s into expandable group
1. Visit http://localhost:8000/data-research/prepaid-accounts/search-agreements/ and compare to https://www.consumerfinance.gov/data-research/prepaid-accounts/search-agreements/ 
There will be some minor spacing differences, especially noticeable with the focus rectangle. Also, the existing filters have a bug where the checkboxes briefly touch the label when closing. That should be fixed.
Before:
After:
=> Move prepaid agreement `filter-section`s into expandable group

cfgov/v1/jinja2/v1/includes/organisms/footer.html
The page "No FEAR Act" has been updated and renamed [No FEAR Act & Cummings Act](https://www.consumerfinance.gov/office-civil-rights/no-fear-act-cummings-act/). This PR modifies the footer link to reflect that change.
---
- Footer link updated
1. localhost
2. View footer on any page
=> Updating No FEAR Act footer link and label

cfgov/v1/jinja2/v1/layouts/base.html
Missing space in `{{ js}}` variable reference, introduced in 3cbc597440e5fdf3c8ac8aa1e8ba7f61212ce183.
=> Minor fix to base template spacing

cfgov/v1/models/base.py, cfgov/v1/tests/models/test_base.py
Translation links are currently broken when you use the Wagtail 4+ live preview panel to preview new pages that have never been saved. A translation link is shown for almost every page on the site. This is because the current logic doesn't properly handle the case where a page's primary key is null.
This commit fixes that logic, while still ensuring that the links render properly both for new English and non-English pages.
Fixes internal D&CP#230.
Create a new page in Wagtail using a type that would show translation links, for example a BrowseFilterablePage. Fill in all the required fields but don't hit save yet. Open the live sidebar panel and note that the translation links don't appear.
Now set the page's language to something other than English, and select an English page. Still don't …
=> Fix translation links when previewing new pages

cfgov/v1/management/commands/publish_pages.py, cfgov/v1/wagtail_hooks.py
Wagtail 4.0 renamed the `get_latest_revision_as_page` method to `get_latest_revision_as_object`; the old name still exists for backwards compatibility, but will be removed in Wagtail 5:
https://docs.wagtail.org/en/stable/releases/4.0.html#page-get-latest-revision-as-page-renamed-to-page-get-latest-revision-as-object
We have a couple of references to the old name, which generate a warning when running tests. This commit renames them.
=> Update `get_latest_revision_as_page` calls

cfgov/unprocessed/apps/regulations3k/css/reg-pagination.less
I can't find references to these classes outside of the less files (both in file search and search of the crawler).
- iRegs: remove `application-footer` and `landing-footer` CSS classes
1. No change to iRegs browser.
=> iRegs: Remove `application-footer` and `landing-footer` CSS classes

cfgov/unprocessed/apps/form-explainer/css/form-explainer.less
Expandables changed their designator to when they are open from a class modifier to a data-open attribute in https://github.com/cfpb/design-system/pull/1600, but an override for this was missed in the form explainers.
- Update form explainers expandable expanded override.
1. Visit http://localhost:8000/owning-a-home/loan-estimate/ and see there's no double line when the form explainer expandables are opened.
Before:
After:
=> Form explainers: Update to fix issue with expandable overrides

cfgov/unprocessed/apps/regulations3k/css/reg-navigation.less
This fixes the hidden secondary nav icons till the iregs secondary nav can be overhauled and untangled from expandables.
- iRegs: Add temporary CSS to fix hidden icons on secondary navigation. 
1. visit http://localhost:8000/rules-policy/regulations/1002/ and resize to mobile and there should be an expand/collapse icon on the secondary navigation.
Before:
After:
=> iRegs: Temp fix for missing icons

docs/atomic-structure.md, docs/feature-flags.md
The whole atomic structure docs needs revisiting, but this fixes some obvious erroneous examples.
- Fix dead header.html link by converting it to a permalink.
- Fix some example markup to align with the current codebase.
=> Update docs: update outdated expandable and banner code

docs/installation.md
This is a handy way to not have to `pynev activate …` every time you refresh your Terminal.
- Add pyenv `local` setting to installation instructions.
=> Add pyenv local setting to installation instructions

cfgov/unprocessed/apps/filing-instruction-guide/css/main.less
I couldn't find references to this CSS in the codebase or in the crawler. 
- FIG: Remove unused CSS
1. http://localhost:8000/data-research/small-business-lending/filing-instructions-guide/2024-guide/ should be unchanged.
=> FIG: Remove unused CSS

cfgov/unprocessed/apps/filing-instruction-guide/css/main.less
This expandable override needs to be updated to the latest expandable expanded code.
- FIG: update expandable CSS
1. http://localhost:8000/data-research/small-business-lending/filing-instructions-guide/2024-guide/ and resize to mobile and expand menu and scroll down.
=> FIG: update expandable CSS to fix mobile scrolling issue

cfgov/prepaid_agreements/jinja2/prepaid_agreements/index.html, cfgov/unprocessed/apps/prepaid-agreements/css/main.less, cfgov/unprocessed/apps/prepaid-agreements/js/common.js, esbuild/scripts.js
Not totally sure how this was working before, but the expandables aren't initialized. This PR adds a script to initialize them.
- Add prepaid script to initialize expandable group.
1. Compare filter expandables in http://localhost:8000/data-research/prepaid-accounts/search-agreements/ vs https://www.consumerfinance.gov/data-research/prepaid-accounts/search-agreements/
Before:
After:
=> Prepaid credit card agreements: Add JS initialization script

cfgov/wagtailadmin_overrides/static/css/global.css
This change updates our env label for Wagtail’s new sidebar. Instead of sitting on top of the sidebar, it now sits beside the collapse button, and will move with the sidebar to collapse.
It still appears across the top on mobile, but now it appears dimensionally the same as the sidebar button.
Much of this is based on the Wagtail admin's CSS and conforming to that.
On desktop expanded:
On desktop collapsed:
On mobile:
=> Fix our env label with Wagtail's new sidebar

cfgov/unprocessed/css/organisms/form.less
This forms CSS appears to be added in https://github.com/cfpb/consumerfinance.gov/pull/1273 and is no longer used.
I can't find these classes in a codebase search or in the crawler.
- Removed unused CSS: `o-form-description`, `o-form-section`, `o-form-actions`.
=> Remove unused forms CSS

cfgov/form_explainer/jinja2/form-explainer/blocks/explainer.html, cfgov/jinja2/rural-or-underserved/_templates/expandable.html, cfgov/jinja2/rural-or-underserved/index.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/macros/financial-item-expandable.html, cfgov/regulations3k/jinja2/regulations3k/inline_interps.html, cfgov/regulations3k/jinja2/regulations3k/regulations3k-secondary-navigation.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/form-page.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-3-5.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-6-8.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/survey/results-9-12.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/tdp_expandable.html, cfgov/unprocessed/css/organisms/secondary-navigation.less, cfgov/v1/jinja2/v1/includes/organisms/expandable.html, cfgov/wellbeing/jinja2/wellbeing/results.html, test/unit_tests/apps/filing-instruction-guide/fixtures/sample-fig-page.js, test/unit_tests/apps/financial-well-being/js/fwb-results-spec.js, test/unit_tests/apps/teachers-digital-platform/html/results-page-analytics.js, test/unit_tests/apps/teachers-digital-platform/html/results-page.js, test/unit_tests/apps/teachers-digital-platform/html/shared-results-page-analytics.js, test/unit_tests/apps/teachers-digital-platform/html/survey-page-analytics.js, test/unit_tests/apps/teachers-digital-platform/html/survey-page.js, test/unit_tests/apps/teachers-digital-platform/js/expandable-facets-spec.js, test/unit_tests/apps/teachers-digital-platform/js/expandable-mobile-spec.js, test/unit_tests/apps/teachers-digital-platform/js/search-spec.js, test/unit_tests/apps/teachers-digital-platform/js/tdp-analytics-spec.js, test/unit_tests/js/organisms/FilterableListControls-spec.js
Lighthouse reports that the icons that have `aria-label`s need the proper aria role. This PR adds a `role="img"` on the icons.
- Add role="img" on expandable icons.
1.  Visit localhost:8000/about-us/blog/ and run lighthouse in the browser dev tools. Compare to production. Accessibility score should be higher.
=> Fix aria role on expandable icons

cfgov/unprocessed/css/enhancements/forms.less
The line in the scale on the financial well-being tool is slightly off and sticks out of the left-hand radio button. 
- Financial well-being: Adjust the line through the scale.
1. Visit http://localhost:8000/consumer-tools/financial-well-being/ and compare the line behind the radio buttons to the version on production.
Before:
After:
=> Fix Financial well-being scale

cfgov/unprocessed/css/on-demand/event.less
The markup for this class was removed in https://github.com/cfpb/consumerfinance.gov/pull/2139
- Remove `event-status_rsvp` class
=> Remove `event-status_rsvp` class

cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/unprocessed/css/molecules/form-field-with-button.less, test/cypress/integration/consumer-tools/find-a-housing-counselor/find-a-housing-counselor-helpers.cy.js
I can't find `m-form-field-with-button__inline-info` in the codebase or crawler.
`m-form-field-with-button_wrapper` only appears in the markup and has no styling. 
This PR removes both.
- FAHC: Remove `m-form-field-with-button__inline-info` and `m-form-field-with-button_wrapper`.
- Adds `data-cy="btn-fahc-submit"` for Cypress test.
1. PR checks should pass. http://localhost:8000/find-a-housing-counselor/ should be unchanged vs production.
=> FAHC: Remove `m-form-field-with-button__inline-info` and `m-form-field-with-button_wrapper`

cfgov/unprocessed/apps/regulations3k/css/reg-navigation.less
With flexbox in use in the expandable header, these settings do not appear to be needed.
- iRegs: Remove expandable width settings
1. Compare the secondary nav expandable icon positioning in e.g. http://localhost:8000/rules-policy/regulations/1002/ vs production
=> iRegs: Remove expandable width settings

test/unit_tests/apps/financial-well-being/js/fwb-results-spec.js
The financial well-being unit test had a `TODO` for `Add aria pressed states to cf-expandables`, however, [aria-pressed](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed) does not appear to be appropriate for expandables, so I have removed the todo.
- Financial Well-Being: Update fwb-results-spec.js expandables to enable skipped test
=> Financial Well-Being: Update fwb-results-spec.js expandables to enable skipped test

cfgov/unprocessed/js/modules/util/scroll.js
`window.requestAnimationFrame` has a good level of support https://caniuse.com/requestanimationframe, and browsers that don't support it should get the no-js experience anyway.
- Form Explainer: Remove older requestAnimationFrame fallbacks
1. Form explainers like http://localhost:8000/owning-a-home/loan-estimate/ should scroll when clicking around the image map.
=> Form Explainer: Remove older requestAnimationFrame fallbacks

cfgov/unprocessed/apps/regulations3k/js/permalinks-utils.js
Fixes https://github.local/Design-Development/External-Products/issues/129
- Go to an ireg
- Note that hidden expandables aren't being included in the wayfinder
=> Check for hidden attribute instead of class in regs3k

.github/workflows/backend.yml, .github/workflows/filter-backend.yml, .github/workflows/filter-frontend.yml, .github/workflows/frontend.yml
Paths filtering doesn't actually work on `merge_group`. When this was added to the actions, it broke the paths filtering since the `paths` key became a subkey of `merge_group` instead of `pull_request`. This fixes that.
=> Fix paths filtering

cfgov/unprocessed/css/organisms/sidebar-breakout.less
`u-centered-on-mobile` was removed in https://github.com/cfpb/consumerfinance.gov/pull/7621/, but these inclusions in a code comment were missed.
- Remove `u-centered-on-mobile` from code comment
=> Remove `u-centered-on-mobile` from code comment

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/09-make-a-plan.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/12-affording-your-loan.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/macros/financial-item-flyout.html, cfgov/paying_for_college/jinja2/paying-for-college/college-costs.html, cfgov/unprocessed/apps/paying-for-college/css/college-costs/college-costs.less, cfgov/unprocessed/apps/paying-for-college/css/college-costs/financial-item.less, cfgov/unprocessed/apps/paying-for-college/css/college-costs/vars.less, cfgov/unprocessed/apps/paying-for-college/js/college-costs/CostsGroup.js, cfgov/unprocessed/apps/paying-for-college/js/college-costs/views/app-view.js
A change in `cf-expandables` broke customization in the Financial Path tool, and @anselmbradford generously gave us guidance on how to fix this so that we weren't dependent on the `cf-expandables` pattern (which should not be customized). 
- remove references to `cf-expandables`
- Change class names
- Update JS, including adding 
1. Generally, the "expandables" in the Covering Your Costs > Make a Plan section of the app should look better!
2. All features of the application should function as before.
-
- [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) …
=> Paying for College - Move expandable code to flyout code

cfgov/v1/jinja2/v1/includes/templates/render_block.html, cfgov/v1/jinja2tags/__init__.py
Commit 11c6b8dfe86032bb4eea9c9e7f54cce0de3da509 introduced a bug where legacy page content wasn't being rendered properly (tracked internally at D&CT#241).
This commit tries to fix that and simplifies our unnecessarily custom render_stream_child logic. We have this custom logic because we have historically supported raw HTML tags in any Wagtail text or rich text field. Ideally we could remove this in future.
Verify that all of these pages render properly:
- http://localhost:8000/about-us/blog/join-us-in-making-mortgage-shopping-easier/
- http://localhost:8000/about-us/newsroom/consumer-financial-protection-bureau-releases-report-on-issues-facing-users-of-international-money-transfers/
- http://localhost:8000/about-us/careers/current-openings/
- …
=> Simplify Wagtail block unescaping logic

cfgov/v1/templates/v1/_list_page_drafts.html, cfgov/v1/views/reports.py
This PR adds a field to the new "Draft Pages" report for the first publishing date, allowing drafts to be filtered by whether they have ever been published.
---
- `first_published_at` field captured and rendered in Draft report
1. localhost
2. `/admin/reports/page-drafts/`
3. See that new field is visible both on rendered page and on CSV export
=> Add "first published" field to draft report

cfgov/v1/forms.py
Commit 19e69581d2614fe6a2c5dff1485a6d1564c11725 introduced a new search aggregation for filterable lists to optimize computation of the earliest post date in search results. Because of the way we use Django caching as part of filterable search, this logic had to be deployed incrementally such that existing cache values would work even without having the aggregation value.
This code has been deployed and the cache has been cleared in all environments; thus, the fallback logic can now be removed. This change does so.
Search a filterable list providing an end date but not a start date (example: http://localhost:8000/about-us/blog/?title=&from_date=&to_date=2023-05-17) and confirm that the start date gets set to the earliest post date.
=> Cleanup unnecessary filterable list logic

cfgov/v1/jinja2/v1/browse-filterable/index.html
Will you look at that. Six years ago `prefooter` was updated to `o-prefooter` in https://github.com/cfpb/consumerfinance.gov/pull/2787, however, the browse-filterable/index.html reference was missed, so all this time prefooters on those pages (62 pages) had an unstyled prefooter. 
This was pointed out in https://github.com/cfpb/consumerfinance.gov/pull/2787#issuecomment-285480919, but looks like the loop didn't get closed.
- Fix `prefooter` reference in browse-filterable/index.html to be `o-prefooter`
1. Visit a browser-filterable page, such as localhost:8000/rules-policy/final-rules/ or localhost:8000/administrative-adjudication-proceedings/administrative-adjudication-docket/ and scroll to the prefooter at the bottom.
Before:
After:
Before:
After:
=> Fix `prefooter` reference in browse-filterable/index.html

cfgov/v1/jinja2/v1/browse-filterable/index.html, cfgov/v1/jinja2/v1/campaign_page.html, cfgov/v1/jinja2/v1/newsroom/index.html, cfgov/v1/jinja2/v1/story_page.html
Most templates collapse the whitespace on the loop `for block in page.header`. This PR adds this for the four templates that weren't, for consistency across the codebase.
- Collapse whitespace for four templates that weren't in their `for block in page.header` loop.
1. These pages should be unchanged (Note: omitted campaign pages, because they are unused):
- http://localhost:8000/about-us/newsroom/
- http://localhost:8000/rules-policy/final-rules/
- http://localhost:8000/about-us/racial-equity/
=> Minor cleanup to collapse whitespace on  `for block in page.header` loop

cfgov/v1/jinja2/v1/layouts/content-base.html, cfgov/v1/jinja2/v1/layouts/layout-2-1-rtl.html
The `post_content` block does not appear to ever be overridden. 
- The `post_content` block in `content_base.html` and `layout-2-1-rtl.html`.
=> Remove `post_content` block

cfgov/v1/templates/v1/_list_page_preview_fields.html, cfgov/v1/templates/v1/page_preview_fields_report.html, cfgov/v1/tests/views/test_reports_view.py, cfgov/v1/views/reports.py, cfgov/v1/wagtail_hooks.py
This commit adds a new Page Preview Fields report in Wagtail that lists all AbstractFilterPages in the main site that have non-empty page preview fields (`preview_title`, `preview_subheading`, `preview_description`).
See internal D&CP#234 for context.
To access the new report, visit http://localhost:8000/admin/reports/page-preview-fields/.
=> Add new Page Preview Fields report

cfgov/unprocessed/apps/teachers-digital-platform/js/ClearableInput.js, test/unit_tests/apps/regulations3k/js/permalinks-utils-spec.js, test/unit_tests/apps/regulations3k/js/search-spec.js, test/unit_tests/apps/teachers-digital-platform/js/expandable-facets-spec.js, test/unit_tests/apps/teachers-digital-platform/js/survey/grade-level-page-analytics-spec.js, test/unit_tests/apps/teachers-digital-platform/js/survey/results-page-analytics-spec.js, test/unit_tests/apps/teachers-digital-platform/js/survey/shared-results-page-analytics-spec.js, test/unit_tests/apps/teachers-digital-platform/js/survey/survey-page-analytics-spec.js, test/unit_tests/apps/teachers-digital-platform/js/tdp-analytics-spec.js, test/util/simulate-event.js
Event.initEvent is deprecated and should be replaced with creating event instances directly. 
- Migrate Event.initEvent to native event creation
1. `yarn jest` should pass.
2. http://localhost:8000/consumer-tools/educator-tools/youth-financial-education/teach/activities/ search clear button should still work.
=> Migrate Event.initEvent to native event creation

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html, cfgov/unprocessed/apps/regulations3k/css/reg-wayfinder.less, test/unit_tests/apps/regulations3k/js/permalinks-utils-spec.js
The iRegs wayfinder includes its own component organism `o-regulations-wayfinder`. Inside this component, the layout is handled by `content_wrapper`, `content_main`, and `content_sidebar` to align the left/right columns with the rest of the page layout. However, these classes have styles specific to the page layout, so `o-regulations-wayfinder` overrides styles of these classes, which it should not do (outside of margin adjustments). Additionally, it mixes in `content__flush-top content__flush-bottom`, which is fine, but the combined mixing of utility classes and overrides makes this brittle. 
This PR rewrites the wayfinder to handle its own layout and not depend on external layout classes.
Additionally, the wayfinder contained two classes `o-regulations-wayfinder__content` and …
=> iRegs: refactor wayfinder to fix customizations and BEM

cfgov/v1/tests/models/test_story_page.py
The StoryPage breadcrumbs test added in commit defb5e59415a10a1ec176a47f15a1cb4c8925199 introduced a warning to our Python unit tests:
```
BytesWarning: str() on a bytes instance
self.assertNotIn("breadcrumbs_text", str(response.content))
```
This commit fixes that warning by using Django's built-in [`assertNotContains`](https://docs.djangoproject.com/en/4.2/topics/testing/tools/#django.test.SimpleTestCase.assertNotContains) on the page render response.
[Run our Python tests](https://cfpb.github.io/consumerfinance.gov/python-unit-tests/#running-tests) and observe that this warning no longer appears when compared to running them against the `main` branch.
=> Fix warning from StoryPage breadcrumbs test

cfgov/ask_cfpb/documents.py, cfgov/ask_cfpb/tests/test_documents.py
We currently index PortalSearchPages into OpenSearch so they can be searched on pages like
https://www.consumerfinance.gov/consumer-tools/auto-loans/answers/basics/
The "autocomplete" field in the search index actually represents the page title. This is currently indexed as a text field so that fuzzy searches work against it.
But we also want to index this same title as a keyword field so that we can sort on the field, i.e. so that search results can be shown in alphabetical order.
This commit makes a change to the way this field is indexed so that it gets indexed both as a text field AND as a keyword field (under the name "raw").
A subsequent change will actually use this new field to add alphabetical ordering; this needs to be done in two steps so that we first ensure that all live …
=> Add keyword field index to PortalSearchPages

requirements/wagtail.txt
4.1.5 release notes: https://docs.wagtail.org/en/stable/releases/4.1.5.html
4.1.6 release notes: https://docs.wagtail.org/en/stable/releases/4.1.6.html
The change of most interest to us here is "Ensure that copying page correctly picks up the latest revision"; this fixes https://github.com/wagtail/wagtail/issues/10393 which I filed due to our internal D&CT#232.
=> Bump Wagtail version from 4.1.4 to 4.1.6

cfgov/search/elasticsearch_helpers.py, cfgov/v1/tests/test_documents.py, cfgov/v1/tests/test_filterable_list_form.py
Some of our search tests currently use `time.sleep()` to try to ensure that the search index updates after some operation in the test. This commit removes these sleeps by improving the way we patch the OpenSearch library so that updates always take effect immediately.
All tests should continue to pass successfully, just a bit faster.
=> Optimize search tests that use `time.sleep()`

cfgov/cfgov/settings/test.py, cfgov/core/testutils/runners.py, requirements/test.txt
This PR adds the [django-slowtests](https://github.com/realpython/django-slow-tests) package to our Python test environment so that we can measure and report how long our Python tests take to run. Running Python tests (via `tox` or some other method) will now always report the 10 slowest tests:
```
10 slowest tests:
4.9607s test_index_reflects_page_moves_and_deletions (v1.tests.test_documents.TestThatWagtailPageSignalsUpdateIndex)
4.2827s test_page_matches_categories (v1.tests.models.test_browse_filterable_page.TestNewsroomLandingPage)
4.2764s test_page_in_other_site_not_included (v1.tests.models.test_browse_filterable_page.TestNewsroomLandingPage)
4.2064s test_no_pages_matching_categories (v1.tests.models.test_browse_filterable_page.TestNewsroomLandingPage)
3.4575s …
```
=> Always report slowest Django tests

cfgov/search/elasticsearch_helpers.py, cfgov/search/management/commands/es_health.py, cfgov/search/tests/management/commands/test_es_health.py, cfgov/teachers_digital_platform/models/activity_index_page.py, cfgov/v1/documents.py, requirements/libraries.txt
This commit bumps the version of the opensearch-py package from 1.1.0 to [2.2.0](https://github.com/opensearch-project/opensearch-py/releases). This allows us to remove our dependence on opensearch-dsl, which was incorporated into opensearch-py in the latest version.
It also bumps the version of the django-opensearch-dsl from 0.4.1 to [0.5.1](https://github.com/Codoc-os/django-opensearch-dsl/releases).
All unit and functional tests continue to pass with these upgrades.
=> Upgrade OpenSearch-related libraries

cfgov/hmda/jinja2/hmda/hmda-explorer.html
For some reason this page moves the table -20px through a hardcoded negative margin.
If we want this, we could roughly approximate it by adding `block__flush-bottom block__padded-bottom` to the preceding sibling container, or clear the preceding sibling with `block__flush-bottom` and then add `u-mt20` to the table. But either way doesn't seem worth it.
- HMDA: Remove hardcoded negative margin
1. Visit https://www.consumerfinance.gov/data-research/hmda/historic-data/ and compare the table position to https://localhost:8000/data-research/hmda/historic-data/
Before:
After:
=> HMDA: Remove hardcoded negative margin

cfgov/v1/jinja2/v1/blog/blog_page.html
The hardcoded RSS feed was set to `block__sub`, but this only has an affect when it is alone on the page. It should be `block__flush-top` in that case, so that it top-aligns with the page's heading text.
- Replace `block__sub` with `block__flush-top` in rss module for blog pages
1. Visit http://localhost:8000/about-us/blog/how-help-homeowners-protect-their-homes-ar/ and compare to https://www.consumerfinance.gov/about-us/blog/how-help-homeowners-protect-their-homes-ar/  and see that the rss module is further up.
Before:
After:
=> Replace `block__sub` with `block__flush-top` in rss module for blog pages

cfgov/unprocessed/css/enhancements/layout-1-3.less, cfgov/unprocessed/css/enhancements/layout-base.less
The RTL layout-2-1 layouts (such as https://www.consumerfinance.gov/about-us/blog/avoid-covid-19-government-imposter-scams-ar/) have a major bug at mobile where the grid layout is not being configured, so all blocks are overlapping on top of each other. This PR fixes this by moving a default mobile layout to the layout-base.less file.
- Layouts: Move default mobile layout to the layout-base.less file.
1. At mobile, compare https://www.consumerfinance.gov/about-us/blog/avoid-covid-19-government-imposter-scams-ar/ to https://localhost:8000/about-us/blog/avoid-covid-19-government-imposter-scams-ar/
Before: 😬😬😬😬😬
After:
- Ignore breadcrumb indent for now.
=> Bugfix: Set mobile layout in layout-base to fix overlapping mobile layout

cypress.config.cjs
Screenshots on failure were disabled in https://github.com/cfpb/consumerfinance.gov/pull/6303, perhaps because it was causing issues in Jenkins. However, let's try it out again.
- Cypress: Enable screenshots on failure
=> Cypress: Enable screenshots on failure

test/cypress/integration/compliance/small-business-lending/filing-instruction-guide.cy.js
This change skips a test that is failing occasionally internally until we can fix the test/cause of the flakiness.
=> Skip flaky FIG test on mobile

cfgov/unprocessed/css/breadcrumbs.less, cfgov/unprocessed/css/enhancements/layout-1-3.less, cfgov/unprocessed/css/enhancements/layout-2-1.less
- Adjust margin of breadcrumbs across templates to align with main content area text.
- Remove margin on RTL page hero at mobile.
1. `yarn build` and visit the following pages and resize to mobile and see that the breadcrumb aligns with the content text and/or the C in the logo CFPB.
RTL layout-2-1 page with breadcrumbs:
http://localhost:8000/about-us/blog/hidden-cost-junk-fees-ar/
LTR layout-2-1 page with breadcrumbs:
http://localhost:8000/rules-policy/rules-under-development/registry-of-nonbank-covered-persons-subject-to-agency-court-orders/
http://localhost:8000/consumer-tools/educator-tools/library-resources/program-ideas/money-as-you-grow-bookshelf/get-word-out-patrons/
RTL layout-1-3 with breadcrumbs:
http://localhost:8000/language/ar/coronavirus/mortgage-and-housing-assistance/help- …
=> Margin adjustments for breadcrumbs and hero

test/cypress/integration/components/header/header.cy.js
This test is flaky and often fails in CI when it expects the animation class to be absent and it is still present. This PR swaps the order of the test checks to first check that the global search is not visible and then checks that the animation class is absent.
=> Header.cy.js: Swap order of globalsearch checks

cfgov/ask_cfpb/models/search.py, cfgov/ask_cfpb/tests/test_search.py
Currently the results on PortalSearchPages like https://www.consumerfinance.gov/consumer-tools/auto-loans/answers/basics/ default to a random order if the user hasn't entered a search query.
If they do enter a search query, the results are sorted by search relevance (the default behavior of OpenSearch, using the `_score` field).
This commit changes the default sort order to be alphabetical.
1. You'll need to reindex your search index, either with a fresh `./refresh-db.sh` or just by running [these two commands](https://github.com/cfpb/consumerfinance.gov/blob/6311c9d4be9f6cf8cff390b234edf7879b4045b1/refresh-data.sh#L73-L74) manually.
2. Visit http://localhost:8000/consumer-tools/auto-loans/answers/basics/ and observe alphabetical sorting.
3. Do a search, for example …
=> Default PortalSearchPage results to alphabetical

cfgov/ask_cfpb/migrations/0001_squashed_0047_add_use_json_field_to_streamfields.py, cfgov/data_research/migrations/0001_squashed_0003_delete_conferenceregistration.py, cfgov/filing_instruction_guide/migrations/0001_squashed_0011_add_use_json_field_to_streamfields.py, cfgov/filing_instruction_guide/migrations/0012_remove_content_image_bleed_option.py, cfgov/form_explainer/migrations/0001_squashed_0006_add_use_json_field_to_streamfields.py, cfgov/form_explainer/migrations/0007_remove_content_image_bleed_option.py, cfgov/hmda/migrations/0001_initial.py, cfgov/jobmanager/migrations/0001_squashed_0020_hourly_salary.py, cfgov/paying_for_college/migrations/0001_squashed_0018_add_use_json_field_to_streamfields.py, cfgov/paying_for_college/migrations/0019_remove_content_image_bleed_option.py, cfgov/regulations3k/migrations/0001_squashed_0036_add_use_json_field_to_streamfields.py, cfgov/regulations3k/migrations/0037_remove_content_image_bleed_option.py, cfgov/teachers_digital_platform/migrations/0001_squashed_0005_add_use_json_field_to_streamfields.py, cfgov/v1/migrations/0001_squashed_0235_add_use_json_field_to_streamfields.py, cfgov/v1/migrations/0236_case_docket_table.py, cfgov/v1/migrations/0242_filterable_list_topics.py
This PR includes two unrelated fixes to our Django migration files:
1. In previous attempts to squash our migrations, we neglected to remove a few references to the old migration names. Per [the Django docs](https://docs.djangoproject.com/en/4.2/topics/migrations/#squashing-migrations) we need to
> Updating all migrations that depend on the deleted migrations to depend on the squashed migration instead.
but it seems like we missed a few of these.
A way to check this is to try running something like
```
cfgov/manage.py sqlmigrate v1 0001
```
which is supposed to dump out the SQL for a migration; this won't work on main because of these bad references.
2. The v1 0242 migration does a StreamField data migration and depends on some Wagtail 4.x changes (specifically, that revision data is …
=> Migration fixes

cfgov/v1/jinja2/v1/includes/atoms/checkbox.html, cfgov/v1/jinja2/v1/includes/atoms/radio-button.html
Commit 269c54c842debd5cf9d767377b4e7ee5b377dc8e broke some uses of slugify in Jinja templates. Previously you could call slugify in templates as a function, e.g. `slugify(value)` but it's actually only available in the global Jinja context as a filter, e.g. `value | slugify`.
This PR fixes those incorrect uses.
To test: http://localhost:8000/consumer-tools/educator-tools/buying-a-car/
This fails on main but works properly with this PR.
=> Fix incorrect template use of slugify

cfgov/v1/jinja2/v1/includes/organisms/post-preview-snapshot.html
Commit 2f7168072262c4943443f53aa3d8310853bd2925 broke the template for the PostPreviewSnapshot module. This fixes that.
To test, visit this page that contains a PPS:
http://localhost:8000/compliance/amicus/
=> Fix Post Preview Snapshot template

cypress.config.cjs
This commit adds some domains to Cypress' `blockHosts` setting so that we don't load third-party scripts when running functional tests.
I sourced these domains from [our list in Django base settings](https://github.com/cfpb/consumerfinance.gov/blob/867fcac24e2433ef637b826828f1f564b70741f0/cfgov/cfgov/settings/base.py#L514-L535).
=> Add domains to Cypress ignore list

cfgov/unprocessed/js/organisms/FormSubmit.js, test/unit_tests/js/organisms/FormSubmit-spec.js
- i18n: Add getMessages method to FormSubmit for retrieving Form success and error messages
1. `yarn jest` should pass.
1. Visit an english page and it should be in english (e.g. http://localhost:8000/about-us/newsroom/cfpb-takes-action-against-two-companies-for-charging-illegal-debt-relief-fees/)
2. Visit a non-english page and sign up with an example email in the sidebar and see that the success message is in the language of the page:
http://localhost:8000/language/ar/
http://localhost:8000/language/vi/
http://localhost:8000/language/ht/
http://localhost:8000/language/zh/
http://localhost:8000/language/ru/
http://localhost:8000/language/ko/
http://localhost:8000/language/tl/
Before:
After:
=> i18n: Add getMessages method to FormSubmit for retrieving Form success and error messages

cfgov/unprocessed/apps/rural-or-underserved-tool/css/main.less
The SVG in the "show map" toggle was preventing clicks of the toggle. This PR adds CSS to hide it from interactivity. 
See https://[GHE]/CFGOV/platform/issues/4314
- Add CSS to hide show map SVG from interactivity. 
1. Visit http://localhost:8000/rural-or-underserved-tool/ and enter some addresses. Click the show/hide map in the result table. Clicks to the SVG should toggle. Compare to production where clicks to the SVG do not toggle.
=> ROUT: Prevent jsLoadMap SVG from preventing clicks of the "Show map" toggle

cfgov/ask_cfpb/jinja2/ask-cfpb/answer-page.html
The use of tags.html was removed from this file in commit 7d4745ca04130653d103c624ca75d55524c7ef22.
=> Remove unnecessary tags.html and notification.html inclusion

cfgov/unprocessed/css/main.less
See https://[GHE]/Design-Development/Design-and-Content-Team/issues/175
- Swap Arial and Avenir order in font-family on Vietnamese pages.
1. Visit http://localhost:8000/language/vi/ and see that Vietnamese characters do not have differing bolding.
=> Swap font-family order on Vietnamese pages

cfgov/unprocessed/apps/paying-for-college/css/cf-theme-overrides.less, cfgov/v1/jinja2/v1/includes/macros/category-slug.html
The three files that make calls to this macro do not use the `classes` and `use_blog_category` arguments:
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/activity-log/_activity-list.html#L22-L31
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/includes/organisms/item-introduction.html#L39
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/includes/organisms/post-preview.html#L79
- Category slug: remove `classes` and `use_blog_category` arguments.
- `@category-slug-text` and `@category-slug-hover` are not found in the codebase.
=> Category slug: remove `classes` and `use_blog_category` arguments

cfgov/prepaid_agreements/jinja2/prepaid_agreements/search_result_item.html, cfgov/regulations3k/jinja2/regulations3k/regulations3k-search-result-item.html, cfgov/unprocessed/css/molecules/tags.less, cfgov/unprocessed/css/organisms/post-preview.less, cfgov/v1/jinja2/v1/events/_event-detail.html, cfgov/v1/jinja2/v1/includes/article.html, cfgov/v1/jinja2/v1/includes/organisms/post-preview.html, cfgov/v1/jinja2/v1/includes/tags.html
iRegs search has tags in the search results, but unlike elsewhere they are not links. https://github.com/cfpb/consumerfinance.gov/pull/7831 assumed topic tags would be links, so provided a hover state, which is erroneously shown on iregs topic tags. This PR refactors the tags macro to support both links and not for tags.
- Refactor tags macro to support tag links or not.
- Update iregs search topic tags to use tags macro.
1. Visit the following pages and hover the topic tags and resize to mobile and hover:
http://localhost:8000/rules-policy/regulations/search-regulations/results/?q=mortgage&regs=1002&regs=1003&results=25&order=relevance
http://localhost:8000/about-us/blog/we-are-extending-the-deadline-for-comments-about-data-brokers/ …
=> Refactor tags to support links and non-links | Make iregs search use tags macro

cfgov/unprocessed/apps/regulations3k/css/reg-search.less, cfgov/unprocessed/apps/retirement/css/claiming.less, cfgov/unprocessed/css/search.less
The active state for buttons in the retirement before you claim app are [this](https://www.color-hex.com/color/33578e), while the color for navy in the design system is [this](https://www.color-hex.com/color/254b87). So, it appears that navy was intended to be used here.
- Change bespoke color `#33578e` with `@navy` color variable.
- Update regs and prepaid cards search hardcoded colors with `@gray-5` variable.
1. Visit http://localhost:8000/consumer-tools/retirement/before-you-claim/, enter the tool, and click one of the question's buttons and to see the active state color.
Before:
After:
=> Retirement: Replace bespoke color with navy color variable | Update hardcoded gray-5 with variables

cypress.config.cjs, test/cypress/integration/admin/admin-helpers.cy.js, test/cypress/integration/admin/admin.cy.js, test/cypress/integration/components/pagination/pagination-helpers.cy.js, test/cypress/integration/paying-for-college/your-financial-path-to-graduation/financial-path-helpers.cy.js
I ran https://github.com/cypress-io/eslint-plugin-cypress on the tests and it flags to not chain further commands onto `cy` commands. It also flags having arbitrary waits, so I've tried removing them.
- Split chained `cy` commands into multiple commands.
- Remove arbitrary waits.
1. Cypress functional tests should pass.
=> Cypress: Do not chain further commands

cfgov/regulations3k/tests/test_models.py, cfgov/v1/wagtail_hooks.py
Ruff now correctly flags a line in `regulations3/test/test_models.py` where we have `# noqa: ` but do not specify an error or errors.
It also now correctly flags a call to `re.sub` that uses keyword arguments positionally.
=> Fix linting failures with latest Ruff

cfgov/v1/jinja2/v1/includes/blocks/heading.html
This change alters the template for the existing HeadingBlock so that the heading tag (e.g. `<h2>`) always gets an `id` attribute with a slugified version of the heading text.
This uses our existing `slugify_unique` method that avoids duplicate IDs by enforcing unique IDs for a single Django request. For example, if there are two headings with the same text ("Example"), the first will will be given the ID "example" and the second "example-1".
1. Locally visit the template debug view for the heading module at http://localhost:8000/admin/template_debug/v1/heading/, and inspect source to see the heading IDs.
2. Visit a page with headings like http://localhost:8000/consumer-tools/educator-tools/your-money-your-goals/toolkit/ and notice that headings have IDs, for example "Access the full …
=> Automatically assign IDs to rendered HeadingBlocks

requirements/libraries.txt
Upgrade wagtail-inventory version to latest release 2.1:
https://github.com/cfpb/wagtail-inventory/releases/tag/2.1
=> Bump wagtail-inventory from 2.0.0 to 2.1

cfgov/v1/forms.py
This commit fixes an issue with the Django cache logic used for filterable list results. Currently a cache is used to store both (a) the full set of search results for a page and (b) the list of page IDs from those search results.
There is an edge case in the current logic that can result in incorrect empty results or a blank list of topic options:
1. Assume the search index is empty to start, perhaps due to a manual refresh or due to some network or configuration issue.
2. A request to a filterable list page with an empty cache returns an empty list of results.
3. This gets stored in both caches as an empty list (`[]`).
4. Now assume the search index has been repopulated. This doesn't automatically reset the Django caches, unfortunately.
5. Subsequent requests will check the cache, and …
=> Fix: Properly refresh empty filterable list caches

cfgov/unprocessed/apps/find-a-housing-counselor/css/hud_print.css, cfgov/unprocessed/apps/find-a-housing-counselor/css/main.less
- Double colon pseudoelements
- Consolidate margin shorthand.
- Minor newline removal.
1. Visit http://localhost:8000/find-a-housing-counselor/ and compare to production. There should be no change.
- Double colon pseudoelements drops IE8 support.
=> FAHC: Adjust CSS | drop IE8 support

cfgov/unprocessed/apps/filing-instruction-guide/css/main.less
- Use double colon for pseudoelement.
- Consolidate margin shorthand.
- Use url syntax for import.
1. Visit http://localhost:8000/data-research/small-business-lending/filing-instructions-guide/2024-guide/ and compare to production. There should be no change. 
- Double colon for pseudoelement drops IE8 support.
=> FIG: Minor CSS cleanup

cfgov/unprocessed/apps/regulations3k/css/reg-navigation.less, cfgov/unprocessed/apps/regulations3k/css/reg-pagination.less, cfgov/unprocessed/apps/regulations3k/css/reg-search.less, cfgov/unprocessed/apps/regulations3k/css/reg-wayfinder.less
- Double colon pseudoelements to drop IE8 support
- Consolidate CSS shorthand
1. Compare http://localhost:8000/rules-policy/regulations/1002/ to production. It should be unchanged.
=> iRegs: Double colon pseudoelements to drop IE8 support | Consolidate CSS shorthand

cfgov/cfgov/settings/test.py, cfgov/v1/models/__init__.py, cfgov/v1/tests/models/test_snippets.py, cfgov/v1/tests/test_query.py, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/tests/util/test_migrations.py
Currently we use Wagtail's wagtail.test.testapp as part of our test settings in order to use some of its test models, for example SimplePage.
There's no need to use Wagtail's test models if we have a model that can work just as well. Additionally, there's an issue with the migrations for the testapp in Wagtail 4.2.4, and this avoids needing to deal with that -- see [wagtail#10724](https://github.com/wagtail/wagtail/issues/10724).
Theoretically we could maintain our own test models, for example using the method documented [here](https://docs.djangoproject.com/en/4.2/topics/testing/tools/#isolating-apps), but for now using our own models works just as well and avoids the dependency on Wagtail's testapp.
All tests should pass; there is no user-facing impact to this change.
=> Deprecate reliance on Wagtail's testapp

cfgov/unprocessed/css/organisms/video-player.less
- Double colon pseudoelements to drop IE8 support.
- Consolidate color values.
1. Visit http://localhost:8000/about-us/blog/addressing-racial-inequities-consumer-finance-markets/ and compare the video player to production. The timestamp (for example) should be unchanged.
You may need to be reload a few times to see the timestamp. This is purely an internal issue related to our network.
=> Video Player: Clean up CSS

cfgov/unprocessed/apps/prepaid-agreements/css/search-bar.less
- Prepaid agreements: Double colon pseudoelements to drop IE8 support
1. Compare http://localhost:8000/data-research/prepaid-accounts/search-agreements/ to production. It should be unchanged in regard to the search bar.
=> Prepaid agreements: Double colon pseudoelements to drop IE8 support

cfgov/unprocessed/apps/retirement/css/cf-enhancements.less, cfgov/unprocessed/apps/retirement/css/claiming.less
-  Drop browser prefixes 
-  Consolidate CSS shorthand
1. Compare http://localhost:8000/consumer-tools/retirement/before-you-claim/ to production. It should be unchanged.
=> Retirement: Drop browser prefixes | Consolidate CSS shorthand

cfgov/unprocessed/css/atoms/partially-styled-link.less, cfgov/unprocessed/css/calendar-icon.less, cfgov/unprocessed/css/enhancements/layout-2-1.less, cfgov/unprocessed/css/enhancements/typography.less, cfgov/unprocessed/css/misc.less, cfgov/unprocessed/css/molecules/global-search.less, cfgov/unprocessed/css/molecules/related-metadata.less, cfgov/unprocessed/css/on-demand/ask.less, cfgov/unprocessed/css/on-demand/error.less, cfgov/unprocessed/css/on-demand/event.less, cfgov/unprocessed/css/organisms/header.less, cfgov/unprocessed/css/organisms/mega-menu.less, cfgov/unprocessed/css/search.less
- Double colon pseudoelements to drop IE8 support.
- Drop units from CSS zero values
1. Visit an event in http://localhost:8000/about-us/events/ and compare to production. It should be unchanged.
=> Drop units from CSS zero values | Double colon pseudoelements to drop IE8 support

cfgov/unprocessed/apps/paying-for-college/css/cf-enhancements.less, cfgov/unprocessed/apps/paying-for-college/css/college-costs/college-costs.less, cfgov/unprocessed/apps/paying-for-college/css/college-costs/state-based.less, cfgov/unprocessed/apps/paying-for-college/css/disclosures.less, cfgov/unprocessed/apps/paying-for-college/css/print.css
See min-device-pixel-ratio guidance on https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-device-pixel-ratio
- Double colon pseudoelements.
- Consolidate `not` selector.
- Remove browser prefixes.
- Consolidate CSS rule shorthand.
1. Compare changes in http://localhost:8000/paying-for-college/your-financial-path-to-graduation/ to production. 
Compare changes in [the disclosures tool](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=154022&pid=BAHCA&totl=70950&tuit=14160&hous=7109&book=1150&tran=500&othr=4743&pelg=0&schg=&stag=&othg=&mta=&gib=&wkst=0&ppl=&parl=&perl=&subl=3500&unsl=6000&gpl=&prvl=&prvi=&prvf=&insl=&insi=&inst=&oid=4D0B9265B45716DF4B81EEB4BE117E1DF69871A …
=> Paying for College: Clean up CSS

cfgov/unprocessed/apps/ccdb-search/css/main.less
- CCDB: remove @tablet variable
- Use url syntax for import
1. `yarn build` and visit http://localhost:8000/data-research/consumer-complaints/search/ and resize to tablet and there should be no change from production in terms of left/right padding on `wrapper__match-content`.
=> CCDB: remove @tablet variable

cfgov/unprocessed/apps/know-before-you-owe/css/main.less
- KBYO: Remove browser prefixed box-sizing
1. Visit http://localhost:8000/know-before-you-owe/compare/ and compare to production. It should be unchanged.
=> KBYO: Remove browser prefixed box-sizing

cfgov/unprocessed/css/on-demand/mortgage-performance-trends.less, cfgov/unprocessed/css/on-demand/simple-chart.less
- Use url for imports.
- Consolidate CSS shorthand.
- Remove units for zero value.
1. Compare these charts to production and they should be unchanged.
http://localhost:8000/data-research/mortgage-performance-trends/mortgages-30-89-days-delinquent/
http://localhost:8000/data-research/research-reports/data-spotlight-medical-debt-among-older-adults-before-pandemic/full-report/
=> Charting: CSS consolidation

cfgov/privacy/tests/test_views.py, cfgov/privacy/urls.py
In November 2021 in commit 2007ac860ec7dfff0f94517f1a69e75299b97d20 we added some new forms related to FOIA and privacy. At the time, these were added behind a PRIVACY_FORMS feature flag. The flag is no longer needed since the logic has been enabled in production since that time (see <internal domain>/admin/flags/PRIVACY_FORMS/ to confirm). This commit removes it.
To test locally, confirm that the forms on these pages work locally:
- http://localhost:8000/privacy/disclosure-consent/
- http://localhost:8000/privacy/records-access/
=> Deprecate PRIVACY_FORMS feature flag

cfgov/retirement_api/jinja2/retirement_api/claiming.html, cfgov/unprocessed/apps/retirement/css/claiming.less
The retirement before you claim tool has some small text that unnecessarily sets the font size smaller, when it could use a `<small>` HTML element instead.
This was a change decided with discussion with @natalia-fitzgerald 
- Retirement: Convert small font sizes to use <small> HTML element
1. `yarn build` and compare http://localhost:8000/consumer-tools/retirement/before-you-claim/ to https://www.consumerfinance.gov/consumer-tools/retirement/before-you-claim/ The small text should be consistently 14px (0.875em). Small text appears in these places:
- text block to the right of the form inputs on the tool landing page.
- tooltips (button and popup)
- Smaller parentheses text, such as "(in today's dollars)" to the left of the graph, and the text that appears under the claiming age to the …
=> Retirement: Convert small font sizes to use <small> HTML element

cfgov/v1/signals.py, cfgov/v1/tests/test_filterable_list_form.py, cfgov/v1/tests/test_signals.py
Filterable lists don't index or search on post authors, but there are a few references to deleting a cache for searched authors. These were added at some point in the past where filterable list design included filtering by authors, but this functionality was removed in commit b02713f4d2773c76a6a28725afd59a0f4aa013a3.
=> Remove unused filterable list authors cache

cfgov/v1/jinja2/v1/includes/organisms/filterable-list-controls.html
This commit modifies how category options are sorted on filterable list controls. Instead of being sorted arbitrarily by how they are currently defined in code, this change makes it so that filterable categories are always alphabetized.
This addresses internal D&CP#313.
To test, compare http://localhost:8000/data-research/research-reports/ with the version in production at
https://www.consumerfinance.gov/data-research/research-reports/. Expand "Filter reports" and look at the sorting under "Category".
=> Always alphabetize filterable category options

requirements/libraries.txt
This commit bumps wagtail-sharing from 2.9 to 2.10.
https://github.com/cfpb/wagtail-sharing/releases/tag/2.10
This addresses internal D&CP#266.
=> Bump wagtail-sharing to version 2.10

cfgov/v1/tests/models/test_browse_page.py, docs/editing-components.md, docs/wagtail-pages.md
(This PR is to the upgrade/wagtail-4.2 branch.)
This commit fixes some deprecation warnings that appear when you run the Python tests against the upgrade/wagtail-4.2 branch. It also updates some references in the documentation.
=> Fix deprecation warnings in Wagtail 4.2

cfgov/paying_for_college/disclosures/scripts/update_colleges.py
Encountering another linter issue like https://github.com/cfpb/consumerfinance.gov/pull/7907
- Fix linter issue: Use isinstance instead of ==
=> Fix ruff linting error: Use isinstance instead of ==

cfgov/cfgov/settings/base.py, cfgov/v1/tests/test_wagtail_hooks.py, cfgov/v1/wagtail_hooks.py
This commit deprecates the `SERVE_LATEST_DRAFT_PAGES` that allows for arbitrary serving of draft Wagtail page content by primary key. This functionality was added in 2017 in commit e8902bd10ea01b7cac5f4a8b1924ffbf271f9e56 for a few pages and then turned off for those pages in 2018 in commit ae0156d29b5b099d38b1d6af7cfa88d982d13543. It hasn't been used since.
We now use wagtail-sharing to provide this functionality instead.
=> Deprecate SERVE_LATEST_DRAFT_PAGES setting

cfgov/retirement_api/jinja2/retirement_api/_templates/no_js.html, cfgov/retirement_api/jinja2/retirement_api/claiming.html
If the [before you claim retirement tool](https://www.consumerfinance.gov/consumer-tools/retirement/before-you-claim/) is in the no-js state the user can fill in the form inputs but can't click the "Get your estimates" button.
**PR TEST**
yarn build
http://localhost:8000/consumer-tools/retirement/before-you-claim/
_**--disable javascript, reload and verify warning is displayed and that the retirement tool is hidden.**_
=> Retirement: hide tool on no-js

cfgov/unprocessed/css/organisms/mega-menu.less
In https://github.com/cfpb/design-system/pull/1699/files, we removed the max-width of the icons.
In the mega-menu we set the width of the icons to 100% https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/organisms/mega-menu.less#L433
Before the update to the DS, that was being constrained by the max-width of 1em (16px max). Without the max-width, it expanded out to 100% of the available area.
- Mega Menu: Adjust icon width.
1. Pull branch, `yarn build`
2. Visit any page and check that the icons in the mega menu are correct across desktop and mobile.
Before:
After:
=> Mega Menu: Adjust icon width

cfgov/unprocessed/js/modules/util/format.js
Removes one linter warning.
- Fix missing jsdoc param
1. `yarn lint` has 100 warnings vs 101 on `main`.
=> Fix missing jsdoc param

cfgov/v1/documents.py, cfgov/v1/tests/test_documents.py
Currently the search index used for filterable pages does not include the `live` field which indicates whether a page is live or not. This means that search results could potentially include pages that aren't currently live.
We encountered this on internal issue D&CP#324, where unpublished pages appear in search results.
This commit adds the `live` field to the search index; a subsequent commit will actually use the field to filter pages once we have ensured that all environment indexes have been rebuilt.
=> Add "live" field to filterable search index

cfgov/cfgov/settings/base.py
This commit restores the Django AWS_S3_CUSTOM_DOMAIN setting which was incorrectly removed in commit 853c948248b96850d20961e1e6569c6429f7f437.
Without this setting, S3 URLs are constructed like:
https://s3.amazonaws.com/files.consumerfinance.gov/something
where we want them to be instead constructed like:
https://files.consumerfinance.gov/something
This fix makes that happen.
Addresses internal D&CP#325.
To test this, you can run this command at the command line:
```sh
S3_ENABLED=True AWS_STORAGE_BUCKET_NAME=files.consumerfinance.gov AWS_ACCESS_KEY_ID=x AWS_SECRET_ACCESS_KEY=x AWS_S3_CUSTOM_DOMAIN=files.consumerfinance.gov cfgov/manage.py shell -c "from wagtail.documents import get_document_model; Document = get_document_model(); print(Document.objects.last().file.url)"
```
This prints …
=> Fix custom domain for S3 URLs

cfgov/unprocessed/apps/admin/js/table.js, cfgov/v1/atomic_elements/tables.py, cfgov/v1/tests/atomic_elements/organisms/test_tables.py, test/cypress/integration/admin/admin-helpers.cy.js, test/cypress/integration/admin/admin.cy.js
This commit adds the ability to create a Wagtail table by pasting data from the clipboard. It supports data copied from applications like Microsoft Word or Excel, or any table data delimited by newlines and tab characters. It adds two clickable buttons to our custom Table block in Wagtail: one to paste the table as text columns, and one to paste as rich text columns.
This feature requires use of the clipboard.read browser permission, which is supported in Google Chrome but not currently in Firefox. The first time you try to use this feature on a new domain, Chrome will pop up a permissions request asking users to confirm clipboard read permission.
This implements internal D&CP#314.
=> Wagtail data tables

cfgov/jobmanager/models/pages.py, cfgov/jobmanager/tests/models/test_pages.py
This commit modifies the Wagtail admin display title of JobListingPages.
If a page has no grades assigned, its display title is unchanged. With one grade, the title will appear like "Title [Grade 53]". With multiple, it will appear like "Title [Grades 53, 60]".
Note that because of the way that Wagtail drafts work, this display title will unfortunately not always show the grades as of the latest Wagtail draft. It will show the _title_ as of the latest Wagtail draft, but the _grades_ portion will be fixed to the latest published version, or the first draft if the page has never been published.
Addresses internal D&CP#333.
=> Customize JobListingPage admin display title

cfgov/cfgov/settings/base.py
(This PR is to the upgrade/wagtail-4.2 branch.)
We have a TODO comment in the code about something that can be removed in Wagtail 4.2, but it turns out that we can't actually remove this setting. If we want to maintain the easy (meaning: we don't need to worry about running a search index update job) substring search matching behavior in Wagtail admin search, we need to keep this setting even on Wagtail 4.2.
Instead of removing, I've instead clarified the comment.
=> Clarify comment about fallback database backend

cfgov/jobmanager/jinja2/jobmanager/job_listing_list.html, cfgov/unprocessed/css/on-demand/job_listing_list.less, cfgov/unprocessed/css/organisms/sidebar-breakout.less, cfgov/v1/jinja2/v1/includes/organisms/sidebar-breakout.html
**Bug - Enterprise Issue 4502 (o-sidebar-breakout eliminates necessary margin on mobile between columns)**
------
o-sidebar-breakout is used on three pages:
https://www.consumerfinance.gov/about-us/careers/
https://www.consumerfinance.gov/find-a-housing-counselor/
https://www.consumerfinance.gov/rules-policy/
At mobile, there is a border between the items that stack at mobile, however, on two of these pages (housing counselor seems ok) block__flush-top is also applied, the margin is negated and the border sits against the block above it.
-------
Note: CSS class "block__flush-top" is negating top margin at all times with the use of an !important tag. With flush-top removed, top margin is still applied via class .content-l_col. 
To test:
yarn build
visit previous urls and verify margin on …
=> fix missing margin on mobile

cfgov/unprocessed/apps/admin/js/global.js
By default Wagtail strips filename extensions when setting a document's title when it is first created. For example, uploading a file named "something-else.pdf" will create a document entitled "something-else".
As discussed on internal D&CP#323, we want to remove this behavior, and have document titles exactly match the original filename.
This commit makes that change, following the approach documented at https://docs.wagtail.org/en/stable/advanced_topics/documents/title_generation_on_upload.html.
Edit: after further internal discussion, I've added similar logic to image uploads, per the documentation at https://docs.wagtail.org/en/stable/advanced_topics/images/title_generation_on_upload.html.
To test locally, first rebuild your frontend assets using `./frontend.sh`. Then navigate to …
=> Don't strip file extensions from document and image titles

cfgov/cfgov/settings/base.py
Our current configuration for [the django-axes package](https://github.com/jazzband/django-axes) uses its default setting for the `AXES_VERBOSE` Django setting, which is `True` if django-axes is enabled via `AXES_ENABLED`.
The verbose logging generates the following message every single time Django starts up, on every single management command, etc:
```
AXES: BEGIN version 5.41.0, blocking by username only
```
Verbose logging also logs failed/successful login attempts with greater level of detail, for example on failure:
```
AXES: User login failed, running database handler for failure.
AXES: Cleaned up 0 expired access attempts from database that were older than 2023-09-14 12:47:43.162182+00:00
AXES: New login failure by {username: "admin", ip_address: "127.0.0.1", user_agent: …
```
=> Disable verbose logging for django-axes

cfgov/unprocessed/css/enhancements/layout-1-3.less, cfgov/unprocessed/css/enhancements/layout-2-1.less, cfgov/unprocessed/css/enhancements/layout-base.less
=> Fix-up grid-based layout for mobile, 1-3, and 2-1

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html, cfgov/unprocessed/apps/teachers-digital-platform/css/pages/activity-search.less
To address internal D&CP#347, this change modifies the TDP activity search view so that it has the same layout whether there are results or not. Specifically, if there are no results, this change keeps the facet sidebar and moves the "no results" text where the results would otherwise go.
To test locally, rebuild the frontend with `./frontend.sh`, make sure you have an up-to-date database and search index, and visit
http://localhost:8000/consumer-tools/educator-tools/youth-financial-education/teach/activities/?grade_level=5&activity_duration=3&topic=8
Try the page on desktop and mobile; when on mobile, the UI is unchanged, as is the behavior when you tab through the page elements - the "Skip to search results" jump link does not appear when there are no results even though it does when …
=> TDP: No results view should match results view

cfgov/cfgov/settings/base.py
The move from GA4 to UA has come with a new domain, which is currently blocked by our CSP
This fixes that.
=> Add new domain for dap script to csp

requirements/wagtail.txt
This change bumps the version of Wagtail from 4.1.6 to [4.1.8](https://docs.wagtail.org/en/v4.1.8/releases/4.1.8.html). This new patch release allows for a newer version of Pillow ([10.0.1](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.1.html)) that addresses [CVE-2023-4863](https://github.com/advisories/GHSA-j7hp-h8jx-5ppr).
This version was just released today.
This closes internal platform#4524.
=> Bump Wagtail version from 4.1.6 to 4.1.8

cfgov/apache/conf.d/headers.conf
Currently when Apache serves responses that come from Django, we see duplicate HTTP headers:
```
% curl -I https://www.consumerfinance.gov
...
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
...
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
```
...
When responses are served directly by Apache, we don't see this:
```
% curl -I https://www.consumerfinance.gov/code.json ...
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
...
```
This change modifies the Apache configuration to ensure that Apache only sets these headers if they are unset.
See https://httpd.apache.org/docs/2.4/mod/mod_headers.html for Apache documentation.
This fixes internal platform#4522.
=> Fix duplicate HTTP headers for Django responses

cfgov/v1/jinja2/v1/includes/organisms/post-preview-snapshot.html, cfgov/v1/jinja2/v1/includes/organisms/post-preview.html
~~As discussed on https://github.com/cfpb/consumerfinance.gov/pull/7974#issuecomment-1740989439, we want to deprecate the use of hyperlinked category labels in the header of the post preview template. That PR deprecated their use on most post previews; this change takes care of the remaining case in the PostPreviewSnapshot module template.~~
In  https://github.com/cfpb/consumerfinance.gov/pull/7974#issuecomment-1740989439 we deprecated the use of hyperlinked category labels in the header of the post preview template. That PR left behind an unused parameter in the template, which is cleaned up here.
~~This only impacts two pages on the production site:~~
~~https://www.consumerfinance.gov/compliance/amicus/~~
~~https://www.consumerfinance.gov/rules-policy/notice-opportunities-comment/~~ …
=> Deprecate URL option for post preview template

cfgov/v1/management/commands/delete_page.py, cfgov/v1/tests/management/commands/test_delete_page.py
This change modifies our existing `delete_page` Django management command to support deleting only the children of a specified page. It also adds unit tests for this command.
This work relates to internal D&CP#341.
=> Support child deletion in delete_page command

requirements/libraries.txt
This change bumps the version of our wagtail-inventory package from 2.1 to 2.3. This includes these releases:
- https://github.com/cfpb/wagtail-inventory/releases/tag/2.2
- https://github.com/cfpb/wagtail-inventory/releases/tag/2.3
This adds support for Django 4.2, adds ability to filter the block inventory report by page type, and adds the ability to grant access to the block inventory report to non-admins (which addresses internal D&CP#349).
=> Bump wagtail-inventory version from 2.1 to 2.3

cfgov/unprocessed/css/on-demand/simple-chart.less
=> Shrink simple chart footnote to align with cct styles

cfgov/prepaid_agreements/jinja2/prepaid_agreements/search_result_item.html, cfgov/prepaid_agreements/models.py, cfgov/prepaid_agreements/tests/test_models.py
Currently on [the prepaid agreements search page](https://www.consumerfinance.gov/data-research/prepaid-accounts/search-agreements/), detail links are rendered without a trailing slash, like:
/data-research/prepaid-accounts/search-agreements/detail/1234
These detail URLs are constructed manually in the page template. Because our site uses trailing slashes by default, all clicks to these detail URLs result in a redirect.
This commit modifies how those URLs are generated, using Django's get_absolute_url pattern, documented here:
https://docs.djangoproject.com/en/4.2/ref/models/instances/#get-absolute-url
This also adds a unit test for this behavior.
After this change, those detail links will render with a trailing slash, and users won't have to redirect to the actual detail page.
Visit …
=> Fix: Prepaid agreement detail link redirects

requirements/libraries.txt
This commit bumps the version of the django-flags package from 5.0.9 to 5.0.13. See release notes here:
https://github.com/cfpb/django-flags/releases
The version we're on, 5.0.9, was released back in March 2022. The latest version, 5.0.13, was released in June 2023. There shouldn't be any user-visible changes with this upgrade, but this does get us on a version that has Django 4.2 support.
=> Upgrade django-flags from 5.0.9 to 5.0.13

cfgov/unprocessed/css/breadcrumbs.less
The original breadcrumb update had breadcrumbs that could be collapsed down into an ellipsis. The width property was causing an issue where a horizontal scrollbar was appearing.
- Breadcrumbs: remove width
1. Check some pages with breadcrumbs and they should wrap at smaller screen sizes and should not have a horizontal scrollbar:
http://localhost:8000/language/ar/coronavirus/mortgage-and-housing-assistance/help-for-homeowners/
http://localhost:8000/es/herramientas-del-consumidor/prestamos-para-vehiculos/respuestas/conozca-sus-derechos/
http://localhost:8000/consumer-tools/educator-tools/youth-financial-education/teach/activities/
Before: 
Can scroll to the right :(
After: you can't scroll to the right.
=> Bugfix: Breadcrumbs, remove width

cfgov/unprocessed/apps/teachers-digital-platform/js/tdp-analytics.js
Analytics reports that this should be an `event` instead of a `category`. Also, `sendEvent` never has a different category (event) sent in, so that doesn't need to be a parameter.
- TDP: convert category to event
1. PR checks should pass. This will need to go to production and then the analytics team will need to check if it's working.
=> TDP: convert category to event

cfgov/prepaid_agreements/jinja2/prepaid_agreements/search_result_item.html
As a follow up to commit fa1cebd6d02f54e7bb89a65423c71ae70e04dc88, this commit fixes one of the links on the prepaid agreements result view so that it uses better URL logic that ends in a trailing slash.
See #8000 for additional detail.
Run a local server and visit http://localhost:8000/data-research/prepaid-accounts/search-agreements/. Confirm that the search results links "View all agreement files" goes to the same place as the result heading, and ends in a trailing slash.
=> Fix: Prepaid agreement result link (again)

test/cypress/integration/admin/admin-helpers.cy.js
(This PR is to the upgrade/wagtail-4.2 branch.)
The Wagtail 4.2 release made changes to how the StreamField block UI is rendered, which broke our table-related Cypress tests that relied on a particular DOM structure.
This commit fixes those tests. To verify, run a local server and run:
`yarn cypress run --spec=test/cypress/integration/admin/admin.cy.js`
|Wagtail 4.1 editing interface|Wagtail 4.2 editing interface|
|-|-|
|<img width="729" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/3531dc02-2c21-4810-ae29-41c9cb78a3be">|<img width="438" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/02bb92f5-df79-4ee6-9702-d65974bd1ecd">|
=> Fix table Cypress tests against Wagtail 4.2

.github/workflows/frontend.yml
We don't actually respect this or pay much attention to it. It isn't a blocker to merges, it's just noisy and adds time to CI.
I propose we remove the frontend coverage action until we have a specific reason for re-instituting it.
=> Remove frontend coverage action

cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less, cfgov/unprocessed/apps/owning-a-home/js/explore-rates/RateCheckerChart.js, cfgov/unprocessed/apps/owning-a-home/js/explore-rates/highcharts-theme.js
This updates the rate-checker chart such that the labels have been moved to x-axis. This prevents reported disappearing of these labels and wonkiness on print.
Testing:
- Visit http://localhost:8000/owning-a-home/explore-rates/
- Note that all bars have a label and that it's consistent at every screen size
- Note that using "download chart" to get a PNG results in an image consistent with what's included in the webpage.
=> Rate-checker chart label bugfixes

cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
Our internal crawl tool revealed a couple of broken links that were hardcoded into HTML files. This PR corrects those. (Specifics in the "Changes" section below)
---
- Updating the link to "Find financial education lessons from FDIC" on all TDP activity pages
- Updating the link to "list of nationwide HUD-approved counseling agencies" on the Housing Counselor tool
- CFGOV/platform wiki on GHE – for …
=> Broken link fixes from internal crawl

cfgov/cfgov/settings/base.py
With the commits in PRs #8022 and #8024, this project no longer has a cfgov/templates directory. This allows us to remove its reference in the Django settings.
This commit also makes an unrelated bit of cleanup by removing the empty "builtins" option to the Django template engine.
=> Cleanup obsolete template-related settings

cfgov/v1/jinja2/v1/includes/organisms/expandable.html
This change alters the rendering of the Expandable block so that link tags are rendered inside of a `<p>..</p>` element. This prevents elements from incorrectly rendering directly next to each other.
See internal D&CP#392 for context.
To test, visit this page with a production dump to compare spacing around link elements with the production version:
http://localhost:8000/consumer-tools/educator-tools/youth-financial-education/resources-research/building-block-activities-resources/
|Before|After|
|-|-|
|![image](https://github.com/cfpb/consumerfinance.gov/assets/654645/318391e3-fc5f-4f8a-bde2-67299889f085)|![image](https://github.com/cfpb/consumerfinance.gov/assets/654645/e76c4e76-1816-44b6-ae36-3942f3bb8445)|
Additionally, try adding two Links inside an Expandable to see that they are …
=> Wrap expandable links in paragraph tag

cfgov/paying_for_college/tests/test_views.py, cfgov/paying_for_college/views.py, cfgov/unprocessed/apps/paying-for-college/js/disclosures/dispatchers/post-verify.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/utils/dollar-sign.js
jquery does some magic massaging of post data which we tried to get around with xhr. However, django was expecting form-encoded data instead of post data. This PR:
- loads the json data posted to the post-verify view (instead of trying to access form data on the `request.POST` object)
- `POST`s with `fetch` for consistency with the other dispatchers
- Removes a stray log
- Get a valid querystring and go through the step 1 -> step 2 flow
- When confirming that ,you better understand your finances', note that there is no longer a `400` on `POST`ing
=> Post with fetch and load fetch data from post verify

cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/financial-view.js
Looks like there was a copy/paste error when converting from jquery. The correct selector when there is negative "remaining cost" is `'[data-financial="overborrowing"]'`
=> Fix data selector for negative cost

cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/financial-view.js
Previously, this check would allow program lengths of `0` provided in the URL to flow to the dropdown, which doesn't make sense and was causing the dropdown to be blank. This fixes that.
- With a valid url, add a `leng=0` and note it falls back to the default program value
=> Change urlProgramLength presence check

requirements/libraries.txt
Snyk reports a vulnerability in Pillow versions < 10.0.0. We don't pin Pillow, which means that Wagtail in practice pulls in the most recent version, which is greater than 10.0.0, BUT for some reason this doesn't satisfy Snyk.
Snyk keeps reporting this vulnerability on all of our cf.gov PRs. In order to make Snyk happy, let's pin Pillow to the currently installed version, which is 10.1.0.
Here's what Snyk reports:
Even though in practice we are already getting Snyk 10.1.0:
```sh
$ /srv/cfgov/current/venv/bin/pip freeze | grep illow
Pillow @ file:///srv/cfgov/versions/20231129110504/wheels/Pillow-10.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=fa1d323703cfdac2036af05191b969b910d8f115cf53093125e4058f62012c9a
```
=> Pin Pillow to 10.1.0 to make Snyk happy

cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/financial-view.js
There was a `null` case which caused some currency values to be improperly formatted. This should address the issue!
- Change code so that the `currentInput` value is not `null` and should not be assigned `null`
- Change checks against the `currentInput` so that they will check properly against the current value
1. Check the values in Step 2 to make sure the currency values show with dollar signs and commas.
This is what the app should look like with proper formatting:
=> [Dynamic Disclosures] FIx a currency formatting issue

cfgov/ask_cfpb/tests/test_views.py, cfgov/ask_cfpb/views.py
This commit removes the `ask_cfpb.views.annotate_links` view. It appears at some point this was intended to automatically generate footnote links for Ask CFPB answer text, but it was never fully implemented.
=> Remove unused ask_cfpb.views.annotate_links

cfgov/unprocessed/js/routes/on-demand/simple-chart/chart-hooks.js
Allows splitting of the aggregated age files into component parts.
=> Add transforms for cct data borrower age pages

cfgov/prepaid_agreements/scripts/import_prepaid_agreements_data.py
@csebianlander brought some prepaid-agreements 404s to my attention. This fixes a certain class of error where the product name, and thus S3 path, has a character that needs escaping.
- Pull
- Activate virtualenv or exec into docker
- `./cfgov/manage.py runscript import_prepaid_agreements_data`
- Visit http://localhost:8000/data-research/prepaid-accounts/search-agreements/?search_field=all&q=Cashpass+Premier
- Note that the `Cashpass Premier %` download location is urlencoded
- (whereas it isn't and 404s at https://www.consumerfinance.gov/data-research/prepaid-accounts/search-agreements/?search_field=all&q=Cashpass+Premier)
=> Escape special characters in prepaid agreement url paths, preventing 404s

cfgov/unprocessed/apps/paying-for-college/js/disclosures/utils/dollar-sign.js
This PR will address an issue of an error that occurs when certain financial fields are edited. The issue stems from missing methods. 
- add `Query.parent()` and `Query.appendTo()`
1. Open a local url and edit tuition and loans. Check if there are any errors in the console, and make sure the overborrowing warnings (when you borrow above federal limits on federal loans) appear.
=> Dynamic Disclosures - Fix overborrowing display error

cfgov/unprocessed/apps/paying-for-college/js/disclosures/index.js
This fixes a bug that is causing the `$percent` elements to be rendered with incorrect values (any really anything depending on constants). I believe this crept in when merging the fetch branch into the big dynamic disclosures PR.
Before:
After:
=> Don't index the constants object when initializing the financial model

cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less, cfgov/unprocessed/css/enhancements/utilities.less
This class was intended as a general utility class, but was only used as a mixin in the rate checker. This PR moves it alongside the rest of the rate checker CSS.
- Move `u-reset` mixin to rate checker CSS
1. Rate checker `.chart figure` and `next-steps-list` should be reset as before.
=> Move `u-reset` mixin to rate checker CSS

cfgov/cfgov/settings/base.py
This commit deprecates 3 unused Django settings:
```
OFFLINE_OUTPUT_DIR = ''
GOOGLE_ANALYTICS_ID = ''
GOOGLE_ANALYTICS_SITE = ''
```
These were all added back in April 2016 (in commit b859cc8bce8e62666f4a8677186d63d2d04cd092) but as far as I can tell are not used anywhere. Therefore we can remove them.
=> Deprecate 3 unused Django settings

test/cypress/integration/data-research/mortgage-performance-trends/mortgage-performance-trends.cy.js
This test only runs on localhost and fails because the map has not loaded before the tests starts interacting with the controls. Ideally, the controls should probably not be actionable before the map shows up, but this test accommodates the status quo of how it currently works.
- MPT test: Add check for the map before interacting with map drop-downs.
1. Pull branch and run `yarn cypress open` and run the mortgage performance trends test.
=> Fix map not visible issue with Mortgage Performance Trends Cypress test

cfgov/cfgov/settings/local.py
This morning https://placekitten.com reports a DreamHost "site not found" error. This commit switches our local placeholder image service to https://dummyimage.com, which generates boxes of text with the image size overlaid.
This service has fewer kittens but does have the benefit of generating the same image each time the same URL is requested, unlike placekitten which generates a random kitten. This makes dummyimage nicer for visual regression testing.
I used Green 60 and Mid Dark Green from the design system palette [here](https://cfpb.github.io/design-system/foundation/color#data-visualization-palettes-1); please suggest a better combination if one is preferred!
=> Switch to dummyimage.com for local placeholder images

cfgov/ask_cfpb/tests/test_views.py, cfgov/cfgov/urls.py, cfgov/filing_instruction_guide/import_data_points.py, cfgov/filing_instruction_guide/models.py, cfgov/regulations3k/models/pages.py, cfgov/retirement_api/urls.py, cfgov/retirement_api/utils/tests/test_ss_update_stats.py, cfgov/retirement_api/utils/tests/test_ss_utilities.py, cfgov/scripts/initial_data.py, cfgov/v1/models/filterable_page.py, pyproject.toml
Our current isort config has a few issues:
1. `wagtailsharing` is classified as "known Wagtail" along with the `wagtail` package, but none of our other third-party Wagtail packages (like `wagtailinventory`) are similarly classified.
2. Our "first party" classification relies on a hardcoded list which is out of date, and doesn't include our `filing_instruction_guide` or `retirement_api` packages.
To address these and simplify in future, this commit migrates our isort configuration to use a new `src_paths` option that automatically treats any library under `/cfgov` as being first-party.
This does have one unfortunate complication, which is that the presence of our `/cfgov/jinja2` path would then shadow the third-party `jinja2` package that we use. For that reason we now have to explicily …
=> Fix incorrect isort config

cfgov/unprocessed/apps/paying-for-college/js/college-costs/views/financial-view.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/index.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/financial-view.js, cfgov/unprocessed/apps/retirement/js/data/index.js, cfgov/unprocessed/apps/retirement/js/utils/num-to-money.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/file-input.js, cfgov/unprocessed/apps/teachers-digital-platform/js/AtomicComponent.js, cfgov/unprocessed/js/organisms/MortgagePerformanceTrends/utils.js
All code is functionally equivalent except the uniqueId generated in the tdp atomic component, which will generate a uniqueId of variable length instead of always 9 chars (this doesn't matter in context though).
=> Converts use of substr to slice, as substr has been deprecated

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
`activity_page` extends `layout-2-1`, which extends `base`, which has an existing title section at https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/layouts/base.html#L46-L51
The section removed in this PR appears redundant to that defined in the base template.
- TDP: Remove redundant page title from activity_page template
1. Search `activity_page` in the crawler and see that pages from that result set viewed in this PR have an unchanged title.
=> TDP: Remove redundant page title

cfgov/retirement_api/utils/tests/test_ss_utilities.py
This test was failing in the New Year.
- Fix `test_get_retire_data_too_old` test: Change date of birth to 1/1
=> Fix `test_get_retire_data_too_old` test: Change date of birth to 1/1

cfgov/v1/migrations/0015_grouppagepermission_index_fix.py
We need "#nosec" here to prevent Bandit complaining about raw SQL. For some reason, probably because this is a multi-line string, this doesn't work right if we are more specific using "#nosec B608" instead.
As is this generates the following Bandit warning when you run "tox -e lint":
> WARNING nosec encountered (B608), but no failed test on line 18
Changing this to just "#nosec" correctly suppresses the warning.
`tox -e lint` -- note no Bandit warnings.
=> Fix Bandit linter warning

cfgov/wagtailadmin_overrides/templates/wagtailadmin/pages/listing/_button_with_dropdown.html
The recent upgrade to Wagtail 5.1 missed an update to one of their admin templates that we override. This new content comes from:
https://github.com/wagtail/wagtail/blob/v5.1.3/wagtail/admin/templates/wagtailadmin/pages/listing/_button_with_dropdown.html
To test, run a local server and visit http://localhost:8000/admin/pages/319/.
=> Fix Wagtail template override for 5.1 upgrade

cfgov/v1/jinja2/v1/layouts/layout-2-1.html
Follow up to https://github.com/cfpb/consumerfinance.gov/pull/8076/
The `block content_modifiers` didn't get carried over from `content-base.html` to `layout-2-1.html`, which broke some styling on the ask CFPB pages.
- Adds `block content_modifiers` to `layout-2-1.html`.
1. Ask CFPB pages should have a properly styled "Last viewed" sections (see screenshots).
Before:
After:
=> Bugfix: Add `block content_modifiers`

cfgov/unprocessed/css/enhancements/utilities.less, cfgov/unprocessed/css/organisms/mega-menu.less
`u-link__disabled` is not used in any markup and so these rules should be removed.
=> Remove unused u-link__disabled utility

requirements/libraries.txt
So that we have the correct values for 2024
=> Update oah-api version to include 2024 loan limit data

cfgov/form_explainer/jinja2/form-explainer/index.html, cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html, cfgov/unprocessed/css/molecules/related-posts.less, cfgov/v1/jinja2/v1/browse-basic/index.html, cfgov/v1/jinja2/v1/browse-filterable/index.html, cfgov/v1/jinja2/v1/includes/molecules/related-posts.html, cfgov/v1/jinja2/v1/includes/templates/streamfield-sidefoot.html, cfgov/v1/jinja2/v1/newsroom/index.html
Refactors the related posts to break into columns at (mostly) tablet width.
- Remove `m-related-posts__half-width`
- Refactor related posts CSS to use a responsive grid.
1. Visit a page with related posts in the pre footer, like http://localhost:8000/rules-policy/final-rules/
2. Scroll down till you see the related posts ("Further reading"). They should be two columns at tablet/desktop sizes, and a single column at mobile.
3. Visit a page with a related posts molecule in the sidefoot, such as http://localhost:8000/about-us/
2. Resize the page and observe that the related posts are a single column at desktop, two columns at tablet, and a single column again at mobile.
Mobile:
Tablet:
Desktop:
=> Remove `m-related-posts__half-width`

cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html, cfgov/unprocessed/apps/paying-for-college/js/disclosures/index.js, test/cypress/fixtures/paying-for-college/program-133465_5287.json, test/cypress/fixtures/paying-for-college/school-133465.json, test/cypress/integration/paying-for-college/disclosures/disclosures-helpers.cy.js, test/cypress/integration/paying-for-college/disclosures/disclosures-school-data.cy.js
This is a small re-write of some Dynamic Disclosures tests to address failures we were seeing.
While I originally thought it was something related to failed fixtures/intercepts, it looks like it was actually something interfering with the automated "Step 2" button click. A `cy.wait(500)` placed before the "Step 2" click fixed it. I would have liked to avoid that arbitrary `wait` statement, but other tricks I tried weren't working, and a fix in the short term is more important than my dislike of arbitrary `wait` statements. 😄 
- Rewrite some `disclosures` cypress tests
1. If the Dynamic Disclosures cypress tests work, then we should be good!
=> Fix issue with dynamic disclosures cypress tests

cfgov/ask_cfpb/jinja2/ask-cfpb/_disclaimer.html, cfgov/ask_cfpb/jinja2/ask-cfpb/answer-page.html, cfgov/ask_cfpb/jinja2/ask-cfpb/answer-search-results.html, cfgov/ask_cfpb/jinja2/ask-cfpb/landing-page.html, cfgov/unprocessed/css/on-demand/ask.less
Related to https://github.com/cfpb/consumerfinance.gov/pull/8079
Ask CFPB has a disclaimer block in the sidebar that does not use slug styles. Elsewhere on the site the disclaimer block has slug styling (i.e. https://www.consumerfinance.gov/consumer-tools/managing-someone-elses-money/ or https://www.consumerfinance.gov/paying-for-college/repay-student-debt/federal-parent-plus-loans/ or https://www.consumerfinance.gov/consumer-tools/educator-tools/your-money-your-goals/booklets-talk-about-money/).
Originally Ask CFPB did not have other blocks with slug styling in the sidebar, but later these were added. This made it so the sidebar has only slug styling for the item between the about us block and the disclaimer.
(i.e. https://www.consumerfinance.gov/ask-cfpb/a-few-days-after-my-relatives-obi …
=> Ask CFPB: Standardize disclaimer text

cfgov/v1/jinja2/v1/layouts/layout-2-1-ltr.html, cfgov/v1/jinja2/v1/layouts/layout-2-1.html
Temporary workaround till https://github.com/cfpb/consumerfinance.gov/pull/8079 goes in.
- Creates temporary `layout-2-1-ltr.html` template to fix issue where some arabic pages were devoid of content.
1. http://localhost:8000/language/ar/ should have page content.
=> Fix arabic layout bug

cfgov/retirement_api/jinja2/retirement_api/claiming.html
Use standard language links module for language links in planning for retirement app.
- Retirement: Move language links to standard translation links module
1. http://localhost:8000/consumer-tools/retirement/before-you-claim/ should have standard language links
Before:
After:
=> Retirement: Move language links to standard translation links module

cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/financial-view.js
There was a latent reference to the jquery `.prop` function, now replaced.
- Go to a relevant page.
- Click between 10 and 25yr loan terms in the sidebar
- Values should update
=> Replace prop function

requirements/wagtail.txt
See release notes here:
https://docs.wagtail.org/en/latest/releases/5.2.3.html
Both of these changes are for Django 5.0 support so don't affect us, but it's good to stay on the latest patch version.
=> Upgrade Wagtail from version 5.2.2 to version 5.2.3

cfgov/permissions_viewer/wagtail_hooks.py
Wagtail 5.2 [removed the `classes` keyword argument to `UserListingButton`](https://github.com/wagtail/wagtail/commit/f3adefe362f1f5a13812ab57ec414f9add19591b). The `classname` argument is now used. This fixes this minor problem that's causing a 500 for /admin/users.
It looks like this is a tiny thing that we missed with the Wagtail 5.2 upgrade.
=> Fix admin/users error with UserListingButton

cfgov/cfgov/settings/base.py
The `anchor-identifier` Draftail feature was not high up enough in the list of features. This meant that, when reading the HTML from the database and converting into Draftail's data format, anchors were being identified as regular links and presented as such in the rich text editor. Ultimately, this means that anchors were just becoming regular links *to* the anchor they used to be.
This fixes it by promoting the `anchor-identifier` feature to the top of the list; or, by raising the anchor.
=> Raise anchors

cfgov/privacy/jinja2/privacy/disclosure-consent-form.html, cfgov/privacy/jinja2/privacy/records-access-form.html
- Privacy: Remove inline styles and replace with utility classes, where needed.
1. Visit these two pages and compare to production. 
http://localhost:8000/privacy/disclosure-consent/
http://localhost:8000/privacy/records-access/
Only difference should the increased gap at the bottom of the main content area.
=> Privacy: Remove inline styles

cfgov/paying_for_college/disclosures/scripts/api_utils.py, cfgov/paying_for_college/disclosures/scripts/update_colleges.py, cfgov/scripts/tests/test_smoke_tests.py
`black` was autoupdated and led to linter failures on `main` https://black.readthedocs.io/en/stable/change_log.html#id1
- Fix black linter issues
=> Fix black linter issues

cfgov/ask_cfpb/jinja2/ask-cfpb/landing-page.html, cfgov/v1/jinja2/v1/includes/organisms/ask-search.html
Small follow up to https://github.com/cfpb/consumerfinance.gov/pull/8106
The language links template places the language link in a block that has top and bottom padding. Almost all places the links appear below the heading of the page, but on the Ask landing page it appears above the search, which pushes it too far down. Instead of figuring out how to pass in a `block__flush-top` class to this one use-case, this PR moves the translation likes below the search input. 
- Move translation links below search on Ask landing page.
1. http://localhost:8000/ask-cfpb/ should have the search links below the search input.
Before:
After:
=> Move Ask language link below search

cfgov/prepaid_agreements/jinja2/prepaid_agreements/search_results.html
The label has an attribute `for="card_type"`, but there is no associated ID. This PR fixes ID association.
- Prepaid agreements: Fix `id` for `for` attribute by changing name to `issuer_name`.
1. Visit http://localhost:8000/data-research/prepaid-accounts/search-agreements/ and see that interacting with "Issuer name" will interact with its associated multiselect.
=> Prepaid agreements: Add `id` for `for` attribute

cfgov/ask_cfpb/jinja2/ask-cfpb/answer-page.html, cfgov/ask_cfpb/jinja2/ask-cfpb/landing-page.html, cfgov/retirement_api/jinja2/retirement_api/claiming.html, cfgov/v1/jinja2/v1/includes/molecules/text-introduction.html, cfgov/v1/jinja2/v1/includes/molecules/translation-links.html, cfgov/v1/jinja2/v1/includes/organisms/ask-search.html, cfgov/v1/jinja2/v1/includes/organisms/item-introduction.html, cfgov/v1/jinja2/v1/sublanding-page/index.html, cfgov/wellbeing/jinja2/wellbeing/about.html, cfgov/wellbeing/jinja2/wellbeing/error.html, cfgov/wellbeing/jinja2/wellbeing/home.html
Small error in https://github.com/cfpb/consumerfinance.gov/pull/8115. When the translation links move below the ask search, the search needs its bottom margin removed. Turns out the bottom margin is used at mobile to space the button and search input apart. This PR turns the whole translation-links template into a macro and adds the option to pass in a modifier class. 
- Update translation-links to use macro and allow passing in of a container CSS class.
1. Visit the following translation link pages:
http://localhost:8000/ask-cfpb/
http://localhost:8000/ask-cfpb/what-should-i-know-before-i-shop-for-auto-loan-at-a-bank-credit-union-dealership-or-other-lender-en-755/
http://localhost:8000/language/ru/
http://localhost:8000/consumer-tools/financial-well-being/ …
=> Update translation-links to use macro

cfgov/unprocessed/apps/retirement/css/claiming.less
I noticed some CSS in the before you claim app that could be cleaned up:
- `#claiming-social-security` was nested inside `#claiming-social-security`
- Nested classes under IDs
- Removes unreferenced `benefit-selection`
- Removes `hero_image` inside media query (app's page doesn't have a hero)
- Removes `#age-selector-response .next-steps li.next-step-two`. `next-step-two` is not in HTML.
- Fix small screen responsive styling.
- Retirement: Clean up CSS and remove unused selectors
1. http://localhost:8000/consumer-tools/retirement/before-you-claim/ should be unchanged from production, EXCEPT at mobile, where it should have spacing between form elements:
Before:
After:
=> Retirement: Clean up CSS and remove unused selectors

cfgov/ask_cfpb/jinja2/ask-cfpb/landing-page.html, cfgov/retirement_api/jinja2/retirement_api/claiming.html, cfgov/v1/jinja2/v1/includes/molecules/text-introduction.html, cfgov/v1/jinja2/v1/includes/molecules/translation-links.html, cfgov/v1/jinja2/v1/includes/organisms/item-introduction.html, cfgov/wellbeing/jinja2/wellbeing/about.html, cfgov/wellbeing/jinja2/wellbeing/error.html, cfgov/wellbeing/jinja2/wellbeing/home.html
Translation_links `value` object was bleeding outside the macro with the call to `value.update(…)`. This PR refactors the macro signature to pass in explicit arguments.
- Refactor translation links template to pass in specific arguments.
- Get `language` from the page context only.
1. http://localhost:8000/ask-cfpb/
http://localhost:8000/ask-cfpb/what-should-i-know-before-i-shop-for-auto-loan-at-a-bank-credit-union-dealership-or-other-lender-en-755/
http://localhost:8000/language/ru/
http://localhost:8000/consumer-tools/financial-well-being/
http://localhost:8000/consumer-tools/financial-well-being/about/
http://localhost:8000/consumer-tools/financial-well-being/error/
http://localhost:8000/consumer-tools/retirement/before-you-claim/
text-introduction page (should not have language link) …
=> Refactor translation_links macro signature

cfgov/ask_cfpb/jinja2/ask-cfpb/answer-page.html, cfgov/ask_cfpb/jinja2/ask-cfpb/answer-search-results.html, cfgov/ask_cfpb/jinja2/ask-cfpb/landing-page.html, cfgov/hmda/jinja2/hmda/hmda-explorer.html, cfgov/jobmanager/jinja2/jobmanager/job_listing_page.html, cfgov/prepaid_agreements/jinja2/prepaid_agreements/detail.html, cfgov/regulations3k/jinja2/regulations3k/landing-page.html, cfgov/unprocessed/css/main.less, cfgov/unprocessed/css/molecules/related-posts.less, cfgov/unprocessed/css/organisms/sidebar-content.less, cfgov/v1/jinja2/v1/document-detail/index.html, cfgov/v1/jinja2/v1/enforcement-action/index.html, cfgov/v1/jinja2/v1/landing-page/index.html, cfgov/v1/jinja2/v1/learn-page/index.html, cfgov/v1/jinja2/v1/sublanding-page/index.html
https://github.com/cfpb/consumerfinance.gov/pull/8079 migrated the layout-2-1 to a CSS grid, which doesn't need the `content_sidebar_modifiers`. Therefore the child templates that extend this template don't need `content_sidebar_modifiers` blocks.
Additionally, the related-posts did target the (now unused) sidebar class, so we need to update that to target the newer CSS grid sidebar container class. I don't love burying this class reference in the related-posts, but I couldn't immediately think of a better way.
- Remove unused `content_sidebar_modifiers` blocks
- Remove unused `sidebar-content.less` file.
- Target sidebar for related-posts to fix layout bug.
http://localhost:8000/enforcement/actions/enforcement-action-definitions/ should have related posts that extend the full width of …
=> Remove unused `content_sidebar_modifiers` blocks

cfgov/unprocessed/apps/homepage/css/main.less, cfgov/unprocessed/css/enhancements/layout.less, cfgov/v1/jinja2/v1/home_page/home_page.html, esbuild/styles.js
We have a homepage app that has images for the homepage. However, the CSS that is only used on the homepage is included in the global layout CSS delivered to all pages. This PR moves the homepage-specific classes to a new CSS file in the homepage app.
- Move homepage styles to homepage app
1. Homepage should be unchanged.
=> Move homepage styles to homepage app

cfgov/ask_cfpb/jinja2/ask-cfpb/answer-page.html, cfgov/hmda/jinja2/hmda/hmda-explorer.html, cfgov/jobmanager/jinja2/jobmanager/job_listing_page.html, cfgov/prepaid_agreements/jinja2/prepaid_agreements/detail.html, cfgov/v1/jinja2/v1/document-detail/index.html, cfgov/v1/jinja2/v1/enforcement-action/index.html, cfgov/v1/jinja2/v1/landing-page/index.html, cfgov/v1/jinja2/v1/learn-page/index.html
https://github.com/cfpb/consumerfinance.gov/pull/8079 migrated the layout-2-1 to a CSS grid, which doesn't need the `content_main_modifiers`. Therefore the child templates that extend this template don't need `content_main_modifiers` blocks.
- Remove unused `content_main_modifiers` blocks
The layout-2-1.html template doesn't have the `block content_main_modifiers` block, so there should be no change in removing this, but if you want to double-check, these are example pages from the changed templates:
ask-cfpb/answer-page.html
http://localhost:8000/ask-cfpb/a-box-on-my-credit-card-bill-says-that-i-will-pay-off-the-balance-in-three-years-if-i-pay-a-certain-amount-what-does-that-mean-do-i-have-to-pay-that-much-if-i-pay-that-much-and-make-new-purchases-will-i-still-owe-nothing-after-three-year …
=> Remove unused `content_main_modifiers` blocks

.github/workflows/build-artifact.yml, .github/workflows/frontend.yml
This uses the centos package built in https://github.com/cfpb/consumerfinance.gov/pull/7732 to build our deployable zipfile and push it to S3, replacing the cf.gov-ansible-build and cf.gov-ansible-upload jenkins jobs. As such, this is blocked by #7732.
Testing is best done on a fork, where you will need to provide the appropriate secrets.
=> Build deployable artifact in GHA

.github/workflows/build-artifact.yml
This way, we know that a commit that lands in main will have a corresponding artifact
=> Build the artifact as part of the merge queue instead of on push to main

cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js
This adds a little check off the chart type to make the styling for projected data in column-type simple charts better.
Before:
After:
=> Allow projected simple chart values to work for column charts

test/cypress/integration/admin/admin-helpers.cy.js
-  Edit admin Cypress test to assert "Copy" exists on regulations test before clicking it 
- Target link inside the `children` class
1. PR checks should pass
=> Edit admin Cypress test to assert "Copy" exists on regulations test before clicking it

cfgov/v1/jinja2/v1/includes/molecules/translation-links.html
https://www.consumerfinance.gov/consumer-tools/prepaid-cards/understand-fees/ isn't showing language links because text introduction is not receiving `language`. This PR sets the language from the page, if `language` is not available.
- Set language default from page
1. Visit http://localhost:8000/consumer-tools/prepaid-cards/understand-fees/ and see that there's a language picker that works.
2. Visit http://localhost:8000/es/herramientas-del-consumidor/tarjetas-prepagadas/entienda-las-tarifas/ and see that there is a functional language picker.
Before:
After:
=> Set language default from page

cfgov/unprocessed/css/organisms/full-width-text-group.less
This came up as part of #8127: because we have an `overflow: auto` on `.o-full-width-text-group`, [margins don't collapse across the scroll container boundary](https://www.joshwcomeau.com/css/rules-of-margin-collapse/#blocked-by-a-scroll-container-7). In practice, this means that if you happen to put a block that has a top margin at the beginning of a full-width text group (or a block with a bottom margin at the end), the margin won't collapse with whatever precedes (or follows) the full-width text block. That can lead to some huge margins. As an example, look on Content at `/data-research/credit-card-data/terms-credit-card-plans-survey-new/terms-of-credit-card-plans-tccp-data-dictionary/`:
That 120 px margin between the text introduction and the first table is because the page is …
=> Clear floats on full-width text blocks

cfgov/prepaid_agreements/jinja2/prepaid_agreements/search_results.html, cfgov/unprocessed/apps/regulations3k/css/reg-search.less, cfgov/unprocessed/apps/regulations3k/js/search.js, cfgov/unprocessed/css/atoms/tag.less, cfgov/unprocessed/css/search.less, cfgov/v1/jinja2/v1/includes/atoms/tag.html, test/unit_tests/apps/regulations3k/js/search-spec.js
Analytics requested that these tags in TDP be clickable on the whole button, as they function on CCDB. These tags are shared between iRegs, Prepaid product agreements database, and TDP, so I took this opportunity to align them all with the tags/pills we have in the DS on https://cfpb.github.io/design-system/components/selects
- Refactor tags/pills in iRegs, Prepaid product agreements database, and TDP to be clickable on the whole button and look like the tags in the DS.
1. Compare the tags/pills of these three apps to production and across different screensizes.
Prepaid
http://localhost:8000/data-research/prepaid-accounts/search-agreements/
TDP
http://localhost:8000/consumer-tools/educator-tools/youth-financial-education/teach/activities/
iRegs …
=> Refactor tags to align with design system tags

cfgov/unprocessed/apps/financial-well-being/js/fwb-questions.js, cfgov/unprocessed/apps/financial-well-being/js/fwb-results.js
In https://github.com/cfpb/consumerfinance.gov/pull/7336, there was a call to `getDataLayerOptions(…)`, which took an argument of `category`. Inside that function the `category` was then assigned to an `event` key in the event payload. Unfortunately, when `getDataLayerOptions(…)` was refactored away the `category` key was sent in the payload directly, instead of mapping it to `event` before sending. This PR fixes that.
- FWB: fix incorrect event payload key (`category` --> `event`)
1. PR checks should pass and then analytics team needs to test
=> FWB: fix incorrect event payload key

cfgov/tccp/jinja2/tccp/card.html
Adds the card name and availability to the TCCP card details page. Since this is still more prototype than production, some notes:
- Since we're still iterating on both this page and the front end of the TCCP app, I'm just stuffing all the CSS in the head of the card details page for now. We'll refactor that to the right place once the front end architecture comes together more.
- Similarly, right now there's a ton of logic to handle all the possible combinations of card availability data in the Jinja template. We'll refactor that as we keep adding data and iterating on this page.
---
- Card name details
- Card availability details
1. Pull up some card detail pages and make sure the heading, updated date, and availability section appear and match what's in the data. Some good example …
=> Add card name and availability to details page

cfgov/tccp/filters.py, cfgov/tccp/filterset.py, cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/macros/filter_form.html, cfgov/tccp/situations.py, cfgov/tccp/tests/test_fields.py, cfgov/tccp/tests/test_filterset.py, cfgov/tccp/tests/test_views.py
These commits fix a few minor bugs from #8153 and iterates on the card list view.
Visit http://localhost:8000/consumer-tools/credit-cards/tccp/cards/ to test locally.
Alternatively visit the same URL on our internal DEV4 server to see this branch deployed there.
=> Iterating on the TCCP card list view

tox.ini
These two environment variables don't need to be explicitly passed to tox.
See #1098 for background.
All tests pass even without these variables set.
=> Remove two unused tox.ini environment variables

pyproject.toml
ruff version 0.2.0 deprecated certain settings and their use is currently generating these warnings when running `tox -e lint`:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
```
This commit fixes those warnings.
`tox -e lint` and look for warnings -- you won't see any!
=> Fix ruff warnings due to ruff 0.2.0

cfgov/tccp/filters.py, cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/serializers.py, cfgov/tccp/tests/test_filterset.py
This changes the TCCP cards table so that all filterable/sortable columns are shown.
To test, visit http://localhost:8000/consumer-tools/credit-cards/find-cards/cards/ (or check DEV4).
See internal DTUR#226 for background.
=> Show all columns in TCCP cards table

.stylelintrc.cjs, cfgov/tccp/jinja2/tccp/cards.html, cfgov/unprocessed/apps/tccp/.yarnrc, cfgov/unprocessed/apps/tccp/css/main.less, cfgov/unprocessed/apps/tccp/package.json, cfgov/v1/jinja2/v1/includes/organisms/tables/base.html, cfgov/v1/template_debug/tables.py, esbuild/styles.js
Adds a new hybrid responsive table pattern that stacks *some* columns on smaller screens, specified with a new [`preserve_column_on_mobile`](https://github.com/cfpb/consumerfinance.gov/compare/tccp/styles?expand=1#diff-f7439a4b28b7d7839c310d626549810c4a56ec588d77c6807f08a82125306826R65-R66) property in our base table template. I also added a `right_align` property to let us [right align table cells](https://cfpb.github.io/design-system/components/tables#right-aligned-table).
See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/232
- New hybrid responsive table pattern.
- Optional `preserve_column_on_mobile` and `right_align` table column properties.
- New stylesheet and front-end "app" for TCCP.
1. Visit …
=> Add new hybrid responsive table pattern to TCCP app

cfgov/retirement_api/utils/ss_utilities.py, cfgov/retirement_api/utils/tests/test_ss_utilities.py
This test didn't properly handle Leap Day logic. Fixed this and added some additional comments to clarify what is being tested.
=> Fix retirement_api test that was failing on 2/29

cfgov/unprocessed/apps/retirement/css/claiming.less
Back in https://github.com/cfpb/consumerfinance.gov/pull/7788 I did a mistake 😬 and moved the retirement ID to the top scope, so that all selectors are inside `#claiming-social-security`. However, there is a selector `[lang='es']`, that targeted the `<html>` element, so the selector should have been `[lang='es'] #claiming-social-security`, but instead ended up as  `#claiming-social-security [lang='es']`. The consequence of this is that the retirement app lost some images.
- Retirement: Fix missing images by moving spanish target overrides to their own section.
- Retirement: refactor CSS to standard media queries, color variables, etc
- Retirement: Add hand cursor when hovering over tooltip trigger.
1. `yarn build` and visit http://localhost:8000/consumer-tools/retirement/before-you-claim/ …
=> Retirement: Fix missing images and refactor CSS to standard media queries, color variables, etc

cfgov/ask_cfpb/jinja2/ask-cfpb/landing-page.html
- Ask CFPB: Remove `content-l` from search landing page that was throwing the left alignment off
1. Visit http://localhost:8000/ask-cfpb/ and resize the page and watch the alignment of search input text.
Before:
After:
=> Ask CFPB: Remove `content-l` from search landing page that was throwing the left alignment off

cfgov/v1/jinja2/v1/sublanding-page/index.html
The sublanding page template removes breadcrumbs, but has language links that are spaced how they'd be if there were breadcrumbs. This PR adds a modifier class to the language links on this template so that they are flush with the top on their container.
- Sublanding page: Fix issue where language links weren't flush with top
1. The language links and sidebar content should be level with each other on http://localhost:8000/es/coronavirus/
Before:
After:
=> Sublanding page: Fix issue where language links weren't flush with top

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/jinja2/tccp/macros/fields.html
Add purchase APR details to credit card details. See DTUR issue 231 for more. There are a bunch of content questions we need to work out in that issue, so let's focus on the code in this PR. Lots of TODOs noted below, too.
---
- Purchase APR details to credit card details page
There are a ton of possible combinations you can check on localhost:
- [Min and max APR, no median, varies by credit tier](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/advantis-credit-union-signature-cashback-rewards-credit-card/)
- [Min, max, and median APR, doesn't vary by credit tier](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/cadence-bank-platinum/)
- [A single APR (i.e. min, max, and median APR are all the same), doesn't vary by credit …
=> Add purchase APR to card details page

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py
Currently the TCCP feature flag logic prohibits it from running in either beta or production. Soon we want to be able to test on beta.
This change modifies the feature flag logic such that TCCP is always available locally or on our internal DEV4 testing server. Deploying it in other environments will require manually enabling it via the Wagtail UI.
Running locally (`./runserver.sh`) TCCP should work properly.
Running locally as if you were in another environment (`DEPLOY_ENVIRONMENT=beta ./runserver.sh`) should result in a 404 for TCCP pages, unless you explicitly enable it by going to http://localhost:8000/admin/flags/TCCP/.
=> TCCP: Feature flag logic to support beta testing

cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/unprocessed/apps/tccp/css/main.less
Assorted visual improvements for TCCP, mostly around the width of form elements.
2. Form fields should be narrower and the "See all cards" link should be next to the submit button instead of under it.
| <img width="1246" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/1060248/d8a5f0fc-0f92-4cfd-b2a9-50124a2161ea"> | <img width="1246" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/1060248/55595877-6363-414c-bfa0-34c216b41ec6"> |
- [This repo’s …
=> Tidy up TCCP form styles

cfgov/tccp/jinja2/tccp/card.html, cfgov/unprocessed/apps/tccp/css/main.less
Clean up card details Jinja to match the other TCCP templates and pulls the inline CSS into the TCCP app's stylesheet.
- You might have to show whitespace changes in the diff view to see some of the cleanup
- I tried to match the Jinja style in the other TCCP templates as best I could, but happy to keep tweaking so everything is consistent
- @contolini, do you think the `.m-list__card-details` variant is the right way to style the card details definition list? I don't have any strong opinions, happy to change to something else.
---
- Jinja formatting cleanup
- Moved inline CSS to TCCP app stylesheet
1. Poke around a few cards' details pages. Everything should match what's currently on DEV4.
- PR titles are used to generate the change log in [releases](../../releases); good ones make that …
=> Card details cleanup

cfgov/tccp/jinja2/tccp/cards.html, cfgov/unprocessed/apps/tccp/css/main.less, cfgov/v1/jinja2/v1/includes/organisms/tables/base.html, cfgov/v1/template_debug/tables.py
Adds our directory table pattern that's already in the DS to our cf.gov table organism template.
Also iterates on our card listing page by using a new directory table variant that sticks the top rows to the viewport when scrolling.
See https://cfpb.github.io/design-system/components/tables#responsive-stacked-table-with-header-directory-table
See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/232
- Replaces the table pattern used on the TCCP all cards page
2. Visit the [all cards page](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/) on a small screen and scroll to see a sticky header.
- Consider …
=> Add directory table pattern to base table template

cfgov/tccp/filterset.py, cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/macros/filter_form.html, cfgov/tccp/serializers.py, cfgov/tccp/situations.py
Instead of filtering by balance transfer fees, we want to filter by whether balance transfers are offered or not.
New logic for "transfer a balance" is:
Filter by:
- Credit score
Sort by:
- Balance Transfer APR by credit tier in ascending order (We show results based on chosen credit tier, use min and max apr as fallback if tier column is empty. This also filters out cards that don't offer a balance transfer APR.)
- Secondary ordering: Purchase APR by credit tier in ascending order
See internal DTUR#235#issuecomment-350326.
=> TCCP: Simplify filtering by balance transfers

cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/tccp/views.py
This commit retitles the TCCP app from
> Explore cards for your situation
to
> Explore credit cards for your situation
For now the URL remains /explore-cards/.
It also updates the landing page link about credit scores to https://www.consumerfinance.gov/ask-cfpb/where-can-i-get-my-credit-scores-en-316/.
=> Retitle TCCP to "Explore credit cards..."

docs/python-unit-tests.md
As of tox v4, this no longer works:
```
tox -e unittest path.to.tests
```
Instead you have to do:
```
tox -e unittest -- path.to.tests
```
See tox documentation here:
https://tox.wiki/en/latest/upgrading.html#cli-arguments-changed
=> Correct Python unit test docs for tox v4

.pre-commit-config.yaml, tox.ini
The ruff linter version 0.3.0 (released 5 days ago) deprecates the usage `ruff <path>` in favor of `ruff check <path>`, see release notes:
https://github.com/astral-sh/ruff/releases/tag/v0.3.0
This fixes the warning that currently appears if you run ruff with the latest version:
```
lint: commands[1]> ruff cfgov
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.
```
=> Fix ruff warning for ruff v0.3.0

cfgov/agreements/jinja2/agreements/archive.html, cfgov/agreements/jinja2/agreements/base_agreements.html, cfgov/agreements/jinja2/agreements/index.html, cfgov/agreements/jinja2/agreements/search.html
- Credit card agreement database: migrate to use standard layout 2-1 template
1. The three agreement templates are as follows. They should largely be unchanged, but you will see when you resize to mobile that the breadcrumbs are in our standard breadcrumb gray box:
Landing page
http://localhost:8000/credit-cards/agreements/
Archive 
http://localhost:8000/credit-cards/agreements/archive/
Individual entry (example)
http://localhost:8000/credit-cards/agreements/issuer/1st-summit-bank/
Before:
After:
=> Credit card agreement database: migrate to use standard layout 2-1 template

cfgov/unprocessed/apps/rural-or-underserved-tool/css/print.less
I can't find any references to the `margin-top-2` CSS class.
- ROUT: Remove unused `container.margin-top-2` print rule
=> ROUT: Remove unused `container.margin-top-2` print rule

cfgov/tccp/jinja2/tccp/card.html
Adds more data to the "purchases" section of the TCCP card details page: purchase APR variability, intro APR, and foreign transaction fee.
---
- Purchase APR variability
- Intro APR
- Foreign transaction fee
- Changed some logic that controls APR display to use `is not none` instead of just checking for truthy values since APRs can be 0 (especially intro APRs)
As with #8177, there are lots of possible variations you can look at. Here are `localhost` links to lots of them.
- [Variable, based on prime index](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/onpoint-community-credit-union-platinum/)
- [Fixed, based on T-bill index](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/state-employees-credit-union-visa-classic/)
- …
=> Add more purchase data to card details

requirements/libraries.txt
`psycopg2` > 2.9.6 causes cf.gov to hang locally for people with on-network Macs, so we'll pin to 2.9.6 for now. See https://github.com/psycopg/psycopg2/issues/1645 and https://github.com/dbt-labs/dbt-core/issues/9303#issuecomment-1864934933 for the details. Huge thanks to @chosak for the super-sleuthing and figuring this out.
---
- Pin psycopg to 2.9.6
If you happen to be on an on-network Mac:
1. Build cf.gov with this PR, `./runserver.sh`, and note the server starts up as normal
2. `pip install psycopg2-binary==2.9.7`, `./runserver.sh`, and note the server hangs when starting up
If you're not on an on-network Mac, build cf.gov and make sure everything works as expected.
- It's not clear when, if, or by whom this bug will ever be fixed (sounds like it's a misconfiguration of GSSAPI), but …
=> Pin psycopg to 2.9.6

cfgov/wellbeing/jinja2/wellbeing/home.html, cfgov/wellbeing/jinja2/wellbeing/results.html
- FWB: convert utility classes to blocks for notifications
1. Visit http://localhost:8000/consumer-tools/financial-well-being/ and http://localhost:8000/consumer-tools/financial-well-being/results/ and see the gap between the notification and the content isn't so tight.
Before:
After:
Before:
After:
=> FWB: convert utility classes to blocks for notifications

cfgov/filing_instruction_guide/jinja2/filing_instruction_guide/index.html
The FIG can have an eyebrow added via Wagtail. If it doesn't have an eyebrow added, however, it gets an empty `<div class="eyebrow"></div>`, which occupies space on the page. This PR wraps that block in a conditional, so that it is only added if it has a value.
- FIG: Add conditional for inclusion of eyebrow block
1. Visit http://localhost:8000/data-research/small-business-lending/filing-instructions-guide/2024-guide/ and edit the page in Wagtail and see that an eyebrow can be added.
Before (has additional padding above h1 for the eyebrow's container):
After:
=> FIG: Add conditional for inclusion of eyebrow block

cfgov/unprocessed/apps/retirement/js/views/tooltips-view.js
There's an existing bug where if you open a tooltip and resize the screen an error will be throw in the dev console. This PR removes the offending code. 
The existing JS also tries to determine the page's padding set in the CSS and match that as the tooltip margin from the edge of the screen. It seems like this could just be hardcoded to a reasonable amount, since the tooltip is floating.
- Remove `[data-tooltip-current-target]` reference on resize, which doesn't reference an element.
- Hardcode padding to 10px.
1. If you visit http://localhost:8000/consumer-tools/retirement/before-you-claim/ and open a tooltip near the left or right corner of the screen, it shouldn't be able to clip the tooltip. 
2. If you open the tooltip and then resize the screen, the tooltip should disappear and …
=> Retirement: tooltip script tweaks

cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/unprocessed/apps/find-a-housing-counselor/css/hud_print.css
- Find-a-housing-counselor: Migrate to layout-full template
1. http://localhost:8000/find-a-housing-counselor/ should be basically unchanged. The one difference should be slightly more space after the social media icons at the bottom of the page.
=> Find-a-housing-counselor: Migrate to layout-full template

cfgov/tccp/jinja2/tccp/card.html
Add balance transfer and cash advance data to TCCP credit card detail pages. Also add a `<title>` element.
---
- Balance transfer data
- Cash advance data
- `<title>`
As with #8198, there are a bunch of variations of the data you can check.
- [Single APR](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/first-security-bank-first-security-bank-visa-cash-back-card/)
- [Min-max (median)](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/golden-1-credit-union-the-member-cash-rewards/)
- [Min-max + median by credit tier](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/los-angeles-police-federal-credit-union-visa-classic/)
- [No transfer offered](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/navy-federal-credi …
=> Add balance transfer and cash advance to card details

cfgov/v1/jinja2/v1/includes/organisms/mortgage-chart.html, cfgov/v1/jinja2/v1/includes/organisms/mortgage-map.html
This PR adds a hyperlink to the Mortgage Chart Block HTML templates to standardize the addition of a "Learn more about the data" link at the end of the "Note" section.
---
1. localhost
2. Navigate to e.g. `/data-research/mortgage-performance-trends/mortgages-30-89-days-delinquent/` and review the "Note" fields on both figures. Note that there should now be _two_ "Learn more about the data" links, as the first one is hard-coded in the Wagtail field
- Once this is live, we will remediate the pages that use this block to remove the hard-coded Wagtail version of the link. …
=> Add data link to mortgage chart template

cfgov/ask_cfpb/tests/test_blocks.py, cfgov/v1/jinja2/v1/includes/blocks/schema/how-to.html, cfgov/v1/jinja2/v1/includes/molecules/related-content.html
This small change adds id slugs as anchors to our How-To schema block headings and our related links headings.
=> Add anchors to related links and how-to headings

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/serializers.py, cfgov/tccp/views.py, cfgov/unprocessed/apps/tccp/css/main.less
This change modifies the TCCP list view so that institution names are listed above product names.
The list view page heading has also been updated to "Customize for your situation".
Run `./frontend.sh` to rebuild your frontend assets. Then visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/ locally.
=> TCCP: Show institution name in list view

cfgov/v1/jinja2/v1/includes/molecules/related-content.html
This quick change restores a closing `</a>` that went missing in #8191 [here](https://github.com/cfpb/consumerfinance.gov/pull/8191/files#diff-bc71fb370e65a3a44b33b57e4f2327711d4b6b8e5ce670fa9f905218e5c1e7dfL49-R54).
=> Restore a lost closing `</a>`

cfgov/tccp/filters.py, cfgov/tccp/filterset.py, cfgov/tccp/jinja2/tccp/macros/filter_form.html, cfgov/tccp/situations.py, cfgov/tccp/templates/tccp/widgets/checkbox_option.html, cfgov/tccp/tests/test_filterset.py, cfgov/tccp/views.py, cfgov/tccp/widgets.py
This commit expands the current "Offers rewards" checkbox into three separate checkboxes allowing users to filter by cards offering different reward types: cashback, travel, and other.
These checkboxes work like an OR: if none are selected, no filter is applied. If one or more are selected, cards with any of the options are shown.
To test, run a local server and visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/. Select the "Earn rewards" option. Then experiment with the rewards checkboxes.
=> TCCP: Add ability to filter cards by reward type

cfgov/unprocessed/apps/tccp/css/main.less
On non-mobile layouts, cards with a lot of states cause the table to poorly render.
1. Visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/ and the table should look better.
| <img width="1203" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/1060248/cf18baa7-7d82-4064-9458-b040d348dd37"> | <img width="1203" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/1060248/7aaf880f-ca29-4d26-8a1a-6dfab5145df4"> |
=> Cap the width of TCCP's card availability column

cfgov/v1/jinja2/v1/includes/atoms/radio-button.html
This change fixes a bug introduced in #8169, which disabled converting unsafe HTML into safe HTML across a large swatch of components. We have some calls to the `radio.render` macro which include HTML in their `label`. This change enables that behavior explicitly by marking the label as safe.
=> Fix radio button label rendering by making it safe

cfgov/v1/jinja2/v1/home_page/_hardcoded_en.html
This small fix marks the hardcoded homepage heading string as safe.
=> Mark homepage strong heading as safe

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/macros/filter_form.html, cfgov/unprocessed/apps/tccp/css/main.less
Adds a spinner to the submit button and dims the results pane when the user changes a filter and a request is in flight. See https://htmx.org/attributes/hx-indicator/
2. Visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/ and change a filter.
3. A spinner will appear in the submit button and the results will dim while the request is being made.
- CFGOV/platform …
=> Add htmx loading indicators to TCCP results

cfgov/data_research/jinja2/data_research/mortgage-performance-downloads.html, cfgov/data_research/models.py, cfgov/v1/jinja2/v1/includes/organisms/mortgage-chart.html, cfgov/v1/jinja2/v1/includes/organisms/mortgage-map.html
Mortgage performance charts and maps use non-breaking space entities and endash entities for formatting in month/years. This fixes the rendering of those entities after #8169 by marking them as safe.
Before:
After:
=> Fix mortgage performance HTML entities

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/macros/filter_form.html, cfgov/unprocessed/apps/tccp/css/main.less
Here's another approach to showing loading state that we can test. Adds a progress bar at the top of the viewport so that users are aware when a request is inflight.
See https://htmx.org/examples/progress-bar/
See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/253
- Sticky progress bar at the top of the viewport.
- The TCCP filter submit button when a user has JS enabled.
- The spinner icon that was in the button.
2. Go to the [card pages](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/) and change some filters.
| mobile | desktop |
| ![linear-spinner-mobile](https://github.com/cfpb/consumerfinance.gov/assets/1060248/72b99881-203a-4331-9f6e-62957d2cf308) | …
=> Add htmx linear progress bar to TCCP results

requirements/docs.txt
The version of PyYAML specified in the docs requirements file is invalid, and as such our docs builds have been failing. This fixes it.
```
pip install -r requirements/docs.txt
mkdocs serve
```
@willbarton I'm not sure what happened here. Your PR #8188 last updated this file and the checks all passed on your PR. Could the `6.0.livereload1` version of PyYAML have been published and then unpublished at some point? I can't seem to find any reference to this release at all.
=> Docs: Fix broken build due to PyYAML version

cfgov/tccp/situations.py, cfgov/tccp/tests/test_situations.py, cfgov/tccp/tests/test_views.py, cfgov/tccp/views.py
This commit improves the logic for handling multiple TCCP situations. The logic is identical with previous, but uses less (and hopefully simpler) Python code to do the same thing.
Run a local server, visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/, and confirm that multiple situation selection continues to work as previously from #8236.
=> TCCP: Multiple situation logic cleanup

cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less, cfgov/unprocessed/apps/regulations3k/css/reg-text.less, cfgov/unprocessed/apps/teachers-digital-platform/css/pages/activity-search.less
`regdown-form_extend` was used in the `regdown.py` file, which no longer exists.
- TDP: `results__full` class.
- iRegs: `regdown-form_extend` class.
- BAH: `arm-info-comparison` class.
1. PR checks should pass. TDP and iRegs should be unchanged.
=> Remove unused css

cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
I didn't find any CSS or other connections to `search_intro`.
- iRegs: Remove `search_intro` class
1. The heading area ("Search regulations") should be unchanged on http://localhost:8000/rules-policy/regulations/search-regulations/results/?regs=1002&q=test
=> iRegs: Remove `search_intro` class

cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html, cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/question-view.js, test/unit_tests/apps/paying-for-college/disclosures/fixtures/overview.js
There doesn't appear to be any CSS attached to the `followup__all` class. With this class removed, the whole div container can be removed
- PfC: Remove `followup__all` class and container.
1. Visit a disclosure test URL: [test url for localhost](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=133465&pid=5287&oid=ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE&totl=45000&tuit=38976&hous=3000&book=650&tran=500&othr=500&pelg=1500&schg=2000&stag=2000&othg=100&ta=3000&mta=3000&gib=3000&wkst=3000&parl=14000&perl=3000&subl=15000&unsl=2000&ppl=1000&gpl=1000&prvl=3000&prvi=4.55&prvf=1.01&insl=3000&insi=4.55&inst=8&leng=30)
2. Click through the app to the final screen and see that the "What you can do" sidebar is unchanged.
=> PfC: Remove `followup__all` container

cfgov/cfgov/settings/base.py, cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/tccp/jinja2/tccp/includes/filter_form.html, cfgov/tccp/tests/test_views.py, cfgov/tccp/views.py, requirements/libraries.txt
This commit adds the ability to request a "partial" rendering of the TCCP list view, including only the results portion. This is intended to support better AJAX-based updates of the page.
To test, run a local server. Visit
http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/ and then try visiting
http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/?partial=1
TODO: @contolini we still need to modify the form to append `?partial` to the URL when being requested via AJAX. It'd be nice if there were a way to use [`hx-boost`](https://htmx.org/attributes/hx-boost/) with an alternate URL, but I'm not sure that's possible. Should we use JS to somehow alter that param on page load?
=> TCCP: Add "partial" page fragment results view

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/unprocessed/apps/tccp/css/main.less, cfgov/unprocessed/apps/tccp/js/index.js
Adds a "show more" button that hides table rows > 10.
See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/244
2. Go to the [cards page](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/), scroll down and click the red link.
=> Hide surplus TCCP card results behind a "show more" button

cfgov/cfgov/settings/base.py, cfgov/tccp/jinja2/tccp/card.html, cfgov/unprocessed/apps/tccp/css/main.less
Cleans up a few things on the card details page ahead of usability testing.
---
- `TCCP_DEBUG_DETAILS` feature flag
- Table of all card fields
- `a-card-url` class and style; #8252 makes an app-specific style redundant
- Institution name is now an eyebrow instead of part of the main heading
- "Availability" section is now "Application requirements"
- "Secured card" is now "Down payment required?"
2. From http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/, check a few cards to make sure:
- The institution name is in an eyebrow above the `h1`
- "Availability" section is now "Application requirements"
- "Secured card" is now "Down payment required?"
- The table with all the card fields in it is gone
- [Long …
=> TCCP: Clean up card details

cfgov/tccp/jinja2/tccp/includes/card_list.html
This commit changes the HTML for the TCCP results view page so that the card rating key is more semantic.
Instead of using a list of `spans`, use a `dl`.
Key continues to look like this:
=> TCCP: Make card rating key more semantic

cfgov/unprocessed/apps/tccp/js/index.js
Enabling the htmx cache busting config option appends `org.htmx.cache-buster=true` to URLs that are fetched by htmx, causing them to be viewed as separate destinations to Akamai.
2. Go to the [cards page](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/) and click some filters.
3. View the network activity in dev tools and you should see that the XHR URLs have `org.htmx.cache-buster=true` appended to them.
=> Enable htmx cache busting for TCCP requests

cfgov/teachers_digital_platform/tests/models/test_activity_index_page.py, cfgov/v1/jinja2/v1/layouts/base.html
This PR changes how canonical links are generated in `base.html`, specifically it strips the querystring. Across all the pages I audited (perhaps non-exhaustive) the querystring is simply used as a filter or as a way to track specific selections. The whole point of canonical links is to collate these views of the same page into one... canonical link... that google can then reference and give more link equity to, instead of diffusing it across N pages (where N is the number of pages in a filterable list or w/e).
- Pull
- Load various pages
- On pages without querystrings, the canonical link should be unchanged
- On pages WITH querystrings, eg, [this one](http://localhost:8000/about-us/blog/?title=&topics=access-to-credit&from_date=&to_date=), the canonical link should have the querystring …
=> Remove querystring from generated canonical links

cfgov/jinja2/rural-or-underserved/index.html
Migrates Rural or Underserved Tool to our standard landing-page template (which extends layout-2-1).
- Migrate ROUT to landing-page template
1. Visit http://localhost:8000/rural-or-underserved-tool/ and compare to production across screen sizes.
Fixes some page footer spacing weirdness
Before:
After:
=> ROUT: Migrate to landing-page template

cfgov/v1/jinja2tags/__init__.py
#8113 removed the ResourceList template but left behind the `get_model` Jinja tag that [had been created for it](https://github.com/cfpb/consumerfinance.gov/commit/6c2ac2b499a82970eb7d6ff3ee8e640fedbf237b#diff-02618be188a8919b4ad1e0c4c7d1487c2e46ad25bf09ccae90b477741cf91236). This tag isn't used elsewhere in the codebase and can be removed.
=> Remove unused v1.jinja2tags.get_model

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/includes/filter_form.html, cfgov/unprocessed/apps/tccp/js/htmx.js, cfgov/unprocessed/apps/tccp/js/index.js, esbuild/scripts.js, test/cypress/integration/consumer-tools/credit-cards/explore-cards-helpers.cy.js, test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js
Adds two htmx extensions: One that adds an `htmx` query param to URLs immediately before htmx makes a request and then removes it before pushing it to the browser's history. This allows endpoints fetched via AJAX to have a URL that is different from their host page's URL, (hopefully) solving our Akamai issues. The second extension stores the filter page's
pathname to web storage so that our breadcrumbs can later retrieve it.
I also added a few cypress tests to detect future regressions.
1. Visit the [cards page](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/) and open the dev tools network tab. Notice that when you change filters, the AJAX requests have `htmx=true` query params but the page's URL does not.
1. Type …
=> Add TCCP htmx extensions to handle cache busting and filter tracking

cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/tccp/views.py
- Remove breadcrumbs on TCCP landing page
- Style subheading as h2, not h3
For context, visit internal DTUR#265.
To test, run a local server, visit:
http://localhost:8000/consumer-tools/credit-cards/explore-cards/
=> TCCP: Landing page tweaks

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/tests/test_views.py, cfgov/tccp/views.py, cfgov/unprocessed/apps/tccp/js/index.js, test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js
Adds breadcrumbs to the card details page and progressively enhances them with JavaScript so the breadcrumb that points back to the card list will take you to the specific filtered list you came from.
We have to update that breadcrumb client-side because there's a chance Akamai may cache a version of the page with a breadcrumb to a specific filtered list if we do it on the backend, see #7108 for details. I'm comfortable making this enhancement here even though we chose to remove it in other places. A primary goal of the TCCP tool is to help users compare different cards that meet their needs, so we're actually **hoping** they'll go from a filtered list to card details back to the filtered list and so on to look at a number of different cards. Most people will use the back button for that, …
=> TCCP: Add breadcrumbs to card detail page

cfgov/unprocessed/css/molecules/global-search.less
https://github.com/cfpb/consumerfinance.gov/pull/8043 removed the `m-btn-inside-input` class from the global search markup, which was used to adjust the button size in non-english search buttons. This PR removes that class from the global search CSS and uses `line-height` instead of flexbox to align the non-english search buttons with their inputs.
- Remove unused `m-btn-inside-input` CSS from global search.
- Set `line-height` on the search trigger and button to accommodate x-height differences in non-english typefaces.
1. Visit http://localhost:8000/language/zh/ and click through the language links at the top of the page and check that the button and input are aligned correctly across screen sizes.
Before:
After:
=> Global search: fix misalignment in non-english search text

cfgov/login/forms.py
Wagtail [no longer marks error messages as safe by default](https://github.com/wagtail/wagtail/blob/e425244fd8a225dda2ca840d8dd3fa0b03d95243/wagtail/admin/templates/wagtailadmin/login.html#L12-L24), which has broken a link we've had in our custom password expiration error message for a while. This PR just marks that error message as safe so the link renders correctly.
---
- Mark our custom password expiration error message as safe so the link to the reset password page renders
1. Try logging in at localhost:8000/admin/login/ with a user who has an expired password (or you can change `if timezone.now() - latest_password.created >= timedelta(` to `if timezone.now() - latest_password.created <= timedelta(` in cfgov/login/forms.py line 40 to trigger the message on any non-expired login)
2. …
=> Mark password expired error message as safe

cfgov/unprocessed/css/molecules/inset.less, cfgov/v1/jinja2/v1/includes/organisms/full-width-text.html
Fixes an issue where inset email signups spilled off the page margin.
- Remove custom email signup CSS and wrap email inset with a top-flushed `block` and `well`.
1. `yarn build` and visit any non-BAH page (they have their own issues) with an inset email signup, such as https://www.consumerfinance.gov/compliance/compliance-resources/signup/, and resize the page to see that the email signup is not clipped.
Before:
After:
=> Inset email: Remove custom email signup CSS

cfgov/tccp/filterset.py, cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/includes/filter_form.html, cfgov/tccp/tests/test_widgets.py, cfgov/tccp/widgets.py, cfgov/unprocessed/apps/tccp/js/index.js, test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js
To increase the sorting dropdown's visibility, move it outside the expandable. To accommodate no-JS users, it's moved via JS instead of at the template level.
The `load` event listener was replaced with `DOMContentLoaded` because our JS only needs to wait for the DOM to load and not all images, stylesheets, etc.
See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/241
@chosak `form="tccp-filters"` gets added to all `select` elements but it technically only *needs* to be on the sorting select element. It's harmless but lmk if you'd prefer I create a separate widget for the sorting element.
1. Visit the [cards page](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/) and you'll see the sort dropdown is below the expandable when JS is …
=> Move TCCP card sorting dropdown below filters' expandable

cfgov/v1/jinja2/v1/includes/molecules/feature-card.html, cfgov/v1/jinja2/v1/includes/organisms/feature-cards.html
- Indent featured cards markup.
- Remove unimplemented `value.category.aria_label` from code comment.
- Remove empty `class=""` from link.
- Remove unused `ask-categories` class.
1. Visit http://localhost:8000/ask-cfpb/ and it should be visually unchanged. 
- These featured cards should probably go inside the ask_cfpb app, as they are only used on the Ask landing pages, and the CSS associated with them (aside from the card classes) lives in Ask only.
- This seems like it just about could use the existing `card-group.html` template. We should probably consider either elevating the ask cards to the Design System, or changing the ask cards to the existing featured card from the Design System.
- We should probably find a way to make the cards `h3`s, like the other cards on the site. There is …
=> Ask CFPB: Featured cards tidying

cfgov/ask_cfpb/jinja2/ask-cfpb/ask-answer-content.html, cfgov/ask_cfpb/tests/test_blocks.py, cfgov/unprocessed/css/on-demand/ask.less
The expandable cue CSS I suspect predates the summary component.
- Ask: Remove `inset-row`, `video_player-row`, `content_sidebar`
- Ask: Remove `o-expandable_cue-close` custom CSS.
1. Search the crawler for `video_player-row`, which will give you the video player pages, such as http://localhost:8000/ask-cfpb/i-cant-make-my-mortgage-payments-how-long-will-it-take-before-ill-face-foreclosure-en-1849/ and see that the video player has existing space above it.
2. Search the crawler for `inset-row`, which will give you a list of pages with an inset tip, such as http://localhost:8000/ask-cfpb/i-want-to-submit-a-complaint-about-an-international-money-transfer-what-should-i-do-en-1753/ and see that the tip doesn't reverse positions at mobile.
=> Ask CFPB: Remove `inset-row`, `video_player-row`, `content_sidebar`

cfgov/v1/jinja2/v1/includes/organisms/sidebar-contact-info.html
These two classes don't have any CSS associated with them.
- Remove unused `o-sidebar-contact-info_heading` and `o-sidebar-contact-info_contacts`
- Update sidebar-contact-info code comments.
1. The contact info at the bottom of http://localhost:8000/cfpb-ombudsman/ombudsman-resources/ should be unchanged in appearance from production (but it will have less nested markup).
=> Remove unused `o-sidebar-contact-info_heading` and `o-sidebar-contact-info_contacts`

cfgov/tccp/filter_backend.py, cfgov/tccp/filters.py, cfgov/tccp/filterset.py, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/tccp/models.py, cfgov/tccp/serializers.py, cfgov/tccp/tests/test_filters.py, cfgov/tccp/tests/test_filterset.py, cfgov/tccp/tests/test_models.py, cfgov/tccp/tests/test_views.py, cfgov/tccp/views.py
This PR makes some substantial changes to how the TCCP app filters, orders, and rates cards by purchase APR.
Some credit cards offer a purchase APR for a specific credit tier but are not marked as being "specifically targeted" to that credit tier, recorded in the TCCP survey under the "Targeted credit tiers" column. Previously TCCP filter results would include these cards, so if a user marked their credit tier as 620-719, they might see cards that, while they offer a purchase APR for this range, are not marked as being "specifically targeted" to this range. This PR removes those cards from the results.
This PR also modifies which cards are included in TCCP filtering results by expanding the purchase APR logic. Previously, we would only include cards that had a tier-specific purchase APR, …
=> TCCP: Changes to card filtering and purchase APR logic

cfgov/regulations3k/jinja2/regulations3k/regulations3k-secondary-nav.html, cfgov/unprocessed/apps/regulations3k/css/reg-navigation.less, cfgov/v1/jinja2/v1/includes/organisms/expandable.html
The change introduced in https://github.com/cfpb/consumerfinance.gov/commit/51f8662800884863004932829d7c375893d3cdf8, broke the regs3k secondary nav. This restores the previous appearance (but with better expandable button alignment ^_^)
Current:
With this PR:
=> Fix regs secondary nav for ds@0.43.0

cfgov/tccp/fields.py, cfgov/tccp/tests/test_fields.py
Commit b4121bb1e0a3248afc2d63f887e02ea7997ca2a9 modified some of the TCCP dataset columns, changing them from strings to decimal values. This broke import of the last dataset. This change fixes that.
To test:
1. Download current dataset from https://files.consumerfinance.gov/f/documents/cfpb_tccp-data_2023-01-01_2023-06-30.xlsx
2. Run `cfgov/manage.py import_tccp cfpb_tccp-data_2023-01-01_2023-06-30.xlsx`. Confirm that the dataset loads with no errors.
=> TCCP: Fix import command of currency values

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/unprocessed/apps/tccp/js/htmx.js, cfgov/unprocessed/apps/tccp/js/index.js, cfgov/unprocessed/apps/tccp/js/ordering.js, test/cypress/integration/consumer-tools/credit-cards/explore-cards-helpers.cy.js, test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js
Moves the "Sort by" dropdown immediately above the list of card results. This section of the page is swapped out by htmx so we have to re-inject the element after every htmx update.
See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/271
1. Visit the [cards page](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/) and you should see the sort by dropdown under the APR key.
1. `yarn cypress run --spec test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js`
| <img width="468" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/1060248/6c0458c3-59f4-414e-8b99-c21f0ea46111"> | <img width="468" alt="image" …
=> TCCP: Move "Sort by" widget into the card results pane

cfgov/tccp/filters.py, cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/tccp/jinja2/tccp/situations/results/avoid-fees.html, cfgov/tccp/jinja2/tccp/situations/results/build-credit.html, cfgov/tccp/jinja2/tccp/situations/results/earn-rewards.html, cfgov/tccp/jinja2/tccp/situations/results/make-a-big-purchase.html, cfgov/tccp/jinja2/tccp/situations/results/pay-less-interest-make-a-big-purchase.html, cfgov/tccp/jinja2/tccp/situations/results/pay-less-interest.html, cfgov/tccp/jinja2/tccp/situations/results/transfer-a-balance.html, cfgov/tccp/situations.py, cfgov/tccp/tests/test_situations.py, cfgov/tccp/views.py, cfgov/unprocessed/apps/tccp/css/main.less, cfgov/unprocessed/apps/tccp/js/index.js, test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js
This PR modifies the TCCP results view in a few ways: it reorders the introductory content, migrates that content from wells to a bulleted list, and adds rating-specific result counts.
See internal Figma for latest comps, and internal DTUR#271 for context.
To test, first rebuild your local assets with `./frontend.sh`. Then run a local server and visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/. Experiment with selecting multiple scenarios to see how the results change. Also visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/ without any scenarios to see how that looks.
- ~~The "sort by" disappears when we make a new AJAX request; I need to rebase this against @contolini #8302 once that is merged, so marking this PR as draft for now.~~ Done.
- …
=> TCCP: Results redesign based on round 2 testing

cfgov/unprocessed/apps/teachers-digital-platform/css/molecules/search-hero.less, cfgov/unprocessed/apps/teachers-digital-platform/css/pages/activity-search.less
Flexbox has wide browser support. This was maybe there for IE9?
- TDP: Remove `@supports` checks for flexbox
1. On http://localhost:8000/consumer-tools/educator-tools/youth-financial-education/teach/activities/ the hero and search results `activity_meta-wrapper` blocks should have a flexbox layout, as they do in production currently.
=> TDP: Remove `@supports` checks for flexbox

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/serializers.py
Adds APR ratings to the credit card details page. Also shows the APR-by-credit-tier table for all cards instead of just for those with tier-specific APRs as a way to show ratings for cards that have a single median or a single APR.
There's so much refactoring we can do here to get a lot of the messy logic out of the Jinja template and reuse pieces across the list and detail views. I figured I'd open this PR in case we want to get APR ratings in quickly for testing and refactor later. If we don't need to go to testing as soon, we can refactor this now, either in this PR or a new one.
---
- Purchase APR ratings to card details
- Purchase APR-by-credit-tier tables now show for all cards as a way to show the ratings for cards that have a single median or just one APR for everyone
I tried to …
=> TCCP: Add APR ratings to TCCP details page

cfgov/tccp/jinja2/tccp/card.html
Adds a "did you know" callout about small banks and credit unions and links to some Ask CFPB questions to the card details page.
---
- "Did you know" callout
- Links to Ask CFPB questions
- Fixed a couple of typos
1. Look at the details page of a card from a small institution (i.e. one where `top_25_institution == false`) and confirm the "did you know" callout looks like the screenshot below. Then look at a card from a top-25 institution and confirm the callout doesn't show up.
2. Make sure the links all point to the correct Ask CFPB question.
- We'll revise which Ask questions we link to (and maybe add more) after user testing
- Depending on how similar we want the wording of the small institutions callout to be between the card list and card details, we might want to refactor the …
=> TCCP: Add links and tips to card details

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/unprocessed/apps/tccp/css/main.less
Changes the size of some headings, adds a link back to the landing page, and changes the eligibility requirements text. Also speed bumps are teal now.
See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/291
1. Visit the [cards page](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/) and things should look a little different. You'll see a new `Choose what you're looking for in a card` that reads `Change what you're looking for in a card` if you selected a situation on the landing page.
1. `yarn cypress run --spec test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js`
| <img width="433" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/1060248/1d …
=> TCCP: Assorted visual and content improvements

cfgov/v1/atomic_elements/atoms.py, cfgov/v1/tests/atomic_elements/test_atoms.py, requirements/libraries.txt
`URLOrRelativeURLBlock` was added in https://github.com/cfpb/consumerfinance.gov/commit/f1e99cb734246fef46a4f8241a8e7a2995c4b32d and used in `HighlightCardBlock`, which was later removed in https://github.com/cfpb/consumerfinance.gov/commit/48ad711103a36da36a683086c32f8db3a74fa71f
- Remove unused `URLOrRelativeURLBlock`, tests, and related `django-url-or-relative-url-field` dependency
=> Remove unused `URLOrRelativeURLBlock`

cfgov/tccp/jinja2/tccp/card.html
Couple of small tweaks to the TCCP card details page for testing. The APR ratings element is not correctly BEM'd yet; we're going to refactor that to use the same macro across the list and details views in a subsequent PR, so I just made it look right for testing for now.
---
- Fixed APR rating colors
- "Other requirements for applying" heading is now "Eligibility requirements" to match how we refer to those in the results list
1. Make sure APR rating dollar signs are the right colors on the card details page
2. Make sure the heading before the list of other requirements is now "Eligibility requirements"
- As mentioned above, refactor the `card_rating` element to be a macro that can be shared by both the card list and details views
- PR titles are used to generate the change log in …
=> TCCP: Tweak a few card detail details

cfgov/v1/atomic_elements/organisms.py
`AskSearch` was used in `WellWithAskSearch`, which was added in https://github.com/cfpb/consumerfinance.gov/pull/5230/ and removed in https://github.com/cfpb/consumerfinance.gov/commit/f2067960135362dc2ca560db0c4a814180c66b80
- Remove `AskSearch`
=> Remove unused `AskSearch`

cfgov/tccp/models.py, cfgov/tccp/tests/test_models.py
This commit changes the TCCP percentile computation to exclude cards that only include min-max purchase APRs. It also changes our percentile ratings from 25th/50th to 25th/75th.
See internal DTUR#289 for context.
To test, you can run a local server and compare against our beta testing site. Look at the JSON output of e.g.
http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/?credit_tier=Credit%20score%20of%20720%20or%20greater&location=&ordering=purchase_apr&format=json
You'll see that with this change we now compute purchase_apr_poor_pct75 instead of purchase_apr_poor_pct75.
=> TCCP: Percentile computation updates

cfgov/v1/jinja2/v1/layouts/layout-2-1.html, cfgov/v1/jinja2/v1/layouts/layout-full.html
Pages like https://www.consumerfinance.gov/compliance/compliance-resources/ have an empty content_intro block, but it does contain whitespace, so it is passing the check on whether the block is empty, which leads to an empty `<div class="u-layout_content-intro"></div>` block on the page. This PR aims to strip out the whitespace on the check, so it is only included if it actually has non-whitespace content.
- Strip whitespace for template block content checks
1. http://localhost:8000/compliance/compliance-resources/  should not have an empty `<div class="u-layout_content-intro"></div>` block.
=> Strip whitespace for template block content checks

cfgov/v1/jinja2/v1/includes/organisms/expandable.html
Whoops, https://github.com/cfpb/consumerfinance.gov/pull/8295 removed the `o-expandable_icon` class, which busts the styles for padded expandables that have icons.
- Bugfix: re-add `o-expandable_icon` class
1. `yarn build` and visit http://localhost:8000/learnmore and compare to production
Before:
After:
=> Bugfix: re-add `o-expandable_icon` class

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/landing_page.html
AFAIK the left-hand text should be aligned. This was getting indented by the extra `content_wrapper` container. Also, the last block should have greater space between the content and the footer.
- Remove `content_wrapper` container.
- Change ending blocks to `block__flush-top` instead of `block__sub`
1. Visit TCCP landing page and see that left edge of the text aligns across the hero and the content area. Also, check the bottom of the content on the landing page and search results page and see that the gap between the content and the footer has been increased (see screenshots).
Before:
After:
Before:
After:
=> TCCP: Adjust container padding

cfgov/tccp/jinja2/tccp/includes/filter_form.html
The hidden form fields conflict with a `last-child` CSS rule. Moving them to the start of the form fixes the issue. The order of all the form fields doesn't matter to the server.
1. Check the bottom of the expandable.
1. The Cypress GHA tests should pass.
| <img width="1166" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/1060248/8381d7c7-e5d7-4419-8cdf-3838ff5597ed"> | <img width="1166" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/1060248/5c138cfb-102c-403a-a942-d9cf4a5ef021"> |
=> TCCP: Move location of hidden fields to fix padding bug

cfgov/tccp/jinja2/tccp/card.html
Fixes a bug that made all cards show that they had no grace periods.
---
- Fix grace period logic
1. Check that a card that does have a grace period (like [this one](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/interra-credit-union-standard-mastercard/), although almost all of them do) lists it in the other details expandable in the making purchases section. It should say something like "25 days until interest begins to accrue on purchases"
2. Make sure that cards that don't offer a grace period, like [this one](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/credit-human-federal-credit-union-rate-preferred-mastercard/), still say "None, interest begins accruing on purchases immediately"
- PR titles are used to generate the change log in …
=> TCCP: Fix grace periods in card details

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html, cfgov/regulations3k/models/pages.py, cfgov/v1/jinja2/v1/layouts/base.html
Currently the canonical link in iregs, no matter the regulation version being viewed, is just set to the current URL. Analytics pointed out it would make more sense if the canonical link was set to the current regulation. This PR does that (and does so for the open graph url as well).
=> Set canonical links to current reg/section in iregs

cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
These classes appear in the markup only and appear to be unused.
- Remove unneeded empty results classes.
1. http://localhost:8000/rules-policy/regulations/search-regulations/results/?regs=1002&q= vs https://www.consumerfinance.gov/rules-policy/regulations/search-regulations/results/?regs=1002&q= should be unchanged.
=> iRegs: Remove unneeded empty results classes

cfgov/tccp/templates/tccp/widgets/checkbox_select.html, cfgov/tccp/widgets.py
The cf.gov upgrade to Django 4.2 broke rendering of multiple checkboxes, removing the intended space between them. This was due to this Django commit:
https://github.com/django/django/commit/5942ab5eb165ee2e759174e297148a40dd855920
which added `<div></div>` wrappers around each select option. This broke our expected markup per our design system:
https://cfpb.github.io/design-system/components/fieldsets#sizes-1
|Before|After|
|-|-|
|<img width="493" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/58752975-f024-4381-afe3-07b7d3a46d20">|<img width="497" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/cb912927-6515-43ca-9791-d313cb53f8d1">|
=> TCCP: Fix multiple checkbox rendering

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/jinja2/tccp/includes/data_published.html, cfgov/tccp/jinja2/tccp/includes/fields.html, cfgov/unprocessed/apps/tccp/css/main.less
Make some design tweaks to the card details page. See https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/272 for more details.
---
- The "data published" info now comes in two flavors: a compact version for the list view and a more verbose version for the details view
- Section headings are now H2 on desktop and H3 + demi-bold on mobile
- Expandables are now gray
- All APR-by-credit-tier tables now only show rows for targeted credit tiers
- Any 0% APRs now show as "0%" instead of "0.00%"
Generally everything should look like the screenshots below. You may want to check some cards with tier-specific median APRs to make sure the APR tables are only showing rows for targeted credit tiers, like:
- [1](http://localhost:8000/consumer-tools/credit-cards/explore-cards …
=> TCCP: Tweak design of card details page

cfgov/tccp/jinja2/tccp/landing_page.html
This commit adds a missing underline to the link on the landing page that says "find your credit score".
To test, visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/.
|Before|After|
|-|-|
|<img width="380" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/a2454e27-c0f5-4c9a-b927-2c1b9aaf5af3">|<img width="381" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/e6983b6b-f4c4-4f8f-9ffd-e53285f7e205">|
=> TCCP: Underline link on landing page

cfgov/tccp/jinja2/tccp/about.html, cfgov/tccp/management/commands/validate_tccp.py, cfgov/tccp/models.py, cfgov/tccp/tests/test_models.py, cfgov/tccp/tests/test_validate.py, cfgov/tccp/views.py
This commit modifies the TCCP "Explore credit cards" tool to exclude cards from the search results if they fail certain validation checks:
1. {purchase, transfer}_apr_great > {purchase, transfer}_apr_good
2. {purchase, transfer}_apr_good > {purchase, transfer}_apr_poor
3. {purchase, transfer}_apr_great > {purchase, transfer}_apr_poor
4. {purchase, transfer}_median > {purchase, transfer}_max
5. {purchase, transfer}_min > {purchase, transfer}_max
6. {purchase, transfer}_min > {purchase, transfer}_median
These cards are still available at a detail page URL but will not appear in search results.
A sentence mentioning this has been added to the "About this tool" page available locally at
http://localhost:8000/consumer-tools/credit-cards/explore-cards/about/.
Additionally, the TCCP dataset …
=> TCCP: Exclude cards with inconsistent APRs

cfgov/v1/jinja2/v1/includes/organisms/secondary-nav-fig.html
I don't see any CSS attached to `a-tag__dark`
- FIG: Remove dark tag `a-tag__dark` class
1. Visit https://www.consumerfinance.gov/data-research/small-business-lending/filing-instructions-guide/2024-guide-archive-v2/ and see `a-tag__dark` can be removed with no effect.
=> FIG: Remove dark tag modification

cfgov/unprocessed/css/on-demand/ask.less
Ask pages shouldn't have an h4 outside of a tip. If they do, the page should be opened, saved and re-published.
- Remove ask h4 custom margin
1. PR checks should pass. Pages like http://localhost:8000/ask-cfpb/can-a-debt-collector-take-my-social-security-or-va-benefits-en-1157/ shouldn't have a large gap before the h4 in the embedded tip.
=> Remove ask h4 custom margin

Dockerfile
This change adds the requirements to build numpy/matplotlib to our cfgov-python-builder container.
`docker-compose build python` should succeed.
=> Add requirements to build numpy/matplotlib

cfgov/teachers_digital_platform/models/activity_index_page.py
Currently, when bingbot is hitting pages WITH facets that are globally valid (1 - 14) but are invalid for that result set. This results in `EmptyPage` errors.
To swallow these, this simply sets the current page to the `num_pages` before attempted to pull an out of bounds page from the paginator.
http://localhost:8000/consumer-tools/educator-tools/youth-financial-education/teach/activities/?page=5&grade_level=4&grade_level=5 should render page 4 of the results instead of throw an `EmptyPage` error
=> Max out current_page at `num_pages`

cfgov/tccp/enums.py, cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/jinja2/tccp/includes/apr_table.html, cfgov/tccp/models.py, cfgov/tccp/serializers.py, cfgov/tccp/tests/test_models.py, cfgov/tccp/views.py
This commit consolidates some of the Jinja logic in the TCCP card details page. It creates a new `apr_table` macro to remove some of the duplication in the current details page. It also avoids the need to hardcode the various credit tiers in the template, instead reusing the values from the backend.
There is more cleanup and consolidation to be done on this page, and this is just a first iteration.
To test, run a local server and visit cards under http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/.
Past PRs iterating on this page are a good place to see example URLs to test:
https://github.com/cfpb/consumerfinance.gov/pulls?q=is%3Apr+author%3Aniqjohnson+is%3Aclosed
@niqjohnson this could definitely use your Level 5 JinjaStar eyes on it. I've tried to go through a …
=> TCCP: Card details page template consolidation

cfgov/ask_cfpb/tests/test_hooks.py, cfgov/ask_cfpb/wagtail_hooks.py, cfgov/unprocessed/css/on-demand/ask.less, cfgov/wagtailadmin_overrides/static/css/question-tips.css
`answer-module` has been removed and replaced with the inset tip on Ask pages. 
- Remove `answer-module` CSS
=> Ask CFPB: Remove `answer-module` CSS

cfgov/unprocessed/css/breadcrumbs.less
- Remove unneeded `m-breadcrumbs__crumbs` CSS.
- Remove unneeded `.content__wrapper .m-breadcrumbs` rule.
1. The only place a breadcrumb appears inside `content__wrapper` is on http://localhost:8000/owning-a-home/explore-rates/. After running `yarn build`, see that the breadcrumb is unaffected across screen sizes on that page.
We have a `m-breadcrumbs__crumb` class that has no styles attached to it. However, the breadcrumb can either be a `a` or `span` element, and this class is referenced in JS in TCCP and in cypress tests, so I decided to leave it so that the crumb can be referenced independent of the underlying HTML element in use.
=> Remove unneeded breadcrumbs CSS

cfgov/v1/jinja2/v1/includes/molecules/hero.html, cfgov/v1/jinja2/v1/landing-page/index.html
Currently, pages with heroes don't get `translation-links` like pages with item introductions or text-introductions. This PR changes that, rendering these links if they exist (english versions of translated pages set in the wagtail config).
- Get a recent dump
- Visit https://www.consumerfinance.gov/consumer-tools/ and notice no links
- Compare with http://localhost:8000/consumer-tools/ and notice the links
- Pages with heroes (or jumbo heroes) and no linked translations (like the homepage at http://localhost:8000) should not render any new markup
=> Add translation links to the hero

cfgov/v1/jinja2/v1/layouts/layout-2-1.html, cfgov/v1/jinja2/v1/layouts/layout-full.html
https://github.com/cfpb/consumerfinance.gov/pull/8164 set the class `u-layout_content-intro` in the markup, but it should have been a block of `u-layout-grid`, and with BEM updates should be `u-layout-grid__content-intro`
- Update `u-layout_content-intro` to `u-layout-grid__content-intro`
1. Inspect https://www.consumerfinance.gov/ask-cfpb/ vs http://localhost:8000/ask-cfpb/ and see that this branch adds `max-width: 41.875rem;` to the paragraph in the hero.
=> Bugfix: Update `u-layout_content-intro` to `u-layout-grid__content-intro`

cfgov/wellbeing/jinja2/wellbeing/results.html
- Wellbeing: fix BEM elements and modifiers.
1. Visit http://localhost:8000/consumer-tools/financial-well-being/ and fill out the form and go to the results page and make sure the chart looks un-broken.
Before:
After:
=> Wellbeing: fix BEM

cfgov/unprocessed/apps/rural-or-underserved-tool/css/print.less
This class appears unused.
- ROUT: Remove `super` class
=> ROUT: Remove `super` class

cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/13-school-results.html, cfgov/paying_for_college/jinja2/paying-for-college/disclosure.html, cfgov/unprocessed/apps/paying-for-college/css/cf-enhancements.less, cfgov/unprocessed/apps/paying-for-college/css/college-costs/number-callout.less, cfgov/unprocessed/apps/paying-for-college/css/disclosures.less, cfgov/unprocessed/apps/paying-for-college/css/print.css
These classes appear to be unused.
- PfC: Remove unused classes: `btn`, `btn-close`, `btn__cohort`, `hero--intro`, `change-list`, `number-callout--divisor`, `aid-form__caption`, `aid-form--time`, `question__controls`, `continue__answers`
1. PfC disclosure tool should be unchanged.
- There are other classes in the markup that are unused, such as `cost-of-attendance`, `private-loans-group`, `tuition-payment-plan`, but I've left them for now.
=> PfC: Remove unused classes

cfgov/unprocessed/apps/retirement/css/claiming.less, cfgov/unprocessed/apps/retirement/js/views/graph-view.js, cfgov/unprocessed/apps/retirement/js/views/questions-view.js
- Removes unused `thank-you` class.
- Remves unused `helpful-btn` class.
-  Update `lifestyle-btn__active` to `lifestyle-btn--active` modifier.
- Update `notification-input__warning` to `notification-input-warning` block.
1. http://localhost:8000/consumer-tools/retirement/before-you-claim/ should show golden border around age inputs when date is incorrect (put in letters, for example).
=> Retirement: BEM fixes

cfgov/unprocessed/css/on-demand/event.less, cfgov/v1/jinja2/v1/events/_event-detail.html, cfgov/v1/jinja2/v1/events/_macros.html
Additional cleanup followup to https://github.com/cfpb/consumerfinance.gov/pull/8274 + refactoring to remove unnecessary classes.
- Update BEM class names in the events templates.
- Remove `post` classes and replace with standard `block` classes. 
- Increase padding in modified date pill so it doesn't look so squashed vertically.
- Increase bottom margin on social media block, so it's not up against the description.
- Merge `event-meta__description--text` into `event-meta__description`.
- Remove unused `event-venue_live-btn_text` class.
1. Visit an event, such as http://localhost:8000/about-us/events/spring-2024-consumer-advisory-board-meeting/, and compare to production.
Before:
After:
=> Events page: BEM fixes + refactor to remove bespoke layout classes

cfgov/v1/jinja2/v1/includes/macros/time.html, test/cypress/integration/components/filterable-lists/filterable-list-control-helpers.cy.js
There are no styles associated with these elements.
- Remove unused `datetime` elements, `datetime_date`, `datetime_divider`, `datetime_time`
=> Remove unused `datetime` elements

cfgov/v1/jinja2/v1/includes/blocks/email-signup.html, docs/functional-testing.md, test/cypress/integration/components/email-signup/email-signup-helpers.cy.js, test/unit_tests/mocks/emailSignupSnippet.js
This class appears to be unused, other than as a reference in the tests, which can have their query written another way.
- Remove `o-form__email-signup`
=> Remove `o-form__email-signup`

cfgov/core/tests/test_utils.py, cfgov/core/utils.py
Additional cleanup followup to https://github.com/cfpb/consumerfinance.gov/pull/8274 
The link with an icon middleware was adding the old-style BEM classes. This PR updates them to the new style.
- Update `a-link_text` to `a-link__text`
- Update `a-link__icon` to `a-link--icon`
- Update `a-btn_icon a-btn_icon__on-right` to `a-btn__icon a-btn__icon--on-right`
1. PR checks should pass. A page such as http://localhost:8000/consumer-tools/retirement/before-you-claim/about/ should have links with an external link icon that do not have the underline under the icon.
Before:
After:
=> Update link middleware to getBEM style

cfgov/ask_cfpb/jinja2/ask-cfpb/answer-search-results.html
- Ask: Migrate `question_summary` to `question__summary` and `question_title` to `question__title`
1. Ask search results should look more formatted than prod http://localhost:8000/ask-cfpb/search/?q=mortgage
=> Ask: Migrate `question_summary` to `question__summary` and `question_title` to `question__title`

cfgov/regulations3k/jinja2/regulations3k/search-regulations.html
https://github.com/cfpb/consumerfinance.gov/commit/9d49f38de5c2e44d5d6f1477c3999300b1a5c5bc#diff-bd7e59eefd89b569316bc5cc82be98df274e751750f5bfbce965a6fb29feeaf7R174 made a typo on the class list in iRegs search. 
- iRegs: fix typo in class list
1. PR checks should pass. http://localhost:8000/rules-policy/regulations/search-regulations/results/?q=mortgage should have a flush margin on the bottom of the content area.
=> iRegs: fix typo in class list

cfgov/v1/jinja2/v1/includes/molecules/text-introduction.html
- Trim whitespace in link in text introduction
1. Check the "Download the user guide" link on http://localhost:8000/consumer-tools/educator-tools/financial-well-being-resources/measure-and-score/
Before:
After:
=> Trim whitespace in link in text introduction

cfgov/v1/jinja2/v1/includes/organisms/video-player.html
Video player `o-video-player__video-container__flexible` should be `o-video-player__video-container--flexible` and was messing up the player dimensions.
- Fix video player modifiers (`o-video-player__video-container--flexible` and `o-video-player--youtube`)
1. Visit http://localhost:8000/ask-cfpb/do-buy-now-pay-later-bnpl-loans-have-fees-en-2118/ and play the video. It should be full sized.
Before:
After:
=> Fix video player modifiers

cfgov/v1/jinja2/v1/includes/organisms/video-player.html
Missed this in https://github.com/cfpb/consumerfinance.gov/pull/8368
- Fix video thumbnails `o-video-player__image--thumbnail` modifier
1. PR checks should pass. Pages like http://localhost:8000/complaint/ should have a video thumbnail.
=> Fix video thumbnails

.stylelintrc.cjs, cfgov/unprocessed/apps/tccp/css/main.less
Remove unused stylelint rule added in https://github.com/cfpb/consumerfinance.gov/pull/8167
- Remove unused stylelint rule `media-query-no-invalid`.
- Autofix linter issues with gradient.
1. `yarn build` and the gradient at the bottom of the TCCP results list should be unchanged.
=> TCCP: Remove unused `media-query-no-invalid` stylelint config and autofix linter issues

cfgov/unprocessed/css/on-demand/event.less
The existing live stream inset box is very low contrast and fails color accessibility checks.
- Events: Fix contrast in event-meta by darkening gray from gray-40 to gray-90.
1. Go to a future event in Wagtail and check the streamable option to get the live stream inset that has the `event-meta__body` class that sets the color.
Before:
After:
=> Events: Fix contrast in event-meta

cfgov/unprocessed/apps/paying-for-college/css/college-costs/financial-item.less
This style was setting the `border-width` to zero, but then on the next line has a `border` shorthand that sets a transparent border. This means the shorthand is actually overriding the border width and making a 1px transparent border, which indents the content 1px. It didn't appear an existing border was added that this was overriding, so it seems like the border is unnecessary.
- PfC: Remove unused border on `financial-item__label` and `financial-item__value`
1. `yarn build` and http://localhost:8000/paying-for-college/your-financial-path-to-graduation/ should not have borders on the items after the first step.
Before, indented 1px
After, left-aligned
=> PfC: Remove unused border

cfgov/hmda/jinja2/hmda/hmda-explorer-controls.html, cfgov/jinja2/rural-or-underserved/index.html, cfgov/paying_for_college/jinja2/paying-for-college/college-cost-blocks/12-affording-your-loan.html, cfgov/privacy/jinja2/privacy/disclosure-consent-form.html, cfgov/privacy/jinja2/privacy/privacy-styles.html, cfgov/privacy/jinja2/privacy/records-access-form.html, cfgov/retirement_api/jinja2/retirement_api/claiming.html, cfgov/tccp/jinja2/tccp/includes/filter_form.html, cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/unprocessed/css/molecules/file-input.less, cfgov/unprocessed/js/routes/on-demand/simple-chart/data-filters.js, cfgov/v1/jinja2/v1/includes/organisms/filterable-list-controls.html, cfgov/v1/jinja2/v1/includes/organisms/mortgage-chart.html, cfgov/v1/jinja2/v1/includes/organisms/mortgage-map.html
There are no styles associated with `m-form-field__selectable` (should be `m-form-field--selectable`). This was likely added for consistency because we do have `m-form-field--checkbox` and `m-form-field--radio`, however, we don't have a modifier for every single type of form input (e.g. text inputs), so it's probably better if we add this back if its needed. There's an argument this could be helpful in the crawler, but in that case the internal select `a-select` or `m-multiselect` classes could be queried instead.
- Unstyled `m-form-field__select` class.
- Update `m-form-field__file-input` to `m-form-field--file-input` because it's a modifier not an element.
=> Remove/update `m-form-field` modifiers

cfgov/unprocessed/js/modules/util/strings.js, test/unit_tests/js/modules/util/strings-spec.js
@lfatty noted this utility is being flagged by his tools. It's not used, so I'm removing it here.
- Remove `stringEscape` and `stringMatch`
=> Remove `stringEscape` and `stringMatch`

cfgov/v1/jinja2/v1/includes/organisms/contact-preview.html, cfgov/v1/models/snippets.py, cfgov/v1/tests/models/test_snippets.py
This commit makes our Contact snippet type previewable in the Wagtail admin. When editing a Contact, the right panel now allows Wagtail users to preview what the snippet will look like using our SidebarContactInfo module.
Run a local server, and edit a Contact snippet. Using a production dump, you can try these URLs to see a variety of contacts:
- http://localhost:8000/admin/snippets/v1/contact/edit/5/
- http://localhost:8000/admin/snippets/v1/contact/edit/18/
- http://localhost:8000/admin/snippets/v1/contact/edit/26/
I'm planning on proposing a change to make Contact phone numbers clickable links, and wanted to add this functionality to make that change easier to review. I'm opening this first as a separate PR independent from that proposal because I hope it'll be generally useful either …
=> Make Contact snippets previewable

cfgov/jobmanager/jinja2/jobmanager/job_listing_details.html, cfgov/jobmanager/jinja2/jobmanager/job_listing_page.html, cfgov/unprocessed/css/on-demand/job_listing_page.less
I couldn't find a use for `vacancy-announcement_apply` and `vacancy-announcement_description`
- Careers: Remove unused `vacancy-announcement` classes
1. Visit a job listing details page and it should be unchanged.
=> Careers: Remove unused `vacancy-announcement` classes

cfgov/unprocessed/apps/owning-a-home/js/explore-rates/rate-checker.js
We had bug reports that interest rates 10% or great were coming before the lower rates. Upon inspection, the existing sort was sorting string keys alphabetically instead of numerically.
This fixes that.
A bit finicky to test since there aren't any active rates over 10 right now, but http://localhost:8000/owning-a-home/explore-rates/ should appear normal.
=> Correctly sort rate-checker values numerically

cfgov/tccp/jinja2/tccp/situations/results/pay-less-interest-make-a-big-purchase.html
When users select both "Pay less interest" and "Make a big purchase", we currently show two empty links. This fixes that by pointing those links to the correct place.
To test, run a local server and visit
http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/?credit_tier=Credit+scores+from+620+to+719&location=AK&situations=Pay+less+interest&situations=Make+a+big+purchase&ordering=purchase_apr
=> TCCP: Fix result links

cfgov/unprocessed/css/on-demand/mortgage-performance-trends.less, cfgov/v1/atomic_elements/organisms.py
Closes https://github.local/CFGOV/platform/issues/4571
This includes the standard `chart.css` on MPT pages via the `Media` mechanism. Since this file has the chart-builder css included, I also pulled that (now unnecessary) import out of MPT.
- Visit http://localhost:8000/data-research/mortgage-performance-trends/mortgages-30-89-days-delinquent/ and not the styled footnotes
- Open dev tools network and refresh. Note the chart.css file included and the small MPT file as well
=> Include chart styling on mpt pages

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/jinja2/tccp/includes/contact_info.html, cfgov/tccp/jinja2tags.py, cfgov/tccp/tests/test_jinja2tags.py, cfgov/tccp/views.py, cfgov/v1/jinja2/v1/includes/molecules/contact-hyperlink.html
The TCCP card details template currently includes various logic to format card contact information (URLs or phone numbers). This commit pulls the logic out of Jinja and into Python.
See tests in cfgov/tccp/tests/test_jinja2tags.py for examples, but the logic works as follows for URLs:
Valid schemes are http:// and https://. Valid hostnames have to have at least one ".", e.g. "https://foo" is not a valid hostname. If a URL has both of these, it is rendered as a link, with its visible text equal only to the domain, e.g. a link to https://example.com/path/ gets displayed as ~~https://~~ example.com. ~~One change from the current logic here is that we no longer strip a leading "www." from a domain, as we can't make assumptions that bare domains will work.~~
The logic works as follows for …
=> TCCP: Render card contact info using Python

cfgov/v1/jinja2/v1/includes/macros/util/format/contact.html, cfgov/v1/jinja2/v1/includes/molecules/contact-phone.html
This commit alters our template for the ContactPhone molecule such that phone numbers are rendered as clickable links.
The regular phone number and TTY phone numbers are both already required to be a string containing only numbers, which complies with [the RFC for tel: links](https://datatracker.ietf.org/doc/html/rfc3966). The vanity number may contain letters, which are not supported by the RFC, and so is not made into a clickable link.
As part of this change I removed the bolding we currently have for phone numbers to make the weight more consistent with the rest of the text.
Run a local server, and preview these Contact snippets (using the "phone" icon in the upper right):
- http://localhost:8000/admin/snippets/v1/contact/edit/26/
- …
=> Make Contact phone numbers clickable links

cfgov/v1/jinja2/v1/story_page.html
This PR adds the `translation-links` molecule element to the Story page template, to align it with other page types that allow for the automated display of translation links.
---
- `translation-links` import into `story_page.html` template
1. localhost
2. view a Story page with translations, e.g. `/about-us/small-business-lending/`
- …
=> Add translation links to story template

cfgov/tccp/jinja2/tccp/about.html, cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/tccp/jinja2/tccp/includes/data_published.html, cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/tccp/jinja2/tccp/situations/results/build-credit.html
Updating content based on feedback received during pre-clearance.
Content changes should match the Explore credit cards content v2 doc
=> Update TCCP content

.vscode/launch.json
Allows for running the Django dev server in the VSCode debugger. For documentation on this file see:
https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
=> Add VSCode debugger launch configuration

cfgov/tccp/jinja2/tccp/card.html
This commit tidies up the Jinja logic for "other fees" in the card details page. It has no impact on the visible rendering of the content.
Running a local server with the latest dataset, here are some pages to check:
- [No other fees](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/canvas-credit-union-platinum-elite-credit-card/)
- [1 other fee](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/barclays-bank-delaware-jetblue-mastercard/)
- [5 other fees](http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/cadence-bank-platinum/) (the maximum possible)
|No fees|1 fee|5 fees|
|-|-|-|
|<img width="759" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/549287ca-2fed-4943-b5b3-a6181a1bd7b9">|<img width="752" …
=> TCCP: Tidy up detail page "other fees" Jinja

cfgov/unprocessed/apps/ask-cfpb/css/main.less, cfgov/v1/jinja2/v1/includes/organisms/feature-cards.html
This right-hand margin was added in https://github.com/cfpb/consumerfinance.gov/commit/0877172cb6b0bddfbfecffce65bb9072b0c2013a, perhaps to make the right-hand gap and the gap between the cards and search the same? At any rate, if https://github.com/cfpb/consumerfinance.gov/pull/8401 goes ahead, the search will be full width, and removal of this padding on the cards make them align with the search on the right-hand side.
- Ask Cards: Remove right-hand padding and `question-categories` class.
1. Visit http://localhost:8000/ask-cfpb/ and see that the right-hand gap after the cards is narrower than prod.
Before:
After:
=> Ask Cards: Remove right-hand padding

cfgov/ask_cfpb/jinja2/ask-cfpb/_ask-search.html
`complaint_link` was added in https://github.com/cfpb/consumerfinance.gov/commit/139ab186f7005f52d1bf6b70e4d6c809d7dfd83c#diff-78223a1f2676248e59578ecf7984d406bebaf3c9eb322b8ae70d89103206c234 as an option in Wagtail, but was removed in https://github.com/cfpb/consumerfinance.gov/pull/8312 because the underlying `WellWithAskSearch` used in Wagtail had been removed. 
- Remove `complaint_link` from jinja template
1. PR checks should pass. Search codebase for `complaint_link` and see that the only reference is in the template where it's set to False.
=> Ask CFPB: Remove unused `complaint_link`

cfgov/housing_counselor/jinja2/housing_counselor/index.html
This PR removes the coronavirus sidebar from `/find-a-housing-counselor`, as part of a larger COVID content cleanup initiative.
---
1. localhost
2. View `/find-a-housing-counselor`
| Before | After | 
| - | - |
| <img width="1182" alt="Screenshot 2024-05-15 at 2 56 37 PM" src="https://github.com/cfpb/consumerfinance.gov/assets/29648039/639c4680-1b7b-4abf-8472-190bb02d8474"> | <img width="1180" alt="Screenshot 2024-05-15 at 2 56 21 PM" src="https://github.com/cfpb/consumerfinance.gov/assets/29648039/c2dc9875-5bd4-4121-8372-dccfe2c06380"> |
- [This repo’s …
=> Remove COVID sidebar from find-a-housing-counselor

cfgov/housing_counselor/jinja2/housing_counselor/index.html
Follow-on to https://github.com/cfpb/consumerfinance.gov/pull/8421
With the removal of the covid breakout sidebar, we need to also delete some corresponding column classes that expect a second column.
- Find a Housing Counselor: Removes heading area `content-l` columns and `o-sidebar-breakout` 
1. Visit http://localhost:8000/find-a-housing-counselor/ and resize to mobile and see that intro content extends full width.
Before:
After:
=> Find a Housing Counselor: Remove sidebar breakout and content-l column classes post-covid sidebar breakout removal

cfgov/apache/conf.d/redirects.conf, cfgov/cfgov/urls.py, cfgov/wellbeing/es_urls.py, cfgov/wellbeing/urls.py
- Visit http://localhost:8000/consumer-tools/financial-well-being/
- Click over to spanish with the language picker
- Note the url
- The tool should function and bring you to the result page
=> Move the financial wellbeing tool to the standard /es/-first format

cfgov/tccp/jinja2/tccp/card.html
This PR simplifies some of the logic on the TCCP card detail page, removing code that tried to determine if a card has a varying periodic fee. The dataset schema doesn't provide enough information for us to reliably report this to users.
This change simplifies the fee rendering so that we only show annual, monthly, and weekly fees, without information on periodic changes.
See internal https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/306#issuecomment-354469 for additional context behind this change.
To test, run a local server with the latest data and visit a card page with fees, for example
http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/credit-one-bank-national-association-platinum-visa-for-rebuilding-credit/.
=> TCCP: Cleanup detail page fee logic

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/models.py, cfgov/tccp/serializers.py, cfgov/tccp/tests/test_models.py
Minor update to TCCP card detail page to avoid hardcoding strings related to fee types. This has no impact on visible content.
See internal https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/306 for additional context.
To test, run a local server with the latest dataset and visit:
- Late fee details only: http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/pennsylvania-state-employees-cu-classic-visa/
- Late fee + details: http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/ally-bank-ally-everyday-cash-back-mastercard_1/
- Over limit fee only: http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/university-bank-university-bank-visa-credit-card/
- Over limit fee + details: …
=> TCCP: Don't hardcode fee strings

cfgov/tccp/jinja2/tccp/includes/apr_rating.html, cfgov/tccp/jinja2/tccp/includes/apr_table.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/unprocessed/apps/tccp/css/main.less
And add some descriptive rating text for assistive technologies.
=> Have all APR ratings contained within an APR rating group

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/jinja2/tccp/includes/apr_rating.html, cfgov/tccp/jinja2/tccp/includes/apr_table.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/tccp/management/commands/validate_tccp.py, cfgov/tccp/views.py, cfgov/unprocessed/apps/tccp/css/main.less
This commit consolidates several different ways that we markup TCCP card ratings (the colored icon next to a description like "Pay less interest").
The new apr_rating macro can be used to render just this bit; various places on the card list and details view now use this macro.
Styles have been reworked to support this new approach.
To test, run a local server and visit pages like:
- http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/
- http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/vinton-county-national-bank-consumer-credit-card/
Check sizing on mobile and desktop widths.
Display should be unchanged from before:
An unrelated obsolete comment has also been removed from the detail page template; see internal …
=> TCCP: Consolidate card rating markup 

cfgov/tccp/jinja2/tccp/card.html
This commit creates a new `data_section` macro in the TCCP card details page template, removing some boilerplate used repeatedly to render this page.
See internal https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/306 for context.
To test, run a local server with the latest data and visit pages like: http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/vinton-county-national-bank-consumer-credit-card/
=> TCCP: Consolidate card detail headings into macro

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, docs/browser-support.md, mkdocs.yml
- Add browser-support page to mkdocs and move content from the contributing readme.
- Reference mkdocs browser support page in Pull Request template.
1. Run `mkdocs serve -a localhost:8888` and visit localhost:8888/browser-support to see the page in the docs.
=> Add browser-support page to mkdocs and update references

cfgov/jinja2/owning-a-home/explore-rates/index.html, cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less, cfgov/v1/jinja2/v1/includes/molecules/notification.html
BAH/OAH has this borderless notification that is not used anywhere else. This requires a custom notification block and uses the custom `credit-note-ctr` class to add a divider. This PR moves the whole block to a standard `block` and a standard warning notification. It also adds the ability to open links in a new window to the standard notification.
cc @csebianlander for content changes.
- BAH/OAH: Move borderless notification to standard notification.
- BAH/OAH: remove custom `credit-note-ctr` class.
- Adds the ability to open links in a new window to the standard notification.
1. `yarn build` and visit http://localhost:8000/owning-a-home/explore-rates/ and scroll down till you see the notification.
Before:
---
---
After:
---
=> BAH/OAH: Move borderless notification to standard notification

cfgov/jinja2/owning-a-home/_templates/brand-header.html
Before:
After:
The above appears on localhost:8000/owning-a-home/explore-rates/
=> BEM fix to BAH header

cfgov/jinja2/owning-a-home/explore-rates/index.html, cfgov/unprocessed/apps/owning-a-home/css/helpers.less
I couldn't find a use of rate checkers' `u-pb0` utility class.
The `sans` class only sets the bolding on `<strong>` text, but we already set the same weight via our base styling, so this was redundant.
- BAH/OAH: Remove `sans` and `u-pb0` classes
1. There should be no changes to rate checker.
You can inspect https://www.consumerfinance.gov/owning-a-home/explore-rates/ and search for `sans` and then remove that class and see there is no change to the paragraph of text.
=> BAH/OAH: Remove `sans` and `u-pb0` classes

cfgov/jinja2/rural-or-underserved/index.html, cfgov/privacy/jinja2/privacy/disclosure-consent-form.html, cfgov/privacy/jinja2/privacy/records-access-form.html, cfgov/unprocessed/css/molecules/file-input.less
There are three inputs that use the flush right button: rout, and two privacy forms. The privacy forms don't have an actual file input control, so don't need a flushed right button. ROUT had some broken classes that needed to be fixed.
- Remove `a-btn__flush-right` from file inputs that don't need it.
- Fix BEM of ROUT file input.
1. `yarn build` and visit these links and see that the file upload control looks correct and buttons are not unnecessarily rounded:
http://localhost:8000/rural-or-underserved-tool/
http://localhost:8000/privacy/records-access/
http://localhost:8000/privacy/disclosure-consent/
Before:
After:
=> Fix file inputs

cfgov/jinja2/rural-or-underserved/index.html
Rural or underserved tool has a wrapper div for the about section that has the classes `group sans border-top-2`. I could not find any styles associated with these classes. 
- ROUT: remove `group sans border-top-2` wrapper div.
1. Visit https://www.consumerfinance.gov/rural-or-underserved-tool/ and manually remove `group sans border-top-2` and see there is no effect. Visit http://localhost:8000/rural-or-underserved-tool/ and see that the removal of the wrapper div has no effect.
=> ROUT: remove `group sans border-top-2` wrapper

cfgov/v1/atomic_elements/organisms.py, cfgov/v1/jinja2/v1/includes/molecules/related-posts.html
- Visit http://localhost:8000/about-us/blog/whats-ahead-for-bank-of-america-and-its-customers-zh/
- Note the "Further Reading" section is all in Chinese
- Visit http://localhost:8000/about-us/blog/strengthening-information-accessibility-for-consumers-limited-english-proficiency-zh/ and note that the "Further Reading" section is gone.
- Unfortunately due to how we add spacing in the streamfield-sidefoot, the EmailSignup block is unable to get `flush-top` at this time. I don't foresee this being too big of an issue, because most things have RelatedPosts
- Visit http://localhost:8000/about-us/events/archive-past-events/special-populations-presentation/
- Note that "Further Reading" is all in English
=> Limit related posts to those in the same language

cfgov/v1/jinja2/v1/includes/molecules/notification.html
Notification links with icons are getting incorrect markup because of whitespace in the HTML template. This commit fixes that.
Run a local server and visit http://localhost:8000/owning-a-home/explore-rates/. Check the links in the notification towards the bottom of the page.
|Before|After|
|-|-|
|<img width="254" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/27c0553f-7e5d-4f27-a453-6f90a9fa9d82">|<img width="256" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/ddfc403e-7ad3-413b-a70b-de5c26cffa70">|
=> Fix notification link markup

cfgov/core/tests/test_utils.py, cfgov/core/utils.py
Our link icon markup incorrectly leaves behind whitespace in certain cases. For example, given a link like this:
```html
<a href="https://example.com"> text </a>
```
the markup will generate:
```html
<a href="https://example.com" class="a-link a-link--icon">
<span class="a-link__text"> text </span>
<svg class="cf-icon-svg cf-icon-svg--external-link">...</svg>
</a>
```
The extra whitespace in the `<span>` gets underlined incorrectly.
See "View a webinar on the rule" on https://www.consumerfinance.gov/know-before-you-owe/ for an example where this happens on the live site.
This fix attempts to strip surrounding whitespace from the link text to prevent this happening.
Run a local server and visit http://localhost:8000/know-before-you-owe/, and compare the link above to the live site. …
=> Fix extra whitespace in some link markup cases

cfgov/v1/jinja2/v1/includes/organisms/post-preview.html
Commit 54ccbf85838e08744a3b766e24213d721c206b0b removed the `comments_close_by` field from AbstractFilterPage. A reference to `comments_close_date` was left behind in the post preview template, but that is never set anywhere. This commit cleans that up.
[There are no other references to this field in the codebase.](https://github.com/search?q=repo%3Acfpb%2Fconsumerfinance.gov%20comments_close_date&type=code)
=> Remove reference to deprecated comments_close_date

cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/v1/jinja2/v1/layouts/layout-full.html
Currently the layout-full.html template queries page breadcrumbs but then doesn't use them below. It imports _breadcrumbs.html which recomputes the breadcrumbs anyway.
Additionally, the two TCCP templates import a breadcrumbs template but don't use it.
With this change there are no longer any templates that import breadcrumbs.html directly (the template that depends on having the breadcrumbs already defined). All templates now import the _breadcrumbs.html template, which queries them (if not defined) and then renders the actual breadcrumbs.html template.
Confirm that Wagtail pages that inherit from layout-full.html still have functional breadcrumbs, [for example](http://localhost:8000/rules-policy/regulations/search-regulations/results/?regs=1002).
=> Breadcrumbs template cleanup

cfgov/regulations3k/jinja2/regulations3k/browse-regulation.html
- Migrate iRegs notifications to standard notification
1. Visit a regulation, like http://localhost:8000/rules-policy/regulations/1005/, and click "View all versions of this regulation"
2. Click on a prior date for the regulation and note that there's a notification that says the regulation is not current. Compare to production and it should be the same (*almost—see notes below)
3. Click into a section of the regulation and see that there's a notification with a link. Compare to production and it have the same content.
4. To view a future regulation, you'll need to go into Wagtail and edit a regulation to have a future publish date, and then follow steps 1-3 to see the future notifications.
Before/after across past/future and screensizes
- The hardcoded notifications used paragraph tags …
=> Migrate iRegs notifications to standard notification

cfgov/jinja2/owning-a-home/_templates/brand-footer.html, cfgov/jinja2/owning-a-home/explore-rates/index.html
As reported by @anselmbradford.
On http://localhost:8000/owning-a-home/explore-rates/, the footer images should have more sensible alt-text while the strange aria-labels on the links have been removed.
=> Remove weird aria-labels on links and fixup alt text for images

cfgov/unprocessed/apps/ask-cfpb/js/ask-autocomplete.js
- Ask: Change `innerHTML` to `innerText` in Ask Search.
1. Visit http://localhost:8000/ask-cfpb/ and type some text into the Ask autocomplete and it should still work as before.
=> Ask: Change `innerHTML` to `innerText` in Ask Search

cfgov/unprocessed/apps/form-explainer/js/FormExplainer.js
- Fix ID in Form Explainer
1. VIsit http://localhost:8000/owning-a-home/closing-disclosure/ and the form explainer pagination should work.
THIS SHOULD HAVE TESTS!
=> Fix ID in Form Explainer

cfgov/unprocessed/apps/filing-instruction-guide/js/fig-sidenav.js
- Go to http://localhost:8000/data-research/small-business-lending/filing-instructions-guide/2024-guide/#pricing-information
- Make sure you're in the mobile view
- Click on one of the fields and note that it scrolls down as expected
=> FIG: Don't swallow clicks to field links on mobile

cfgov/v1/jinja2/v1/includes/organisms/post-preview.html, cfgov/v1/models/learn_page.py, cfgov/v1/tests/models/test_event_page.py
EventPages that don't specify a location currently render with an extra leading dash, for example:
\- MAY 30, 2024 @ 01:00 PM EDT
This commit fixes that and adds some tests around how the preview location string renders.
See https://www.consumerfinance.gov/about-us/events/ for a live example of this bug right now.
Run a local server and visit http://localhost:8000/about-us/events/ and http://localhost:8000/about-us/events/archive-past-events/, and compare against production.
|Before|After|
|-|-|
|<img width="745" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/d4197dce-3867-4145-8b6c-aac3b1162b63">|<img width="753" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/0a57e77a-3065-4715-9f75-36bee37e4c31">|
=> Fix: EventPage previews without a location

cfgov/v1/forms.py, cfgov/v1/tests/test_forms.py
The Python unit tests for FilterableListForm currently patch the `builtins.super` function which can break unit tests when run in a reverse or unpredictable order.
This PR updates those tests to avoid the need to patch super while still continuing to test the same functionality. I also removed an unused `set_field_html_name` method whose only use was removed in 2019 in 934a39791d10041e8142517ef3cb6feb787d541e.
All tests continue to pass with the same coverage (actually slightly increased due to removal of unused code). 
This is a followup to #8461 which removed the only other patching of `builtins.super` in the codebase.
=> Modify Python tests to avoid patching super()

cfgov/wagtailadmin_overrides/templates/wagtailadmin/account/password_reset/confirm.html
Wagtail 6.0 included this change to the password reset confirmation template:
https://github.com/wagtail/wagtail/commit/84f885ff17056c0c01954637d645dc50cbcb77bb
This broke our template override, which you can see if you try to reset a password. This commit fixes that.
See also https://github.com/wagtail/wagtail/issues/11550 which discusses why this wasn't documented.
=> Fix broken tag in password reset confirm template

cfgov/v1/jinja2/v1/home_page/_hardcoded_en.html, cfgov/v1/jinja2/v1/home_page/home_page.html, cfgov/v1/jinja2/v1/home_page/home_page_legacy.html
Right now one of the three highlights under the hero on the homepage links to page that no longer exists. This PR removes that highlight entirely and modifies the template HTML so that the two remaining items are spaced properly.
For similar reasons (broken/outdated links), this PR removes both "feature" items on the Spanish homepage.
---
1. localhost
2. view `/`
3. view `/es`
| Before | After |
| - | - |
| <img width="1279" alt="Screenshot 2024-06-11 at 11 50 42 AM" src="https://github.com/cfpb/consumerfinance.gov/assets/29648039/d4c38b45-1321-4787-8302-1dd883bd5faa"> | <img width="1243" alt="Screenshot 2024-06-11 at 11 50 49 AM" src="https://github.com/cfpb/consumerfinance.gov/assets/29648039/3605a884-5a60-4d06-9794-4ec1436aa477"> |
- A replacement for that highlight page is in …
=> Remove broken highlight from homepage

cfgov/ask_cfpb/tests/test_hooks.py
These Ask CFPB tests are trying to create an HttpRequest for a specific user, but instead of creating a new instance and modifying it, they modify the HttpRequest class itself.
This has side effects for other Python unit tests that need to use HttpRequest objects, because they always get the user that was assigned here.
All tests continue to pass.
=> Fix incorrect use of HttpRequest in Ask CFPB tests

cfgov/unprocessed/css/organisms/full-width-text-group.less
My proposal for https://github.local/Design-Development/Design-and-Content-Team/issues/379
- http://localhost:8000/about-us/blog/los-pasos-que-debe-tomar-para-cerrar-el-trato-de-su-vivienda-con-confianza/ should have consistent spacing between sections at mobile and desktop
- The MANY pages with full width text components should appear unchanged. Use this querystring with the crawler for examples: `?q=m-full-width-text&search_type=components`
There MAY be pages where this breaks the existing spacing and the use of `h2`s as the heading level in "full width text" content sections is not universal (eg, http://localhost:8000/about-us/careers/application-process/ is `h3`s). But this seems like a decent enough compromise. Happy to hear other theories of what the ideal spacing should be. I'd say …
=> Add margins to m-full-width-text 'content' blocks that match h2s

cfgov/unprocessed/css/organisms/full-width-text-group.less
This was added in https://github.com/cfpb/consumerfinance.gov/pull/2810 and should have been removed in https://github.com/cfpb/consumerfinance.gov/pull/7606
- Remove `.m-inset__test` class
=> Remove `.m-inset__test` class

cfgov/agreements/jinja2/agreements/index.html, cfgov/ask_cfpb/jinja2/ask-cfpb/landing-page.html, cfgov/v1/jinja2/v1/includes/organisms/mortgage-chart.html, cfgov/v1/jinja2/v1/includes/organisms/mortgage-map.html, cfgov/v1/jinja2/v1/includes/organisms/simple-chart.html
Modifiers should appear with their accompanying block.
- Fix orphan `block--sub` by adding accompanying `block` class.
1. /ask-cfpb/ search input margin should be unchanged.
/data-research/mortgage-performance-trends/mortgages-90-or-more-days-delinquent/ chart footers should be unchanged.
/credit-cards/agreements/ archive link should be unchanged.
=> Fix orphan `block--sub`

cfgov/search/elasticsearch_helpers.py, cfgov/v1/documents.py
We have a bug whereby AbstractFilterPage deletes (and, presumably, updates) don't get reflected in the filterable list search index. This happens because of some logic around Wagtail specific page types; see internal
https://github.local/Design-Development/Design-and-Content-Team/issues/471 for details.
Our current code hooks up Wagtail Page save/delete events to django-opensearch-dsl save/delete handlers but, before passing along the events, casts AbstractFilterPage instances to their specific page type. This prevents the d-o-d logic from actually updating the search index because it can't associate a specific page model type with any particular document/index.
With this change, we do two things:
1. Ensure that pages are cast to their AbstractFilterPage versions, thus ensuring that d-o-d …
=> Fix search index updates for AbstractFilterPages

cfgov/v1/models/sublanding_page.py, cfgov/v1/tests/models/test_sublanding_page.py
Commit 942be7067d9a0d6009d7328244a5ce6ecb4dddbf broke rendering of PostPreviewSnapshots because the post preview template now expects a serialized version of pages, not the page objects themselves.
I've updated the relevant code and added a new regression test that actually renders the PPS template, something we lacked before.
To test, run a local server and visit
http://localhost:8000/compliance/amicus/
http://localhost:8000/rules-policy/notice-opportunities-comment/
These pages now once again render properly.
It's strange and suboptimal that SublandingPages with PostPreviewSnapshots don't use the same page search approach that regular FilterableLists do. For example, [this page](https://www.consumerfinance.gov/compliance/amicus/) looks like a FilterableList but under the hood it's using …
=> Fix PostPreviewSnapshot rendering

cfgov/unprocessed/css/organisms/video-player.less
The `grid__wrapper` mixin has these rules:
```css
max-width: (@grid_wrapper-width - @grid_gutter-width);
padding-right: (@grid_gutter-width / 2);
padding-left: (@grid_gutter-width / 2);
margin: 0 auto;
clear: both;
```
Where `@grid_wrapper-width` is 1230px and  `@grid_gutter-width` is 30px;
https://github.com/cfpb/design-system/blob/6b566bdb7ae2ce4c80a1cd05404bf3ea2e8fe6fa/packages/cfpb-grid/src/cfpb-grid.less#L20
It appears the only aspect of these rules that the video player actually uses is the left and right padding, which is the same as the top and bottom padding. This PR replaces the `grid__wrapper()` with padding.
- Video Player: replace the `grid__wrapper()` mixin with padding.
1. Check that when playing, across screen sizes, that our various video layouts are unchanged, such as: …
=> Video Player: Remove `grid__wrapper`

cfgov/v1/jinja2/v1/includes/organisms/item-introduction.html, cfgov/v1/models/base.py, cfgov/v1/tests/models/test_author_names.py
This crept in via https://github.com/cfpb/consumerfinance.gov/pull/8450 and is currently throwing 500s in prod
The visual bug:
And the 500 error is on any page with an author name without a space (usually `CFPB`)
=> Fix index bug in author sorting method and display bug in item introduction

cfgov/core/templatetags/svg_icon.py, cfgov/core/tests/templatetags/test_svg_icon.py
Currently any use of the `{% svg_icon %}` template tag loads the SVG contents from disk. This commit modifies that behavior so that SVG icons are cached in memory, to avoid the need to load from file each time.
In [our icon library](https://github.com/cfpb/design-system/tree/6b566bdb7ae2ce4c80a1cd05404bf3ea2e8fe6fa/packages/cfpb-icons/src/icons) icon files range from 220 bytes to 2.6 KB in size. The total size of all icons is 2.8 MB.
Closes internal https://github.local/CFGOV/platform/issues/3667.
Everything should work the same, just slightly faster at the expense of slightly greater memory usage.
Locally, `SKIP_DJANGO_MIGRATIONS=1 tox -e unittest` takes 285s vs 291s for me on main, as an example of code that does a whole bunch of icon loads. On our production instances, [we don't limit …
=> Cache SVG icons in memory

cfgov/v1/jinja2/v1/blog/blog_page_list_preview.html, cfgov/v1/models/blog_page.py, cfgov/v1/tests/models/test_blog_page.py
This change prototypes using Wagtail's page [preview modes](https://docs.wagtail.io/en/stable/reference/pages/model_reference.html#wagtail.core.models.Page.preview_modes) to allow for previewing of blog posts in their list view, i.e. how they show up [on the blog page](https://www.consumerfinance.gov/about-us/blog/).
Run a local server and edit a blog page. Note that the Preview button is now a dropdown, and you can either preview as normal or preview the post in its "post preview" mode.
~~This can't be merged right now because the use of Django template caching [here](https://github.com/cfpb/consumerfinance.gov/blob/c85439f63dfd6c213be0c185bfbefee90f0c2d53/cfgov/jinja2/v1/_includes/organisms/post-preview.html#L116) means that previewing changes either won't work as expected or will …
=> Add support for previewing blog posts in list view

cfgov/jinja2/owning-a-home/explore-rates/index.html, cfgov/unprocessed/apps/owning-a-home/css/explore-rates.less
Remove use of `grid__pull` from the codebase, and `grid__push` from rate explorer (this is still used in PfC disclosures). 
The DOM changes are just swapping the DOM order and adding `content__main` and `content__sidebar` classes.
- BAH/OAH: Move rate explorer to content--2-1 layout
1. `yarn build` and rate explorer should be (generally) unchanged in its layout. The calculator is slightly closer to the right-hand edge, but this is more correct as it aligns with the header items now.
=> BAH/OAH: Move rate explorer to content--2-1 layout

cfgov/unprocessed/css/molecules/inset.less, cfgov/unprocessed/css/organisms/prefooter.less, cfgov/v1/jinja2/v1/includes/organisms/full-width-text.html
- Add `m-inset` to accompany orphan `m-inset--email`
- Add bottom margin to `m-inset--email` to mimic block spacing.
- Remove `float: right` on `m-inset--email`, since that's already set on `m-inset`.
- Add clear float to `o-prefooter`, to clear any floats above the prefooter.
1. Crawler search for pages is `?q=m-inset--email&search_type=html`. For example:
http://localhost:8000/compliance/compliance-resources/mortgage-resources/loan-origination-rule/
http://localhost:8000/compliance/compliance-resources/signup/
http://localhost:8000/compliance/compliance-resources/consumer-cards-resources/credit-card-penalty-fees/
In some cases, the inset is below the heading because of the top margin of the block that was there, so in this PR the inset moves up to be in line with the heading. This seems …
=> Properly BEMify `m-inset--email`

cfgov/hmda/jinja2/hmda/hmda-explorer.html, cfgov/v1/jinja2/v1/document-detail/index.html, cfgov/v1/jinja2/v1/enforcement-action/index.html, cfgov/v1/jinja2/v1/includes/article.html, cfgov/v1/jinja2/v1/includes/organisms/item-introduction.html, cfgov/v1/jinja2/v1/learn-page/index.html, cfgov/v1/tests/atomic_elements/organisms/test_organisms.py
Commit 7cebc54f09f8510f4b8ce8836c7b5f609677b712 fixed a bug related to how the ItemIntroduction organism is rendered. This went undiscovered because we didn't have tests for the II.
This commit adds a unit test for the II module and also simplifies its invocation across the various page types.
Some local URLs to test to verify that this doesn't impact rendering:
- http://localhost:8000/about-us/blog/recuperese-y-preparese-financieramente-para-las-tormentas/
- http://localhost:8000/enforcement/actions/pennsylvania-higher-education-assistance-agency-pheaa-dba-american-education-services-or-aes/
- http://localhost:8000/rules-policy/notice-opportunities-comment/commenting-on-notices/
- http://localhost:8000/data-research/research-reports/2012-college-credit-card-agreements/
=> Simplify usage of ItemIntroduction

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/includes/apr_rating.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/tccp/jinja2/tccp/includes/data_published.html, cfgov/tccp/jinja2/tccp/includes/fields.html, cfgov/tccp/jinja2/tccp/situations/results/avoid-fees.html, cfgov/tccp/jinja2/tccp/situations/results/build-credit.html, cfgov/tccp/jinja2/tccp/situations/results/earn-rewards.html, cfgov/tccp/jinja2/tccp/situations/results/make-a-big-purchase.html, cfgov/tccp/jinja2/tccp/situations/results/pay-less-interest-make-a-big-purchase.html, cfgov/tccp/jinja2/tccp/situations/results/pay-less-interest.html, cfgov/tccp/jinja2/tccp/situations/results/transfer-a-balance.html, cfgov/tccp/management/commands/validate_tccp.py, cfgov/tccp/situations.py, cfgov/tccp/tests/test_situations.py, cfgov/tccp/tests/test_validate.py, cfgov/tccp/views.py, cfgov/unprocessed/apps/tccp/css/main.less
This commit modifies the TCCP landing view in these ways:
- Remove "Cards your looking for have these features" and dynamic bullets
- Keep link "Change what you're looking for in a card" above filter
- Add APR ranges to key
- Update content of "Data reported on Dec. 31, 2023..." to "Data as of Dec. 31, 2023. Learn about the data"
- Add asterisk to purchase APR and balance transfer APR
- Add disclaimer under "Purchase APR" label that displays date of reporting that says "*As of Month, XX, XXXX"
See internal https://github.local/Design-Development/Design-Thinking-and-User-Research/issues/334 for context.
To test, run a local server and visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/.
=> TCCP: Design iteration

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/jinja2/tccp/includes/apr_disclaimer.html, cfgov/tccp/jinja2/tccp/includes/data_published.html, cfgov/tccp/situations.py, cfgov/unprocessed/apps/tccp/css/main.less, cfgov/v1/jinja2/v1/includes/macros/time.html
Adds APR disclaimers to TCCP card details. Also fixes a few issues that came up during this work as noted below.
---
- The "Review details with the company before applying" section just above the contact information
- Disclaimers under the purchase, balance transfer, and cash advance APRs (all handled by a single, new `apr_disclaimer` macro)
- FIXED: Added a did-you-know to the rewards section that was missing
- Generic `u-small-text--subtle` disclaimer from the card details page (no longer needed since we now have disclaimers specific to each APR)
- Small content, margin, and stying tweaks
- Stripped whitespace from the end of the `time.html` macro to allow for the data published date to be followed directly by a period without a space in between; I checked everywhere else I could find …
=> TCCP: Add APR disclaimers to card details

cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/unprocessed/apps/tccp/js/index.js, test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js
Wraps the date range in TCCP tooltips in a `nowrap` element to prevent it from line breaking. Also prevents TCCP card links from being mistakenly followed when a user clicks away to close a tooltip.
1. PR tests should pass.
1. `yarn cypress run --spec test/cypress/integration/consumer-tools/credit-cards/explore-cards.cy.js`
1. http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/ is the same ol' thang.
| mobile | desktop |
|--------|---------|
|![Screenshot 2024-06-26 at 9 41 19 AM](https://github.com/cfpb/consumerfinance.gov/assets/1060248/26f1554f-64a8-4bae-b6d7-3aa0014aee4a)|![Screenshot 2024-06-26 at 9 40 48 AM](https://github.com/cfpb/consumerfinance.gov/assets/1060248/e6ea432c-80c0-4fda-aac5-6c23eaccb7da)|
|![Screenshot 2024-06-26 at 9 41 …
=> Improve TCCP tooltip handling and visuals

cfgov/paying_for_college/views.py, cfgov/regulations3k/models/pages.py
These two files triggered ruff's `SIM103: Return the condition directly` warning, which wants you to return a boolean directly rather than testing it then returning `True` or `False` literals.
=> Fix new ruff warnings

cfgov/jobmanager/blocks.py, cfgov/jobmanager/tests/test_blocks.py
This commit optimizes rendering of the JobListingTable organism found on https://www.consumerfinance.gov/about-us/careers/current-openings/ so that it takes 5 database queries instead of 13.
When this code was last touched in April 2020, django-modelcluster didn't properly support prefetching of ParentalManyToManyFields (see https://github.com/wagtail/django-modelcluster/issues/101). In May 2020 I opened a PR to remedy this (see https://github.com/wagtail/django-modelcluster/issues/122), and this was released in September 2020, but I neglected to revisit this code to add the optimization. This commit does so.
All existing tests continue to pass properly.
=> Optimize JobListingTable DB queries

cfgov/draftail_icons/static/draftail_icons/js/draftail_icons.js
This PR modifies the helper text shown in the `window.prompt` when selecting an SVG in Draftail, to point users to the relevant Design System name where appropriate icon names can be found.
My VSCode linter appears to have enforced some other formatting opinions across the .js file; feel free to revert if any of those don't seem right.
---
1. localhost
2. Edit any page with a rich text editor
3. Click the "Icon" button to see the prompt
| Before | After |
| - | - |
| <img width="446" alt="Screenshot 2024-07-03 at 12 48 35 PM" src="https://github.com/cfpb/consumerfinance.gov/assets/29648039/985edff2-8d4a-4482-8f94-873d8932e35a"> | <img width="450" alt="Screenshot 2024-07-03 at 12 47 42 PM" src="https://github.com/cfpb/consumerfinance.gov/assets/29648039/0c00308d-1961-474d-a5ff-a7bbdd2399c1" …
=> Improve helper text for SVG picker

cfgov/ask_cfpb/models/pages.py
Similar to https://github.com/cfpb/consumerfinance.gov/pull/8360, this sorts spanish key terms pages such that the results are ordered by the english results (so they're stable when switching between english and spanish).
=> Sort spanish key terms pages to match english page results

cfgov/unprocessed/css/print.less
Printing seems fine without this, and also `-webkit-min-device-pixel-ratio` is deprecated. 
- Remove Chrome blank first print page hack
1. Try printing a few pages from Chrome and seeing that there is no blank first page in the preview or when saved to a PDF.
=> Remove Chrome blank first print page hack

cfgov/unprocessed/apps/form-explainer/css/form-explainer.less
- Form explainers: Remove redundant CSS
1. Check the code block immediately above the one being deleted and see that it is the same https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/apps/form-explainer/css/form-explainer.less#L128-L138
=> Form explainers: Remove redundant CSS

cfgov/unprocessed/apps/retirement/css/claiming.less
- Retirement: remove redundant CSS
1. See that this CSS is set the same further down
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/apps/retirement/css/claiming.less#L418-L420
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/apps/retirement/css/claiming.less#L439-L441
=> Retirement: remove redundant CSS

cfgov/tccp/jinja2/tccp/includes/contact_info.html, cfgov/tccp/jinja2tags.py, cfgov/tccp/tests/test_jinja2tags.py
This commit modifies how phone numbers are rendered on the frontend of the "Explore credit cards" tool. It fixes an issue with parsing phone numbers that have spaces in them in the TCCP dataset. The TCCP dataset contains cards that only provide a single phone number, but sometimes this can include spaces, for example:
1 (800) 555-1234
Instead of parsing this like multiple phone numbers separated by spaces, we need to parse this as a single phone number.
=> TCCP: Fix phone number parsing

cfgov/unprocessed/css/on-demand/chart.less
This CSS defines a simple variable and then uses it on the very next line and nowhere else (that I can see). It seems simpler to use the direct value.
I'm sure @contolini remembers with crystal clarity why he added this 7.5 years ago in https://github.com/cfpb/consumerfinance.gov/pull/2688, and will stop me if this is breaking something.
- `@font-size` variable from `chart.less`
1. Pages with `m-chart-footnote` (see crawler) should still have small text for their footnotes.
=> Charts: Remove `@font-size` variable that is used on the next line

cfgov/unprocessed/css/organisms/mega-menu.less
- Remove `&-item--has-icon .cf-icon-svg` `display: inline-block` rule, which is overridden with `display: inline` by the same selector further down. 
- Rearrange `&-list--featured &-link` so that redundant definition is removed.
1. See that `&-item--has-icon .cf-icon-svg` display rule appears twice.
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/organisms/mega-menu.less#L238
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/organisms/mega-menu.less#L263
2. See that `&-list--featured &-link` appeared twice. 
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/organisms/mega-menu.less#L861
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/organisms/mega-menu.less#L898
3. Pull branch, run …
=> Mega Menu: remove redundant CSS

cfgov/unprocessed/css/on-demand/mortgage-performance-trends.less
Mortgage Performance Trends sets the margin bottom of its `a-label h4` to 15px. However, an h4 already has its styles setting a 15px bottom margin https://github.com/cfpb/design-system/blob/main/packages/cfpb-core/src/base.less#L76
I think what happened is this was added as a 10px margin override, and then it was updated to 15px in https://github.com/cfpb/consumerfinance.gov/commit/92e17a3a5b863820426db164fb074b38b7ae4de4, when it could have been removed entirely. 
- Remove redundant `a-label h4` bottom margin utility.
1. `yarn build` and http://localhost:8000/data-research/mortgage-performance-trends/mortgages-30-89-days-delinquent/ should have unchanged spacing under "Select map view", for example.
=> Mortgage Performance Trends: Remove redundant margin bottom

cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html, cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_result.html, cfgov/unprocessed/apps/teachers-digital-platform/css/pages/activity-search.less
`datetime_date` was removed in https://github.com/cfpb/design-system/pull/1966
`activity_title-link` does not have any associated styles that I can find.
- TDP: Remove unused CSS 
- Update BEM names in markup that were still on old BEM styles.
- Simplify font-size calculation.
1. `yarn build` and visit localhost:8000/consumer-tools/educator-tools/youth-financial-education/teach/activities/
Before:
After:
=> TDP: Remove unused CSS | Update BEM names in markup

cfgov/data_research/models.py, cfgov/regulations3k/jinja2tags.py, cfgov/retirement_api/utils/ss_utilities.py
Ruff is complaining about our comparison operators and wants us to "use `is` and `is not` for type comparisons".
See failed job at https://github.com/cfpb/consumerfinance.gov/actions/runs/9942217435/job/27463160690?pr=8506#step:8:20
=> Fix ruff E721 comparison errors

cfgov/tccp/jinja2/tccp/card.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/tccp/serializers.py
Refine content about card eligibility to be as specific as we can.
---
- `geographic_restrictions` and `professional_affiliation` to `CardSurveyDataListSerializer` so they're available to tooltips in the card list
- A phrase at the end of the generic credit union eligibility requirement noting some common credit union membership requirements
- Eligibility tooltips now use a few fields to tailor the content for each card
1. Make sure the eligibility tooltip content looks like the screenshots below and matches the requirements called out on the details page
2. Make sure the generic credit union eligibility requirement on the details page now ends with the phrase, "which typically include living in certain areas or working for certain employers." 
Credit union, no requirements in data | …
=> TCCP: Improve eligibility content

package.json
This is much nicer than having to invoke it from .bin
`yarn run open` opens cypress as expected
=> Add open script to invoke cypress

cfgov/unprocessed/apps/tccp/js/index.js
`keyCode` is deprecated https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
Follow-on to https://github.com/cfpb/consumerfinance.gov/pull/8506
- TCCP: Move deprecated keyCode to key
1. Hover over a tooltip and click `esc` to close it.
=> TCCP: Move deprecated keyCode to key

cfgov/jobmanager/models/django.py, cfgov/jobmanager/views.py, cfgov/permissions_viewer/wagtail_hooks.py, requirements/wagtail.txt, test/cypress/integration/admin/admin-helpers.cy.js, test/cypress/integration/admin/admin.cy.js
This PR upgrades us to Wagtail 6.1. The required changes are minor.
One thing to note, we still have a `RemovedInWagtail70Warning: The usage of `WidgetWithScript` hook is deprecated. Use external scripts instead.` warning that will be fixed by https://github.com/wagtail/wagtail-autocomplete/pull/180 when (if?) it gets merged.
=> Upgrade Wagtail to 6.1

cfgov/search/elasticsearch_helpers.py, requirements/libraries.txt, requirements/local.txt
This PR bumps some of our Python dependency versions. 
One notable one is django-opensearch-dsl, which in its 0.6 version made the `BaseSignalProcessor` we subclass into an abstract base class, and changed the delete-related method name. Instead of `BaseSignalProcessor`, we now subclass `RealTimeSignalProcessor `.
=> Update some of our Python dependencies

cfgov/tccp/jinja2/tccp/about.html, cfgov/unprocessed/apps/tccp/css/main.less
We rarely use `.respond-to-max(@bp-sm-min, {…});`, which is 601px, and instead use `.respond-to-max(@bp-xs-max, {…});` for mobile only, which is 600px.
- Fix issue where jump link didn't have underlining class.
- Change breakpoint to be 600px instead of 601px.
1. Check TCCP
=> TCCP: minor markup and breakpoint adjustments

cfgov/unprocessed/css/molecules/related-metadata.less, cfgov/v1/jinja2/v1/includes/molecules/related-metadata-enforcement-action.html, cfgov/v1/jinja2/v1/includes/molecules/related-metadata.html
- Update topic tag related metadata pattern to use jump links.
- Adds `a-link--jump-gold` modifier to handle related metadata appearance.
- Darken topic tag gray to be color contrast accessible.
- Add a black text hover state.
1. `yarn build` and visit http://localhost:8000/data-research/research-reports/no-fear-act-annual-report-fiscal-year-2015/ and compare the topic tags across screensizes to production.
2. Visit http://localhost:8000/enforcement/actions/1st-alliance-lending-llc-et-al/ and compare the topic tags across screensizes to production.
Before:
After:
Before:
After:
- Topic tags use jump links and should therefore always be links. They are currently only sometimes links.
=> Update topic tag related metadata pattern to use jump links

cfgov/hmda/jinja2/hmda/hmda-explorer-controls.html, cfgov/tccp/jinja2/tccp/includes/filter_form.html, cfgov/tccp/jinja2/tccp/landing_page.html, cfgov/v1/jinja2/v1/includes/organisms/filterable-list-controls.html, cfgov/wellbeing/jinja2/wellbeing/home.html, test/unit_tests/js/organisms/FilterableListControls-spec.js
The `a-legend` class was just an h4 with additional IE legacy CSS. With the legacy CSS removed it just becomes an h4, so best to just set `<legend class="h4">` instead.
See https://github.com/cfpb/design-system/pull/2009
- Replace `a-legend` with `h4`
=> Replace `a-legend` with `h4`

cfgov/v1/jinja2/v1/includes/molecules/footnotes.html
This PR changes the automatic H2 for a generated footnotes section from "Footnotes" to "Endnotes", per ongoing discussion about best-practices and labeling for this kind of web content. This is not meant to be the final word on how this section is labeled or set up, but instead an improvement/iteration on existing work that will be checked and reinforced (or altered) by forthcoming user research and testing.
1. localhost
2. Preview or view any page with a footnotes section
- This does conflict with the use of "footnotes" everywhere in the code; we can revisit that as needed down the road when we do proper, wider-scale reassessment and improvement of the functionality.
- …
=> Change H2 for footnotes to "Endnotes"

cfgov/unprocessed/apps/tccp/js/index.js
Closes https://github.local/Design-Development/External-Products/issues/398
- Go to http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards
- Hover over some tooltip triggers -> :)
- Check some boxes and/or sort the cards
- Hover over some tooltip triggers again -> :)
=> Reinitialize tooltips after htmx ajax calls

cfgov/unprocessed/css/main.scss
This import got wiped out in the Less to Sass conversion (added in https://github.com/cfpb/consumerfinance.gov/pull/8466 and wiped out in https://github.com/cfpb/consumerfinance.gov/pull/8514)
- Import footnotes CSS file to main
1. A page like http://localhost:8000/compliance/circulars/consumer-financial-protection-circular-2023-02-reopening-deposit-accounts-that-consumers-previously-closed/ should have inline footnote links.
=> Import footnotes CSS file to main

cfgov/unprocessed/apps/ask-cfpb/css/main.scss, cfgov/unprocessed/apps/cfpb-chart-builder/css/cfpb-chart-builder.scss, cfgov/unprocessed/apps/filing-instruction-guide/css/main.scss, cfgov/unprocessed/apps/paying-for-college/css/disclosures.scss, cfgov/unprocessed/apps/tccp/css/main.scss, cfgov/unprocessed/css/enhancements/typography.scss, cfgov/unprocessed/css/molecules/global-header-cta.scss, cfgov/unprocessed/css/molecules/global-search.scss, cfgov/unprocessed/css/molecules/tags.scss, cfgov/unprocessed/css/on-demand/job-listing-list.scss
This PR moves some mixins to remove some deprecation warnings we get on `yarn build`.
Sass says 
> Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version
This mostly comes from our heading mixins—which include nested CSS—so, those mixins need to appear after declarations.  The remaining warnings are mostly margin overrides that are applied to the heading mixins, which need to appear after the mixin in order to perform the override.
- Move some mixin calls to after declarations within a block.
- Fix misnamed tag BEM.
- Fix some deprecated division syntax.
1. `yarn build` on this branch should have less deprecation warnings than `yarn build` on `main`.
- There's a deprecation warning originating from the …
=> Reduce deprecation warnings

test/cypress/integration/consumer-tools/before-you-claim/before-you-claim-helpers.cy.js
We mock the responses from the retirement API, however the starting year was relative t the current year. This change freezes the starting year to 2024 and adjusts the month to ensure the tests pass against the fixture data.
Hopefully this avoids any future failures due to the continued march of time.
=> Freeze before-you-claim tests in 2024

cfgov/v1/jinja2/v1/includes/organisms/search-input.html
This class should be `a-text-input--full`, however, it only has an effect inside an `m-form-field` (see https://github.com/cfpb/design-system/blob/main/packages/cfpb-design-system/src/components/cfpb-forms/form-field.scss#L6). The global search separately makes its text field 100% width. We could either leave `a-text-input--full` to show the intent is that it is full width, or remove it. I opted to remove it, since it doesn't actually apply any styling.
- Remove `a-text-input__full`
1. Global search should be unchanged.
=> Remove `a-text-input__full`

cfgov/regulations3k/parser/regtable.py
These are old-style BEM names that should be updated.
- Update reg table BEM names
1. I'm not sure how this file is run, but an example page that uses these classes is http://localhost:8000/rules-policy/regulations/1010/2016-06-10/a/
- Can this not use a template that it populates with content? The classes here seem very buried.
=> Update reg table BEM names

cfgov/jobmanager/jinja2/jobmanager/job_listing_page.html
The `a-link__external-link` class shouldn't be specified here. External link markup is added by the cf.gov middleware. See CFPB Design System documentation at https://cfpb.github.io/design-system/components/links#link-with-icon.
To test, run a local server and confirm that the external link markup still appears correctly at any job listing under http://localhost:8000/about-us/careers/current-openings/.
External link icon still appears after this change:
=> Remove deprecated `a-link__external-link` class

cfgov/cdntools/backends.py
Wagtail 6.2 introduced new initialization and configuration in frontend cache backends. This ensures that gets run in the Akamai backend.
=> Fix Akamai frontend cache backend

cfgov/ask_cfpb/tests/test_blocks.py, cfgov/v1/jinja2/v1/includes/blocks/schema/faq-group.html, cfgov/v1/jinja2/v1/includes/blocks/schema/faq.html, cfgov/v1/jinja2/v1/includes/organisms/expandable.html, cfgov/v1/jinja2/v1/layouts/base.html
itemscope is just a boolean attribute, so the `=""` is unnecessary.
Also, removing the quotes in the multi-attribute conditionals in jinja prevents weird double quoting
=> Update itemscope usage and jinja multi-attributes-in-conditionals

cfgov/v1/jinja2/v1/includes/molecules/related-metadata-enforcement-action.html, cfgov/v1/jinja2/v1/includes/molecules/related-metadata.html
We alphabetize the topic tags in the filterable search results, but not necessarily in the sidebar of individual posts. This PR alphabetizes them.
- Alphabetize topic tags in sidebar
1. Visit http://localhost:8000/rules-policy/final-rules/prepaid-accounts-under-electronic-fund-transfer-act-regulation-e-and-truth-lending-act-regulation-z/ and see sidebar tags are alphabetized.
2. Visit http://localhost:8000/enforcement/actions/colony-ridge/ and see sidebar tags are alphabetized.
Before:
After:
=> Alphabetize topic tags in sidebar

cfgov/unprocessed/css/on-demand/event.scss
`h5` includes `text-transform: uppercase`, so it doesn't seem like we need to declare it again.
- Remove redundant `text-transform`
- Move h6 mixin below declarations and note letter-spacing override.
1. An event like http://localhost:8000/about-us/events/archive-past-events/2016-academic-research-council-meeting/ should be unchanged in its datetime appearances.
=> Events - Organize overrides

cfgov/v1/jinja2/v1/includes/organisms/expandable.html
Follow-up to https://github.com/cfpb/consumerfinance.gov/pull/8565. There's another itemprop that was getting double-quoted.
=> Update itemprop quoting in jinja template 

cfgov/unprocessed/apps/regulations3k/css/reg-navigation.scss
This code includes the heading-4 mixin, but then overwrites the font-size, font-weight, and margin-bottom, which is most of the heading-4 mixin. The remaining values of `letter-spacing`, `line-height`, `text-transform` come from the base secondary nav.
- Swap out heading mixin
1. `o-secondary-nav__link--parent` on a regs page, like http://localhost:8000/rules-policy/regulations/1092/204/, should be visually unchanged.
=> Swap out heading mixin

cfgov/unprocessed/css/organisms/footer.scss
In the Less to Sass work this override for the default `li` margin was overlooked.
- Bugfix: Footer missing margin clearing at mobile
1. `yarn build` and visit any page and resize to mobile and hover over the footer links. The line above and below the link should go solid.
Before:
After:
- The footer links should be re-written to be groups of jump links.
=> Bugfix: Footer missing margin clearing at mobile

cfgov/unprocessed/css/on-demand/event.scss
On event pages like https://www.consumerfinance.gov/about-us/events/archive-past-events/2016-academic-research-council-meeting/ we make the "modification date" have a tighter letter spacing.
It would be easier if we didn't have to override our standard h6 letter spacing. This seems like a non-standard pattern that we should probably remove, particularly since there's another date on the same page without the same spacing.
- Remove h6 letter-spacing override
1. http://localhost:8000/about-us/events/archive-past-events/2016-academic-research-council-meeting/ shouldn't have such tightly spaced modification date compared to production.
Before:
After:
=> Remove h6 letter-spacing override

cfgov/jobmanager/jinja2/jobmanager/job_listing_list.html, cfgov/retirement_api/jinja2/retirement_api/about.html, cfgov/unprocessed/apps/paying-for-college/css/cf-enhancements.scss, cfgov/v1/jinja2/v1/includes/organisms/chart.html, cfgov/v1/jinja2/v1/includes/organisms/mortgage-chart.html, cfgov/v1/jinja2/v1/includes/organisms/mortgage-map.html, cfgov/v1/jinja2/v1/includes/organisms/simple-chart.html
`short-desc` only has styles in `cf-notification`, which is a deprecated notification used on PfC disclosures, which actually doesn't include `short-desc` in its markup.
- Remove `short-desc`
=> Remove `short-desc` CSS class

cfgov/unprocessed/apps/regulations3k/css/reg-search.scss
Expandables already format labels as h4s, so the `@include h4;` was redundant, other than it added margin at mobile. However, with the margin added it was misaligning the label text and the cue, since the margin was only added to the label. Probably best to just strip out this customization and make the label slightly closer to its content, which matches the desktop appearance.
- Moves all expandable overriding code together and adds a TODO.
- Change `nth-child(3n)` to `last-child()` to remove last border of filters.
- Removes expandable label h4 customization.
1.  `yarn build`
2. Visit http://localhost:8000/rules-policy/regulations/search-regulations/results/?regs=1002&q=mortgage 
3. Resize to mobile and compare the filters labels position to production. It should be slightly closer to …
=> Remove regs label margin

cfgov/prepaid_agreements/jinja2/prepaid_agreements/detail.html, cfgov/unprocessed/apps/prepaid-agreements/css/main.scss
The prepaid agreements have definition lists for each company. The detail pages set these definition terms (dt) as h2s, which includes them in the heading structure. On the search results list they are not h2s, so are not included in the heading structure.
On the details page, the dts are h2s that are set as h4s via CSS, which steps down at mobile. The search result page set these dts as heading-4s, which don't step down at mobile.
I could be wrong, but it doesn't seem like the dts should be heading elements, but instead their parent should be the heading element, which it is (the company name). 
- Remove h2 from definition terms.
- Remove unneeded heading CSS.
1.  `yarn build` and visit http://localhost:8000/data-research/prepaid-accounts/search-agreements/ and compare to production. …
=> Remove h2s from prepaid agreements

cfgov/unprocessed/apps/regulations3k/css/reg-search.scss
Tiny follow-on to https://github.com/cfpb/consumerfinance.gov/pull/8577/ to remove unnecessary parentheses.
=> Tiny fix to remove parentheses

cfgov/unprocessed/apps/paying-for-college/css/disclosures.scss
I couldn't find that `.estimated-expenses .aid-form__summary-heading` matched any element.
- PfC: Remove `.estimated-expenses .aid-form__summary-heading`
1. Check [the disclosures tool](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=154022&pid=BAHCA&totl=70950&tuit=14160&hous=7109&book=1150&tran=500&othr=4743&pelg=0&schg=&stag=&othg=&mta=&gib=&wkst=0&ppl=&parl=&perl=&subl=3500&unsl=6000&gpl=&prvl=&prvi=&prvf=&insl=&insi=&inst=&oid=4D0B9265B45716DF4B81EEB4BE117E1DF69871AF) and try to find an element that matches `.estimated-expenses .aid-form__summary-heading`.
=> PfC: Remove `.estimated-expenses .aid-form__summary-heading`

cfgov/tccp/management/commands/validate_tccp.py, cfgov/tccp/tests/test_validate.py, requirements/libraries.txt
This change removes our matplotlib dependency and chart-generation code and option in the TCCP validation management command.
This should fix our dev docker container build for folks while we're still on Python 3.8.
=> Remove matplotlib and dependent code

cfgov/unprocessed/apps/owning-a-home/css/explore-rates.scss
Introduced in the scss migration
=> Fix explore rates columns

requirements/libraries.txt
This change updates wagtail-inventory to 3.0, which adds support for Wagtail 6.2's universal listings in the report view.
This unbreaks the block inventory report.
=> Bump wagtail-inventory

cfgov/tccp/jinja2/tccp/includes/fields.html
Changes "N/A" to "Not available" when APRs are blank in the data.
See GHE/Design-Development/External-Products/issues/399 for full details. The upshot is when people saw "N/A balance transfer APR" on cards in the card list in usability testing, they thought the card had no APR on balance transfers instead of what it actually means: the card doesn't offer balance transfers. This change is our attempt to make it clearer.
Note that the `apr` macro is used in lots of places and, in theory, "N/A" (as in "not applicable") might make more sense in some spots. Practically, though, in the current datasets the only place "N/A" will show up is in the card list for cards that don't offer a balance transfer, so this change seems better than something more complex like making both "N/A" and "Not …
=> TCCP: Change "N/A" to "Not available"

.env_SAMPLE, cfgov/apache/conf.d/wagtail_deletion.conf.sample, cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/production.py, cfgov/cfgov/settings/test.py, cfgov/wagtail_deletion_archival/apps.py, cfgov/wagtail_deletion_archival/templates/wagtail_deletion_archival/import_page.html, cfgov/wagtail_deletion_archival/tests/temp_storage.py, cfgov/wagtail_deletion_archival/tests/test_utils.py, cfgov/wagtail_deletion_archival/tests/test_views.py, cfgov/wagtail_deletion_archival/tests/test_wagtail_hooks.py, cfgov/wagtail_deletion_archival/utils.py, cfgov/wagtail_deletion_archival/views.py, cfgov/wagtail_deletion_archival/wagtail_hooks.py, requirements/libraries.txt
These code changes propose using Django storage to store and serve the Wagtail deletion archive from #8310, instead of using Apache to serve those files.
This simplifies the configuration and makes it easier to test locally and easier to port in future to other webserver approaches.
With these changes, the deletion archive is now only available behind the Wagtail admin login, at the URL /admin/__deleted/. This URL provides a nicely formatted Wagtail report view where archives can be downloaded (instead of the current PR approach that uses Apache directory serving).
With this change, Django storage configuration has been migrated to `settings.STORAGES` from `settings.STATICFILES_STORAGE`, which was [deprecated in Django 4.2](https://docs.djangoproject.com/en/5.1/releases/4.2/#custom-file-st …
=> Use Django storage for Wagtail deletion archive

cfgov/unprocessed/apps/tccp/js/index.js
Closes https://github.local/Design-Development/External-Products/issues/420
This focuses the next element in the list on reveal after click the the "Show more results" button. This is slightly different that what is being ask for in that issue (setting tab index after the last tabbed result) but seems slightly more helpful. Specifically, since the next result can be off screen after activating "show more," auto-focusing the next element helpfully (imo) re-orients the user to the next item and brings it on screen.
Thoughts @niqjohnson? I can also do precisely what that issue is asking for but (imo) it's worse keyboard UX.
=> Focus first un-hidden result on reveal

cfgov/tccp/jinja2/tccp/includes/tooltip.html
Closes https://github.local/Design-Development/External-Products/issues/419
This allows a user to read tooltips as they tab through the list of cards.
An alternative would be to auto-open all tooltips when a user focuses on the card that contains them, which would make tabbing through the list a bit quicker. I don't really have a preference either way. Thoughts @niqjohnson?
=> Give tccp tooltips a tabindex since spans aren't natively tabbable

cfgov/teachers_digital_platform/models/pages.py, cfgov/teachers_digital_platform/tests/models/test_activity_index_page.py, cfgov/v1/models/filterable_page.py
In #8310 we added functionality to allow us to delete our "Trash" site that was being used in lieu of Wagtail deletion.
Now that the Trash is no more, this commit removes a few straggling references to it.
=> Remove references to the Trash

cfgov/v1/wagtail_hooks.py
This is not used in the admin! Begone!
=> Remove unused/unneeded form-explainer.css file from wagtail admin

docs/running-virtualenv.md, esbuild/build.js, package.json
There's a bug in the `yarn scripts` task where it needs a loader for SCSS. Instead of fixing that, I'm proposing ripping out the `yarn scripts`, `yarn styles` and `yarn copy` tasks and just having a single `yarn build` (and accompanying `yarn watch`) task. Build doesn't take _that_ long, and that simplifies our maintenance of these scripts.
- Remove `yarn scripts`, `yarn styles`, `yarn copy` tasks
1. `yarn build` and `yarn watch` should run without error.
=> Remove `yarn scripts`, `yarn styles`, `yarn copy` tasks

cfgov/v1/tests/management/commands/test_publish_pages.py
Ruff started throwing a SIM115 error:
```
cfgov/v1/tests/management/commands/test_publish_pages.py:33:14: SIM115 Use a context manager for opening files
```
This fixes that by using a context management.
=> Fix SIM115 by using a context manager

requirements/libraries.txt
This PR updates wagtail-footnotes to 0.13.0, which includes [our fix for footnote ordering](https://github.com/torchbox/wagtail-footnotes/pull/74). It makes two changes to footnotes admin UX:
- Fixes a bug where footnotes could change how they're ordered in the admin for content editors between adding footnotes and saving the draft with the new footnotes. 
- Makes it possible for content editors to reorder footnotes in the admin just like any other Wagtail content element.
Neither of these ordering problems had any impact on the final rendered page — rendered footnotes are always numbered and ordered in the the order they are referenced in content.
See GHE/Design-Development/Design-and-Content-Team/issues/545 and https://github.com/torchbox/wagtail-footnotes/issues/75 for more context.
=> Update wagtail-footnotes to fix footnote ordering

cfgov/jinja2/robots.txt
The "sitemap" directive in robots.txt should be "Sitemap".
See
- https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt
- https://en.wikipedia.org/wiki/Robots.txt#Sitemap
- https://search.gov/indexing/robotstxt.html#xml-sitemaps
=> Capitalize "Sitemap" in robots.txt

cfgov/core/tests/test_utils.py, cfgov/core/utils.py
Currently certain archive-it.org URLs are missing an external link icon due to an issue with the regex we use to detect non-cf.gov URLs.
For example, a URL like this:
https://archiving-service.com/1234/https://www.consumerfinance.gov/about-us/blog/fall-2015-rulemaking-agenda/
is missing its external link icon because the current regex matches the "www.consumerfinance.gov" part of the URL, even though it's in the path part, not the host part.
This commit fixes that and adds a regression test.
To test, run a local server and visit:
http://localhost:8000/about-us/blog/fall-2015-rulemaking-agenda/
and compare it against production:
https://www.consumerfinance.gov/about-us/blog/fall-2015-rulemaking-agenda/
|Before|After|
|-|-|
|<img width="619" alt="image" …
=> Fix link markup for certain non-cf.gov URLs

cfgov/unprocessed/js/modules/util/FormModel.js
This doesn't seem like it is needed? It looks like `isInGroup` will always have a value that it passes to `_getLabelText`, which has an if/else statement that checks `isInGroup`' value.
- FormModel: remove `false ||`
2. /blog should work as before.
=> FormModel: remove `false ||`

cfgov/unprocessed/apps/cfpb-chart-builder/js/charts/LineChartIndex.js, cfgov/unprocessed/apps/cfpb-chart-builder/js/utils/process-json.js, cfgov/unprocessed/js/routes/on-demand/simple-chart/tilemap-chart.js
- Stops cfpb-chart-builder from removing data before 2009 in its processing script
- Changes the index charts' y-axes (as per stakeholder)
- Removes projected data from index charts
=> Changes supporting the CCT 2024 data release

cfgov/privacy/jinja2/privacy/privacy-styles.html
I couldn't find a reference to this ID
- Remove `id_description` ID
=> Privacy forms: Remove `id_description` ID

cfgov/agreements/jinja2/agreements/search.html, cfgov/v1/jinja2/v1/includes/molecules/pagination.html, test/unit_tests/apps/teachers-digital-platform/js/tdp-analytics-spec.js
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
> you can nest the <input> directly inside the <label>, in which case the for and id attributes are not needed because the association is implicit:
- Remove `for` attribute from pagination label.
1. Run local server and visiting /blog and /data-research/prepaid-accounts/search-agreements/ and interact with the pagination and see that you can click the text next to the page number input to go to the input.
- The input IDs get some use in the Cypress tests, but maybe those could be pointed to something else and the IDs could be removed overall.
=> Remove `for` attribute from pagination label

cfgov/unprocessed/css/print.scss
Long URLs were not wrapping and getting clipped in the print styles. This helps that.
- Add white-space:normal to print CSS
1. Visit /about-us/blog/recovering-financially-from-heavy-storms-and-preparing-for-storm-season/ and either emulate the print styles (dev tools > rendering > emulate media type, or FIle > Print and view the preview. The long URL should be wrapped.
=> Add white-space:normal to print CSS

.github/workflows/build-artifact.yml, .github/workflows/builder.yml
Currently there are two GitHub Actions for this repository that attempt to gate their execution by ensuring that they don't run on forks, using the check 
```
if: github.repository == 'cfpb/consumerfinance.gov'
```
This doesn't work properly, because on PRs this still refers to this repo (cfpb/consumerfinance.gov), not the fork.
You can see an example where this didn't work right on #8617, where @lfatty opened a PR from his fork but the "Build cf.gov artifact" action [still ran](https://github.com/cfpb/consumerfinance.gov/actions/runs/11578761970/job/32233360954).
This PR attempts to fix the syntax to work properly using this check instead:
```
if: "! github.event.pull_request.head.repo.fork"
```
I've created this PR from my fork so these two actions should not run.
=> Don't run builder GitHub Actions on forks

.env_SAMPLE, .github/workflows/functional-tests.yml, cfgov/cfgov/settings/base.py, docker-compose.yml, docker-entrypoint.sh, dump-data.sh, requirements/libraries.txt, tox.ini
Previously cf.gov supported use of the `DATABASE_URL` environment variable to configure the Django database, as implemented by the [dj-database-url](https://github.com/jazzband/dj-database-url) package. This functionality was removed in 2022 (in 4d0b24b1d326a884545a3a066ad765958e379541) to support a since-abandoned migration to Helm. Newer EKS/Helm workflows allow us to use a single environment variable for DB configuration, motivating restoration of this capability.
With this change, we no longer rely on environment variables like `PGHOST`, `PGUSER`, etc. but instead rely on the single `DATABASE_URL` variable.
See internal WAM#8 for additional context.
=> Restore use of DATABASE_URL for DB configuration

cfgov/unprocessed/js/organisms/VideoPlayer.js, cfgov/v1/jinja2/v1/includes/organisms/video-player.html
- Add placeholder `title` attribute to video iframe.
- Remove `aria-hidden` and `tabindex` when the video has loaded.
1. Visit /about-us/blog/addressing-racial-inequities-consumer-finance-markets/ and load the page without JS enabled and see that there is a placeholder `title` attribute. Load the video normally and see that the `title` attribute value is replaced and the `aria-hidden` and `tabindex` values are removed.
=> Handle a11y in video iframe

cfgov/v1/jinja2/v1/includes/molecules/pagination.html
If you tab through the pagination buttons, the order is wrong.
With https://github.com/cfpb/design-system/pull/2091, the pagination component uses a grid, so the order can now be corrected and it won't harm the layout. 
- Swap order of pagination buttons to follow logical tab order.
1. Visit /blog and tab to the pagination component and see that the order follows the logical tab order.
=> Pagination: Swap order of buttons

cfgov/prepaid_agreements/jinja2/prepaid_agreements/index.html, test/cypress/integration/data-research/prepaid-agreements-search/prepaid-agreements-search.cy.js
In https://github.com/cfpb/consumerfinance.gov/commit/563b99ddaa34a4a7f671754d58063869e7a74419#diff-7996a09f3bb94a40123742ebd6f5d5fad5c89a49e2eee19d24149f7e5f15bf54L80 the input value was accidentally copied from the Ask CFPB search. It should actually have a different variable name.
- Prepaid agreements DB: bugfix incorrect input value
- Add test for search term in input.
1. Visit http://localhost:8000/data-research/prepaid-accounts/search-agreements/ and perform a search. See that the search term remains in the search input.
=> Prepaid agreements DB: bugfix incorrect input value

.github/PULL_REQUEST_TEMPLATE.md
It can be nice to put screenshots in a before/after table, which sizes them down and gives them borders. This PR adds a starter before/after table to the PR template.
- Add before/after table starter to PR template.
=> Add before/after table starter to PR template

cfgov/prepaid_agreements/jinja2/prepaid_agreements/search_results.html, cfgov/unprocessed/apps/prepaid-agreements/css/search.scss
If there are no results in a search, the narrow results filter shows up, but broken and un-functional. This PR adds some filler text to replace it when there are no results.
- Prepaid agreements DB: Add no-results filter state.
- Standardize CSS padding to use hardcoded pixels in calculations.
1. http://localhost:8000/data-research/prepaid-accounts/search-agreements/?search_field=name&q=mortgage and see that there's a no results filter state. Try a good search to remove it.
Before:
After:
=> Prepaid agreements DB: Add no-results filter state

cfgov/agreements/jinja2/agreements/search.html
- Update the credit card agreement db to use our standard pagination template.
1. Visit http://localhost:8000/credit-cards/agreements/issuer/citibank-na/?page=3#ccagrsearch and interact with the pagination. It should work like prod.
=> Credit Card Agreements DB: Use standard pagination template

cfgov/unprocessed/apps/regulations3k/css/main.scss
import is deprecated in sass. Migrate to use instead.
- iRegs: migrate scss imports to use
1. Visit an iregs page, such as http://localhost:8000/rules-policy/regulations/1002/, and ensure the sidebar and search are unchanged to prod.
=> iRegs: migrate scss imports to use

cfgov/paying_for_college/data_sources/bls_processing.py, cfgov/prepaid_agreements/jinja2/prepaid_agreements/index.html, cfgov/unprocessed/apps/prepaid-agreements/css/search-bar.scss, cfgov/unprocessed/apps/prepaid-agreements/css/search.scss
The presence or absence of `flex-fixed` does not appear to make a difference to the drop-down menu on the prepaid agreements search. 
`.search__wrapper.o-well` did not appear to target anything. The only `o-well` on prepaid agreements is the database disclaimer, which appears outside of the `search__wrapper`.
`num-results` appears to have been copied over from iRegs, which has it in the markup. However, prepaid agreements does not have it in the markup.
- Remove `flex-fixed` class, which did not appear to affect anything.
- Remove `layout-column` class, which I couldn't find references for.
- Remove `.search__wrapper.o-well` rule, which appears to be unused.
- Remove `num-results` class, which appears to be unused.
1. `yarn build` and …
=> Prepaid agreements: Remove unused CSS

cfgov/unprocessed/apps/prepaid-agreements/css/main.scss
- Prepaid agreements: Migrate Sass imports to Sass use.
1. `yarn build` and http://localhost:8000/data-research/prepaid-accounts/search-agreements/ should be unchanged.
=> Prepaid agreements: Migrate Sass imports to Sass use

cfgov/unprocessed/apps/form-explainer/css/main.scss, cfgov/unprocessed/apps/paying-for-college/css/main.scss, cfgov/unprocessed/css/on-demand/error.scss, cfgov/unprocessed/css/on-demand/event.scss, cfgov/unprocessed/css/on-demand/sidebar-contact-info.scss, cfgov/unprocessed/css/on-demand/simple-chart.scss
In LESS, these imports were `(reference)`s which allowed access to variables without actually duplicating the css. However, in the switch to scss, these imports were copied over even though they are no longer needed (as the variables are imported directly from the design system now).
The upshot is that these small css files (were) including an entire copy of main.css when built, ballooning their size like 20x (or more). This fixes that.
- Pull and build. Should work without errors.
- Pages with the various components, eg. localhost:8000/consumer-tools/prepaid-cards/understand-fees/, http://localhost:8000/paying-for-college/your-financial-path-to-graduation/, etc. should look identical to prod.
=> Remove unneeded 'main' imports from scss

docker-compose.sso.yml
Our SSO local rig pulls the "latest" oidc-testprovider image. A [new version](https://hub.docker.com/r/mozilla/oidc-testprovider/tags?name=testprovider) that was released Oct. 29 breaks our rig with a client-id error.
<hr>
<hr>
There's nothing wrong with the passing of our single-digit client_id, but perhaps some new code demands a longer one.
I found that stepping back to the previous version will keep our rig humming while we explore how to address the breaking change, or wait for a fixed image if it's a bug.
- Remove any existing oidc-testprovider docker image you may have locally.
- Run `docker compose -f docker-compose.sso.yml up` to pull the latest image and launch the SSO machinery.
- Try to log in to localhost:8000/admin
=> Pin the version of the mozilla/oidc-testprovider image

cfgov/core/utils.py, cfgov/v1/management/commands/_sync_storage_base.py, cfgov/v1/management/commands/sync_image_storage.py
Ruff recently auto-updated to 0.8.0, which introduced some breaking changes.
- Migrate ruff flagged code to using format specifiers instead of percent format.
1. BEWD lint PR check should pass.
=> Migrate ruff flagged code to using format specifiers instead of percent format

cfgov/unprocessed/css/organisms/video-player.scss
Buttons lay out their icon and divider using flexbox now (see https://github.com/cfpb/design-system/pull/2091), so explicitly setting the button to `display: block` breaks this, as is done in the video player close button.
- Video Player: Remove `display: block;` from video close button.
1. Play a featured content video, such as that on http://localhost:8000/about-us/diversity-and-inclusion/self-assessment-financial-institutions/ and see that the divider is correctly between the text and icon.
|      <img width="194" alt="Screenshot 2024-11-26 at 3 32 13 PM" src="https://github.com/user-attachments/assets/a79f67d5-0e6e-4f46-bbfd-97cbc41ff410">|   <img width="157" alt="Screenshot 2024-11-26 at 3 31 57 PM" …
=> Video Player: fix close button CSS

cfgov/v1/jinja2/v1/includes/organisms/featured-content.html, cfgov/v1/template_debug/featured_content.py
This pattern appears to have been usurped by the 25/75 info unit pattern. It was not possible to set this in Wagtail, as there was no option to set it. It is only set in the debug template view. 
Accompanying DS PR https://github.com/cfpb/design-system/pull/2128
- Remove `o-featured-content-module--left`
1. View http://localhost:8000/admin/template_debug/v1/featured_content/ and see that the left aligned version is gone.
On arabic pages, the FCM maybe should flip, but this should happen without the need to add a modifier.
(e.g. https://www.consumerfinance.gov/language/ar/)
=> Remove `o-featured-content-module--left`

.prettierignore
https://github.com/cfpb/consumerfinance.gov/pull/8657 removed Chosen from CC agreements. This PR removes some no longer applicable references from the prettier ignore config.
- Remove agreements' chose and jquery entries from prettier ignore config
1. `yarn lint` should be unchanged.
=> Remove agreements' chose and jquery entries from prettier ignore config

docker-entrypoint.sh, initial-data.sh, refresh-data.sh
This commit modifies several scripts to make it easier to setup the database as part of a containerized cf.gov deploy.
It removes a portion of the refresh-data.sh script that attempts to manually rename the existing 'cfpb' schema in our database dumps, to a schema named for a different Postgres user. We no longer use the PGUSER environment variable as of 59b109b2a3d85fa551a8cb37b82cdbc9ad9058e8, so this code doesn't work right now.
In the future, if we need to import a 'cfpb' schema into a database where the username is something different (for example in an RDS instance where we might have less control over the username) we might have to revisit this code.
This change also consolidates the various 'DB setup' steps we do after loading a dump -- running migrations, creating the cache …
=> Database script updates to support containerization

cfgov/apache/conf.d/alias.conf, cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/production.py, requirements/libraries.txt
This change uses [WhiteNoise](https://whitenoise.readthedocs.io/en/latest/index.html) for static file serving in development and when served via Apache.
1. Run `runserver` in your preferred way and observe that static files serve successfully.
=> Use WhiteNoise for serving static files

cfgov/cfgov/settings/production.py
We've got some unexpected behavior with WhiteNoise's `CompressedManifestStaticFilesStorage`. This quick change switches back with Django's `ManifestStaticFilesStorage` until we can do more testing.
This backs out one change made in #8678, but not the use of WhiteNoise generally.
=> Switch back to Django's ManifestStaticFilesStorage

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/production.py
Commit de10b0745bb946ac10257b9a0b5fab62e2dcc9bf in #8678 for some reason removed the WhiteNoise middleware entirely.
This change restores it, and reverts #8680 using WhiteNosie to compress and hash static files.
I've tested these changes on staging.
=> Restore all white noise

cfgov/privacy/forms.py
The ChoiceField for the radio buttons needs to specify the radio select widget for it to get proper IDs.
- Fix privacy forms address selector by adding a RadioSelect widget to privacy form contact_channel fields.
1. Visit http://localhost:8000/privacy/records-access/ and http://localhost:8000/privacy/disclosure-consent/ and see that you can toggle the email/address radio buttons.
=> Fix privacy forms address selector

cfgov/tccp/jinja2/tccp/cards.html, cfgov/tccp/jinja2/tccp/includes/card_list.html, cfgov/tccp/jinja2/tccp/includes/tooltip.html, cfgov/unprocessed/apps/tccp/css/main.scss, cfgov/unprocessed/apps/tccp/js/index.js
This Pull Request will adjust some accessibility features. These aren't major changes, but will move things more in line with recommendations.
As a result of this PR, tab-based keyboard navigation will be improved to allow users to get more information without clicking through to see more details on the card. It will also skip the "faded" 11th card initially, sending the user instead to the "Show more results" button, then redirecting the user back to the 11th card when that button is clicked.
- Change `tabindex` properties
- Add handling for "Enter" when then "proxy link" is focused
1. Visit `/consumer-tools/credit-cards/explore-cards/cards/` and search
2. Use keyboard navigation to `TAB` through the results. You should focus the entire "card", then the tooltips (if present), then the …
=> TCCP: ITAP Changes

cfgov/tccp/jinja2/tccp/includes/card_list.html
Minor fix to get tooltip content rendering correctly.
---
1. Make sure the "As of Jun. 20, 2024" tooltip content renders correctly, without the `('` and `')` around it.
| <img width="496" alt="before" src="https://github.com/user-attachments/assets/c2831c6c-1f32-4b15-a2ae-f2d38944465b" />  | <img width="499" alt="after" src="https://github.com/user-attachments/assets/536babcb-bfd4-49ff-9f43-e9f74a293a99" /> |
=> TCCP: Fix tooltip content

cfgov/tccp/jinja2/tccp/card.html
Fixes an error for cards that don't provide a median length of balance transfer.
---
- Handle cards that offer balance transfers but don't provide a median length of balance transfer
1. Check a card that offers balance transfers but doesn't provide a median length of balance transfer, like `/consumer-tools/credit-cards/explore-cards/cards/southeast-financial-credit-union-visa-platinum-credit-card/` or `/consumer-tools/credit-cards/explore-cards/cards/first-national-bank-of-omaha-seiusm-platinum-editionr-visa-card/`, and confirm the card details page renders OK and without any reference to a transfer period
2. Check some other cards that do offer balance transfers and do specify the median length to make sure their details page hasn't changed
- PR titles are used to generate the change log …
=> TCCP: Fix cards with no balance transfer period

cfgov/unprocessed/apps/ccdb-search/css/main.scss
=> DATAP-1586 - CCDB: remove spacing under filter headings

cfgov/tccp/tests/test_views.py, cfgov/tccp/views.py
This prevents key error 500s when the situations are manually nudged
=> Return an empty list for tccp situations when invalid data gets cleaned

cfgov/v1/atomic_elements/charts.py, requirements/libraries.txt
The wagtailcharts 0.6.2 release notes say 0.6.1 was not released correctly: https://github.com/overcastsoftware/wagtailcharts/releases
In addition, it appears we copied in an old list of js dependencies that included accounting.js, a script removed in 0.6. 
- 2022 list: https://github.com/overcastsoftware/wagtailcharts/blob/v0.5/wagtailcharts/templates/wagtailcharts/tags/render_charts.html
- 0.6 release note: https://github.com/overcastsoftware/wagtailcharts/blob/main/RELEASE_NOTES.md?plain=1#L12
This updates the package to 0.6.2 and removes our include of accounting.js, which is causing server errors in production.
=> Update the wagtailcharts package and remove an outdated script

cfgov/v1/wagtail_hooks.py
This PR adds a wagtail hook that leverages the machinery introduced to manage the `translation_links` to allow easy switching in the admin view between available versions of languages. To wit, see this screenshot:
If a page has no translations, no menu item will be added. If a page has many translations, eg. http://localhost:8000/language/cfpb-in-english/, they'll all be added:
This latter case is a bit unwieldy, but, imo, rare enough that it's worth the general benefit.
This work was spurred on by the old school wagtailadmin_override used in ask-cfpb for the link between english and spanish answer pages:
The idea here being that, if/when we move Ask to the now-standard way of associating translations with each other, it would be cool to retain the functionality of being able to quickly …
=> Add wagtail hook to create menu items for translations

.github/workflows/backend.yml, .github/workflows/filter-backend.yml
The backend.yml and filter-backend.yml GitHub Actions workflow files currently contain invalid path directives. The paths and paths-ignore directives only apply to the pull_request action, not the merge_group or workflow_dispatch actions.
See docs at:
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#merge_group
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch
=> Remove invalid Actions workflow path directives

cfgov/v1/jinja2/v1/home_page/_hardcoded_es.html
Update new Spanish homepage content.
---
- Updated content for the new Spanish homepage
1. If needed, enable the `SPANISH_HOMEPAGE` flag (though it should already be enabled for a local environment)
2. Make sure the Spanish homepage, `/es/`, looks like the screenshot below
3. If you happen to read Spanish, give the content a quick skim to make sure it all makes sense
| Current | New  |
| ![old-es](https://github.com/user-attachments/assets/5467ffc7-c560-4003-98b7-7f403f08e77a) | ![new-es](https://github.com/user-attachments/assets/b6183c78-252d-43be-886e-80c14526a732) |
- The new Spanish homepage is still behind a feature flag. When the new page launches, we'll clean up the feature flag and unused files: `home_page_legacy.html` and `hardcoded_legacy_es.html`.
- PR …
=> Update Spanish homepage content

cfgov/cdntools/management/commands/purge_by_cache_tags.py, cfgov/cfgov/urls.py, cfgov/core/management/commands/inactive_users.py, cfgov/data_research/tests/test_scripts.py, cfgov/paying_for_college/disclosures/scripts/load_programs.py, cfgov/paying_for_college/disclosures/scripts/notification_tester.py, cfgov/paying_for_college/models/disclosures.py, cfgov/paying_for_college/tests/test_load_programs.py, cfgov/paying_for_college/tests/test_scripts.py, cfgov/paying_for_college/tests/test_views.py, cfgov/privacy/forms.py, cfgov/regulations3k/parser/regtable.py, cfgov/scripts/http_smoke_test.py, cfgov/scripts/static_asset_smoke_test.py, cfgov/tccp/management/commands/validate_tccp.py, cfgov/v1/atomic_elements/molecules.py, cfgov/v1/atomic_elements/organisms.py, cfgov/v1/feeds.py, cfgov/v1/management/commands/delete_page.py, cfgov/v1/template_debug/tables.py, cfgov/v1/tests/atomic_elements/organisms/test_organisms.py, cfgov/wellbeing/views.py
Ruff auto-updated to v0.9.0 on GHA and is breaking. To see these breaking changes locally I ran `pip install --upgrade ruff` to update ruff (`./backend.sh` does not update ruff) and ran `ruff format`
- Ruff auto-format changes for v0.9.0
=> Ruff auto-format changes for v0.9.0

cfgov/paying_for_college/tests/test_models.py
This test in paying_for_college isn't actually testing anything. The call to
```py
self.assertTrue(mock_requests.called_with, unicode_endpoint.encode("utf-8"))
```
is invalid because mock objects don't have a `called_with` method, they have [`assert_called_with`](https://docs.python.org/3.8/library/unittest.mock.html#unittest.mock.Mock.assert_called_with).
The existing code is asserting True against something that is always truth, namely, the new mock returned by the call to the non-existent `mock_requests.called_with` method. The second argument is ignored as it's treated as [the `msg` argument in `assertTrue`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertTrue).
This PR fixes the test by correctly calling `assert_called_with` and also changing the mock to patch …
=> Fix invalid paying_for_college test

cfgov/paying_for_college/tests/test_commands.py, cfgov/paying_for_college/tests/test_scripts.py, cfgov/paying_for_college/tests/test_search.py, cfgov/regulations3k/tests/test_scripts.py
This followup to #8711 fixes various Python tests that are incorrectly trying to call `called_with` on a mock object, when the correct call is [`assert_called_with`](https://docs.python.org/3.8/library/unittest.mock.html#unittest.mock.Mock.assert_called_with).
Most of these tests are in the Paying for College disclosures code, and one is in iRegulations.
Currently these tests don't actually test anything, as `assertTrue(something that is truthy)` does nothing.
=> Fix incorrect Python tests using mock.called_with

cfgov/housing_counselor/geocoder.py, cfgov/housing_counselor/tests/management/test_geocoder.py
Currently, if when the housing_counselor mgmt command attempts to geocode data with an invalid zipcode, it throws a `KeyError`. This bails out of the command and thus causes our daily update to fail.
Since we don't control this data, I think it would be better to simply drop the counselor with the invalid zip (while logging that this is being done). This should allow us to be more resilient to erroneous data creeping into the HUD list of counselors.
=> Drop counselors with invalid zips when geocoding

cfgov/unprocessed/apps/paying-for-college/css/cf-enhancements.scss, cfgov/unprocessed/apps/paying-for-college/js/disclosures/index.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/utils/print-page.js, cfgov/unprocessed/apps/paying-for-college/js/disclosures/views/financial-view.js
This PR will address a few bugs in our Paying for College "Dynamic Disclosures" application. It fixes a bug with Private Loans, a style bug with numeric icons and unordered lists, and a fix for the Print Button in the final step of the disclosure.
- Run enumeratePrivateLoans() on init to fix Remove Button bug
- Fix numbered icons padding in Part 3 list
- Fix print button
1. Try to remove the first Private Loan (without adding one). There should be no error.
2. Check on the numbered icons and make sure they don't overlap text in "Next Steps"
3. Make sure the Print button in "Next Steps" shows the browser's print dialog.
=> Paying for College: Dynamic Disclosures - Bug Fixes

cfgov/cfgov/settings/base.py, cfgov/tccp/views.py
This PR will remove the code that leaves TCCP as a feature-flag-dependent product.
- Change TCCP's views.py to use TemplateView instead of FlaggedTemplateView, etc
- Remove "TCCP" from flags in base.py
1. Make sure http://localhost:8000/consumer-tools/credit-cards/explore-cards/ works as expected!
=> Remove TCCP Feature Flag

cfgov/jinja2/rural-or-underserved/index.html
Adds a small note about the rout data being inaccurate in Connecticut in early Jan. Concomitant with this PR being merged, I'll push the new data.
- Pull
- Note the added FAQ entry at http://localhost:8000/rural-or-underserved-tool/#rural-or-underserved
=> Add note about rout data being off for CT in early Jan

cfgov/v1/management/commands/update_data_snapshot_values.py, cfgov/v1/tests/management/commands/test_update_data_snapshot_values.py
This is the last manual piece of the otherwise automated CCT update process. This now updates the cct sublanding page with the date from the snapshot file so the whole update is fully automated.
=> Update cct snapshot management command to update landing page

cfgov/tccp/jinja2/tccp/cards.html, cfgov/unprocessed/css/enhancements/layout-base.scss
There's a slight but annoying horizontal scroll on the [TCCP card list page](https://www.consumerfinance.gov/consumer-tools/credit-cards/explore-cards/cards/) in mobile Safari (see GHE/Design-Development/External-Products/issues/491). Looks like it was being caused by the combination of breadcrumbs on a full-width page, which I don't think we do anywhere else on the site (at least not in quite the same way). It's most easily fixed with an `overflow-x: hidden` on the `u-layout-grid` container, [just like we do in the 2-1 layout to prevent the sidebar from bleeding](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/enhancements/layout-2-1.scss#L79). Doing some grid magic like we do with the [1-3 layout](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unp …
=> TCCP: Fix mobile horizontal scroll in card list

cfgov/cfgov/settings/base.py, cfgov/regulations3k/parser/patterns.py
This commit implements `OIDC_CREATE_USER = False`, preventing Django users from being created automatically just because they exist in the SSO provider.
See documentation for this setting here:
https://mozilla-django-oidc.readthedocs.io/en/stable/settings.html#OIDC_CREATE_USER
=> Disable automatic Django user creation with SSO

requirements/docs.txt
Followup to f680164542f0de13b04705f23249b9286880c83a.
=> Bump docs Jinja2 version from 3.1.5 to 3.1.6

cfgov/cfgov/tests/test_urls.py, cfgov/cfgov/urls.py
Currently if our 500 error page itself triggers another error (say, if the connection to the database is down, and the error page tries to access the DB to query flag state), we fall into an infinite recursion of error handling.
Ideally our 500 error page should be static, and not access the database or other resources that might trigger another error.
As a more immediate fix, we can change 500 errors to a simpler text response if we're not able to render the proper 500 page. Other errors (like 404s) should still be able to trigger the 500 page if their own error page (like the 404 page) fail to render for whatever reason.
See internal DEVPLAT-1465 for additional context.
=> Fix: Better handling of errors on 500 page

cfgov/alerts/github_alert.py
When cf.gov requests generate errors with excessively long tracebacks, we're not able to post them to GitHub issues.
GH doesn't seem to document an official limit but according to https://github.com/dead-claudia/github-limits?tab=readme-ov-file#issue-description the limit is 65536 characters. When we post excessively long issues to GH, we get a 422 Validation Failed error, which prevents us from recording them.
This commit truncates the stack trace so that we can at least record the error message.
See internal DEVPLAT-1465 for additional context.
=> Fix: Properly handle posting of long GitHub alerts

cfgov/unprocessed/js/modules/util/dollar-sign.js
The previous check wasn't working in Safari, whereas the new one works cross-browser.
- Open http://localhost:8000/consumer-tools/retirement/before-you-claim/ in Safari
- Fill out the form and notice the chart is broken
- Refresh, fill out the form again, notice it's fixed.
- Do the same in Chrome
=> Change .css check to work in safari

cfgov/v1/jinja2/v1/includes/article.html
Notifications appear as an option in Wagtail for blog pages, but they do not render in the template. This adds a block so that they render. 
- Enable notifications on articles.
1. Edit a blog page and add a notification in the header section, under general content. 
2. Preview the blog page and see that there is a notification visible on the page.
=> Enable notifications on articles

.dockerignore, Dockerfile
- When building the cfgov image, ignore the cfgov/apache directory, as we're using a separate cfgov-apache image to run Apache and so don't need to include these files.
- When building the cfgov image, ignore the cfgov/f directory, which developers may have locally if they've used local Wagtail file uploads.
- Correct various Docker build warnings about:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format
- JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals
=> Minor fixes to cf.gov Dockerfile

cfgov/diversity_inclusion/jinja2/diversity_inclusion/voluntary-assessment-form.html, cfgov/v1/jinja2/v1/includes/blocks/email-signup.html, test/unit_tests/mocks/emailSignupSnippet.js
- Remove `a-btn--secondary` class from privacy act statement links
1. Pull branch, `yarn build`, and run local server.
2. View http://localhost:8000/about-us/diversity-and-inclusion/voluntary-assessment-onboarding-form/ and http://localhost:8000/about-us/blog/13000-lessons-learned/ and see that the privacy act statement link is not gray by default.
| <img width="384" alt="Screenshot 2025-04-10 at 1 06 24 PM" src="https://github.com/user-attachments/assets/2181cb6c-7b9b-43d8-9750-7c4bf048148e" /> | <img width="387" alt="Screenshot 2025-04-10 at 1 06 16 PM" src="https://github.com/user-attachments/assets/3c58276b-f9ac-4826-a5da-0a4bf7f6f306" /> |
| <img width="426" alt="Screenshot 2025-04-10 at 1 09 28 PM" …
=> Remove `a-btn--secondary` class from privacy act statement links

cfgov/apache/Dockerfile
Currently the httpd:2.4-alpine image is vulnerable to [CVE-2025-27113](https://nvd.nist.gov/vuln/detail/CVE-2025-27113) due to its version of libxml2 (2.13.4-r3). A future release of the upstream httpd:2.4-alpine image should hopefully address this; until then we can manually patch libxml2 from the Alpine edge repository.
With this change the cfgov-apache image gets libxml2 2.13.7-r1, which addresses the vulnerability while still working properly with Apache.
=> Upgrade libxml2 in Apache image (CVE-2025-27113)

cfgov/unprocessed/css/organisms/full-width-text-group.scss
See https://github.local/Design-Development/Design-and-Content-Team/issues/623 for background.
The top and bottom margins applied to `full-width-text` elements are needed for when there are multiple, eg, `content` sections in one `full width text` organism. However, this clashed with the outer logic for removing `block` top margin via, eg, `block--flush-top`, which gets automatically added to the first block on a page.
This fix makes it so that the first `full-width-text` element in a group doesn't get top margin, thus preventing the margin stacking.
As an aside, this was unnoticeable in quite a few cases due to margin collapsing, but the initial spacing on `u-layout-grid__main` is provided by a combination of margin AND padding, which prevents the collapse and causes the unsightly extra …
=> Removes the top margin from the first full width text div

cfgov/v1/templates/v1/_list_page_metadata.html, cfgov/v1/views/reports.py
This PR adds the "Authors" field to the metadata report.
---
- "authors" field on report, both HTML view and export
1. localhost
2. /admin/reports/page-metadata/
3. View this page and also "Export as CSV" to confirm the new field
=> Add authors to metadata report

cfgov/v1/jinja2/v1/includes/organisms/footer.html
This PR adds a link to the CFPB public archive, via Archive-It, to the site-wide footer.
1. localhost
2. View any rendered page
=> Add public archive link to footer

cfgov/unprocessed/apps/rural-or-underserved-tool/js/address-utils.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/call-census.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/common.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/count.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/dom-tools.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/file-input.js, cfgov/unprocessed/apps/rural-or-underserved-tool/js/text-inputs.js
- ROUT: Simplify dom queries to use native querySelector calls directly, instead of through helper.
- Convert concatenated strings to template literals.
1. Visit http://localhost:8000/rural-or-underserved-tool/ and see that the tool works the same.
2. `getEl` calls should be `document.querySelector`
3. `getEls` calls should be `document.querySelectorAll`
=> ROUT: Simplify dom queries and strings

cfgov/housing_counselor/jinja2/housing_counselor/index.html
Convert alert to field level error (see https://cfpb.github.io/design-system/components/alerts#error-1)
- Convert FAHC error to field-level error.
1. Pull branch and build and visit http://localhost:8000/find-a-housing-counselor/ and screen sizes. Enter an incorrect zip enter an incorrect error dialog.
|<img width="1200" alt="Screenshot 2025-04-24 at 12 40 56 PM" src="https://github.com/user-attachments/assets/c10147fa-12ee-4cfc-8662-33017440c1d8" />|<img width="1229" alt="Screenshot 2025-04-24 at 12 25 10 PM" src="https://github.com/user-attachments/assets/03a4e330-cfaa-4296-af64-6d2515a20461" />|
The spacing between the icon and text for the alert is too close. This needs fixing in the DS directly.
=> Convert FAHC error to field-level error

.github/workflows/apache.yml, cfgov/apache/Dockerfile
Because we want the cf.gov Apache image to run as a non-root user, it can't bind to local port 80. Use 8080 instead.
=> Fix Apache image to expose port 8080, not 80

cfgov/v1/jinja2/v1/includes/macros/time.html, cfgov/v1/jinja2/v1/layouts/_last-modified.html, cfgov/v1/jinja2/v1/layouts/layout-1-3.html, cfgov/v1/jinja2/v1/layouts/layout-2-1.html, cfgov/v1/jinja2/v1/layouts/layout-full.html
- Add last modified datestamp to jinja templates.
1. Pull branch and visit a page and look for a date stamp and archive link in the content area footer.
- Not sure how to do the timezone yet!
=> Add last modified datestamp

cfgov/v1/jinja2/v1/browse-basic/index.html, cfgov/v1/jinja2/v1/browse-filterable/index.html, cfgov/v1/jinja2/v1/layouts/layout-1-3.html, cfgov/v1/jinja2/v1/newsroom/index.html
- Fix positioning of last modified date when there's a prefooter by elevating the prefooter block to the `layout-1-3.html` template.
- Add an overridable `prefooter_more_content` block for adding additional content to the prefooter.
1. Visit pages touched by this change and see that the last modified appears above the prefooter
http://localhost:8000/consumer-tools/educator-tools/library-resources/outreach-materials-to-use-outside-the-library/
http://localhost:8000/about-us/newsroom/?categories=press-release
=> Fix positioning of last modified date when there's a prefooter

cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/housing_counselor/views.py, cfgov/unprocessed/apps/find-a-housing-counselor/css/hud.scss, cfgov/v1/jinja2/v1/includes/snippets/no_js_notification.html
Supercedes https://github.com/cfpb/consumerfinance.gov/pull/8779/
- Update FAHC to use standard search input
- Add standard no-js notification.
- Add line break to two sentences in standard no-js notification.
1. Visit http://localhost:8000/find-a-housing-counselor/ and see that the functionality is unchanged.
---
---
=> Update FAHC to use standard search input

cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/unprocessed/css/skip-nav.scss, cfgov/v1/jinja2/v1/layouts/base.html, test/unit_tests/js/modules/footer-button-spec.js
The "super button" appearance was deprecated awhile back and isn't in the design system any longer. This PR downgrades the faux-super button skip nav buttons and converts them to regular primary buttons.
- Convert skip nav buttons to primary appearance, instead of super
1. Tab and shift+tab on any page to see the skip-nav button. 
2. Visit http://localhost:8000/find-a-housing-counselor/ and perform a zip code search and then tab beyond the search input to see the skip nav button next to the map.
|<img width="638" alt="Screenshot 2025-04-25 at 3 08 59 PM" src="https://github.com/user-attachments/assets/e81b3f09-4f57-4f4a-9c44-893746ac7f44" /> |
|
=> Convert skip nav buttons to primary appearance, instead of super

cfgov/v1/jinja2/v1/newsroom/index.html
- Newsroom: fix prefooter content alignment
1. Visit http://localhost:8000/about-us/newsroom/?categories=press-release and compare the prefooter to production across screen sizes.
|<img width="754" alt="Screenshot 2025-04-25 at 5 45 00 PM" src="https://github.com/user-attachments/assets/669d3c7a-7835-445d-96c5-2101dcf5bfd2" />|<img width="893" alt="Screenshot 2025-04-25 at 5 44 24 PM" src="https://github.com/user-attachments/assets/52b8dc31-cf7c-41c2-a441-9e2da7f30402" />|
|<img width="372" alt="Screenshot 2025-04-25 at 5 44 50 PM" src="https://github.com/user-attachments/assets/484e9508-c566-4455-b4d9-74113d89bd59" />|<img width="375" alt="Screenshot 2025-04-25 at 5 44 37 PM" src="https://github.com/user-attachments/assets/a5462191-479e-4599-8b47-f2 …
=> Newsroom: fix prefooter content alignment

cfgov/retirement_api/utils/ss_calculator.py
SSA has made some changes to their website recently (see also #8786). One of these changes is breaking `before you claim`. I unbroke it by including a normal browser UA string in our backend request.
It's likely that there are a bunch of efforts right now to scrape/crawl the SSA web presence, so this was most likely added as a speed bump.
hattip to @niqjohnson who noticed this
=> Add user-agent to ssa request

cfgov/housing_counselor/jinja2/housing_counselor/index.html, cfgov/housing_counselor/views.py, cfgov/unprocessed/apps/find-a-housing-counselor/css/hud.scss, cfgov/v1/jinja2/v1/includes/organisms/search-input.html
@natalia-fitzgerald requested the following:
- Move text to the bottom of the well (inside of the well)
- Place form level alert within the well under the search input
- Remove period from form level alert heading
- Update the helper text to "Enter a valid 5-digit ZIP code. "
- Confirm that the validation text reads: "You must enter a valid 5-digit ZIP code."
- Tweak to language under "Search by ZIP code"
Addtiionally,
- Add error state to search input template.
- Adjust max-width to our standard 41.875rem
1. Check http://localhost:8000/find-a-housing-counselor/ and see the changes per the screenshots below. The floating skip nav button appears on tabbing.
=> FAHC: additional refinement of UI

cfgov/privacy/forms.py, cfgov/privacy/tests/test_forms.py
I imagine this was missed because the fields are required on the frontend, that is, it can only be triggered via script/shell.
This silently swallows bad data without triggering an email, which seems like the best response to invalid triggering scripts.
=> Protect dict access in privacy/disclosure forms

cfgov/searchgov/jinja2/searchgov/index.html, cfgov/searchgov/jinja2/searchgov/recommended.html, cfgov/searchgov/jinja2/searchgov/result.html, cfgov/unprocessed/apps/searchgov/css/main.scss, esbuild/styles.js
Shows URLs in search result snippets.
---
- URLs to search result snippets
- Tweak best bet styles
- Since I added another few lines of CSS, I moved to an app-specific stylesheet to keep everything in one place
1. Perform a search for any term and note the URLs at the end of each result.
| <img width="803" alt="before" src="https://github.com/user-attachments/assets/3c342888-bd09-45ef-9576-012ab3058799" />  | <img width="802" alt="after" src="https://github.com/user-attachments/assets/22907dab-2bec-4be9-b01e-cba790c87823" /> |
=> Add URLs to search snippets

cfgov/tccp/tests/test_views.py, cfgov/tccp/views.py
Requests to a TCCP card detail page with an invalid DRF formatter currently result in an unhandled exception, for example
http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/vinton-county-national-bank-consumer-credit-card/?format=invalid
This commit fixes the current exception handling logic to properly handle this case, and also applies it to the list view, so that selecting an invalid formatter shows the regular 404 page, and not DRF's simpler one:
http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/?format=invalid
Unit tests have been added for these cases.
=> Fix unhandled error from invalid TCCP formatter

cfgov/unprocessed/apps/regulations3k/js/search.js, cfgov/unprocessed/apps/teachers-digital-platform/js/search.js
Fixes page search bug that was preventing iregs and tdp JS from selecting the correct `input`
(The code was assuming `input[name=q]` was globally unique, which is no longer true!)
=> Specifically target page search for iregs and tdp

requirements/docs.txt
I don't think there's enough active work on the docs to justify cleaning this up in another manner
=> Temporarily remove livereload from docs to satisfy snyk

cfgov/cfgov/settings/base.py, cfgov/cfgov/settings/local.py, cfgov/cfgov/settings/test.py
Currently settings.base defines [`ALLOWED_HOSTS`](https://docs.djangoproject.com/en/5.2/ref/settings/#allowed-hosts) as a wildcard `["*"]` which triggers a Veracode error. In practice we always override this setting in production via settings.production.
This change moves the wildcard into settings.test and settings.local to avoid the definition in our base settings. Production is unaffected by this change.
Addresses internal https://github.local/Design-Development/cfgov/issues/4612
=> Remove wildcard ALLOWED_HOSTS from settings.base

Dockerfile
This change modifies the cfgov Dockerfile to address several image vulnerabilities identified by Prisma:
1. Our version of setuptools is vulnerable to [CVE-2025-47273](https://nvd.nist.gov/vuln/detail/CVE-2025-47273). We can't upgrade setuptools until we upgrade Python past 3.8. As a workaround, we can remove setuptools from the built image.
2. The unprocessed frontend code is left behind in the built image, which can trigger false positive vulnerabilities in source libraries. We can remove that unprocessed code from the built image.
3. One of our Python libraries (ndg-httpsclient, required by edgegrid-python) includes a sample private SSH key, which is flagged as a vulnerability. We can remove this file as it's only used for testing of the library.
With these fixes, Prisma reports no …
=> Address vulnerabilites in cfgov Docker image

cfgov/tccp/tests/test_views.py, cfgov/tccp/views.py
HTTP POST requests are not supported to TCCP views, for example https://www.consumerfinance.gov/consumer-tools/credit-cards/explore-cards/cards/. These currently trigger an unhandled 500 error due to a logic bug in the custom TCCP exception handler.
This change fixes the logic so that rest_framework.MethodNotSupported errors are properly handled by DRF logic that converts them to standard Django 405 errors.
=> Fix: Handle unsupported POSTs to TCCP views

cfgov/searchgov/jinja2/searchgov/result.html, cfgov/unprocessed/apps/searchgov/css/main.scss
Makes the snippet plain text in search results. See github.local/Design-Development/External-Products/issues/653 for details.
---
- Only the title and URL of each search result are in the link now; the snippet is plain text
- Slight adjustments to margins to keep the focus state outlines looking nice
1. Do any global site search and make sure only the result title and URL are links
| ![before](https://github.com/user-attachments/assets/aafd0c8b-0aa9-4434-8012-8de77a2d1120) | ![after](https://github.com/user-attachments/assets/f88eb831-5a6c-476b-a4ad-bb6056d034e8) |
- Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: …
=> Remove snippet from search results link

cfgov/unprocessed/apps/tccp/css/main.scss
TCCP has a customization for field-level alerts that adds a large gap between the icon and text. I'm guessing this was maybe targeting an earlier version of the field-level alert. 
- Remove field-level alert customization
1. Go to http://localhost:8000/consumer-tools/credit-cards/explore-cards/ and try submitting the form without selecting an item in the form. There should be a field-level alert without a wide gap.
| <img width="427" alt="Screenshot 2025-06-03 at 4 43 20 PM" src="https://github.com/user-attachments/assets/943f38dc-54ea-44b9-a0c8-18bc52836250" /> | <img width="417" alt="Screenshot 2025-06-03 at 4 47 34 PM" src="https://github.com/user-attachments/assets/57f28f74-3b02-457f-add3-90503753640f" /> |
=> TCCP: Remove field-level alert customization

cfgov/prepaid_agreements/jinja2/prepaid_agreements/index.html
Fixes 
- Fix heading level order
1. The heading "search within" should be visually unchanged between http://localhost:8000/data-research/prepaid-accounts/search-agreements/ and production.
=> Prepaid: Fix heading level order

cfgov/teachers_digital_platform/models/pages.py
No TDP activity page has a meta description. This is an SEO/search issue which we can rectify by repurposing the pages' `summary`s.
- Pull
- Load up an [activity page](http://localhost:8000/consumer-tools/educator-tools/youth-financial-education/teach/activities/understanding-jobs-teens-taxes/)
- Look in the source or elements panel for a friendly meta description tag (instead of a blank one).
=> Set tdp activity page meta descriptions to their modified summary

cfgov/searchgov/jinja2/searchgov/index.html, cfgov/searchgov/jinja2/searchgov/recommended.html, cfgov/searchgov/jinja2/searchgov/result.html
This is generally useful when testing and also better for dev servers and beta. This will also allow us to remove our beta and beta_es search.gov sites and associated logic + vars.
- Pull
- Visit http://localhost:8000/search/?q=mortgage
- Note both the recommended results and the normal results have both actual urls and url labels updated to reflect the local protocol+domain+port (in this case http://localhost:8000).
=> Update searchgov template to render results local to the deployment

docker/centos7/Dockerfile
Testing CCDB API code in the cfgov context requires that we install a branch of the ccdb5-api repo via cfgov's requirements/libraries.txt file.
The libraries.txt file normally imports wheel artifacts that don't require git. But for testing, we use a "git+https" protocol and ".git" suffix to install a branch, and that process invokes git.
It appears that when we moved to the centos7 container for building artifacts, we lost the ability to add packages via this "git+https" method.
Attempts to build a cfgov artifact for deploying ccdb5-api code to a dev server now fail on this error:
```bash
ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```
build reference: …
=> Add git to the centos7 artifact-builder container

.github/workflows/build-docker.yml
We don't currently have a GitHub Action that makes sure that our Docker images (`cfgov` and `cfgov-apache`) build successfully after all PRs. We recently had a couple of PRs that broke the frontend build in the Docker context.
This PR adds a new GitHub Action that verifies that those images can build.
=> Add GitHub Action to validate Docker image build

cfgov/cfgov/settings/base.py, cfgov/v1/jinja2/v1/layouts/base.html, docs/feature-flags.md
Google Optimize settings were added in https://github.com/cfpb/consumerfinance.gov/pull/7444, however, since that time Google Optimize has been sunset https://support.google.com/analytics/answer/12979939?hl=en
This PR removes the references to `optimize.google.com` and `googleoptimize.com`. Additionally, it removes the `AB_TESTING` flag.
- Remove google optimize legacy code cruft.
- Remove `AB_TESTING` optimize flag.
I left the `fonts.gstatic.com` settings, since they may be used by google analytics too (not sure if they actually are).
Follow the Feature Flag hygiene instructions after this is merged https://cfpb.github.io/consumerfinance.gov/feature-flags/#hygiene
=> Remove google optimize legacy code cruft and AB_TESTING flag

cfgov/cfgov/settings/base.py
Update the allowed Mouseflow URL in `CSP_CONNECT_SRC`; it now matches other allowed Mouseflow URLs. See github.local/Design-Development/External-Products/issues/685 for details.
---
- Allowed Mouseflow URLs in `CSP_CONNECT_SRC`
I'm not sure there's a way to test this locally. As noted in the issue, the URL `us01.rec.mouseflow.com` needs to be allowed in `CSP_CONNECT_SRC`.
- We'll need to do a delete-purge in Akamai once this change is deployed for all pages to pick up the change.
=> Update Mouseflow CSP

cfgov/core/tests/test_utils.py, cfgov/core/utils.py
Commit bf5a764d744573b32f128124ec80f222d3f4040f (#8848) introduced a bug in our link parsing logic that would raise an unhandled exception for certain links. Links with text containing certain invalid characters would trigger a ValueError in urlparse, which cause a 500 error on pages like:
https://www.consumerfinance.gov/about-us/blog/guide-covid-19-economic-stimulus-checks-zh/
This commit fixes that bug and adds appropriate unit tests.
=> Fix unhandled link parsing exception

mkdocs.yml
Commit 6f18cb6cb69e34739208a358d6b45725b0b9d466 removed a documentation page related to Kubernetes, but did not remove a reference to it from the docs table of contents. This causes documentation builds to fail.
See for example failing GitHub Action here:
https://github.com/cfpb/consumerfinance.gov/actions/runs/16422811362/job/46405557057
=> Docs: Remove reference to missing k8s page

cfgov/cfgov/settings/base.py
Changes password min-length to 14, up from 12.
This will not immediately affect existing accounts unless we mass invalidate them.
=> Update password min-length to 14 chars

cfgov/apache/Dockerfile
Pinning so that we don't run into any funny business like the .64 shenanigans
`apk info libxml2` returns `libxml2-2.13.8-r0` in .65, so this also removes the code upgrading libxml2 since this doesn't have the referenced CVE.
=> Pin httpd to version 2.4.65 and remove the (now unnecessary) libxml hacky upgrade

.github/workflows/frontend.yml
We're being bit by: https://github.com/nodejs/node/issues/59480
When this is fixed/when there's an upgrade path we should revert this.
=> Pin node to v24.5.0 to get around jest-related bug in v24.6.0

cfgov/searchgov/jinja2/searchgov/recommended.html, cfgov/searchgov/jinja2/searchgov/result.html, cfgov/searchgov/tests/test_views.py, cfgov/searchgov/views.py, package.json, test/unit_tests/apps/financial-well-being/js/fwb-questions-spec.js, test/unit_tests/js/organisms/FilterableListControls-spec.js, test/unit_tests/js/organisms/MegaMenuMobile-spec.js
Now that search.gov has picked up our encoded meta descriptions from https://github.com/cfpb/consumerfinance.gov/pull/8865, we can use them in search.
- Pull
- Search for a term, results should populate as expected. Best bets/recommended data should still exist.
=> Use encoded meta descriptions via search.gov faceted search

requirements/libraries.txt
See release notes:
https://github.com/cfpb/ccdb5-api/releases/tag/1.7.3
https://github.com/cfpb/ccdb5-api/releases/tag/1.7.4
=> Bump ccdb5-api from version 1.7.2 to 1.7.4

cfgov/jinja2/owning-a-home/explore-rates/index.html, cfgov/unprocessed/apps/owning-a-home/css/explore-rates.scss
This PR adds a banner notification regarding the Explore Interest Rates tool data.
- Add notification about data staleness
- Change notification lower on the page from `warning` to `information`
1. Pull this PR down, set it up, then check out the explore interest rates tool.
2. Look for the banner/notification (see screenshot below)
=> Add and update Explore Interest Rates notifications

Dockerfile
The gevent Python package used for the cfgov Docker image includes several test key files. These aren't used at runtime but do trip our image vulnerability scanning software. They can be removed as part of the build process, as we already do for a similar key in the ndg-httpsclient Python package.
=> Remove gevent test key files from cfgov Dockerfile
